### ISSUE TITLE
Charts are rendering misleading values. Missing peak values

### ISSUE THREAD

**Issue by kromit** [netdata/netdata#9373] opened 2020-06-18 12:12 UTC
##### Bug report summary

Charts are rendering different values depending on zoom level. It looks like some time series are dropped.

![normal chart with zoom](https://i.imgur.com/cxESxyN.png)

![misleading chart with zoom](https://i.imgur.com/cqg9Otw.png)

Look at time stamps, percentage and value. The same peak around 13:30 is selected. It looks like the whole chart was lowered.
It creates entirely different picture of the system and is highly misleading.

##### OS / Environment
```
Firefox Browser
```

##### Netdata version
v1.22.1

##### Component Name
Web app, Charts

##### Steps To Reproduce

1. Look at some chart in the web app
2. Lower zoom level in the chart multiple times
3. Different chart values are rendered

##### Expected behavior

Zoom should never drop any time series, because it creates a misleading chart.
If the chart is not able to render all time series the `max` value in the given time period should be used for rendering and value.

**Comment by thiagoftsm** [comment] 2020-06-22 22:57
Hi @kromit ,

Firstly I apologize the delay to answer you.
I tested now on Mozilla Firefox `68.9.0esr` and Google Chrome `83.0.4103.106`. I observed that the problem reported when the lower zoom is applied is happening with the `React` dashboard and also with the `classic` dashboard, no less important this is also affecting the cloud.
@jacekkolasa , @VLegakis, @Azein  and @manos-saratsis  this is affecting us everywhere. 

Best regards!

**Comment by ilyam8** [comment] 2020-06-22 22:59
I guess it is expected (i dont say it is correct), it is interpolation.

**Comment by thiagoftsm** [comment] 2020-06-22 23:04
> I guess it is expected (i dont say it is correct), it is interpolation.

I could do a peak of `0.8` to become `0.4`, I am not sure if this is what we want.

**Comment by manos-saratsis** [comment] 2020-06-23 07:51
@kromit thanks for reporting it.

@dim08 this is high prio.

**Comment by jacekkolasa** [comment] 2020-06-23 08:44
I agree with @ilyam8 it's an interpolation problem. We can change the grouping method, but it won't work in all cases and current "average" setting is a compromise. Maybe we should have a setting for this? @dim08

**Comment by dim08** [comment] 2020-06-24 07:25
@jacekkolasa will follow up with you

**Comment by dim08** [comment] 2020-06-29 11:02
Hi @kromit,

Thank you very much for your feedback. I followed up with one of our FE developers, it seems this is not a bug, it works like that by design. I will investigate further if we can change this feature.

**Comment by kromit** [comment] 2020-06-29 12:23
Hi @dim08, 

I do understand that this is how the FE is designed, so it is not qualified as a bug, but sometimes the initial design is not optimal.
I believe this is the case here. Saying  is a feature is like saying "It was intended to show wrong values when zoomed out".

I mean if the system runs into 100% CPU spikes every 10 min and if zoomed out it looks like the system is always on 10% CPU all the time without spikes, the provided information albeit mathematically correct, is wrong from the user perspective. It is out of the box like this and is really hard so detect especially if you do not expect such behavior from a piece of software created do exactly this one thing right: provide correct status information. 

Anyways, I think the grouping should per default be `max` for positive and `min` for negative. I see how `average` is a compromise here because you do not need to differentiate between negative and positive, but it is not the proper way to handle it.

Cheers. :wink:

**Comment by dim08** [comment] 2020-06-30 14:14
Hi @kromit, 

You are right, this is confusing. I am currently working with our engineers to figure out how to change it. 

Cheers

**Comment by ilyam8** [comment] 2021-08-04 12:29
Closing this feature request. We will re-evaluate the request internally.

**Closed by ilyam8** 2021-08-04 12:29 UTC
Labels: feature request, priority/high
