### ISSUE TITLE
btrfs: false alarm for disk space

### ISSUE THREAD

**Issue by RubenKelevra** [netdata/netdata#9264] opened 2020-06-03 17:00 UTC
##### Bug report summary
I got a critical alarm on netdata today, regarding a btrfs volume - which seems to be false.

`df` shows the following:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        71G   46G   23G  68% /
```

`btrfs` shows the following:

```
# btrfs fi df  /
Data, single: total=65.52GiB, used=43.44GiB
System, single: total=32.00MiB, used=16.00KiB
Metadata, single: total=4.94GiB, used=1.44GiB
GlobalReserve, single: total=212.06MiB, used=48.00KiB
```

The alarm:

![Screenshot_20200603_185356](https://user-images.githubusercontent.com/614929/83665707-13a95f80-a5cc-11ea-8437-09fad685f75f.png)

##### OS / Environment

```
/etc/lsb-release:LSB_VERSION=1.4
/etc/lsb-release:DISTRIB_ID=Arch
/etc/lsb-release:DISTRIB_RELEASE=rolling
/etc/lsb-release:DISTRIB_DESCRIPTION="Arch Linux"
/etc/os-release:NAME="Arch Linux"
/etc/os-release:PRETTY_NAME="Arch Linux"
/etc/os-release:ID=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:HOME_URL="https://www.archlinux.org/"
/etc/os-release:DOCUMENTATION_URL="https://wiki.archlinux.org/"
/etc/os-release:SUPPORT_URL="https://bbs.archlinux.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.archlinux.org/"
/etc/os-release:LOGO=archlinux
```

##### Netdata version
netdata v1.22.1-184-nightly

##### Component Name
health - btrfs

##### Expected behavior
Shows only a warning if there's no unallocated disk space and either data, metadata or system chunks runs out of spaces.

**Comment by ilyam8** [comment] 2020-06-03 19:16
Hi @RubenKelevra 

The alarm is

https://github.com/netdata/netdata/blob/380a3a7f56f1f644172921acc4019be26f7d6423/health/health.d/btrfs.conf#L2-L14

Are you willing to fix the alarm? A PR would be nice 😄

**Comment by Ferroin** [comment] 2020-06-23 16:59
The alarm is not wrong here.

BTRFS uses a two-stage allocator, first allocating large chunks of space (usually 1GB at a time) which it then allocates individual filesystem blocks within, with each chunk being used for only one type of filesystem block (data or metadata).

`df` (and our regular disk space charts) only report usage at the second (block-level) stage, while this alarm is looking at the first (chunk-level) stage. Being out of space at the first stage can lead to a BTRFS volume reporting as being out of space when there actually appears to be plenty of free space, which is why we have this alarm.

Based on the output you posted from `btrfs filesystem df` and `df`, the volume in question is out of space at that first allocation stage, though it may not actually return any errors for quite some time (you still have a lot of free space in the second stage for both data and metadata). You can remedy the out-of-space condition in the first-stage by running `btrfs balance start -dusage=50 -musage=50` on the filesystem in question to run a compaction/defragmentation pass on that first stage.

**Comment by thiagoftsm** [comment] 2020-06-23 18:16
Thank you for your comments @Ferroin .
I executed some tests using the following commands:

```
dd if=/dev/zero of=diskimage.img bs=1M count=100
losetup loop1 diskimage.img 
mkfs.btrfs -L"test" -f /dev/loop1 
mount -U 73869de0-dfe7-4c45-8a00-c972f98ee2ef ./test
```

After this I got the Netdata variables used to calculate the alarm using the API: 

```
curl -k -o free.txt "https://localhost:19999/api/v1/alarm_variables?chart=btrfs.disk_test"
```

Finally I copied a file bigger than my volume:

```
cp /home/thiago/download/kernel_source/4.9/linux-4.9.226.tar.xz test/
``` 

And again I requested data:

```
curl -k -o fill.txt "https://localhost:19999/api/v1/alarm_variables?chart=btrfs.disk_test"
``` 

As @Ferroin said, the alarm worked as expected on both situation, and the command `df` was never given a complete information about the disk.

Best regards!

**Comment by amoss** [comment] 2020-08-07 14:38
I'm labelling this as wontfix because based on the discussion above it is not a bug in the agent. Please re-open if there is new information.

**Closed by amoss** 2020-08-07 14:38 UTC
Labels: bug, wontfix
