### ISSUE TITLE
Link from Master node to Replica nodes not working with v1.22.0

### ISSUE THREAD

**Issue by svrnwnsch** [netdata/netdata#8980] opened 2020-05-12 07:23 UTC
##### Bug report summary

After upgrade the our mater server which runs inside docker to version 1.22.0 the linking to the slave servers no longer works correctly with the new switcher. The master is accessible on the url: `https://monitoring.example.com/`
 The new links look like: 
`https://monitoring.example.com/host/node1` which then redirects to `http://netdata:19999/host/node1/` but the correct working link to access the node1 netdata is: `https://monitoring.example.com/host/node1/` which works if inputted manually in the browser.

Additional Notes: The netdata master server is running behind a caddy server (v1). After updating the current used netdata.conf needed to be updated as I saw the `Access to file is not permitted: /usr/share/netdata/web//index.html` error which I could fix by following this instruciton: https://github.com/netdata/netdata/issues/8343#issuecomment-596210901 and setting:
```
web files owner = root
web files group = root
```
which was before unmodified by myself.

##### OS / Environment

```
docker container
```

##### Netdata version

Netdata v1.22.0 via docker on master, and netdata v1.22.0 via stable release channel on slaves.
 

##### Component Name

dashboard, cloud,

##### Steps To Reproduce

1. Run Master node behind caddy with working configuration from v 1.21.1 with slave nodes

##### Expected behavior

Set correct working link to host.

**Comment by cakrit** [comment] 2020-05-12 14:37
We've broken the -W set command that's used in packaging/docker/run.sh to set the web owner and group. We're doing a patch.

**Comment by cakrit** [comment] 2020-05-12 14:39
Duplicate of #8969

**Comment by svrnwnsch** [comment] 2020-05-13 08:41
So I updated to v1.22.1 but this bug of incorrect links still persists. I even reverted the netdata web config to the old state, which now works without any permissions problems. But the problems I mentioned above still persists.

**Comment by ilyam8** [comment] 2020-05-13 10:42
it wasnt duplicate, the problem in `Additional Notes:` is not the OP problem

**Comment by ilyam8** [comment] 2020-05-13 10:43
@jacekkolasa i think you can help here, please

**Comment by jacekkolasa** [comment] 2020-05-13 11:25
Sure, thanks @ilyam8 for asking. @svrnwnsch could you please explain what you mean by "redirect"? If you right+click and do "Copy link address" (in Chrome), what do you get?

**Comment by svrnwnsch** [comment] 2020-05-13 12:50
The url changes as described above (tested on firefox) so you enter `https://monitoring.example.com/host/node1` and then the url is `http://netdata:19999/host/node1/` which cannot work as the port is not accessible as we use caddy with basic auth to block access.

Manually appending the `/` to fix url to `https://monitoring.example.com/host/node1/` works as expected.

**Comment by jacekkolasa** [comment] 2020-05-13 17:12
@svrnwnsch indeed, in the new dashboard version we don't append `/` at the end, that is a bug, apologies for that! I'll add it to the next nightly and stable builds. All servers which we used to test it had a redirect in this scenario, that's why we didn't catch it... Is it possible for you to tweak your caddy config until you'll have the fix?

**Comment by svrnwnsch** [comment] 2020-05-14 08:28
I am currently replacing the link manually in my browser which is acceptable as the alerting via webhook still works and I do not need to do it to often. Nevertheless I would be happy with a quick fix :)

**Comment by svrnwnsch** [comment] 2020-07-01 07:22
I updated all my servers to version 1.23.0 and this is still not working.

**Comment by cakrit** [comment] 2020-07-07 14:31
@jacekkolasa it's the same thing we were talking about yesterday, can you please provide an update when we have a proper fix?

**Comment by jacekkolasa** [comment] 2020-08-24 10:23
closing, 2 fixes (one with trailing slash, second with [https redirect](https://github.com/netdata/netdata/issues/9154)) are in nightlies, and will be included into next stable release

Thanks for help @svrnwnsch

**Closed by jacekkolasa** 2020-08-24 10:23 UTC
Labels: area/web, bug, priority/medium
