### ISSUE TITLE
Netdata takes too long to give the metrics to the Prometheus server

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8251] opened 2020-03-02 07:03 UTC
##### Bug report summary
We have a Prometheus server that collects `average` and `as-collected` metrics every 90 seconds with the timeout of 75 seconds from our master netdata server which is monitoring 250 slaves. 
The problem is most of the time the scrape duration from the master netdata is bellow 20 seconds but sometimes the scrape duration reaches the timeout (75s) hence we lose the metrics on our grafana dashboards.
I tried to download the metrics manually via `wget` in the Prometheus server and here is the results:
![image](https://user-images.githubusercontent.com/7656049/75652465-5b88b580-5c70-11ea-8a42-5bfca95ec21c.png)
As you can see, the metrics are downloaded in 1.5s but it took about 50 seconds to establish the connection to the master netdata.
And here is the network graph in the central netdata (the only process which may cause the network output is either we opening the web UI and the Prometheus server reading the metrics and the 777 Mb/s out peak is when I run the `wget` command):
![image](https://user-images.githubusercontent.com/7656049/75652545-9854ac80-5c70-11ea-80bb-4e88191db183.png)
 
##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.1 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.1 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 netdata v1.20.0

**Comment by thiagoftsm** [comment] 2020-03-02 12:36
@mfundul I talked with @vlvkobal about this problem, is there possibility of the database to be slow here?
@yasharne I believe I already asked you about this, but I do not remember your database configuration, please, can you give us the values that you are using for `page cache size` and `dbengine disk space`?

**Comment by yasharne** [comment] 2020-03-02 12:38
Hi @thiagoftsm We use 128Mb as `page cache size` and 2048 Gb as `dbengine disk space`

**Comment by mfundul** [comment] 2020-03-02 14:33
> 
> 
> @mfundul I talked with @vlvkobal about this problem, is there possibility of the database to be slow here?
> @yasharne I believe I already asked you about this, but I do not remember your database configuration, please, can you give us the values that you are using for `page cache size` and `dbengine disk space`?

I'm not sure if taking too long to connect is related to the database. In any case, setting `memory mode = ram` at the server side  temporarily could show if there is a big difference or not. For this configuration change to apply you would need to restart the netdata service. Existing data of `dbengine` are not lost and you can switch back to it after this experiment.

**Comment by yasharne** [comment] 2020-03-02 15:49
@mfundul Apparently setting `memory mode` to `ram` improves the performance as I set  the scrape timeout to 45s in the Prometheus (setting scrape timeout to 30 still caused `context deadline excited` error) and we haven't seen any problem in the last hour in our Grafana server, but now we don't have the history of the metrics for more than 30 minutes

**Comment by mfundul** [comment] 2020-03-02 15:58
This looks like a single-threaded bottleneck at first glance. It would make sense if `ram` consumes 50% of the CPU of `dbengine` during query processing, and that would also explain why `dbengine` times out at 75 sec and `ram` at 30 sec.

@yasharne how does CPU utilization look during the scraping? If I'm correct then one of the netdata threads should hit 100% of a single CPU in your system.

**Comment by yasharne** [comment] 2020-03-02 16:08
@mfundul Yes, CPU 1 hit 100%  during the scrape
![image](https://user-images.githubusercontent.com/7656049/75694066-2eaebf80-5cbd-11ea-8afb-8705ad0a3559.png)

**Comment by yasharne** [comment] 2020-03-02 16:19
@mfundul We got to the problem again with `memory mode` to `ram`:
![image](https://user-images.githubusercontent.com/7656049/75694878-77b34380-5cbe-11ea-8cd5-aacbd8d92ff6.png)
`wget`:
![image](https://user-images.githubusercontent.com/7656049/75695152-e2647f00-5cbe-11ea-9db4-e2aef37b38f4.png)

**Comment by vlvkobal** [comment] 2020-03-02 16:24
Please show your `apps.cpu` chart for `netdata` dimension (Applications -> cpu -> netdata).

**Comment by yasharne** [comment] 2020-03-02 16:34
@vlvkobal 
![image](https://user-images.githubusercontent.com/7656049/75696582-0cb73c00-5cc1-11ea-8ab5-0724776d7a32.png)

**Comment by vlvkobal** [comment] 2020-03-02 16:42
Wow, Netdata uses almost four cores.

Was it at 20:01:40 - 20:02:00 when you experienced the issue? Does the issue correlate to CPU usage?

@mfundul, @thiagoftsm, I don't see how the Prometheus API response can be delayed sporadically. It should be consistent in the time it takes to query the database. Might it be an OS slowdown?

**Comment by yasharne** [comment] 2020-03-02 16:48
@vlvkobal  No It was earlier (around 19:45) But I don't have the history anymore to check it

**Comment by vlvkobal** [comment] 2020-03-02 16:50
I suppose that when streaming and database querying happens at the same time, Netdata is struggling. How can we check it?

**Comment by vlvkobal** [comment] 2020-03-02 16:55
@yasharne, could you make a Netdata snapshot when you just have experienced the issue? Please send it to vlad@netdata.cloud.

**Comment by yasharne** [comment] 2020-03-02 17:07
@vlvkobal 

> I suppose that when streaming and database querying happens at the same time, Netdata is struggling. How can we check it?

@vlvkobal Most of the slaves send the metrics every 5 seconds but some of them send it every 2 seconds and some send every second

**Comment by mfundul** [comment] 2020-03-02 17:19
> 
> 
> Wow, Netdata uses almost four cores.
> 
> Was it at 20:01:40 - 20:02:00 when you experienced the issue? Does the issue correlate to CPU usage?
> 
> @mfundul, @thiagoftsm, I don't see how the Prometheus API response can be delayed sporadically. It should be consistent in the time it takes to query the database. Might it be an OS slowdown?

Monitoring 250 slaves could already be too much overhead depending on the server's capabilities. The API response might be the cherry on top.

**Comment by thiagoftsm** [comment] 2020-03-02 22:04
I agree with @mfundul  and probably this has relationship with #8218 .

**Comment by yasharne** [comment] 2020-03-03 15:30
@vlvkobal I sent you the email
@mfundul our server has 128Gb of ram and 8cores of CPU

**Comment by mfundul** [comment] 2020-03-03 15:45
> 
> 
> @vlvkobal I sent you the email
> @mfundul our server has 128Gb of ram and 8cores of CPU

The CPU is what I'm concerned about, is it 8 real cores or is it 4 cores with 8 hardware threads? Maybe you can share the `lscpu` output?

**Comment by yasharne** [comment] 2020-03-03 16:06
Sure @mfundul 
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           8
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
Stepping:            1
CPU MHz:             2197.472
BogoMIPS:            4394.94
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear
```

**Comment by mfundul** [comment] 2020-03-03 18:27
> 
> 
> Sure @mfundul
> 
> ```
> Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> CPU(s):              8
> On-line CPU(s) list: 0-7
> Thread(s) per core:  1
> Core(s) per socket:  1
> Socket(s):           8
> NUMA node(s):        1
> Vendor ID:           GenuineIntel
> CPU family:          6
> Model:               79
> Model name:          Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
> Stepping:            1
> CPU MHz:             2197.472
> BogoMIPS:            4394.94
> Virtualization:      VT-x
> Hypervisor vendor:   KVM
> Virtualization type: full
> L1d cache:           32K
> L1i cache:           32K
> L2 cache:            4096K
> NUMA node0 CPU(s):   0-7
> Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear
> ```

Ok, so this is 8 virtual cores at relatively low clock on different NUMA domains. This also means that a 60 second query would take about half the time in a modern desktop architecture than a virtualized Haswell core at 2.2GHz. Maybe we should look into parallelizing this kind of queries. However, we must also see how much we can improve single-threaded performance.

**Comment by yasharne** [comment] 2020-03-04 05:41
@mfundul Is there any solution to fix this temporarily? We have tried to disable unnecessary charts to reduce the size of the metrics but it wasn't enough and people call us from Call Center or DevOps asking what's wrong with the dashboards and are we down?

**Comment by mfundul** [comment] 2020-03-04 05:47
> 
> 
> @mfundul Is there any solution to fix this temporarily? We have tried to disable unnecessary charts to reduce the size of the metrics but it wasn't enough and people call us from Call Center or DevOps asking what's wrong with the dashboards and are we down?

Since changing `memory mode` does not solve the problem I am not aware of any workaround currently. Is this the first time you see this problem in this set-up? Do you think it's related to version 1.20 somehow?

**Comment by ilyam8** [comment] 2020-03-04 05:54
How about to split the load and have 2 masters? 125 slaves per master.

I dont think we have tested such big load, we need to consider to do it @mfundul

**Comment by mfundul** [comment] 2020-03-04 06:00
> 
> 
> How about to split the load and have 2 masters? 125 slaves per master.
> 
> I dont think we have tested such big load, we need to consider to do it @mfundul

Agreed. I'm just wondering if this is a regression of some sort.

Are you suggesting a set-up of:
```
         master
        /      \
      /          \
master/slave   master/slave
|||||||||||||||||||||||||||
slave slave slave ... slave
```

**Comment by yasharne** [comment] 2020-03-04 06:03
@mfundul We already had problem #8218 on version 1.19 but upgrading to version 1.20 didn't fix it until I took 25 slaves out of it and added them again after a while, but this can happen again after a while.
@ilyam8 We haven't added all the machines yet, so we still have more than  150 machines to add

**Comment by ilyam8** [comment] 2020-03-04 06:05
> Are you suggesting a set-up of:

No, just 2 masters. Prometheus will scrape data from both of them.

**Comment by ilyam8** [comment] 2020-03-04 06:09
> We haven't added all the machines yet, so we still have more than 150 machines to add

Perhaps there is a limit at which Netdata is not stable and different weired bugs can appear.

As for now it seems you need to split the load to avoid

> people call us from Call Center or DevOps asking what's wrong with the dashboards


And we need to setup lab enviroment and try to understand what is wrong and try to fix it.

**Comment by yasharne** [comment] 2020-03-04 17:47
@ilyam8 @mfundul So I made another master and migrated 30 hosts (the ones with the most metrics) to the new master (the metric size on the first master reduced from 160Mb to 109Mb), although the situation got far better than what we had, we still see some drops:
![image](https://user-images.githubusercontent.com/7656049/75907182-22616880-5e5d-11ea-8238-e68b700b2ddb.png)
As you can see, at 18:43 problem got solved but we still see some problem after

**Comment by mfundul** [comment] 2020-03-12 15:24
@yasharne can you test #8375 for your master netdata server? It should be much better for #8251 and especially #8218

**Comment by mfundul** [comment] 2020-03-16 11:41
#8375 has now been merged to master.

**Comment by mfundul** [comment] 2020-03-25 15:27
The original issue has been mitigated by splitting the load across 2 master servers. The remaining optimization work relates to the netdata health subsystem and we'll keep track on it in #8368

**Closed by mfundul** 2020-03-25 15:27 UTC
Labels: bug, priority/high

**Comment by yasharne** [comment] 2020-05-06 05:27
@mfundul I still face this problem on version `1.21.1`, it is not as severe as before, but It happens sometimes, in the Prometheus, it usually takes less than 12 seconds to read the metrics but some times it exceeds the 75s timeout. In the meantime, system CPU usage goes a little high:
![image](https://user-images.githubusercontent.com/7656049/81140633-57825800-8f7f-11ea-8ea5-7d243e33f55a.png)
and we start getting dbengine errors like this:
![image](https://user-images.githubusercontent.com/7656049/81140702-9b755d00-8f7f-11ea-8eea-4203f0ba44da.png)
(I'm not sure if these two problems are correlated)
Currently, we allow each slave to use 128mb of ram and 1Gb of the disk but we are planning to reduce it to 512mb since we persist the metrics on the Prometheus and only need dbengine for the alerts

**Comment by mfundul** [comment] 2020-05-06 12:58
This is potentially related to https://github.com/netdata/netdata/issues/8368 and https://github.com/netdata/netdata/issues/8384.

**Comment by yasharne** [comment] 2020-05-06 20:11
@mfundul The thing is, we haven't added any nodes to this master in the past three weeks and it was monitoring only 200 nodes (when I created this issue it was monitoring 250 nodes) but not we are encountering the same problem:
![image](https://user-images.githubusercontent.com/7656049/81220168-22651c80-8ff6-11ea-9c8c-e1ecb7cffd0d.png)
The weird thing is I moved 35 nodes from this master to the other one with 70 nodes and I got the same problem on master number 2:
 
![image](https://user-images.githubusercontent.com/7656049/81220554-b800ac00-8ff6-11ea-834c-dc58ac588852.png)
So now I think each master cannot handle more than 150 slaves approximately. although we have plenty of ram (more than half) and CPU available

**Comment by yasharne** [comment] 2020-05-07 05:57
After losing netdata web again for about an hour, I stopped the master netdata and deleted all of the contents of `/opt/netdata/var/lib/netdata/` and `/opt/netdata/var/cache/netdata/` and started the service again and everything seems fine for now
