### ISSUE TITLE
Repeated dbengine global flushing errors

### ISSUE THREAD

**Issue by kmlucy** [netdata/netdata#7468] opened 2019-12-07 14:21 UTC
##### Bug report summary
No matter how I setup dbengine, I still get `10min dbengine global flushing errors` alerts during periods of moderate to high server usage. I have tried putting the dbengine files on an HDD, SSD, and even a RAMDISK without being able to solve the issue. I have increased the page cache size repeatedly without effect. 

##### OS / Environment
Docker

##### Netdata Version
`netdata v1.19.0-53-g7953472f`

##### Component Name
dbengine

##### Steps To Reproduce
Current settings:
```
[global]
    page cache size = 128
    dbengine disk space = 512
````
##### Expected behavior
No errors. Netdata should be able to handle moderate server utilization without being unable to write to disk.

**Comment by mfundul** [comment] 2019-12-07 14:41
How many metrics is your server actually gathering? Is it over 16K metrics?

This is possibly a false positive in your case. It should be resolved by an improvement to the code that is not ready just yet. I should just commit a hotfix for this case and let you try it and see if the warning is resolved.

**Comment by mfundul** [comment] 2019-12-07 14:50
@kmlucy can you test #7469 please?

**Comment by kmlucy** [comment] 2019-12-07 15:25
I don't actually know how to check how many metrics I am gathering, and I'm running inside Docker, so I'm not sure if there is a good way to test the branch. I'm happy to test if it's possible, I just don't know how.

**Comment by mfundul** [comment] 2019-12-07 15:50
You can look at the rightmost column in the netdata dashboard, below System Overview. If you go at the bottom of this column you should see something like:
```
netdata on london3.my-netdata.io, 
collects every second 1,907 metrics, 
presented as 317 charts and monitored by 91 alarms
```

**Comment by mfundul** [comment] 2019-12-07 20:27
@kmlucy after you update with the latest code, if you ever see this problem again feel free to reopen this issue.

**Comment by kmlucy** [comment] 2019-12-07 22:17
@mfundul Sorry, been out all day. I have 6732 metrics, so nowhere near 16k. I'll update to the newest version and let you know if the issue crops back up. Thanks for the fix!

**Comment by kmlucy** [comment] 2020-01-12 17:20
This has started cropping up again. It doesn't seem to coincide with spikes in disk usage, cpu usage, etc., and the times aren't consistent enough to be when various cron jobs run, but it is always overnight, so I'm assuming it is do the increased usage from backup and maintenance jobs.

**Comment by mfundul** [comment] 2020-01-13 13:15
What is your configuration this time?
netdata version, current configuration, HDD/SSD/RAM, number of metrics?

**Comment by kmlucy** [comment] 2020-01-14 03:21
My configuration is the same as before, SSD, 6812 metrics, and netdata version: v1.19.0-267-g7597c80d.

**Comment by mfundul** [comment] 2020-01-14 17:22
@kmlucy can you export a snapshot from the netdata dashboard? You can zoom out so that a meaningful duration is visible in your dashboard that includes the issue. Then click on the arrow in the top-right corner of the dashboard and export a snapshot. You should select "1 second per point" as your resolution.

You can send it to me privately at markos@netdata.cloud and I can take a look at your metrics if that is not a problem.

**Comment by kmlucy** [comment] 2020-01-14 17:26
@mfundul It doesn't happen every night, and I only store 24hrs of metrics, so I will send it the next time I get errors.

**Comment by kmlucy** [comment] 2020-01-15 13:57
@mfundul Just sent the snapshot.

**Comment by mfundul** [comment] 2020-01-15 17:53
@kmlucy thanks for the snapshot, it looks indeed problematic. Can you also send me the relevant `var/log/netdata/error.log*` file?

**Comment by kmlucy** [comment] 2020-01-15 19:43
Because netdata is running in Docker, I don't have an `error.log` file per se; it is redirected to `stderr`. I grabbed the information from there for the time period of the snapshot +/- a few hours and emailed that to you. Let me know if you want an extended time period, because I have the error logs going back to the last time I restarted the container, I think about four days ago.

**Comment by mfundul** [comment] 2020-01-15 20:36
It looks like the cause for the condition which triggers the alarm is that some data file deletion took too long to complete. Can you send me the full logs to see if there is some kind of pattern please?

**Comment by kmlucy** [comment] 2020-01-15 20:41
I just sent the full error log, starting from 2020-01-09 through now.

**Comment by ElleshaHackett** [comment] 2020-02-03 14:56
I currently have the same issue on one machine. 

On that machine the warning is: 
`netdata.dbengine_global_errors: 2875 errors`

GUI shows:
`Every second, Netdata collects 3.178 metrics on XXX, presents them in 312 charts and monitors them with 137 alarms.`

What can I do about it?

**Comment by ilyam8** [comment] 2020-02-03 15:01
hi @ElleshaHackett i see there is a fix https://github.com/netdata/netdata/pull/7777, i think it will be merged soon

**Comment by mfundul** [comment] 2020-02-03 15:05
@ilyam8 I don't think it's related. @ElleshaHackett look at your alarms and see which one is the problematic one of the "10min_dbengine_global_fs_errors", "10min_dbengine_global_io_errors" or "10min_dbengine_global_flushing_errors". Also please check your `var/log/netdata/error.log` for any relevant messages.

**Comment by ilyam8** [comment] 2020-02-03 16:19
oh, ok, in my defence

the pr fixes the issue and i see `I currently have the same issue` 😄

**Comment by ElleshaHackett** [comment] 2020-02-03 21:19
![image](https://user-images.githubusercontent.com/5116641/73691661-1013d380-46d3-11ea-91c7-5235b956f6f2.png)

**Comment by mfundul** [comment] 2020-02-03 21:46
@ElleshaHackett it looks like it's similar after all, it's probably going to be fixed by #7777 .

**Comment by ElleshaHackett** [comment] 2020-02-03 21:50
@mfundul thanks. Hopefully it will be fixed soon

**Comment by jbfuzier** [comment] 2020-03-11 09:29
Hi,

I am having the same issue in v1.20 with the following setup : 

- 10 headless, memory = none collectors, streaming to a central colector
- Around 5k metrics / collector => ~50k metrics on the central collector
- Central collector is running in a lxc container (proxmox), storage is on a dedicated SSD (memory=dbengine)

- OS / Environment
> Linux grafana 4.15.18-12-pve #1 SMP PVE 4.15.18-35 (Wed, 13 Mar 2019 08:24:42 +0100) x86_64 GNU/Linux Debian 9.5 running in a LXC container (Proxmox) - 32GB of RAM (7GB used, the rest is used by the OS for caching), 8 CPU cores peak use 10%

- Netdata Version
>v1.20.0

- Component  Name
>dbengine

In error.log I get the messages : 
```
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
2020-03-11 10:04:09: netdata ERROR : MAIN : Failed to flush dirty buffers quickly enough in dbengine instance "/opt/netdata/var/cache/netdata/e295a868-5042-11e7-9bce-3863bb3e6c28/dbengine". M
etric data are being deleted, please reduce disk load or use a faster disk.
```

I also get alarms : 

![image](https://user-images.githubusercontent.com/4688432/76400669-f70cdb00-6380-11ea-99d4-6a8dee8d150a.png)

Db engine related metrics : 
![image](https://user-images.githubusercontent.com/4688432/76400819-3affe000-6381-11ea-8d28-878a1e55dfd4.png)

Storage metric for the volume used by the netdata central collector (the one having memory=dbengine), which seems to indicate the disk is not overloaded: 
![image](https://user-images.githubusercontent.com/4688432/76400960-71d5f600-6381-11ea-81b2-385c577fe43c.png)
![image](https://user-images.githubusercontent.com/4688432/76401074-9f22a400-6381-11ea-9f04-4f0107376890.png)

Still on the central collector : 
![image](https://user-images.githubusercontent.com/4688432/76401198-d09b6f80-6381-11ea-9584-0b3b7008bdeb.png)

```

[backend]
	enabled = yes
	type = graphite
	destination = tcp:127.0.0.1:2003
	data source = as-collected
	prefix = netdata
	update every = 30
	buffer on failures = 10000
	timeout ms = 20000


[global]
	update every = 1
	memory mode = dbengine
	page cache size = 192
	dbengine disk space = 2048
	errors flood protection period = 10
	errors to trigger flood protection = 100000


[statsd]
	decimal detail = 1
	update every (flushInterval) = 1
	max private charts allowed = 100000
	max private charts hard limit = 100001
	private charts memory mode = ram
	private charts history = 600
	private charts hidden = yes
	add dimension for number of events received = no
	gaps on gauges (deleteGauges) = yes
	listen backlog = 16384
	bind to = udp:*:8125 tcp:*:8125

```

**Comment by mfundul** [comment] 2020-03-11 11:27
It seems like those errors are only about one of the netdata slaves, namely `e295a868-5042-11e7-9bce-3863bb3e6c28`. Can you share some history from `error.log` that may relate to what's happening to `e295a868-5042-11e7-9bce-3863bb3e6c28`? Did an event happen immediately before those errors, or do those errors happen constantly with a certain frequency?

**Comment by jbfuzier** [comment] 2020-03-11 13:00
It happen constantly : 

![image](https://user-images.githubusercontent.com/4688432/76419312-6b0aab80-63a0-11ea-8108-3c26d94a0a74.png)
![image](https://user-images.githubusercontent.com/4688432/76419359-7cec4e80-63a0-11ea-9ddf-8c1718b4dfd4.png)

I think this UID is the central collector. How can I find which host is being a given uid ?

**Comment by mfundul** [comment] 2020-03-11 13:04
> 
> 
> It happens constantly :
> 
> ![image](https://user-images.githubusercontent.com/4688432/76419312-6b0aab80-63a0-11ea-8108-3c26d94a0a74.png)
> ![image](https://user-images.githubusercontent.com/4688432/76419359-7cec4e80-63a0-11ea-9ddf-8c1718b4dfd4.png)
> 
> I think this UID is the central collector. How can I find which host is being a given uid ?

The master server would be at `/opt/netdata/var/cache/netdata/dbengine`, this is one of the slaves.

You can check your slave's netdata installation folders, the UUID should be under `var/lib/netdata/registry/netdata.public.unique.id`. For example, for your netdata master server it would be under:
`/opt/netdata/var/lib/netdata/registry/netdata.public.unique.id`.

**Comment by mfundul** [comment] 2020-03-11 13:34
> 
> 
> It happens constantly :
> 
> ![image](https://user-images.githubusercontent.com/4688432/76419312-6b0aab80-63a0-11ea-8108-3c26d94a0a74.png)
> ![image](https://user-images.githubusercontent.com/4688432/76419359-7cec4e80-63a0-11ea-9ddf-8c1718b4dfd4.png)
> 
> I think this UID is the central collector. How can I find which host is being a given uid ?

Can you highlight the "flushing_pressure_deletions" dimension instead of the "deletions" dimension for me please?

**Comment by jbfuzier** [comment] 2020-03-11 13:38
Here are the error log from the slave e295a868 and from the central instance : 

[error_log.zip](https://github.com/netdata/netdata/files/4318502/error_log.zip)

This slave instance collects lots of metric using statsd, those metrics are used in the graphite backend, we are using netdata just to centralise & collect them.

On  e295a868 : 

![image](https://user-images.githubusercontent.com/4688432/76422526-a3f94f00-63a5-11ea-9093-4006815d0850.png)


This slave is running v1.17.1, however the central which is running the dbengine is on v1.20.0; could this be an issue ?


On the central (flushing_pressure_deletions selected) : 

![image](https://user-images.githubusercontent.com/4688432/76422747-02bec880-63a6-11ea-90e8-9745a1184623.png)

**Comment by mfundul** [comment] 2020-03-11 13:43
> 
> This slave is running v1.17.1, however the central which is running the dbengine is on v1.20.0; could this be an issue ?
> 

This shouldn't be a problem. I will take a look at the logs.

**Comment by mfundul** [comment] 2020-03-11 16:39
It seems like it's always related to the netdata slave `pleistocene11` from localhost not updating its own local statsd metrics frequently enough, e.g.:

```
2020-03-11 11:15:09: netdata INFO  : STREAM_RECEIVER[pleistocene11,[localhost]:37624] : statsd_gauge_syslogng.pleistocene111.src_host.webserver__oranea3adm_mc2_company_fr.processed: too old data (last updated at 1583920029.0, last collected at 1583921709.2427). Resetting it. Will not store the next entry.
```

It seems like those metrics are not being collected for tens of minutes at a time for some reason.

**Comment by mfundul** [comment] 2020-03-11 16:55
@jbfuzier do you have any idea why that may be happening to `pleistocene11`? Can you give me additional information about this specific netdata agent?

**Comment by mfundul** [comment] 2020-03-11 17:14
I'd also like to know how many total metrics are in this agent (5K again?) and how many charts. I'd like to get a feeling of the average amount of metrics per chart in `pleistocene11`. Doing a query at `localhost:19999/api/v1/charts` would be useful (or whatever IP address is the correct one for this netdata agent).

**Comment by jbfuzier** [comment] 2020-03-11 18:22
Every second, Netdata collects 5,460 metrics on pleistocene11, presents them in 2,232 charts and monitors them with 247 alarms.

**Comment by mfundul** [comment] 2020-03-11 18:27
> 
> 
> Every second, Netdata collects 5,460 metrics on pleistocene11, presents them in 2,232 charts and monitors them with 247 alarms.

Is there a chance there may be some huge charts (lots of dimensions per very few charts)? How many charts are produced by statsd? Could you identify what the largest chart is from statsd? How many dimensions in it?

**Comment by jbfuzier** [comment] 2020-03-11 18:35
Is it ok if I collect the /api/v1/charts through the central netdata through <my_central_netdata>/host/pleistocene11/api/v1/charts ? Or do I need to do it on the slave itself ?

I can send the file to you if you send me your email (I can not post this publicly)

From you question on what my be happening, pleistocene11 has the folowing config : 


```
[global]
        memory mode = none
        update every = 1
        errors flood protection period = 1
        errors to trigger flood protection = 10000
[web]
        mode = none
[plugins]
        tc = no
        enable running new plugins = no
        python.d = no
        apps = yes
        node.d = no
        charts.d = no
[statsd]
        update every (flushInterval) = 1
        decimal detail = 1
        max private charts allowed = 0
        max private charts hard limit = 20000
        private charts history = 600
        udp messages to process at once = 4096
        listen backlog = 16384
        add dimension for number of events received = no
        gaps on gauges (deleteGauges) = yes

```

There are lots of different scripts that run on this server and take advantage of the statsd daemon to collect metrics data; however for most of those, metrics are only sent to the statsd daemon every X minutes. (Most job are cron scripts, one usual use case is for the script to report the time it took, the amont of data it processed... to the statsd daemon on 127.0.01). For most scripts there is a kind of batch effect where lot of metric are sent quickly to statsd.

```

	"charts_count": 2232,
	"dimensions_count": 5460,
	"alarms_count": 247,
	"rrd_memory_bytes": 13399632,
```

**Comment by jbfuzier** [comment] 2020-03-11 18:42
> Is there a chance there may be some huge charts (lots of dimensions per very few charts)? How many charts are produced by statsd? Could you identify what the largest chart is from statsd? How many dimensions in it?

All my statsd charts are single dimension charts. 1241 charts currently.


Here is a typical chart : 
```

		"statsd_gauge_syslogng.pleistocene110.src_host.firewall1__firewall1_intra_.processed": 		{
			"id": "statsd_gauge_syslogng.pleistocene110.src_host.firewall1__firewall1_intra_.processed",
			"name": "statsd_gauge_syslogng.pleistocene110.src_host.firewall1__firewall1_intra_.processed",
			"type": "statsd_gauge_syslogng",
			"family": "gauges",
			"context": "statsd_gauge.syslogng.pleistocene110.src_host.firewall1__firewall1_intra_.processed",
			"title": "statsd private chart for gauge syslogng.pleistocene110.src_host.firewall1__firewall1_intra_.processed (statsd_gauge_syslogng.pleistocene110.src_host.firewall1__firewall1_intra_.processed)",
			"priority": 90000,
			"plugin": "statsd.plugin",
			"module": "private_chart",
			"enabled": true,
			"units": "value",
			"data_url": "/api/v1/data?chart=statsd_gauge_syslogng.pleistocene110.src_host.firewall1__firewall1_intra_.processed",
			"chart_type": "line",
			"duration": 804500,
			"first_entry": 1583147389,
			"last_entry": 1583951888,
			"update_every": 1,
			"dimensions": {
				"gauge": { "name": "gauge" }
			},
			"chart_variables": {
			},
			"green": null,
			"red": null,
			"alarms": {

			}
```

This is from one script which query the syslog-ng daemon on the server every 60s, get the number of event received for each host sending logs to the syslog server, send this data to statsd.

**Comment by mfundul** [comment] 2020-03-11 18:46
> 
> 
> Is it ok if I collect the /api/v1/charts through the central netdata through <my_central_netdata>/host/pleistocene11/api/v1/charts ? Or do I need to do it on the slave itself ?
> 
> I can send the file to you if you send me your email (I can not post this publicly)
> 

You can send it to me at markos@netdata.cloud but that may not be necessary if the statsd charts are single dimension charts.

> From you question on what my be happening, pleistocene11 has the folowing config :
> 
> ```
> [global]
>         memory mode = none
>         update every = 1
>         errors flood protection period = 1
>         errors to trigger flood protection = 10000
> [web]
>         mode = none
> [plugins]
>         tc = no
>         enable running new plugins = no
>         python.d = no
>         apps = yes
>         node.d = no
>         charts.d = no
> [statsd]
>         update every (flushInterval) = 1
>         decimal detail = 1
>         max private charts allowed = 0
>         max private charts hard limit = 20000
>         private charts history = 600
>         udp messages to process at once = 4096
>         listen backlog = 16384
>         add dimension for number of events received = no
>         gaps on gauges (deleteGauges) = yes
> ```
> 
> There are lots of different scripts that run on this server and take advantage of the statsd daemon to collect metrics data; however for most of those, metrics are only sent to the statsd daemon every X minutes. (Most job are cron scripts, one usual use case is for the script to report the time it took, the amont of data it processed... to the statsd daemon on 127.0.01). For most scripts there is a kind of batch effect where lot of metric are sent quickly to statsd.
> 
> ```
> 
> 	"charts_count": 2232,
> 	"dimensions_count": 5460,
> 	"alarms_count": 247,
> 	"rrd_memory_bytes": 13399632,
> ```

@ilyam8 @vlvkobal do you have any insight on the effects of this statsd batch effect?

**Comment by mfundul** [comment] 2020-03-11 19:30
Let's keep track of this problem in #8384.

**Closed by mfundul** 2020-03-11 19:30 UTC
Labels: area/database, bug, needs triage
