### ISSUE TITLE
Inconsistent information on Netdata Cloud

### ISSUE THREAD

**Issue by thoggs** [netdata/netdata#9114] opened 2020-05-20 17:49 UTC
Hello people,
I know that the Netdata Cloud project is recent, and with that it is a fact that we will have some small problems; still, for the progress of the project, which I like a lot and, I use it daily; I would like to report what is happening to me:

**NOTE:** Occurs with machines running Linux and FreeBSD; both clean installations, from scratch, with no other software running, ie only Netdata is running.

**Problem ->** My machine (a server running FreeBSD), is showing up with inconsistent information that doesn't match what my hardware is (on the Dashboard), as shown in the following photo:

**NOTE: It is not a Virtual Machine, it is a physical machine**

![Captura de Tela 2020-05-20 às 14 36 18](https://user-images.githubusercontent.com/43221193/82479446-c9db5800-9aa8-11ea-8b9e-c1ae374d9195.png)

**OS:** FreeBSD 12.1 RELEASE - Standard installation: no lib32
**Netdata Version:** 1.22.1-74-nightly

**Comment by thiagoftsm** [comment] 2020-05-20 18:03
Hello @thoggs ,

@Ferroin could be a problem with our `daemon/system-info.sh` script?
@thoggs , please, could you run `daemon/system-info.sh` and verify if it is identifying your computer information correctly?

Best regards!

**Comment by thoggs** [comment] 2020-05-20 18:08
> Hello @thoggs ,
> 
> @Ferroin could be a problem with our `daemon/system-info.sh` script?
> @thoggs , please, could you run `daemon/system-info.sh` and verify if it is identifying your computer information correctly?
> 
> Best regards!

Hello @thiagoftsm,

Here is the output from the script `system-info.sh`:

![Captura de Tela 2020-05-20 às 15 06 01](https://user-images.githubusercontent.com/43221193/82481461-b8477f80-9aab-11ea-92e7-1f0468a71611.png)

**Comment by thiagoftsm** [comment] 2020-05-20 18:13
Thank you very much @thoggs !
Is the script output matching your hardware?

**Comment by thoggs** [comment] 2020-05-20 18:20
So in reality yes, but in parts, for example:

**NETDATA_SYSTEM_TOTAL_DISK_SIZE=3097889267712** (this will give 3 terabyte right?)
In this case, no, because I don't have 3 terabytes of disk installed on this hardware.

**Comment by thiagoftsm** [comment] 2020-05-20 18:27
Thank you for the additional information!

> NETDATA_SYSTEM_TOTAL_DISK_SIZE=3097889267712 (this will give 3 terabyte right?)
In this case, no, because I don't have 3 terabytes of disk installed on this hardware.

@Ferroin , please, can you take a look on this?

**Comment by prologic** [comment] 2020-05-21 00:51
@Ferroin Don't have you a PR to improve this? Can we get that merged? I believe it is #7902

**Comment by Ferroin** [comment] 2020-05-21 11:10
#7902 wouldn't fix this (it does nothing in the FreebSD case), but is indeed related.

@thoggs Can you share the output from `df` on the same system you shared the `system-info.sh` output for above?

**Comment by thoggs** [comment] 2020-05-21 15:09
> #7902 wouldn't fix this (it does nothing in the FreebSD case), but is indeed related.
> 
> @thoggs Can you share the output from `df` on the same system you shared the `system-info.sh` output for above?

Following request:

![Captura de Tela 2020-05-21 às 12 08 47](https://user-images.githubusercontent.com/43221193/82573272-f4d2b400-9b5b-11ea-9225-e98844f9d4c1.png)

**Comment by amoss** [comment] 2020-05-22 09:47
It sounds as if the problem is that we treat bare-metal installs as `unknown` virtualization. If we reach the end of the cases in the `system-info.sh` without detecting any virtualization then we should assume that we are running on bare metal. We could overwrite the `unknown` value with `none` at this point, but I think it will still require a change to the display on the cloud side.

**Comment by thoggs** [comment] 2020-05-23 05:14
> It sounds as if the problem is that we treat bare-metal installs as `unknown` virtualization. If we reach the end of the cases in the `system-info.sh` without detecting any virtualization then we should assume that we are running on bare metal. We could overwrite the `unknown` value with `none` at this point, but I think it will still require a change to the display on the cloud side.

I understand, in other words, is there anything that the user can do?

**Comment by amoss** [comment] 2020-05-23 05:59
> I understand, in other words, is there anything that the user can do?

I don’t think there is anything that you can do immediately, we need to release a patch to change the script. @manos-saratsis could you check with the Cloud Team how we can fix this?

**Comment by prologic** [comment] 2020-05-25 05:02
> I don’t think there is anything that you can do immediately, we need to release a patch to change the script. @manos-saratsis could you check with the Cloud Team how we can fix this?

If you're talking about the `./daemon/system-info.sh` script; We can probably update this.

**Comment by prologic** [comment] 2020-06-24 07:12
Circling back on this; I understand the problem to be that we don't report bare-metal instances of Netdata. Is this right @amoss @thoggs ?

**Comment by amoss** [comment] 2020-06-24 09:37
Yes - the cloud UI should be updated to indicate bare metal.

**Comment by prologic** [comment] 2020-06-24 13:43
A quick one-line fix for this could be we just swap `unknown` for `bare-metal` and assume that if we cannot figure out what Hypervisor is being used that we _must_ surely be running on bare-metal (_if also not running in a container_). Will this work for everyone?

**Comment by Ferroin** [comment] 2020-06-24 15:19
@prologic that sounds like a reasonable solution to me. Barring stuff like cpuidle and frequency scaling, virtualization we can't ID is functionally equivalent to bare metal for our purposes.

**Closed** 2020-06-29 18:21 UTC
Labels: area/daemon, bug, needs triage

**Comment by Ferroin** [comment] 2020-06-29 18:24
A fix for the virtualization reporting that prompted this issue has been merged. We're planning on releasing 1.23.1 including this and a few other fixes within the next few days, but it should e in the nightlies starting tonight.
