### ISSUE TITLE
[Bug]: LXD containers on ZFS not showing disk space usage

### ISSUE THREAD

**Issue by k-hristov** [netdata/netdata#14789] opened 2023-03-22 08:04 UTC
### Bug description

There is no graph for zfs dataset usage after setting up disk quota.

### Expected behavior

There should be a graph with ZFS dataset space usage.

### Steps to reproduce

1. Install LXD from snapd and configure it to work with ZFS backend
2. Install netdata with kickstart
3. Create container and set disk quota
4. In netdata UI i can see the container, cpu usage, network, ram, some disk statistics but not usage for the quota

### Installation method

kickstart.sh

### System info

```shell
Linux BOX1 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.2 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Version: netdata v1.38.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

zfs list shows all dataset and with "disk usage":
```
NAME                                                                                      USED  AVAIL     REFER  MOUNTPOINT
default                                                                                  17.0G   118G       24K  legacy
default/buckets                                                                            24K   118G       24K  legacy
default/containers                                                                       14.6G   118G       24K  legacy
default/containers/gitlab                                                                2.75G   118G     2.97G  legacy
default/containers/mir                                                                    141M   118G      347M  legacy
default/containers/nc                                                                     128M   118G      298M  legacy
default/containers/nextcloud                                                             1.09G   118G     1.22G  legacy
default/containers/onlyoffice                                                            1.37G   118G     1.57G  legacy
default/containers/rocketchat                                                            1.47G   118G     1.66G  legacy
default/containers/storage                                                               2.92G  15.7G     3.11G  legacy
default/containers/storage3                                                              3.54G   118G     3.68G  legacy
default/containers/ub                                                                    82.1M   118G      254M  legacy
default/containers/ub2                                                                   83.0M   118G      251M  legacy
default/containers/vms                                                                    420M   118G      646M  legacy
```

**Comment by ilyam8** [comment] 2023-03-22 09:57
Hi, @k-hristov. I think that is not a bug. Netdata collects containers/VMs metrics from [/sys/fs/cgroup/](https://man7.org/linux/man-pages/man7/cgroups.7.html). It doesn't expose the metrics you want.

**Comment by ilyam8** [comment] 2023-03-22 10:43
- [diskspace.plugin](https://github.com/netdata/netdata/tree/master/collectors/diskspace.plugin#monitor-disk-diskspaceplugin) shows disk usage for mountpoints. So you should see disk usage stats for those datasets that have a value in the MOUNTPOINT column (not `-` or `legacy`).
- if you install Netdata inside a container you will get much more metrics including disk usage stats. I think parent-child setup is an option here (parent is a regular install on the host system, and Netdata is installed in every container and streams to the parent).

Collecting `zfs list` metrics would be a new collector, I think it is easy to add, but it won't be possible to associate a dataset with VM/container.

**Comment by k-hristov** [comment] 2023-03-23 15:43
It could probably be an additional graph for ZFS plugin. For each dataset.

Is there a tutorial how I can create it?

**Comment by ilyam8** [comment] 2023-12-26 18:35
Closing because that is [not a bug](https://github.com/netdata/netdata/issues/14789#issuecomment-1479246037).

> Collecting zfs list metrics would be a new collector, but it won't be possible to associate a dataset with VM/container.

It looks like we have an issue for it #14937

**Closed by ilyam8** 2023-12-26 18:35 UTC
Labels: question, area/collectors
