### ISSUE TITLE
netdata/packaging: Provide pre-compiled static binary of netdata for other architectures 

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6847] opened 2019-09-15 06:51 UTC
##### Feature idea summary
As per the issues https://github.com/netdata/netdata/issues/6846 and https://github.com/netdata/netdata/issues/6818, we need to provide pre-compiled binaries of other architectures apart from amd64, so that we can be compatible with devices such as routers.

We are currently taking advantage of docker images to build our pre-compiled binary, so if we combine the technique we use to build multi-arch docker images of netdata, we can easily provide multi-arch versions of pre-compiled versions

##### Expected behavior
Provide pre-compiled static binary of netdata for multiple architectures together with the rest of the release artifacts for stable and nightly releases

**Comment by BH1NBN** [comment] 2019-09-26 13:53
+1

**Comment by BH1NBN** [comment] 2020-01-16 12:58
@paulkatsoulakis @prologic 
Hello there! Because I know very little about Linux and how to compile, but I can give you the information you need. What information do you need or what should I do?

Attached are some commands I am running for your reference! If I need to use remote ssh, I will authorize my network specifically for you
======================================================== ============
I also provided you with some related links! Links needed for cross compilation
https://github.com/koolshare/rogsoft (Chinese)
https://github.com/RMerl/am-toolchains/tree/master/brcm-arm-hnd
======================================================== ============
[busybox --list.txt] (https://github.com/netdata/netdata/files/4071244/busybox.--list.txt)
[uname -a.txt] (https://github.com/netdata/netdata/files/4071245/uname.-a.txt)
[version.txt] (https://github.com/netdata/netdata/files/4071246/version.txt)

**Comment by Ferroin** [comment] 2021-08-10 12:38
This is planned as part of the followup work for the upcoming overhaul of the installer and updater code. Right now, the plan is to just worry about 32 and 64 bit ARM in our static builds and some binary packages. Longer term we _may_ add POWER8+ support as well.

**Comment by Ferroin** [comment] 2021-08-10 12:47
Closing as a duplicate of #7824, which will be the canonical issue for this going forwards.

**Closed by Ferroin** 2021-08-10 12:47 UTC
Labels: area/packaging, feature request
