### ISSUE TITLE
injecting/marking a checkpoint from cli

### ISSUE THREAD

**Issue by levinale-github** [netdata/netdata#10117] opened 2020-10-21 22:47 UTC
##### Feature idea summary
When debugging/inspecting performance it typically comes with some testing or a scenario, e.g. fio. As it is, it's sometimes hard to tell where the test starts and ends as in many cases the system has other processes or pre-conditions.

##### Expected behavior
I would want to be able to inject markers, from cli to mark a test start and test finish so that the analysis would be more pressie. An even better solution would be to allow an option to delete the data gathered beyond the scopes of these markers (but this is secondary to being able to put these markers on there)

Here is an image borrowed form issue #1195 (which was closed by stating this is implemented from UI's perspective, which for most practical use isn't a usable implementation).
![image](https://user-images.githubusercontent.com/23265436/96794989-2f16da80-13b4-11eb-92c6-51c7e7e1afc0.png)

**Comment by Saruspete** [comment] 2020-10-23 08:26
Hello,

Looks like Epic #6523 which I would love to have since many years !
There's also #9815 that would allow to store such events.

**Comment by OdysLam** [comment] 2020-10-23 16:07
Hey @levinale-github,

Thanks for this feature request and welcome to the forums. As @Saruspete said, we are already investigating this, but due to the sheer number of features that we want to build, we have to be ruthless with our prioritization. BTW, welcome to our community!

@Saruspete thanks for providing the information :)

**Comment by levinale-github** [comment] 2020-10-23 18:23
Thanks @OdysLam . 

I really like the way netdata allows a "look under the hood" but keep in mind that most if not all need for performance debug is for a specific load. If need be I can provide a few real examples. Load is generated by scenarios/tests controlled only from shell. 

Just looking at netdata while running load is good, but allowing to take precise snapshot or mark events (e.g. DTPF events, perf events) on the time axis will add immense usability. 

Maybe a bit of background for the prioritization part - I'm trying to use netdata as part of ChromeOS (which I'm part of). As any other organization running Linux, test/load is done via cli. We have to be able to script this into the infrastructure.

Having this feature would potentially allow wider adoption and in turn more contributors from Google.

**Comment by OdysLam** [comment] 2020-10-26 08:06
Hey @levinale-github,

Thanks for the thorough feedback. As I am logging this and communicating back with the team, would you like to be able to insert timestamp marks in Netdata which will be communicated back to the user in the charts?

**Comment by Saruspete** [comment] 2020-10-26 09:16
Hello,

More than a timestamp, we need a label too. Just having a mark per-see without text / tag is not that useful.

**Comment by cakrit** [comment] 2020-10-26 17:21
Closing this as a duplicate of #6523. Let's continue there.

**Closed by cakrit** 2020-10-26 17:21 UTC
Labels: feature request, needs triage
