### ISSUE TITLE
Terabytes receive speed, not be  possible:(

### ISSUE THREAD

**Issue by lygstate** [netdata/netdata#5701] opened 2019-03-24 16:05 UTC
![新建位图图像 (2)](https://user-images.githubusercontent.com/121040/54882135-ecb4b100-4e91-11e9-93ed-e0f1c11b7b7b.jpg)

**Comment by ilyam8** [comment] 2019-03-24 16:17
Hi @lygstate 	

related: #4962

That is how netdata handle counter (incremental) reset.

**Comment by cakrit** [comment] 2019-03-25 09:19
Closing this as duplicate of #4962, I pinged @ktsaou so we can look at #5317 again.

**Closed by cakrit** 2019-03-25 09:19 UTC
