### ISSUE TITLE
Alarm on max on any dimension

### ISSUE THREAD

**Issue by kmlucy** [netdata/netdata#3249] opened 2018-01-09 00:40 UTC
I am trying to create an alarm based on my maximum hard drive temperature. I am using the hddtemp plugin which creates a chart with a dimension for each hard drive. 

The problem I am running into is that hard drives are not always mounted to the same point, i.e. a drive might be /dev/sdb on one boot, but /dev/sda on another. Because not all my drives are capable of temperature monitoring, every boot I have to modify my alarms to match which drives are temperature monitoring capable.

Here is what I am currently using:
```
 alarm: sdb_temp
    on: hddtemp.temperatures
lookup: max -1m of sdb
 green: 40
   red: 45
 every: 10s
  warn: $this > $green
  crit: $this > $red
  info: max HDD temperature of the last 1 minute
```

Is there a better way to monitor the max drive temperature?

**Comment by l2isbad** [comment] 2018-01-09 01:20
Hi @kmlucy 
[Templates](https://github.com/firehol/netdata/wiki/health-configuration-reference#entities-in-the-health-files) ?
context is` hddtemp.temperatures`

**Comment by kmlucy** [comment] 2018-01-09 01:25
Yeah, best I can tell you can template on charts, but not on dimensions.

**Comment by l2isbad** [comment] 2018-01-09 01:33
Yeah. Actually i have the same problem (`dns_quiery_time` module)
I may be wrong but the only way is to create N alarms:

```yaml
 alarm: sda_temp
    on: hddtemp.temperatures
lookup: max -1m of sda
 green: 40
   red: 45
 every: 10s
  warn: $this > $green
  crit: $this > $red
  info: max HDD temperature of the last 1 minute

 alarm: sdb_temp
    on: hddtemp.temperatures
lookup: max -1m of sdb
 green: 40
   red: 45
 every: 10s
  warn: $this > $green
  crit: $this > $red
  info: max HDD temperature of the last 1 minute
```

This is what i did.

**Comment by l2isbad** [comment] 2018-01-09 01:37
Found it
https://github.com/firehol/netdata/issues/3097

So the feature is on TODO list

**Comment by ddipak** [comment] 2019-03-26 17:18
How about using the disk UUID instead of names like sda_temp. The Linux support the uuids for disk, partitions. Please check [https://unix.stackexchange.com/questions/375548/what-is-uuid-partuuid-and-ptuuid](url). 

`$ sudo blkid  /dev/sda
/dev/sda: PTUUID="454077d5" PTTYPE="dos"`

Now template could look like as follows
`alarm: 454077d5_temp
    on: hddtemp.temperatures
lookup: max -1m of sda
 green: 40
   red: 45
 every: 10s
  warn: $this > $green
  crit: $this > $red
  info: max HDD temperature of the last 1 minute
`
This is my first comment. I hope it is making sense.

**Comment by cakrit** [comment] 2019-03-27 12:38
We have to avoid creating individual alarm configurations for each dimension. Just as we have alarm templates that ensure we have the same alarm regardless of host or device monitored, the query function of MAX will need to be modified to let us run it on any of the individual dimensions of a chart.

**Comment by ilyam8** [comment] 2019-03-28 07:45
i think we need another set of functions and not modifying current max

**Comment by cakrit** [comment] 2019-03-28 12:42
We're getting confused. #2107 is supposed to allow alarms on every dimension. That can be done by adding something at the end of lookup, to indicate that we want each dimension treated separately. 
I'm pretty sure we said that `max` has a different issue, it's the only one doing a sum of the dimensions first, so it's a separate change for this one. Did I get something wrong?

**Comment by gpapamathND** [comment] 2019-08-16 12:16
Duplicate of #4154

**Closed by gpapamathND** 2019-08-16 12:16 UTC
Labels: area/health, feature request, priority/medium
