### ISSUE TITLE
opentsdb backend enhancements

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#2690] opened 2017-09-06 20:41 UTC
When netdata is pushing metrics to backends, it assumes each dimension of each chart is a backend metric.

For prometheus though, we assumed that the chart is the backend metric, and the dimensions are tags / attributes of the metric.

So, for opentsdb we send:

```
system.cpu.user
system.cpu.nice
```

But for prometheus we send

```
system.cpu{dimension="user"}
system.cpu{dimension="nice"}
```

Of course, this format allows prometheus users to write more efficient queries (easier to remember, more flexible, etc).

I know opentsdb supports tags, but I am not sure if it supports tags in a way that could allow the prometheus methodology to be applied to it.

If anyone is using opentsdb and can help me figure out, just post.

**Comment by sarlalian** [comment] 2017-09-15 18:54
OpenTSDB supports tags as well, as do Influxdb which has an available OpenTSDB endpoint for use.

Stealing a bit from the OpenTSDB documentation, 

> Every time series in OpenTSDB must have at least one tag.

> The easiest way to get started with OpenTSDB is to open up a terminal or telnet client, connect to your > TSD and issue a put command and hit 'enter'. If you are writing a program, simply open a socket, print > the string command with a new line and send the packet. The telnet command format is:
```
put <metric> <timestamp> <value> <tagk1=tagv1[ tagk2=tagv2 ...tagkN=tagvN]>
```
> For example:
```
put sys.cpu.user 1356998400 42.5 host=webserver01 cpu=0
```

A posible schema for your above example would be.

```
put system.cpu 1356998400 10.0 host=myhostname dimension=user
put system.cpu 1356998400 11.0 host=myhostname dimension=nice
```

**Comment by ktsaou** [comment] 2017-09-15 22:15
thanks! this is nice.
Do you use netdata with opentsdb (or compatible) backend?
I would love to apply the same methodologies we applied to prometheus. But I need a tester, someone that will install the modified netdata and verify it works well with the new opentsdb interface. Can you help?

**Comment by sarlalian** [comment] 2017-09-18 03:03
Yes, netdata on about 400 hosts, pushing to InfluxDB via OpenTSDB emulation.  Happy to help

**Comment by grozeille** [comment] 2017-12-29 21:48
I have quite similar need.
I wish to use netdata to monitor my Docker containers and centralize that in OpenTSDB.
The problem is: the name of the docker image is not in a tag, but in the metric name.
Ex:

`netdata.cgroup_r_jenkins_jenkins_lb_1_d40571db.cpu.user`

When I use Grafana to query OpenTSDB, it tries to get all metrics with the "suggest" API, but it requires a "limit" that is hardcoded in Grafana for OpenTSDB plugin, so I don't have all my docker images from the list.

It seems that Telegraf has the ability to create multiples tags:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker

Using tags instead of metric name won't solve the hardcoded limit issue in Grafana, but I'll be able to filter using multiple tags:
http://docs.grafana.org/features/datasources/opentsdb/#nested-templating

Ex:
- on the metric "netdata.cgroup.cpu.user", get all values of the tag "hostname"
- then on the metric "netdata.cgroup.cpu.user", get all values of the tag "cgroup" with the previously selected tag "hostname" (and hopefully it will be less than the hardcoded limit)

What would be nicer if, as in telegraf, netdata retrieves the docker image as tag to have even finer filter.

In fact, all "dynamic" values should be defined as tag instead of metric name (cpu id, disk name, etc.).
And as suggested for cpu, all graph (cpu dimension, but also io read/write, network sent/received, etc.) could be defined as tag.

**Comment by grozeille** [comment] 2017-12-29 22:02
Oh, in fact, using tags will solve my "grafana hardcoded limit".
I'm reaching the 3000 limit today, not because I have more than 3000 docker containers (cgroup) but because I can't search for metrics using a regex, only by a prefix, so I'm getting all metrics per cgroup in my query.

Using tags, I just have to ask for all values for a key and a single metric . If I'm reaching more than 3000 cgroup in the same time range, it will be another problem.

**Comment by ktsaou** [comment] 2018-01-03 15:36
@grozeille I think the problem you face is not relevant to this issue.

This issue is about passing the chart dimensions as tags.

What you need is to split the netdata chart IDs in parts, and use a few of these parts as tags. The way netdata is now, this is somewhat messy to do. We will need first to enhance netdata charts naming conventions (check #807 ) and then use that information to provide tags for the backends.

I suggest to open a new issue for this.

**Comment by grozeille** [comment] 2018-01-20 22:11
I agree with passing the chart dimensions as tags.
I'm asking to pass also some dynamic metric names as tags also:
- cpu.cpu0, cpu.cpu1...
- net.eth0, net.eth1...
- disks.sda, disks.sdb...
And same for cgroups:
- cgroup_c5102650.cpu, cgroups_65166b0f.cpu...

If you thing it's another issue, I can create a new one.
Passing them as tags solve my issue.
Ex: image I'm having 4 cgroups.
Asking the OpenTSDB API for all tags for key = "cgroup" will return 4 elements.
Asking the OpenTSDB API for all metrics starting with cgroup_ will return 4 x 3 (3 is the number of metrics per cgroup, cpu/mem/disk). 

By the way, the cgroup management is not consistent with other metrics.
- apps: seems to be a "family" with your convention
- apps.cpu / apps.disk... : seems to be a "category"
- apps.cpu.java / apps.cpu.ssh ... : seems to be a "dimension"

I suggest to do the same with cgroups:
- cgroup: family
- cgroup.cpu : category
- cgroup.cpu.user.65166b0f : dimension (type/subtype ?)
Today, the ID of the cgroup is family (cgroup_[the_id])

**Comment by ktsaou** [comment] 2018-11-23 14:59
@cakrit 	this is about improving the OpenTSDB backend to support tags, like the prometheus one does.
Generally, we should support backends in the most comperhensive way.

**Comment by vlvkobal** [comment] 2021-01-29 07:59
It is a much more general problem than opentsdb exporting. It is related to data model redesign - metrics naming and labeling in our database.

**Comment by ilyam8** [comment] 2021-07-19 15:00
Closing this feature request. We will re-evaluate the request internally.

**Closed by ilyam8** 2021-07-19 15:00 UTC
Labels: area/daemon, area/exporting, feature request, priority/medium
