### ISSUE TITLE
specification for the Netdata master

### ISSUE THREAD

**Issue by hamzash9500** [netdata/netdata#11395] opened 2021-08-04 08:07 UTC
Hello All,

I have a plan to monitor more than 200 devices using the Netdata but I have some concerns and questions:

1) what is the specification for the Netdata master needed to handle more than 200 clients.

2)Is there an equation to calculate the CPU, RAM, and bandwidth needed for Netdata master.

Thanks in advance.

**Comment by ilyam8** [comment] 2021-08-04 17:01
Hey, @hamzash9500. That is not a bug, closing in favor of https://community.netdata.cloud/t/specification-for-the-netdata-master/1596

**Closed by ilyam8** 2021-08-04 17:01 UTC
Labels: bug, needs triage, question
