### ISSUE TITLE
netdata 1.23.0 alerts are not redirecting to local registry

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9439] opened 2020-06-29 06:26 UTC
##### Bug report summary

After updating our parents to version `1.23.0`, when I click on the alert, It won't take me to the local netdata registry, it will take me to `app.netdata.cloud` instead. 
I only have this problem on alerts, inside the netdata dashboard, I can click on the visited nodes without any problem so the registry is working file.
Here is my `netdata.conf` in parent servers:
```
[registry]
        enabled = no
        registry to announce = http://172.16.76.5:19999
```

##### Netdata version

v1.23.0

##### Component Name

health

##### Expected behavior

Clicking on the alert should take me to the local registry server like before

**Comment by ilyam8** [comment] 2020-06-29 07:17
seem duplicate of https://github.com/netdata/netdata/issues/9427

fix is https://github.com/netdata/netdata/issues/9427

**Closed by ilyam8** 2020-06-29 07:17 UTC
Labels: area/health, area/registry, bug, duplicate

**Comment by ilyam8** [comment] 2020-06-29 11:28
@yasharne the issue should be fixed in master
