### ISSUE TITLE
[Bug]: Relative queries return old data

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12314] opened 2022-03-03 18:07 UTC
### Bug description

When we call `/api/v1/data` with a relative timeframe (e.g. `before=0` and `after=-600` to show the last 10 minutes), the agent responds with the relative timeframe against the last time a chart was collected.

This means that:

1. for charts that are currently being collected, the agent responds with the last 10 minutes.
2. for charts that are no longer being collected, the agent responds with 10 minutes of data, relative to the time the chart was last collected.

This makes things on the dashboard very confusing. Charts are not always aligned and if a chart failed to be updated recently the user accidentally sees stale data on the charts (the x-axis is right, but still the user needs to pay attention to notice it).

### Expected behavior

When we ask data for the last 10 minutes, the duration of the data returned should be of the last 10 minutes, independently of the whether the chart stopped being collected.

### Steps to reproduce

1. Start a container
2. Wait a few minutes for netdata to gather some data
3. Stop the container
4. Wait a few minutes
5. refresh the agent dashboard
6. the container charts do not have a gap at the end of the chart. They feel "recent".

### Installation method

kickstart.sh

### System info

```shell
N/A
```

### Netdata build info

```shell
N/A
```

**Comment by stelfrag** [comment] 2022-03-03 20:44
This will generate "null" values as needed.

**Comment by stelfrag** [comment] 2022-03-03 20:54
Sample --- chart stopped being collected at 1646340628

Query executed `http://127.0.0.1:19999/api/v1/data?chart=system.cpu&after=-30&options=jsonwrap`

```
{
   "api": 1,
   "id": "system.cpu",
   "name": "system.cpu",
   "view_update_every": 1,
   "update_every": 1,
   "first_entry": 1645688032,
   "last_entry": 1646340628,
   "before": 1646340652,
   "after": 1646340623,
   "dimension_names": ["user", "system", "steal", "softirq", "nice", "irq", "iowait", "idle", "guest_nice", "guest"],
   "dimension_ids": ["user", "system", "steal", "softirq", "nice", "irq", "iowait", "idle", "guest_nice", "guest"],
   "latest_values": [null, null, null, null, null, null, null, null, null, null],
   "view_latest_values": [null, null, null, null, null, null, null, null, null, null],
   "dimensions": 10,
   "points": 30,
   "format": "json",
   "result": {
 "labels": ["time", "user", "system", "steal", "softirq", "nice", "irq", "iowait", "idle", "guest_nice", "guest"],
    "data":
 [
      [ 1646340652, null, null, null, null, null, null, null, null, null, null],
      [ 1646340651, null, null, null, null, null, null, null, null, null, null],
      [ 1646340650, null, null, null, null, null, null, null, null, null, null],
      [ 1646340649, null, null, null, null, null, null, null, null, null, null],
      [ 1646340648, null, null, null, null, null, null, null, null, null, null],
      [ 1646340647, null, null, null, null, null, null, null, null, null, null],
      [ 1646340646, null, null, null, null, null, null, null, null, null, null],
      [ 1646340645, null, null, null, null, null, null, null, null, null, null],
      [ 1646340644, null, null, null, null, null, null, null, null, null, null],
      [ 1646340643, null, null, null, null, null, null, null, null, null, null],
      [ 1646340642, null, null, null, null, null, null, null, null, null, null],
      [ 1646340641, null, null, null, null, null, null, null, null, null, null],
      [ 1646340640, null, null, null, null, null, null, null, null, null, null],
      [ 1646340639, null, null, null, null, null, null, null, null, null, null],
      [ 1646340638, null, null, null, null, null, null, null, null, null, null],
      [ 1646340637, null, null, null, null, null, null, null, null, null, null],
      [ 1646340636, null, null, null, null, null, null, null, null, null, null],
      [ 1646340635, null, null, null, null, null, null, null, null, null, null],
      [ 1646340634, null, null, null, null, null, null, null, null, null, null],
      [ 1646340633, null, null, null, null, null, null, null, null, null, null],
      [ 1646340632, null, null, null, null, null, null, null, null, null, null],
      [ 1646340631, null, null, null, null, null, null, null, null, null, null],
      [ 1646340630, null, null, null, null, null, null, null, null, null, null],
      [ 1646340629, null, null, null, null, null, null, null, null, null, null],
      [ 1646340628, 2.255639, 1.0860485, 0, 0, 0, 0, 1.1695906, 94.6533, 0, 0.8354219],
      [ 1646340627, 4.25, 2.166667, 0, 0.1666667, 0, 0, 0.1666667, 92.5, 0, 0.75],
      [ 1646340626, 6.583333, 3, 0, 0, 0, 0, 1.3333333, 87.91667, 0, 1.1666667],
      [ 1646340625, 7.118928, 3.60134, 0, 0.0837521, 0, 0, 0.0837521, 87.68844, 0, 1.4237856],
      [ 1646340624, 6.144781, 2.609428, 0, 0.0841751, 0, 0, 1.010101, 89.14141, 0, 1.010101],
      [ 1646340623, 6.323777, 2.866779, 0, 0, 0, 0, 1.0118044, 88.44857, 0, 1.3490725]
  ]
},
 "min": 0,
 "max": 94.6533
}
```

**Comment by ktsaou** [comment] 2022-03-04 09:19
```sh
# curl 'http://localhost:19999/api/v1/data?chart=web_log_nginx.response_statuses&format=json&options=jsonwrap%7Cnonzero%7Cflip%7Cms&points=111&group=average&gtime=0&after=-900'
{
   "api": 1,
   "id": "web_log_nginx.response_statuses",
   "name": "web_log_nginx.response_statuses",
   "view_update_every": 8,
   "update_every": 1,
   "first_entry": 1646212113,
   "last_entry": 1646250899,
   "before": 1646250896,
   "after": 1646249993,
   "dimension_names": ["bad"],
   "dimension_ids": ["bad_requests"],
   "latest_values": [null],
   "view_latest_values": [0],
   "dimensions": 1,
   "points": 113,
   "format": "json",
   "result": {
 "labels": ["time", "bad"],
    "data":
 [
      [ 1646250000000, 0],
      [ 1646250008000, 0],
      [ 1646250016000, 0],
      [ 1646250024000, 0],
      [ 1646250032000, 0],
      [ 1646250040000, 0],
      [ 1646250048000, 0],
      [ 1646250056000, 0],
      [ 1646250064000, 0],
      [ 1646250072000, 0],
      [ 1646250080000, 0],
      [ 1646250088000, 0],
      [ 1646250096000, 0],
      [ 1646250104000, 0],
      [ 1646250112000, 0],
      [ 1646250120000, 0],
      [ 1646250128000, 0],
      [ 1646250136000, 0],
      [ 1646250144000, 0],
      [ 1646250152000, 0],
      [ 1646250160000, 0],
      [ 1646250168000, 0],
      [ 1646250176000, 0],
      [ 1646250184000, 0],
      [ 1646250192000, 0],
      [ 1646250200000, 0],
      [ 1646250208000, 0],
      [ 1646250216000, 0],
      [ 1646250224000, 0],
      [ 1646250232000, 0],
      [ 1646250240000, 0],
      [ 1646250248000, 0],
      [ 1646250256000, 0],
      [ 1646250264000, 0],
      [ 1646250272000, 0],
      [ 1646250280000, 0],
      [ 1646250288000, 0],
      [ 1646250296000, 0],
      [ 1646250304000, 0],
      [ 1646250312000, 0],
      [ 1646250320000, 0],
      [ 1646250328000, 0],
      [ 1646250336000, 0],
      [ 1646250344000, 0],
      [ 1646250352000, 0],
      [ 1646250360000, 0],
      [ 1646250368000, 0],
      [ 1646250376000, 0],
      [ 1646250384000, 0],
      [ 1646250392000, 0],
      [ 1646250400000, 0],
      [ 1646250408000, 0],
      [ 1646250416000, 0],
      [ 1646250424000, 0],
      [ 1646250432000, 0],
      [ 1646250440000, 0],
      [ 1646250448000, 0],
      [ 1646250456000, 0],
      [ 1646250464000, 0],
      [ 1646250472000, 0],
      [ 1646250480000, 0],
      [ 1646250488000, 0],
      [ 1646250496000, 0],
      [ 1646250504000, 0],
      [ 1646250512000, 0],
      [ 1646250520000, 0],
      [ 1646250528000, 0],
      [ 1646250536000, 0],
      [ 1646250544000, 0],
      [ 1646250552000, 0],
      [ 1646250560000, 0],
      [ 1646250568000, 0],
      [ 1646250576000, 0],
      [ 1646250584000, 0],
      [ 1646250592000, 0],
      [ 1646250600000, 0],
      [ 1646250608000, 0],
      [ 1646250616000, 0],
      [ 1646250624000, 0],
      [ 1646250632000, 0],
      [ 1646250640000, 0],
      [ 1646250648000, 0],
      [ 1646250656000, 0],
      [ 1646250664000, 0],
      [ 1646250672000, 0],
      [ 1646250680000, 0],
      [ 1646250688000, 0],
      [ 1646250696000, 0],
      [ 1646250704000, 0],
      [ 1646250712000, 0],
      [ 1646250720000, 0],
      [ 1646250728000, 0],
      [ 1646250736000, 0],
      [ 1646250744000, 0],
      [ 1646250752000, 0],
      [ 1646250760000, 0],
      [ 1646250768000, 0],
      [ 1646250776000, 0],
      [ 1646250784000, 0],
      [ 1646250792000, 0],
      [ 1646250800000, 0],
      [ 1646250808000, 0],
      [ 1646250816000, 0],
      [ 1646250824000, 0],
      [ 1646250832000, 0],
      [ 1646250840000, 0],
      [ 1646250848000, 0],
      [ 1646250856000, 0],
      [ 1646250864000, 0],
      [ 1646250872000, 0],
      [ 1646250880000, 1.5],
      [ 1646250888000, 0],
      [ 1646250896000, 0]
  ]
},
 "min": 0,
 "max": 1.5
}
```

and

Now is:

```sh
# date
Fri 04 Mar 2022 11:15:37 AM EET
```

`before` as returned in jsonwrap:

```sh
# date -d @1646250896
Wed 02 Mar 2022 09:54:56 PM EET
```

It returns stale data!

**Comment by erdem2000** [comment] 2022-03-07 18:27
Started working on it...

**Comment by erdem2000** [comment] 2022-03-07 19:27
When I check with the latest netdata agent commit ([297f02fee3e00205ab69ce2d67312fd043c38034](https://github.com/netdata/netdata/commit/297f02fee3e00205ab69ce2d67312fd043c38034)), it returns expected output for offline gaps like below :thinking:; 
 
![2022-03-07T22_03_21](https://user-images.githubusercontent.com/51407/157101322-1176dcfb-3871-4d75-ba33-090554b23563.png)
```
{
   "api": 1,
   "id": "system.cpu",
   "name": "system.cpu",
   "view_update_every": 1,
   "update_every": 1,
   "first_entry": 1646066206,
   "last_entry": 1646679478,
   "before": 1646679478,
   "after": 1646679379,
   "dimension_names": ["guest_nice", "guest", "steal", "softirq", "irq", "user", "system", "nice", "iowait"],
   "dimension_ids": ["guest_nice", "guest", "steal", "softirq", "irq", "user", "system", "nice", "iowait"],
   "latest_values": [0, 0, 0, 0, 0, 2.1052632, 2.1052632, 0, 0],
   "view_latest_values": [0, 0, 0, 0, 0, 2.105263, 2.105263, 0, 0],
   "dimensions": 9,
   "points": 100,
   "format": "json",
   "result": {
 "labels": ["time", "guest_nice", "guest", "steal", "softirq", "irq", "user", "system", "nice", "iowait"],
    "data":
 [
      [ 1646679478, 0, 0, 0, 0, 0, 2.105263, 2.105263, 0, 0],
      [ 1646679477, 0, 0, 0, 0, 0, 0, 2.040816, 0, 0],
      [ 1646679476, 0, 0, 0, 0, 0, 0, 3, 0, 0],
      [ 1646679475, 0, 0, 0, 1.010101, 0, 44.44444, 9.090909, 0, 1.010101],
      [ 1646679474, null, null, null, null, null, null, null, null, null],
      [ 1646679473, null, null, null, null, null, null, null, null, null],
      [ 1646679472, null, null, null, null, null, null, null, null, null],
      [ 1646679471, null, null, null, null, null, null, null, null, null],
      [ 1646679470, null, null, null, null, null, null, null, null, null],
      [ 1646679469, null, null, null, null, null, null, null, null, null],
      [ 1646679468, null, null, null, null, null, null, null, null, null],
      [ 1646679467, null, null, null, null, null, null, null, null, null],
      [ 1646679466, null, null, null, null, null, null, null, null, null],
      [ 1646679465, null, null, null, null, null, null, null, null, null],
      [ 1646679464, null, null, null, null, null, null, null, null, null],
      [ 1646679463, null, null, null, null, null, null, null, null, null],
      [ 1646679462, null, null, null, null, null, null, null, null, null],
      [ 1646679461, null, null, null, null, null, null, null, null, null],
      [ 1646679460, null, null, null, null, null, null, null, null, null],
      [ 1646679459, null, null, null, null, null, null, null, null, null],
      [ 1646679458, null, null, null, null, null, null, null, null, null],
      [ 1646679457, null, null, null, null, null, null, null, null, null],
      [ 1646679456, null, null, null, null, null, null, null, null, null],
      [ 1646679455, null, null, null, null, null, null, null, null, null],
      [ 1646679454, null, null, null, null, null, null, null, null, null],
      [ 1646679453, null, null, null, null, null, null, null, null, null],
      [ 1646679452, null, null, null, null, null, null, null, null, null],
      [ 1646679451, null, null, null, null, null, null, null, null, null],
      [ 1646679450, null, null, null, null, null, null, null, null, null],
      [ 1646679449, null, null, null, null, null, null, null, null, null],
      [ 1646679448, null, null, null, null, null, null, null, null, null],
      [ 1646679447, null, null, null, null, null, null, null, null, null],
      [ 1646679446, null, null, null, null, null, null, null, null, null],
      [ 1646679445, null, null, null, null, null, null, null, null, null],
      [ 1646679444, null, null, null, null, null, null, null, null, null],
      [ 1646679443, null, null, null, null, null, null, null, null, null],
      [ 1646679442, null, null, null, null, null, null, null, null, null],
      [ 1646679441, 0, 0, 0, 0, 0, 2.020202, 3.030303, 0, 0],
      [ 1646679440, 0, 0, 0, 0, 0, 1.0204082, 1.0204082, 0, 0],
      [ 1646679439, 0, 0, 0, 0, 0, 1.0204082, 1.0204082, 0, 0],
      [ 1646679438, 0, 0, 0, 0, 0, 0, 1.0204082, 0, 0],
      [ 1646679437, 0, 0, 0, 0, 0, 1.010101, 1.010101, 0, 0],
      [ 1646679436, 0, 0, 0, 0, 0, 0, 2, 0, 0],
      [ 1646679435, 0, 0, 0, 0, 0, 0, 2.020202, 0, 0],
      [ 1646679434, 0, 0, 0, 0, 0, 1, 1, 0, 0],
      [ 1646679433, 0, 0, 0, 0, 0, 0, 1.0204082, 0, 0],
      [ 1646679432, 0, 0, 0, 0, 0, 1, 1, 0, 0],
      [ 1646679431, 0, 0, 0, 0, 0, 0, 1.0204082, 0, 0],
      [ 1646679430, 0, 0, 0, 0, 0, 0, 1.010101, 0, 0],
      [ 1646679429, 0, 0, 0, 0, 0, 1.010101, 2.020202, 0, 1.010101],
      [ 1646679428, 0, 0, 0, 0, 0, 0, 1.0204082, 0, 0],
      [ 1646679427, 0, 0, 0, 0, 0, 0, 1.010101, 0, 0],
      [ 1646679426, 0, 0, 0, 0, 0, 1.010101, 1.010101, 0, 0],
      [ 1646679425, 0, 0, 0, 0, 0, 1.010101, 1.010101, 0, 0],
      [ 1646679424, 0, 0, 0, 0, 0, 1.010101, 2.020202, 0, 0],
      [ 1646679423, 0, 0, 0, 0, 0, 1.010101, 1.010101, 0, 0],
      [ 1646679422, 0, 0, 0, 0, 0, 0, 1.0204082, 0, 0],
      [ 1646679421, 0, 0, 0, 0, 0, 0, 1.0204082, 0, 1.0204082],
      [ 1646679420, 0, 0, 0, 0, 0, 0, 2, 0, 0],
      [ 1646679419, 0, 0, 0, 0, 0, 0, 1.0204082, 0, 0],
      [ 1646679418, 0, 0, 0, 0, 0, 0, 1.010101, 0, 0],
      [ 1646679417, 0, 0, 0, 0, 0, 0, 1.0204082, 0, 0],
      [ 1646679416, 0, 0, 0, 0, 0, 2, 1, 0, 0],
      [ 1646679415, 0, 0, 0, 0, 0, 1.0204082, 0, 0, 0],
      [ 1646679414, 0, 0, 0, 0, 0, 0, 2.020202, 0, 0],
      [ 1646679413, 0, 0, 0, 0, 0, 0, 1.010101, 0, 1.010101],
      [ 1646679412, 0, 0, 0, 1, 0, 36, 8, 0, 2],
      [ 1646679411, null, null, null, null, null, null, null, null, null],
      [ 1646679410, null, null, null, null, null, null, null, null, null],
      [ 1646679409, null, null, null, null, null, null, null, null, null],
      [ 1646679408, null, null, null, null, null, null, null, null, null],
      [ 1646679407, null, null, null, null, null, null, null, null, null],
      [ 1646679406, null, null, null, null, null, null, null, null, null],
      [ 1646679405, null, null, null, null, null, null, null, null, null],
      [ 1646679404, null, null, null, null, null, null, null, null, null],
      [ 1646679403, null, null, null, null, null, null, null, null, null],
      [ 1646679402, null, null, null, null, null, null, null, null, null],
      [ 1646679401, null, null, null, null, null, null, null, null, null],
      [ 1646679400, null, null, null, null, null, null, null, null, null],
      [ 1646679399, null, null, null, null, null, null, null, null, null],
      [ 1646679398, null, null, null, null, null, null, null, null, null],
      [ 1646679397, null, null, null, null, null, null, null, null, null],
      [ 1646679396, null, null, null, null, null, null, null, null, null],
      [ 1646679395, null, null, null, null, null, null, null, null, null],
      [ 1646679394, null, null, null, null, null, null, null, null, null],
      [ 1646679393, null, null, null, null, null, null, null, null, null],
      [ 1646679392, null, null, null, null, null, null, null, null, null],
      [ 1646679391, null, null, null, null, null, null, null, null, null],
      [ 1646679390, null, null, null, null, null, null, null, null, null],
      [ 1646679389, null, null, null, null, null, null, null, null, null],
      [ 1646679388, null, null, null, null, null, null, null, null, null],
      [ 1646679387, null, null, null, null, null, null, null, null, null],
      [ 1646679386, null, null, null, null, null, null, null, null, null],
      [ 1646679385, null, null, null, null, null, null, null, null, null],
      [ 1646679384, null, null, null, null, null, null, null, null, null],
      [ 1646679383, null, null, null, null, null, null, null, null, null],
      [ 1646679382, null, null, null, null, null, null, null, null, null],
      [ 1646679381, null, null, null, null, null, null, null, null, null],
      [ 1646679380, null, null, null, null, null, null, null, null, null],
      [ 1646679379, null, null, null, null, null, null, null, null, null]
  ]
},
 "min": 0,  
```
I first experienced `netdata `service was not stopped by the command `sudo systemctl stop netdata` so I got continuous data from the agent. Then I realized it does not stops working then I restarted the netdata VM and it is fixed. @ktsaou If I am not mistaken about reproducing the issue maybe this could be a reason for your experience? 

I am going on with figuring out **stale data** issue besides the topic above.

**Comment by erdem2000** [comment] 2022-03-08 07:25
I get expected result with stale data scenario, too. I am going to discuss with @stelfrag if I miss something to reproduce the issue and then take action to find root problem. 

``` 
curl 'http://localhost:19999/api/v1/data?chart=system.cpu&format=json&options=jsonwrap%7Cnonzero%7Cflip%7Cms&points=111&group=average&gtime=0&after=-900'
{
   "api": 1,
   "id": "system.cpu",
   "name": "system.cpu",
   "view_update_every": 8,
   "update_every": 1,
   "first_entry": 1646066206,
   "last_entry": 1646722609,
   "before": 1646722608,
   "after": 1646721705,
   "dimension_names": ["softirq", "user", "system", "iowait"],
   "dimension_ids": ["softirq", "user", "system", "iowait"],
   "latest_values": [0, 1.0204082, 1.0204082, 0],
   "view_latest_values": [0.125, 0.7576015, 1.6504851, 0],
   "dimensions": 4,
   "points": 113,
   "format": "json",
   "result": {
 "labels": ["time", "softirq", "user", "system", "iowait"],
    "data":
 [
      [ 1646721712000, 0, 0.5025252, 1.2613894, 0],
      [ 1646721720000, 0, 0.2538136, 1.3864152, 0],
      [ 1646721728000, 0, 0.375025, 1.2602283, 0],
      [ 1646721736000, 0, 0.5037879, 1.2563131, 0],
      [ 1646721744000, 0, 0.5050763, 1.135101, 0],
      [ 1646721752000, 0, 0.1262626, 1.265203, 0],
      [ 1646721760000, 0, 0.125, 1.2601783, 0],
      [ 1646721768000, 0, 0.5012626, 1.0076015, 0],
      [ 1646721776000, 0, 0.5025252, 1.1351268, 0],
      [ 1646721784000, 0, 0.6313131, 1.1377036, 0],
      [ 1646721792000, 0, 0.6351783, 1.0126778, 0],
      [ 1646721800000, 0, 0.6275252, 1.2614152, 0],
      [ 1646721808000, 0, 0.6300505, 1.2639404, 0],
      [ 1646721816000, 0, 0.2512626, 1.3876262, 0],
      [ 1646721824000, 0, 0.3775252, 1.387652, 0],
      [ 1646721832000, 0, 0.2512626, 1.3838642, 0],
      [ 1646721840000, 0, 0.375, 1.5050763, 0],
      [ 1646721848000, 0, 0.3762876, 0.877601, 0],
      [ 1646721856000, 0, 0.5025252, 1.0101525, 0],
      [ 1646721864000, 0, 0.3762626, 1.0088642, 0],
      [ 1646721872000, 0, 0.3788136, 1.1313647, 0],
      [ 1646721880000, 0, 0.3762626, 1.2602049, 0],
      [ 1646721888000, 0, 0.3762626, 1.1338641, 0.1262626],
      [ 1646721896000, 0, 0.5038137, 1.1313389, 0],
      [ 1646721904000, 0, 0.2512626, 1.6338899, 0],
      [ 1646721912000, 0, 0.3737624, 1.3878574, 0],
      [ 1646721920000, 0, 0.5025252, 1.1351268, 0],
      [ 1646721928000, 0, 0.3762626, 1.3851525, 0],
      [ 1646721936000, 0, 0.502576, 1.5077023, 0],
      [ 1646721944000, 0, 0.5037879, 1.2614151, 0],
      [ 1646721952000, 0, 0.3775252, 1.385101, 0],
      [ 1646721960000, 0, 0.6300763, 1.1326015, 0],
      [ 1646721968000, 0, 0.7538129, 0.8788894, 0],
      [ 1646721976000, 0, 0.5037879, 1.2601268, 0],
      [ 1646721984000, 0, 0.25, 1.2576015, 0],
      [ 1646721992000, 0, 0.6263369, 0.9989859, 0],
      [ 1646722000000, 0, 0.5012626, 1.2563389, 0],
      [ 1646722008000, 0, 0.5050763, 1.0088384, 0],
      [ 1646722016000, 0, 0.5025252, 0.8826015, 0],
      [ 1646722024000, 0, 0.4987874, 0.8813639, 0],
      [ 1646722032000, 0, 0.3788136, 1.1351525, 0],
      [ 1646722040000, 0, 0.2525252, 1.137652, 0],
      [ 1646722048000, 0, 0.2512626, 1.1338641, 0],
      [ 1646722056000, 0, 0.3762626, 1.1377036, 0],
      [ 1646722064000, 0, 0.5050763, 1.1338384, 0],
      [ 1646722072000, 0, 0.3788136, 1.2614152, 0],
      [ 1646722080000, 0, 0.5025252, 1.1351525, 0],
      [ 1646722088000, 0, 1.0114152, 0.7550763, 0],
      [ 1646722096000, 0, 0.50005, 1.0063889, 0],
      [ 1646722104000, 0, 0.25, 1.1376778, 0],
      [ 1646722112000, 0, 0.5025252, 1.1326015, 0],
      [ 1646722120000, 0, 0.4988382, 0.8802028, 0],
      [ 1646722128000, 0, 0.3775252, 1.0127036, 0],
      [ 1646722136000, 0, 0.3813647, 1.1326015, 0],
      [ 1646722144000, 0, 0.5076273, 1.3775252, 0],
      [ 1646722152000, 0, 0.5038137, 1.1351525, 0],
      [ 1646722160000, 0, 0.5012626, 1.2614409, 0],
      [ 1646722168000, 0, 0.2525252, 1.3888889, 0],
      [ 1646722176000, 0, 0.502576, 1.3877793, 0],
      [ 1646722184000, 0, 0.5037879, 1.1364152, 0],
      [ 1646722192000, 0, 0.25, 1.1338899, 0.125],
      [ 1646722200000, 0, 0.502576, 0.8763384, 0],
      [ 1646722208000, 0, 0.7550505, 0.8813131, 0],
      [ 1646722216000, 0, 0.377551, 0.8826015, 0],
      [ 1646722224000, 0, 0.2487624, 1.1302044, 0],
      [ 1646722232000, 0, 1.0089157, 1.2601783, 0],
      [ 1646722240000, 0, 0.6300505, 1.3877044, 0],
      [ 1646722248000, 0, 0.3775252, 1.2639404, 0],
      [ 1646722256000, 0, 0.2512626, 1.5126262, 0],
      [ 1646722264000, 0, 0.5025252, 1.2601525, 0],
      [ 1646722272000, 0, 0.6300763, 1.2614152, 0],
      [ 1646722280000, 0, 0.375025, 1.3801263, 0],
      [ 1646722288000, 0, 0.505127, 1.1314147, 0],
      [ 1646722296000, 0, 0.6288386, 1.2489389, 0],
      [ 1646722304000, 0, 0.6288137, 1.1338641, 0],
      [ 1646722312000, 0, 0.3762626, 1.2626778, 0],
      [ 1646722320000, 0, 0.2512626, 1.387652, 0],
      [ 1646722328000, 0, 0.2512626, 1.1313389, 0],
      [ 1646722336000, 0, 0.378866, 1.5113636, 0],
      [ 1646722344000, 0, 0.3775252, 1.0076015, 0],
      [ 1646722352000, 0, 0.1237624, 1.2564139, 0],
      [ 1646722360000, 0, 0.375025, 1.2576773, 0],
      [ 1646722368000, 0, 0.6288136, 1.6428588, 0],
      [ 1646722376000, 0.127551, 1.5308762, 1.9110056, 0],
      [ 1646722384000, 0, 1.2796975, 1.5242508, 0],
      [ 1646722392000, 0.125, 1.6326273, 2.0164914, 0],
      [ 1646722400000, 0, 0.6300505, 1.3889404, 0],
      [ 1646722408000, 0, 1.0114917, 2.0115917, 0],
      [ 1646722416000, 0, 0.6313389, 1.385101, 0.1262626],
      [ 1646722424000, 0, 1.5203832, 1.5216458, 0.127551],
      [ 1646722432000, 0, 0.7576273, 1.5178055, 0],
      [ 1646722440000, 0, 0.6301536, 0.87505, 0],
      [ 1646722448000, 0, 0.3762626, 1.2550505, 0],
      [ 1646722456000, 0, 0.5038137, 1.1351783, 0.1262626],
      [ 1646722464000, 0, 0.5025252, 1.2601525, 0],
      [ 1646722472000, 0, 0.25, 1.3864152, 0],
      [ 1646722480000, 0, 0.3788136, 1.0114152, 0],
      [ 1646722488000, 0, 0.6300505, 1.1363894, 0.1262626],
      [ 1646722496000, 0, 0.5012626, 1.2614409, 0],
      [ 1646722504000, 0, 0.3762626, 1.2601268, 0.127551],
      [ 1646722512000, 0, 0.7563131, 1.1363894, 0],
      [ 1646722520000, 0, 0.7576538, 1.6441472, 0],
      [ 1646722528000, 0, 0.5012626, 1.5088899, 0],
      [ 1646722536000, 0, 0.5050505, 1.1363636, 0],
      [ 1646722544000, 0, 0.5050763, 1.1351525, 0],
      [ 1646722552000, 0, 0.8826015, 1.2639662, 0],
      [ 1646722560000, 0, 0.5063912, 1.3851268, 0],
      [ 1646722568000, 0, 0.7576273, 2.1389146, 0],
      [ 1646722576000, 0, 0.6338899, 1.137652, 0],
      [ 1646722584000, 0, 0.8788136, 2.0140442, 0],
      [ 1646722592000, 0, 0.2512626, 1.1351268, 0],
      [ 1646722600000, 0, 0.375, 1.1338641, 0],
      [ 1646722608000, 0.125, 0.7576015, 1.6504851, 0]
  ]
},
 "min": 0,
 "max": 2.1389146
}

date
Sal 08 Mar 2022 09:56:57 +03
date -d @1646722608
Sal 08 Mar 2022 09:56:48 +03
git log -1
commit 297f02fee3e00205ab69ce2d67312fd043c38034 (HEAD -> master, origin/master, origin/HEAD)

```

**Comment by ktsaou** [comment] 2022-03-08 07:38
I think it is here:

https://github.com/netdata/netdata/blob/d8b7b6a25f7fc0ec4d79a7f8a72c779e3bf4afd7/web/api/queries/query.c#L761-L831

**Comment by stelfrag** [comment] 2022-03-08 19:07
> I think it is here:
> 
> https://github.com/netdata/netdata/blob/d8b7b6a25f7fc0ec4d79a7f8a72c779e3bf4afd7/web/api/queries/query.c#L790-L793

@erdem2000 This is the start of it -- line 791

- Start an agent and let it run a few minutes
- Execute http://127.0.0.1:19999/api/v1/data?chart=system.cpu&after=-30&options=jsonwrap and see that you get the latest data as they are collected
- Stop the agent
  - Go to netdata.conf  `[plugins]` and set `proc = no` 
 - Start the agent and do http://127.0.0.1:19999/api/v1/data?chart=system.cpu&after=-30&options=jsonwrap

You will be getting stale data (relative to the last collected)

**Comment by erdem2000** [comment] 2022-03-10 11:55
Thank both of you for the detail info which helped a lot to figure out the root problem.

I created a PR to fix the issue, but there is also another scenario which can be an issue related with this topic. This bug is subjecting the timeline after last entry and we only check "after" parameter with first entry currently. 
**Should we also consider the timeline before the first entry (obviously there will be no metrics)?** Because if there is a query which requests the metrics before the first entry the relative point will be first entry.

Example scenario:
- Start netdata service at t = 0. second
- Run the query below at t = 50. second 
 http://127.0.0.1:19999/api/v1/data?chart=disk.sda&after=-60&options=jsonwrap
- It responds with 50 metrics currently, but if we remove first entry conditionals in the code like the fix for this bug it returns 60 metrics (first 10 would be null)

**As a summary, should we leave the code as it is or change behavior like the example scenario?**

**Comment by ktsaou** [comment] 2022-03-10 12:17
Thank you @erdem2000 .

I think the timestamps of the data should not be considered at all.

What an absolute query currently does? So, if I request a absolute time-frame for `t1` to `t2`, does it return `null` even if `first_t` is after the absolute `after` parameter wanted?

Generally, relative and absolute queries should behave exactly the same for the same timeframe.

**Comment by stelfrag** [comment] 2022-03-10 12:24
> * It responds with 50 metrics currently, but if we remove first entry conditionals in the code like the fix for this bug it returns 60 metrics (first 10 would be null)

There is an option `allow_past` that will do that (return null for the missing entries before that first_t)

**Comment by stelfrag** [comment] 2022-06-17 09:42
Fix applied

**Closed by stelfrag** 2022-06-17 09:42 UTC
Labels: bug, area/database
