### ISSUE TITLE
Netdata Installation failed in Manjaro（Arch）Latest

### ISSUE THREAD

**Issue by CallMeR** [netdata/netdata#2812] opened 2017-09-27 09:28 UTC
When I tried  to install Netdata in Manjaro 17.05,It shows me an err:
 "error: failed to prepare transaction (conflicting dependencies)  :: gcc-libs and gcc-libs-multilib are in conflict".
But I've been installed gcc-multilib instead before,and I can't just remove gcc-libs-multilib.
How could I fix this err？

**Comment by Aitkots** [comment] 2017-09-27 09:44
By useing command：
`curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all`

**Comment by ktsaou** [comment] 2017-09-27 11:14
Could you please post all the output of `bash /tmp/kickstart.sh -i netdata-all` ?

**Comment by Aitkots** [comment] 2017-09-28 00:43
sure：
`Loading /etc/os-release ...
Unknown distribution ID: manjaro
Cannot find valid distribution in: manjaro 
Loading /etc/lsb-release ...

We detected these:
Distribution    : ManjaroLinux
Version         : 17.0.5
Codename        : Gellivara
Package Manager : install_pacman
Packages Tree   : arch
Detection Method: /etc/lsb-release
Default Python v: 2 


The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:  sudo pacman -Syu  

sudo pacman --needed -S autoconf autoconf-archive autogen automake curl gcc git libmnl lm_sensors make mysql-python netcat nodejs pkgconfig python python2-psycopg2 python2-yaml util-linux zlib 


Press ENTER to run it > 
sudo pacman --needed -S autoconf autoconf-archive autogen automake curl gcc git libmnl lm_sensors make mysql-python netcat nodejs pkgconfig python python2-psycopg2 python2-yaml util-linux zlib 
warning: autoconf-2.69-4 is up to date -- skipping
warning: autoconf-archive-1:2017.03.21-1 is up to date -- skipping
warning: autogen-5.18.12-2 is up to date -- skipping
warning: automake-1.15.1-1 is up to date -- skipping
warning: curl-7.55.1-2 is up to date -- skipping
warning: git-2.14.1-1 is up to date -- skipping
warning: libmnl-1.0.4-1 is up to date -- skipping
warning: lm_sensors-3.4.0-2 is up to date -- skipping
warning: make-4.2.1-2 is up to date -- skipping
warning: mysql-python-1.2.5-1 is up to date -- skipping
warning: gnu-netcat-0.7.1-6 is up to date -- skipping
warning: nodejs-8.5.0-1 is up to date -- skipping
warning: pkg-config-0.29.2-1 is up to date -- skipping
warning: python-3.6.2-1 is up to date -- skipping
warning: python2-psycopg2-2.7.3.1-1 is up to date -- skipping
warning: python2-yaml-3.12-2 is up to date -- skipping
warning: util-linux-2.30.1-2 is up to date -- skipping
warning: zlib-1:1.2.11-2 is up to date -- skipping
resolving dependencies...
looking for conflicting packages...
:: gcc-libs and gcc-libs-multilib are in conflict. Remove gcc-libs-multilib? [y/N] y
:: gcc and gcc-multilib are in conflict. Remove gcc-multilib? [y/N] y

Packages (4) gcc-libs-7.2.0-3  gcc-libs-multilib-7.2.0-1 [removal]  gcc-multilib-7.2.0-1 [removal]  gcc-7.2.0-3

Total Download Size:    46.72 MiB
Total Installed Size:  207.48 MiB
Net Upgrade Size:       -8.65 MiB

:: Proceed with installation? [Y/n] n



We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues

`
And the gcc-libs-multilib is seems like a system-level dependency：
`sudo pacman -Rscn gcc-libs-multilib 
正在检查依赖关系...
警告：检测到依赖关系环：
警告：harfbuzz 将在它 freetype2 的依赖关系之后被删除
警告：检测到依赖关系环：
警告：libglvnd 将在它 mesa 的依赖关系之后被删除
警告：检测到依赖关系环：
警告：lib32-libglvnd 将在它 lib32-mesa 的依赖关系之后被删除
警告：检测到依赖关系环：
警告：lib32-harfbuzz 将在它 lib32-freetype2 的依赖关系之后被删除
警告：检测到依赖关系环：
警告：usbmuxd 将在它 libimobiledevice 的依赖关系之后被删除
警告：检测到依赖关系环：
警告：manjaro-gnome-extension-settings 将在它 manjaro-gnome-settings 的依赖关系之后被删除
警告：manjaro-system 被指定为 HoldPkg (保留软件包) 。
警告：pacman 被指定为 HoldPkg (保留软件包) 。
:: 在目标清单中发现 HoldPkg 指定的软件包。你确定要继续吗？ [y/N] n
`

**Comment by Aitkots** [comment] 2017-09-28 00:46
And the default Python version is 3.6.2，not“2”...

**Comment by ktsaou** [comment] 2017-09-29 20:48
ok,

this is what netdata runs:

```
sudo pacman --needed -S autoconf autoconf-archive autogen automake curl gcc git libmnl lm_sensors make mysql-python netcat nodejs pkgconfig python python2-psycopg2 python2-yaml util-linux zlib
```

As you can see there is nothing in this about multilib. Unfortunately I don't know how to fix this problem. I suggest to seek help at the manjaro or arch forums.

I personally use manjaro, and I don't have this problem. So, this is something triggered by the packages you have already installed.

If you have a working gcc in place, I think you can just `git clone` the repo and run `./netdata-installer.sh` from it. If your gcc works, it will be installed.

If you don't have a working gcc, netdata can also be compiled with `clang`. Run `export CC=clang` before running `./netdata-installer.sh` and the installer will use clang.



> And the default Python version is 3.6.2，not“2”...

To detect the python version, the [script runs](https://github.com/firehol/netdata-demo-site/blob/4301df6d6fd7426e5aaa54a3ef3bf9f7e537f23b/install-required-packages.sh#L1524-L1534) `python --version`.  Could you please post the output of this command?

**Comment by l2isbad** [comment] 2017-09-30 01:07
i am manjaro too and have the same problem (never installed netdata via kickstart.sh before)

> If you have a working gcc in place, I think you can just git clone the repo and run ./netdata-installer.sh from it. If your gcc works, it will be installed.

Works!

**Comment by Aitkots** [comment] 2017-09-30 02:55
I think it's about the "gcc" ,manjaro has installed the gcc-libs-multilib by default...
And 
`$ python --version`
`Python 3.6.2 :: Anaconda, Inc.`

**Comment by ktsaou** [comment] 2017-09-30 23:27
fixed the python detection problem.

Any ideas how to fix the gcc issue?

**Comment by Aitkots** [comment] 2017-10-01 06:34
Add some gcc,gcc-multilib,clang detection?

**Comment by ktsaou** [comment] 2017-10-01 07:18
Well, this is what it does: https://github.com/firehol/netdata-demo-site/blob/55a18028775684b2ac6b418e715e34210fb14774/install-required-packages.sh#L968

It attempts to install gcc, only if it is not already there.

You say the binary is called `gcc-mutlilib` and not `gcc`?

**Comment by l2isbad** [comment] 2017-10-01 08:02
```
pacman --query --search gcc
local/gcc-libs-multilib 7.2.0-1
    Runtime libraries shipped by GCC for multilib
local/gcc-multilib 7.2.0-1 (multilib-devel)
    The GNU Compiler Collection - C and C++ frontends for multilib
local/lib32-gcc-libs 7.2.0-1
    Runtime libraries shipped by GCC (32-bit)
```

**Comment by ktsaou** [comment] 2017-10-01 08:25
Could you please try it now?

**Comment by l2isbad** [comment] 2017-10-01 08:37
```
resolving dependencies...
looking for conflicting packages...
:: gcc-libs and gcc-libs-multilib are in conflict. Remove gcc-libs-multilib? [y/N] ^C
Interrupt signal received

```

**Comment by ktsaou** [comment] 2017-10-01 08:39
Could you please post the `pacman` command generated?

**Comment by l2isbad** [comment] 2017-10-01 08:43
```
Press ENTER to run it > 
sudo pacman --needed -S autoconf autoconf-archive autogen automake curl gcc git libmnl lm_sensors make mysql-python netcat nodejs pkgconfig python python-psycopg2 python-yaml python2-psycopg2 python2-yaml python3 util-linux zlib
```

**Comment by ktsaou** [comment] 2017-10-01 08:47
strange... it is like it cannot find any command...

Could you please post your version of this:

```sh
# ./install-required-packages.sh netdata
Loading /etc/os-release ...

/etc/os-release information:
NAME            : Fedora
VERSION         : 26 (Workstation Edition)
ID              : fedora
ID_LIKE         : 
VERSION_ID      : 26

We detected these:
Distribution    : fedora
Version         : 26
Codename        : 26 (Workstation Edition)
Package Manager : install_dnf
Packages Tree   : rhel
Detection Method: /etc/os-release
Default Python v: 2 

 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'zlib-devel' is installed...
 > Checking if package 'libuuid-devel' is installed...
 > Checking if package 'libmnl-devel' is installed...
 > Checking if package 'PyYAML' is installed...

All required packages are already installed. Now proceed to the next step.
```

**Comment by l2isbad** [comment] 2017-10-01 09:06
```
Loading /etc/os-release ...
Unknown distribution ID: manjaro
Cannot find valid distribution in: manjaro 
Loading /etc/lsb-release ...

We detected these:
Distribution    : ManjaroLinux
Version         : 17.0.5
Codename        : Gellivara
Package Manager : install_pacman
Packages Tree   : arch
Detection Method: /etc/lsb-release
Default Python v: 3 

WARNING
package python3-mysqldb is not available in this system.
You may try to install without it.


The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   pacman -Syu  

pacman --needed -S autoconf autoconf-archive autogen automake curl gcc git libmnl lm_sensors make mysql-python netcat nodejs pkgconfig python python-psycopg2 python-yaml python2-psycopg2 python2-yaml python3 util-linux zlib
```

**Comment by ktsaou** [comment] 2017-10-01 09:54
ok, this is really strange...

This is my manjaro:

```sh
$ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version: 4
 --- Downloading script to detect required packages... --- 
$ /usr/bin/curl https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40648  100 40648    0     0  40648      0  0:00:01 --:--:--  0:00:01 62631
 OK   

 --- Running downloaded script to detect required packages... --- 
$ sudo /usr/bin/bash /tmp/netdata-kickstart-5QWBts netdata 
Loading /etc/os-release ...
Unknown distribution ID: manjaro
Cannot find valid distribution in: manjaro 
Loading /etc/lsb-release ...

We detected these:
Distribution    : ManjaroLinux
Version         : 17.0.5
Codename        : Gellivara
Package Manager : install_pacman
Packages Tree   : arch
Detection Method: /etc/lsb-release
Default Python v: 3 

 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'zlib' is installed...
 > Checking if package 'util-linux' is installed...
 > Checking if package 'libmnl' is installed...
 > Checking if package 'python2-yaml' is installed...
 > Checking if package 'python-yaml' is installed...

All required packages are already installed. Now proceed to the next step.

 OK   
```

Could you please check if option `-i` is passed to `/usr/bin/bash /tmp/netdata-kickstart-XXXXX` ?

**Comment by l2isbad** [comment] 2017-10-01 10:12
no problems without -i

```
/usr/bin/bash /tmp/netdata-kickstart-jR8YGf netdata
Loading /etc/os-release ...
Unknown distribution ID: manjaro
Cannot find valid distribution in: manjaro 
Loading /etc/lsb-release ...

We detected these:
Distribution    : ManjaroLinux
Version         : 17.0.5
Codename        : Gellivara
Package Manager : install_pacman
Packages Tree   : arch
Detection Method: /etc/lsb-release
Default Python v: 3 

 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'autogen' is installed...
 > Checking if package 'zlib' is installed...
 > Checking if package 'util-linux' is installed...
 > Checking if package 'libmnl' is installed...
 > Checking if package 'python2-yaml' is installed...
 > Checking if package 'python-yaml' is installed...

The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:  sudo pacman -Syu  

sudo pacman --needed -S autogen python2-yaml 


Press ENTER to run it >
```

And all python2 packages should be excluded if version is 3

**Comment by ktsaou** [comment] 2017-10-01 10:42
> Could you please check if option -i is passed to /usr/bin/bash /tmp/netdata-kickstart-XXXXX ?

but did it run with `-i` ?

**Comment by Aitkots** [comment] 2017-10-01 11:28
With the fully fresh installed Manjaro , it's also gives me the conflict about gcc-libs and gcc-libs-multilib...
I've been use the "manjaro-gnome-17.0.5-stable-x86_64.iso" to install the Manjaro...

**Comment by l2isbad** [comment] 2017-10-01 11:31
It runs.

```
/usr/bin/bash /tmp/kickstart.sh -i netdata
Loading /etc/os-release ...
Unknown distribution ID: manjaro
Cannot find valid distribution in: manjaro 
Loading /etc/lsb-release ...

We detected these:
Distribution    : ManjaroLinux
Version         : 17.0.5
Codename        : Gellivara
Package Manager : install_pacman
Packages Tree   : arch
Detection Method: /etc/lsb-release
Default Python v: 3 


The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:  sudo pacman -Syu  

sudo pacman --needed -S autoconf autoconf-archive autogen automake curl gcc git libmnl make netcat pkgconfig python python-yaml python2-yaml python3 util-linux zlib 


Press ENTER to run it > ^C
```

**Comment by ktsaou** [comment] 2017-10-01 17:34
@l2isbad in my version (check above for the log), it runs without `-i`:

```
sudo /usr/bin/bash /tmp/netdata-kickstart-5QWBts netdata 
```

Are you sure on your manjaro, the kickstart script adds `-i` ?

**Comment by Aitkots** [comment] 2017-10-01 19:35
@ktsaou  I am useing the Gnome as my desktop environment，are you the same ...?

**Comment by ktsaou** [comment] 2017-10-01 21:43
> @ktsaou I am useing the Gnome as my desktop environment，are you the same ...?

This is not related. It seems your Manjaro have multilib installed, while mine does not.
I think the key question here what triggers the kickstart script to ignore the installed packages.

If you can post an entire session of `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`, I might be able to spot it. Could you please do this for me?

**Comment by l2isbad** [comment] 2017-10-01 22:47
i copied the command from https://github.com/firehol/netdata/issues/2812#issuecomment-332468521 when i checked.

`bash <(curl -Ss https://my-netdata.io/kickstart.sh)` does not add anything

**Comment by ktsaou** [comment] 2017-10-04 06:27
I need to reproduce this. I can't figure out how the script makes the wrong decision.

I will install a manjaro on a VM. How can I enable multilib?

**Comment by ktsaou** [comment] 2017-10-12 19:40
I just installed manjaro 17.05 on a VM. I updated it and then run this:

```
$ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version: 4
 --- Downloading script to detect required packages... --- 
[/home/costa]$ /usr/bin/curl https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40942  100 40942    0     0  40942      0  0:00:01 --:--:--  0:00:01 53379
 OK   

 --- Running downloaded script to detect required packages... --- 
[/home/costa]$ sudo /usr/bin/bash /tmp/netdata-kickstart-UCO13f netdata 
[sudo] password for costa: 
Loading /etc/os-release ...
Unknown distribution ID: manjaro
Cannot find valid distribution in: manjaro 
Loading /etc/lsb-release ...

We detected these:
Distribution    : ManjaroLinux
Version         : 17.0.5
Codename        : Gellivara
Package Manager : install_pacman
Packages Tree   : arch
Detection Method: /etc/lsb-release
Default Python v: 3 

 > Checking if package 'autoconf-archive' is installed...
 > Checking if package 'autogen' is installed...
 > Checking if package 'netcat' is installed...
 > Checking if package 'zlib' is installed...
 > Checking if package 'util-linux' is installed...
 > Checking if package 'libmnl' is installed...
 > Checking if package 'python2-yaml' is installed...
 > Checking if package 'python-yaml' is installed...

The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   pacman -Syu  

pacman --needed -S autoconf-archive autogen netcat python2-yaml 


Press ENTER to run it > ^C
```

It does not try to install gcc, since it is already installed.

I checked if multilib is installed:

```
$ pacman -Sl multilib | grep installed
multilib gcc-libs-multilib 7.2.0-1 [installed]
multilib gcc-multilib 7.2.0-1 [installed]
```

It is. Cannot reproduce the problem you face. Any ideas what to check?

**Comment by Aitkots** [comment] 2017-10-13 01:02
Seems like “gcc” is gone...

**Comment by ktsaou** [comment] 2018-11-19 08:36
I think this issue has been fixed.
If you still have problems, just post here and we will try to fix it.

**Closed by ktsaou** 2018-11-19 08:36 UTC
Labels: bug
