### ISSUE TITLE
Non-root Docker -> no Docker containers CPU+Memory

### ISSUE THREAD

**Issue by schklom** [netdata/netdata#11069] opened 2021-04-30 03:19 UTC
##### Bug report summary
The webpage doesn't include any information on Docker containers

##### OS / Environment

```
$ uname -a; grep -Hv "^#" /etc/*release
Linux <REDACTED> 5.10.0-0.bpo.5-arm64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) aarch64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

```
netdata v1.30.1-112-nightly
```
##### Installation method

Docker
##### Component Name

CPUs
Memory

I can see the CPU utilization of Docker processes, but there is no general list of containers where I can see CPU and Memory use.
##### Steps To Reproduce

1. Install [Rootless Docker](https://docs.docker.com/engine/security/rootless/#install) without packages
2. docker-compose.yml
```
  netdata:
    image: netdata/netdata
    container_name: netdata
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - TZ=${TZ}
      - DOCKER_USR=root
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERDATA}/netdata/config:/etc/netdata
      - ${DOCKERDATA}/netdata/lib:/var/lib/netdata
      - ${DOCKERDATA}/netdata/cache:/var/cache/netdata
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /run/user/1001/docker.sock:/var/run/docker.sock
    ports:
      - 19999:19999
```

##### Expected behavior

As with regular (Rootful) Docker, I expect to see the list of containers along with their CPU and Memory use.

**Comment by Conna576** [comment] 2021-04-30 06:46
Thank you.  I don't understand it all, I just know I got hacked a very long
time ago.  Now & then, something weired happens to phone I try Investigate
it

Thank you
Suzi

**Comment by ilyam8** [comment] 2021-05-07 15:40
Hi @schklom 👋 

> As with regular (Rootful) Docker

[That is default](https://learn.netdata.cloud/docs/agent/packaging/docker#create-a-new-netdata-agent-container). It supposed to be working when running as a non-root user.

---

Could you show (restart netdata docker container; wait ~30s)

```
# assuming the container name is netdata
docker logs netdata 2>&1 | grep -i cgroup

mount | grep cgroup
```

**Comment by schklom** [comment] 2021-05-07 16:17
@ilyam8 Hi 👋 

Here are the results
```
$ docker logs netdata 2>&1 | grep -i cgroup
2021-05-07 16:13:04: netdata INFO  : PLUGIN[cgroups] : thread created with task id 105
2021-05-07 16:13:04: netdata INFO  : PLUGIN[cgroups] : set name of thread 105 to PLUGIN[cgroups]
2021-05-07 16:13:04: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'START' '-' '-' 'false' '"dbengine"' 'false' 'null' 'null' 'null' 'null' 'null' 'null' 'null' '"dbengine|Native HTTPS|Netdata Cloud|TLS Host Verification|JSON-C|libcrypto|libm|LWS v3.2.2|mosquitto|zlib|apps|cgroup Network Tracking|IPMI|perf|slabinfo|MongoDB|Prometheus Remote Write"' '32' '256' 'true' 'true' '"stable"' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null' 'null'
2021-05-07 16:13:07: netdata ERROR : PLUGIN[cgroups] : child pid 185 exited with code 127.
2021-05-07 16:13:08: netdata ERROR : PLUGIN[cgroups] : child pid 208 exited with code 127.
2021-05-07 16:13:08: netdata INFO  : PLUGIN[cgroups] : use unified cgroups false

$ mount | grep cgroup
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
```

**Comment by ilyam8** [comment] 2021-05-07 16:22
Let's see `tree -d /sys/fs/cgroup/`

**Comment by schklom** [comment] 2021-05-07 16:36
```
$ docker-compose up -d netdata && sleep 30 && tree -d /sys/fs/cgroup/
/sys/fs/cgroup/
├── blkio
├── cpu -> cpu,cpuacct
├── cpu,cpuacct
├── cpuacct -> cpu,cpuacct
├── cpuset
├── devices
│   ├── machine.slice
│   ├── system.slice
│   │   ├── boot-firmware.mount
│   │   ├── cron.service
│   │   ├── dbus.service
│   │   ├── dev-hugepages.mount
│   │   ├── dev-mqueue.mount
│   │   ├── exim4.service
│   │   ├── fail2ban.service
│   │   ├── networking.service
│   │   ├── rsyslog.service
│   │   ├── ssh.service
│   │   ├── sys-fs-fuse-connections.mount
│   │   ├── sys-kernel-debug.mount
│   │   ├── system-container\x2dshell.slice
│   │   ├── system-getty.slice
│   │   ├── system-serial\x2dgetty.slice
│   │   ├── system-systemd\x2dfsck.slice
│   │   ├── systemd-journald.service
│   │   ├── systemd-logind.service
│   │   ├── systemd-machined.service
│   │   ├── systemd-timesyncd.service
│   │   ├── systemd-udevd.service
│   │   ├── unattended-upgrades.service
│   │   └── wpa_supplicant.service
│   └── user.slice
├── freezer
├── hugetlb
├── memory
│   ├── machine.slice
│   ├── system.slice
│   │   ├── boot-firmware.mount
│   │   ├── cron.service
│   │   ├── dbus.service
│   │   ├── dev-hugepages.mount
│   │   ├── dev-mqueue.mount
│   │   ├── exim4.service
│   │   ├── fail2ban.service
│   │   ├── networking.service
│   │   ├── rsyslog.service
│   │   ├── ssh.service
│   │   ├── sys-fs-fuse-connections.mount
│   │   ├── sys-kernel-debug.mount
│   │   ├── system-container\x2dshell.slice
│   │   │   └── container-shell@2.service
│   │   ├── system-getty.slice
│   │   │   └── getty@tty1.service
│   │   ├── system-serial\x2dgetty.slice
│   │   │   └── serial-getty@ttyS1.service
│   │   ├── system-systemd\x2dfsck.slice
│   │   ├── systemd-journald.service
│   │   ├── systemd-logind.service
│   │   ├── systemd-machined.service
│   │   ├── systemd-timesyncd.service
│   │   ├── systemd-udevd.service
│   │   ├── unattended-upgrades.service
│   │   └── wpa_supplicant.service
│   └── user.slice
│       ├── user-0.slice
│       │   ├── session-c2.scope
│       │   ├── session-c3.scope
│       │   └── user@0.service
│       │       └── dbus.socket
│       └── user-1001.slice
│           ├── session-125.scope
│           └── user@1001.service
├── net_cls -> net_cls,net_prio
├── net_cls,net_prio
├── net_prio -> net_cls,net_prio
├── perf_event
├── pids
│   ├── machine.slice
│   ├── system.slice
│   │   ├── boot-firmware.mount
│   │   ├── cron.service
│   │   ├── dbus.service
│   │   ├── dev-hugepages.mount
│   │   ├── dev-mqueue.mount
│   │   ├── exim4.service
│   │   ├── fail2ban.service
│   │   ├── networking.service
│   │   ├── rsyslog.service
│   │   ├── ssh.service
│   │   ├── sys-fs-fuse-connections.mount
│   │   ├── sys-kernel-debug.mount
│   │   ├── system-container\x2dshell.slice
│   │   │   └── container-shell@2.service
│   │   ├── system-getty.slice
│   │   │   └── getty@tty1.service
│   │   ├── system-serial\x2dgetty.slice
│   │   │   └── serial-getty@ttyS1.service
│   │   ├── system-systemd\x2dfsck.slice
│   │   ├── systemd-journald.service
│   │   ├── systemd-logind.service
│   │   ├── systemd-machined.service
│   │   ├── systemd-timesyncd.service
│   │   ├── systemd-udevd.service
│   │   ├── unattended-upgrades.service
│   │   └── wpa_supplicant.service
│   └── user.slice
│       ├── user-0.slice
│       │   ├── session-c2.scope
│       │   ├── session-c3.scope
│       │   └── user@0.service
│       │       └── dbus.socket
│       └── user-1001.slice
│           ├── session-125.scope
│           └── user@1001.service
├── rdma
├── systemd
│   ├── init.scope
│   ├── machine.slice
│   ├── system.slice
│   │   ├── boot-firmware.mount
│   │   ├── cron.service
│   │   ├── dbus.service
│   │   ├── dev-hugepages.mount
│   │   ├── dev-mqueue.mount
│   │   ├── exim4.service
│   │   ├── fail2ban.service
│   │   ├── networking.service
│   │   ├── rsyslog.service
│   │   ├── ssh.service
│   │   ├── sys-fs-fuse-connections.mount
│   │   ├── sys-kernel-debug.mount
│   │   ├── system-container\x2dshell.slice
│   │   │   └── container-shell@2.service
│   │   ├── system-getty.slice
│   │   │   └── getty@tty1.service
│   │   ├── system-serial\x2dgetty.slice
│   │   │   └── serial-getty@ttyS1.service
│   │   ├── system-systemd\x2dfsck.slice
│   │   ├── systemd-journald.service
│   │   ├── systemd-logind.service
│   │   ├── systemd-machined.service
│   │   ├── systemd-timesyncd.service
│   │   ├── systemd-udevd.service
│   │   ├── unattended-upgrades.service
│   │   └── wpa_supplicant.service
│   └── user.slice
│       ├── user-0.slice
│       │   ├── session-c2.scope
│       │   ├── session-c3.scope
│       │   └── user@0.service
│       │       ├── dbus.socket
│       │       └── init.scope
│       └── user-1001.slice
│           ├── session-125.scope
│           └── user@1001.service
│               ├── -.mount
│               ├── boot-firmware.mount
│               ├── dbus.socket
│               ├── dev-hugepages.mount
│               ├── dev-mqueue.mount
│               ├── dirmngr.socket
│               ├── docker.service
│               │   ├── 057ccd0c76004aec529f43c4b7c49c7466ece91f5b051e9958aee1af152a5bba
│               │   ├── 098bc0ba28b547ccaeb17d1600a2638497cecd4f235f8898b0e0ebf67aac68fd
│               │   ├── 19b9705545bd8b9d952ace7a897733492eb604e0cef8f122d10dfdbc562405f4
│               │   ├── 287f24c584be9a89237d80a3a702be5683566d4c29e2c7c42420d5634ed695dd
│               │   ├── 37412ea640b67c402eb7d2a8b7404f4f85a5253b9b8c4a458cc1d8cf7d576524
│               │   ├── 3cdee39045ffa6ef591f3f8e2b20aa52bda84b7d149ab21f42207746df86a393
│               │   ├── 3dab42a41786eacc53671248a39ee846014bcc7534f0cb78f19ab726451e2859
│               │   ├── 47d29803906e22256c02ea70a34b45b58a88aa76bd21d2eab890680df9703216
│               │   ├── 4ab7b301f838d4df96db0c53e53f5977fade75e374e13f97332f5affc06572d5
│               │   ├── 4d8760f4078eb98bcfcc0347dbff0bdd0dfda5ec70f111b4726c8b53258182d5
│               │   ├── 5b2d7dd6c4ce56e8eadf28c38285b43e3506c6943da54957021625b6471b01d3
│               │   ├── 65c3e17deb5564ec6f22243985221c4326ec47218093a05225876c76843cc511
│               │   ├── 7cb83617400c47ffa4defd6177008cd524cae56f2867cc557e42ac9e6a320932
│               │   ├── 7e2b3135b9dcf615f74c2c01c8f7a964fd3545b0fff7822fac606c94d58d0c71
│               │   ├── 854bfd14b24e9e5dee80162bf77785097da15fc8e34debab0b6965da7d12fa5b
│               │   ├── 90dfa9adc14fa9d845f1caa45c571d4b8f2dc3c812578eea61e17413ea365c00
│               │   ├── 9e538815207eb76d9c5c271cff5f1b93d3393241bb67970df1ad71b9ac24d667
│               │   ├── 9fc463505cbf6af78fba096213341b82f45d8f29acd85846bed19e7a816c6fe7
│               │   ├── a7452cf06a14e6e79f575121d6c317863974a78da2e47c8e92b82e54805645a0
│               │   ├── ac5717649c969911ad799cc9f13ff730545ec1ff9aafe42bf46cb98b6fd0a39f
│               │   ├── c0940ca22f8853311072e189e6c03dc0e7d86f97590714f84d7912251be8d6fe
│               │   ├── c4be0c992b43eb4454598fbbe38747de990c88f798f1f5afe222699586f76646
│               │   ├── c5dcadb5b176b3067fcf7e9dc86de71880444061797c69529ec8172f0db86115
│               │   ├── cbcf79e7491bc4ebae25c462631bf88c71a34ba594f2c489aff5994a97b32972
│               │   ├── d4b0de99a93850ecedffdfb6f9912820c323d9be49bae4f2bfab3e35bca2dafe
│               │   ├── e3b9b3bda5db16c2bd98b608e8045eed6a8dbf6de7739db9c65502956adc9932
│               │   ├── e5547782a48675f7c648a25eab5c84808bf7e33280ea2a7f02f090c094c748f9
│               │   ├── e92ef73baef58ae37b2db3043460d9dca9020a6eba417ea317ab95d45cc8d042
│               │   └── f443f182c2fef0d7cda36fe722c03304e295bc9f2e68525809224e4aef90a49f
│               ├── gpg-agent-browser.socket
│               ├── gpg-agent-extra.socket
│               ├── gpg-agent-ssh.socket
│               ├── gpg-agent.socket
│               ├── init.scope
│               ├── media-<redacted_user>-data\x2dhdd.mount
│               ├── run-user-0.mount
│               ├── run-user-1001.mount
│               ├── sys-kernel-debug.mount
│               ├── var-hdd.log.mount
│               └── var-log.mount
└── unified
    ├── init.scope
    ├── machine.slice
    ├── system.slice
    │   ├── boot-firmware.mount
    │   ├── cron.service
    │   ├── dbus.service
    │   ├── dev-hugepages.mount
    │   ├── dev-mqueue.mount
    │   ├── exim4.service
    │   ├── fail2ban.service
    │   ├── networking.service
    │   ├── rsyslog.service
    │   ├── ssh.service
    │   ├── sys-fs-fuse-connections.mount
    │   ├── sys-kernel-debug.mount
    │   ├── system-container\x2dshell.slice
    │   │   └── container-shell@2.service
    │   ├── system-getty.slice
    │   │   └── getty@tty1.service
    │   ├── system-serial\x2dgetty.slice
    │   │   └── serial-getty@ttyS1.service
    │   ├── system-systemd\x2dfsck.slice
    │   ├── systemd-journald.service
    │   ├── systemd-logind.service
    │   ├── systemd-machined.service
    │   ├── systemd-timesyncd.service
    │   ├── systemd-udevd.service
    │   ├── unattended-upgrades.service
    │   └── wpa_supplicant.service
    └── user.slice
        ├── user-0.slice
        │   ├── session-c2.scope
        │   ├── session-c3.scope
        │   └── user@0.service
        │       ├── dbus.socket
        │       └── init.scope
        └── user-1001.slice
            ├── session-125.scope
            └── user@1001.service
                ├── -.mount
                ├── boot-firmware.mount
                ├── dbus.socket
                ├── dev-hugepages.mount
                ├── dev-mqueue.mount
                ├── dirmngr.socket
                ├── docker.service
                ├── gpg-agent-browser.socket
                ├── gpg-agent-extra.socket
                ├── gpg-agent-ssh.socket
                ├── gpg-agent.socket
                ├── init.scope
                ├── media-<redacted_user>-data\x2dhdd.mount
                ├── run-user-0.mount
                ├── run-user-1001.mount
                ├── sys-kernel-debug.mount
                ├── var-hdd.log.mount
                └── var-log.mount

260 directories
```

**Comment by ilyam8** [comment] 2021-05-07 20:05
Hm, if I understand it right, i see:
 - Cgroups v1
 - driver `systemd`
 - systemd default-hierarchy=hybrid

I expect docker container cgroups to be in:
 - `/sys/fs/cgroup/cpuacct/system.slice/docker-<longid>.scope/`
 - `/sys/fs/cgroup/cpuset/system.slice/docker-<longid>.scope/`
 - `/sys/fs/cgroup/memory/system.slice/docker-<longid>.scope/`
 - `/sys/fs/cgroup/blkio/system.slice/docker-<longid>.scope/`
 - `/sys/fs/cgroup/devices/system.slice/docker-<longid>.scope/`

That is not the case 🤔 @vlvkobal Take a look

---

That is my server, it has 2 running docker containers:

```cmd
[ilyam@pc ~]$ tree -d /sys/fs/cgroup/cpuacct/docker /sys/fs/cgroup/cpuset/docker /sys/fs/cgroup/memory/docker /sys/fs/cgroup/blkio/docker /sys/fs/cgroup/devices/docker
/sys/fs/cgroup/cpuacct/docker
├── 061fe1b1094453d1233c3b2fbc7b6755140e7b1e1bba01afefde021d768beaae
└── 71268b6c1652fb837a816e22e08f08a0ab7ec12aba6fc27534920255d487f3cb
/sys/fs/cgroup/cpuset/docker
├── 061fe1b1094453d1233c3b2fbc7b6755140e7b1e1bba01afefde021d768beaae
└── 71268b6c1652fb837a816e22e08f08a0ab7ec12aba6fc27534920255d487f3cb
/sys/fs/cgroup/memory/docker
├── 061fe1b1094453d1233c3b2fbc7b6755140e7b1e1bba01afefde021d768beaae
└── 71268b6c1652fb837a816e22e08f08a0ab7ec12aba6fc27534920255d487f3cb
/sys/fs/cgroup/blkio/docker
├── 061fe1b1094453d1233c3b2fbc7b6755140e7b1e1bba01afefde021d768beaae
└── 71268b6c1652fb837a816e22e08f08a0ab7ec12aba6fc27534920255d487f3cb
/sys/fs/cgroup/devices/docker
├── 061fe1b1094453d1233c3b2fbc7b6755140e7b1e1bba01afefde021d768beaae
└── 71268b6c1652fb837a816e22e08f08a0ab7ec12aba6fc27534920255d487f3cb

10 directories
```

**Comment by ilyam8** [comment] 2021-05-07 20:15
Likely I am missing something 🤔 

> /run/user/1001/docker.sock

How did you install docker? Docker version?

**Comment by ilyam8** [comment] 2021-05-07 20:17
[Known limitations](https://docs.docker.com/engine/security/rootless/#known-limitations)

> Cgroup is supported only when running with cgroup v2 and systemd.

I guess you need to enable Cgroups v2.

**Comment by ilyam8** [comment] 2021-05-07 20:22
The following guide works for Manjaro, likely will do for debian too, **but better to google how to do it**.

- add _systemd.unified_cgroup_hierarchy=1_ to the `GRUB_CMDLINE_LINUX_DEFAULT` (`/etc/default/grub`)

```cmd
[ilyam@pc ~]$ grep hierarchy=1 /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="quiet apparmor=1 security=apparmor udev.log_priority=3 systemd.unified_cgroup_hierarchy=1"
```

- `update-grub`
- `reboot`

**Comment by schklom** [comment] 2021-05-07 23:05
I hadn't thought of this, nice find!
[Apparently](https://rootlesscontaine.rs/getting-started/common/cgroup2/), it requires Kernel 4.15 and a recent version of systemd `systemd 244 or later is recommended`.

I don't know why but I have no file for grub (I haven't modified any boot options, this is beyond what I'm comfortable doing)
```
$ cat /etc/default/grub
cat: /etc/default/grub: No such file or directory
```
In case it matters, I have a headless Debian 10 from https://raspi.debian.net/tested-images/.

`$ find / -name "grub"` resulted in nothing.

Any idea on solving this? ^^

**Comment by ilyam8** [comment] 2021-05-08 09:48
Unfortunately, no. And I have no Raspberry Pi to test anything.

@schklom closing this issue because [it is not a bug](https://github.com/netdata/netdata/issues/11069#issuecomment-834747968).

**Closed by ilyam8** 2021-05-08 09:48 UTC
Labels: docker, question

**Comment by schklom** [comment] 2021-09-05 01:32
Hey, I upgraded to Debian 11 and cgroup v2 is now active. The problem is that I still cannot see any sign of Docker containers on Netdata.

I think it is because Rootless Docker doesn't create files `/sys/fs/cgroup/cpuacct/docker /sys/fs/cgroup/cpuset/docker /sys/fs/cgroup/memory/docker /sys/fs/cgroup/blkio/docker /sys/fs/cgroup/devices/docker`.
`find /sys/fs/cgroup/ -name "docker"` gives me nothing.

I don't know where the cpu and memory usage can be found (apart from `docker stats`), but surely it is available somewhere.
Would it help if I asked the devs where they're available, or is this not the issue?

**Comment by schklom** [comment] 2021-09-15 23:37
@ilyam8 As posted just above this, I now have activated cgroups v2 but still no luck, so I think it qualifies as a bug now.
Any chance you have new insights on this issue? ^^

**Comment by ilyam8** [comment] 2021-09-16 08:09
Hey, @schklom. `cgroups.plugin` works with v2, we need to check.

> netdata v1.30.1-112-nightly

Are you still on that version? I suggest you try v1.31.0, v2 detection was fixes in https://github.com/netdata/netdata/pull/11102

**Comment by schklom** [comment] 2021-09-16 16:45
Hey, thanks for getting back to me!

I moved to v1.31.0, but still no luck :/
Is there any info I can provide to pinpoint the issue?

**Comment by ilyam8** [comment] 2021-09-16 20:03
Let's check `error.log`

```cmd
[ilyam@pc ~]$ docker restart netdata
# wait 5 seconds
[ilyam@pc ~]$ docker logs  netdata 2>&1 | grep unified
2021-09-16 20:01:24: netdata INFO  : PLUGIN[cgroups] : use unified cgroups true
```

**Comment by schklom** [comment] 2021-09-16 21:30
This part is good.

    2021-09-16 21:29:36: netdata INFO  : PLUGIN[cgroups] : use unified cgroups true

**Comment by schklom** [comment] 2021-10-13 12:44
@ilyam8 Thank you so much for persevering :)

```bash
$ docker logs netdata 2>&1 | grep -i cgroup
2021-10-13 01:07:12: netdata INFO  : PLUGIN[cgroups] : thread created with task id 114
2021-10-13 01:07:12: netdata INFO  : PLUGIN[cgroups] : set name of thread 114 to PLUGIN[cgroups]
2021-10-13 01:07:20: netdata INFO  : PLUGIN[cgroups] : use unified cgroups true
2021-10-13 01:07:24: netdata INFO  : PLUGIN[cgroups] : Restarting ACLK popcorn timer for host "ca0958ef2efc" with GUID "e7dbb1e6-08df-11ec-933a-0242c0a81203"
2021-10-13 01:07:25: netdata ERROR : PLUGIN[cgroups] : Failed to create an alarm for dimension user of chart netdata.plugin_cgroups_cpu 5 times. Skipping alarm. (errno 22, Invalid argument)
2021-10-13 01:07:27: netdata ERROR : PLUGIN[cgroups] : Failed to create an alarm for dimension system of chart netdata.plugin_cgroups_cpu 5 times. Skipping alarm.
2021-10-13 01:07:28: netdata ERROR : PLUGIN[cgroups] : heartbeat missed 5999956 monotonic microseconds
2021-10-13 01:07:38: cgroup-name.sh: INFO: cgroup 'init-scope' is called 'init-scope'
```

Without `2>&1`, there is way too much log to display. But given the amount of errors, I thought it may help
```bash
$ docker logs netdata | grep -i cgroup
2021-10-13 12:28:40: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface eth0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:40: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface wlan0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:41: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface eth0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:41: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface wlan0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:41: apps.plugin ERROR : MAIN : Cannot process /host/proc/1265663/io (command 'su') (errno 13, Permission denied)
2021-10-13 12:28:41: apps.plugin ERROR : MAIN : Cannot process entries in /host/proc/1265663/fd (command 'su') (errno 13, Permission denied)
2021-10-13 12:28:42: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface eth0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:42: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface wlan0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:43: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface eth0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:43: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface wlan0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:44: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface eth0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:44: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface wlan0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process /host/proc/1265687/io (command 'bash') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process entries in /host/proc/1265687/fd (command 'bash') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process /host/proc/1265703/io (command 'exim4') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process entries in /host/proc/1265703/fd (command 'exim4') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process /host/proc/1265704/io (command 'exim4') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process entries in /host/proc/1265704/fd (command 'exim4') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process /host/proc/1265707/io (command 'sudo') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process entries in /host/proc/1265707/fd (command 'sudo') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process /host/proc/1265708/io (command 'bash') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process entries in /host/proc/1265708/fd (command 'bash') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process /host/proc/1265723/io (command 'exim4') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process entries in /host/proc/1265723/fd (command 'exim4') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process /host/proc/1265724/io (command 'exim4') (errno 13, Permission denied)
2021-10-13 12:28:44: apps.plugin ERROR : MAIN : Cannot process entries in /host/proc/1265724/fd (command 'exim4') (errno 13, Permission denied)
2021-10-13 12:28:45: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface eth0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:45: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface wlan0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:46: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface eth0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
2021-10-13 12:28:46: netdata ERROR : PLUGIN[proc] : Cannot refresh mtu for interface wlan0 by reading '(null)'. Stop updating it. (errno 2, No such file or directory)
```

**Comment by ilyam8** [comment] 2021-10-15 10:43
@schklom I see there are too few lines, let's restart the container, wait for 20 seconds and grep again.

**Comment by schklom** [comment] 2021-10-20 22:28
@ilyam8 
```bash
$ docker exec netdata ls -l /host/sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/user.slice/docker-7add903ef98f9974fcd73ecd653cef3a298acba2a14ad55a64859fb7638fb1
33.scope/
total 0
-r--r--r--    1 root     root             0 Oct 20 00:59 cgroup.controllers
-r--r--r--    1 root     root             0 Oct 20 00:59 cgroup.events
-rw-r--r--    1 root     root             0 Oct 20 00:59 cgroup.freeze
-rw-r--r--    1 root     root             0 Oct 20 00:59 cgroup.max.depth
-rw-r--r--    1 root     root             0 Oct 20 00:59 cgroup.max.descendants
-rw-r--r--    1 root     root             0 Oct 20 00:59 cgroup.procs
-r--r--r--    1 root     root             0 Oct 20 00:59 cgroup.stat
-rw-r--r--    1 root     root             0 Oct 20 00:59 cgroup.subtree_control
-rw-r--r--    1 root     root             0 Oct 20 00:59 cgroup.threads
-rw-r--r--    1 root     root             0 Oct 20 00:59 cgroup.type
-rw-r--r--    1 root     root             0 Oct 20 00:59 cpu.max
-rw-r--r--    1 root     root             0 Oct 20 00:59 cpu.pressure
-r--r--r--    1 root     root             0 Oct 20 00:59 cpu.stat
-rw-r--r--    1 root     root             0 Oct 20 00:59 cpu.weight
-rw-r--r--    1 root     root             0 Oct 20 00:59 cpu.weight.nice
-rw-r--r--    1 root     root             0 Oct 20 00:59 cpuset.cpus
-r--r--r--    1 root     root             0 Oct 20 00:59 cpuset.cpus.effective
-rw-r--r--    1 root     root             0 Oct 20 00:59 cpuset.cpus.partition
-rw-r--r--    1 root     root             0 Oct 20 00:59 cpuset.mems
-r--r--r--    1 root     root             0 Oct 20 00:59 cpuset.mems.effective
-rw-r--r--    1 root     root             0 Oct 20 00:59 io.max
-rw-r--r--    1 root     root             0 Oct 20 00:59 io.pressure
-r--r--r--    1 root     root             0 Oct 20 00:59 io.stat
-rw-r--r--    1 root     root             0 Oct 20 00:59 io.weight
-r--r--r--    1 root     root             0 Oct 20 00:59 memory.current
-r--r--r--    1 root     root             0 Oct 20 00:59 memory.events
-r--r--r--    1 root     root             0 Oct 20 00:59 memory.events.local
-rw-r--r--    1 root     root             0 Oct 20 00:59 memory.high
-rw-r--r--    1 root     root             0 Oct 20 00:59 memory.low
-rw-r--r--    1 root     root             0 Oct 20 00:59 memory.max
-rw-r--r--    1 root     root             0 Oct 20 00:59 memory.min
-r--r--r--    1 root     root             0 Oct 20 00:59 memory.numa_stat
-rw-r--r--    1 root     root             0 Oct 20 00:59 memory.oom.group
-rw-r--r--    1 root     root             0 Oct 20 00:59 memory.pressure
-r--r--r--    1 root     root             0 Oct 20 00:59 memory.stat
-r--r--r--    1 root     root             0 Oct 20 00:59 memory.swap.current
-r--r--r--    1 root     root             0 Oct 20 00:59 memory.swap.events
-rw-r--r--    1 root     root             0 Oct 20 00:59 memory.swap.high
-rw-r--r--    1 root     root             0 Oct 20 00:59 memory.swap.max
-r--r--r--    1 root     root             0 Oct 20 00:59 pids.current
-r--r--r--    1 root     root             0 Oct 20 00:59 pids.events
-rw-r--r--    1 root     root             0 Oct 20 00:59 pids.max
```
