### ISSUE TITLE
[Bug]: Ubuntu 22.04 Unmet dependencies

### ISSUE THREAD

**Issue by stevenhrabok** [netdata/netdata#17619] opened 2024-05-08 21:27 UTC
### Bug description

When attempting to install netdata it fails with unmet dependency errors:
```
 apt install netdata
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 netdata : Depends: libbson-1.0-0 (>= 1.24.3) but it is not going to be installed
           Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
           Depends: libmongoc-1.0-0 (>= 1.24.3) but it is not going to be installed
           Depends: libsnappy1v5 (>= 1.1.10) but it is not going to be installed
           Depends: libstdc++6 (>= 13.1) but 12.3.0-1ubuntu1~22.04 is to be installed
           Depends: libzstd1 (>= 1.5.5) but 1.4.8+dfsg-3build1 is to be installed
           Depends: netdata-plugin-ebpf (= 1.45.4) but it is not going to be installed
           Depends: netdata-plugin-apps (= 1.45.4) but it is not going to be installed
           Depends: netdata-plugin-debugfs (= 1.45.4) but it is not going to be installed
           Depends: netdata-plugin-nfacct (= 1.45.4) but it is not going to be installed
           Depends: netdata-plugin-slabinfo (= 1.45.4) but it is not going to be installed
           Depends: netdata-plugin-perf (= 1.45.4) but it is not going to be installed
           Recommends: netdata-plugin-systemd-journal (= 1.45.4) but it is not going to be installed
           Recommends: netdata-plugin-logs-management (= 1.45.4) but it is not going to be installed
           Recommends: netdata-plugin-network-viewer (= 1.45.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

### Expected behavior

Package to be installed

### Steps to reproduce

apt install netdata

### Installation method

manual setup of official DEB/RPM packages

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.4 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
not installed
```

### Additional info

Previously reported recently in old issue that was closed - https://github.com/netdata/netdata/issues/17617

**Comment by AnnAngela** [comment] 2024-05-09 01:44
Same issue, `apt install netdata` from https://packagecloud.io/netdata/netdata/ubuntu/ log:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 netdata : Depends: libbson-1.0-0 (>= 1.24.3) but 1.21.0-1build1 is to be installed
           Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
           Depends: libmongoc-1.0-0 (>= 1.24.3) but 1.21.0-1build1 is to be installed
           Depends: libsnappy1v5 (>= 1.1.10) but 1.1.8-1build3 is to be installed
           Depends: libstdc++6 (>= 13.1) but 12.3.0-1ubuntu1~22.04 is to be installed
           Depends: libzstd1 (>= 1.5.5) but 1.4.8+dfsg-3build1 is to be installed
 netdata-plugin-apps : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
 netdata-plugin-debugfs : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
 netdata-plugin-ebpf : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
 netdata-plugin-logs-management : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
 netdata-plugin-network-viewer : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
 netdata-plugin-nfacct : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
 netdata-plugin-perf : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
 netdata-plugin-slabinfo : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
 netdata-plugin-systemd-journal : Depends: libc6 (>= 2.38) but 2.35-0ubuntu3.7 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Ferroin** [comment] 2024-05-09 11:09
Closing as a duplicate of #17617, see https://github.com/netdata/netdata/issues/17617#issuecomment-2102456549 for details on why the issue was not fully resolved at first.

**Closed by Ferroin** 2024-05-09 11:09 UTC
Labels: bug, needs triage

**Comment by stevenhrabok** [comment] 2024-05-10 15:58
@Ferroin this is still not resolved and not related to arm packages. This is still being experienced on amd64 packages in the following repos:
deb https://packagecloud.io/netdata/netdata/ubuntu/ jammy main
deb-src https://packagecloud.io/netdata/netdata/ubuntu/ jammy main

**Comment by stevenhrabok** [comment] 2024-05-10 16:16
@Ferroin @AnnAngela it seems that the packagecloud.io repos are no longer being maintained - https://learn.netdata.cloud/docs/netdata-agent/installation/linux/native-linux-distribution-packages
I've switched to the new repo's in the article described and the installation works again.
