### ISSUE TITLE
netdata-updater.sh: No such file or directory

### ISSUE THREAD

**Issue by gaia** [netdata/netdata#10372] opened 2020-12-11 17:36 UTC
##### Bug report summary
```/etc/cron.daily/netdata-updater: line 31: /etc/cron.daily/netdata-updater.sh: No such file or directory
run-parts: /etc/cron.daily/netdata-updater exited with return code 127```

##### OS / Environment
```Linux node2 5.4.60-1-pve #1 SMP PVE 5.4.60-2 (Fri, 04 Sep 2020 10:24:50 +0200) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"```

##### Netdata version
`netdata v1.26.0-333-nightly`

##### Component Name
Updater (?)

##### Steps To Reproduce
run cron to update daily

##### Expected behavior
no errors, successful update when available

**Comment by ilyam8** [comment] 2020-12-11 18:59
Hi @gaia, thx for reporint! Unfortunately updater in `netdata v1.26.0-333-nightly` is broken. The problem is fixed in master.

To fix it you need to re-run the installer, see https://github.com/netdata/netdata/issues/10366#issuecomment-742699376

**Comment by gaia** [comment] 2020-12-11 21:53
thanks, sorry i didn't see it before i posted!

**Comment by gaia** [comment] 2020-12-12 14:35
still happening

```
/etc/cron.daily/netdata-updater:
/etc/cron.daily/netdata-updater: line 31: /etc/cron.daily/netdata-updater.sh: No such file or directory
run-parts: /etc/cron.daily/netdata-updater exited with return code 127
```

**Comment by LordBrud** [comment] 2020-12-13 11:13
I fixed it by changing Line 31 in `netdata-updater.sh`.
I changed `script_source="$("$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)/netdata-updater.sh")"`  (https://github.com/netdata/netdata/commit/7a416ecdcba6c1f4dda389731404afa7cc62a3f3#diff-4ecececabbbf75e2b00768f09ba63bef87a6c323c8b1959ad9d79faca7b9f5c9)
to  `script_source=""$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)/netdata-updater.sh"` .
Then I manually the script and it worked.

Here you can find the fix netdata made https://github.com/netdata/netdata/commit/19dd150acf48f3f83ee66edd82a54193d6921130#diff-4ecececabbbf75e2b00768f09ba63bef87a6c323c8b1959ad9d79faca7b9f5c9

**Comment by Ferroin** [comment] 2020-12-14 14:34
Indeed, manually patching the file as outlined in the above-mentioned commit should fix it. The other option is to run the installer again using the same options you originally installed with and adding `--reinstall` (without the `--reinstall` it will try to run the updater, and get stuck in an infinite loop because of the same bug).

**Comment by gaia** [comment] 2020-12-14 15:38
> Indeed, manually patching the file as outlined in the above-mentioned commit should fix it. The other option is to run the installer again using the same options you originally installed with and adding `--reinstall` (without the `--reinstall` it will try to run the updater, and get stuck in an infinite loop because of the same bug).

I did that but I am still having the issue.

**Comment by Ferroin** [comment] 2020-12-14 16:24
@gaia Can you try `bash -x <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstall` (with any extra options you used on install added to the end) and post the output. This will fail in the same way, but will produce debugging output for the script itself, which should help us figure out why exactly it’s trying to run the updater instead of doing a clean install.

**Comment by gaia** [comment] 2020-12-14 17:09
> @gaia Can you try `bash -x <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstall` (with any extra options you used on install added to the end) and post the output. This will fail in the same way, but will produce debugging output for the script itself, which should help us figure out why exactly it’s trying to run the updater instead of doing a clean install.

I had done it w/o `-x` before, tried now with it. it reinstalls fine, i only get the alert when cron runs. the reinstall output looks good.

**Comment by Ferroin** [comment] 2020-12-15 13:58
@gaia To clarify, you are still seeing the issue even _after_ reinstalling?

**Comment by Ferroin** [comment] 2020-12-15 14:54
@gaia Further update, there’s apparently a bug in the option parsing for the kickstart installer that is causing it to care about the order of the options passed to it. Working on a fix now, but in the short term you should be able to work around this by putting `--reinstall` as the first option instead of putting it later in the option list.

**Comment by gaia** [comment] 2020-12-15 17:00
> @gaia To clarify, you are still seeing the issue even _after_ reinstalling?

Yes, reinstalled twice, once with once without the `-x`. Still:

```
etc/cron.daily/netdata-updater:
/etc/cron.daily/netdata-updater: line 31: /etc/cron.daily/netdata-updater.sh: No such file or directory
run-parts: /etc/cron.daily/netdata-updater exited with return code 127
```

> @gaia Further update, there’s apparently a bug in the option parsing for the kickstart installer that is causing it to care about the order of the options passed to it. Working on a fix now, but in the short term you should be able to work around this by putting `--reinstall` as the first option instead of putting it later in the option list.

That was my only option on both runs.

**Comment by darsys** [comment] 2020-12-18 14:49
I had the same original issue and I followed the instructions to reinstall using
`/etc/cron.daily/netdata-updater: line 44: 3: Bad file descriptor'

Here is a pastebin of my output: [https://pastebin.com/rvbkYL4b](url)

After running this (and restarting netdata service), the updater now does this:
`/etc/cron.daily/netdata-updater: line 44: 3: Bad file descriptor

This is  dell 610 server with updated current debian
uname: Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux`

I will look into this further but wanted to post my results to try to help

**Comment by kaplandani** [comment] 2020-12-20 17:01
when it moves to run netdata updater  is stuck in a look forking more and more netdata_updater.sh processes

**Comment by stelfrag** [comment] 2020-12-21 09:55
> when it moves to run netdata updater is stuck in a look forking more and more netdata_updater.sh processes

Hi @kaplandani 

Unfortunately there has been an issue with the updater (this is really bad and we will try our best not to have this happen again :disappointed:). 

Please proceed with a reinstall as described in 

[https://learn.netdata.cloud/docs/agent/packaging/installer#automatic-one-line-installation-script](https://learn.netdata.cloud/docs/agent/packaging/installer#automatic-one-line-installation-script)

`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstall`

**Comment by kaplandani** [comment] 2020-12-21 10:59
will it remove any current settings / enabled plugins ?
Thanks.

**Comment by stelfrag** [comment] 2020-12-21 11:10
> will it remove any current settings / enabled plugins ? Thanks.

No it will not affect settings

**Comment by kaplandani** [comment] 2020-12-21 11:17
The installer tries to upgrade libcurl3 and remove php5-culr which I cannot
allow (php5 is installed on the server)
is there any breaking dependencies on version 28 that needs to be installed
after version 26 is installed ?
Dani

**Comment by stelfrag** [comment] 2020-12-21 14:14
> The installer tries to upgrade libcurl3 and remove php5-culr which I cannot allow (php5 is installed on the server) is there any breaking dependencies on version 28 that needs to be installed after version 26 is installed ? Dani

Since you have 1.26 running, 1.28 does not have different dependencies as far as the agent is concerned

If you choose to say **n** to the update command (apt-get install or equivalent) that wants to upgrade libcurl3 and remove php5-curl then you will get something like

```
Abort.

We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/netdata/netdata/issues


 FAILED  

 WARNING  It failed to install all the required packages, but installation might still be possible. 

Press ENTER to attempt netdata installation > 
```

**Comment by gaia** [comment] 2021-01-06 15:55
on the current version as of yesterday, in the same system as my OP, the issue now is `/etc/cron.daily/netdata-updater: line 101: _cannot_find_tmpdir: command not found`

should I open a separate issue?

**Comment by Ferroin** [comment] 2021-01-06 16:27
@gaia It is indeed an unrelated issue, but someone already beat you to it. See: #10461.

**Closed** 2021-01-12 12:32 UTC
Labels: area/packaging, bug, priority/high
