### ISSUE TITLE
Memory leak / Too much memory used in the dashboard

### ISSUE THREAD

**Issue by PegasisForever** [netdata/netdata#9231] opened 2020-05-30 21:14 UTC
##### Bug report summary
The dashboard takes more and more ram over time and crash the tab at the end.

##### OS / Environment

```
Linux pegasis-x79 5.4.40-1-MANJARO #1 SMP PREEMPT Sun May 10 14:17:40 UTC 2020 x86_64 GNU/Linux
/etc/arch-release:Manjaro Linux
/etc/lsb-release:DISTRIB_ID=ManjaroLinux
/etc/lsb-release:DISTRIB_RELEASE=20.0.1
/etc/lsb-release:DISTRIB_CODENAME=Lysia
/etc/lsb-release:DISTRIB_DESCRIPTION="Manjaro Linux"
/etc/manjaro-release:Manjaro Linux
/etc/os-release:NAME="Manjaro Linux"
/etc/os-release:ID=manjaro
/etc/os-release:ID_LIKE=arch
/etc/os-release:PRETTY_NAME="Manjaro Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:HOME_URL="https://www.manjaro.org/"
/etc/os-release:SUPPORT_URL="https://www.manjaro.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.manjaro.org/"
/etc/os-release:LOGO=manjarolinux
```

##### Netdata version

netdata v1.22.1-170-nightly

##### Chrome version

83.0.4103.61 Linux

##### Component Name

Web

##### Steps To Reproduce

1. Open the netdata dashboard
2. Set "When to refresh the charts" to always
3. Wait for one day, don't scroll it or change the dimention of the window
4. The tab will either crash or use gbs of memory

##### Expected behavior

The netdata dashboard shouldn't use that much memory after long period of use.

**Comment by PegasisForever** [comment] 2020-05-31 01:24
This is a heap snapshot after I let it sit for about 4 hours and it's taking around 500mb of memory: https://drive.google.com/file/d/1UPsNJ-w3Wpjz2zT9OO3W4RJuGx0865pu/view?usp=sharing

**Comment by jacekkolasa** [comment] 2020-10-22 19:33
Thanks @PegasisForever (if you're reading this after months...) I'm setting priority/low because other bugs/feature-requests seems to be more needed, but if this issue is problematic for someone, please leave your notes. We've experienced up to 1.1 GB consumption (overnight, no scrolling involved). If it will be hard to fix this (for example it could be related to old charting libraries), maybe we'll just auto-refresh after few hours of inactivity

**Comment by PegasisForever** [comment] 2020-10-22 19:38
That sounds like an acceptable workaround

**Comment by ilyam8** [comment] 2021-08-25 15:21
Duplicate of #4366

**Closed by ilyam8** 2021-08-25 15:21 UTC
Labels: bug, duplicate, area/web, priority/low
