### ISSUE TITLE
eBPF support for DEB/RPM packages.

### ISSUE THREAD

**Issue by Nirjonadda** [netdata/netdata#8242] opened 2020-02-28 11:56 UTC
Please can you let me know that How to enable eBPF Kernel Collector? I am using CentOS 7.7 with cPanel v86.0.7

```
 --- eBPF Kernel Collector (opt-in) ---
 FAILED  ebpf not enabled. --enable-ebpf to enable
```

![ScreenShot00032](https://user-images.githubusercontent.com/6899856/75546408-c051cf00-5a28-11ea-8557-7303f7c6f84c.png)

I am installed netdata with this Installation guide.

Enabled the EPEL repo
Enabled the additional repo from okay.network

And installed the minimum required dependencies

`yum install autoconf automake curl gcc git libmnl-devel libuuid-devel openssl-devel libuv-devel lz4-devel Judy-devel make nc pkgconfig python zlib-devel cmake libwebsockets-devel
`

Then Installed Netdata.

```
cd /root/netdata

./netdata-installer.sh
```

**Comment by ilyam8** [comment] 2020-02-28 12:01
Hi @Nirjonadda 

>  FAILED  ebpf not enabled. --enable-ebpf to enable


you need to pass that option to the installer

https://github.com/netdata/netdata/blob/1ea0d8d0897ec2d84ff447874e2ebd6170f54287/netdata-installer.sh#L173

**Comment by Nirjonadda** [comment] 2020-02-28 12:08
Does not understanding what do you meaning? Please can you add more information?

Also do we need enable eBPF or not? If we need enable eBPF then how can enable eBPF?

**Comment by thiagoftsm** [comment] 2020-02-28 12:09
Hi @Nirjonadda ,

Unfortunately Centos 7.7 uses a different kind of kernel, for example, on my computer when I run `uname -r` I receive:

```
3.10.0-1062.12.1.el7.x86_64
```

And this should not have the necessary features to run the eBPF collector, but when I run the next group of commands:

```
[fractal@malta2183 ~]$ grep BPF /boot/config-3.10.0-1062.12.1.el7.x86_64 
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_NET_CLS_BPF=m
CONFIG_BPF_JIT=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
CONFIG_BPF_KPROBE_OVERRIDE=y
[fractal@malta2183 ~]$ grep KPROBE /boot/config-3.10.0-1062.12.1.el7.x86_64 
CONFIG_KPROBES=y
CONFIG_KPROBES_ON_FTRACE=y
CONFIG_HAVE_KPROBES=y
CONFIG_HAVE_KPROBES_ON_FTRACE=y
CONFIG_HAVE_KPROBE_OVERRIDE=y
# CONFIG_KPROBES_SANITY_TEST is not set
CONFIG_KPROBE_EVENT=y
CONFIG_BPF_KPROBE_OVERRIDE=y
```

The output says for us that we have everything inside the kernel image.

I did not test yet the eBPF on CentOS, because our installer is not prepared to detect it, not less important the CentOS kernel does not reflect the exact features it has.

I assigned this issue for our SRE team for we work on this ASAP. Right now we are completing the support for kernels that their names match the expect features, after this we will work with RedHat families that follow other pattern.

Best regards!

**Comment by thiagoftsm** [comment] 2020-02-28 12:13
> Does not understanding what do you meaning? Please can you add more information?

@ilyam8 was saying that to install Netdata with eBPF it is necessary to run:

```
# ./netdata-installer.sh --enable-ebpf
```

> Also do we need enable eBPF or not? If we need enable eBPF then how can enable eBPF?

eBPF is an alpha collector, and the motive I described in the previous message.  It is not obligatory to enable it for Netdata runs, but it is an interesting feature that brings more information from your system.

After to have success in the installation, you can enable it changing your `netdata.conf` this way:

```
[plugins]
     ebpf_process = yes
```

Best regards!

**Comment by thiagoftsm** [comment] 2020-02-28 12:14
I changed your issue pipeline for we work on it next week.

**Comment by Nirjonadda** [comment] 2020-02-28 14:52
@thiagoftsm Does work with this command. We have run this `./netdata-installer.sh --enable-ebpf` but still getting error.

![ScreenShot00033](https://user-images.githubusercontent.com/6899856/75558551-43cbea00-5a42-11ea-8082-3d092a543839.png)

**Comment by thiagoftsm** [comment] 2020-02-28 16:08
@Nirjonadda as you can see in the message, our installer is searching for a kernel >= 4.11, and CentOS and few versions of RHEL  are using in their kernel name `3.10.x` , but they are bringing all the new features thaat the kernel team developed for these kernels, so they have old name kernels with new features. 
Next week I will dedicate a time exclusively for RH families and with this the whole community will be able to use our installer to install eBPF collector on CentOS and RH.

Best regards!

**Comment by Nirjonadda** [comment] 2020-03-16 13:39
@prologic @thiagoftsm Does this issue fixed?

**Comment by thiagoftsm** [comment] 2020-03-16 14:47
Hi @Nirjonadda we merged today on `kernel-collector` repository the eBPF programs that we compiled for the latest Kernel versions of CentOS and RH, we are only missing the changes on `netdata-installer.sh`.
I will work on this today, and it will be possible to also use this collector on RedHat and CentOS.
We apologize the delay, but we are working also working on other features during these days.

**Comment by hvisage** [comment] 2020-03-23 04:02
Is the ebpf collector yet supported in the static64 binary distributed via the `kickstart-static64.sh` process/option? Just tried it on a ProxMox node, and that failed with a ```2020-03-23 04:56:51: ebpf_process.plugin ERROR : MAIN : [EBPF PROCESS] setrlimit(RLIMIT_MEMLOCK) (errno 1, Operation not permitted)``` error. However the "normal" building process of using the `kickstarter.sh` scripts works and have ebpf reporting

**Comment by prologic** [comment] 2020-03-23 08:26
> Is the ebpf collector yet supported in the static64 binary distributed via the `kickstart-static64.sh` process/option? Just tried it on a ProxMox node, and that failed with a `2020-03-23 04:56:51: ebpf_process.plugin ERROR : MAIN : [EBPF PROCESS] setrlimit(RLIMIT_MEMLOCK) (errno 1, Operation not permitted)` error. However the "normal" building process of using the `kickstarter.sh` scripts works and have ebpf reporting
> 
> Reason I'm testing the static64: preparation for custom "air gapped"/firewalled systems

I don't think it is at the moment. cc @thiagoftsm What are your thoughts on supporting this?

It's a different packaging model and different installation tooling for the static `kickstart_static64.sh` -- Namely that it uses [Makeself](https://makeself.io/) and has its own logic.

It _could_ be supported; but we did not target this at the time. If this is useful to you and others and the team agrees I'd open a new feature request for this.

**Comment by hvisage** [comment] 2020-03-23 08:53
also @prologic the "normal" installation installs compilers etc. that I don't  want nor need (other than for this portion of netdata) so that also helps to cut on the root partition for VMs and containers

**Comment by prologic** [comment] 2020-03-23 10:57
Yeap I totally understand. Let me bring this up with the team. I don't see why we shouldn't support this; but as I said we didn't initially. We are heavily focused on getting more support for native packages (cc @Ferroin) out the door; but we should bring eBPF to the static installation as well as that is our primary fallback if all else fails.

**Comment by chrisfw** [comment] 2020-04-11 14:43
> @Nirjonadda as you can see in the message, our installer is searching for a kernel >= 4.11, and CentOS and few versions of RHEL are using in their kernel name `3.10.x` , but they are bringing all the new features thaat the kernel team developed for these kernels, so they have old name kernels with new features.
> Next week I will dedicate a time exclusively for RH families and with this the whole community will be able to use our installer to install eBPF collector on CentOS and RH.
> 
> Best regards!

Hi, I just wanted to inquire as to the status of this issue?  I just tried to build netdata from source on RHEL 7.8 with the latest available kernel (3.10.0-693) and experienced the described issue with the install script:
Your kernel appears to be older than 4.11 or you are using RH version older than 7.6.1810. This may still work in some cases, but probably won't.  Given the information that the requisite epbf functionality is apparently supported by these 3.x RHEL kernels, is there a way to change the value in the check-kernel-config.sh script since it appears to be downloaded on the fly by the installer?
Thanks in advance,
Chris Whelan

**Comment by thiagoftsm** [comment] 2020-04-11 16:20
Hi @chrisfw ,

Let me update about what is happening, we are finishing the necessary adjusts to have support for CentOS 7.x and RH 7.x . Both have kernels 3.10.0-X, but in reality the kernel name does not match the kernel features. RH brought some features that began to be released after kernel 4.7 to their kernels, and we are working for the next Netdata release to have complete support for RH 7.x family.

Yesterday I finish the necessary changes in our repository that compiles the eBPF programs. And right now I am adjusting the collector to monitor the functions that are present only on kernel 3.x .

About the necessary updates in our scripts, they are happening in this PR https://github.com/netdata/netdata/pull/8665 . 

We apologize for the delay, but RH 7.x has a special kernel, this is the motive we brought support firstly for "normal" kernels and now we are taking care of it.

Best regards!

**Comment by chrisfw** [comment] 2020-04-11 17:28
Sounds great!  Thanks very much for your quick and informative reply.

Regards,
Chris

**Comment by thiagoftsm** [comment] 2020-05-12 03:27
We are waiting code freeze finishes to merge the PR that will solve this, the next release will also convert the eBPF from alpha to a stable version.

**Comment by prologic** [comment] 2020-05-13 00:40
I think you're safe to merge today :) -- If you want to get this into a `v1.22.x` nightly :)

**Comment by thiagoftsm** [comment] 2020-05-13 01:05
I will wait few hours after 1.22.x to be released, it is the safest option! :)

**Comment by prologic** [comment] 2020-05-13 01:23
I think `v1.22.1` is already out not?

**Comment by thiagoftsm** [comment] 2020-05-13 23:14
You are right @prologic , I already merged the majority of the PRs related to eBPF, but we are missing few steps to merge others.

**Comment by prologic** [comment] 2020-05-19 22:51
I think we can close this now that #8665 is merged?

**Comment by prologic** [comment] 2020-05-19 22:52
i.e: eBPF is installed and enabled by default starting from today's nightly.

**Comment by thiagoftsm** [comment] 2020-05-29 22:40
Hi @Nirjonadda, @chrisfw and @hvisage ,

I tested now on CentOS 7.8 the installation with `./netdata-installer.sh` using the master branch  and it is running without any problem now,  please, can you confirm that you are able to run on CentOS the current branch?

Best regards!

**Comment by Nirjonadda** [comment] 2020-05-30 14:40
@thiagoftsm I am not using copy `./netdata-installer.sh`. We have installed netdata from [PackageCloud](http://packagecloud.io/netdata/netdata) (stable release) repo. So how can check for PackageCloud repo?

**Comment by thiagoftsm** [comment] 2020-05-30 16:05
I am not sure about PackageCloud, @prologic and @Ferroin  did we already upload the new packages on PackageCloud?

**Comment by prologic** [comment] 2020-06-01 01:47
> I am not sure about PackageCloud, @prologic and @Ferroin did we already upload the new packages on PackageCloud?

AFAIK No. These would need an additional set of packages. We should file an issue for this and add to our backlog (_but first we need to decide the direction we're taking with regards to native packaging_).

**Comment by Ferroin** [comment] 2020-07-27 11:27
Not actually stale, just moving slowly, should hopefully have better progress soon.

**Comment by v12mike** [comment] 2020-08-01 05:53
I hope that it is appropriate to ask here, but how should one disable ebpf?

I compiled and installed netdata v1.23.2-91-nightly, installed on Centos 7.8.2003 with kernel  3.10.0-1127.18.2.el7.x86_64.  After installing, and each time the machine is booted, the CPU usage of the ebpf.plugin process gradually grows so that after 12 hours it is using 100% of one core.  I would like to just switch off ebpf in a safe manner.

**Comment by ilyam8** [comment] 2020-08-01 09:34
@thiagoftsm @vlvkobal ^^

@v12mike it is in the `netdata.conf` under `[plugins]` section.

**Comment by thiagoftsm** [comment] 2020-08-01 14:39
Hi @v12mike ,

As @ilyam8 said, you can disable it with the following configuration inside your `netdata.conf`:

```
[plugins]
    ebpf = no
```

**Comment by ilyam8** [comment] 2020-08-01 14:48
@thiagoftsm i mentioned both of you because of 

> and each time the machine is booted, the CPU usage of the ebpf.plugin process gradually grows so that after 12 hours it is using 100% of one core.

couldbe something we want to investigate 🤷‍♂️ 😄

**Comment by v12mike** [comment] 2020-08-02 07:01
> Hi @v12mike ,
> 
> As @ilyam8 said, you can disable it with the following configuration inside your `netdata.conf`:
> 
> ```
> [plugins]
>     ebpf = no
> ```

Thanks. That solves the immediate issue.


> @thiagoftsm i mentioned both of you because of
> 
> > and each time the machine is booted, the CPU usage of the ebpf.plugin process gradually grows so that after 12 hours it is using 100% of one core.
> 
> couldbe something we want to investigate 🤷‍♂️ 😄

I don't think that the issue should be hard to reproduce, but I found it on a live server, so don't want to play around with it any more than I need to.

**Comment by vlvkobal** [comment] 2020-08-03 12:48
> > and each time the machine is booted, the CPU usage of the ebpf.plugin process gradually grows so that after 12 hours it is using 100% of one core.
>
> couldbe something we want to investigate 🤷‍♂️ 😄

I've run a test for 6 hours - no visible changes to CPU usage. Tested it on CentOS 7 3.10.0-957 and Arch Linux  5.7.11.

**Comment by thiagoftsm** [comment] 2020-08-03 13:21
I also never had problems like this on Slackware, but CentOS 7.x has a special kernel.

**Comment by v12mike** [comment] 2020-08-04 06:03
I turned on ebpf again today, and here is the result.  The real memory used bu the ebpf.plugin process increased from 1.5MB to 16MB over the same period.
![ebpf](https://user-images.githubusercontent.com/14261011/89258630-9c03b980-d67c-11ea-9557-f64011659e73.png)

**Comment by vlvkobal** [comment] 2020-08-04 08:20
Well, I couldn't see any changes in CPU usage charts but I confirm that memory used by eBPF plugin is constantly growing.

**Comment by amoss** [comment] 2020-08-04 08:28
This is problematic. In the short-term use the new kernel version reject-list to switch off eBPF on this particular CentOS kernel, then we can test on this specific kernel version internally to find and fix the problem in the code.

**Comment by keithmork** [comment] 2020-08-06 14:07
I meet the same problem.

![image](https://user-images.githubusercontent.com/5634347/89541471-fc3b5c80-d830-11ea-90a0-5bad75e494a2.png)

- CentOS Linux release 7.7.1908 (Core)
- kernel 3.10.0-957.21.3.el7.x86_64
- netdata v1.23.2-131-nightly, fresh install

**Comment by vlvkobal** [comment] 2020-08-06 14:26
@keithmork what does mean "the same problem"? `java` is growing. How is it connected to eBPF and what can we do about it?

**Comment by vlvkobal** [comment] 2020-08-06 14:27
Or do you mean that eBPF takes 52% of CPU usage?

**Comment by amoss** [comment] 2020-08-06 14:31
Hi @keithmork, thanks for the report. It does not look like the same problem as the CPU load from the eBPF plugin is constant but high, rather than growing. This is higher that we expected and we would like to investigate why it is consuming so much CPU time. Could you open a separate bug report? This will allow us to track it and get some information on the workload on your system to try to investigate the root cause.

**Comment by ilyam8** [comment] 2020-08-06 14:37
@keithmork zoom out chart (to get bigger timespan, it is 7 minutes on your charts) and choose only `ebpf` dimension. It is not clear - is it growing or constant but high?. Check `mem` charts too.

**Comment by keithmork** [comment] 2020-08-06 15:11
@vlvkobal @amoss @ilyam8 
OK I'll move to a new issue and provide more details there.  
For short, it isn't growing but always that high.   ebpf takes about 30%+ usr and 15% sys (total 100%) on a 4-core machine.

(The java process above is fine and not related to any issue, just the result of growing requests at that time.  Sorry for the confusion)

**Comment by git1977** [comment] 2020-08-07 04:34
Even for me in the cpu usage by apps, I see ebpf is using 8% of CPU on single core machine.
Followup question: What will I be losing if I disable ebpf?

**Comment by ilyam8** [comment] 2020-08-07 07:06
- see `eBPF` section charts
- see `ebpf syscall`, `ebpf net` subsections under `Applications` section

**Comment by prologic** [comment] 2020-09-10 05:38
@Ferroin Correct me if I'm wrong, but don't we already support the eBPF plugin with our DEB/RPM packages? I _think_ we can close this right?

**Comment by Ferroin** [comment] 2020-09-10 11:10
I _believe_ so, but I'm not sure.

**Closed** 2020-09-14 04:08 UTC
Labels: ebpf, no changelog, question
