### ISSUE TITLE
InfluxDB backend with HTTP auth

### ISSUE THREAD

**Issue by simonszu** [netdata/netdata#3824] opened 2018-06-14 10:10 UTC
Hi,

in my setup i have InfluxDB on another host than the netdata streaming server. I'd like to configure this InfluxDB instance as a backend for netdata. Currently i have proxied the influxDB so it is reachable on port 443 at its own subdomain, with HTTP Auth enabled. This looks legit, since InfluxDB speaks just plain HTTP. 
But this rises the problem: How can i define the HTTP auth credentials in netdata's backend configuration? The example does not consider any kind of proxying, just connecting directly to port 8086.

**Comment by ktsaou** [comment] 2018-06-22 00:14
Hi,

unfortunately netdata does not support influxdb directly. It supports graphite, opentsdb and prometheus. Influxdb has both graphite and opentsdb connectors, so netdata uses them when pushing metrics to influxdb. And unfortunately these protocols do not support authentication.

So, your request is actually an enhancement request to support influxdb http backends.

**Comment by Ehekatl** [comment] 2018-08-07 07:31
same requirement here, basic auth is very essential
I know I can combine graphite and opentsdb with network acl but that's a hassle to manage when you have tons of server running on public network

**Comment by emanzx** [comment] 2018-11-09 04:18
+1 for the influxDB and I would love if can support data tagging too..

**Comment by Kazyini** [comment] 2019-12-17 11:53
+1 For nativ InfluxDB

**Comment by AlexHeylin** [comment] 2020-05-15 20:43
+1 from me too

**Comment by vlvkobal** [comment] 2020-05-15 21:20
@dim08 please pay attention to the number of votes.

**Comment by dim08** [comment] 2020-05-26 14:19
Hi there, we are very sorry for the late response. This is an interesting feature. However due to limited capacity we would like your support. Please feel free to implement an PR.

**Comment by AlexHeylin** [comment] 2020-05-26 22:06
To avoid potentially reinventing the wheel - there is a pending PR for Telegraf which adds Netdata as a data source. Telegraf of course supports InfluxDB as an output. I can confirm the PR works as I'm using it myself.
https://github.com/influxdata/telegraf/pull/2039
Caveat - there does tend to be some differences in the metrics, but usually max() will return data close to the Netdata native. Any development effort might be better spent getting that PR over the line, rather than starting again from the other end.

**Comment by ilyam8** [comment] 2021-07-20 13:46
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).

**Closed by ilyam8** 2021-07-20 13:46 UTC
Labels: area/exporting, data-collection-mteam, feature request, help wanted, priority/medium

**Comment by ilyam8** [comment] 2021-07-26 14:49
@d-mo we will consider this issue when re-evaluating https://github.com/netdata/netdata/issues/8681

I agree that we need to add basic HTTP auth to all exporting destinations if applicable.

**Comment by d-mo** [comment] 2021-07-26 15:06
@ilyam8 Thanks for the heads up. Sounds like a feature that's highly desired by the community and shouldn't be hard to implement. It would also enable us to explore potential integrations between Netdata and Mist.

**Comment by ilyam8** [comment] 2021-07-26 15:26
@d-mo what [exporter](https://github.com/netdata/netdata/tree/master/exporting#features) do you use? prometheus remote write?
