### ISSUE TITLE
Memory leak in python.d.plugin

### ISSUE THREAD

**Issue by fdurand** [netdata/netdata#3817] opened 2018-06-12 20:26 UTC
Hi,
We are using netdata in PacketFence and we encounter a huge memory consumption with python.d.plugin process.
After a while, it can be few hours or few days, the python.d.plugin process start to consume more and more memory on each iteration.

I tried to debug the issue but i wasn't able to point where in the code it happen and which module is causing the issue.

To 'fix' the issue i added gc in the code (https://stackoverflow.com/questions/1316767/how-can-i-explicitly-free-memory-in-python).

```
diff --git a/plugins.d/python.d.plugin b/plugins.d/python.d.plugin
index 957d7e26..ca39cce8 100755
--- a/plugins.d/python.d.plugin
+++ b/plugins.d/python.d.plugin
@@ -11,6 +11,7 @@ echo "ERROR python IS NOT AVAILABLE IN THIS SYSTEM")" "$0" "$@" # '''
 import os
 import sys
 import threading
+import gc
 
 from re import sub
 from sys import version_info, argv
@@ -343,6 +344,7 @@ class Plugin(object):
                 run_and_exit(Logger.info)('FINISHED')
 
             sleep(self.sleep_time)
+           gc.collect()
             self.cleanup()
             self.autodetect_retry()
```
It looks that it works, the process is running since 6 days, but it's a dirty fix.

I am open to test anything that will fix the issue properly.

Thanks!

**Comment by ktsaou** [comment] 2018-06-12 22:31
It would help a lot if you could post the modules your run.

**Comment by l2isbad** [comment] 2018-06-12 23:32
> Memory leak in python.d.plugin

I saw this some time ago on manjaro. The problem modules were modules that starts new threads on every iteration (`dns_query_time`, `elasticsearch` etc). And it was fixed after the nex `python` upgrade.

Another thing is memory consumption very depends on `python` version. it was +40MB of ram after `import yaml` on some versions :cry:

**Comment by fdurand** [comment] 2018-06-13 01:12
For the list of modules:
- apache

```
httpd_aaa:
  name : 'httpd.aaa'
  url  : 'http://localhost:7070/apache_status/?auto'

httpd_webservices:
  name : 'httpd.webservices'
  url  : 'http://localhost:9090/apache_status/?auto'

httpd_portal:
  name : 'httpd.portal'
  url  : 'http://10.0.0.40:1444/modstatus/?auto'

```
- chrony with the default config

- cpufreq with the dwfault config

- dns_query_time (the file is there but not configured yet)

- freeradius

```
radiusauth:
  name: 'Freeradius Auth'
  host: 'localhost'
  port: '18121'
  secret: 'adminsecret'

radiusacct:
  name: 'Freeradius Acct'
  host: 'localhost'
  port: '18122'
  secret: 'adminsecret'
  acct: yes
  proxy_auth: yes
  proxy_acct: yes

radiusloadbalancer:
  name: 'Freeradius LoadBalancer'
  host: 'localhost'
  port: '18123'
  secret: 'adminsecret'
  proxy_auth: yes
  proxy_acct: yes

radiuseduroam:
  name: 'Freeradius Eduroam'
  host: 'localhost'
  port: '18124'
  secret: 'adminsecret'
  proxy_auth: yes

```
- go_expvar (the file is there but not configured yet)
- haproxy 
```
haproxy-portal:
 name : haproxy-portal
 url : 'http://10.0.0.40:1025/stats;csv;norefresh'
 user : 'admin'
 pass : 'packetfence'

haproxy-db:
 name : haproxy-db
 url : 'http://10.0.0.40:1026/stats;csv;norefresh'
 user : 'admin'
 pass : 'packetfence'
```
- mysql
```
pfdb:
  name : 'PacketFence Database'
  user : 'pf'
  pass : 'ZaymeIsMyName'
  host : 'localhost'
```
- postfix (default config)
- redis
```
redis_cache:
  name : 'redis cache'
  host : '127.0.0.1'
  port : 6379

redis_queue:
  name : 'redis queue'
  host : '127.0.0.1'
  port : 6380
```
- web_log
```
autodetection_retry: 10
portal_log:
  name: 'apache portal log'
  path: '/usr/local/pf/logs/httpd.portal.access'

webservices_log:
  name: 'apache webservices log'
  path: '/usr/local/pf/logs/httpd.webservices.access'

aaa_log:
  name: 'apache aaa log'
  path: '/usr/local/pf/logs/httpd.aaa.access'

admin_log:
  name: 'apache admin log'
  path: '/usr/local/pf/logs/httpd.admin.access'
```
An example when the issue occur (python.d.plugin memory and cpu)

![python](https://user-images.githubusercontent.com/1553962/41324494-ca89a3f0-6e82-11e8-8616-5015f928ec36.png)

I am running it on Centos 7 and actually the memory used is 130508 Kb
I also use it on debian Jessie but i have another issue about the initial memory used by python.d.plugin (1157168 Kb with the same config) but it's another problem and i need to investigate.

**Comment by ktsaou** [comment] 2018-06-14 15:13
I understand this is related to the python version installed on this system.

However, I strongly believe we should do something about it. I don't like having this threat on netdata.

Could a module trigger this behaviour? @fdurand is it possible for you to do a binary search to find the plugin causing this?

"binary search" = enable only the first half of the modules. It it happens, then enable half of them again and retry. If it does not happen, enable the other half and retry. This will lead you to the problematic module with the minimum tries.

I know this is a lengthy procedure. I am also open to other ideas...

**Comment by ktsaou** [comment] 2018-06-14 15:15
I marked it as bug, only because I think this is important. Based on the above, we don't have evidence this is triggered by our code.

**Comment by l2isbad** [comment] 2018-06-14 15:53
I am not an expert but this looks strange to me. In general `gc.collect()` is not something you should run manually in most cases.

`gc` module is interface to the optional part of garbage collector (first part is reference counting which cannot be disabled).

It runs periodically based on [thresholds](https://docs.python.org/2/library/gc.html#gc.set_threshold). Defaults threasholds are 700, 10, 10.


If i understand it right algorithm counts objects allocations minus deallocations since the last collection and if diff greater then threashlod it triggers the collection.

//-----------

So if `gc` module is not disabled it should run `gl.collect` periodically.

>  also use it on debian Jessie but i have another issue about the initial memory used by python.d.plugin 

Well, almost all of my vms/servers are debian 7/8/9. No such problem.

`python.d.plugin` uses 13,7 MB of ram deb8 (8.10): `bind_rndc`, `cpufreq`, `isc_dhcpd`, `mysql`, `nginx`, `ntpd`, `ovpn_status_log`, `smartd_log`, `web_log`

**Comment by fdurand** [comment] 2018-06-14 17:47
Ok so i started the binary search but it will propably take days to find the module in cause.

For python i am not an expert but for the last 8 days with the gc.collect in the code the memory didn't changed.

**Comment by ktsaou** [comment] 2018-06-15 08:51
> Ok so i started the binary search but it will propably take days to find the module in cause.

This is good. Let's see if we can isolate this.

**Comment by l2isbad** [comment] 2018-07-09 13:51
Any news on this @fdurand ?

btw about inital memory usage. To reduce it i suggest to set [default_run](https://github.com/firehol/netdata/blob/master/conf.d/python.d.conf#L14) to `no` and explicitly enable modules you are interested in.

**Comment by fdurand** [comment] 2018-07-20 02:24
Sorry for the late reply.
So it's not apache, freeradius or haproxy module.
It's one of mysql , redis or web_log module.
But since i set default_run to no it happen less often.

**Comment by Sheeri** [comment] 2018-09-04 18:34
I am having this issue after having added more collectors that use the MySQL module.

We have done the gc.collect workaround and are still seeing this, although the workaround did reduce our memory leak significantly.

I'm running some tests to see how frequency affects the memory usage.

**Comment by ktsaou** [comment] 2018-09-11 14:11
@Sheeri which distro is this?

**Comment by Sheeri** [comment] 2018-09-11 16:05
@ktsaou package and distro specs:
netdata-1.10.0-1.el7.centos.x86_64
CentOS Linux release 7.5.1804 (Core)

**Comment by paulfantom** [comment] 2018-09-11 16:34
That's strange, we do have a CentOS package but we don't have a maintainer for it? via https://github.com/firehol/netdata/wiki/netdata-package-maintainers

**Comment by Sheeri** [comment] 2018-09-11 16:40
*shrug* we're willing to patch it if that will help - we already applied the gc.collect workaround.

**Comment by ktsaou** [comment] 2018-09-11 17:44
@Sheeri is it possible to use the latest netdata from git? It would help significantly if we can verify this happens with the current code.

Also, is the netdata package you used provided by CentOS or you have installed some other repo?

**Comment by paulfantom** [comment] 2018-09-11 18:43
CentOS doesn't ship netdata.

**Comment by ktsaou** [comment] 2018-09-11 20:43
> @ktsaou I work with Sheeri and we use the provided build-netdata-rpm.sh script to pull down a release and create an rpm from it. Were there any changes made to specific memory/gc features since version 1.10.0?

@l2isbad could you please check?

**Comment by l2isbad** [comment] 2018-09-11 21:00
> Were there any changes made to specific memory/gc features since version 1.10.0?

No

**Comment by l2isbad** [comment] 2018-09-11 23:11
> It looks that it works, the process is running since 6 days, but it's a dirty fix.

Ok, if `gc.collect()` solves the problem i see no reason why to not add it as a temporary fix. We can run it every N iterations (300?).

@paulfantom ?

**Comment by paulfantom** [comment] 2018-09-11 23:18
Generally I am against temporary fixes as they tend to create parts of code which after some time are surrounded by comments like "Magic happens here. Do not touch or it will break.". However if you think this will solve this issue and you will know later why garbage collector is explicitly called (which is discouraged in python), then ok.

**Comment by l2isbad** [comment] 2018-09-11 23:30
> Also it seems that running gc.collect() does not solve the issue:

Somehow i missed that. `It looks that it works, the process is running since 6 days, but it's a dirty fix` is from OP.

**Comment by ktsaou** [comment] 2018-09-12 08:36
I think we should

1. identify the root cause of the problem
2. fix it (if it is ours) or work around it (it is not ours)

Adding `gc.collect()` every 5 mins is a "work around it" and it is perfectly valid for me when "fix it" is not in our control.

So, ideally we should "identify the root cause of the problem". If this is distro related, we should file a bug report at the distro so that the root cause is eliminated.

I find such problems quite important for netdata. If we overlook such problems, people will go away from netdata, considering a "time bomb".

So, what can we do to "identify the root cause of the problem"?

**Comment by ilyam8** [comment] 2019-03-10 19:24
Ok, this is old, we add some changes and there is no new reports about memory leak in python plugins/modules. I am closing this.
If someone experiencing memory leak on latest version please report/reopen.

**Closed by ilyam8** 2019-03-10 19:24 UTC
Labels: area/external, area/external/python, bug, help wanted

**Comment by ilyam8** [comment] 2022-07-13 21:13
Hi, @ipkpjersi. Try `rss` instead of `size`. Or check python.d.plugin memory usage on the dashboard - Applications->mem.

**Comment by ipkpjersi** [comment] 2022-07-14 03:16
```
 ps -eo rss,pid,user,command --sort -size | awk '{ hr=$1/1024 ; printf("%13.2f Mb ",hr) } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' | grep python.d 
43.79 Mb /usr/bin/python3 /opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin 1 
```
