### ISSUE TITLE
[Bug]: Cannot install on FreeBSD with kickstart.sh - Tarball checksum validation failed

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12426] opened 2022-03-16 11:18 UTC
### Bug description

I get the following error:

```
 ABORTED  Tarball checksum validation failed. Usually this is a result of an older copy of the file being cached somewhere upstream and can be resolved by retrying in an hour.
```

Full log:

```
# wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
--2022-03-16 13:15:28--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 104.21.13.159, 172.67.156.192, 2606:4700:3031::6815:d9f, ...
Connecting to my-netdata.io (my-netdata.io)|104.21.13.159|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: '/tmp/netdata-kickstart.sh'

/tmp/netdata-kickstart.sh                    [ <=>                                                                            ]  46.57K  --.-KB/s    in 0.004s  

2022-03-16 13:15:28 (10.2 MB/s) - '/tmp/netdata-kickstart.sh' saved [47685]


 --- Using /tmp/netdata-kickstart-XXXXXXXXXX.1Lr9JJle as a temporary directory. --- 
 --- No existing installations of netdata found, assuming this is a fresh install. --- 
 --- Fetching script to detect required packages... --- 
[/tmp/netdata-kickstart-XXXXXXXXXX.1Lr9JJle]# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-XXXXXXXXXX.1Lr9JJle/install-required-packages.sh https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh 
 OK 

 --- Running downloaded script to detect required packages... --- 
[/tmp/netdata-kickstart-XXXXXXXXXX.1Lr9JJle]# /usr/local/bin/bash /tmp/netdata-kickstart-XXXXXXXXXX.1Lr9JJle/install-required-packages.sh netdata 
 > FreeBSD Version: 12.3-RELEASE ...
 > Checking for gmake ...

We detected these:
Distribution    : freebsd
Version         : 12.3-RELEASE
Codename        : 
Package Manager : install_pkg
Packages Tree   : freebsd
Detection Method: uname
Default Python v: 3 

Searching for distro_sdk ...
Searching for gcc ...
Searching for gxx ...
Searching for autoconf_archive ...
Searching for autogen ...
Searching for libtool ...
Searching for libz_dev ...
Searching for libuuid_dev ...
Searching for libmnl_dev ...
WARNING
package libmnl-dev is not available in this system.

Searching for json_c_dev ...
Searching for libuv ...
Searching for lz4 ...
Searching for openssl ...
Searching for judy ...
Searching for libelf ...
Searching for python3 ...

The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:  pkg update 

pkg install autoconf-archive autogen gcc libtool lzlib openssl 


Press ENTER to run it > 
pkg install autoconf-archive autogen gcc libtool lzlib openssl 
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 16 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	autoconf-archive: 0.2019.01.06
	autogen: 5.18.16_1
	binutils: 2.37_2,1
	boehm-gc: 8.0.6
	boehm-gc-threaded: 8.0.6
	gcc: 10_4
	gcc10: 10.3.0
	gmp: 6.2.1
	guile2: 2.2.7_1
	libltdl: 2.4.6
	libtool: 2.4.6_1
	libxml2: 2.9.12
	lzlib: 1.12
	mpc: 1.2.1
	mpfr: 4.1.0_1
	openssl: 1.1.1m_1,1

Number of packages to be installed: 16

The process will require 496 MiB more space.
85 MiB to be downloaded.

Proceed with this action? [y/N]: y
[1/16] Fetching autoconf-archive-0.2019.01.06.pkg: 100%  390 KiB 399.1kB/s    00:01    
[2/16] Fetching autogen-5.18.16_1.pkg: 100%  625 KiB 639.6kB/s    00:01    
[3/16] Fetching gcc-10_4.pkg: 100%    828 B   0.8kB/s    00:01    
[4/16] Fetching libtool-2.4.6_1.pkg: 100%  357 KiB 365.2kB/s    00:01    
[5/16] Fetching lzlib-1.12.pkg: 100%   42 KiB  43.2kB/s    00:01    
[6/16] Fetching openssl-1.1.1m_1,1.pkg: 100%    4 MiB   2.1MB/s    00:02    
[7/16] Fetching libxml2-2.9.12.pkg: 100%  828 KiB 847.4kB/s    00:01    
[8/16] Fetching guile2-2.2.7_1.pkg: 100%    6 MiB   6.1MB/s    00:01    
[9/16] Fetching gmp-6.2.1.pkg: 100%  477 KiB 488.3kB/s    00:01    
[10/16] Fetching libltdl-2.4.6.pkg: 100%   37 KiB  38.4kB/s    00:01    
[11/16] Fetching boehm-gc-threaded-8.0.6.pkg: 100%  162 KiB 165.9kB/s    00:01    
[12/16] Fetching boehm-gc-8.0.6.pkg: 100%  265 KiB 271.4kB/s    00:01    
[13/16] Fetching gcc10-10.3.0.pkg: 100%   54 MiB   7.1MB/s    00:08    
[14/16] Fetching mpfr-4.1.0_1.pkg: 100%  449 KiB 459.4kB/s    00:01    
[15/16] Fetching mpc-1.2.1.pkg: 100%   88 KiB  89.7kB/s    00:01    
[16/16] Fetching binutils-2.37_2,1.pkg: 100%   17 MiB   4.6MB/s    00:04    
Checking integrity... done (0 conflicting)
[1/16] Installing gmp-6.2.1...
[1/16] Extracting gmp-6.2.1: 100%
[2/16] Installing boehm-gc-8.0.6...
[2/16] Extracting boehm-gc-8.0.6: 100%
[3/16] Installing mpfr-4.1.0_1...
[3/16] Extracting mpfr-4.1.0_1: 100%
[4/16] Installing libltdl-2.4.6...
[4/16] Extracting libltdl-2.4.6: 100%
[5/16] Installing boehm-gc-threaded-8.0.6...
[5/16] Extracting boehm-gc-threaded-8.0.6: 100%
[6/16] Installing mpc-1.2.1...
[6/16] Extracting mpc-1.2.1: 100%
[7/16] Installing binutils-2.37_2,1...
[7/16] Extracting binutils-2.37_2,1: 100%
[8/16] Installing libxml2-2.9.12...
[8/16] Extracting libxml2-2.9.12: 100%
[9/16] Installing guile2-2.2.7_1...
[9/16] Extracting guile2-2.2.7_1: 100%
[10/16] Installing gcc10-10.3.0...
[10/16] Extracting gcc10-10.3.0: 100%
[11/16] Installing autoconf-archive-0.2019.01.06...
[11/16] Extracting autoconf-archive-0.2019.01.06: 100%
[12/16] Installing autogen-5.18.16_1...
[12/16] Extracting autogen-5.18.16_1: 100%
[13/16] Installing gcc-10_4...
[13/16] Extracting gcc-10_4: 100%
[14/16] Installing libtool-2.4.6_1...
[14/16] Extracting libtool-2.4.6_1: 100%
[15/16] Installing lzlib-1.12...
[15/16] Extracting lzlib-1.12: 100%
[16/16] Installing openssl-1.1.1m_1,1...
[16/16] Extracting openssl-1.1.1m_1,1: 100%
=====
Message from gcc10-10.3.0:

--
To ensure binaries built with this toolchain find appropriate versions
of the necessary run-time libraries, you may want to link using

  -Wl,-rpath=/usr/local/lib/gcc10

For ports leveraging USE_GCC, USES=compiler, or USES=fortran this happens
transparently.

All Done! - Now proceed to the next step.

 OK 

[/tmp/netdata-kickstart-XXXXXXXXXX.1Lr9JJle]# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-XXXXXXXXXX.1Lr9JJle/sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt 
 OK 

[/tmp/netdata-kickstart-XXXXXXXXXX.1Lr9JJle]# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-XXXXXXXXXX.1Lr9JJle/netdata-latest.tar.gz https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz 
 OK 

 ABORTED  Tarball checksum validation failed. Usually this is a result of an older copy of the file being cached somewhere upstream and can be resolved by retrying in an hour.

```

### Expected behavior

install netdata

### Steps to reproduce

Run kickstart.

### Installation method

kickstart.sh

### System info

```shell
# uname -a; uname -K
FreeBSD freebsd 12.3-RELEASE FreeBSD 12.3-RELEASE r371126 GENERIC  amd64
1203000
```

### Netdata build info

```shell
Not installed.
```

### Additional info

@Ferroin

**Comment by ktsaou** [comment] 2022-03-16 11:23
@Ferroin I understand this may be a more generic problem. The checksum does not match the source tarball.

**Comment by ilyam8** [comment] 2022-03-16 12:03
Duplicate of #12060

**Closed by ilyam8** 2022-03-16 12:03 UTC
Labels: bug, area/packaging, needs triage, os/bsd
