### ISSUE TITLE
Failed to connect to https://app.netdata.cloud, return code 7

### ISSUE THREAD

**Issue by Martin-Luther** [netdata/netdata#10071] opened 2020-10-14 22:20 UTC
```tty
Netdata user: netdata
Failed to connect to https://app.netdata.cloud, return code 7
```

##### Question summary

I was trying to claim from a machine using only one IPv6 interface (No IPv4)
I can ping and download the agent from `my-netdata.io` which is IPv6 compliant.
I can not ping or claim using `app.netdata.cloud` which is not configured for IPv6, while `netdata.cloud` is.

Could my problem be related to the fact that the subdomain `app.netdata.cloud` is not configured for IPv6 ?

I have done this several times on host with IPv4 without troubles.

##### OS / Environment

Linux myhost 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

##### Component Name
netdata-claim.sh

**Comment by ilyam8** [comment] 2020-10-14 22:52
Hi @Martin-Luther 

Seems duplicate of #10070, closing the issue

**Closed by ilyam8** 2020-10-14 22:52 UTC
Labels: bug, needs triage

**Comment by OdysLam** [comment] 2020-10-15 07:17
Hey @Martin-Luther,

Thanks for pinging us on this issue. As Ilya wrote, we are aware and we work on fixing this. Thanks for bearing with us 💪

BTW, welcome to our community! If you have any other questions please create an issue or even better create a post at our [forums](https://community.netdata.cloud)! :)
