### ISSUE TITLE
Create a Complete Snapshot via API

### ISSUE THREAD

**Issue by mritzmann** [netdata/netdata#8830] opened 2020-04-27 06:56 UTC
##### Question summary

Hi! I don't think my question is too difficult, but I couldn't find anything special about it (except this issue #217). I would like to export a snapshot via API. It should be possible to import the snapshot.

My API request looks like this:

```shell
$ curl "http://localhost:19999/api/v1/data?chart=system.cpu&before=0&after=-600" >> /tmp/test.snapshot
```

In response I receive a JSON file. If I now import the file in Netdata Ui, I get the following error message: `Failed to parse this file!`

If I interpret the JSON file correctly, an export with `/api/v1/data` is not the same as an export via the Ui. Is there a [parameter](https://editor.swagger.io/?url=https://raw.githubusercontent.com/netdata/netdata/master/web/api/netdata-swagger.yaml) I have forgotten? Or maybe there is another way to create an export via curl that I can import later? Thanks & Sorry for the stupid question. Have a nice day!

##### OS / Environment

* Netdata: 1.12.0-1+deb10u1
* OS: Debian 10.3

##### Expected results

Via HTTP request (curl) a file should be exported that can be imported into Netdata Ui later.

**Comment by mritzmann** [comment] 2020-05-12 08:24
I found this https://github.com/netdata/netdata/issues/309#issuecomment-343900018:

> (..) that snapshots are saved on your computer (not the server) and cannot be triggered programmatically.

If this information is still current, this issue is no longer a question but a feature request. :-)

**Comment by ilyam8** [comment] 2020-05-12 09:17
@jacekkolasa please take a look

**Comment by jacekkolasa** [comment] 2020-06-11 20:56
hi @mritzmann , i confirm - the snapshot exported via UI has different structure than `data?chart=` call. It has more other data, like chart metadata, metrics for other charts, hostname, etc. It is unfortunately now impossible to export snapshot without UI. It would be a nice feature to have, i agree!

**Comment by jacekkolasa** [comment] 2020-06-11 20:56
cc @dim08

**Comment by ilyam8** [comment] 2021-07-30 12:32
duplicate of #9872

**Closed by ilyam8** 2021-07-30 12:32 UTC
Labels: area/web, feature request
