### ISSUE TITLE
[Bug]: Netdata experiences slow memory leak

### ISSUE THREAD

**Issue by IDeletedSystem64** [netdata/netdata#12839] opened 2022-05-06 16:53 UTC
### Bug description

Netdata slowly consumes all of the memory on the system. 
Yesterday I was looking at my server, saw that it was using over 6 GB of 8 and Netdata was consuming most of that. (4.4 GB)
On my Debian system, (albeit running a older version) its only using 191 MB (with 3 days uptime) 

### Expected behavior

Netdata to not consume most of the system memory, (normally for me, under 256 MB) 

### Steps to reproduce

1. Install Netdata (via ``pacman -S netdata``)
2. Wait some time (it's been 19 hours since last restart as of reporting.)
3. Run ``systemctl status netdata``, See memory. 
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux borkeonv2 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux
/etc/os-release:NAME="Arch Linux"
/etc/os-release:PRETTY_NAME="Arch Linux"
/etc/os-release:ID=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:LOGO=archlinux-logo
```

### Netdata build info

```shell
Version: netdata v1.34.1
Configure options:  '--prefix=/usr' '--sbindir=/usr/bin' '--sysconfdir=/etc' '--libexecdir=/usr/lib' '--localstatedir=/var' '--with-zlib' '--with-math' '--with-user=netdata' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -flto=auto' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto' 'CXXFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

**Comment by diizzyy** [comment] 2022-05-06 21:19
You should most likely report that to the maintainer for Arch for further debugging, there's also lot of non standard flags used.
Since it seems to accumulate rather quickly I'd disable all plugins and enable one by one until you see the issue or if it still occurs in "barebone" configuration.

**Comment by IDeletedSystem64** [comment] 2022-05-09 01:55
Ight, Where can I view plugins? (I didn't know Netdata supported plugins, but being non-standard flags I want to check)

**Comment by ilyam8** [comment] 2022-05-09 06:54
@IDeletedSystem64 can you:
 - change the time range to the last 6 or 12 hrs.
 - check 'Applications->mem->apps.mem' chart. It will help us to identify which process consumes a lot of memory (e.g.: whether it is `netdata` or one of its external plugins).

**Comment by MrZammler** [comment] 2022-05-09 07:28
Hi @IDeletedSystem64 , is the agent connected to Netdata cloud?

**Comment by IDeletedSystem64** [comment] 2022-05-10 17:03
@ilyam8 
![image](https://user-images.githubusercontent.com/47640864/167683260-edcbaacd-1691-4e65-bba8-bd7b029b93de.png)
Just Netdata consuming the memory.
@MrZammler 
No it isn't.

**Comment by MrZammler** [comment] 2022-05-11 06:52
Hi @IDeletedSystem64 , can you please also share your `netdata.conf` file? Thank you!

**Comment by MrZammler** [comment] 2022-05-12 12:05
Also if possible a copy of the `error.log` file please! Thanks!!

**Comment by IDeletedSystem64** [comment] 2022-05-12 22:20
@MrZammler 
[error.log](https://github.com/netdata/netdata/files/8682866/error.log)
[netdata.conf](https://pastebin.com/JeyZjK0y)

**Comment by MrZammler** [comment] 2022-05-13 07:51
Hi @IDeletedSystem64, it seems perhaps the `error.log` is truncated, there's not much in... Can you also send any `error.log.gz.X` files present in `logs`? Thanks!

**Comment by IDeletedSystem64** [comment] 2022-05-19 00:03
[error.log.9.gz](https://github.com/netdata/netdata/files/8721616/error.log.9.gz)
[error.log.10.gz](https://github.com/netdata/netdata/files/8721617/error.log.10.gz)
[error.log.7.gz](https://github.com/netdata/netdata/files/8721618/error.log.7.gz)
[error.log.8.gz](https://github.com/netdata/netdata/files/8721619/error.log.8.gz)
@MrZammler Here's the past 4, Heads up that I may not be able to perform much more troubleshooting since I'm in the middle of migrating to a new drive (and Fedora, Don't really want to install Arch at the current moment) because of the previous drive starting to show signs of failure X_X

**Comment by MrZammler** [comment] 2022-05-26 14:05
Hi @IDeletedSystem64 !

Sorry, there's not much indication in the logs as to what could be causing the leak.

I see you're running the latest stable, is it possible maybe to switch to a nightly version to see whether it still exhibits the same behavior? Whenever it's possible.

Thanks!

**Comment by IDeletedSystem64** [comment] 2022-06-11 17:57
After running Netdata for approximately two weeks on a fresh Arch installation (with system restarts here and there), there have been no memory leaks, which leads me to believe it could be either something from a previous Netdata version. or something else on the old Arch installation some how causing Netdata to leak memory

**Comment by IDeletedSystem64** [comment] 2022-06-14 13:53
5.17.x, Likely 5.17.5 not exactly sure on which particular version

**Comment by ilyam8** [comment] 2022-06-14 14:07
> two weeks on a fresh Arch installation (with system restarts here and there), there have been no memory leak

Thanks for the information. Closing as "can't reproduce". @thiagoftsm feel free to open if you (somehow) want to keep debugging it.

**Closed by ilyam8** 2022-06-14 14:07 UTC
Labels: bug, Cannot reproduce

**Comment by thiagoftsm** [comment] 2022-06-14 14:44
All right @ilyam8 ,

Today I am still busy with OpenSSL, but I intend to return this week yet to investigate these possible leaks. :handshake:
