### ISSUE TITLE
Can't install from packagecloud on Ubuntu 19.10 (eoan)

### ISSUE THREAD

**Issue by pickscrape** [netdata/netdata#8393] opened 2020-03-12 19:39 UTC
##### Bug report summary

With the packagecloud.io repository set up, I see the latest netdata version to be 1.20.0 (as opposed to the ubuntu repository's 1.16.1-2). However, the package will not install due to missing dependencies:

```
# apt install netdata
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 netdata : Depends: libjson-c3 but it is not installable
           Depends: libprotoc10 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

##### OS / Environment

```
# uname -a; grep -Hv "^#" /etc/*release
Linux lydian 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=19.10
/etc/lsb-release:DISTRIB_CODENAME=eoan
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 19.10"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="19.10 (Eoan Ermine)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 19.10"
/etc/os-release:VERSION_ID="19.10"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=eoan
/etc/os-release:UBUNTU_CODENAME=eoan
```

##### Netdata version

N/A

##### Steps To Reproduce

1. Try to install on Ubuntu 19.10 via packagecloud.

##### Expected behavior

Package installs as expected

**Comment by Ferroin** [comment] 2020-03-12 20:45
Correct deps for 19.10 should be `libjson-c4` and `libprotoc17`.

**Comment by prologic** [comment] 2020-03-13 04:57
This is actually more broken than we realised on Ubuntu 19.10 😳

```sh
root@ubuntu1910:~# dpkg -i /home/prologic/netdata_0.1_amd64.deb
Selecting previously unselected package netdata.
(Reading database ... 69362 files and directories currently installed.)
Preparing to unpack .../prologic/netdata_0.1_amd64.deb ...
Unpacking netdata (0.1) ...
dpkg: dependency problems prevent configuration of netdata:
 netdata depends on libuv1 (>= 1.4.2); however:
  Package libuv1 is not installed.
 netdata depends on libjudydebian1; however:
  Package libjudydebian1 is not installed.
 netdata depends on libnetfilter-acct1; however:
  Package libnetfilter-acct1 is not installed.
 netdata depends on libprotobuf-c1; however:
  Package libprotobuf-c1 is not installed.
 netdata depends on libsnappy1v5; however:
  Package libsnappy1v5 is not installed.
 netdata depends on libprotoc17; however:
  Package libprotoc17 is not installed.
 netdata depends on libprotobuf17; however:
  Package libprotobuf17 is not installed.

dpkg: error processing package netdata (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (242-7ubuntu3.6) ...
Errors were encountered while processing:
 netdata
root@ubuntu1910:~#
```

Still working on it...

**Comment by prologic** [comment] 2020-03-13 05:00
Wait hold on I _might_ have forgotten `dpkg -i` doesn't handle dependencies? 🤔

**Comment by prologic** [comment] 2020-03-13 05:02
Okay I _assume_ this should work:

```sh
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 netdata : Depends: libuv1 (>= 1.4.2) but it is not installed
           Depends: libjudydebian1 but it is not installed
           Depends: libnetfilter-acct1 but it is not installed
           Depends: libprotobuf-c1 but it is not installed
           Depends: libsnappy1v5 but it is not installed
           Depends: libprotoc17 but it is not installed
           Depends: libprotobuf17 but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
root@ubuntu1910:~# ^C
root@ubuntu1910:~#
Get:7 http://au.archive.ubuntu.com/ubuntu eoan/main amd64 libprotoc17 amd64 3.6.1.3-2 [623 kB]
Fetched 1,599 kB in 1s (2,596 kB/s)
Selecting previously unselected package libuv1:amd64.
(Reading database ... 70575 files and directories currently installed.)
Preparing to unpack .../0-libuv1_1.30.1-1_amd64.deb ...
Unpacking libuv1:amd64 (1.30.1-1) ...
Selecting previously unselected package libjudydebian1.
Preparing to unpack .../1-libjudydebian1_1.0.5-5_amd64.deb ...
Unpacking libjudydebian1 (1.0.5-5) ...
Selecting previously unselected package libnetfilter-acct1:amd64.
Preparing to unpack .../2-libnetfilter-acct1_1.0.3-2_amd64.deb ...
Unpacking libnetfilter-acct1:amd64 (1.0.3-2) ...
Selecting previously unselected package libprotobuf-c1:amd64.
Preparing to unpack .../3-libprotobuf-c1_1.3.1-1build1_amd64.deb ...
Unpacking libprotobuf-c1:amd64 (1.3.1-1build1) ...
Selecting previously unselected package libsnappy1v5:amd64.
Preparing to unpack .../4-libsnappy1v5_1.1.7-1_amd64.deb ...
Unpacking libsnappy1v5:amd64 (1.1.7-1) ...
Selecting previously unselected package libprotobuf17:amd64.
Preparing to unpack .../5-libprotobuf17_3.6.1.3-2_amd64.deb ...
Unpacking libprotobuf17:amd64 (3.6.1.3-2) ...
Selecting previously unselected package libprotoc17:amd64.
Preparing to unpack .../6-libprotoc17_3.6.1.3-2_amd64.deb ...
Unpacking libprotoc17:amd64 (3.6.1.3-2) ...
Setting up libprotobuf-c1:amd64 (1.3.1-1build1) ...
Setting up libjudydebian1 (1.0.5-5) ...
Setting up libsnappy1v5:amd64 (1.1.7-1) ...
Setting up libuv1:amd64 (1.30.1-1) ...
Setting up libnetfilter-acct1:amd64 (1.0.3-2) ...
Setting up libprotobuf17:amd64 (3.6.1.3-2) ...
Setting up libprotoc17:amd64 (3.6.1.3-2) ...
Setting up netdata (0.1) ...
dpkg-statoverride: warning: deprecated --force option; use --force-all instead
dpkg-statoverride: warning: --update given but /var/lib/netdata/registry does not exist
Created symlink /etc/systemd/system/multi-user.target.wants/netdata.service → /lib/systemd/system/netdata.service.
Processing triggers for libc-bin (2.30-0ubuntu2) ...
Processing triggers for systemd (242-7ubuntu3.6) ...
root@ubuntu1910:~#
```

Now I just need to push the updated packages up to PackageCloud.

**Comment by prologic** [comment] 2020-03-13 05:05
And its running:

```sh
root@ubuntu1910:~# ps aux | grep netdata
netdata   3552  0.4  2.7 193424 27160 ?        Ssl  05:01   0:00 /usr/sbin/netdata -D
netdata   3756  0.3  0.3   4348  3184 ?        S    05:01   0:00 /usr/libexec/netdata/plugins.d/apps.plugin 1
netdata   3757  0.0  0.0   4604   816 ?        S    05:01   0:00 /usr/libexec/netdata/plugins.d/nfacct.plugin 1
netdata   3759  0.0  1.6 123544 16608 ?        Sl   05:01   0:00 /usr/libexec/netdata/plugins.d/go.d.plugin 1
netdata   3762  0.0  0.3   4084  3200 ?        S    05:01   0:00 bash /usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
root      4023  0.0  0.0   6428   924 pts/0    S+   05:03   0:00 grep --color=auto netdata
root@ubuntu1910:~# curl -qs http://localhost:19999/api/v1/info | grep version
	"version": "v1.20.0-153-gdcc8ba97",
	"os_version": "19.10 (Eoan Ermine)",
	"os_version_id": "19.10",
	"container_os_version": "none",
	"container_os_version_id": "none",
	"kernel_version": "5.3.0-40-generic",
		"_os_version": "19.10 (Eoan Ermine)",
		"_kernel_version": "5.3.0-40-generic",
root@ubuntu1910:~#
```

I've attached the Debian packages here to this issue in case anyone wants to directly install them on Ubuntu 19.10 by hand.

[artifacts.zip](https://github.com/netdata/netdata/files/4327956/artifacts.zip)

**Comment by prologic** [comment] 2020-03-16 05:09
Manually uploaded a `1.20.168` set of Ubuntu eoan packages to our packagecloud repo and it works:

```sh
root@ubuntu1910:~# apt-get update
Hit:1 http://au.archive.ubuntu.com/ubuntu eoan InRelease
Hit:2 http://au.archive.ubuntu.com/ubuntu eoan-updates InRelease
Hit:3 http://au.archive.ubuntu.com/ubuntu eoan-backports InRelease
Hit:4 http://au.archive.ubuntu.com/ubuntu eoan-security InRelease
Get:5 https://packagecloud.io/netdata/netdata-edge/ubuntu eoan InRelease [23.3 kB]
Get:6 https://packagecloud.io/netdata/netdata-edge/ubuntu eoan/main amd64 Packages [18.0 kB]
Fetched 41.3 kB in 8s (5,065 B/s)
Reading package lists... Done
root@ubuntu1910:~# apt-get install netdata
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libjudydebian1 libnetfilter-acct1 libprotobuf-c1 libprotobuf17 libprotoc17 libsnappy1v5 libuv1
The following NEW packages will be installed:
  libjudydebian1 libnetfilter-acct1 libprotobuf-c1 libprotobuf17 libprotoc17 libsnappy1v5 libuv1 netdata
0 upgraded, 8 newly installed, 0 to remove and 57 not upgraded.
Need to get 8,485 kB of archives.
After this operation, 38.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://au.archive.ubuntu.com/ubuntu eoan/main amd64 libuv1 amd64 1.30.1-1 [72.6 kB]
Get:2 http://au.archive.ubuntu.com/ubuntu eoan/universe amd64 libjudydebian1 amd64 1.0.5-5 [94.6 kB]
Get:3 http://au.archive.ubuntu.com/ubuntu eoan/universe amd64 libnetfilter-acct1 amd64 1.0.3-2 [6,968 B]
Get:4 http://au.archive.ubuntu.com/ubuntu eoan/universe amd64 libprotobuf-c1 amd64 1.3.1-1build1 [19.0 kB]
Get:5 http://au.archive.ubuntu.com/ubuntu eoan/main amd64 libsnappy1v5 amd64 1.1.7-1 [16.0 kB]
Get:6 http://au.archive.ubuntu.com/ubuntu eoan/main amd64 libprotobuf17 amd64 3.6.1.3-2 [767 kB]
Get:7 http://au.archive.ubuntu.com/ubuntu eoan/main amd64 libprotoc17 amd64 3.6.1.3-2 [623 kB]
Get:8 https://packagecloud.io/netdata/netdata-edge/ubuntu eoan/main amd64 netdata amd64 1.20.168 [6,887 kB]
Fetched 8,485 kB in 3s (2,722 kB/s)
Selecting previously unselected package libuv1:amd64.
(Reading database ... 69362 files and directories currently installed.)
Preparing to unpack .../0-libuv1_1.30.1-1_amd64.deb ...
Unpacking libuv1:amd64 (1.30.1-1) ...
Selecting previously unselected package libjudydebian1.
Preparing to unpack .../1-libjudydebian1_1.0.5-5_amd64.deb ...
Unpacking libjudydebian1 (1.0.5-5) ...
Selecting previously unselected package libnetfilter-acct1:amd64.
Preparing to unpack .../2-libnetfilter-acct1_1.0.3-2_amd64.deb ...
Unpacking libnetfilter-acct1:amd64 (1.0.3-2) ...
Selecting previously unselected package libprotobuf-c1:amd64.
Preparing to unpack .../3-libprotobuf-c1_1.3.1-1build1_amd64.deb ...
Unpacking libprotobuf-c1:amd64 (1.3.1-1build1) ...
Selecting previously unselected package libsnappy1v5:amd64.
Preparing to unpack .../4-libsnappy1v5_1.1.7-1_amd64.deb ...
Unpacking libsnappy1v5:amd64 (1.1.7-1) ...
Selecting previously unselected package libprotobuf17:amd64.
Preparing to unpack .../5-libprotobuf17_3.6.1.3-2_amd64.deb ...
Unpacking libprotobuf17:amd64 (3.6.1.3-2) ...
Selecting previously unselected package libprotoc17:amd64.
Preparing to unpack .../6-libprotoc17_3.6.1.3-2_amd64.deb ...
Unpacking libprotoc17:amd64 (3.6.1.3-2) ...
Selecting previously unselected package netdata.
Preparing to unpack .../7-netdata_1.20.168_amd64.deb ...
Unpacking netdata (1.20.168) ...
Setting up libprotobuf-c1:amd64 (1.3.1-1build1) ...
Setting up libjudydebian1 (1.0.5-5) ...
Setting up libsnappy1v5:amd64 (1.1.7-1) ...
Setting up libuv1:amd64 (1.30.1-1) ...
Setting up libnetfilter-acct1:amd64 (1.0.3-2) ...
Setting up libprotobuf17:amd64 (3.6.1.3-2) ...
Setting up libprotoc17:amd64 (3.6.1.3-2) ...
Setting up netdata (1.20.168) ...
dpkg-statoverride: warning: deprecated --force option; use --force-all instead
dpkg-statoverride: warning: --update given but /var/lib/netdata/registry does not exist
Created symlink /etc/systemd/system/multi-user.target.wants/netdata.service → /lib/systemd/system/netdata.service.
Processing triggers for systemd (242-7ubuntu3.6) ...
Processing triggers for libc-bin (2.30-0ubuntu2) ...
root@ubuntu1910:~#
```

But I'll have to remove them in case the bumped manual version collides with our CI :/

Hopefully I can get #8397 merged before tomorrow's nightly.

**Comment by dannysauer** [comment] 2020-03-28 19:51
Is this bug actually fixed?  Because it doesn't look that way from my house. ;)

```plaintext
sauer@cerberus:~$ lsb_release -d
Description:	Ubuntu 19.10
sauer@cerberus:~$ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu eoan InRelease
Get:2 http://security.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]      
Get:3 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease [97.5 kB]     
Hit:4 http://archive.canonical.com/ubuntu eoan InRelease                       
Hit:5 http://ppa.launchpad.net/iconnor/zoneminder-1.34/ubuntu eoan InRelease   
Get:6 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease [88.8 kB]   
Hit:7 https://packagecloud.io/netdata/netdata/ubuntu eoan InRelease
Fetched 284 kB in 1s (267 kB/s)
Reading package lists... Done
sauer@cerberus:~$ sudo apt-get install netdata
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 netdata : Depends: libjson-c3 but it is not installable
           Depends: libprotoc10 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by prologic** [comment] 2020-03-31 00:43
Confirmed. Something went wrong here and I apologize. We're in the middle of refactoring the way we build and publish DEB and RPM packages. Still trying to figure out what went wrong here...

**Comment by prologic** [comment] 2020-03-31 02:27
Sorry about this, looks like I missed something in our old/legacy (_soon to be replaced_) CI/CD for native packaging :/ I've put up a PR that hopefully fixes this and I'll confirm it actually does after it gets approved/merged and I see it get published.

**Closed** 2020-04-01 00:24 UTC
Labels: area/packaging, bug

**Comment by dannysauer** [comment] 2020-06-04 13:51
Whoops. I forgot to follow up; this also worked for me. Thanks. :)
