### ISSUE TITLE
PowerDNS plug-in error messages

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#6705] opened 2019-08-21 22:35 UTC
##### Question summary
I'm honestly unsure if this is a bug or not but I'm trying to get the PowerDNS python collector plugin working on the latest Netdata nightly version 'v1.16.1-77-nightly' but I'm receiving errors in the log and via debugging the module in relation to character codes/Unicode. This chart doesn't display.

Netdata Error log:

`2019-08-21 22:57:59: python.d INFO: plugin[checker] : powerdns : checking
2019-08-21 22:57:59: python.d INFO: plugin[checker] : powerdns : source successfully loaded
2019-08-21 22:57:59: python.d INFO: plugin[checker] : powerdns : found config file '/etc/netdata/python.d/powerdns.conf'
2019-08-21 22:57:59: python.d INFO: plugin[checker] : powerdns : created 1 job(s) from the config
2019-08-21 22:57:59: python.d ERROR: powerdns[powerdns_default] : Url: http://127.0.0.1:8081/api/v1/servers/localhost/statistics. Error: 'ascii' codec can't encode character u'\xa3' in position 11: ordinal not in range(128)
2019-08-21 22:57:59: python.d INFO: plugin[checker] : powerdns[powerdns_default] : check failed, skipping the job
2019-08-21 22:57:59: python.d INFO: plugin[checker] : powerdns : all jobs failed, skipping module
`

Debug:

`bash-4.2$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace powerdns
2019-08-21 23:01:09: python.d INFO: plugin[main] : using python v2
2019-08-21 23:01:09: python.d INFO: plugin[main] : starting setup
2019-08-21 23:01:09: python.d INFO: plugin[main] : checking for config in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-08-21 23:01:09: python.d INFO: plugin[main] : config found, loading config '/etc/netdata/python.d.conf'
2019-08-21 23:01:09: python.d INFO: plugin[main] : config successfully loaded
2019-08-21 23:01:09: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
2019-08-21 23:01:09: python.d INFO: plugin[checker] : starting...
2019-08-21 23:01:09: python.d INFO: plugin[checker] : powerdns : checking
2019-08-21 23:01:09: python.d INFO: plugin[checker] : powerdns : source successfully loaded
2019-08-21 23:01:09: python.d INFO: plugin[checker] : powerdns : found config file '/etc/netdata/python.d/powerdns.conf'
2019-08-21 23:01:09: python.d INFO: plugin[checker] : powerdns : created 1 job(s) from the config
2019-08-21 23:01:09: python.d DEBUG: powerdns[powerdns_default] : urllib3 version: 1.25.3
2019-08-21 23:01:09: python.d ERROR: powerdns[powerdns_default] : Url: http://127.0.0.1:8081/api/v1/servers/localhost/statistics. Error: 'ascii' codec can't encode character u'\xa3' in position 11: ordinal not in range(128)
2019-08-21 23:01:09: python.d ERROR: powerdns[powerdns_default] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 120, in _get_raw_data
    status, data = self._get_raw_data_with_status(url, manager, **kwargs)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 149, in _get_raw_data_with_status
    **kwargs
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1074, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib64/python2.7/httplib.py", line 1016, in putheader
    values = [str(v) for v in values]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 11: ordinal not in range(128)

2019-08-21 23:01:09: python.d INFO: plugin[checker] : powerdns[powerdns_default] : check failed, skipping the job
2019-08-21 23:01:09: python.d INFO: plugin[checker] : powerdns : all jobs failed, skipping module
2019-08-21 23:01:09: python.d INFO: plugin[checker] : terminating...
2019-08-21 23:01:09: python.d INFO: plugin[main] : stopping checker process
2019-08-21 23:01:09: python.d INFO: plugin[main] : no modules to run
DISABLE
bash-4.2$ 
`
##### OS / Environment
CentOS7.6 Virtuozzo
WHM/cPanel v82.0.10
PHP 7.3.8
MariaDB 10.3
PowerDNS 4.1.13 

`2019-08-21 22:48:51: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1024, max = 4096
2019-08-21 22:48:51: netdata INFO  : MAIN : Out-Of-Memory (OOM) kept as-is (running with 1000)
2019-08-21 22:48:51: netdata INFO  : MAIN : Running with process scheduling policy 'idle'
2019-08-21 22:48:51: netdata INFO  : MAIN : netdata started on pid 10522.
2019-08-21 22:48:51: netdata INFO  : MAIN : Executing /usr/libexec/netdata/plugins.d/system-info.sh
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_OS_NAME="CentOS Linux"
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_OS_ID=centos
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_OS_ID_LIKE=rhel fedora
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_OS_VERSION=7 (Core)
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_OS_VERSION_ID=7
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_OS_DETECTION=/etc/os-release
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_KERNEL_NAME=Linux
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_KERNEL_VERSION=3.10.0-042stab138.1
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_ARCHITECTURE=x86_64
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_VIRTUALIZATION=none
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_VIRT_DETECTION=systemd-detect-virt
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_CONTAINER=openvz
2019-08-21 22:48:51: netdata INFO  : MAIN : NETDATA_SYSTEM_CONTAINER_DETECTION=systemd-detect-virt
2019-08-21 22:48:51: netdata ERROR : MAIN : Cannot open the file /var/lib/netdata/health.silencers.json (errno 2, No such file or directory)
2019-08-21 22:48:51: netdata INFO  : MAIN : CONFIG: cannot load user config '/etc/netdata/stream.conf'. Will try stock config.
2019-08-21 22:48:51: netdata INFO  : MAIN : Host 'vpsxxxxxx.webhost.com' (at registry as 'vpsxxxxxx.webhost.com') with guid '64f2424e-ab13-11e9-8d59-d566d5314dd2' initialized, os 'linux', timezone 'Europe/London', tags '', program_name 'netdata', program_version 'v1.16.1-77-nightly', update every 1, memory mode save, history entries 3996, streaming disabled (t:
`
##### Component Name
/etc/netdata/python.d/powerdns.conf

`# AUTO-DETECTION JOBS
# only one of them will run (they have the same name)

powerdns_default:
����name: 'local'
����url: 'http://127.0.0.1:8081/api/v1/servers/localhost/statistics'
����header:
���������X-API-Key: '123123123123'
`

##### Expected results

PowerDNS chart to display correctly in Netdata.

**Comment by ilyam8** [comment] 2019-08-22 05:51
Hey @TheOldMan2000 

Please change

https://github.com/netdata/netdata/blob/1a4e81c218d8e56f367b61b17d5f8e71a2cbb40b/collectors/python.d.plugin/python_modules/bases/FrameworkServices/UrlService.py#L153

to 

```python
return response.status, response.data.decode('utf-8', 'ignore')
```

and see if the issue is fixed

**Comment by TheOldMan2000** [comment] 2019-08-22 17:19
Hello @ilyam8 
Thanks for the help! I couldn't find that file so I searched for it and found it at:

`locate UrlService.py
/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py
/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.pyc
`

After amending line 153 as above, I restarted Netdata but it still doesn't show the PowerDNS chart.
I ran the debug on the collector plugin and got:

`bash-4.2$ /usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace powerdns
2019-08-22 18:13:16: python.d INFO: plugin[main] : using python v2
2019-08-22 18:13:16: python.d INFO: plugin[main] : starting setup
2019-08-22 18:13:16: python.d INFO: plugin[main] : checking for config in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-08-22 18:13:16: python.d INFO: plugin[main] : config found, loading config '/etc/netdata/python.d.conf'
2019-08-22 18:13:16: python.d INFO: plugin[main] : config successfully loaded
2019-08-22 18:13:16: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
2019-08-22 18:13:16: python.d INFO: plugin[checker] : starting...
2019-08-22 18:13:16: python.d INFO: plugin[checker] : powerdns : checking
2019-08-22 18:13:16: python.d INFO: plugin[checker] : powerdns : source successfully loaded
2019-08-22 18:13:16: python.d INFO: plugin[checker] : powerdns : found config file '/etc/netdata/python.d/powerdns.conf'
2019-08-22 18:13:16: python.d INFO: plugin[checker] : powerdns : created 1 job(s) from the config
2019-08-22 18:13:16: python.d DEBUG: powerdns[powerdns_default] : urllib3 version: 1.25.3
2019-08-22 18:13:16: python.d ERROR: powerdns[powerdns_default] : Url: http://127.0.0.1:8081/api/v1/servers/localhost/statistics. Error: 'ascii' codec can't encode character u'\xa3' in position 11: ordinal not in range(128)
2019-08-22 18:13:16: python.d ERROR: powerdns[powerdns_default] : Traceback (most recent call last):
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 120, in _get_raw_data
    status, data = self._get_raw_data_with_status(url, manager, **kwargs)
  File "/usr/libexec/netdata/python.d/python_modules/bases/FrameworkServices/UrlService.py", line 149, in _get_raw_data_with_status
    **kwargs
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1074, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib64/python2.7/httplib.py", line 1016, in putheader
    values = [str(v) for v in values]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 11: ordinal not in range(128)

2019-08-22 18:13:16: python.d INFO: plugin[checker] : powerdns[powerdns_default] : check failed, skipping the job
2019-08-22 18:13:16: python.d INFO: plugin[checker] : powerdns : all jobs failed, skipping module
2019-08-22 18:13:16: python.d INFO: plugin[checker] : terminating...
2019-08-22 18:13:16: python.d INFO: plugin[main] : stopping checker process
2019-08-22 18:13:16: python.d INFO: plugin[main] : no modules to run
DISABLE
bash-4.2$ `

**Comment by TheOldMan2000** [comment] 2019-08-22 17:43
Hi again @ilyam8 
I think I may have found the issue. That character code was for a British Pound sign £ and I noticed that there were a few of these within the symbols of the API Key that I had created randomly. 

I replaced the API Key in PowerDNS and then Netdata's PowerDNS python plugin, restarted both PowerDNS and then Netdata, and the chart displayed as soon as refresh the Netdata webpage. I'd also left line 153 as you suggested.

Hope this helps.

**Comment by ilyam8** [comment] 2019-08-22 17:52
> File "/usr/lib64/python2.7/httplib.py", line 1074, in _send_request
self.putheader(hdr, value)
File "/usr/lib64/python2.7/httplib.py", line 1016, in putheader
values = [str(v) for v in values]


Oh, yes, i didnt notice, the error is in `self.putheader(hdr, value)` during request.


> replaced the API Key in PowerDNS
> the chart displayed as soon as refresh the Netdata webpage

Nice! So it is not the bug actually, so i am closing the issue

**Closed** 2019-08-22 17:52 UTC
Labels: area/external/python, question
