### ISSUE TITLE
/etc/cron.daily/netdata-updater: line 101: _cannot_find_tmpdir: command not found

### ISSUE THREAD

**Issue by a-schaefers** [netdata/netdata#10461] opened 2021-01-06 16:24 UTC
After the recent updater broke, we used kickstart.sh --reinstall to fix the updater, but now we get a new error on updates,

```
/etc/cron.daily/netdata-updater
Checking if a newer version of the updater script is available.
Wed Jan  6 10:23:16 CST 2021 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
/etc/cron.daily/netdata-updater: line 101: _cannot_find_tmpdir: command not found
Wed Jan  6 10:23:16 CST 2021 : INFO:  Current Version: 00102800000068
Wed Jan  6 10:23:16 CST 2021 : INFO:  Latest Version: 00102800000068
Wed Jan  6 10:23:16 CST 2021 : INFO:  Newest version (current=00102800000068 >= latest=00102800000068) is already installed
```

Ubuntu 18.04

**Comment by a-schaefers** [comment] 2021-01-06 16:26
Someone else is affected here: https://github.com/netdata/netdata/issues/10372#issuecomment-755383621

**Comment by Ferroin** [comment] 2021-01-06 16:28
For reference, this should not prevent the updater from updating the system in _most_ cases.

I will have a PR to fix it up shortly however.

**Comment by jobenvil** [comment] 2021-01-07 10:13
@Ferroin fighting since last weeks due to netdata and cron spam messages.

Yesterday:

```
/etc/cron.daily/netdata-updater:
/tmp/netdata-updater-j3AjMDJbUQ/netdata-updater.sh: line 354: THIS_SHOULD_BE_REPLACED_BY_INSTALLER_SCRIPT: No such file or directory
run-parts: /etc/cron.daily/netdata-updater exited with return code 1

```

Today morning:
```

/etc/cron.daily/netdata-updater:
/etc/cron.daily/netdata-updater: line 101: _cannot_find_tmpdir: command not found

```
I'm considering to stick to stable since I reinstalled netdata probably 20 times already (having 5 servers). It's little bit annoying. 

Nevertheless thanks for Netdata and taking care so quick & fix.

**Comment by Ferroin** [comment] 2021-01-07 13:45
@jobenvil Apologies for all the issues with the updater recently, a couple of recent changes that were intended to make it simpler for users to recover from updater bugs ironically introduced a slew of bugs, and we’re still dealing with the fallout from that (and it’s been a bit slow because of the holidays).

There’s a PR up to fix this particular issue (the one you are seeing currently) and it will automatically be picked up by the updater once it’s merged. Short-term though the only impact should be the messages on stderr (and the associated emails), updating should otherwise work correctly.

**Closed** 2021-01-12 12:32 UTC
Labels: area/packaging, bug, priority/high

**Comment by gaia** [comment] 2021-01-12 19:06
pls update one of these issues so that we know to manually update. because I let it fail everyday and will only update manually once it is fixed. thanks @Ferroin !

**Comment by Ferroin** [comment] 2021-01-13 12:50
The fix is merged and should be picked up automatically if you have auto-updates enabled.

Otherwise, you should be able to just manually run the (existing) updater script that’s already on your system to get the updated version.

**Comment by gaia** [comment] 2021-01-13 17:09
> The fix is merged and should be picked up automatically if you have auto-updates enabled.

well, the issue is exactly that auto update doesn't update. so this confuses me.
either way, I will manually update. thank you!

**Comment by Ferroin** [comment] 2021-01-13 18:21
> > The fix is merged and should be picked up automatically if you have auto-updates enabled.
> 
> well, the issue is exactly that auto update doesn't update. so this confuses me.
> either way, I will manually update. thank you!

There was also a bug with the update script that was preventing it from working correctly which may have been what you were seeing with auto-updates. A fix has been merged for that too now, so if that was the issue, auto-updates should start working again for you.
