### ISSUE TITLE
data-legend="no" not working

### ISSUE THREAD

**Issue by krnlpanic** [netdata/netdata#3625] opened 2018-04-12 12:25 UTC
I have several charts that work wonderfully, but I want to get rid of the legends on several of them to conserve space.

When I set data-legend="no" the chart doesn't display.  It looks like it's setting a span for the whole chart to zero, as follows:

```
<div class="netdata-container" data-legend="no" ...>
  <span style="position: absolute; opacity:0; width: 0px;>
  ipv4.mcast
  <span>
</div>
```

**Comment by krnlpanic** [comment] 2018-04-12 16:30
Here's the full block of one that's failing to display with data-legend="no".  If I set data-legend="yes" it displays the graph with legend as expected.

```
<div data-netdata="system.load"
  data-host="http://master:19999/host/slave"
  data-title="Load"
  data-chart-library="dygraph"
  data-width="100%"
  data-height="50%"
  data-after="-300"
  data-legend="no"
  ></div>

```

**Comment by ktsaou** [comment] 2018-06-12 01:40
Did you solve it?

It works for me:

![image](https://user-images.githubusercontent.com/2662304/41265360-9c70e970-6dfa-11e8-9729-5222ad2bc2d7.png)

Most probably you need to press control-F5 on your browser, to force it reload your html.

I am closing this, but if you need help, post.

**Comment by BirkhoffLee** [comment] 2019-01-12 11:00
Same to me. When added `data-legend="no"` the chart no longer shows up.

**Comment by cakrit** [comment] 2019-01-14 12:01
@BirkhoffLee can you please let us know the following?

- Netdata version
- Browser
- Device
- OS

**Comment by BirkhoffLee** [comment] 2019-01-14 12:08
@cakrit Of course.

* Netdata version: `v1.11.1_rolling`
* Browser: `Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)`
* Device: `MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)`
* OS: `macOS Mojave 10.14.2 (18C54)`

**Comment by cakrit** [comment] 2019-01-14 16:46
Ok, so I verified that it works when I pass data-legend="no" in a custom dashboard div (i.e. like the tv.html one). Since the issue doesn't yet mention where people are trying to pass the option, can you please tell me what you've changed where so I can try to replicate?

**Comment by BirkhoffLee** [comment] 2019-01-16 08:22
@cakrit I've uploaded full html to https://gist.github.com/BirkhoffLee/25cd9fda0468320257d26bf3a5a0b587#file-netdata-html-L94
Thank you!

**Comment by Macley-Kun** [comment] 2019-01-16 14:17
Hi,
I'm also trying this, but for some reason when adding this option, it will hide it completely. Changeing no to yes shows the grapth, but also the legend sadly.

Full html code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Your dashboard</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <!-- here we will add dashboard.js -->
	<!-- <script>var netdataNoBootstrap = true;</script> -->
	<script type="text/javascript" src="https://gremagol.com/stats/dashboard.js"></script>

</head>
<body>

<!-- here we will add charts -->

	 <!-- remove bottom part to hide the data legend -->
	 <!--data-legend="no"-->
	 
<div data-netdata="cgroup_deltabot.mem_usage"
></div>
<div data-netdata="cgroup_deltabot.mem_activity"
     data-after="80"
     data-before="2"
	 data-width="50%"
     data-height="20%"
	 data-legend="no"
     ></div>

	 <div data-netdata="cgroup_deltabot.mem_activity"
     data-append-options="absolute,percentage"
     ></div>
</body>
<!--
https://gremagol.com/stats/#menu_cgroup_deltabot;after=1547589233000;before=1547589533000;theme=slate;help=true
https://docs.netdata.cloud/web/api/badges/
https://gremagol.com/stats/api/v1/badge.svg?chart=cgroup_deltabot.cpu
https://docs.netdata.cloud/web/gui/custom/#custom-dashboards
-->
</html>
```

**Comment by cakrit** [comment] 2019-01-16 17:45
Found it. The problem is with the data-height. When we give it a %, it doesn't know what to calculate the % on. There are two ways to get it working, either include this div in another div that has a fixed height, or to give data-height something fixed (e.g. 24vh)

I'm sure it will work for you, please close when you verify it.

**Comment by Macley-Kun** [comment] 2019-01-16 18:11
Yup your right, it misses a value in height/width.
I suggest the idea of having a fixed height by default, that can then be alterd using %'s.

I'm very new to this all, so don't take my word for it. But thank you so much for your solution! <3

**Comment by cakrit** [comment] 2019-01-16 19:22
Since it's really easy to just include it in another div or use a fixed height, I'll leave this suggestion from @Macley-Kun  as help wanted.

**Comment by BirkhoffLee** [comment] 2019-01-16 23:40
It works with `data-height` set. Thank you @cakrit

**Comment by Macleykun** [comment] 2021-06-07 19:54
Any update on this?

**Comment by ilyam8** [comment] 2021-07-09 14:37
[The proposed solution](https://github.com/netdata/netdata/issues/3625#issuecomment-454986244) works. @Macleykun if you still have the problem I suggest opening a new bug report with a proper description/steps to reproduce.

**Closed by ilyam8** 2021-07-09 14:37 UTC
Labels: area/web, feature request, help wanted, priority/low
