### ISSUE TITLE
Humongous error.log?

### ISSUE THREAD

**Issue by fakemoth** [netdata/netdata#4312] opened 2018-09-28 16:53 UTC
Hi - I got today an email that some backups (via NFS on a beefy storage) have failed on two of my CentOS 7 servers; I investigated and... no free space on those machines, weird since I have netdata on them and I should be notified, right? And of course I couldn't access netdata. Turns out it was the / partition:
df -h
Filesystem                      Size  Used Avail Use% Mounted on
/dev/mapper/mpatha3              64G   64G   20K 100% /

So hardly running any commands I saw that it was the netdata log:
find /var -type f -printf '%s %p\n'| sort -nr | head -10
65754984448 /var/log/netdata/error.log

Managed to delete the thing, restarted netdata, the same - the file grew and the partition filled up at an astounding rate.
So stopped the service and tried to gather some info because things were running smoothly; but I can't really do anything else as it is eating all of my iops and those are production servers. And logrotate can't do a thing at that rate.

It happens on two different HP servers used as KVM hypervisors, the 3rd one is still fine; on one of them I reinstalled netdata, same thing. I think it's since the last update as it seems the binary (on the other one which I didn't update) has a today print?

ls -lsha netdata
984K -rwxr-xr-x. 1 root root 981K Sep 28 03:25 netdata

So I stopped netdata everywhere as precaution. Did anyone else experience this issue?

**Comment by greatwitenorth** [comment] 2018-10-01 15:13
@fakemoth Yep I had a very similar issue. We run netdata on the cPanel nameserver (Centos 7) and The log file was filling up extremely fast until it consumed all the storage space. Here's the line in the log file:

```
2018-10-01 10:50:14: netdata ERROR : MAIN : Health configuration has invalid line 682 of file '/etc/netdata/health.d/././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././../.././../proc/16456/fd/142/../../named.conf'. It does not contain a ':'. Ignoring it.
```

When I emptied the log file netdata would immediately start filling it up again (at a rate of about 100MB/s) with this line until the storage was full again. I've disabled netdata for now until I figure out what the issue is.

**Comment by paulfantom** [comment] 2018-10-01 16:40
> But the config files were not in their place (/etc/netdata/), not all of them, and there was some weird link; sometime along the road you changed their location as now their path is /usr/lib/netdata/conf.d/ As a personal note I hate when apps are doing windowish stuff putting things all over the place, I don't know what was wrong with /etc/netdata

Yes, we changed them to allow easier upgrade mechanism (shamelessly taken from how systemd handles service files). From now on, netdata will first look for user defined configuration files in `/etc/netdata` and if it won't find such it will look for default configuration files in `/usr/lib/netdata/conf.d/` (which can be overwritten during installation). This allow us not to check if files were changed by a user and just overwrite default config files during upgrade. More in #4182.
We are now using directories `/etc` and `/usr` for what they were historically made for - so it is not "windowish" :smile:

@fakemoth @greatwitenorth did you install netdata via our installation script or from third-party packages? Do you use our [logrotate config](https://github.com/netdata/netdata/blob/master/system/netdata.logrotate.in)?

**Comment by wccropper** [comment] 2018-10-01 17:20
I'm seeing this large error.log file as well. i install with the oneliner git install on CentOS7. I have this installed on 60+ servers, physical and virtual. I use saltstack to manage the configurations. On Friday morning, after the cron.daily updated the systems, 4 of them have this issue. 3 are ESX VMs and one is physical. I can uninstall and once I put my config back on the error.log goes crazy. It spits out lines like the following:

2018-10-01 12:07:21: netdata ERROR : MAIN : Configuration cannot open user-config directory '/etc/netdata/health.d/././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././././..'. (errno 24, Too many open files)

My /etc/security/limits.conf is configured:
*     soft   nofile  4096
*     hard   nofile  65535
root     soft   nofile  4096
root     hard   nofile  65535

**Comment by ktsaou** [comment] 2018-10-01 18:41
This is very strange.

I need to reproduce it.
Until I can reproduce it, I have added a protection to prevent it from descending more than 10 directories, in PR #4342

**Comment by fakemoth** [comment] 2018-10-01 19:50
@paulfantom Thanks for taking the time - yes, I installed via your script bash <(curl -Ss https://my-netdata.io/kickstart.sh) sorry about the "windowish" stuff :) I was very upset at that time, this problem took me by surprise in the middle of upgrades an such...

So it seems it's a bigger problem than I thought - I am reinstalling netdata now for as many servers as I can, I am worried about what will it do on a mariadb server or a centralized storage for example.

**Comment by ktsaou** [comment] 2018-10-01 20:11
I think I fixed it in #4342 
I installed netdata on a centos 7 but couldn't reproduce it.
I compared what previous versions did vs the current one. I found that previous versions where descending on directories only when the directory entry had type `DT_DIR`. But, now we also need to allow links `DT_LNK`.

It seems that on the problematic systems, the filesystem reports `.` and `..` with `DT_LNK`, while we only checked for `DT_DIR` to exclude them. This made netdata think `.` and `..` are directories it should examine.

It should be now fixed. `.` and `..` are always excluded using the same checks we make the descent into directories.

I am very sorry for the frustration...

**Comment by ktsaou** [comment] 2018-10-01 20:13
Waiting for travis to complete to merge it.
I'll let you know to test it.

btw, @fakemoth which filesystem do you use on the servers you found this?

**Comment by fakemoth** [comment] 2018-10-01 20:16
Thanks for the hard work you put into this project @ktsaou. This happened only on XFS at least for me.

**Comment by ktsaou** [comment] 2018-10-01 20:22
merged it.
Could you please update your netdata?

**Comment by ktsaou** [comment] 2018-10-01 20:22
And please report if it works properly now.

**Closed** 2018-10-01 20:22 UTC
Labels: bug, module/core, question

**Comment by fakemoth** [comment] 2018-10-01 20:36
Yes I can confirm it' working just fine on one physical machine and three virtual so I think it is solved.

**Comment by ktsaou** [comment] 2018-10-01 21:16
ok perfect!
thank you for reporting this!

**Comment by ktsaou** [comment] 2018-10-01 23:38
nice.

Keep in mind netdata has a log flood protection. But this is disabled during initialization, to allow you see all the startup logs.

I checked the flood protection works.

I think at instead of disabling it during startup, we should allow a big number of log entries (eg 10000), to avoid flooding everything on such bugs.

**Comment by ktsaou** [comment] 2018-10-02 00:17
Did the above too: https://github.com/netdata/netdata/pull/4344
