### ISSUE TITLE
Temperature Sensor Wrong Number

### ISSUE THREAD

**Issue by ibigbug** [netdata/netdata#9629] opened 2020-07-30 00:14 UTC
##### Bug report summary
The temperature sensor is showing wrong number
![image](https://user-images.githubusercontent.com/543405/88865903-b6343680-d23b-11ea-97f0-367632d6dcbb.png)

##### OS / Environment

```
root@pve:~# uname -a; grep -Hv "^#" /etc/*release  # Linux
Linux pve 5.4.44-1-pve #1 SMP PVE 5.4.44-1 (Fri, 12 Jun 2020 08:18:46 +0200) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

 
root@pve:~# netdata -V
netdata v1.23.2-79-nightly

##### Steps To Reproduce

1. ...
2. ...

##### Expected behavior

The temperature shouldn't go that high, assuming it's Celsius shown in the title.

**Comment by ilyam8** [comment] 2020-07-30 07:25
hi @ibigbug 

duplicate of https://github.com/netdata/netdata/issues/9110

**Closed by ilyam8** 2020-07-30 07:25 UTC
Labels: bug, cloud, duplicate
