### ISSUE TITLE
First characters of plugin names cut off

### ISSUE THREAD

**Issue by arnowelzel** [netdata/netdata#8508] opened 2020-03-26 21:33 UTC
##### Bug report summary

Some names of plugins are cut off - sometimes the first two letters are missing, sometimes only one letter:

"postfix" becames "stfix"
"dovecot" becomes "vecot"
"ts3 "becomes "s3"
"nextcloud" becomes "extcloud"

Screenshot:

![grafik](https://user-images.githubusercontent.com/6613614/77698440-e7aca500-6fb0-11ea-9c24-731b5ae5e541.png)

After removing custom plugins "ts3" and "nextcloud" the problem with "postfix" and "dovecot" still remain:

![grafik](https://user-images.githubusercontent.com/6613614/77698890-ab2d7900-6fb1-11ea-9617-815c9b019f0d.png)

Reinstalling netdata did not change anyhing.

##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

netdata v1.20.0-238-nightly

##### Component Name

web

##### Steps To Reproduce

1. Install netdata using `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
2. Open the dashboard and check the names

##### Expected behavior
Names are output properly.

**Comment by ilyam8** [comment] 2020-03-26 21:42
Hi @arnowelzel 

duplicate of #8490 fixed in #8492

**Closed by ilyam8** 2020-03-26 21:42 UTC
Labels: bug, needs triage
