### ISSUE TITLE
Netdata SNMP will not fetch data if an OID is missing/wrong

### ISSUE THREAD

**Issue by nikobearrr** [netdata/netdata#9580] opened 2020-07-22 05:45 UTC
##### Bug report summary
I have a small router which I would like to get some information from. I would like to fetch uptime and interface status. So far it has worked pretty well. However, for one of the virtual interfaces the OID changes all the time. That is not netdata's fault in any way, but when that happens all the other data (the other interface status AND the uptime) is not collected either. 
I think that in case we have a wrong/non-existing OID netdata shouldn't just say "OID is not valid", but instead should give us a warning and fetch what is possible.
Now I get alerts that everything is down, instead of this virtual interface

##### OS / Environment
docker

##### Netdata version
v1.23.2

##### Component Name
node.d / snmp

##### Steps To Reproduce
1. Setup snmp collection
2. Collect some metrics from some device
3. Purposely put wrong OID (non-existing) and see no data is gathered

##### Expected behavior
I would really love if nevertheless of the issue netdata continues to fetch data

**Comment by cakrit** [comment] 2020-08-07 08:14
You are correct, but fixing this isn't simple at all, because the module doesn't do individual requests for each OID, but sends multiple of them in a single request (see the `slice`  around https://github.com/netdata/netdata/blob/master/collectors/node.d.plugin/snmp/snmp.node.js#L244 ). You can tell when you run the module in debug mode that the entire request fails, if a single OID is problematic. 
Doing it in a different way would require a major redesign, so that we don't sacrifice the speed, for a broken OID. I'm afraid we won't work on this, since the OIDs are entirely under the user's control.

**Comment by ilyam8** [comment] 2020-08-07 11:12
> shouldn't just say "OID is not valid", but instead should give us a warning and fetch what is possible.

i tend to agree, if that is really the case it is not good, i marked that issue as `unread`, will try to look into it on weekend, if it is an easy fix (i dont know nodejs) will try to fix it.

**Comment by nikobearrr** [comment] 2020-08-07 11:19
I haven't really looked into how the node js plugin works and I generally agree with you @cakrit 
However, in this specific case we have a switch which has a virtual interface which tends to change it's OID, at random intervals, sometimes every day, sometimes every week. Surely that is not up to netdata to handle, but once it changed this OID all the data cannot be fetched due to an invalid OID. That is the reason why I brought this issue, but I understand it might not be easy to fix it.

**Comment by ilyam8** [comment] 2020-08-07 11:25
I had same problems with virtual ifaces on linux, i got new oid on every server restart 😅

**Comment by ilyam8** [comment] 2020-08-08 12:20
ok, i tried to reproduce the problem but couldnt

- i created `TEMP_DUMMY` interface

```cmd
[ilyam@ilyam-pc ~]$ sudo ip link add dev TEMP_DUMMY type dummy
[ilyam@ilyam-pc ~]$ sudo ip link set dev TEMP_DUMMY up
...
[ilyam@ilyam-pc ~]$ snmpwalk -v 2c -c public localhost 1.3.6.1.2.1.2.2.1.2
IF-MIB::ifDescr.1 = STRING: lo
IF-MIB::ifDescr.2 = STRING: loopback1
IF-MIB::ifDescr.3 = STRING: Intel Corporation Ethernet Connection (7) I219-V
IF-MIB::ifDescr.4 = STRING: Realtek Semiconductor Co., Ltd. RTL8188CE 802.11b/g/n WiFi Adapter
IF-MIB::ifDescr.5 = STRING: docker0
IF-MIB::ifDescr.6 = STRING: br-e778654af11a
IF-MIB::ifDescr.7 = STRING: br-ee8f2f7b4466
IF-MIB::ifDescr.8 = STRING: TEMP_DUMMY
```

- created `snmp.conf` (collect `ifHCInOctets` and `ifHCOutOctets`)

```json
{
    "enable_autodetect":false,
    "update_every":1,
    "max_request_size":100,
    "servers":[
        {
            "hostname":"127.0.0.1",
            "community":"public",
            "update_every":1,
            "max_request_size":50,
            "options":{
                "version":1
            },
            "charts":{
                "snmp.bandwidth_iface_lo":{
                    "title":"Bandwidth iface lo",
                    "units":"Mb/s",
                    "type":"area",
                    "priority":1,
                    "context":"snmp.bandwidth",
                    "family":"Interfaces",
                    "dimensions":{
                        "in":{
                            "oid":"1.3.6.1.2.1.31.1.1.1.6.1",
                            "algorithm":"incremental",
                            "multiplier":8,
                            "divisor":1000000,
                            "offset":0
                        },
                        "out":{
                            "oid":"1.3.6.1.2.1.31.1.1.1.10.1",
                            "algorithm":"incremental",
                            "multiplier":8,
                            "divisor":1000000,
                            "offset":0
                        }
                    }
                },
                "snmp.bandwidth_iface_temp":{
                    "title":"Bandwidth iface temp",
                    "units":"Mb/s",
                    "type":"area",
                    "priority":1,
                    "context":"snmp.bandwidth",
                    "family":"Interfaces",
                    "dimensions":{
                        "in":{
                            "oid":"1.3.6.1.2.1.31.1.1.1.6.8",
                            "algorithm":"incremental",
                            "multiplier":8,
                            "divisor":1000000,
                            "offset":0
                        },
                        "out":{
                            "oid":"1.3.6.1.2.1.31.1.1.1.10.8",
                            "algorithm":"incremental",
                            "multiplier":8,
                            "divisor":1000000,
                            "offset":0
                        }
                    }
                }
            }
        }
    ]
}
```

- restarted `netdata.service`

There are two charts on the dashboard: in/out for `lo` and `temp` interfaces

- deleted `TEMP_DUMMY` interface

```cmd
[ilyam@ilyam-pc ~]$ sudo ip link del dev TEMP_DUMMY
```

- checked the dashboard

No problems with charts, i see `snmp` section

<img width="1259" alt="Screenshot 2020-08-08 at 15 14 51" src="https://user-images.githubusercontent.com/22274335/89710260-f0af7900-d989-11ea-8375-75c74f447a29.png">


Interesting result: `TEMP_DUMMY` chart was not frozen.

---

I had another instance of `node.d.plugin` running in debug mode

 - before deleting iface

```cmd
BEGIN snmp.bandwidth_iface_lo 1004000
SET in = 0x5fce82
SET out = 0x5fce82
END

BEGIN snmp.bandwidth_iface_temp 1004000
SET in = 0x00
SET out = 0x0230
END

BEGIN snmp.bandwidth_iface_lo 1004000
SET in = 0x5fce82
SET out = 0x5fce82
END

BEGIN snmp.bandwidth_iface_temp 1004000
SET in = 0x00
SET out = 0x0230
END
```

- after deleting iface

```cmd
2020-08-08 15:03:34: node.d.plugin: ERROR: snmp: 127.0.0.1: OID 1.3.6.1.2.1.31.1.1.1.6.8 gave error: NoSuchInstance: 1.3.6.1.2.1.31.1.1.1.6.8
BEGIN snmp.bandwidth_iface_lo 1003000
SET in = 0x5fd50c
SET out = 0x5fd50c
END

BEGIN snmp.bandwidth_iface_temp 1003000
SET in = 0x00
SET out = 0x0230
END

2020-08-08 15:03:35: node.d.plugin: ERROR: snmp: 127.0.0.1: OID 1.3.6.1.2.1.31.1.1.1.6.8 gave error: NoSuchInstance: 1.3.6.1.2.1.31.1.1.1.6.8
BEGIN snmp.bandwidth_iface_lo 1003000
SET in = 0x5fd50c
SET out = 0x5fd50c
END
```

What is interesting is there only one error (`ifHCInOctets`):

> 2020-08-08 15:03:34: node.d.plugin: ERROR: snmp: 127.0.0.1: OID 1.3.6.1.2.1.31.1.1.1.6.8 gave error: NoSuchInstance: 1.3.6.1.2.1.31.1.1.1.6.8


There is no complains about `1.3.6.1.2.1.31.1.1.1.10.8` (`ifHCOutOctets`)

It could be that `snmp` module skips rest OIDs for a chart right after the error 🤔

**Comment by ilyam8** [comment] 2020-08-08 12:32
> It could be that snmp module skips rest OIDs for a chart right after the error 🤔

No, it doesnt. I pull everything in one chart (in_temp, out_temp, in_lo, out_lo), despite the error module keeps collecting `lo` iface data.

**Comment by ilyam8** [comment] 2020-08-08 13:17
> There is no complains about 1.3.6.1.2.1.31.1.1.1.10.8 (ifHCOutOctets)

It is because of broken (i think?) log flood control

https://github.com/netdata/netdata/blob/3d33eea007967ffe70f7918e6b617366cb34dd28/collectors/node.d.plugin/node_modules/netdata.js#L174

error log function

https://github.com/netdata/netdata/blob/3d33eea007967ffe70f7918e6b617366cb34dd28/collectors/node.d.plugin/node_modules/netdata.js#L287-L294

---

So it **only logs one error** during collect, all other errors log as debug messages.

**Comment by ilyam8** [comment] 2020-08-08 13:31
@nikobearrr 

> ./node.d.plugin debug

**Comment by nikobearrr** [comment] 2020-08-08 16:10
Hi @ilyam8 , thank you for the effort.
I will come back to you with debug data as soon as possible

**Comment by cakrit** [comment] 2020-08-10 09:02
The interesting thing to verify is this: Given X OIDs to collect, Y SNMP get request should be done, with X < Y. Say X=6 and Y=2, so each request attempts to get data for 3 OIDs (don't know how exactly the array is getting spliced to tell you the truth, so this is hypothetical). If an invalid OID exists in the first request, all 3 OIDs should return no value. But if the other 3 OIDs in the second request are valid, they should return values. Is it what really happens? I had just verified with 2 OIDs in a single request. 

Assuming that's how it works, then the only options to get all available data are:
A: Upon failure, remove the offending OID completely and splice the arrays again
B: Have a setting to allow fetching OIDs one by one (i.e. X=Y on the example above).

Another alternative would be to extend the collector, so that it can do an SNMP walk, instead of a get. That's actually an even better solution, that would generically handle dynamic OIDs. But to assign meaning to those metrics (i.e. to get a dimension name), you need some additional logic. 

Instead of messing with the node.js SNMP collector, I would opt for a completely new SNMP collector in go, built on top of an open source project built by people who know their SNMP. A proper solution would be able to ingest MIBs and - when we extend netdata to accept events - handle SNMP traps as well.

**Comment by nikobearrr** [comment] 2020-08-10 09:16
@ilyam8 

This is the exception I get:

```
2020-08-10 09:01:25: node.d.plugin: ERROR: snmp: 192.168.2.1: Received error = { RequestFailedError: NoSuchName: 1.3.6.1.2.1.2.2.1.8.13
    at Req.Session.onSimpleGetResponse [as onResponse] (/usr/libexec/netdata/node.d/node_modules/net-snmp.js:1844:25)
    at Session.onMsg (/usr/libexec/netdata/node.d/node_modules/net-snmp.js:1806:21)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage [as onmessage] (dgram.js:628:8)
  name: 'RequestFailedError',
  message: 'NoSuchName: 1.3.6.1.2.1.2.2.1.8.13',
  status: 2 } varbinds = undefined
2020-08-10 09:01:25: node.d.plugin: ERROR: named: local: Failed to make request, message: connect ECONNREFUSED 127.0.0.1:8888

```

When I run the `node.d.plugin debug` command I cannot see anything related to this device. It seems the snmp module makes a new check when starting as it does not even create the charts.

**Comment by ilyam8** [comment] 2020-08-10 09:31
ok, that is another error `NoSuchName`, in my tests it was `NoSuchInstance`

this branch

https://github.com/netdata/netdata/blob/9954ccf952893428475e7b3da58b8df57659fd13/collectors/node.d.plugin/snmp/snmp.node.js#L245-L251

my tests branch

https://github.com/netdata/netdata/blob/9954ccf952893428475e7b3da58b8df57659fd13/collectors/node.d.plugin/snmp/snmp.node.js#L252-L266

**Comment by nikobearrr** [comment] 2020-08-16 16:59
I am not fully aware to the full extend of the SNMP protocol.
Could this result be device based? My configuration is the same (excluding different interfaces + uptime). However it seems I get an `error` and you get pass this. 
In general it does not look like it's a netdata issue at all and probably there is not much you guys can do. 

Perhaps I can do what @cakrit suggests and try to split it in some way. In that case if only this failing one fails then the others do not need to fail. 
For the specific issue I have I have contacted the vendor and explained them the issue. Hopefully they are able (and willing to fix it). 

From my side I do not think there is more on this topic. If you (the netdata) team decides you want to keep it as reference/feature request to some of the mentioned points that is fine to me, otherise you can close it.

Thank you for the time you spent on this with me

**Comment by cakrit** [comment] 2020-08-18 09:50
Just to explain why a specific OID can work today and fail tomorrow, a lot of indexes are dynamic and could even [contain gaps](https://www.ibm.com/support/pages/discovery-does-not-handle-gaps-oids-returned-snmp-agent). So e.g. I could have OID a.b.x, where x identifies one of three possible devices. Depending on how the manufacturer decides which value identifies which device, it's possible that the same device could appear with a different value for x (I'm making this up, but really, there are no rules here, it's up to the manufacturer and one needs to read their MIB and perhaps other docs to understand what they do). 

But I think you're right to complain about it @nikobearrr , it would make sense for the same device to always produce metrics with the same OIDs. 

I changed this to a feature request, we do need to get a bit more serious about SNMP at some point. We would of course appreciate any contributions here!

**Comment by ilyam8** [comment] 2021-07-27 14:57
Closing this feature request. We will re-evaluate the request internally.

Related https://github.com/netdata/netdata/issues/9406

**Closed by ilyam8** 2021-07-27 14:57 UTC
Labels: area/external, data-collection-mteam, feature request, help wanted, wontfix
