### ISSUE TITLE
Netdata in master/slave deployment losing metrics after restart

### ISSUE THREAD

**Issue by AaronRobinson** [netdata/netdata#7360] opened 2019-11-23 09:02 UTC
##### Bug report summary
Please see #7303 
I have a maser/slave deploy. I had been losing metrics because Netdata determined that data was redundant during a restart of multiple nodes. I switched to using dbengine memory mode and this seemed to address the issue. This morning I discovered the issue again. Metrics missing before ~6:30. I *think* my netdata estate is being restarted due to the Netdata log rotation as part of cron daily. Sorry for raising as a new issue - couldn't see how to reopen the original.

##### OS / Environment
Ubuntu

##### Netdata version (ouput of `netdata -V`)
netdata v1.18.1-161-nightly

##### Expected behavior
Metrics aren't lost

Happy to email full logs. This is some of what I'm seeing: -

```
2019-11-23 06:25:53: netdata ERROR : STREAM_RECEIVER[my-server,[my-ip]:39402] : read failed: end of file
2019-11-23 06:25:53: netdata ERROR : STREAM_RECEIVER[my-server,[my-ip]:39402] : STREAM my-server [receive from [my-ip]:39402]: disconnected (completed 26185080 updates).
2019-11-23 06:25:53: netdata INFO  : STREAM_RECEIVER[my-server,[my-ip]:39402] : STREAM my-server [receive from [my-ip]:39402]: receive thread ended (task id 11947)
2019-11-23 06:25:53: netdata INFO  : STREAM_RECEIVER[my-server,[my-ip]:39402] : thread with task id 11947 finished
2019-11-23 06:25:56: netdata INFO  : MAIN : SIGNAL: Received SIGTERM. Cleaning up to exit...
2019-11-23 06:25:56: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 0...
2019-11-23 06:25:56: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'EXIT' 'OK' '-'
2019-11-23 06:25:57: netdata INFO  : MAIN : EXIT: cleaning up the database...
2019-11-23 06:25:57: netdata INFO  : MAIN : Cleaning up database [6 hosts(s)]...
2019-11-23 06:25:57: netdata INFO  : MAIN : Cleaning up database of host 'server-1'...
2019-11-23 06:25:57: netdata INFO  : MAIN : Cleaning up database of host 'server-2'...
2019-11-23 06:25:57: netdata INFO  : MAIN : Deleting database of host 'my-server'...
...
```

**Comment by thiagoftsm** [comment] 2019-11-23 12:49
Hi @AaronRobinson ,

What are the values you are using for the `dbengine` variables https://docs.netdata.cloud/database/engine/#configuration? 

In the same link that I already gave in the previous question, there is a section talking about file descriptors https://docs.netdata.cloud/database/engine/#file-descriptor-requirements, please, can you also try to adjust it.

**Comment by mfundul** [comment] 2019-11-23 13:10
It appears that the problem persists. I suggest doing the following and hopefully it's a permanent solution.

Keep both the localhost and the slaves at `memory mode = dbengine`.

Set `delete obsolete charts files` and `delete orphan hosts files` to `no`. See [here](https://docs.netdata.cloud/daemon/config/).

You should never have this problem again. @thiagoftsm we should discuss the decision making of `streaming` and deleting slaves host databases.

**Comment by AaronRobinson** [comment] 2019-11-23 13:11
dbengine values are left to default
I had followed the link previously and set the FD limits using `sudo systemctl edit netdata` and set the contents to ```[Service]
LimitNOFILE=65536```
I also see this in the logs `2019-11-23 06:25:59: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 65536, max = 65536`

**Comment by mfundul** [comment] 2019-11-23 13:28
@AaronRobinson I'm closing this as a duplicate of #7303. Please follow my [suggestion](https://github.com/netdata/netdata/issues/7360#issuecomment-557796791) and report in the other issue.

**Closed by mfundul** 2019-11-23 13:28 UTC
Labels: area/database, bug, duplicate
