### ISSUE TITLE
pfSense cannot currently install netdata version 1.17.1

### ISSUE THREAD

**Issue by lordcantide** [netdata/netdata#7030] opened 2019-10-08 21:33 UTC
##### Bug report summary
netdata version 1.17.1 service will not start after upgrade from 1.15
running command "/usr/local/sbin/netdata" generates the following error:
-Shared object "libjson-c.so.4" not found, required by "netdata"

The file appears related to the json-c library dependency and is apparently supposed to be optional for netdata. The current stable release of pfSense distributes with json-c version 0.13, but patch 0.13.1 changelog references a version bump which appears related to this issue. It is unclear when pfSense will distribute a package update given that the relevant update was ported to FreeBSD 5/Sept/2018.

##### OS / Environment
pfSense 2.4.4-RELEASE-p3

##### Netdata version (ouput of `netdata -V`)
Does not run. See error in summary.

##### Steps To Reproduce
1) Remove netdata version 1.15 and old dependencies.
2) Reinstall using instructions documented here - https://docs.netdata.cloud/packaging/installer/#pfsense
3) Edit "bind to" in netdata.conf
4) Attempt to "service netdata onestart" without errors.
5) Check "service netdata onestatus" to verify that service is not running.
6) Run "/usr/local/sbin/netdata" to confirm error in summary.

##### Expected behavior
netdata service will start.

**Comment by thiagoftsm** [comment] 2019-10-09 13:39
Hi @lordcantide ,

Thank you for your report, I already could see that our documentation is missing important information about the installation for 1.17.1:

![VirtualBox_pfsense_09_10_2019_13_36_10](https://user-images.githubusercontent.com/49162938/66486445-1fbf3a80-ea9a-11e9-8a74-7dc17491c052.png)

It is also possible that our image has not been compiled correctly, we are studying the case and we will release the fix ASAP.

Best regards

**Comment by thiagoftsm** [comment] 2019-10-09 14:03
Confirming what I said before, we have problem in the documentation and our machine that generates the image are not compatible with 1.17.1, another thing, the source of the package is not kept by Netdata it is kept by Netdata team (pkg.freebsd.org), I will talk with our team to regenerate the packages and I will contact the FreeBSD team for we fix this.
Finally, here is the last output after I detect problem with packages:

![VirtualBox_pfsense_09_10_2019_13_59_13](https://user-images.githubusercontent.com/49162938/66488525-9578d580-ea9d-11e9-9e2a-608abd7db6fe.png)

**Comment by diizzyy** [comment] 2019-10-09 14:19
This is not a bug as pfsense doesn't use FreeBSD's package repo by default
https://docs.netgate.com/pfsense/en/latest/packages/installing-freebsd-packages.html

**Comment by thiagoftsm** [comment] 2019-10-09 14:25
Hi @lordcantide ,

While we are fixing the problems here, I verified that I can run Netdata case I run the three commands on pfSense:

```
pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/Judy-1.0.5_2.txz
ln -s /usr/local/lib/libjson-c.so /usr/local/lib/libjson-c.so.4
pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/netdata-1.17.1.txz
```

Best regards!

**Comment by lordcantide** [comment] 2019-10-09 16:37
@thiagoftsm ,
Thanks for mentioning the Judy package dependency! I got down in the weeds of troubleshooting the issue with json-c that I forgot to include that as a missing instruction.
I can confirm that the workaround instructions above have me back up and running. Thank you for your help.
Follow-up question: Is the link command in your instructions a hotfix or the committed change in json-c 0.13.1? I tested that it remains after a pkg remove just like similar links I assume are part of the same json-c package. Normally, I operate inside jails to mask my passing knowledge of packages, FreeBSD, and pfSense for this sort of stuff.

Cheers!

**Comment by thiagoftsm** [comment] 2019-10-09 18:41
I am glad that everything is working now in your side. :)
For while it is a hotfix, I already said for our devops guys to take care about this, but I decided to give this already to avoid you stay without the newest Netdata.
I also created  a PR to fix the documentation, but It does not fix the main problem as I wrote in the PR.

**Comment by amoss** [comment] 2019-10-10 07:02
Testing this on a fresh pfSense 2.4.4-RELEASE I don't see the same issue. The system is slightly different (I will try the `-p3` update next):

```
> pkg info | grep json-c
json-c-0.13   JSON (JavaScript Object Notation) implementation in C
> ls -l /usr/local/lib/libjson-c.so
lrwxr-xr-x 1 root wheel 18 Oct 3 2018 libjson-c.so -> libjson-c.so.3.0.1
```
So the library is one point-release older and the link is installed. The ABI version on the library is different to what you are seeing (`.3` instead of `.4`). I will do the `-p3` upgrade next and see if it pulls in a broken install of the json-c library. Something that looks strange on the system (I'm not familiar with pfSense) is that the ldconfig cache is empty and cannot be regenerated?
```
> ldconfig -r
/var/run/ld-elf.so.hints:
    search directories:
> ldconfig -R
> ldconfig -r
/var/run/ld-elf.so.hints:
    search directories:
```
This is completely different to FreeBSD so there must be a difference in their packaging system.

**Comment by lordcantide** [comment] 2019-11-05 20:37
Sorry for the slow reply @amoss but I'm not sure why your ldconfig is empty. Mine has 220 lines in it. Additionally, -p3 is the current stable release of pfSense. Is there something more I can inspect on my install for you?

**Comment by amoss** [comment] 2019-11-05 20:53
Hello @lordcantide, thanks for replying but I don’t think that we need any more information. The comment was more to help @thiagoftsm diagnose which versions were affected. I think the comment was part of the review of his PR. I remember setting the box up to test the hotfix, but I can’t remember why it was recorded here instead of inside the PR.

**Comment by thiagoftsm** [comment] 2019-11-07 17:33
We are closing this now and we will work to bring packages for pfSense, because FreeBSD and pfSense are not working more with the same library version.

**Closed by thiagoftsm** 2019-11-07 17:33 UTC
Labels: bug
