### ISSUE TITLE
Net drops warnings going red

### ISSUE THREAD

**Issue by TetrisWolf** [netdata/netdata#8985] opened 2020-05-12 11:56 UTC
Using Ubuntu Server 20.04LTS on Intel NUC BEH2 intel core i3

I get warnings for netdrops and packetloss.
If i do ifconfig i get RX drops.

how do I fix this or is this no bug/issue?

![netdata](https://user-images.githubusercontent.com/65229847/81684935-bf411300-9457-11ea-9c6a-a6e3589359d2.PNG)
![Capture](https://user-images.githubusercontent.com/65229847/81685188-2c54a880-9458-11ea-8a12-82cd8cf3378c.PNG)

**Comment by TetrisWolf** [comment] 2020-05-12 12:51
1Hour later and keeps rising drops and warnings
![89722184_3109846059048870_3190492253692887040_o](https://user-images.githubusercontent.com/65229847/81693320-06cb9d00-9460-11ea-9a95-f92cbc00140d.jpg)

**Comment by TetrisWolf** [comment] 2020-05-12 13:02
i Found some drops using the DropWatch, but i still dont know how to fix them... Or cant i fix them?
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
8 drops at netlink_broadcast_filtered+257 (0xffffffff8639f0e7)
3 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
1 drops at __udp4_lib_rcv+ae5 (0xffffffff863e9da5)
1 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
3 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
1 drops at __udp4_lib_rcv+ae5 (0xffffffff863e9da5)
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
2 drops at __udp4_lib_rcv+ae5 (0xffffffff863e9da5)
2 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
1 drops at __udp4_lib_rcv+ae5 (0xffffffff863e9da5)
1 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)
1 drops at __netif_receive_skb_core+14e (0xffffffff8633411e)

**Comment by ilyam8** [comment] 2020-05-12 14:06
It is hard to identify the cause, but i would use `tcpdump`.

**Comment by TetrisWolf** [comment] 2020-05-12 14:52
> It is hard to identify the cause, but i would use `tcpdump`.

it now keeps repeating the same very fast..
![Capture](https://user-images.githubusercontent.com/65229847/81707529-01c31980-9471-11ea-809f-8812544ffdc7.PNG)

**Comment by TetrisWolf** [comment] 2020-05-12 15:03
> > It is hard to identify the cause, but i would use `tcpdump`.
> 
> it now keeps repeating the same very fast..
> ![Capture](https://user-images.githubusercontent.com/65229847/81707529-01c31980-9471-11ea-809f-8812544ffdc7.PNG)

i just changed the ip of that device and all rx drops are gone, uh ok? thx for the help!

**Comment by TetrisWolf** [comment] 2020-05-12 15:13
and after 10minutes it came back -_-

**Comment by TetrisWolf** [comment] 2020-05-12 15:16
![Capture](https://user-images.githubusercontent.com/65229847/81711823-4b613380-9474-11ea-89f6-79ba870cf36f.PNG)

**Comment by TetrisWolf** [comment] 2020-05-12 15:34
if tcpdump runs everything will slowly descend and be okay.
Does this mean i should make a startup script for tcpdump?

**Comment by ilyam8** [comment] 2020-05-12 15:59
> if tcpdump runs everything will slowly descend and be okay.


Yes, if you run tcpdump there is no drops.

I advised tcpdump to check rx traffic - probably your server connected via trunk port and there is vlan tagged traffic goes through it and your srv drops it. 


> Does this mean i should make a startup script for tcpdump?

No, you use it to check rx traffic and find what is being dropped.

___

I am closing the issue because there is no bug in Netdata.

**Closed by ilyam8** 2020-05-12 15:59 UTC
Labels: question
