### ISSUE TITLE
There is no ebpf.plugin on uos(based on Debian 10)

### ISSUE THREAD

**Issue by wangpei-nice** [netdata/netdata#10998] opened 2021-04-20 09:02 UTC
##### Bug report summary

I can't find ebpf.plugin after install netdata(v1.12.0, using 'apt install') 
![image](https://user-images.githubusercontent.com/81410079/115368071-53376500-a1f9-11eb-863c-e9f318f5324b.png)
![image](https://user-images.githubusercontent.com/81410079/115370135-592e4580-a1fb-11eb-8760-45eb85e296d2.png)

There is no netdata-kernel-collector deb on debian, is this the reason why I can't find the ebpf.plugin?

##### OS / Environment

OS: UnionTech OS Desktop 20 Pro (based on Debian 10)
kernel: 4.19.0
 

##### Expected behavior

There will be any info about ebpf.plugin when exec 'systemctl status netdata' or 'ps -elf | grep ebpf.plugin

**Comment by thiagoftsm** [comment] 2021-04-20 14:03
@Ferroin  are we delivering the `ebpf.plugin` with our debian repo?

@wangpei-nice did you use our [repo](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages) to install the packages?

**Comment by Ferroin** [comment] 2021-04-20 15:38
> @Ferroin are we delivering the `ebpf.plugin` with our debian repo?

AFAICT we should be.

Any third-party packages will lack it though unless they go out of their way to support it.

**Comment by ilyam8** [comment] 2021-04-20 15:51
@wangpei-nice hey, the reason is using pretty old version of Netdata Agent.

Steps to _fix_ the issue:
 - uninstall netdata v1.12.0
 - install latest stable [using our repository](https://packagecloud.io/netdata/netdata)

**Comment by Ferroin** [comment] 2021-04-20 16:18
> @wangpei-nice hey, the reason is using pretty old version of Netdata Agent.
> 
> Steps to _fix_ the issue:
> 
> * uninstall netdata v1.12.0
> * install latest stable [using our repository](https://packagecloud.io/netdata/netdata)

@joelhans Just thought of this, but perhaps we need to look at listing in our documentation what version of Netdata a given collector/plugin/feature was originally added in? Possibly just something near the top of the page about the feature/collector mentioning a minimum version needed to use it.

**Comment by ilyam8** [comment] 2021-04-21 08:23
Closing the issue since it is not a bug, @wangpei-nice you need to [update your Netdata Agent](https://packagecloud.io/netdata/netdata).

**Closed by ilyam8** 2021-04-21 08:23 UTC
Labels: question

**Comment by wangpei-nice** [comment] 2021-04-21 09:29
@ilyam8 

> @wangpei-nice hey, the reason is using pretty old version of Netdata Agent.
> 
> Steps to _fix_ the issue:
> 
> * uninstall netdata v1.12.0
> * install latest stable [using our repository](https://packagecloud.io/netdata/netdata)

Thanks for your help, I have fix it.

**Comment by wangpei-nice** [comment] 2021-04-21 09:46
> @Ferroin are we delivering the `ebpf.plugin` with our debian repo?
> 
> @wangpei-nice did you use our [repo](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages) to install the packages?

I used the default repo on debian, now I have fixed it using your repo. Thank you.
