### ISSUE TITLE
Samsung PM1733 stats

### ISSUE THREAD

**Issue by csutcliff** [netdata/netdata#9560] opened 2020-07-17 22:41 UTC
##### Bug report summary
Completely insane values for Samsung PM1733 SSDs
see: https://i.imgur.com/ia4sa7X.png

##### OS / Environment
Linux pve-1 5.4.44-2-pve #1 SMP PVE 5.4.44-2 (Wed, 01 Jul 2020 16:37:57 +0200) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"

##### Netdata version
netdata v1.23.2-10-nightly

##### Steps To Reproduce
All my hosts with Samsung PM1733 SSDs show the same/similar figures

##### Expected behavior
Sane values

**Comment by cakrit** [comment] 2020-08-07 08:25
@vlvkobal plz check

**Comment by vlvkobal** [comment] 2020-08-11 13:32
@csutcliff please provide the output of `for i in {1..10}; do cat /proc/diskstats; sleep 1; done`.

**Comment by csutcliff** [comment] 2020-08-11 15:03
`for i in {1..10}; do cat /proc/diskstats; sleep 1; done
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673486 1951481 1281792136 2423228 0 22667636 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903402 1670329 1204958632 2340053 0 20538184 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081160 0 9310247 242918 73945562 0 1628185952 2921571 0 18317936 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945562 0 1628185952 2921571 0 18108748 264904 0 0 0 0
 259       6 nvme2n1 7081543 0 9287831 271978 72389944 0 1628185952 2982138 0 18333812 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72389944 0 1628185952 2982138 0 17960932 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260808 83164 152124592 771909 0 6960760 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60533905 0 1204958632 2859376 0 20546864 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594380 0 1281792136 3129284 0 22678656 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367400 0 152124592 797600 0 6965124 6551048 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673499 1951481 1281792416 2423228 0 22667652 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903402 1670329 1204958632 2340053 0 20538184 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081162 0 9310247 242918 73945564 0 1628186064 2921571 0 18317940 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945564 0 1628186064 2921571 0 18108752 264904 0 0 0 0
 259       6 nvme2n1 7081545 0 9287831 271978 72389946 0 1628186064 2982138 0 18333816 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72389946 0 1628186064 2982138 0 17960936 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260808 83164 152124592 771909 0 6960760 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60533905 0 1204958632 2859376 0 20546864 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594393 0 1281792416 3129284 0 22678672 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367400 0 152124592 797600 0 6965124 6551048 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673504 1951481 1281792480 2423228 0 22667664 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903404 1670329 1204958656 2340053 0 20538188 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081166 0 9310247 242919 73945568 0 1628186216 2921571 0 18317948 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945568 0 1628186216 2921571 0 18108760 264904 0 0 0 0
 259       6 nvme2n1 7081549 0 9287831 271978 72389950 0 1628186216 2982138 0 18333824 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72389950 0 1628186216 2982138 0 17960944 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260825 83164 152124888 771911 0 6960768 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60533907 0 1204958656 2859376 0 20546868 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594398 0 1281792480 3129284 0 22678684 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367417 0 152124888 797604 0 6965132 6551052 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673576 1951481 1281793592 2423230 0 22667688 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903517 1670329 1204960184 2340056 0 20538204 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081170 0 9310247 242919 73945572 0 1628186344 2921571 0 18317956 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945572 0 1628186344 2921571 0 18108768 264904 0 0 0 0
 259       6 nvme2n1 7081553 0 9287831 271978 72389954 0 1628186344 2982138 0 18333832 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72389954 0 1628186344 2982138 0 17960952 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260825 83164 152124888 771911 0 6960768 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60534020 0 1204960184 2859376 0 20546884 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594470 0 1281793592 3129284 0 22678708 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367417 0 152124888 797604 0 6965132 6551052 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673585 1951481 1281793768 2423230 0 22667696 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903528 1670331 1204960400 2340056 0 20538208 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081176 0 9310247 242919 73945716 0 1628189208 2921574 0 18317968 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945716 0 1628189208 2921574 0 18108780 264904 0 0 0 0
 259       6 nvme2n1 7081559 0 9287831 271978 72390101 0 1628189208 2982141 0 18333844 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72390101 0 1628189208 2982141 0 17960964 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260825 83164 152124888 771911 0 6960768 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60534033 0 1204960400 2859376 0 20546888 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594479 0 1281793768 3129284 0 22678716 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367417 0 152124888 797604 0 6965132 6551052 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673585 1951481 1281793768 2423230 0 22667696 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903528 1670331 1204960400 2340056 0 20538208 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081178 0 9310247 242919 73945718 0 1628189320 2921574 0 18317972 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945718 0 1628189320 2921574 0 18108784 264904 0 0 0 0
 259       6 nvme2n1 7081561 0 9287831 271978 72390103 0 1628189320 2982141 0 18333848 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72390103 0 1628189320 2982141 0 17960968 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260830 83164 152124920 771911 0 6960772 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60534033 0 1204960400 2859376 0 20546888 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594479 0 1281793768 3129284 0 22678716 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367422 0 152124920 797604 0 6965136 6551052 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673591 1951481 1281793904 2423230 0 22667704 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903529 1670331 1204960408 2340056 0 20538212 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081180 0 9310247 242919 73945720 0 1628189352 2921574 0 18317976 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945720 0 1628189352 2921574 0 18108788 264904 0 0 0 0
 259       6 nvme2n1 7081563 0 9287831 271978 72390105 0 1628189352 2982141 0 18333852 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72390105 0 1628189352 2982141 0 17960972 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260830 83164 152124920 771911 0 6960772 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60534034 0 1204960408 2859376 0 20546892 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594485 0 1281793904 3129284 0 22678724 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367422 0 152124920 797604 0 6965136 6551052 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673602 1951481 1281794120 2423230 0 22667720 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903529 1670331 1204960408 2340056 0 20538212 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081182 0 9310247 242919 73945722 0 1628189464 2921574 0 18317980 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945722 0 1628189464 2921574 0 18108792 264904 0 0 0 0
 259       6 nvme2n1 7081565 0 9287831 271978 72390107 0 1628189464 2982141 0 18333856 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72390107 0 1628189464 2982141 0 17960976 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260830 83164 152124920 771911 0 6960772 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60534034 0 1204960408 2859376 0 20546892 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594496 0 1281794120 3129284 0 22678740 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367422 0 152124920 797604 0 6965136 6551052 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673604 1951481 1281794184 2423230 0 22667724 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903531 1670331 1204960432 2340056 0 20538216 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081186 0 9310247 242919 73945726 0 1628189512 2921574 0 18317988 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945726 0 1628189512 2921574 0 18108800 264904 0 0 0 0
 259       6 nvme2n1 7081569 0 9287831 271978 72390111 0 1628189512 2982141 0 18333864 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72390111 0 1628189512 2982141 0 17960984 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260838 83164 152125016 771912 0 6960776 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60534036 0 1204960432 2859376 0 20546896 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594498 0 1281794184 3129284 0 22678744 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367430 0 152125016 797604 0 6965140 6551052 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
   0       0 nvme1c1n1 15574215 6668274 1306035176 3068997 59673604 1951481 1281794184 2423230 0 22667724 452688 0 0 0 0
   0       0 nvme0c0n1 18224147 7326821 1473911640 3682046 58903531 1670331 1204960432 2340056 0 20538216 551548 0 0 0 0
 259       2 nvme1n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       3 nvme0n1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 259       4 nvme3n1 7081190 0 9310247 242919 73945880 0 1628192328 2921576 0 18318004 264904 0 0 0 0
 259       5 nvme3n1p1 174 0 11372 19 0 0 0 0 0 212 0 0 0 0 0
 259       7 nvme3n1p2 354 0 57560 115 0 0 0 0 0 752 0 0 0 0 0
 259       8 nvme3n1p3 53828 0 9186747 15491 73945880 0 1628192328 2921576 0 18108816 264904 0 0 0 0
 259       6 nvme2n1 7081573 0 9287831 271978 72390262 0 1628192328 2982144 0 18333880 275200 0 0 0 0
 259       9 nvme2n1p1 174 0 11372 19 0 0 0 0 0 200 0 0 0 0 0
 259      10 nvme2n1p2 354 0 57560 87 0 0 0 0 0 748 0 0 0 0 0
 259      11 nvme2n1p3 54211 0 9164331 15873 72390262 0 1628192328 2982144 0 17961000 275196 0 0 0 0
   8       0 sda 1230103 3187347 500235672 1076487 11260838 83164 152125016 771912 0 6960776 22504 0 0 0 0
   8      16 sdb 1271659 4202163 650307560 1221547 4942631 184278 118940712 475966 0 3536408 14368 0 0 0 0
 253       0 dm-0 5537159 0 650261920 7107344 5130124 0 118940712 692632 0 3539088 7799976 0 0 0 0
 253       1 dm-1 25536049 0 1473866000 5769104 60534036 0 1204960432 2859376 0 20546896 8628480 0 0 0 0
 253       2 dm-2 22229469 0 1305989536 4940280 61594498 0 1281794184 3129284 0 22678744 8069564 0 0 0 0
 253       3 dm-3 4480087 0 500190032 5753448 11367430 0 152125016 797604 0 6965140 6551052 0 0 0 0
`

**Comment by vlvkobal** [comment] 2020-08-12 07:37
Look at https://github.com/netdata/netdata/issues/5744#issuecomment-479379202. In your case, the problem is the same - wrong major and minor numbers
```
   0       0 nvme1c1n1
   0       0 nvme0c0n1
```
You can try applying #5799 as a temporary workaround, but in general, it is better to look for a correctly working NVMe driver.

I'm closing this in favor of #5744.

**Closed by vlvkobal** 2020-08-12 07:37 UTC
Labels: area/collectors, bug, needs triage
