### ISSUE TITLE
LiteSpeed plugin doesn't work on CentOS 6, works great on CentOS 7/8

### ISSUE THREAD

**Issue by georgetasioulis** [netdata/netdata#10641] opened 2021-02-15 17:55 UTC
##### Bug report summary
We're deploying Netdata to a mix of CentOS 6, 7 and 8 based servers (CloudLinux specifically), running cPanel with LiteSpeed Webserver.
Other than the underlying OS, the rest of the software stack is pretty much the same on all servers.

While the LiteSpeed metrics plugin works out of the box on all CentOS 7/8 based servers, on CentOS 6 based servers it will not show up in the Netdata dashboard.

##### OS / Environment
Affected servers are running CloudLinux 6
```
# uname -a; grep -Hv "^#" /etc/*release
Linux srv.domain.tld 2.6.32-954.3.5.lve1.4.79.1.el6.x86_64 #1 SMP Tue Jul 28 05:24:18 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/redhat-release:CloudLinux Server release 6.10 (Vladimir Lyakhov)
/etc/system-release:CloudLinux Server release 6.10 (Vladimir Lyakhov)
```
and CentOS 6
```
# uname -a; grep -Hv "^#" /etc/*release
Linux srv.domain.tld 2.6.32-754.33.1.el6.x86_64 #1 SMP Tue Aug 25 15:29:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS release 6.10 (Final)
/etc/redhat-release:CentOS release 6.10 (Final)
/etc/system-release:CentOS release 6.10 (Final)
```

##### Netdata version
```
netdata v1.29.1-38-nightly
```
 
##### Component Name
Running the plugin in debug mode on a CentOS/CloudLinux 6 server, shows that it's reading data from `/tmp/lshttpd/.rtreport`

```
# sudo -u netdata /usr/libexec/netdata/plugins.d/python.d.plugin debug litespeed
2021-02-15 17:34:49: python.d INFO: plugin[main] : using python v2
2021-02-15 17:34:49: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2021-02-15 17:34:49: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2021-02-15 17:34:49: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2021-02-15 17:34:49: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2021-02-15 17:34:49: python.d WARNING: plugin[main] : 'pythond-jobs-statuses.json' was not found
2021-02-15 17:34:49: python.d DEBUG: plugin[main] : [litespeed] looking for 'litespeed.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2021-02-15 17:34:49: python.d DEBUG: plugin[main] : [litespeed] loading '/usr/lib/netdata/conf.d/python.d/litespeed.conf'
2021-02-15 17:34:49: python.d DEBUG: plugin[main] : [litespeed] '/usr/lib/netdata/conf.d/python.d/litespeed.conf' is loaded
2021-02-15 17:34:49: python.d INFO: plugin[main] : [litespeed] built 1 job(s) configs
2021-02-15 17:34:49: python.d DEBUG: litespeed[localhost] : stats files: ['/tmp/lshttpd/.rtreport']
2021-02-15 17:34:49: python.d INFO: plugin[main] : litespeed[localhost] : check success
CHART netdata.runtime_litespeed_local '' 'Execution time for litespeed_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 10
DIMENSION run_time 'run time' absolute 1 1

2021-02-15 17:34:49: python.d DEBUG: litespeed[localhost] : started, update frequency: 10
CHART litespeed_local.connections_https '' 'Connections HTTPS' 'conns' 'connections' 'litespeed.connections' stacked 60003 10 '' 'python.d.plugin' 'litespeed'
DIMENSION 'ssl_conn_free' 'free' absolute 1 1 ' '
DIMENSION 'ssl_conn_used' 'used' absolute 1 1 ' '

BEGIN litespeed_local.connections_https 0
SET 'ssl_conn_free' = 9994
SET 'ssl_conn_used' = 6
END

CHART litespeed_local.connections_http '' 'Connections HTTP' 'conns' 'connections' 'litespeed.connections' stacked 60002 10 '' 'python.d.plugin' 'litespeed'
DIMENSION 'conn_free' 'free' absolute 1 1 ' '
DIMENSION 'conn_used' 'used' absolute 1 1 ' '

BEGIN litespeed_local.connections_http 0
SET 'conn_free' = 9992
SET 'conn_used' = 2
END

CHART litespeed_local.private_cache_hits '' 'Private Cache Hits' 'hits/s' 'cache' 'litespeed.cache' line 60007 10 '' 'python.d.plugin' 'litespeed'
DIMENSION 'private_cache_hits' 'hits' absolute 1 100 ' '

BEGIN litespeed_local.private_cache_hits 0
SET 'private_cache_hits' = 0
END

CHART litespeed_local.static_hits '' 'Static Hits' 'hits/s' 'static' 'litespeed.static' line 60008 10 '' 'python.d.plugin' 'litespeed'
DIMENSION 'static_hits' 'hits' absolute 1 100 ' '

BEGIN litespeed_local.static_hits 0
SET 'static_hits' = 50
END

CHART litespeed_local.pub_cache_hits '' 'Public Cache Hits' 'hits/s' 'cache' 'litespeed.cache' line 60006 10 '' 'python.d.plugin' 'litespeed'
DIMENSION 'pub_cache_hits' 'hits' absolute 1 100 ' '

BEGIN litespeed_local.pub_cache_hits 0
SET 'pub_cache_hits' = 0
END

CHART litespeed_local.net_throughput_http '' 'Network Throughput HTTP' 'kilobits/s' 'net throughput' 'litespeed.net_throughput' area 60000 10 '' 'python.d.plugin' 'litespeed'
DIMENSION 'bps_in' 'in' absolute 1 1 ' '
DIMENSION 'bps_out' 'out' absolute -1 1 ' '

BEGIN litespeed_local.net_throughput_http 0
SET 'bps_in' = 0
SET 'bps_out' = 0
END

CHART litespeed_local.requests_processing '' 'Requests In Processing' 'requests' 'requests' 'litespeed.requests_processing' line 60005 10 '' 'python.d.plugin' 'litespeed'
DIMENSION 'requests_processing' 'processing' absolute 1 1 ' '

BEGIN litespeed_local.requests_processing 0
SET 'requests_processing' = 7
END

CHART litespeed_local.net_throughput_https '' 'Network Throughput HTTPS' 'kilobits/s' 'net throughput' 'litespeed.net_throughput' area 60001 10 '' 'python.d.plugin' 'litespeed'
DIMENSION 'ssl_bps_in' 'in' absolute 1 1 ' '
DIMENSION 'ssl_bps_out' 'out' absolute -1 1 ' '

BEGIN litespeed_local.net_throughput_https 0
SET 'ssl_bps_in' = 0
SET 'ssl_bps_out' = 848
END

CHART litespeed_local.requests '' 'Requests' 'requests/s' 'requests' 'litespeed.requests' line 60004 10 '' 'python.d.plugin' 'litespeed'
DIMENSION 'requests' 'requests' absolute 1 100 ' '

BEGIN litespeed_local.requests 0
SET 'requests' = 90
END

BEGIN netdata.runtime_litespeed_local 0
SET run_time = 0
END

2021-02-15 17:34:53: python.d DEBUG: litespeed[localhost] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
BEGIN litespeed_local.connections_https 10006000
SET 'ssl_conn_free' = 9988
SET 'ssl_conn_used' = 12
END

BEGIN litespeed_local.connections_http 10006000
SET 'conn_free' = 9984
SET 'conn_used' = 4
END

BEGIN litespeed_local.private_cache_hits 10006000
SET 'private_cache_hits' = 0
END

BEGIN litespeed_local.static_hits 10006000
SET 'static_hits' = 1040
END

BEGIN litespeed_local.pub_cache_hits 10006000
SET 'pub_cache_hits' = 50
END

BEGIN litespeed_local.net_throughput_http 10006000
SET 'bps_in' = 0
SET 'bps_out' = 0
END

BEGIN litespeed_local.requests_processing 10006000
SET 'requests_processing' = 12
END

BEGIN litespeed_local.net_throughput_https 10006000
SET 'ssl_bps_in' = 0
SET 'ssl_bps_out' = 2288
END

BEGIN litespeed_local.requests 10006000
SET 'requests' = 1220
END

BEGIN netdata.runtime_litespeed_local 10006000
SET run_time = 0
END

2021-02-15 17:35:03: python.d DEBUG: litespeed[localhost] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
BEGIN litespeed_local.connections_https 10000000
SET 'ssl_conn_free' = 9985
SET 'ssl_conn_used' = 15
END

BEGIN litespeed_local.connections_http 10000000
SET 'conn_free' = 9980
SET 'conn_used' = 5
END

BEGIN litespeed_local.private_cache_hits 10000000
SET 'private_cache_hits' = 0
END

BEGIN litespeed_local.static_hits 10000000
SET 'static_hits' = 70
END

BEGIN litespeed_local.pub_cache_hits 10000000
SET 'pub_cache_hits' = 10
END

BEGIN litespeed_local.net_throughput_http 10000000
SET 'bps_in' = 0
SET 'bps_out' = 8
END

BEGIN litespeed_local.requests_processing 10000000
SET 'requests_processing' = 16
END

BEGIN litespeed_local.net_throughput_https 10000000
SET 'ssl_bps_in' = 0
SET 'ssl_bps_out' = 8
END

BEGIN litespeed_local.requests 10000000
SET 'requests' = 360
END

BEGIN netdata.runtime_litespeed_local 10000000
SET run_time = 0
END

2021-02-15 17:35:13: python.d DEBUG: litespeed[localhost] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
```

However, it doesn't show up in the dashboard:
<img width="184" alt="Screenshot 2021-02-15 at 7 51 36 PM" src="https://user-images.githubusercontent.com/460954/107979684-a9084a80-6fc7-11eb-8055-15f73a9870e1.png">

**Comment by ilyam8** [comment] 2021-02-15 18:53
Hi @georgetasioulis 

Let's check error.log


```cmd
cd /var/log/netdata/
> error.log
service netdata restart
grep litespeed error.log
```

**Comment by georgetasioulis** [comment] 2021-02-15 21:08
Hi @ilyam8 

Here's the output:
```
2021-02-15 20:57:29: python.d INFO: plugin[main] : [litespeed] built 1 job(s) configs
2021-02-15 20:57:30: python.d INFO: plugin[main] : litespeed[localhost] : check success
```

In case it help, this is what a CentOS 6 based server has related to litespeed (ie nothing) in netdata.conf: https://gist.github.com/georgetasioulis/d23c48e6ea64ee2229bb0c29ddd994e7
while on a CentOS 7 based server we have all the necessary configs: https://gist.github.com/georgetasioulis/eaefd7937e6687bcacea188be7b80b1f

**Comment by ilyam8** [comment] 2021-02-16 11:12
Ok, interesting, we have:

- [it works when running the plugin in the debug mode as netdata user](https://github.com/netdata/netdata/issues/10641#issue-808727098) ✅ 
- [there is litespeed[localhost] : check success in the error.log](https://github.com/netdata/netdata/issues/10641#issuecomment-779448119) ✅ 
- there is no Litespeed section on the dashboard ⚠️ 

Perhaps there is some problem with other collector and python.d.plugin fails to start.

Lets try to debug python.d.plugin with all modules

```
sudo -u netdata /usr/libexec/netdata/plugins.d/python.d.plugin debug
```

**Comment by georgetasioulis** [comment] 2021-02-16 11:23
Here you go https://gist.github.com/georgetasioulis/13a80037c90b17d384e95c93ddc726d5
Indeed, it's not finishing correctly.

**Comment by ilyam8** [comment] 2021-02-16 11:47
Ok, so you are using python2.6?

The problem is ([py-filelock](https://github.com/benediktschmitt/py-filelock) package, we vendor it).

https://github.com/netdata/netdata/blob/57adb073c5135d88a2b62036612a8650df528bd9/collectors/python.d.plugin/python_modules/third_party/filelock.py#L98-L100

See https://docs.python.org/2/library/string.html#format-string-syntax

> Changed in version 2.7: The positional argument specifiers can be omitted for str.format() and unicode.format(), so '{} {}' is equivalent to '{0} {1}', u'{} {}' is equivalent to u'{0} {1}'.

---

Try to change `The file lock '{}'...` to `The file lock '{0}'...`. Does it work after the change?

**Comment by georgetasioulis** [comment] 2021-02-16 12:15
CentOS 6 by default runs python 2.6
```
# python --version
Python 2.6.6
```
Of course, as per netdata installation requirements, `python3` has also been installed on the CentOS 6 servers:
```
# python3 --version
Python 3.4.10
```
I can probably try https://github.com/netdata/netdata/issues/1731#issuecomment-277767601 to create a symlink to the python3 binary so that netdata uses that instead.

After editing the `filelock.py` file according to your instructions, I restarted netdata and tried the debug command again. This time it finished without an issue. Also LiteSpeed is now visible in the dashboard, and reports metrics fine.

The only thing I still don't see, is the config entries in netdata.conf like on CentOS 7 servers, as shown here: https://gist.github.com/georgetasioulis/eaefd7937e6687bcacea188be7b80b1f
Since I'm using defaults anyway, it shouldn't matter - I'm just letting you know.

I will now try reverting the change in `filelock.py` + create the symlink to python3, and will report back.

**Comment by ilyam8** [comment] 2021-02-16 12:22
Hold on, there is configuration option in the `netdata.conf`, you can force python.d.plugin to use python3

```cmd
[ilyam@pc netdata]$ grep "plugin:python" -A 2 netdata.conf
[plugin:python.d]
	# update every = 1
	command options = -ppython3
```

Closing this issue as `wontfix`. Supporting python2.6 is not something we want to do.

**Closed by ilyam8** 2021-02-16 12:22 UTC
Labels: area/external/python, bug, needs triage

**Comment by ilyam8** [comment] 2021-02-16 12:27
Is CentOS 6 still a thing? It is EOL. Just curiosity - why do you keep using it?

**Comment by georgetasioulis** [comment] 2021-02-16 13:00
Thanks, both the symlink solution, and the command option solution worked fine. Since I have already installed Python 3, I'm just going to push the configuration option in `netdata.conf` to those servers.

> Is CentOS 6 still a thing? It is EOL. Just curiosity - why do you keep using it?
Those are either CloudLinux 6 or CentOS 6 [with ELS](https://www.cloudlinux.com/extended-lifecycle-support) servers, ie unofficially supported until 2024. 
Shared hosting servers hold a large number of domains & email accounts, and combined with the fact that many end-users may be using external DNS for their domains, makes migrations really painful. Full RHEL/CentOS8 support in cPanel for production environments is only available in "release candidate" (CURRENT) tier [v94](https://cpanel.net/version-94/) at the moment - it should be released into CURRENT/STABLE tier within the next couple of weeks. 
As the typical lifecycle of a shared hosting server is several years, to avoid migrating all these servers to CentOS 7 first (which will EOL in 2024) and then to 8, we're temporarily using ELS on those servers for critical/security updates and plan on migrating them to CentOS 8 (or one of the forks that are being prepared), in Q2-Q3 2021.

**Comment by ilyam8** [comment] 2021-02-16 13:06
Thx for the explanation!
