### ISSUE TITLE
netdata fails to restart after nightly update

### ISSUE THREAD

**Issue by mismacku** [netdata/netdata#7320] opened 2019-11-14 17:53 UTC
##### Kudos
As always, huge thanks for all of the work you put into netdata!  
  
##### Bug report summary
It looks like netdata fails to die during the daily update. I'm running netdata on ~75 servers and this seems to happen only on my low powered Dell R330 servers. (specs below).  Netdata is running directly on the hosts, not in containers or VM's. The problem doesn't occur on every update, but does occur several times per week on ~6 servers. Simply restarting with `systemctl restart netdata` resolves the issue.  
  
netdata-installer.log:  
```[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# tar xf /tmp/netdata-go-YwCYLW/go.d.plugin-v0.10.0.linux-amd64.tar.gz  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# mv go.d.plugin-v0.10.0.linux-amd64 /usr/libexec/netdata/plugins.d/go.d.plugin  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# chown root:netdata /usr/libexec/netdata/plugins.d/go.d.plugin  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# chmod 0750 /usr/libexec/netdata/plugins.d/go.d.plugin  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# cp system/netdata.service /lib/systemd/system/netdata.service  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# systemctl daemon-reload  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# systemctl enable netdata  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# stop_all_netdata  ... [root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# kill 15448  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# kill 15448  ... FAILED with exit code 1
OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# systemctl start netdata  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# systemctl start netdata  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# stop_all_netdata  ... OK
[root /tmp/netdata-updater-ontssx/netdata-v1.18.1-28-g9a9bee64]# /usr/sbin/netdata  ... FAILED with exit code 1
```

##### OS / Environment
- Ubuntu 16.04
- 4.4.0-112-generic
- Dell R330
- 4GB RAM
- Dual core Intel Pentium G4500

##### Netdata version
netdata v1.18.1-114-nightly

##### Steps To Reproduce
Allow netdata to update via netdata-updater (cron.daily). This may be reproducible by another means, but I can't seem to make that happen.

##### Expected behavior
The old version of netdata should die and the new version should start when cron runs **netdata-updater**

**Comment by mismacku** [comment] 2019-11-14 18:07
Output from a second identical machine:
```
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# mv go.d.plugin-v0.10.0.linux-amd64 /usr/libexec/netdata/plugins.d/go.d.plugin  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# chown root:netdata /usr/libexec/netdata/plugins.d/go.d.plugin  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# chmod 0750 /usr/libexec/netdata/plugins.d/go.d.plugin  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# cp system/netdata.service /lib/systemd/system/netdata.service  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# systemctl daemon-reload  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# systemctl enable netdata  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# stop_all_netdata  ... [root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# kill 14673  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# kill 14673  ... FAILED with exit code 1
OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# systemctl start netdata  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# systemctl start netdata  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# stop_all_netdata  ... OK
[root /tmp/netdata-updater-5aCpnL/netdata-v1.18.1-91-gb107a6c7]# /usr/sbin/netdata  ... FAILED with exit code 1
```

**Comment by thiagoftsm** [comment] 2019-11-14 18:19
Hi @mismacku ,

you said that only Dell R330  servers are having problems, I will do a question for we try to recreate the error, are all the 7 Dells running exactly the same Ubuntu version?

best regards!

**Comment by mismacku** [comment] 2019-11-14 18:44
One of them is on Ubuntu 16.04.3 and the remaining five servers are on 16.04.6

**Comment by dkowis** [comment] 2019-11-23 23:35
netdata v1.18.1-161-g114d2a20
uname: `Linux monitor.dark.kow.is 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

All the netdatas on my (xen-based) virtual machines on ubuntu 18.04 are segfaulting.

Been happening for a while now, I think, prometheus shows the last data collection on 22 Nov at 6am. So I guess yesterday morning. Probably after an automated update.

```
Nov 23 17:32:12 monitor netdata[3004]: 2019-11-23 17:32:12: netdata INFO  : MAIN : SIGNAL: Not enabling reaper
Nov 23 17:32:12 monitor kernel: [  774.936176] PLUGIN[diskspac[3024]: segfault at 7c ip 00007f5e142efefd sp 00007f5e14715830 error 4 in netdata[7f5e14217000+317000]
Nov 23 17:32:12 monitor kernel: [  774.936202] Code: 8d 3d 4b 27 1a 00 89 44 24 1c e8 ae ed 00 00 89 05 d4 e6 46 00 48 8b 05 a1 2c 48 00 48 8d 35 86 13 18 00 48 8d 3d 27 27 1a 00 <48> 63 50 7c e8 1a d5 00 00 48 8b 15 83 2c 48 00 41 89 c6 48 8d 35
Nov 23 17:32:13 monitor systemd[1]: netdata.service: Main process exited, code=killed, status=11/SEGV
Nov 23 17:32:13 monitor systemd[1]: netdata.service: Failed with result 'signal'.
```

**Comment by amoss** [comment] 2019-11-25 11:42
The problem is in `packaging/installer/function.sh` inside `stop_netdata_on_pid`. There seem to be two issues:
* Not detecting that the kill succeeded.
* No fall-back for cases where the kill did not succeed after 90 seconds.

**Comment by mismacku** [comment] 2019-12-13 15:19
Any updates or thoughts on this? It still happens regularly. I'm happy to provide additional information if needed. Thanks for looking into it!

**Comment by amoss** [comment] 2019-12-13 15:24
@knatsakis is it possible to estimate when we can deliver a fix for this?

**Comment by Ferroin** [comment] 2020-01-06 15:19
#7595 should fix this, currently awaiting required approvals for the changes.

**Closed** 2020-01-07 11:23 UTC
Labels: bug
