### ISSUE TITLE
vmware photon os build-essentials not detected as being not installed

### ISSUE THREAD

**Issue by osde8info** [netdata/netdata#8525] opened 2020-03-28 22:56 UTC
##### Bug report summary

vmware photon os build-essentials not detected as being not installed

##### OS / Environment

```
vmware photon os
```

##### Netdata version

 latest

##### Component Name

installer

##### Steps To Reproduce

1. ...
netdata install
2. ...

 --- Prepare custom libmosquitto version ---
v.1.6.8_Netdata-3.tar.gz: OK
[/tmp/netdata-kickstart-zjCCDO/netdata-v1.20.0-254-ge328b23a]# tar -xf /tmp/netdata-mosquitto-dJUBxb/v.1.6.8_Netdata-3.tar.gz -C /tmp/netdata-mosquitto-dJUBxb
 OK

[/tmp/netdata-kickstart-zjCCDO/netdata-v1.20.0-254-ge328b23a]# env CFLAGS= CXXFLAGS= LDFLAGS= make -C /tmp/netdata-mosquitto-dJUBxb/mosquitto-v.1.6.8_Netdata-3/lib
env: 'make': No such file or directory
 FAILED

 FAILED  Failed to build libmosquitto. The install process will continue, but you will not be able to connect this node to Netdata Cloud.

##### Expected behavior

should warn that build-essentials has NOT been installed

**Comment by prologic** [comment] 2020-04-16 04:58
Duplicate of https://github.com/netdata/netdata/issues/8526 Closing in favor of https://github.com/netdata/netdata/issues/8526

**Closed by prologic** 2020-04-16 04:58 UTC
Labels: bug, duplicate
