### ISSUE TITLE
Centos6 rpmbuild

### ISSUE THREAD

**Issue by Jolin-blank** [netdata/netdata#9891] opened 2020-09-07 12:11 UTC
netdata-v.1.24.0
libbpf.c: In function ‘bpf_program__attach_perf_event’:
libbpf.c:7586: error: ‘PERF_EVENT_IOC_SET_BPF’ undeclared (first use in this function)
libbpf.c:7586: error: (Each undeclared identifier is reported only once
libbpf.c:7586: error: for each function it appears in.)
libbpf.c: In function ‘perf_buffer__new’:
libbpf.c:8407: error: ‘PERF_COUNT_SW_BPF_OUTPUT’ undeclared (first use in this function)
cc1: warnings being treated as errors
libbpf.c:8408: error: left-hand operand of comma expression has no effect
libbpf.c:8408: error: value computed is not used
make: *** [staticobjs/libbpf.o] Error 1

**Comment by prologic** [comment] 2020-09-15 05:05
@Ferroin Please look into this when you're up. Thanks! 🙇‍♂️

**Comment by Ferroin** [comment] 2020-09-15 11:30
We don't have a conditional in the spec file for eBPF support, but we can't build eBPF support on CentOS 6. Should be a relatively easy fix, and I should have a PR up for this later today.

**Comment by Ferroin** [comment] 2020-09-15 11:58
Hmm, looking further, we do have such a conditional, it just doesn't appear to be working here. I'll try and reproduce this locally.

**Comment by Ferroin** [comment] 2020-09-15 12:12
Based on quick and dirty testing here, i cannot reproduce this.

@Jolin-blank Could you please provide some more inf about how you're trying to build the RPMs on CentOS 6?

**Comment by ilyam8** [comment] 2021-08-31 14:10
Closing because Centos6 is EOL

**Closed by ilyam8** 2021-08-31 14:10 UTC
Labels: bug, area/packaging, needs triage, need feedback
