### ISSUE TITLE
Nvidia-smi, Nginx, Smartd gone, APCUPSD showing far less info than before

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#9175] opened 2020-05-26 20:49 UTC
##### OS / Environment

```
Linux HDA 4.18.19-100.fc27.x86_64 #1 SMP Wed Nov 14 22:04:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/amahi-release:Amahi release 11 (based on Fedora 27)
/etc/fedora-release:Fedora release 27 (Twenty Seven)
/etc/os-release:NAME=Fedora
/etc/os-release:VERSION="27 (Twenty Seven)"
/etc/os-release:ID=fedora
/etc/os-release:VERSION_ID=27
/etc/os-release:PRETTY_NAME="Fedora 27 (Twenty Seven)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:fedoraproject:fedora:27"
/etc/os-release:HOME_URL="https://fedoraproject.org/"
/etc/os-release:SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Fedora"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=27
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Fedora"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION=27
/etc/os-release:PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
/etc/redhat-release:Fedora release 27 (Twenty Seven)
/etc/system-release:Fedora release 27 (Twenty Seven)
```

##### Netdata version

 netdata v1.22.1-123-nightly

##### Component Name

Nvidia-smi, Nginx, Smartd and APCUPSD

##### Steps To Reproduce

1. Since latest update nvidia-smi stats have dissapeared and apcupsd is only showing battery level, no voltages no frequency, no time left etc.
2. ... No changes have been made in configs.

##### Expected behavior

Nvidia-smi, nginx and smartd to show up and apcupsd to show all relevant info.

![image](https://user-images.githubusercontent.com/4349962/82948995-c52c0d80-9f9a-11ea-897d-11275c677f58.png)

![image](https://user-images.githubusercontent.com/4349962/82949031-d1b06600-9f9a-11ea-8815-7c301bf7f3b8.png)

![image](https://user-images.githubusercontent.com/4349962/82949754-0d97fb00-9f9c-11ea-848b-2eaa4cd5cb6f.png)

![image](https://user-images.githubusercontent.com/4349962/82949144-fefd1400-9f9a-11ea-8d8a-2c8cfce2d57a.png)

**Comment by ilyam8** [comment] 2020-05-26 22:00
> netdata v1.22.1-123-nightly

 it is likely duplicate of #9156

**Comment by ilyam8** [comment] 2020-05-26 22:01
It is fixed in latest.

> https://github.com/netdata/netdata/issues/9156#issuecomment-633912988

**Closed by ilyam8** 2020-05-26 22:01 UTC
Labels: bug, needs triage
