### ISSUE TITLE
Operating System Integration

### ISSUE THREAD

**Issue by TheeMahn** [netdata/netdata#3876] opened 2018-06-23 14:54 UTC
I build operating systems for fun.  https://ultimateedition.info/  I have built a deb as well as trying to build netdata into the O/S and have failed on both fronts.  Is there something I am missing?

After the O/S is installed goes right in:
http://keyserver.ueserver.space:19999/#menu_system;theme=slate;help=true

The deb I built DEC 2017, fails as well:
http://os-builder.com/UETOYS/netdata-1.3_all.deb

Do you provide a debian based package?

**Comment by paulfantom** [comment] 2018-09-22 16:36
It is on our roadmap.

Closing as this is a duplicate of https://github.com/netdata/netdata/issues/42 and https://github.com/netdata/netdata/issues/2728

**Closed by paulfantom** 2018-09-22 16:36 UTC
Labels: duplicate, packaging
