### ISSUE TITLE
Netdata refuses to start

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#9597] opened 2020-07-23 15:18 UTC
##### Bug report summary
Netdata refuses to start presumable after a recent nightly update in the last 1-2 days.
I have tried updating and it seems to install but will not run and I noticed it reports that I have disabled the updater, which is untrue.

The Dashboard won't load in my browser any longer.

I can't seem to get the version number but have attached netdata error.log and systemctl status for netdata.

``` 
Install (but not enable) netdata updater tool --- 
Update script is located at /opt/netdata/usr/libexec/netdata/netdata-updater.sh

 --- Check if we must enable/disable the netdata updater tool --- 
You chose *NOT* to enable auto-update, removing any links to the updater from cron (it may have happened if you are reinstalling)

Did not find any cron entries to remove

```

##### OS / Environment

Cloud VPS 6GB RAM 48 Cores
CENTOS 7.8 virtuozzo 
WHM/CPanel  v88.0.13

``` uname -a; grep -Hv "^#" /etc/*release
Linux myvps.inmotionhosting.com 3.10.0-1062.12.1.vz7.131.10 #1 SMP Mon Mar 16 15:39:59 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)

```

[netdata_error.log.gz](https://github.com/netdata/netdata/files/4966975/netdata_error.log.gz)
[netdata_systemctl_status.txt.gz](https://github.com/netdata/netdata/files/4966984/netdata_systemctl_status.txt.gz)

**Comment by ilyam8** [comment] 2020-07-23 15:27
```cmd
2020-07-23 15:50:09: netdata INFO  : MAIN : Initializing data file "/opt/netdata/var/cache/netdata/dbengine/datafile-1-0000000357.ndf".
2020-07-23 15:50:09: netdata ERROR : MAIN : File length is too short.

2020-07-23 15:50:09: netdata ERROR : MAIN : 1 datafiles failed to load.
2020-07-23 15:50:09: netdata ERROR : MAIN : Failed to scan path "/opt/netdata/var/cache/netdata/dbengine". (errno 22, Invalid argument)
2020-07-23 15:50:09: netdata INFO  : MAIN : Freed 0 bytes of memory from page cache.
2020-07-23 15:50:09: netdata ERROR : MAIN : Host 'myvps.inmotionhosting.com': cannot initialize host with machine guid 'b8c73894-bc37-11ea-bdcb-959fa06c43a9'. Failed to initialize DB engine at '/opt/netdata/var/cache/netdata'. (errno 22, Invalid argument)
2020-07-23 15:50:09: netdata INFO  : MAIN : Freeing all memory for host 'myvps.inmotionhosting.com'...
2020-07-23 15:50:09: netdata ERROR : MAIN : RRDHOST 'myvps.inmotionhosting.com' removed from index, deleted the wrong entry. (errno 22, Invalid argument)
2020-07-23 15:50:09: netdata ERROR : MAIN : Request to free RRDHOST 'myvps.inmotionhosting.com': cannot find it
2020-07-23 15:50:09: netdata INFO  : MAIN : SYSTEM_INFO: free 0x7fc75ba48b80
2020-07-23 15:50:09: netdata FATAL : MAIN : Cannot initialize localhost instance with name 'myvps.inmotionhosting.com'. # : Invalid argument

2020-07-23 15:50:09: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2020-07-23 15:50:09: netdata INFO  : MAIN : EXIT: cleaning up the database...
2020-07-23 15:50:09: netdata INFO  : MAIN : Cleaning up database [18446744073709551615 hosts(s)]...
2020-07-23 15:50:09: netdata INFO  : MAIN : EXIT: removing netdata PID file '/opt/netdata/var/run/netdata/netdata.pid'...
2020-07-23 15:50:09: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.
```

Hi. Try https://github.com/netdata/netdata/issues/9595#issuecomment-662964633

**Comment by ilyam8** [comment] 2020-07-23 15:28
Perhaps @mfundul needs that file to check what happend, so dont hurry with deleting dbengine cache.

**Comment by mfundul** [comment] 2020-07-23 15:30
You should delete `/opt/netdata/var/cache/netdata/dbengine/datafile-1-0000000357.ndf`. This is a duplicate of https://github.com/netdata/netdata/issues/9521

**Closed by mfundul** 2020-07-23 15:30 UTC
Labels: bug, needs triage

**Comment by TheOldMan2000** [comment] 2020-07-23 15:57
Hi thanks for the fast response.
I forgot to add that I'd tried that suggestion from the other thread and it made no difference at all. I will try it again though.

**Comment by TheOldMan2000** [comment] 2020-07-23 16:07
I just tried deleting both files as suggested but effect. However it's saying the next file (in numerical sequence' is now fubared, so I will delete them all again.

> You should delete `/opt/netdata/var/cache/netdata/dbengine/datafile-1-0000000357.ndf` and its matching journalfile. This is a duplicate of #9521

**Comment by TheOldMan2000** [comment] 2020-07-23 16:10
And we're back! Deleting all the files worked this time with:
rm -rf /opt/netdata/var/cache/netdata/*

Thanks again.
