### ISSUE TITLE
netdata-lite - power saving mode

### ISSUE THREAD

**Issue by earthgecko** [netdata/netdata#238] opened 2016-04-15 15:07 UTC
netdata is great, but it occurs to me that even though it is very lightweight it is still consuming power and CPU.  Seeing as netdata is not looking to replace graphite, collectd, etc, etc and is sticking to realtime it seems as if there should be a power saving or idle mode that it can be run in.

Consider that on a small VM netdata accounts for a small ~2% CPU cost.  It is probably true that netdata is only ever going to be queried and looked at on a machine very, very rarely.  That means netdata is burning ~2% CPU (and electricity) 99.999% of the time on most machines for nothing, other than a 3600 second timeseries of what happened, which arguably is provider by graphite or newrelic or some other historical metrics app.

Since it release netdata has been a very popular download, so how many CPU ticks and watts of energy are being used all over the world now to run netdata? A lot of energy for recording a lot of realtime data that is hardly ever looked at.  As engineers we should strive for efficiency.

I have hacked a little netdata-lite program for my running of netdata (nc bound to 19999 on a request start netdata - https://github.com/earthgecko/netdata-lite) which I was looking at fitting into the netdata/system area with a pull request, but it is a hack.  It would be great if netdata had a native power saving mode (if configed) where it could start up lite natively and only start the really work if it got a request on the port, it would possibly save loads of CPU and energy across the world now.  Just a thought.

And yes it is awesome, however the error log can runaway and consume the disk if netdata has an issue as I found with have nc bound to the port and netdata starting somehow

```
[root@machine ~] du -sh /var/log/netdata/error.log
2.3G    /var/log/netdata/error.log
[root@machine ~] cat /var/log/netdata/error.log | wc -l
19013175
[root@machine ~] tail -n 1000 /var/log/netdata/error.log | grep -v "is too old\. Clearing it" | head -n 3
16-04-09 17:07:22: ERROR: netdata: 11578853: Cannot accept new incoming connection. (errno 88, Socket operation on non-socket)
16-04-09 17:07:22: ERROR: netdata: 11578854: Cannot accept new incoming connection. (errno 88, Socket operation on non-socket)
16-04-09 17:07:22: ERROR: netdata: 11578855: Cannot accept new incoming connection. (errno 88, Socket operation on non-socket)
[root@machine ~] cat /var/log/netdata/error.log | grep -c "errno 88, Socket operation on non-socket" 
19004697
[root@machine ~]
```

**Comment by glensc** [comment] 2016-04-15 15:31
perhaps under systemd could use [socket activation](http://0pointer.de/blog/projects/socket-activation.html), and run daemon for X seconds, then die, and if another incoming connection comes, systemd could activate it again

**Comment by earthgecko** [comment] 2016-04-15 16:07
@glensc many ways to skin a cat :)  but systemd is a hack too, in some ways.  It would be better if netdata could do it natively, less dependencies.

**Comment by glensc** [comment] 2016-04-15 16:21
@earthgecko it's not hack, socket activation is supported officially in systemd.

what i proposed is combination of changes in both:
- create systemd config with socket activation
- modify netdata to handle socket activation
- modify netdata to exit itself after timeout N seconds

**Comment by earthgecko** [comment] 2016-04-15 17:28
@glensc well it is a bit of a hack if you are running any OS versions that do not have systemd support :)

**Comment by glensc** [comment] 2016-04-15 17:52
[a hack](https://en.wikipedia.org/wiki/Hack_(computer_science)) would be invent something else! socket activation was written exactly such purposes, and adding application socket activation support is rather [minimal code](http://0pointer.de/blog/projects/socket-activation.html)

some random patches for socket activation done in other projects:
https://github.com/pantheon-systems/nginx/blob/master/nginx-systemd-socket-activation.patch
https://gist.github.com/marktheunissen/7ce9426e66aa8f0ec2e1
https://github.com/yarrick/iodine/pull/4
https://wiki.php.net/rfc/socketactivation

btw, the iodine patch does exactly the same as wanted here

only hack part in systemd is probably the daemon dying, haven't actually tested it works, but should as `Restart` directive exists in unit files.

**Comment by mailinglists35** [comment] 2017-02-27 13:09
I would pretty much like to have this feature available. I know I should just be subscribing this issue and liking comments to keep noise down, but I'm commenting just as a kind reminder to netdata authors that since the issue has been filed, lots of energy has been wasted worldwide :(

**Comment by ktsaou** [comment] 2017-02-27 14:37
ok. point taken... If there is demand for something like this, I will check what can be done and how.

**Comment by mailinglists35** [comment] 2017-02-27 15:25
IMHO it should pause processing after it is not being watched at.

This can be done in two ways: allow user to inform netdata that he is going to take a break (a "pause/continue" button at the top bar) or detect that the user has gone away (example: pause processing if user has gone away more than N minutes).

The first one is going to be quite useless as most of the time the user can dissapear from the computer without having time to push the pause button, leaving the second option as the best way to handle this.

I'm not sure how html5 & javascript allows detection of user presence, but definitely sites like facebook can detect if the user is idle/away.

If this turns out to work ok, later imho it should become the default behaviour, with user configurable parameter to revert to "older" behaviour for cases when netdata is used for always-on monitoring.

**Comment by l2isbad** [comment] 2017-02-27 15:49
How many energy it save? I mean real numbers not theoretical stuff. Is it worth?

**Comment by ktsaou** [comment] 2017-02-27 16:16
> ow many energy it saves? I mean real numbers not theoretical stuff. Is it worth it?

Probably not. Check the CPU states chart.

The problem is a lot more complex. Let's assume that netdata can detect it is not accessed by a user. This can easily be done. So, after 2 minutes of the last access it does something.

If that something is exit, or even stop collecting data, everything is super simple, so let's say we do this.

Question 1: alarms? what about them? Should they be stopped? A lot of them will trigger if we don't.

Then, after some time, you have a problem with your system and go to netdata. Netdata detects this and starts collecting metrics.

Question 2: what about the short past? There will be no metrics, so how would find out what happened?

One viable solution would be for netdata to slow down data collection when you don't use it. But this is a lot more complicated, it requires quite a refactoring and should be done only when there is strong evidence it will give a valued benefit.

Otherwise, we will just over-optimizing for no reason...

**Comment by l2isbad** [comment] 2017-02-27 16:31
I think the guy just wants to use netdata as a console tool. No more no less. So 

> stop collecting data

and

> no metrics

is what he means.

After that you can put "green" sticker on netdata 😄

**Comment by candlerb** [comment] 2017-03-23 10:50
> Question 2: what about the recent past? There will be no metrics, so how would you find out what happened?

That's the crucial thing.  I want netdata running all the time, precisely so that when there's a problem I can see what's been going on, in detail.  Plus: if there *is* an ongoing problem, that's not the time I want to start up a new service or change the collection rate, which in turn may have an impact (even if it's a small one).

For the OP maybe a stop collection / start collection button is what they want; but they can also just run `systemctl [stop|start] netdata`.

**Comment by cakrit** [comment] 2018-11-23 11:57
I'm having a hard time understanding from this thread what exactly Netdata would be doing while in power saving mode. What I understand from this request is that we can have a lower collection rate (though per second monitoring is a key differentiator of Netdata) and perhaps completely turning off everything related to health monitoring, to save the cycles used to evaluate whether an alarm should be raised or not. 
Is that what is being asked here? 

If so, then bringing up the browser would just automatically increase the monitoring rate to per sec?

**Comment by ktsaou** [comment] 2018-11-23 12:03
I think this is a workstation feature, not a server or IoT one.

Of course we need to support workstations too, and netdata perfectly runs laptops, it is friendly to hibernation, automounting of disks, waking up of remote filesystems, etc. but I think this is as far as we can get with workstation support.

So, unless we can find a real use for servers, VMs, IoT, I don't think we should explore this area more.

I am closing this. But we can still discuss it if you believe I am wrong.

**Closed by ktsaou** 2018-11-23 12:03 UTC
Labels: feature request
