### ISSUE TITLE
What is the expected permission / ownership of logdir (/var/log/netdata)

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#4964] opened 2018-12-10 09:09 UTC
##### Question summary
What is the expected permission / ownership of logdir `/var/log/netdata`?
When installing netdata from git with kickstart.sh the permission / ownership is set to:
```
# ls -l /var/log/ | grep netdata
drwxr-xr-x 2 netdata  root          4096 Dez 10 06:25 netdata
```
##### OS / Environment
SLES 12SP3

**Comment by cakrit** [comment] 2018-12-10 09:47
Let's treat this as a duplicate of #4963 and answer the question there.

**Closed by cakrit** 2018-12-10 09:47 UTC
