### ISSUE TITLE
[Bug]: Official RPM packages fail to install inside openSUSE Docker images.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#11460] opened 2021-08-26 16:50 UTC
##### Bug report summary

When attempting to install our official RPM packages on openSUSE in a Docker container, the installation fails due to the container not running systemd.

##### OS / Environment

Any version of openSUSE running in a Docker container that we build a RPM package for (currently leap 15.2 and Leap 15.3).

##### Netdata version

Any

##### Installation method

Native RPM packages.

##### Component Name

packaging

##### Steps To Reproduce

1. Start an interactive openSUSE docker container (relevant images are either `opensuse/leap:15.2` or `opensuse/leap:15.3`).
2. Install curl using `zypper install curl` (this is required for the third step).
3. Attempt to install a native RPM version of Netdata either following the steps at: https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages. Note that for openSUSE Leap 15.3, only nightly packages are available.

##### Expected behavior

Installation succeeds without issue.

**Comment by maneamarius** [comment] 2021-11-04 08:11
I reproduced the issue with the following Dockerfile:

```
FROM opensuse/leap:15.2

RUN zypper --non-interactive install curl sudo

RUN curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.rpm.sh | sudo bash

RUN zypper --non-interactive install netdata-repo

RUN zypper --non-interactive install netdata
```

The output of ```docker build -t netdata .``` shows:

```
(33/33) Installing: netdata-1.31.0-1.x86_64 [............done]
Additional rpm output:
Failed to connect to bus: No such file or directory
warning: %post(netdata-1.31.0-1.x86_64) scriptlet failed, exit status 1


Executing %posttrans script 'blog-2.18-lp152.6.6.x86_64.rpm' [.....
Output of systemd-presets-common-SUSE-15-lp152.9.9.1.noarch.rpm %posttrans script:
    Created symlink /etc/systemd/system/default.target.wants/ca-certificates.path -> /usr/lib/systemd/system/ca-certificates.path.
    Created symlink /etc/systemd/system/multi-user.target.wants/kbdsettings.service -> /usr/lib/systemd/system/kbdsettings.service.

...
Output of udev-234-lp152.31.34.1.x86_64.rpm %posttrans script:
    Creating /lib/udev -> /usr/lib/udev symlink.

..done]
The command '/bin/sh -c zypper --non-interactive install netdata' returned a non-zero code: 107
```

**Comment by Ferroin** [comment] 2022-03-07 12:26
Based on further investigation, this is a result of issues in how openSUSE chooses to handle systemd (namely, they blindly assume that there is a running instance of systemd no matter whether this actually makes sense or not). Given this, it should actually affect _any_ type of containerization that does not run an init process.

Our own package does the best it can within the constraints we have to work under, but a number of our indirect dependencies (most notably dbus) do not. Until this gets fixed upstream we can’t really do anything about it ourselves, so I’m labeling this issue appropriately and moving it out of the backlog.

**Comment by tkatsoulas** [comment] 2023-02-28 11:43
Trying to close this issue and provide a workaround. I can't reproduce the actual bug described above (at least in the leap version)

After some further investigation, Suse ecosystem provides container images which are specifically designed to [perform operations with systemd on a host](https://documentation.suse.com/container/all/single-html/SLES-container/index.html#id-sle-bci-base-and-sle-bci-init-when-you-need-flexibility). I think if we use these Base Container Images, we will not bump again to this issue

**Comment by Ferroin** [comment] 2023-03-21 14:20
Correction, this is not actually an upstream issue, we are just doing absolutely braindead things in our RPM spec file for handling system service installation. This is also broken on Amazon Linux 2023, and in retrospect I’m amazed it happens to work on any RPM platform at all.

Draft PR shortly to fix this.

**Closed as completed** 2023-03-27 13:19 UTC
Labels: bug, area/packaging
