### ISSUE TITLE
Cent OS Dependency problem

### ISSUE THREAD

**Issue by alfredvalderrama98** [netdata/netdata#7936] opened 2020-01-31 03:07 UTC
##### Question summary

Press ENTER to run it > 
yum install Judy-devel autoconf-archive autogen libmnl-devel libuuid-devel libuv-devel lz4-devel 
Last metadata expiration check: 0:02:23 ago on Fri Jan 31 10:25:00 2020.
No match for argument: Judy-devel
No match for argument: autoconf-archive
No match for argument: autogen
No match for argument: libmnl-devel
No match for argument: libuv-devel
Error: Unable to find a match: Judy-devel autoconf-archive autogen libmnl-devel libuv-devel

##### OS / Environment
CentOS 8
##### Component Name
Judy-devel autoconf-archive autogen libmnl-devel libuuid-devel libuv-devel lz4-devel
##### Expected results
Im expecting that it will automatically install. But those packages listed cannot found in any centos repositories. Please fix this error.

**Comment by prologic** [comment] 2020-01-31 04:18
Duplicate of #6967 and fixed by #7890 and #7918 

Please help me test the fixes :) These PRs will be merged soon!

**Closed** 2020-02-04 19:52 UTC
Labels: duplicate, no changelog, question
