### ISSUE TITLE
netdata alerting service is not reliable 

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9342] opened 2020-06-15 16:17 UTC
##### Bug report summary

We have 5 netdata masters and all of them managed by ansible so they have the same configuration.
yesterday, I had to change an alert template about storage, after `killall -URS2 netdata` command, I only got 1 alert from past which was indicating one of our certificates will expire in 13 days which is correct, today, again I had to change an alert template about storage and after `killall -USR2 netdata`, I got A LOT of alerts, most of them indicating `web_log` last collected on some of our Nginx servers is more than 17 days!
The worse part is I got an alert from one of our MySQL databases which claiming `seconds_behind_master` is more than 6 hours whereas the alert template is 15 minutes (I'm using go version of MySQL plugin):
```
template: go_mysql_replication_lag
      on: mysql.slave_behind
   hosts: !mariadb-02.db.x.y.z *
    calc: $seconds_behind_master
   units: seconds
   every: 10s
    crit: $this > 900
   delay: up 15s down 15m multiplier 1.5 max 1h
    info: the number of seconds mysql replication is behind this master
      to: dba
```
Since we persist metrics on the Prometheus, I checked the history and realized this change has happened on May 24th (about a month ago) and again I checked our slack channel on this day and didn't see any alerts from netdata about this problem.
P.S: While I was writing this issue, I had to change another health template and again after `killall -USR2 netdata` I didn't get any of the previous alarms and just got the certificate expiry alert

##### Netdata version

 1.22.1 on both masters and slaves

##### Component Name

health.d

**Comment by thiagoftsm** [comment] 2020-06-17 20:54
Hi @yasharne ,

I am investigating this problem now, it looks like it has relationship with a reset Netdata does when it is reloading the logs. I will bring more information in the next hours.

Best regards!

**Comment by thiagoftsm** [comment] 2020-06-20 00:46
Hi @yasharne ,

I debugged your problem during the last days and I observed that when I had a small number of slaves, I could not recreate the problem, on the other hand, when the number was growing the event starts to happen. 
I am suspecting that you are having problems with Netdata `lock` system that we are working. On the other hand, yesterday an user that is working with nightly builds reported to us a problem that he began to have. On his environment, the slaves are not streaming more to master all the variables necessaries for the master raise alarms. 
Considering both possibilities, I would like to answer few questions for you:

1 - Are you only working with the latest stable version?  If you are, did you have problems like this before the version 1.22.1?
2 - Is the stream between slave and master stable? Or are you seeing gaps on your charts?

Best regards!

**Comment by yasharne** [comment] 2020-07-28 09:12
Sorry @thiagoftsm, I didn't notify on your answer.
1. yes I'm using the latest version
2. the connection is stable and there no gaps
I also encountered the same issue again, we had set an X509 certificate alert threshold on 30 days, later we changed it to 90 days, and today after running `killall -USR2 netdata` netdata fired an alert about this certificate indicating it will expire in 77 days! and we didn't get any notification on certificate expiry in the previous days, it has passed 13 days from the 90-day threshold

**Comment by ilyam8** [comment] 2020-07-28 10:51
Perhaps [`repeat`](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-repeat) option is workaround here?

**Comment by yasharne** [comment] 2020-07-28 11:26
@ilyam8 The `repeat` option was turned on but we still didn't get the notification

**Comment by thiagoftsm** [comment] 2020-08-11 01:42
Hi @yasharne ,

Firstly I apologize the big delay, but I was busy with other Netdata features.

I worked today debugging deeply the problem that you reported, and I arrived in the conclusion that in reality we have two bugs here and not only one. 

I set up an environment that had parent(old master) and child (old slave) with the same Netdata version and configuration(they have the same `health_alarm_notify.conf` and both had `dbengine`). The unique change was made on parent, because I commented the lines 677 and 678 before to compile:

https://github.com/netdata/netdata/blob/6caa2b65cae0193ca776cc53be64b873c16e3563/health/health.c#L677

with this change I had both parent and child sending for the same channels the alarms.  Finally I changed the [10min_cpu_usage alarm] (https://github.com/netdata/netdata/blob/master/health/health.d/cpu.conf) to become a second alarm when I had a high cpu usage.

After to do these changes I cleaned my database, and I executed the next two tests:

1 - In the first test, I did exactly what you did on your environment, I used `killall -USR2` on parent and the child runs without stop.
2 - In the second test, I did not use `killall -USR2` to reload the parent health, instead I stopped the child different times and I restarted it.

After these tests, I arrived in the following conclusions:

1 - We have a real problem with alarms when either the `parent` receives a `-USR2` or the `child` is restart, this creates delay on parent to send the alarm or even worse, the alarm is ignored on parent, but the child sent me it. For both errors, I verified that I did not miss data on streaming channel, the parent database and the child database was 100% equal.
2 - There is another bug that I detected, and this does not have relationship with `parent` or `child`. I always received at least the double of alarms on Telegram than Slack. This bug can be also confirmed on my `error.log`.

I will continue working on both bugs during this week.

Best regards!

**Comment by thiagoftsm** [comment] 2020-08-14 01:45
I finished the tests to understand what is happening, I had to use two different versions of Netdata, because the spawn server has a bug that was not allowing me to do the number of tests I wanted. I used Netdata 1.20.0 and netdata v1.24.0-26-gd897c6512.

I continued the tests that I described in the [link](https://github.com/netdata/netdata/issues/9342#issuecomment-671675113). I added the debug messages at

https://github.com/netdata/netdata/blob/61ae554aebdf790c70cb640da5c46f0d5fd70195/collectors/proc.plugin/proc_stat.c#L1066

to confirm that `child` were adding messages at the correct time.

I also added two debug messages inside the spawn.c

https://github.com/netdata/netdata/blob/61ae554aebdf790c70cb640da5c46f0d5fd70195/spawn/spawn.c#L70

and

https://github.com/netdata/netdata/blob/61ae554aebdf790c70cb640da5c46f0d5fd70195/spawn/spawn.c#L108

to check that what was scheduled was really executed.

to compare the values used on `child` and `parent` I also added a debug message at line 

https://github.com/netdata/netdata/blob/61ae554aebdf790c70cb640da5c46f0d5fd70195/health/health.c#L869

where I print the values `rc->value`, `rc->warning->result`, and `rc->critical->result`.

Finally I added a debug message at

https://github.com/netdata/netdata/blob/61ae554aebdf790c70cb640da5c46f0d5fd70195/web/api/queries/query.c#L1161

to print some details about the result delivered by the function `rrdset2value_api_v1`.

I always used the endpoint `api/v1/data?chart=system.cpu`  to compare the raw data and I observed that they are 100% equal  on parent and child.

The debug message used inside `proc_stat.c` and `query.c` helped me to confirm that we always use the same number of points to do the math.

I also observed that with the results that Netdata got from `rrdset2value_api_v1` health is working as expected, the system is not missing any alarm.

Finally I observed that independent of the changes I made in the alarm, for good part of the time I had different results for alarms generated on parent and child and these results are coming from the function  `rrdset2value_api_v1`. As the values are not 100% equal all time on parent and child for the same period of time, the two Netdatas did not generate the same alarms.

There is a work in progress to improve our stream, but at least with 1 child I could not observe problems with the raw data. My concern here is with the functions that make aggregations, because `rc->value` should be equal on parent and child and this is the problem that @yasharne is reporting for us.

**Comment by yasharne** [comment] 2020-09-30 15:15
@thiagoftsm 
I encountered the problem again, parent and child both are `v1.24.0` and I accidentally realized the child was not sending metrics for a long time but we didn't get any last collected errors at all:
![image](https://user-images.githubusercontent.com/7656049/94704377-b5f40c80-034c-11eb-9e0b-bd8ceca7071d.png)

The rime range is July 24th to September 30th

**Comment by yasharne** [comment] 2022-02-22 15:32
Hi @ilyam8 
I still see this problem in some children (it is not easy to find it, we discover it either by chance or when the service breaks)
![image](https://user-images.githubusercontent.com/7656049/155165208-7336c2e0-696b-404d-a350-a0d12a195560.png)

**Comment by cronlabspl** [comment] 2022-02-22 19:04
@yasharne while I dont experience the bug you're experiencing, I can wholeheartedely agree that alerting service in ND sucks big time.

**Comment by stelfrag** [comment] 2022-02-23 13:38
> Hi @ilyam8 @thiagoftsm I still see this problem in some children (it is not easy to find it, we discover it either by chance or when the service breaks) ![image](https://user-images.githubusercontent.com/7656049/155165208-7336c2e0-696b-404d-a350-a0d12a195560.png)

@yasharne what netdata version are you currently using?

**Comment by cronlabspl** [comment] 2022-02-24 06:31
TBH after today's night where ND was left on-screen, and hasnt been touched for 7+ hours, all the charts in dashboard were displaying `timeout`, I musat say that not only alerting is unreliable, but **whole ND is piece of unusable crap**.

Sorry for my language, but situations like this ( timeouts ) is totally unacceptable in any serious workplace.

Just imagine monitoring critical infrastructure during some "down period" and, out of the blue, critical chart(s) go `timeout`ed. Infuriating as hell.

**Comment by ktsaou** [comment] 2022-02-24 08:00
@yasharne @cronlabspl thank you for these reports. Please don't give up yet.

From the chart you posted, I see that your system starved for CPU. Netdata by default runs with `CPUSchedulingPriority=idle` so your system didn't allow netdata to run while your system was under pressure.

We have made this choice as a default to respect the production applications you run. If they need all the CPU, Netdata stops for a while, and this is reflected on the charts via these gaps.

To change this, you can edit `netdata.service` and set:

```
CPUSchedulingPolicy=rr
CPUSchedulingPriority=99
```

This way, Netdata will get all the resources it needs, no matter what.

Another sane use is this:

```
CPUSchedulingPolicy=other
Nice=0
```

This will allow netdata to compete for resources with the same priority as every other application.

Generally, for production systems I prefer to have netdata freeze when the system starves for resources and indicate this at the charts. The monitoring system should never negatively influence the operation of the system.

But probably having it compete equally is a better default, to avoid such confusing conditions with big gaps.

@yasharne at the "Applications", "Users" and "Groups" sections of the dashboard, can you tell which apps, users, groups needed all the CPU resources?

> @yasharne while I dont experience the bug you're experiencing, I can wholeheartedely agree that alerting service in ND sucks big time.

@cronlabspl please help us understand why. What issues do you face with alerts in ND?

**Comment by cronlabspl** [comment] 2022-02-24 08:13
@ktsaou oh c'mon; Seriously you think that timeouts are ok in serious monitoring solution ND tries to be? Or are you trying to say its not NDs fault? Than let me say this: there was other monitoring solution powered up monitoring same env, and guess what? **Nothing**, not even warming, not to mention critical alert.

**Comment by ktsaou** [comment] 2022-02-24 08:37
> Seriously you think that timeouts are ok in serious monitoring solution

Well, if your system starves for resources, you have to pick. You want the monitoring to work or you want the application to work? I get your point though. Probably the right solution is to let both apps compete equally.

@Ferroin please make a PR to remove the settings that lower the scheduling priority of netdata. Let's have the netdata compete for resources.

> Than let me say this: there was other monitoring solution powered up concurently monitoring same env, and guess what? **Nothing**, not even warming, not to mention critical alert.

Well, if your system starves for resources to the degree applications cannot be reliably run and the monitoring solution doesn't say anything about it, I think that monitoring system is not reliable. I understand our choice of showing gaps may not be good. This is why, based on your report, we are going to change this default behavior of netdata.

> We gave ND an extensive test-ride for 2 weeks,

Thank you for that!

> ND proved itself to be unreliable ( to say midly )

Why? What happened? I would love some more feedback.

If you are available for a quick call, I would love to hear from you the problems you faced. Send me an email to costa@netdata.cloud.

> we went to your forums/Discord only to be met with **hostility** of your team.

Oops! I am really sorry for that! This should never happen!
@cakrit please check this and let's find a way so that this never happens again.

**Comment by cronlabspl** [comment] 2022-02-24 08:45
@ktsaou there is nothing more to add in email as everything was posted by me here..........

> Well, if your system starves for resources

Thats untrue. We have quite a big amount of resources lying idle waiting to be used. None of our system starves for resources.

> Well, if your system starves for resources to the degree applications cannot be reliably run and the monitoring solution doesn't say anything about it, I think that monitoring system is not reliable.

Thats also untrue. Whats more: you arer pushing fault away from ND. As you are original creator of ND its quite understandable, but please, do not change facts........

> Why? What happened? I would love some more feedback.

Please read posts prior to this to understand what happened

**Comment by ktsaou** [comment] 2022-02-24 13:01
> there is nothing more to add in email as everything was posted by me here..........

You mean in this ticket? You haven't said much in this ticket, so probably you mean some other ticket. Please mention me in them. I really want to know! I am sorry I don't monitor every ticket. They are way too many...

> Thats untrue. We have quite a big amount of resources lying idle waiting to be used. None of our system starves for resources.

Probably we are talking about different things. This is a very old ticket opened by @yasharne and the last image he has posted 2 days ago, shows clearly a system that starves for resources.

> Thats also untrue. **Its not infrastructure thats unreliable** What more: you are pushing fault away from ND.

This is unfair I think. I am not trying to push away any fault from netdata. The opposite actually. I am trying to understand where is the netdata fault you found. I need to understand you and I am asking for feedback that will help us make netdata better.

> As you are original creator of ND and ND is taken care of by for-profit company, its quite understandable, but please, do not change facts........

I understand you are pissed off and I am really sorry we did this to you. Still I think your comment implies some kind of a dark plan, which is not there.

The netdata agent is OSS and will remain like this forever. We want the netdata agent to be the best single node monitoring, with automation, features, ease of use and capabilities unlike any other solution. And I think we have already achieved that to a great degree. All the monitoring value we create is inside the OSS agent. Our DB is there, our ML is there, we are moving our correlation engine there. Of course there are issues to solve. There will always be. We are hunting them! We are committed to solve them. And we need your feedback to pin point them!

Netdata Cloud is closed source but it is a thin layer orchestrating the agents and providing user collaboration. It has no monitoring value by itself. It relies on the agent for everything it does. Of course it is complicated. We need it to scale to millions of nodes connected. We have 40k nodes online as we speak! We spent the last 2 years refactoring it to make it scale. Although closed source, we are committed to provide it as a free SaaS to the whole world. Yes, this is a bet. It has a risk attached to it. Will we be able to sustain it?

To sustain it, the cloud needs to be extremely thin. All the magic should happen at the agent and the browser. The cloud should do the absolute minimum to properly support a highly distributed architecture, using the agent features to provide high fidelity monitoring and automated troubleshooting.

Of course the company will eventually need paying customers. We are 70 people in netdata now. This does not necessarily contradict the OSS or the free SaaS. Actually the greater the success of the OSS and the free SaaS, the most likely it is for netdata as a company to succeed financially too. Not with a dark plan, but by offering services on top of the free SaaS that companies will be willing to pay for because it will be a lot more cost efficient for them to use netdata for monitoring and troubleshooting instead of anything else, including open-source solutions (yes, open-source solution do cost to run).

Think of it for a moment. An amazing OSS monitoring solution and a permanently free SaaS, financially viable just because businesses around the world find value in it, want the most out of it and are prepared to pay for it. Not for monitoring. This is free forever. But to integrate it better with their processes.

So, our only plan currently is to please our users! We will not gain anything by hiding our problems and pushing netdata faults away. We will never succeed if we do this. Because our success goes through the massive adoption of the OSS and free SaaS.

> If it can be of any value I will add that none of our monitored systems went unresponsive in.... quite a long period of time.

Probably I am not aware of the problems you have. Please mention me in your tickets.

> Please read posts prior to this to understand what happened.

Please mention me at your posts. I really want to understand.

> If you want my honest opinion, here you go: if you want ND to prosper ( and Im sure you do ) ND needs to be rewritten from scratch. There were **so many** bad design-wise ( I mean code design; not UI design ) decisions taken that as the codebase grow, it becomes harder and harder to correct them.

Thank you for sharing your opinion. But this does not resolve in my mind. It is an open-ended suggestion. Rewrite what? Why?

Could you please open tickets with your suggestions? I would love to discuss them.

**Comment by cronlabspl** [comment] 2022-02-24 14:04
> An amazing OSS monitoring solution 

Maybe one day it will be amazing, who knows? Let it be / let it not be. Its a question of your ( as a business leader ) skills.......
As of today: ND has long way ahead, should it become "amazing OSS monitoring solution"

>  Rewrite what? 

ND core

> Why?

Because itas heavily impacted by flawed design decisions taken when in planning-phase.........

> Which weaknesses you see?
Wow. Many. Just read Discord channel ( my nick on Discord is: wlisikpl ). I discussed it there in great detail. Will not repeat myself. If, after reading, any questions arise, just ping me, either here, or on Discord.........

> Probably I am not aware of the problems you have. Please mention me in your tickets.
Read Discord, you will be aware than......... I will not mention you, because I simply dont care anymore........

> where is the netdata fault you found
OK: Will repeat this for you ( I regret not taking screenshot of this ) : 

After one night ( 7 hours ) of displaying dashboard every graph ( out of 6 ) on it had "Timeout" written in red colour in t5he left topmost corner and NO data has been displayed.

This and much, much more.

> They are way too many...
What? Excuse me but this is lame excuse. As a project founder / leader you **have to** closely follow things like tickets. If you cant handle this (due to whatever), than just resign.

**Comment by cronlabspl** [comment] 2022-02-25 00:35
@ktsaou @cakrit 
Just logged to my private ND instance and guess what I saw?

https://imgur.com/HtqjSbL

Pay close attention to RAM availability / usage......

This proves the problem reported by @yasharne **is still valid**.

Sorry guys, I seriously feel bad for you @ktsaou @cakrit .......

**Comment by ktsaou** [comment] 2022-02-25 06:03
@cronlabspl 

> Pay close attention to RAM availability / usage......

I understand you mean that the chart of memory availability in netdata is wrong.
Let's see. The data comes from here:

In the screenshot you posted, `htop` says you are using `459MB` out of `7.67G`. In the netdata chart I see the currently available is `7.0137G`. 

Let's verify. Please run this:

```sh
cat /proc/meminfo  | grep MemAvailable
```

What does it say?

**Comment by cronlabspl** [comment] 2022-02-25 11:39
@ktsaou what are you talking aBOUT? I cleasrly showed that alerting is unreliable; so what else you need? and what you need it for? There is nothing to verify.

You still seems to push guilt away from ND upon me.

**Comment by ktsaou** [comment] 2022-02-25 17:10
@cronlabspl as you wish. Thank you for your contribution so far.

---

@yasharne sorry for derailing this ticket. Do you need help with the issue you face?

**Comment by MrZammler** [comment] 2022-05-20 13:44
@yasharne hi! Have you checked with an updated agent?

**Closed** 2022-06-29 14:41 UTC
Labels: bug, area/health, needs triage
