### ISSUE TITLE
Install on a managed dedicated web server?

### ISSUE THREAD

**Issue by analyserdmz** [netdata/netdata#14340] opened 2023-01-27 18:32 UTC
### Problem

I am trying to find information on installing netdata on a managed (WHM / CPanel) dedicated web server.

### Description

I am trying to find information on installing netdata on a managed (WHM / CPanel) dedicated web server, without disrupting the existing accounts and services running on it, like NGinx / Apache / MySQL etc.

Is there a way to separately install netdata without touching existing services?

Thank you.

### Importance

must have

### Value proposition

1. Install without disrupting running services.
2. Have a solution for managed servers in general.

**Comment by Dim-P** [comment] 2023-01-30 09:48
Hi @analyserdmz , thank you for your interest in Netdata! WHM should allow you to login as root, in which case you can use our [one-line installer script](https://learn.netdata.cloud/docs/get-started). You don't need to restart any services once you install Netdata, so nothing would be disrupted.

**Comment by ilyam8** [comment] 2023-01-30 09:51
An additional question: why do you mean by "disrupting the existing accounts and services running"?

**Comment by Dim-P** [comment] 2023-02-06 11:19
@analyserdmz Is this still a problem for you? Have you tried logging in and installing Netdata using the `kickstart.sh` script?

Also, please answer @ilyam8 's question to help us understand better what the problem is.

**Comment by analyserdmz** [comment] 2023-02-06 12:28
> An additional question: why do you mean by "disrupting the existing accounts and services running"?

I mean without touching the current nginx configuration. Because the server is currently hosting cusomers' websites and I am afraid of messing their websites.

**Comment by Dim-P** [comment] 2023-02-07 12:35
> > An additional question: why do you mean by "disrupting the existing accounts and services running"?
> 
> I mean without touching the current nginx configuration. Because the server is currently hosting cusomers' websites and I am afraid of messing their websites.

Netdata doesn't write to any configuration of services or software that it monitors, so it should be safe to use. Did you try to install the Netdata agent using the `kickstart.sh` script from the link above?

**Comment by Ferroin** [comment] 2023-02-07 13:00
@Dim-P I think @analyserdmz is referring to the configuration required to actually expose Netdata for remote access, though I’m a bit confused myself (this type of thing is exactly what virtual hosts are for, and adding a new one just for Netdata shouldn’t disrupt any of the others).

**Comment by MrZammler** [comment] 2023-02-21 14:45
Hi @analyserdmz ! Did you install Netdata ? Have you encountered any issues?

**Comment by MrZammler** [comment] 2023-02-28 08:33
Closing this for now, @analyserdmz if you have any updates please let us know. Thanks!

**Closed by MrZammler** 2023-02-28 08:33 UTC
Labels: bug, question, area/docs

**Comment by Dim-P** [comment] 2023-02-28 09:22
@MrZammler I know that @ilyam8 wanted to update the docs about this topic, since other users have had a similar question in the past. Only reason I kept the issue open (and tagged as `area/docs` and `bug`).

@ilyam8 Can you please make a PR about this?

**Comment by Dim-P** [comment] 2023-02-28 09:36
> @Dim-P I re-read the discussion and am not sure what docs need to be updated.

OK, np. Let's reopen it if it comes up again from the OP or anyone else.
