### ISSUE TITLE
[health] segfault on empty rrdset with repeating alerts

### ISSUE THREAD

**Issue by Saruspete** [netdata/netdata#10553] opened 2021-01-26 01:23 UTC
##### Bug report summary
When a recurring alert is generated again, but the rrdset was deleted, we have a segfault
the coredump I got is in [health/health.c:981](https://github.com/netdata/netdata/blob/master/health/health.c#L981) and is around since 1.17 up to 1.28

##### OS / Environment

All netdata version since 1.17 to 1.28, on RHEL 6, 7 and 8.

##### Netdata version
Netdata 1.17 to 1.28, built from contrib/rhel/build-netdata-rpm.sh

##### Component Name
Health

##### Steps To Reproduce

Not always able to. 

1. Enable repeating error in `[health]` section with `default repeat warning = 1m`
2. get an alert to trigger (eg, fill memory)
3. In my coredump, errors are about cgroup (don't know yet if it's due to a netdata restart/reload, or the cgroup being deleted)

Note: I was first thinking about create a tmpfs, filling it and umounting it, but the data is still collected using the parent mountpoint instead. 

I cannot upload the coredumps (airgap system),  but I can do whatever command / check you want. Here's an extract of one (having `now = 1611308422` : Fri Jan 22 10:40:22 CET 2021)
```
SEGFAULT in health_main.
>>> p *rc
$1 = {
avl = {
  avl_link = {[0] = 0x10f787a0, [1]=0x11177200},
  avl_balance = 0 '\000'
},
id = 1611075547,
next_event_id = 10,
name = ... "cgroup_ram_in_use"
hash = 3547325902,
exec = 0x0,
recipient = ... "sysadmin"
chart = 0x11175c30 "cgroup_twisp_4381207.mem_usage",
hash_chart = 278533502,
plugin_match = 0x0,
plugin_pattern = 0x0,
module_match = 0x0,
module_pattern = 0x0,
source = ... "16@/usr/lib/netdata/conf.d/health.d/cgroup.conf",
units = ... "%",
info = ... "RAM used by cgroup",
update_every = 10,
green = nan,
red = nan,
dimensions = 0x0,
foreachdim = 0x0,
spdim = 0x0,
foreachcounter = 0,
group = RRDR_GROUPING_UNDEFINED,
before = 0,
after = 0,
options = 0,
calculation = 0x11176810,
warning = 0x1176e10
critical = 0x11177430,
delay_up_duration = 0,
delay_down_duration = 0,
delay_multiplier = 1,
warn_repeat_every = 900,
crti_repeat_every = 300,
labels = 0x0,
splabels = 0,0,
old_status = RRDCALC_STATUS_CLEAR,
rrdcalc_flags = 0,
last_updated =  1611302960,        # Fri Jan 22 09:09:20 CET 2021 ( now - 5462 )
next_updated = 1611302970,         # Fri Jan 22 09:09:30 CET 2021 ( now - 5452 )
last_status_change = 1611300320,   # Fri Jan 22 08:25:20 CET 2021 ( now - 8102 )
last_repeat = 1611307522,          # Fri Jan 22 10:25:22 CET 2021 ( now -  900 )
db_after = 0,
db_before = 0,
delay_up_to_timestamp = 1611300320,   # Fri Jan 22 08:25:20 CET 2021 ( now - 8102 )
delay_up_current = 0,
delay_last = 0,
local = 0x0,
family = 0x0,
hostid = 0x0,
hostname = 0x0,
rrdset = 0x0,
rrdset_next = 0x0,
rrdset_prev = 0x0,
next = 0x11177200
}
```

We see it's a repeating alert, as the "last_repeat" matches the value configured (15m = 900) which matches also the condition in the source file.

##### Expected behavior
netdata shouldn't segfault, and the alarm should be cleaned when the rrdset is removed.

**Comment by stelfrag** [comment] 2021-01-26 07:39
Hi @Saruspete !!! :wave: 

Thank you for reporting this!!

**Comment by Saruspete** [comment] 2021-01-28 17:09
I'd like to fix the bug, but I'm not sure how to fix it in the global alerts workflow. Should we just skip it, remove it totally, should it be done when removing the rrdset itself... ?

@thiagoftsm do you have an idea on how we should handle it ?

**Comment by thiagoftsm** [comment] 2021-01-29 10:55
Hello @Saruspete ,

When a `rrdset` is removed, it does not make sense we keep an alarm for it. I think the safest here is remove it completely. 

Best regards!

**Comment by erdem2000** [comment] 2022-02-20 09:10
Hi @Saruspete ! 
@ilyam8 and I tested this issue with different combinations on the master branch and latest version of the Netdata and unfortunately ( maybe fortunately :) ) we could not reproduce segfault.  
So I would like to ask you if you still experience this issue with the latest version or the master branch of the Netdata. If you don't then we can close it.

**Comment by erdem2000** [comment] 2022-03-03 07:40
@ilyam8 and I could not reproduced the issue again. So It is closed.

**Closed by erdem2000** 2022-03-03 07:40 UTC
Labels: bug, area/health, needs triage
