### ISSUE TITLE
Alarms dialog does not load correctly

### ISSUE THREAD

**Issue by djmattyg007** [netdata/netdata#9035] opened 2020-05-14 08:20 UTC
##### Bug report summary
Loading the Alarms dialog by clicking on the Alarms button in the toolbar does not work correctly. I get four error messages, one after the other, informing me that various JS libraries failed to load.

Specifically, the following libraries fail to load:

- clipboard-polyfill-be05dad.js
- bootstrap-table-1.11.0.min.js
- bootstrap-table-export-1.11.0.min.js
- tableExport-1.6.0.min.js

I believe this is something to do with how I'm accessing Netdata. I have Nginx set up to reverse proxy to Netdata, following the instructions here, in the "As a subfolder for multiple Netdata servers, via one Nginx" section:

https://learn.netdata.cloud/docs/agent/running-behind-nginx/#as-a-subfolder-for-multiple-netdata-servers-via-one-nginx

For some reason, for the four libraries listed above, instead of trying to load URLs that look like this:

https://example.com/netdata/hostname/lib/library.js

The URLs look like this:

https://example.com/netdata/lib/library.js

To confirm, I do have the snippet in place that ensures there is a trailing slash, and that does appear to be working correctly.

##### OS / Environment
```
Linux shacklebolt 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux
/etc/os-release:NAME="Arch Linux"
/etc/os-release:PRETTY_NAME="Arch Linux"
/etc/os-release:ID=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:HOME_URL="https://www.archlinux.org/"
/etc/os-release:DOCUMENTATION_URL="https://wiki.archlinux.org/"
/etc/os-release:SUPPORT_URL="https://bbs.archlinux.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.archlinux.org/"
/etc/os-release:LOGO=archlinux

```

##### Netdata version
netdata v1.22.1
 

##### Component Name
Alarms dialog in dashboard

##### Steps To Reproduce
Click on the alarms button in the toolbar

##### Expected behavior
There should be no errors when loading the dialog.

**Comment by sebastianopilla** [comment] 2020-05-19 21:14
I have the same setup (netdata behind nginx, in a subdirectory) and I can confirm that I have the same problem with 1.22.1. The requests for the 4 above mentioned js files return a 404 error to the browser.

Sample screenshots:

![Screenshot_20200519_230044](https://user-images.githubusercontent.com/1286189/82378460-6f4ce800-9a25-11ea-8e3c-67a06b21ceb3.png)
![Screenshot_20200519_230117](https://user-images.githubusercontent.com/1286189/82378463-707e1500-9a25-11ea-9ff7-99b39ed17913.png)
![Screenshot_20200519_230142](https://user-images.githubusercontent.com/1286189/82378464-707e1500-9a25-11ea-944e-525151ab94bd.png)
![Screenshot_20200519_230338](https://user-images.githubusercontent.com/1286189/82378466-7116ab80-9a25-11ea-8651-4e8decbd781f.png)

The requests as they appear in my browser's console:

![Screenshot_20200519_230222](https://user-images.githubusercontent.com/1286189/82378465-7116ab80-9a25-11ea-8196-8de7cfc4d1de.png)

Though I'm far from being a JavaScript expert, I noticed a change in the `web/gui/main.js` file which may have something to do with the errors. The relevant line in 1.21.1 is

https://github.com/netdata/netdata/blob/v1.21.1/web/gui/main.js#L1935

and in 1.22.1 this line has changed to 

https://github.com/netdata/netdata/blob/v1.22.1/web/gui/main.js#L1932

Editing the main.js file to conform to the 1.21.1 version makes the alerts go away for me.

**Comment by thiagoftsm** [comment] 2020-05-19 23:00
@jacekkolasa , please, take a look on this for us.

**Comment by jacekkolasa** [comment] 2020-05-21 09:45
I think it's a cache problem (related to https://github.com/netdata/netdata/issues/8889), @sebastianopilla @djmattyg007 can you please check if the same situation happens in private mode? I see in screenshots that it's loading old Dashboard (1.21 or older). New dashboard (with different navbars) looks like this: https://frankfurt.my-netdata.io/

The `../${url}` in /web/gui/main.js@v1.22.1#L1932 was done to support old dashboard with `/old/` suffix and that main.js should be loaded in that case. New codebase was moved to https://github.com/netdata/dashboard repo

**Comment by sebastianopilla** [comment] 2020-05-23 13:09
@jacekkolasa Thanks for your input, I see the same issue in private mode.

I tried a manual install of the new dashboard, replacing the old one: I didn't get the 4 JavaScript alerts above, but instead a different JavaScriptalert about a missing  `dashboard_info.js` file.

In the end, what made it all work for me was reinstalled (manually) the old dashboard code, and then adding on top the new dashboard code: reloading the browser page I got the look of the new dashboard and no unwanted JavaScript alert when loading the alarms dialog.

**Comment by djmattyg007** [comment] 2020-05-24 02:32
To confirm, I had the exact same experience as @sebastianopilla 

I'm using the official Arch Linux package, which only provides a single package with everything bundled together. I tried opening Netdata in private browsing mode, and that didn't change anything. I'm still seeing what is apparently the old dashboard too.

I'm not sure how reinstalling would help in this situation. I hadn't opened Netdata for months before coming across this issue, so I'm reasonably confident it's not to do with my browser cache. Are there cached assets on the server that could be the issue? If so, where are they and how can I delete them?

**Comment by tixetsal** [comment] 2020-05-25 00:34
I'm on Arch and also have the same issue.

**Comment by ghisl1** [comment] 2020-06-19 07:28
Hi, 
I have the same issue.
I think that the callback url is malformed i.e. not including the url that sent the original request in order to be properly processed by the reverse-proxy
I'm not a developer but I saw in /usr/share/netdata/web/main.js that the function loadJs use url variable.

**Comment by UBERPHP** [comment] 2020-07-14 15:06
I have the same issue on CentOS 8 on netadata v1.22.1

**Comment by marty1885** [comment] 2020-07-19 03:33
For those waiting for a proper solution. A quick hack to fix this is to make a link to the reverse proxy's default content directory. For me using `nginx` that becomes:

```bash
sudo ln -s /usr/share/netdata/web/lib /usr/share/nginx/html/lib
```

Or whatever path your Apache/Nginx/etc uses

**Comment by UBERPHP** [comment] 2020-07-19 07:53
thanks @marty1885

**Comment by tixetsal** [comment] 2020-08-09 19:08
Anyone have any ideas? I would think that this is affecting a large number of folks, but maybe I don't understand the target audience or am using netdata in a weird way with basic auth and apache reverse proxy. *?*

**Comment by UBERPHP** [comment] 2020-08-11 19:08
commit: d34f3ce1fc3fe6bdd46002311bd41a628a79717b
web/gui/main.js:1932

`url: `../${url}`,` -> url: `${url}`,

this should fix. However, I'm not Js expert and not familias with the bug fix flow in github, but  the problem with the path when loading js library via function `loadJs`

**Comment by UBERPHP** [comment] 2020-08-11 20:09
commit: d34f3ce1fc3fe6bdd46002311bd41a628a79717b
web/gui/main.js:1932

`url: `../${url}`,` -> url: `${url}`,

'../' removal should be the fix. However, I'm not Js expert, therefore I'm leaving it for someone else to fix it the proper way (with a pull request, etc. ) ;)

edit: friendly ping to @Ferroin

**Comment by jacekkolasa** [comment] 2020-08-25 10:50
Thanks a lot for the screens, and information! I wasn't aware that other packages are hosting our old dashboard. We normally don't support 3rd party packaging, but a smaller fix was possible here, so I've made a pr. To test it you can get the main.js file from https://github.com/jacekkolasa/netdata/blob/9035-fix-old-dashboard-3rd-party-packaging/web/gui/main.js and put it in proper location (typically `/usr/share/netdata/web/`).

But the best thing which we recommend is installing netdata using [one-line installation script](https://learn.netdata.cloud/docs/agent/packaging/installer#automatic-one-line-installation-script). You will be able to access new functionalities, like growing new Netdata Cloud. We cannot guarantee that newer Netdata versions will be compatible with old dashboard.

@prologic @Ferroin Do you know if there's something we can do about external packages hosting the old dashboard?

**Comment by djmattyg007** [comment] 2020-08-27 23:59
A lot of people are absolutely going to prefer installing a package provided by their distribution over an installation script provided by a software maintainer. If my distribution (eg. Arch) provides a package for something, 99.99% of the time I'm going to use that instead of installing the software manually. Doing so provides a clear managed path for upgrades, and a central point of trust for where the software running on my machine comes from.

I wasn't even aware there was a new dashboard until reading through this thread. If there's a "new" dashboard that's been available for a while, why is the "old" dashboard still available? Is it simply a configuration issue because my installation is a few years old, or is it a packaging issue? If it's the latter, I'd be happy to file an issue on the Arch Linux bug tracker if you can provide me with some technical details to pass on.

**Comment by prologic** [comment] 2020-08-28 03:11
> @prologic @Ferroin Do you know if there's something we can do about external packages hosting the old dashboard?

Our _own_ packages we can easily fix. @Ferroin  Do you know if we need to do anything here?

Any _other_ packages maintained by the community need "community reach-out". cc @zack-shoylev

**Comment by marty1885** [comment] 2020-09-04 03:38
FYI,

https://bugs.archlinux.org/task/66257?project=5&string=netdata
There's already a bug report for the exact issue on Arch's package. But the maintainer doesn't seem have fixed it. I'd like to make a patch but don't have the authorization. Any Trusted Arch User here?

**Comment by djmattyg007** [comment] 2020-11-26 10:15
So what's the path forward here? If this is just an issue with the "old" dashboard that won't be fixed, shouldn't this issue just be closed?

**Comment by ilyam8** [comment] 2020-11-26 10:33
@jacekkolasa added `wontfix` label, so it seems to be the case, i am closing the issue. @jacekkolasa repoen if i am wrong.

**Closed by ilyam8** 2020-11-26 10:33 UTC
Labels: area/web, wontfix
