### ISSUE TITLE
Unexpected ipv4 tcp listen drops

### ISSUE THREAD

**Issue by tiaga** [netdata/netdata#3234] opened 2018-01-05 12:24 UTC
Hi, 
I'm running `netdata` on CentOS 7.4 and almost every day I receive the following message via Telegram:
```
ipv4.tcplistenissues (tcp)
1m ipv4 tcp listen drops = 1 drops
the number of TCP listen socket drops during the last minute
```
I checked every log file on the server, but did not find anything that could be related to the issue. Could you please help me to detect what causes such messages?

In addition, here is `netstat` output:
```
# netstat -anp | grep LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      840/sshd            
tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN      31168/netdata       
tcp        0      0 127.0.0.1:19999         0.0.0.0:*               LISTEN      31168/netdata       
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      1200/mysqld         
tcp6       0      0 :::80                   :::*                    LISTEN      837/httpd           
tcp6       0      0 :::22                   :::*                    LISTEN      840/sshd            
tcp6       0      0 :::443                  :::*                    LISTEN      837/httpd           
tcp6       0      0 ::1:8125                :::*                    LISTEN      31168/netdata       
unix  2      [ ACC ]     STREAM     LISTENING     10514    1/systemd            /run/lvm/lvmpolld.socket
unix  2      [ ACC ]     SEQPACKET  LISTENING     10524    1/systemd            /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     16466    1200/mysqld          /var/lib/mysql/mysql.sock
unix  2      [ ACC ]     STREAM     LISTENING     12968    1/systemd            /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     7592     1/systemd            /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     23225    2521/NetworkManager  /var/run/NetworkManager/private-dhcp
unix  2      [ ACC ]     STREAM     LISTENING     10458    1/systemd            /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     10483    1/systemd            /run/lvm/lvmetad.socket
```

**Comment by ktsaou** [comment] 2018-01-05 16:49
Hi, netdata just gave you an indication of the problem.

You can verify netdata is right by running this:

```sh
# netstat -s | grep -i listen
    12 SYNs to LISTEN sockets dropped
```

or this:

```sh
# nstat -a | grep -i listen
TcpExtListenDrops               12                 0.0
```

Unfortunately this is not easy to trace. There is little to no documentation about the root cause of ListenDrops (unlike ListenOverflows, which cause ListenDrops too).

**Comment by ktsaou** [comment] 2018-01-05 17:25
The only info I found about ListenDrops is this: https://github.com/BrightcoveOS/Diamond/wiki/collectors-TCPCollector

> We couldn't accept a connection because one of: we had no route to the destination, we failed to allocate a socket, we failed to allocate a new local port bind bucket. Note: this counter also include all the increments made to ListenOverflows.

Not very helpful though...

**Comment by ericfri** [comment] 2018-01-24 21:02
I'm getting the same thing. I've got netdata installed on 2 cPanel servers, both of which are VM's and the alert happens multiple times a day.

**Comment by tiaga** [comment] 2018-01-25 12:38
@ericfri I found several solutions that suggest increasing the `net.core.somaxconn` and `net.ipv4.tcp_max_syn_backlog` parameters (also, similar situation are described here: https://planet.mysql.com/entry/?id=28147)

Increasing `net.ipv4.tcp_max_syn_backlog` up to 512 did not help in my situation and I have increased `net.ipv4.tcp_max_syn_backlog` up to 1024. However, increasing `net.core.somaxconn` is needed for Apache, as its listen backlog is set to 511 by default (http://www.ryanfrantz.com/posts/apache-tcp-backlog/). So, let's wait for a while. 

You can also increase these parameters one by one to find out what parameter controls such behaviour.

**Comment by nafex** [comment] 2018-01-26 13:23
@tiaga I have the same issue. Please report back if increasing net.ipv4.tcp_max_syn_backlog resolved the issue for you. Thank you.

**Comment by ericfri** [comment] 2018-01-26 22:19
my `net.ipv4.tcp_max_syn_backlog` was already at 1024 and my `net.core.somaxconn` was at 128. I've bumped `net.core.somaxconn` up to 1024 based on [NASA's](https://wiki.earthdata.nasa.gov/display/HDD/SOMAXCONN) suggestions

**Comment by ericfri** [comment] 2018-01-30 21:05
My change didn't resolve the issue. I will continue to dig into it when I can.

**Comment by tiaga** [comment] 2018-02-16 16:06
I finally find out the root cause of the issue using Wireshark:
![1](https://user-images.githubusercontent.com/10153548/36315330-f6097f38-1369-11e8-96de-d86a13084bdd.png)
And it's a kind of ICMP attack (with the ICMP type 3 [Destination unreachable] package) that causes connection reset. 
So, in my case it's just bots, but I'm going to figure out how to protect my server from such behaviour. Note, that it is a **bad idea to drop all ICMP packages**.

**Comment by ktsaou** [comment] 2018-02-19 20:05
I think the iptables `RELATED` match allows only ICMP that are related to a connection in the conntrack table.

**Comment by eleshar** [comment] 2018-03-12 11:34
@tiaga Did you ever manage to find a solution to the reported issue?

**Comment by tiaga** [comment] 2018-03-12 14:05
@eleshar yes, in my case I added the following rules to `iptables`:
```
# iptables -A INPUT -p icmp -m icmp --icmp-type 3/4 -m conntrack --ctstate NEW -j ACCEPT
# iptables -A INPUT -p icmp -m icmp --icmp-type 3 -j DROP
```
But it's not a general solution. First of all, I would recommend you gather network packages using `tcpdump` and make sure that ICMP attacks are the root cause.

**Comment by djfordz** [comment] 2018-05-24 09:52
experiencing same issue on high traffic server that gets flooded with bot traffic.

Going to setup tcpdump, thank you for suggestion @tiaga 

Although I appreciate the information here, is it common to open issues that are not related to the software code?

**Comment by ktsaou** [comment] 2018-05-27 12:48
> Although I appreciate the information here, is it common to open issues that are not related to the software code?

well, it is always related. For example, based on your findings we may decide the change the alarm (ie. change the thresholds, the description, correlate it with something else, or even delete it).

Actually, I would love to have an issue for each alarm where we can discuss about them and link that issue in the alarm notifications, so that people having this alarm could easily exchange ideas. But I don't have the time to do it. If anyone is willing to help, please do so...

**Comment by arnowelzel** [comment] 2018-06-14 08:21
Further reading:

https://perfchron.com/2015/12/26/investigating-linux-network-issues-with-netstat-and-nstat/
https://blog.cloudflare.com/syn-packet-handling-in-the-wild/
http://www.nateware.com/linux-network-tuning-for-2013.html
https://blog.cloudflare.com/the-story-of-one-latency-spike/

**Comment by literal** [comment] 2018-09-18 11:40
I'm also getting a handful of `1m ipv4 tcp listen drops` alarms every day from a moderately busy server.

And while I'm still investigating, finding it quite difficult to find reliable in-depth information on the Linux network stack on the web, there are already some things I'd like to point out:


@tiaga I don't believe your Wireshark screenshot shows an attack:

- The client requests to open a TCP connection by sending a SYN packet.
- Your server continues TCP handshake by replying with a SYN/ACK packet.
- The SYN/ACK packet doesn't reach the client because it's blocked by a firewall.
- The client's (well-behaved) firewall sends your server an ICMP packet to indicate what happened ("administratively prohibited" means just that - a firewall blocked the packet).
- Your server sends a TCP reset packet to indicate it aborted the handshake (even though this packet will probably not reach the client, either).

To me this looks like a misconfigured firewall on the client side. And I doubt this will even be counted as `SYNs to LISTEN sockets dropped` reported by `netstat`. My understaning of `SYNs to LISTEN sockets dropped` is that it means SYN packets silently discarded (i.e. never answered with a SYN/ACK), e.g. because the listen queue overflowed. Still trying to find definite confirmation for this, though.


@taylorthurlow Your `tcpdump` command doesn't do what you think it does. `icmp[0] = 3 and icmp[1] = 4` means ICMP type 3 ("Destination Unreachable") and code (i.e. subtype) 4 ("Fragmentation required but DF bit set"). No wonder it didn't catch any packets...

**Comment by literal** [comment] 2018-09-18 14:04
Back from a little journey into the Linux source code.

My assumption in the previous post was wrong. There are various cases in which the `TcpExtListenDrops` counter is increased, including
- TCP handshakes cancelled by an ICMP error message (i.e. what @tiaga saw),
- SYN packets received on broadcast or multicast addresses,
- a full accept queue (also increases `TcpExtListenOverflows` counter),
- a full SYN queue and fallback to SYN cookies disabled (also increases `TcpExtTCPReqQFullDrop` counter).

So I guess it's quite normal to see occasional TCP listen drops. As long as the `TcpExtListenOverflows` and `TcpExtTCPReqQFullDrop` counters stay at zero that doesn't indicate a server problem and requires no tuning of any backlog sizes (of either the network stack or server applications) as mentioned above.

Maybe it's a good idea to change the default sensitivity of the `1m_ipv4_tcp_listen_drops` alarm in Netdata or even drop it?

**Comment by lkraav** [comment] 2018-09-18 14:56
> Maybe it's a good idea to change the default sensitivity of the 1m_ipv4_tcp_listen_drops alarm in Netdata or even drop it?

I've upped my threshold to 5m, and still get this alarm slightly more often than I'd enjoy, but def. a lot less annoying.

**Comment by literal** [comment] 2018-09-18 15:14
> I've upped my threshold to 5m, and still get this alarm slightly more often than I'd enjoy, but def. a lot less annoying.

With "5m", do you mean you changed `lookup: sum -60s unaligned absolute of ListenDrops` in `health.d/tcp_listen.conf` to `lookup: sum -5m ...`? That shouldn't make any difference as the default threshold is zero (`warn: $this > 0`), so every single listen drop will still cause an alarm.

**Comment by lkraav** [comment] 2018-09-18 15:26
> With "5m", do you mean you changed

Current dirty worktree diff:

```diff
diff --git a/netdata/health.d/tcp_listen.conf b/netdata/health.d/tcp_listen.conf
index 957964a..472f620 100644
--- a/netdata/health.d/tcp_listen.conf
+++ b/netdata/health.d/tcp_listen.conf
@@ -1,11 +1,11 @@
 # -----------------------------------------------------------------------------
 # tcp listen sockets issues
 
-   alarm: 1m_ipv4_tcp_listen_overflows
+   alarm: 5m_ipv4_tcp_listen_overflows
       on: ipv4.tcplistenissues
       os: linux freebsd
    hosts: *
-  lookup: sum -60s unaligned absolute of ListenOverflows
+  lookup: sum -300s unaligned absolute of ListenOverflows
    units: overflows
    every: 10s
     crit: $this > 0
@@ -13,11 +13,11 @@
     info: the number of TCP listen socket overflows during the last minute
       to: sysadmin
 
-   alarm: 1m_ipv4_tcp_listen_drops
+   alarm: 5m_ipv4_tcp_listen_drops
       on: ipv4.tcplistenissues
       os: linux
    hosts: *
-  lookup: sum -60s unaligned absolute of ListenDrops
+  lookup: sum -300s unaligned absolute of ListenDrops
    units: drops
    every: 10s
     crit: $this > 0
diff --git a/netdata/health.d/udp_errors.conf b/netdata/health.d/udp_errors.conf
index 382b396..5f8cbfe 100644
--- a/netdata/health.d/udp_errors.conf
+++ b/netdata/health.d/udp_errors.conf
@@ -26,7 +26,7 @@
   lookup: sum -1m unaligned absolute of RcvbufErrors
    units: errors
    every: 10s
-    warn: $this > 0
+    warn: $this > 10
     crit: $this > 100
     info: number of UDP receive buffer errors during the last minute
    delay: up 0 down 60m multiplier 1.2 max 2h
```

**Comment by literal** [comment] 2018-09-18 15:46
@lkraav I see. But your changes do not reduce the number of notifications.

Your config still has `crit: $this > 0` which makes the state go to `critical` when there was even a single TCP listen drop during the last 5 minutes.

The default delay to end the critical state is 5 minutes anyway (`delay: up 0 down 5m ...`), so multiple listen drops during a 5-minute-period wouldn't cause multiple notifications with the default config either. (A notification is only sent when the alarm's state changes.)

**Comment by literal** [comment] 2018-09-18 23:10
> But I don't see anywhere `TcpExtTCPReqQFullDrop`.
> It is not in `/proc/net/snmp`.
> Where did you find it?

It's in `/proc/net/netstat` as `TCPReqQFullDrop`. (And I also find `ListenOverflows`there and not in `/proc/net/snmp`.)
```
# nstat -za TcpExtTCPReqQFullDrop
TcpExtTCPReqQFullDrop           0                  0.0
```
The counter is increased here: https://github.com/torvalds/linux/blob/69973b830859bc6529a7a0468ba0d80ee5117826/net/ipv4/tcp_input.c#L6267 inside function `tcp_syn_flood_action()` which is called when the SYN queue is full.
The function only increments the counter when the fallback to SYN cookies (which allow for TCP handshakes without keeping track of half-open connections) is disabled.

**Comment by ktsaou** [comment] 2018-09-22 02:19
ok, added it (not merged yet, check the commit on github, above my comment):

![image](https://user-images.githubusercontent.com/2662304/45912176-fc413780-be25-11e8-96b7-322e64cbf4d0.png)

(btw, `/proc/net/netstat` has a lot of info, but I am not sure how to structure it, how to group all these metrics in charts with common meaning, units, title, etc - if you can help, I would love to parse and visualize every metric found there)

I tried it on a few servers: it is just zero on all of them.

So, what you say we should modify alarm `1m_ipv4_tcp_listen_drops`, so that:

1. It lookups the `sum -1m unaligned absolute of ListenDrops`
2. It lookups the `sum -1m unaligned absolute of TcpExtListenOverflows`
3. It lookups the `sum -1m unaligned absolute of TcpExtTCPReqQFullDrop`
4. It triggers the alarm only when (the above sums):

```
ListenDrops > 0 AND (TcpExtListenOverflows > 0 OR TcpExtTCPReqQFullDrop > 0)
```

Right?

**Comment by literal** [comment] 2018-09-24 10:45
The `TcpExtListenDrops` counter is very generic and I would suggest to just remove the alarm for it. In those cases I consider worth monitoring (i.e. overflows, which indicate either an attack or a performance problem) some other more specific counter is also incremented anyway.

> So, you say we should modify alarm 1m_ipv4_tcp_listen_drops, so that:
> [...]
> `ListenDrops > 0 AND (TcpExtListenOverflows > 0 OR TcpExtTCPReqQFullDrop > 0)`

Why not just add an alarm for `TcpExtTCPReqQFullDrop` instead?

And there is yet another related counter in `/proc/net/netstat` that I would suggest monitoring and adding an alarm for: `TcpExtTCPReqQFullDoCookies`.

---

To add some background info - there are two queues involved when incoming TCP connections are handled:

1. The **SYN queue** tracks TCP handshakes until connections are fully established. It overflows when too many incoming TCP connection requests hang in the half-open state **and** the server is not configured to fall back to SYN cookies*. Overflows are usually caused by SYN flood DoS attacks (i.e. someone sends lots of SYN packets and never completes the handshakes).

2 The **accept queue** holds fully established TCP connections waiting to be handled by the listening application. It overflows when the server application fails to accept new connections at the rate they are coming in.

_* SYN cookies: When the SYN queue is full, the server, instead of remembering it locally, encodes the connection information in the sequence number of its SYN which the client passes back to the server (incremented by one) in its final ACK. There are, however, some serious drawbacks, so SYN cookies should only used as a last resort when the server's SYN queue is full. (And that's exactly what the sysctl setting of `net.ipv4.tcp_syncookies = 1` does.)_

---

When the SYN queue is full, either `TcpExtTCPReqQFullDoCookies` or `TcpExtTCPReqQFullDrop` is incremented, depending on whether SYN cookies are enabled or not. In both cases this probably indicates a SYN flood attack, so i guess a notification should be sent.

When the accept queue is full, `TcpExtListenOverflows` is incremented. An alarm for that already exists.

---

As for the other values in `/proc/net/netstat`: I will need some time to look into that. But I expect most of them to not be too interesting from a monitoring perspective...

**Comment by l2isbad** [comment] 2018-09-24 10:48
@literal very nice job :+1:

**Comment by ktsaou** [comment] 2018-09-24 13:50
@literal you really rock!
Check PR #4281 
I incorporated all your suggestions and used your content to describe them.

**Comment by ktsaou** [comment] 2018-09-27 17:37
The fix has been merged.

**Closed** 2018-09-27 17:37 UTC
Labels: question

**Comment by nicdnepr** [comment] 2019-09-22 10:35
Hi
I get such errors
```
9/21/2019 11:40:11 PM | ip.tcp_accept_queue | 1m tcp accept queue drops | 159 drops | CRITICAL
9/21/2019 11:37:31 PM | ip.tcp_accept_queue | 1m tcp accept queue overflows | 7 overflows | CRITICAL
```
net data v1.17.1, centos 7
Is it fixed?

**Comment by patademahesh** [comment] 2022-09-23 17:53
We were able to fix this alert by setting below sysctl params on the varnish server.

`net.ipv4.tcp_max_syn_backlog = 512`
`net.ipv4.tcp_syn_retries = 1`

> Note: By reducing syn retries from 6 to 1 we could mitigate the drops but not eliminate them entirely. So we had to increase tcp_max_syn_backlog from 256 to 512
