### ISSUE TITLE
Wrong number visualized when using unix timestamp as an example

### ISSUE THREAD

**Issue by lucasRolff** [netdata/netdata#9803] opened 2020-08-21 08:00 UTC
##### Question summary

Based on #9798 -  I see if I have an external plugin that e.g. logs the unix timestamp, when calling the chart directly from command line, I see increments happening every second as expected, however, looking at the web UI the number only seems to update every 100 seconds that passes:

![https://snaps.hcdn.dk/6bZpVqfYVZScslvoyzATipx6EQvZoccOo7GHK7l1OH.png](https://snaps.hcdn.dk/6bZpVqfYVZScslvoyzATipx6EQvZoccOo7GHK7l1OH.png)

Even if I get the Prometheus endpoint, it also only increases there every 100 seconds, so I know it's not a chart thing.

Doing an strace of the charts.d.plugin process I do see the SET value increasing every second, but doesn't seem to persist in the actual netdata metrics - the same is the case if I do a metric every 5 seconds, I still only see the increase every 100 seconds.

It might be worth mentioning the same happens when doing it as a python plugin.
What I did find interesting is that if I change it from `absolute` to `incremental`, then netdata will list `1` every second, because the value incremented by 1, so it seems to be fine when using `incremental`, but `absolute` only seems to really register a "change" every 100 seconds as the above screenshot shows.

##### OS / Environment

Vultr High Frequency instance with Ubuntu 20.04 (KVM)

##### Component Name

charts.d.plugin

##### Expected results

I would expect the graph to increase by 1 every second.

##### Debug information

```
2020-08-21 07:52:59: charts.d: INFO: main: started from './usr/libexec/netdata/plugins.d/charts.d.plugin' with options: dnsmon debug
2020-08-21 07:52:59: charts.d: INFO: main: Configuration file '/opt/netdata/usr/lib/netdata/conf.d/charts.d.conf' loaded.
2020-08-21 07:52:59: charts.d: WARNING: main: Configuration file '/opt/netdata/etc/netdata/charts.d.conf' not found.
2020-08-21 07:52:59: charts.d: DEBUG: ap: is enabled for auto-detection.
2020-08-21 07:52:59: charts.d: DEBUG: apcupsd: is enabled for auto-detection.
2020-08-21 07:52:59: charts.d: DEBUG: dnsmon: is enabled for auto-detection.
2020-08-21 07:52:59: charts.d: INFO: example: is disabled. Add a line with example=force in '/opt/netdata/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2020-08-21 07:52:59: charts.d: DEBUG: libreswan: is enabled for auto-detection.
2020-08-21 07:52:59: charts.d: DEBUG: nut: is enabled for auto-detection.
2020-08-21 07:52:59: charts.d: DEBUG: opensips: is enabled for auto-detection.
2020-08-21 07:52:59: charts.d: INFO: sensors: is disabled. Add a line with sensors=force in '/opt/netdata/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2020-08-21 07:52:59: charts.d: DEBUG: main: enabled charts:  ap apcupsd dnsmon libreswan nut opensips
2020-08-21 07:52:59: charts.d: DEBUG: ap: loading module: './usr/libexec/netdata/plugins.d/../charts.d/ap.chart.sh'
2020-08-21 07:52:59: charts.d: DEBUG: ap: loading module configuration: '/opt/netdata/usr/lib/netdata/conf.d/charts.d/ap.conf'
2020-08-21 07:52:59: charts.d: DEBUG: ap: not found module configuration: '/opt/netdata/etc/netdata/charts.d/ap.conf'
2020-08-21 07:52:59: charts.d: ERROR: ap: no devices found in AP mode, with 'iw dev'
2020-08-21 07:52:59: charts.d: ERROR: ap: module's 'ap' check() function reports failure.
2020-08-21 07:52:59: charts.d: DEBUG: apcupsd: loading module: './usr/libexec/netdata/plugins.d/../charts.d/apcupsd.chart.sh'
2020-08-21 07:52:59: charts.d: DEBUG: apcupsd: loading module configuration: '/opt/netdata/usr/lib/netdata/conf.d/charts.d/apcupsd.conf'
2020-08-21 07:52:59: charts.d: DEBUG: apcupsd: not found module configuration: '/opt/netdata/etc/netdata/charts.d/apcupsd.conf'
2020-08-21 07:52:59: charts.d: WARNING: apcupsd: command 'apcaccess' is not found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
2020-08-21 07:52:59: charts.d: ERROR: apcupsd: module's 'apcupsd' check() function reports failure.
2020-08-21 07:52:59: charts.d: DEBUG: dnsmon: loading module: './usr/libexec/netdata/plugins.d/../charts.d/dnsmon.chart.sh'
2020-08-21 07:52:59: charts.d: DEBUG: dnsmon: not found module configuration: '/opt/netdata/usr/lib/netdata/conf.d/charts.d/dnsmon.conf'
2020-08-21 07:52:59: charts.d: DEBUG: dnsmon: not found module configuration: '/opt/netdata/etc/netdata/charts.d/dnsmon.conf'
2020-08-21 07:52:59: charts.d: DEBUG: dnsmon: module 'dnsmon' activated
2020-08-21 07:52:59: charts.d: DEBUG: libreswan: loading module: './usr/libexec/netdata/plugins.d/../charts.d/libreswan.chart.sh'
2020-08-21 07:52:59: charts.d: DEBUG: libreswan: loading module configuration: '/opt/netdata/usr/lib/netdata/conf.d/charts.d/libreswan.conf'
2020-08-21 07:52:59: charts.d: DEBUG: libreswan: not found module configuration: '/opt/netdata/etc/netdata/charts.d/libreswan.conf'
2020-08-21 07:52:59: charts.d: WARNING: libreswan: command 'ipsec' is not found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
2020-08-21 07:52:59: charts.d: ERROR: libreswan: module's 'libreswan' check() function reports failure.
2020-08-21 07:52:59: charts.d: DEBUG: nut: loading module: './usr/libexec/netdata/plugins.d/../charts.d/nut.chart.sh'
2020-08-21 07:52:59: charts.d: DEBUG: nut: loading module configuration: '/opt/netdata/usr/lib/netdata/conf.d/charts.d/nut.conf'
2020-08-21 07:52:59: charts.d: DEBUG: nut: not found module configuration: '/opt/netdata/etc/netdata/charts.d/nut.conf'
2020-08-21 07:52:59: charts.d: WARNING: nut: command 'upsc' is not found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
2020-08-21 07:52:59: charts.d: ERROR: nut: module's 'nut' check() function reports failure.
2020-08-21 07:52:59: charts.d: DEBUG: opensips: loading module: './usr/libexec/netdata/plugins.d/../charts.d/opensips.chart.sh'
2020-08-21 07:52:59: charts.d: DEBUG: opensips: loading module configuration: '/opt/netdata/usr/lib/netdata/conf.d/charts.d/opensips.conf'
2020-08-21 07:52:59: charts.d: DEBUG: opensips: not found module configuration: '/opt/netdata/etc/netdata/charts.d/opensips.conf'
2020-08-21 07:52:59: charts.d: WARNING: opensips: command 'opensipsctl' is not found in /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin.
2020-08-21 07:52:59: charts.d: ERROR: opensips: module's 'opensips' check() function reports failure.
2020-08-21 07:52:59: charts.d: DEBUG: main: activated modules:  dnsmon
2020-08-21 07:52:59: charts.d: DEBUG: main: requested to run only for: 'dnsmon'
2020-08-21 07:52:59: charts.d: DEBUG: main: activated charts: dnsmon
2020-08-21 07:52:59: charts.d: DEBUG: dnsmon: calling 'dnsmon_create()'...
CHART dnsmon.txtvalue '' "A random number" "random number" dnsmon dnsmon_txt line 150001 1
DIMENSION txtvalue '' absolute 1 1
2020-08-21 07:52:59: charts.d: DEBUG: dnsmon: 'dnsmon' initialized.
2020-08-21 07:52:59: charts.d: DEBUG: main: run_charts=' dnsmon'
CHART netdata.plugin_chartsd_dnsmon '' 'Execution time for dnsmon plugin' 'milliseconds / run' charts.d netdata.plugin_charts area 145000 1
DIMENSION run_time 'run time' absolute 1 1
2020-08-21 07:52:59: charts.d: DEBUG: dnsmon: sleeping for 0.313 seconds.
BEGIN dnsmon.txtvalue
SET txtvalue = 1597996380
END
BEGIN netdata.plugin_chartsd_dnsmon
SET run_time = 0
END
2020-08-21 07:53:00: charts.d: DEBUG: dnsmon: sleeping for 0.993 seconds.
BEGIN dnsmon.txtvalue 990000
SET txtvalue = 1597996381
END
BEGIN netdata.plugin_chartsd_dnsmon 990000
SET run_time = 10
END
2020-08-21 07:53:01: charts.d: DEBUG: dnsmon: sleeping for 0.993 seconds.
BEGIN dnsmon.txtvalue 1000000
SET txtvalue = 1597996382
END
BEGIN netdata.plugin_chartsd_dnsmon 1000000
SET run_time = 0
END
2020-08-21 07:53:02: charts.d: DEBUG: dnsmon: sleeping for 1.003 seconds.
BEGIN dnsmon.txtvalue 1010000
SET txtvalue = 1597996383
END
BEGIN netdata.plugin_chartsd_dnsmon 1010000
SET run_time = 0
END
2020-08-21 07:53:03: charts.d: DEBUG: dnsmon: sleeping for 0.993 seconds.
```

##### Code example

```bash
# shellcheck shell=bash

# _update_every is a special variable - it holds the number of seconds
# between the calls of the _update() function
dnsmon_update_every=1

# the priority is used to sort the charts on the dashboard
# 1 = the first chart
dnsmon_priority=150000

# global variables to store our collected data
# remember: they need to start with the module name dnsmon_
dnsmon_txtvalue=

dnsmon_get() {
  # do all the work to collect / calculate the values
  # for each dimension
  #
  # Remember:
  # 1. KEEP IT SIMPLE AND SHORT
  # 2. AVOID FORKS (avoid piping commands)
  # 3. AVOID CALLING TOO MANY EXTERNAL PROGRAMS
  # 4. USE LOCAL VARIABLES (global variables may overlap with other modules)
  dnsmon_txtvalue=$(date +%s)

  # this should return:
  #  - 0 to send the data to netdata
  #  - 1 to report a failure to collect the data

  return 0
}

# _check is called once, to find out if this chart should be enabled or not
dnsmon_check() {
  # this should return:
  #  - 0 to enable the chart
  #  - 1 to disable the chart

  # check that we can collect data
  dnsmon_get || return 1

  return 0
}

# _create is called once, to create the charts
dnsmon_create() {
  # create the chart with 3 dimensions
  cat << EOF
CHART dnsmon.txtvalue '' "A random number" "random number" dnsmon dnsmon_txt line $((dnsmon_priority + 1)) $dnsmon_update_every
DIMENSION txtvalue '' absolute 1 1
EOF

  return 0
}

# _update is called continuously, to collect the values
dnsmon_update() {
  # the first argument to this function is the microseconds since last update
  # pass this parameter to the BEGIN statement (see bellow).

  dnsmon_get || return 1

  # write the result of the work.
  cat << VALUESEOF
BEGIN dnsmon.txtvalue $1
SET txtvalue = $dnsmon_txtvalue
END
VALUESEOF

  return 0
}
```

**Comment by ilyam8** [comment] 2020-08-21 08:38
Indeed, i have same problem with `Code example` script

I changed update func to

```bash
VAL=1

dnsmon_update() {
  dnsmon_get || return 1

  cat << VALUESEOF
BEGIN dnsmon.txtvalue $1
SET txtvalue = $VAL
END
VALUESEOF

(( VAL++ ))

  return 0
}
```

and it works fine

---

So it seems the problem with big number? :thinking:

**Comment by ilyam8** [comment] 2020-08-21 08:48
@mfundul @stelfrag take a look

> Doing an strace of the charts.d.plugin process I do see the SET value increasing every second

```cmd
BEGIN dnsmon.txtvalue 1000000
SET txtvalue = 1597996382
END

BEGIN dnsmon.txtvalue 1010000
SET txtvalue = 1597996383
END
```

**Comment by amoss** [comment] 2020-08-24 12:49
The details are in https://github.com/netdata/netdata/tree/master/libnetdata/storage_number

From my reading of the code I think the rationale behind it was two-fold:
* To save enough space to store some flags within the 32-bits.
* To provide nicer rounding modes for the values on the charts.

The large steps are caused by the range hitting a region where it needs to set the `SN_EXISTS_100` flag, which reduces the precision. If we were using actual floating point then around the sizes in the example above (46M) the loss in accuracy would be much lower - the gaps between values would be `2` instead of `100`.

I'm not sure what we can do to work around this as the internal number format is buried quite deeply in the source code and changing it would affect almost every part of Netdata.

**Comment by lucasRolff** [comment] 2020-08-24 12:57
If it ain't possible to get accuracy closer than 100 apart when using "big" numbers, then what's the workaround? If we have metrics that are based e.g. on the unix timestamp (serial in DNS for example) or just any other really large number, then we'd have a hard time ever measuring changes in Netdata.

In my particular case, I'm having a bunch of cronjobs to use the Prometheus PushGateway to make additional metrics available, however, ideally I'd want to avoid having to create all these custom cronjobs, and simply have a collector "job" in Netdata to gather the information for me (at a much finer granularity since I can do metrics every 10 seconds easily).

I don't feel like dividing metrics by `100000` is a nice solution, and since I want the "raw" number, using an `increment` chart won't really do the job.

**Comment by amoss** [comment] 2020-08-24 13:23
@mfundul / @stelfrag Do you have any ideas?

**Comment by stelfrag** [comment] 2020-08-25 08:24
> @mfundul / @stelfrag Do you have any ideas?

I think the main idea was saving memory (and integers are easier to work with) with an "acceptable" precision loss (in most cases). 

- Changing the storage number (now 4 bytes) will impact memory usage (e.g 2000 metrics now need about 8Mib of memory for ~17 min of data).  

Say we go to 8 bytes (either a similar 64bit enhanced compaction or float that plays well on all systems)
- It will break compatibility with existing collected metrics
  - Need to evaluate impact 
- The existing page size (4096 bytes) will hold half the amount of data
  - Evaluate if we will hold ~8 mins of data
  - Evaluate if we increase page size 
    - Impact on I/O etc

Now, I don't want to list only problems :smiley: so we might want to test this.

Switch to 64bit and see what it looks like.

- Change the `storage_number` 
- Change the pack / unpack functions 

@mfundul what do you think?

**Comment by mfundul** [comment] 2020-08-25 08:32
Changing the internal number representation will affect the users in the following ways:
- Breaks compatibility of persisted metrics on disk for all persistent memory modes.
- Halves the retention period for the same amount of memory/disk space.

As far as development goes, we would need to refactor the agent to be able to function in 2 modes, 32-bit and 64-bit internal number modes. This could potentially be a lot of work to make it production ready.

**Comment by amoss** [comment] 2020-08-25 09:08
So the summary is that what looks like a small change on a chart is a fundamental rewrite of Netdata. It would improve the use of Netdata against arbitrary metrics coming from Prometheus but given the huge amount of development work involved I cannot estimate the benefit vs the cost of the change. I think @cakrit should be involved in the discussion (although he is on vacation so there won't be an answer until next week).

**Comment by lucasRolff** [comment] 2020-08-25 15:48
So based on the info from @stelfrag - it would mean ~ 8Mib for 8 minutes of data, containing 2000 metrics.

While doubling memory on embedded devices or super tiny machines, I can see this being a problem.

On one of my smaller systems (2GB RAM), Netdata is currently using 52MiB of memory (26MiB private, 26MiB shared), it keeps 900 seconds of metrics (15 minutes), and collects 1819 metrics every second.

This (and all other systems) are configured with `memory mode = save` in my case - because I don't need the persistence.

If 4MiB of this data is used for actual metrics, then increasing it from 4MiB to 8MiB would yield a 7.7% increase in memory usage?

**If it's a huge change**, I don't see the point in changing it to use more memory, and also the fact it would affect every existing metric - however:

1. Would it be easier to allow specifying a `precision` setting for a metric (or a collector), so *I* can decide whether I want to be able to store an insanely high number, or a number being 100 times less?

It would then simply when rendering the chart taking the precision into account, this way, we can select which metrics/collectors we want to store more precise numbers, with the downside of it being we can't store `167772150000000.0` but only `1677721500000.0` (Assuming we remove 2x zero?)

2. Collect with the higher precision, but store at the lower precision
2.1. Configure whether to collect at higher or lower precision, and simply knowing that we double the memory of metrics that are in memory

I'm simply throwing ideas, and you guys for sure know more about the internals (and code) than I do, so there's certainly stuff I might not have taken into account, or not be aware of.

But I can imagine people who for example uses the various backends, would like a short but precise "in-memory" database, simply to get pushed/pulled into long term storage, where we can then decide how we want to aggregate metrics.

I think there's a difference between collecting and storing metrics - and collection should be (as precise) as possible, while storing it, can lower the precision if one desires (e.g. `dbengine` can enforce a lower precision).

And even if it ain't possible to get a super precise collection, I'd still like to hear if anyone has ideas how to then collect (with at least 10sec precision) in my above use-case where the epoch time is used for example as a "metric" (comparing raw SOA serials for example).

With that said - sorry for ending up with a bunch of people dragged into the conversation! However, but kudos to everyone for working on Netdata! It's absolutely amazing, and a key component for server monitoring and metrics gatherings!

**Comment by ilyam8** [comment] 2021-07-15 14:17
Closing this feature request. We will re-evaluate the request internally.

**Closed by ilyam8** 2021-07-15 14:17 UTC
Labels: area/database, feature request
