### ISSUE TITLE
[Bug]: upgrade to 1.4x.y doesn't automatically show new charts in System Overview, such as Average System Load

### ISSUE THREAD

**Issue by Ximalas** [netdata/netdata#16065] opened 2023-09-28 07:45 UTC
### Bug description

Average System Load doesn't automatically appear in System Overview after upgrading to, say 1.42.4.

### Expected behavior

New charts should appear automatically after upgrade.

### Steps to reproduce

1. Install any recent version of FreeBSD.
2. Install an older version of Netdata.
3. Start Netdata and let it run for a few minutes gathering metrics.
4. Visit the V2 dashboard, and observe the current contents of System Overview.
5. Upgrade Netdata to, say 1.42.4.
6. Restart Netdata.
7. Refresh the web browser.
8. Observe System Overview in the V2 dashboard is missing Average System Load.

### Installation method

other

### System info

```shell
FreeBSD builder01.[REDACTED] 13.2-STABLE FreeBSD 13.2-STABLE #6359 stable/13+local-n252364-15a0e6727958: Thu Aug  3 02:18:17 CEST 2023     root@builder01.[REDACTED]:/usr/obj/usr/src/amd64.amd64/sys/PER740 amd64
1302507
```

### Netdata build info

```shell
root@builder01:~ # netdata -W buildinfo
Packaging:
    Netdata Version ____________________________________________ : v1.42.4
    Installation Type __________________________________________ : custom
    Package Architecture _______________________________________ : unknown
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ :  '--disable-h2o' '--disable-unit-tests' '--with-user=netdata' '--disable-cloud' '--disable-plugin-cups' '--enable-dbengine' '--disable-plugin-freeipmi' '--enable-lto' '--enable-ml' '--prefix=/usr/local' '--localstatedir=/var' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/share/info/' '--build=amd64-portbld-freebsd13.2' 'build_alias=amd64-portbld-freebsd13.2' 'CC=cc' 'CFLAGS=-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing ' 'LDFLAGS=  -fstack-protector-strong -L/usr/local/lib ' 'LIBS=' 'CPPFLAGS=-D_WANT_VMMETER -isystem /usr/local/include' 'CXX=c++' 'CXXFLAGS=-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include ' 'PKG_CONFIG=pkgconf' 'PKG_CONFIG_LIBDIR=/construction/xports/net-mgmt/netdata/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig' 'CPP=cpp'
Default Directories:
    User Configurations ________________________________________ : /usr/local/etc/netdata
    Stock Configurations _______________________________________ : /usr/local/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/db/netdata
    Plugins ____________________________________________________ : /usr/local/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/local/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/db/netdata/lock
    Home _______________________________________________________ : /var/db/netdata
Operating System:
    Kernel _____________________________________________________ : FreeBSD
    Kernel Version _____________________________________________ : 1302507
    Operating System ___________________________________________ : FreeBSD
    Operating System ID ________________________________________ : FreeBSD
    Operating System ID Like ___________________________________ : FreeBSD
    Operating System Version ___________________________________ : 13.2-STABLE
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : uname
Hardware:
    CPU Cores __________________________________________________ : 44
    CPU Frequency ______________________________________________ : 2100 MHz
    CPU Architecture ___________________________________________ : 1647758217216
    RAM Bytes __________________________________________________ : 23717393865728
    Disk Capacity ______________________________________________ : amd64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : sysctl
Container:
    Container __________________________________________________ : unknown
    Container Detection ________________________________________ : none
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : FreeBSD
    Netdata Cloud ______________________________________________ : NO (disabled)
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (lz4)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    map ________________________________________________________ : YES
    save _______________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : NO
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : NO
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Judy (high-performance dynamic arrays and hashtables) ______ : YES (bundled)
    dlib (robust machine learning toolkit) _____________________ : YES (bundled)
    protobuf (platform-neutral data serialization protocol) ____ : NO
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libm (mathematical functions) ______________________________ : YES
    jemalloc ___________________________________________________ : NO
    TCMalloc ___________________________________________________ : NO
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : NO
    cgroup-network (associate interfaces to CGROUPS) ___________ : NO
    proc (monitor Linux systems) _______________________________ : NO
    tc (monitor Linux network QoS) _____________________________ : NO
    diskspace (monitor Linux mount points) _____________________ : NO
    freebsd (monitor FreeBSD systems) __________________________ : YES
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : NO
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : NO
    freeipmi (monitor enterprise server H/W) ___________________ : NO
    nfacct (gather netfilter accounting) _______________________ : NO
    perf (collect kernel performance events) ___________________ : NO
    slabinfo (monitor kernel object caching) ___________________ : NO
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : NO
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : NO
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

### Additional info

Only solved by stopping Netdata, emptying Ephemeral Databases (metrics data, metadata), i.e. /var/cache/netdata, and starting Netdata.

**Comment by ilyam8** [comment] 2023-09-28 09:11
Hey, @Ximalas. First of all - thanks for reporting! That seems to be a very weird problem - we haven't changed anything in freebsd.plugin and UI shouldn't matter. And the fact that only the `system.load` metric is missing makes it even more mysterious 😄 I don't think this has something to do with FreeBSD but regardless I went forward and did your "step to reproduce" - no problem for me.

I am closing this issue as "cannot reproduce" but let us know if you see this problem happen again.

**Closed by ilyam8** 2023-09-28 09:11 UTC
Labels: bug, needs triage, cannot reproduce
