### ISSUE TITLE
Install error: possibly undefined macro: AC_MSG_NOTICE

### ISSUE THREAD

**Issue by rafariossaa** [netdata/netdata#9139] opened 2020-05-23 16:00 UTC
##### Bug report summary

When installing with :
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel --disable-telemetry
```
finally I got the following error:

```
...
 --- Run autotools to configure the build environment --- 
[/tmp/netdata-kickstart-WEgiIh/netdata-v1.22.1]# autoreconf -ivf 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:16: error: possibly undefined macro: AC_MSG_NOTICE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:257: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:269: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:542: error: possibly undefined macro: AC_CHECK_HEADER
autoreconf: /usr/bin/autoconf failed with exit status: 1
 FAILED   
```

I was able to fix it by installing `pkg-config` package.

##### OS / Environment

```
$ uname -a; grep -Hv "^#" /etc/*release
Linux debian 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="9"
/etc/os-release:VERSION="9 (stretch)"
/etc/os-release:VERSION_CODENAME=stretch
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

It was not installed, so I picked it from the `/tmp/` directory name:
`/tmp/netdata-kickstart-WEgiIh/netdata-v1.22.1`

##### Steps To Reproduce

1. run: 
```bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel --disable-telemetry```
2. ...

##### Expected behavior

Netdata installed.

**Comment by prologic** [comment] 2020-05-25 05:00
I am not able to reproduce this error:

```#!sh
$ docker run -t --rm -e DEBIAN_FRONTEND=noninteractive -v "$PWD":/netdata -w /netdata debian:9 /bin/bash -c 'apt-get update && apt-get -y install curl; bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel --disable-telemetry'.
.
.
 --- Wrap up environment set up ---
Preparing .environment file
[/netdata]# chmod 0644 /etc/netdata/.environment
 OK

Setting netdata.tarball.checksum to 'new_installation'

 --- We are done! ---

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata              .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed now!  -'   '-'   '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  enjoy real-time performance and health monitoring...
```

So I would ask that firstly you try again and if the problem persists I'll need to know more about your system.

**Comment by kimmoahola** [comment] 2020-06-09 07:22
Same here, installing `pkg-config` fixed the problem.

The package mentioned in the error message when installation fails:

```
4. You need basic build tools installed, like:

gcc make autoconf automake pkg-config

```

**Comment by prologic** [comment] 2020-06-24 03:20
Closing this since we are unable to reproduce. If you are able to reproduce this and can put together a Docker image that demonstrates the failure we would be more than happy to revisit this. If you are still having issues please feel free to comment or open a new issue with specific details.

**Closed by prologic** 2020-06-24 03:20 UTC
Labels: Cannot reproduce, bug
