### ISSUE TITLE
Problem loading module sensors

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#5490] opened 2019-02-25 03:27 UTC
##### Question summary
I installed netdata with the command:
`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
Everything is working fine. Then I installed lm-sensors package and rebooted.
No sensors show up in my netdata.
The following errors are showing up in the error.log

> python.d ERROR: plugin: main: load source error : /usr/bin/python: undefined symbol: libsensors_version
> python.d ERROR: plugin: main: module load source: 'sensors' => [FAILED]
> python.d ERROR: plugin: main: load source error : /usr/bin/python: undefined symbol: libsensors_version
> python.d ERROR: plugin: main: cannot load '/etc/netdata/python.d/sensors.conf' : [Errno 2] No such file or directory: '/etc/netdata/python.d/sensors.conf'. Will try stock version.

Output of sensors command:

> pch_skylake-virtual-0
> Adapter: Virtual device
> temp1:        +32.0°C  
> 
> acpitz-virtual-0
> Adapter: Virtual device
> temp1:        +27.8°C  (crit = +119.0°C)
> temp2:        +29.8°C  (crit = +119.0°C)
> 
> coretemp-isa-0000
> Adapter: ISA adapter
> Package id 0:  +24.0°C  (high = +80.0°C, crit = +100.0°C)
> Core 0:        +24.0°C  (high = +80.0°C, crit = +100.0°C)
> Core 1:        +24.0°C  (high = +80.0°C, crit = +100.0°C)
> Core 2:        +23.0°C  (high = +80.0°C, crit = +100.0°C)
> Core 3:        +23.0°C  (high = +80.0°C, crit = +100.0°C)

##### OS / Environment
Ubuntu 18.04.2
Default Python 2.7.15rc1
Also installed Python3
##### Component Name
lm-sensors
##### Expected results
Sensor charts showing up.

**Comment by ilyam8** [comment] 2019-02-25 06:00
Hi @Steve8291 	

Please comment out this line
https://github.com/netdata/netdata/blob/3b28e0f5ed1ab1eb441be9bcc74de0a0722aea82/collectors/python.d.plugin/python_modules/third_party/lm_sensors.py#L23

restart netdata.service and see if it is fixed

**Comment by Steve8291** [comment] 2019-02-25 11:36
No luck.
I don't need to install the sensord package that does logging as well do I?
Also, I'm running lm-sensors version:
sensors version 3.4.0 with libsensors version 3.4.0

**Comment by ilyam8** [comment] 2019-02-25 13:07
@Steve8291 	can't reproduce it.

I load ubuntu 18.04.02 in `try` mode (usbstick), install `lm-sensors` and `nedata`.  No error, module works.

**Comment by SuperSandro2000** [comment] 2019-02-25 15:38
@ilyam8 Did you try installing netdata first and then lm-sensors? You may need a VM for the reboot inbetween.

**Comment by ilyam8** [comment] 2019-02-25 15:41
I don't think the order is a thing.

Can you reproduce it? If yes give me a step by step guide :smile:

**Comment by SuperSandro2000** [comment] 2019-02-25 15:43
I just thought that order may play a role. Only thing I noticed that was different between your tests and his description.

**Comment by ilyam8** [comment] 2019-02-25 15:50
Nah, i don't think so. But thanks for looking into that :+1:

**Comment by Steve8291** [comment] 2019-02-25 18:02
Thanks for the ideas. I will try to uninstall netdata and lm-sensors and reinstall them again tonight.

**Comment by Steve8291** [comment] 2019-02-26 03:19
Tried uninstalling netdata and lm-sensors.
Installed lm-sensors, ran sensors-detect, then installed netdata.
Still no luck. This is a brand new install of Ubuntu 18.04.2 Server. Netdata was the first app I had installed.
I did notice that I get an error when installing netdata:
```
WARNING
package autoconf-archive is not available in this system.
You may try to install without it.
```
However, autoconf-archive Version: 20170928-2  is installed on my machine.

**Comment by Steve8291** [comment] 2019-03-02 18:35
Trying a debug trace of the sensors module:
`/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace sensors`

> 2019-03-02 13:24:21: python.d INFO: plugin: main: Using python 2
> 2019-03-02 13:24:21: python.d DEBUG: plugin: main: loading '/etc/netdata/python.d.conf'
> 2019-03-02 13:24:21: python.d DEBUG: plugin: main: module load source: 'sensors' => [OK]
> 2019-03-02 13:24:21: python.d DEBUG: plugin: main: loading '/etc/netdata/python.d/sensors.conf'
> 2019-03-02 13:24:21: python.d DEBUG: plugin: main: job initialization: 'sensors sensors' => ['OK']
> 2019-03-02 13:24:21: python.d DEBUG: plugin: main: module status: 'sensors' => [OK] (jobs: 1)
> 2019-03-02 13:24:21: python.d INFO: sensors: sensors: check() => [OK]

Seems like everything should be fine but I get not sensors charts.
Then if I uncomment the following line in charts.d.conf it starts working:
`sensors=force`
As I understand it this will allow me to use the older bash module rather than the newer python one. So it seems the problem is with python. Upon restarting I get the following errors in the error.log

> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[apps] : read failed
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[go.d] : read failed
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[apps] : '/usr/libexec/netdata/plugins.d/apps.plugin' (pid 2559) disconnected after 27005 successful data collections (ENDs).
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 2560) disconnected after 0 successful data collections (ENDs).
> 2019-03-02 13:32:27: netdata ERROR : PLUGIN[tc] : child pid 2546 killed by signal 15.
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[go.d] : child pid 2560 killed by signal 15.
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 2560) exited with error code -1. Disabling it.
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[apps] : child pid 2559 killed by signal 15.
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[apps] : '/usr/libexec/netdata/plugins.d/apps.plugin' (pid 2559) exited with error code -1, but has given useful output in the past (27005 times). Waiting a bit before starting it again.
> 2019-03-02 13:32:27: netdata INFO  : PLUGINSD[go.d] : thread with task id 2557 finished
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[python.d] : read failed
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[python.d] : '/usr/libexec/netdata/plugins.d/python.d.plugin' (pid 2568) disconnected after 0 successful data collections (ENDs).
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[python.d] : child pid 2568 killed by signal 15.
> 2019-03-02 13:32:27: netdata ERROR : PLUGINSD[python.d] : '/usr/libexec/netdata/plugins.d/python.d.plugin' (pid 2568) exited with error code -1. Disabling it.
> 2019-03-02 13:32:27: netdata INFO  : PLUGINSD[python.d] : thread with task id 2563 finished

Does anyone know if these might be related to my problem?

**Comment by ilyam8** [comment] 2019-03-05 16:36
@Steve8291 so [the problem with any python module](https://github.com/netdata/netdata/issues/5541), not only with `sensors`, am i right?

**Comment by Steve8291** [comment] 2019-03-05 19:05
That's correct. I also tried with redis. So I'm assuming the problem is with any python module.
Both redis and sensors work fine from a desktop version of Ubuntu running off the live-cd.

**Comment by ilyam8** [comment] 2019-03-05 19:11
ok, @Steve8291 	so i am closing the issue in favor of #5541

**Closed by ilyam8** 2019-03-05 19:11 UTC
Labels: area/external/python, bug, help wanted

**Comment by nuumio** [comment] 2020-02-09 18:51
Sorry to bump up an old issue but I just had exactly same symptoms (`undefined symbol: libsensors_version`) with sensors plugin.

The problem turned out to be `ctypes.util.find_library` not finding any libraries at all. That was because I'm running netdata in a Buildroot based system which lacks all tools Python 2.7 needs to find libraries (`/sbin/ldconfig`, `gcc`, and `objdump`, see https://docs.python.org/2.7/library/ctypes.html#finding-shared-libraries). It also looks like Python 2.7 can load libc even when `None` is given as argument to `cdll.LoadLibrary` and that's why sensors module doesn't fail already on `_libc.free.argtypes = [c_void_p]`.

Python >= 3.6 would also try `LD_LIBRARY_PATH` env variable so setting that might help with newer Python versions (https://docs.python.org/3.8/library/ctypes.html#finding-shared-libraries).

To workaround this issue I made a patch that allows to specify paths to libc and libsensors in environment variables: https://github.com/nuumio/netdata/commit/c20a19489a
With that patch I can do:
```
export NETDATA_LIBC_PATH=/lib/libc.so.6
export NETDATA_LIBSENSORS_PATH=/usr/lib/libsensors.so.5
```
before stating netdata and sensors plugin works (libc path is not exactly needed but I added that in case it's not found in some weird environment). 

I can do a PR if that patch looks acceptable.

**Comment by SuperSandro2000** [comment] 2020-02-10 15:37
This should only be used as a fallback and clearly noted in debug logs. The risk is that we load the wrong libc.so or lib.sosensors.so and this causes always major headaches if someone played with library paths. The more correct way would be to fix your system and not netdata.

**Comment by nuumio** [comment] 2020-02-10 19:46
> This should only be used as a fallback and clearly noted in debug logs. The risk is that we load the wrong libc.so or lib.sosensors.so and this causes always major headaches if someone played with library paths. The more correct way would be to fix your system and not netdata.

Fixing the system works too: I just took a look at Buildroot and found out why `ldconfig` was missing from target: glibc package didn't have install commands for utils which include `ldconfig`. That was just recently added to Buildroot and my version didn't have it. Adding missing install commands fixed that.

So now netdata works for me without patching.
