### ISSUE TITLE
[Bug]: Browser GUI consumes lots of memory

### ISSUE THREAD

**Issue by savedario** [netdata/netdata#4366] opened 2018-10-07 15:17 UTC
My first issue here...

I keep a browser window open whilst working on a server I monitor with netdata, with the settings option to always keep the charts updated.
I noticed that after a while (right now top reports 64 mins) the memory used by what top report as 'Web Content' (I'm using Firefox 62.0.2) keeps growing (currently at 2152932K).
It happened already that size reached 80% of my 16GB RAM.
It does not seems that a refresh of the window clear anything, but I noticed that turning off the constant update seems to reduce, although quite slowly, the memory used.

Is this a design choice or did I miss something ?

**Comment by ilyam8** [comment] 2021-08-17 14:14
> Is this a design choice or did I miss something ?

@jacekkolasa can you comment if that is still an issue?

**Comment by jacekkolasa** [comment] 2021-08-24 12:21
@ilyam8 thanks for closing, this ticket was created before the big refactor last year, i think it's no longer an issue

**Comment by douglasparker** [comment] 2022-10-17 16:04
> > Is this a design choice or did I miss something ?
> 
> @jacekkolasa can you comment if that is still an issue?

This is still an issue for me. I have a browser tab open on a second monitor for monitoring an external node.

Once a day I am greeted with a white error page with the following message: `Error code: Out of Memory in browser`

I noticed #9231 was closed as a duplicate. This is definitely not an issue that's been resolved.

My machine has 64 GB of ram, and it seems that RAM usage continues to grow until the browser decides to crash the web page.

**Comment by douglasparker** [comment] 2022-10-21 09:02
Memory usage continues to grow until it crashes my browser...

@jacekkolasa  @ilyam8 Can we please have this issue reopened until this can be resolved? This is a major pain point for anyone that wants 24/7 monitoring on a secondary monitor.

![Screenshot 2022-10-21 015830](https://user-images.githubusercontent.com/18235822/197156736-50cf6d32-8b30-47fc-99b0-b022fb97eab2.png)

**Comment by douglasparker** [comment] 2022-10-21 09:41
> @douglasparker hey, is it the local agent dashboard you have open in another tab or app.netdata.cloud?

It’s the local agent; exposed via the latest version of Caddy.

**Comment by andrewm4894** [comment] 2022-10-21 14:47
@douglasparker hey - i wonder if this might be a work-around for now perhaps until we figure it out? https://chrome.google.com/webstore/detail/tab-auto-refresh/jaioibhbkffompljnnipmpkeafhpicpd

Raising with our FE team to try figure it out.

I'll leave a tab open on my end and try to recreate too.

**Comment by jacekkolasa** [comment] 2022-10-21 14:55
Hi @douglasparker , since you mentioned Netdata is exposed by Caddy - can you tell if it looks similarly as https://registry.my-netdata.io/? Ie. Is the left bar present in the Dashboard?
I'm asking because some 3rd party providers were bundling the old version of Dashboard, ie. https://registry.my-netdata.io/old/

**Comment by douglasparker** [comment] 2022-10-21 21:15
> Hi @douglasparker , since you mentioned Netdata is exposed by Caddy - can you tell if it looks similarly as https://registry.my-netdata.io/? Ie. Is the left bar present in the Dashboard? I'm asking because some 3rd party providers were bundling the old version of Dashboard, ie. https://registry.my-netdata.io/old/

@jacekkolasa It has the left bar present in the Dashboard. I am using the official NetData Docker image.

> @douglasparker hey - i wonder if this might be a work-around for now perhaps until we figure it out? https://chrome.google.com/webstore/detail/tab-auto-refresh/jaioibhbkffompljnnipmpkeafhpicpd

@andrewm4894 Thank you, I will take a look at this extension!

**Comment by douglasparker** [comment] 2022-11-08 04:29
Any updates on this? Can we have this issue reopened?

I don't particularly like using extensions from developers that I do not know.

**Comment by andrewm4894** [comment] 2022-11-08 08:04
Relabeling and renaming and reopening. @hugovalente-pm I think we maybe need to do an investigation here. @jacekkolasa had a quick look but i think maybe we need to get it more formally onto the FE teams radar probably.

**Comment by hugovalente-pm** [comment] 2022-11-09 10:03
thanks for bringing this to my attention @andrewm4894.

I know we have plans to replace the local Agent dashboard so that Netdata Cloud UI dashboard will be providing the dashboard experience on the agent. we don't know yet when this will happen so wanted to get also @novykh and @amalkov 👀 and opinion on this one

**Comment by ilyam8** [comment] 2023-09-12 14:37
> I know we have plans to replace the local Agent dashboard so that Netdata Cloud UI dashboard

It has happened, closing the issue.

**Closed by ilyam8** 2023-09-12 14:37 UTC
Labels: bug, area/web, priority/high, performance

**Comment by scarlion1** [comment] 2024-04-21 04:48
Am having this issue and seeing it both on local dashboard ("{Host}: Netdata Agent Console" at http://{hostname}:19999/) and Netdata cloud ("Netdata Console" at https://app.netdata.cloud/), I can trigger it very quickly just by scrolling and looking through several charts.  Within 1 minute, browser (Firefox) `%MEM` in _top_ was over `40.0` (or ~4.8G), and quickly rising too as charts were still loading.  Closed the tab and `%MEM` dropped back down to normal levels.

**Comment by ilyam8** [comment] 2024-04-21 10:28
Hi, @scarlion1. Can you record a short video (show what you do and %MEM of the Netdata UI tab) and share it?

**Comment by scarlion1** [comment] 2024-04-21 20:08
Ok sure, here you go:
[screencast_00000-av1_aom.webm](https://github.com/netdata/netdata/assets/2446600/2abb5e24-4fc5-400b-a206-56c228ff7d52)
_top_ is running in the upper right, on top. 😒  Came out a little longer than expected, that's because I waited too long to close the tab and the usage got so high it started swapping.  This is still interesting and entertaining.

You can see to about 1:15 the usage goes up to 33.1% (of 12 gigs in this system so ~4G there), then it appears to recover a bit as the charts loaded, and drops back down to 7.7%.  However, that quickly rises again as I try to view more charts, and is at 43.3% by 2:30.

This is around when it starts swapping and at 2:45 I frantically start trying to close the tab for the next several minutes.  At 6:50 I finally succeed, with _Firefox_ consuming `60.7%MEM` by that point and causing something in Gnome to get killed which triggers the annoying overlay telling me I have to log out.  Unfortunately it doesn't know what it's talking about as I've seen this before and I can just move the overlay to another workspace and continue using Gnome as normal.

By about 7:30 the system has recovered and I'm able to continue interacting with and using it.  _Firefox_ `%MEM` drops down to `6.7` in the end...

**Comment by ilyam8** [comment] 2024-04-22 06:36
@scarlion1 I can't reproduce it on my mac laptop (Firefox 124.0.2 (64-bit))

- I've spent 5 minutes scrolling up and down in a room with 490 nodes.
- 2 tabs open (GitHub and app netdata cloud)
- Firefox's total memory usage was 1 GB, netdata cloud tab was 415 MB.

<details>
<summary>Screenshot</summary>

<img width="864" alt="Screenshot 2024-04-22 at 09 30 53" src="https://github.com/netdata/netdata/assets/22274335/46880324-3cd2-4b90-a0b3-109bb9187447">

</details>

---

cc @netdata/cloud-fe guys please check if you can help with https://github.com/netdata/netdata/issues/4366#issuecomment-2068183976

**Comment by scarlion1** [comment] 2024-04-22 19:36
That's not fair!  wtf

I don't know what was going on.  I updated FF from 122 to 125, though.  Now, while scrolling, `%MEM` increased from `7.1` (base) to about `12`, then there was slight hiccup in the scrolling while charts were loading and `%MEM` dropped back to `7.1` (or so).  I kept scrolling, `%MEM` jumped up to `17` or so, then a hiccup, and dropped back down to `12`, I think.  As I kept scrolling, it increased to about `20` and system started swapping for a couple minutes, then it dropped back down to `8`.

It's behaving much better, now, at least.
