### ISSUE TITLE
Alarms badges are not showing the correct data

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#10871] opened 2021-03-27 06:24 UTC
##### Bug report summary

When I open the alarm panel on the netdata UI, badges have no data or undefined, and I'm not sure if the alarm is working as expected:
disk usage sample:
![image](https://user-images.githubusercontent.com/7656049/112711996-2f2e7f80-8eea-11eb-899f-8e42ab9aa2e9.png)
Here is the corresponding chart:
![image](https://user-images.githubusercontent.com/7656049/112712017-440b1300-8eea-11eb-94cd-f9c2d1b9d00c.png)

MySQL sample:
![image](https://user-images.githubusercontent.com/7656049/112712035-5422f280-8eea-11eb-9c80-2c91f840e477.png)
Here is the corresponding chart:
![image](https://user-images.githubusercontent.com/7656049/112712041-63a23b80-8eea-11eb-96dd-c51d792ec7bc.png)

##### OS / Environment

Parent environment

```
Linux netdata-01 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

1.29.1

##### Installation method

Prebuilt binary

##### Component Name

Health

##### Expected behavior

Badges to have values

**Comment by ilyam8** [comment] 2021-03-29 20:43
@yasharne hi 👋 

i installed netdata using `netdata-v1.29.1.gz.run` and i have no such problem. 

<img width="975" alt="Screenshot 2021-03-29 at 23 41 44" src="https://user-images.githubusercontent.com/22274335/112897468-53f04600-90e8-11eb-8715-2af4ded4196a.png">

---


I see you are using custom alarms (disk space have no warn and crit is 95). Can you share it?

**Comment by stelfrag** [comment] 2021-04-02 07:46
I haven't been able to reproduce either

**Comment by yasharne** [comment] 2021-04-04 07:45
Hi @ilyam8 
Are you using the parent/child architecture as well? or maybe this problem happens after certain period of time, the netdata unit is running for more than 50 days and we encountered this the previous week

**Comment by stelfrag** [comment] 2021-04-06 13:27
I am using parent / child. A couple of questions
- You have the parent running without restart for 50 days before you observe this behavior?
  - Or after a prolonged time in general e.g. just a few days?
- If the parent is running for a few days do the children disconnect and reconnect during that time?

**Comment by davidmehren** [comment] 2021-08-09 10:50
I experience a similar problem in a streaming setup.
All child notes only have gray alarm badges.

If I set `health enabled by default = on` in `stream.conf` on the parent node, the alarms start working. Maybe the default of `auto` for this option is somehow broken?

**Comment by stelfrag** [comment] 2021-08-09 14:21
@davidmehren Can you share the parent `stream.conf` ?

I am interested to see if there is both a API key section (that sets the `health enabled by default`) and a machine guid section that has a `heath enabled` parameter.

**Comment by davidmehren** [comment] 2021-08-09 14:31
We don't have anything child-specific configured, you can take a look at the template at https://gitlab.fachschaften.org/fsi-ansible/netdata-server/-/blob/master/templates/stream.conf.j2

**Comment by stelfrag** [comment] 2021-08-09 14:48
@davidmehren thank you for the information. 

We will try to reproduce. In the meantime, would it possible for you to share the netdata version running on the parent ? (netdata -v)

**Comment by stelfrag** [comment] 2021-08-10 08:02
> I experience a similar problem in a streaming setup.
> All child nodes only have gray alarm badges.
> 
> If I set `health enabled by default = on` in `stream.conf` on the parent node, the alarms start working. Maybe the default of `auto` for this option is somehow broken?

The issue observed does not seem to be related to the `auto` option.

**Comment by stelfrag** [comment] 2022-02-15 12:24
> I experience a similar problem in a streaming setup. All child nodes only have gray alarm badges.
> 
> If I set `health enabled by default = on` in `stream.conf` on the parent node, the alarms start working. Maybe the default of `auto` for this option is somehow broken?

@davidmehren you were right!! As we kept investigating, turns out there was a bug related to `auto` and there has been a 
a fix related to that in v1.33.0

**Comment by stelfrag** [comment] 2022-02-15 12:26
@yasharne are you still having an issue? Did you try the latest version?

**Comment by MrZammler** [comment] 2022-04-15 06:58
Hi, closing this, thanks for the follow up!

**Closed by MrZammler** 2022-04-15 06:58 UTC
Labels: bug, area/health, needs triage, area/streaming
