### ISSUE TITLE
Documentation clarification 

### ISSUE THREAD

**Issue by ritzzbv** [netdata/netdata#7617] opened 2019-12-24 12:26 UTC
##### Question summary
Is the following description is correct?
Given on https://docs.netdata.cloud/database/

_Running Netdata in embedded devices¶
Embedded devices usually have very limited RAM resources available.

There are 2 settings for you to tweak:

update every, which controls the data collection frequency
history, which controls the size of the database in RAM (except for memory mode = dbengine)
By default update every = 1 and history = 3600. This gives you an hour of data with per second updates.

If you set update every = 2 and history = 1800, you will still have an hour of data, but collected once every 2 seconds. This will cut in half both CPU and RAM resources consumed by Netdata. Of course experiment a bit. On very weak devices you might have to use update every = 5 and history = 720 (still 1 hour of data, but ⅕ of the CPU and RAM resources)._

**Comment by thiagoftsm** [comment] 2019-12-24 13:16
Hi @ritzzbv ,

Yes it is correct.  Netdata collects data according these rules, and every time  that `update every` is increased the amount of space necessary to store data is reduced.

Best regards!

**Comment by ritzzbv** [comment] 2019-12-24 13:23
Hi @thiagoftsm thank you for getting back to me. I am a little confused here.
As I can read above: update every = 1 and history 3600, will keep 1 hour's stats in netdata.

Now as per my settings i.e update every = 60 and history 86400, will it keep data for 1440 hours?

**Comment by thiagoftsm** [comment] 2019-12-24 13:36
Hi @ritzzbv ,

It is almost what you wrote, the problem is the dimension. Let me explain the situatoin,  when you have an `update every = 60` seconds and the `history = 86400` seconds this means that at the end you will have `86400/60` = 1440 minutes and not hours. 

Storing all the 1440 minutes of the day, you will have the whole day stored, but with granularity of minutes.

Best regards!

**Comment by ritzzbv** [comment] 2019-12-24 15:21
Hi @thiagoftsm ,

Thank you so much for clearing this doubt for me. With my configuration, I will have only 24 hours data in my netdata master(I have a master-slave system in place). But I can see matrics older than 24 hours. Am I missing something here?
Thank you for you time.

**Comment by thiagoftsm** [comment] 2019-12-24 17:03
What is the memory mode set in your `netdata.conf`? Case you are using `dbengine` this makes sense, because Netdata stores the old data compressed on disk, but it keeps the data for the specified period of time inside memory.

Best regards!

**Comment by ritzzbv** [comment] 2019-12-24 17:41
memory mode is save.

**Comment by thiagoftsm** [comment] 2019-12-24 18:30
I have to do more few questions for you to understand better the case you are reporting here, because we are in front a situation that is not expected:

1 ) What is your Netdata version?
2 ) What are the values set for `history` and `update every`?
3) Case it is possible to do a big request for your master, please, run the following command `curl -o request.json http://localhost19999/api/v1/data?chart=system.cpu` . How many lines the output file have? I am using `localhost` here assuming that there is enough space in the device to store the data there.

Best regards!

**Comment by ritzzbv** [comment] 2019-12-25 05:26
Hi @thiagoftsm ,

1. I am running on older version of netdata i.e 1.10.1_rolling

2. history = 86400
    update every = 60

3. Data array in request.json contains total 31821 entries.
   Out of 31821 entries, 4327 entries have values and remaining have null values.
   The last valid value came on 22nd Dec which is when we restarted the netdata in master.

Will this info help?

Regards,
Ritesh

**Comment by thiagoftsm** [comment] 2019-12-25 12:12
Hi @ritzzbv ,

I was not at Netdata when the version 1.10 was released, but I can say for you that we released different bug fixes since that time and probably this problem was fixed. There is also the possibility of this do not be a real problem, to confirm this I assigned this issue to our Database Engineer. 

I will also do more tests during the week to understand the numbers given in `3`, I have an idea about what is happening, but I prefer to do an investigation to avoid write a wrong answer to you.

Best regards!

**Comment by ritzzbv** [comment] 2019-12-26 10:11
Hi @thiagoftsm ,

Thank you so much. I am moving to newer version of netdata now with dbengine mode.
Now to store data for 7 days.
[global]
     history = 604800
      update every = 60
[statsd]
   private charts memory mode = dbengine
   private charts history = 604800

The above config will work?

Regards,
Ritesh

**Comment by mfundul** [comment] 2019-12-26 12:06
> 
> 
> Hi @thiagoftsm ,
> 
> Thank you so much. I am moving to newer version of netdata now with dbengine mode.
> Now to store data for 7 days.
> 
> ```
> [global]
>      history = 604800
>       update every = 60
> [statsd]
>    private charts memory mode = dbengine
>    private charts history = 604800
> ```
> 
> The above config will work?
> 
> Regards,
> Ritesh

Check [here](https://docs.netdata.cloud/database/engine/) for reference. The `history` configuration option does not apply to `memory mode = dbengine`. I would suggest something like:
```
[global]
    update every = 1
    memory mode = dbengine
    page cache size = 32
    dbengine disk space = 256
```
You can allocate more RAM to `dbengine` by increasing `page cache size` to reduce the frequency of going to disk when doing queries.

The 256 MiB of disk space (`dbengine disk space`) are enough for about 1 day of data retention when your data collection frequency is every 1 second (`update every = 1`) for ~4000 metrics. You could set disk space to 2048 MiB to achieve about 7 days of history. If you set `update every = 60` you reduce your resolution 60 times, which may not be very useful, but you get 60 times more history effectively.

**Comment by ritzzbv** [comment] 2019-12-26 12:38
Hi @mfundul ,

Thanks and that makes sense. Does this work in same manner for Master slave streaming ```
stream.conf
Master:
   default history = 3600
    default memory mode = dbengine 

```
If you see here we are asked for page cache size or dbengine disk space

In this case [global] conf from netdata.conf will be considered?

Thanks Again.

Regards,
Ritesh

**Comment by mfundul** [comment] 2019-12-26 13:12
> 
> 
> Hi @mfundul ,
> 
> Thanks and that makes sense. Does this work in same manner for Master slave streaming ```
> 
> ```
> stream.conf
> Master:
>    default history = 3600
>     default memory mode = dbengine
> ```
> 
> If you see here we are asked for page cache size or dbengine disk space
> 
> In this case [global] conf from netdata.conf will be considered?
> 
> Thanks Again.
> 
> Regards,
> Ritesh

Look [here](https://github.com/netdata/netdata/blob/master/streaming/README.md#configuration) for reference.
It would be something like:
```
[API_KEY]
    default memory mode = dbengine
```
and the additional page cache size and dbengine disk space configuration options are inherited from the global Netdata configuration.

**Comment by ritzzbv** [comment] 2019-12-26 13:13
@mfundul doubts clear. Thank you..!!

**Closed** 2019-12-30 10:38 UTC
Labels: no changelog, question
