### ISSUE TITLE
[Bug]: kickstart.sh installs netdata to /usr/local on FreeBSD

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#12430] opened 2022-03-16 15:26 UTC
### Bug description

The kickstart shows this:

```sh
# ./kickstart.sh

 --- Using /tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV as a temporary directory. --- 
 --- No existing installations of netdata found, assuming this is a fresh install. --- 
 --- Fetching script to detect required packages... --- 
[/tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV]# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV/install-required-packages.sh https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh 
 OK 

 --- Running downloaded script to detect required packages... --- 
[/tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV]# /usr/local/bin/bash /tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV/install-required-packages.sh netdata 
 > FreeBSD Version: 12.3-RELEASE ...
 > Checking for gmake ...

We detected these:
Distribution    : freebsd
Version         : 12.3-RELEASE
Codename        : 
Package Manager : install_pkg
Packages Tree   : freebsd
Detection Method: uname
Default Python v: 3 

Searching for distro_sdk ...
Searching for autoconf_archive ...
Searching for libz_dev ...
Searching for libuuid_dev ...
Searching for libmnl_dev ...
WARNING
package libmnl-dev is not available in this system.

Searching for json_c_dev ...
Searching for libuv ...
Searching for lz4 ...
Searching for openssl ...
Searching for judy ...
Searching for libelf ...
Searching for python3 ...

All required packages are already installed. Now proceed to the next step.

 OK 

[/tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV]# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV/sha256sum.txt https://storage.googleapis.com/netdata-nightlies/sha256sums.txt 
 OK 

[/tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV]# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV/netdata-latest.tar.gz https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz 
 OK 

[/tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV]# tar -xf /tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV/netdata-latest.tar.gz -C /tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV 
 OK 

 --- Building netdata --- 
[/tmp/netdata-kickstart-XXXXXXXXXX.Yx5esXjV/netdata-v1.33.1-177-gd14059673]# ./netdata-installer.sh --install-no-prefix /usr/local --auto-update --require-cloud 

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata  .-.   .-.   .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'               '-'   '-'   '-'   '-'   '-'   
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

 --- real-time performance monitoring, done right! --- 

  You are about to build and install netdata to your system.

  The build process will use /tmp for
  any temporary files. You can override this by setting $TMPDIR to a
  writable directory where you can execute files.

  It will be installed at these locations:

   - the daemon     at /usr/local/usr/sbin/netdata
   - config files   in /usr/local/etc/netdata
   - web files      in /usr/local/usr/share/netdata
   - plugins        in /usr/local/usr/libexec/netdata
   - cache files    in /usr/local/var/cache/netdata
   - db files       in /usr/local/var/lib/netdata
   - log files      in /usr/local/var/log/netdata
   - pid file       at /usr/local/var/run/netdata.pid
   - logrotate file at /etc/logrotate.d/netdata

  This installer allows you to change the installation path.
  Press Control-C and run the same command with --help for help.


  NOTE:
  Anonymous usage stats will be collected and sent to Netdata.
  To opt-out, pass --disable-telemetry option to the installer or export
  the environment variable DISABLE_TELEMETRY to a non-zero or non-empty value
  (e.g: export DISABLE_TELEMETRY=1).

Press ENTER to build and install netdata to '/usr/local' > 
```

After it finished:

```sh
# find /usr/local -name netdata
/usr/local/etc/netdata
/usr/local/usr/libexec/netdata
/usr/local/usr/lib/netdata
/usr/local/usr/share/netdata
/usr/local/usr/sbin/netdata
/usr/local/var/run/netdata
/usr/local/var/lib/netdata
/usr/local/var/cache/netdata
/usr/local/var/log/netdata
```

### Expected behavior

I am  not sure. I would expect either `/opt/netdata` or install it at `/`.

### Steps to reproduce

Run kickstart.sh on FreeBSD.

### Installation method

kickstart.sh

### System info

```shell
# uname -a; uname -K
FreeBSD freebsd 12.3-RELEASE FreeBSD 12.3-RELEASE r371126 GENERIC  amd64
1203000
```

### Netdata build info

```shell
# /usr/local/usr/sbin/netdata -W buildinfo
Version: netdata v1.33.1-177-nightly
Configure options:  '--prefix=/usr/local/usr' '--sysconfdir=/usr/local/etc' '--localstatedir=/usr/local/var' '--libexecdir=/usr/local/usr/libexec' '--libdir=/usr/local/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--disable-dependency-tracking' '--with-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=-O2' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: NO
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by ilyam8** [comment] 2022-03-16 15:32
`/usr/local` is the default install prefix on FreeBSD when `--install` is not provided.

https://github.com/netdata/netdata/blob/121129aaeb60aa40d9c2572979cda98d12daccf5/packaging/installer/kickstart.sh#L781-L796

**Comment by ktsaou** [comment] 2022-03-16 16:14
> `/usr/local` is the default install prefix on FreeBSD when `--install` is not provided.

Why?

**Comment by Ferroin** [comment] 2022-03-16 18:26
> > `/usr/local` is the default install prefix on FreeBSD when `--install` is not provided.
> 
> Why?

Because `/opt` is not a standard install prefix for _anything_ on FreeBSD, and _NOTHING_ should be installing in `/` directly on FreeBSD (even native packages install under `/usr/local`, `/` is _only_ for core OS components).

**Comment by Ferroin** [comment] 2022-03-16 18:26
To clarify further, this is expected behavior for _normal_ FreeBSD users, and was specifically requested by them.

**Comment by ktsaou** [comment] 2022-03-16 20:51
> To clarify further, this is expected behavior for _normal_ FreeBSD users, and was specifically requested by them.

ok, great! The way we install it is it right? Like `/usr/local/usr/sbin/netdata` ?

**Comment by MikeJakubik** [comment] 2022-03-16 23:51
This is the correct location based on FreeBSD standards, either use the port or this script, but not both. Please don't pollute heir with Linux dirs like /opt.

https://www.freebsd.org/cgi/man.cgi?hier(7)

**Comment by ilyam8** [comment] 2022-03-17 09:03
Closing the issue because using `/usr/local` as install prefix is the correct way. Thanks @MikeJakubik and @Ferroin.

**Comment by Ferroin** [comment] 2022-03-17 14:23
Reopening, because if we’re dumping things in `/usr/local/usr/sbin` then that is blatantly wrong, but for different reasons from why the issue was originally opened...

**Comment by Ferroin** [comment] 2022-06-28 12:00
Closing this in favor of https://github.com/netdata/netdata/issues/13242, which more concretely explains the specific issue that this was being kept open for.

**Closed by Ferroin** 2022-06-28 12:00 UTC
Labels: bug, area/packaging, os/bsd
