### ISSUE TITLE
mysql.handlers has 3000 "read rnd next" and 1600 "write" on an *empty* MySQL instance

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/netdata#10890] opened 2021-03-31 10:47 UTC
##### Bug report summary

Hi thanks for the lib! I have an almost **empty** mysql instance. However, I see mysql.handlers has 3000 "read rnd next" and 1600 "write". (See the screenshot below). At the same time, *all other metrics are fine* (e.g. they are near zero). I also look at the metrics grabbed by my cloud provider, and that metric is also near zero.

Therefore, I wonder whether this is a bug of NetData? What should I do to solve it?

![image](https://user-images.githubusercontent.com/5236035/113132551-2ecb1700-9251-11eb-9bc1-a40176366677.png)

##### OS / Environment

```
kubernetes + netdata helm chart
host machine is centos
```

##### Netdata version

```
Version: netdata v1.29.3
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' '--with-libJudy=externaldeps/libJudy' 'CFLAGS=' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

##### Installation method

kubernetes netdata helmchart

##### Component Name

mysql

##### Steps To Reproduce

1. install netdata
2. look at it

##### Expected behavior

metric near zero

**Comment by fzyzcjy** [comment] 2021-03-31 14:47
@ilyam8 Hi 👋, thanks for the reply!

I look at `SHOW GLOBAL STATUS where variable_name = 'Handler_write';` and re-execute it about once per second. I do see it increase by >1000 per second. Thus netdata may be correct in faithfully reporting this value.

However, I wonder what is happending? This is an almost empty database with few queries and data...

**Comment by ilyam8** [comment] 2021-03-31 14:58
Well, i don't know, but it is interesting, indeed 🤔  If you find out what is happening, please share!

**Comment by ilyam8** [comment] 2021-03-31 15:20
Closing the issue because it is not a bug.

**Closed by ilyam8** 2021-03-31 15:20 UTC
Labels: area/external, question

**Comment by fzyzcjy** [comment] 2021-04-01 00:25
@ilyam8 Thanks for your help! I will share when I find out the cause

**Comment by fzyzcjy** [comment] 2021-04-17 14:11
A bit of update: I use a feature provided by my cloud service called "full sql logging". It logs and shows each and every sql that is executed. following is everything from 2021/04/17 22:04:32 GMT+08:00 to 2021/04/17 22:04:33 GMT+08:00. Notice this is a sql service with very low workload at this moment, so almost no query except for the metric scrapers.

![image](https://user-images.githubusercontent.com/5236035/115115931-9dd29a80-9fc9-11eb-8f55-fcbe190bff85.png)

Interestingly, such full sql logging does not show anything like the "1600 writes per second".

**Comment by ilyam8** [comment] 2021-04-18 13:08
@fzyzcjy those are internal write statements ([`Handle_write`](https://mariadb.com/kb/en/server-status-variables/#handler_write)), could be that gathering metrics results in creating some internal temporary table or something like that 🤷‍♂️ 

To test it:
 - stop monitoring tools
 - invoke `SHOW GLOBAL STATUS LIKE 'Handler_%';`
 - count number of rows in reply
 - check `Handler_write` value

**Comment by ilyam8** [comment] 2021-06-15 12:09
@fzyzcjy hey

[Was I correct?](https://github.com/netdata/netdata/issues/10890#issuecomment-821989269)

**Comment by fzyzcjy** [comment] 2021-06-16 00:05
@ilyam8 Hi sorry I did not test it yet since have many high priority things to do... I will check it soon
