### ISSUE TITLE
Cannot connect to cloud from amazon linux 2.

### ISSUE THREAD

**Issue by zack-shoylev** [netdata/netdata#9169] opened 2020-05-26 15:51 UTC
##### Bug report summary
Cannot connect to cloud from amazon linux 2.
Failed to connect to https://app.netdata.cloud, return code 5

##### OS / Environment
amazon linux 2

##### Netdata version
netdata v1.22.1 

##### Component Name
aclk

##### Steps To Reproduce
```
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)  --stable-channel
```
aclk-available: false
Failed to connect to https://app.netdata.cloud, return code 5

##### Expected behavior
aclk should work

**Comment by Treadstone06** [comment] 2020-05-26 18:49
Here is the requested error log.  Thanks for your time!  
[error.log](https://github.com/netdata/netdata/files/4684372/error.log)

**Comment by underhood** [comment] 2020-06-01 12:48
This is a duplicate of #8966 . @zack-shoylev we now have known issue that kickstart-static64 cannot connect to cloud on some systems. Other install methods work on same system

**Comment by underhood** [comment] 2020-06-01 13:01
@Treadstone06 Looking at your logfile you seem to be trying to use proxy for outgoing connection? Can you share some insight into what kind of proxy are you using and how is it configured?

**Comment by underhood** [comment] 2020-06-01 13:02
@zack-shoylev I am bit confused now .did you open this issue in for the problem that @Treadstone06 is experiencing?

**Comment by zack-shoylev** [comment] 2020-06-01 14:16
@underhood this came from this ticket https://netdata.zendesk.com/agent/tickets/116 and yes

**Comment by Treadstone06** [comment] 2020-06-01 14:35
> @Treadstone06 Looking at your logfile you seem to be trying to use proxy for outgoing connection? Can you share some insight into what kind of proxy are you using and how is it configured?

I'm not, or at least not intentionally.  I did attempt to work through troubleshooting a bit and may've installed it there.  Originally, I just installed straight without any proxy attempt and had the same issue for what it's worth.

**Comment by underhood** [comment] 2020-06-01 15:17
from the log you provided i can see :
```
2020-05-26 18:14:31: netdata INFO  : ACLK_Main : Connecting using HTTP proxy:"http://localhost:443"
2020-05-26 18:14:31: netdata ERROR : ACLK_Main : Libwebsockets: lws_client_socket_service: ERROR proxy did not reply with h1
 (errno 22, Invalid argument)
```
which seems to point to an attempt to use an HTTP proxy that doesn't work. Do you have logfile where the agent cannot connect with `proxy = none`?

**Comment by underhood** [comment] 2020-06-01 17:37
OK, I just tested with Amazon Linux 2 in VM fresh install with:
`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)  --stable-channel`
no other commands/tweaks used and it compiled with ACLK enabled:
```
{
	"version": "v1.22.1",
	"uid": "fbce01c2-a42c-11ea-b3bd-080027a7b4ab",
	"mirrored_hosts": [
		"amazonlinux.onprem"
	],
	"alarms": {
		"normal": 58,
		"warning": 0,
		"critical": 0
	},
	"os_name": "Amazon Linux",
	"os_id": "amzn",
	"os_id_like": "centos rhel fedora",
	"os_version": "2",
	"os_version_id": "2",
	"os_detection": "/etc/os-release",
	"cores_total": "1",
	"total_disk_space": "52428800",
	"cpu_freq": "4013000000",
	"ram_total": "2090049536",
	"container_os_name": "none",
	"container_os_id": "none",
	"container_os_id_like": "none",
	"container_os_version": "none",
	"container_os_version_id": "none",
	"kernel_name": "Linux",
	"kernel_version": "4.14.177-139.254.amzn2.x86_64",
	"architecture": "x86_64",
	"virtualization": "kvm",
	"virt_detection": "systemd-detect-virt",
	"container": "unknown",
	"container_detection": "none",
	... .... .... (SKIPPED UNIMPORTANT STUFF)
	"cloud-enabled": true,
	"cloud-available": true,
	"agent-claimed": false,
	"aclk-available": false
}
```

Error log shows following:
`ACLK_Main : Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)`

Which is the same case as in #8966 and is case for all RHEL based distros. The current workaround is to use another install method than `kickstart-static64.sh`

As for the proxy issue seen in the log. The user mentioned above that he didn't intend to use HTTP proxy for outbound ACLK connection and was part of the troubleshooting.

**Comment by underhood** [comment] 2020-06-01 17:48
additionally I installed with:
`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --no-updates --stable-channel`
and claimed again,
`netdata` connects to cloud successfully
```
2020-06-01 17:44:40: netdata INFO  : ACLK_Main : Waiting for netdata to be ready
2020-06-01 17:44:40: netdata INFO  : ACLK_Main : Waiting for Cloud to be enabled
2020-06-01 17:44:40: netdata INFO  : ACLK_Main : Waiting for netdata to be claimed
2020-06-01 17:45:27: netdata INFO  : ACLK_Main : Setting ACLK target host=app.netdata.cloud port=443 from https://app.netdata.cloud
2020-06-01 17:45:27: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-06-01 17:45:27: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/9184d04a-a42f-11ea-9c34-080027a7b4ab/challenge
2020-06-01 17:45:27: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-06-01 17:45:28: netdata INFO  : ACLK_Main : aclk_send_https_request POST
2020-06-01 17:45:28: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_PROTOCOL_INIT
2020-06-01 17:45:28: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_SERVER_NEW_CLIENT_INSTANTIATED
2020-06-01 17:45:28: netdata INFO  : ACLK_Main : Using challenge-response: 9184d04a-a42f-11ea-9c34-080027a7b4ab / fPil/gt7Qx0k9GjgVC6J5CbXHTA=
2020-06-01 17:45:29: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_CLIENT_ESTABLISHED
2020-06-01 17:45:29: netdata INFO  : ACLK_Main : Establishing MQTT link to [app.netdata.cloud:443]
2020-06-01 17:45:29: netdata INFO  : ACLK_Main : Connection to cloud estabilished
2020-06-01 17:45:29: netdata INFO  : ACLK_Main : Connection detected (0 queued queries)
2020-06-01 17:45:30: netdata INFO  : ACLK_Query : thread created with task id 17230
2020-06-01 17:45:30: netdata INFO  : ACLK_Query : set name of thread 17230 to ACLK_Query
2020-06-01 17:45:30: netdata INFO  : ACLK_Query : AGENT stable, last collector initialization activity was 27 seconds ago
```
![Screenshot from 2020-06-01 19-45-59](https://user-images.githubusercontent.com/6674623/83437837-be8d1280-a440-11ea-99ad-38f27dd4038c.png)

I am therefore closing this as a duplicate of #8966

**Closed by underhood** 2020-06-01 17:48 UTC
Labels: bug

**Comment by rdifrancesco** [comment] 2020-07-28 02:57
@underhood Any ETA for a resolution on the issue with using the kickstart-static64.sh install method?

**Comment by underhood** [comment] 2020-07-28 07:51
@rdifrancesco this should be closed already, I did testing on Amazon Linux in Virtual Box. In case you have a problem can you open a new issue and provide some more details/logs?
Maybe something broke in new versions...
Thanks
