### ISSUE TITLE
Netdata not updating

### ISSUE THREAD

**Issue by jamesnr** [netdata/netdata#10128] opened 2020-10-22 21:15 UTC
I have tried to find a related issue, though have not seen one.

Netdata is not updating overnight and I can not manually update via "bash <(curl -Ss https://my-netdata.io/kickstart.sh)", I receive:
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 --- Found existing install of Netdata under: / ---
 ABORTED  Existing installation detected which cannot be safely updated by this script, refusing to continue.

If I manually update via:
cd netdata
./netdata-installer.sh 
The installation seems to work, but the version stays the same, currently "d5e1197". There is a later version that has not updated and I have watched the update check state there are other versions that have past.

![image](https://user-images.githubusercontent.com/71431693/96930302-65874f00-14b3-11eb-9051-d03a0146e835.png)

##### OS / Environment
grep -Hv "^#" /etc/*release
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)

##### Netdata version
netdata d5e1197

Thank you.

**Comment by stelfrag** [comment] 2020-10-23 07:39
Hi @jamesnr ,

can you check 

https://learn.netdata.cloud/docs/agent/packaging/installer/update#one-line-installer-script-kickstartsh

and see if `--reinstall` helps?

**Comment by jamesnr** [comment] 2020-10-23 08:29
Hi @stelfrag 

Tried the reinstall, actually I forgot to include that previously, get:

bash <(curl -Ss https://my-netdata.io/kickstart.sh) --reinstall
 --- Found existing install of Netdata under: / ---
 ABORTED  Existing install is a static install, please use kickstart-static64.sh instead.

Part of the challenge maybe that I don't have an ".environment" file in /etc/netdata

This option was definitely not used
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)

Any thoughts?? Thank you!

**Comment by stelfrag** [comment] 2020-10-23 09:01
@Ferroin Can you please take a look ? (if there is a way to document how this can be fixed)

**Comment by jamesnr** [comment] 2020-10-23 12:25
Just in case as the install advised, I tried a static install and received

bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)
 --- Found existing install of Netdata under: / ---
 ABORTED  Existing installation detected which cannot be safely updated by this script, refusing to continue.

**Comment by Ferroin** [comment] 2020-10-26 14:45
The ideal fix is to completely clean off the existing install of Netdata. The case this check is trying to protect against is a user installing Netdata through some external source, then installing through our installer, then uninstalling through that external source, which will usually break the install done through the installer.

If you are _100% certain_ that you have properly cleaned off the existing install, you can add `--allow-duplicate-install` to the kickstart install command to force it to ignore the failure to identify the type of the existing install.

**Comment by jamesnr** [comment] 2020-10-26 17:31
I've found the environment file with the following contents. Just checking, do I need to still fully install.. The "./netdata-installer.sh" ran, completed though didn't update the site, ie change the version. Thoughts?

You help is much appreciated.

# Created by installer
PATH="/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin$
CFLAGS="-O2"
NETDATA_PREFIX=""
NETDATA_CONFIGURE_OPTIONS=""
NETDATA_ADDED_TO_GROUPS=" adm nobody"
INSTALL_UID="0"
REINSTALL_COMMAND="./netdata-installer.sh "
# next 3 values are meant to be populated by autoupdater (if enabled)
NETDATA_TARBALL_URL="https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz"
NETDATA_TARBALL_CHECKSUM_URL="https://storage.googleapis.com/netdata-nightlies/sha256sums.txt"
NETDATA_TARBALL_CHECKSUM="new_installation"

**Comment by Ferroin** [comment] 2020-10-26 17:48
Manually running `./netdata-installer.sh` from a clone of the repo will never update you to anything other than the version of the repo that you checked out, which is why the version did not appear to change.

By ‘kickstart install command’ I meant `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`. Running `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --allow-duplicate-install` should get you the newest version and enable auto-updates so that you stay up to date.

**Comment by jamesnr** [comment] 2020-10-26 18:41
Apologies, I knew that. I'll arrange an uninstall an re-install and advise.

Best regards,
Reece James
07500 115311
https://www.fides-it.co.uk

This email and any attachments are confidential and intended solely for the
use of the addressee. You should not copy or disclose its contents to any
other person. If you have received this email in error, please notify the
sender immediately. Unless otherwise stated any views or opinions presented
are solely those of the author and are not endorsed by the entity in the
signature block.

E-mail transmission cannot be guaranteed to be secure or error-free as
information could be intercepted, corrupted, lost, destroyed, arrive late,
or contain viruses. Fides-IT Consulting Limited does not therefore accept
liability for any errors or omissions in the contents of this message,
which arise as a result of e-mail transmission. Although we have taken
reasonable precautions to ensure no viruses are present in this email,
Fides-IT Consulting Limited cannot accept liability for any loss or damage
sustained as a result of viruses.

**Comment by jamesnr** [comment] 2020-10-27 08:37
OK, I performed the uninstall process per instructions.

wget https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-uninstaller.sh
chmod +x ./netdata-uninstaller.sh
./netdata-uninstaller.sh --yes --env <environment_file>

However the uninstall errors as per below.

./netdata-uninstaller.sh --yes --env <environment_file>
bash: syntax error near unexpected token `newline'

Any thoughts?

**Comment by jamesnr** [comment] 2020-11-03 08:48
I've tried an uninstall with a --force and while it uninstalls, the bash <(curl -Ss https://my-netdata.io/kickstart.sh) --allow-duplicate-install fails with  Cannot install netdata from source (the source directory does not include netdata-installer.sh). Leaving all files in /tmp/netdata-kickstart-vexnUzr6fI

I have read that you may need to just remove directory structure "/opt/netdata" is that correct? 

Should I try the uninstall with a --force and ensure yum removes netdata just in case something odd has gone on? Not sure at this point what the best route is. Thanks for your assistance.

**Comment by Ferroin** [comment] 2020-11-03 12:09
That particular issue is (probably unrelated  unrelated to the uninstall issue, though it may be related to the failures to update. Please see #9863.

**Comment by jamesnr** [comment] 2020-11-04 08:15
I don't think so, I have standard settings of drwxrwxrwt and I'm logged in as root which is the owner.  Any other thoughts?

**Comment by kozicpetar** [comment] 2020-11-05 09:27
I wrote in other issue, I have same problem.
Manual run of netdata-updater.sh

```
./netdata-updater.sh
Thu Nov  5 10:21:18 CET 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
./netdata-updater.sh: line 77: /tmp/netdata-test.chXW7LOEW2: Permission denied
Thu Nov  5 10:21:19 CET 2020 : INFO:  Current Version: 001025000000
Thu Nov  5 10:21:19 CET 2020 : INFO:  Latest Version: 001026000000
./netdata-latest.tar.gz: OK
Thu Nov  5 10:21:44 CET 2020 : INFO:  Re-installing netdata...
./netdata-updater.sh: line 225: ./netdata-installer.sh: Permission denied
Thu Nov  5 10:21:44 CET 2020 : ERROR:  FAILED TO UPDATE NETDATA : FAILED TO COMPILE/INSTALL NETDATA
```

If I need to remove and install again all my netdata instance that will be devastating. I have more than 50 servers.

**Comment by jamesnr** [comment] 2020-11-12 17:46
Can I ask if this is being looked at or any ideas? I have two servers and one is updating correctly and there's a marked difference between V1.26 and the server that has this problem. Thank you.

**Comment by stelfrag** [comment] 2020-11-12 19:42
@Ferroin can you please check ?

**Comment by jamesnr** [comment] 2020-11-19 09:16
Can I ask if anyone is looking at this given a week has past? Thank you.

**Comment by Ferroin** [comment] 2020-11-19 11:52
Apologies for the delays on this one. I’m currently working on a number of improvements to the updater that should include a fix for this.

**Comment by jamesnr** [comment] 2020-11-19 12:02
Understand, I will wait, now I know. Thank you.

**Comment by jamesnr** [comment] 2020-12-21 14:53
May I ask, as it's been over a month when you hope to make the changes to the updater? 

Much appreciated and hoping Covid isn't impacting. 

Thank you.

**Comment by Ferroin** [comment] 2021-01-04 14:19
The primary issue should be fixed in master now, but the fix for that introduced a different bug that should be fixed by #10447

**Comment by jamesnr** [comment] 2021-01-04 15:58
Thanks, Ferroin!!

I will wait a bit for the fix to work its way through to release, ie keep an eye on its progress and advise when tried and all working again. Appreciate the work!

**Comment by jamesnr** [comment] 2021-01-07 08:21
Ferroin, may I ask, will the normal overnight update pick up the change, or a manual "./netdata-installer.sh", or is a remove and re-install required in my case, as tried previously?

Thanks!

**Comment by Ferroin** [comment] 2021-01-07 13:41
The issues other than the one mentioned above that has a currently unmerged PR to fix it will likely need a manual re-run of the install.

The issue mentioned above that currently has an unmerged PR to fix it will automatically have the fix picked up by the regular updater when merged, as should almost all other issues with the updater code from now on (adding this functionality was part of what I was working on with the updater fixes back in November).

**Comment by jamesnr** [comment] 2021-01-08 08:53
Thanks Forroin, I'll wait for the merge to complete and the new updater to be live and try it. If I need to do an uninstall and re-install I will and will then report back, success or not. Response appreciated.

**Comment by Ferroin** [comment] 2021-01-12 12:39
The above-mentioned PR has now been merged, so the next automatic update should work correctly without needing any user intervention.

**Comment by kozicpetar** [comment] 2021-01-12 12:45
@Ferroin 
May I run now to check:

`/bin/bash /usr/libexec/netdata/netdata-updater.sh`

**Comment by Ferroin** [comment] 2021-01-12 13:26
> @Ferroin
> May I run now to check:
> 
> `/bin/bash /usr/libexec/netdata/netdata-updater.sh`

Yes, running the updater by hand should also pick up the fixes.

**Comment by kozicpetar** [comment] 2021-01-12 13:42
@Ferroin 
I run it on WHM server but same error:

```
/bin/bash /usr/libexec/netdata/netdata-updater.sh
Tue Jan 12 14:41:42 CET 2021 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
/usr/libexec/netdata/netdata-updater.sh: line 77: /tmp/netdata-test.JHGr9JxchD: Permission denied
Tue Jan 12 14:41:43 CET 2021 : INFO:  Current Version: 001026000000
Tue Jan 12 14:41:43 CET 2021 : INFO:  Latest Version: 001028000000
./netdata-latest.tar.gz: OK
Tue Jan 12 14:41:46 CET 2021 : INFO:  Re-installing netdata...
/usr/libexec/netdata/netdata-updater.sh: line 225: ./netdata-installer.sh: Permission denied
Tue Jan 12 14:41:46 CET 2021 : ERROR:  FAILED TO UPDATE NETDATA : FAILED TO COMPILE/INSTALL NETDATA
```

**Comment by Ferroin** [comment] 2021-01-12 14:34
@kozicpetar Can you retry with `$TMPDIR` set to a path that the user you are running the script as has permissions to both write files and execute files from?

**Comment by kozicpetar** [comment] 2021-01-12 14:49
@Ferroin 
Yes, I do that now. I exported folder `/opt` to TMPDIR
`export TMPDIR=/opt`

and I run installer again with command:
`/bin/bash /usr/libexec/netdata/netdata-updater.sh`

Update finished sucessfully
```
 --- We are done! ---

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed and running now!  -'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->
```

That mean I need to set manually TMPDIR on every WHM server and run script?
Thank you.

**Comment by jamesnr** [comment] 2021-01-12 15:00
Just checking, same for me? Thanks. If I run a ./netdata-updater.sh from within netdata dir, the installer complete by HTML page advises there's a later version "c817387". Just check best way to proceed.

**Comment by Ferroin** [comment] 2021-01-12 15:23
@kozicpetar You should only need to have `$TMPDIR` set appropriately once on each install. Current versions of the installer and updater will reuse what was set initially provided it appears to still work.

@jamesnr Yes, you should be able to run the updater now by hand and have it work correctly. You may or may not need to explicitly specify a `$TMPDIR` in the environment depending on the specifics of your system (most users should not need to). However, if you have automatic updates configured, you shouldn’t actually need to do anything, as they will also pick up the fixes the next time they run.

**Comment by jamesnr** [comment] 2021-01-12 16:43
Automatic updates are configured. I did run normally. Update completed but IP:19999/#menu_system_submenu_cpu;theme=slate;help=true shows update still available and percentages are on the right not underneath like V1.28 which I have on another platform. Therefore I think it hasn't worked. I'm on Centos 7, hence updater is located within the netdata directory. 

I am not confident the updater has worked, though will wait for the overnight process to run.

**Comment by kozicpetar** [comment] 2021-01-14 23:33
> @kozicpetar You should only need to have `$TMPDIR` set appropriately once on each install. Current versions of the installer and updater will reuse what was set initially provided it appears to still work.
> 

Unfortunately this works only in the moment when I export TMPDIR. 
Next day when update runs through cron, update again fails with same error and env variable TMPDIR is empty. Looks like WHM servers overwrite that.
Look like this merge is not permanently sort problem with update?

**Comment by jamesnr** [comment] 2021-01-16 16:40
The over night update definately isn't working. Do I need to un-install Netdata and install again?

**Comment by kozicpetar** [comment] 2021-01-19 12:33
@Ferroin 
I will be very appreciate to you if you can describe me something and point what to do.

On my WHM Centos 7 servers I installed netdata with kickstart script. That script also setup netdata-update cron in `/etc/cron.daily/`

Every day I get notification from cron that netdata isn't updated with error:

```
/etc/cron.daily/netdata-updater:

/etc/cron.daily/netdata-updater: line 87: /tmp/netdata-test.Y9yrNC08gb: Permission denied
```

This error is related with TMPDIR.

If I set (export) variable as root on example:
`export TMPDIR=/opt`

and run updater as root with command:
`/bin/bash /usr/libexec/netdata/netdata-updater.sh`
everything works well.

I set also TMPDIR variable as `netdata` user in case updater script was running as netdata user, but as I can see that works as root.

To clarify, with exported TMPDIR as root and netdata user, netdata-update cron don't work and showing error from above.
What I can do to solve this problem?

**Comment by Ferroin** [comment] 2021-01-19 19:03
@jamesnr It’s unfortunately looking like you will indeed need to reinstall.

**Comment by Ferroin** [comment] 2021-01-19 19:06
@kozicpetar I’m actually not sure why things are still not working correctly for you in this case. Running the updater manually with `$TMPDIR` set to a usable location _should_ be saving the value of `$TMPDIR` and then using that for subsequent runs of the updater, but it sounds like that’s not working.

Can you check the contents of `/etc/netdata/.environment` on a system you are seeing this issue on to see if there is a line that starts with `NETDATA_TMPDIR=` and if so, whether the value it lists matches what you last used for `$TMPDIR` when running the updater manually?

**Comment by kozicpetar** [comment] 2021-01-20 12:19
@Ferroin 
I'm really appreciate on all your help.
I checked my `/etc/netdata/.environment`

This is content:

```
# Created by installer
PATH="/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin:/sbin:/opt/cpanel/composer/bin"
CFLAGS="-O2"
LDFLAGS=""
NETDATA_PREFIX=""
NETDATA_CONFIGURE_OPTIONS=""
NETDATA_ADDED_TO_GROUPS=" adm nobody"
INSTALL_UID="0"
NETDATA_GROUP="netdata"
REINSTALL_OPTIONS="--auto-update --stable-channel "
RELEASE_CHANNEL="stable"
IS_NETDATA_STATIC_BINARY="no"
NETDATA_LIB_DIR="/var/lib/netdata"
```

I just set:
`NETDATA_TMPDIR="/opt"`

I hope that will be enough. We will see tomorrow when cron run.
Thank you.

**Comment by Ferroin** [comment] 2021-01-20 14:20
> @Ferroin
> I'm really appreciate on all your help.
> I checked my `/etc/netdata/.environment`
> 
> This is content:
> 
> ```
> # Created by installer
> PATH="/usr/local/cpanel/3rdparty/lib/path-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/root/bin:/sbin:/opt/cpanel/composer/bin"
> CFLAGS="-O2"
> LDFLAGS=""
> NETDATA_PREFIX=""
> NETDATA_CONFIGURE_OPTIONS=""
> NETDATA_ADDED_TO_GROUPS=" adm nobody"
> INSTALL_UID="0"
> NETDATA_GROUP="netdata"
> REINSTALL_OPTIONS="--auto-update --stable-channel "
> RELEASE_CHANNEL="stable"
> IS_NETDATA_STATIC_BINARY="no"
> NETDATA_LIB_DIR="/var/lib/netdata"
> ```
> 
> I just set:
> `NETDATA_TMPDIR="/opt"`
> 
> I hope that will be enough. We will see tomorrow when cron run.
> Thank you.

It _should_ be enough provided that the code in the updater to actually use that path is working correctly. It looks like you found a bug in the code that’s supposed to actually _set_ the value in that file though.

**Comment by kozicpetar** [comment] 2021-01-21 11:08
@Ferroin 
wont' work.
Same error from cron:

```
/etc/cron.daily/netdata-updater:

/etc/cron.daily/netdata-updater: line 87: /tmp/netdata-test.Y9yrNC08gb: Permission denied
```

When I login to server I can see cariable is there:

```
echo $TMPDIR

/opt
```

File `/etc/netdata/.environment`
have line
`NETDATA_TMPDIR="/opt"`

I don't know what happen. I don't understand, really.

**Comment by jamesnr** [comment] 2021-01-24 12:58
@Ferroin, I've performed an uninstall, I did have to create a basic ./environment file. Re-installed and I'm stuck with the same version, ie it's not updated. I've also waited overnight for an overnight update to occur, just in case. Still no joy. Any ideas? The new install does seem to have a complete ./environment file now.

**Comment by jamesnr** [comment] 2021-02-05 17:20
@Forrrin, Apologies to ask again, only because it's been nearly 2 weeks, do you have any ideas? Are there any key files that, after an uninstall, I can check are removed, to ensure there is a full clean install? Thank you.

**Comment by Ferroin** [comment] 2021-02-08 12:26
Apologies for the long delay on getting back with you on this.

---

@jamesnr Unfortunately there’s no master list of files that you can check to verify that an uninstall was completed without anything left. The big things to look for are a `netdata` binary in `$PATH` (or under `/opt/netdata/bin` if you installed there), a `.environment` file in `/etc/netdata`, and a copy of the updater script in `/etc/cron.daily` or `/etc/periodic/daily`.

Can you confirm though whether you are still seeing a commit hash instead of an actual version number, and possibly post the output of `netdata -V`?

---

@kozicpetar Can you confirm that you are indeed still seeing the temporary directory errors?

**Comment by kozicpetar** [comment] 2021-02-08 12:27
@Ferroin yes, I confirm, everyday same error, I don't have idea.

**Comment by Ferroin** [comment] 2021-02-08 13:02
@petarkozic Probably a result of the same root cause as #10606. Working on a PR to fix that right now (and somewhat embarrassed that I did not notice it myself...).

**Comment by jamesnr** [comment] 2021-02-08 14:05
Thanks @Ferroin! I will try an uninstall again and check the files etc.

**Comment by kozicpetar** [comment] 2021-03-23 08:27
Hi @Ferroin, do you have some info when we can expect this fix will be merged?

**Comment by kozicpetar** [comment] 2021-03-24 08:57
@Ferroin 
thank you very much. After merging PR, update works well on all my WHM servers. 

Note:
Must to be exported TMPDIR in environment, updater will not work without that.

**Comment by stelfrag** [comment] 2021-07-09 06:32
Closing this after several updates to the updater (and recommended workarounds)

**Closed by stelfrag** 2021-07-09 06:32 UTC
Labels: bug, question
