### ISSUE TITLE
kickstart.sh hangs (without controlling terminal?)

### ISSUE THREAD

**Issue by MichaelRiss** [netdata/netdata#9588] opened 2020-07-22 14:43 UTC
##### Bug report summary

We are running `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait` on our Fedora 31/32 machines with the ansible shell module to install and update netdata. Currently, updates this way don't work anymore; the ansible shell module hangs for a long time (30 min++, timeout?) without any activity.

Doing manual tests I found out that running
```
# bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait
```
works, but
```
# nohup bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait
```
does not work and hangs similar to the ansible shell module. Using the last version of kickstart.sh from https://github.com/netdata/netdata/commit/57c916530c7ce9b7ca7905bfc06d676d34dd2f76 on Jun 2, it *does* also work with nohup. So it seems the latest change did introduce something that requires a controlling terminal. 
Looking at the `nohup.out` file during the moment the installer script hangs, shows:
```
 --- Found existing install of Netdata under: / --- 
 --- Attempting to update existing install instead of creating a new one --- 
[/root]# //usr/libexec/netdata/netdata-updater.sh
```
So, probably the hang occurs in `/usr/libexec/netdata/netdata-updater.sh` - and the latest change introduced calls to this script.

##### OS / Environment

```
# uname -a; grep -Hv "^#" /etc/*release
Linux XXX 5.7.9-100.fc31.x86_64 #1 SMP Fri Jul 17 17:18:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/fedora-release:Fedora release 31 (Thirty One)
/etc/os-release:NAME=Fedora
/etc/os-release:VERSION="31 (Thirty One)"
/etc/os-release:ID=fedora
/etc/os-release:VERSION_ID=31
/etc/os-release:VERSION_CODENAME=""
/etc/os-release:PLATFORM_ID="platform:f31"
/etc/os-release:PRETTY_NAME="Fedora 31 (Thirty One)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:LOGO=fedora-logo-icon
/etc/os-release:CPE_NAME="cpe:/o:fedoraproject:fedora:31"
/etc/os-release:HOME_URL="https://fedoraproject.org/"
/etc/os-release:DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
/etc/os-release:SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Fedora"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=31
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Fedora"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION=31
/etc/os-release:PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
/etc/redhat-release:Fedora release 31 (Thirty One)
/etc/system-release:Fedora release 31 (Thirty One)
```

##### Netdata version

 netdata v1.23.2-40-nightly

##### Component Name

packaging/installer
##### Steps To Reproduce

1. have netdata already installed on the system, the bug only affects updates!
2. `# bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait` works as expected
3. `# nohup bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait` currently hangs

##### Expected behavior

The installation script should not hang for updates, even when started without controlling terminal.

**Comment by Ferroin** [comment] 2020-07-22 15:59
Probable culprit is #9408, and I'm fairly certain looking back at the diff that I now what's wrong. I should have a PR up later today with a potential fix.

**Comment by MichaelRiss** [comment] 2020-07-22 16:02
sounds good, thanks for looking into it!

**Comment by Ferroin** [comment] 2020-07-22 16:06
OK, confirmed, the issue is that our updater script has a random delay to avoid a stampede effect from automatic updates, but I forgot when writing #9408 to set things up to disable that delay when called from `kickstart.sh`. I need to do a little bit more testing, but can guarantee that I'll have a PR for this today, and it should be fixed in the nightlies either tonight or tomorrow.

However, because we use the updater script from the existing install, you'll have to update any existing installs once the fix is released before you'll see it's effects.

**Comment by MichaelRiss** [comment] 2020-07-22 16:09
I understand. Currently I do a manual uninstall anyway to get the ansible playbook to work. So, this should suffice until the fix propagates through.

**Closed** 2020-07-23 11:14 UTC
Labels: area/packaging, bug
