### ISSUE TITLE
[Bug]: cannot install on OL9 - "Status code: 404 for https://repo.netdata.cloud/repos/edge/ol/9/x86_64/repodata/098735c218f242ed95b81aea7b9443d3d7a56a9850cb1bd9cacf23f659f9fd47-filelists.xml.gz (IP: 172.67.72.170)"

### ISSUE THREAD

**Issue by mailinglists35** [netdata/netdata#15107] opened 2023-05-28 01:14 UTC
### Bug description

download servers return 404 when downloading stuff

### Expected behavior

download servers return the requested files

### Steps to reproduce

````
$ LD_PRELOAD=/usr/lib64/nosync/nosync.so sudo -E dnf install https://repo.netdata.cloud/repos/edge/ol/9/x86_64/netdata-repo-edge-2-1.noarch.rpm
Last metadata expiration check: 1:23:14 ago on Sun 28 May 2023 02:45:35 AM EEST.
netdata-repo-edge-2-1.noarch.rpm                                                                                               127 kB/s | 7.0 kB     00:00
Dependencies resolved.
===============================================================================================================================================================
 Package                                      Architecture                      Version                          Repository                               Size
===============================================================================================================================================================
Installing:
 netdata-repo-edge                            noarch                            2-1                              @commandline                            7.0 k

Transaction Summary
===============================================================================================================================================================
Install  1 Package

Total size: 7.0 k
Installed size: 548
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                       1/1
  Installing       : netdata-repo-edge-2-1.noarch                                                                                                          1/1
  Verifying        : netdata-repo-edge-2-1.noarch                                                                                                          1/1

Installed:
  netdata-repo-edge-2-1.noarch

Complete!
````

````
$ sudo dnf  list available netdata
Netdata Edge                                                                                                                    77  B/s |  18  B     00:00
Errors during downloading metadata for repository 'netdata-edge':
  - Status code: 404 for https://repo.netdata.cloud/repos/edge/ol/9/x86_64/repodata/098735c218f242ed95b81aea7b9443d3d7a56a9850cb1bd9cacf23f659f9fd47-filelists.xml.gz (IP: 172.67.72.170)
  - Status code: 404 for https://repo.netdata.cloud/repos/edge/ol/9/x86_64/repodata/491d3a162382bd7447036c062d61056c432c3d671e9b6e0b335ef86242bea63e-primary.xml.gz (IP: 172.67.72.170)
Error: Failed to download metadata for repo 'netdata-edge': Yum repo downloading error: Downloading error(s): repodata/491d3a162382bd7447036c062d61056c432c3d671e9b6e0b335ef86242bea63e-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/098735c218f242ed95b81aea7b9443d3d7a56a9850cb1bd9cacf23f659f9fd47-filelists.xml.gz - Cannot download, all mirrors were already tried without success
````

### Installation method

manual setup of official DEB/RPM packages

### System info

```shell
$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux gen8 5.15.0-101.103.2.1.el9uek.x86_64 #2 SMP Tue May 2 01:10:45 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/oracle-release:Oracle Linux Server release 9.2
/etc/os-release:NAME="Oracle Linux Server"
/etc/os-release:VERSION="9.2"
/etc/os-release:ID="ol"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="9.2"
/etc/os-release:PLATFORM_ID="platform:el9"
/etc/os-release:PRETTY_NAME="Oracle Linux Server 9.2"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:oracle:linux:9:2:server"
/etc/os-release:
/etc/os-release:ORACLE_BUGZILLA_PRODUCT="Oracle Linux 9"
/etc/os-release:ORACLE_BUGZILLA_PRODUCT_VERSION=9.2
/etc/os-release:ORACLE_SUPPORT_PRODUCT="Oracle Linux"
/etc/os-release:ORACLE_SUPPORT_PRODUCT_VERSION=9.2
/etc/redhat-release:Red Hat Enterprise Linux release 9.2 (Plow)
/etc/system-release:Oracle Linux Server release 9.2

$ uname -a; uname -K
Linux gen8 5.15.0-101.103.2.1.el9uek.x86_64 #2 SMP Tue May 2 01:10:45 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux
uname: invalid option -- 'K'
Try 'uname --help' for more information.

$ uname -a; sw_vers
Linux gen8 5.15.0-101.103.2.1.el9uek.x86_64 #2 SMP Tue May 2 01:10:45 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux
-bash: sw_vers: command not found
```

### Netdata build info

```shell
N/A
```

**Comment by mailinglists35** [comment] 2023-05-28 01:21
````
$ yumdownloader https://repo.netdata.cloud/repos/edge/ol/9/x86_64/netdata-1.39.0.69.nightly-1.el9.x86_64.rpm
Netdata Edge                                                                                                                   4.7 kB/s | 687  B     00:00
Netdata Edge                                                                                                                    48 kB/s | 2.4 kB     00:00
Importing GPG key 0x65F56346:
 Userid     : "Netdatabot <bot@netdata.cloud>"
 Fingerprint: 6588 FDD7 B147 21FE 7C31 15E6 F917 7B52 65F5 6346
 From       : https://repo.netdata.cloud/netdatabot.gpg.key
Is this ok [y/N]: y
Netdata Edge                                                                                                                    79  B/s |  18  B     00:00
Errors during downloading metadata for repository 'netdata-edge':
  - Status code: 404 for https://repo.netdata.cloud/repos/edge/ol/9/x86_64/repodata/098735c218f242ed95b81aea7b9443d3d7a56a9850cb1bd9cacf23f659f9fd47-filelists.xml.gz (IP: 104.26.8.141)
  - Status code: 404 for https://repo.netdata.cloud/repos/edge/ol/9/x86_64/repodata/491d3a162382bd7447036c062d61056c432c3d671e9b6e0b335ef86242bea63e-primary.xml.gz (IP: 104.26.8.141)
Error: Failed to download metadata for repo 'netdata-edge': Yum repo downloading error: Downloading error(s): repodata/491d3a162382bd7447036c062d61056c432c3d671e9b6e0b335ef86242bea63e-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/098735c218f242ed95b81aea7b9443d3d7a56a9850cb1bd9cacf23f659f9fd47-filelists.xml.gz - Cannot download, all mirrors were already tried without success
````

however...

````
$ curl -kJOL https://repo.netdata.cloud/repos/edge/ol/9/x86_64/netdata-1.39.0.69.nightly-1.el9.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39.6M  100 39.6M    0     0  22.1M      0  0:00:01  0:00:01 --:--:-- 22.1M
````

manually resolving deps, libuv and protobuf, then

````
$ LD_PRELOAD=/usr/lib64/nosync/nosync.so sudo -E dnf install ./netdata-1.39.0.69.nightly-1.el9.x86_64.rpm
Last metadata expiration check: 1:35:20 ago on Sun 28 May 2023 02:45:35 AM EEST.
Dependencies resolved.
===============================================================================================================================================================
 Package                          Architecture                    Version                                          Repository                             Size
===============================================================================================================================================================
Installing:
 netdata                          x86_64                          1.39.0.69.nightly-1.el9                          @commandline                           40 M

Transaction Summary
===============================================================================================================================================================
Install  1 Package

Total size: 40 M
Installed size: 178 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                       1/1
  Running scriptlet: netdata-1.39.0.69.nightly-1.el9.x86_64                                                                                                1/1
  Installing       : netdata-1.39.0.69.nightly-1.el9.x86_64                                                                                                1/1
  Running scriptlet: netdata-1.39.0.69.nightly-1.el9.x86_64                                                                                                1/1
Created symlink /etc/systemd/system/multi-user.target.wants/netdata.service → /usr/lib/systemd/system/netdata.service.

  Verifying        : netdata-1.39.0.69.nightly-1.el9.x86_64                                                                                                1/1

Installed:
  netdata-1.39.0.69.nightly-1.el9.x86_64

Complete!
````

**Comment by Ferroin** [comment] 2023-05-30 11:37
Likely related to #15092 (probably same root cause).

**Comment by Dim-P** [comment] 2023-06-27 17:36
Closing as this seems to be working fine now for both release channels. @mailinglists35 please let us know if you experience this issue again.

**Closed by Dim-P** 2023-06-27 17:36 UTC
Labels: bug, area/packaging
