### ISSUE TITLE
[Bug]: mysql check issues rendering apps.plugin faulty

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#13175] opened 2022-06-17 14:18 UTC
### Bug description

This issue is maybe related to [another mysql check issue with go plugin](https://github.com/netdata/netdata/issues/13317).

The installation has following configuration of go.d plugin:
```
# grep "yes" /etc/netdata/go.d.conf 
enabled: yes
  x509check: yes
  supervisord: yes
  filecheck: yes
  nginx: yes
  phpfpm: yes
  mysql: yes
  rabbitmq: yes
  redis: yes
  portcheck: yes
```

The issue happens on setup with mariadb-10.4.25 and mariadb-10.6.8-r1, buth run galera-26.4.10-r1. First one has heavy load (production), second has no load. Each nude has two instances of mariadb (haveing same version) running.
Symptoms are very same. Suddenly plugin stops collecting data from mysql. For both local instances in same time. No error message logged by netdata, no error logged by mariadb also. However, netdata triggers alarms about mysql status changed.
Also apps.plugin charts (all the groups, including "Applications", "User groups" and "Users") have gaps all the time (like every second data collection is failing). This also triggers false alerts.
In same time, TCP portcheck, redis, rabbitmq and other checks that are performed by go plugin have no issues, no false positives and so on.
Presence or absence of real mariadb issues doesn't affect the above mentioned problem. But all the above mentioned problems disappear (including gaps in apps.plugin charts) in case mysql check is disabled in go.d.conf file.
Notable fact: while mysql check is enabled, appl.plugin chart has gaps all the times, gaps are 50% of chart space: it looks like every second check is failing.
In same time, mysql-related charts have long lasting gaps of unpredictable size, 2 minutes to 3 hours, and alarm flapping time 2 minutes to 20 hours in same time.

### Expected behavior

It is expected that a) mysql check collects the data all the time and doesn't trigger false alarms and b) applications plugin collects all the data regardless of go.d plugin behavior.
The problem is also enforced by the fact that recent versions of netdata (1.34 and 1.35) seems to have no mysql check in python plugin anymore, thus there's no way to monitor it except of go.d plugin.

### Steps to reproduce

Install mariadb and enable mysql monitoring with go plugin

### Installation method

other

### System info

```shell
Linux 5.15.47-gentoo netdata/go.d.plugin#1 SMP Tue Jun 14 23:46:30 CEST 2022 x86_64 AMD EPYC 7451 24-Core Processor AuthenticAMD GNU/Linux
Gentoo Base System release 2.8
DISTRIB_ID="Gentoo"
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
VERSION_ID="2.8"
```

### Netdata build info

```shell
Version: netdata v1.35.1
Configure options:  '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--datarootdir=/usr/share' '--disable-dependency-tracking' '--disable-silent-rules' '--docdir=/usr/share/doc/netdata-1.35.1' '--htmldir=/usr/share/doc/netdata-1.35.1/html' '--libdir=/usr/lib64' '--localstatedir=/var' '--with-user=netdata' '--without-bundled-protobuf' '--disable-cloud' '--enable-jsonc' '--disable-plugin-cups' '--enable-dbengine' '--enable-plugin-nfacct' '--disable-plugin-freeipmi' '--disable-exporting-kinesis' '--enable-lto' '--disable-exporting-mongodb' '--disable-exporting-prometheus-remote-write' '--disable-plugin-xenstat' '--enable-x86-sse' '--with-zlib' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CFLAGS=-march=native -O2 -pipe' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'CXXFLAGS=-march=native -O2 -pipe' 'PKG_CONFIG_PATH=/var/tmp/portage/net-analyzer/netdata-1.35.1/temp/python3.10/pkgconfig'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO (by user request)
    ACLK Next Generation:       NO
    ACLK-NG New Cloud Protocol: NO
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

* Netdata is installed with portage (gentoo ebuild)
* one instance of same netdata and sortware configuration (but having 32GB RAM instead of 256GB and 500 times smaller mariadb database size) has no above mentioned problem.
* Thus bug can also be seen on Linux kernel having version 5.10.120 and 5.15.47, other kernels not tested.
This but is related to go plugin and is present on Netdata versions 1.32.1 - 1.35.1.
Go.d.plugin version used is 0.31.2 everywhere.
* It was also noticed that one installation has had netdata log flooded with messages like
```
2022-06-13 12:30:42: apps.plugin ERROR : MAIN : heartbeat missed 2000000 monotonic microseconds
2022-06-13 12:30:45: apps.plugin ERROR : MAIN : heartbeat missed 2000000 monotonic microseconds
2022-06-13 12:30:48: apps.plugin ERROR : MAIN : heartbeat missed 2000000 monotonic microseconds
2022-06-13 12:30:51: apps.plugin ERROR : MAIN : heartbeat missed 2000000 monotonic microseconds
```
However, another installation has very same problems but without these lines logged.

**Comment by ilyam8** [comment] 2022-06-17 15:22
Hi, @ekexcello. Do you have `requested a SET to dimension with id` lines in error.log? Can you check?

**Comment by ilyam8** [comment] 2022-06-17 15:48
Every time such an event occurs Netdata would disable go.d.plugin. We fixed it in https://github.com/netdata/go.d.plugin/pull/689 (but haven't released the new go.d.plugin since then).

Any change you can build go.d.plugin from the master branch, replace go.d.plugin in plugins.d and see if it helps?

**Comment by ekexcello** [comment] 2022-06-17 15:58
Will try to rebuild go plugin from master branch and let you know, thank you!

**Comment by ekexcello** [comment] 2022-06-18 19:50
Hello @[ilyam8](https://github.com/ilyam8),
Unfortunately, even with fixes from master the issue is present.

**Comment by ilyam8** [comment] 2022-06-18 20:01
Can you do a [shapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) while there are problems with rendering and send it to `ilya@netdata.cloud`?

**Comment by ekexcello** [comment] 2022-07-11 19:33
Sorry to say, @ilyam8, but last days the issue is not visible.
There were several system updates (but not kernel) in mean time, also netdata was updated. 
Current running versions are netdata-1.35.1 and go-plugin 0.33.0.
Can I ask you to keep this bug open for the case the issue appears again? If it will not appear within 2-3 months, let's consider it might be reasonable to consider it gone, as for now it's not clear why this issue appeared and what caused it.

**Comment by ilyam8** [comment] 2022-07-11 20:28
@ekexcello thanks for the info. I am going to close the issue but will reopen it if needed. No need to keep it open if you can't reproduce it.

**Closed** 2022-07-11 20:29 UTC
Labels: bug, area/collectors, Cannot reproduce, collectors/go.d
