### ISSUE TITLE
netdata/packaging: Replace LXC with docker in packaging CI infrastructure

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6742] opened 2019-08-30 06:18 UTC
##### Feature idea summary
Selecting LXC was a choice based on a few criteria that seemed to make sense back when we were designing the whole thing. We wanted the advantage of having systemd capability and a more real world looking like containerized environment. In practise we faced the problem of not having the distributions we needed in LXC containers, plus the whole concept proved to be poor in design for the python library we have been using, resulting in endless hacks and tricks to get the job done.  

Since we will be soon moving to new infrastructure anyway, it is vital that we first migrate our current set up to run within docker containers that will significantly simplify our lives and in the same time allow us to get seemless migration to any CI infrastructure we want.

##### Expected behavior
Netdata packaging code runs on docker

**Comment by knatsakis** [comment] 2020-01-16 11:42
Duplicate of #7346?

**Comment by Ferroin** [comment] 2020-01-16 12:56
No, #7346 is a dupe of this, somehow I missed this one when I opened it.

**Comment by cosmix** [comment] 2020-01-22 20:15
Closing this one as #7346 is already in progress.

**Closed by cosmix** 2020-01-22 20:15 UTC
Labels: area/packaging, feature request
