### ISSUE TITLE
netdata-updater broke

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#5529] opened 2019-03-01 09:40 UTC
##### Bug report summary

On one of my systems I received this:

```
/etc/cron.daily/netdata-updater:
http://: Invalid host name.
http://: Invalid host name.
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
Fri Mar  1 06:32:56 EET 2019 : ERROR:  FAILED TO UPDATE NETDATA : Tarball checksum validation failed. Stopping netdata upgrade and leaving tarball in /tmp/netdata-updater-5Z9ZO0
run-parts: /etc/cron.daily/netdata-updater exited with return code 1
```

##### OS / Environment

```sh
# cat /etc/os-release
PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="December 2018"
VERSION_ID="2018.12-1"
ID=osmc
ID_LIKE=debian

ANSI_COLOR="1;31"
HOME_URL="https://www.osmc.tv"
SUPPORT_URL="https://www.osmc.tv"
BUG_REPORT_URL="https://www.osmc.tv"
```

```sh
# uname -a 
Linux jasontv 4.14.78-4-osmc #1 SMP PREEMPT Wed Dec 12 17:58:11 UTC 2018 armv7l GNU/Linux
```

##### Netdata version (ouput of `netdata -V`)

```
# netdata -V
netdata v1.12.2-2-g54dae3f2
```

##### Component Name

updater

##### Steps To Reproduce

```sh
# /etc/cron.daily/netdata-updater 
Fri Mar  1 11:39:53 EET 2019 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
http://: Invalid host name.
http://: Invalid host name.
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
Fri Mar  1 11:39:53 EET 2019 : ERROR:  FAILED TO UPDATE NETDATA : Tarball checksum validation failed. Stopping netdata upgrade and leaving tarball in /tmp/netdata-updater-IPxh4X
```

```
# ls -l /tmp/netdata-updater-IPxh4X
total 0
-rw-r--r-- 1 root root 0 Mar  1 11:39 netdata-latest.tar.gz
-rw-r--r-- 1 root root 0 Mar  1 11:39 sha256sum.txt
```

##### Expected behavior

update netdata to latest version

**Comment by ktsaou** [comment] 2019-03-01 09:43
also:

```sh
# cat /etc/netdata/.environment 
# Created by installer
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/osmc/bin:/opt/vc/bin"
CFLAGS="-O2"
NETDATA_PREFIX=""
NETDATA_CONFIGURE_OPTIONS=""
NETDATA_ADDED_TO_GROUPS=" adm proxy"
INSTALL_UID="0"
REINSTALL_COMMAND="./netdata-installer.sh "
RELEASE_CHANNEL="nightly"
# This value is meant to be populated by autoupdater (if enabled)
NETDATA_TARBALL_CHECKSUM="new_installation"
```

**Comment by ktsaou** [comment] 2019-03-01 09:47
And:

```sh
# bash -x /etc/cron.daily/netdata-updater 
+ : /etc/netdata/.environment
+ source /etc/netdata/.environment
++ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/osmc/bin:/opt/vc/bin
++ CFLAGS=-O2
++ NETDATA_PREFIX=
++ NETDATA_CONFIGURE_OPTIONS=
++ NETDATA_ADDED_TO_GROUPS=' adm proxy'
++ INSTALL_UID=0
++ REINSTALL_COMMAND='./netdata-installer.sh '
++ RELEASE_CHANNEL=nightly
++ NETDATA_TARBALL_CHECKSUM=new_installation
++ id -u
+ '[' 0 '!=' 0 ']'
++ pidof netdata
+ pids=
+ do_not_start=
+ '[' -n '' ']'
+ do_not_start=--dont-start-it
+ tmp=
+ '[' -t 2 ']'
+ exec
+ update
+ '[' -z '' ']'
+ info 'Running on a terminal - (this script also supports running headless from crontab)'
++ date
+ echo 'Fri Mar  1 11:46:15 EET 2019 : INFO: ' 'Running on a terminal - (this script also supports running headless from crontab)'
Fri Mar  1 11:46:15 EET 2019 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
+ grep -Eq '^[^ ]+ /tmp [^ ]+ ([^ ]*,)?noexec[, ]' /proc/mounts
+ pattern=/tmp/netdata-updater-XXXXXX
++ mktemp -d /tmp/netdata-updater-XXXXXX
+ dir=/tmp/netdata-updater-oqSO8o
+ cd /tmp/netdata-updater-oqSO8o
+ wget '' -O sha256sum.txt
http://: Invalid host name.
+ grep new_installation sha256sum.txt
+ wget '' -O netdata-latest.tar.gz
http://: Invalid host name.
+ sha256sum --check -
+ grep netdata-latest.tar.gz sha256sum.txt
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
+ failed 'Tarball checksum validation failed. Stopping netdata upgrade and leaving tarball in /tmp/netdata-updater-oqSO8o'
+ error 'FAILED TO UPDATE NETDATA : Tarball checksum validation failed. Stopping netdata upgrade and leaving tarball in /tmp/netdata-updater-oqSO8o'
++ date
+ echo 'Fri Mar  1 11:46:16 EET 2019 : ERROR: ' 'FAILED TO UPDATE NETDATA : Tarball checksum validation failed. Stopping netdata upgrade and leaving tarball in /tmp/netdata-updater-oqSO8o'
Fri Mar  1 11:46:16 EET 2019 : ERROR:  FAILED TO UPDATE NETDATA : Tarball checksum validation failed. Stopping netdata upgrade and leaving tarball in /tmp/netdata-updater-oqSO8o
+ '[' -n '' ']'
+ exit 1
```

Check that is says:

```
wget '' -O sha256sum.txt
wget '' -O netdata-latest.tar.gz
```

**Comment by ktsaou** [comment] 2019-03-01 09:49
So, somehow `NETDATA_TARBALL_CHECKSUM_URL` and `NETDATA_TARBALL_URL` are not defined.

**Comment by cakrit** [comment] 2019-03-01 09:49
You shouldn't have a netdata-updater in cron with the REINSTALL_COMMAND missing the `--auto-update` or `-u` option. I'm pretty sure that you have an old `netdata-updater` in `cron.daily`. Can you please call the installer with `-u` an run the updater again?

**Comment by ktsaou** [comment] 2019-03-01 09:51
Yes, `/etc/cron.daily/netdata-updater` is from Feb 1st.

**Comment by ktsaou** [comment] 2019-03-01 09:53
How did it work until today?

**Comment by ktsaou** [comment] 2019-03-01 09:53
It managed to update netdata for the last month...

**Comment by cakrit** [comment] 2019-03-01 09:54
So at some point an installer ran with the `--auto-update` option and at another point it was ran again without it. I think there's something we can be doing there, ensure that when the `--auto-update` option is not provided, we remove `netdata-updater` from cron. 

It worked until today because the latest installer no longer puts those two lines there. The updater that goes with that version of the installer knows not to expect them and looks for the RELEASE_CHANNEL instead.

**Comment by cakrit** [comment] 2019-03-01 09:55
But of course that new updater was not copied to cron.daily, since the installer was executed without the proper option.

**Comment by ktsaou** [comment] 2019-03-01 09:56
I think the updater:

1. should have defaults for the URLs or the CHANNEL is case they are missing
2. should always call the installer by appending `-u`

What do you think?

**Comment by cakrit** [comment] 2019-03-01 10:18
Without .environment it just won't work, there are more things we need there. But @paulfantom had the exact same idea as the second point, that will fix it.

**Comment by ktsaou** [comment] 2019-03-01 12:02
> Without .environment it just won't work, there are more things we need there

And what is the reason for not providing defaults in case it is missing?

**Comment by cakrit** [comment] 2019-03-01 12:52
> And what is the reason for not providing defaults in case it is missing?

Defaults can corrupt the user's installation. e.g. one of the parameters is `NETDATA_PREFIX`. We can't assume it is empty by default. 

Having that file there is the same as replacing a number of parameters in a `sh.in` script. In the [uninstall instructions](https://docs.netdata.cloud/packaging/installer/uninstall/) we ask the user to provide the two parameters needed by the uninstaller, in case `.environment` is not there.   For the updater, if the file was removed it's much easier for the user to run an installation via kickstart or netdata-installer with the appropriate options, to have it generated again with the proper parameters.

**Comment by ktsaou** [comment] 2019-03-01 18:32
We already modify the updater script: https://github.com/netdata/netdata/blob/c05954cf0537da81e24eb698fe0a60fa088848f5/packaging/installer/netdata-updater.sh#L116-L117

What changed, is that instead of modifying it via the makefiles, we now do it via the installer (which I think is not better, but anyway this is different story).

We could embed all the info we need there for providing sane defaults.

Actually instead of this: https://github.com/netdata/netdata/blob/c05954cf0537da81e24eb698fe0a60fa088848f5/netdata-installer.sh#L1025-L1034

We could embed the whole `.environment` in the updater as defaults, and still source it when it is available.

**Comment by paulkatsoulakis** [comment] 2019-03-12 23:25
Just a litte bit of a history checking on `netdata-installer.sh` and `netdata-updater.sh` scripts, seems that we removed `NETDATA_TARBALL_URL` and `NETDATA_TARBALL_CHECKSUM_URL` definitions from the installer with (https://github.com/netdata/netdata/commit/7a98b56ad9c5d708894189d1c95756f031991c60), which probably justifies why the problem popped up only recently.

I been torturing myself as to why did the problem suddenly popped up, i think this justifies it clearly.

As a next step, I tried to reproduce the problem with the latest code by doing various executions of netdata-installer and netdata-updater by alternating the auto-update flag and i could not find a way to fail the process, so with the latest code we should be okay.

I am not sure i understand how #5559 would fix the issue. Not to mention that the decided pattern, even adjusted can't be bullet proof from any future changes.

Why not simply re-instate the two variables creation inside the .environment that were removed from the installer, with the only difference that we can respect any existing definitions of the variables, the same way we do for other vars. Seems that should do the trick for the backwards compatibility, what you think?

**Comment by cakrit** [comment] 2019-03-13 08:36
> Why not simply re-instate the two variables creation inside the .environment that were removed from the installer, with the only difference that we can respect any existing definitions of the variables, the same way we do for other vars. Seems that should do the trick for the backwards compatibility, what you think?

The URLs depend on the channel and that has a default. The remaining question here is the scenario where for some reason the `.environment` file is missing, which won't be covered by adding the parameters back. @ktsaou is talking about more graceful handling of this scenario, for the updater and the uninstaller. There are many options here. The one we generally use is to have the necessary params updated in the scripts themselves. 

Do note that the uninstaller still needs to be added back to the installed files in #5290.

**Comment by paulkatsoulakis** [comment] 2019-03-13 11:49
> > Why not simply re-instate the two variables creation inside the .environment that were removed from the installer, with the only difference that we can respect any existing definitions of the variables, the same way we do for other vars. Seems that should do the trick for the backwards compatibility, what you think?
> 
> The URLs depend on the channel and that has a default. The remaining question here is the scenario where for some reason the `.environment` file is missing, which won't be covered by adding the parameters back. @ktsaou is talking about more graceful handling of this scenario, for the updater and the uninstaller. There are many options here. The one we generally use is to have the necessary params updated in the scripts themselves.
> 
> Do note that the uninstaller still needs to be added back to the installed files in #5290.

Ok i see, i will re-iterate and come back on this.

**Comment by paulkatsoulakis** [comment] 2019-04-12 09:44
I wasn't able to get a reproduce on this case.
I installed `netdata v1.12.2-2-g54dae3f2` on a clean docker image and tried to do various things like run the installer second time then update, directly update, use and don't use the auto-update flag and i could not get the updater fail.

@ktsaou any chance you can provide insights on how i can see the reproduce? It is likely we already fixed things in the latest version, so the updater can't break now, but i want to confirm it somehow that the issue is no longer reproducible

**Comment by paulkatsoulakis** [comment] 2019-04-12 09:55
I wasn't able to make the updater fail with or without  auto update option in the reinstall command variable inside /etc/netdata/.environment.

In the netdata-installer, we push the auto-update properly to reinstall command, so when the user runs the installer with auto-update, the flag will remain and the updater will keep it.

If by any reason the installer or the updater runs without the flag, makes sense to me that the flag needs to be removed from the environment.  Running the updater doesn't imply i want auto-update on.

I tried to run installer and updater with a few combinations of using and not using the auto-update flag and couldn't fail it.

@ktsaou @cakrit I am resolving this for now, but do let me know if you can help me get a reproduce of this.

**Closed by paulkatsoulakis** 2019-04-12 09:55 UTC
Labels: area/packaging, bug
