### ISSUE TITLE
Modernize dashboard.js

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#4462] opened 2018-10-22 13:59 UTC
We should perform a mild cleanup of dashboard.js, mostly updating the code to leverage modern (ES6+) JavaScript features:

* const
* arrow functions
* class
* removal of C-like snake_case variable names

etc.

**Comment by paulfantom** [comment] 2018-10-22 14:55
Closing as a duplicate of #4461

**Closed by paulfantom** 2018-10-22 14:55 UTC
Labels: duplicate
