### ISSUE TITLE
FAILED build in FreeBSD 12.1 -> Solution alternative (netdata cloud service now works)

### ISSUE THREAD

**Issue by thoggs** [netdata/netdata#9054] opened 2020-05-15 02:49 UTC
Hi,
I encountered a problem when trying to install FreeBSD 12.1 RELEASE; during the construction process, watching the Netdata 1.22.1 installation script returned error:

**1 -> FAILED, the cmake, needed to compile libwebsockets, could not be found.**

**Solution to the problem:**
I installed the cmake via pkg.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
**OS:** FeeBSD 12.1 RELEASE, without debug kernel and lib32
**Netdata version:** 1.22.1

**Comment by Ferroin** [comment] 2020-05-15 14:52
Was this with the FreeBSD Port of Netdata, or our official installer (`kickstart.sh` or `netdata-installer.sh`)?

**Comment by thoggs** [comment] 2020-05-15 16:19
It happened with the Netdata installer (netdata-installer.sh).

Ports/pkg versions are out of date.

**Comment by thoggs** [comment] 2020-05-15 16:20
> Isso aconteceu com o FreeBSD Port of Netdata, ou com o nosso instalador oficial ( `kickstart.sh`ou `netdata-installer.sh`)?

It happened with the Netdata installer (netdata-installer.sh).
Ports/pkg versions are out of date.

**Comment by thiagoftsm** [comment] 2020-05-15 16:36
> Obrigado pela informação adicional @thoggs ! :)

I already communicated the BSD team about the latest version.

**Comment by thoggs** [comment] 2020-05-15 16:44
> > Obrigado pela informação adicional @thoggs ! :)
> 
> I already communicated the BSD team about the latest version.

Thank you!
Netdata is such an interesting project that there is no way not to help the project...

**Comment by thiagoftsm** [comment] 2020-05-15 17:10
We are glad to read words like yours, and of course, in my case I am also glad to read words like these ( "Isso aconteceu com o FreeBSD Port of Netdata, ou com o nosso instalador oficial" ) :D

**Comment by Ferroin** [comment] 2020-05-15 18:25
> > Isso aconteceu com o FreeBSD Port of Netdata, ou com o nosso instalador oficial ( `kickstart.sh`ou `netdata-installer.sh`)?
> 
> It happened with the Netdata installer (netdata-installer.sh).
> Ports/pkg versions are out of date.

OK, then unfortunately this is expected. Our installer currently doesn't have support for pulling in dependencies on FreeBSD. Progress on that can be tracked in #8130, though it's low priority at the moment as our SRE team (who are also responsible for our packaging/installer code) is abnormally busy at the moment due to the Netdata Cloud release.

**Comment by Ferroin** [comment] 2020-05-15 18:27
Closing this as a duplicate of #8130.

**Closed by Ferroin** 2020-05-15 18:27 UTC
Labels: bug, needs triage
