### ISSUE TITLE
Cannot access with IP: 19999 after installation，Access to file is not permitted: ***

### ISSUE THREAD

**Issue by admlke** [netdata/netdata#8015] opened 2020-02-10 08:05 UTC
##### Question summary
Cannot access with IP: 19999 after installation，Access to file is not permitted: /usr/share/netdata/web//index.html
##### OS / Environment
centos 7
##### Component Name
netdata v1.13.0
##### Expected results
![image](https://user-images.githubusercontent.com/24238594/74131350-151ada80-4c1f-11ea-9af4-0e7cda223406.png)

**Comment by ilyam8** [comment] 2020-02-10 08:57
hi @admlke 

How did you install it?

> netdata v1.13.0

1.13.0 is pretty old, we are about to release 1.20.0

**Comment by admlke** [comment] 2020-02-10 09:25
> hi @admlke
> 
> How did you install it?
> 
> > netdata v1.13.0
> 
> 1.13.0 is pretty old, we are about to release 1.20.0

Thank you. I have reinstalled v1.19.0

**Comment by ilyam8** [comment] 2020-02-10 09:28
Did it solve the problem?

**Comment by href** [comment] 2020-02-25 11:03
I have the same issue with the latest DEB from stable (1.20.0). To fix it I had to do the following:

```
sudo chown netdata:netdata -R /usr/share/netdata
sudo chown netdata:netdata -R /var/lib/netdata/www
```

The files were owned by root and set to 0755 and 0644 respectively. I would assume that should still be good enough to at least read the files, but it's possible I'm missing something.

**Comment by prologic** [comment] 2020-02-25 22:30
cc @Ferroin As discussed this is somewhat related to #8083 and [this comment](https://github.com/netdata/netdata/issues/8083#issuecomment-586143208)

**Comment by ilyam8** [comment] 2020-02-26 07:45
same problem on macOS, just upgraded netdata to 1.20.0 view brew

**Comment by jn9999** [comment] 2020-03-31 12:18
> I have the same issue with the latest DEB from stable (1.20.0). To fix it I had to do the following:
> 
> ```
> sudo chown netdata:netdata -R /usr/share/netdata
> sudo chown netdata:netdata -R /var/lib/netdata/www
> ```
> 
> The files were owned by root and set to 0755 and 0644 respectively. I would assume that should still be good enough to at least read the files, but it's possible I'm missing something.

Another solution to the problem 

> File '/var/lib/netdata/www//index.html' is owned by user 0 (expected user 109). Access Denied.

is to add 
```
web files owner = root
web files group = netdata
```
in netdata.conf. Don't know what solution is preferred to fix this bug.

**Comment by SyntrophicConsortium** [comment] 2020-04-17 01:24
I'm having this problem too, running Manjaro Linux. It's strange because in netdata.conf "web files owner" is set to root, but to fix the problem, I had to change ownership to the netdata user.

**Comment by Ferroin** [comment] 2020-06-23 14:36
Apologies for the long delay on an official response to this.

When Netdata goes to read the files for the web UI, in addition to the regular permissions checks done by the OS, Netdata itself checks that the file ownership matches what is expected based on it's configuration, and refuses to serve them if they don't match.

The 'official' fix for this is to update `/etc/netdata.conf` (or the equivalent file in your installation) as suggested by @jn9999 earlier in the discussion here so that `web files owner` and `web files group` match the ownership of the files on your system.

**Closed by Ferroin** 2020-06-23 14:36 UTC
Labels: bug, needs triage

**Comment by prologic** [comment] 2020-06-24 04:41
> The 'official' fix for this is to update /etc/netdata.conf (or the equivalent file in your installation) as suggested by @jn9999 earlier in the discussion here so that web files owner and web files group match the ownership of the files on your system.

@joelhans Would you be able to update our "Troubleshooting" section with this? Basically if users run into permissions problems with accessing the Agent's local Dashboard that they should check the configured ownerships in the web section in the configuration and the ownership of the filfes and ensure they match and/or modify their configuration. Thanks!

**Comment by joelhans** [comment] 2020-06-24 15:10
@prologic Sure thing. You mean add it to this section on the install doc? https://learn.netdata.cloud/docs/agent/packaging/installer#installation-notes-and-known-issues

**Comment by prologic** [comment] 2020-06-25 07:16
Yes Please :)

**Comment by T-vK** [comment] 2021-01-13 12:28
This fixes it for me on Fedora 32:

``` bash
sudo chown -R root:netdata /usr/share/netdata
```

I did not have to run with `-u root` or make any changes to my config files.

**Comment by theY4Kman** [comment] 2021-03-09 20:06
I think I'm unable to download `kickstart.sh` and `kickstart-static64.sh` due to this :P

https://my-netdata.io/kickstart-static64.sh

![image](https://user-images.githubusercontent.com/33840/110531019-11d77400-80e9-11eb-86a8-0f1a3c64d84c.png)

**Comment by ilyam8** [comment] 2021-03-09 22:05
@theY4Kman the issue is https://github.com/netdata/netdata/issues/10744
