### ISSUE TITLE
Question: Does the "memory mode" setting enable local caching?

### ISSUE THREAD

**Issue by ddeimeke** [netdata/netdata#2540] opened 2017-07-31 06:04 UTC
We have a central netdata instance which collects data from all clients.

Clients are configured with "memory mode = none" in netdata.conf.

If the master (central node) breaks it starts collecting recent data once it is up again and we have a gap in the data.

Question: If we store the data locally would it transfer all missing data after the master (central) node is up again?

If this is not the case I like to open a feature request for this.

Thank you!

**Comment by ktsaou** [comment] 2017-07-31 06:24
Hi, it does not, so I flagged this as enhancement.

It should be relatively easy to do it. But netdata tries to detect if plugins or slaves stay behind reality and automatically adds gaps. So, the protocol needs to be extended a bit, to disable all these checks and allow streaming old data without gaps.

**Comment by ddeimeke** [comment] 2017-07-31 07:12
Great, Costa! Thank you!

**Comment by ktsaou** [comment] 2018-11-23 15:11
@cakrit 	yet another issue for fixing the streaming protocol to stream past metrics.
This is highly critical for IoT and quite handy for servers.
So, it is quite high in our priorities.

**Comment by cakrit** [comment] 2018-11-23 19:54
Duplicate of #2061

**Closed by cakrit** 2018-11-23 19:54 UTC
Labels: area/streaming, feature request, module/core
