### ISSUE TITLE
[Bug]: ERROR:  FAILED TO UPDATE NETDATA : You are running this script as user with uid 0. We recommend to run this script as root (user with uid 0)

### ISSUE THREAD

**Issue by EnesPalit** [netdata/netdata#12531] opened 2022-03-27 22:46 UTC
### Bug description

I got a problem while installing netdata but it was sorted in [12490](https://github.com/netdata/netdata/issues/12490)

Now after installing I wanted to Connect an agent running in Linux.

When I tried `wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token qi4792HvAVrb-g2orhhjuhu764OBz7yEnT7rPngJaNfN9VYmary_td_Qn8r7lF1778bPbv69-gn0CdH7IF9ulZFxSfxQkSH1ZJU14762awsdrftgyhjEE5BdnyHHg7EW7mNNWjwXQhI --claim-rooms ed1479ef-d7bb-656b-b51b-49e9541b247 --claim-url https://app.netdata.cloud`
I keep getting ` ERROR:  FAILED TO UPDATE NETDATA : You are running this script as user with uid 0. We recommend to run this script as root (user with uid 0)
 FAILED
 ABORTED  Failed to update existing Netdata install at /`

I tried it with the root user and with a normal user with sudo but I keep getting this error.

Any help would be appreciated!

### Expected behavior

That the agent is claimed

### Steps to reproduce

`wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token qi4792HvAVrb-g2orhhjuhu764OBz7yEnT7rPngJaNfN9VYmary_td_Qn8r7lF1778bPbv69-gn0CdH7IF9ulZFxSfxQkSH1ZJU14762awsdrftgyhjEE5BdnyHHg7EW7mNNWjwXQhI --claim-rooms ed1479ef-d7bb-656b-b51b-49e9541b247 --claim-url https://app.netdata.cloud`

### Installation method

kickstart.sh

### System info

```shell
Linux enespalitL1 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.33.1-236-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by ilyam8** [comment] 2022-03-28 05:13
Hi, @EnesPalit. This issue is a duplicate of #12525 (that I created yesterday).

**Closed by ilyam8** 2022-03-28 05:13 UTC
Labels: bug, duplicate, area/packaging
