### ISSUE TITLE
print() statements in python plugins make plugin disappear with no error messages.

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#8570] opened 2020-04-01 15:57 UTC
##### Bug report summary

It seems that if you leave a print() statement anywhere in a method inside python collector SimpleService object it causes the collector to disappear from the front end, but i dont see any error messages in the error log and the collector runs fine when i run it in debug mode. 

For example if i was to make a copy of the [example](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/example) python plugin and just add a print statement like [here](https://github.com/andrewm4894/netdata/blob/master/collectors/python.d.plugin/example2/example2.chart.py#L40) it seems to trigger this behaviour. 

##### OS / Environment

Place the output from the command in the code section below.  
 -->
```
Linux andrew-VirtualBox 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

netdata v1.20.0-401-gd0c01c52

 

##### Component Name

collectors/python.d.plugin

**Comment by ilyam8** [comment] 2020-04-01 16:08
`print` writes to stdout, netdata (plugins.d) reads stdout, see

> https://docs.netdata.cloud/collectors/plugins.d/#external-plugins-api

So it is expected. If you want to print something use logging (writes to stderr): self.error, self.warning, self.info, self.debug.

**Comment by ilyam8** [comment] 2020-04-01 16:26
@andrewm4894 i am closing it because it is not a bug

**Closed by ilyam8** 2020-04-01 16:26 UTC
Labels: area/external/python, question
