### ISSUE TITLE
/etc/netdata/edit-config charts.d.conf

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#5252] opened 2019-01-22 23:15 UTC
##### Question summary
Hello, attempting to add the UPS plugin, but when I try to run /etc/netdata/edit-config charts.d.conf I get the following message: 

```
[~]$ /etc/netdata/edit-config charts.d.conf
File 'charts.d.conf' is not found in '/usr/lib/netdata/conf.d'
```

I might be being an idiot here!
##### OS / Environment
Fedora
##### Component Name
charts.d.conf
##### Expected results
Expecting some form of config file to be able to be edited.

**Comment by ilyam8** [comment] 2019-01-23 06:51
what's your netdata version?

dupo of #5249, should be fixed in latest

**Comment by cakrit** [comment] 2019-01-23 12:57
This is a duplicate of #5136, which is fixed by #5244. Please check #5136 for the latest comment and a check regarding the netdata version that fixes it.

**Comment by cakrit** [comment] 2019-01-23 13:18
Fix verified in #5136. Please do the update, verify it yourself and close this as well.

**Comment by modem7** [comment] 2019-01-23 17:12
OK, attempted it again, still same error. 

![capture](https://user-images.githubusercontent.com/4349962/51624020-e9ed1c80-1f31-11e9-8026-c167d25220c1.JPG)

I also note the following during running bash <(curl -Ss https://my-netdata.io/kickstart.sh):

```
Version update check warning

The way you downloaded netdata, we cannot find its version. This means the
Update check on the dashboard, will not work.

If you want to have version update check, please re-install it
following the procedure in:

https://github.com/netdata/netdata/tree/master/installer#installation

```

**Comment by cakrit** [comment] 2019-01-23 17:56
Regarding the version warning, it was a  non-impacting bug. #5256 will fix it, along with the link to the docs site.

I don't get why you'd have the error though, you have the correct version. 
First, verify that you see the following in `/etc/netdata/edit-config`
```
[ -z "${NETDATA_USER_CONFIG_DIR}"  ] && NETDATA_USER_CONFIG_DIR="/etc/netdata"
[ -z "${NETDATA_STOCK_CONFIG_DIR}" ] && NETDATA_STOCK_CONFIG_DIR="/usr/lib/netdata/conf.d"
```
Then, please do  `ls -l` on both `/etc/netdata` and `/usr/lib/netdata/conf.d`

**Comment by modem7** [comment] 2019-01-23 18:00
Within /etc/netdata/edit-config:
```
fi

[ -z "${NETDATA_USER_CONFIG_DIR}"  ] && NETDATA_USER_CONFIG_DIR="/etc/netdata"
[ -z "${NETDATA_STOCK_CONFIG_DIR}" ] && NETDATA_STOCK_CONFIG_DIR="/usr/lib/netdata/conf.d"

if [ -z "${file}" ]
then
        cat <<USAGE
```
```
[~]$ ls -l /etc/netdata/
total 452
-rw-r----- 1 root netdata   9606 Dec  5 19:29 apps_groups.conf
drwxr-xr-x 2 root netdata     39 Jan 23 17:14 charts.d
-rwxr-xr-x 1 root netdata   2364 Jan 23 17:14 edit-config
drwxr-xr-x 2 root netdata     19 Jan 23 17:14 health.d
-rw-r----- 1 root netdata 444853 Dec  5 21:12 netdata.conf
drwxr-xr-x 2 root netdata     19 Jan 23 17:14 node.d
lrwxrwxrwx 1 root root        25 Jan 23 17:14 orig -> /usr/lib64/netdata/conf.d
drwxr-xr-x 2 root netdata     34 Jan 23 17:14 python.d
drwxr-xr-x 2 root netdata     19 Jan 23 17:14 statsd.d
```
```
[~]$ ls -l /usr/lib/netdata/conf.d
total 0
```
```
[~]$ ls -l /usr/lib/netdata/
total 0
drwxr-xr-x 2 root netdata 6 Dec  5 17:57 conf.d
```

**Comment by cakrit** [comment] 2019-01-24 08:19
The attempt to do autoconf centrally is behind this. For a workaround, make /usr/lib/netdata a symlink to /usr/lib64/netdata/

**Comment by cakrit** [comment] 2019-01-24 16:55
@paulfantom I believe that our problems are caused by the recent change that pulls the nightly build created with `.travis/create_artifacts.sh` instead of the source code. We end up doing `autoconf` , `configure` and `make` twice, once where travis runs (`make dist`) and once from within `netdata-installer.sh`. If I'm not mistaken, the problems will completely go away either if the first `make dist` does not actually save any information related to installation directories (e.g. in our .sh scripts), or if those scripts simply don't get generated at all from the first `make dist`.

**Comment by cakrit** [comment] 2019-01-24 18:41
I found out how/when we end up with `lib64`:

```
[root@localhost netdata-v1.12.0-rc3-28-gcec6d4d0]# cat /usr/share/config.site 
# This is the config.site file to satisfy FHS defaults when installing below
# /usr.
#
# You may override this file by your config.site using the CONFIG_SITE env
# variable.
#
# Note: This file includes also RHEL/Fedora fix for installing libraries into
# "/lib/lib64" on 64bit systems.

if test -n "$host"; then
    # skip when cross-compiling
    return 0
fi

if test "$prefix" = /usr \
   || { test "$prefix" = NONE && test "$ac_default_prefix" = /usr ; }
then
    test "$sysconfdir" = '${prefix}/etc' && sysconfdir=/etc
    test "$sharedstatedir" = '${prefix}/com' && sharedstatedir=/var
    test "$localstatedir" = '${prefix}/var' && localstatedir=/var

    ARCH=`uname -m`
    for i in x86_64 ppc64 s390x aarch64; do
        if test $ARCH = $i; then
            test "$libdir" = '${exec_prefix}/lib' && libdir='${exec_prefix}/lib64'
            break
        fi
    done
fi
```

**Comment by cakrit** [comment] 2019-01-24 19:03
The installer will always be running make clean before make in #5265. This will fix all issues with wrong paths.

**Closed** 2019-01-24 19:08 UTC
Labels: area/packaging, bug
