### ISSUE TITLE
Multiple metrics on the same graph

### ISSUE THREAD

**Issue by julsemaan** [netdata/netdata#3761] opened 2018-05-28 16:57 UTC
Hi,

I think this question was asked a few times but the resolution and path that was taken for it isn't exactly what we have in mind.

Basically, we would like to be able to show data from 2 different metrics (lets say the RAM usage and the swap usage) and combine them on the same graph without having to predeclare that metric on the server side.

Basically, we would like the frontend library to be able to combine the data from 2 different metrics on the same graph with 2 separate graph lines.

Is this possible in the current version of the library ?
Or otherwise, could you point me to the code that would need adjustments, we would likely attempt to patch it and then submit a PR here with that feature.

Thanks!

**Comment by ktsaou** [comment] 2018-06-10 21:22
> Is this possible in the current version of the library ?

unfortunately not. But I agree this is needed. netdata charts seem restricted / limited without it.

The code is in `dashboard.js`, but it will be somewhat complicated to do, as it would require a lot of tweaking.

In general the flow is like this:

1. dashboard.js calls `updateChart()`. This makes the ajax call to receive the chart in the format expected by the chart library.
2. once the data have been fetched `updateChart()` call `updateChartWithData()` which calls the chart library to draw the chart.

It will be tricky, because there are a lot metadata involved... But it would be a great accomplishment if you manage to do it.

**Comment by julsemaan** [comment] 2018-06-13 12:02
@ktsaou 

I'll give it a shot and see how far I can go

**Comment by julsemaan** [comment] 2018-11-23 12:18
@ktsaou 

I've submitted a PR (#3828) to fix this issue.

Any chance it can be merged ?

**Comment by ktsaou** [comment] 2018-11-23 12:49
@julsemaan 	sorry for the delay. A lot have happened in the last few months.
I think we will be able to proceed faster now.

@gmosx 	have a look at the PR #3828 
We need this - it is on our roadmap, and it is implemented.

**Comment by gmosx** [comment] 2018-12-18 07:50
I reapplied @julsemaan 's changes in PR #4983 - Needs review.

**Comment by cakrit** [comment] 2019-09-17 09:45
@jacekkolasa please check https://github.com/netdata/netdata/pull/4983 which hasn't been merged. We should implement this after the refactoring.

**Comment by cakrit** [comment] 2019-09-20 14:14
I'm closing #4983, the feature will be provided after the migration to React.js

**Comment by ilyam8** [comment] 2021-07-19 15:59
Duplicate of #2359

**Closed by ilyam8** 2021-07-19 15:59 UTC
Labels: area/web, feature request, priority/high
