### ISSUE TITLE
netdata-installer.sh is not honouring  --stable-channel, still install nightly version

### ISSUE THREAD

**Issue by ritzzbv** [netdata/netdata#8142] opened 2020-02-20 09:56 UTC
##### OS / Environment

```

```

##### Steps To Reproduce

1. run ./netdata-installer.sh --stable-channel

##### Expected behavior

Should install current stable release but install nightly release.

**Comment by prologic** [comment] 2020-03-17 04:03
@ritzzbv Apologies for the dealyed response, but this is intended behaviour and although maybe needs clearing up in the `./netdata-installer.sh --help` and the [docs](https://docs.netdata.cloud/packaging/installer/#nightly-vs-stable-releases).

I'm not sure we want to change this at this point as it makes for a more complicated `netdata-installer.sh`.

cc @Ferroin your thoughts?

**Comment by prologic** [comment] 2020-03-17 04:04
As shown `RELEASE_CHANNEL` and thus --release-channel` argument which is passed t othe installer from kickstart affects the NetData installer/updater environmenbt/configuration:

```sh
prologic@Jamess-iMac
Tue Mar 17 13:59:36
~/NetData/netdata
 (fix_8142) 0
$ sift 'if.*RELEASE_CHANNEL'
packaging/docker/build.sh:22:if [ "${RELEASE_CHANNEL}" != "nightly" ] && [ "${RELEASE_CHANNEL}" != "stable" ]; then
packaging/installer/netdata-updater.sh:100:  if [ "${RELEASE_CHANNEL}" == "stable" ]; then
.travis/create_artifacts.sh:34:if [ "${RELEASE_CHANNEL}" == stable ]; then
web/api/formatters/charts2json.c:26:                    if (!strcmp(procfile_lineword(ff, i, 0), "RELEASE_CHANNEL") && !strcmp(procfile_lineword(ff, i, 1), "stable")) {
```

It is only really used in the updater.

**Comment by prologic** [comment] 2020-03-17 04:05
If you want to install NetData in an offline environment see [Install NetData on offline systems](https://docs.netdata.cloud/packaging/installer/methods/offline/) which _could_ also be used to install specific versions of the agent as well (_since it installs from local files_).

**Comment by prologic** [comment] 2020-03-27 02:50
Closing this as wontfix. If this is incorrect, please reopen or file a new issue. Based on the information I provided above this is the intended behaviour.

**Closed by prologic** 2020-03-27 02:50 UTC
Labels: area/packaging, wontfix
