### ISSUE TITLE
Docker container show container id instead of name. ​

### ISSUE THREAD

**Issue by ilevac** [netdata/netdata#5112] opened 2019-01-03 22:31 UTC
##### Bug report summary
Docker container show container id instead of name.
I tried my own docker “monitoring container” and with the official netdata container.
In both it show only the container ID with a lot of error about cgroup in the error log.
The only container that work for me is : titpetric/netdata.

##### OS / Environment
Ubuntu 16.04 dockerised (phusion) and netdata official container.
​
##### Component Name
Cgroup

##### Steps To Reproduce
Install netdata in phusion ubuntu container.
Lauch the original netdata container.
​

##### Expected behavior
`
2019-01-03 04:21:04: cgroup-name.sh: WARNING: cannot find the name of docker container '8878e983d5a27bf6f11628025ec83226c0e24cfdf7270c6b4ab0285917e246a5'
2019-01-03 04:21:04: cgroup-name.sh: INFO: cgroup 'docker_8878e983d5a27bf6f11628025ec83226c0e24cfdf7270c6b4ab0285917e246a5' is called '8878e983d5a2'
2019-01-03 04:21:04: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : running: exec /usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/host/sys/fs/cgroup/cpu,cpuacct/docker/8878e983d5a27bf6f11628025ec83226c0e24cfdf7270c6b4ab0285917e246a5'
2019-01-03 04:21:04: cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/host/sys/fs/cgroup/cpu,cpuacct/docker/8878e983d5a27bf6f11628025ec83226c0e24cfdf7270c6b4ab0285917e246a5'
2019-01-03 04:21:04: cgroup-name.sh: WARNING: cannot find the name of docker container '016d0f6729b0a48db90c202bca7206ae9b167a470dea129fc04d2ae4f73ac11d'
2019-01-03 04:21:04: cgroup-name.sh: INFO: cgroup 'docker_016d0f6729b0a48db90c202bca7206ae9b167a470dea129fc04d2ae4f73ac11d' is called '016d0f6729b0'
2019-01-03 04:21:05: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : running: exec /usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/host/sys/fs/cgroup/cpu,cpuacct/docker/016d0f6729b0a48db90c202bca7206ae9b167a470dea129fc04d2ae4f73ac11d'
2019-01-03 04:21:05: cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/host/sys/fs/cgroup/cpu,cpuacct/docker/016d0f6729b0a48db90c202bca7206ae9b167a470dea129fc04d2ae4f73ac11d'
2019-01-03 04:21:05: /usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : Cannot find a cgroup PID from cgroup '/host/sys/fs/cgroup/cpu,cpuacct/docker/016d0f6729b0a48db90c202bca7206ae9b167a470dea129fc04d2ae4f73ac11d'
`

**Comment by paulfantom** [comment] 2019-01-04 00:07
Did you set `PGID` environment variable in a way described in docs: https://docs.netdata.cloud/packaging/docker/#docker-container-names-resolution ?

**Comment by ilevac** [comment] 2019-01-04 02:42
Yes, I add the PGID to to the run argument.

 Here’s the complete command.

  sudo docker run -d \
  -p 19999:19999 \
  -e PGID=999 \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \


Regards,
iLevac

**Comment by paulfantom** [comment] 2019-01-04 09:09
Are you sure that 999 is a docker group id?

**Comment by ilevac** [comment] 2019-01-04 13:23
Yes 

`
root@server:~$ grep docker /etc/group | cut -d ':' -f 3
999
`

**Comment by paulfantom** [comment] 2019-01-04 14:34
One more thing that is coming to my mind is that you might have an old netdata image on your host (solvable by executing `docker pull netdata/netdata` before running netdata container). Otherwise I have no idea what is going on, this mechanism was actually tested and developed on ubuntu 16.04 and it was working there. As for titpetric/netdata container, it is working because it is running netdata process as root inside a container.

**Comment by ilevac** [comment] 2019-01-04 18:07
I pull the new netdata/netdata image and that does the trick!
What is the difference in the images to have that fixed?
I'm now trying to make it work on my own container without a chance.
Any idea of what modif does it need?

**Comment by paulfantom** [comment] 2019-01-04 18:36
I don't know how your container looks like, but I would recommend to base it on netdata container (`FROM netdata`) and not create some other solution.

I am closing it as the issue is solved.

**Closed by paulfantom** 2019-01-04 18:36 UTC
Labels: bug, wontfix

**Comment by ilevac** [comment] 2019-01-04 19:33
Thank you for everything.
