### ISSUE TITLE
support statsd tags per collected value

### ISSUE THREAD

**Issue by username1366** [netdata/netdata#3813] opened 2018-06-12 11:14 UTC
I'm sending statsd metrics from my app to netdata statsd server and I want to pull this metrics with all app custom tags (e.g api_version, deployment, cluster-name, etc) from prometheus but in prometheus I don't see any of my statsd tags

Statsd metric with tags:
```
user.fc.fallback.timer.stddev:0|g|#api_version:2.0.1944,deployment:app,cluster-name:europe-central1,api_name:app
```

Prometheus metrics with omitted tags:
```
curl -s http://localhost:19999/api/v1/allmetrics?format=prometheus | grep user.fc.fallback.timer.stddev
netdata_statsd_gauge_user_fc_fallback_timer_stddev_gauge{chart="statsd_gauge_user.fc.fallback.timer.stddev",family="gauges"} 0 1528799565393
netdata_statsd_gauge_user_fc_fallback_timer_stddev_events_total{chart="statsd_gauge_user.fc.fallback.timer.stddev",family="gauges"} 0 1528799565393
```

Maybe It's ok and Should I need to adjust some config options to change this behavior?

**Comment by hauleth** [comment] 2018-06-21 23:40
The problem is that whole "tagging" isn't defined in stated format, it is extension added by DataDog I believe, but since then it became quite popular addition that would be enormously helpful in using Netdata as stats gatherer that would then dispatch them to DD or InfluxDB.

**Comment by ktsaou** [comment] 2018-06-22 00:17
nice request.
Can you point me to some documentation about statsd metric tags?

**Comment by hauleth** [comment] 2018-06-22 07:43
@ktsaou all I have found in form of documentation in that matter is [DataDog help article](https://help.datadoghq.com/hc/en-us/articles/206441345-Send-metrics-and-events-using-dogstatsd-and-the-shell).

Wire protocol is quite simple, it is just `metric#tag1:value1,tag2,tag3:value3`.

**Comment by ktsaou** [comment] 2018-06-22 09:41
And you expect these tags to be propagated to prometheus. Right?
I guess the tags are fixed, so a single metric will always have the same tags.
That is , you don't vary the tags between different values. Right?

**Comment by hauleth** [comment] 2018-06-22 09:57
@ktsaou you vary. I use it heavily to provide support for additional metadata, for example I store metric `phoenix.request.duration` in overall form and then in tags I store metadata like:

- response code
- controller
- action
- format (JSON/HTML)
- host

So then in Graphana/DataDog I can for example display list of the controllers that are taking most time to respond.

**Comment by ktsaou** [comment] 2018-06-22 10:08
hm... I see. So, this will have to wait a bit. We need to extend the internal structures of netdata to maintain this info per collected value.

**Comment by FedericoCeratto** [comment] 2019-07-03 13:14
Please keep the issue open. There aren't well-designed solutions to generate and manage application metrics. StatsD + tags + Netdata + Prometheus can become a good one.

**Comment by cakrit** [comment] 2019-07-03 15:50
It's definitely not getting closed, that `stale` comment shouldn't have been added in the first place.

**Comment by jeremyjpj0916** [comment] 2019-11-07 16:57
Agree the statsd tags will be good, the prometheus can see it...

So:
```
user.fc.fallback.timer.stddev:0|g|#api_version:2.0.1944
```

```
netdata_statsd_gauge_user_fc_fallback_timer_stddev_gauge{chart="statsd_gauge_user.fc.fallback.timer.stddev",family="gauges", api_version="2.0.1944"} 0 1528799565393
```

**Comment by jogster** [comment] 2019-11-23 11:58
Would love for tags to be a higher priority.

I started looking at how to add monitoring to my application and initially looked at statsd which i discarded initially due to the metrics 'dot' notation. I saw that Prometheus has solved this issue using key/value attributes. I was horrified when I looked at the prometheus client code  that I had to include in my app. I then went back to the simplicity of sending a string over a UDP packet. 

I found that AWS now also supports StatsD tags and converts them to dimensions.  Each dimension combination results in a new metric.

Having tags will allow much more flexible graphs to be created.

**Comment by vlvkobal** [comment] 2019-11-25 09:09
The issue is blocked by #6503 which is a high priority one.

**Comment by ilyam8** [comment] 2021-07-20 13:42
Closing this feature request. We will re-evaluate the request internally.

**Closed by ilyam8** 2021-07-20 13:42 UTC
Labels: area/collectors, data-collection-mteam, feature request, priority/low

**Comment by Rush** [comment] 2024-02-14 07:10
So 2 years later is tagging supported? I think replicating dogstatd behavior shouldn't be too hard
