### ISSUE TITLE
Netdata Debian repo doesn't support bullseye (testing)

### ISSUE THREAD

**Issue by Daniel15** [netdata/netdata#8882] opened 2020-05-03 06:45 UTC
##### Bug report summary
Ran:
```
curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.deb.sh | sudo bash
```

But when I run `apt update`, I get an error:
```
Err:4 https://packagecloud.io/netdata/netdata/debian bullseye Release
  404  Not Found [IP: 2600:1f1c:2e5:6901:786e:510b:4f4f:d29c 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/netdata/netdata/debian bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

##### OS / Environment
```
Linux ny03.d.sb 5.5.0-2-cloud-amd64 #1 SMP Debian 5.5.17-1 (2020-04-15) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux bullseye/sid"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"

```

##### Netdata version
N/A

##### Steps To Reproduce
1. Install Debian testing release
2. Add Netdata Debian repo:
```
curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.deb.sh | sudo bash
```
3. Run `apt update`

**Comment by Daniel15** [comment] 2020-05-03 06:46
Also, I just tried the Buster repo, but its packages don't work on Bullseye:
```
The following packages have unmet dependencies:
 netdata : Depends: libprotoc17 but it is not installable
           Depends: libprotobuf17 but it is not installable

```

**Comment by prologic** [comment] 2020-05-04 11:58
Yes Unfortunately we only build and publish packages for Debian jessie and Debian buster in our packagecloud repo at this time. I don't have a very good answer for you at this time, but I'll discuss with the team, we're unfortunately trying to refactor how we build and publish packages so we can support a much wider variety of systems. Stay tuned!

**Comment by prologic** [comment] 2020-05-04 11:58
cc @Ferroin

**Comment by redbaron-gt** [comment] 2020-07-12 20:11
Same problem with Ubuntu 20.04 LTS.

**Comment by NathanTheGr8** [comment] 2021-07-10 23:50
I think this issue still exists. I just preparing for an upgrade to Debian 11 and got the same error as Daniel15 .

**Comment by Daniel15** [comment] 2021-07-10 23:55
@prologic @roedie The Bullseye launch is coming very soon (the freeze is one week from now, and the final release should be at most a few weeks after that) so this would be good to fix. It seems like it's still an issue, based on the comment above.

**Comment by roedie** [comment] 2021-07-12 17:12
You cannot install the Buster version on Bullseye since libprotoc17 and libprotobuf17 are not available on these systems. That's just basic package management and not a bug. But, building on Bullseye most likely will work since during the build the version of libprotoc and libprotobuf which are available in Bullseye will be used. (Did not test yet, might do this later this week)

The Netdata team  just needs to enable the Bullseye builds and everything will be fine.

**Comment by NathanTheGr8** [comment] 2021-07-12 18:08
I was not trying to install the buster version on bullseye. I think daniel15 and I were both trying to install a native bullseye package and got the 404 error code. I understood that these meant the package didn’t exist, I am just surprised with the stable release only weeks away that Netdata had not added it. A bug report may be the wrong way to handle this however it was one of the first google search result left for Netdata bullseye package.

**Comment by roedie** [comment] 2021-07-12 19:49
It might be better to open up a new ticket with the request to build Bullseye packages.

**Comment by Ferroin** [comment] 2021-07-13 11:54
Do note however that there may be a delay in packages being available for Debian 11. We’re stuck with [Package Cloud](https://packagecloud.io/) for repository hosting right now (as much as I would love to switch to pretty much anything else), and they are not always quick about adding the relevant stuff to their API to support new releases of distros (it took multiple months from the release of Fedora 34 before we could publish Fedora 34 packages because of this).

**Comment by Daniel15** [comment] 2021-07-13 16:54
> It might be better to open up a new ticket with the request to build Bullseye packages.

@roedie That's what this issue was supposed to be :)



> We’re stuck with [Package Cloud](https://packagecloud.io/) for repository hosting right now (as much as I would love to switch to pretty much anything else),

@Ferroin Have you considered self-hosting a repo using Aptly? That's what I did for Yarn v1 (v2 and later are only on npm though).

**Comment by roedie** [comment] 2021-07-13 18:57
@Daniel15 Never mind me... somehow I missed the first message in this issue and thought this was about the buster package not installing on Bullseye.

**Comment by Ferroin** [comment] 2021-07-14 11:12
> @Ferroin Have you considered building your own repo using Aptly? That's what I did for Yarn v1 (v2 and later are only on npm though). A Debian repo is just plain files with no server-side code, so you can just upload them to any static web host (your own Apache/Nginx server or cluster, S3, Github Pages, Netlify, etc). For Yarn we just used Github Pages with a custom CNAME to host the repo.

Our plan long-term is to self-host all of our package repos as we’ve been rather dissatisfied with PackageCloud (long delays in support for new releases are actually the least of our complaints right now). The issue with getting this done now is more one of prioritization (there’s an ongoing overhaul of our installer and updater code to provide better integration between the different installation methods, and that’s been stated as the top priority right now) than difficulty of actually hosting things ourselves (and even the cost savings that would result haven’t been enough to convince upper management to prioritize it).

Of course, as of right now the issue is getting the packages to build correctly on Bullsye, something’s going wrong and the FreeIPMI plugin isn’t building at all for some reason.

**Comment by olivluca** [comment] 2021-08-16 10:46
I was going to upgrade a test machine from debian 10 to debian 11 but I see that there are still no packages for it, (I only checked for https://packagecloud.io/netdata/netdata/packages/debian/bullseye/netdata-repo_1-1_all.deb)

**Comment by Ferroin** [comment] 2021-08-16 11:55
@olivluca Yeah, we’re having issues getting them to build correctly in CI at the moment. I’m hoping to get the PR including all of CI related to Debian 11 merged some time today or tomorrow, but it may be a while before we have binary packages working correctly.

**Comment by Ferroin** [comment] 2021-08-18 13:11
OK, we’ve _finally_ got the CI and packaging working. Debian 11 packages should be available for nightly builds starting from tonight’s nightly and for stable builds starting from the next release.

**Closed** 2021-08-18 13:11 UTC
Labels: bug, area/packaging
