### ISSUE TITLE
[Bug]: Lost all historical data upgrading from 1.35 to 1.36

### ISSUE THREAD

**Issue by ced1check** [netdata/netdata#13548] opened 2022-08-11 07:36 UTC
### Bug description

After the upgrade to 1.36, all historical data are gone

### Expected behavior

Keep historical data as defined in configuration file.

### Steps to reproduce

1. Upgrade from 1.35 to 1.36

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment] 2022-08-22 08:20
@ced1check guess this is then a duplicate of https://github.com/netdata/netdata/issues/13186, right?
can we close this one?

**Comment by ced1check** [comment] 2022-08-22 08:30
Yes sorry for the dups.

**Closed** 2022-08-22 08:42 UTC
Labels: bug, needs triage
