### ISSUE TITLE
Secure data in transit without requiring Nginx or other additional tools

### ISSUE THREAD

**Issue by mikeweilgart** [netdata/netdata#3998] opened 2018-07-24 00:18 UTC
I found #2590 where @ktsaou wrote (11 months ago):

> I plan to add SSL to netdata (also support HTTPS natively) and convert the stream protocol to web sockets (so that it will be proxy friendly).

In the March bullet points for v1.10.0, I see:

> new web server, a lot faster and more secure

So I got my hopes up!  But no, it looks like data in transit is still in plaintext unless you tack on additional tools.

Since there is no other issue open with this request, here it is:

**Please add native support for TLS.**  :)

**Comment by mikeweilgart** [comment] 2018-07-24 00:19
(For readers wondering: [What's the difference between SSL, TLS, and HTTPS?](https://security.stackexchange.com/a/5127/96753))

**Comment by cakrit** [comment] 2019-04-01 16:46
Duplicate of #2637. We will use websockets for this communication, once we port the static threaded server to libuv.

**Closed by cakrit** 2019-04-01 16:46 UTC
Labels: area/daemon, duplicate, help wanted
