### ISSUE TITLE
Cannot enable netdata updater tool

### ISSUE THREAD

**Issue by Nirjonadda** [netdata/netdata#10035] opened 2020-10-06 13:50 UTC
How can enable netdata updater tool? I am using Automatic one-line installation script

`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

![ScreenShot00040](https://user-images.githubusercontent.com/6899856/95210182-84b38a80-07eb-11eb-8e88-c1c4e0b97893.png)

**Comment by ilyam8** [comment] 2020-10-06 13:55
Hi @Nirjonadda 

This is duplicate of https://github.com/netdata/netdata/issues/10025, fixed in https://github.com/netdata/netdata/pull/10028

**Closed** 2020-10-06 13:56 UTC
Labels: area/packaging, bug, duplicate, no changelog

**Comment by Nirjonadda** [comment] 2020-10-07 12:08
What version fixed this issue? Aldo does released fixed version?

**Comment by ilyam8** [comment] 2020-10-07 12:12
It is fixed in the master branch.

**Comment by Nirjonadda** [comment] 2020-10-07 12:13
So we need re-run `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` it again to update Netdata?

**Comment by ilyam8** [comment] 2020-10-07 12:16
I think yes.
