### ISSUE TITLE
vsphere display name is shortened

### ISSUE THREAD

**Issue by kmai007** [netdata/netdata#7808] opened 2020-01-21 16:16 UTC
##### Question summary
Is there a way to display the discovered host/vm name without it being shortened.
##### OS / Environment
rhel7, prod
##### Component Name
vsphere.conf
##### Expected results
from the vsphere discovery of hosts, we have names that start with kne.....plaza.com  It is well over 14 characters so the graphed display name is hidden from view.  Is there a way to have it fully displayed?

**Comment by kmai007** [comment] 2020-01-21 16:16
![2020-01-21 10_09_12-knentdald001 kiewitplaza com netdata dashboard](https://user-images.githubusercontent.com/28964522/72822082-1d42b400-3c37-11ea-8fcb-9754e0250443.png)

**Comment by ilyam8** [comment] 2020-01-21 16:21
@jacekkolasa please take a look

i recall we had same issue with `family` (subsection on the dashboard)

**Comment by ilyam8** [comment] 2020-01-21 16:23
> i recall we had same issue with family (subsection on the dashboard)

Oh, that is the issue we had here 🙈

**Comment by ilyam8** [comment] 2020-01-21 16:25
@kmai007 found

https://github.com/netdata/netdata/issues/6972

duplicate of https://github.com/netdata/netdata/issues/6972

**Closed by ilyam8** 2020-01-21 16:25 UTC
Labels: duplicate, no changelog, question
