### ISSUE TITLE
Disabling proc plugin causes snapshot save to report error

### ISSUE THREAD

**Issue by KickerTom** [netdata/netdata#10175] opened 2020-11-02 12:17 UTC
##### Bug report summary

When I disable _plugin:proc_ using _netdata.conf_ configuration and then try saving snapshot using the default dashboard,js, I receive an error that one graph failed to be saved.
This seems to be caused by this section in _index.html_ (starting line 124), hardcoding access to _system.intr_ data:

```
    <div id="masthead" style="display: none;">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h1>Netdata
                        <p class="lead">Real-time performance monitoring, in the greatest possible detail</p>
                    </h1>
                </div>
                <div class="col-md-5">
                    <div class="well well-lg">
                        <div class="row">
                        <div class="col-md-6">
                            <b>Drag</b> charts to pan.
                            <b>Shift + wheel</b> on them, to zoom in and out.
                            <b>Double-click</b> on them, to reset.
                            <b>Hover</b> on them too!
                            </div>
                        <div class="col-md-6">
                            <div class="netdata-container" data-netdata="system.intr" data-chart-library="dygraph" data-dygraph-theme="sparkline" data-dygraph-type="line" data-dygraph-strokewidth="3" data-dygraph-smooth="true" data-dygraph-highlightcirclesize="6" data-after="-90" data-height="60px" data-colors="#C66"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
```

For my use-case, I have commented out this section entirely, but that not a good generic solution. Any reason the system.intr reference is hardcoded here?

##### Netdata version
1.26.0, but present in master as well.

##### Component Name
web

##### Steps To Reproduce
1. Add this to netdata.conf:
```
[plugins]
proc = no

```
2. Restart netdata
3. Try exporting snapshot, you will receive error "1 failed to be downloaded".

**Comment by stelfrag** [comment] 2021-04-02 17:32
Hi @KickerTom 

Sorry it took so long to get back to you :disappointed:  I tried this is the latest master and the issue seems to be resolved. Could you please confirm so we can close this or investigate further if this doesn't work for you?

**Comment by KickerTom** [comment] 2021-04-06 16:17
I am sorry to bring the bad news :-), but it still fails for me. What I did:
- clean clone of master
- build (autoreconf -ivf; ./configure --prefix=/opt/netdata --localstatedir=/tmp/netdata --disable-ebpf --disable-cloud --enable-https=no --enable-dbengine=no; make)
- install (make install)
- copy example netdata.conf from system folder in sources, add the section disabling proc plugin
- start netdata, let it run for couple of seconds
- try exporting snapshot

What I got was red line in the dialog "1 charts have failed to be downloaded" and when the progress line is full, I get a popup saying "1 failed to be downloaded". Tested with Firefox and Chromium, both on Linux.

Let me know if you need anything else.

**Comment by ilyam8** [comment] 2021-04-06 16:34
@stelfrag i confirm the issue

> using the default dashboard,js

noticed that sentence and decided to check our old dashboard (`/old`)


<img width="1268" alt="Screenshot 2021-04-06 at 19 33 58" src="https://user-images.githubusercontent.com/22274335/113746473-09d21a80-970f-11eb-88f7-cc36ed03735f.png">

**Comment by stelfrag** [comment] 2021-04-06 17:38
Confirmed on the old dashboard .. thank you @KickerTom !

**Comment by stelfrag** [comment] 2021-04-06 17:39
@jacekkolasa can this be addressed?

**Comment by KickerTom** [comment] 2021-04-06 19:08
Just out of curiosity - I am using the default dashboard installed by _make install_. If this is "the old" dashboard, where is "the new" one, and why it is not the default one? :-)

**Comment by Ferroin** [comment] 2021-04-07 11:56
> Just out of curiosity - I am using the default dashboard installed by _make install_. If this is "the old" dashboard, where is "the new" one, and why it is not the default one? :-)

The ‘new’ one can be found at https://github.com/netdata/dashboard. The same code is also used as part of the Netdata Cloud UI, so it got split to a separate repo so it could be more easily shared in both places.

As of right now, it’s installed correctly by our install scripts `packaging/installer/kickstart.sh` and `netdata-installer.sh`), but not by a plain manual install with `make install`. The lack of `make install` support is honestly something we should fix though.

@jacekkolasa @stelfrag I think the cleanest way to actually handle the dashboard properly is to make it a submodule (given that we are now obviously allowing usage of them) and have it handled by existing build system instead of the installer. That would get us the proper up-to-date dashboard in our release tarballs, which would also mean that most third-party packages would have it as well, as well as allowing `make install` to properly install the current version of the dashboard.

**Comment by KickerTom** [comment] 2021-04-08 11:11
Hmm, more bad news :-). I just tried the new dashboard, and the problem is still there.
To make sure I haven't made anything stupid, I used the official release installation script (netdata-v1.30.0.gz.run). You need to make sure netdata does not start automatically at all after install. Then you modify configuration and disable the proc plugin, then you can start netdata and try exporting snapshot.
If you had proc plugin running in the past, or started during install, you need to clear your history data (by deleting the local db, caches etc). Otherwise even the old data in the db are enough to hide this problem.

**Comment by ilyam8** [comment] 2021-04-08 11:37
This is the case, i confirm.

**Comment by OdysLam** [comment] 2021-04-08 11:44
Thanks @KickerTom for helping us figure this out.

@stelfrag @jacekkolasa I second @Ferroin's proposal in the sense that we need to address this discrepancy if we really want to remove unnecessary friction from Netdata installation via different methods (e.g homebrew, distro packages, etc.)

**Comment by jacekkolasa** [comment] 2021-04-15 13:36
@KickerTom Indeed, there is a bug (on new Dashboard, too), your instructions are very accurate, thanks!
FTR it still allows using snapshots, the problem is only that annoying alert popup.

@Ferroin re: submodules we should also consult with @novykh and @netdata/cloud-fe , i like the idea.

**Comment by Ferroin** [comment] 2021-04-16 14:47
@jacekkolasa Do you want to set up a meeting to discuss this some time next week? The requirements for getting the dashboard integrated as a submodule are not exactly trivial, but should not be particularly difficult either, and it would be good to make sure everyone is on the same page about what would be needed before we start trying to decide if we want to do it or not.

**Comment by ilyam8** [comment] 2021-08-31 15:10
Issue moved to [netdata/dashboard #298](https://github.com/netdata/dashboard/issues/298) via [**ZenHub**](https://www.zenhub.com/)

**Closed by ilyam8** 2021-08-31 15:10 UTC
Labels: bug, area/web, needs triage
