### ISSUE TITLE
[Feat]: use "_" instead of " " in .conf files

### ISSUE THREAD

**Issue by andrewm4894** [netdata/netdata#14088] opened 2022-12-05 15:39 UTC
### Problem

It would be better to use "_" instead of " " in all netdata conf files for parameter names. This will make the conf files more easy to parse and handle programmatically.

feature request raised internally: https://netdata-cloud.slack.com/archives/CS3PB0VJ7/p1670242755967129

### Description

Instead of 

```
[some section]
  some param = yes
```

have

```
[some_section]
  some_param = yes
```

### Importance

nice to have

### Value proposition

1. clearer conf files and easier to handle/parse programatically.
2.
3.
...

### Proposed implementation

1. support "_" params.
2. ensure backward compatibility with existing " " params.
3. update default configs to use new "_" approach.

**Comment by ilyam8** [comment] 2022-12-05 15:46
In order to be parsable the conf files should use one of the well-known formats. At the moment some of the files (e.g. netdata.conf, apps_groups.conf, exporting.conf, stream.conf) have a custom (ini-like) format.

So 
> use "_" instead of " " in .conf files

by itself doesn't fix the problem. Should be a more general issue.

**Comment by andrewm4894** [comment] 2022-12-05 15:58
yep "_" does not fix the problem but would maybe be not too big of effort and would improve it a bit to at least make it a little more machine readable than currently.

or maybe the feature here should be to just use [INI](https://en.wikipedia.org/wiki/INI_file#:~:text=An%20INI%20file%20is%20a,sections%20that%20organize%20the%20properties.) globally and adopt convention of not using " " in param names. 

Chat GPT says you can use spaces but its not best practice :) 

![image](https://user-images.githubusercontent.com/2178292/205682979-6de11b9f-5c85-4c01-85fc-d28d84a5130f.png)

**Comment by ilyam8** [comment] 2022-12-05 16:05
> and would improve it a bit to at least make it a little more machine readable than currently.

My understanding is that it wouldn't because 
- if the parser fails to parse a file it doesn't matter what the problem is (underscores or some other thing). 
- if you write your custom parser (which you don't) then spaces/underscores are not a problem.

So it is either all (strictly follow some format) or nothing.

**Comment by Ferroin** [comment] 2022-12-05 18:16
I would personally vote for YAML here over INI if we’re unifying our config formats (and `-` instead of `_`, but I’m also a UNIX traditionalist in that I despise excess typing). We already favor it by simple count of files using it, it’s reasonably portably supported, has a solid C implementation that has zero external dependencies (https://github.com/yaml/libyaml), gets us support for include directives (this is _huge_ from a usability perspective), and lets us uses proper lists (again, huge from a usability perspective), among other benefits.

**Comment by darylblake** [comment] 2022-12-06 06:00
Yes use an underscore please. I am about to roll out kinesis and for some reason you have a word with a space in the name as the parameter.

**Comment by ilyam8** [comment] 2023-12-26 15:25
I think we decided to use YAML, it's not the number one priority right now, but it will be implemented. We are closing because switching to YAML solves the problem, and we are 100% not changing the existing parameters.

**Closed by ilyam8** 2023-12-26 15:25 UTC
Labels: feature request, needs triage
