### ISSUE TITLE
Export on alert

### ISSUE THREAD

**Issue by stevenhrabok** [netdata/netdata#6232] opened 2019-06-06 20:07 UTC
##### Feature idea summary
Requesting a configuration option to automate export of netdata snapshot when any warning/critical alerts occur to a storage destination (local filesystem/AWS S3 bucket/other providers). 

In some cases alarms cannot be responded to within the default retention window (~1 hour) and instead of increasing the duration or creating a centralized netdata solution having snapshots exported on alert to the cloud could be useful for triage after the fact.

I'm sure it may require some thresholds for excessive alerts.

Thanks again for a great tool.

##### Expected behavior

- Feature can be enabled with a specified storage provider, alert levels and thresholds in a config file.
- When alerts occur an export snapshot task is triggered
- Snapshot is transferred to the storage provider destination

**Comment by cakrit** [comment] 2019-06-07 08:13
Thanks @stevenhrabok. As this is almost (but not quite) a duplicate of  #3973, I will close it, but please go through it and put your additional ideas there. I'm sure the discussion will trigger some more thoughts too. It's definitely on our roadmap.

**Comment by cakrit** [comment] 2019-06-07 08:13
Oh, and thanks for your kind words! :)

**Closed by cakrit** 2019-06-07 08:13 UTC
Labels: duplicate, feature request
