### ISSUE TITLE
web_log plugin cannot handle high load traffic

### ISSUE THREAD

**Issue by alibo** [netdata/netdata#4354] opened 2018-10-04 08:56 UTC
As you can see in the screenshots, the `web_log` plugin cannot handle high load traffic (over 10k RPS) and its latency keeps go higher after several seconds. 

![screen_shot_2018-10-04_at_11_42_13](https://user-images.githubusercontent.com/5338482/46461413-821c9580-c7cb-11e8-88d8-c43b47fc9223.jpg)
![screen_shot_2018-10-04_at_11_41_19](https://user-images.githubusercontent.com/5338482/46461414-82b52c00-c7cb-11e8-85e7-17dc4adee3e5.jpg)

Also, it seems all python plugins (together) use only 1 cpu core:

![screen_shot_2018-10-04_at_11_47_50](https://user-images.githubusercontent.com/5338482/46461507-ad06e980-c7cb-11e8-9974-d74227d862e4.jpg)

When I read the `LogService.py` I realized there is no timeout for reading logs (please correct me if I'm worng):

```python
        try:
            if self.__re_find['current'] == self.__re_find['run']:
                self._find_recent_log_file()
            size = os.path.getsize(self.log_path)
            if size == self._last_position:
                self.__re_find['current'] += 1
                return list()  # return empty list if nothing has changed
            elif size < self._last_position:
                self._last_position = 0  # read from beginning if file has shrunk

            with open(self.log_path) as fp:
                fp.seek(self._last_position) # <- 2
                for line in fp:
                    lines.append(line)
                self._last_position = fp.tell() # <- 3
                self.__re_find['current'] = 0
# ...

    def create(self):
        # set cursor at last byte of log file
        self._last_position = os.path.getsize(self.log_path) # <- 1
        status = SimpleService.create(self)
        return status
```  

If I understand correctly:

1. First, it sets the `_last_position` to the end of the file.
2. Then in `_get_raw_data()` method, it reads the lines from the current position (read from `_last_position`) to the end of the file. 
3. Then it updates the `_last_position` by calling `fp.tell()`

The problem is if step 2 takes more than `update_every`, it couldn't update the `_last_position`. So, the next loop should be read the logs from the previous `_last_position` and the number of logs to read are almost doubled. So the next loops also take more than previous ones and cannot update this variable. It will be slower and slower until it doesn't do anything but wasting cpu, memory and disk io:

![screen shot 2018-10-04 at 13 04 52](https://user-images.githubusercontent.com/5338482/46465718-33282d80-c7d6-11e8-8368-eb711104cb81.jpg)
![screen shot 2018-10-04 at 13 05 15](https://user-images.githubusercontent.com/5338482/46465719-33282d80-c7d6-11e8-813f-5b381a6b8c37.jpg)

Also it seems there is a data race here for variable `_last_position`.

I tested these solutions but they didn't work:

1. Increasing/decreasing `update_every`
2. Disabling categories and histogram
3. Adding `flush=10s` and `buffer=5M` options to `access_log` directive in nginx

**Possible solutions:**

1. Supporting multi-processes/threads for this plugin to use multiple cpu cores
2. Adding timeout for reading logs, (which doesn't solve handling high load traffic but it reduces the cpu and disk usage)
3. Using the go version of this plugin: https://github.com/l2isbad/go.d.plugin/ (written by @l2isbad) but I don't know it's ready to use
4. Improving reading logs in the current python plugin (using c-based modules, improving regex patterns, ...)
5. Reading logs via [filebeat](https://www.elastic.co/products/beats/filebeat) and sending them to netdata (Apparently, it's faster than this plugin specially when the number of its workers is set to more than 1) 
6. Nginx modules (lua-based modules, nginx plus, other stats modules)

Btw here is the spec of this hw (The RPS is high but I don't think it's a hardware or os issue)

- ~50cpu cores (only 30% of them are used)
- ~128G ram
- it's a bare metal not a vm (obviously!)
- ssd disks (cache of raid controller is also enabled + with raid 6)
- only nginx is running on this server

**Comment by ktsaou** [comment] 2018-10-04 10:08
hm... this is a problem...
@l2isbad please check this. I had the impression the python version could do 20k lines per second.

**Comment by l2isbad** [comment] 2018-10-04 10:58
@alibo how many jobs?

> web_log plugin cannot handle high load traffic (over 10k RPS) 

Depends on number of jobs and features (categories, filters are expensive). But yes, current design cannot handle high load traffic.

> The problem is if step 2 takes more than update_every, it couldn't update the _last_position

Hm, i don't see any time limit for `get_data`, so `_last_position` will be updated sooner or later.

> Supporting multi-processes/threads for this plugin to use multiple cpu cores

Process per job can help. 

> Using the go version of this plugin

This. Not ready. Under development (it is easy to write it, but hard to write it good). Working on weekends with @Wing924 on it (UMLs mostly). Will have more free time soon.

**Comment by Ferroin** [comment] 2018-10-04 11:18
> Also, it seems all python plugins (together) use only 1 cpu core:

Yes, this is unfortunately the case because we use threads for the individual modules instead of processes (so we run into the GIL).  I've been meaning to verify that `python.d.plugin` works correctly with PyPy for exactly this reason (PyPy has a saner implementation of threading than CPython, and doesn't have to use a GIL as a result).

**Comment by l2isbad** [comment] 2018-10-04 11:29
So we have a problem when a process writes to a file faster than plugin reads from there.

**Comment by l2isbad** [comment] 2018-10-04 11:57
Memory leak problem is bad. To fix it asap we can add some limit to

```
                for line in fp:
                    lines.append(line)
```

like 50K, if it is more then 50k in `lines` already we should stop, log error and return `None`. 

what do you think @Ferroin 
This is ofc not a solution, but 5G of ram on screenshot,  oh man :smile_cat:

**Comment by Ferroin** [comment] 2018-10-04 12:01
Even if it's not actually a solution to the issue at hand, I think it's still a good idea, though it might be worth exposing it as a configuration item since what makes sense for the limit is kind of dependent on the specifics of the system itself (50k lines is fine on a big server, but anything over about2k is likely to be an issue on a small IoT device).

**Comment by alibo** [comment] 2018-10-04 12:06
> Depends on number of jobs and features (categories, filters are expensive). But yes, current design cannot handle high load traffic.

@l2isbad I disabled all of them (just name and path) but it doesn't help

> Process per job can help.

@l2isbad How can I do this? By adding another python.d.plugin with a different name?

> This. Not ready. Under development (it is easy to write it, but hard to write it good). Working on weekends with @Wing924 on it (UMLs mostly). Will have more free time soon.

I saw the repo and I realized you're using the same approach in go plugin (-> GetData -> open file -> seek -> read line by line to the end of the file (at this moment) -> close the file -> next loop)

I think it's not efficient. Another approach is considering this plugin as an agent which keeps tailing logs and increasing the stats (ex. stats_5xx++) when netdata is calling this agent, you just need to pass these stats metrics. This Prometheus exporter works like this:

https://github.com/martin-helmich/prometheus-nginxlog-exporter

(If Netdata also can support the structure of metrics used by Prometheus exporters, it would be awesome! :) )

Also, this talk may help:
https://www.youtube.com/watch?v=lLDWF59aZAo

> Hm, I don't see any time limit for get_data, so _last_position will be updated sooner or later.


That's one of the issues. It may be stuck forever until we restart the Netdata service. Another issue is a data race. If the next two loops update it sooner and the first loop updates it after them, the 4th loop will read duplicated logs. 

> Have done tests on my PC:

> 3 jobs, 20k RPS - OK
> 4 jobs, 20k RPS - same result as @alibo

What's the job :D? Do you mean another log file? we have only one nginx log file. Or do you mean another python plugin?

**Comment by l2isbad** [comment] 2018-10-04 12:19
> I saw the repo and I realized you're using the same approach in go plugin (-> GetData -> open file -> seek -> read line by line to the end of the file (at this moment) -> close the file -> next loop)

Nice idea :+1: 

> What's the job :D?

```yaml
nginx_log:
  name: 'nginx'
  path: '/var/log/test/access.log'

nginx_log1:
  name: 'nginx2'
  path: '/var/log/test/access.log'
```

> How can I do this? By adding another python.d.plugin with a different name?

You can't with current version. And If you have only one job it doesn't help.

**Comment by alibo** [comment] 2018-10-04 13:04
@l2isbad We can only expose a `delay` metric (now - log_time) and set an alarm for it. But it would be faster and more efficient than the current solution because it opens and closes the log file only one time and it doesn't use seek method each time. Also, you can process each line asynchronously in different threads/goroutines and you don't need to keep all logs in memory first to process them.

Filebeat uses Elasticsearch indexing feature, it eventually read all the logs and it corrects the stats because it's using time of the logs, not the time which logs are sent. However, it's not real-time monitoring anymore. I think each solution has own advantages and disadvantages.

**Comment by ktsaou** [comment] 2018-10-04 14:16
Guys there are 4 options:

1. fix python plugin, if it can be fixed. I don't like missing entries, so this is not a fix. If we can't make it digest logs faster, this is not an option.

2. finish the `go` version of `web_log`.

3. write a `C` version of it (I guess the fastest that could possibly be written)

4. write a `prometheus` importer for netdata (I think we will eventually need this, although I don't like instructing people to install another component - this could use the same methodology statsd uses for synthetic charts, so synthetic charts could be a generic feature of netdata). But this will need some time.

**Comment by stohrendorf** [comment] 2018-10-04 14:49
Jumping in here, because I've seen medium-high traffic problems, too. Isn't a simple CSV parser an option? Basically, the standard logs I've seen so far are space-separated values, sometimes enclosed in double-quotes, so there's actually no real need to do a pattern matching to extract the columns, although some columns contain composed data; most columns can be treated as strings or numbers, and don't need extensive syntax checks at all. Other fields (like `example.com:443` or `GET /index.html HTTP/1.1`) can be decomposed using string magic if you don't want to do a full syntax check.

Although it could lead to parsing invalid log lines, it reduces the use of regular expressions and thus should give a performance boost. My suggestion would be to define the standard column semantics (`vhost`, `response_code`, `response_size`, `request` etc.) and make it possible to specify the log format with something like `columns: "vhost - - request response_code response_size ..."`.

**Comment by l2isbad** [comment] 2018-10-04 23:04
> Isn't a simple CSV parser an option? 
> Although it could lead to parsing invalid log lines, it reduces the use of regular expressions and thus should give a performance boost.

yes, go version will use csv parser, it's **much** faster on high load

**Comment by stohrendorf** [comment] 2018-10-17 20:41
Just wrote a prometheus exporter myself for parsing access logs, maybe a few ideas are helpful: https://github.com/stohrendorf/csv-prometheus-exporter. Cheers.

**Comment by ilyam8** [comment] 2018-12-19 20:13
> web_log high load support

* won't be added to python version 100%
* added to go version

Somehow i [managed to do this](https://github.com/netdata/go.d.plugin/pull/74)

improvements in `go` version:
 * uses `csv` parser
  * uses https://github.com/hpcloud/tail as a tailer

!Module still isn't ready for production, next phase is testing/tuning/optimization!

@alibo i really need your help 

And i want to have a chat with you, it will be much faster/better then collaborating via github. Is this ok for you? What messenger do you prefer? [Telegram](https://telegram.org/) would be great.

I think the issue is solved, i am closing it.

Continue in https://github.com/netdata/go.d.plugin

**Closed by ilyam8** 2018-12-19 20:13 UTC
Labels: area/external/python, bug, priority/high

**Comment by alibo** [comment] 2018-12-20 12:47
> @alibo i really need your help

> And i want to have a chat with you, it will be much faster/better then collaborating via github. Is this ok for you? What messenger do you prefer? Telegram would be great.

@ilyam8 Sure, I would be happy to help :) Telegram (`aliborhani`) or Skype (`aliborhani1`) is fine to me :)
