### ISSUE TITLE
streaming missing data with no error on client side

### ISSUE THREAD

**Issue by Ehekatl** [netdata/netdata#5014] opened 2018-12-17 13:38 UTC
##### Bug report summary

On the latest and recent version of netdata, I found some server failed to stream the data while the tcp connection "exist". 

Use `sudo netstat -ptan | grep netstat` will **show a ESTABLISHED tcp connection to streaming master, however, on the other side, streaming master don't have the TCP connection**.

There is no error and nothing in the log (I didn't enable debug log though, it's too complicate to switch debug mode and generate too much log while waiting for reproduce.)

Sometimes the error seems to be self-recovered, but usually last for day or longer. And it wasn't completely missing data, the data will come back for every a few hour, last for a while and gone again. Restart netdata service would fix it immediately. See the pic below, after a restart at 18:00 pm, streaming become stable again.

![screen shot 2018-12-17 at 8 53 12 pm](https://user-images.githubusercontent.com/7362589/50088412-f3ea7400-023d-11e9-84af-add3a9a64f51.png)

I noticed this bug for a while since #4425 get merged, but again, I wasn't able to reproduce it.

##### OS / Environment

Linux

##### Component Name

Streaming

##### Steps To Reproduce

I can't reproduce it now, but I hope netdata could support switch debug output on the fly, so we could at least provide some useful log.

##### Expected behavior

The TCP connection should be close cleanly on connection error, and fall back to other ip in case of network issue, now the connection between server is fine, but it periodically lost data on some server.

**Comment by ktsaou** [comment] 2019-01-16 19:49
Netdata logs to its `error.log` all connection attempts and timeouts. Could you please post the related logs from both the master and the slave?

**Comment by Ehekatl** [comment] 2019-01-25 09:59
Hi @ktsaou thanks for looking into this, 
there is no log at all when it happens.

the connection is in a broken state, on the problem server, it's still established state in netstat, but on the other server the connection is already gone.

Maybe we could have debug log enable on the fly first to able to catch what's really happening.

**Comment by Ehekatl** [comment] 2019-01-25 14:18
found some interesting log from the stream master side:

```
2019-01-25 14:01:06: netdata INFO  : STREAM_RECEIVER[vm172-26-0-26.ksc.com,[111.222.333.444]:50212] : host 'vm172-26-0-26.ksc.com', chart groups.pwrites: took too long to be updated (counter #1270, update #56, 6311.013 secs). Resetting it.
2019-01-25 14:01:06: netdata INFO  : STREAM_RECEIVER[vm172-26-0-26.ksc.com,[111.222.333.444]:50212] : host 'vm172-26-0-26.ksc.com', chart groups.files: took too long to be updated (counter #1270, update #56, 6311.010 secs). Resetting it.
2019-01-25 14:01:06: netdata INFO  : STREAM_RECEIVER[vm172-26-0-26.ksc.com,[111.222.333.444]:50212] : host 'vm172-26-0-26.ksc.com', chart groups.sockets: took too long to be updated (counter #1270, update #56, 6311.007 secs). Resetting it.
2019-01-25 14:01:06: netdata INFO  : STREAM_RECEIVER[vm172-26-0-26.ksc.com,[111.222.333.444]:50212] : host 'vm172-26-0-26.ksc.com', chart groups.pipes: took too long to be updated (counter #1270, update #56, 6311.003 secs). Resetting it.
```

**Comment by cakrit** [comment] 2019-05-08 10:33
The slave doesn't have similar error messages as well?
In addition, I'd be interested to see what happened on the slave during that period. Can you do an export from the netdata UI (top row button) after you've focused on the particular period? Perhaps we can see the issue the slave had in the charts themselves, before the connection was lost.

**Comment by cakrit** [comment] 2019-05-08 10:35
You can email me the netdata snapshot (chris@netdata.cloud), in case it contains sensitive info.

**Comment by Ehekatl** [comment] 2019-05-23 07:03
@cakrit I've just sent a email with all the details, please check.

let' me know if there is something else I could help.

**Comment by cakrit** [comment] 2019-05-23 08:40
Ok, found your problem:

```
2019-05-22 23:39:29: netdata INFO  : STREAM_RECEIVER ... multiple streaming connections for the same host detected. If multiple netdata are pushing metrics for the same charts, at the same time, the result is unexpected.
```
Ensure that:
- All the slaves have different UUIDs in `/var/lib/netdata/registry/netdata.public.unique.id`. You can only get the same if you have carried over that file in a cloned image. Ensure that if you clone images, this file does not exist, as netdata will create it once, when it starts for the first time.
- Each slave sends a different host name. On the master, I see the same slave hostname from many different ips. Not sure if it's the machine GUID causing it, but one could override the hostname in `netdata.conf`, section `[global]`, param `hostname`. If that has been modified and all slaves get the same config, then we could see these conflicts.

**Comment by Ehekatl** [comment] 2019-05-24 12:48
@cakrit I've confirmed that the hostname is unique
the multiple connection issue I guess it's related to load balancer in front of netdata master, but that's not the root problem.

Bypass lb give me the same result.

When I look the streaming data at master and slave at the same time, I found something interesting.

it does streaming, but delay more and more, at first it only delay seconds, then to minutes, eventually cause "took too long to be updated (counter #1945, update #992, 4683.449 secs). Resetting it."

since prometheus can't scape outdate data, when it delay by a lot, the graph shows missing data, when it reset, it recover for a few minutes, repeat over and over, cause this weird pattern.

Now I wonder what cause the delay, the network connection between slave and master looks good, they are in the same data center.

**Comment by cakrit** [comment] 2019-05-27 10:15
We need to get rid of the `multiple streaming connections for the same host detected` for sure. netdata's behavior is completely unpredictable when that happens. Within a nine minute period in the log you sent me you had connections from 4 different IPs: `xxx.xxx.xx[1.50 , 1.52, 6.180, 1.48]`. All of them were from your LB?  

I went back and saw another strange thing in your log:
```
2019-05-23 03:28:03: netdata ERROR : STREAM_RECEIVER[...] : sent command 'BE' which is not known by netdata, for host '...'. Disabling it.
```
From the comments in #4049 and #4425 it looks like you can get such a message when you have the same GUID on your machines. 

So:
- How many slaves do you have pushing to the master? Can you verify that all of them have a different UUID as mentioned before?
- If that's not the issue, can I see the master's log when all the slaves communicate directly with the master, without the LB?

**Comment by stelfrag** [comment] 2019-12-10 13:40
I am closing this as it cannot be reproduced. 

In fact we are checking a similar issue #7327 with additional checks in place, and still cannot reproduce

**Closed by stelfrag** 2019-12-10 13:40 UTC
Labels: area/streaming, bug
