### ISSUE TITLE
[Bug]: The limit on metric length cannot accommodate Prometheus endpoint based metrics

### ISSUE THREAD

**Issue by sashwathn** [netdata/netdata#14730] opened 2023-03-15 11:01 UTC
### Bug description

While trying to import metrics from AWS Cloudwatch exporter endpoint, the metric lengths are ~350 characters and are not processed by Netdata.

### Expected behavior

The metric length should not be a limiting factor on importing metrics

### Steps to reproduce

1. Configure the AWS Cloudwatch endpoint
2. Collect metrics using the Prometheus collector
3.
...

### Installation method

kickstart.sh

### System info

```shell
Applicable to any system
```

### Netdata build info

```shell
Applicable to the latest nightly
```

### Additional info

Error:

```
(https://netdata-cloud.slack.com/archives/D03V346R890/p1678865132495559)
[ WARN  ] prometheus[prometheus-mon_cloudwatch-exporter-65646447c-nz5g4_cloudwatch-exporter_tcp_5000] job.go:383 chart 'type.id' length (350) >= max allowed (200), the chart is ignored (prometheus_prometheus-mon_cloudwatch-exporter-65646447c-nz5g4_cloudwatch-exporter_tcp_5000.aws_nlb_active_flow_count_minimum-account_id=731490016344-dimension_AvailabilityZone=us-east-1b-dimension_LoadBalancer=net/tcorp/7d6cf324a0f0f7d0-name=arn:aws:elasticloadbalancing:us-east-1:731490016344:loadbalancer/net/tcorp/7d6cf324a0f0f7d0-region=us-east-1)
(https://netdata-cloud.slack.com/archives/D03V346R890/p1678865165474279)
```

**Comment by ilyam8** [comment] 2023-03-15 18:44
Duplicate of #14515

**Comment by sashwathn** [comment] 2023-03-16 13:13
@ilyam8 and @MrZammler : Can you please fix the metric length to 400 or even 500 characters?
@ktsaou has confirmed this is not a breaking change.

**Comment by Tensibai** [comment] 2023-03-16 14:05
Well, a blanket statement that it is not a breaking change versus this comment https://github.com/netdata/netdata/issues/10164#issuecomment-719441054 worth a bit more details I think.

I'd be very sad to have all my agents in memory mode ram replicating to a parent breaking because of this.

**Closed** 2023-03-16 17:30 UTC
Labels: bug, duplicate
