### ISSUE TITLE
Cannot read disk space usage metrics && wrong metrics inside Docker/Kubernetes environment (important because we should alert when disks become full)

### ISSUE THREAD

**Issue by fzyzcjy** [netdata/netdata#10604] opened 2021-02-06 14:10 UTC
##### Bug report summary

Hi thanks for the lib! I find the "disk" section incomplete. It does not have `disk_spaces._`/`disk_usages._` chart for most of the disks (e.g. `sda`, `sdb`, ... and `dm-1`, `dm-2`, ... It only has that for a few disks like `/`.

In addition, even for the `/` filesystem, the disk size that netdata says is *different* from the actual value. When execute `df -h` in my host machine, it says `/dev/vda1                      40G  3.5G   34G   10% /`. But as you can see from figure 1, netdata think it is 8GB (not 40GB).

I guess it is related to permission problems and problems of container volume mapping? Possibly related (not sure): https://github.com/netdata/netdata/issues/3716. But I do not have any ideas on how to solve this.

Thanks!

figure 1: it has metrics for `/`

![image](https://user-images.githubusercontent.com/5236035/107111788-cafa2280-688d-11eb-8d36-c0a4c6ebce08.png)

figure 2: it does **not** for `sda`

![image](https://user-images.githubusercontent.com/5236035/107111801-d9483e80-688d-11eb-8299-94c066b698ce.png)

##### OS / Environment

```
kubernetes on centos 7
```

##### Netdata version

latest

##### Component Name

disk

##### Steps To Reproduce

1. install official helmchart
2. see it

##### Expected behavior

should see correct metrics

**Comment by vlvkobal** [comment] 2021-02-08 11:55
Hi @fzyzcjy, you can't get diskspace stats for devices, only for mount points.

As for the second question, you should mount volumes you are willing to monitor using the diskspace plugin. Please look at a relevant [comment](https://github.com/netdata/netdata/issues/5071#issuecomment-460442980).

I'm closing the issue because it's a question, not a bug. If you have further questions, please consider using our [community forum](https://community.netdata.cloud/).

**Closed by vlvkobal** 2021-02-08 11:55 UTC
Labels: bug, needs triage

**Comment by fzyzcjy** [comment] 2021-02-08 12:10
@vlvkobal Hi I have already tried to mount `/mnt` to `/host/mnt` (hoping that things like `/mnt/sda`, `/mnt/sdb`, etc can be found), but no success. Nothing more is appeared in the UI. :( Any suggestions?

**Comment by vlvkobal** [comment] 2021-02-08 12:31
What are `/mnt/sda` and `/mnt/sdb`? Are they mounted filesystems?

**Comment by fzyzcjy** [comment] 2021-02-08 12:47
@vlvkobal IMHO yes. They are just normal disk partitions(?). You know, just those paths seen everywhere when you have a linux machine.
