### ISSUE TITLE
[Bug]: go.d.plugin has no permission to run

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#15252] opened 2023-06-25 12:15 UTC
### Bug description

I have installed netdata with kickstart script (v1.40.0), then I realized no golang plugin is working, so I tried to run it as the netdata user and it gave me permission denied error:
```
/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin -d -m proxysql
bash: /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin: Permission denied
```
when I run the command as root it works correctly. 

### Expected behavior

go.d.plugin should work with `netdata` user as the process is running with this username and group in the SystemD unit

### Steps to reproduce

1. `wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --no-updates --stable-channel --disable-telemetry --static-only`
2. `sudo su -s /bin/bash netdata` 
3. `/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin -d -m proxysql`
...

### Installation method

kickstart.sh

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

### Netdata build info

```shell
Version: netdata v1.40.0
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -I/libnetfilter-acct-static/include/libnetfilter_acct -I/usr/include/libmnl -pipe' 'LDFLAGS=-static -L/openssl-static/lib -L/libnetfilter-acct-static/lib -lnetfilter_acct -L/usr/lib -lmnl' 'PKG_CONFIG=pkg-config --static' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig:/libnetfilter-acct-static/lib/pkgconfig:/usr/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment] 2023-06-27 06:58
Hi, @yasharne. Thanks for reporting. Yes, the v1.40.0 static build has problems with external plugins ownership. v1.40.1 will be released soon.

The issue fixed in https://github.com/netdata/netdata/pull/15230

**Comment by ilyam8** [comment] 2023-06-27 06:59
Duplicate of #15228

**Closed by ilyam8** 2023-06-27 06:59 UTC
Labels: bug, duplicate, area/packaging
