### ISSUE TITLE
Netdata Cloud node unreachable in war room

### ISSUE THREAD

**Issue by rdifrancesco** [netdata/netdata#9624] opened 2020-07-29 03:22 UTC
##### Bug report summary

When attempting to connect my nodes to Netdata Cloud, each node shows as unreachable in the war room and each node reports the following error:

```
Connection Problem
This agent cannot connect to Netdata Cloud. Please talk to system's administrator for more information.
```

The error log also reports:
```
tail -f /opt/netdata/var/log/netdata/error.log | grep -i ACLK
...
2020-07-27 23:00:28: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-07-27 23:00:28: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/4cc65786-c2f1-11ea-a6ea-b8ca3a6562a0/challenge
2020-07-27 23:00:28: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-07-27 23:00:28: netdata ERROR : ACLK_Main : Libwebsockets: SSL error: unable to get local issuer certificate (preverify_ok=0;err=20;depth=1)
2020-07-27 23:00:28: netdata ERROR : ACLK_Main : Challenge failed:
```

I have been installing using the static binary:
```
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --stable-channel --disable-telemetry
```

This issue does not occur if I manually build Netdata or use the non-64bit kickstart script.

I've also read some recent similar bug reports which indicate those issues have been resolved, yet I continue to experience this connection failure related to the ssl error.

##### OS / Environment

I have primarily been testing on RHEL 6, but can confirm the issue occurs on RHEL 7 and Amazon Linux 2 as well.
```
Linux myhost 2.6.32-754.9.1.el6.x86_64 #1 SMP Wed Nov 21 15:08:21 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
/etc/redhat-release:Red Hat Enterprise Linux Server release 6.10 (Santiago)
/etc/system-release:Red Hat Enterprise Linux Server release 6.10 (Santiago)
```

##### Netdata version

netdata v1.23.2-32-g1602d66a

##### Component Name

Netdata Cloud
ACLK_Main

##### Steps To Reproduce

1. Install using the 64bit static binary:
```
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --stable-channel --disable-telemetry
```
2. Attempt to claim a node:
```
/opt/netdata/bin/netdata-claim.sh -token=mytoken -rooms=mywarroom -url=https://app.netdata.cloud
```
3. Confirm the ssl cert error in the log:
```
tail -f /opt/netdata/var/log/netdata/error.log | grep -i ACLK
```

I've also reviewed installations which work using kickstart.sh or building manually and compared all the dependency packages installed using either of those methods against the packages installed using kickstart-static64.sh and the package list and versions are identical.

##### Expected behavior

For RHEL and Amazon Linux 2 nodes to successfully connect to Netdata Cloud using kickstart-static64.sh.

**Comment by rdifrancesco** [comment] 2020-08-07 03:15
Checking if there are any thoughts or updates on this issue.

**Comment by cakrit** [comment] 2020-08-07 07:12
> This issue does not occur if I manually build Netdata or use the non-64bit kickstart script.

**Comment by amoss** [comment] 2020-08-07 08:22
This is a packaging issue. We need to check that the version of openssl being bundled in the static install is working correctly on this configuration. The underlying problem is whether or not the CA-roots have been installed correctly. I thought this had been fixed, @Ferroin / @prologic please investigate.

**Comment by Ferroin** [comment] 2020-08-10 11:53
It should have been fixed indeed. I'll try and look into it today.

**Comment by Ferroin** [comment] 2020-08-10 16:32
OK, tested a bit, and I cannot reproduce this locally in my CentOS 7 test VM (but that's unsurprising since that's what I used to test the changes that originally fixed this). I'll try with RHEL Docker images shortly and hopefully have better success there.

**Comment by Ferroin** [comment] 2020-08-10 19:47
@prologic Can you take a look at this, I'm not having any success reproducing the issues outlined here either in my CentOS test VMs or in CentOS or RHEL docker containers. I'm pretty sure I'm doing something wrong trying to reproduce it, but a second opinion would be appreciated.

**Comment by prologic** [comment] 2020-08-11 05:03
Nope I am _unable_ to repro this either:

<img width="1312" alt="Screen Shot 2020-08-11 at 15 00 17" src="https://user-images.githubusercontent.com/1290234/89859083-8265f300-dbe3-11ea-8814-ef63316199dc.png">

I _suspect_ something else is going on here...

@rdifrancesco We need your help to figure this out. Either one of two things is happening... (_really hope its not the later..._):

- Your CA bundle on your system(s) is either wrong, outdated or invalid, or non-existent.
- Something is _trying_ to perform some kind of MitM :/

**Comment by rdifrancesco** [comment] 2020-08-11 12:24
@prologic I had thought there might be an issue with something on my end since initially I was experiencing this issue on my on-prem RHEL6 and RHEL7 servers.  But then I began testing against newly-launched Amazon Linux 2 instances and the issue persisted there, suggesting the problem isn't specific to my on-prem servers and that if it is an issue with the CA bundle, then it's coming "broken" straight from AWS.

I've been following the documentation for installation, but if you could spell out the precise install steps you're using when trying to reproduce, this could help check my sanity and that I'm not missing something important.

Is there a command which could help me verify the validity of the CA bundle?

**Comment by prologic** [comment] 2020-08-13 05:58
I'm actually following the same _exact_ steps as you are! The only difference is I'm not doing this from inside an AWS environment but on Docker containers locally on an iMac or Virtualbox CentOS VMs.

So... I'm only left with jumping on to a fresh EC2 instance on AWS to figure this out 👍 Unless there's something more you can share from your end? Happy to help!

**Comment by rdifrancesco** [comment] 2020-08-13 12:17
I'm out of ideas on my end.  If you are able to test against an EC2 instance (Amazon Linux 2 AMI), I'd appreciate it.  Then we'll know we're comparing apples to apples.

**Comment by prologic** [comment] 2020-08-20 00:40
Okay I'll spin up an EC2 and have a play today... Sorry about the delay!

**Comment by prologic** [comment] 2020-08-24 10:50
I was also successfully able to claim an EC2 instance to Netdata Cloud.

```#!sh
[ec2-user@ip-172-31-33-81 ~]$ sudo /opt/netdata/bin/netdata-claim.sh -token=xxxx -rooms=xxxx -url=https://app.netdata.cloud
Token: ****************
Base URL: https://app.netdata.cloud
Id: xxxx
Rooms: xxxx
Hostname: ip-172-31-33-81.us-east-2.compute.internal
Proxy:
Netdata user: netdata
Generating private/public key for the first time.
Generating RSA private key, 2048 bit long modulus
................................+++
...........+++
e is 65537 (0x10001)
Extracting public key from private key.
writing RSA key
Node was successfully claimed.
[ec2-user@ip-172-31-33-81 ~]$ yes 'I'm a little tea pot'
> ^C
````

<img width="1312" alt="Screen Shot 2020-08-24 at 20 48 47" src="https://user-images.githubusercontent.com/1290234/91036819-5585f700-e64b-11ea-866f-63fbef24d9a5.png">

**Comment by prologic** [comment] 2020-08-24 10:52
@rdifrancesco If there's something you'd like me to try on my end to help you debug this I'll leave this EC2 instance up for a few days...

Nothing special here; just an ordinary EC2, mostly with defaults. Ran the same command you did above to install the Netdata Agent, then followed the instructions on [app.netdata.cloud](https://app.netdata.cloud) in one of my War Rooms to claim it.

**Comment by prologic** [comment] 2020-08-31 04:03
I am closing this as stated above, We cannot reproduce this even on a live EC2 instance on AWS. If you are sitll having troubles with this, __please__ file a bug report with some reproducible steps we can verify and fix! Thank you. 🙇‍♂️

**Closed by prologic** 2020-08-31 04:03 UTC
Labels: Cannot reproduce, question

**Comment by rdifrancesco** [comment] 2020-09-16 17:29
@prologic closing the loop on this.  After putting this on hold for several weeks, I just resumed testing with Netdata v1.24 and it seems all issues are resolved.  I can install the agent with the 64bit kickstart script and nodes can successfully connect to the war rooms.  I have successfully tested this on RHEL 6 and the latest Amazon Linux 2 instance.  Nothing in my testing routine changed so my guess is that something in v1.24 fixed the issue.  Thanks!

PS...Netdata is so ef-ing good it makes me want to punch someone.

**Comment by prologic** [comment] 2020-09-17 04:43
> @prologic closing the loop on this. After putting this on hold for several weeks, I just resumed testing with Netdata v1.24 and it seems all issues are resolved. I can install the agent with the 64bit kickstart script and nodes can successfully connect to the war rooms. I have successfully tested this on RHEL 6 and the latest Amazon Linux 2 instance. Nothing in my testing routine changed so my guess is that something in v1.24 fixed the issue. Thanks!
> 
> PS...Netdata is so ef-ing good it makes me want to punch someone.

So glad to hear this! I _really_ could not figure out wtf was going on! Glad it magically™ solved itself! 😀
