### ISSUE TITLE
gpu name not updating in Nvidia-smi python plugin

### ISSUE THREAD

**Issue by cg-cnu** [netdata/netdata#10138] opened 2020-10-26 05:40 UTC
##### Bug report summary

I installed Netdata on a brand new machine. Tested out the **K2200** gpu, on the machine. Swapped the card with an **RTX**, booted back and enabled Netdata. All the charts are displaying proper data reflecting the new card, but the name under nvidia smi is still showing as **gpu0 Quadra K2200** instead of RTX. 

##### OS / Environment

```
CentOS - 7
```

##### Netdata version

 netdata v1.24.0 

##### Component Name

nvidia-smi

##### Steps To Reproduce

1. Enable nvidia smi python plugin
2. Swap Nvidia graphic card model on the machine
3. Restart netdata

##### Expected behavior

Netdata should update the Nvidia Card name to the one on in the system instead of previous card.

* Clearing up the browser cache didn't worked.
* re-enabling the nvidia-smi plugin didn't helped.

Let me know if you need more details. Cheers!

**Comment by Ferroin** [comment] 2020-10-26 13:26
I _think_ what’s going on here is a combination of two things:

* The chart’s ID is tied to the GPU device index (so GPU 0 is always the same chart).
* We never actually update the chart names once they are created.

The first point is, strictly speaking, _technically_ correct in that it matches up with the view provided by other monitoring tools, as well as what the NVIDIA tools themselves will show, so any fix would have to change the second point. I don’t actually know if we _can_ update chart names after chart creation without recreating the chart from scratch (which would lose all historical data).

**Comment by Ferroin** [comment] 2020-10-26 14:05
@cg-cnu This was a case of shutting down, replacing the card, and then rebooting, not hot-swapping cards, correct?

Just want to make sure because I’m pretty sure we can only fix this for the case of switching out cards across a reboot, not the case of hot-swapping cards.

**Comment by cg-cnu** [comment] 2020-10-27 00:31
Hey @Ferroin ! 
> This was a case of shutting down, replacing the card, and then rebooting, not hot-swapping cards, correct?

Yes, its not hot-swapping cards, shutdown and replace.

**Comment by ilyam8** [comment] 2020-10-27 09:08
Hi there. There is only gpu index in the chart id.

https://github.com/netdata/netdata/blob/4b56242ec0e5abd64da7f0ca80a231e0c264c19b/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L460-L461

https://github.com/netdata/netdata/blob/4b56242ec0e5abd64da7f0ca80a231e0c264c19b/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L290-L292

https://github.com/netdata/netdata/blob/4b56242ec0e5abd64da7f0ca80a231e0c264c19b/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L136-L143

---

GPU name only in the `family` (subsection on the dashboard)

https://github.com/netdata/netdata/blob/4b56242ec0e5abd64da7f0ca80a231e0c264c19b/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L55-L56

https://github.com/netdata/netdata/blob/4b56242ec0e5abd64da7f0ca80a231e0c264c19b/collectors/python.d.plugin/nvidia_smi/nvidia_smi.chart.py#L302-L303

---

i think this is well-known that it is impossible to change a chart title, units, family, etc just resending the chart definition.

@mfundul

**Comment by ilyam8** [comment] 2020-10-27 09:12
@cg-cnu not a fix but if you are not interested in metrics (charts) history you could remove dbengine data

```cmd
[karasik dbengine]# pwd
/opt/netdata/var/cache/netdata/dbengine

[karasik dbengine]# ls -l
total 652
-rw------- 1 netdata netdata 221184 окт 27 11:57 datafile-1-0000000001.ndf
-rw------- 1 netdata netdata 131072 окт 27 11:57 journalfile-1-0000000001.njf
-rw------- 1 netdata netdata 291212 окт 27 11:57 metadatalog-00000-00002.mlf
-rw------- 1 netdata netdata   5568 окт 27 11:58 metadatalog-00000-00003.mlf

[karasik dbengine]# rm -rf *

[karasik dbengine]# systemctl restart netdata
[karasik dbengine]#
```

**Comment by ilyam8** [comment] 2020-10-27 14:28
Since it is not a bug i am closing the issue

**Closed by ilyam8** 2020-10-27 14:28 UTC
Labels: area/external/python, question
