### ISSUE TITLE
Streaming not working with ^SSL option in bind to =

### ISSUE THREAD

**Issue by pgassmann** [netdata/netdata#6457] opened 2019-07-14 14:12 UTC
##### Bug report summary

Slave cannot stream to netdata when `^SSL=` option is defined on streaming port. Same ERROR on sender with `^SSL=optional` or `^SSL=force`

netdata.conf of reciever
```
[web]
        ssl key = /etc/netdata/ssl/key.pem
        ssl certificate = /etc/netdata/ssl/cert.pem
        default port = 19999
        bind to = *:19999=dashboard|netdata.conf^SSL=optional, *:19996=streaming^SSL=optional
        # working configuration:
        # bind to = *:19999=dashboard|netdata.conf^SSL=optional, *:19996=streaming
```

stream.conf reciever:
```
[stream]
    enabled = no
    # destination = IP:PORT 
    # api key = XXXXXXXXXXX
[63....81c]
    # Default settings for this API key
    enabled = yes
    default history = 3600
    default memory mode = save
    health enabled by default = auto
    allow from = *
    default postpone alarms on connect seconds = 60
    multiple connections = allow
```

stream.conf sender (same ERROR with and without `:SSL`!)
```
[stream]
    enabled = yes
    destination = <reciever-ip>:19996:SSL
    ssl skip certificate verification = yes
    api key = 63....81c
```

Error message sender:
```
netdata_1  | 2019-07-14 13:52:16: netdata INFO  : STREAM_SENDER[playground01t.example.net] : STREAM playground01t.example.net [send to <reciever-ip>:19996]: connecting...
netdata_1  | 2019-07-14 13:52:16: netdata INFO  : STREAM_SENDER[playground01t.example.net] : STREAM playground01t.example.net [send to <reciever-ip>:19996]: initializing communication...
netdata_1  | 2019-07-14 13:52:16: netdata INFO  : STREAM_SENDER[playground01t.example.net] : STREAM playground01t.example.net [send to <reciever-ip>:19996]: waiting response from remote netdata...
netdata_1  | 2019-07-14 13:52:16: netdata ERROR : STREAM_SENDER[playground01t.example.net] : STREAM playground01t.example.net [send to <reciever-ip>:19996]: server is not replying properly (is it a netdata?).
```

LOG messages Reciever when ERROR:

```
netdata_1  | 2019-07-14 13:51:08: 2: 23 '[<sender-ip>]:39260' 'STREAM' (sent/all = 44/44 bytes -0%, prep/sent/total = 1563112268033.62/1563112268033.90/0.28 ms) 403 'key=63....1c&hostname=playground01t.example.net&registry_hostname=playground01t.example.net&machine_guid=0a91f46e-a63d-11e9-b937-9600001ccab5&update_every=1&os=linux&timezone=Europe/Berlin&tags=&NETDATA_SYSTEM_OS_NAME="Alpine Linux"&NETDATA_SYSTEM_OS_ID=alpine&NETDATA_SYSTEM_OS_ID_LIKE=unknown&NETDATA_SYSTEM_OS_VERSION=unknown&NETDATA_SYSTEM_OS_VERSION_ID=3.9.4&NETDATA_SYSTEM_OS_DETECTION=/etc/os-release&NETDATA_SYSTEM_KERNEL_NAME=Linux&NETDATA_SYSTEM_KERNEL_VERSION=4.15.0-42-generic&NETDATA_SYSTEM_ARCHITECTURE=x86_64&NETDATA_SYSTEM_VIRTUALIZATION=hypervisor&NETDATA_SYSTEM_VIRT_DETECTION=/proc/cpuinfo&NETDATA_SYSTEM_CONTAINER=docker&NETDATA_SYSTEM_CONTAINER_DETECTION=dockerenv'
netdata_1  | 2019-07-14 13:51:13: 3: 23 '[<sender-ip>]:39262' 'STREAM' (sent/all = 44/44 bytes -0%, prep/sent/total = 1563112273081.62/1563112273081.97/0.35 ms) 403 'key=63....1c&hostname=playground01t.example.net&registry_hostname=playground01t.example.net&machine_guid=0a91f46e-a63d-11e9-b937-9600001ccab5&update_every=1&os=linux&timezone=Europe/Berlin&tags=&NETDATA_SYSTEM_OS_NAME="Alpine Linux"&NETDATA_SYSTEM_OS_ID=alpine&NETDATA_SYSTEM_OS_ID_LIKE=unknown&NETDATA_SYSTEM_OS_VERSION=unknown&NETDATA_SYSTEM_OS_VERSION_ID=3.9.4&NETDATA_SYSTEM_OS_DETECTION=/etc/os-release&NETDATA_SYSTEM_KERNEL_NAME=Linux&NETDATA_SYSTEM_KERNEL_VERSION=4.15.0-42-generic&NETDATA_SYSTEM_ARCHITECTURE=x86_64&NETDATA_SYSTEM_VIRTUALIZATION=hypervisor&NETDATA_SYSTEM_VIRT_DETECTION=/proc/cpuinfo&NETDATA_SYSTEM_CONTAINER=docker&NETDATA_SYSTEM_CONTAINER_DETECTION=dockerenv'
```

Reciever Log on SUCCESS:
```
netdata_1  | 2019-07-14 13:52:27: netdata INFO  : WEB_SERVER[static1] : clients wants to STREAM metrics.
netdata_1  | 2019-07-14 13:52:27: 1: 23 '[<sender-ip>]:39616' 'STREAM' (sent/all = 0/0 bytes -0%, prep/sent/total = 1563112347045.63/1563112347057.56/11.93 ms) 200 'key=63....1c&hostname=playground01t.example.net&registry_hostname=playground01t.example.net&machine_guid=0a91f46e-a63d-11e9-b937-9600001ccab5&update_every=1&os=linux&timezone=Europe/Berlin&tags=&NETDATA_SYSTEM_OS_NAME="Alpine Linux"&NETDATA_SYSTEM_OS_ID=alpine&NETDATA_SYSTEM_OS_ID_LIKE=unknown&NETDATA_SYSTEM_OS_VERSION=unknown&NETDATA_SYSTEM_OS_VERSION_ID=3.9.4&NETDATA_SYSTEM_OS_DETECTION=/etc/os-release&NETDATA_SYSTEM_KERNEL_NAME=Linux&NETDATA_SYSTEM_KERNEL_VERSION=4.15.0-42-generic&NETDATA_SYSTEM_ARCHITECTURE=x86_64&NETDATA_SYSTEM_VIRTUALIZATION=hypervisor&NETDATA_SYSTEM_VIRT_DETECTION=/proc/cpuinfo&NETDATA_SYSTEM_CONTAINER=docker&NETDATA_SYSTEM_CONTAINER_DETECTION=dockerenv'
netdata_1  | 2019-07-14 13:52:27: netdata INFO  : STREAM_RECEIVER[playground01t.example.net,[<sender-ip>]:39616] : thread created with task id 35
netdata_1  | 2019-07-14 13:52:27: netdata INFO  : STREAM_RECEIVER[playground01t.example.net,[<sender-ip>]:39616] : STREAM playground01t.example.net [<sender-ip>]:39616: receive thread created (task id 35)
netdata_1  | 2019-07-14 13:52:27: netdata ERROR : STREAM_RECEIVER[playground01t.example.net,[<sender-ip>]:39616] : HEALTH [playground01t.example.net]: cannot open health file: /var/lib/netdata/0a91f46e-a63d-11e9-b937-9600001ccab5/health/health-log.db.old (errno 2, No such file or directory)
netdata_1  | 2019-07-14 13:52:27: netdata ERROR : STREAM_RECEIVER[playground01t.example.net,[<sender-ip>]:39616] : HEALTH [playground01t.example.net]: cannot open health file: /var/lib/netdata/0a91f46e-a63d-11e9-b937-9600001ccab5/health/health-log.db (errno 2, No such file or directory)
netdata_1  | 2019-07-14 13:52:27: netdata INFO  : STREAM_RECEIVER[playground01t.example.net,[<sender-ip>]:39616] : Host 'playground01t.example.net' (at registry as 'playground01t.example.net') with guid '0a91f46e-a63d-11e9-b937-9600001ccab5' initialized, os 'linux', timezone 'Europe/Berlin', tags '', program_name 'netdata', program_version 'v1.16.0-43-gb548214e', update every 1, memory mode save, history entries 3996, streaming disabled (to '' with api key ''), health enabled, cache_dir '/var/cache/netdata/0a91f46e-a63d-11e9-b937-9600001ccab5', varlib_dir '/var/lib/netdata/0a91f46e-a63d-11e9-b937-9600001ccab5', health_log '/var/lib/netdata/0a91f46e-a63d-11e9-b937-9600001ccab5/health/health-log.db', alarms default handler '/usr/libexec/netdata/plugins.d/alarm-notify.sh', alarms default recipient 'root'
netdata_1  | 2019-07-14 13:52:27: netdata INFO  : STREAM_RECEIVER[playground01t.example.net,[<sender-ip>]:39616] : STREAM playground01t.example.net [receive from [<sender-ip>]:39616]: initializing communication...
netdata_1  | 2019-07-14 13:52:27: netdata INFO  : STREAM_RECEIVER[playground01t.example.net,[<sender-ip>]:39616] : Postponing health checks for 60 seconds, on host 'playground01t.example.net', because it was just connected.
```

##### OS / Environment

Netdata with Docker image: netdata/netdata:latest

##### Netdata version (ouput of `netdata -V`)

netdata v1.16.0-43-gb548214e

**Comment by cakrit** [comment] 2019-07-15 08:27
The configuration looks fine. @thiagoftsm note that the slave is running in a docker container, though that shouldn't have impacted the communication at all. 

@pgassmann I expect that the netdata version is the same for both the sender and the receiver, correct?

**Comment by pgassmann** [comment] 2019-07-15 11:03
> @pgassmann I expect that the netdata version is the same for both the sender and the receiver, correct?

yes, i updated both to latest (docker pull) and i tried with two instances.

**Comment by thiagoftsm** [comment] 2019-07-15 13:05
I am trying to simulate the scenario here. The fact that is in a docker does not affect the SSL.

**Comment by thiagoftsm** [comment] 2019-07-15 13:06
Hi @pgassmann , what is the version of  OpenSSL library you are using?

**Comment by pgassmann** [comment] 2019-07-15 13:12
@thiagoftsm openssl is packaged in the docker image netdata/netdata:latest. https://github.com/netdata/netdata/tree/master/packaging/docker

**Comment by pgassmann** [comment] 2019-07-15 13:15
docker-compose.yml of the reciever:

```
version: '3'
services:

  netdata:
    image: netdata/netdata:latest
    restart: always
    hostname: monitor.example.net
    volumes:
      - ./netdata.conf:/etc/netdata/netdata.conf:ro
      - ./stream.conf:/etc/netdata/stream.conf:ro
      - ./ssl:/etc/netdata/ssl
      - ./cache:/var/cache/netdata:rw # persistent data
    environment:
      TZ: Europe/Berlin
      PGID: 999
      NETDATA_PORT: 19999
      VIRTUAL_HOST: 'monitor.example.net'
      LETSENCRYPT_HOST: 'monitor.example.net'
      LETSENCRYPT_EMAIL: 'monitoring@example.net'
      VIRTUAL_PORT: '19999'

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
    expose:
      - 19999
      - 19996
    ports:
      - 19996:19996
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy

```

**Comment by thiagoftsm** [comment] 2019-07-15 13:21
Thank you! I am doing some tests without docker to check that everything is OK with the Netdata itself, after this I will check our docker image.

**Comment by thiagoftsm** [comment] 2019-07-15 14:07
Hi @pgassmann I am thinking that the problem is not the SSL itself, but to confirm this, I am needing two information from you, firstly, can you confirm that your access.log has some line like this:

'STREAM' (sent/all = 44/44 bytes -0%, prep/sent/total = 1563199222966.59/1563199222966.60/0.02 ms) 403 'key=......"

Case this is happening, so probably we have an access forbidden in your side too. To confirm that we are having problem when we apply default rules, can you set the following option in the received and test again:

bind to = *:19999=dashboard|netdata.conf^SSL=optional *:19996=streaming|dashboard|registry|badges|netdata.conf|management^SSL=optional

Regards!

**Comment by cakrit** [comment] 2019-07-15 14:28
Actually, now that I see the configuration above again, there IS an issue:
```
 bind to = *:19999=dashboard|netdata.conf^SSL=optional, *:19996=streaming^SSL=optional
```

The comma should not appear there.
@thiagoftsm : There is no need to enable additional endpoints on port 19996, it looks like the comma threw of the parsing somehow, though it shouldn't have.

**Comment by thiagoftsm** [comment] 2019-07-15 14:31
I did not use the comma in my tests, I will put to confirm that is the problem.

**Comment by pgassmann** [comment] 2019-07-15 14:40
> 'STREAM' (sent/all = 44/44 bytes -0%, prep/sent/total = 1563199222966.59/1563199222966.60/0.02 ms) 403 'key=......"

Yes, these lines appear as written in de issue description:
```
netdata_1  | 2019-07-14 13:51:08: 2: 23 '[<sender-ip>]:39260' 'STREAM' (sent/all = 44/44 bytes -0%, prep/sent/total = 1563112268033.62/1563112268033.90/0.28 ms) 403 'key=63....1c&hostname=playground01t.example.net&registry_hostname=playground01t.example.net&machine_guid=0a91f46e-a63d-11e9-b937-9600001ccab5&update_every=1&os=linux&timezone=Europe/Berlin&tags=&NETDATA_SYSTEM_OS_NAME="Alpine Linux"&NETDATA_SYSTEM_OS_ID=alpine&NETDATA_SYSTEM_OS_ID_LIKE=unknown&NETDATA_SYSTEM_OS_VERSION=unknown&NETDATA_SYSTEM_OS_VERSION_ID=3.9.4&NETDATA_SYSTEM_OS_DETECTION=/etc/os-release&NETDATA_SYSTEM_KERNEL_NAME=Linux&NETDATA_SYSTEM_KERNEL_VERSION=4.15.0-42-generic&NETDATA_SYSTEM_ARCHITECTURE=x86_64&NETDATA_SYSTEM_VIRTUALIZATION=hypervisor&NETDATA_SYSTEM_VIRT_DETECTION=/proc/cpuinfo&NETDATA_SYSTEM_CONTAINER=docker&NETDATA_SYSTEM_CONTAINER_DETECTION=dockerenv'
netdata_1  | 2019-07-14 13:51:13: 3: 23 '[<sender-ip>]:39262' 'STREAM' (sent/all = 44/44 bytes -0%, prep/sent/total = 1563112273081.62/1563112273081.97/0.35 ms) 403 'key=63....1c&hostname=playground01t.example.net&registry_hostname=playground01t.example.net&machine_guid=0a91f46e-a63d-11e9-b937-9600001ccab5&update_every=1&os=linux&timezone=Europe/Berlin&tags=&NETDATA_SYSTEM_OS_NAME="Alpine Linux"&NETDATA_SYSTEM_OS_ID=alpine&NETDATA_SYSTEM_OS_ID_LIKE=unknown&NETDATA_SYSTEM_OS_VERSION=unknown&NETDATA_SYSTEM_OS_VERSION_ID=3.9.4&NETDATA_SYSTEM_OS_DETECTION=/etc/os-release&NETDATA_SYSTEM_KERNEL_NAME=Linux&NETDATA_SYSTEM_KERNEL_VERSION=4.15.0-42-generic&NETDATA_SYSTEM_ARCHITECTURE=x86_64&NETDATA_SYSTEM_VIRTUALIZATION=hypervisor&NETDATA_SYSTEM_VIRT_DETECTION=/proc/cpuinfo&NETDATA_SYSTEM_CONTAINER=docker&NETDATA_SYSTEM_CONTAINER_DETECTION=dockerenv'
```

@cakrit Removing the comma does not fix it. following gives the same error:

`    bind to = *:19999=dashboard|netdata.conf^SSL=optional *:19996=streaming^SSL=optional`

**Comment by pgassmann** [comment] 2019-07-15 14:51
It works when the `registry` endpoint is also enabled on that port:

all working configs:
```
    bind to = *:19999=dashboard|netdata.conf^SSL=optional *:19996=streaming
    bind to = *:19999=dashboard|netdata.conf^SSL=optional *:19996=streaming|dashboard|registry|badges|netdata.conf|management^SSL=optional
    bind to = *:19999=dashboard|netdata.conf^SSL=optional *:19996=streaming|registry^SSL=optional
```

not working:

```
    bind to = *:19999=dashboard|netdata.conf^SSL=optional *:19996=streaming^SSL=optional
```

**Comment by thiagoftsm** [comment] 2019-07-15 14:52
Hi @pgassmann , thank you very much by your feedback, you confirmed to me what I have found, I am already working to deliver a PR to fix it.

**Comment by pgassmann** [comment] 2019-07-15 14:53
Update: 
It works when a second endpoint is enabled.

~~~
bind to = *:19999=dashboard|netdata.conf^SSL=optional *:19996=streaming|management^SSL=optional
~~~

**Comment by thiagoftsm** [comment] 2019-07-15 14:56
Our problem is some combination of ACLs inside Netdata. I am investigating what are the combinations that are creating problem, thanks for your feed back, because you are helping to confirm some of them and you are saving me time with others.

**Comment by thiagoftsm** [comment] 2019-07-15 18:57
Hi @pgassmann ,

I finishied a lot of tests with the ACLs and I created the PR #6468 that will be merged soon that will fix this issue you related and we were missing.

Thank you a lot by all feed backs and of course to bring this issue for us!

**Comment by cakrit** [comment] 2019-07-16 08:13
We'll publish a patch to 1.16 when this issue and #6468 are resolved.

**Comment by splatt** [comment] 2019-07-16 10:09
> Update:
> It works when a second endpoint is enabled.
> 
> ```
> bind to = *:19999=dashboard|netdata.conf^SSL=optional *:19996=streaming|management^SSL=optional
> ```

I struggled with SSL streaming and found my way to this ticket.

It 'works' for me now, using the above suggestions, but the traffic is *not* encrypted, using either setting SSL=optional or SSL=force on the master and host:port:SSL on the slave.

**Comment by thiagoftsm** [comment] 2019-07-16 19:27
Hi @splatt , we already identificated the motive this was happening. And when we release the bug fix for the problem described initially here, it will have the fix that you reported too.

Best regards!

**Comment by splatt** [comment] 2019-07-16 21:15
> Hi @splatt , we already identificated the motive this was happening. And when we release the bug fix for the problem described initially here, it will have the fix that you reported too.
> 
> Best regards!

:-)  Wonderful. Thank you.

**Comment by thiagoftsm** [comment] 2019-07-18 14:04
Hi everyone,

I finished last night the PR #6468 that has the solution for everything described here and in the issue #6471, please, case you wanna test to confirm that everything was fixed before we merge, please let us know your results.

Best regards!

**Closed** 2019-07-25 16:43 UTC
Labels: area/streaming, bug
