### ISSUE TITLE
[Bug]: Anomaly Detection enabled by default for new installation

### ISSUE THREAD

**Issue by svrnwnsch** [netdata/netdata#13223] opened 2022-06-27 07:32 UTC
### Bug description

I installed netdata in version `v1.35.0-69-g7a14c6ae9` by default my netdata configuration only contains values I want to change. So the `[ml]` section is completely missing. 

Running with such a configuration resulted in netdata automatically starting the Anomaly Detection.
The documentation on: https://learn.netdata.cloud/guides/monitor/anomaly-detection still states that the machine learning should be disabled by default. 

### Expected behavior

I would expect that machine learning is disabled by default.

### Steps to reproduce

1. Install netdata
2. Set minimalist configuration with missting `[ml]` section as `netdata.conf`
3. Start netdata
...

### Installation method

kickstart.sh

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.4 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.35.0-69-g7a14c6ae9
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS=' 'ZLIB_CFLAGS= ' 'ZLIB_LIBS=-lz' 'UUID_CFLAGS= ' 'UUID_LIBS=-luuid'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by andrewm4894** [comment] 2022-06-27 12:24
Thanks @svrnwnsch - this is more like a little grey area in our docs. That page you mention was planned to be like a central landing page for all things ML or AD related once we had built out the main features. A while back i had just updated it to have the ml readme section while we built the Anomaly Advisor.  

As such it was just a temporary static copy of the [agent ML readme](https://github.com/netdata/netdata/blob/master/ml/README.md) from a while back. 

The agent ML readme gets automatically pulled into here: https://learn.netdata.cloud/docs/agent/ml

Now that we have the anomaly advisor and a couple other related features, it makese sense that i update this page to be more like the cental landing we wanted and also avoid any chance for confusion since that ml readme was itself not dynamic and so going a little stale. 

I have made [this PR](https://github.com/netdata/learn/pull/1078/) to fix this issue with the docs and make https://learn.netdata.cloud/guides/monitor/anomaly-detection more like this central landing page that brings it all together. You can see [my version here](https://github.com/andrewm4894/learn/blob/improve-anomaly-detection-guide/guides/monitor/anomaly-detection.md) until it gets merged.

So the behaviour you saw was expected - its just that the docs you were looking at were a little outdated and needed to be refactored anyway which is what my pr is a first stab at doing. 

Thanks for reporting as i may very well have forgotten about this and no doubt it could have confused other users!

**Comment by svrnwnsch** [comment] 2022-06-30 08:41
Okay I was not aware of the change to have `ml.enabled = true` by default. I only checked the release notes. This caused some performance problems on my VM due to now higher CPU usage of netdata.

**Comment by svrnwnsch** [comment] 2022-06-30 16:07
There is a low level 2cpu b-series vm (Standard_B2s) on azure running they have some credits on how much CPU you can use.
There are some docker images running. Netdata is collecting 2.565 metrics every 2 seconds.
It seemed that the CPU usage of netdata increased over time after installation.
I assume over time more and more data existed to train the ML algorithm which caused higher CPU usage.

At some point all CPU credits of the B-Series were consumed which could have resulted in potential degradation of the other services running on the vm.

See this azure monitoring: 
![grafik](https://user-images.githubusercontent.com/1852828/176725133-460f5c76-8aa4-4b16-b569-d7f8e5bce352.png)

blue is the CPU%. Orange is the CPU credits of the VM. At some point netdata used more then the magical 60% baseline CPU.

After figuring out the problem I disabled ML manually on netdata which solved the problem.

**Comment by andrewm4894** [comment] 2022-06-30 17:37
hmm - thanks @svrnwnsch i'll try recreate a similar set up on such Azure VM and see what i can see. 

> I assume over time more and more data existed to train the ML algorithm which caused higher CPU usage.

It will by default max out at last `14400`, so ~4 hours, observations based on the `maximum num samples to train` param. 

https://learn.netdata.cloud/docs/agent/ml#configuration

So after its had 4-5 hours it should sort of be in a steady state in terms of the ML overhead.

Anyway - ill have a look on my end and see what i can find. Thanks for the feedback!

**Comment by andrewm4894** [comment] 2022-06-30 17:39
adding PR to clean up the original docs as reference: https://github.com/netdata/netdata/pull/13238

**Comment by andrewm4894** [comment] 2022-07-04 14:28
I have a b1s and b2s node running on Azure and have ML enabled. Going to give it 24 hours and see how things look then in Netdata and Azure monitoring.

**Comment by andrewm4894** [comment] 2022-07-05 09:15
I have had both a b1s (dev) and b2s (dev-b2s) running for 24 hours now just with default set up - looks like about 1500 metrics on each by default. Both running `v1.35.0-130-nightly`.

All looking ok to me in terms of the ML running fine with little overhead as far as i can see. Obviously with nothing else going on these machines this is not conclusive or anything but i just wanted to make sure at least this all works ok. 

So I'm happy that things look to be working as expected on either a B1S or B2S, but maybe we'd need to dig in more to fully get to root cause of the original behaviour @svrnwnsch was reporting. At least for me simple first test things look ok and we can be mindful if anyone else reports similar. 

I think we should also improve [our telemetry](https://learn.netdata.cloud/docs/agent/anonymous-statistics#agent-backend---anonymous-statistics-script) to add netdata metrics like cpu and memory usage etc since it would not be hard and would let us more proactively spot cases where on average netdata uses more resources than expected etc. I will make an issue for this.

my b1s:
![image](https://user-images.githubusercontent.com/2178292/177291086-910b5a57-1f8a-4f2b-b406-e47aec5c5f4e.png)

my b2s:
![image](https://user-images.githubusercontent.com/2178292/177291269-7a2f1fb4-e3e2-4b4e-9c27-a2ecdef3f792.png)

(around 8:00 on below charts im pretty sure is just netdata updating and can be ignored)

Apps CPU from Netdata:
![image](https://user-images.githubusercontent.com/2178292/177291694-03420989-4086-4e66-90bc-9b42f711e959.png)

Apps Mem from Netdata:
![image](https://user-images.githubusercontent.com/2178292/177292227-c75ecc07-c082-4777-bae8-0f1ba72b12f8.png)

ML detection worker threads:
![image](https://user-images.githubusercontent.com/2178292/177293430-03118524-f328-41c2-b55a-f2d886f7bbc0.png)

ML training worker threads:
![image](https://user-images.githubusercontent.com/2178292/177293548-2e923bab-4bb0-44b9-b1cb-4ae16614bf74.png)

Anomaly detection charts showing trained about ~1500 dims on each node:
![image](https://user-images.githubusercontent.com/2178292/177291908-cd34e0f3-dae7-404d-816d-b0dd34a938ab.png)

Overall orange line and blue line close here so most of the metrics/dims got trained:
![image](https://user-images.githubusercontent.com/2178292/177292066-b8232412-88aa-44b3-b145-be0e070c33af.png)

**Comment by MrZammler** [comment] 2023-10-31 09:00
I think we can close this. @svrnwnsch if possible, please report back if there are still performance issues with ML in latest Netdata releases.

**Closed by MrZammler** 2023-10-31 09:00 UTC
Labels: priority/medium, area/ml, data-products-team
