### ISSUE TITLE
freeipmi plugin died and did not restart

### ISSUE THREAD

**Issue by gregjhogan** [netdata/netdata#6698] opened 2019-08-21 03:29 UTC
##### Bug report summary
I am seeing an 'Inlet Temp' as 41 C but if I query the sensor with `ipmimonitoring` it shows 31C and has been for hours.  For some reason this temperature sensor (and others) stopped updating.

![image](https://user-images.githubusercontent.com/4112046/63400157-af444900-c387-11e9-81ac-909b4d81a6b8.png)

If I hit the HTTP API endpoint, it reports 41C, but the timestamp is from 5 hours ago!
```
curl 'http://localhost:19999/api/v1/data?chart=ipmi.temperatures_c&dimension=Inlet%20Temp&after=-60&before=0&points=60&group=average&gtime=0&format=json&options=seconds'
{
 "labels": ["time", "Inlet Temp"],
    "data":
 [
      [ 1566339980, 41],
      [ 1566339975, 41],
      [ 1566339970, 41],
      [ 1566339965, 41],
      [ 1566339960, 41],
      [ 1566339955, 41],
      [ 1566339950, 41],
      [ 1566339945, 41],
      [ 1566339940, 41],
      [ 1566339935, 41],
      [ 1566339930, 41],
      [ 1566339925, 41]
  ]
```

I see the time window in the UI also ends 5 hours ago (which is really confusing because it is aligned vertically with current readings from other things that are still updating).  Seems like it is just this one plugin that is hung up.  I have a bunch of other identical servers that are updating successfully.  What should I do to resolve this and prevent it in the future?

Thanks!

##### OS / Environment
ubuntu 16.04

##### Netdata version (ouput of `netdata -V`)
netdata v1.16.1

##### Component Name
freeipmi.plugin

##### Steps To Reproduce
not sure

##### Expected behavior
up to date temperatures

**Comment by gregjhogan** [comment] 2019-08-21 05:20
FYI, I am running the stock config (no changes after install)
Restarting the `netdata` service got the data flowing again
Here is the [error.log](https://github.com/netdata/netdata/files/3523630/error.log)

**Comment by cakrit** [comment] 2019-08-21 08:02
@vlvkobal I see the following:
```
2019-08-20 15:26:24: freeipmi.plugin ERROR : MAIN : ipmi_monitoring_sel_by_record_id(): internal IPMI error (errno 2, No such file or directory)
2019-08-20 15:26:24: freeipmi.plugin FATAL : MAIN :data collection failed. # : Success
```

Regardless of the cause, I don't get we don't retry the plugin after the failure, since it has collected data in the past. Looks like a logic gap in the handling of this type of failure?

**Comment by ilyam8** [comment] 2019-08-21 08:54
> I don't get we don't retry the plugin after the failure

I see there is some `SERIAL_FAILURES_THRESHOLD`, pluginds gives up on retrying in num of failures in a `row >  SERIAL_FAILURES_THRESHOLD`

https://github.com/netdata/netdata/blob/d1c5937e71fac294472d1cbdc1ef17d43f4a755b/collectors/plugins.d/plugins_d.c#L701-L717

**Comment by cakrit** [comment] 2019-08-21 08:57
Yes, I didn't see these types of log messages around that time, you can check it. We probably never went to that part of the code in this case.

**Comment by ilyam8** [comment] 2019-08-21 09:03
error

```
2019-08-20 15:26:24: freeipmi.plugin ERROR : MAIN : ipmi_monitoring_sel_by_record_id(): internal IPMI error (errno 2, No such file or directory)
2019-08-20 15:26:24: freeipmi.plugin FATAL : MAIN :data collection failed. # : Success
2019-08-20 22:06:46: netdata ERROR : PLUGINSD[freeipmi] : read failed: end of file
2019-08-20 22:06:46: netdata ERROR : PLUGINSD[freeipmi] : '/usr/libexec/netdata/plugins.d/freeipmi.plugin' (pid 17964) disconnected after 10280 successful data collections (ENDs).
2019-08-20 22:06:46: netdata ERROR : PLUGINSD[freeipmi] : child pid 17964 exited with code 1.
```

error handling
```
2019-08-20 22:06:46: netdata ERROR : PLUGINSD[freeipmi] : '/usr/libexec/netdata/plugins.d/freeipmi.plugin' (pid 17964) exited with error code 1, but has given useful output in the past (10280 times). Waiting a bit before starting it again.
2019-08-20 22:06:47: netdata INFO  : PLUGINSD : stopping plugin thread: plugin:freeipmi
2019-08-20 22:06:47: netdata INFO  : PLUGINSD[freeipmi] : data collection thread exiting
2019-08-20 22:06:47: netdata INFO  : PLUGINSD[freeipmi] : killing child process pid 17964
2019-08-20 22:06:47: netdata ERROR : PLUGINSD[freeipmi] : Request to kill pid 17964, but it is not running. (errno 3, No such process)
2019-08-20 22:06:47: netdata INFO  : PLUGINSD[freeipmi] : thread with task id 17949 finished
2019-08-20 22:06:47: netdata INFO  : PLUGINSD[freeipmi] : thread created with task id 177022
2019-08-20 22:06:47: netdata INFO  : PLUGINSD[freeipmi] : connected to '/usr/libexec/netdata/plugins.d/freeipmi.plugin' running on pid 177034
2019-08-20 22:06:47: freeipmi.plugin ERROR : MAIN : update frequency 1 seconds is too small for IPMI. Using 5.
2019-08-20 22:07:05: netdata INFO  : PLUGINSD[freeipmi] : File /var/cache/netdata/ipmi.events/main.db is too old. Clearing it.
2019-08-20 22:07:05: netdata INFO  : PLUGINSD[freeipmi] : File /var/cache/netdata/ipmi.events/events.db is too old (last collected 24045 seconds ago, but the database is 19980 seconds). Clearing it.
```

**Comment by ilyam8** [comment] 2019-08-21 09:11
ops, i am wrong, didnt look at the timestamps 🙈

**Comment by ilyam8** [comment] 2019-08-21 09:34
btw @cakrit 	

the issue is

> ipmi reporting data from 5 hours ago, but graph shows the data as current
> from 5 hours ago, but graph shows the data as current

**Comment by ilyam8** [comment] 2019-08-21 09:59
I dont understand why netdata didnt restart it

> 2019-08-20 15:26:24: freeipmi.plugin FATAL : MAIN :data collection failed. # : 
Success

That means that freeipmi process exits using `fatal` (code 1).

This is ok, pluginsd is able to handle it, there should be a message right after process exited

> 2019-08-20 22:06:46: netdata ERROR : PLUGINSD[freeipmi] : read failed: end of file

But there is no 🤔

**Comment by gregjhogan** [comment] 2019-08-21 17:41
> btw @cakrit
> 
> the issue is
> 
> > ipmi reporting data from 5 hours ago, but graph shows the data as current
> > from 5 hours ago, but graph shows the data as current

oh sorry, title is not accurate, I will update the title

initially I didn't realize that what the UI displayed as the right hand edge of this one graph was 5 hours in the past (very confusing that all graphs in UI do not share the same time window)

**Comment by ilyam8** [comment] 2019-08-21 17:49
> (very confusing that all graphs in UI do not share the same time window)

i agree, sounds like an issue to me @cakrit

**Comment by cakrit** [comment] 2019-08-21 18:08
We'll need to try and replicate the behavior (not necessarily with this plugin) and see where the issue is.

**Comment by gregjhogan** [comment] 2019-08-21 18:11
what can I do to help?  it happened again already

[error.log](https://github.com/netdata/netdata/files/3526649/error.log)

[error.1.log](https://github.com/netdata/netdata/files/3526651/error.1.log)

**Comment by gregjhogan** [comment] 2019-08-21 18:14
wait, maybe it didn't happen again.  the ipmi graphs in the UI were all blank, but now they look fine after refreshing the UI.  either way, let me know what to do next time I see it happen, or if you want me to do anything pro-actively

thanks!

**Comment by ilyam8** [comment] 2019-08-21 18:19
> That means that freeipmi process exits using fatal (code 1).

I repliced it with python.d, i changed the code to `exit(1)` every 10 seconds, pluginds handles it pretty well. I think i missed something ¯\_(ツ)_/¯

**Comment by Saruspete** [comment] 2019-09-04 21:42
Hello,

From the name of the temperature probes, I expect the hardware to be a Dell Poweredge, so the values are reported by the idrac (would be the same for HP server, through the ILO).

As seen in the log, the default reporting time of 1 is pushed to 5. 
Generally speaking, these BMC are not very beefy, and their access through /dev/ipmi0 may be somewhat messy and not handle errors very well.

Should the issue arise again, try to reboot the bmc (not the server) to see if it can unblock the plugin:
- IPMI: `ipmitool bmc reset cold`
- Dell iDRAC:  `racadm racreset soft`
- HP iLO: `echo -e 'cd /map1\nreset' | ssh you-ilo`

As a general advice, try to not poll the data faster than 10sec, monitor the usage of the ipmi_module.
If you see a high cpu usage, the [Kernel documentation](https://www.kernel.org/doc/Documentation/IPMI.txt) recommands tunning a parameter:

```
echo 100 > /sys/module/ipmi_si/parameters/kipmid_max_busy_us
```
to wait 100us before sleeping for a tick (often 1ms).

**Comment by stelfrag** [comment] 2019-11-13 09:36
Following up on this

Hi @gregjhogan have you had any more problems with this lately? If everything looks OK, I will close this issue in a couple of days.

**Comment by stelfrag** [comment] 2019-11-21 12:43
Closing, we can revisit if there is new information available

**Closed by stelfrag** 2019-11-21 12:43 UTC
Labels: area/collectors, bug, priority/medium
