### ISSUE TITLE
Netdata slave/clients should buffer and resend data when master is back in service

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#2061] opened 2017-04-06 15:37 UTC
Currently we seem to be losing metrics for the period when Netdata master goes out of service, for upgrade, maintenance etc. There should be a option for the slave to hold the data locally  (map/save/memory) in case if the master is not reachable. 

It can maintain an offset of some sort for the data that has been sent so far especially if the slave is also persisting data on its end. So that when the master returns all data since offset marker can be dispatched to cover any gaps from outage.

**Comment by ktsaou** [comment] 2017-04-06 22:43
yes, it should.

The problem is that when they disconnect, the slave needs to re-send all chart definitions since it cannot know if the master is aware of the charts (the master will not, if it just restarted).

It can be done though...

**Comment by gamefundas** [comment] 2017-05-15 02:04
Can redis pubsub play as backup here such that the Slave nodes start transmitting message to redis soon as the connectivity to master is lost. Master be be subscribed to the redis topic so it can recover from where it left off.

**Comment by gamefundas** [comment] 2017-05-18 10:41
Read your comments again on this. So it's not about the missing data, the slaves need to send the entire set of chart definitions again. On reconnect then this might be the first thing to do and then send the data. Should be the same as first time when a slave connects to master. I am sure there is more to this.

**Comment by ktsaou** [comment] 2017-05-18 11:20
> I am sure there is more to this.

yes, there are a lot more. The most important is that the protocol will need to be extended a bit, to allow adding past data to the database.

**Comment by ktsaou** [comment] 2018-11-23 13:19
@cakrit 	this is on our roadmap (use the database to avoid gaps when streaming).
It requires a new protocol for slave->master communication.

**Comment by gamefundas** [comment] 2019-10-27 18:39
@cakrit  I believe this has been addressed in one of the recent release where the client/agent retains the data in the file system and then resends when the stream connection is restored.

**Comment by cakrit** [comment] 2019-10-27 18:50
@thiagoftsm can you verify and close if this is the case?

**Comment by thiagoftsm** [comment] 2019-10-28 00:20
@cakrit I think this problem continues, I ran a test where both master and slave are using `dnengine`, I stopped the master during few seconds as you can see in the next image

![master1](https://user-images.githubusercontent.com/49162938/67644315-76d96200-f918-11e9-8bd1-327a0b131862.png)

and during this interval, I did not stop the slave, but I had gaps on the slave too 

![slave1](https://user-images.githubusercontent.com/49162938/67644319-7e990680-f918-11e9-9096-87c8c8791cad.png)

Considering that we have now the dbengine, we can fix this.
Our current code has structure to restart the communication when the connection is lost, but it does not restart from the last message sent.

**Comment by ilyam8** [comment] 2021-07-08 13:33
Will be fixed when https://github.com/netdata/netdata/pull/9832 is merged

**Closed by ilyam8** 2021-07-08 13:33 UTC
Labels: area/streaming, feature request, priority/high
