### ISSUE TITLE
How to get streaming working?

### ISSUE THREAD

**Issue by nraynaud** [netdata/netdata#6826] opened 2019-09-11 20:52 UTC
##### Question summary
  I have set up a very bare bone streaming system, and the streaming host doesn't show up in the web interface, but shows up in the access.log and error.log
##### OS / Environment
  Linux XCP-ng (centos) / debian 
##### Expected results
  I would expect to see the streaming host in the web interface.

I have put a few relevant files in this gist: https://gist.github.com/nraynaud/7d9d3d91f11df8320a2e6ed9252d5b6d

both side of the stream run in a virtualbox VM, I guess that's where the timing warnings come from.

Thanks for your help.

**Comment by cakrit** [comment] 2019-09-13 07:43
This doesn't look like a bug in 1.12, but a compatibility issue in the newer versions. The master believes it's done it's job and is waiting for data. The slave doesn't understand the master's response, ergo the message "is it a netdata"? I believe we need to try and replicate the situation with a v1.12 master and a v1.17.1 slave, to see if any of the recent changes have broken compatibility.  

Of course @nraynaud that doesn't mean you shouldn't upgrade your master, we always have lots of goodies in each new version! :)

**Comment by thiagoftsm** [comment] 2019-09-13 11:20
Hi @cakrit,

I will test try to replicate the situation now , as I said for @nraynaud one of my suggestions to update was to fix possible errors, but we are always keeping backward compatibility .
I will bring updates as soon I finish the tests.

**Comment by thiagoftsm** [comment] 2019-09-13 23:32
Hi @cakrit  and @nraynaud ,

I installed a VM with Debian 9.11 and in this VM I installed Netdata 1.12.1 after this I set it as slave of a Master running Netdata 1.17.1, I could not identify any problem between the communication  channel, so the compatibility was not broken.

After to obtain the previous results, I decided to read again the logs that was sent to us in this issue and I verified that we have the following lines:

```
2019-09-11 13:34:00: netdata INFO  : WEB_SERVER[static1] : STREAM [receive from [172.22.111.213]:49406]: request has parameter 'c73948ee-c9db-11e9-93b0-08002720c76c' = '"XCP-ng"', which is not used.
2019-09-11 13:34:00: netdata INFO  : WEB_SERVER[static1] : STREAM [receive from [172.22.111.213]:49406]: request has parameter 'c73948ee-c9db-11e9-93b0-08002720c76c' = 'xenenterprise', which is not used.
2019-09-11 13:34:00: netdata INFO  : WEB_SERVER[static1] : STREAM [receive from [172.22.111.213]:49406]: request has parameter 'c73948ee-c9db-11e9-93b0-08002720c76c' = 'centos rhel fedora', which is not used.
2019-09-11 13:34:00: netdata INFO  : WEB_SERVER[static1] : STREAM [receive from [172.22.111.213]:49406]: request has parameter 'c73948ee-c9db-11e9-93b0-08002720c76c' = '8.0.0', which is not used.
2019-09-11 13:34:00: netdata INFO  : WEB_SERVER[static1] : STREAM [receive from [172.22.111.213]:49406]: request has parameter 'c73948ee-c9db-11e9-93b0-08002720c76c' = '8.0.0', which is not used.
```

This helped to remember me something, few days ago an user reported in a issue that he had problem after an update, in his report he said that he lost completely the capability to use SSL in his stream after an update. After few messages we discover that the problem that he had was due the fact his provider had set a repository that was not official and the openssl library was compiled wrong, after to describe this situation,  @nraynaud I have a question, did you get Netdata from our official repository (https://docs.netdata.cloud/packaging/installer/)?

**Comment by thiagoftsm** [comment] 2019-09-13 23:33
I forgot to mention, the logs that you are seeing in the previous message is not hoped, so the message format has a problem.

**Comment by nraynaud** [comment] 2019-09-14 00:01
Hi @thiagoftsm thank you for your exploration. I did not configure SSL purposefully, so it should not be a factor.

About the packaging: we packaged it ourselves internally, so that might be a factor, the RPM recipe ought to be open source. @stormi do you want to explain the creation of the RPM?

**Comment by thiagoftsm** [comment] 2019-09-14 00:17
Netdata released our own RPM version few weeks ago, you can find the spec in our github, here it is the link ( https://github.com/netdata/netdata/blob/master/netdata.spec.in ). 

I did not create this spec file, but I helped to debug and I tested everything until we release the RPMs, case you have any doubt, please let me know.

**Comment by stormi** [comment] 2019-09-14 12:32
My package also comes from https://github.com/netdata/netdata/blob/master/netdata.spec.in which I have adapted, mostly to avoid dynamically downloading go.plugin.d during the build (that's bad practice and build systems for linux distros explicitly disable that. As we use Fedora's Koji as a build system, even if I wanted to I couldn't let that happen.) and to try to fix file modes according to https://github.com/netdata/netdata/issues/6619.

Our spec file is there: https://github.com/xcp-ng-rpms/netdata/blob/master/SPECS/netdata.spec

I tried my best no to break anything with my changes, but I don't promise I haven't :)

**Comment by cakrit** [comment] 2019-09-15 11:44
Thanks for the info gents, it's clearer now. Unfortunately we don't currently have the capacity to help with a deep dive into that spec file. However, I doubt that the packaging is at fault here, since you're supposedly not using SSL at all in the communication. @nraynaud, the only suggestions I can think of at this point are the following:
- Upgrade the master version, using the installation method of your choice (not sure if you can use @stormi's package on that server, but perhaps try it.
- If you're still facing problems, try one of our supported installation methods on both the master and the slave (first ensure you back up your configs before uninstalling the packages and then proceed with the installation and put the configs back). Depending on the results, we'll at least know if the package has anything to do with it, or if there's something else going on with your specific configuration.

**Comment by thiagoftsm** [comment] 2019-09-15 12:52
Hi everybody,

I compare both specs and I verified that at least the package dependency are correct between the official repository and @stormi spec file. 

I also did not test @stormi RPM, but he can get more details how the official Netdata is working in our documentation ( https://packagecloud.io/netdata/netdata ) and compare the behavior of official RPM with his RPM.

Best regards.

**Comment by thiagoftsm** [comment] 2019-09-27 12:26
Hi @stormi and @nraynaud ,

Could you solve your problem updating your RPM? Is the streaming working without any problem?

Best regards.

**Comment by nraynaud** [comment] 2019-09-27 12:31
I am sorry, I have been preempted by a few other things since then, I have not worked on this subject.

**Comment by thiagoftsm** [comment] 2019-09-27 12:37
All right, I asked you, because I am doing a complete review in our stream channel and case the problem is present yet we fix this for you and our users in the next days.
I will use this message to ask you something, what is your ```memory mode``` in both master and slave? We had an user with a problem like yours these days and after he changes the memory mode, everything began to work.

**Comment by nraynaud** [comment] 2019-09-27 12:43
I intend to use memory mode on both sides. I'll be out of tempo for the review if I find an actual issue. I came here looking for help with configuration and use, we are still a long ways before finding an actual bug in the code.

**Comment by thiagoftsm** [comment] 2019-09-27 13:23
Ok, let us know case we can help you.

**Comment by cakrit** [comment] 2019-10-06 10:51
@nraynaud the discussion in #6852 may be useful for your case as well. I'm closing this, but please comment again if you're facing a different issue.

**Closed by cakrit** 2019-10-06 10:51 UTC
Labels: area/streaming, question
