### ISSUE TITLE
 Installation issue: Found existing install of Netdata under: /

### ISSUE THREAD

**Issue by gouthamravee** [netdata/netdata#10330] opened 2020-12-06 20:05 UTC
##### Bug report summary
Re-installing netdata using the kickstarter script on a Proxmox machine results in the error below:
```
 --- Found existing install of Netdata under: / ---
 --- Existing install appears to be handled manually or through the system package manager. ---
 ABORTED  Existing installation detected which cannot be safely updated by this script, refusing to continue.
```

Using bash `<(curl -Ss https://my-netdata.io/kickstart.sh) --allow-duplicate-install `works

I also found a symlink to netdata-updater and a file called 'netdata-updater.log.UKLJ5O' in / on the proxmox server. 
Contents of the log file are: 
```
curl: (7) Failed to connect to storage.googleapis.com port 443: Connection refused
Sun 14 Jun 2020 06:56:10 AM EDT : ERROR:  FAILED TO UPDATE NETDATA : Cannot download https://storage.googleapis.com/netdata-nightlies/sha256sums.txt
cat: /netdata-updater.log.UKLJ5O: input file is output file
```

I saw a similar bug here - https://github.com/netdata/netdata/issues/9772
There's a valid work around, but created this ticket to provide more info in case it helps. 
Can be closed if not applicable. 

##### OS / Environment

Linux pmx2 5.4.73-1-pve #1 SMP PVE 5.4.73-1 (Mon, 16 Nov 2020 10:52:16 +0100) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"

##### Netdata version

 Netdata install, nothing is running at this point. Used the commands below to remove previous netdata install, unfortunately do not remember what method I used to install netdata. 

sudo systemctl stop netdata
sudo systemctl disable netdata
sudo systemctl unmask netdata
sudo rm -rf /lib/systemd/system/netdata.service
sudo rm -rf /lib/systemd/system/netdata-updater.service
sudo rm -rf /lib/systemd/system/netdata-updater.timer
sudo systemctl daemon-reload
 
sudo apt --purge remove netdata
sudo /usr/libexec/netdata/netdata-uninstaller.sh --yes --env /etc/netdata/.environment

##### Steps To Reproduce

1. setup proxmox using - https://www.proxmox.com/en/proxmox-ve/get-started
2. install netdata but make sure not to document anything about the process
3. wait a year or so
4. realize you screwed up installing netdata and try to redo the install using the kickstarter script
5. be thankful for the netdata devs for including the --allow-duplicate-install  flag

##### Expected behavior
Netdata re-install should work fine

**Comment by Ferroin** [comment] 2020-12-07 12:48
This is expected behavior if the kickstart script cannot figure out what type of install the existing installation is. It’s a safety net to prevent people from ending up with completely broken installs by doing things like installing through their package manager, installing over top of that with the kickstart script, and then removing the version from the package manager (which will usually break the kickstart install).

It sounds like you may have ended up in such a situation yourself before trying to run the kickstart script most recently, and that will unfortunately also be seen by the kickstart script as a state that it’s not safe to install over top of.

**Comment by gouthamravee** [comment] 2020-12-07 14:54
Thank you for the reply Ferroin! 

Its been a while since I setup both my proxmox servers but I have setup netdata on both in different manners over time so you're right, its possible I have some bad netdata installs on there. 

I have tried to remove all netdata installs through apt and by running the uninstall script as described in the "Netdata Version" section in the report. Are there any other things I should do to make sure I have removed everything pertaining to Netdata before trying the kickstarter script? 

Though as of right now I don't have any issues with Netdata on proxmox, running the kickstarter script with the '--allow-duplicate-install' flag worked well enough.

**Comment by Ferroin** [comment] 2020-12-07 16:07
If you’ve tried through both the package manager and the uninstaller, that _should_ cover everything. If it doesn’t it’s probably a bug somewhere.

More specifically, what the installer is actually doing here is looking for `netdata` in in the configured binary search path, and if it finds it then looking for the file `/etc/netdata/.environment`. If that file is present, it assumes that this is an install handled through one of our installers, otherwise it assumes it was done some other way.

Also, if it finds what it thinks is an existing install done through one of our installers and is able to find the updater script for that install, it will run that instead of doing a clean install (the intent here is that this way you can just run the kickstart script and be certain you have the newest version of Netdata if the script finishes successfully).

**Comment by gouthamravee** [comment] 2020-12-07 19:00
Yup i tried the package manager and uninstaller methods, so probably some weird remnant somewhere. I believe the uninstaller deletes every possible file that's related to netdata.

Anyways if you want to close this ticket by all means go ahead, the allow duplicates flag lets me install without issues and I only had this issue with proxmox. One thing to note is I had this issue on both my proxmox servers, but none of the VMs running on either proxmox instance. 

Looking at htop or services I don't see any issues with duplicate instances of netdata or anything breaking there. I do plan on spinning up another proxmox instance in the next few months, so if I see this again I'll open a ticket with more info, or add to this ticket if that's better. 

Thank you for the prompt reply and additional details on the installer, all very good info.

**Comment by jordihuertas** [comment] 2021-05-16 15:03
Maybe a little later but I had the same problem and I have found a solution.

I have uninstalled netnada to reinstall it without stopping the service, so netdata uninstaller removed all the files but left some trash behind, included the netdata service running.

So I have searched with `sudo find / -iname '*netdata*'` netdata files and I have removed them manually.
After this action, I have run the installer without any problem.

**Comment by OdysLam** [comment] 2021-05-17 08:08
Hey @jordihuertas can you give us information about your OS?

@Ferroin should it be troubling that the uninstaller left over files?

**Comment by Ferroin** [comment] 2021-05-17 12:55
> @Ferroin should it be troubling that the uninstaller left over files?

The uninstaller _should_ be stpping the Netdata service before it tries to remove anything if it0s running. If that fails, then some files being left behind is expected and there’s not really anything we can do about it.

**Comment by jordihuertas** [comment] 2021-05-17 13:34
@OdysLam my OS is Ununtu Server 20.04 LTS

**Comment by Jayto1** [comment] 2021-05-23 22:37
> Maybe a little later but I had the same problem and I have found a solution that worked for me.
> 
> I uninstalled netnada to reinstall it without stopping the service, so netdata uninstaller removed all the files but left some trash behind, included the netdata service running.
> But it removed `/etc/netdata/.environment` file.
> 
> So I searched with `sudo find / -iname '*netdata*'` netdata files and I removed them manually.
> After this action, I run the installer without any problems.

Thank you so much I've spent the past couple of days trying to figure out how to remove Netdata from Raspbian and this was the only solution that worked. Much love

**Comment by jordihuertas** [comment] 2021-05-24 05:46
@Ferroin, maybe the bug is not related to the operating system, but to the motherboard. I am also running it on a **Raspberry Pi**, like @Jayto1, who is using Raspbian.
Maybe it is due to low ram memory or a small processor?

**Comment by Jayto1** [comment] 2021-05-24 05:58
I don't know anything about Linux or how the code works but all I can tell you is that I reinstalled Netdata on my Ubuntu Server (PC) and it actually worked. Un-claiming it was very buggy but this was the case on my Raspberry Pi too. If there is any info you need from me let me know, more than glad to help.

**Comment by iconoclasthero** [comment] 2021-09-25 13:53
My initial install was done via apt and then I saw this on [url=https://linuxhint.com/how-to-install-netdata-monitoring-tool-on-ubuntu-20-04/] _Linux Hint_ suggesting the use of the kickstarter script.

I did an apt remove and then an apt purge and when I still got the ABORTED message, I did a `find / -iname "netdata*" -type d -exec mv {} {}~ \;` (ok: I did the -exec part manually, might not work) which obviously should remove the /etc/netdata/.environment file to a different directory **but it doesn't exist**:
```
$ ll /etc/netdata~/
total 44
drwxr-xr-x   7 root root  4096 Sep 24 08:23 ./
drwxr-xr-x 164 root root 12288 Sep 25 09:49 ../
drwxr-xr-x   2 root root  4096 Apr  9  2020 charts.d/
-rwxr-xr-x   1 root root  2358 Apr  9  2020 edit-config*
drwxr-xr-x   2 root root  4096 Apr  9  2020 health.d/
-rw-r--r--   1 root root   488 Apr  9  2020 netdata.conf
drwxr-xr-x   2 root root  4096 Apr  9  2020 node.d/
-rw-r--r--   1 root root     0 Apr  9  2020 .opt-out-from-anonymous-statistics
drwxr-xr-x   2 root root  4096 Apr  9  2020 python.d/
drwxr-xr-x   2 root root  4096 Apr  9  2020 statsd.d/
```

I also did all of this:

sudo systemctl stop netdata
sudo systemctl disable netdata
sudo systemctl unmask netdata
sudo rm -rf /lib/systemd/system/netdata.service
sudo rm -rf /lib/systemd/system/netdata-updater.service
sudo rm -rf /lib/systemd/system/netdata-updater.timer
sudo systemctl daemon-reload

sudo apt --purge remove netdata
sudo /usr/libexec/netdata/netdata-uninstaller.sh --yes --env /etc/netdata/.environment

In the end I gave up and did the --allow-duplicates install.

**Comment by shellshock1953** [comment] 2021-09-27 08:48
Got same issue, uninstalled netdata using apt
but kickstart.sh runs only after apt autoclean:
`sudo apt autoclean`

**Comment by Ferroin** [comment] 2022-02-22 16:09
This should be essentially fixed now with the current kickstart script except for some uncommon edge cases.

If you still are seeing an issue like this, please open a new bug report with more specific details.

**Closed by Ferroin** 2022-02-22 16:09 UTC
Labels: bug, area/packaging

**Comment by tbarbette** [comment] 2022-10-18 10:32
The --allow-duplicate-install flag appears to be removed. It worked with "--reinstall" though.

**Comment by alirizaaribas-ibg** [comment] 2022-10-29 12:50
Nothing worked even I didn't set any custom style or install any netdata:

```
[root@node003 tmp]# wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --reinstall
--2022-10-29 15:47:46--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 188.114.96.7, 188.114.97.7, 2a06:98c1:3121::7, ...
Connecting to my-netdata.io (my-netdata.io)|188.114.96.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

    [ <=>                                             ] 78,147      --.-K/s   in 0.06s

2022-10-29 15:47:46 (1.16 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [78147]


 --- Using /tmp/netdata-kickstart-i4W4XibsSV as a temporary directory. ---
 --- Checking for existing installations of Netdata... ---
 WARNING  Found an existing netdata install at /, but could not determine the install type. Usually this means you installed Netdata through your distribution’s regular package repositories or some other unsupported method.

 --- Found an existing netdata install at /, but user requested reinstall, continuing. ---
Reinstalling over top of a unknown installation may be unsafe, do you want to continue? [y/n]
y
 --- OK, continuing. ---
 --- Attempting to install using native packages... ---
 --- Repository configuration is already present, attempting to install netdata. ---
 --- Checking for libuv availability. ---
[/tmp/netdata-kickstart-i4W4XibsSV]# env yum install netdata
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.turhost.com
 * epel: mirror.telepoint.bg
 * extras: centos.turhost.com
 * updates: centos.turhost.com
Package netdata-1.36.1-1.el7.x86_64 already installed and latest version
Nothing to do
 OK

 WARNING  Could not find netdata-updater.sh. This means that auto-updates cannot (currently) be enabled on this system. See https://learn.netdata.cloud/docs/agent/packaging/installer/update for more information about updating Netdata.

Successfully installed the Netdata Agent.

The following non-fatal warnings or errors were encountered:

  - Found an existing netdata install at /, but could not determine the install type. Usually this means you installed Netdata through your distribution’s regular package repositories or some other unsupported method.
  - Could not find netdata-updater.sh. This means that auto-updates cannot (currently) be enabled on this system. See https://learn.netdata.cloud/docs/agent/packaging/installer/update for more information about updating Netdata.

Official documentation can be found online at https://learn.netdata.cloud/docs/.

Looking to monitor all of your infrastructure with Netdata? Check out Netdata Cloud at https://api.netdata.cloud.

Join our community and connect with us on:
  - GitHub: https://github.com/netdata/netdata/discussions
  - Discord: https://discord.gg/5ygS846fR6
  - Our community forums: https://community.netdata.cloud/
[root@node003 tmp]#

```

**Comment by slrslr** [comment] 2023-05-20 11:49
@alirizaaribas-ibg what may help:
Debian/Ubuntu: sudo apt purge netdata*
CentOS/Fedora may work: yum remove netdata*;dnf remove netdata*

**Comment by dasbootbee** [comment] 2024-03-31 19:47
> @alirizaaribas-ibg what may help: Debian/Ubuntu: sudo apt purge netdata* CentOS/Fedora may work: yum remove netdata*;dnf remove netdata*

apt purge netdata* worked for me on proxmox 8.  apt remove netdata didn't get everything.
