### ISSUE TITLE
When will custom alarms be built in and can I help test it?

### ISSUE THREAD

**Issue by nsturtz** [netdata/netdata#9788] opened 2020-08-19 13:36 UTC
I am asking about the GUI alarms and what can I do to help? I would also like to say Thank you to everyone who has worked on the wonderful project!

**Comment by thiagoftsm** [comment] 2020-08-19 17:24
Hi @nsturtz,

If I understood correctly your question, we will need to do the following steps:

FrontEnd:

1 - It is necessary to create a PR at github.com/netdata/dashboard/ that will bring the new GUI. This GUI will need to give conditions for the users to set the possible values present in this [link](https://learn.netdata.cloud/docs/agent/health/reference)
2 - If you want to load the alarms applied on host to the GUI, you can use the endpoint `/api/v1/alarms?all`

@jacekkolasa , please, correct me if I missed something for frontend.

Backend:

The first step you can work without any iteration, but it won't be ready until we have an endpoint capable to store the  new alarm. When the frontend is ready, we will do the following changes to Netdata:

1 - We will create a new endpoint inside our Webserver to accept receiving data. Right now Netdata only accepts `GET`, STREAM` and `OPTIONS` as methods. If you can send data using GET, this will simplify the process inside the webserver.
2 - After the new file is created inside our internal structure, Netdata needs to be reload to apply it, this can be done using (health api)[https://github.com/netdata/netdata/tree/master/web/api/health]. 

Now I will describe some concerns I have and we will need to consider when you are creating the interface:

1 - This new endpoint will insert files probably inside `/etc/netdata/health.d`, we cannot install it in the default directory where alarms are stored, because they can be overwritten when Netdata is installed. 
2 - The new file needs following all the specifications that we have for alarms, you can see some examples [here](https://github.com/netdata/netdata/tree/master/health/health.d)
3 - The defined methods that we accept, are not used to send data to be stored inside a webserver, and in reality we won't store any possible alarm inside the web server directory,  it would be stored inside the configuration directory  so I would like to hear @cakrit , @amoss, @dim08   and probably @ktsaou about the possibility to bring this feature.

Best regards!

**Comment by nsturtz** [comment] 2020-08-19 20:01
Ok thank you and I can help test.

**Comment by cakrit** [comment] 2020-08-20 12:32
This is part of the configuration management epic, which we haven't put on the roadmap yet. So closing it as duplicate of #6432

**Closed by cakrit** 2020-08-20 12:32 UTC
Labels: area/health, area/web, no changelog, question

**Comment by ilyam8** [comment] 2020-08-20 14:46
@cakrit gratz on closing 5000th issue 🎉
