### ISSUE TITLE
Debian package missing directory creation

### ISSUE THREAD

**Issue by and0x000** [netdata/netdata#8439] opened 2020-03-19 15:02 UTC
##### Bug report summary
with the debian package from https://packagecloud.io/netdata/netdata the installation routine seems to miss some directories.

namely `/var/log/netdata` and `/var/cache/netdata`

##### OS / Environment

```
Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
cat /etc/debian_version 
10.3
```

##### Netdata version
```
netdata -v
netdata v1.20.0
```
 
##### Component Name
packaging

##### Steps To Reproduce
Install a fresh Debian 10.3

run 
```
curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.deb.sh | sudo bash
apt update && apt install netdata -y
systemctl status netdata
```

Check `/var/log/syslog` to find the following entries
```
Mar 19 11:55:11 Cannot cd to directory '/var/cache/netdata'
Mar 19 11:55:11 netdata[3516]: 2020-03-19 11:55:11: netdata FATAL : MAIN :Cannot cd to directory '/var/cache/netdata' # : No such file or directory
Mar 19 11:55:16 netdata: Cannot cd to directory '/var/log/netdata'
Mar 19 11:55:16 netdata[3518]: 2020-03-19 11:55:16: netdata FATAL : MAIN :Cannot cd to directory '/var/log/netdata' # : No such file or directory
```

Ways to fix this manually: Create both directories with the correct permissions.

##### Expected behavior
I would expect netdata to run out of the box from such a package. For me, this means, that either installation routine or netdata itself creates the necessary directories with the corresponding permissions for the service to run with it's default configuration.

**Comment by ilyam8** [comment] 2020-03-19 15:29
Hi @and0x000 it looks this issue is duplicate of #8405

**Closed** 2020-03-19 15:29 UTC
Labels: area/packaging, bug, duplicate, needs triage

**Comment by and0x000** [comment] 2020-03-19 15:38
Indeed, sorry I missed that. I was mostly looking for similar issues bearing the label `area/packaging`. Could you probably add this label to #8405 as well?
