### ISSUE TITLE
Cannot remove node in Nodes

### ISSUE THREAD

**Issue by felixonmars** [netdata/netdata#7417] opened 2019-12-04 10:06 UTC
### Bug report summary
In the nodes view, I have one mis-added node "arch" (currently shown as unavailable) and I want to remove it. However whenever I clicked it the whole web page went white and I cannot remove it.

If I take another node offline I can successfully click on it and there is a remove button. But for this one particular node the whole web page always turn completely white preventing me from removing it.

In browser console there is an error whenever I clicked on the node:
```
TypeError: "e.urls is null"
    renderURLsPanel https://netdata.cloud/static/console/main.js?v=4:1
    render https://netdata.cloud/static/console/main.js?v=4:1
    Eo https://netdata.cloud/static/console/main.js?v=4:1
    Co https://netdata.cloud/static/console/main.js?v=4:1
    Tf https://netdata.cloud/static/console/main.js?v=4:1
    di https://netdata.cloud/static/console/main.js?v=4:1
    oi https://netdata.cloud/static/console/main.js?v=4:1
    Qo https://netdata.cloud/static/console/main.js?v=4:1
    Vn https://netdata.cloud/static/console/main.js?v=4:1
    unstable_runWithPriority https://netdata.cloud/static/console/main.js?v=4:1
    Mn https://netdata.cloud/static/console/main.js?v=4:1
    Vn https://netdata.cloud/static/console/main.js?v=4:1
    Bn https://netdata.cloud/static/console/main.js?v=4:1
    ti https://netdata.cloud/static/console/main.js?v=4:1
    In https://netdata.cloud/static/console/main.js?v=4:1
main.js:1:50702
    No https://netdata.cloud/static/console/main.js?v=4:1
    callback https://netdata.cloud/static/console/main.js?v=4:1
    ya https://netdata.cloud/static/console/main.js?v=4:1
    ga https://netdata.cloud/static/console/main.js?v=4:1
    _i https://netdata.cloud/static/console/main.js?v=4:1
    unstable_runWithPriority https://netdata.cloud/static/console/main.js?v=4:1
    Mn https://netdata.cloud/static/console/main.js?v=4:1
    mi https://netdata.cloud/static/console/main.js?v=4:1
    Qo https://netdata.cloud/static/console/main.js?v=4:1
    Vn https://netdata.cloud/static/console/main.js?v=4:1
    unstable_runWithPriority https://netdata.cloud/static/console/main.js?v=4:1
    Mn https://netdata.cloud/static/console/main.js?v=4:1
    Vn https://netdata.cloud/static/console/main.js?v=4:1
    Bn https://netdata.cloud/static/console/main.js?v=4:1
    ti https://netdata.cloud/static/console/main.js?v=4:1
    In https://netdata.cloud/static/console/main.js?v=4:1
```

##### OS / Environment
Arch Linux

##### Netdata version (ouput of `netdata -V`)
1.19.0

##### Component Name
Nodes

##### Steps To Reproduce
Accidentally added a node which is actually inside a container, not sure if that's related though.

##### Expected behavior
The side panel appears and I can remove the node.

**Comment by ilyam8** [comment] 2019-12-04 10:27
Hi @felixonmars 

Duplicate of #7381

Will be fixed soon

**Closed** 2019-12-04 10:27 UTC
Labels: bug, duplicate, needs triage

**Comment by ilyam8** [comment] 2019-12-04 10:30
@VLegakis check the error, probably it is not same as i sent you

**Comment by ilyam8** [comment] 2019-12-09 11:17
@felixonmars the bug is fixed, please check

**Comment by felixonmars** [comment] 2019-12-09 13:15
@ilyam8 it works fine here now. Thanks!
