### ISSUE TITLE
Kickstart installer fails to due missing function

### ISSUE THREAD

**Issue by TheRyanHowell** [netdata/netdata#5768] opened 2019-04-02 09:17 UTC
##### Bug report summary
It looks like as a result of https://github.com/netdata/netdata/pull/5760 the kickstart scripts fail because the function safe_sha256sum does not exist. I assume the function needs to be included / copied over from functions.sh? Perhaps this should be automated by CI?

##### OS / Environment
Ubuntu Linux 18.04

##### Netdata version (ouput of `netdata -V`)
All new installs

##### Component Name
Installer

##### Steps To Reproduce
`  bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`

```
 --- Downloading static netdata binary: https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run --- 
$'[/tmp/netdata-kickstart-w1Q0at\E(B\E[0m]# \E[1m\E[33m' curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/sha256sums.txt $'\E(B\E[0m\\n'  OK  curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/sha256sums.txt 

$'[/tmp/netdata-kickstart-w1Q0at\E(B\E[0m]# \E[1m\E[33m' curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run $'\E(B\E[0m\\n'  OK  curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run 

 ABORTED  Static binary checksum validation failed. Stopping netdata installation and leaving binary in /tmp/netdata-kickstart-w1Q0at 
```
##### Expected behavior
Installer succeeds. I would of expected the kickstart.sh scripts to simply determine the latest release per channel, then include/run the install script from there.

**Comment by cakrit** [comment] 2019-04-02 09:28
Thanks @TheRyanHowell, It's getting fixed now.

**Comment by hennr** [comment] 2019-04-02 09:28
Can confirm the bug on a Debian stable system

**Comment by paulkatsoulakis** [comment] 2019-04-02 09:37
That was me guys, sorry for that.
I am working on it so that it won't slip through again

**Comment by cakrit** [comment] 2019-04-02 09:37
Reopening until the manual step is completed.

**Comment by cakrit** [comment] 2019-04-02 09:41
Manual step completed. Please retry.

**Comment by createproblem** [comment] 2019-04-02 09:43
It works, tried auto install during a chef recipe of my own! Thanks for the fast fix!

**Comment by cakrit** [comment] 2019-04-02 09:45
Thanks to this amazing community for keeping us honest! :)

**Comment by andvgal** [comment] 2019-04-02 09:50
Looks like https://my-netdata.io/kickstart-static64.sh has not been updated yet.

**Comment by cakrit** [comment] 2019-04-02 10:01
Checking with @ktsaou...

**Comment by cakrit** [comment] 2019-04-02 10:05
I just got kickstart-static64.sh and it works. Checked the md5sum and executed it. No errors.

**Closed by cakrit** 2019-04-02 10:05 UTC
Labels: area/packaging, bug

**Comment by andvgal** [comment] 2019-04-02 10:07
I confirmed, it's updated now.

**Comment by hennr** [comment] 2019-04-02 15:14
Works for us again, thanks for the fast fix guys!

**Comment by geoffjukes** [comment] 2020-04-25 01:26
I think this is broken again. Ubuntu 18.04 here, same as OP, same error.
