### ISSUE TITLE
Missing linux/amd64 manifest in docker image for v1.18.0

### ISSUE THREAD

**Issue by svrnwnsch** [netdata/netdata#7063] opened 2019-10-11 11:41 UTC
##### Bug report summary
The docker images tagged [`v1.18.0`](https://hub.docker.com/r/netdata/netdata/tags?page=1&name=v1.18) does not contain a manifest entry for linux/amd64. For [`v1.17.1`](https://hub.docker.com/r/netdata/netdata/tags?page=1&name=v1.17.1) this existed.

##### OS / Environment

linux docker

##### Component Name
docker hub

**Comment by cakrit** [comment] 2019-10-11 13:34
This strange, [the travis step](https://travis-ci.com/netdata/netdata/jobs/244149610) seems to have been successful. @knatsakis @paulkatsoulakis any idea how we can resolve this? We can't repeat the entire step, because we can't label 1.18.0 as `latest` any more, the nightly has been executed already.

**Comment by paulkatsoulakis** [comment] 2019-10-11 14:14
> This strange, [the travis step](https://travis-ci.com/netdata/netdata/jobs/244149610) seems to have been successful. @knatsakis @paulkatsoulakis any idea how we can resolve this? We can't repeat the entire step, because we can't label 1.18.0 as `latest` any more, the nightly has been executed already.

Not sure what happened, might be something missed when we merged that PR to parallelise the generation of the images.  I can have a look later if @knatsakis can jump in

**Comment by paulkatsoulakis** [comment] 2019-10-11 14:16
That is weird, the image for amd64 missing completely for 1.18.0

**Comment by cakrit** [comment] 2019-10-11 14:35
Looks like we'll need to generate and upload it manually. When I checked, I saw a similar issue for a previous release, but for a different image.

**Comment by paulkatsoulakis** [comment] 2019-10-11 14:38
> Looks like we'll need to generate and upload it manually. When I checked, I saw a similar issue for a previous release, but for a different image.

Do something simple first, click retry on that single job.
I suspect those things shouldn't run in parallel, they need to be synchronised probably

**Comment by paulkatsoulakis** [comment] 2019-10-11 16:54
Okay i think i see what happened.
Looks like the same problem that hit us with the other steps in the release process.
`Create release draft` runs in parallel with `Trigger .RPM and .DEB package generation` that runs in parallel with the jobs that generate the docker images and that is why half of docker images are not tagged correctly. 

We need to orchestrate them differently, but first i need someone from the org to help me verify this is indeed the bug by probably replaying the release on his own fork (i have removed/cleared all my accesses and settings)

**Comment by knatsakis** [comment] 2019-10-14 00:44
I will look into this today, try to figure out what happened and find a way to fix the docker images

**Comment by knatsakis** [comment] 2019-10-14 07:41
Hi @paulkatsoulakis,

The `Create release draft` creates and publishes the `netdata-latest.tar.gz` and `netdata-latest.gz.run` artifacts for GitHub. How can this affect the jobs that generate the docker images?

Could you share some more details?

**Comment by knatsakis** [comment] 2019-10-14 08:36
It seems to me that this was caused because these two jobs:
https://travis-ci.com/netdata/netdata/jobs/244149609
https://travis-ci.com/netdata/netdata/jobs/244149610
published images tagged as `latest` instead of `v1.18.0`

These jobs seem to have done their job correctly:
https://travis-ci.com/netdata/netdata/jobs/244149611
https://travis-ci.com/netdata/netdata/jobs/244149612

**Comment by paulkatsoulakis** [comment] 2019-10-14 09:19
Yes @knatsakis, this is what i mentioned on my first comment, two jobs built 1.18.0 and two built latest.

The *root cause* of this state though, is 99% because of what i said.
We rely on the latest commit message which the task is running, because before we build the docker image we do a git pull to fetch the tip, because we expect that the latest commit will be the tagged commit upon release.

The tasks run in parallel with the packaging trigger, so its random which runs will get the tagged commit and which runs will get the package trigger commits and miss the tagged commit.

That is why we must merge the above PR i mentioned, PLUs some re-organising of the flow to ensure that the release draft and the docker publishing runs before the packaging trigger or something like that. You need to think about how to re-organise them a bit to get this straight.

**Comment by paulkatsoulakis** [comment] 2019-10-14 09:20
Almost forgot, we haven't merged https://github.com/netdata/netdata/pull/7055 also, that kind of explains a bit what we found when we run our release

**Comment by knatsakis** [comment] 2019-10-14 11:42
> Yes @knatsakis, this is what i mentioned on my first comment, two jobs built 1.18.0 and two built latest.
> 
> The _root cause_ of this state though, is 99% because of what i said.
> We rely on the latest commit message which the task is running, because before we build the docker image we do a git pull to fetch the tip, because we expect that the latest commit will be the tagged commit upon release.
> 
> The tasks run in parallel with the packaging trigger, so its random which runs will get the tagged commit and which runs will get the package trigger commits and miss the tagged commit.
> 
> That is why we must merge the above PR i mentioned, PLUs some re-organising of the flow to ensure that the release draft and the docker publishing runs before the packaging trigger or something like that. You need to think about how to re-organise them a bit to get this straight.

Ok, I see what you mean now. I think you are right but I will have to verify.

**Comment by knatsakis** [comment] 2019-10-14 14:01
I believe I have figured out what happened.

The problem occurs when the `Trigger .RPM and .DEB package generation` job runs before the `Build & Publish docker image for xxx` jobs.

This is what happened with [Travis Build #5449](https://travis-ci.com/netdata/netdata/builds/127200406) for v1.17.1:
The 'Trigger .RPM and .DEB package generation` job run before `Build & Publish docker image for aarch64` that is why the arm64 image is missing for v1.17.1

Ditto for [Travis Build #6002](https://travis-ci.com/netdata/netdata/builds/131293094) v1.18.0:
The 'Trigger .RPM and .DEB package generation` job run before `Build & Publish docker image for amd64` and that is why the amd64 image is missing for v1.18.0 

When the above occurs, there are new commits added to the master branch before the docker image build job starts. When the docker image build actually starts, HEAD is not pointing to a tag anymore, so the docker image is tagged with 'latest'.

This was introduced by #6766 so, that is why it didn't happen before the v1.17.1 release.

**Comment by knatsakis** [comment] 2019-10-14 20:55
The v1.18.0-amd64 image and v1.18.0 manifest list have been restore with the following procedure

```
docker pull netdata/netdata@sha256:8a997d11844ed84b8d990a659ebc98b07a44c7bc23326b1510b45fc0254cabf5
docker image ls --digests | grep sha256:8a997d11844ed84b8d990a659ebc98b07a44c7bc23326b1510b45fc0254cabf5
docker tag 3d94621b1127 netdata/netdata:v1.18.0-amd64
docker push netdata/netdata:v1.18.0-amd64
```
```
docker manifest create netdata/netdata:v1.18.0 netdata/netdata:v1.18.0-i386 netdata/netdata:v1.18.0-armhf netdata/netdata:v1.18.0-aarch64 netdata/netdata:v1.18.0-amd64
docker manifest annotate netdata/netdata:v1.18.0 netdata/netdata:v1.18.0-amd64 --os linux --arch amd64
docker manifest annotate netdata/netdata:v1.18.0 netdata/netdata:v1.18.0-i386 --os linux --arch 386
docker manifest annotate netdata/netdata:v1.18.0 netdata/netdata:v1.18.0-armhf --os linux --arch arm
docker manifest annotate netdata/netdata:v1.18.0 netdata/netdata:v1.18.0-aarch64 --os linux --arch arm64
docker manifest push netdata/netdata:v1.18.0
```

**Comment by knatsakis** [comment] 2019-10-14 21:11
The v1.17.1-aarch64 image and v1.17.1 manifest list have been restored with the following procedure:

```
docker pull netdata/netdata@sha256:a32a6d128b55adc27f6c9f5fad218aa44e121e3d3a81fd41fac8bd457c11a553
```
> sha256:a32a6d128b55adc27f6c9f5fad218aa44e121e3d3a81fd41fac8bd457c11a553: Pulling from netdata/netdata
> 1cfb243ff225: Pull complete
> b146b4f1431f: Pull complete
> 1426597e813d: Pull complete
> 28a6eec1da79: Pull complete
> 34e74e6c9129: Pull complete
> 84cad3c5de4c: Pull complete
> 71340dc054ee: Pull complete
> Digest: sha256:a32a6d128b55adc27f6c9f5fad218aa44e121e3d3a81fd41fac8bd457c11a553
> Status: Downloaded newer image for netdata/netdata@sha256:a32a6d128b55adc27f6c9f5fad218aa44e121e3d3a81fd41fac8bd457c11a553
> docker.io/netdata/netdata@sha256:a32a6d128b55adc27f6c9f5fad218aa44e121e3d3a81fd41fac8bd457c11a553

```
docker image ls --digests | grep sha256:a32a6d128b55adc27f6c9f5fad218aa44e121e3d3a81fd41fac8bd457c11a553
```
>  netdata/netdata     <none>              sha256:a32a6d128b55adc27f6c9f5fad218aa44e121e3d3a81fd41fac8bd457c11a553   92f1aee1385a        4 weeks ago         237MB

```
docker tag 92f1aee1385a netdata/netdata:v1.17.1-aarch64
docker push netdata/netdata:v1.17.1-aarch64
```
> The push refers to repository [docker.io/netdata/netdata]
> 744bf3ebaee2: Layer already exists
> 59bd67189dfa: Layer already exists
> 6e0e2de8ca43: Layer already exists
> f6a4335d5465: Layer already exists
> 84248e88ff46: Layer already exists
> 24c83620fc9f: Layer already exists
> 081de0e854c7: Layer already exists
> v1.17.1-aarch64: digest: sha256:a32a6d128b55adc27f6c9f5fad218aa44e121e3d3a81fd41fac8bd457c11a553 size: 1793

```
docker manifest create netdata/netdata:v1.17.1 netdata/netdata:v1.17.1-i386 netdata/netdata:v1.17.1-armhf netdata/netdata:v1.17.1-aarch64 netdata/netdata:v1.17.1-amd64
```
> Created manifest list docker.io/netdata/netdata:v1.17.1

```
docker manifest annotate netdata/netdata:v1.17.1 netdata/netdata:v1.17.1-amd64 --os linux --arch amd64
docker manifest annotate netdata/netdata:v1.17.1 netdata/netdata:v1.17.1-i386 --os linux --arch 386
docker manifest annotate netdata/netdata:v1.17.1 netdata/netdata:v1.17.1-armhf --os linux --arch arm
docker manifest annotate netdata/netdata:v1.17.1 netdata/netdata:v1.17.1-aarch64 --os linux --arch arm64
docker manifest push netdata/netdata:v1.17.1
```
> sha256:315f0bd7933cb13d69d2487f57b32f75abc819befe3ecad4ab6a881faff78458

**Comment by knatsakis** [comment] 2019-10-14 21:21
Hi @svrnwnsch,

Thank you very much for your report. I have restored the missing image, so please try again and feel free to tell me if you have any further issues.

I will close this issue and continue working on a fix so that this does not happen again in #7055 with @paulkatsoulakis

**Closed by knatsakis** 2019-10-14 21:21 UTC
Labels: area/packaging, bug

**Comment by svrnwnsch** [comment] 2019-10-16 11:02
Updating via docker now worked. Thank you for the fix.

**Comment by vioan** [comment] 2020-05-03 12:03
could be that the same issue it with `netdata/netdata:v1.21.1-aarch64`?
I am asking because I get:
`standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by prologic** [comment] 2020-05-04 12:12
Try to run the [v1.21.1-aarch64](https://hub.docker.com/layers/netdata/netdata/v1.21.1-aarch64/images/sha256-46b4c67aacc3afc83aeed3edc7186aa9efa6742382faf81e660f3108e228ea87?context=explore) image directly. Its not super clear to me why this manifest is missing from the primary release tag. LMK if this works fo ryou?
