### ISSUE TITLE
Annotations / time related tags

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#312] opened 2016-04-24 13:16 UTC
One interesting feature is annotations.

Annotations are just labeled points in time. All these could be annotations:
1. started / stopped docker/container X
2. database cleanup started / stopped
3. ssh login / logout of users (with the username)
4. backup started / ended

Considerations:
1. Do we need only global annotation or annotations per dimension or per chart could be useful too? The internal round robin database of netdata already has support of them at the dimension level.
2. Do we need a central annotations server? Each netdata will have its own annotation database, but do we also need a central repository of all annotations?
3. Will annotations slow down chart refreshes? If they will, we need to find a way of supporting them efficiently (possibly stop auto-refresh when annotations are shown, or have a special always-shown header chart on the dashboards that will visualize the annotation points).
4. Annotations will be rotated, much like the chart data, but do we need something like an RSS feed for them? If we do, then probably we will also need a central annotations server to aggregate annotations from multiple netdata servers, to one RSS feed.

**Comment by ktsaou** [comment] 2018-11-23 08:48
This is on our roadmap.

**Comment by prologic** [comment] 2020-06-24 02:53
@cakrit Please appropriately hand this over to the right teams to plan and deliver. I'm un-assigning Austin to reduce clutter for our team.

**Comment by cakrit** [comment] 2020-06-24 09:27
@dim08 we talked about this last week, @prologic discovered the old existing issue on it. Please ensure we either plan this one, or close it and link it to the issue you'll be monitoring for the implementation.

**Comment by cakrit** [comment] 2021-02-12 17:17
Duplicate of https://github.com/netdata/netdata/issues/6523

**Closed by cakrit** 2021-02-12 17:17 UTC
Labels: area/daemon, area/health, area/web, feature request, priority/low
