### ISSUE TITLE
Docker Container Restarts

### ISSUE THREAD

**Issue by outerepic** [netdata/netdata#9614] opened 2020-07-27 18:46 UTC
Unable to find an exact match to what I am experiencing and don't know how to test latest release on my platform

##### Bug report summary

Netdata docker container on Synology NAS continuously restarts.

##### OS / Environment

```
uname -a; grep -Hv "^#" /etc/*release
Linux Boron-Five 4.4.59+ #25426 SMP PREEMPT Tue May 12 04:54:55 CST 2020 x86_64 GNU/Linux synology_apollolake_218+
grep: /etc/*release: No such file or directory
```

I'm on a Synology DS218+ NAS with latest DSM running Netdata in docker (app is up to date)

##### Netdata version

netdata -V
-ash: netdata: command not found

 

##### Component Name

Can't get netdata to start so I do not know which component could be causing the issue

##### Steps To Reproduce

I tried following this guide for install 

https://learn.netdata.cloud/docs/agent/packaging/docker

I SSH into my Synology NAS and run this command as root: 

docker run -d --name=netdata \
  -p 19999:19999 \
  -v netdatalib:/var/lib/netdata \
  -v netdatacache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  netdata/netdata

The terminal returns: 

e742ddde35c47a54aee7e551c40c01a225e71d13d3c11290c9bc93be2e218d07
docker: Error response from daemon: Bind mount failed: '/etc/os-release' does not exists.

A new container appears on the Synology Docker GUI container tab with the settings shown in the pictures below. (the other tabs have generic, expected settings I didn't think were worth putting in)

<img width="648" alt="Screen Shot 2020-07-27 at 14 25 37" src="https://user-images.githubusercontent.com/25163201/88577798-96bbc480-d015-11ea-8079-94ca0636f9ac.png">
<img width="649" alt="Screen Shot 2020-07-27 at 14 25 45" src="https://user-images.githubusercontent.com/25163201/88577808-99b6b500-d015-11ea-8ce7-993f4ada5d8a.png">

I start the container and after a minute or two it will restart. If I check the option for 'auto-restart' it will restart continuously. I have attached the export of the logs from the Docker app. After attempting this multiple times the logs all appear to be similar. Sometimes when I try to start the container for the first time this message appears.

<img width="493" alt="Screen Shot 2020-07-27 at 14 32 37" src="https://user-images.githubusercontent.com/25163201/88578170-1e093800-d016-11ea-95cf-19884f80db56.png">

[netdata init start.txt](https://github.com/netdata/netdata/files/4983857/netdata.init.start.txt)

I had this container up and running a few days ago with no issues and I went away for the weekend and came back to the container continuously restarting. I did not have internet access when I was away so I don't know what could have caused it to start acting up. It was working for at least 24-36 hours with no problems before I left. 

##### Expected behavior

Netdata container should start and be accessible via port 19999 as it was before. I am not an expert for this type of stuff and really just need netdata for basic monitoring of my Synology. I did not adjust any settings through the web portal when it was working and don't intend to. I just need a basic install for generic system monitoring. Any help would be appreciated! I have tried deleting the docker container and redoing the command line container creation several times since this problem first started all with the same result.

**Comment by prologic** [comment] 2020-07-28 07:24
@outerepic Just going through your description of your problem now and trying to understand what's going on (_I have no Synolgy NAS to test with, I have a VM image but I haven't had time yet to play with that_)...

> docker: Error response from daemon: Bind mount failed: '/etc/os-release' does not exists.

I _think_ you should attempt to fix this incorrect bind-mount first.

I'll keep reading and have a look at the other things you have attached/mentioned.

**Comment by prologic** [comment] 2020-07-28 07:52
@mfundul Do you mind having a look at the logs attached which seem to be agent logs. Its not super clear ot me why it's bailing out here...

**Comment by mfundul** [comment] 2020-07-28 08:40
The netdata cache folder has been corrupted. The workaround here is to delete `/var/cache/netdata/dbengine/*`. This is a duplicate of https://github.com/netdata/netdata/issues/9521

**Closed by mfundul** 2020-07-28 08:40 UTC
Labels: bug

**Comment by prologic** [comment] 2020-07-28 12:11
> The netdata cache folder has been corrupted. The workaround here is to delete `/var/cache/netdata/dbengine/*`. This is a duplicate of #9521

For our benefit, can you describe the pattern of log lines that you clearly know how to recognise :)

**Comment by mfundul** [comment] 2020-07-28 12:15
> 
> 
> > The netdata cache folder has been corrupted. The workaround here is to delete `/var/cache/netdata/dbengine/*`. This is a duplicate of #9521
> 
> For our benefit, can you describe the pattern of log lines that you clearly know how to recognise :)

Sure:
```
netdata ERROR : MAIN : Failed to scan path "/var/cache/netdata/dbengine". (errno 22, Invalid argument)
netdata ERROR : MAIN : 1 datafiles failed to load.
netdata ERROR : MAIN : File length is too short.
```

**Comment by outerepic** [comment] 2020-07-29 15:11
> The netdata cache folder has been corrupted. The workaround here is to delete `/var/cache/netdata/dbengine/*`. This is a duplicate of #9521

Thank you for identifying the problem! Being on a Synology Docker install however I have been unable to find this file location. When I SSH into my Synology, login as root, and navigate to the /var/cache/ folder there is no netdata folder when doing _ls_, _ls .._, or _cd netdata_  

I was thinking that because it's through Docker the location would be different. I am not an expert on doing complex command line things but if you have any advice on how to find the /netdata/dbengine/ folder that would be greatly appreciated! 

Just moving around the folder structure a little bit, there is an @docker folder on /volume1 I didn't know if it might be there somewhere. There is a 'volumes' folder here that contains the folders netdatacache & netdatalib but neither contain the dbengine folder you mentioned.

**Comment by mfundul** [comment] 2020-07-29 15:19
If the agent is inside a docker container, then yes you are correct, this path would have to be inside the container's namespace. I'm not sure exactly where it could be located, maybe you can find out by running something like `find / | grep "var/cache/netdata/dbengine".

Corruption could be due to segfaults in the agent, power failure, maybe killing the agent process. In any case it is a netdata bug and it should be able to recover, when the bug is fixed.

**Comment by outerepic** [comment] 2020-07-29 15:35
> @outerepic Just going through your description of your problem now and trying to understand what's going on (_I have no Synolgy NAS to test with, I have a VM image but I haven't had time yet to play with that_)...
> 
> > docker: Error response from daemon: Bind mount failed: '/etc/os-release' does not exists.
> 
> I _think_ you should attempt to fix this incorrect bind-mount first.
> 
> I'll keep reading and have a look at the other things you have attached/mentioned.

Do you have any suggestions on how to go about fixing this bind mount error? When the container was initially working I ran the docker run command with that line removed and it didn't seem to cause any issues. If I remember correctly it was also working after throwing that error and just ignoring it. I don't know if this would be connected to when it crashed over the weekend.

**Comment by mfundul** [comment] 2020-07-29 15:39
Since we have logs from the agent that point to the other issue, it's safe to say that the bind mount failure is not responsible for the netdata agent restarting, but the cache folder corruption. I believe if you resolve this (maybe delete the container?), the bind mount error will not stop netdata from running.

**Comment by outerepic** [comment] 2020-07-29 17:57
@mfundul I tried deleting the container along with deleting/reinstalling the image from the Synology Docker app with no luck. 

I tried the _find / | grep "var/cache/netdata/dbengine"_ command you recommended from root folder with no results. When I ran _find / -type d -name dbengine_  I got this result: /volume1/@docker/volumes/netdatacache/_data/dbengine

I then ran: rm /volume1/@docker/volumes/netdatacache/_data/dbengine/* and now it appears to be working!!! Thanks so much!!!

**Comment by prologic** [comment] 2020-07-30 05:52
Thanks @mfundul !

The _dead_ give away is:

> netdata ERROR : MAIN : File length is too short.

I think :) Thanks!

**Comment by mx2k** [comment] 2022-11-09 17:12
> > @outerepic Just going through your description of your problem now and trying to understand what's going on (_I have no Synolgy NAS to test with, I have a VM image but I haven't had time yet to play with that_)...
> > > docker: Error response from daemon: Bind mount failed: '/etc/os-release' does not exists.
> > 
> > 
> > I _think_ you should attempt to fix this incorrect bind-mount first.
> > I'll keep reading and have a look at the other things you have attached/mentioned.
> 
> Do you have any suggestions on how to go about fixing this bind mount error? When the container was initially working I ran the docker run command with that line removed and it didn't seem to cause any issues. If I remember correctly it was also working after throwing that error and just ignoring it. I don't know if this would be connected to when it crashed over the weekend. @prologic @mfundul

Syno stores os-release info in /etc/VERSION, not /etc/os-release. No idea how to mount that to docker so Netdata displays the actual OS info instead of N/A. I have not gotten this to work anyhow, so I just commented out the os-release mount and live without that info for now.

```
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/VERSION:/host/etc/os-release:ro
```
This volume mount doesn't throw the os-release error on container start. However, netdata still does not read the OS version.
