### ISSUE TITLE
Packagecloud Centos 7 1.23.2-1 rpm does not install

### ISSUE THREAD

**Issue by KrisShannon** [netdata/netdata#9643] opened 2020-08-03 02:40 UTC
#### Bug report summary
The [netdata-1.23.2-1.el7.x86_64.rpm](https://packagecloud.io/netdata/netdata/packages/el/7/netdata-1.23.2-1.el7.x86_64.rpm) on Packagecloud requires `libc.so.6(GLIBC_2.26)(64bit)` which is not available on CentOS 7

##### OS / Environment
```
Linux cpanel-test 3.10.0-962.3.2.lve1.5.35.el7.x86_64 #1 SMP Tue Apr 14 15:56:28 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/cloudlinux-release:CloudLinux release 7.8 (Alexei Leonov) 
```

##### Netdata version
Currently running netdata v1.23.1
Yum update to v1.23.2 fails

**Comment by prologic** [comment] 2020-08-03 10:36
I will look into this...

**Comment by Ferroin** [comment] 2020-09-01 14:22
Testing with both current stable (1.24.0) and the current nightlies, I am unable to reproduce this issue.

**Comment by prologic** [comment] 2020-09-02 05:52
@Ferroin Following the Instructions from [here](https://packagecloud.io/netdata/netdata-edge/install#bash-rpm) I run into numerous installation errors:

<details>
<summary>Logs</summary>

```#!console
$ dki -t --rm centos:7 /bin/sh
sh-4.2# yum install -y sudo && curl -s https://packagecloud.io/install/repositories/netdata/netdata-edge/script.rpm.sh | sudo bash
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirror.realcompute.io
 * extras: mirror.realcompute.io
 * updates: mirror.overthewire.com.au
base                                                                                                                                     | 3.6 kB  00:00:00
extras                                                                                                                                   | 2.9 kB  00:00:00
updates                                                                                                                                  | 2.9 kB  00:00:00
(1/4): base/7/x86_64/group_gz                                                                                                            | 153 kB  00:00:00
(2/4): extras/7/x86_64/primary_db                                                                                                        | 206 kB  00:00:00
(3/4): base/7/x86_64/primary_db                                                                                                          | 6.1 MB  00:00:01
(4/4): updates/7/x86_64/primary_db                                                                                                       | 4.5 MB  00:00:01
Resolving Dependencies
--> Running transaction check
---> Package sudo.x86_64 0:1.8.23-9.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================
 Package                            Arch                                 Version                                       Repository                          Size
================================================================================================================================================================
Installing:
 sudo                               x86_64                               1.8.23-9.el7                                  base                               842 k

Transaction Summary
================================================================================================================================================================
Install  1 Package

Total download size: 842 k
Installed size: 3.0 M
Downloading packages:
warning: /var/cache/yum/x86_64/7/base/packages/sudo-1.8.23-9.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for sudo-1.8.23-9.el7.x86_64.rpm is not installed
sudo-1.8.23-9.el7.x86_64.rpm                                                                                                             | 842 kB  00:00:00
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-8.2003.0.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : sudo-1.8.23-9.el7.x86_64                                                                                                                     1/1
  Verifying  : sudo-1.8.23-9.el7.x86_64                                                                                                                     1/1

Installed:
  sudo.x86_64 0:1.8.23-9.el7

Complete!
Detected operating system as centos/7.
Checking for curl...
Detected curl...
Downloading repository file: https://packagecloud.io/install/repositories/netdata/netdata-edge/config_file.repo?os=centos&dist=7&source=script
done.
Installing pygpgme to verify GPG signatures...
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.realcompute.io
 * extras: mirror.realcompute.io
 * updates: mirror.overthewire.com.au
netdata_netdata-edge-source/signature                                                                                                    |  833 B  00:00:00
Retrieving key from https://packagecloud.io/netdata/netdata-edge/gpgkey
Importing GPG key 0x4B987DCC:
 Userid     : "https://packagecloud.io/netdata/netdata-edge (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: f3a9 5d59 f9ce 7471 b2d0 1381 98cc 3e6a 4b98 7dcc
 From       : https://packagecloud.io/netdata/netdata-edge/gpgkey
netdata_netdata-edge-source/signature                                                                                                    |  951 B  00:00:04 !!!
netdata_netdata-edge-source/primary                                                                                                      |  175 B  00:00:01
Package pygpgme-0.3-9.el7.x86_64 already installed and latest version
Nothing to do
Installing yum-utils...
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.realcompute.io
 * extras: mirror.realcompute.io
 * updates: mirror.overthewire.com.au
Package yum-utils-1.1.31-54.el7_8.noarch already installed and latest version
Nothing to do
Generating yum cache for netdata_netdata-edge...
Importing GPG key 0x4B987DCC:
 Userid     : "https://packagecloud.io/netdata/netdata-edge (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: f3a9 5d59 f9ce 7471 b2d0 1381 98cc 3e6a 4b98 7dcc
 From       : https://packagecloud.io/netdata/netdata-edge/gpgkey
Generating yum cache for netdata_netdata-edge-source...

The repository is setup! You can now install packages.
sh-4.2# yum install netdata
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.realcompute.io
 * extras: mirror.realcompute.io
 * updates: mirror.overthewire.com.au
Resolving Dependencies
--> Running transaction check
---> Package netdata.x86_64 0:1.24.171-1.el7 will be installed
--> Processing Dependency: libuv >= 1 for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: snappy for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: protobuf-c for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: protobuf for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: openssl for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: libmnl for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: Judy for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: libuv.so.1()(64bit) for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: libJudy.so.1()(64bit) for package: netdata-1.24.171-1.el7.x86_64
--> Running transaction check
---> Package libmnl.x86_64 0:1.0.3-7.el7 will be installed
---> Package netdata.x86_64 0:1.24.171-1.el7 will be installed
--> Processing Dependency: libuv >= 1 for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: Judy for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: libuv.so.1()(64bit) for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: libJudy.so.1()(64bit) for package: netdata-1.24.171-1.el7.x86_64
---> Package openssl.x86_64 1:1.0.2k-19.el7 will be installed
--> Processing Dependency: make for package: 1:openssl-1.0.2k-19.el7.x86_64
---> Package protobuf.x86_64 0:2.5.0-8.el7 will be installed
---> Package protobuf-c.x86_64 0:1.0.2-3.el7 will be installed
---> Package snappy.x86_64 0:1.1.0-3.el7 will be installed
--> Running transaction check
---> Package make.x86_64 1:3.82-24.el7 will be installed
---> Package netdata.x86_64 0:1.24.171-1.el7 will be installed
--> Processing Dependency: libuv >= 1 for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: Judy for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: libuv.so.1()(64bit) for package: netdata-1.24.171-1.el7.x86_64
--> Processing Dependency: libJudy.so.1()(64bit) for package: netdata-1.24.171-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: netdata-1.24.171-1.el7.x86_64 (netdata_netdata-edge)
           Requires: libuv.so.1()(64bit)
Error: Package: netdata-1.24.171-1.el7.x86_64 (netdata_netdata-edge)
           Requires: Judy
Error: Package: netdata-1.24.171-1.el7.x86_64 (netdata_netdata-edge)
           Requires: libuv >= 1
Error: Package: netdata-1.24.171-1.el7.x86_64 (netdata_netdata-edge)
           Requires: libJudy.so.1()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
sh-4.2#
```
</details>

How did you test/verify the non-reproducibility? 🤔 (_This llooks really broken to me 😢_)

**Comment by Ferroin** [comment] 2020-09-02 11:35
@prologic You're missing EPEL, and therefore couldn't get Judy or libuv. I thought we had this pre-dependency documented somewhere but we apparently do not...

**Comment by KrisShannon** [comment] 2020-09-09 04:56
Hi,

This wasn't a problem with EPEL.

This was specifically an issue with the [netdata-1.23.2-1.el7.x86_64.rpm](https://packagecloud.io/netdata/netdata/packages/el/7/netdata-1.23.2-1.el7.x86_64.rpm) on packagecloud.

It was linked against a version of glibc which doesn't exist in either the CentOS 7 or EPEL 7 repositories.

Looking at the differences between the "Requires" for this rpm and for previous ones shows that as well as needing a newer version of glibc:

```diff
- libc.so.6(GLIBC_2.17)(64bit)
+ libc.so.6(GLIBC_2.26)(64bit)
```

it also required specific versions of the dynamic linker:

```diff
+ ld-linux-x86-64.so.2()(64bit)
+ ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)
```

as well as libbpf and libelf:

```diff
+ libbpf_kernel-3.so()(64bit)
+ libbpf_kernel-3.so(LIBBPF_0.0.1)(64bit)
+ libbpf_kernel-3s.so()(64bit)
+ libbpf_kernel-3s.so(LIBBPF_0.0.1)(64bit)
+ libbpf_kernel-7.so()(64bit)
+ libbpf_kernel-7.so(LIBBPF_0.0.1)(64bit)
+ libbpf_kernel-7s.so()(64bit)
+ libbpf_kernel-7s.so(LIBBPF_0.0.1)(64bit)
+ libelf.so.1()(64bit)
+ libelf.so.1(ELFUTILS_1.0)(64bit)
```

There is now a newer package in the stable repository - [netdata-1.24.0-1.el7.x86_64.rpm](https://packagecloud.io/netdata/netdata/packages/el/7/netdata-1.24.0-1.el7.x86_64.rpm) - which doesn't have the libbpf dependencies and has reverted back to requiring `libc.so.6(GLIBC_2.17)(64bit)` again.

Something either went wrong in the process of either building 1.23-2-1 for CentOS 7,  or the wrong build was uploaded to the stable repository.

**Comment by Ferroin** [comment] 2020-09-09 11:07
@KrisShannon I understand your issue had nothing to do with EPEL, I was pointing out that @prologic was missing EPEL on his test system, which is why he got the errors he did.

Thank you for digging deeper though, given what you're seeing it looks like your issue was a result of some issues we had with packaging the eBPF collectors a while back, so it should indeed no longer be a problem (and I'm closing the issue under the assumption that this is the case).

**Closed by Ferroin** 2020-09-09 11:07 UTC
Labels: area/packaging, bug
