### ISSUE TITLE
No disk read stats, but write stats work

### ISSUE THREAD

**Issue by PhilsLab** [netdata/netdata#4955] opened 2018-12-08 14:33 UTC
##### Bug report summary
When accessing netdata, it shows all stats correctly, except the disk reads (-> writes are shown properly!)

As you can see, the read graph shows `0.0` constantly, except some weird and buggy bumps that have no relation to the actual reads:
![image](https://user-images.githubusercontent.com/15452526/49686948-4324fc00-fafc-11e8-9c82-d74518818c81.png)

While doing a `cp a b` on the same disk:
![image](https://user-images.githubusercontent.com/15452526/49686960-71a2d700-fafc-11e8-9400-12f45d800cb4.png)

Output of `iostat -x`:
```
$ iostat -x
Linux 4.15.0-42-generic (cluster-m3)    12/08/2018      _x86_64_        (4 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.08    0.24    2.70    1.10    0.00   92.89

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
loop0            0.01    0.00      0.29      0.00     0.00     0.00   0.00   0.00    4.00    0.00   0.00    22.55     0.00   1.79   0.00
loop1            2.24    0.00      2.51      0.00     0.00     0.00   0.00   0.00    0.85    0.00   0.00     1.12     0.00   0.04   0.01
loop2            0.00    0.00      0.00      0.00     0.00     0.00   0.00   0.00    0.00    0.00   0.00     1.60     0.00   0.00   0.00
scd0             0.09    0.00      1.95      0.00     0.00     0.00   0.00   0.00    0.12    0.00   0.00    22.35     0.00   0.12   0.00
sda              7.34   32.89    407.65   1018.68     0.95    13.59  11.51  29.24    3.48   44.79   1.50    55.57    30.97   0.85   3.40
```

##### OS / Environment
Ubuntu Server 18.04 LTS, Netdata inside of Docker (this might be really relevant to the issue)
It's installed with the documentation in mind, the container is privileged and has the recommended security parameters set (SYS_PTRACE, AppArmor etc.).

I had this problem on Alpine, Ubuntu Server 18.04, and RHEL7, all while dockerizing the Netdata application.

##### Component Name
Chart:
disk.<disk_name>

##### Steps To Reproduce
Install netdata with docker according to [https://github.com/netdata/netdata/tree/master/packaging/docker](https://github.com/netdata/netdata/tree/master/packaging/docker)

**Comment by cakrit** [comment] 2018-12-08 17:14
@PhilsLab what's your netdata version?
@vlvkobal / @paulfantom can you please help with the analysis?

**Comment by PhilsLab** [comment] 2018-12-08 17:16
I had this issue with several previous versions in the past few months, the one I am running right now is the latest docker image, so that should be `v1.12.0-rc0-amd64`.

**Comment by ktsaou** [comment] 2018-12-09 04:59
@PhilsLab could you please post the output of this:

```
for x in 1 2 3 4 5; do echo; date; cat /proc/diskstats; sleep 1; done
```

Could you please repeat the above, while copying a large file?

**Comment by vlvkobal** [comment] 2019-01-13 21:01
I can't reproduce the issue.
@PhilsLab instead of copying a large file, please run this command on you host OS:
```
echo 3 | sudo tee /proc/sys/vm/drop_caches && find /usr -name "*" -exec grep -L . {} \;
```
Do it in parallel with running
```
for x in 1 2 3 4 5; do echo; date; cat /proc/diskstats; sleep 1; done
```
Please post here the output of the last command as @ktsaou requested.

**Comment by PhilsLab** [comment] 2019-01-15 14:38
Sorry for the delay.

This is what i got from running
```
echo 3 | sudo tee /proc/sys/vm/drop_caches && find /usr -name "*" -exec grep -L . {} \;
```

Output of the diskstats:
```
Tue Jan 15 14:35:58 UTC 2019
   7       0 loop0 155 0 4326 456 0 0 0 0 0 32 92
   7       1 loop1 350 0 8996 664 0 0 0 0 0 32 40
   7       2 loop2 10670 0 29588 23092 0 0 0 0 0 872 15672
   7       3 loop3 12986 0 28142 2308 0 0 0 0 0 92 1576
   7       4 loop4 5 0 16 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
  11       0 sr0 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 318583 17699 16706676 471828 3479214 8806074 117924328 16765696 0 9546008 17242696
   8       1 sda1 519 0 13812 356 0 0 0 0 0 356 356
   8       2 sda2 317374 17699 16668030 470528 3479214 8806074 117924328 16765696 0 9545608 17241400
   8      16 sdb 767288 22467 171221290 2449232 70322803 85851967 2165292736 351597032 0 295863892 354004248
 253       0 dm-0 789718 0 171219794 2917920 155985427 0 2165292736 622981192 0 296004796 625943876

Tue Jan 15 14:35:59 UTC 2019
   7       0 loop0 155 0 4326 456 0 0 0 0 0 32 92
   7       1 loop1 350 0 8996 664 0 0 0 0 0 32 40
   7       2 loop2 10670 0 29588 23092 0 0 0 0 0 872 15672
   7       3 loop3 12986 0 28142 2308 0 0 0 0 0 92 1576
   7       4 loop4 5 0 16 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
  11       0 sr0 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 319363 17761 16722692 472572 3479214 8806074 117924328 16765696 0 9546612 17243440
   8       1 sda1 519 0 13812 356 0 0 0 0 0 356 356
   8       2 sda2 318154 17761 16684046 471272 3479214 8806074 117924328 16765696 0 9546212 17242144
   8      16 sdb 767288 22467 171221290 2449232 70322812 85851970 2165292832 351597124 0 295863984 354004340
 253       0 dm-0 789718 0 171219794 2917920 155985439 0 2165292832 622981304 0 296004888 625943988

Tue Jan 15 14:36:00 UTC 2019
   7       0 loop0 155 0 4326 456 0 0 0 0 0 32 92
   7       1 loop1 350 0 8996 664 0 0 0 0 0 32 40
   7       2 loop2 10670 0 29588 23092 0 0 0 0 0 872 15672
   7       3 loop3 12986 0 28142 2308 0 0 0 0 0 92 1576
   7       4 loop4 5 0 16 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
  11       0 sr0 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 319975 17761 16729028 473064 3479218 8806409 117927040 16765744 1 9547124 17243980
   8       1 sda1 519 0 13812 356 0 0 0 0 0 356 356
   8       2 sda2 318766 17761 16690382 471764 3479218 8806409 117927040 16765744 1 9546724 17242684
   8      16 sdb 767291 22467 171221314 2449236 70322885 85852042 2165294752 351598292 0 295865052 354005512
 253       0 dm-0 789721 0 171219818 2917924 155985584 0 2165294752 622983628 0 296005956 625946316

Tue Jan 15 14:36:01 UTC 2019
   7       0 loop0 155 0 4326 456 0 0 0 0 0 32 92
   7       1 loop1 350 0 8996 664 0 0 0 0 0 32 40
   7       2 loop2 10670 0 29588 23092 0 0 0 0 0 872 15672
   7       3 loop3 12986 0 28142 2308 0 0 0 0 0 92 1576
   7       4 loop4 5 0 16 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
  11       0 sr0 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 320755 17783 16737996 473828 3479218 8806409 117927040 16765744 1 9547868 17244740
   8       1 sda1 519 0 13812 356 0 0 0 0 0 356 356
   8       2 sda2 319546 17783 16699350 472528 3479218 8806409 117927040 16765744 1 9547468 17243444
   8      16 sdb 767293 22467 171221330 2449236 70322927 85852083 2165295728 351599148 0 295865832 354006368
 253       0 dm-0 789723 0 171219834 2917924 155985667 0 2165295728 622985380 0 296006736 625948068

Tue Jan 15 14:36:02 UTC 2019
   7       0 loop0 155 0 4326 456 0 0 0 0 0 32 92
   7       1 loop1 350 0 8996 664 0 0 0 0 0 32 40
   7       2 loop2 10670 0 29588 23092 0 0 0 0 0 872 15672
   7       3 loop3 12986 0 28142 2308 0 0 0 0 0 92 1576
   7       4 loop4 5 0 16 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
  11       0 sr0 0 0 0 0 0 0 0 0 0 0 0
   8       0 sda 321271 17783 16743716 474280 3479218 8806409 117927040 16765744 0 9548320 17245192
   8       1 sda1 519 0 13812 356 0 0 0 0 0 356 356
   8       2 sda2 320062 17783 16705070 472980 3479218 8806409 117927040 16765744 0 9547920 17243896
   8      16 sdb 767293 22467 171221330 2449236 70322936 85852086 2165295824 351599196 0 295865880 354006416
 253       0 dm-0 789723 0 171219834 2917924 155985679 0 2165295824 622985440 0 296006784 625948128

```

**Comment by vlvkobal** [comment] 2019-01-15 14:52
Did you run the second command on your host machine? Did you see any changes in `disk.sda` chart for `reads` dimension?

Could you run the same test, but now execute the first command on your host machine and the second one inside the netdata container. Please post the output for the `/proc/diskstats` here.

**Comment by PhilsLab** [comment] 2019-01-15 15:01
Apparently, this makes it work.
See my grafana logging:
![grafana](https://user-images.githubusercontent.com/15452526/51188681-ba5d6500-18de-11e9-826a-d80f3f75b162.png)

Have i been fooled by caching? I was wondering to see no reads at all, but the last command made it visible instantly.

**Comment by vlvkobal** [comment] 2019-01-15 15:18
Yes. It was the result of caching. Since the issue is solved can we close it?

**Comment by PhilsLab** [comment] 2019-01-15 15:21
Yes, i guess my issue is solved then. Thanks for your time.

**Closed** 2019-01-15 15:23 UTC
Labels: area/collectors, priority/low, question
