### ISSUE TITLE
edit-config uses vi, even if it isn't the system editor

### ISSUE THREAD

**Issue by foux** [netdata/netdata#4549] opened 2018-11-02 10:37 UTC
##### Bug report summary
Using edit-config, the editor used is not the system editor, but is forced to vi

##### OS / Environment
Debian, but should be the same on all Unix based distribed

##### Component Name
edit-conf

##### Steps To Reproduce
Set, for example, `nano` as your system editor (and `$EDITOR` would be equal to `/bin/nano`. Then launch `edit-config` and vi would be use, because `edit-config` forces `EDITOR="${EDITOR-vi}"`

##### Expected behavior
The system editor should be used

**Comment by Ferroin** [comment] 2018-11-02 11:20
Confirmed on Gentoo.  I'll have a PR for this posted soon.

**Comment by Ferroin** [comment] 2018-11-02 11:31
Correction, confirmed on _some_ Gentoo systems.  It looks like it's an issue with the choice of shell.

**Comment by Ferroin** [comment] 2018-11-02 11:34
Also, for the record, this: `EDITOR="${EDITOR-vi}"` is a special substitution syntax.  It says to use the existing value of `$EDITOR` if it's set, or fall back to `vi` as the value if it's not set.

**Comment by foux** [comment] 2018-11-02 12:19
> Also, for the record, this: `EDITOR="${EDITOR-vi}"` is a special substitution syntax. It says to use the existing value of `$EDITOR` if it's set, or fall back to `vi` as the value if it's not set.

Thanks for the explanation! In my case, it doesn't work on Debian with zsh as shell and nano as default editor

**Comment by Ferroin** [comment] 2018-11-02 12:32
OK, having looked further, it appears that what I saw on Gentoo was actually a different issue (I use a _really_ odd ZSH config, and it looks like that was causing the behavior here).

Regarding Debian though, do you have an `editor` command?  I seem to remember from when I used Debian actively that they handle the default editor via their alternatives framework, and that it ends up being specified as a symlink to the selected editor.

**Comment by foux** [comment] 2018-11-02 12:44
> OK, having looked further, it appears that what I saw on Gentoo was actually a different issue (I use a _really_ odd ZSH config, and it looks like that was causing the behavior here).
> 
> Regarding Debian though, do you have an `editor` command? I seem to remember from when I used Debian actively that they handle the default editor via their alternatives framework, and that it ends up being specified as a symlink to the selected editor.

Exactly. In fact Debian doesn't use `$EDITOR` but selecting a default editor (via `update-alternative`) creates a `/usr/bin/editor` file, linking to `/etc/alternatives/editor`, itself linking to the chosen editor. Doesn't Gentoo have the same link (the first one, not the `/etc/alternatives` one)? I think to remember as much.

**Comment by Ferroin** [comment] 2018-11-02 12:54
My systems don't.  However, I should be able to get something put together quickly that will fix this on systems that do provide it.

**Comment by Ferroin** [comment] 2018-11-02 13:09
Should be fixed in #4551.

**Comment by foux** [comment] 2018-11-02 13:11
Update looks great, thanks! 👍

**Closed** 2018-11-02 18:28 UTC
Labels: bug
