### ISSUE TITLE
Stream to multiple Master

### ISSUE THREAD

**Issue by DeWaRs1206** [netdata/netdata#6895] opened 2019-09-19 17:26 UTC
2nd question in 2 days, it should be the last one :) 
#### Question summary
I'm using Netdata Master / Slave streaming feature to save my monitoring data on a separate server and be able to switch between my instances easily. Everything works perfectly. 
One question remains. Is there a way to stream slave data to multiple master? 
##### OS / Environment
Ubuntu 18.04

Thanks for you answer :)

**Comment by ilyam8** [comment] 2019-09-19 18:57
Hi @DeWaRs1206 

It looks like it is not possible
https://github.com/netdata/netdata/blob/551617bd322e2b855ccf19375650348fda77938a/streaming/stream.conf#L22-L33

> If many are given, the first available will get the metrics.

**Comment by DeWaRs1206** [comment] 2019-09-19 20:18
Yes, but maybe there is a tric with the proxy feature ? Maybe if master 1 is proxy for master 2 would I works ?
 My problem is the following: my prod landscape is composed of physical server, my test / stage are virtual server hosted on openstack. If my whole openstack tenant is dead (which happens last week) I would not get any monitoring alert anymore, therefor a 2nd master hosted on another cloud infrastructure (aws for example). If openstack is down I would get alert for prod landscape from the aws instance. If aws is dead, i would get alert from the openstack instance.

**Comment by cakrit** [comment] 2019-09-20 07:56
Of course it's possible to do more advanced setups, a master can also be a slave. Start reading from https://docs.netdata.cloud/streaming/#an-advanced-setup until the end of the page. 

It's not an ideal solution for the issue you're facing and we've been discussing the need to improve streaming. So I'm making this a feature request, since we haven't yet opened another issue to describe the improvements we want to make.

**Comment by DeWaRs1206** [comment] 2019-09-20 09:00
Okey, I will try to put my Master as Proxy for the AWS instance. Thanks a lot for the quick answer !

**Comment by thiagoftsm** [comment] 2019-09-20 11:04
Hi @DeWaRs1206 I will put this in my roadmap for the next months.

**Comment by cakrit** [comment] 2020-04-30 12:22
Duplicate of #4395

**Closed by cakrit** 2020-04-30 12:22 UTC
Labels: area/streaming, feature request, priority/medium
