### ISSUE TITLE
Share controls across charts

### ISSUE THREAD

**Issue by pjlegato** [netdata/netdata#266] opened 2016-04-18 19:25 UTC
Currently, every chart has its own small controls (play, pause, etc. buttons) attached to it.

Is it possible to define a single set of larger shared controls that will operate all charts (or some specified set of charts) on a page in sync?

**Comment by ktsaou** [comment] 2016-04-18 23:42
If we do this, then all charts have to be synced.
Now it is a user option in the settings, so if the users chooses to, each chart can be completely autonomous.

**Comment by ktsaou** [comment] 2016-04-18 23:44
I think though we will need these global settings:

1. Play / Pause (so we can remove the play button from the charts)
2. Auto-refresh state duration. Now it is dynamic, 3 pixels per point and the dashboard will fit as many seconds as it can. We could have something like 5min, 10min, 15mins, 30mins, 1hour, 2hours, etc.

**Comment by ktsaou** [comment] 2016-04-18 23:45
This though seems to be a duplicate of #250

**Comment by pjlegato** [comment] 2016-04-19 00:13
Many (probably most) charts are synced anyway. It could be optional to have shared controls, one per group. If the user doesn't opt in, then they'd get the standard "one set of controls per chart" behavior.

**Comment by ktsaou** [comment] 2018-11-23 10:12
@gmosx 	this is on our roadmap.

**Comment by ilyam8** [comment] 2021-07-08 12:27
Added in https://github.com/netdata/netdata/pull/11316

**Closed by ilyam8** 2021-07-08 12:27 UTC
Labels: area/web, feature request
