### ISSUE TITLE
Ubuntu 16.04 deb install of 1.24.0 from pkgcloud fails looking for /usr/libexec/netdata/plugins.d/ebpf.plugin

### ISSUE THREAD

**Issue by anl** [netdata/netdata#9707] opened 2020-08-10 21:28 UTC
#### Bug report summary
Installing netdata 1.24.0 from packagecloud.io/netdata fails on Ubuntu 16.04:

```
Setting up netdata (1.24.0) ...
chmod: cannot access '/usr/libexec/netdata/plugins.d/ebpf.plugin': No such file or directory
dpkg: error processing package netdata (--configure):
 subprocess installed post-installation script returned error exit status 1
```

##### OS / Environment

```
Linux ip-10-141-2-245 4.4.0-1111-aws #123-Ubuntu SMP Sat Jul 4 02:03:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=16.04
/etc/lsb-release:DISTRIB_CODENAME=xenial
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="16.04.6 LTS (Xenial Xerus)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 16.04.6 LTS"
/etc/os-release:VERSION_ID="16.04"
/etc/os-release:HOME_URL="http://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="http://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
/etc/os-release:VERSION_CODENAME=xenial
/etc/os-release:UBUNTU_CODENAME=xenial
```

##### Netdata version

netdata v1.24.0
 
##### Component Name

contrib

##### Steps To Reproduce

1. curl -s https://packagecloud.io/install/repositories/netdata/netdata/script.deb.sh | sudo bash
2. apt-get install netdata

##### Expected behavior

netdata package installation via apt-get on Ubuntu 16.04 should succeed.

**Comment by fettfoen** [comment] 2020-08-11 17:25
Same problem here. I installed Netdata with provided Ubuntu 16.04 repo:

deb https://packagecloud.io/netdata/netdata/ubuntu/ xenial main
deb-src https://packagecloud.io/netdata/netdata/ubuntu/ xenial main

Today I updated (apt update/upgrade) my server and got the same error:

```
...
chmod: cannot access '/usr/libexec/netdata/plugins.d/ebpf.plugin': No such file or directory
dpkg: error processing package netdata (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 netdata
E: Sub-process /usr/bin/dpkg returned an error code (1)
...
```

**Comment by Kazyini** [comment] 2020-08-12 08:20
Same problem with Debian Stretch.

Repo:

deb https://packagecloud.io/netdata/netdata/debian/ stretch main
deb-src https://packagecloud.io/netdata/netdata/debian/ stretch main

```bash
apt-get install netdata:
Setting up netdata (1.24.0) ...
chmod: cannot access '/usr/libexec/netdata/plugins.d/ebpf.plugin': No such file or directory
dpkg: error processing package netdata (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 netdata
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by prologic** [comment] 2020-08-13 11:42
Confirmed.

**Comment by jspasiuk** [comment] 2020-08-14 13:41
Same issue here! Ubuntu 16.04.6 LTS

**Comment by roedie** [comment] 2020-08-19 13:11
This is because of #8996. It tries to chmod the ebpf plugins which isn't in the package.

**Comment by prologic** [comment] 2020-08-19 22:42
I _think_ there's an inbound PR to fix this... Let me see if I can find it...

**Comment by prologic** [comment] 2020-08-19 22:43
I _think_ [this PR](https://github.com/netdata/netdata/pull/9752) from @Saruspete _might_ fix this situation! 🎉 We'll try to get this merged today!

**Closed** 2020-08-25 05:10 UTC
Labels: area/packaging, bug
