### ISSUE TITLE
Idle Jitter Throwing Bogus Results

### ISSUE THREAD

**Issue by MrAmos123** [netdata/netdata#8436] opened 2020-03-19 14:21 UTC
##### Bug report summary
IdleJitter is reporting values of 360 Quadrillion as seen here: https://i.imgur.com/t6nJTJm.png

I've rebooted the entire host and it's still showing it... http://eu.nbsclan.org:19999/#menu_system_submenu_idlejitter;theme=slate;help=true

This used to work fine, not sure what happened. It's stopped working within the last few days.

##### OS / Environment
```
root@france:~# grep -Hv "^#" /etc/*release
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version
 netdata v1.20.0-186-nightly

##### Component Name
IdleJitter

##### Steps To Reproduce
1. Open http://eu.nbsclan.org:19999/ 
2. Go to IdleJitter
3. Experience weird values?

##### Expected behavior
Normalised values, nothing past 1 quadrillion please, haha. :)

**Comment by mfundul** [comment] 2020-03-19 14:25
Closing as duplicate of #8409

**Closed by mfundul** 2020-03-19 14:25 UTC
Labels: bug, needs triage
