### ISSUE TITLE
clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)

### ISSUE THREAD

**Issue by Wing924** [netdata/netdata#5367] opened 2019-02-12 08:38 UTC
##### Bug report summary
error.log reports many `clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)` and tc plugin become deadlock when stop the service. 
```
2019-02-12 17:14:24: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:24: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:24: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:24: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:25: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:25: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:25: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:25: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:26: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:26: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:26: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:26: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:27: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:27: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:27: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:27: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:28: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:28: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:28: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:28: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:29: netdata ERROR : WEB_SERVER[static1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:30: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:30: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:14:30: netdata LOG FLOOD PROTECTION too many logs (201 logs in 43 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 1157 seconds.
2019-02-12 17:18:24: netdata LOG FLOOD PROTECTION reset for process 'netdata' (prevented 2351 logs in the last 278 seconds).
2019-02-12 17:18:24: netdata INFO  : MAIN : SIGNAL: Received SIGTERM. Cleaning up to exit...
2019-02-12 17:18:24: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 0...
2019-02-12 17:18:24: netdata INFO  : MAIN : EXIT: cleaning up the database...
2019-02-12 17:18:24: netdata INFO  : MAIN : Cleaning up database [1 hosts(s)]...
2019-02-12 17:18:24: netdata INFO  : MAIN : Cleaning up database of host '***********'...
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: stopping master threads...
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: Stopping master thread: PLUGIN[proc]
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: Stopping master thread: PLUGIN[diskspace]
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: Stopping master thread: PLUGIN[cgroups]
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: Stopping master thread: PLUGIN[tc]
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: Stopping master thread: PLUGIN[idlejitter]
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: Stopping master thread: STATSD
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: Stopping master thread: WEB_SERVER[static1]
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: Stopping master thread: PLUGINSD
2019-02-12 17:18:25: netdata INFO  : MAIN : EXIT: Stopping master thread: HEALTH
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 9 threads to finish...
2019-02-12 17:18:25: netdata INFO  : PLUGIN[proc] : cleaning up...
2019-02-12 17:18:25: netdata INFO  : PLUGIN[proc] : thread with task id 12688 finished
2019-02-12 17:18:25: netdata INFO  : PLUGIN[diskspace] : cleaning up...
2019-02-12 17:18:25: netdata INFO  : PLUGIN[diskspace] : thread with task id 12689 finished
2019-02-12 17:18:25: netdata INFO  : PLUGIN[cgroups] : cleaning up...
2019-02-12 17:18:25: netdata INFO  : PLUGIN[cgroups] : thread with task id 12690 finished
2019-02-12 17:18:25: netdata INFO  : PLUGIN[idlejitter] : cleaning up...
2019-02-12 17:18:25: netdata INFO  : PLUGIN[idlejitter] : thread with task id 12692 finished
2019-02-12 17:18:25: netdata INFO  : STATSD : cleaning up...
2019-02-12 17:18:25: netdata INFO  : STATSD : STATSD: stopping data collection thread 1...
2019-02-12 17:18:25: netdata INFO  : STATSD : STATSD: closing sockets...
2019-02-12 17:18:25: netdata INFO  : STATSD : STATSD: cleanup completed.
2019-02-12 17:18:25: netdata INFO  : STATSD : thread with task id 12693 finished
2019-02-12 17:18:25: netdata INFO  : WEB_SERVER[static1] : freeing local web clients cache...
2019-02-12 17:18:25: netdata INFO  : WEB_SERVER[static1] : stopped after 7706 connects, 7706 disconnects (max concurrent 6), 8593 receptions and 15527 sends
2019-02-12 17:18:25: netdata INFO  : WEB_SERVER[static1] : closing all web server sockets...
2019-02-12 17:18:25: netdata INFO  : WEB_SERVER[static1] : all static web threads stopped.
2019-02-12 17:18:25: netdata INFO  : WEB_SERVER[static1] : thread with task id 12695 finished
2019-02-12 17:18:25: netdata INFO  : PLUGINSD : cleaning up...
2019-02-12 17:18:25: netdata INFO  : PLUGINSD : stopping plugin thread: plugin:python.d
2019-02-12 17:18:25: netdata INFO  : PLUGINSD : stopping plugin thread: plugin:apps
2019-02-12 17:18:25: netdata INFO  : PLUGINSD : cleanup completed.
2019-02-12 17:18:25: netdata INFO  : PLUGINSD : thread with task id 12696 finished
2019-02-12 17:18:25: netdata INFO  : HEALTH : cleaning up...
2019-02-12 17:18:25: netdata INFO  : HEALTH : thread with task id 12697 finished
2019-02-12 17:18:25: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:18:25: netdata ERROR : STATSD_COLLECTOR[1] : POLLFD: LISTENER: processing POLLNVAL events for slot 0 fd 1 (events = 32, revents = 7)
2019-02-12 17:18:25: netdata ERROR : STATSD_COLLECTOR[1] : POLLFD: LISTENER: processing POLLNVAL events for slot 1 fd 1 (events = 32, revents = 8) (errno 22, Invalid argument)
2019-02-12 17:18:25: netdata ERROR : STATSD_COLLECTOR[1] : clock_gettime(7, &timespec) failed. (errno 22, Invalid argument)
2019-02-12 17:18:25: netdata INFO  : STATSD_COLLECTOR[1] : cleaning up...
2019-02-12 17:18:25: netdata INFO  : STATSD_COLLECTOR[1] : thread with task id 12699 finished
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:25: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:26: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:27: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:28: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2019-02-12 17:18:30: netdata ERROR : MAIN : Master thread PLUGIN[tc] takes too long to exit. Giving up... (errno 22, Invalid argument)
2019-02-12 17:18:30: netdata INFO  : MAIN : EXIT: freeing database memory...
2019-02-12 17:18:30: netdata INFO  : MAIN : Freeing all memory for host '***********'...
2019-02-12 17:18:30: netdata INFO  : MAIN : EXIT: removing netdata PID file '/opt/netdata/var/run/netdata.pid'...
2019-02-12 17:18:30: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
2019-02-12 17:18:30: netdata INFO  : PLUGINSD[python.d] : thread with task id 12704 finished
2019-02-12 17:18:30: netdata ERROR : PLUGINSD[apps] : requested a BEGIN on chart 'netdata.apps_cpu', which does not exist on host '????'. Disabling it.
2019-02-12 17:18:30: netdata ERROR : PLUGINSD[apps] : '/opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin' (pid 1439) disconnected after 413545 successful data collections (ENDs). (errno 22, Invalid argument)
2019-02-12 17:18:30: netdata INFO  : PLUGINSD[apps] : thread with task id 12703 finished
```

##### OS / Environment
```
Linux ********* 2.6.32-279.22.1.el6.centos.plus.x86_64 #1 SMP Wed Feb 6 05:16:56 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```
##### Netdata version (ouput of `netdata -V`)
netdata 1.11.1_rolling

**Comment by cakrit** [comment] 2019-02-12 10:36
Please [upgrade to the latest netdata](https://docs.netdata.cloud/packaging/installer/update/) and let us know if you still face the issue.

**Comment by Wing924** [comment] 2019-02-13 00:36
@cakrit I use static binary package. 1.11.1 is the latest released version.

**Comment by Wing924** [comment] 2019-02-13 04:54
I tested it against these kernels and versions:

netdata 1.11.1_rolling

|OS|kernel|compile from source|static binary|
|--|------|--|--|
|CentOS 6.3|2.6.32-279.22.1.el6.centos.plus.x86_64|OK|**NG**|
|CentOS 6.10|2.6.32-754.10.1.el6.x86_64|OK|**NG**|
|CentOS 7.6|3.10.0-693.2.2.el7.x86_64|OK|OK|

**Comment by cakrit** [comment] 2019-02-14 11:44
The latest binaries were tested with CentOS 6.x, but we have an issue with `kickstart-static64.sh`. Please monitor  #5390 for the resolution, or [select a different installation method](https://docs.netdata.cloud/packaging/installer/) if it's urgent.

**Comment by Wing924** [comment] 2019-02-14 22:48
@cakrit Could you tell me the google cloud link to downlod latest binary?

**Comment by Wing924** [comment] 2019-02-15 02:01
@cakrit I installed latest binary package: v1.12.0.
This still happen to me.

**Comment by cakrit** [comment] 2019-02-15 08:35
Ok, thanks. clock_gettime with clockid_t clk_id=7 is a request to get the CLOCK_BOOTTIME.
`man 2 clock_gettime` says that that's available after 2.6.39:
```
       CLOCK_BOOTTIME (since Linux 2.6.39; Linux-specific)
```

From the OS info you posted (2.6.32-279.22.1.el6.centos.plus.x86_64) it looks like netdata just wont work on Linux < 2.6.39.

**Comment by mfundul** [comment] 2019-02-15 11:23
I have verified that the prebuilt static binaries have issues with CentOS 6 (related to #5366).  I have also verified that compiling from source does not produce any such errors.

The problem is that code such as `#ifndef CLOCK_BOOTTIME` should run at compile time in CentOS 6 but it hasn't for the build environment of the prebuilt binary.

One idea is to choose the oldest possible kernel for the build environment for maximum compatibility of the static binary.

**Comment by paulfantom** [comment] 2019-02-15 13:40
We don't have full control over build env for creating static binary. It is running on Ubuntu 14.04 in travis CI.

**Comment by cakrit** [comment] 2019-02-15 13:41
So installation from source it is. @Wing924, are you good to close this one?

**Comment by Wing924** [comment] 2019-02-15 14:15
@cakrit I changed to install them from source temporary. But it's not good to ignore this problem since the docs suggest binary package can be run on anywhere.

I think we have a few options:
* build binary package per platform like rpm.
* Document which on OS the binary package is tested and can run.
* Use circleCI + Docker to build to get full control build env.

**Comment by paulfantom** [comment] 2019-02-15 15:06
> Use circleCI + Docker to build to get full control build env.

Docker is already used to build static binaries. It doesn't abstract everything as kernel is shared and proposed workaround needs control over which kernel is used.

CircleCI could be used, but we are Google-bound and not AWS-bound. Also this would need additional resources (money) to boot custom VMs (plural!) in AWS every day. Additionally this would need to be a complete refactor of current CI/CD pipeline.

**Closed** 2019-02-18 16:29 UTC
Labels: bug, needs triage
