### ISSUE TITLE
Updating to 1.2.5 from 1.2.4 

### ISSUE THREAD

**Issue by gaia** [netdata/netdata#9939] opened 2020-09-16 18:12 UTC
```
# bash <(curl -Ss https://my-netdata.io/kickstart.sh)
 --- Found existing install of Netdata under: / ---
 --- Attempting to update existing install instead of creating a new one ---
[/root]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron Wed 16 Sep 2020 11:10:34 AM PDT : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Wed 16 Sep 2020 11:10:34 AM PDT : INFO:  Current Version: 001024000233
Wed 16 Sep 2020 11:10:34 AM PDT : INFO:  Latest Version: 001024000233
Wed 16 Sep 2020 11:10:34 AM PDT : INFO:  Newest version (current=001024000233 >= latest=001024000233) is already installed
```

latest is > 001024000233, it's 1.2.5

**Comment by ilyam8** [comment] 2020-09-16 18:28
Indeed

> https://storage.googleapis.com/netdata-nightlies/sha256sums.txt

```cmd
115b4fa4471bfeb6e445546619a138612b99c4993f9b4c18714d5f72fa05e34a *./latest-version.txt
0e7f458f1049d6afde0c8b42c16f6aa3a7c069b850d44881e3a39fdc88466c0a *./netdata-latest.gz.run
424b3e7e5943cb63f81ad5a4232a5f9f124120bf787a09178af1bfd4be7402e7 *./netdata-latest.tar.gz
0e7f458f1049d6afde0c8b42c16f6aa3a7c069b850d44881e3a39fdc88466c0a *./netdata-v1.24.0-233-gb6632363.gz.run
424b3e7e5943cb63f81ad5a4232a5f9f124120bf787a09178af1bfd4be7402e7 *./netdata-v1.24.0-233-gb6632363.tar.gz
```

**Comment by johnpiers** [comment] 2020-09-17 02:05
This seems to have (been) resolved itself. The update script eventually updated to v1.25.0-7-nightly. So, for now, it appears that things are working as expected, regarding the nightly update process. Cheers.

**Comment by prologic** [comment] 2020-09-17 04:49
> This seems to have (been) resolved itself. The update script eventually updated to v1.25.0-7-nightly. So, for now, it appears that things are working as expected, regarding the nightly update process. Cheers.

FWIW our release process is still a little manual, so the next nightly for the current stable can be up to a day out.j Sorry about this, it was actually my fault as I was so exhausted the previous day I didn't get up  in time to re-enable nightlies 😀

**Comment by prologic** [comment] 2020-09-17 04:49
I will however close this as its not a bug, just a process deficiency and we're working on refactiring out entire release process (_its just taking time_).

**Closed by prologic** 2020-09-17 04:49 UTC
Labels: no changelog, question
