### ISSUE TITLE
Netdata not listening on port Ubuntu 18.10 Cosmic Cuttlefish:

### ISSUE THREAD

**Issue by SaintFenix** [netdata/netdata#4456] opened 2018-10-21 00:02 UTC
I recently installed fresh copies of Ubuntu 18.10 on two seperate machines and installed netdata on them, however though `systemctl ` shows that they are running, `ss-l` doesn't read anything listening on the port.

And when I try to navigate to `hostname:19999` I'm greeted with a Connection refused.

It's strange, as my virtual machines and physical machines which had it installed during 18.04 had it running fine after the in-place Ubuntu upgrade to 18.10. But the freshly installed 18.10 machines refuse to run it.

Wanted to see if anyone else was having this issue, or if I missed something.

Edit: I also installed using the Bash one liner, I tried the Apt repo's first but had no luck with that, apt purged them, and then installed using the one liner hoping for a better outcome, that is the current installation I still have.

**Comment by Kiousis** [comment] 2018-10-21 15:56
Are you sure that the port is open?
`sudo ufw status`

**Comment by SaintFenix** [comment] 2018-10-22 15:31
it returns: 
`Status: inactive`

I haven't setup a firewall on these machines, so that sounds about right.

**Comment by jaraddowning** [comment] 2018-11-09 03:00
I'm having the same on Ubuntu 18.04. All machines (tried on 3vms and two bare metal) give same result.

**Comment by paulfantom** [comment] 2018-11-18 20:50
I am closing this as it is essentially a duplicate of https://github.com/netdata/netdata/issues/3844

**Closed by paulfantom** 2018-11-18 20:50 UTC
Labels: area/packaging, duplicate, question
