### ISSUE TITLE
Libs libelf-dev, liblz4-dev, libuv1-dev and uuid-dev could not be installed

### ISSUE THREAD

**Issue by arthurduarte1** [netdata/netdata#10665] opened 2021-02-20 03:35 UTC
##### Bug report summary

Typed:
`$ sudo apt install libelf-dev -y`

Response:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libelf-dev : Depends: libelf1 (= 0.170-0.4ubuntu0.1) but 0.176-1.1build1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Then, typed:
`$ sudo apt install liblz4-dev -y`

Response:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 liblz4-dev : Depends: liblz4-1 (= 0.0~r131-2ubuntu3) but 1.9.2-2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

After that, I've typed:
`$ sudo apt install libuv1-dev -y`

And:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libuv1-dev : Depends: libuv1 (= 1.18.0-3) but 1.34.2-1ubuntu1.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

The last one was:
`$ sudo apt install uuid-dev -y`

And then:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 uuid-dev : Depends: libuuid1 (= 2.31.1-0.4ubuntu3.7) but 2.34-0.1ubuntu9.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

##### OS / Environment
```
Linux ip-172-31-30-16 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:56:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version
netdata 1.9.0

##### Component Name
`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

##### Steps To Reproduce
1. Open the console e type `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
2. Press Enter
3. It will ask to install the libs libelf-dev, liblz4-dev, libuv1-dev
4. Try to install typing: `sudo apt install libelf-dev liblz4-dev libuv1-dev uuid-dev`

##### Expected behavior
I just wanna all these libs been installed.
Thanks in advance.

**Comment by kalufinnle** [comment] 2021-07-23 03:34
encounter the same problem

**Comment by kalufinnle** [comment] 2021-07-23 03:35
libuuid1 (= 2.31.1-0.4ubuntu3.7) but 2.34-0.1ubuntu9.1 is to be installed
E: Unable to correct problems, you have held broken packages.

 libblkid-dev : Depends: libblkid1 (= 2.34-0.1ubuntu9) but 2.34-0.1ubuntu9.1 is to be installed
 uuid-dev : Depends: libuuid1 (= 2.34-0.1ubuntu9) but 2.34-0.1ubuntu9.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Ferroin** [comment] 2021-07-23 12:09
I can’t reproduce this in a clean Ubuntu 20.04 install. Can you please share the output of `cat /etc/apt/sources.list.d/*` on a system where you’re seeing this issue?

**Comment by rudysetiawan** [comment] 2021-07-23 14:23
got the same issue with ubuntu 16.04:

`The following packages have unmet dependencies:
 libuv1-dev : Depends: libuv1 (= 1.8.0-1) but 1.9.1-3+deb.sury.org~xenial+1 is to be installed
E: Unable to correct problems, you have held broken packages.`

my list of sources.list.d:
`deb http://apt.newrelic.com/debian/ newrelic non-free
deb http://ppa.launchpad.net/nginx/stable/ubuntu xenial main
# deb-src http://ppa.launchpad.net/nginx/stable/ubuntu xenial main
deb https://deb.nodesource.com/node_12.x xenial main
deb-src https://deb.nodesource.com/node_12.x xenial main
deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main
# deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main
deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main
# deb-src http://ppa.launchpad.net/ondrej/php/ubuntu xenial main
deb https://archive.serverdensity.com/ubuntu/ xenial main
deb https://archive.serverdensity.com/ubuntu/ xenial main
`

**Comment by Ferroin** [comment] 2021-07-23 15:09
OK, it’s exceedingly likely that this is a package dependency conflict caused by something in a third-party repository (hence my query about the contents of `/etc/apt/source.list.d`. We’ve had people report such issues a couple of times before as well, and there’s unfortunately not much we can do about it. Assuming it’x a 64-bit x86 system, you should be able to get things working correctly by [using our pre-built static version](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64), or alternatively our [official DEB packages](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/packages).

Otherwise, the general approach I would suggest to figure out exactly which repo is causing the issues is as follows:

1. Note down the exact list of extra repositories on the problem system (you don’t need to worry about source repos, just the regular ones).
2. Get a clean install of Ubuntu (I recommend either using a Docker image, or a locally created VM that you’ve taken a snapshot of, as you’ll need to get back to a clean install a number of times while testing). Ideally, this should _not_ be a pre-existing Ubuntu image from a VPS provider, but an actual clean install from an install CD (or installation ISO image), because most VPS providers include additional repos in their base images (and one of those may be the problem repo).
3. Add exactly one of the repos noted in step 1.
4. Attempt to install Netdata and see if it fails with a complaint about dependencies (you probably want to add the `--dont-start-it` flag to the installer, which will cause it to just attempt the install without actually trying to start the Netdata service).
5. If step 4 suceeded (that is, there was no failure to install netdata), repeat from step 2 with a different repo.

**Comment by rudysetiawan** [comment] 2021-07-29 14:38
@Ferroin  yupp in fact I used the static version and it just worked right away. Thank you!

**Comment by ilyam8** [comment] 2021-09-07 14:01
> it’s exceedingly likely that this is a package dependency conflict caused by something in a third-party repository

Closing because that is not Netdata bug and _the fix_ is provided.

**Closed by ilyam8** 2021-09-07 14:01 UTC
Labels: bug, area/packaging

**Comment by xiang-xx** [comment] 2021-12-02 02:13
uninstall libuv1，and reinstall it。It works to me.

**Comment by ntsanq** [comment] 2022-08-11 13:36
@xiang-xx thanks for your cmt

**Comment by stex2005** [comment] 2024-10-08 21:59
Installation of ROS2 foxy seems to be messing with libelf-dev
