### ISSUE TITLE
alarm-notify.sh: WARNING: Cannot find file

### ISSUE THREAD

**Issue by adrfantini** [netdata/netdata#5136] opened 2019-01-08 19:54 UTC
I am using netdata on ArchLinux. I am aware that Arch uses different netdata locations compared to the standard, and this might be what is happening here. This Arch box uses `ssmtp`.

I need to send mail notifications to the email specified in `/etc/netdata/health_alarm_notify.conf`:
```
EMAIL_SENDER="email+netdata@gmail.com"
DEFAULT_RECIPIENT_EMAIL="email+netdata@gmail.com"
```
Mail seems to work, but the sender and recipient are not what specified: the "+netdata" part is missing.
This might be related to this:
```
sudo su -s /bin/bash netdata
/usr/lib/netdata/plugins.d/alarm-notify.sh test
```
returning:
```
# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2019-01-08 20:42:37: alarm-notify.sh: WARNING: Cannot find file '/usr/local/lib/netdata/conf.d/health_alarm_notify.conf'.
2019-01-08 20:42:37: alarm-notify.sh: WARNING: Cannot find file '/usr/local/etc/netdata/health_alarm_notify.conf'.
2019-01-08 20:42:40: alarm-notify.sh: INFO: sent email notification for: serverino test.chart.test_alarm is WARNING to 'root'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2019-01-08 20:42:40: alarm-notify.sh: WARNING: Cannot find file '/usr/local/lib/netdata/conf.d/health_alarm_notify.conf'.
2019-01-08 20:42:40: alarm-notify.sh: WARNING: Cannot find file '/usr/local/etc/netdata/health_alarm_notify.conf'.
2019-01-08 20:42:42: alarm-notify.sh: INFO: sent email notification for: serverino test.chart.test_alarm is CRITICAL to 'root'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2019-01-08 20:42:43: alarm-notify.sh: WARNING: Cannot find file '/usr/local/lib/netdata/conf.d/health_alarm_notify.conf'.
2019-01-08 20:42:43: alarm-notify.sh: WARNING: Cannot find file '/usr/local/etc/netdata/health_alarm_notify.conf'.
2019-01-08 20:42:45: alarm-notify.sh: INFO: sent email notification for: serverino test.chart.test_alarm is CLEAR to 'root'
# OK
```

I'm not sure if the issue here is due to improperly configured `ssmtp` or to the wrong paths `alarm-notify.sh` expects.

**Comment by paulfantom** [comment] 2019-01-08 20:32
Seems like a package was build with `./configure --prefix=/usr/local`, but installed with out this prefix.

**Comment by adrfantini** [comment] 2019-01-09 08:13
This is the pkgbuild: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/netdata

I opened a bug report for Arch: https://bugs.archlinux.org/task/61316
I'll follow the bugreport and report back any news.

**Comment by mpan-pl** [comment] 2019-01-09 09:23
The exact command used to build this package is given

**Comment by adrfantini** [comment] 2019-01-09 09:32
This is probably also affecting this other arch-related bug:
https://bugs.archlinux.org/task/60919

Thanks for taking interest in this.

**Comment by mpan-pl** [comment] 2019-01-09 09:42
The file, as it is exiting the build process.

[alarm-notify.sh](https://github.com/netdata/netdata/files/2740237/alarm-notify.sh.txt)

**Comment by paulfantom** [comment] 2019-01-09 16:20
I see it is downloading v1.11.1, could someone verify if this is still problematic when building from master?

**Comment by cakrit** [comment] 2019-01-10 16:38
I was able to replicate it with the latest, but NOT with the command in https://github.com/netdata/netdata/issues/5136#issuecomment-452629212

I get the `/usr/local` which is the `ac_default_prefix` in the generated `configure` in the post vars, only when I execute `configure` without any arguments and then run make.

**Comment by cakrit** [comment] 2019-01-16 12:58
I may have run into a similar situation by accident. Can you gents check for the following in your systems?
Find a file called `.environment.sh`. It's supposed to be in the user config directory (e.g. `/etc/netdata`), but I saw it placed in the directory with the source files, under `packaging/installer/`.

There are two parameters of interest there, CFLAGS and REINSTALL_COMMAND. I suspect that in REINSTALL_COMMAND, you may find a `--install` option.  

Even if that option is not there now, the installer could have been run with an option to install to another directory at some point. It called `configure` passing the different directories and it messed up the built binary. The effect on my machine was that when I executed the following:

`/usr/sbin/netdata -c /etc/netdata/netdata.conf -W get global 'config directory' /etc/netdata`
 
I got `/opt/netdata/etc/netdata`

To get rid of it, since I wasn't passing the directory argument from anywhere any more,  I had to do a `make clean` inside the source directory, before running the installer again.

**Comment by paulfantom** [comment] 2019-01-16 14:20
@cakrit First of all Arch packages aren't created with our shell installer script, but directly with `configure` and `make`. This means that there won't be any `.environment*` files created and there is no way to use `--install` (which translates to `./configure --prefix <sth>`.
Secondly no installation method create `.environment.sh` file in user configuration directory (usually `/etc/netdata`). Installer script from before https://github.com/netdata/netdata/commit/0dbd4fb0cba640347d8fd88fec6071a5510828e5 placed `.environment.sh` file inside `packaging/installer/` (inside a directory with source code). After that commit installer puts file with similar values into user configuration directory (usually `/etc/netdata`) with a name `.environment`.


This is either some problem with our `configure.ac` script or some strange Arch-related issue. I will try to reproduce this on some other OS (I *don't* use Arch :P) with commands executed while building package.

Right now it looks like `--prefix` passed to `./configure` is not used and autoconf assignes default value of `/usr/local` (https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/Default-Prefix.html).

**Comment by paulfantom** [comment] 2019-01-16 15:09
I replicated this bug. After running `make DESTDIR=tmpbuild install` it created only a small subset of needed files, which means that our `configure.ac` is very broken. Somehow our installer script is automatically fixing all this problems.

Currently I don't have any ideas how to solve this problem. However since in the following weeks we are moving away from autotools to CMake and away from installer script doing magic things, this issue might get solved "accidentally" :smile:

**Comment by mpan-pl** [comment] 2019-01-17 21:50
The installer script ends in an error, but since it produces the related files before that, it was enough to point me to the right general direction — despite initially the exact direction was wrong.

The aforementioned invocation of `configure` produces valid output (even for 1.11.1), as long as it is based on the actual source code from the repository. It fails only for the release version of *netdata*, as found in [netdata-v1.11.1.tar.gz](https://github.com/netdata/netdata/releases/tag/v1.11.1). The reason is… the release package hardcodes “/usr/local” paths in “help/notifications/alarm-notify.sh”. *Yes, something is wrong. No, it isn’t Arch-related issue.*

In the process, accidentally, I have discovered few other oddities. As a non-user I am not the one interested in reporting them as issues, but if someone wants to:

1. The install script has no option to split the process of building and installing the software. It requies the whole operation to be done in one step and building with root privileges.
2. If the `--install` is used, the script produces a set of paths that make little sense. For example `netdata-installer.sh
 --install /usr` wants to do something in “/usr/netdata/var” and so on. And it prepends it blindly, so “/” becomes “//netdata”.
3. The general approach feels against common practices and a dangerous path to follow. Writing a build system is a complex task that requires immerse understanding of various platforms and possible scenarios. Point № 1 shows a problem with a task that is the goal of a build script.

**Comment by paulfantom** [comment] 2019-01-17 21:57
Thanks for your insight @mpan-pl. All those points are valid and they are related to why we are currently in a process of transforming that shell installer script into proper build system with proper packaging.

**Comment by mpan-pl** [comment] 2019-01-17 22:08
OK. I guess¹ it makes little sense to fix that now, if a complex solution is coming. Better to focus on it. :)
____
¹ But this is my opinion — the maintainer may differ.

**Comment by paulfantom** [comment] 2019-01-17 22:37
I wasn't clear, we are in a process of dropping our own shell "build and install" script and want to move towards proper build system. Our plan is to drop autotools, move to CMake and use CPack for packaging. But first I need to do some cleanup :)

**Comment by cakrit** [comment] 2019-01-21 18:51
This isn't limited to Arch. I just reproduced on a fedora VM, by just executing kickstart.sh. 
As @mpan-pl mentioned, it's the tar.gz archives that have the problem, because in them the scripts have already been corrupted with wrong paths. I saw the same thing in `system/edit-config`, which is installed as `/etc/netdata/`.

The tar.gz should NOT have such files with hardcoded paths at all, they are the output of make, using their .in counterparts. As we have shifted the entire update process to use the google cloud tars, we'll start having more and more users with problems, so a fix for this can't wait.

**Comment by cakrit** [comment] 2019-01-21 19:46
I traced it to the options passed to `configure` in `.travis/create_artifacts.sh`. PR #5244 is an attempt to fix it.

**Comment by svenstaro** [comment] 2019-01-22 13:21
Can you make a release with this fix in? It's quite important for Arch.

**Comment by cakrit** [comment] 2019-01-22 15:37
Release 1.12 will be available next week. In the meantime, anyone running the netdata-updater will get the  tar.gz with the fix from tomorrow (nightly build).

**Comment by cakrit** [comment] 2019-01-22 15:41
I'm reopening so that we get a verification that tonight's nightly build resolves the issue for you.

**Comment by szywo** [comment] 2019-01-22 17:31
node.d also tries to look for plugins' configs in `/usr/local/etc/netdata` instead of `/etc/netdata`. I wiped out old install and reinstalled with `kickstart.sh`, still the same, had to `ln -s /etc/netdata /usr/local/etc/netdata' as a temporary workaround.
My current netdata version: `v1.12.0-rc3-18-nightly`. Will it change after tonight's nightly build? If not how can I tell if my instance was updated? (there were commit hashes before)

**Comment by cakrit** [comment] 2019-01-23 08:55
I just ran the `netdata-updater` that was in my cron and verified that the paths are as expected now.  
The version you will see is `netdata v1.12.0-rc3-24-nightly` and my `/etc/netdata/.environment` has the following checksum in it:

```
NETDATA_TARBALL_CHECKSUM="1bfd1e0eeeba15f41710866189ac2b05c88a0055c9b96477da889fbe372d3504"
```

**Comment by szywo** [comment] 2019-01-23 11:09
Indeed, got `v1.12.0-rc3-24-nightly` tonight. Removed symlink, `/usr/libexec/netdata/plugins.d/node.d.plugin 1 snmp` works as expected, `edit-config` also. No more missing config entries in `/var/log/netdata/error.log` about `/usr/local/etc/netdata`

**Comment by cakrit** [comment] 2019-01-23 13:17
Excellent, thanks @szywo

**Closed by cakrit** 2019-01-23 13:17 UTC
Labels: area/packaging, bug, priority/high

**Comment by adrfantini** [comment] 2019-02-24 17:49
Can confirm fixed in the latest Arch release.
