### ISSUE TITLE
Installation of Netdata fails because of missing packages python-mysqldb python-psycopg2 python-pymongo 

### ISSUE THREAD

**Issue by e-alfred** [netdata/netdata#10033] opened 2020-10-06 09:02 UTC
##### Bug report summary
Installing Netdata fails because of missing packages

##### OS / Environment

```
Ubuntu 20.04

Linux cloud 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

##### Steps To Reproduce

1. Install Netdata

```
Downloading the Netdata script...
Updating lib...
Checking if Netdata is already installed...
Installing Netdata...
[\] System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version: 
 --- Fetching script to detect required packages... --- 
[/tmp/netdata-kickstart-0fWVbFt7KA]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-0fWVbFt7KA/install-required-packages.sh https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh  OK  

 --- Running downloaded script to detect required packages... --- 
[/tmp/netdata-kickstart-0fWVbFt7KA]# /usr/bin/bash /tmp/netdata-kickstart-0fWVbFt7KA/install-required-packages.sh --dont-wait --non-interactive netdata-all Loading /etc/os-release ...

/etc/os-release information:
NAME            : Ubuntu
VERSION         : 20.04.1 LTS (Focal Fossa)
ID              : ubuntu
ID_LIKE         : debian
VERSION_ID      : 20.04

We detected these:
Distribution    : ubuntu
Version         : 20.04
Codename        : 20.04.1 LTS (Focal Fossa)
Package Manager : install_apt_get
Packages Tree   : debian
Detection Method: /etc/os-release
Default Python v: 2 

Searching for distro_sdk ...
Searching for autoconf_archive ...
 > Checking if package 'autoconf-archive' is installed...
Searching for libz_dev ...
 > Checking if package 'zlib1g-dev' is installed...
Searching for libuuid_dev ...
 > Checking if package 'uuid-dev' is installed...
Searching for libmnl_dev ...
 > Checking if package 'libmnl-dev' is installed...
Searching for json_c_dev ...
 > Checking if package 'libjson-c-dev' is installed...
Searching for libuv ...
 > Checking if package 'libuv1-dev' is installed...
Searching for lz4 ...
 > Checking if package 'liblz4-dev' is installed...
Searching for openssl ...
 > Checking if package 'libssl-dev' is installed...
Searching for judy ...
 > Checking if package 'libjudy-dev' is installed...
Searching for libelf ...
 > Checking if package 'libelf-dev' is installed...
dpkg-query: no packages found matching libelf-dev
Searching for python_pymongo ...
 > Checking if package 'python-pymongo' is installed...
dpkg-query: no packages found matching python-pymongo
Searching for python_mysqldb ...
 > Checking if package 'python-mysqldb' is installed...
dpkg-query: no packages found matching python-mysqldb
Searching for python_psycopg2 ...
 > Checking if package 'python-psycopg2' is installed...
dpkg-query: no packages found matching python-psycopg2

The following command will be run:

Running in non-interactive mode
NOTE: Running apt-get update and updating your APT caches ...
apt-get -yq update 
apt-get -yq install libelf-dev python-mysqldb python-psycopg2 python-pymongo 


Running in non-interactive mode
NOTE: Running apt-get update and updating your APT caches ...
apt-get -yq update 
Hit:1 http://at.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://at.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://at.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 https://download.docker.com/linux/ubuntu focal InRelease
Hit:5 http://at.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists...
apt-get -yq install libelf-dev python-mysqldb python-psycopg2 python-pymongo 
Reading package lists...
Building dependency tree...
Reading state information...
Package python-mysqldb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-psycopg2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-pymongo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-mysqldb' has no installation candidate
E: Package 'python-psycopg2' has no installation candidate
E: Package 'python-pymongo' has no installation candidate



We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/netdata/netdata/issues


 FAILED  

 WARNING  It failed to install all the required packages, but installation might still be possible. 

 ABORTED  Stopping due to non-interactive mode. Fix the issue or retry installation in an interactive mode. 

```

##### Expected behavior
Installation of Netdata should succeed without error.

**Comment by e-alfred** [comment] 2020-10-06 11:22
Solved by setting Python 3 as default:

`sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2`

Please add a message for deprecated or non-existent packages if the Python version is too old that you need at least Python 3.

**Comment by OdysLam** [comment] 2020-10-07 06:49
Thanks for that @e-alfred, a member from the team will respond promptly as we look into this bug™️

Welcome to our little community :) If you have any questions, please don't hesitate to reach out!

**Comment by ilyam8** [comment] 2021-08-31 14:51
Tested the kickstart script on a clean ubuntu 20.04, can't reproduce the problem. Closing the issue.

**Closed by ilyam8** 2021-08-31 14:51 UTC
Labels: bug, area/packaging
