### ISSUE TITLE
[Bug]: Netdata crashing with ABRT

### ISSUE THREAD

**Issue by johnramsden** [netdata/netdata#6999] opened 2019-10-05 23:11 UTC
##### Bug report summary

Starting today netdata has been repeatedly crashing on _multiple_ servers. It seems to be ending with the signal `ABRT`.

After crashing multiple times it starts working again.

This is what's repeated in my logs:

```
Oct 05 06:55:16 kv2 systemd[1]: Started Real time performance monitoring.
Oct 05 06:55:36 kv2 systemd[1]: netdata.service: Main process exited, code=killed, status=6/ABRT
Oct 05 06:55:36 kv2 systemd[1]: netdata.service: Failed with result 'signal'.
Oct 05 06:55:36 kv2 systemd[1]: netdata.service: Triggering OnFailure= dependencies.
Oct 05 06:56:06 kv2 systemd[1]: netdata.service: Service hold-off time over, scheduling restart.
Oct 05 06:56:06 kv2 systemd[1]: netdata.service: Scheduled restart job, restart counter is at 36.
Oct 05 06:56:06 kv2 systemd[1]: Stopped Real time performance monitoring.
Oct 05 06:56:06 kv2 systemd[1]: Starting Real time performance monitoring...
```

##### OS / Environment

Ubuntu 18.04

##### Netdata version

netdata v1.17.1-182-nightly

**Comment by mfundul** [comment] 2019-10-06 05:10
Can you share your error log (`/var/log/netdata/error.log`)?

**Comment by johnramsden** [comment] 2019-10-06 22:50
@mfundul Is there anything private in the error logs that will expose anything about my server? Should I share it privately?

**Comment by mfundul** [comment] 2019-10-07 03:52
> 
> 
> @mfundul Is there anything private in the error logs that will expose anything about my server? Should I share it privately?

You may send it to markos@netdata.cloud

**Comment by johnramsden** [comment] 2019-10-07 04:58
@mfundul sent.

I believe the error started sometime around `2019-10-05 16:28`. Let me know if you can tell anything from the logs, if you need the logs from the other servers I can send those too.

**Comment by mfundul** [comment] 2019-10-07 05:34
Some timestamps in the log have a 5 hour difference between them. The timestamps are all out of order in the log. Did you change something time related in your configuration?

**Comment by mfundul** [comment] 2019-10-07 05:35
Other than that I have seen an issue with the database in the logs that I will be working on to fix as soon as possible.

**Comment by mfundul** [comment] 2019-10-07 06:04
@johnhomelan can you send me another server's log in case I'm missing something here? The log flood protection is hiding some prints.

**Comment by johnramsden** [comment] 2019-10-07 06:35
@mfundul Sure. I'll send you logs from a few servers. I believe they all had the problem start on the same couple of days, so I'll send you those few days from all the servers.

**Comment by mfundul** [comment] 2019-10-07 14:56
@johnramsden please let us know if the problem persists when you update to tomorrow's nightly builds.

**Comment by johnramsden** [comment] 2020-01-11 06:46
@mfundul I believe this error has cropped up again, Identical 6/ABRT occurring on all of our servers. Should I send you some logs again?

**Comment by mfundul** [comment] 2020-01-13 13:30
@johnramsden yes please. What netdata version are you running?

**Comment by johnramsden** [comment] 2020-01-15 02:37
netdata v1.14.0-rc0-20-nightly

Sent logs.

**Comment by prologic** [comment] 2020-01-15 02:59
> @mfundul netdata v1.14.0-rc0-20-nightly

Out of curiosity; why are you running v1.14.x and not the latest v1.19.x?

**Comment by mfundul** [comment] 2020-01-15 05:57
@johnramsden from the logs that I received I can observe:
sk2 has been 14 days without a restart, probably updates are not working there.
m01 has an ancient version of v1.14.0-rc0-12-nightly, you should manually update this machine.
db1 received multiple SIGTERM signals during the day and that's the reason it keeps shutting down.

Can you point me to where I should look?

**Comment by johnramsden** [comment] 2020-01-16 01:24
@mfundul Interesting I guess the auto updater is not working, any idea why that would be? I have it in my crontab.

I'll track down some dates and send you some more specific logs.

db1s SIGTERMs yesterday were unrelated.

**Comment by johnramsden** [comment] 2020-01-16 01:27
I just attempted to upgrade one of the servers:

```
/etc/cron.daily/netdata-updater

Wed Jan 15 19:25:53 CST 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
79c6195551c48a4c84494c94044d6dcf9a47a931ac9e22fe7f842c5c4e88c50d *./latest-version.txt
6457d347d86dcaa27e91262547541ff27a095cbb9c914e337d02a434c1853b3e *./netdata-latest.gz.run
851c8a87210f50a7723c259de93a027e65cbec40de900afcb39cf8f202d5a22e *./netdata-latest.tar.gz
6457d347d86dcaa27e91262547541ff27a095cbb9c914e337d02a434c1853b3e *./netdata-v1.19.0-323-g516b955f.gz.run
851c8a87210f50a7723c259de93a027e65cbec40de900afcb39cf8f202d5a22e *./netdata-v1.19.0-323-g516b955f.tar.gz
Wed Jan 15 19:25:53 CST 2020 : INFO:  Newest version is already installed
```

However:

```
netdata -v
netdata v1.14.0-rc0-12-nightly
```

I also tried restarting, and after it shows the same version

**Comment by mfundul** [comment] 2020-01-16 13:14
@prologic @Ferroin any thoughts on the updater issue?

**Comment by Ferroin** [comment] 2020-01-16 14:05
@johnramsden Was this installed using `kickstart-static64.sh`? If so, that's probably why the updater isn't working, it didn't work correctly for installs through `kickstart-static64.sh` prior to #7704 being merged 2 days ago.

**Comment by johnramsden** [comment] 2020-01-16 19:57
@Ferroin I used:

```
netdata-installer.sh --dont-wait --auto-update
```

Should I just do a full reinstall?

**Comment by Ferroin** [comment] 2020-01-16 20:01
OK, that's odd then that the updater isn't working. I don't know that you _need_ to do a full install, but it may fix auto-updates if you do. Unless you have some specific reason to use `netdata-installer.sh` directly, it' is generally better to use the `kickstart.sh` script you can find on the website instead as it's better tested (and will eventually use binary package instead of having to build locally).

**Comment by johnramsden** [comment] 2020-01-16 20:07
OK, will reinstall and see if the issue is gone. Thanks.

**Comment by johnramsden** [comment] 2020-01-18 19:50
So I did complete reinstalls and have the same error occurring. I just noticed I got the error right after the cron job ran to update. I didn't see anything in the logs that might be of use but I sent them @mfundul  just in case.

Also of note, the cron jobs seem to have started outputting the following in the last week, which are sending me emails. Should this be occurring?

```
/etc/cron.daily/netdata-updater:
--auto-update
```

At 06:26CT:

```
Jan 18 06:26:15 m01 systemd[1]: netdata.service: Main process exited, code=killed, status=6/ABRT
Jan 18 06:26:15 m01 systemd[1]: netdata.service: Failed with result 'signal'.
```

Version: netdata v1.19.0-336-nightly

**Comment by mfundul** [comment] 2020-01-18 20:17
Ok, this is very strange. So, in the most recent logs there are 2 netdata shutdown events and both of them have been triggered by the system so it's not an unexpected sudden crash.

Secondly, there doesn't even seem to be any crash whatsoever. Especially in the second shutdown event that matches the systemd timestamp there is a proper shutdown procedure in the logs that prints even the last message:
```
2020-01-18 06:26:15: netdata INFO  : MAIN : EXIT: removing netdata PID file '/var/run/netdata/netdata.pid'...
2020-01-18 06:26:15: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
```
After this message it is practically impossible for the netdata agent to crash since it exits immediately.

The first shutdown was triggered by SIGTERM. The second shutdown probably from the updater since the version changed.

The final very strange thing is that the earlier version in the logs is `v1.19.0-345-nightly` and after the update it becomes `v1.19.0-336-nightly` which is a smaller number! The only way I can explain this is if netdata was installed from a branch other than the master branch.

**Comment by johnramsden** [comment] 2020-01-18 20:30
Isn't v1.19.0-336 after v1.19.0-345 ?

When I attempt to upgrade it says it's on v1.19.0-336-nightly , the latest.

Is it possible the cronjob is sending an abort signal? That's the message I get in the systemd logs, and is interpreted as failure.

**Comment by mfundul** [comment] 2020-01-18 20:36
336 is indeed the latest, 345 shouldn't have been possible.

**Comment by johnramsden** [comment] 2020-01-18 21:31
Strange... I installed from master.

**Comment by johnramsden** [comment] 2020-01-20 07:38
Confirmed, that when I run a manual update that data is stopped with 6/ABRT.

I assume this is due to the following code triggering the signal which is treated as failure by systemd:

https://github.com/netdata/netdata/blob/c7e13846a87054d1e6e412d8edbc25b9dcbc684f/packaging/installer/functions.sh#L494-L506

Would it be possible to maybe check if the system is managed with systemd, and if so shut down the service with the unit?

Or just in some way that is not treated as failure by the service manager?

**Comment by Ferroin** [comment] 2020-01-21 00:03
Reopening this to track the SIGABRT issue, which is orthogonal to #7798. We need to figure out why this is happening, because it shouldn't be (no correctly functioning program should be receiving a SIGABRT).

@johnramsden Can you try triggering this bug while monitoring the agent with `strace` and report back here with the output?

Just start the agent normally, figure out what PID it's running as, then run:

```
strace -p <PID>
```

as root, with `<PID>` replaced by the agent's PID. Then try to trigger the bug, and finally upload the output from the `strace` command to a pastebin site (probably will be too big for GitHub) and post the link here.

**Comment by johnramsden** [comment] 2020-01-25 01:56
@Ferroin Right now there hasn't been a new release so I haven't been able to trigger the bug with the updater yet. I'm just waiting for a new nightly.

Not sure if it's even still wanted since a fix potentially went in #7814 ?

**Comment by prologic** [comment] 2020-01-28 23:02
@Ferroin Let's get this refined and someone on it to fix the underlying root cause here (_if still relevant_).

**Comment by Ferroin** [comment] 2020-01-29 12:34
With #7814 being merged, it's going to be non-trivial to reproduce this long term. I'd still kind of like to get this fixed eventually, but it shouldn't be affecting users anymore.

Given that and the fact that we don't currently know what exactly is causing this, I'm dropping the priority to low and adding the 'needs triage' flag.

**Comment by prologic** [comment] 2020-01-29 23:01
Did we ever manage to get a Stack Trace / Core Dump at all? We should still be able to reproduce this locally in our own dev environments and produce a Stack Trace?

**Comment by Ferroin** [comment] 2020-01-30 12:55
> Did we ever manage to get a Stack Trace / Core Dump at all? We should still be able to reproduce this locally in our own dev environments and produce a Stack Trace?

Not that I know of, but yes, we should be able to repro this in our dev environments, since it _should_ happen also if you run the unpatched kickstart script to do an upgrade.

**Comment by cakrit** [comment] 2020-09-02 11:13
Closing until we have a reoccurence.

**Comment by marcelmfs** [comment] 2022-10-19 09:39
I have built v1.36.1 from the repository and am facing this issue. My work around is to stop abrtd altogether but that's not ideal, albeit I don't really care too much for abrtd on this instance, it only runs netdata as proxy, no dbengine, no web, only proxying traffic.

**Comment by MrZammler** [comment] 2022-10-19 11:19
Hi @marcelmfs . Can you share your `error.log` ? You can send to manolis@netdata.cloud

Does it happen during shutdown ? Could you maybe try a nightly build?

**Comment by marcelmfs** [comment] 2022-10-19 11:30
Hello @MrZammler - no, it happens during startup whenever I issue `systemctl restart netdata`, I see processes starting, but they get aborted right away, I could try a nightly build later today...

**Comment by ilyam8** [comment] 2023-01-10 18:30
@marcelmfs please update to the latest nightly (at least v1.37.0-113) and check if you still have the issue. If yes - please open a new bug report.

**Closed by ilyam8** 2023-01-10 18:30 UTC
Labels: bug, priority/low, area/database
