### ISSUE TITLE
[Bug]: Our description of manual build preparation does not correspond reality

### ISSUE THREAD

**Issue by iigorkarpov** [netdata/netdata#13034] opened 2022-05-30 08:10 UTC
### Bug description

According to our [page, describing the manual build preparations](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/manual), the user should run

` bash <(curl -sSL https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh)`

to install the dependencies. But in fact this script does not work without specifying parameters, and in the proposed form of launching it is impossible to specify parameters:

`bash <(curl -sSL https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh)
OPTIONS:

/dev/fd/63 [--dont-wait] [--non-interactive] \
  [distribution DD [version VV] [codename CN]] [installer IN] [packages]`

### Expected behavior

The documentation must be rewritten so that the process is possible. There is no point in making it the one-liner, because the manual build process assumes some command line skills.

### Steps to reproduce

Run above command.

### Installation method

from source

### System info

```shell
Linux debian-11-new 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
N/A
```

**Comment by Ferroin** [comment] 2022-05-31 15:01
Actually, you can just manually append parameters to the command line and it generally works.

We need to get rid of that damn `<()` syntax though, it only works in some shells, does not work properly with wrappers (such as `sudo` or `doas`), and makes some error types much harder to debug.

**Comment by iigorkarpov** [comment] 2022-06-02 09:47
Even considering what you say, our documentation is misleading, isn't it? An idea of kickstart is to make it possible for using by an inexperienced user.

**Comment by Ferroin** [comment] 2022-06-29 11:00
Closing as duplicate of https://github.com/netdata/netdata/issues/12427

**Closed by Ferroin** 2022-06-29 11:00 UTC
Labels: bug, area/packaging, area/docs, priority/low
