### ISSUE TITLE
Zookeeper restart brake the netada plugin

### ISSUE THREAD

**Issue by jrevillard** [netdata/netdata#10753] opened 2021-03-11 14:09 UTC
##### Bug report summary

WHen Zk is restarted, the netdata plugin crash like this:

```
2021-03-11 14:06:06: go.d ERROR: zookeeper[local_rcc] PANIC: runtime error: invalid memory address or nil pointer dereference
2021-03-11 14:06:07: go.d ERROR: zookeeper[local_rcc] PANIC: runtime error: invalid memory address or nil pointer dereference
2021-03-11 14:06:08: go.d ERROR: zookeeper[local_rcc] PANIC: runtime error: invalid memory address or nil pointer dereference

```

##### OS / Environment
```
[root@zk1 [RCC] ~]#  uname -a; grep -Hv "^#" /etc/*release
Linux zk1.int-bigeys-rcc.openstack.local 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

##### Netdata version
```
 [root@zk1 [RCC] ~]# /opt/netdata/bin/netdata -V
netdata v1.29.1
```

##### Component Name

Zookeeper plugin

##### Steps To Reproduce

1. Install Zk
2. Install and configure netdata with the Zk plugin
3. restart Zk

##### Expected behavior

Netdata should see that Zk is back and send metrics...

**Comment by ilyam8** [comment] 2021-03-11 15:57
Hm, i tried to reproduce it, but no luck so far. 

 - start [jplock/zookeeper](https://hub.docker.com/r/jplock/zookeeper) docker container
 - run go.d.plugin in the debug mode (`./go.d.plugin -d -m zookeeper`)
 - docker restart container; docker stop; wait; docker start container

 - restart

<details>
<summary>output click click</summary>

```cmd
BEGIN 'netdata.execution_time_of_zookeeper_local' 1000050
SET 'time' = 5
END

[ DEBUG ] run[manager] run.go:41 tick 16
[ ERROR ] zookeeper[local] zookeeper.go:99 dial tcp 127.0.0.1:2181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 17
[ ERROR ] zookeeper[local] zookeeper.go:99 read tcp 127.0.0.1:53534->127.0.0.1:2181: read: connection reset by peer
[ DEBUG ] run[manager] run.go:41 tick 18
BEGIN 'zookeeper_local.requests' 1000115
SET 'outstanding_requests' = 0
END

BEGIN 'zookeeper_local.requests_latency' 1000115
SET 'min_latency' = 0
SET 'avg_latency' = 0
SET 'max_latency' = 0
END

BEGIN 'zookeeper_local.connections' 1000115
SET 'num_alive_connections' = 2
END

BEGIN 'zookeeper_local.packets' 1000115
SET 'packets_received' = 2
SET 'packets_sent' = 0
END
```


</details>

 - stop; wait; start

<details>
<summary>output click click</summary>

```cmd
BEGIN 'zookeeper_local.server_state' 999952
SET 'server_state' = 4
END

BEGIN 'netdata.execution_time_of_zookeeper_local' 999952
SET 'time' = 3
END

[ DEBUG ] run[manager] run.go:41 tick 13
[ ERROR ] zookeeper[local] zookeeper.go:99 dial tcp 127.0.0.1:2181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 14
[ ERROR ] zookeeper[local] zookeeper.go:99 dial tcp 127.0.0.1:2181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 15
[ ERROR ] zookeeper[local] zookeeper.go:99 dial tcp 127.0.0.1:2181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 16
[ ERROR ] zookeeper[local] zookeeper.go:99 dial tcp 127.0.0.1:2181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 17
[ DEBUG ] run[manager] run.go:41 tick 18
[ DEBUG ] zookeeper[local] job.go:170 skip the tick due to previous run hasn't been finished
[ ERROR ] zookeeper[local] zookeeper.go:99 read tcp 127.0.0.1:50752->127.0.0.1:2181: i/o timeout
[ DEBUG ] run[manager] run.go:41 tick 19
[ DEBUG ] run[manager] run.go:41 tick 20
[ DEBUG ] run[manager] run.go:41 tick 21
BEGIN 'zookeeper_local.requests' 4000097
SET 'outstanding_requests' = 0
END

BEGIN 'zookeeper_local.requests_latency' 4000097
SET 'min_latency' = 0
SET 'avg_latency' = 0
SET 'max_latency' = 0
END

BEGIN 'zookeeper_local.connections' 4000097
SET 'num_alive_connections' = 1
END

BEGIN 'zookeeper_local.packets' 4000097
SET 'packets_received' = 2
SET 'packets_sent' = 1
END
```

</details>

**Comment by ilyam8** [comment] 2021-03-11 16:00
@jrevillard 

Can you run the plugin in the debug mode and restart zookeeper during it?

**Comment by jrevillard** [comment] 2021-03-11 16:24
Here it is @ilyam8 

```
BEGIN 'zookeeper_local_rcc.approximate_data_size' 999903
SET 'approximate_data_size' = 58339
END

BEGIN 'zookeeper_local_rcc.server_state' 999903
SET 'server_state' = 2
END

BEGIN 'netdata.execution_time_of_zookeeper_local_rcc' 999903
SET 'time' = 16
END

[ DEBUG ] run[manager] run.go:41 tick 33
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 read tcp 192.168.133.6:54424->192.168.133.6:3181: read: connection reset by peer
[ DEBUG ] run[manager] run.go:41 tick 34
[ ERROR ] zookeeper[local_rcc] job.go:289 PANIC: runtime error: invalid memory address or nil pointer dereference
[ DEBUG ] run[manager] run.go:41 tick 35
[ ERROR ] zookeeper[local_rcc] job.go:289 PANIC: runtime error: invalid memory address or nil pointer dereference
[ DEBUG ] run[manager] run.go:41 tick 36
[ ERROR ] zookeeper[local_rcc] job.go:289 PANIC: runtime error: invalid memory address or nil pointer dereference


```

**Comment by ilyam8** [comment] 2021-03-11 17:59
@jrevillard 

Do you have golang installed on your server? Bad thing that we have no panic stacktraces, hard to debug it. I added logging stacktraces in the debug mode, but you need to compile the plugin from source.

**Comment by jrevillard** [comment] 2021-03-11 19:40
If I need to find goland I will find it. I'm running centos 7 :-)

Could you guide me on how to compile it and run it again please ?

Best.

**Comment by ilyam8** [comment] 2021-03-11 22:42
You need golang v1.14+



```cmd
git clone https://github.com/netdata/go.d.plugin
cd go.d.plugin
hack/go-build.sh

# assuming Zookeeper listens on 127.0.0.1:2181 
bin/godplugin -d -m zookeeper
```

**Comment by jrevillard** [comment] 2021-03-12 07:20
Hi @ilyam8 

It does not compile:

```
[root@zk1 [RCC] go.d.plugin]# hack/go-build.sh
Building binaries for version: v0.28.0-2-ga8304ee
Building linux/amd64
go: github.com/go-redis/redis/v8@v8.4.0 requires
	github.com/onsi/gomega@v1.10.3 requires
	github.com/golang/protobuf@v1.4.2 requires
	google.golang.org/protobuf@v1.23.0 requires
	github.com/golang/protobuf@v1.4.0 requires
	google.golang.org/protobuf@v1.21.0 requires
	github.com/golang/protobuf@v1.4.0-rc.4.0.20200313231945-b860323f09d0: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/6e18cbff36266c74e48dd81b4b672026ac74fb69c838ddb6240f256bb8edf590: exit status 128:
	fatal: git fetch-pack: expected shallow list


```

**Comment by jrevillard** [comment] 2021-03-12 07:29
Ok seems that git version is too old... I need to update it.

**Comment by jrevillard** [comment] 2021-03-12 07:38
Another error @ilyam8 

```
[root@zk1 [RCC] go.d.plugin]# hack/go-build.sh
Building binaries for version: v0.28.0-2-ga8304ee
Building linux/amd64
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/gofrs/flock v0.8.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/vmware/govmomi v0.22.2
go: downloading github.com/cloudflare/cfssl v1.4.1
go: downloading github.com/ilyam8/hashstructure v1.1.0
go: downloading github.com/go-redis/redis/v8 v8.4.0
go: downloading github.com/miekg/dns v1.1.29
verifying github.com/ilyam8/hashstructure@v1.1.0: checksum mismatch
	downloaded: h1:o3hpiGa1yergDO4AlUVBJGNvCEeaD+Ynu0OWYxee0iA=
	go.sum:     h1:N8t8hzzKLf2Da87XgC/DBYqXUmSbclgx+2cZxS5/klU=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

```

**Comment by ilyam8** [comment] 2021-03-12 07:52
go version?

**Comment by jrevillard** [comment] 2021-03-12 07:53
```
[root@zk1 [RCC] go.d.plugin]# go version
go version go1.15.5 linux/amd64
```
So it compiled now.

How to run bin/godplugin with the conf that I need ?

```
jobs:
  - name: local_rcc
    address: zk1.int-bigeys-rcc.openstack.local:3181
    use_tls: true
```

**Comment by jrevillard** [comment] 2021-03-12 07:55
Here we are:

```
[ DEBUG ] run[manager] run.go:41 tick 31
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 32
[ ERROR ] zookeeper[local_rcc] job.go:296 PANIC: runtime error: invalid memory address or nil pointer dereference
[ ERROR ] zookeeper[local_rcc] job.go:298 STACK: goroutine 32 [running]:
runtime/debug.Stack(0xc000106340, 0x10179a8, 0x9)
	/usr/lib/golang/src/runtime/debug/stack.go:24 +0x9f
github.com/netdata/go.d.plugin/agent/module.(*Job).collect.func1(0xc000156460)
	/root/go.d.plugin/agent/module/job.go:298 +0xb4
panic(0xde03c0, 0x1795f40)
	/usr/lib/golang/src/runtime/panic.go:969 +0x1b9
crypto/tls.(*Conn).Close(0x0, 0xc00005e120, 0x1083ec8)
	/usr/lib/golang/src/crypto/tls/conn.go:1286 +0x26
github.com/netdata/go.d.plugin/modules/zookeeper.(*client).disconnect(...)
	/root/go.d.plugin/modules/zookeeper/client.go:61
github.com/netdata/go.d.plugin/modules/zookeeper.(*client).fetch(0xc0001453b0, 0x10146ef, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go.d.plugin/modules/zookeeper/client.go:96 +0x29d
github.com/netdata/go.d.plugin/modules/zookeeper.(*Zookeeper).collectMntr(0xc000144a80, 0x0, 0x0, 0xc000299d78)
	/root/go.d.plugin/modules/zookeeper/collect.go:15 +0x5e
github.com/netdata/go.d.plugin/modules/zookeeper.(*Zookeeper).collect(...)
	/root/go.d.plugin/modules/zookeeper/collect.go:10
github.com/netdata/go.d.plugin/modules/zookeeper.(*Zookeeper).Collect(0xc000144a80, 0x4c14c6)
	/root/go.d.plugin/modules/zookeeper/zookeeper.go:97 +0x2f
github.com/netdata/go.d.plugin/agent/module.(*Job).collect(0xc000156460, 0x0)
	/root/go.d.plugin/agent/module/job.go:302 +0x68
github.com/netdata/go.d.plugin/agent/module.(*Job).runOnce(0xc000156460)
	/root/go.d.plugin/agent/module/job.go:273 +0xc5
github.com/netdata/go.d.plugin/agent/module.(*Job).Start(0xc000156460)
	/root/go.d.plugin/agent/module/job.go:190 +0x245
created by github.com/netdata/go.d.plugin/agent/job/run.(*Manager).Start
	/root/go.d.plugin/agent/job/run/run.go:52 +0x85
```

**Comment by jrevillard** [comment] 2021-03-12 16:17
Do you have an idea then @ilyam8 ?

**Comment by ilyam8** [comment] 2021-03-12 16:31
So far - no. But i see why i couldnt reproduce it - i didn't use tls.

**Comment by ilyam8** [comment] 2021-03-12 16:34
> zk1.int-bigeys-rcc.openstack.local:3181

If it is possible i suggest to switch to `:2181` until we get it fixed.

**Comment by jrevillard** [comment] 2021-03-12 19:27
Unfortunately no I cannot... We can leave some time with this: we already have alarming for this.

**Comment by ilyam8** [comment] 2021-03-17 12:22
@jrevillard need your help, i want to setup zookeeper with tls.

I use [bitnami/zookeeper](https://hub.docker.com/r/bitnami/zookeeper/) image.

To get it working i need [to generate KeyStore and TrustStore](https://stackoverflow.com/questions/47434877/how-to-generate-keystore-and-truststore). It doesn't look straightforward to me. Can you give me a quick guide how to do it?

**Comment by ilyam8** [comment] 2021-03-17 12:31
Ok, i managed to reproduce the problem 🎉

**Comment by ilyam8** [comment] 2021-03-17 13:11
fixed in https://github.com/netdata/go.d.plugin/pull/562

**Closed** 2021-03-17 13:36 UTC
Labels: area/external, bug, data-collection-mteam

**Comment by ilyam8** [comment] 2021-03-17 13:39
@jrevillard i plan to release bug fixes release of go.d early next week. Compile the plugin from source and use it if you want to get the fix quickly.

**Comment by jrevillard** [comment] 2021-03-17 14:54
Thanks a lot for your reactivity @ilyam8 . I will try to test it before you release to be 100% sure that it is fixed.

**Comment by jrevillard** [comment] 2021-03-17 15:19
Works !

```
BEGIN 'zookeeper_local_rcc.watches' 999975
SET 'watch_count' = 105
END

BEGIN 'zookeeper_local_rcc.approximate_data_size' 999975
SET 'approximate_data_size' = 114983
END

BEGIN 'zookeeper_local_rcc.server_state' 999975
SET 'server_state' = 2
END

BEGIN 'netdata.execution_time_of_zookeeper_local_rcc' 999975
SET 'time' = 16
END

[ DEBUG ] run[manager] run.go:41 tick 17
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 read tcp 192.168.133.9:55194->192.168.133.9:3181: read: connection reset by peer
[ DEBUG ] run[manager] run.go:41 tick 18
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 19
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 20
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 21
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 22
[ DEBUG ] run[manager] run.go:41 tick 23
[ DEBUG ] run[manager] run.go:41 tick 24
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 25
[ DEBUG ] run[manager] run.go:41 tick 26
[ DEBUG ] run[manager] run.go:41 tick 27
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 28
[ DEBUG ] run[manager] run.go:41 tick 29
[ DEBUG ] run[manager] run.go:41 tick 30
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 31
[ DEBUG ] run[manager] run.go:41 tick 32
[ DEBUG ] run[manager] run.go:41 tick 33
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 34
[ DEBUG ] run[manager] run.go:41 tick 35
[ DEBUG ] run[manager] run.go:41 tick 36
[ ERROR ] zookeeper[local_rcc] zookeeper.go:99 dial tcp 192.168.133.9:3181: connect: connection refused
[ DEBUG ] run[manager] run.go:41 tick 37
[ DEBUG ] run[manager] run.go:41 tick 38
[ DEBUG ] run[manager] run.go:41 tick 39
[ DEBUG ] run[manager] run.go:41 tick 40
[ DEBUG ] run[manager] run.go:41 tick 41
[ DEBUG ] run[manager] run.go:41 tick 42
BEGIN 'zookeeper_local_rcc.requests' 5999776
SET 'outstanding_requests' = 0
END

BEGIN 'zookeeper_local_rcc.requests_latency' 5999776
SET 'min_latency' = 0
SET 'avg_latency' = 0
SET 'max_latency' = 0
END


```

**Comment by ilyam8** [comment] 2021-03-17 15:43
thx for the quick test @jrevillard 👍
