### ISSUE TITLE
Improve data backtracing/browsing

### ISSUE THREAD

**Issue by kkoomen** [netdata/netdata#7589] opened 2019-12-20 02:19 UTC
##### Feature idea summary

Last night there was a big load on the production server where I use netdata on, but I have to go 9 hours back and the only way I can see now is to use my touchpad (because I don't use a mouse) to drag the content of the charts 9 hours back which takes me several minutes. Unless there is an option built in that allows me to do this in a quick way, I think we should look into improving this. I don't want to move every chart to a specific time, that's very inconvenient and as far as I see, I can't trace back quick and efficiently.

##### Expected behavior

I have two options right now:
What I also would like is:

1) input type date where I can select a date + time and then all the charts will go to that datetime

2) a slider which I can drag where as the beginning of the slider is the first record that is being monitored and the end position is the very last item being monitored.

**Comment by ilyam8** [comment] 2019-12-20 05:33
Hi @kkoomen

This issue is duplicate of https://github.com/netdata/netdata/issues/250

**Closed** 2019-12-20 05:34 UTC
Labels: duplicate, feature request, needs triage
