### ISSUE TITLE
Netdata does not auto-update after installing using the one-liner

### ISSUE THREAD

**Issue by Kramerican** [netdata/netdata#7261] opened 2019-11-06 13:59 UTC
Installed Netdata using the one-liner:

`bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`

According to the docs [here](https://github.com/netdata/netdata/blob/master/packaging/installer/UPDATE.md) should automatically enable auto-updates. However, I seem to be stuck on version v1.17.1-80-gd4213ef5

I've taken a look in `/etc/cron.daily/` and nothing netdata related is there

This is on Ubuntu Bionic

**Comment by thiagoftsm** [comment] 2019-11-06 14:06
Hi @Kramerican ,

Firstly, thank you for your report. We merged few hours ago a solution for this https://github.com/netdata/netdata/pull/7200 , so the next version won't have more this problem. 

Best regards!

**Comment by Kramerican** [comment] 2019-11-06 14:21
OK I will update after the enxt nightly and then keep an eye on things. Thanks.!

**Comment by knatsakis** [comment] 2019-11-06 14:22
@Kramerican, @thiagoftsm this is a duplicate of #7039 

Also, #7197 is closely related.

@kramerican, thank you very much for your report. Let's track progress in #7197 

Closing this.

**Closed** 2019-11-06 14:23 UTC
Labels: bug, duplicate
