### ISSUE TITLE
How to suppress charts generated through from filecheck plugin?

### ISSUE THREAD

**Issue by fti-cneve** [netdata/netdata#11232] opened 2021-06-09 11:21 UTC
How to suppress chanrts generated through filecheck plugin?
I need to hide the unnecessary charts from netdata graphs. Is there any way or configuration for filecheck or for netdata to hide or suppress the unnecessary charts?

OS / Environment:
Debian 10 (buster)
Netdata Version: v1.30.0

Output of uname -a; grep -Hv "^#" /etc/*release # Linux
```
root@DEB-Vostro35-B0GMJZ2:~# uname -a; grep -Hv "^#" /etc/*release
Linux DEB-Vostro35-B0GMJZ2 5.10.0-0.bpo.5-amd64 #1 SMP Debian 5.10.24-1~bpo10+1 (2021-03-29) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```
Output of netdata -W buildinfo
```
root@DEB-Vostro35-B0GMJZ2:/opt/scorer/sbin# ./netdata -W buildinfo
Version: netdata v1.31.0
Configure options:  '--prefix=/opt/scorer' '--with-user=netdata' '--sysconfdir=/opt/scorer/etc' '--localstatedir=/opt/scorer' '--with-zlib' '--with-math' '--with-jemalloc=/opt/scorer' '--enable-https' '--enable-plugin-nfacct' 'CFLAGS=-I/opt/scorer/include -ftree-vectorize'
Features:
    dbengine:                NO
    Native HTTPS:            YES
    Netdata Cloud:           NO 
    TLS Host Verification:   YES
Libraries:
    jemalloc:                YES
    JSON-C:                  NO
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     NO 
    mosquitto:               NO
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```
##### Installation method
from github, using make

##### Component Name
filecheck module (go.d.plugin)

##### Steps To Reproduce
I can see following charts in netdata which are generated by filecheck module:
1. Dir Existence 
2. Dir Time Since the Last Modification
3. Dir Number of Files
4. Dir Size

##### Expected behavior
My expectation is to suppress or hide "Dir Existence" chart from netdata.

I've checked filecheck configurations but unfortunately there is nothing which can be useful to do the above. 
Is there any way to achieve the same.?
@ilyam8 Thank you so much in advance :)

Following is the snapshot of charts generated by filecheck module:
![image](https://user-images.githubusercontent.com/47653578/121345672-1b7aad00-c960-11eb-8b4f-90ab31ab153e.png)

**Comment by ilyam8** [comment] 2021-06-09 15:23
Hi @fti-cneve 

That is not a bug, so I am going to close the issue. If there are any questions consider using [our community forum](https://community.netdata.cloud/)!

---

 > I've checked filecheck configurations but unfortunately there is nothing which can be useful to do the above.

Correct, there is nothing. Still, there is a way to disable the chart.

You can find the chart in the `netdata.conf` and disable it.

```cmd
[pc netdata]# grep "dir_existence\]" netdata.conf -A 5
[filecheck_dirs_example.dir_existence]
	# history = 5
	enabled = no
	# cache directory = /opt/netdata/var/cache/netdata/filecheck_dirs_example.dir_existence
	# chart type = line
	# type = filecheck_dirs_example
```

If you can't find the chart in the conf you can download the actual config via Netdata REST API

```cmd
# assuming Netdata is running
[pc ~]# cd /opt/netdata/etc/netdata/
[pc netdata]# curl -s  -o netdata.conf http://localhost:19999/netdata.conf
[pc netdata]#
```

**Closed by ilyam8** 2021-06-09 15:23 UTC
Labels: bug, needs triage
