### ISSUE TITLE
Bug   os debian 9  

### ISSUE THREAD

**Issue by genrihx2** [netdata/netdata#7362] opened 2019-11-24 16:34 UTC
root@s01:~# bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)
 --- Downloading static netdata binary: https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run ---
[/tmp/netdata-kickstart-QtDopy]# curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/sha256sums.txt
 OK

[/tmp/netdata-kickstart-QtDopy]# curl -sSL --connect-timeout 10 --retry 3 https://storage.googleapis.com/netdata-nightlies/netdata-latest.gz.run
 OK

 ABORTED  Static binary checksum validation failed. Stopping netdata installation and leaving binary in /tmp/netdata-kickstart-QtDopy

**Comment by thiagoftsm** [comment] 2019-11-24 18:07
Hi @genrihx2 ,

I tested the same command that you ran before on a Debian 9.11 and everything worked fine, please, can you run the following command and give us the output?

```
sha256sum /tmp/netdata-kickstart-QtDopy/netdata-latest.gz.run
``` 

I suspect that there was a problem to do download of this file and you could not install on your computer because the output of the previous command is different of the expected result that you can find inside the file `https://storage.googleapis.com/netdata-nightlies/sha256sums.txt`.

Best regards!

**Comment by genrihx2** [comment] 2019-11-24 18:45
@thiagoftsm hi    Thanks, it works  
my server vds

**Comment by thiagoftsm** [comment] 2019-11-24 19:03
I am glad to read this! :) 

@genrihx2 considering that the problem is fixed, I will close this issue, case you have any problem again, be free to return here. 

Best regards!

**Closed by thiagoftsm** 2019-11-24 19:03 UTC
Labels: bug, needs triage
