### ISSUE TITLE
Localization of HTML Docs

### ISSUE THREAD

**Issue by LimeZky** [netdata/netdata#5197] opened 2019-01-17 13:36 UTC
Hello, I am a Netdata user from China. I found that Netdata is now only available in English. It is not very convenient in normal use. If you can, I hope to participate in the translation of Netdata (this is free). I am very willing to provide convenience for other users.

**Comment by Ferroin** [comment] 2019-01-17 14:00
Personally, I think having translations would be great, and I think that Simplified Chinese is probably the best possible first translation given the sheer number of users it would benefit (with Spanish being a very close second, and Hindi a very close third, both by the same reasoning).

At the moment, the biggest issue is probably the fact that significant parts of the current design aren't exactly translation-friendly.  The dashboard and the documentation probably wouldn't be too hard to handle, but notifications are going to be a pain (they're currently generated using fixed templates in one rather large script), as are config file comments, and log messages would probably need an extra dependency (gettext).

**Comment by paulfantom** [comment] 2019-01-17 14:38
Looking at google analytics, it would make much more sense to translate to German :)

**Comment by Ferroin** [comment] 2019-01-17 14:59
@paulfantom Well, I'm mostly going off of potential users just based on number of people who speak the language.  Based on the most recent data from [Ethnologue](https://www.ethnologue.com/), the most spoken languages in the world by native speakers are Mandarin (covered by Simplified Chinese), Spanish, English, Hindi, and Arabic.  I think German is at number 11 right now, and it's also linguistically close to English (and therefore learning English as an L2 with German as a native language is easier) than 3 of the four other languages in the top 5.

High usage in Germany though just says to me there are a lot of people using Netdata in Germany, not necessarily that there are a lot of people who would preferentially use it in German if we offered it that way.  Without actually having translations and data on which are used most where, we really can't conclusively say more than that (unless of course we're tracking preferred language lists in browsers that load the dashboard or system locales on systems where Netdata is installed, but I don't remember that being part of the usage tracking).

**Comment by paulfantom** [comment] 2019-01-17 19:15
Nonetheless I am closing this as a duplicate of #219

**Comment by cakrit** [comment] 2019-01-18 00:09
There is a big difference in this issue, @PeterZky000 has kindly volunteered to assist with the translation. We were discussing the very large growth we are seeing in interest from China just last night. 

One big difference with Germany - other than the relative growth - is that most German professionals have a working knowledge of English, which is not necessarily true for Chinese users.

@PeterZky000, let's start with some suggestions from your side regarding what you think we should try first. The documentation and the standard web  dashboard are obvious possibilities and we can think about the best way to approach whichever you think would be more useful.

**Comment by PeterZky000** [comment] 2019-01-18 03:21
Ok, when you find a good enough way to solve this problem (for example: language switching file), please contact me, I think the translation of the document on the web should be in the first place, because people will first pass the website. It’s also important to understand each product and have them successfully installed, which will make people feel more cordial.

**Comment by Ferroin** [comment] 2019-01-18 12:44
I would tend to agree that translating the documentation first is probably going to have the most benefit for the amount of effort it's likely to require.  I don't really understand exactly how our documentation system works, but I suspect that whatever we're using for generating the docs site probably either has native support for translations, or a plugin for handling them.

**Comment by paulfantom** [comment] 2019-01-18 13:47
There is no "documentation system", currently docs are generated by grabbing all README files, arranging them into the same structure they are in source code and publishing them as a static site. With something like this I can hardly imagine how we can do translations apart from creating multiple more README files which are translations. And our "system" used to assemble all that doesn't support internationalization (https://github.com/mkdocs/mkdocs/issues/211).

**Comment by ilyam8** [comment] 2019-01-18 13:56
The question is what should be translated and ... really? Do we really need translation from English into X in 2019? 

The only way is to translate using some tool/program, otherwise there is no way no mantain/sync translations.

**Comment by PeterZky000** [comment] 2019-01-18 15:11
I think we can try to use machine translation (such as Google Translate, as well as Baidu translation in China), then manually review and correct it, and open the translation suggestion channel. This series of methods can make translation. More localized (accurate)

**Comment by PeterZky000** [comment] 2019-01-18 15:17
> 没有“文档系统”，目前通过获取所有README文件生成文档，将它们安排到源代码中的相同结构中并将它们作为静态站点发布。有了这样的东西，我很难想象除了创建多个翻译的README文件之外我们怎么做翻译。我们的“系统”用于组装所有不支持国际化的系统（[mkdocs / mkdocs＃211](https://github.com/mkdocs/mkdocs/issues/211)）。

I think we can look forward to the switching of language files, you can try to direct all the text to a file (although I know this is very difficult)

**Comment by cakrit** [comment] 2019-01-18 23:53
I will need to play around a bit, hopefully during the weekend, but the main idea for docs is the following:

- Create localization directories  for additional languages under docs. Probably something like `docs/localization/` with subdirectory names taken from the abbreviations at https://gist.github.com/DavidWells/0881c21414e81431ed42. We'll just add zh_CN for now. 
- The structure under those directories for anything translated will need to be identical to the directory structure we already have. E.g `zh_CN/packaging/installer/README.md`
- The content for a given language will be shown under `docs.netdata.cloud/[abbreviation]/`. 

The tricky part is what exactly to show. I believe that the best way to do this is to treat the new .md files under those localization directories as replacements of the existing ones, without changing the table of contents. If a page hasn't been translated, the default (English) page will be shown instead. Consider that this means that I will start seeing just a few entries in Mandarin, with most of the content remaining in English. It's not ideal perhaps, but I think that the alternatives are worse.

Now, what happens when a change is done in a file that has a translation in place? The documentation build system can add a warning at the beginning of the particular translated page in the html site, to signify that this translation may be outdated. It's not certain that a change is required when the source file is changed, because someone could have just corrected a grammatical error in the English version. Still, someone would need to do a commit adding at least a space somewhere, to get rid of that warning. 

Contributors can utilize any machine-assisted translation methodology they like, but I really don't want to publish automatically translated pages. The domain-specific knowledge is just not there in the translators and people will be seeing even configuration examples translated, which is completely wrong. I did find what sounds like a promising command line tool described [here](https://www.ostechnix.com/use-google-translate-commandline-linux/), but it's not something we will ever automate. We will of course be using machine translation to verify that what our contributing translators create PRs for make some sense. @PeterZky000 could write literally anything in a markdown, if we don't follow that step. I'll be doing that for now. If we get enough trusted contributors in the future, this need can go away and they can be correcting each other.

**Comment by PeterZky000** [comment] 2019-01-19 04:38
I think this is feasible, you can create a blog/forum to gather enough translators and collect corrections through it.

**Comment by Ferroin** [comment] 2019-01-22 12:48
@cakrit I can help with double checking submitted translations too (depending on the language, I may be able to help more than just verifying that back-translation makes sense too).

Also, I think we should think _very_ hard about whether we want this in the main repo instead of having a separate repository for the translations.  Depending on how well this turns out, we may see a _lot_ of PR's (and possibly issues) relating to translations.  If we keep them in the main repo, we should probably have a tag for issues and PR's related to translations, and possibly one specifically for new translations.

**Comment by cakrit** [comment] 2019-01-22 14:22
> I think we should think very hard about whether we want this in the main repo instead of having a separate repository for the translations

The only problem I have with that is that our automated tests run for PRs in netdata/netdata only. We will need to get travis to trigger the netlify build for netdata/netdata, for every PR in netdata/localization. Seems doable enough. Getting the readmes from another project is already tested for the go.d.plugin markdowns (see #5215).

Let me start it with a separate repo, it's easy to go back.

**Comment by cakrit** [comment] 2019-01-22 14:46
I created https://github.com/netdata/localization
@LimeZky take a look at the README there and start adding some content whenever you want. I'm starting with the mechanism to integrate those files to our docs

**Comment by LimeZky** [comment] 2019-01-22 14:50
Hello,I have already saw it.I will try my best to translate it.

**Comment by cakrit** [comment] 2019-01-22 14:51
Whichever files you feel like doing first, this is just to help us build the prototype.

**Comment by LimeZky** [comment] 2019-01-22 14:52
OK.Can I share it to my friends?They maybe will help it.

**Comment by cakrit** [comment] 2019-01-22 15:32
Of course, no problem. I'm not even sure how the PRs will be approved, we'll see :)

**Comment by LimeZky** [comment] 2019-01-22 15:39
I just finished the Chinese translation of the upgrade document, the link is as follows:
https://github.com/LimeZky/localization/blob/master/zh_CN/UPDATE.md
(Because I don't seem to have permission at https://github.com/netdata/localization, so I cloned one)

**Comment by Ferroin** [comment] 2019-01-22 15:45
@LimeZky Nice.  I know essentially zero Chinese, so I can't really check the translation itself, but I would like to point out that you've got a single component in the path in the block talking about the cron job for the updates translated, while none of the other instances of that same sequence of path components are.  Not exactly critical, but stylistically it's better to either translate all instances of something or none of them.

**Comment by LimeZky** [comment] 2019-01-22 15:57
Sorry, this is a mistake of mine. I have found and fixed it in time. Thank you.

**Comment by LimeZky** [comment] 2019-01-22 16:44
Hello, I just finished the Chinese translation of the uninstall instructions, the links are as follows:
https://github.com/LimeZky/localization/blob/master/zh_CN/UNINSTALL.md
(Sorry, I don't seem to know how to create a new folder, please forgive me for being stupid)

**Comment by cakrit** [comment] 2019-01-22 17:04
@LimeZky it doesn't allow you to create a pull request at all? I want to fix it, but not sure what access rights I need to give (haven't found much about it, supposedly anyone can create a pull request).

**Comment by paulfantom** [comment] 2019-01-22 19:35
Anyone can create PR. Here one: https://github.com/netdata/localization/pull/1

**Comment by LimeZky** [comment] 2019-01-23 07:45
Hello, I just finished and uploaded a Chinese translation of README.md with the following link:
https://github.com/LimeZky/localization/blob/master/zh_CN/README.md
This document is a bit long, I am constantly checking for errors and fixing it

**Comment by Ferroin** [comment] 2019-01-23 13:13
> @cakrit Hello, when I open "https://github.com/netdata/localization/tree/master/zh_CN" and click "Upload File", it tells me that the upload is disabled. File uploads need to be pushed to access this repository.

OK, that's where the issue is.  You need to open a regular PR, not one of the automatic curated ones GitHub creates when you try to just add a file.  In your clone of the repository, there should be a button on the left just above the file listing that says 'New Pull Request'.  If you click that, it should properly open a PR to add the files you currently have translated.

**Comment by LimeZky** [comment] 2019-01-23 13:20
Hello, I just finished the Chinese translation of the Docker installation documentation, the link is as follows:
http://119.29.138.103:3000/Lime/Chinese_translation_of_Netdata_documentation/src/master/zh_CN/packaging/docker/README.md
(This is my server, because I don't know how to create a new folder in Github's repository... I will upload it to Github after I learn it, sorry)

**Comment by LimeZky** [comment] 2019-01-23 13:57
In addition, I think we may need to hire some new translators (after all, there are too many documents)

**Comment by LimeZky** [comment] 2019-01-23 13:58
@Ferroin Ok, I will try it.

**Comment by cakrit** [comment] 2019-01-23 17:40
FYI I started working on the site generator, but it needs some refactoring in all three scripts involved in the generation. It's not too much work, but there are some circumstances that will probably prevent me from putting in the required time during this week and the next.  I also won't be commenting much during this period, but don't let this discourage you. 

I'm not sure if we'll be hiring translators soon, so it will need to be a community effort for the foreseeable future.

**Comment by LimeZky** [comment] 2019-01-24 05:40
Now, I am already working on translating the "docs" folder.

**Comment by LimeZky** [comment] 2019-02-04 17:47
Today is the Chinese New Year. Here, I wish you all good health and good luck, and I wish Netdata continues to flourish and progress.

**Comment by ilyam8** [comment] 2019-02-04 18:37
Happy New Year @LimeZky :pig:

**Comment by LimeZky** [comment] 2019-02-06 05:46
Recently, I translated several documents (sorry, the speed is a bit slow), the link is as follows: https://github.com/LimeZky/localization/tree/master/zh_CN

**Comment by cakrit** [comment] 2019-02-06 19:43
Ok gentlemen, I have the framework ready, you can check out PR #5342.
@LimeZky, please do a new pull request to add some more of your files. Please pay special attention to the relative links. You had 3 `../../docs` links that caused the build to fail. 
@paulfantom any ideas on how we might be able to trigger the netlify tests we have on `netdata/netdata` to show up for PR in `netdata/localization`? The only (stupid) thing I could think of was the following:
- Create a hidden Netlify site, with builds triggered by changes to `netdata/localization`
- Write a build script in `netdata/localization` that clones `netdata/netdata` and executes `docs/generator/buildhtml.sh`, with a parameter that tells it not to clone `netdata/localization` from git, but to just copy all the files it sees in the PR.

**Comment by paulfantom** [comment] 2019-02-06 20:01
No, I don't have any good ideas. Due to choices on how we handle docs we are now in uncharted territory.

Probably the best in current situation is to write a webhook gateway, deploy it somewhere, point GitHub webhook to it and make it spit out payload to netlify webhook endpoint.

**Comment by cakrit** [comment] 2019-02-07 11:55
I did it as I described, it's the most straightforward way. PRs are now checked automatically by Netlify.

**Comment by cakrit** [comment] 2019-02-07 12:36
We will use the abbreviations mkdocs-material supports, so that the UI site also has translated buttons and we don't have to manually map the other abbreviations. You can see the available languages here:
https://squidfunk.github.io/mkdocs-material/getting-started/#localization

@LimeZky I will take the files from your repo, because I don't want it to become more difficult for you, due to the renaming of the folder from `zh_CN` to `zh`

**Comment by LimeZky** [comment] 2019-02-07 14:24
@cakrit Ok. I think it's time to set up a translation forum, because I will start school on February 17, I will not have much time to use the computer after school (sorry

**Comment by Ferroin** [comment] 2019-02-07 14:37
I have no idea how hard it might be to integrate, but it may be worth looking into using one of the various collaborative digital translation platforms out there for this.  I know at least some of them (Transifex for example) offer free options for FOSS projects, but don't know if Netdata would qualify for any of them.

**Comment by cakrit** [comment] 2019-02-07 18:29
The forum will be the GitHub project https://github.com/netdata/localization
I will add a page on the main netdata README, for people who want to continue this work.

**Comment by LimeZky** [comment] 2019-02-08 00:51
@cakrit OK.

**Comment by cakrit** [comment] 2019-02-13 15:26
The site with the translations we have is live at https://docs.netdata.cloud. `packaging/installer/UPDATE.md` is already outdated, because we had several recent changes. Thank you for your contributions @LimeZky and I hope we'll get more from your fellow countrymen! :)

For any problems, please create new issues, or comment on #5369.

**Closed by cakrit** 2019-02-13 15:26 UTC
Labels: area/docs, feature request, priority/medium

**Comment by LimeZky** [comment] 2019-02-15 17:04
I fixed some grammatical errors and corrected some translations these days. I think they have no problem now, I will upload them to GitHub later.
