### ISSUE TITLE
Frequent reconnects between master and slave

### ISSUE THREAD

**Issue by tctovsli** [netdata/netdata#6679] opened 2019-08-16 08:44 UTC
##### Bug report summary
I have a single master and multiple headless collectors running.
One of these slaves are having issues with very frequent reconnects which makes holes in the graph on the master.
The difference between this slave and the others, are that this slave is installed with the .run-package and the others are installed with the kickstart-script.
This slave is placed behind a more strict firewall-rule that the other slaves (see #6676).

This is the stream.conf on the slave:

    [stream]
        enabled = yes
        destination = master
        api key = SECRET
        timeout seconds = 60
        default port = 19999
        send charts matching = *
        buffer size bytes = 1048576
        reconnect delay seconds = 5
        initial clock resync iterations = 60

And the following logs are repeated in the error.log on the slave:

    2019-08-16 10:26:10: netdata ERROR : STREAM_SENDER[slave] : STREAM slave [send to master]: too many data pending - buffer is 1052292 bytes long, 1052292 unsent - we have sent 19114069 bytes in total, 129880 on this connection. Closing connection to flush the data.
    2019-08-16 10:26:10: netdata ERROR : PLUGIN[proc] : STREAM slave [send]: not ready - discarding collected metrics. (errno 2, No such file or directory)
    2019-08-16 10:26:11: netdata INFO  : STREAM_SENDER[slave] : STREAM slave [send to master]: connecting...
    2019-08-16 10:26:11: netdata INFO  : STREAM_SENDER[slave] : STREAM slave [send to master]: initializing communication...
    2019-08-16 10:26:11: netdata INFO  : STREAM_SENDER[slave] : STREAM slave [send to master]: waiting response from remote netdata...
    2019-08-16 10:26:11: netdata INFO  : STREAM_SENDER[slave] : STREAM slave [send to master]: established communication - ready to send metrics...
    2019-08-16 10:26:11: netdata ERROR : STREAM_SENDER[slave] : STREAM slave [send]: discarding 1052339 bytes of metrics already in the buffer. (errno 22, Invalid argument)
    2019-08-16 10:26:11: netdata INFO  : PLUGIN[idlejitter] : STREAM slave [send]: sending metrics...
    2019-08-16 10:26:41: netdata ERROR : STREAM_SENDER[slave] : STREAM slave [send to master]: too many data pending - buffer is 1048581 bytes long, 1029757 unsent - we have sent 19135048 bytes in total, 20979 on this connection. Closing connection to flush the data.
    2019-08-16 10:26:41: netdata ERROR : PLUGIN[proc] : STREAM slave [send]: not ready - discarding collected metrics. (errno 2, No such file or directory)
    2019-08-16 10:26:42: netdata INFO  : STREAM_SENDER[slave] : STREAM slave [send to master]: connecting...
    2019-08-16 10:26:42: netdata INFO  : STREAM_SENDER[slave] : STREAM slave [send to master]: initializing communication...
    2019-08-16 10:26:42: netdata INFO  : STREAM_SENDER[slave] : STREAM slave [send to master]: waiting response from remote netdata...
    2019-08-16 10:26:42: netdata INFO  : STREAM_SENDER[slave] : STREAM slave [send to master]: established communication - ready to send metrics...
    2019-08-16 10:26:42: netdata ERROR : STREAM_SENDER[slave] : STREAM slave [send]: discarding 1050432 bytes of metrics already in the buffer. (errno 22, Invalid argument)
    2019-08-16 10:26:42: netdata INFO  : WEB_SERVER[static2] : STREAM slave [send]: sending metrics...

This is the appropriate logs from the master:

    2019-08-16 10:20:42: netdata INFO  : WEB_SERVER[static1] : clients wants to STREAM metrics.
    2019-08-16 10:20:42: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40454] : thread created with task id 2085
    2019-08-16 10:20:42: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40454] : STREAM slave [IP-REDACTED]:40454: receive thread created (task id 2085)
    2019-08-16 10:20:42: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40454] : STREAM slave [receive from [IP-REDACTED]:40454]: initializing communication...
    2019-08-16 10:20:42: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40454] : STREAM slave [receive from [IP-REDACTED]:40454]: multiple streaming connections for the  ame host detected. If multiple netdata are pushing metrics for the same charts, at the same time, the result is unexpected.
    2019-08-16 10:20:42: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40454] : Postponing health checks for 60 seconds, on host 'slave', because it was just connected.
    2019-08-16 10:20:42: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40454] : STREAM slave [receive from [IP-REDACTED]:40454]: receiving metrics...
    2019-08-16 10:21:13: netdata INFO  : WEB_SERVER[static1] : clients wants to STREAM metrics.
    2019-08-16 10:21:13: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40456] : thread created with task id 2122
    2019-08-16 10:21:13: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40456] : STREAM slave [IP-REDACTED]:40456: receive thread created (task id 2122)
    2019-08-16 10:21:13: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40456] : STREAM slave [receive from [IP-REDACTED]:40456]: initializing communication...
    2019-08-16 10:21:13: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40456] : STREAM slave [receive from [IP-REDACTED]:40456]: multiple streaming connections for the same host detected. If multiple netdata are pushing metrics for the same charts, at the same time, the result is unexpected.
    2019-08-16 10:21:13: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40456] : Postponing health checks for 60 seconds, on host 'slave', because it was just connected.
    2019-08-16 10:21:13: netdata INFO  : STREAM_RECEIVER[slave,[IP-REDACTED]:40456] : STREAM slave [receive from [IP-REDACTED]:40456]: receiving metrics...
    2019-08-16 10:21:13: netdata ERROR : STREAM_RECEIVER[slave,[IP-REDACTED]:40456] : RRDSET: chart name 'system.idlejitter' on host 'slave' already exists.

I checked `/var/lib/netdata/registry/netdata.public.unique.id` on the slaves, and it's unique.

##### OS / Environment
RHEL 7
##### Netdata version (ouput of `netdata -V`)
Master: v1.16.1-39-nightly
Slave: v1.16

##### Component Name
Streaming
##### Expected behavior
Continous connection, no holes in the graphs.

**Comment by thiagoftsm** [comment] 2019-08-16 10:51
Hi @tctovsli ,

I will try to repeat the issue to fix it, but let me ask one thing before I begin to work on this, are you using SSL to encrypt the communication channel?

**Comment by tctovsli** [comment] 2019-08-16 11:10
Thanks for looking into this. No, it's plain HTTP.

**Comment by thiagoftsm** [comment] 2019-08-16 14:09
Thank you very much, I am creating the environment here to verify this issue.

**Comment by thiagoftsm** [comment] 2019-08-16 22:26
Hi @tctovsli ,

Are you receiving errors like the image in one of the computers with Netdata?

![err](https://user-images.githubusercontent.com/49162938/63201366-77ca5980-c074-11e9-89ba-4c64cb3d290a.png)

I am running tests here in the last 5 hours and I will extend the test in the next hours to have more data to arrive in a conclusion, but this special message called my attention, so I decided to ask you before to give more details about the issue.

**Comment by thiagoftsm** [comment] 2019-08-17 03:17
Hi @tctovsli ,

I finished the first round of tests to discover what is happening with you, tomorrow I wanna execute more one round of tests, but firstly let me describe what was done today. I basically ran two types of tests:

- I started a master and a slave in the same computer, where the slave was a Virtual Box. In this first case I used in both the Slackware Linux current with kernel 4.19.66 and all the libraries updated for the last version released with the distribution. Here I had a direct communication and I did not have any error message related a bad communication between master and slave. This was the longest test that I ran, it ran without stop during 09 hours and 30 minutes.
- After three hours running the first test, I started a VM in a different computer , the VM was running RedHat 7.7 with the kernel 3.10.0-1062, this Red Hat registers various disconnects from the master and displayed the error demonstrated in the previous image. The configuration of this specific slave was a exact copy of the first VM, and the Netdata reported errors, as expected, and I had various messages like this:

```
 multiple streaming connections for the same host detected. If multiple netdata are pushing metrics for the same charts, at the same time, the result is unexpected.
``` 

I already had ideas about possible problems that we are having, but I wanna execute more two tests to confirm this. Until Monday I expect to have a complete vision about this problem.

Best regards!

**Comment by cakrit** [comment] 2019-08-17 10:31
@thiagoftsm plz verify the slaves don't have the same GUID in `/var/lib/netdata/netdata.api.key`. If they don't, then indeed you have replicated the issue and we'll need to see why the master erroneously considers the two streams as coming from the same host. It's the GUID that should matter, not the source IP/hostname.

**Comment by thiagoftsm** [comment] 2019-08-17 12:29
Hi @cakrit ,

Before I start a new round of tests between master and slave, I confirmed that the two Virtual Machines(VMs) have different GUID, so we are having other problem to receive the cited message.
I will continue the tests during the day collecting the necessary information and debug message to understand what is happening, for while, with Red Hat 7 and kernel 3.10.0-x.

**Comment by thiagoftsm** [comment] 2019-08-17 23:01
Hi everybody,

Today I ran another test,  with the following specifications:

- Master running Slackware current with the kernel 4.19.67 and the latest version of all packages.
- One Slave with the same O.S. and packages of the master running inside a Virtual Machine in the same master hardware.
- Final slave was running in another computer with the same slave config files copied of the previous slave and the same Operate System and packages of the other two. This computer is an old laptop that has wireless with maximum speed 100MBps and a core 2 duo processor.

The three environments ran together during 09:00 hours without to lose any data between Slaves and master, of course I never hoped to lose information between Master and Slave on same machine, but I was hoping to lose something with the oldest laptop. Until now it looks like that the problem can be associated with old libraries or kernel version, but I won't say that this is the case yet, because I wanna run more one test using Debian and Ubuntu.

best regards!

**Comment by cakrit** [comment] 2019-08-19 07:07
Why don't you focus specifically on RHEL 7 where you already reproduced the issue?

**Comment by thiagoftsm** [comment] 2019-08-19 13:39
@cakrit  I was only confirming that we do not have a problem with other Linux distribution, case we had this, it would be more explicit that we have a common Netdata error, instead distribution error, no less important I do not have RHEL7 direct installed in my labs, I am always using Virtual Machines to run it.

**Comment by tctovsli** [comment] 2019-09-23 12:32
Somehow, the issue seems to be gone now.

When I first reported the issue, we also had issues with OpenLDAP running on that machine. We did some tuning on OpenLDAP to resolve those issues, but I can't think of any changes that would resolve the netdata-issue.
We also saw the same issue on a neighboring server (in the same firewall-zone).
During the debugging of OpenLDAP, I turned off netdata on both those server, as the graphs didn't work properly.

Today, I started netdata again, and it has been running for over 30 minutes now without a single reconnect.

I will check with some colleagues of mine if there has been some changes to the firewall or similar.
We have also had a regular maintenance with OS updates, and 253 packages has been updates since (RHEL 7.7 now, so I guess there was a bigger update).
netdata on the problematic servers are still v.1.16, but the server is now running v1.17.1-91-nightly.

**Comment by thiagoftsm** [comment] 2019-09-23 13:04
Hi @tctovsli ,

This week I will expand good part of my time with Netdata stream, I verified that the problem you reported was related only to RedHat 7.7, I could reproduce it using Debian and Slackware. It will be good to know what is happening with the RedHat libraries, case you continue having problems, I will start Netdata monitoring all syscalls and library calls to verify what is happening yet.

Thank you!

**Comment by amoss** [comment] 2020-08-20 08:16
@tctovsli Hello, I'm checking up on old bug reports that are still open. Have you upgraded to a new version of Netdata and are you still seeing problems with the node using kickstart? The agent has changed a lot in the past year and this part of the code has been rewritten. Could you let us know if you are still having problems?

**Closed** 2021-08-20 09:40 UTC
Labels: bug, area/streaming
