### ISSUE TITLE
Dashboard TV white page

### ISSUE THREAD

**Issue by rpirsc13** [netdata/netdata#4710] opened 2018-11-22 15:17 UTC
##### Bug report summary

TV dashboard and main page no longer work on WebOS Browser. The page loads but the background is white. I can see the div titles but no graphs are shown. I am assuming that the dashboard.js script is the culprit. However I have no idea on how to extract the console output of the browser from the device.
 
Netdata server has been updated on November 19th 2018. 

##### OS / Environment

Client: LG TV WebOS 
Server: Ubuntu 16.04 
Netdata: 1.11.0-87-g9b305ee_rolling
##### Component Name

I am assuming dashboard.js is the culprit
##### Steps To Reproduce

Access netdata main dashboard or tv.html from a WebOS device.

```yaml

```

##### Expected behavior

I would expect to see a working dashboard.

**Comment by gmosx** [comment] 2018-11-22 15:22
Thank you for the report. Do you see any error messages in the console of the Web Browser? If so, can you post them here? `tv.html` seems to be working fine on my Chrome browser.

**Comment by gmosx** [comment] 2018-11-22 16:09
Maybe the WebOS browser does not support modern JS features.

**Comment by paulfantom** [comment] 2018-11-22 17:14
One could probably use an emulator to reproduce it: http://webostv.developer.lge.com/sdk/tools/emulator/introduction-emulator/

**Comment by rpirsc13** [comment] 2018-11-22 18:45
@paulfantom I will try that to get some information out of it
@gmosx It has worked just fine until the last few updates. Slow :) but fine. Will try the emulator and post the errors here

**Comment by gmosx** [comment] 2018-11-22 18:51
We started using some ES6 features in the latest version, I guess that's the culprit. Need to think how to resolve this.

**Comment by gmosx** [comment] 2018-12-03 13:06
The second error should be fixed already in master, I will push a fix for the first error. Thank you for the report.

**Comment by rpirsc13** [comment] 2018-12-07 12:33
@gmosx Sorry for the late reply. Still a white page however the ie11 console output has changed

```
SCRIPT1004: Expected ';'
dashboard.js (1039,28)
```

**Comment by gmosx** [comment] 2018-12-07 15:09
OK, will have a look.

**Comment by gmosx** [comment] 2018-12-18 07:55
Seems that IE11 does not support the `for (var of...` construct.

**Comment by gmosx** [comment] 2018-12-20 07:00
I think the proper solution to problems such as this is using a transpiler (e.g. [BabelJS](https://babeljs.io)) to convert modern JavaScript (ES6+) to ES3. IMO, we should not avoid modern language features.

**Comment by gmosx** [comment] 2018-12-20 07:08
@ktsaou I suggest we close this issue in favor of #5042

**Comment by cakrit** [comment] 2019-01-17 12:47
Closing in favor of #5042

**Closed by cakrit** 2019-01-17 12:47 UTC
Labels: area/web, bug
