### ISSUE TITLE
Is there a way to prevent Netdata from regularly removing my netdata.conf?

### ISSUE THREAD

**Issue by TheOldMan2000** [netdata/netdata#9117] opened 2020-05-21 00:46 UTC
##### Question summary
How to prevent Netdata from removing my netdata.conf when it updates?

##### OS / Environment

CENTOS 7.8 virtuozzo [vpsxxxxxx]  v86.0.21
Server Version: Apache/2.4.43 (cPanel) OpenSSL/1.1.1g mod_bwlimited/1.4 mod_fcgid/2.3.9 mod_cpanel/1.4
Server MPM: event
48 core cloud VPS 6GB
LSAPI PHP Handler

##### Component Name
Netdata.conf

##### Expected results

After reinstalling Netdata using the 64bit kickstart installer, there was no netdata.conf. Eventually I got it to download using the wget command using 127.0.0.1 instead of using localhost.

After spending ages setting it up, it updated to v1.22.1-74-gd218786a and I noticed all the disk stats were back again. Upon checking, the netdata.conf file had indeed been overwritten again with the default empty one (with the download instructions). 

Is it possible to rebuild the conf best it can, instead of replacing it?

Or is it something to do with Apache, as that keeps resetting my Vhost log file permissions which keeps preventing my go.d web_log from working as intended.

Many thanks!

**Comment by prologic** [comment] 2020-05-21 02:32
This was fixed with #9046 and a duplicate of #8531 and #8679 -- The fix should be in the latest nightly. Please if this is not the case feel free to reopen this issue or comment.

And now a duplicate of #9111

I am therefore closing this as such. If this is not correct and the problem persist, please lte me know!

**Closed by prologic** 2020-05-21 02:32 UTC
Labels: duplicate, no changelog, question

**Comment by TheOldMan2000** [comment] 2020-05-26 04:25
Netdata didn't update despite telling me an update was available for a few days, so I just ran the kick64 command to update it and v1.22.1-123-gb17a9f91 immediately reset (destroyed) my Netdata.conf file again. Cue the ridiculous onslaught of health email notifications and hours configuring everything again, copying and pasting TLS certs from WHM into Netdata via SSH (why doesn't it automatically import from CentOS?). 

It's my own fault I know, because I was too lazy to back it up first before running the update.

**Comment by prologic** [comment] 2020-05-26 04:49
@Ferroin You fixed this in #9046 Can you please investigate and if necessary reopen if this is still a problem. Thanks!

**Comment by Ferroin** [comment] 2020-05-26 13:26
This is indeed still an issue, reopening the original issue.

**Comment by TheOldMan2000** [comment] 2020-05-31 23:34
Hi folks,
Sadly this is still occurring every time Netdata updates, it resets the Netdata.conf
Happened again after upgrading to v1.22.1-175-ga97709b7

It's very time consuming setting everything back up!

**Comment by prologic** [comment] 2020-06-01 02:21
See #8531 where the issue was reopened. @Ferroin is working on it.

**Comment by Ferroin** [comment] 2020-06-01 14:48
This should now be properly fixed in tonight's nightly builds.

**Comment by TheOldMan2000** [comment] 2020-06-05 14:21
Woohoo, thanks for saving my sanity. Working fine now.
