### ISSUE TITLE
Streaming: re-lookup the DNS entry once the connection breaks down

### ISSUE THREAD

**Issue by netchild** [netdata/netdata#7456] opened 2019-12-06 13:24 UTC
##### Question summary

How often does the streaming feature transfer data from the slave to the master, e.g. in which timeinterval does it send "a bunch of data"?

Does it each time it wants to transfer data to the master lookup the IP of the master host or is the IP resolved once on startup?

The idea here is if it is feasible to configure a master host which may change IPs once a day (dyndns).

##### OS / Environment

FreeBSD

**Comment by Ferroin** [comment] 2019-12-06 13:37
Not sure on the timings (never used streaming myself and I can't find anything in the documentation), but I think once it connects it just sends data as it comes in locally.

As far as DNS and IP handling, unless things have changed significantly since I last looked at it, it's all IP based. DNS lookups are done once at startup and then connections are just done by IP.

If you _need_ to have a master with an unstable IP, you could set up a VPN connecting the master to each slave and use the master's IP on the VPN for streaming (this would also let you stream to a master that's behind a firewall you can't open a port through).

**Comment by netchild** [comment] 2019-12-06 14:07
A VPN is off course a workaround for this, but the complexity is higher on the VPN setup than on the possibility to use a hostname and have it resolve an IP from it each time it opens a connection to it.

I have found some traces that the streaming code may be http/websockets requests. So assuming websockets I can imagine that the reality currently looks like:  open connection to IP, stays open and data is transferred as it is collected, connection may break down and it is re-opened.

Plain IP based configuration was already outdated 20 years ago when I started to put my hands into unix like systems, so it really makes sense to have a DNS lookup in front of this (and makes the config also much more user friendly when we take IPv6 into acount), and then it also makes sense to re-lookup the DNS entry once the connection breaks down.

Do not only think about my usage scenario, also think about normal operational scenarios like e.g. mergers of companies, address range restructuring and such. In such cases you have already a lot on the plate, and you are happy if you just need change the DNS and be done, no need to touch every host which had the old IP configured.

**Comment by Ferroin** [comment] 2019-12-06 14:24
> A VPN is off course a workaround for this, but the complexity is higher on the VPN setup than on the possibility to use a hostname and have it resolve an IP from it each time it opens a connection to it.

Agreed.

> I have found some traces that the streaming code may be http/websockets requests. So assuming websockets I can imagine that the reality currently looks like: open connection to IP, stays open and data is transferred as it is collected, connection may break down and it is re-opened.

It looks like HTTP/websockets, but it isn't really (unless they've changed things since I last looked at the code). Otherwise you seem to be correct based on my own understanding of the code.

> Plain IP based configuration was already outdated 20 years ago when I started to put my hands into unix like systems, so it really makes sense to have a DNS lookup in front of this (and makes the config also much more user friendly when we take IPv6 into acount), and then it also makes sense to re-lookup the DNS entry once the connection breaks down.

You can still use hostnames in the config, it just looks them up once and then uses the IP's. The issue is with the handling of ACL's (for ACL's to work as expected (and securely), you need to resolve all the hostnames in the ACL list on each connect attempt, but doing that gives attackers a trivial way to DoS your infrastructure). There are actually a number of other tools that still work the same way for exactly the same reason.

**Comment by ilyam8** [comment] 2019-12-06 14:47
> and then it also makes sense to re-lookup the DNS entry once the connection breaks down.

Sounds good. @thiagoftsm what do you think?

**Comment by thiagoftsm** [comment] 2019-12-06 16:41
> Sounds good. @thiagoftsm what do you think?

I agree 100% with this suggestion, Netdata lookups DNS only when it starts the connection, but there are situations it changes.

I will add this in my roadmap for this sprint.

**Comment by Ferroin** [comment] 2019-12-06 17:18
Again, we need to be careful here. If we don't rate-limit the DNS lookups appropriately, this becomes an easy method to DoS DNS infrastructure.

**Comment by ilyam8** [comment] 2019-12-06 17:33
> only when it starts the connection

> this becomes an easy method to DoS DNS infrastructure

Well, to DoS DNS infrastructure is not so easy from my experience (big ISP - zero DNS DoS successful atacks in several years). Usually there is ip-rate limit... whici is very easy to confugure.

**Comment by ilyam8** [comment] 2019-12-06 17:39
@thiagoftsm do we cache hostname-ip reslove in `allow from` feature?

**Comment by thiagoftsm** [comment] 2019-12-06 18:24
We are not caching internally, we are using OS cache.

**Comment by ilyam8** [comment] 2020-01-06 16:29
^^ hotel wifi 😅

**Comment by ilyam8** [comment] 2021-08-02 14:13
Closing this feature request. We will re-evaluate the request internally.

**Closed by ilyam8** 2021-08-02 14:13 UTC
Labels: area/streaming, feature request
