### ISSUE TITLE
Found many error logs when using docker for deployment

### ISSUE THREAD

**Issue by FirstJavaMaster** [netdata/netdata#8769] opened 2020-04-20 04:41 UTC
##### Bug report summary

There are many error logs when installing using docker. However, it seems that the monitoring page can be accessed normally.

![image](https://user-images.githubusercontent.com/22362110/79714650-185bd200-8304-11ea-9a5b-1a95bac55f64.png)

I configured docker-compose according to the official method. Just like this:

```
version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: "139"
    environment:
      - PGID=991
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

It will be the same even if I remove `environment`.

And this is the docker log file.

[e0862d1f69e58a9be92ba244f73c87efbcbddd1a3e3752b40b7c0c20ec5b621e-json.log](https://github.com/netdata/netdata/files/4501228/e0862d1f69e58a9be92ba244f73c87efbcbddd1a3e3752b40b7c0c20ec5b621e-json.log)

##### OS / Environment

```
Linux docker1 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.7.1908 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.7.1908 (Core)
/etc/system-release:CentOS Linux release 7.7.1908 (Core)
```

##### Netdata version

The latest version in docker hub. 2020-04-20.

##### Component Name

It seems to be related to the performance monitoring of docker.

##### Steps To Reproduce

Just start the image according to the docker-compose file.

##### Expected behavior

Are these error logs normal? Are the resources occupied by docker on this machine counted normally?

**Comment by FirstJavaMaster** [comment] 2020-04-20 05:31
It seems that the docker occupancy on this server is not successfully monitored. 

![image](https://user-images.githubusercontent.com/22362110/79716980-e0a45880-830a-11ea-9a55-c2514bb7eeca.png)

After executing top on the machine, as shown below, there are two relatively high-occupancy services `dontstarve_dedi`. But it is not marked in netdata:

![image](https://user-images.githubusercontent.com/22362110/79717081-324ce300-830b-11ea-9566-89d5a548ae6b.png)

**Comment by prologic** [comment] 2020-04-21 04:55
When you talk about errors, do you mean the 'not found" errors on `/host/dev/...`?

**Comment by prologic** [comment] 2020-04-21 04:55
Can you paste an excerpt here as a comment so we're clear on what we're talking about?

**Comment by FirstJavaMaster** [comment] 2020-04-21 09:40
Sorry, maybe my problem is not described clearly. In general, I saw a lot of error logs when the docker container started, and I do n’t know if they are normal.

For example (The log file is in the problem description above):

340 lines of the log file:
![image](https://user-images.githubusercontent.com/22362110/79849649-52f16780-83f5-11ea-8d7b-97ced1aa6836.png)

469 lines of the log file (It seems to be about elasticsearch and fail2ban):
![image](https://user-images.githubusercontent.com/22362110/79850029-e88cf700-83f5-11ea-88f8-76d6d2be2df1.png)

900 lines of the log file (this is in the last part of the log file when container started. It seems like something went wrong while monitoring the docker container):
![image](https://user-images.githubusercontent.com/22362110/79850311-4ae5f780-83f6-11ea-83be-4a8dc2e79d91.png)


There is too much information for me to understand the situation. In the end, what I want to say is whether these errors can be ignored. Or these logs have some help for the project.

**Comment by ilyam8** [comment] 2020-04-21 12:45
duplicate of #5480

**Closed by ilyam8** 2020-04-21 12:45 UTC
Labels: bug, duplicate, needs triage

**Comment by ilyam8** [comment] 2020-04-21 12:48
We write everything to the one file (`error.log`), all netdata components logs go there. And yes, we use `error` level to much.

**Comment by FirstJavaMaster** [comment] 2020-04-22 01:53
Understood! And thanks!
