### ISSUE TITLE
mqtt topics/subscriptions monitoring? [FR]

### ISSUE THREAD

**Issue by LeeNX** [netdata/netdata#3935] opened 2018-07-05 12:24 UTC
Looking to possibly monitor mqtt topics and/subscriptions, ie IoT device sends topic/values to a mqtt server.  
  
I could not find anything close to mqtt topic monitoring, which I think might be very similar to snmp and/or custom log monitoring.  
  
As per my crazy request for custom log format monitoring for ESP devices, what is the chance this Feature Request get some dev time?  
  
I have some IoT devices that do mqtt, including the ESP devices, which I can test, if that helps any?  
  
Thanks for an awesome tool!!!

**Comment by paulfantom** [comment] 2018-07-07 16:32
You want to monitor how many messages are comming on some topic (1) or do you want to parse data from mqtt topics (2) and get it into netdata?

Problem with MQTT is similar to problems with SNMP - every implementation is different. Monitoring number of messages (1) comes more likely to monitoring mqtt broker by using its $SYS topic (ex. for mosquitto: https://github.com/mqtt/mqtt.github.io/wiki/SYS-Topics). And monitoring sent and received values (2) is actually log parsing due to lack of standarization of MQTT on this layer. You can send to a topic everything from a simple number to a full-blown JSON object.
In the second case it would be probably better to use something that is designed for this purpose, like [home assistant](https://www.home-assistant.io/components/#search/mqtt) to which you could also [connect netdata](https://www.home-assistant.io/components/sensor.netdata/) or something designed for log parsing like ELK/EFK stack.

**Comment by LeeNX** [comment] 2018-07-07 17:57
As I said, I think this is going to be like SNMP and/or custom log monitoring because of the unique implementations!  
  
I really luv the ease at which ```netdata``` does almost real-time trending and want to throw it at every project ... ;-)  
  
mqtt is nice that multiple clients can connect and all recieved subscribe ```topics```  
  
My current home need is for two client subscriptions, one a Weather Station  
```
/data/RFLINK/Acurite/cbd5/R/WINDIR 157.5
/data/RFLINK/Acurite/cbd5/R/WINSP 0.0
/data/RFLINK/Acurite/cbd5/R/BAT OK
/data/RFLINK/Acurite/cbd5/R/RAIN 496.8
/data/RFLINK/Acurite/cbd5/R/HUM 62
/data/RFLINK/Acurite/cbd5/R/WINSP 0.0
/data/RFLINK/Acurite/cbd5/R/BAT OK
/data/RFLINK/Acurite/cbd5/R/TEMP 7.7
/data/RFLINK/Acurite/cbd5/R/WINDIR 157.5
/data/RFLINK/Acurite/cbd5/R/WINSP 0.0
/data/RFLINK/Acurite/cbd5/R/BAT OK
/data/RFLINK/Acurite/cbd5/R/RAIN 496.8
/data/RFLINK/Acurite/cbd5/R/HUM 62
/data/RFLINK/Acurite/cbd5/R/WINSP 0.0
/data/RFLINK/Acurite/cbd5/R/BAT OK
/data/RFLINK/Acurite/cbd5/R/TEMP 7.7
```
and the other is VictronEnergy Solar gear ..
```
N/04a123fc4a3e/battery/512/Alarms/LowVoltage {"value": 0}
N/04a123fc4a3e/battery/512/Connected {"value": 1}
N/04a123fc4a3e/battery/512/Dc/0/Current {"value": -13.399999618530273}
N/04a123fc4a3e/battery/512/Dc/0/Power {"value": -652}
N/04a123fc4a3e/battery/512/Dc/0/Temperature {"value": 16.600000381469727}
N/04a123fc4a3e/battery/512/Dc/0/Voltage {"value": 48.729999542236328}
N/04a123fc4a3e/battery/512/DeviceInstance {"value": 512}
N/04a123fc4a3e/battery/512/FirmwareVersion {"value": null}
N/04a123fc4a3e/battery/512/Info/BatteryLowVoltage {"value": null}
N/04a123fc4a3e/battery/512/Info/MaxChargeCurrent {"value": 50.0}
N/04a123fc4a3e/battery/512/Info/MaxChargeVoltage {"value": 53.200000762939453}
N/04a123fc4a3e/battery/512/Info/MaxDischargeCurrent {"value": 50.0}
N/04a123fc4a3e/battery/512/Mgmt/Connection {"value": "CAN-bus"}
N/04a123fc4a3e/battery/512/ProductId {"value": 45065}
N/04a123fc4a3e/battery/512/ProductName {"value": "Pylontech battery"}
N/04a123fc4a3e/battery/512/Redetect {"value": 0}
N/04a123fc4a3e/battery/512/Soc {"value": 50}
N/04a123fc4a3e/battery/512/Soh {"value": 100}
N/04a123fc4a3e/fronius/0/AutoDetect {"value": 0}
N/04a123fc4a3e/fronius/0/ScanProgress {"value": 100.0}
N/04a123fc4a3e/grid/30/Ac/Current {"value": 1.137}
N/04a123fc4a3e/grid/30/Ac/Energy/Forward {"value": 1741.1000000000001}
N/04a123fc4a3e/grid/30/Ac/Energy/Reverse {"value": 2.3000000000000003}
N/04a123fc4a3e/grid/30/Ac/L1/Current {"value": 1.137}
```
thou the VictronEnergy might need only a select number attribs monitored, as it has  plenty of attribs that are not worth trending or subscribing too, but that is a later problem too address, much like the large number SNMP attribs in a MIB.  

But as the two samples posted, VictronEnergy is json vs plain values in the WeatherStation monitor.  
  
I have used OpenHAB in the past, but the trending is not near real-time line ```netdata```, which is just so pretty!  
  
@paulfantom - Thanks for the reply.

**Comment by paulfantom** [comment] 2018-07-07 18:19
I don't think this can be implemented as a generic solution. For SNMP netdata uses external library which does much of heavy lifting. In this case someone would need to implement whole library for multiple mqtt message scenarios and maintain it under netdata - doesn't seem like a good plan. And those two scenarios you mentioned aren't everything what would be needed, for example what if one topic have multiple values or is sending data in xml (I wonder if someone is that crazy :smile:)?

What I mean is that you can send anything through MQTT protocol and there is no documentation on how this should be sent. And if there is no documentation, how can someone implement generic monitoring solution?

However, the key here is **generic**. If you want a module which would work just for you, it would be quite simple to do so. You would need:
- python
- [paho-mqqt](https://pypi.org/project/paho-mqtt/) python library
- [documentation on how to write netdata module](https://github.com/firehol/netdata/wiki/How-to-write-new-module)
- some free time :smile:

**Comment by LeeNX** [comment] 2018-07-07 18:52
@paulfantom , thanks for the quick reply.  
  
I am learning that MQTT is as bad if not worse than SNMP ... '-}  
  
Python OOP just breaks my brain, I have tried a few times to learn, but it seems beyond me. Been able to hack up a few things in python and extend, but that is my limit.  
  
My Acurite Weather Station is already using Python script to pull data from 433MHz RF via [RFLink GateWay](http://www.rflink.nl/blog2/) using [RFLink Gateway to MQTT](https://github.com/LeeNX/RFLinkGateway)  
  
Was hoping to trend this in ```netdata``` via MQTT and view on our mobile devices in the house, but I think I will need to just hack up the suggestion as per #2813 in the past. Just feels a little messy. :-)

**Comment by cakrit** [comment] 2018-11-23 20:36
@LeeNX why don't you just tell us which metrics and charts make sense and what alerts would be meaningful? We could then handle the implementation of the collector relatively quickly. We'd also love it if you could help us with debugging the collector.

**Comment by paulfantom** [comment] 2018-11-26 09:51
It looks like what you need is [Home Assistant](https://home-assistant.io)

**Comment by LeeNX** [comment] 2018-11-26 10:49
Actually used [OpenHAB](https://www.openhab.org) v1.8 in the past, but did not like the too many things in one place and how poor the trends/graphs.   
  
Other options are systems like Node-Red and Domoticz, but I will re-deploy my OpenHAB automation in the near future, but would like to keep trends and possible alerts in netdata.  
  
Getting by with my bash hacks, so not stress.

**Comment by paulfantom** [comment] 2018-11-26 10:54
That's why Home Assistant can export data to other solutions: https://www.home-assistant.io/components/#history. Sadly there is no netdata there.

**Comment by ktsaou** [comment] 2018-11-26 12:05
There is statsd.

**Comment by ilyam8** [comment] 2018-12-05 23:09
duplicate of #3611

**Closed** 2018-12-05 23:10 UTC
Labels: area/external/python, duplicate, feature request, priority/low
