### ISSUE TITLE
CentOS 8.2 Installation: "missing binary operator before token" and "Cannot detect if this is a 32 or 64 bit CPU"

### ISSUE THREAD

**Issue by rienath** [netdata/netdata#9594] opened 2020-07-23 10:47 UTC
I am installing netdata on CentOS 8.2 and running into  "missing binary operator before token" and "Cannot detect if this is a 32 or 64 bit CPU" errors. I have attached the output. It's and OpenHPC clusters master node. 
```
make[2]: Entering directory '/home/admin/netdata'
  CC       collectors/apps.plugin/apps_plugin.o
  CC       libnetdata/adaptive_resortable_list/adaptive_resortable_list.o
  CC       libnetdata/config/appconfig.o
  CC       libnetdata/avl/avl.o
  CC       libnetdata/buffer/buffer.o
  CC       libnetdata/circular_buffer/circular_buffer.o
  CC       libnetdata/clocks/clocks.o
  CC       libnetdata/dictionary/dictionary.o
In file included from /usr/include/sys/stat.h:446,
                 from /usr/include/uv/unix.h:26,
                 from /usr/include/uv.h:66,
                 from collectors/apps.plugin/../../libnetdata/libnetdata.h:86,
                 from collectors/apps.plugin/apps_plugin.c:9:
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("
   38 | #if __glibc_has_include ("__linux__/stat.h")
      |                         ^
In file included from /usr/include/sys/stat.h:446,
                 from /usr/include/uv/unix.h:26,
                 from /usr/include/uv.h:66,
                 from libnetdata/config/../libnetdata.h:86,
                 from libnetdata/config/appconfig.c:3:
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("
   38 | #if __glibc_has_include ("__linux__/stat.h")
      |                         ^
In file included from /usr/include/sys/stat.h:446,
                 from /usr/include/uv/unix.h:26,
                 from /usr/include/uv.h:66,
                 from libnetdata/adaptive_resortable_list/../libnetdata.h:86,
                 from libnetdata/adaptive_resortable_list/adaptive_resortable_list.c:3:
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("
   38 | #if __glibc_has_include ("__linux__/stat.h")
      |                         ^
In file included from /usr/include/sys/stat.h:446,
                 from /usr/include/uv/unix.h:26,
                 from /usr/include/uv.h:66,
                 from libnetdata/buffer/../libnetdata.h:86,
                 from libnetdata/buffer/buffer.c:3:
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("
   38 | #if __glibc_has_include ("__linux__/stat.h")
      |                         ^
In file included from /usr/include/sys/stat.h:446,
                 from /usr/include/uv/unix.h:26,
                 from /usr/include/uv.h:66,
                 from libnetdata/avl/../libnetdata.h:86,
                 from libnetdata/avl/avl.c:3:
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("
   38 | #if __glibc_has_include ("__linux__/stat.h")
      |                         ^
In file included from /usr/include/sys/stat.h:446,
                 from /usr/include/uv/unix.h:26,
                 from /usr/include/uv.h:66,
                 from libnetdata/circular_buffer/../libnetdata.h:86,
                 from libnetdata/circular_buffer/circular_buffer.c:1:
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("
   38 | #if __glibc_has_include ("__linux__/stat.h")
      |                         ^
In file included from /usr/include/sys/stat.h:446,
                 from /usr/include/uv/unix.h:26,
                 from /usr/include/uv.h:66,
                 from libnetdata/clocks/../libnetdata.h:86,
                 from libnetdata/clocks/clocks.c:3:
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("
   38 | #if __glibc_has_include ("__linux__/stat.h")
      |                         ^
In file included from /usr/include/sys/stat.h:446,
                 from /usr/include/uv/unix.h:26,
                 from /usr/include/uv.h:66,
                 from libnetdata/dictionary/../libnetdata.h:86,
                 from libnetdata/dictionary/dictionary.c:3:
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("
   38 | #if __glibc_has_include ("__linux__/stat.h")
      |                         ^
In file included from libnetdata/adaptive_resortable_list/adaptive_resortable_list.c:3:
libnetdata/adaptive_resortable_list/../libnetdata.h:161:2: error: #error "Cannot detect if this is a 32 or 64 bit CPU"
  161 | #error "Cannot detect if this is a 32 or 64 bit CPU"
      |  ^~~~~
In file included from collectors/apps.plugin/apps_plugin.c:9:
collectors/apps.plugin/../../libnetdata/libnetdata.h:161:2: error: #error "Cannot detect if this is a 32 or 64 bit CPU"
  161 | #error "Cannot detect if this is a 32 or 64 bit CPU"
      |  ^~~~~
In file included from libnetdata/config/appconfig.c:3:
libnetdata/config/../libnetdata.h:161:2: error: #error "Cannot detect if this is a 32 or 64 bit CPU"
  161 | #error "Cannot detect if this is a 32 or 64 bit CPU"
      |  ^~~~~
In file included from libnetdata/buffer/buffer.c:3:
libnetdata/buffer/../libnetdata.h:161:2: error: #error "Cannot detect if this is a 32 or 64 bit CPU"
  161 | #error "Cannot detect if this is a 32 or 64 bit CPU"
      |  ^~~~~
In file included from libnetdata/circular_buffer/circular_buffer.c:1:
libnetdata/circular_buffer/../libnetdata.h:161:2: error: #error "Cannot detect if this is a 32 or 64 bit CPU"
  161 | #error "Cannot detect if this is a 32 or 64 bit CPU"
      |  ^~~~~
In file included from libnetdata/avl/avl.c:3:
libnetdata/avl/../libnetdata.h:161:2: error: #error "Cannot detect if this is a 32 or 64 bit CPU"
  161 | #error "Cannot detect if this is a 32 or 64 bit CPU"
      |  ^~~~~
In file included from libnetdata/clocks/clocks.c:3:
libnetdata/clocks/../libnetdata.h:161:2: error: #error "Cannot detect if this is a 32 or 64 bit CPU"
  161 | #error "Cannot detect if this is a 32 or 64 bit CPU"
      |  ^~~~~
In file included from libnetdata/dictionary/dictionary.c:3:
libnetdata/dictionary/../libnetdata.h:161:2: error: #error "Cannot detect if this is a 32 or 64 bit CPU"
  161 | #error "Cannot detect if this is a 32 or 64 bit CPU"
      |  ^~~~~
make[2]: *** [Makefile:4799: libnetdata/circular_buffer/circular_buffer.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:4799: libnetdata/adaptive_resortable_list/adaptive_resortable_list.o] Error 1
make[2]: *** [Makefile:4799: libnetdata/dictionary/dictionary.o] Error 1
make[2]: *** [Makefile:4799: libnetdata/avl/avl.o] Error 1
make[2]: *** [Makefile:4799: libnetdata/buffer/buffer.o] Error 1
make[2]: *** [Makefile:4799: libnetdata/clocks/clocks.o] Error 1
make[2]: *** [Makefile:4799: libnetdata/config/appconfig.o] Error 1
make[2]: *** [Makefile:4799: collectors/apps.plugin/apps_plugin.o] Error 1
make[2]: Leaving directory '/home/admin/netdata'
make[1]: *** [Makefile:5481: all-recursive] Error 1
make[1]: Leaving directory '/home/admin/netdata'
make: *** [Makefile:2968: all] Error 2
 FAILED   

[root@computer-10 netdata]# 
```

**Comment by rienath** [comment] 2020-07-24 08:27
1 ticket for 2 bugs because looks like the problems are very similar

**Comment by Ferroin** [comment] 2020-07-24 11:23
@netdata/agent While this was an issue on install, I'm fairly certain it's a problem with either the C code or the build system.

**Comment by rienath** [comment] 2020-07-24 14:13
@Ferroin as I said it's OpenHPC cluster. Might be their problem, but does netdata need to access ohpc files it doesn't like?

**Comment by cakrit** [comment] 2020-08-07 07:26
@amoss I think we need your help to understand what can be done here

**Comment by amoss** [comment] 2020-08-07 08:26
I'll set up a Centos 8.2 VM and see what happens.

**Comment by Ferroin** [comment] 2020-09-01 14:36
I cannot reproduce this locally using the official CentOS 8 Docker images.

**Comment by prologic** [comment] 2020-09-02 06:52
I will test this too.

**Comment by rienath** [comment] 2020-09-02 14:25
I would suggest installing openhpc before netdata

**Comment by prologic** [comment] 2020-09-08 06:09
> I would suggest installing openhpc before netdata

Why would installing another piece of software having any effect here? Specifically `openhpc`?

**Comment by prologic** [comment] 2020-09-08 06:11
> > I would suggest installing openhpc before netdata
> 
> Why would installing another piece of software having any effect here? Specifically `openhpc`?

In fact (_I didn't notice this before_), somehow you are using some non-standard toolchain here from openhcp? Why? How is this your default compiler?

**Comment by prologic** [comment] 2020-09-08 06:12
Furthermore I don't know _anything_ about `openhpc`:

```#!console
[root@fccd5420adbd /]# yum search openhpc
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:00:57 ago on Tue Sep  8 06:10:42 2020.
No matches found.
```

Can you please provide us reproducible steps we can work with? As far as I'm conferned our installer works correctly as intended on a fresh CentOS 7/8 system.

**Comment by rienath** [comment] 2020-09-15 16:38
> OpenHPC is a set of community driven FOSS tools for Linux based HPC. **(c) Wiki**

It is a very popular collection of software that people use to implement clusters.

> somehow you are using some non-standard toolchain here from openhcp

Yeah, you are right. Now I see where the error is coming from. There is a part in openhpc installation guide, where you set up a default development environment (para 4.5). That is where the default compiler gets changed.

Way to reproduce:

1. Enable ohpc repo:
```
yum install http://repos.openhpc.community/OpenHPC/2/CentOS_8/aarch64/ohpc-release-2-1.el8.aarch64.rpm
yum install dnf-plugins-core
yum config-manager --set-enabled PowerTools
```

2. Install the environment
```
yum -y install lmod-defaults-gnu9-openmpi4-ohpc
```

3. Install netdata
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

**Comment by prologic** [comment] 2020-09-16 05:52
Thank you. We'll look into how we can solve this on our end to avoid such situations. cc @Ferroin But as you've found a work-around I will put this on our Backlog at a lower priority after first discussing with the team. Thanks! 🙇‍♂️

**Comment by Ferroin** [comment] 2020-09-16 11:17
> I'll leave the issue open in case you want to add gcc 9.2.0 support, but otherwise, the problem is settled. Thanks.

Speaking from personal experience, _stock_ GCC 9.2.0 works just fine to build Netdata. This is something with the OpenHPC builds that's causing the issue. We do want to eventually have this working, but right now we can't technically even be certain that this is an issue with our code (we could be hitting a bug in the OHPC version of GCC with some uncommon but still standards compliant C code).

I do have a few ideas of what _might_ be wrong here (big one that comes to mind is that we're not explicitly declaring what C standard we want in the compiler options we pass, and that _can_ cause issues), so if I have some spare time to check into this I'll try and test those possibilities and see if they are actually the issue.

**Comment by LordBonkerz** [comment] 2020-09-18 14:56
I have tried with openHPC on the their mailing list, they seem to have not seen this themselfs, yet I'm experiencing the very same thing. Everything bails out the same way when compiling anything. Could be related to the header file(s) statx.h?

Frustrating indeed.

**Comment by LordBonkerz** [comment] 2020-09-18 15:17
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h    REMOVE this file and all works WELL!

**Comment by OdysLam** [comment] 2020-09-21 15:49
Hey @LordBonkerz, 

Welcome to our community! We are glad that we got it fixed in the end. If you have any further question, don't hesitate to create a thread in our forums at https://community.netdata.cloud.

Take care!

**Comment by Ferroin** [comment] 2021-08-10 14:43
Closing this as it appears to be solved.

**Closed by Ferroin** 2021-08-10 14:43 UTC
Labels: bug, area/packaging
