### ISSUE TITLE
cannot claim node - code error 28

### ISSUE THREAD

**Issue by parenok** [netdata/netdata#9921] opened 2020-09-13 12:19 UTC
##### Question summary
When I try to claim some of my nodes I get
```
cannot claim node - code error 28
```
All my nodes have ip addresses from the same network. I suppose, that the problem can be some ware in firewall on host app.netdata.cloud. Why I think so - connection from my nodes to app.netdata.cloud is not established. I checked connection with **nc** and **wget** programmes 
```
root@mysql:~# nc -w 30 -zv app.netdata.cloud 443
nc: connect to app.netdata.cloud port 443 (tcp) timed out: Operation now in progress
```
```
root@mysql:~# nc -w 30 -zv 35.196.244.138 443
nc: connect to 35.196.244.138 port 443 (tcp) timed out: Operation now in progress
```
```
root@mysql:~# wget --timeout 30 https://app.netdata.cloud
--2020-09-13 14:32:39--  https://app.netdata.cloud/
Resolving app.netdata.cloud (app.netdata.cloud)... 35.196.244.138
Connecting to app.netdata.cloud (app.netdata.cloud)|35.196.244.138|:443... failed: Connection timed out.
```
Log from tcpdump, when i try to claim node - as you can see, my node doesn't get ACK response from app.netdata.cloud host
```
root@mysql:~# tcpdump -nnn host 35.196.244.138
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp3s0, link-type EN10MB (Ethernet), capture size 262144 bytes
14:39:20.295945 IP MY-NODE-IP.35182 > 35.196.244.138.443: Flags [S], seq 2071580411, win 64240, options [mss 1460,sackOK,TS val 3134057555 ecr 0,nop,wscale 7], length 0
14:39:21.318416 IP MY-NODE-IP.35182 > 35.196.244.138.443: Flags [S], seq 2071580411, win 64240, options [mss 1460,sackOK,TS val 3134058576 ecr 0,nop,wscale 7], length 0
14:39:23.334379 IP MY-NODE-IP.35182 > 35.196.244.138.443: Flags [S], seq 2071580411, win 64240, options [mss 1460,sackOK,TS val 3134060590 ecr 0,nop,wscale 7], length 0
14:39:27.526370 IP MY-NODE-IP.35182 > 35.196.244.138.443: Flags [S], seq 2071580411, win 64240, options [mss 1460,sackOK,TS val 3134064779 ecr 0,nop,wscale 7], length 0
14:39:35.718478 IP MY-NODE-IP.35182 > 35.196.244.138.443: Flags [S], seq 2071580411, win 64240, options [mss 1460,sackOK,TS val 3134072948 ecr 0,nop,wscale 7], length 0
14:39:51.296569 IP MY-NODE-IP.35184 > 35.196.244.138.443: Flags [S], seq 2581772642, win 64240, options [mss 1460,sackOK,TS val 3134088481 ecr 0,nop,wscale 7], length 0
14:39:52.326408 IP MY-NODE-IP.35184 > 35.196.244.138.443: Flags [S], seq 2581772642, win 64240, options [mss 1460,sackOK,TS val 3134089510 ecr 0,nop,wscale 7], length 0
14:39:54.342420 IP MY-NODE-IP.35184 > 35.196.244.138.443: Flags [S], seq 2581772642, win 64240, options [mss 1460,sackOK,TS val 3134091524 ecr 0,nop,wscale 7], length 0
14:39:58.502418 IP MY-NODE-IP.35184 > 35.196.244.138.443: Flags [S], seq 2581772642, win 64240, options [mss 1460,sackOK,TS val 3134095680 ecr 0,nop,wscale 7], length 0
14:40:06.694574 IP MY-NODE-IP.35184 > 35.196.244.138.443: Flags [S], seq 2581772642, win 64240, options [mss 1460,sackOK,TS val 3134103862 ecr 0,nop,wscale 7], length 0
14:40:23.297278 IP MY-NODE-IP.35186 > 35.196.244.138.443: Flags [S], seq 3541699880, win 64240, options [mss 1460,sackOK,TS val 3134120407 ecr 0,nop,wscale 7], length 0
14:40:24.326420 IP MY-NODE-IP.35186 > 35.196.244.138.443: Flags [S], seq 3541699880, win 64240, options [mss 1460,sackOK,TS val 3134121435 ecr 0,nop,wscale 7], length 0
14:40:26.342436 IP MY-NODE-IP.35186 > 35.196.244.138.443: Flags [S], seq 3541699880, win 64240, options [mss 1460,sackOK,TS val 3134123448 ecr 0,nop,wscale 7], length 0
14:40:30.502435 IP MY-NODE-IP.35186 > 35.196.244.138.443: Flags [S], seq 3541699880, win 64240, options [mss 1460,sackOK,TS val 3134127605 ecr 0,nop,wscale 7], length 0
14:40:38.694401 IP MY-NODE-IP.35186 > 35.196.244.138.443: Flags [S], seq 3541699880, win 64240, options [mss 1460,sackOK,TS val 3134135791 ecr 0,nop,wscale 7], length 0
14:40:56.297809 IP MY-NODE-IP.35188 > 35.196.244.138.443: Flags [S], seq 3705201928, win 64240, options [mss 1460,sackOK,TS val 3134153385 ecr 0,nop,wscale 7], length 0
14:40:57.318514 IP MY-NODE-IP.35188 > 35.196.244.138.443: Flags [S], seq 3705201928, win 64240, options [mss 1460,sackOK,TS val 3134154405 ecr 0,nop,wscale 7], length 0
14:40:59.334403 IP MY-NODE-IP.35188 > 35.196.244.138.443: Flags [S], seq 3705201928, win 64240, options [mss 1460,sackOK,TS val 3134156420 ecr 0,nop,wscale 7], length 0
14:41:03.526406 IP MY-NODE-IP.35188 > 35.196.244.138.443: Flags [S], seq 3705201928, win 64240, options [mss 1460,sackOK,TS val 3134160610 ecr 0,nop,wscale 7], length 0
```
But all good from my node to app.netdata.cloud host from network side
```
root@mysql:~# mtr -r -c 100 -n app.netdata.cloud
Start: 2020-09-13T14:55:49+0300
HOST: mysql                       Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- 100.64.0.1                 0.0%   100    0.2   0.2   0.1   0.8   0.1
  2.|-- 88.208.54.254              0.0%   100    0.7   1.3   0.6  16.4   2.4
  3.|-- 10.10.247.100              0.0%   100    0.9   1.1   0.7  15.5   1.6
  4.|-- 10.10.247.14               0.0%   100    1.0   0.8   0.7   1.5   0.1
  5.|-- 80.249.208.247             0.0%   100    0.9   2.5   0.8 113.7  11.3
  6.|-- 108.170.241.205            0.0%   100    1.6   1.7   1.4   3.0   0.2
  7.|-- 216.239.43.27             67.0%   100    1.5   2.0   1.2   8.3   1.4
  8.|-- 108.170.237.243           62.0%   100    7.2   7.4   6.7  12.8   1.2
  9.|-- 142.250.59.180            23.0%   100   86.4  86.8  86.2  89.4   0.6
 10.|-- 216.239.50.98              0.0%   100   94.4  95.3  94.1 123.0   4.0
 11.|-- 209.85.252.112             0.0%   100   92.6  93.9  92.2 137.3   6.1
 12.|-- 209.85.254.23              0.0%   100   95.8  96.1  95.5 100.9   0.7
 13.|-- ???                       100.0   100    0.0   0.0   0.0   0.0   0.0
 14.|-- ???                       100.0   100    0.0   0.0   0.0   0.0   0.0
 15.|-- ???                       100.0   100    0.0   0.0   0.0   0.0   0.0
 16.|-- ???                       100.0   100    0.0   0.0   0.0   0.0   0.0
 17.|-- ???                       100.0   100    0.0   0.0   0.0   0.0   0.0
 18.|-- ???                       100.0   100    0.0   0.0   0.0   0.0   0.0
 19.|-- ???                       100.0   100    0.0   0.0   0.0   0.0   0.0
 20.|-- ???                       100.0   100    0.0   0.0   0.0   0.0   0.0
 21.|-- ???                       100.0   100    0.0   0.0   0.0   0.0   0.0
 22.|-- 35.196.244.138             0.0%   100   92.3  92.8  92.0 130.8   4.0
```

# OS / Environment
```
Linux mysql 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
```
root@mysql:~# netdata -V
netdata v1.24.0
```

I have another nodes with such OS in the same network, and they claim without problem. I use the same configuration on all my nodes (I mean firewall, network, netdata). I tried to claim my nodes several times within 2 days and always got error. I can send my nodes ip addresses in a personal message, can someone from netdata team to check if my nodes ips don't block on the netdata infrastructure side?

**Comment by OdysLam** [comment] 2020-09-14 08:28
Hey!

Welcome to our community @parenok. Someone from the team will try to reply as soon as possible.  As a starter, how did you install netdata on the systeM? 

Happy monitoring :)

**Comment by parenok** [comment] 2020-09-14 08:48
> Hey!
> 
> Welcome to our community @parenok. Someone from the team will try to reply as soon as possible. As a starter, how did you install netdata on the systeM?
> 
> Happy monitoring :)

Hello!
I use kickstart script with those options
```
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait --disable-telemetry --stable-channel
```

**Comment by underhood** [comment] 2020-09-16 07:53
@netdata/cloud-be can you guys check this? Is there any rate-limiting firewall or something like that? Seems only one node cannot connect for some reason.

**Comment by parenok** [comment] 2020-09-16 08:11
> Seems only one node cannot connect for some reason.

At this moment I have 3 nodes which can't connect to https://app.netdata.cloud

**Comment by underhood** [comment] 2020-09-17 07:16
@parenok Will try to get somebody from the cloud team to look at this. However, as you yourself see it is a network connectivity issue. Can be caused by the network on your side or by some firewall on the cloud side.
Are you by any chance behind any corporate firewall/proxy?

@netdata/cloud-be @prologic @Ferroin  any ideas?

**Comment by fracasula** [comment] 2020-09-17 11:32
At a first glance it doesn't look like an agent or cloud issue. `wget` is failing too. Can we get a traceroute please @parenok?

`traceroute app.netdata.cloud`

**Comment by fracasula** [comment] 2020-09-17 12:06
Sorry I meant on 443: `sudo traceroute --icmp -m 100 app.netdata.cloud 443`

**Comment by parenok** [comment] 2020-09-17 13:40
> However, as you yourself see it seems to be a network connectivity issue (not a bug in ACLK/agent).
This cannot be confirmed at least until we see a backtrace from the app.netdata.cloud host to my server. In traceroute from my server to app.netdata.cloud, you can see that packets are coming at the network level. But communication is not established at the transport level. This may mean that packages are dropped either on the app.netdata.cloud host or on intermediate nodes. I assume that traffic from the ip addresses of my servers is blocked completely on app.netdata.cloud host. And I want you to check it out.

> Can be caused by the network on your side or by some firewall on the cloud side.
> Are you by any chance behind any corporate firewall/proxy?

From my side I have checked all intermediate points from my server to my boarder router - any restriction were not found. 

> @parenok Sorry I meant on 443: `sudo traceroute --icmp -m 100 app.netdata.cloud 443`

You command will show the same result which I have already post at the beginning of discussion (```traceroute --icmp -m 100 app.netdata.cloud 443``` is the same for ```mtr -r -c 100 -n app.netdata.cloud``` because both commands work at the network layer by default and both will show that packets are accepted by app.netdata.cloud host). Result is below

```
root@mysql:~# traceroute --icmp -m 100 app.netdata.cloud 443
traceroute to app.netdata.cloud (35.196.244.138), 100 hops max, 443 byte packets
 1  _gateway (100.64.0.1)  0.301 ms  0.301 ms  0.300 ms
 2  88.208.54.254 (88.208.54.254)  0.831 ms  1.282 ms  1.738 ms
 3  10.10.247.100 (10.10.247.100)  0.827 ms  1.173 ms  1.569 ms
 4  10.10.247.14 (10.10.247.14)  0.943 ms  1.026 ms  1.108 ms
 5  core1.ams.net.google.com (80.249.208.247)  1.156 ms  1.158 ms  1.120 ms
 6  108.170.241.237 (108.170.241.237)  1.540 ms  1.427 ms  1.481 ms
 7  216.239.42.170 (216.239.42.170)  1.483 ms  1.463 ms *
 8  * * *
 9  142.250.59.184 (142.250.59.184)  86.675 ms  86.723 ms  86.728 ms
10  * * *
11  * * 216.239.48.6 (216.239.48.6)  88.823 ms
12  209.85.253.158 (209.85.253.158)  114.014 ms  114.066 ms  114.048 ms
13  209.85.252.112 (209.85.252.112)  103.392 ms  103.788 ms  103.791 ms
14  209.85.249.99 (209.85.249.99)  105.353 ms  105.248 ms  105.740 ms
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  138.244.196.35.bc.googleusercontent.com (35.196.244.138)  97.595 ms  97.637 ms  97.637 ms
```
As you can see at network layer packets are accepted.  

I suppose you want to see tcptraceroute results, don't you ? :) Here is result for tcptraceroute, which works at transport layer
```
root@mysql:~# tcptraceroute -m 30 app.netdata.cloud 443
Selected device enp3s0, address 100.125.164.1, port 52879 for outgoing packets
Tracing the path to app.netdata.cloud (35.196.244.138) on TCP port 443 (https), 30 hops max
 1  _gateway (100.64.0.1)  0.082 ms  0.072 ms  0.090 ms
 2  88.208.54.254  0.620 ms  0.616 ms  0.603 ms
 3  10.10.247.100  0.969 ms  0.698 ms  0.672 ms
 4  10.10.247.14  0.679 ms  0.734 ms  0.705 ms
 5  core1.ams.net.google.com (80.249.208.247)  1.909 ms  0.831 ms  3.888 ms
 6  108.170.241.140  1.302 ms  1.445 ms  1.404 ms
 7  * 216.239.40.135 1.377 ms  1.494 ms
 8  * * *
 9  142.250.59.180  86.198 ms  86.478 ms  86.220 ms
10  172.253.71.184  81.640 ms  81.721 ms *
11  216.239.48.2  88.198 ms  89.973 ms *
12  108.170.230.172  102.838 ms  102.686 ms  103.469 ms
13  216.239.46.64  127.839 ms  97.874 ms  97.942 ms
14  216.239.50.29  102.598 ms  102.636 ms  102.693 ms
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
Destination not reached
```
I limited tcptraceroute with 30 hops because at network layer we saw that app.netdata.cloud host is located within 30 hops. As we can see in tcptraceroute result app.netdata.cloud host is not reached on 443 port from my server. Can you check from you side if my server ip addresses are not blocked some ware on app.netdata.cloud infrastructure? I can send my ips in private message.

**Comment by fracasula** [comment] 2020-09-17 15:39
> I suppose you want to see tcptraceroute results, don't you ? :) Here is result for tcptraceroute, which works at transport layer

Yes, thank you :slightly_smiling_face: 

> As we can see in tcptraceroute result app.netdata.cloud host is not reached on 443 port from my server. Can you check from you side if my server ip addresses are not blocked some ware on app.netdata.cloud infrastructure? I can send my ips in private message.

Send them at francesco@netdata.cloud please.

You also mentioned that you were able to claim other nodes, if they are in the same network, can we please get a `tcptraceroute` from one of them please? Thanks.

**Comment by parenok** [comment] 2020-09-17 16:22
> Send them at [francesco@netdata.cloud](mailto:francesco@netdata.cloud) please.

Sent, check please.

> You also mentioned that you were able to claim other nodes, if they are in the same network, can we please get a `tcptraceroute` from one of them please? Thanks.

Sure. Here is some examples
```
root@dsm-NL:~# tcptraceroute -m 30 app.netdata.cloud 443
Selected device enp3s0, address 100.113.8.1, port 42761 for outgoing packets
Tracing the path to app.netdata.cloud (35.196.244.138) on TCP port 443 (https), 30 hops max
 1  _gateway (100.64.0.1)  0.190 ms  0.113 ms  0.077 ms
 2  88.208.54.254  0.558 ms  0.552 ms  0.529 ms
 3  10.10.247.98  0.814 ms  0.716 ms  0.733 ms
 4  10.10.247.10  0.861 ms  0.717 ms  17.051 ms
 5  core1.ams.net.google.com (80.249.208.247)  0.820 ms  0.882 ms  5.739 ms
 6  108.170.241.140  1.388 ms  1.435 ms  1.383 ms
 7  * 216.239.40.135 1.227 ms *
 8  * * *
 9  * 142.250.59.180 83.794 ms  83.876 ms
10  * 72.14.233.136 83.350 ms *
11  216.239.48.6  88.690 ms  88.832 ms  88.891 ms
12  209.85.253.158  97.839 ms  98.071 ms  97.651 ms
13  209.85.247.210  109.042 ms  102.434 ms  103.614 ms
14  172.253.74.155  102.303 ms  102.125 ms  102.801 ms
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  138.244.196.35.bc.googleusercontent.com (35.196.244.138) [open]  99.679 ms  99.676 ms  99.883 ms
```
```
root@dsm-anycast-NL:~# tcptraceroute -m 30 app.netdata.cloud 443
Selected device enp3s0, address 100.102.236.1, port 34687 for outgoing packets
Tracing the path to app.netdata.cloud (35.196.244.138) on TCP port 443 (https), 30 hops max
 1  _gateway (100.64.0.1)  0.087 ms  0.129 ms  0.132 ms
 2  88.208.54.254  0.573 ms  0.596 ms  0.699 ms
 3  10.10.247.98  0.670 ms  2.932 ms  0.725 ms
 4  10.10.247.10  0.810 ms  0.998 ms  0.766 ms
 5  core1.ams.net.google.com (80.249.208.247)  3.597 ms  1.462 ms  1.312 ms
 6  108.170.241.236  1.101 ms  1.263 ms  1.131 ms
 7  209.85.254.49  1.332 ms  5.512 ms *
 8  108.170.237.243  7.224 ms * *
 9  142.250.59.180  88.943 ms  88.521 ms *
10  172.253.71.184  84.518 ms * *
11  216.239.48.2  93.804 ms  93.544 ms  93.622 ms
12  108.170.230.172  100.032 ms  101.699 ms  100.051 ms
13  72.14.234.70  101.847 ms  101.063 ms  101.128 ms
14  172.253.76.135  97.554 ms  97.669 ms  97.698 ms
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  138.244.196.35.bc.googleusercontent.com (35.196.244.138) [open]  97.864 ms  97.805 ms  97.775 ms
```
Ips of those hosts also provided in email.

**Comment by prologic** [comment] 2020-09-18 04:04
@parenok / @fracasula The SRE team __does not__ actively (_or even unknowingly_) block IPs into our Infrastructure. The only _thing_ in place is rate limiting, but that would not explain the failed TCP routing I just saw above.

Can I get a `tcpdump` please? I'd love to see the PCAP on your side.

**Comment by parenok** [comment] 2020-09-18 11:55
> Can I get a `tcpdump` please? I'd love to see the PCAP on your side.

pcap file is attached in zip archive. I run ```tcpdump -w tcpdump.pcap port 443 or 53``` and then run claim command and after ```nc -zv app.netdata.cloud 443```
[tcpdump.pcap.zip](https://github.com/netdata/netdata/files/5245293/tcpdump.pcap.zip)

**Comment by OdysLam** [comment] 2020-10-25 10:19
Hey @parenok,

We seem that we dropped the ball on this issue. Pinging again the team to look into it, thank you for your patience!

**Comment by cakrit** [comment] 2020-10-26 14:52
We need to investigate this, so that you don't have to change your IPs @parenok. Either @Ferroin or @knatsakis will continue the investigation and @kaskavel will see if we can reproduce the issue in the lab.

**Comment by parenok** [comment] 2020-11-02 09:40
> We need to investigate this, so that you don't have to change your IPs @parenok. Either @Ferroin or @knatsakis will continue the investigation and @kaskavel will see if we can reproduce the issue in the lab.

Ok. I will wait.

**Comment by kaskavel** [comment] 2020-11-02 13:06
hello @parenok. We did some thorough investigation of this issue. However we believe that the problem isn't on our part of the system. 
To be more specific, as already mentioned we are not firewalling any IPs and for sure not the one discussed here. Logs investigation in haproxy do not help since we are not logging any timed out requests (only successful tcp sockets). Whatever similar setup we have used also did not reproduce the issue. 
No reason to guess why these requests are getting lost but we think it is out of our reach. 
Can we propose to try to change the IP in one of these nodes and see if this fixes the problem?

**Comment by parenok** [comment] 2020-11-08 08:24
> Can we propose to try to change the IP in one of these nodes and see if this fixes the problem?
Ip changing is solve problem. But some servers are still can't connect to app.netdata.cloud.

**Comment by ilyam8** [comment] 2021-08-31 14:20
@parenok, hi. Can you re-test claiming?

**Comment by parenok** [comment] 2021-09-01 12:06
> @parenok, hi. Can you re-test claiming?

Hi. Node was claimed successful.

**Comment by ilyam8** [comment] 2021-09-01 13:15
Thanks for the quick answer!

**Comment by ilyam8** [comment] 2021-09-01 13:15
Closing this issue, because we can't reproduce it and there is no other users report the same problem and it appears to be working for @parenok now.

**Closed by ilyam8** 2021-09-01 13:15 UTC
Labels: bug, needs triage

**Comment by g0rbe** [comment] 2021-09-23 09:59
I cant claim my nodes too.

```
Failed to connect to https://app.netdata.cloud, return code 28
Connection attempt 1 failed. Retry in 1s.
Failed to connect to https://app.netdata.cloud, return code 28
Connection attempt 2 failed. Retry in 2s.
Failed to connect to https://app.netdata.cloud, return code 28
Connection attempt 3 failed. Retry in 3s.
grep: /var/lib/netdata/cloud.d/tmpout.txt: No such file or directory
grep: /var/lib/netdata/cloud.d/tmpout.txt: No such file or directory
Failed to claim node with the following error message:"Unknown HTTP error message"
 FAILED  
```

**Comment by arsenick69** [comment] 2021-10-04 09:19
Hello, i have the same problem on 2 servers (debian jessie and debian 9)



```
 --- Found existing install of Netdata under: / --- 
 --- Attempting to claim agent to https://app.netdata.cloud --- 
Token: ****************
Base URL: https://app.netdata.cloud
Id:  xxxxx
Rooms: xxxxx
Hostname: ns311782
Proxy: 
Netdata user: netdata
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 1 failed. Retry in 1s.
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 2 failed. Retry in 2s.
Failed to connect to https://app.netdata.cloud, return code 60
Connection attempt 3 failed. Retry in 3s.
grep: /var/lib/netdata/cloud.d/tmpout.txt: No such file or directory
grep: /var/lib/netdata/cloud.d/tmpout.txt: No such file or directory
Failed to claim node with the following error message:"Unknown HTTP error message"
```

and 

```
root@ns311782:~# wget https://app.netdata.cloud
--2021-10-04 11:18:14--  https://app.netdata.cloud/
Resolving app.netdata.cloud (app.netdata.cloud)... 35.196.244.138
Connecting to app.netdata.cloud (app.netdata.cloud)|35.196.244.138|:443... connected.
ERROR: The certificate of 'app.netdata.cloud' is not trusted.
ERROR: The certificate of 'app.netdata.cloud' has expired
```

**Comment by kaskavel** [comment] 2021-10-04 10:13
@arsenick69 can you try the solution described [here](https://community.netdata.cloud/t/certificate-verification-error-connecting-to-the-cloud/1790) ?
