### ISSUE TITLE
Register (claim) a Netdata Agent to a specific Netdata Account 

### ISSUE THREAD

**Issue by gmosx** [netdata/netdata#4771] opened 2018-11-28 07:47 UTC
Will support the registration of a Netdata Agent to a specific Netdata Account.

**Comment by gmosx** [comment] 2018-12-20 07:09
This issue was preempted by MVP-0 and will be rescheduled for MVP-1.

**Comment by cakrit** [comment] 2019-07-03 10:10
Closing as duplicate of #6318, which has more details

**Closed by cakrit** 2019-07-03 10:10 UTC
Labels: area/registry, area/web, cloud, feature request, priority/high
