### ISSUE TITLE
Syntax error after mount

### ISSUE THREAD

**Issue by casperklein** [netdata/netdata#3449] opened 2018-02-20 21:09 UTC
netdata version: 1.9.0-457-g1063556_rolling

I noticed an error when having a mount like this:

```/dev/mapper/foo  on  /mnt/example%2ecom/test  type  ext3            (rw,relatime,data=ordered)```

In my browsers console I can see the following:

```Error: Syntax error, unrecognized expression: #menu_disk_submenu__mnt_example%2ecom_test     jquery-2.2.4.min.js:2:12556```

I guess the dot (%2e) in the mount directorys name is the cause of that error.

**Comment by jptuomi** [comment] 2020-03-18 10:54
Had this problem with netdata on Synology, the offending path was /volume1/@docker which was easily excluded in the diskspace plugin.

However the above error is quite critical as the web-interface stops working as it should with regards to the Alarms popup among other things.

**Comment by ilyam8** [comment] 2020-03-18 11:54
@jacekkolasa please take a look

**Comment by jacekkolasa** [comment] 2020-08-24 10:30
closing, the problem is not relevant now, with the new dashboard

**Closed by jacekkolasa** 2020-08-24 10:30 UTC
Labels: area/web, bug, priority/medium
