### ISSUE TITLE
Adding additional tags - I'd like to create a tag in netdata that allows me to select individual cpus when l use the data later with grafana. I can't seem to create a tag that is associated with cpus on an individual socket.

### ISSUE THREAD

**Issue by springerst94** [netdata/netdata#4561] opened 2018-11-05 13:29 UTC

**Comment by l2isbad** [comment] 2018-11-05 15:06
yo @springerst94 
please fix title

**Comment by cakrit** [comment] 2018-12-16 17:32
This is essentially a duplicate of #2690, as tags will not be implemented only for backends.

**Closed by cakrit** 2018-12-16 17:32 UTC
Labels: area/backends, area/daemon, duplicate, feature request, question
