### ISSUE TITLE
Error when deleting nodes from My nodes menu

### ISSUE THREAD

**Issue by joelhans** [netdata/netdata#6876] opened 2019-09-17 16:51 UTC
##### Bug report summary

It seems like sometimes nodes aren't deleted and removed from a user's **My nodes** menu and Nodes View even after explicitly deleting them via the **My nodes** menu.

Here's what I've been trying:

I click on the trash can/delete icon for a node that's registered in the **My nodes** menu.

![image](https://user-images.githubusercontent.com/1153921/65061729-63a5a080-d92f-11e9-9639-a6bf69662527.png)

I then click on **delete it** in the modal that appears.

![image](https://user-images.githubusercontent.com/1153921/65061839-9a7bb680-d92f-11e9-9a6b-dd1c7f0f0660.png)

Nothing happens. Even after a refresh, and a log out/back in, the node that was deleted still shows in the **My nodes** menu and in the Nodes View.

There's some console output on Firefox 69, beginning from the moment I click on the **delete it** button:

```
ERROR 412: Netdata registry DELETE failed: https://registry.my-netdata.io dashboard.js:602:13
Received error from registry null main.js:1059:37
ACCESS *** *** dashboard.js:10009:17
Checking if sync is needed. 
Array [ {…} ]
main.js:5060:13
Rendering my-netdata menu from netdata.cloud 
Array(11) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
```

##### OS / Environment

Linux/Fedora 30

##### Netdata version (ouput of `netdata -V`)

v1.17.1

##### Component Name

web/cloud

##### Steps To Reproduce

1. Log in to Netdata Cloud account with >1 node associated with it
2. Click on the delete icon beneath any of the nodes
3. Click on the **delete it** button in the modal window.
4. Check console output to see if error appeared
5. Refresh or log out/in to see if node was deleted properly

##### Expected behavior

I expect the node to be removed from the **My nodes** menu _and_ the Nodes View after requesting deletion.

**Comment by cakrit** [comment] 2019-09-18 08:06
Don't worry too much about the error deleting from the netdata registry, the important thing is the deletion from netdata.cloud. 

Case 1, deleting node with a `/` at the end?
```
Request URL: https://netdata.cloud/api/v1/accounts/2f51cd5c-dd10-423f-87fc-53bf7d740e58/agents/87cebdd0-3d87-11e6-bc3e-040117f2a301/url?value=http%3A%2F%2Fbangalore.netdata.rocks%2F
Request Method: DELETE
Status Code: 200 
Remote Address: [2001:4860:4802:34::15]:443
Referrer Policy: no-referrer-when-downgrade
```

Response: `{"result":{"count":1}}`

But the node is still there.

Case 2: 
```
Request URL: https://netdata.cloud/api/v1/accounts/2f51cd5c-dd10-423f-87fc-53bf7d740e58/agents/2314aa54-d892-11e9-8c43-0242ac110002/url?value=https%3A%2F%2Fmaster-ypajs.squash.io
Request Method: DELETE
Status Code: 422 
Remote Address: [2001:4860:4802:34::15]:443
Referrer Policy: no-referrer-when-downgrade
```


Went on the console view to see what the delete from there would do.

Bug 1:
![Screenshot from 2019-09-18 09-56-15](https://user-images.githubusercontent.com/43294513/65129248-2f97b180-d9fb-11e9-80ce-5603b22a577c.png)

Really bad. Why did we keep an agent with no URLs?

Bug 2:

We lost the delete button we had next to the URLs.

![Screenshot from 2019-09-18 09-59-57](https://user-images.githubusercontent.com/43294513/65129563-d7ad7a80-d9fb-11e9-9618-12e5d49589d0.png)

Doing some more tests, but this is now top priority.

**Comment by syedomair** [comment] 2019-09-18 08:14
I am looking into it.

**Comment by cakrit** [comment] 2019-09-18 08:17
Regarding Case 1, here's Bug 3:
- When trying to delete a URL with a `/` at the end, netdata.cloud apparently strips the `/` and tries to delete a URL without the `/`:

i.e. Clicking delete on this:
![Screenshot from 2019-09-18 10-10-03](https://user-images.githubusercontent.com/43294513/65130293-6d95d500-d9fd-11e9-8d35-5ba154d8a8dc.png)

ends up with this:
![Screenshot from 2019-09-18 10-12-12](https://user-images.githubusercontent.com/43294513/65130321-74244c80-d9fd-11e9-8a3f-22fa8e56a19f.png)

The URL without the `/` is what was removed

**Comment by cakrit** [comment] 2019-09-18 08:40
The delete from the nodes view seems to be a different method 

```
https://netdata.cloud/api/v1/agents/7b2c4e75-f6e8-35e0-8e67-05dbdb9dcb8e/urls/http://netdata.k8s.local/host/gke-standard-cluster-2-default-pool-86353fdd-t45s/

Request URL: https://netdata.cloud/api/v1/agents/7b2c4e75-f6e8-35e0-8e67-05dbdb9dcb8e/urls/http://netdata.k8s.local/host/gke-standard-cluster-2-default-pool-86353fdd-t45s/
Request Method: DELETE
Status Code: 301 
Remote Address: [2001:4860:4802:36::15]:443
Referrer Policy: no-referrer-when-downgrade
```

I tried with bangalore in the nodes view. Clicked delete once and I saw 6 (!) requests, none with `200` response, but at least it deleted the URL:

![Screenshot from 2019-09-18 10-34-34](https://user-images.githubusercontent.com/43294513/65132098-aedbb400-da00-11e9-95f7-579813f01570.png)

**Comment by VLegakis** [comment] 2019-09-18 08:55
So on the Nodes View (cloud console) the delete button is making a call to:
const response = await this.http<Agent>(
            "DELETE",
            `${this.v1}/accounts/${accountID}/agents/${agentID}/url?value=${url}`
        )
Perhaps the Dashboard should do the same?

**Comment by cakrit** [comment] 2019-09-18 09:01
I see the `agentID` in the list of agents returned, so it's possible. What's the difference between the two methods?

**Comment by jacekkolasa** [comment] 2019-09-18 09:03
@syedomair @fracasula @nicolasparada do you know which endpoint should be used in this case? If they are used to the same thing, perhaps we shouldn't have both of them. Should i use the same endpoint in Agent Dashboard as Cloud does?

Anyway, it's interesting to know what happened, because the corresponding Agent Dashboard code haven't been touched for a long time

**Comment by VLegakis** [comment] 2019-09-18 09:32
Since this part of the dashboard has not been touched for a long time I assume it maybe handling the deletion from the old "registry". So may that be that we need to handle 2 calls? One for the old registry and one for the cloud? Just making assumptions here. Let's see what the BE guys have to say.

**Comment by syedomair** [comment] 2019-09-18 09:42
Cloud: DELETE /agents/:agent_id/urls/:url
https://github.com/netdata/cloud-frontend/blob/release-mvp1/pkg/account/accountagent/transport.go#L23

Dashboard: DELETE /accounts/:account_id/agents/:agent_id/url
https://github.com/netdata/cloud-frontend/blob/release-mvp1/pkg/account/accountagent/transport.go#L30

Both URLs are calling the same function `RemoveURLs`  therefore both are same. 
https://github.com/netdata/cloud-frontend/blob/release-mvp1/pkg/account/accountagent/transport.go#L90
https://github.com/netdata/cloud-frontend/blob/release-mvp1/pkg/account/accountagent/transport.go#L172

**Comment by jacekkolasa** [comment] 2019-09-18 10:14
i cannot do DELETE also in the cloud. i have 2 urls:
```
http://frankfurt.my-netdata.io/ 
http://frankfurt.my-netdata.io 
```
and i'm not able to delete any of them. after the delete, sometimes i see that one is gone, but when i refresh, i see the same situation. For each deletion there are 6 calls made (and i'm not talking about pre-flight OPTIONS call), 4 result with 301 and 2 with 404

**Comment by cakrit** [comment] 2019-09-18 10:20
> Both URLs are calling the same function `RemoveURLs` therefore both are same.

Well, not quite. The console one does `url := r.URL.Query().Get("value")` the cloud one does `url := servemux.Value(r, "url")`

So can you please see what `r.URL.Query().Get("value")` returns for various URLs? Do note that the content of value is URL-encoded in the request from the agent.

FYI, I modified the call URL on my browser to what the cloud sends and I still can't get it to work. There's also the response part that's different between the two calls, one sends back a count, the other one something else.

**Comment by syedomair** [comment] 2019-09-18 10:34
I think the problem is on this line. 
https://github.com/netdata/cloud-frontend/blob/release-mvp1/pkg/account/accountagent/repository_firestore.go#L196
Somehow firestore is not updating the record.

**Comment by nicolasparada** [comment] 2019-09-20 12:46
OK. For the back-end API, these are the endpoints:

To delete an agent URL:
```
DELETE /api/v1/agents/{agentID}/urls?urls={jsonArrayOfURLs}
```

This returns `204 No Content`.
And agent cannot have zero URLs so you can get a 422 error back:
```json
{"error": "zero agent URLs"}
```

In that case you can ask the user to delete the agent:
```
DELETE /api/v1/agents/{agentID}
```

As well, this returns `204 No Content`.

---

We need to deploy.

**Comment by nicolasparada** [comment] 2019-09-20 13:16
At the back-end we introduced this zero URLs check at the account refactor.
But before, there was no validation. So you could remove all URLs from an agent, which is wrong, but then at the front-end is this check: https://github.com/netdata/netdata/blob/c6819cd535b3699676099cfe46dfa8c10e289fa6/web/gui/main.js#L4639-L4641
Which checks for agent URLs length to mark an agent as "invalid" so it was filtered out from the list. Like it was deleted.

Now it's different. To delete an agent you must do it explicitly. This functionality is not there in agent `main.js`. Only at Cloud (tho it's buggy at mvp1).

**Comment by cakrit** [comment] 2019-09-20 13:33
So you're saying that we MUST also fix main.js now?

**Comment by jacekkolasa** [comment] 2019-09-20 13:44
@nicolasparada but please confirm that you'll support "zero URLs" agents for backwards compatibility, right?

**Comment by nicolasparada** [comment] 2019-09-20 14:50
Supporting agents with no URLs would mean removing the validation? Then, no.

**Comment by jacekkolasa** [comment] 2019-09-20 18:13
Do you mean that users with old Agent Dashboard will not be able to completely remove server from the list? I think we cannot do this.

**Comment by nicolasparada** [comment] 2019-09-20 21:50
Well, there is no backward compatible way. They were not really removing the agents. It was a bug.

**Comment by cakrit** [comment] 2019-09-22 10:58
Why don't you remove the agent when the last URL is removed? What's the point of keeping it without a URL?

**Comment by cakrit** [comment] 2019-09-23 11:58
The fix doesn't work as is. The last URL can't be deleted, the message received is "Sorry, this command was rejected by netdata.cloud!". Please allow deletion of the last URL and trigger deletion of the agent as well. Only then can we close this.

**Comment by Z-Zen** [comment] 2019-09-24 12:36
I agree, I am also having the same issue, the nodes are added and I can't delete them.

**Comment by cakrit** [comment] 2020-02-10 17:58
I believe we've fixed this and forgot to close the issue. We're changing the entire cloud implementation  very soon, so we'll ensure deletion works properly during QA.

**Closed by cakrit** 2020-02-10 17:58 UTC
Labels: bug, priority/high
