### ISSUE TITLE
[Bug]: false positives on mysql/galera cluster size

### ISSUE THREAD

**Issue by ekexcello** [netdata/netdata#13427] opened 2022-07-23 14:55 UTC
### Bug description

Mysql mysql.galera_cluster_size has false-positive status and is marked "resolved" when it should be critical.

For example, on 2-node cluster that runs two nodes for long time, alert is always present:

```
mysql_Galera.galera_cluster_size
mysql galera cluster size: 2 nodes.
 cluster size has changed
```

Even more strange point, when one of the nodes has problems and cluster size is reduced, a "resloved" notification is sent (like `recovered, mysql_Galera.galera_cluster_size (galera), mysql galera cluster size (was warning for 2 days and 10 hours)` ) meaning that cluster in fact lost 1 node and is running single node now. Once problem is resolved, a notification of `needs attention, mysql_Galera.galera_cluster_size (galera), mysql galera cluster size = 2 nodes` is sent instead of real recovery.

In addition, test cluster running single node - always has alert of "cluster size has changed".

The alert configuration was created back in 2019 and was not modified since that time (file `/usr/lib64/netdata/conf.d/health.d/mysql.conf` ) :

```
# galera cluster size

 template: mysql_galera_cluster_size_max_2m
       on: mysql.galera_cluster_size
    class: Utilization
     type: Database
component: MySQL
   lookup: max -2m absolute
    units: nodes
    every: 10s
     info: maximum galera cluster size in the last 2 minutes
       to: dba

 template: mysql_galera_cluster_size
       on: mysql.galera_cluster_size
    class: Utilization
     type: Database
component: MySQL
     calc: $nodes
    units: nodes
    every: 10s
     warn: $this > $mysql_galera_cluster_size_max_2m
     crit: $this < $mysql_galera_cluster_size_max_2m
    delay: up 20s down 5m multiplier 1.5 max 1h
     info: current galera cluster size, compared to the maximum size in the last 2 minutes
       to: dba
```

Just for the case, it seems that something is wrong with alert processing logic. For example, another alert, about redis, is also always present in the form of

```
redis_keydb_local.bgsave_health
 redis bgsave broken: ok
states if redis bgsave is working
```

and zero shown as a value.
That check is defined by default in `/usr/lib64/netdata/conf.d/health.d/redis.conf`  as

```
 template: redis_bgsave_broken
 families: *
       on: redis.bgsave_health
    class: Errors
     type: KV Storage
component: Redis
    every: 10s
     crit: $rdb_last_bgsave_status != 0
    units: ok/failed
     info: status of the last RDB save operation (0: ok, 1: error)
    delay: down 5m multiplier 1.5 max 1h
       to: dba
```
And disappears when `crit: $rdb_last_bgsave_status != 0` is replaced with `crit: $rdb_last_bgsave_status > 0`

### Expected behavior

Alert should appear only when cluster size has changed or problem is present

### Steps to reproduce

1. Configure galera cluster
2. Install netdata
3. Configure galera monitoring with netdata.

### Installation method

other

### System info

```shell
Linux 5.18.10-gentoo #1 SMP PREEMPT_DYNAMIC Fri Jul 8 18:48:37 CEST 2022 x86_64 AMD Opteron(tm) Processor 6376 AuthenticAMD GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.8
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:VERSION_ID="2.8"
```

### Netdata build info

```shell
Version: netdata v1.35.1
Configure options:  '--prefix=/usr' '--build=x86_64-pc-linux-gnu' '--host=x86_64-pc-linux-gnu' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share' '--sysconfdir=/etc' '--localstatedir=/var/lib' '--datarootdir=/usr/share' '--disable-dependency-tracking' '--disable-silent-rules' '--docdir=/usr/share/doc/netdata-1.35.1' '--htmldir=/usr/share/doc/netdata-1.35.1/html' '--libdir=/usr/lib64' '--localstatedir=/var' '--with-user=netdata' '--without-bundled-protobuf' '--disable-cloud' '--enable-jsonc' '--disable-plugin-cups' '--enable-dbengine' '--enable-plugin-nfacct' '--disable-plugin-freeipmi' '--disable-exporting-kinesis' '--enable-lto' '--disable-exporting-mongodb' '--disable-exporting-prometheus-remote-write' '--disable-plugin-xenstat' '--enable-x86-sse' '--with-zlib' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=x86_64-pc-linux-gnu' 'CFLAGS=-O2 -pipe' 'LDFLAGS=-Wl,-O1 -Wl,--as-needed' 'CXXFLAGS=-O2 -pipe' 'PKG_CONFIG_PATH=/var/tmp/portage/net-analyzer/netdata-1.35.1/temp/python3.10/pkgconfig'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO (by user request)
    ACLK Next Generation:       NO
    ACLK-NG New Cloud Protocol: NO
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by ilyam8** [comment] 2022-07-23 18:13
Hi, @ekexcello. The problem with Redis alarms is fixed in the latest master (https://github.com/netdata/netdata/pull/13296).

---

Did you check the alarms values?

- `mysql_galera_cluster_size_max_2m` is the `max` values of `wsrep_cluster_size` (nodes) in the last 2 minutes.
- `mysql_galera_cluster_size` is the current value of `wsrep_cluster_size` (nodes).


I checked the config and it is expected that after 2 minutes 
- `mysql_galera_cluster_size_max_2m` becomes 1
- 1 => 2 transitions warning instead of recovery

https://github.com/netdata/netdata/blob/94040523c73c0f515ea3d682ab0a20c11400a43c/health/health.d/mysql.conf#L123-L131

**Comment by ekexcello** [comment] 2022-07-23 19:03
Hello @ilyam8 

Yes, it should work in the way you wrote, for example: server is started and joined the cluster. This triggers the alert as current value is bigger than maximum of last 2 minutes. In 2 minutes + hysteresis time, the alert might be gone as current number of nodes (`mysql.galera_cluster_size`), that is 2, becomes equal to `mysql_galera_cluster_size_max_2m` that is also 2 as cluster size didn't change for more than 2 minutes. But it doesn't. The warning remains for several days, with the value of 2 nodes on the cluster having 2 nodes. And it suddenly turns into "recovered" in case one of the node disconnects, while it is expected that it might send 'critial' alarm meaning that one of cluster member node disconnected or failed.

**Comment by ilyam8** [comment] 2022-07-23 19:34
What is your setup?

- parent/child or standalone?
- number of mysql jobs? 1 or more?

**Comment by ekexcello** [comment] 2022-07-23 20:07
We have standalone setup and single mysql job. Used to be two, situation was the same.

**Comment by ilyam8** [comment] 2022-07-23 20:42
> The warning remains for several days, with the value of 2 nodes on the cluster having 2 nodes.

So the value of `mysql_galera_cluster_size_max_2m` was 1? Did you check it when the alarm was raised? Was it 1 or `-`?

**Comment by ekexcello** [comment] 2022-07-23 20:48
Checked it, on 2-node cluster mysql_galera_cluster_size_max_2m is 2 and in same time alarm is in "warning" state.

**Comment by ilyam8** [comment] 2022-07-25 14:08
Can you send me a [snapshot](https://learn.netdata.cloud/docs/dashboard/import-export-print-snapshot#export-a-snapshot) when the alarm is active? (ilya at netdata.cloud)

**Comment by donaldsteele** [comment] 2022-08-21 20:05
I am experiencing this issue as well. I have a percona 8 cluster setup and am running the latest build of the netdata client.

**Comment by ilyam8** [comment] 2022-08-23 13:13
@donaldsteele do you have more than one Percona instances on a host?

**Comment by ilyam8** [comment] 2022-08-23 13:40
I plan to set up 3 nodes Galera cluster and see if I can reproduce the problem.

**Comment by donaldsteele** [comment] 2022-08-23 14:29
@ilyam8 only 1 install / instance per server in my configuration.

**Comment by ilyam8** [comment] 2022-08-23 14:56
I think all the timing _issues_ come from my not understanding the lookup absolute option 🤷‍♂️ 

https://github.com/netdata/netdata/blob/575986a692003638f09c975da847062637b915f4/health/health.d/mysql.conf#L112-L117

We can change the line to `max -2m at -1m unaligned`

> max value starting 3 mins ago and up to 1 min ago (last 2 mins starting -1 min ago)

- current < max: stays 3 minutes + up to 10 seconds.
- current > max: stays 1 minute + up to 10 seconds.

**Comment by ilyam8** [comment] 2022-08-23 15:32
I adjusted the alarm to make time in warn/crit state more predictable in #13563. The important part: an alarm state != sending notifications.

The alarm has the following line:

https://github.com/netdata/netdata/blob/575986a692003638f09c975da847062637b915f4/health/health.d/mysql.conf#L133

See [alarm-line-delay](https://learn.netdata.cloud/docs/agent/health/reference#alarm-line-delay) for details. So delaying sending notifications is expected and can be up to 1 hr in cases when the alarm switches from CLEAR to WARN/CRIT and back several times.

I think the confusion is because of the `delay`. I tried to reproduce the problem, but couldn't - the alarm switches from one state to another according to the warn/crit triggers.

**Closed by ilyam8** 2022-08-23 15:32 UTC
Labels: bug, area/health, Cannot reproduce, collectors/go.d

**Comment by ilyam8** [comment] 2022-08-23 15:34
Despite the issue being closed, I am happy to continue discussion/trying to reproduce the issue (can follow a step-by-step guide - fortunately, it is easy to set up Galera cluster using Docker).

**Comment by ekexcello** [comment] 2022-09-02 23:08
Hello @ilyam8 
Sorry for the long delay. 
Unfortunately, attempt to adjust health check definitions in the way you wrote above are not enough.
Now we run go.d plugin 0.37.2 and netdata 1.36.1.
After netdata restart we have following values displayed on 'Raised Alarms' window:

mysql galera cluster state --
mysql galera cluster status --

Mean, values are "-" (that is NAN). However, on charts you the values collected are displayed.
But values displayed for node state and status are also displayed incorrectly: node real state is "Primary/Synced" that is "0/4" in numeric form. But charts display 'Cluster Component State (mysql_Galera_main.galera_cluster_state) = 1" and "Cluster Component Status (mysql_Galera_main.galera_cluster_status) = 1" that is "non-Primary/Joining" and is not true, for sure.

I reconfigured netdata to provide only galera-related and minimum system information for now, so finally can provide a snapshot. Could you please let me know how to share it with you?

**Comment by ilyam8** [comment] 2022-09-03 11:00
Encoding the state as an integer was wrong, I changed it to a dimension per state. The value is either 1 (in the state) or 0. See [new charts](https://github.com/netdata/go.d.plugin/blob/01922de1dd4429f5bc112c0444093f35a3811692/modules/mysql/charts.go#L751-L779). I did test the alarms (see [set up Galera using Docker](https://github.com/netdata/netdata/pull/13563)).
