### ISSUE TITLE
Badges showing current number of normal/warning/critical alarms

### ISSUE THREAD

**Issue by nodiscc** [netdata/netdata#6592] opened 2019-08-04 19:22 UTC
##### Feature idea summary

Hi, I would like to generate SVG badges showing the current number of normal/warning/critical alarms for a host. Once embedded on any plain HTML page, they would look like that (sorry for my poor mockup skills):

- host1: ![badge-noraml](https://user-images.githubusercontent.com/3950390/62428026-92ebaf80-b6eb-11e9-9439-fe44e51ac02f.png) ![badge-warn-0](https://user-images.githubusercontent.com/3950390/62428038-e2ca7680-b6eb-11e9-8088-02403b4b81b5.png)  ![badge-crit-0](https://user-images.githubusercontent.com/3950390/62428039-e52cd080-b6eb-11e9-8f72-ee0d0489f2e2.png)
- host2: ![badge-noraml](https://user-images.githubusercontent.com/3950390/62428026-92ebaf80-b6eb-11e9-9439-fe44e51ac02f.png)  ![badge-warn-on](https://user-images.githubusercontent.com/3950390/62428042-fb3a9100-b6eb-11e9-996d-10175485ab7a.png) ![badge-crit-0](https://user-images.githubusercontent.com/3950390/62428039-e52cd080-b6eb-11e9-8f72-ee0d0489f2e2.png)
- host3: ![badge-noraml](https://user-images.githubusercontent.com/3950390/62428026-92ebaf80-b6eb-11e9-9439-fe44e51ac02f.png)  ![badge-warn-0](https://user-images.githubusercontent.com/3950390/62428044-0f7e8e00-b6ec-11e9-85fd-e526073cbf09.png)  ![badge-crit-on](https://user-images.githubusercontent.com/3950390/62428047-13121500-b6ec-11e9-8730-dca736307121.png)

This information is available from the API at `api/v1/info` (`alarms.normal`, `alarms.warning`, `alarms.critical` return the number of alarms in each state). However the `badge.svg` API endpoint requires a `chart` parameter and there is no chart for the number of alarms over time as far as I know.

Would you be interested in adding badges showing the number of alarms in each state?

Or is there a workaround? (I thought about creating a module that queries the `info/alarms.*` API endpoint, creates charts for these numbers, then use the badge API to return badges for these charts... I'm not sure this is the best way to go)

##### Expected behavior

Querying an URL such as `https://registry.my-netdata.io/api/v1/badge.svg?info=alarms.critical` should return an SVG badge with the number of current critical alarms - colored gray if the number of alarms is 0, red if > 0.

Similar badges should exist for active warning alarms (colored orange if > 0), and for alarms in the normal state (badge always green).

**Comment by ilyam8** [comment] 2019-08-05 10:01
@nodiscc have you considered using `netdata.cloud` (`Nodes View`)? There you can find exactly what you want - number of alarms in warning/crit state for every node.

**Comment by cakrit** [comment] 2019-08-13 17:48
This is a duplicate of #6536, with the PR to implement the API call being #6554. 
I like the idea of showing not raised alarms as well, let's add it to that PR @alpes214

As soon as the API call to get the data is ready, we can move to the second phase and provide a new badge.svg call that utilizes the same function.

**Comment by nodiscc** [comment] 2019-08-16 17:28
> #6554

@cakrit Thank you, this is what I am looking for.

I have considered netdata.cloud which is very good but overkill for my needs at the moment (and introduces a dependency to a 3rd party service - some of my test networks don't have Internet access). At my scale a simple static dashboard is the way to go. If it grows beyond that I will consider setting up streaming and centralize alarms, or use the cloud service.

Thanks again

**Comment by nodiscc** [comment] 2020-08-07 11:09
Hi, I believe I closed this issue in error. Necessary API endpoints were added in https://github.com/netdata/netdata/pull/6554, however it is still not (?) possible to show badges with the number of alarms as I described

**Comment by ilyam8** [comment] 2020-08-07 11:14
@nodiscc i believe we have aggregated active alarms numbers per severity in the cloud, it is not you want but worth to mention.

**Comment by cakrit** [comment] 2020-08-10 08:47
How about converting the response to be compatible with https://shields.io/endpoint? Then people can use shields.io.

**Comment by nodiscc** [comment] 2020-12-07 18:05
> Then people can use shields.io.

I would expect this feature to not depend on a third-party service

**Comment by ilyam8** [comment] 2021-07-28 14:47
Closing this feature request. If you are still interested in it, consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).

**Closed by ilyam8** 2021-07-28 14:47 UTC
Labels: feature request, needs triage
