### ISSUE TITLE
QEMU metrics incorrect and crashing dashboard

### ISSUE THREAD

**Issue by youreunwelcome** [netdata/netdata#9254] opened 2020-06-02 17:24 UTC
##### Bug report summary

Netdata appears to be grabbing all data for both LXC containers and the one KVM VM i have, and putting them all under a single "qemu" section. It lists all virtual nics, as well as all vcpus, and when i go to that section it updates for about 5 seconds before completely crashing whatever tab its running in, and occasionally the entire browser. 
![Capture](https://user-images.githubusercontent.com/16448983/83549995-63e8ca80-a4c3-11ea-9ec6-4af42839a9b9.PNG)

##### OS / Environment
Proxmox 6.1-8

```
Linux genvm01 5.3.18-3-pve #1 SMP PVE 5.3.18-3 (Tue, 17 Mar 2020 16:33:19 +0100) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

netdata v1.22.1-184-nightly
 

##### Component Name

plugin:cgroup i think

##### Steps To Reproduce

1. Create VM in proxmox
2. Install netdata

##### Expected behavior

Qemu section would have the correct VM name, and have only data about that VM. 

I'd be glad if I could turn off metrics for KVM machines and still get info for containers, but if i have to I'd settle for just turning off metrics for both if this isnt a simple fix.

**Comment by ilyam8** [comment] 2020-06-02 18:58
@underhood since you [are working](https://github.com/netdata/netdata/pull/9249) with cgroups code i hope you can help with the issue, please take a look

**Comment by ilyam8** [comment] 2020-06-02 18:59
> completely crashing whatever tab its running in, and occasionally the entire browser.

@jacekkolasa

**Comment by cakrit** [comment] 2020-08-10 14:23
@youreunwelcome I expect that the issue is caused by Netdata's attempt to show a gauge chart for each one of the 48 cpus you have there. Can you please look at 
https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info.js#L1711
through 
https://github.com/netdata/netdata/blob/master/web/gui/dashboard_info.js#L1835
and start commenting out sections until you stop having problems?  The first two tell Netdata to draw cpu limit and cpu gauges, depending on a condition I'm not really clear on. That file is usually under `/usr/share/netdata/web`, but you can check where exactly it is on your system by looking at the value of  the `web files directory` you see when you input in your browser your netdata's URL, followed by `/netdata.conf`. e.g. http://localhost:19999/netdata.conf.

If you can get the dashboard to behave by leaving out some of those entries and not displaying those gauge charts, then you can persist that dashboard by following the instructions at https://learn.netdata.cloud/docs/agent/web/gui#customizing-the-standard-dashboard

**Comment by cakrit** [comment] 2020-08-10 14:25
Of course we'll need to fix our default dashboard as well. @vlvkobal is it safer to just leave out the section on the CPUs? What do you think?

**Comment by vlvkobal** [comment] 2020-08-10 15:48
> the issue is caused by Netdata's attempt to show a gauge chart for each one of the 48 cpus

We also probably have problems with the number of dimensions our dashboard is able to display flawlessly. 

> putting them all under a single "qemu" section

It looks like another bug I noticed today while I was working on LXC bugs. All containers with names `lxc.payload.*` were aggregated on a single menu item `lxc`.

@youreunwelcome what version of LXC do you use? Is it 4.x?

> is it safer to just leave out the section on the CPUs?

I don't think that 48 charts or dimensions should be considered as a critical number for the dashboard performance. It would be better to find out what's wrong with the UI part.

**Comment by ilyam8** [comment] 2020-08-10 19:52
> I don't think that 48 charts or dimensions should be considered as a critical number for the dashboard performance.

48 is not critical, i confirm it 😄  I tested it working on prometheus collector.

**Comment by ilyam8** [comment] 2021-04-12 15:58
> Netdata appears to be grabbing all data for both LXC containers and the one KVM VM i have, and putting them all under a single "qemu" section. 

This is the case, indeed.

- It happens for all charts that have id's with dots (`.`).
- The problem affects only streaming. They are separate charts on the child dashboard, but got _squashed_ on the parent.

Child:

<img width="199" alt="Screenshot 2021-04-12 at 18 53 39" src="https://user-images.githubusercontent.com/22274335/114424008-66767f00-9bc0-11eb-9eae-74b08471218f.png">


Parent:
<img width="1343" alt="Screenshot 2021-04-12 at 18 54 06" src="https://user-images.githubusercontent.com/22274335/114424084-7726f500-9bc0-11eb-9cdd-e92fa2a39f8f.png">

---

Child:


```json
		"cgroup_qemu.slice_101.scope.cpu_limit": 		{
			"id": "cgroup_qemu.slice_101.scope.cpu_limit",
			"name": "cgroup_qemu.slice_101.scope.cpu_limit",
			"type": "cgroup_qemu.slice_101.scope",
```


Parent:

```json
		"cgroup_qemu.slice_101.scope.cpu_limit": 		{
			"id": "cgroup_qemu.slice_101.scope.cpu_limit",
			"name": "cgroup_qemu.slice_101.scope.cpu_limit",
			"type": "cgroup_qemu",
```


There is no way to detect correct `type` during streaming if there are several `.`. 

See [External plugins API CHART definition](https://learn.netdata.cloud/docs/agent/collectors/plugins.d#chart):

> type.id

> uniquely identifies the chart, this is what will be needed to add values to the chart
the type part controls the menu the charts will appear in

**Comment by ilyam8** [comment] 2021-04-12 15:59
In case of qemu it happens when name resolution fails, because we don't add `netdata` user to `www-data` group by default.

> 2021-04-12 13:05:24: cgroup-name.sh: ERROR: proxmox config file missing /etc/pve/qemu-server/100.conf or netdata does not have read access.  Please ensure netdata is a member of www-data group.

**Comment by ilyam8** [comment] 2021-04-12 16:10
How can we _fix_ it:

- [add `netdata` to the `www-data` group](https://github.com/netdata/netdata/blob/f39406c9b692aa17e1d7842feba13fe01e5a3d71/netdata-installer.sh#L1113). Doesn't really fix the problem, but fixes qemu containers name resolution when netdata installed directly on the host.
- _sanitize_ containers names in the cgroups collector. This is ~a breaking change. Affects all setups (the issue exists for parent/child setups, only for parent nodes).
- extend external plugins API? @stelfrag

**Comment by ilyam8** [comment] 2021-05-11 11:11
Fixed in https://github.com/netdata/netdata/pull/11050

**Closed by ilyam8** 2021-05-11 11:11 UTC
Labels: area/collectors, bug, data-collection-mteam, needs triage
