### ISSUE TITLE
Netdata não compila no FreeBSD após Nightly Netdata-v1.22.1-96

### ISSUE THREAD

**Issue by thoggs** [netdata/netdata#9143] opened 2020-05-23 19:03 UTC
Hello,
Today I noticed that starting with version v1.22.1-96 of Netdata, I can't compile using the script netdata-installer.sh; I had already reported problems in relation to dependencies (#9095), but this time I cannot say with the same precision.

Due to this problem, I ended up changing the installation method to FreeBSD in the installation document, which is still an unapproved PR #9116 (for obvious reasons).

The test below was performed in a virtualization environment, with a clean installation of FreeBSD, without any other noise:

**OS: FreeBSD 12.1 RELEASE - No lib32 installed
Netdata: v1.22.1-96 @ 108**

![Captura de Tela 2020-05-23 às 14 30 00](https://user-images.githubusercontent.com/43221193/82738579-d660ea00-9d0e-11ea-89bc-9e27b0f6940b.png)

![Captura de Tela 2020-05-23 às 15 07 50](https://user-images.githubusercontent.com/43221193/82738582-dc56cb00-9d0e-11ea-92c2-5caaee4e1d7b.png)

![Captura de Tela 2020-05-23 às 15 54 20](https://user-images.githubusercontent.com/43221193/82738585-df51bb80-9d0e-11ea-9733-c1101946c5d9.png)

**Comment by prologic** [comment] 2020-05-25 04:22
Are you working out of.a Git tree?

If so can you rebase to HEAD@master and try again?

**Comment by thoggs** [comment] 2020-05-26 05:00
> Are you working out of.a Git tree?
> 
> If so can you rebase to HEAD@master and try again?

Yes, without any problem, I will do and post the result here...

**Comment by Ferroin** [comment] 2020-05-26 12:10
Looks like the same thing as #9163.

**Comment by amoss** [comment] 2020-05-26 12:29
It is the same problem, the work-around should work until we fix the installer.

**Comment by prologic** [comment] 2020-06-24 03:23
Closing as dupe of #9163

**Closed by prologic** 2020-06-24 03:23 UTC
Labels: bug, duplicate, os/bsd
