### ISSUE TITLE
About activating Ceph monitoring

### ISSUE THREAD

**Issue by fantastic2085** [netdata/netdata#10272] opened 2020-11-21 02:51 UTC
version：
![image](https://user-images.githubusercontent.com/4116773/99865699-8643e100-2be6-11eb-8600-896401bcaa68.png)

After executing this command  **./edit-config python.d/ceph.conf**, see the following figure 
![image](https://user-images.githubusercontent.com/4116773/99865737-db7ff280-2be6-11eb-9e65-72961bd2724c.png)

Ceph has been installed, as shown below:
![image](https://user-images.githubusercontent.com/4116773/99865757-ffdbcf00-2be6-11eb-95a2-9dc26c4b6142.png)

The operating system and kernel versions are as follows:
![image](https://user-images.githubusercontent.com/4116773/99865785-23067e80-2be7-11eb-8ef4-fc53e6109de8.png)

The problem is: NetData Dashboard did not create new chart, which should be ceph.The following:
![image](https://user-images.githubusercontent.com/4116773/99865842-7ed10780-2be7-11eb-9c4d-ef1b0e3eb129.png)

**Comment by ilyam8** [comment] 2020-11-21 17:11
Hi @fantastic2085 👋 

If there any problems with python collector, good first step is to try it in the debug mode, see https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin#how-to-debug-a-python-module

---

I see your configuration file has YAML syntax errors (it is likely you will see them in the debug mode).

It should be like

```yaml
cephcluster-ceph01:
  config_file: '/etc/ceph/ceph.conf'
  keyring_file: '/etc/ceph/ceph.client.admin.keyring'
  rados_id: 'admin'
```

**Comment by OdysLam** [comment] 2020-11-25 06:49
@ilyam8 another github issue that is more of a support request. I think it's best to start implementing the new policy. Thoughts?

**Comment by OdysLam** [comment] 2020-11-25 06:50
@fantastic2085 welcome to our community btw, we are going to sort everything out! We are sorry that you are experiencing this issue. :)

**Comment by ilyam8** [comment] 2020-11-25 07:38
Border between a support request/bug is not clear for a user. Something doesn't work so it is understandable to see it as a bug.

**Comment by OdysLam** [comment] 2020-11-25 07:40
That' s an interesting notion Ilya. Do you think we can improve the template so that it's more clear and save the user that extra step of opening an issue and then us closing it.

**Comment by ilyam8** [comment] 2021-09-01 12:42
The problem is invalid YAML syntax in the `ceph.conf`. Closing due to no response.

**Closed by ilyam8** 2021-09-01 12:42 UTC
Labels: bug, needs triage
