### ISSUE TITLE
nut collector (upsc) broken in Docker arm64 in v1.30

### ISSUE THREAD

**Issue by augustozanellato** [netdata/netdata#10903] opened 2021-04-04 14:18 UTC
##### Bug report summary

`upsc` is broken in Netdata Docker image on arch arm64 so UPS monitoring isn't possible.

##### OS / Environment

Docker image version: `82ad2e98a33eb19cecb946cf91b27c9f29a132925891d80f7384aeffe9227cd0` (latest image pushed to netdata/netdata:edge as of 04/04/2021 14:08 UTC), but issue is also present on `4f2de2df26a06c480f8e463dc5b04c1c1577d2b60cd6e558d38f7f761f198b0d` (v1.30.0)

```
Linux *snip* 5.10.14-v8+ #1401 SMP PREEMPT Mon Feb 8 14:31:24 GMT 2021 aarch64 GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version

```
Version: netdata v1.30.0-3-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws=externaldeps/libwebsockets' '--with-libJudy=externaldeps/libJudy' 'CFLAGS=' 'LDFLAGS='
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

##### Installation method

Docker image using docker-compose

##### Component Name

`packaging`

##### Steps To Reproduce

1. `docker run -d --name netdata_test netdata/netdata`
2. `docker exec -it netdata_test upsc`
3. `docker rm -f netdata_test`

##### Expected behavior

```
Error: invalid UPS definition.
Required format: upsname[@hostname[:port]]
```

##### Actual behavior

```
Error relocating /usr/lib/libupsclient.so.4: __select_time64: symbol not found
Error relocating /usr/lib/libupsclient.so.4: __gettimeofday_time64: symbol not found
Error relocating /usr/lib/libupsclient.so.4: __difftime64: symbol not found
Error relocating /usr/lib/libnspr4.so: __dlsym_time64: symbol not found
Error relocating /usr/lib/libnspr4.so: gettid: symbol not found
Error relocating /usr/lib/libnspr4.so: __select_time64: symbol not found
Error relocating /usr/lib/libnspr4.so: __pthread_cond_timedwait_time64: symbol not found
Error relocating /usr/lib/libnspr4.so: __gettimeofday_time64: symbol not found
Error relocating /usr/lib/libnspr4.so: __fstat_time64: symbol not found
Error relocating /usr/lib/libnspr4.so: __stat_time64: symbol not found
Error relocating /usr/lib/libnspr4.so: __localtime64_r: symbol not found
Error relocating /usr/lib/libnspr4.so: __mktime64: symbol not found
Error relocating /usr/lib/libnspr4.so: __clock_gettime64: symbol not found
Error relocating /usr/lib/libnspr4.so: __fstat_time64: symbol not found
Error relocating /usr/lib/libnspr4.so: __stat_time64: symbol not found
Error relocating /usr/bin/upsc: __select_time64: symbol not found
Error relocating /usr/bin/upsc: __gettimeofday_time64: symbol not found
Error relocating /usr/bin/upsc: __difftime64: symbol not found
```

**Comment by stelfrag** [comment] 2021-04-06 07:10
Hi @augustozanellato 

thank you for reporting this

**Comment by stelfrag** [comment] 2021-04-08 09:13
This is confirmed and it appears to have a different behavior in various minor versions of alpine 3.12.x

**Comment by kmlucy** [comment] 2021-06-08 02:05
Has there been any progress on this? I'm not able to upgrade to v1.30 with this bug.

**Comment by stelfrag** [comment] 2021-06-08 09:10
@Ferroin any idea on how to best handle this? Looks like alpine 3.12.7 is affected

```
bash-5.0# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.7
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
bash-5.0# upsc
Error relocating /usr/lib/libnspr4.so: gettid: symbol not found
bash-5.0#
```

**Comment by Ferroin** [comment] 2021-06-08 14:40
All versions of Alpine are affected, because the relevant packages are being pulled from the testing repo for Alpine Edge. NSPR appears to be broken _there_, and there is exactly nothing we can do about it.

**Comment by georgeok** [comment] 2021-09-30 10:42
It looks like if we update the [base and build images](https://github.com/netdata/helper-images) to `alpine 3.14`  the issue will be fixed. I've made a relevant [PR](https://github.com/netdata/helper-images/pull/140).

**Closed** 2021-12-17 17:34 UTC
Labels: bug, needs triage
