### ISSUE TITLE
[Bug]: ebpf.plugin -hardirq crashes with 'malloc(): invalid size (unsorted)'

### ISSUE THREAD

**Issue by Ukko-Ylijumala** [netdata/netdata#14487] opened 2023-02-09 16:23 UTC
### Bug description

`ebpf.plugin` crashes if hardirq program is enabled in `ebpf.d.conf`, or if being run with `-hardirq` parameter.

### Expected behavior

ebpf.plugin does not crash

### Steps to reproduce

1. run ebpf.plugin with '`hardirq = yes`' in /etc/netdata/ebpf.d.conf (or with `-hardirq` command line parameter)
2. observe a crash, malloc(): invalid size (unsorted)

### Installation method

from git

### System info

```shell
Linux <hostname> 5.17.0-1025-oem #26-Ubuntu SMP PREEMPT Wed Dec 7 12:41:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Version: netdata v1.38.0-43-g2ec714523
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -g' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO 
    ACLK:                       NO
    TLS Host Verification:      YES
    Machine Learning:           NO
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     YES
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Short backtrace from gdb:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140006663112256) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140006663112256) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140006663112256, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f55d89d8476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f55d89be7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f55d8a1f6f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f55d8b71b8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007f55d8a36d7c in malloc_printerr (str=str@entry=0x7f55d8b74be0 "malloc(): invalid size (unsorted)") at ./malloc/malloc.c:5664
#7  0x00007f55d8a3a15c in _int_malloc (av=av@entry=0x7f55c8000030, bytes=bytes@entry=72) at ./malloc/malloc.c:4002
#8  0x00007f55d8a3c679 in __libc_calloc (n=n@entry=1, elem_size=elem_size@entry=72) at ./malloc/malloc.c:3679
#9  0x0000555eeea33215 in callocz (nmemb=nmemb@entry=1, size=size@entry=72) at libnetdata/libnetdata.c:469
#10 0x0000555eeea05ce2 in hardirq_read_latency_map (mapfd=19) at collectors/ebpf.plugin/ebpf_hardirq.c:237
#11 hardirq_reader () at collectors/ebpf.plugin/ebpf_hardirq.c:308
#12 hardirq_collector (em=0x555eeeb6f680 <ebpf_modules+1760>) at collectors/ebpf.plugin/ebpf_hardirq.c:409
#13 ebpf_hardirq_thread (ptr=0x555eeeb6f680 <ebpf_modules+1760>) at collectors/ebpf.plugin/ebpf_hardirq.c:450
#14 0x0000555eeea44e1d in thread_start (ptr=<optimized out>) at libnetdata/threads/threads.c:206
#15 0x00007f55d8a2ab43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#16 0x00007f55d8abca00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

Full trace in gist:
https://gist.githubusercontent.com/Ukko-Ylijumala/7bc387f163fcaf0f5a40a97614269b41/raw/77d0ddd97e6497bf89500568481b489570c35ec2/gistfile1.txt

**Comment by ilyam8** [comment] 2023-02-09 16:30
Duplicate of #14406. There are quite a [few problems](https://github.com/netdata/netdata/issues/14406#issuecomment-1416200614) (hardirq is one of them).

**Closed by ilyam8** 2023-02-09 16:30 UTC
Labels: bug, needs triage, area/collectors, collectors/ebpf
