### ISSUE TITLE
Fails to execute on Raspberry Pi 4B

### ISSUE THREAD

**Issue by t0xic0der** [netdata/netdata#10748] opened 2021-03-10 17:47 UTC
##### Bug report summary
On running the Docker image on an aarch64 installation of a Raspberry Pi 4B - the following logs are generated

```
2021-03-10 17:39:59: netdata INFO  : MAIN : CONFIG: cannot load user config '/etc/netdata/netdata.conf'. Will try the stock version.
2021-03-10 17:39:59: netdata INFO  : MAIN : CONFIG: cannot load stock config '/usr/lib/netdata/conf.d/netdata.conf'. Running with internal defaults.
2021-03-10 17:39:59: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2021-03-10 17:39:59: netdata INFO  : MAIN : Found 0 legacy dbengines, setting multidb diskspace to 256MB
2021-03-10 17:39:59: netdata INFO  : MAIN : Created file '/var/lib/netdata/dbengine_multihost_size' to store the computed value
2021-03-10 17:39:59: netdata INFO  : MAIN : Using host prefix directory '/host'
2021-03-10 17:39:59: netdata INFO  : MAIN : SIGNAL: Enabling reaper
2021-03-10 17:39:59: netdata INFO  : MAIN : process tracking enabled.
2021-03-10 17:39:59: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1048576, max = 1048576
2021-03-10 17:39:59: netdata INFO  : MAIN : Adjusted my Out-Of-Memory (OOM) score from 0 to 1000.
2021-03-10 17:39:59: netdata ERROR : MAIN : Cannot adjust netdata scheduling policy to idle (5), with priority 0. Falling back to nice. (errno 38, Function not implemented)
2021-03-10 17:39:59: netdata ERROR : MAIN : Cannot get my current process scheduling policy. (errno 38, Function not implemented)
2021-03-10 17:39:59: netdata INFO  : MAIN : netdata started on pid 1.
2021-03-10 17:39:59: netdata FATAL : MAIN : Cannot create directory '/var/lib/netdata/registry'. # : Invalid argument

2021-03-10 17:39:59: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
2021-03-10 17:39:59: netdata INFO  : MAIN : EXIT: cleaning up the database...
2021-03-10 17:39:59: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
2021-03-10 17:39:59: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
```

##### OS / Environment
Arch Linux ARM (aarch64) 
Raspberry Pi 4B 4GB

To get this information, execute the following commands based on your operating system:
- uname -a; grep -Hv "^#" /etc/*release

```
Linux alarm 5.11.4-1-ARCH #1 SMP Sun Mar 7 23:46:10 UTC 2021 aarch64 GNU/Linux
/etc/os-release:NAME="Arch Linux ARM"
/etc/os-release:PRETTY_NAME="Arch Linux ARM"
/etc/os-release:ID=archarm
/etc/os-release:ID_LIKE=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:ANSI_COLOR="38;2;23;147;209"
/etc/os-release:HOME_URL="https://archlinuxarm.org/"
/etc/os-release:DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
/etc/os-release:SUPPORT_URL="https://archlinuxarm.org/forum"
/etc/os-release:BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
/etc/os-release:LOGO=archlinux
```
- uname -a; uname -K

```
Not applicable
```

- uname -a; sw_vers

```
Not applicable
```

##### Netdata version
v1.29.0

##### Component Name
Not applicable

##### Steps To Reproduce
Follow the instructions on README.md on a aarch64 Docker setup.

##### Expected behavior
It should run normally.

**Comment by OdysLam** [comment] 2021-03-11 14:28
Hey @t0xic0der and welcome to our community!

Can you share the Docker command that you used to run Netdata? Did you use the command that we have in our [documentation](https://learn.netdata.cloud/docs/agent/packaging/docker)?

**Comment by t0xic0der** [comment] 2021-03-11 14:36
Sure, @OdysLam.

The following is the output when `docker info` is executed.

```
[alarm@alarm ~]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 23
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.11.4-1-ARCH
 Operating System: Arch Linux ARM
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.697GiB
 Name: alarm
 ID: NW5L:XSDN:ONCL:D2PY:5YUI:K26X:IO6M:HNK4:CEYQ:SGYG:XOL6:RP3G
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: t0xic0der
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

and the following are the execution commands that I stored in an executable `netdata.sh`, they have been taken from the documentation.

```
#!/bin/bash

docker run -d --name=netdata \
  -p 19999:19999 \
  -v /home/alarm/data/netdata/config:/etc/netdata \
  -v /home/alarm/data/netdata/lib:/var/lib/netdata \
  -v /home/alarm/data/netdata/cache:/var/cache/netdata \
  -v /etc/passwd:/host/etc/passwd:ro \
  -v /etc/group:/host/etc/group:ro \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc/os-release:/host/etc/os-release:ro \
  --restart unless-stopped \
  --cap-add SYS_PTRACE \
  --security-opt apparmor=unconfined \
  netdata/netdata
```

Thanks for reaching back.

**Comment by Ferroin** [comment] 2021-03-11 14:39
@t0xic0der Can you confirm that the volumes you are mounting in `/var/cache/netdata` and `/var/lib/netdata` are owned by UID 201 (that’s the default UID used by the container to actually run Netdata)?

**Comment by Ferroin** [comment] 2021-03-11 14:40
Tentatively marking this as a platform support issue as it does not appear to be happening on other platforms.

**Comment by t0xic0der** [comment] 2021-03-11 14:55
> @t0xic0der Can you confirm that the volumes you are mounting in /var/cache/netdata and /var/lib/netdata are owned by UID 201 (that’s the default UID used by the container to actually run Netdata)?

I could use some pointers to figure that out @Ferroin.

**Comment by Ferroin** [comment] 2021-03-11 14:59
> > @t0xic0der Can you confirm that the volumes you are mounting in /var/cache/netdata and /var/lib/netdata are owned by UID 201 (that’s the default UID used by the container to actually run Netdata)?
> 
> I could use some pointers to figure that out @Ferroin.

`ls -n` should do it (the `-n` option is like `ls -l`, but it lists numeric UIDs and GIDs instead of user and group names).

**Comment by t0xic0der** [comment] 2021-03-11 15:11
This is the output.

```
[alarm@alarm netdata]$ ls -n
total 12
drwxr-xr-x 2 0 0 4096 Mar 11 12:59 cache
drwxr-xr-x 2 0 0 4096 Mar 11 12:59 config
drwxr-xr-x 4 0 0 4096 Mar 11 12:59 lib
```

Here. As `alarm` (my user which I use to run `docker`) is in the `docker` group, they should be from the same access group as well, I think. Please correct me if I am wrong.

**Comment by Ferroin** [comment] 2021-03-11 15:18
AFAIK, Docker doesn’t do anything to correct the ownership/permissions of any mounted volumes in the container. IOW, inside the container those will also be owned by the root user.

I _suspect_ that if you `chown -R 201:201` the `lib` and `cache` directories it will fix your issue, but I can’t guarantee that for certain.

**Comment by t0xic0der** [comment] 2021-03-13 04:23
> AFAIK, Docker doesn’t do anything to correct the ownership/permissions of any mounted volumes in the container. IOW, inside the container those will also be owned by the root user.

Hi @Ferroin, that makes sense.

> I _suspect_ that if you `chown -R 201:201` the `lib` and `cache` directories it will fix your issue, but I can’t guarantee that for certain.

I am gonna try doing that and report here if it works (or if it doesn't).

**Comment by ilyam8** [comment] 2021-03-18 22:53
Closing this because it is not a bug, but permissions issue. Same as https://github.com/netdata/netdata/issues/10793#issuecomment-802146027.

We recommend [to use volumes](https://learn.netdata.cloud/docs/agent/packaging/docker#create-a-new-netdata-agent-container) at least for cache/lib directories. For config directory there is [a section how to make it working correctly using bind mounts](https://learn.netdata.cloud/docs/agent/packaging/docker#host-editable-configuration).

**Closed by ilyam8** 2021-03-18 22:53 UTC
Labels: area/packaging, bug, needs triage
