### ISSUE TITLE
No longer getting all metrics from LXD containers after switch to Snap

### ISSUE THREAD

**Issue by Kramerican** [netdata/netdata#6481] opened 2019-07-17 10:42 UTC
##### Bug report summary

I no longer get all metrics for all of my LXD containers as I used to since I switched from LXD apt package to installing LXD from Snap. I now have two places in the Netdata UI where metrics are reported:

lxc.monitor *
lxc.payload *

Where I think I only had one of them before (not 100% sure here) - what's odd is that containers can also be entirely missing, and it seems almost random what metrics are present and which ones aren't. Sometimes I can get reported IO and Network use, most often not.

##### OS / Environment

Ubuntu Bionic

##### Netdata version (ouput of `netdata -V`)

v1.15.0-111-g61e45b55

##### Steps To Reproduce

Install LXD from Snap - install Netdata - spawn a container and check out metrics

##### Expected behavior

I'd expect to see all charts/metrics as I did before

**Comment by vlvkobal** [comment] 2019-10-25 13:21
Have you tried using the [`enable zero metrics` option](https://docs.netdata.cloud/collectors/cgroups.plugin/#charts-with-zero-metrics)?

**Comment by Kramerican** [comment] 2019-10-25 13:34
@vlvkobal Hey that seems to work! Nice one. Thanks :)

**Comment by Kramerican** [comment] 2019-11-06 14:02
Need to re-open this, as after a while this has "reverted" in the sense that now I have lots of "chart not found" across most containers now. This is the same across 10 hosts and about ~300 containers.

enable zero metrics is set to yes and even after a restart of netdata I do not get all metrics, like I did before.

I am on version v1.17.1-80-gd4213ef5 on Ubuntu Bionic - I have a seperate ticket #7261  regarding auto updates not working, as I thought it might be due to that, but it does not seem netdata is auto-updating for me

**Comment by ilyam8** [comment] 2019-11-06 15:17
> enable zero metrics is set to yes and even after a restart of netdata I do not get all metrics, like I did before.

So what do you have what you dont?

**Comment by Kramerican** [comment] 2019-12-05 19:02
I finally got around to looking at this as I was waiting for auto updates to get working again. I just updated to the latest v1.19.0-48-ge7100432 and I still see this behavior across all hosts even with zero metrics enabled.

In response to @ilyam8 : I have some metrics for some containers. Many (most) containers are not discovered by Netdata and the ones that are, are usually missing a few metrics.

It _**seems**_ to be that the most active containers have metrics while mostly idle ones do not.

I can grant access to the netdata dashboards and provide more info, but I'd rather not share the information publicly.

**Comment by ilyam8** [comment] 2019-12-05 19:08
@kralewitz you can send a snapshot to vlad@netdata.cloud 😄

**Comment by Kramerican** [comment] 2019-12-05 19:11
@ilyam8 What do you mean by snapshot exactly? :)

**Comment by ilyam8** [comment] 2019-12-05 19:23
See `export/save a netdata snapshot` on the top bar

**Comment by Kramerican** [comment] 2019-12-05 19:29
I have sent a mail with information :)

**Comment by vlvkobal** [comment] 2019-12-10 12:00
What configuration do you have in the `[plugin:cgroups]` section?

**Comment by Kramerican** [comment] 2019-12-10 12:06
Do you mean:

```
# cat /opt/netdata/etc/netdata/netdata.conf
[global]
 history = 86400
 enable zero metrics = yes
```

This is all we got. We just install Netdata with kickstart, and write that config, That's it.

**Comment by vlvkobal** [comment] 2019-12-10 14:03
Please try
```
[plugin:cgroups]
	enable by default cgroups matching = *
```
Do you see all the containers you need with this setting?

**Comment by Kramerican** [comment] 2019-12-10 14:24
Now with

```
# cat /opt/netdata/etc/netdata/netdata.conf
[global]
 history = 86400
 enable zero metrics = yes

[plugin:cgroups]
        enable by default cgroups matching = *
```

I see not much of a difference. I lost all metrics for a while after `systemctl restart netdata`  and now after several minutes it's really the same. Metrics for some containers, some not.

**Comment by vlvkobal** [comment] 2019-12-10 15:34
Hm... It's strange. I expected many more containers being detected because the default filter is quite strict. Please search for `cgroup-name.sh` in the `error.log`. Do you have anything suspicious there?

Try the following settings:
`use unified cgroups = yes`
`search for cgroups in subpaths matching = *`

**Comment by Kramerican** [comment] 2019-12-10 18:55
All I see in the log are a lot of info lines:

`2019-12-10 15:22:20: cgroup-name.sh: INFO: cgroup 'lxc.payload_maintenance' is called 'lxc.payload_maintenance'`

Matching the containers which _**do**_ have metrics.

I updated the settings so now I have:

```
# cat /opt/netdata/etc/netdata/netdata.conf
[global]
 history = 86400
 enable zero metrics = yes

[plugin:cgroups]
        enable by default cgroups matching = *
        use unified cgroups = yes
        search for cgroups in subpaths matching = *
```

I still see basically the exact same behavior. The remaining containers are not being discovered.

**Comment by Kramerican** [comment] 2019-12-27 09:50
@vlvkobal Does this mean you ran out of ideas? :) I am motivated to help in any way I can here, so please let me know if I can provide more information or access

**Comment by vlvkobal** [comment] 2020-01-16 10:52
Okay, so the result of the investigation is that in the `error.log` there are a lot of messages like
```
2020-01-15 06:25:05: netdata INFO  : PLUGIN[cgroups] : CGROUP: maximum number of cgroups reached (1000). Not adding cgroup '/lxc.payload/peterkam/system.slice/kestrel-peterkam-rest-api.service'
```

The problem is that in `/sys/fs/cgroup/*` folders there are subfolders with the following names: `lxc.monitor`, `lxc.payload`, and `lxc.pivot` instead of `lxc`. With the following config option

```
[plugin:cgroups]
 search for cgroups in subpaths matching =  !*/init.scope  !*-qemu  !*.libvirt-qemu  !/init.scope  !/system  !/systemd  !/user  !/user.slice  !/lxc/*/* !/lxc.payload/*/* *
```
we filtered out `system.slice` folders, drastically reducing the total number of containers, and all useful containers are available now in the dashboard. We need, however, to filter out all container which are not useful. I presume we can get meaningful information only from `lxc.payload` (https://github.com/lxc/lxc/issues/2782#issuecomment-459286284).

**Comment by vlvkobal** [comment] 2020-01-16 12:03
@Kramerican please remove the `enable by default cgroups matching` and `search for cgroups in subpaths matching` options from your `netdata.conf` after #7760 have been merged and your Netdata is updated.

**Comment by vlvkobal** [comment] 2020-01-16 15:32
Thank you @Kramerican for your report and cooperation!

**Closed** 2020-01-16 15:31 UTC
Labels: area/collectors, bug

**Comment by Kramerican** [comment] 2020-01-16 15:48
No THANK YOU @vlvkobal for your awesome willingness to help and attention to detail in this matter!

**Comment by Kramerican** [comment] 2020-07-13 11:22
Hello @vlvkobal 

This issue has now reverted for me, as of a few versions ago. I am up to date on `v1.23.1-77-g013c9da6` and seeing the exact same symptoms as before.

I am also seeing lots of the error messages in my error log you refer to earlier:

`2020-07-13 12:45:06: netdata INFO  : PLUGIN[cgroups] : CGROUP: maximum number of cgroups reached (1000). Not adding cgroup '/lxc.payload.xxxx/system.slice/console-setup.service'`

Has your code been reverted / removed from the latest Netdata versions?!

**Comment by webdock-io** [comment] 2020-07-20 11:26
@vlvkobal any updates on this issue?

**Comment by vlvkobal** [comment] 2020-07-21 07:52
I might be able to look at it next week.

**Comment by vlvkobal** [comment] 2020-07-31 11:22
I can't find any changes in the cgroups plugin's code that might lead to reverting the expected behavior. Probably, lxd directory structure was changed again.

@Kramerican could you send your error.log to vlad@netdata.cloud?

**Comment by webdock-io** [comment] 2020-08-02 12:28
@vlvkobal error log sent your way by email :)

**Comment by vlvkobal** [comment] 2020-08-03 08:37
@webdock-io, @Kramerican please test #9645.

**Comment by Kramerican** [comment] 2020-08-03 09:41
@vlvkobal How exactly? By building from source, or?

**Comment by vlvkobal** [comment] 2020-08-03 09:48
> How exactly? By building from source, or?

Well, maybe installing Netdata from source is an overkill. You can temporarily set the following options in `netdata.conf` in `[plugin:cgroups]` section.

```
enable by default cgroups matching =  !*/init.scope  !/system.slice/run-*.scope  *.scope  /machine.slice/*.service  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.socket  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/*  !/lxc.monitor*  !/lxc.pivot  !/lxc.payload*  !/machine  !/qemu  !/system  !/systemd  !/user  * 
search for cgroups in subpaths matching =  !*/init.scope  !*-qemu  !*.libvirt-qemu  !/init.scope  !/system  !/systemd  !/user  !/user.slice  !/lxc/*/*  !/lxc.monitor*  !/lxc.payload*/*/*  * 
```

**Comment by Kramerican** [comment] 2020-08-03 09:58
@vlvkobal That effectively breaks monitoring of containers and I get no metrics whatsoever for any containers now :(

I copy/pasted your lines and then just did a `systemctl restart netdata`

**Comment by vlvkobal** [comment] 2020-08-03 14:46
Could you try this configuration?
```
enable by default cgroups matching =  !*/init.scope  !/system.slice/run-*.scope  *.scope  /machine.slice/*.service  !*/vcpu*  !*/emulator  !*.mount  !*.partition  !*.service  !*.socket  !*.slice  !*.swap  !*.user  !/  !/docker  !/libvirt  !/lxc  !/lxc/*/*  !/lxc.monitor*  !/lxc.pivot  !/lxc.payload/ !/lxc.payload*/* !/machine  !/qemu  !/system  !/systemd  !/user  *
```

**Comment by vlvkobal** [comment] 2020-08-13 07:14
@webdock-io thank you for providing access to your system! It was much easier to figure out how to fix the issue seeing the live example.
