### ISSUE TITLE
collect prometheus formatted metrics

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#3685] opened 2018-05-05 10:21 UTC
Spring boot has moved to Micrometer for metrics and already supports many backends. Netdata support will simplify the overall integration and all metrics (instrumentation and JVM) will be available for view in Netdata.

I may be able to experiment with a custom Spring MetricsRegistry to push data to Netdata but need to figure out the format of data on both ends to make this work.

Wonder if the current spring boot plugin uses actuator endpoints to pull metrics in to Netdata.

**Comment by gamefundas** [comment] 2018-05-05 10:57
The following gives me a good idea of how it works currently.
https://github.com/firehol/netdata/wiki/Monitoring-Java-Spring-Boot-Applications

**Comment by ktsaou** [comment] 2018-05-07 21:59
@Wing924 check this. If I understand this right, the application using micrometer has to create a listener of some kind for netdata to query it. This is what it does for prometheus and other backends.

I also see micrometer supports statsd, so netdata can collect metrics from it. Using netdata statsd synthetic charts, custom grouping of the metrics can also be done.

**Comment by Wing924** [comment] 2018-05-08 02:00
@ktsaou micrometer don't report json like springboot 1.x, but it report prometheus format. I think we can create the dashboard from prometheus metrics. Creating a prometheus plugin may be helpful.

**Comment by ktsaou** [comment] 2018-05-08 08:38
hm... interesting idea... collect metrics in a format of another collector... we could even collect metrics in graphite or opentsdb format...

**Comment by ktsaou** [comment] 2018-05-08 08:40
This would have a few implications though... for example all these time series dbs support collecting past data, while netdata cannot do this. For netdata all metrics collected are current.

**Comment by Wing924** [comment] 2018-05-08 08:43
Prometheus also don't support collect past data :)
In addition, parse prometheus metrics is very easy if we write the plugin in Go.

**Comment by ktsaou** [comment] 2018-05-08 08:48
ok, then.
I know @l2isbad is working to port all python plugins to go.

@l2isbad what do you think? Would this be a good go-only plugin to start with?

**Comment by l2isbad** [comment] 2018-05-08 09:41
> all python plugins to go

Well, not sure about all. The plan was to port `web_log`,` httpcheck`, `portcheck` (i did it already). I will do others on demand i think.  

> what do you think? Would this be a good go-only plugin to start with?

Why not.

Still i need some time to finish `go.d.plugin`.

**Comment by gamefundas** [comment] 2018-05-08 15:41
My understanding is Micrometer produces prometheus format in case of PrometheusMetricRegistry as Prometheus is a pull based collector and spring exposes it in its own format to consume. In case of StatsD there is a configurable format/frequency in which it pushes to the StatsD host/port. So the way I see it if a NetdataMetricRegistry is implemented we could support the Netdata format and have this added to Spring micrometer project.

**Comment by ktsaou** [comment] 2018-05-08 22:47
The key difference of netdata with all the other backends, is that netdata groups individual metrics into meaningful entities. So metrics go into charts, charts are grouped in families and families into apps. 

On the other hand, all time series dbs work with just a "bunch of metrics" and you are expected to give meaning to them with grafana or other visualization tools.

For netdata, the technical details of collecting the metrics is not that important. We only need a "name = value" list from the application. A JSON API will do, prometheus format will do, statsd format will also do.

1. JSON API: the grouping logic is in the netdata plugin (like we do today)

2. prometheus API: the grouping logic will have to implemented also in the netdata plugin - if we did this with python, I guess a PrometheusService would take care of parsing the raw metrics and then the plugin will just group them and push them to netdata.

3. statsd API: the grouping logic can be configured with [netdata statsd synthetic charts](https://github.com/firehol/netdata/wiki/statsd#synthetic-statsd-charts). So for each application pushing statsd metrics, an `app.conf` file can be created to convert the raw metrics into meaningful charts.

**Comment by Wing924** [comment] 2018-07-18 08:01
@ktsaou @l2isbad 
It looks go plugin will take a long time, but many people use springboot2 now.
How do you think to implement the prometheus format service by python?

**Comment by l2isbad** [comment] 2018-07-18 08:11
@Wing924 

> In addition, parse prometheus metrics is very easy if we write the plugin in Go.

[Do it](https://github.com/l2isbad/go.d.plugin/tree/master/internal/modules) :smile:

**Comment by l2isbad** [comment] 2018-07-18 08:20
> It looks go plugin will take a long time

I will have a vacation in august. I plan to start working hard on it in in september. If you willing to help please read the source code. I am open to any suggestion.

**Comment by Wing924** [comment] 2018-07-18 13:42
@ktsaou @l2isbad 
Before I start to read the code in deep, I want to confirm some questions.

## How do we install the go plugin?

### Compile in servers like what kick-starter.sh currently do

* **Pros.**
* User don't need to care about the internal and install it as usual.
* **Cons.**
* Not all platform can have go compiler.
  * Almost all UNIX-like system can easily install C compiler by pkg manager
  * Not all platform can do that for Go compiler.

### Pre-build the plugin by CI and download the binary

* **Pros.**
  * User don't need Go compiler.
* **Cons.**
  * Not true install from source.

## How do we execute the go plugin?

### Create a single binary

* **Pros.**
  * Performance is good.
* **Cons.**
  * Hard to add custom go plugin.
  * Hard to handle panics.
  * Can't seplate privileged plugin and non-privileged plugin.

### Create each plugin in shared library (\*.so) and load them in runtime

* **Pros.**
  * User can easily add custom go plugin.
* **Cons.**
  * It break Go's single binary rule.
  * The more so files, the more complexity the plugin.
  * Make it harder to debug since shared library can't be executed alone.
  * Only Linux and MacOS support shared library.
  * Hard to handle panics.
  * Can't seplate privileged plugin and non-privileged plugin.

ref. <https://golang.org/pkg/plugin/>

### Create each plugin in a binary and link them with pipe

* **Pros.**
  * User can easily add custom go plugin.
  * All platforms support this plugin style.
  * Easy to debug because each plugin can execute alone.
  * Easier to handle panics and errors.
  * Seplate privileged plugin and non-privileged plugin.
* **Cons.**
  * It break Go's single binary rule.
  * One plugin one process.
  * Hard to limit the resource.

# Proposal

* Pre-build the plugin by CI and download the binary
* Create a single binary for all non-privileged plugin
* Create another plugin for privileged plugin (if needed)

**Comment by l2isbad** [comment] 2018-07-18 13:54
I was thinking of

> How do we install the go plugin?

Pre-build. _User don't need Go compiler_ is must have.

> How do we execute the go plugin?

Create a single binary. `Hard to handle panics` - why?

**Comment by l2isbad** [comment] 2018-07-18 14:03
@Wing924 
actually if you want we can collaborate via telegram/discord/any other thing (first two preferred, i have them on my desktop)

**Comment by Wing924** [comment] 2018-07-18 14:05
@l2isbad 
Go have 2 methods to handle error:
* return `error` and check
* raise a panic and catch it by `recover()`
  * if no `recover()` catch the panic, runtime will kill the entire go process.
  * panic can be raised by `panic()`, null-pointer access, etc.

The problem is `recover()` only can catch the panic raised in the same go-routine.
If any plugin create a go-routine and raise a panic, all plugins will be killed.

**Comment by l2isbad** [comment] 2018-07-18 14:12
@Wing924 

I know about go errors. And that is the reason i asked, because it's easy to handle (**if `panic` is recoverable**).

I took this into account when creating the plugin.

https://github.com/l2isbad/go.d.plugin/blob/master/internal/modules/module.go#L56-L60
https://github.com/l2isbad/go.d.plugin/blob/master/internal/godplugin/job/job.go#L10-L18
https://github.com/l2isbad/go.d.plugin/blob/master/internal/godplugin/job/job.go#L96-L112

**Comment by Wing924** [comment] 2018-07-18 14:20
@l2isbad 
I mean you never can catch this panic and program dies.
```go
func foo() {
  go func() {
    panic("error!")
  }()
}
```

**Comment by paulfantom** [comment] 2018-07-20 09:17
Just a note. 

Prometheus will soon switch to use this metrics format: https://github.com/RichiH/OpenMetrics, which is developed in cooperation with Google, OVH and some other companies. Format is based on one which currently used by prometheus, but has some minor changes.

**Comment by ktsaou** [comment] 2018-11-23 13:37
@l2isbad 	collecting openmetrics and prometheus metrics are on our roadmap. High priority.

**Comment by cakrit** [comment] 2018-11-26 10:20
Closing as duplicate of #4730, it will be delivered there.

**Closed by cakrit** 2018-11-26 10:20 UTC
Labels: area/external/python, feature request, priority/high
