### ISSUE TITLE
System status by date

### ISSUE THREAD

**Issue by LuisReinoso** [netdata/netdata#3356] opened 2018-01-28 00:07 UTC
Hello everyone,

I want to see the system status by date. Is there any way to do that?
Thanks.

**Comment by paulfantom** [comment] 2018-09-22 21:46
Not yet. It has low priority on the roadmap as said in https://github.com/netdata/netdata/issues/3420#issuecomment-365411851


Closing as it is partial duplicate of #3420

**Closed by paulfantom** 2018-09-22 21:46 UTC
