### ISSUE TITLE
[Bug]:Cannot access to the PMU: Permission denied after recompiled perf_plugin.c

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#11957] opened 2022-01-12 09:57 UTC
### Bug description

I changed the perf_plugin.c and want to recompile it and add new PMU metrics to netdata.

After edit perf_plugin.c ( I tried keep it as original and recompiled but still failed ) I recomplile with command:
```bash
rm -f collectors/perf.plugin/perf_plugin.o

gcc -std=gnu99 -DHAVE_CONFIG_H -I.   -DTARGET_OS=1      -DVARLIB_DIR="\"/var/lib/netdata\""     -DCACHE_DIR="\"/var/cache/netdata\""    -DCONFIG_DIR="\"/etc/netdata\""         -DLIBCONFIG_DIR="\"/usr/lib/netdata/conf.d\""   -DLOG_DIR="\"/var/log/netdata\""        -DPLUGINS_DIR="\"/usr/libexec/netdata/plugins.d\""      -DRUN_DIR="\"/var/run/netdata\""        -DWEB_DIR="\"/usr/share/netdata/web\""     -I/usr/include/uuid          -O2 -pthread -I /home/test/netdata/externaldeps/protobuf/src     -I/usr/include/uuid                  -I /home/test/netdata/exporting/prometheus/remote_write              -I /home/test/netdata/mqtt_websockets/src/include -I /home/test/netdata/mqtt_websockets/c-rbuf/include -I /home/test/netdata/mqtt_websockets/MQTT-C/include -I /home/test/netdata/aclk/aclk-schemas -DDLIB_NO_GUI_SUPPORT -I /home/test/netdata/ml/kmeans/dlib  -MT collectors/perf.plugin/perf_plugin.o -MD -MP -MF collectors/perf.plugin/.deps/perf_plugin.Tpo -c -o collectors/perf.plugin/perf_plugin.o collectors/perf.plugin/perf_plugin.c

rm -f perf.plugin

gcc -std=gnu99    -I/usr/include/uuid          -O2 -pthread -I /home/test/netdata/externaldeps/protobuf/src     -I/usr/include/uuid                  -I /home/test/netdata/exporting/prometheus/remote_write              -I /home/test/netdata/mqtt_websockets/src/include -I /home/test/netdata/mqtt_websockets/c-rbuf/include -I /home/test/netdata/mqtt_websockets/MQTT-C/include -I /home/test/netdata/aclk/aclk-schemas -DDLIB_NO_GUI_SUPPORT -I /home/test/netdata/ml/kmeans/dlib    -o perf.plugin collectors/perf.plugin/perf_plugin.o libnetdata/adaptive_resortable_list/adaptive_resortable_list.o libnetdata/config/appconfig.o libnetdata/avl/avl.o libnetdata/buffer/buffer.o libnetdata/circular_buffer/circular_buffer.o libnetdata/clocks/clocks.o libnetdata/dictionary/dictionary.o libnetdata/eval/eval.o libnetdata/libnetdata.o libnetdata/locks/locks.o libnetdata/log/log.o libnetdata/popen/popen.o libnetdata/procfile/procfile.o libnetdata/os.o libnetdata/simple_pattern/simple_pattern.o libnetdata/socket/socket.o libnetdata/socket/security.o libnetdata/statistical/statistical.o libnetdata/storage_number/storage_number.o libnetdata/threads/threads.o libnetdata/url/url.o libnetdata/json/json.o libnetdata/json/jsmn.o libnetdata/health/health.o  -lm  -lz   -lcrypto -lssl -luuid    -luv -llz4 -lJudy -lcrypto -lssl -ljson-c   -lrt

/bin/install perf.plugin /usr/libexec/netdata/plugins.d/perf.plugin
chown root:netdata /usr/libexec/netdata/plugins.d/perf.plugin
```

Then I try `service netdata restart`. Error log shows that `perf.plugin ERROR : MAIN : Cannot access to the PMU: Permission denied (errno 13, Permission denied)`

### Expected behavior

Recompile perf_plugin.c and apply changes to netdata service.

### Steps to reproduce

1.Recompile perf_plugin.c as shown above.
2.service netdata restart

### Installation method

from source

### System info

```shell
Linux localhost 4.14.0-115.el7a.0.1.aarch64 #1 SMP Thu Aug 12 14:16:47 CST 2021 aarch64 aarch64 aarch64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.6.1810 (AltArch)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (AltArch)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (AltArch)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.6.1810 (AltArch)
/etc/system-release:CentOS Linux release 7.6.1810 (AltArch)
```

### Netdata build info

```shell
Version: netdata v1.32.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO
    ACLK Next Generation:       NO
    ACLK-NG New Cloud Protocol: NO
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           NO
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     NO
    mosquitto:               NO
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by ilyam8** [comment] 2022-01-12 10:29
@oleotiger, hey. Does it work when you run the plugin manually?

> ./perf.plugin all

**Comment by vlvkobal** [comment] 2022-01-12 11:10
Since Linux 5.8 you need to set [`CAP_PERFMON` capability](https://manned.org/perf_event_open.2#head8) to access PMUs. Please do
```
sudo systemctl edit netdata.service
```
Add
```
[Service]
CapabilityBoundingSet=CAP_PERFMON
```
at the beginning of the file
```
sudo systemctl daemon-reload
sudo systemctl restart netdata
```

**Comment by vlvkobal** [comment] 2022-01-12 12:03
Oh, BTW, did you set special permissions for `perf.plugin`? 
```
chown root:netdata /usr/libexec/netdata/plugins.d/perf.plugin
chmod 0750 /usr/libexec/netdata/plugins.d/perf.plugin
setcap cap_perfmon+ep /usr/libexec/netdata/plugins.d/perf.plugin || setcap cap_sys_admin+ep /usr/libexec/netdata/plugins.d/perf.plugin
```

**Comment by ilyam8** [comment] 2022-01-12 12:43
> Since Linux 5.8 you need to set CAP_PERFMON capability t

@oleotiger system is 4.14, so the following should do:

```bash
chown root:netdata /usr/libexec/netdata/plugins.d/perf.plugin
chmod 0750 /usr/libexec/netdata/plugins.d/perf.plugin
setcap cap_sys_admin+ep /usr/libexec/netdata/plugins.d/perf.plugin
```

**Comment by ilyam8** [comment] 2022-01-17 13:14
Closing because it is not a bug and the [solution was provided](https://github.com/netdata/netdata/issues/11957#issuecomment-1011008086).

**Closed by ilyam8** 2022-01-17 13:14 UTC
Labels: question, area/external
