### ISSUE TITLE
Can't be installed in China (one line installation script)

### ISSUE THREAD

**Issue by startryst** [netdata/netdata#9138] opened 2020-05-23 05:31 UTC
`raw.githubusercontent.com`, and `storage.googleapis.com` is unable to connect within china, I assume everyone knows the reason, so any plan to have a secondary repository to let the broader China users to enjoy the simplicity of one line installation script?

I tried other methods as well: rpm by package cloud, but it turns out the netdata.conf is different than the one line installation script.

For offline installation, tried without any luck, and it's a bit too much.

**Comment by prologic** [comment] 2020-05-25 05:50
Duplicate of #8527

**Closed by prologic** 2020-05-25 05:50 UTC
Labels: bug, needs triage

**Comment by startryst** [comment] 2020-07-23 05:36
any new development/progress on this?
