### ISSUE TITLE
Cannot delete server from list

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#6904] opened 2019-09-21 19:39 UTC
#### Summary
I cannot delete a server from the list that is associated with the registry.
The error message is:
"Sorry, this command was rejected by netdata.cloud"
Please check the screenshot for details.

I reported a similar issue before here #4375, the the provided solution is not working.

Please advise how to fix it.

THX

**Comment by 74cmonty** [comment] 2019-09-21 19:44
![pc8-t410 netdata dashboard - Chromium_010](https://user-images.githubusercontent.com/12523591/65378469-0310bd80-dcb9-11e9-84a6-cdfaf97fe9ea.png)

**Comment by 74cmonty** [comment] 2019-09-21 19:45
![pc8-t410 netdata dashboard - Chromium_011](https://user-images.githubusercontent.com/12523591/65378479-29365d80-dcb9-11e9-9842-5aad6ebf1e17.png)

**Comment by cakrit** [comment] 2019-09-22 09:47
Duplicate of #6876 
We have a fix, just need to test and deploy it on Monday.

**Closed by cakrit** 2019-09-22 09:47 UTC
