### ISSUE TITLE
Prometheus may cause API json response to be invalid

### ISSUE THREAD

**Issue by jurgenhaas** [netdata/netdata#9737] opened 2020-08-13 08:42 UTC
##### Bug report summary

On one of my hosts with GitLab being installed, the API call to http://host:19999/api/v1/allmetrics?format=json&help=no&types=no&timestamps=yes&names=yes&data=average returns invalid JSON:

```
{
	"prometheus_gitlab-workhorse_local.gitlab_workhorse_http_time_to_write_header_seconds_bucket|code=200,method=post,route=^/([^/]+/){1,}[^/]+/uploads\z": {
		"name":"prometheus_gitlab_workhorse_local.gitlab_workhorse_http_time_to_write_header_seconds_bucket_code_200_method_post_route____________1________uploads_z",
		"family":"gitlab_workhorse",
		"context":"prometheus.gitlab_workhorse_http_time_to_write_header_seconds_bucket",
		"units":"observations",
		"last_updated": 1597306745,
		"dimensions": {
			"gitlab_workhorse_http_time_to_write_header_seconds_bucket|code=200,le=0.005,method=post,route=^/([^/]+/){1,}[^/]+/uploads\z": {
				"name": "0.005",
				"value": 0.0000000
			},
			"gitlab_workhorse_http_time_to_write_header_seconds_bucket|code=200,le=0.025,method=post,route=^/([^/]+/){1,}[^/]+/uploads\z": {
				"name": "0.025",
				"value": 0.0000000
			},
```

The error message reads `SyntaxError: JSON.parse: bad escaped character at line 2 column 150 of the JSON data` which is caused by the `\z` at the end of line 2 and many more further down in the same response.

##### OS / Environment

Both client and server are on Ubuntu 18.04 LTS

##### Netdata version

1.24.0

**Comment by ilyam8** [comment] 2020-08-13 08:53
Hi

quick workaround is to disable

- the job

https://github.com/netdata/go.d.plugin/blob/5f61c42fdd4e0e4b4801d4ac574cc78a5f9a0dec/config/go.d/prometheus.conf#L405-L406

or 

- the module

https://github.com/netdata/go.d.plugin/blob/5f61c42fdd4e0e4b4801d4ac574cc78a5f9a0dec/config/go.d.conf#L45

**Comment by jurgenhaas** [comment] 2020-08-13 09:23
Confirmed. I guess the API requires some string sanitization generally before output.

**Comment by amoss** [comment] 2020-08-14 12:14
@ilyam8 When you get back from vacation please link this to the similar issue (where the backslashes in the windows-style paths cause the same problem) and fix both by sanitizing the chart and dimension names.

**Comment by ilyam8** [comment] 2022-07-15 10:53
I think the issue is fixed in the latest stable version. @jurgenhaas let us know if I am wrong and if it is not fixed yet.

**Closed by ilyam8** 2022-07-15 10:53 UTC
Labels: bug, area/collectors, collectors/go.d
