### ISSUE TITLE
Python modules not running on Ubuntu Server 18.04

### ISSUE THREAD

**Issue by Steve8291** [netdata/netdata#5541] opened 2019-03-03 18:34 UTC
##### Bug report summary
No python modules will display charts on Ubuntu Server 18.04
Both Sensors and Redis modules appear to be working.
Output of `/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug sensors`

> 2019-03-03 13:23:36: python.d INFO: plugin: main: Using python 2
> 2019-03-03 13:23:36: python.d DEBUG: plugin: main: loading '/etc/netdata/python.d.conf'
> 2019-03-03 13:23:36: python.d ERROR: plugin: main: cannot load '/etc/netdata/python.d.conf': [Errno 2] No such file or directory: '/etc/netdata/python.d.conf'. Will try stock version.
> 2019-03-03 13:23:36: python.d DEBUG: plugin: main: loading '/usr/lib/netdata/conf.d/python.d.conf'
> 2019-03-03 13:23:36: python.d DEBUG: plugin: main: module load source: 'sensors' => [OK]
> 2019-03-03 13:23:36: python.d DEBUG: plugin: main: loading '/etc/netdata/python.d/sensors.conf'
> 2019-03-03 13:23:36: python.d ERROR: plugin: main: cannot load '/etc/netdata/python.d/sensors.conf' : [Errno 2] No such file or directory: '/etc/netdata/python.d/sensors.conf'. Will try stock version.
> 2019-03-03 13:23:36: python.d DEBUG: plugin: main: loading '/usr/lib/netdata/conf.d/python.d/sensors.conf'
> 2019-03-03 13:23:36: python.d DEBUG: plugin: main: job initialization: 'sensors sensors' => ['OK']
> 2019-03-03 13:23:36: python.d DEBUG: plugin: main: module status: 'sensors' => [OK] (jobs: 1)
> 2019-03-03 13:23:36: python.d INFO: sensors: sensors: check() => [OK]
> CHART netdata.runtime_sensors '' 'Execution time for sensors' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
> DIMENSION run_time 'run time' absolute 1 1
> 
> 2019-03-03 13:23:36: python.d DEBUG: sensors: sensors: create() => [OK] (charts: 3)
> 2019-03-03 13:23:36: python.d DEBUG: sensors: sensors: started, update frequency: 1
> CHART sensors.coretemp-isa-0000_temperature '' 'coretemp-isa-0000 temperature' 'Celsius' 'temperature' 'sensors.temperature' line 60002 1 '' 'python.d.plugin' 'sensors'
> DIMENSION 'coretemp-isa-0000_temp1' 'Package id 0' absolute 1 1000 ''
> DIMENSION 'coretemp-isa-0000_temp2' 'Core 0' absolute 1 1000 ''
> DIMENSION 'coretemp-isa-0000_temp3' 'Core 1' absolute 1 1000 ''
> DIMENSION 'coretemp-isa-0000_temp4' 'Core 2' absolute 1 1000 ''
> DIMENSION 'coretemp-isa-0000_temp5' 'Core 3' absolute 1 1000 ''
> 
> BEGIN sensors.coretemp-isa-0000_temperature 0
> SET 'coretemp-isa-0000_temp1' = 37000
> SET 'coretemp-isa-0000_temp2' = 23000
> SET 'coretemp-isa-0000_temp3' = 25000
> SET 'coretemp-isa-0000_temp4' = 24000
> SET 'coretemp-isa-0000_temp5' = 36000
> END

I have attempted run netdata off an Ubuntu 18.04 Desktop livecd. This works fine.
Also attempted to install all python packages on the server that were not present as compared with the livecd. This also had no effect.

##### OS / Environment
Ubuntu Server 18.04

##### Netdata version (ouput of `netdata -V`)
netdata v1.12.2-4-nightly

##### Component Name
python.d.plugin

##### Steps To Reproduce
Fresh install of Ubuntu Server 18.04
```
apt install lm-sensors
apt install redis-server
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

##### Expected behavior
Charts should show for Sensors and Redis.

**Comment by Steve8291** [comment] 2019-03-03 18:37
Also, enabling sensors=force in charts.d.plugin allows the sensors charts to show.
This is of course not using python.d.plugin but rather the shell script.

**Comment by ilyam8** [comment] 2019-03-05 16:40
@Steve8291 

Please correct me if i'm wrong.

Python module `sensors` works only if you are running `python.d.plugin` in debug mode, it doesn't work in normal mode and there is no `Sensors` on the dashboard, right?

**Comment by ilyam8** [comment] 2019-03-05 16:43
Anyway, plese do:
 - cd /to/netdata/log/dir
 - cp /dev/null error.log
 - systemctl restart netdata.service
 - wait a bit
 - copy the whole error.log and upload it to, for example, [pastebin.com](https://pastebin.com/) and drop the link here

**Comment by Steve8291** [comment] 2019-03-05 19:03
Thanks ilyam8 I will post my error log tonight. 
The output that I pasted in the original post was from running in debug. I am assuming that the sensors are working the same while netdata is running without debug turned on. You are correct, there are no sensors showing on the dashboard unless I use the shell script with sensors=force.

**Comment by Steve8291** [comment] 2019-03-06 02:58
Here is the full output from my error.log after clearing it and restarting netdata:
[https://pastebin.com/KJDtAPfc](url)

**Comment by ilyam8** [comment] 2019-03-06 14:27
@Steve8291 

Ok, wait unitl #5552 is merged, update netdata to the latest, and try again. If the problem is not fixed please provide the error.log again.

**Comment by ilyam8** [comment] 2019-03-06 14:27
> I am assuming that the sensors are working the same while netdata is running without debug turned on.

Yes.

**Comment by Steve8291** [comment] 2019-04-14 15:29
Currently running v1.14.0-rc0-52-nightly and this issue is fixed for both Redis and Sensors graphs. For comparison with the initial bug report, here is the output from 
`/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug sensors`

> 2019-04-14 10:45:45: python.d INFO: plugin[main] : using python v2
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : starting setup
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : checking for config in ['/etc/netdata', '/usr/lib/netdata/conf.d']
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : config found, loading config '/usr/lib/netdata/conf.d/python.d.conf'
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : config successfully loaded
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
> 2019-04-14 10:45:45: python.d INFO: plugin[checker] : starting...
> 2019-04-14 10:45:45: python.d INFO: plugin[checker] : sensors : checking
> 2019-04-14 10:45:45: python.d INFO: plugin[checker] : sensors : source successfully loaded
> 2019-04-14 10:45:45: python.d INFO: plugin[checker] : sensors : found config file '/usr/lib/netdata/conf.d/python.d/sensors.conf'
> 2019-04-14 10:45:45: python.d INFO: plugin[checker] : sensors : created 1 job(s) from the config
> 2019-04-14 10:45:45: python.d INFO: plugin[checker] : sensors[sensors] : check successful
> 2019-04-14 10:45:45: python.d INFO: plugin[checker] : terminating...
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : stopping checker process
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : setup complete, 1 active module(s) : '['sensors']'
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : sensors : created 1 job(s)
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : sensors[sensors] : init successful
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : sensors[sensors] : check successful
> CHART netdata.runtime_sensors '' 'Execution time for sensors' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
> DIMENSION run_time 'run time' absolute 1 1
> 
> 2019-04-14 10:45:45: python.d INFO: plugin[main] : sensors[sensors] : started in thread
> 2019-04-14 10:45:45: python.d DEBUG: sensors[sensors] : started, update frequency: 1
> CHART sensors.coretemp-isa-0000_temperature '' 'coretemp-isa-0000 temperature' 'Celsius' 'temperature' 'sensors.temperature' line 60002 1 '' 'python.d.plugin' 'sensors'
> DIMENSION 'coretemp-isa-0000_temp1' 'Package id 0' absolute 1 1000 ' '
> DIMENSION 'coretemp-isa-0000_temp2' 'Core 0' absolute 1 1000 ' '
> DIMENSION 'coretemp-isa-0000_temp3' 'Core 1' absolute 1 1000 ' '
> DIMENSION 'coretemp-isa-0000_temp4' 'Core 2' absolute 1 1000 ' '
> DIMENSION 'coretemp-isa-0000_temp5' 'Core 3' absolute 1 1000 ' '
> 
> BEGIN sensors.coretemp-isa-0000_temperature 0
> SET 'coretemp-isa-0000_temp1' = 24000
> SET 'coretemp-isa-0000_temp2' = 26000
> SET 'coretemp-isa-0000_temp3' = 25000
> SET 'coretemp-isa-0000_temp4' = 24000
> SET 'coretemp-isa-0000_temp5' = 24000
> END

Oddly though, rebooting the machine or restarting netdata with 
`systemctl restart netdata`
Causes the Redis and Sensors graphs to disappear. I'm not sure exactly how long it takes for them to come back up but it is within a few hours at least.

**Comment by Steve8291** [comment] 2019-04-14 15:53
Just timed it. Takes about 40 minutes to get the graphs back after a restart.

**Comment by ilyam8** [comment] 2019-04-16 12:35
This is strange, please do

 - `sudo su -s /bin/bash netdata`
 - `/usr/lib/netdata/plugins.d/python.d.plugin 1 debug trace`

Will see what is the problem of delay

**Comment by Steve8291** [comment] 2019-04-24 10:53
I've run the debug and you can find the output here. I don't think it matters but my python.d.plugin is located in /usr/libexec/netdata/plugins.d/python.d.plugin
[https://pastebin.com/5PAC4g84](url)
While watching the output I noticed that there are some large hangs. Each one occurs during a
> connecting socket to "::1", port XXXX

Average hang times were from 4-5 minutes and that would explain why it is taking so long to see charts posted to the dashboard. Here are where the biggest waits were:
dovecot (don't even have it installed)
hddtemp (it is installed and I have to wait for it but it is the first to show up in dashboard)
memcached (not installed)
redis (installed and also a long wait to see any charts)
squid (not installed and took about 35 minutes to pass that point)

**Comment by ilyam8** [comment] 2019-04-24 11:22
wrong link

**Closed** 2019-04-25 08:16 UTC
Labels: area/external/python, bug
