### ISSUE TITLE
Monitor if slave is alive

### ISSUE THREAD

**Issue by MoritzFago** [netdata/netdata#3931] opened 2018-07-04 20:58 UTC
I wasn't able to figure out, how i can have an alarm if one of my slave nodes goes away?
Neither in the alarms directory, nor in the wiki i could find what i need to do. Fping doesn't do what i want, i don't want to ping the host, i want to know if it is still delivering stats.

I am unsure if `ipv4.udperrors` does what i want, but it seemed to not fire acordingly (standart conf)

**Comment by finasfinas** [comment] 2018-07-27 15:43
I would like to know when a client ( a machine running netdata ) goes offline. So lets say I have 500 machines all running netdata. I would like to know if it is possible to have a "master" machine that monitors all the others and sends alerts when one of them goes down.
This is similar you your request, right?

**Comment by ktsaou** [comment] 2018-07-27 21:20
Hi,

you have many options:

1. In `stream.conf` of the master, set this setting to `yes`: https://github.com/firehol/netdata/blob/3dd456202d7a39fec9c6cc434ced30f8acd6c25f/conf.d/stream.conf#L103-L110

   The above will trigger a lot of alarms if the slave data stay 5 seconds behind current time. It will also work for all slaves automatically (actually it is defined per API KEY and MACHINE GUID).

2. There is an `httpcheck` plugin that you can configure to check the slave netdata web server (actually it can check any web server, and any number of them concurrently). This will trigger alarms if any is down or slow, or even if it responds with bad content.

3. There is a `portcheck` plugin that you can configure to check if any remote port is open or not. This will also trigger alarms if any is down or slow.

4. There is the `fping` plugin that can measure the network latency and jitter from the master netdata to any other server. This will also trigger alarms if any is down or has increased latency.

**Comment by finasfinas** [comment] 2018-08-02 11:14
I tried the first option, enabling health monitoring for the hosts. What happens is that for instance, I have a host named abcd, and I create an alarm for high cpu usage. it's the only alarm that exists inside health.d. If I push the cpu the alarm is raised and I get a notification via the telegram integration that I made. I also get a notification when the cpu goes back to normal.
the problem: If I stop netdata on the host, the master doesn't notify me of anything. Do I need to create an alarm specifically for this? if so, is there an examble somewhere?

cheers

**Comment by finasfinas** [comment] 2018-08-03 14:13
ok, so being unable to make 1. work, I thought about 2,3 and 4, and they don't work in my case because the netdata master server has no connection to them. The slaves can send data to anywhere but are unable to receive data, meaning I can't test from the internet if  the netdata web port is running, or if the machine responds to pings. The only way here for me to pull this off is such as that the netdata server senses that the slave stopped sending data and raises an alarm because of this.
Unfortunatly, I have no idea on how to make this work. Simply enabling health enabled by default = yes on the master does nothing, or I mean, I shut down netdata on a slave and the master doesn't generate any alarm.

**Comment by finasfinas** [comment] 2018-08-06 15:10
is there a file inside health.d that governs the alarm related to slaves not sending data?

**Comment by tinyhammers** [comment] 2019-06-21 14:43
Sorry to threadjack this a year later...but...

I am trying to achieve the same thing. I have a whole bunch of slaves that are happily streaming to my master, but I've still not been able to get alerts if a slave goes down.
I've changed this setting to `yes`
https://github.com/firehol/netdata/blob/3dd456202d7a39fec9c6cc434ced30f8acd6c25f/conf.d/stream.conf#L103-L110
I've also set `enabled = yes` under `[health]` in the `netdata.conf` file.

However, if I stop Netdata on a slave, the master doesn't raise an alert. This solution seems the best for me, as the `portcheck` or `fping` check will require adding reams of slaves to the conf file. This introduces human error into the chain, as someone (probably me) will likely forget to add a new slave to the conf file.
Most of our machines don't run a webserver, so the `httpcheck` is no good either.

My guess would be with both health settings set to `yes`, if I shut a slave down, or stop Netdata, the master should show an alarm. Is that the expected behaviour?
Am I missing something in the config somewhere?

Failing that, is there some mystical sorcery that can means I can get a dynamic list of the slaves to populate the `portcheck` or `fping` conf files?

Thanks guys, and thanks for Netdata. It's amazing and you should all be very proud :)

**Comment by ilyam8** [comment] 2019-06-21 15:02
> Monitor if slave is alive

This doesn't look `priority/low` for me i would say it is medium or even high. A lot of people use master/slave feature, slave availability check should be built-in ().

@thiagoftsm please take a look. We need to track slave availability for health too.

**Comment by cakrit** [comment] 2019-06-21 15:05
Gracefully stopping a slave means that you won't get an alarm. It's a good thing too that it works this way, check #6266. You will actually get a LOT of alarms if you the slave  just crashes, they are also mentioned in that issue. We can definitely think about a more graceful handling of these cases, so it's not just no alarms or a storm of alarms.

**Comment by ilyam8** [comment] 2019-06-21 15:23
@tinyhammers 

> Failing that, is there some mystical sorcery that can means I can get a dynamic list of the slaves to populate the portcheck or fping conf files?

i see [`info` endpoint](https://registry.my-netdata.io/swagger/#/default/get_info) has `mirrored_hosts` list


```json
{
  "version": "1.11.1_rolling",
  "uid": "24e9fe3c-f2ac-11e8-bafc-0242ac110002",
  "mirrored_hosts": [
    "host1.example.com",
    "host2.example.com"
  ],
  "os_name": "Manjaro Linux",
  "os_id": "manjaro",
  "os_id_like": "arch",
  "os_version": "18.0.4",
  "os_version_id": "unknown",
  "os_detection": "Mixed",
  "kernel_name": "Linux",
  "kernel_version": "4.19.32-1-MANJARO",
  "architecture": "x86_64",
  "virtualization": "kvm",
  "virt_detection": "systemd-detect-virt",
  "container": "docker",
  "container_detection": "dockerenv",
  "collectors": [
    {
      "plugin": "python.d.plugin",
      "module": "dockerd"
    }
  ],
  "alarms": {
    "normal": 0,
    "warning": 0,
    "critical": 0
  }
}
```

**Comment by tinyhammers** [comment] 2019-06-21 15:26
@cakrit Ahh, so you're saying running `service netdata stop` wouldn't trigger an alarm anyway?
Is that the same if I shut the slave down completely?
Desperately trying to find a host I can kill to test, but obviously I'm testing in production, on a Friday afternoon.... #noshitsgiven

**Comment by cakrit** [comment] 2019-06-21 16:30
I haven't tried myself to replicate that behavior, I assume that a `kill -9` would do the trick though... Monitor the error.log. A graceful shutdown shows some very clear messages. A hard kill / crash wouldn't show them.

**Comment by ilyam8** [comment] 2021-07-20 14:04
Closing this feature request. We will re-evaluate the request internally.

**Closed by ilyam8** 2021-07-20 14:04 UTC
Labels: area/docs, feature request, priority/medium
