### ISSUE TITLE
[Bug]:  _Cannot create directory '/var/lib/netdata/registry'  = container restart loop

### ISSUE THREAD

**Issue by jaxjexjox** [netdata/netdata#15075] opened 2023-05-19 06:59 UTC
### Bug description

Upon running the container, it goes into a restart loop, the logs reveal the following error:

```
2023-05-19 06:51:48: netdata INFO  : MAIN : NETDATA STARTUP: in       0 ms, initialize threads after fork - next: initialize registry
 # : Invalid argument
2023-05-19 06:51:48: netdata FATAL : netdata : **_Cannot create directory '/var/lib/netdata/registry'._**
2023-05-19 06:51:48: netdata INFO  : MAIN : NETDATA SHUTDOWN: initializing shutdown with code 
```

My command to run the container is as follows:

```
sudo docker run -d --name=netdata \
-p 19999:19999 \
-v /dockerconfigs/netdata/config:/etc/netdata \
-v /dockerconfigs/netdata/lib:/var/lib/netdata \
-v /dockerconfigs/netdata/cache:/var/cache/netdata \
-v /etc/passwd:/host/etc/passwd:ro \
-v /etc/group:/host/etc/group:ro \
-v /proc:/host/proc:ro \
-v /sys:/host/sys:ro \
-v /etc/os-release:/host/etc/os-release:ro \
--restart unless-stopped \
--cap-add SYS_PTRACE \
--security-opt apparmor=unconfined \
netdata/netdata
```

### Expected behavior

Container to start.

### Steps to reproduce

1. See command above in description.
2.
3.
...

### Installation method

docker

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.2 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
scott@ubuntuserver:/run/user/1000$
```

### Netdata build info

```shell
Suspect this is not important 04:56pm Melbourne time, latest docker container.
```

### Additional info

Quite possible I'm missing a dependency? One would imagine though that your container would have enough permissions to create a folder itself within the container.

Let me know if I can provide more information, quite possible with my skills, this is something simple my end.

**Comment by ilyam8** [comment] 2023-05-19 14:52
Hi, @jaxjexjox. Make sure Netdata has read/write permissions on the directories on the host machine mounted in the container (`/dockerconfigs/netdata/`).

Duplicate of #14215

**Closed** 2023-05-19 14:53 UTC
Labels: bug, duplicate, docker

**Comment by jaxjexjox** [comment] 2023-05-20 06:16
10,000% has permissions to write to this folder.


```
jaxjexjox@ubuntuserver:~$ sudo docker stop netdata && sudo docker rm netdata && sudo rm -R /dockerconfigs/netdata/
netdata
netdata
jaxjexjox@ubuntuserver:~$ sudo docker run -d --name=netdata -p 19999:19999 -e PUID=1000 -e PGID=1000 -v /dockerconfigs/netdata/config:/etc/netdata **-v /dockerconfigs/netdata/lib**:/var/lib/netdata -v /dockerconfigs/netdata/cache:/var/cache/netdata -v /etc/passwd:/host/etc/passwd:ro -v /etc/group:/host/etc/group:ro -v /proc:/host/proc:ro -v /sys:/host/sys:ro -v /etc/os-release:/host/etc/os-release:ro --restart unless-stopped --cap-add SYS_PTRACE --security-opt apparmor=unconfined netdata/netdata
d7d731d1925e024030e98ca1b1266a405b0b66b42358dec91ab70f7f5560c5e2
jaxjexjox@ubuntuserver:~$ :~$ sudo docexec -i netdata mkdir /var/lib/netdata/registrytest                                                                           Error response from daemon: Container d7d731d1925e024030e98ca1b1266a405b0b66b42358dec91ab70f7f5560c5e2 is **restarting**, wait until the container is running
jaxjexjox@ubuntuserver:~$ sudo docker exec -i netdata mkdir /var/lib/netdata/registrytest
Error response from daemon: Container d7d731d1925e024030e98ca1b1266a405b0b66b42358dec91ab70f7f5560c5e2 is **restarting**, wait until the container is running
jaxjexjox@ubuntuserver:~$ sudo docker exec -i netdata mkdir /var/lib/netdata/registrytest
Error response from daemon: Container d7d731d1925e024030e98ca1b1266a405b0b66b42358dec91ab70f7f5560c5e2 is **restarting**, wait until the container is running
jaxjexjox@ubuntuserver:~$ **sudo docker exec -i netdata mkdir /var/lib/netdata/registrytest**
jaxjexjox@ubuntuserver:~$ ls /dockerconfigs/netdata/lib/
cloud.d/                 dbengine_multihost_size  lock/                    **registrytest**/
jaxjexjox@ubuntuserver:~$ ls /dockerconfigs/netdata/lib/
cloud.d/                 dbengine_multihost_size  lock/                    registrytest/
jaxjexjox@ubuntuserver:~$ ls /dockerconfigs/netdata/lib/

```
