### ISSUE TITLE
New Chart with all vnet interfaces

### ISSUE THREAD

**Issue by benmcguire79** [netdata/netdata#3999] opened 2018-07-24 02:15 UTC
Hello

Thanks for the great tool.

I am looking for a way to add a new chart with all our vnet interfaces  and view them in a single chart and then be able to hover over the chart and see ( via vnet name ) which interface is using the bandwidth.
I have viewed the code but am having issues with naming the correct interfaces. All vnet interfaces are named such as vnet100, vnet101  ect. 

Any tips for the correct chart code would be apprecited.

**Comment by cakrit** [comment] 2018-11-24 16:38
This requires a query functionality to aggregate dimensions across charts, that netdata currently lacks. We will be looking into this in the future and would appreciate any relevant contributions.

**Comment by ilyam8** [comment] 2021-07-20 14:13
Duplicate of #2359

**Closed by ilyam8** 2021-07-20 14:13 UTC
Labels: area/web, feature request, help wanted, priority/low
