### ISSUE TITLE
netdata.conf option netdata cloud is misplaced

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#8772] opened 2020-04-20 11:47 UTC
There is the `netdata.conf` option:

```
[global]
   netdata cloud = coming soon
```

To follow the conventions we have so far, it should be:

```
[cloud]
   enabled = boolean
```

and the default should be `yes` if the agent is claimed. So, there should be no need to enable the cloud. Just claim the agent and you are done.

**Comment by amoss** [comment] 2020-04-21 11:49
This is not a bug and it is not something to be fixed. There is a specific reason that we have done that way. After the release it will be a boolean value, before then we must have an extra value to indicate that the agent generated its config before the default was changed.

**Comment by amoss** [comment] 2020-04-21 11:50
We can change the two values from `enable` and `disable` to `true` and `false` as requested but the third value must stay for now.

**Comment by ilyam8** [comment] 2020-04-21 12:51
It is pretty common to use `yes`/`no` instead of `true`/`false` in configuration files. I find it more easire to follow. Probably it is me.

**Comment by amoss** [comment] 2020-04-21 13:23
I set it originally to use `enable` / `disable` but in hindsight that was a terrible choice as it is very easy to make a mistake between `enable` and `enabled`. I don't mind the distinction between `true` / `false` and `yes` / `no` - but as @ktsaou points out we have a convention.

**Comment by amoss** [comment] 2020-04-21 18:31
@joelhans We need to update the docs again :)

**Comment by joelhans** [comment] 2020-04-21 19:54
@amoss I can put up a PR, but let me take a moment to make sure I fully understand what's going to happen before I do so. For example, in the ACLK doc, we explain how to disable the ACLK:

**Before**

```conf
[global]
    netdata cloud = disable
```

**After**

```conf
[cloud]
    netdata cloud = false
```

Is this correct?

**Comment by amoss** [comment] 2020-04-21 20:19
@netdata/product please be aware of this change which be merged into the agent later this week as it will affect any last-minute tests you are running.

@netdata/infra this will also affect the operation of the local dev env.

**Comment by amoss** [comment] 2020-04-22 08:33
@joelhans The convention in the code is `yes` and `no`, so the new setting will be:

```
[cloud]
    enabled = yes
```
(@knatsakis)

**Comment by knatsakis** [comment] 2020-04-22 09:26
@joelhans it doesn't seem correct.

I *think* it will be
```
[cloud]
    enabled = no
```

**Comment by knatsakis** [comment] 2020-04-22 09:27
Oh @amoss beat me to it

**Comment by joelhans** [comment] 2020-04-22 13:02
@amoss @knatsakis Yes/no it is then. I didn't mean to assert a different standard, I just didn't had trouble following exactly what my TODO was going to be based on the conversation above.

**Comment by amoss** [comment] 2020-04-28 12:09
This is implemented in the go-live branch.

**Closed by amoss** 2020-04-28 12:09 UTC
