### ISSUE TITLE
Netdata keeps updating even if there is no new version

### ISSUE THREAD

**Issue by skibbipl** [netdata/netdata#10555] opened 2021-01-26 08:18 UTC
##### Bug report summary
Every day when cron updater is ran netdata updates itself:
```
# /etc/cron.daily/netdata-updater
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
Checking if a newer version of the updater script is available.
Entering /tmp/netdata-updater-BwrqtahKHb

  ^
  |.-.   .-.   .-.   .-.   .  netdata
  |   '-'   '-'   '-'   '-'   real-time performance monitoring, done right!
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  (C) Copyright 2017, Costa Tsaousis
  All rights reserved
  Released under GPL v3+

  You are about to install netdata to this system.
  netdata will be installed at:

                    /opt/netdata
...
```

##### OS / Environment
```
Linux server 5.10.0-1-amd64 #1 SMP Debian 5.10.5-1 (2021-01-09) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux bullseye/sid"
```

##### Netdata version
netdata v1.28.0

##### Component Name
Updater

##### Steps To Reproduce
1. Install netdata stable as static binary file `bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh)`
2. Wait for cron job to execute netdata updater

##### Expected behavior
Netdata updates itself only when there is a new version available.

**Comment by stelfrag** [comment] 2021-01-26 08:39
Hi @skibbipl 

Thank you for reporting this!!

@Ferroin please have a look.

**Comment by Ferroin** [comment] 2021-01-26 12:34
Unless you specifically ask for the stable version (by adding `--stable` to the install command), this is expected behavior, as it will be looking at nightly versions not stable releases.

**Comment by skibbipl** [comment] 2021-01-26 12:49
Yes, I intalled netdata with --stable flag.

**Comment by Ferroin** [comment] 2021-01-26 12:53
@skibbipl could you please share the contents of `/etc/netdata/.environment` and the output of `netdata -W buildinfo` on the system where you are seeing this issue?

**Comment by skibbipl** [comment] 2021-01-26 13:36
Hi, I do not have `/etc/netdata/.environment`.
```
# /opt/netdata/bin/netdata -W buildinfo
Version: netdata v1.28.0
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc'                                                                                                                                                                                                '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--li                                                                                                                                                                                               bdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--                                                                                                                                                                                               enable-cloud' '--with-bundled-lws=externaldeps/libwebsockets' '--with-libJudy=ex                                                                                                                                                                                               ternaldeps/libJudy' 'CFLAGS=-static -O3 -I/openssl-static/include' 'LDFLAGS=-sta                                                                                                                                                                                               tic -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

**Comment by Ferroin** [comment] 2021-01-26 14:31
> Hi, I do not have /etc/netdata/.environment.

Ah, sorry, missed the fact that you’re using a static install. In that case it should be `/opt/netdata/etc/netdata/.environment`

**Comment by skibbipl** [comment] 2021-01-26 14:34
```
# cat /opt/netdata/etc/netdata/.environment
# Created by installer
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
CFLAGS="-static -O3 -I/openssl-static/include"
LDFLAGS="-static -L/openssl-static/lib"
NETDATA_PREFIX="/opt/netdata"
NETDATA_CONFIGURE_OPTIONS=" --enable-cloud --with-bundled-lws=externaldeps/libwebsockets --with-libJudy=externaldeps/libJudy"
NETDATA_ADDED_TO_GROUPS=" adm squid nobody"
INSTALL_UID="0"
NETDATA_GROUP="netdata"
REINSTALL_OPTIONS=" --auto-update --stable-channel --disable-telemetry"
RELEASE_CHANNEL="stable"
IS_NETDATA_STATIC_BINARY="yes"
NETDATA_LIB_DIR="/opt/netdata/var/lib/netdata"
```

**Comment by stelfrag** [comment] 2021-04-13 12:17
@ferroin is this issue still valid for investigation?

**Comment by Ferroin** [comment] 2021-04-13 12:32
Yes, it just got kind of lost among other stuff I was working on. I need to get back to trying to reproduce it.

**Comment by stelfrag** [comment] 2021-12-03 10:42
Should we close this?

**Comment by skibbipl** [comment] 2021-12-03 11:18
I switched to debian packaged version of netdata so the issue is not affecting me anymore. But I guess if updater wasn't changed the issue is still there...

**Comment by ilyam8** [comment] 2021-12-03 11:51
I checked and the problem still exists for both static and compiled (if `netdata` is not in PATH) versions.

**Comment by iigorkarpov** [comment] 2021-12-03 14:34
Just checked using copy of `netdata-updater` on Debian (toronto.my-netdata.io). That doesn't seem to be the case.

**Comment by Ferroin** [comment] 2021-12-06 13:59
Hmm, so IOW it sounds like this is only an issue if the `netdata` binary is not in `$PATH`?

I suspect it has something to do with the version detection logic then. I think we query the `netdata` binary to get the current version, and if that fails we assume a version of `0.0.0`, which always triggers an update because it always compares less than the current version.

**Comment by Ferroin** [comment] 2021-12-06 14:03
Yep, confirmed, we’re blindly assuming that there will be a `netdata` binary in the user’s search path, and defaulting to `0.0.0` for the effective version if it’s not there. I’ll get started on a fix.

**Comment by Ferroin** [comment] 2021-12-06 14:04
Correction, we’re blindly assuming this for regular installs.

The issue with static installs is different (we don’t check versions at all there, and just assume we always need to update), but I can cover that in the same fix.

**Closed** 2021-12-17 14:51 UTC
Labels: bug, area/packaging, priority/medium
