### ISSUE TITLE
[Bug]: Netdata through helm setup doesn't start on k8s

### ISSUE THREAD

**Issue by pcm32** [netdata/netdata#13994] opened 2022-11-14 12:53 UTC
### Bug description

After executing:

```
helm repo add netdata https://netdata.github.io/helmchart/

helm install netdata netdata/netdata   --set parent.claiming.enabled="true"   --set parent.claiming.token=<my-token>   --set child.claiming.enabled="true"   --set child.claiming.token=<my-other-token>
```

as instructed by the netdata room page, the pods never reach readiness and keep restarting:

```
kubectl get pods
NAME                                       READY   STATUS             RESTARTS        AGE
netdata-child-29cn8                        1/2     CrashLoopBackOff   7 (4m38s ago)   19m
netdata-child-hk2vz                        1/2     CrashLoopBackOff   7 (5m8s ago)    19m
netdata-child-mgh8j                        1/2     CrashLoopBackOff   7 (4m38s ago)   19m
netdata-k8s-state-5d9468cbdd-kj4x2         0/1     CrashLoopBackOff   7 (36s ago)     19m
netdata-parent-6768b65c44-ws5vg            1/1     Running            2 (6m6s ago)    19m
```

and all nodes appear offline on the netdata cloud UI. Please note that netdata-parent iterates between ready and not ready.

netdata-k8s-state tends to fail with:

```
2022-11-14 11:22:18: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2022-11-14 11:22:18: netdata ERROR : MAIN : Ignoring host prefix '/host': path '/host/proc' failed to statfs() (errno 2, No such file or directory)
2022-11-14 11:22:18: netdata INFO  : MAIN : TIMEZONE: using strftime(): 'UTC'
2022-11-14 11:22:18: netdata INFO  : MAIN : TIMEZONE: fixed as 'UTC'
2022-11-14 11:22:18: netdata INFO  : MAIN : SIGNAL: Enabling reaper
2022-11-14 11:22:18: netdata INFO  : MAIN : process tracking enabled.
2022-11-14 11:22:18: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1073741816, max = 1073741816
2022-11-14 11:22:18: netdata INFO  : MAIN : Out-Of-Memory (OOM) score is already set to the wanted value 1000
2022-11-14 11:22:18: netdata ERROR : MAIN : Cannot adjust netdata scheduling policy to batch (3), with priority 0. Falling back to nice. (errno 38, Function not implemented)
2022-11-14 11:22:18: netdata ERROR : MAIN : Cannot get my current process scheduling policy. (errno 38, Function not implemented)
2022-11-14 11:22:18: netdata INFO  : MAIN : netdata started on pid 1.
2022-11-14 11:22:18: netdata INFO  : MAIN : Initializing spawn client.
2022-11-14 11:22:18: netdata INFO  : MAIN : Executing /usr/libexec/netdata/plugins.d/system-info.sh
```
and
```
Normal   Pulling                 27m (x2 over 29m)     kubelet                  Pulling image "netdata/netdata:v1.36.1"
  Normal   Pulled                  27m                   kubelet                  Successfully pulled image "netdata/netdata:v1.36.1" in 1.346413202s
  Normal   Created                 27m (x2 over 29m)     kubelet                  Created container netdata
  Normal   Started                 27m (x2 over 29m)     kubelet                  Started container netdata
  Warning  Unhealthy               26m (x4 over 28m)     kubelet                  Liveness probe failed: Get "http://10.100.225.77:19999/api/v1/info": dial tcp 10.100.225.77:19999: connect: connection refused
  Warning  Unhealthy               19m                   kubelet                  Readiness probe failed: Get "http://10.100.225.77:19999/api/v1/info": read tcp 10.0.0.216:37254->10.100.225.77:19999: read: connection reset by peer
  Warning  BackOff                 9m36s (x22 over 15m)  kubelet                  Back-off restarting failed container
  Warning  Unhealthy               4m31s (x64 over 29m)  kubelet                  Readiness probe failed: Get "http://10.100.225.77:19999/api/v1/info": dial tcp 10.100.225.77:19999: connect: connection refused
```

netdata-parent fails with:
```
2022-11-14 11:29:46: netdata ERROR : MAIN : Ignoring host prefix '/host': path '/host/proc' failed to statfs() (errno 2, No such file or directory)
2022-11-14 11:29:46: netdata INFO  : MAIN : TIMEZONE: using strftime(): 'UTC'
2022-11-14 11:29:46: netdata INFO  : MAIN : TIMEZONE: fixed as 'UTC'
2022-11-14 11:29:46: netdata INFO  : MAIN : SIGNAL: Enabling reaper
2022-11-14 11:29:46: netdata INFO  : MAIN : process tracking enabled.
2022-11-14 11:29:46: netdata INFO  : MAIN : resources control: allowed file descriptors: soft = 1073741816, max = 1073741816
2022-11-14 11:29:46: netdata INFO  : MAIN : Out-Of-Memory (OOM) score is already set to the wanted value 1000
2022-11-14 11:29:46: netdata ERROR : MAIN : Cannot adjust netdata scheduling policy to batch (3), with priority 0. Falling back to nice. (errno 38, Function not implemented)
2022-11-14 11:29:46: netdata ERROR : MAIN : Cannot get my current process scheduling policy. (errno 38, Function not implemented)
2022-11-14 11:29:46: netdata INFO  : MAIN : netdata started on pid 1.
2022-11-14 11:29:46: netdata INFO  : MAIN : Initializing spawn client.
2022-11-14 11:29:46: netdata INFO  : MAIN : Executing /usr/libexec/netdata/plugins.d/system-info.sh
...
# then sometimes reaches
2022-11-14 11:31:34: netdata INFO  : MAIN : File '/var/lib/netdata/cloud.d/claimed_id' was found. Setting state to AGENT_CLAIMED.
Spawn server is up.
```

and it shows readiness and liveness always unhealthy:
```
Warning  Unhealthy               12m (x17 over 25m)    kubelet                  Readiness probe failed: Get "http://10.100.225.78:19999/api/v1/info": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy               7m57s (x10 over 27m)  kubelet                  Liveness probe failed: Get "http://10.100.225.78:19999/api/v1/info": dial tcp 10.100.225.78:19999: connect: connection refused
  Normal   Pulling                 115s (x5 over 28m)    kubelet                  Pulling image "netdata/netdata:v1.36.1"
```

netdata-child shows:
```
Defaulted container "netdata" out of: netdata, sd, init-persistence (init)
Netdata detected docker.sock
Creating docker group 982
Assign netdata user to docker group 982
```

### Expected behavior

That nodes would be visible on netdata cloud (and that pods would all be ready on kubectl).

### Steps to reproduce

1.
2.
3.
...

### Installation method

helmchart (kubernetes)

### System info

```shell
/etc/fedora-release:Fedora release 35 (Thirty Five)
/etc/os-release:NAME="Fedora Linux"
/etc/os-release:VERSION="35.20220410.3.1 (CoreOS)"
/etc/os-release:ID=fedora
/etc/os-release:VERSION_ID=35
/etc/os-release:VERSION_CODENAME=""
/etc/os-release:PLATFORM_ID="platform:f35"
/etc/os-release:PRETTY_NAME="Fedora CoreOS 35.20220410.3.1"
/etc/os-release:ANSI_COLOR="0;38;2;60;110;180"
/etc/os-release:LOGO=fedora-logo-icon
/etc/os-release:CPE_NAME="cpe:/o:fedoraproject:fedora:35"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Fedora"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=35
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Fedora"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION=35
/etc/os-release:VARIANT="CoreOS"
/etc/os-release:VARIANT_ID=coreos
/etc/os-release:OSTREE_VERSION='35.20220410.3.1'
/etc/os-release:DEFAULT_HOSTNAME=localhost
/etc/redhat-release:Fedora release 35 (Thirty Five)
/etc/system-release:Fedora release 35 (Thirty Five)
```

### Netdata build info

```shell
Doesn't seem to be on the nodes, but this is image netdata/netdata:v1.36.1
```

### Additional info

Also, when logging into one of the k8s master nodes, the netdata process was using >90% of CPU. Kubernetes cluster version 1.23.6, using containerd.

**Comment by aarushisoni** [comment] 2022-11-14 14:09
Hi! I would like to contribute to this issue.

**Comment by MrZammler** [comment] 2022-11-16 15:01
Hi @pcm32 

Thanks for the report.

So is `Executing /usr/libexec/netdata/plugins.d/system-info.sh` the last thing you see on the logs? Is there more after that?

**Comment by pcm32** [comment] 2022-11-16 16:25
I think that this is specific to using CoreOS as image for the VMs in the
k8s hosts. Moving away from CoreOS into rke2 with Ubuntu has removed this
problem. We noticed other helm charts having issues with file descriptors
(/dev/null) with CoreOS.

**Comment by Dim-P** [comment] 2022-11-22 17:52
Hi @pcm32 , thank you for reporting this.

I spent some time today on this issue (setting up Fedora CoreOS as a VM - not as straightforward as I thought it'd be!). 

First off, a wild guess, but Kubernetes troubleshooting reports that [/usr is mounted read-only on nodes](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#usr-mounted-read-only). No idea why this would be causing an issue (I don't believe it is mounted by the Netdata pods), but worth investigating if CoreOS shows other idiosyncrasies like this one that could affect helm's functionality (like the one you mentioned about file descriptors).

Other than that, while my `netdata-child-*` was started (and crashed as yours did), `netdata-k8s-state-*` and `netdata-parent-*` were stuck at `Pending`, since they had `unbound immediate PersistentVolumeClaims`. Did you see that as well and if so, how did you go past that issue?

Finally, where do you run CoreOS on and could you also please provide the output of `kubectl describe pods netdata` ?

**Comment by pcm32** [comment] 2022-11-23 07:25
> netdata-k8s-state-* and netdata-parent-* were stuck at Pending, since they had unbound immediate PersistentVolumeClaims

Yes, saw that as well. Unfortunately I stopped using that k8s setup as I was running into problems due to CoreOS on other deployments as well. So I can't check easily what you ask for :-(. But thanks for taking a look at this.

**Comment by pcm32** [comment] 2022-11-23 07:26
This was on an OpenStack setup, using Magnum as k8s deployer.

**Comment by Dim-P** [comment] 2022-11-24 12:25
@pcm32 Thanks for the update. 

Since:

1. Fedora CoreOS is not in our [list of officially support platforms](https://learn.netdata.cloud/docs/agent/packaging/platform_support).
2. You saw issues with other deployments there, so the issue isn't probably specific to Netdata.
3. You don't have the setup to reproduce it anymore.
4. And most importantly , you got it working using Ubuntu as VMs in the k8s hosts.

I will proceed with closing this issue for the time being. If you or any other users want us to investigate it further in the future, please comment here and I will then reopen it and continue debugging.

**Closed by Dim-P** 2022-11-24 12:25 UTC
Labels: bug, wontfix, K8s
