### ISSUE TITLE
/etc/cron.daily/netdata-updater: line 168: [: : integer expression expected

### ISSUE THREAD

**Issue by skibbipl** [netdata/netdata#10420] opened 2020-12-23 14:41 UTC
##### Bug report summary
There is some problem with netdata updater. I have 2 raspberry pis and on both I'm getting the same error.
```
 # /etc/cron.daily/netdata-updater
Checking if a newer version of the updater script is available.
date: invalid date ‘9999-12-31T23:59:59Z’
/etc/cron.daily/netdata-updater: line 168: [: : integer expression expected
Wed Dec 23 15:36:43 CET 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Wed Dec 23 15:36:44 CET 2020 : INFO:  Current Version: 00102800000010
Wed Dec 23 15:36:44 CET 2020 : INFO:  Latest Version: 00102800000010
Wed Dec 23 15:36:44 CET 2020 : INFO:  Newest version (current=00102800000010 >= latest=00102800000010) is already installed
```
##### OS / Environment
```
Linux rpi4b 5.4.79-v8+ #1373 SMP PREEMPT Mon Nov 23 13:32:41 GMT 2020 aarch64 GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux bullseye/sid"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version
netdata v1.28.0-10-nightly

##### Component Name
netdata-updater

##### Steps To Reproduce
run `/etc/cron.daily/netdata-updater`

##### Expected behavior
No errors

**Comment by Lamera** [comment] 2020-12-27 22:52
Same issue #10417

**Comment by Lamera** [comment] 2020-12-27 22:52
Duplicate of #10417

**Comment by underhood** [comment] 2021-01-04 10:13
@Lamera is correct this is duplicate.
@skibbipl closing this as duplicate of #10417 to track the issue in single place. Thank you reporting and contributing PR with possible fix.

**Closed by underhood** 2021-01-04 10:13 UTC
Labels: bug, needs triage
