### ISSUE TITLE
Installation of Debian package from new repo fails due to missing dependency

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#6774] opened 2019-09-04 06:54 UTC
##### Bug report summary
I try to install the new packages from dedicated repo https://packagecloud.io/netdata/netdata.
However there's a dependency to a package that is not available in Debian:
_libprotoc10_
```
root@ld5506:~# apt install netdata
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 netdata : Hängt ab von: libprotoc10 ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
```

Checking for available packages I get this similar: 
_libprotoc17_
```
root@ld5506:~# apt search libprotoc
Sortierung... Fertig
Volltextsuche... Fertig
libprotoc-dev/stable,testing,unstable 3.6.1.3-2 amd64
  Compiler-Bibliothek für Protocol Buffers (Entwicklungsdateien)

libprotoc17/stable,testing,unstable 3.6.1.3-2 amd64
  Compiler-Bibliothek für Protocol Buffers

libprotocol-acme-perl/stable,testing,unstable 1.01-3 all
  Perl Interface to the Let's Encrypt ACME API

libprotocol-http2-perl/stable,testing,unstable 1.09-1 all
  HTTP/2 protocol implementation with client and server libraries

libprotocol-irc-perl/stable,testing,unstable 0.12-2 all
  IRC protocol handling

libprotocol-osc-perl/stable,testing,unstable 0.09-1 all
  module to implement (de)coding and processing of OSC packets
```

Please advise how to fix this?

##### OS / Environment
Debian 10 (buster)

##### Expected behavior
Installation of netdata 1.17 incl. all dependencies.

**Comment by mfundul** [comment] 2019-09-04 08:09
I confirmed the problem in Debian 10. Moreover it's possible there are no packages in Debian 8 since I cannot install netdata either:
```
root@debian8-test:~# apt-get install netdata
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package netdata
```
It works for Debian 9 though.

**Comment by cakrit** [comment] 2019-09-04 09:15
@Ferroin can you help with this one?

**Comment by Ferroin** [comment] 2019-09-04 11:44
It looks to me like Debian 10 just has a newer version of Google's protobuf libraries.  I suspect that libprotoc17 will work as-is, but I'm not 100% certain.

**Comment by 74cmonty** [comment] 2019-09-04 11:45
Installation of netdata fails if _libprotoc17_ is installed though.

**Comment by Ferroin** [comment] 2019-09-04 12:00
> Installation of netdata fails if libprotoc17 is installed though.

Because it's a different package name that the current Netdata package for Debian 10 is depending on.  What I meant was that if we update the dependency in the Netdata package for Debian 10, I suspect that it will just work with libprotoc17.

**Comment by paulkatsoulakis** [comment] 2019-09-04 12:06
I am on it

**Comment by 74cmonty** [comment] 2019-09-04 12:06
Understood.
If you provide a new version w/o dependency on _libprotoc10_ I can test it.

**Comment by paulkatsoulakis** [comment] 2019-09-04 12:40
@mfundul There is a sneaky error on debian/jessie that did not allow package to be generated on debian/jessie. I am working on it as we speak.

**Comment by 74cmonty** [comment] 2019-09-04 14:10
I'm not sure if you need to provide netdata for a Debian release that is not supported anymore: Debian 8 aka Jessie

**Comment by paulkatsoulakis** [comment] 2019-09-04 14:29
> I'm not sure if you need to provide netdata for a Debian release that is not supported anymore: Debian 8 aka Jessie

We follow the LTS support schedule from the distribution vendors (link: https://wiki.debian.org/LTS)
Jessie is on LTS support until 2020

**Comment by cakrit** [comment] 2019-09-05 07:33
The nightly build with the change @paulkatsoulakis made will be completed in about 4-5 hours. 
Let's see if the latest binary package resolves the issue. We have another for Ubuntu (#6784), after we resolve that one as well we'll need to do a patch release to ensure we have correct binaries on packagecloud.

**Comment by 74cmonty** [comment] 2019-09-05 14:31
Can you estimate by when the new deb-package will be available in repo?
I can't find any newly released packages as of now.

**Comment by cakrit** [comment] 2019-09-09 13:38
@74cmonty have you tried getting the latest from https://packagecloud.io/netdata/netdata-edge ? 
I'd like to release 1.17.1 tomorrow, so we can have them on the stable channel as well.

**Comment by 74cmonty** [comment] 2019-09-10 11:30
Hello,
I didn't test a release from netdata-edge.
However I managed to install the stable package by manipulating the dependencies after unpacking / repacking the package.

**Comment by agrimal** [comment] 2019-09-10 12:20
I just installed 1.17.35 on a fresh debian buster without any problem.

**Comment by paulkatsoulakis** [comment] 2019-09-10 13:13
> I disabled the cups service and netdata is still running and restarting.

Hello @agrimal, you are right wondering.
We have open PRs under review to separate CUPS plugin functionality completely on our binary packages.
When we got out our initial version, there was a thought to get all functionality bundled in, which proved to be a bad idea, especially for CUPS that is pulling in too many dependencies.
We are currently working on separating the various plugins to sub packages, where applicable.

**Comment by agrimal** [comment] 2019-09-10 13:46
Yep indeed netdata is supposed to be lightweight service but pulls 200 MB data from repos to be installed which is not what people want (french installer) :

```bash
root@myserver [~] # apt install netdata/buster
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Version choisie « 1.17.35 » (netdata-edge:1/buster [amd64]) pour « netdata »
Les paquets supplémentaires suivants seront installés : 
  acl avahi-daemon colord colord-data cups cups-browsed cups-client cups-common cups-core-drivers cups-daemon cups-filters cups-filters-core-drivers cups-ipp-utils cups-ppdc
  cups-server-common dbus-user-session dconf-gsettings-backend dconf-service fontconfig-config fonts-dejavu-core fonts-droid-fallback fonts-noto-mono freeipmi freeipmi-bmc-watchdog
  freeipmi-common freeipmi-ipmidetect freeipmi-tools ghostscript gsfonts libavahi-client3 libavahi-common-data libavahi-common3 libavahi-core7 libavahi-glib1 libcairo2 libcolord2
  libcolorhug2 libcups2 libcupsfilters1 libcupsimage2 libdaemon0 libdconf1 libexif12 libfontconfig1 libfontembed1 libfreeipmi17 libgd3 libgphoto2-6 libgphoto2-l10n libgphoto2-port12 libgs9
  libgs9-common libgudev-1.0-0 libgusb2 libgutenprint-common libgutenprint9 libieee1284-3 libijs-0.35 libipmiconsole2 libipmidetect0 libipmimonitoring6 libjbig0 libjbig2dec0
  libjpeg62-turbo libjudydebian1 liblcms2-2 liblouis-data liblouis17 liblouisutdml-bin liblouisutdml-data liblouisutdml8 libltdl7 libmariadb3 libnetfilter-acct1 libnspr4 libnss-mdns
  libnss3 libopenjp2-7 libpam-systemd libpaper-utils libpaper1 libpixman-1-0 libpolkit-agent-1-0 libpolkit-backend-1-0 libpolkit-gobject-1-0 libpoppler82 libprotobuf17 libprotoc17
  libqpdf21 libsane libsane-common libsensors-config libsensors5 libsnappy1v5 libsnmp-base libsnmp30 libtiff5 libuv1 libwebp6 libx11-6 libx11-data libxau6 libxcb-render0 libxcb-shm0
  libxcb1 libxdmcp6 libxext6 libxpm4 libxrender1 libyaml-0-2 mariadb-common mysql-common policykit-1 poppler-data poppler-utils printer-driver-gutenprint sane-utils update-inetd
Paquets suggérés :
  avahi-autoipd colord-sensor-argyll cups-bsd foomatic-db-compressed-ppds | foomatic-db printer-driver-hpcups hplip cups-pdf smbclient antiword docx2txt imagemagick fonts-noto
  ghostscript-x libgd-tools gphoto2 gutenprint-locales liblcms2-utils ooo2dbk rtf2xml avahi-autoipd | zeroconf lm-sensors snmp-mibs-downloader fonts-japanese-mincho | fonts-ipafont-mincho
  fonts-japanese-gothic | fonts-ipafont-gothic fonts-arphic-ukai fonts-arphic-uming fonts-nanum gutenprint-doc unpaper
Les NOUVEAUX paquets suivants seront installés :
  acl avahi-daemon colord colord-data cups cups-browsed cups-client cups-common cups-core-drivers cups-daemon cups-filters cups-filters-core-drivers cups-ipp-utils cups-ppdc
  cups-server-common dbus-user-session dconf-gsettings-backend dconf-service fontconfig-config fonts-dejavu-core fonts-droid-fallback fonts-noto-mono freeipmi freeipmi-bmc-watchdog
  freeipmi-common freeipmi-ipmidetect freeipmi-tools ghostscript gsfonts libavahi-client3 libavahi-common-data libavahi-common3 libavahi-core7 libavahi-glib1 libcairo2 libcolord2
  libcolorhug2 libcups2 libcupsfilters1 libcupsimage2 libdaemon0 libdconf1 libexif12 libfontconfig1 libfontembed1 libfreeipmi17 libgd3 libgphoto2-6 libgphoto2-l10n libgphoto2-port12 libgs9
  libgs9-common libgudev-1.0-0 libgusb2 libgutenprint-common libgutenprint9 libieee1284-3 libijs-0.35 libipmiconsole2 libipmidetect0 libipmimonitoring6 libjbig0 libjbig2dec0
  libjpeg62-turbo libjudydebian1 liblcms2-2 liblouis-data liblouis17 liblouisutdml-bin liblouisutdml-data liblouisutdml8 libltdl7 libmariadb3 libnetfilter-acct1 libnspr4 libnss-mdns
  libnss3 libopenjp2-7 libpam-systemd libpaper-utils libpaper1 libpixman-1-0 libpolkit-agent-1-0 libpolkit-backend-1-0 libpolkit-gobject-1-0 libpoppler82 libprotobuf17 libprotoc17
  libqpdf21 libsane libsane-common libsensors-config libsensors5 libsnappy1v5 libsnmp-base libsnmp30 libtiff5 libuv1 libwebp6 libx11-6 libx11-data libxau6 libxcb-render0 libxcb-shm0
  libxcb1 libxdmcp6 libxext6 libxpm4 libxrender1 libyaml-0-2 mariadb-common mysql-common netdata policykit-1 poppler-data poppler-utils printer-driver-gutenprint sane-utils update-inetd
0 mis à jour, 119 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 52,8 Mo dans les archives.
Après cette opération, 197 Mo d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] 
```

**Comment by paulkatsoulakis** [comment] 2019-09-11 13:32
Yep, for CUPS we have PRs under review to separate it from the main package
https://github.com/netdata/netdata/pull/6724
https://github.com/netdata/netdata/pull/6700

**Comment by paulkatsoulakis** [comment] 2019-10-01 11:04
Hello, it occurred to me that we haven't followed up on this matter after merging the said changes.
@74cmonty latest packages should already fix the CUPS dependency issue.
Feel free to try and let us know if you face any issues.

Thanks again for reaching out!

**Comment by cosmix** [comment] 2019-11-18 21:02
This seems to be fixed, but we need to confirm @knatsakis.

**Comment by 74cmonty** [comment] 2019-11-19 08:18
Hello,
in my opinion this issue is fixed because
a) I can now uninstall cups packages (and its dependencies) w/o uninstalling netdata
b) Output of _apt-cache depends netdata_ shows no dependency on cups
```
root@ld5505:~# apt-cache depends netdata
netdata
  PreDepends: dpkg
  Depends: adduser
  Depends: libcap2-bin
  Depends: lsb-base
  Depends: zlib1g
  Depends: libuuid1
  Depends: libuv1
  Depends: liblz4-1
  Depends: libjudydebian1
  Depends: openssl
  Depends: libmnl0
  Depends: libjson-c3
  Depends: freeipmi
  Depends: libnetfilter-acct1
  Depends: libprotobuf-c1
  Depends: libsnappy1v5
  Depends: libprotoc17
  Depends: libc6
  Depends: libgcc1
  Depends: libipmimonitoring6
  Depends: libprotobuf17
  Depends: libssl1.1
  Depends: libstdc++6
```

**Comment by Ferroin** [comment] 2019-12-10 12:54
Closing this as both the original issue and the secondary ones brought up in discussion appear to be fixed both based on comments from the author and based on my own testing.

**Closed by Ferroin** 2019-12-10 12:54 UTC
Labels: area/packaging, bug, priority/high
