### ISSUE TITLE
[Bug]: OOM Killer invoked, but not logged/charted?

### ISSUE THREAD

**Issue by Raltrwx** [netdata/netdata#13018] opened 2022-05-26 23:06 UTC
### Bug description

One of my nodes began to run out of memory. The OOM-killer got invoked and killed several Netdata processes (And python3), which got the system back into a working state. However, Netdata didn't record any of this in the OOM-Killer chart. 

You can see in the memory chart the memory growing over a week, then it was suddenly resolved, that's when the OOM-Killer kicked in, but in the 2nd chart it should have a spike for the OOM-Kills.
![Memory](https://user-images.githubusercontent.com/20295023/170592941-e95066c6-8738-45c3-a2dd-1cb4967b50a0.png)

This is somewhat random, but I noticed this chart basically matched the others so thought I should include it. 
![page_cache](https://user-images.githubusercontent.com/20295023/170592949-e5694b00-4b1f-43a8-9210-ca5db82a5ca3.png)

### Expected behavior

Main Goal: When OOM-Killer is invoked, for the "kills" to be represented in the "kills" chart. 

Secondary: Netdata shouldn't "memory leak", like this? Honestly not sure if it is a memory leak, but it seems to look like one. 

### Steps to reproduce

1. I have not been able to reproduce this at all, and it only happened in one of my nodes out of over 200. 

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

### Netdata build info

```shell
Version: netdata v1.34.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

All OOM-Kills that happened:

```
May 26 18:20:56 be-99 kernel: VBoxSVCWatcher cpuset=/ mems_allowed=0
May 26 18:20:50 be-99 kernel: VBoxSVCWatcher invoked oom-killer: gfp_mask=0x14200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
May 26 18:20:38 be-99 kernel: vboxdrv: 0000000000000000 VBoxDDR0.r0
May 26 18:20:38 be-99 kernel: vboxdrv: 0000000000000000 VMMR0.r0

May 26 18:23:16 be-99 kernel: EMT cpuset=/ mems_allowed=0
May 26 18:23:16 be-99 kernel: EMT invoked oom-killer: gfp_mask=0x14200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
May 26 18:23:16 be-99 kernel: oom_reaper: reaped process 26502 (ebpf.plugin), now anon-rss:0kB, file-rss:0kB, shmem-rss:524kB
May 26 18:23:16 be-99 kernel: Killed process 26502 (ebpf.plugin) total-vm:1282928kB, anon-rss:33052kB, file-rss:0kB, shmem-rss:524kB
May 26 18:23:16 be-99 kernel: Out of memory: Kill process 26229 (netdata) score 797 or sacrifice child

May 26 18:23:16 be-99 kernel: EMT cpuset=/ mems_allowed=0
May 26 18:23:16 be-99 kernel: EMT invoked oom-killer: gfp_mask=0x14042c0(GFP_KERNEL|__GFP_NOWARN|__GFP_COMP), nodemask=(null), order=1, oom_score_adj=0
May 26 18:23:16 be-99 kernel: oom_reaper: reaped process 26510 (python3), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
May 26 18:23:16 be-99 kernel: Killed process 26510 (python3) total-vm:141568kB, anon-rss:19516kB, file-rss:0kB, shmem-rss:0kB
May 26 18:23:16 be-99 kernel: Out of memory: Kill process 26229 (netdata) score 797 or sacrifice child

May 26 18:23:16 be-99 kernel: rs:main Q:Reg cpuset=/ mems_allowed=0
May 26 18:23:16 be-99 kernel: rs:main Q:Reg invoked oom-killer: gfp_mask=0x14200ca(GFP_HIGHUSER_MOVABLE), nodemask=(null), order=0, oom_score_adj=0
May 26 18:23:16 be-99 kernel: oom_reaper: reaped process 26512 (go.d.plugin), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
May 26 18:23:16 be-99 kernel: Killed process 26512 (go.d.plugin) total-vm:733852kB, anon-rss:7148kB, file-rss:0kB, shmem-rss:0kB
May 26 18:23:16 be-99 kernel: Out of memory: Kill process 26229 (netdata) score 797 or sacrifice child

May 26 18:23:16 be-99 kernel: sh cpuset=/ mems_allowed=0
May 26 18:23:16 be-99 kernel: sh invoked oom-killer: gfp_mask=0x15080c0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), nodemask=(null), order=1, oom_score_adj=0
May 26 18:23:16 be-99 kernel: Killed process 26504 (apps.plugin) total-vm:46928kB, anon-rss:4968kB, file-rss:104kB, shmem-rss:0kB
May 26 18:23:16 be-99 kernel: Out of memory: Kill process 26229 (netdata) score 797 or sacrifice child

May 26 18:23:16 be-99 kernel: sh cpuset=/ mems_allowed=0
May 26 18:23:16 be-99 kernel: sh invoked oom-killer: gfp_mask=0x15080c0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), nodemask=(null), order=1, oom_score_adj=0
May 26 18:23:16 be-99 kernel: oom_reaper: reaped process 26242 (netdata), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
May 26 18:23:16 be-99 kernel: Killed process 26242 (netdata) total-vm:67724kB, anon-rss:180kB, file-rss:0kB, shmem-rss:0kB
May 26 18:23:16 be-99 kernel: Out of memory: Kill process 26229 (netdata) score 797 or sacrifice child

May 26 18:23:16 be-99 kernel: systemd-udevd invoked oom-killer: gfp_mask=0x15080c0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), nodemask=(null), order=1, oom_score_adj=-1000
May 26 18:23:16 be-99 kernel: oom_reaper: reaped process 15801 (sh), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
May 26 18:23:16 be-99 kernel: Killed process 15801 (sh) total-vm:4636kB, anon-rss:68kB, file-rss:0kB, shmem-rss:0kB
May 26 18:23:16 be-99 kernel: Out of memory: Kill process 26229 (netdata) score 797 or sacrifice child

May 26 18:22:46 be-99 systemd-udevd[566]: seq 34112973 '/kmalloc-64(12445848:c85984f9813274501f3bf25b4a41b326e1d9b4c859f1df6271494b0a21cfb72c)' is taking a long time
May 26 18:23:16 be-99 kernel: oom_reaper: reaped process 26229 (netdata), now anon-rss:0kB, file-rss:0kB, shmem-rss:524kB
May 26 18:23:16 be-99 kernel: Killed process 26229 (netdata) total-vm:16722180kB, anon-rss:13474312kB, file-rss:0kB, shmem-rss:524kB
May 26 18:23:16 be-99 kernel: Out of memory: Kill process 26229 (netdata) score 797 or sacrifice child
```

**Comment by MrZammler** [comment] 2022-05-27 12:44
Hi @Raltrwx !

Well, not sure how the oom killer chart works, but I would guess by oom killing netdata it could fail to record the kills.

Can you please also post a long, couple of days chart of Applications -> mem ?

Thanks!

**Comment by ilyam8** [comment] 2022-05-27 13:39
> Well, not sure how the oom killer chart works

We get it from `/proc/vmstat` (the field name is `oom_kill`).

**Comment by ilyam8** [comment] 2022-05-27 14:20
> but I would guess by oom killing netdata it could fail to record the kills

Looks like it. This issue is probably a duplicate of #12839.

**Comment by Raltrwx** [comment] 2022-05-27 14:51
@MrZammler Sure thing,

![image](https://user-images.githubusercontent.com/20295023/170723861-84c6d277-5212-46b6-b6f3-d118feeacd19.png)

**Comment by MrZammler** [comment] 2022-05-30 14:40
Hi @Raltrwx 

Yes, the leak is something we should look into. Would it be possible though for you to switch to a nightly version of Netdata (assuming this is a node you can do that) to check whether the leak still exists there? Thanks in advance!

**Comment by cpipilas** [comment] 2022-06-29 10:01
@Raltrwx what was the kernel version running?
 Would it be possible to update to the latest netdata agent and see if this is still valid?

**Comment by ilyam8** [comment] 2022-08-16 10:17
Closing the issue because it is not a bug really. Netdata can't graph a oom kill when its Netdata that gets killed.

**Closed by ilyam8** 2022-08-16 10:17 UTC
Labels: bug, area/daemon
