### ISSUE TITLE
using with docker. got error after update.

### ISSUE THREAD

**Issue by zaywalker** [netdata/netdata#6018] opened 2019-05-15 07:50 UTC
#### Summary

Error loading shared library liblz4.so.1: No such file or directory (needed by /usr/sbin/netdata)
Error relocating /usr/sbin/netdata: LZ4_compressBound: symbol not found
Error relocating /usr/sbin/netdata: LZ4_compress_default: symbol not found
Error relocating /usr/sbin/netdata: LZ4_decompress_safe: symbol not found

netdata was working fine but after update I got error and netdata container restarts continually.
I use latest tag so it's unclear about the version.. 
I've updated with netdata/netdata 2019.05.15 3:41pm (UTC +9)

**Comment by cakrit** [comment] 2019-05-15 08:11
We're investigating.

**Comment by paulkatsoulakis** [comment] 2019-05-15 08:37
I am preparing an immediate rollback for starters, to avoid breaking other users and will then continue investigation on the root cause. Apologies for the inconvenience caused!

I will ping you once the new image is out @zaywalker

**Comment by paulkatsoulakis** [comment] 2019-05-15 09:22
@zaywalker kindly update again to latest image and verify your service is fine now

**Comment by paulkatsoulakis** [comment] 2019-05-15 10:47
Ok so after some investigation and discussions with @mfundul we nailed the root cause.
Alpine bite me hard, it seems that `lz4` does not provide the libraries, you need to also install `lz4-libs` to get there. In parallel i fall into the trap of compiling my changes with the wrong local base images, thus resulting in the build not including the right packages and thus not seeing the effect of the start up failure.

Next steps:
1) Preparing the fix so that we can re-release the latest code
2) I will create issue to document a faster and safe rollback process
3) I will create an issue to improve our testing to safe guard failures on a highly usage resource like the docker images.

Again @zaywalker my apologies for this bad experience, hope this won't stop you from continuing using us!

**Comment by paulkatsoulakis** [comment] 2019-05-15 13:45
We 'll actually have to wait the re-publishing to finsih prior to resolving this issue. Reopening.

**Comment by paulkatsoulakis** [comment] 2019-05-15 16:26
Issue seems to have been resolved.
@zaywalker do not hesitate to let us know if you face any other issues, thanks for reporting!

**Closed by paulkatsoulakis** 2019-05-15 16:26 UTC
Labels: area/packaging, bug, priority/high

**Comment by zaywalker** [comment] 2019-05-15 23:03
@paulkatsoulakis Thanks!! it works perfactly now! :) sorry for the late reply, i just check email now, and of course i'll report when bump any issue like this. :) thanks again for the fast fix!
