### ISSUE TITLE
netdata: feature: virtual interfaces network link state (operstate)

### ISSUE THREAD

**Issue by k0ste** [netdata/netdata#10628] opened 2021-02-14 10:21 UTC
Currently we know nothing about links state. For example, with prometheus we can't alert when copper/fiber link is down.
It will be good to implement something like:
```
netdata_net_link_state_average{chart="net_link_state.eth0",family="eth0",dimension="state"}
```
Where:
* 0 = link down
* 1 = link up
* 2 = low layer down

**Comment by ilyam8** [comment] 2021-02-14 23:41
Hi @k0ste 

This request is duplicate of #5989, implemented in #7395

Added as Bandwidth chart variables (e.g `net.eth0`)



```json
{
    "duplex": 0,
    "operstate": 6,
    "nic_speed_max": 0
}
```

To get chart variables using prometheus format you need [to add `&variables=yes`](https://learn.netdata.cloud/docs/agent/exporting/prometheus#netdata-host-variables)

**Comment by k0ste** [comment] 2021-02-15 07:38
@ilyam8, thanks. I was not aware of this changes.
I was check netdata 1.29.1 and currently state's is present only for physdev's (copper/fiber), but not for virtual ifaces, such as port-channels, vlans, gres, etc.
Can we reopen this?🤔

**Comment by ilyam8** [comment] 2021-02-15 08:32
Ineed, you are right.

`duplex`, `operstate`, `nic_speed_max` variables are not added for virtual interfaces

https://github.com/netdata/netdata/blob/5571b20dcf76af676f6d1447285f7e3376f117f5/collectors/proc.plugin/proc_net_dev.c#L586-L596

---

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:~$ cat /sys/class/net/docker0/speed
cat: /sys/class/net/docker0/speed: Invalid argument

ilyam@debian-s-1vcpu-1gb-fra1-01:~$ cat /sys/class/net/docker0/duplex
cat: /sys/class/net/docker0/duplex: Invalid argument

ilyam@debian-s-1vcpu-1gb-fra1-01:~$ cat /sys/class/net/docker0/operstate
down
```

We should add `operstate` for all interfaces.

**Comment by k0ste** [comment] 2021-02-15 09:31
Thanks, also we need `mtu`, `carrier`, `speed` metrics. In some metric it will be good to see what iface is lower, for example: `/sys/class/net/vlan666/lower_po1` - for vlan `vlan666` port-channel `po1` is lower and for `po1` lower is `gig0` and `gig1`

**Comment by Ferroin** [comment] 2021-02-15 12:35
What options are available or return useful information will vary by virtual interface type. Bridges don’t report speed or duplex unless they have interfaces assigned to them that have such information. TAP interfaces always report `unknown` for `operstate`, `full` for `duplex`, and `10` for `speed`, none of which is actually useful.

OTOH, `mtu` _should_ be available everywhere, and `carrier` values are functionally correct (but not always useful) for all interface types, and both are indeed useful.

**Comment by k0ste** [comment] 2021-02-15 12:43
@Ferroin indeed. Speed is relevant for port-channels, e.g. we can check port-channels members with this metric, for example if speed is 30000, but we expect speed for 40000 this mean one LAG member is not `up` or not `proto up`.

**Comment by ilyam8** [comment] 2021-02-15 13:40
As for port-channels - there is `/proc/net/bonding/*`. Perhaps we could use that data.

**Comment by Ferroin** [comment] 2021-02-15 13:41
While that data may be useful, the overall state of the bonding interface is also important in a lot of cases. Especially if it’s a failover setup instead of bandwidth aggregation.

**Closed** 2021-02-15 13:52 UTC
Labels: area/collectors, bug, data-collection-mteam

**Comment by ilyam8** [comment] 2021-02-15 13:53
Collecting additional network iface parameters (`mtu`, `carrier`, `speed`, etc.) and data from `/proc/net/bonding/*` should be separate issues.
