### ISSUE TITLE
[Bug]: Protobuf support and Centos 7

### ISSUE THREAD

**Issue by jonknud** [netdata/netdata#12157] opened 2022-02-16 15:03 UTC
### Bug description

I am running Centos 7 (95%) and Oracle Linux 7 (05%) with netdata 1.33.1 from packagecloud.io

Netdata Cloud shown me a warning that protobuf support is missing and I should update but I am already uptodate.

```
root@devel:~# netdata -v
netdata v1.33.1
```

```
root@devel:~# netdata -W buildinfo | grep 'Install type:'
Install type: binpkg-rpm
```

The Dokumentation says:

> binpkg-* installation
> Binpkg type of installations should not experience any difficulties with the new architecture. If you run into an error:
> File a bug on GitHub

### Expected behavior

I would expect that netdata cloud is just running if i install the latest updates or to find instruction what to change.

### Steps to reproduce

1. install centos
2. install netdata
3. connect netdata to netdata cloud
4. see message in netdata cloud

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux devel 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
root@devel:~# $(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
Version: netdata v1.33.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-bundled-libJudy' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Install type: binpkg-rpm
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: NO
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by MrZammler** [comment] 2022-02-16 15:48
Hi @jonknud ! Thanks for your report.

Indeed, it seems the package from packagecloud.io is missing protobuf support which is required for using the new cloud communication protocol: (`protobuf:                NO`)

If possible, could you try in one of your machines to use our kickstart script (https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart) which will try to install a binary package which will contain protobuf.

**Comment by jaxtheking** [comment] 2022-02-16 17:27
I'm experiencing exactly the same issue.

**Comment by Ferroin** [comment] 2022-02-16 18:55
It appears we somehow missed that the system-provided copy of protobuf on CentOS 7 is too old for our usage. Looks like we will need to bundle a copy ourselves as part of the build.

Working on a PR now to do exactly this.

**Comment by bbeckford** [comment] 2022-02-24 13:54
I'm currently experiencing this on one of my Centos 7 nodes (confirmed with Netdata live chat)

Is there a workaround whilst we're waiting for this pull request to be merged?

**Comment by Ferroin** [comment] 2022-02-24 18:00
Short term, explicitly asking for a static build (with `--static-only`) or a local build (with `--build-only`) _should_ work here.

I’ve also politely reminded people internally about it, so we should hopefully have enough reviews to get it merged before the end of the day tomorrow.

**Comment by Ferroin** [comment] 2022-02-25 12:47
The fix for this is now merged and should show up in the nightly builds starting from tonight, as well as in the next stable release (which, IIRC, should be in a couple of weeks).

**Closed** 2022-02-25 12:46 UTC
Labels: bug, area/packaging, priority/high

**Comment by bbeckford** [comment] 2022-02-28 16:36
This is working for me now! Thanks guys :)

**Comment by Ferroin** [comment] 2022-02-28 16:41
@bbeckford Always glad to get feedback that things truly are fixed. Sorry it took so long to get the fix merged in this case.
