### ISSUE TITLE
Memory metrics (mem_usage) for LXC (container) show: 100% used - but this is not true

### ISSUE THREAD

**Issue by 74cmonty** [netdata/netdata#4383] opened 2018-10-11 16:31 UTC
Hello!
The metrics for memory usage of an LXC (container) show 2.4MB and display this as 100% used.
![2018-10-11_18-27-04](https://user-images.githubusercontent.com/12523591/46819162-4bbeb780-cd83-11e8-8fc2-45201b39c58a.png)

However this is not true because the container has a total memory allocation of 50MB and the used memory is therefore only 5%!
![2018-10-11_18-28-31](https://user-images.githubusercontent.com/12523591/46819323-b96ae380-cd83-11e8-8bcb-ddeacaf6cce9.png)

Please check the attached screenshots and verify if you can correct the related collector accordingly.

THX

**Comment by paulfantom** [comment] 2018-10-11 16:51
Closing as a duplicate of #4206

**Closed by paulfantom** 2018-10-11 16:51 UTC
Labels: duplicate
