### ISSUE TITLE
Build fails on FreeBSD

### ISSUE THREAD

**Issue by rsyncOSX** [netdata/netdata#9227] opened 2020-05-30 05:48 UTC
On:
FreeBSD freebsd.local 12.1-RELEASE-p5 FreeBSD 12.1-RELEASE-p5 GENERIC  amd64

##### Bug report summary

config.status: creating config.h
config.status: executing depfiles commands
config.status: error: in `/root/netdata':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
 FAILED

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   sorry, it failed to build...  '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

##### OS / Environment

```

```

##### Steps To Reproduce

1. ...
2. ...

**Comment by stevenh** [comment] 2020-05-30 19:59
I think it assumes `make` is `gnu make` which is not the case. It would need to use `gmake` or set `MAKE=gmake`

**Comment by rsyncOSX** [comment] 2020-05-30 20:14
I might try to change. But I have every second week, for the last two-three years, pulled last changes and compiled netdata.. The error occurred  for about one week ago, no changes to FreeBSD before and after last successful compile...

**Comment by prologic** [comment] 2020-06-01 02:34
I _believe_ this is a duplicate of #9163 . If this is not correct please comment or reopen. Thanks!

**Closed by prologic** 2020-06-01 02:34 UTC
Labels: bug, needs triage, os/bsd

**Comment by rsyncOSX** [comment] 2020-06-07 20:41
Downloaded **version 1.22.1**, builds with no problem on FreeBSD 12.

Pulled last code from master repository **7 June 2020**, build fails
config.status: error: in `/root/tem/netdata':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
 FAILED

**Comment by ilyam8** [comment] 2020-06-07 20:54
> See config.log' for more details

Lets see!

**Comment by ilyam8** [comment] 2020-06-07 20:55
oh, #9163 is not fixed, @rsyncOSX please post there

**Comment by rsyncOSX** [comment] 2020-06-08 12:48
[config.log](https://github.com/netdata/netdata/files/4745997/config.log)
[netdata-installer.log](https://github.com/netdata/netdata/files/4746000/netdata-installer.log)
