### ISSUE TITLE
[Bug]: core dump on shutdown [1.34.1]

### ISSUE THREAD

**Issue by bnesbitt** [netdata/netdata#12816] opened 2022-05-04 12:12 UTC
### Bug description

I have observed that netdata dumps core occasionally on shutdown. This has happened on multiple versions and now happens with the latest - 1.34.1. We are stopping netdata using 'systemctl stop netdata' and 'systemctl restart netdata'

This is the RHEL 8 RPM version obtained from: https://packagecloud.io/netdata/netdata/packages/el/8/netdata-1.34.1-1.el8.x86_64.rpm

gdb output:

```shell
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-16.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/netdata...done.
[New LWP 41082]
[New LWP 41276]
[New LWP 41257]
[New LWP 41108]
[New LWP 41278]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/netdata -P /var/run/netdata/netdata.pid -D'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f5aa61e137f in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f5aa9201940 (LWP 41082))]
Missing separate debuginfos, use: yum debuginfo-install netdata-1.34.1-1.el8.x86_64
(gdb) bt
#0  0x00007f5aa61e137f in raise () from /lib64/libc.so.6
#1  0x00007f5aa61cbdb5 in abort () from /lib64/libc.so.6
#2  0x00007f5aa62244e7 in __libc_message () from /lib64/libc.so.6
#3  0x00007f5aa622b5ec in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f5aa622cefc in _int_free () from /lib64/libc.so.6
#5  0x000055995ac95fc2 in rrddim_free_custom (st=st@entry=0x7f5aa9063000, rd=0x7f5aa9061000, db_rotated=db_rotated@entry=0)
    at database/rrddim.c:498
#6  0x000055995ac9ceb2 in rrdset_free (st=0x7f5aa9063000) at database/rrdset.c:361
#7  0x000055995ac98255 in rrdhost_free (host=0x55995c44d690) at database/rrdhost.c:910
#8  0x000055995ac99d70 in rrdhost_free (host=<optimized out>) at database/rrdhost.c:1011
#9  rrdhost_free_all () at database/rrdhost.c:1011
#10 0x000055995ab64390 in netdata_cleanup_and_exit (ret=ret@entry=0) at daemon/main.c:60
#11 0x000055995ab65aea in signals_handle () at daemon/signals.c:261
#12 0x000055995ab5b735 in main (argc=<optimized out>, argv=<optimized out>) at daemon/main.c:1337
```

where:

```shell
(gdb) p *rd-> state
$6 = {
  rrdeng_uuid = 0x0, 
  page_index = 0x0, 
  aclk_live_status = -1, 
  metric_uuid = "&U\203\323\260\373K\216\210YM\027\237bR\371", 
  handle = {
    slotted = {
      slot = 0, 
      entries = 0
    }, 
    rrdeng = {
      descr = 0x0, 
      prev_descr = 0x0, 
      page_correlation_id = 0, 
      ctx = 0x0, 
      unaligned_page = 0 '\000'
    }
  }, 
  collect_ops = {
    init = 0x55995ac94480 <rrddim_collect_init>, 
    store_metric = 0x55995ac944a0 <rrddim_collect_store_metric>, 
    finalize = 0x55995ac944c0 <rrddim_collect_finalize>
  }, 
  query_ops = {
    init = 0x55995ac94760 <rrddim_query_init>, 
    next_metric = 0x55995ac944d0 <rrddim_query_next_metric>, 
    is_finished = 0x55995ac94520 <rrddim_query_is_finished>, 
    finalize = 0x55995ac94530 <rrddim_query_finalize>, 
    latest_time = 0x55995ac946e0 <rrddim_query_latest_time>, 
    oldest_time = 0x55995ac945d0 <rrddim_query_oldest_time>
  }, 
  ml_dimension = 0x0
}
```

The code in question is doing:

```shell
freez(rd->state);
```

The corresponding logs report:

```shell
2022-05-04 10:35:29: netdata INFO  : MAIN : EXIT: Stopping main thread: PLUGIN[cgroups]
2022-05-04 10:35:29: netdata INFO  : MAIN : Waiting 13 threads to finish...
2022-05-04 10:35:29: netdata INFO  : PLUGIN[cgroups] : cleaning up...
2022-05-04 10:35:29: netdata INFO  : PLUGIN[cgroups] : stopping discovery thread worker
2022-05-04 10:35:29: netdata INFO  : PLUGIN[cgroups] : waiting for discovery thread to finish...
2022-05-04 10:35:29: netdata INFO  : PLUGINSD : stopping plugin thread: plugin:go.d
2022-05-04 10:35:29: netdata INFO  : PLUGINSD : stopping plugin thread: plugin:apps
2022-05-04 10:35:29: netdata INFO  : PLUGINSD : cleanup completed.
2022-05-04 10:35:29: netdata INFO  : PLUGINSD : thread with task id 41265 finished
2022-05-04 10:35:29: netdata INFO  : PLUGINSD[go.d] : data collection thread exiting
2022-05-04 10:35:29: netdata INFO  : PLUGINSD[go.d] : killing child process pid 41301
2022-05-04 10:35:29: netdata INFO  : PLUGINSD[go.d] : thread with task id 41290 finished
2022-05-04 10:35:29: netdata INFO  : PLUGINSD[apps] : data collection thread exiting
2022-05-04 10:35:29: netdata INFO  : PLUGINSD[apps] : killing child process pid 41295
2022-05-04 10:35:29: netdata INFO  : PLUGINSD[apps] : thread with task id 41277 finished
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static1] : stopping worker 2
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static1] : stopping worker 3
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static1] : stopping worker 4
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static1] : Waiting 3 static web threads to finish...
2022-05-04 10:35:29: netdata INFO  : HEALTH : thread with task id 41264 finished
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static4] : freeing local web clients cache...
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static4] : stopped after 0 connects, 0 disconnects (max concurrent 0), 0 receptions and 0 sends
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static4] : thread with task id 41293 finished
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static3] : freeing local web clients cache...
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static3] : stopped after 0 connects, 0 disconnects (max concurrent 0), 0 receptions and 0 sends
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static3] : thread with task id 41292 finished
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static2] : freeing local web clients cache...
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static2] : stopped after 0 connects, 0 disconnects (max concurrent 0), 0 receptions and 0 sends
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static2] : thread with task id 41291 finished
2022-05-04 10:35:29: netdata INFO  : GLOBAL_STATS : thread with task id 41263 finished
2022-05-04 10:35:29: netdata INFO  : PLUGIN[cgroups] : thread with task id 41274 finished
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static1] : closing all web server sockets...
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static1] : all static web threads stopped.
2022-05-04 10:35:29: netdata INFO  : WEB_SERVER[static1] : thread with task id 41269 finished
2022-05-04 10:35:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2022-05-04 10:35:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2022-05-04 10:35:29: netdata INFO  : MAIN : Waiting 1 threads to finish...
2022-05-04 10:35:30: netdata INFO  : MAIN : Waiting 1 threads to finish...
2022-05-04 10:35:30: netdata INFO  : MAIN : Waiting 1 threads to finish...
2022-05-04 10:35:30: netdata INFO  : MAIN : Waiting 1 threads to finish...
2022-05-04 10:35:30: netdata INFO  : MAIN : Waiting 1 threads to finish...
2022-05-04 10:35:30: netdata INFO  : STREAM_SENDER[region1lba1] : STREAM region1lba1 [send]: sending thread cleans up...
2022-05-04 10:35:30: netdata INFO  : STREAM_SENDER[region1lba1] : STREAM region1lba1 [send]: sending thread detaches itself.
2022-05-04 10:35:30: netdata INFO  : STREAM_SENDER[region1lba1] : STREAM region1lba1 [send]: sending thread now exits.
2022-05-04 10:35:30: netdata INFO  : STREAM_SENDER[region1lba1] : thread with task id 41544 finished
2022-05-04 10:35:30: netdata INFO  : ACLK_Main : thread with task id 41270 finished
2022-05-04 10:35:30: netdata INFO  : MAIN : All threads finished.
2022-05-04 10:35:30: netdata INFO  : MAIN : EXIT: freeing database memory...
2022-05-04 10:35:30: netdata INFO  : MAIN : Freeing all memory for host 'region1lba1'...
free(): invalid size
```

The last line is of interest - free(): invalid size. Could this be memory corruption?

### Expected behavior

Netdata should terminate gracefully without dumping core.

### Steps to reproduce

1. Start netdata.
2. Stop/restart netdata
3. Dumps core intermittently on shutdown
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Linux region1lba1 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Tue Mar 8 12:56:54 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/os-release:NAME="Red Hat Enterprise Linux"
/etc/os-release:VERSION="8.5 (Ootpa)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VERSION_ID="8.5"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8.5"
/etc/redhat-release:Red Hat Enterprise Linux release 8.5 (Ootpa)
/etc/system-release:Red Hat Enterprise Linux release 8.5 (Ootpa)
```

### Netdata build info

```shell
[root@region1lba1 ~]# netdata -W buildinfo
Version: netdata v1.34.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-bundled-libJudy' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Install type: binpkg-rpm
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

netdata.conf:

```shell
[global]
    hostname = region1lba1
    run as user = netdata

    #memory mode defined as save
    memory mode = ram

    # history controls the size of the database in RAM, except for memory mode = dbengine
    history = 600

    # Expose the netdata port to all
    bind to = 192.168.100.221

[web]
    web files owner = root
    web files group = netdata

[statsd]
        enabled = yes
        decimal detail = 1000
        update every (flushInterval) = 1
        udp messages to process at once = 10
        create private charts for metrics matching = *
        max private charts allowed = 200
        max private charts hard limit = 1000
        private charts memory mode = ram
        private charts history = 600
        histograms and timers percentile (percentThreshold) = 95.00000
        add dimension for number of events received = yes
        gaps on gauges (deleteGauges) = no
        gaps on counters (deleteCounters) = no
        gaps on meters (deleteMeters) = no
        gaps on sets (deleteSets) = no
        gaps on histograms (deleteHistograms) = no
        gaps on timers (deleteTimers) = no
        listen backlog = 4096
        default port = 8125
        bind to = udp:*:8125 tcp:localhost:8125

[host labels]
        Region=region1
        Node_Type=LBA
```

_No response_

**Comment by cpipilas** [comment] 2022-06-29 10:52
@bnesbitt would it possible to re-test with latest version?

**Comment by ilyam8** [comment] 2022-08-16 09:59
We have merged several patches that fix the core dump on shutdown.  Closing the issue, because the problem is likely fixed. @bnesbitt if you still have the bug with latest stable, please comment and we will reopen the issue.

**Closed by ilyam8** 2022-08-16 09:59 UTC
Labels: bug, area/database
