### ISSUE TITLE
INFO: run netdata on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#8905] opened 2020-05-05 14:17 UTC
Ubuntu 14.04 LTS is EOL, but still if you have such a server, netdata can be run with this:

add a repo to get `libuv1-dev` (https://stackoverflow.com/a/49628607/4525767)

```sh
add-apt-repository ppa:acooks/libwebsockets6
```

export CFLAGS to disable the requirement of openssl host verification. This will lesser your security, but still the version of openssl installed on ubuntu 14.04 LTS cannot do better.

```sh
# as root, run:
export CFLAGS="-DACLK_SSL_ALLOW_SELF_SIGNED"
bash <(curl -Ss https://my-netdata.io/kickstart.sh)
```

With the above netdata is installed and it can communicate with netdata.cloud too.

(I haven't verified the kickstart works, because I used `netdata-installer.sh` from the `go-live` branch)

**Comment by lassebm** [comment] 2020-05-14 09:38
I've observed that while `CFLAGS` are persisted in `.environment` by `kickstart.sh`, it's ignored and overwritten by `netdata-updater.sh`, breaking the workaround during the nightly updates.

**Comment by prologic** [comment] 2020-05-21 01:28
> I've observed that while `CFLAGS` are persisted in `.environment` by `kickstart.sh`, it's ignored and overwritten by `netdata-updater.sh`, breaking the workaround during the nightly updates.

I have noticed this too. Btw what `CFLAGS` are you referring to here? I need to get back to this and get this working and working with Netdata cloud. The PR changes are not quite enough.

**Comment by lassebm** [comment] 2020-05-21 08:20
@prologic I need `-DACLK_SSL_ALLOW_SELF_SIGNED` for cloud connectivity on Ubuntu 14.04.

**Comment by prologic** [comment] 2020-05-21 12:02
> @prologic I need `-DACLK_SSL_ALLOW_SELF_SIGNED` for cloud connectivity on Ubuntu 14.04.

Perfect! Let me add that to this PR and do you mind helping me re-test this? I'm not sure I have an Ubuntu 14.04 VM but I'll go spin one up...

**Comment by lassebm** [comment] 2020-05-21 12:04
@prologic Sure, no problem.

**Comment by zack-shoylev** [comment] 2020-05-27 16:51
There are (related) CentOS, Ubuntu 14, Debian 7 issues:
https://github.com/netdata/netdata/issues/9152
https://github.com/netdata/netdata/issues/9153
@ktsaou told me this is probably caused by SSL problems with self-signed certs. On some systems autoconf may have to allow self-signed and also host verification will have to be disabled.

**Comment by prologic** [comment] 2020-05-28 03:36
Allowing self-signed certs is one thing, turning off host verification is rather dangerous and should be considered very carefually/seriously. @amoss What do you want to have happen here?

**Comment by amoss** [comment] 2020-05-28 06:28
I don't think that we should turn off security features without explicit consent from the user.

**Comment by prologic** [comment] 2020-05-28 08:31
> I don't think that we should turn off security features without explicit consent from the user.

110% Agreed.

**Comment by prologic** [comment] 2020-06-29 02:32
Waiting on reviews for the final PR #8916

**Comment by prologic** [comment] 2020-07-30 05:55
What are we ding about this issue? Its been open for some time now... I've sort of lost the plot a bit here.

**Comment by amoss** [comment] 2020-07-30 08:11
@joelhans Please can you confirm that this is documented and then close the issue?

**Comment by joelhans** [comment] 2020-08-13 16:49
Installing on 14.04 should be possible with the PR Costa himself wrote to address this issue: #9198

The caveats of installing on 14.04 are documented in two places:

https://learn.netdata.cloud/docs/agent/packaging/installer#older-distributions-ubuntu-1404-debian-8-centos-6-and-openssl
https://learn.netdata.cloud/docs/agent/claim#claiming-on-older-distributions-ubuntu-1404-debian-8-centos-6

This seems sufficient to me, so I'm closing the issue.

**Closed by joelhans** 2020-08-13 16:49 UTC
Labels: area/docs, area/packaging, no changelog

**Comment by prologic** [comment] 2020-08-19 04:41
Thanks @joelhans !
