### ISSUE TITLE
[Bug]: Plex triggers inbound_packets_dropped_ratio

### ISSUE THREAD

**Issue by MrPepino** [netdata/netdata#16850] opened 2024-01-25 18:36 UTC
### Bug description

Watching media content using the Plex Web Interface via Google Chrome triggers inbound_packets_dropped_ratio. It does not occur when using the Plex TV App. Both situations are local network-only from server to pc. The threshold of inbound_packets_dropped_ratio was raised several times upto 50% and is still being triggered.

### Expected behavior

inbound_packets_dropped_ratio should not be triggered by Plex Web Interface

### Steps to reproduce

1. Open Plex Web Interface on Google Chrome with IP:PORT/web/index.html on local network
2. Play a show
3. Receive email from Netdata Cloud "Raised to Warning, inbound_packets_dropped_ratio = 120.72 %, on server" within minutes

### Installation method

docker

### System info

```shell
Linux jv-server 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.3 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
Packaging:
    Netdata Version ____________________________________________ : v1.44.0-233-nightly
    Installation Type __________________________________________ : oci
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ : unknown
    Configure Options __________________________________________ : dummy-configure-command
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /usr/share/netdata/web
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 5.15.0-91-generic
    Operating System ___________________________________________ : Ubuntu
    Operating System ID ________________________________________ : ubuntu
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 22.04.3 LTS (Jammy Jellyfish)
    Operating System Version ID ________________________________ : 12
    Detection __________________________________________________ : /host/etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 8
    CPU Frequency ______________________________________________ : 2000000000
    RAM Bytes __________________________________________________ : 16537006080
    Disk Capacity ______________________________________________ : 2000398934016
    CPU Architecture ___________________________________________ : x86_64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : none
Container:
    Container __________________________________________________ : docker
    Container Detection ________________________________________ : dockerenv
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : Debian GNU/Linux
    Container Operating System ID ______________________________ : debian
    Container Operating System ID Like _________________________ : unknown
    Container Operating System Version _________________________ : 12 (bookworm)
    Container Operating System Version ID ______________________ : 12
    Container Operating System Detection _______________________ : /etc/os-release
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Back-filling (of higher database tiers) ____________________ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (zstd lz4 gzip)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    ZSTD (fast, lossless compression algorithm) ________________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Brotli (generic-purpose lossless compression algorithm) ____ : NO
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libyaml (library for parsing and emitting YAML) ____________ : YES
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : NO
    ebpf (monitor system calls) ________________________________ : NO
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : NO
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
    Logs Management ____________________________________________ : YES
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : YES
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

### Additional info

Both the stable and latest docker version were used before opening this issue. I do not mind packet drops for Plex but would prefer keeping the alert enabled for general purpose.

**Comment by Ferroin** [comment] 2024-01-25 19:17
If you’re hitting a dropped packet ratio of over 100%, something is seriously wrong, and it’s unlikely to be anything to do with Netdata. That means more packets are being dropped by the networking stack than are actually being accepted, which should essentially never happen and indicates that significant amounts of resources are being wasted. Anything more than 1% is cause for concern to begin with, and even 5% is enough that you should be investigating what exactly is going on.

**Comment by tkatsoulas** [comment] 2024-01-26 12:01
I agree with what @Ferroin said, it seems that you bumped into an upstream issue of the Plex media server and you spotted it with netdata, please feel free to reopen this issue if you verify that this was a false positive, until then we advise you to seek help in the Plex community.

Closing this issue. 
Have a great day.

**Closed by tkatsoulas** 2024-01-26 12:01 UTC
Labels: bug, needs triage

**Comment by ilyam8** [comment] 2024-01-26 12:44
> 120.72%

Looks wrong, shouldn't be > 100%. 

The [inbound_packets_dropped_ratio](https://github.com/netdata/netdata/blob/60c5371d686644ecc409ae68499e4fff7a3547e7/health/health.d/net.conf#L89) alarm uses other alarm ([net_interface_inbound_packets](https://github.com/netdata/netdata/blob/60c5371d686644ecc409ae68499e4fff7a3547e7/health/health.d/net.conf#L63C12-L63C41)) in [its calculations](https://github.com/netdata/netdata/blob/60c5371d686644ecc409ae68499e4fff7a3547e7/health/health.d/net.conf#L98). There may be an incorrect lookup and we are using the number of packets of different interface - I can't reproduce this problem using `/api/v1/variable` endpoint.

- check `net_interface_inbound_packets` variable lookup for `net_drops.vlan2` chart

```bash
$ curl -sq "http://127.0.0.1:19999/api/v1/variable?chart=net_drops.vlan2&variable=net_interface_inbound_packets"
{
    "variable":"net_interface_inbound_packets",
    "instance":"net_drops.vlan2",
    "context":"net.drops",
    "found":true,
    "value":7984993.661,
    "source":{
        "description":"alarm value",
        "instance":"net_packets.vlan2",
        "context":"net.packets",
        "candidates":22
    }
}
```

It is correct, it selects `net_packets.vlan2` chart.

---

@MrPepino you need to check the packet and drop metrics for the interface for which you are receiving the alarm.
