### ISSUE TITLE
[Bug]: Systemd unit files are missing.

### ISSUE THREAD

**Issue by iigorkarpov** [netdata/netdata#12881] opened 2022-05-11 14:05 UTC
### Bug description

Systemd unit files are missing both in RPM and DEB packages (edge). So the target systems have zero-sizes files:

```
ls -l /usr/lib/systemd/system/netdata-updater.*
-rw-rw-r-- 1 root root 0 May  5 09:19 /usr/lib/systemd/system/netdata-updater.service
-rw-rw-r-- 1 root root 0 May  5 09:19 /usr/lib/systemd/system/netdata-updater.timer
```

### Expected behavior

These files should be included into the packages.

### Steps to reproduce

N/A

### Installation method

kickstart.sh

### System info

```shell
Checked both on Ubuntu 20 and Rocky 8 hosts.
```

### Netdata build info

```shell
N/A
```

**Comment by Ferroin** [comment] 2022-05-12 13:14
Do we know yet if this is _just_ the DEB packages, or both DEB and RPM packages? Likely root cause is different in either case.

**Comment by iigorkarpov** [comment] 2022-05-12 15:54
As I wrote above, both DEB & RPM packages are impacted. I can double-check this.

**Comment by Ferroin** [comment] 2022-05-12 16:53
> As I wrote above, both DEB & RPM packages are impacted. I can double-check this.

Ah, sorry, missed that in the original post somehow.

**Comment by iigorkarpov** [comment] 2022-05-12 17:10
Well, I did not emphasize this

**Comment by Ferroin** [comment] 2022-07-29 12:27
First steps towards fixing this in https://github.com/netdata/netdata/pull/13451

Once that’s merged, I’ll be opening a followup PR to modify the updater so it uses the files that will then be under `/usr/lib/netdata/system` if they exist instead of blindly assuming the installer handled things correctly, which should in turn fully resolve this issue.

**Comment by ilyam8** [comment] 2023-01-24 14:46
@Ferroin has this been fixed?

**Comment by Ferroin** [comment] 2023-01-24 15:01
Yes, it should be fixed at this point.

**Closed by Ferroin** 2023-01-24 15:01 UTC
Labels: bug, area/packaging
