### ISSUE TITLE
On the problem of rate unit display

### ISSUE THREAD

**Issue by smdx** [netdata/netdata#11428] opened 2021-08-12 04:19 UTC
Hello, everyone
Can you provide options for different fixed units when setting up a fixed unit? For example, kilobytes/s, KB/s, MB/s, etc. . Manually modifying the config document is too difficult for the average user. Thank you

##### OS / Environment
Linux OpenWrt 5.10.51

##### Netdata version
netdata 1.30.1-1

**Comment by ilyam8** [comment] 2021-08-16 09:46
Hi, @smdx. 

Netdata's Dashboard has Scale Units feature

> When set to Scale Units the values shown will dynamically be scaled (e.g. 1000 kilobits will be shown as 1 megabit). Netdata can auto-scale these original units: kilobits/s, kilobytes/s, KB/s, KB, MB, and GB. When set to Fixed Units all the values will be rendered using the original units maintained by the netdata server.

It is enabled by default. Can be disabled via "Dashboard options => Locale => Scale Units".

<details>
<summary>screenshot [click]</summary>

<img width="1262" alt="Screenshot 2021-08-16 at 12 43 29" src="https://user-images.githubusercontent.com/22274335/129544284-19cbdcf2-8fe9-4e73-8b6b-204044c19b01.png">

</details>

The list of scalable units (i don't think we have it in the documentation):
https://github.com/netdata/dashboard/blob/99dc56e960c1c4cb310ce9cf49b3d1ebcc1a6da8/src/utils/units-conversion.ts#L14-L152

---

> Manually modifying the config document is too difficult for the average user.

Can you elaborate? Why/what do you need to configure?

**Comment by smdx** [comment] 2021-08-16 10:31
Hello, thank you for your reply. I mean the fixed rate unit selection for network traffic (such as KB/s, MB/s) is provided after you switch to the fixed unit for the Locale page, now you need to modify netdata.a if you want to fix the rate display KB/s. Conf, which is a bit difficult for the average user.

**Comment by ilyam8** [comment] 2021-08-16 17:47
@smdx you want to manually set units for specific charts? For instance, network charts to be in MiB/s (and doesn't scale to KiB/GiB). Am I right?


That is possible, but as you said _a little hard_. I agree, in order to do it, you need

- disable "Scale Units"
- set units to desired units in the "netdata.conf` for the chart + modify multiplier,divisor

That sounds like a feature request, not a bug. Consider creating a topic on [our community forum](https://community.netdata.cloud/c/feature-requests/agent-fr/21).

Closing this issue, since it is not a bug. But we can continue discussing the problem here if i didn't get you right @smdx

**Closed by ilyam8** 2021-08-16 17:47 UTC
Labels: question
