### ISSUE TITLE
Netdata intermittently reporting full disk space usage for a few minutes

### ISSUE THREAD

**Issue by PNRxA** [netdata/netdata#6839] opened 2019-09-13 05:13 UTC
##### Bug report summary
About once every few days day I'll get an alert about the storage being full followed shortly after by it being reported correctly and closing the alert.

We have Netdata running on 40+ servers and this is the only one showing this behaviour. 
It's been doing doing this since September 4th 10AM AEST

##### OS / Environment
Debian Stretch on AWS EC2 T3

##### Netdata version (ouput of `netdata -V`)
v1.17.0-49-nightly

Example Today:
<img width="637" alt="chrome_2019-09-13_14-46-42" src="https://user-images.githubusercontent.com/16978632/64838335-00b5c000-d636-11e9-8861-60dcff49ef07.png">

Earlier this week:
![image](https://user-images.githubusercontent.com/16978632/64838596-458e2680-d637-11e9-80f4-e2c7430e271e.png)

![image](https://user-images.githubusercontent.com/16978632/64838613-5a6aba00-d637-11e9-9fc3-d60611057cb8.png)

**Comment by PNRxA** [comment] 2019-09-13 07:07
Nothing in the `error.log` near the time that there is a problem

Unfortunately I didn't think to take a snapshot when this occurred but I'll be sure to take one the next time it happens and send it through

**Comment by cakrit** [comment] 2019-09-13 07:22
Isn't it in your history? Perhaps you should set `memory mode = dbengine`! :)
I don't think there's much to go on here, so let's wait until you see it again, unless @vlvkobal has any other ideas.

**Comment by PNRxA** [comment] 2019-09-13 07:25
The history only goes back a small amount as it is archived with Prometheus and Thanos

I'll get back with a snapshot hopefully in the next few days when it next happens

**Comment by vlvkobal** [comment] 2019-09-13 07:40
What does `df` show at the moment the issue has happened?

**Comment by PNRxA** [comment] 2019-09-18 23:06
Okay so this happened to a different server this morning. Unfortunately I couldn't get a `df` as I was on my way to work but I'll email that snapshot through.

![image](https://user-images.githubusercontent.com/16978632/65193010-bb254700-dabc-11e9-8840-14e5155d084e.png)

**Comment by stelfrag** [comment] 2019-11-11 09:23
Any news on this?

In the meantime, it would be beneficial to upgrade to the latest version.
Checkout and consider adding 

```
memory mode = dbengine
````

I will close this in a couple of days since we don't have enough information to trouble shoot this
further.

**Comment by stelfrag** [comment] 2019-11-13 09:29
I will close this. 

Please reopen with updated information if it happens again so we can have a better chance of pin pointing what went wrong.

**Comment by PNRxA** [comment] 2020-02-12 06:28
So we've been getting this issue on a few more of our servers recently.
They all run the default configuration which would be mean the dbengine memory mode is what they're using.
They are also all running 1.19.0 stable.

It's happened a few times just today. Here's an example from right now:
![image](https://user-images.githubusercontent.com/16978632/74308661-e33f7a80-4dbc-11ea-9c20-369bcfeb7845.png)

And the df output
![image](https://user-images.githubusercontent.com/16978632/74308708-fce0c200-4dbc-11ea-8432-06f64afebe58.png)

Since we use this to alert us when there are problems (such as low disk space) our alerting systems have kept going off for no reason.

I can email a snapshot through if that helps. I'm not too sure what else I could provide to be useful.

**Comment by vlvkobal** [comment] 2020-02-12 08:46
Are there any errors with the `DISKSPACE` keyword in the `error.log`?

**Comment by PNRxA** [comment] 2020-02-12 22:24
Unfortunately there are no `DISKSPACE` errors in the `error.log` file

**Comment by vlvkobal** [comment] 2020-02-13 14:01
I've checked the code once more. We are using the [`statvfs`](https://github.com/netdata/netdata/blob/master/collectors/diskspace.plugin/plugin_diskspace.c#L197) call to get information from the [`f_bavail`](https://github.com/netdata/netdata/blob/master/collectors/diskspace.plugin/plugin_diskspace.c#L231). I don't see how Netdata can screw the value. I think the problem is on the OS side, but then `df` should give a broken report, but it doesn't. Does anybody have any idea what can we check next?

**Comment by cakrit** [comment] 2020-02-14 03:15
@Ferroin?

**Comment by Ferroin** [comment] 2020-02-14 12:44
Unfortunately, I've got essentially nothing coming to mind. Were this a physical system (or even locally hosted instead of a cloud-hosted node), I'd say it's probably a hardware issue, but I think that's very unlikely given that it's AWS (they would have seen and fixed it).

The only thing I can think of that this _might_ be is at-rest data corruption in executable code on the disk somewhere, which can easily cause strange stuff like this to happen, but that's astronomically unlikely on EC2 because of how storage is handled (it would require an absurd number of things to go wrong in _just_ the right way).

**Comment by cakrit** [comment] 2020-02-18 19:47
So @PNRxA , the only thing I can think of, it to execute something like the following, to get the output of `statvfs`: `python -c 'import os; print os.statvfs("/")'`

May wanna put it in a loop with a sleep, to get the before and after picture as well, but the key thing is for us to verify that you are indeed getting a weird output during those periods. If the output seems ok, then we're definitely talking about a bug.

**Comment by PNRxA** [comment] 2020-02-18 23:38
Thanks @cakrit I'll let you know how it goes. Since it's a bit intermittent it might take a week or so to get the output.

**Comment by PNRxA** [comment] 2020-02-24 03:56
This can probably be closed for now. The instance which was getting the error consistently was shut down and started again which migrated the host to different hardware.

Since this has been done, the alert hasn't been triggered on that host.

If this issue pops up again, I'll run the python line to get the output.

**Comment by mbarper** [comment] 2020-06-25 17:07
I have this exact problem in some of my instances. I have set a cron every minute to get the statvfs and see the values when the problem happens again. In my case /var is the filesystem affectec. Will let you know the results.

**Comment by mbarper** [comment] 2020-07-01 08:32
This behaviour has happened again and I have the statvfs outputs:
![image](https://user-images.githubusercontent.com/3797030/86221723-913d9c80-bb85-11ea-8be4-39733d106d03.png)

statvfs (Time difference is because server has UTC and my pc has CET):

```
Mon Jun 29 11:15:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621641, f_bavail=4398363, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:16:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621634, f_bavail=4398356, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:17:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621628, f_bavail=4398350, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:18:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621622, f_bavail=4398344, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:19:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621616, f_bavail=4398338, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:20:02 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621610, f_bavail=4398332, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:21:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621605, f_bavail=4398327, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:22:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621314, f_bavail=4398036, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:23:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621309, f_bavail=4398031, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:24:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621303, f_bavail=4398025, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
Mon Jun 29 11:25:01 UTC 2020: posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=5144703, f_bfree=4621296, f_bavail=4398018, f_files=1303040, f_ffree=1298650, f_favail=1298650, f_flag=4096, f_namemax=255)
```

**Comment by cakrit** [comment] 2020-07-07 14:29
@vlvkobal we need to understand what's happening here.
@mbarper can you check the netdata error.log around that time to see if anything interested was recorded?

**Comment by mbarper** [comment] 2020-07-07 16:46
There are no messages in the error.log around that time. It is the first thing I checked.

**Comment by PNRxA** [comment] 2020-07-10 00:11
Didn't have enough time to run the python command but can confirm that this still happens from time to time.
I run this on approximately 60 servers all on AWS EC2 instances.

This is a different server than last time. While I'm guessing that stopping and starting it will fix it, is there any troubleshooting you want me to run?

![image](https://user-images.githubusercontent.com/16978632/87102559-a1483100-c295-11ea-9820-06d6d681df18.png)

**Comment by mfundul** [comment] 2020-07-13 12:11
@PNRxA @mbarper can you test #9531 to see if the problem goes away?
To compile from source you can do the following:
```
git clone https://github.com/netdata/netdata.git
cd netdata/
git fetch origin pull/9531/head:PR9531
git checkout PR9531
```

To get any additional changes from the PR if it's needed you'd have to run:
```
git pull origin pull/9531/head
```
from the same `netdata/` directory.

To replace the existing installation you need to run the installer. Run those from the `netdata/` directory:
```
sudo ./netdata-installer.sh
```

**Comment by mfundul** [comment] 2020-07-13 12:20
Give it some time guys, the Pull Request is not ready yet, I will let you know when to run the code again.

**Comment by mfundul** [comment] 2020-07-13 13:19
Please disregard the PR, it does not fix the issue.

**Closed** 2020-07-14 15:32 UTC
Labels: Cannot reproduce, area/collectors, bug

**Comment by fitzg2** [comment] 2021-03-19 16:13
Has this been fixed for netdata v1.29.3? getting a lot of false positives for the same issue on different disks `/` `/var/tmp/` `/tmp/`

**Comment by ilyam8** [comment] 2021-03-19 17:10
@fitzg2 what version are you on?

---

Well well, i was wondering why `disk_space_usage` is top1 active alarm. Was really doubtful that it is the most common problem 

https://github.com/netdata/netdata/blob/7ac626bb8148976cdaa78baae4de2c1a9a81b898/health/health.d/disks.conf#L20-L21

A lot of users have 90%+ full mountpoints, no way. Looks like this bug contributes a lot in making this alarm top1.

**Comment by ilyam8** [comment] 2021-03-19 17:18
@vlvkobal that is the pattern:
 - `avail` goes to 0
 - `used` stays the same

Perhaps we could spot such situation and apply some workaround. On the other hand, if the problem cause is some hardware problems, we would mask it 🤔 

@PNRxA @PNRxA @fitzg2 , guys, you didn't mention and it is kind of clear from the context, but worth to ask - it is only disk usage, there is no problem with inodes, correct?

**Comment by fitzg2** [comment] 2021-03-19 17:40
> @PNRxA @PNRxA @fitzg2 , guys, you didn't mention and it is kind of clear from the context, but worth to ask - it is only disk usage, there is no problem with inodes, correct?

Actually began to see inode alerts too. Some examples below

disk_inodes._run_netdata | disk inode rate | -127.4 inodes/hour | UNDEFINED
disk_inodes._var_tmp | out of disk inodes time | 5479d 2h | CLEAR
disk_inodes._var_tmp | disk inode rate | 1.99 inodes/hour | UNDEFINED
disk_space._var_tmp | disk fill rate | 0.0000003 GB/hour | UNDEFINED
disk_space._var_tmp | out of disk space time | 460950d 3h | CLEAR

**Comment by ilyam8** [comment] 2021-03-19 18:01
The following alarms were removed in https://github.com/netdata/netdata/pull/10688 because of high chance to false positive :
 - `disk_inode_rate`
 - `out_of_disk_inodes_time`
 - `disk_fill_rate`
 - `out_of_disk_space_time`

Disk utilization alarm (the subject of this topic)

https://github.com/netdata/netdata/blob/7ac626bb8148976cdaa78baae4de2c1a9a81b898/health/health.d/disks.conf#L12-L24

Inodes utilization alarm (i was asking about it)

https://github.com/netdata/netdata/blob/7ac626bb8148976cdaa78baae4de2c1a9a81b898/health/health.d/disks.conf#L26-L38

**Comment by ilyam8** [comment] 2021-03-23 19:53
> I've checked the code once more. We are using the statvfs call to get information from the f_bavail. I don't see how Netdata can screw the value. 

@vlvkobal 

It is interesting, i see `reserved for root` [doesn't change](https://github.com/netdata/netdata/issues/6839#issuecomment-656411143).

https://github.com/netdata/netdata/blob/e5aa543cac723a039ff98b0dc238c861f7807b33/collectors/diskspace.plugin/plugin_diskspace.c#L214-L222


If `f_bavail` is 0, then `breserved_root` (`f_bfree` - `f_bavail`) would increse?

**Comment by vlvkobal** [comment] 2021-03-24 10:28
I guess, AWS EC2 drops `f_bfree` to the same extent as `f_bavail` and their difference is still the same, which is logical as far as this amount of space is _reserved for root_. Unfortunately, we still don't have any information of what are the values of `f_bfree` and `f_bavail` when `avail` drops in the chart. In https://github.com/netdata/netdata/issues/6839#issuecomment-652276300 the drop is at 21:18-21:27, `statvfs()` samples are at 21:01 and 22:01.
