### ISSUE TITLE
[Bug]: Installing via kickstart on Ubuntu requires a manual restart to start agent

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/netdata#13616] opened 2022-09-02 13:41 UTC
### Bug description

In both of the below cases I have to manually restart agent for it to connect to cloud, post a successful claim

1. Installed Ubuntu (22.04.1 LTS) on docker running on a Windows host. Installed Netdata via kickstart, successfully claimed but agent not reachable. Had to manually do "service netdata restart" for cloud connection.

3. Installing Netdata on a Google Colab Notebook which is running Ubuntu 18.04.06 LTS, same as above, Installed Netdata via kickstart, successfully claimed but agent not reachable. Had to manually do "service netdata restart" for cloud connection.

### Expected behavior

Manual restart of agent should not be required when installing Netdata via kickstart on Ubuntu.

### Steps to reproduce

1. On a Windows system with Docker installed, open a terminal and run the following:

- docker pull ubuntu
- docker run -it ubuntu
- (In the new ubuntu terminal) apt update
- (In the new ubuntu terminal) apt-get install wget curl openssl
- (In the new ubuntu terminal) kickstart installation

2. Open Colab in a browser [Google colab](https://colab.research.google.com/) 

- Open a blank new notebook
- Type the kickstart command (preceded by an exclamation mark) in to a cell and run it (shift + enter)

### Installation method

kickstart.sh

### System info

```shell
# uname -a; grep -HvE "^#|URL" /etc/*release
Linux 0b607493177b 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy


!uname -a; grep -HvE "^#|URL" /etc/*release
Linux 1d60e35c48a5 5.4.188+ #1 SMP Sun Apr 24 10:03:06 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.6 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.6 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

### Netdata build info

```shell
# netdata -W buildinfo
Version: netdata v1.36.0-74-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
#
```

**Comment by HariVamsiK** [comment] 2022-09-08 12:56
Hi
I want to work on this issue. Could you please assign it to me, it would be beneficial for my academics too.
Thanks

**Comment by MrZammler** [comment] 2022-10-04 09:30
Hi @shyamvalsan !

Just tried on a clean 22.04 VM and it seems to work ok. Kickstart both started and claimed the agent, so I think on a basic level it's ok. Also updated it to 22.04.1 and it seems to work.

On the colab notebook, indeed the netdata service is not started from the kickstart script. There is an output:
```
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
```

But that seems more like a "problem" with the environment rather that our script (which will try to start the service).

I couldn't get much far on linux/docker as you described, most likely my own setup's problem.

Is it possible to try the windows/docker setup again, and paste the output?

**Comment by shyamvalsan** [comment] 2022-10-10 08:41
@MrZammler still see the problem in windows/docker ubuntu setup. Here's the stdout, let me know if you want me to grab any logs.

```
# wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --claim-token EXBWh1IBX7PDPxGPD9iI4hkLS7Hvfbgx0-XLs96CFwvyUjh1LorJi3EIi_fMjtYl3u27dRQQYyokd5yltMUjXhsJpKhDSpkO9XWHgLJ6exZfiz6C0apLL9GUKbVxHo2k32Dw-pA --claim-url https://app.netdata.cloud
--2022-10-10 08:39:58--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 188.114.96.1, 188.114.97.1, 2a06:98c1:3121::1, ...
Connecting to my-netdata.io (my-netdata.io)|188.114.96.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: '/tmp/netdata-kickstart.sh'

/tmp/netdata-kickstart.sh         [ <=>                                              ]  75.15K  --.-KB/s    in 0.04s

2022-10-10 08:39:58 (1.68 MB/s) - '/tmp/netdata-kickstart.sh' saved [76956]


 --- Using /tmp/netdata-kickstart-MzjwPKx2UL as a temporary directory. ---
 --- Checking for existing installations of Netdata... ---
 --- No existing installations of netdata found, assuming this is a fresh install. ---
 --- Attempting to install using native packages... ---
 --- Checking for availability of repository configuration package. ---
[/tmp/netdata-kickstart-MzjwPKx2UL]# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-MzjwPKx2UL/netdata-repo-edge_1-2_all.deb https://packagecloud.io/netdata/netdata-repoconfig/packages/ubuntu/jammy/netdata-repo-edge_1-2_all.deb/download.deb
 OK

[/tmp/netdata-kickstart-MzjwPKx2UL]# env apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
 OK

[/tmp/netdata-kickstart-MzjwPKx2UL]# env apt-get install /tmp/netdata-kickstart-MzjwPKx2UL/netdata-repo-edge_1-2_all.deb

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'netdata-repo-edge' instead of '/tmp/netdata-kickstart-MzjwPKx2UL/netdata-repo-edge_1-2_all.deb'
The following additional packages will be installed:
  debian-archive-keyring dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf
  gpgsm libassuan0 libksba8 libnpth0 libreadline8 libsqlite3-0 pinentry-curses readline-common
Suggested packages:
  dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage scdaemon pinentry-doc readline-doc
The following NEW packages will be installed:
  debian-archive-keyring dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf
  gpgsm libassuan0 libksba8 libnpth0 libreadline8 libsqlite3-0 netdata-repo-edge pinentry-curses readline-common
0 upgraded, 19 newly installed, 0 to remove and 10 not upgraded.
Need to get 3250 kB/3257 kB of archives.
After this operation, 8230 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 /tmp/netdata-kickstart-MzjwPKx2UL/netdata-repo-edge_1-2_all.deb netdata-repo-edge all 1-2 [7100 B]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 readline-common all 8.1.2-1 [53.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libreadline8 amd64 8.1.2-1 [153 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsqlite3-0 amd64 3.37.2-2 [643 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 debian-archive-keyring all 2021.1.1ubuntu2 [90.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libassuan0 amd64 2.5.5-1build1 [38.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gpgconf amd64 2.2.27-3ubuntu2.1 [94.2 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libksba8 amd64 1.6.0-2build1 [119 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libnpth0 amd64 1.6-3build2 [8664 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 dirmngr amd64 2.2.27-3ubuntu2.1 [293 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gnupg-l10n all 2.2.27-3ubuntu2.1 [54.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gnupg-utils amd64 2.2.27-3ubuntu2.1 [308 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gpg amd64 2.2.27-3ubuntu2.1 [519 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 pinentry-curses amd64 1.1.1-1build2 [34.4 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gpg-agent amd64 2.2.27-3ubuntu2.1 [209 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gpg-wks-client amd64 2.2.27-3ubuntu2.1 [62.7 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gpg-wks-server amd64 2.2.27-3ubuntu2.1 [57.5 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gpgsm amd64 2.2.27-3ubuntu2.1 [197 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gnupg all 2.2.27-3ubuntu2.1 [315 kB]
Fetched 3250 kB in 3s (1017 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package readline-common.
(Reading database ... 4979 files and directories currently installed.)
Preparing to unpack .../00-readline-common_8.1.2-1_all.deb ...
Unpacking readline-common (8.1.2-1) ...
Selecting previously unselected package libreadline8:amd64.
Preparing to unpack .../01-libreadline8_8.1.2-1_amd64.deb ...
Unpacking libreadline8:amd64 (8.1.2-1) ...
Selecting previously unselected package libsqlite3-0:amd64.
Preparing to unpack .../02-libsqlite3-0_3.37.2-2_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.37.2-2) ...
Selecting previously unselected package debian-archive-keyring.
Preparing to unpack .../03-debian-archive-keyring_2021.1.1ubuntu2_all.deb ...
Unpacking debian-archive-keyring (2021.1.1ubuntu2) ...
Selecting previously unselected package libassuan0:amd64.
Preparing to unpack .../04-libassuan0_2.5.5-1build1_amd64.deb ...
Unpacking libassuan0:amd64 (2.5.5-1build1) ...
Selecting previously unselected package gpgconf.
Preparing to unpack .../05-gpgconf_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpgconf (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package libksba8:amd64.
Preparing to unpack .../06-libksba8_1.6.0-2build1_amd64.deb ...
Unpacking libksba8:amd64 (1.6.0-2build1) ...
Selecting previously unselected package libnpth0:amd64.
Preparing to unpack .../07-libnpth0_1.6-3build2_amd64.deb ...
Unpacking libnpth0:amd64 (1.6-3build2) ...
Selecting previously unselected package dirmngr.
Preparing to unpack .../08-dirmngr_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking dirmngr (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gnupg-l10n.
Preparing to unpack .../09-gnupg-l10n_2.2.27-3ubuntu2.1_all.deb ...
Unpacking gnupg-l10n (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gnupg-utils.
Preparing to unpack .../10-gnupg-utils_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gnupg-utils (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gpg.
Preparing to unpack .../11-gpg_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpg (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package pinentry-curses.
Preparing to unpack .../12-pinentry-curses_1.1.1-1build2_amd64.deb ...
Unpacking pinentry-curses (1.1.1-1build2) ...
Selecting previously unselected package gpg-agent.
Preparing to unpack .../13-gpg-agent_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpg-agent (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gpg-wks-client.
Preparing to unpack .../14-gpg-wks-client_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpg-wks-client (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gpg-wks-server.
Preparing to unpack .../15-gpg-wks-server_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpg-wks-server (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gpgsm.
Preparing to unpack .../16-gpgsm_2.2.27-3ubuntu2.1_amd64.deb ...
Unpacking gpgsm (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package gnupg.
Preparing to unpack .../17-gnupg_2.2.27-3ubuntu2.1_all.deb ...
Unpacking gnupg (2.2.27-3ubuntu2.1) ...
Selecting previously unselected package netdata-repo-edge.
Preparing to unpack .../18-netdata-repo-edge_1-2_all.deb ...
Unpacking netdata-repo-edge (1-2) ...
Setting up libksba8:amd64 (1.6.0-2build1) ...
Setting up libsqlite3-0:amd64 (3.37.2-2) ...
Setting up debian-archive-keyring (2021.1.1ubuntu2) ...
Setting up libnpth0:amd64 (1.6-3build2) ...
Setting up libassuan0:amd64 (2.5.5-1build1) ...
Setting up gnupg-l10n (2.2.27-3ubuntu2.1) ...
Setting up readline-common (8.1.2-1) ...
Setting up pinentry-curses (1.1.1-1build2) ...
Setting up libreadline8:amd64 (8.1.2-1) ...
Setting up gpgconf (2.2.27-3ubuntu2.1) ...
Setting up gpg (2.2.27-3ubuntu2.1) ...
Setting up gnupg-utils (2.2.27-3ubuntu2.1) ...
Setting up gpg-agent (2.2.27-3ubuntu2.1) ...
Setting up gpgsm (2.2.27-3ubuntu2.1) ...
Setting up dirmngr (2.2.27-3ubuntu2.1) ...
Setting up gpg-wks-server (2.2.27-3ubuntu2.1) ...
Setting up gpg-wks-client (2.2.27-3ubuntu2.1) ...
Setting up gnupg (2.2.27-3ubuntu2.1) ...
Setting up netdata-repo-edge (1-2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
N: Download is performed unsandboxed as root as file '/tmp/netdata-kickstart-MzjwPKx2UL/netdata-repo-edge_1-2_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
 OK

[/tmp/netdata-kickstart-MzjwPKx2UL]# env apt-get update
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 https://packagecloud.io/netdata/netdata-edge/ubuntu jammy InRelease [24.8 kB]
Get:6 https://packagecloud.io/netdata/netdata-repoconfig/ubuntu jammy InRelease [24.8 kB]
Get:7 https://packagecloud.io/netdata/netdata-edge/ubuntu jammy/main amd64 Packages [16.3 kB]
Get:8 https://packagecloud.io/netdata/netdata-repoconfig/ubuntu jammy/main amd64 Packages [1087 B]
Fetched 67.0 kB in 4s (18.4 kB/s)
Reading package lists... Done
 OK

[/tmp/netdata-kickstart-MzjwPKx2UL]# env apt-get install netdata
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libcap2-bin libelf1 libjson-c5 libmnl0 libnetfilter-acct1 libpam-cap libprotobuf23 libsnappy1v5 libuv1
The following NEW packages will be installed:
  libcap2-bin libelf1 libjson-c5 libmnl0 libnetfilter-acct1 libpam-cap libprotobuf23 libsnappy1v5 libuv1 netdata
0 upgraded, 10 newly installed, 0 to remove and 10 not upgraded.
Need to get 28.1 MB of archives.
After this operation, 129 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcap2-bin amd64 1:2.44-1build3 [26.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libelf1 amd64 0.186-1build1 [51.0 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libjson-c5 amd64 0.15-3~ubuntu1.22.04.1 [33.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmnl0 amd64 1.0.4-3build2 [13.2 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libnetfilter-acct1 amd64 1.0.3-3 [7228 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libprotobuf23 amd64 3.12.4-1ubuntu7 [876 kB]
Get:7 https://packagecloud.io/netdata/netdata-edge/ubuntu jammy/main amd64 netdata amd64 1.36.0-189-nightly [27.0 MB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsnappy1v5 amd64 1.1.8-1build3 [17.5 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libuv1 amd64 1.43.0-1 [93.1 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpam-cap amd64 1:2.44-1build3 [7932 B]
Fetched 28.1 MB in 2s (15.9 MB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libcap2-bin.
(Reading database ... 5241 files and directories currently installed.)
Preparing to unpack .../0-libcap2-bin_1%3a2.44-1build3_amd64.deb ...
Unpacking libcap2-bin (1:2.44-1build3) ...
Selecting previously unselected package libelf1:amd64.
Preparing to unpack .../1-libelf1_0.186-1build1_amd64.deb ...
Unpacking libelf1:amd64 (0.186-1build1) ...
Selecting previously unselected package libjson-c5:amd64.
Preparing to unpack .../2-libjson-c5_0.15-3~ubuntu1.22.04.1_amd64.deb ...
Unpacking libjson-c5:amd64 (0.15-3~ubuntu1.22.04.1) ...
Selecting previously unselected package libmnl0:amd64.
Preparing to unpack .../3-libmnl0_1.0.4-3build2_amd64.deb ...
Unpacking libmnl0:amd64 (1.0.4-3build2) ...
Selecting previously unselected package libnetfilter-acct1:amd64.
Preparing to unpack .../4-libnetfilter-acct1_1.0.3-3_amd64.deb ...
Unpacking libnetfilter-acct1:amd64 (1.0.3-3) ...
Selecting previously unselected package libprotobuf23:amd64.
Preparing to unpack .../5-libprotobuf23_3.12.4-1ubuntu7_amd64.deb ...
Unpacking libprotobuf23:amd64 (3.12.4-1ubuntu7) ...
Selecting previously unselected package libsnappy1v5:amd64.
Preparing to unpack .../6-libsnappy1v5_1.1.8-1build3_amd64.deb ...
Unpacking libsnappy1v5:amd64 (1.1.8-1build3) ...
Selecting previously unselected package libuv1:amd64.
Preparing to unpack .../7-libuv1_1.43.0-1_amd64.deb ...
Unpacking libuv1:amd64 (1.43.0-1) ...
Selecting previously unselected package netdata.
Preparing to unpack .../8-netdata_1.36.0-189-nightly_amd64.deb ...
Unpacking netdata (1.36.0-189-nightly) ...
Selecting previously unselected package libpam-cap:amd64.
Preparing to unpack .../9-libpam-cap_1%3a2.44-1build3_amd64.deb ...
Unpacking libpam-cap:amd64 (1:2.44-1build3) ...
Setting up libprotobuf23:amd64 (3.12.4-1ubuntu7) ...
Setting up libsnappy1v5:amd64 (1.1.8-1build3) ...
Setting up libcap2-bin (1:2.44-1build3) ...
Setting up libuv1:amd64 (1.43.0-1) ...
Setting up libmnl0:amd64 (1.0.4-3build2) ...
Setting up libnetfilter-acct1:amd64 (1.0.3-3) ...
Setting up libelf1:amd64 (0.186-1build1) ...
Setting up libpam-cap:amd64 (1:2.44-1build3) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libjson-c5:amd64 (0.15-3~ubuntu1.22.04.1) ...
Setting up netdata (1.36.0-189-nightly) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
 OK

 --- Attempting to claim agent to https://app.netdata.cloud ---
 --- Attempting to claim agent to https://app.netdata.cloud ---
[/tmp/netdata-kickstart-MzjwPKx2UL]# /usr/sbin/netdata-claim.sh -token=EXBWh1IBX7PDPxGPD9iI4hkLS7Hvfbgx0-XLs96CFwvyUjh1LorJi3EIi_fMjtYl3u27dRQQYyokd5yltMUjXhsJpKhDSpkO9XWHgLJ6exZfiz6C0apLL9GUKbVxHo2k32Dw-pA -rooms= -url=https://app.netdata.cloud -daemon-not-running
Unable to communicate with Netdata daemon, querying config from disk instead.
Unable to communicate with Netdata daemon, querying config from disk instead.
Token: ****************
Base URL: https://app.netdata.cloud
Id: 45b2e43e-530e-41a1-b8ff-3d46759b4271
Rooms:
Hostname: be8c7916c25e
Proxy:
Netdata user: netdata
Generating private/public key for the first time.
Extracting public key from private key.
writing RSA key
Connection attempt 1 successful
uv_pipe_connect(): no such file or directory
Make sure the netdata service is running.
The claim was successful but the agent could not be notified (0)- it requires a restart to connect to the cloud.
 OK

 --- Successfully claimed node ---
Mon Oct 10 08:40:19 UTC 2022 : INFO: netdata-updater.sh:  Auto-updating has been ENABLED through cron, updater script linked to /etc/cron.daily/netdata-updater

Mon Oct 10 08:40:19 UTC 2022 : INFO: netdata-updater.sh:  If the update process fails and you have email notifications set up correctly for cron on this system, you should receive an email notification of the failure.
Mon Oct 10 08:40:19 UTC 2022 : INFO: netdata-updater.sh:  Successful updates will not send an email.
Successfully installed the Netdata Agent.

Official documentation can be found online at https://learn.netdata.cloud/docs/.

Looking to monitor all of your infrastructure with Netdata? Check out Netdata Cloud at https://app.netdata.cloud.

Join our community and connect with us on:
  - GitHub: https://github.com/netdata/netdata/discussions
  - Discord: https://discord.gg/5ygS846fR6
  - Our community forums: https://community.netdata.cloud/
#
```

**Comment by MrZammler** [comment] 2022-10-19 08:08
It [appears](https://stackoverflow.com/questions/46247032/how-to-solve-invoke-rc-d-policy-rc-d-denied-execution-of-start-when-building) to be a docker _problem_ rather than netdata's.

More here: http://jpetazzo.github.io/2013/10/06/policy-rc-d-do-not-start-services-automatically/

If I understand correctly, by default Ubuntu under docker prohibits services (not just netdata) from starting automatically. I don't think it's a good idea to override this from our script. Perhaps we could just print a proper message when we detect that we couldn't run the service? @Ferroin ?

**Comment by Dim-P** [comment] 2022-10-20 15:33
Is this expected behaviour then? Doesn't sound like a Netdata bug to me.

**Comment by Ferroin** [comment] 2022-10-20 17:36
Yes, it’s generally expected when running in a context without a usable service manager that we can’t start the agent as part of the install.

**Comment by Dim-P** [comment] 2022-10-20 17:49
@shyamvalsan Are you OK if we close this since it isn't actually a bug on our end?

**Closed** 2022-10-21 09:55 UTC
Labels: bug, needs triage
