### ISSUE TITLE
Latest update failure on Docker

### ISSUE THREAD

**Issue by schklom** [netdata/netdata#10581] opened 2021-02-02 04:50 UTC
##### Bug report summary

On startup after new update, the container crashes with this log:
```
Error loading shared library libprotobuf.so.24: No such file or directory (needed by /usr/sbin/netdata)
Error relocating /usr/sbin/netdata: __fstat_time64: symbol not found
Error relocating /usr/sbin/netdata: __getrusage_time64: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal13OnShutdownRunEPFvPKvES3_: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal9ArenaImpl28AllocateAlignedAndAddCleanupEjPFvPvE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf5Arena19CallDestructorHooksEv: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal17AssignDescriptorsEPKNS1_15DescriptorTableEb: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal18EpsCopyInputStream12DoneFallbackEPKci: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf11StringPiece18LogFatalSizeTooBigEjPKc: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf5Arena21AllocateAlignedNoHookEj: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal10VerifyUTF8ENS0_11StringPieceEPKc: symbol not found
Error relocating /usr/sbin/netdata: __gmtime64_r: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal16ReadSizeFallbackEPKcj: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal12ExtensionSet17RegisterExtensionEPKNS0_11MessageLiteEihbb: symbol not found
Error relocating /usr/sbin/netdata: __nanosleep_time64: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal9ArenaImplD1Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal10WireFormat37InternalSerializeUnknownFieldsToArrayERKNS0_15UnknownFieldSetEPhPNS0_2io19EpsCopyOutputStreamE: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf11MessageLite17SerializeToStringEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal20RepeatedPtrFieldBase7ReserveEi: symbol not found
Error relocating /usr/sbin/netdata: __mktime64: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal14WireFormatLite16VerifyUtf8StringEPKciNS2_9OperationES4_: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf5Arena17OnArenaAllocationEPKSt9type_infoj: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal15ReadTagFallbackEPKcj: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf8internal9ArenaImpl14SpaceAllocatedEv: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal13ReflectionOps5MergeERKNS0_7MessageEPS3_: symbol not found
Error relocating /usr/sbin/netdata: __select_time64: symbol not found
Error relocating /usr/sbin/netdata: __pselect_time64: symbol not found
Error relocating /usr/sbin/netdata: __utimes_time64: symbol not found
Error relocating /usr/sbin/netdata: __gettimeofday_time64: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal11InitSCCImplEPNS1_11SCCInfoBaseE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal13VerifyVersionEiiPKc: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf15UnknownFieldSet9MergeFromERKS1_: symbol not found
Error relocating /usr/sbin/netdata: __localtime64_r: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal11LogFinisheraSERNS1_10LogMessageE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf2io19EpsCopyOutputStream30WriteStringMaybeAliasedOutlineEjRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPh: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf15UnknownFieldSet13ClearFallbackEv: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal17UnknownFieldParseEyPNS0_15UnknownFieldSetEPKcPNS1_12ParseContextE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf2io19EpsCopyOutputStream19EnsureSpaceFallbackEPh: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal10LogMessageC1ENS0_8LogLevelEPKci: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf23ShutdownProtobufLibraryEv: symbol not found
Error relocating /usr/sbin/netdata: __stat_time64: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal20RepeatedPtrFieldBase14InternalExtendEi: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal10LogMessagelsEPKc: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal14AddDescriptorsEPKNS1_15DescriptorTableE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal10LogMessageD1Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal9ArenaImpl4InitEv: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal24ComputeUnknownFieldsSizeERKNS1_16InternalMetadataEjPNS1_10CachedSizeE: symbol not found
Error relocating /usr/sbin/netdata: __recvmmsg_time64: symbol not found
Error relocating /usr/sbin/netdata: __clock_gettime64: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal24InlineGreedyStringParserEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKcPNS1_12ParseContextE: symbol not found
Error relocating /usr/sbin/netdata: __lstat_time64: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal17VarintParseSlow64EPKcj: symbol not found
Error relocating /usr/sbin/netdata: __localtime64: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf12FieldOptions16default_instanceEv: symbol not found
Error relocating /usr/sbin/netdata: __time64: symbol not found
Error relocating /usr/sbin/netdata: descriptor_table_google_2fprotobuf_2fdescriptor_2eproto: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message25InitializationErrorStringB5cxx11Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message25InitializationErrorStringB5cxx11Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message25InitializationErrorStringB5cxx11Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message25InitializationErrorStringB5cxx11Ev: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf7Message21CheckTypeAndMergeFromERKNS0_11MessageLiteE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf7Message21CheckTypeAndMergeFromERKNS0_11MessageLiteE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf7Message21CheckTypeAndMergeFromERKNS0_11MessageLiteE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf7Message21CheckTypeAndMergeFromERKNS0_11MessageLiteE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf7Message20DiscardUnknownFieldsEv: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf7Message20DiscardUnknownFieldsEv: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf7Message20DiscardUnknownFieldsEv: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf7Message20DiscardUnknownFieldsEv: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message13SpaceUsedLongEv: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message13SpaceUsedLongEv: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message13SpaceUsedLongEv: symbol not found
Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message13SpaceUsedLongEv: symbol not found
Error relocating /usr/sbin/netdata: _ZTIN6google8protobuf7MessageE: symbol not found
Error relocating /usr/sbin/netdata: _ZTIN6google8protobuf7MessageE: symbol not found
Error relocating /usr/sbin/netdata: _ZTIN6google8protobuf7MessageE: symbol not found
Error relocating /usr/sbin/netdata: _ZTIN6google8protobuf7MessageE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal14DestroyMessageEPKv: symbol not found
Error relocating /usr/sbin/netdata: _ZTVN6google8protobuf11MessageLiteE: symbol not found
Error relocating /usr/sbin/netdata: _ZN6google8protobuf15UnknownFieldSet16default_instanceEv: symbol not found
Error relocating /usr/sbin/netdata: _ZTVN6google8protobuf7MessageE: symbol not found
Error relocating /usr/sbin/netdata: __stat_time64: symbol not found
Error relocating /usr/sbin/netdata: __fstat_time64: symbol not found
Error relocating /usr/sbin/netdata: __lstat_time64: symbol not found
```

##### OS / Environment

```
$ uname -a; grep -Hv "^#" /etc/*release
Linux MYHOSTNAME 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version

The closest I can give is the image digest since the container fails to properly start:
```
$ docker pull netdata/netdata
Using default tag: latest
latest: Pulling from netdata/netdata
Digest: sha256:e8d5fb55835a62580ed5aabeb518aebbe620030190845572de7d705e71286f63
Status: Image is up to date for netdata/netdata:latest
docker.io/netdata/netdata:latest
```

##### Component Name

The entire Docker container.

##### Steps To Reproduce

The bug appeared before I updated my docker. Even after `apt update && apt full-upgrade`, the bug is still there.
docker-compose.yml:
```
version: "3.8"

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: "no"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

##### Expected behavior

As before the last update, I expected the container to start and have very well designed graphs :D
Thanks for the container guys, I love it despite this bug :)

**Comment by mbartosi** [comment] 2021-02-02 06:05
Same here:

netdata    | Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message13SpaceUsedLongEv: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message13SpaceUsedLongEv: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message13SpaceUsedLongEv: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZNK6google8protobuf7Message13SpaceUsedLongEv: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZTIN6google8protobuf7MessageE: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZTIN6google8protobuf7MessageE: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZTIN6google8protobuf7MessageE: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZTIN6google8protobuf7MessageE: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZN6google8protobuf8internal14DestroyMessageEPKv: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZTVN6google8protobuf11MessageLiteE: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZN6google8protobuf15UnknownFieldSet16default_instanceEv: symbol not found
netdata    | Error relocating /usr/sbin/netdata: _ZTVN6google8protobuf7MessageE: symbol not found

**Comment by TheCatLady** [comment] 2021-02-02 06:36
Also experiencing this same issue.  Reverting to `netdata/netdata:v1.28.0.226.latest` in the meantime.

**Comment by ilyam8** [comment] 2021-02-02 08:26
Thx for reporting, guys! We are checking what happened.

**Comment by DavidPesticcio** [comment] 2021-02-02 12:48
## FYI

> Netdata Docker container error loading shared library libprotobuf.so.24, after upgrading from 1.26 to 1.28

https://github.com/netdata/netdata/issues/10582#issuecomment-771606027

**Comment by ilyam8** [comment] 2021-02-02 12:48
Related issue #10582

This one is about `latest` tag, #10582 is about `v1.28.0`.

**Comment by Ferroin** [comment] 2021-02-02 12:57
They’re the same bug in the image itself. The tagging problem that meant that 1.28.0 was affected is fixed now though.

I’m currently working on reproducing the exact issue here (a local build of the same version that the nightly image was based on does not have the problem, so I’m sincerely hoping that the linking issue with protobuf was a transient error of some sort).

**Comment by Ferroin** [comment] 2021-02-02 13:42
We’re now pointing people at this forum topic https://community.netdata.cloud/t/today-docker-image-not-working/861 for any futher updates.

This issue will be closed only once we have the `latest` tag fixed so that it’s working properly again. Any other updates will be posted to the aforementioned forum topic.

**Comment by Ferroin** [comment] 2021-02-02 14:09
The `latest` tag now appears to be working correctly.

We’re not sure what exactly went wrong with last-night’s nightly, but it looks like it was just a transient error.

**Closed by Ferroin** 2021-02-02 14:09 UTC
Labels: area/packaging, bug, needs triage, priority/high
