### ISSUE TITLE
ebpf plugin memory violation

### ISSUE THREAD

**Issue by prophoto** [netdata/netdata#9522] opened 2020-07-10 23:35 UTC
Installed Netdata on a second web server today from script. Works fine except I can't get apache logs to show up. This is my latest error in /var/log/audit/audit.log

type=ANOM_ABEND msg=audit(1594422517.795:1589560): auid=4294967295 uid=994 gid=991 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 pid=19998 comm="ebpf.plugin" reason="memory violation" sig=6

I had followed this tutorial and it seemed to bypass SELinux. I currently have setenforce 0 so its not caused by SELinux.
https://learn.netdata.cloud/docs/agent/collectors/ebpf.plugin#creation-of-bpf-policies

##### OS / Environment
/etc/centos-release:CentOS Linux release 7.7.1908 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.7.1908 (Core)
/etc/system-release:CentOS Linux release 7.7.1908 (Core)

##### Netdata version
netdata v1.23.1-62-nightly

**Comment by prophoto** [comment] 2020-07-10 23:37
$ cat /var/log/netdata/error.log

2020-07-10 23:18:55: netdata INFO  : PLUGINSD : stopping plugin thread: plugin:ebpf
2020-07-10 23:18:55: netdata INFO  : PLUGINSD[ebpf] : data collection thread exiting
2020-07-10 23:18:55: netdata INFO  : PLUGINSD[ebpf] : killing child process pid 20513
2020-07-10 23:18:55: netdata INFO  : PLUGINSD[ebpf] : waiting for child process pid 20513 to exit...
2020-07-10 23:18:55: ebpf.plugin INFO  : EBPF SOCKET : thread with task id 20531 finished
2020-07-10 23:18:55: ebpf.plugin INFO  : EBPF PROCESS : thread with task id 20530 finished
2020-07-10 23:18:57: netdata INFO  : PLUGINSD[ebpf] : thread created with task id 21624
2020-07-10 23:18:57: netdata INFO  : PLUGINSD[ebpf] : set name of thread 21624 to PLUGINSD[ebpf]
2020-07-10 23:18:57: netdata INFO  : PLUGINSD[ebpf] : connected to '/usr/libexec/netdata/plugins.d/ebpf.plugin' running on pid 21633
2020-07-10 23:18:57:  ERROR : MAIN : Does not have a configuration file inside `/etc/netdata/ebpf.conf. It will try to load stock file. (errno 2, No such file or directory)
2020-07-10 23:18:57: ebpf.plugin INFO  : EBPF PROCESS : thread created with task id 21650
2020-07-10 23:18:57: ebpf.plugin INFO  : EBPF PROCESS : set name of thread 21650 to EBPF PROCESS
2020-07-10 23:18:57: ebpf.plugin INFO  : EBPF PROCESS : Cannot load library /usr/libexec/netdata/plugins.d/libnetdata_ebpf.so.3.10.0-1062.12.1.el7.x86_64 for the current kernel.
2020-07-10 23:18:57: ebpf.plugin INFO  : EBPF PROCESS : Default shared library /usr/libexec/netdata/plugins.d/libnetdata_ebpf.so.3.10.0 loaded with success.
2020-07-10 23:18:57: ebpf.plugin INFO  : EBPF SOCKET : thread created with task id 21651
2020-07-10 23:18:57: ebpf.plugin INFO  : EBPF SOCKET : set name of thread 21651 to EBPF SOCKET
2020-07-10 23:18:57: ebpf.plugin INFO  : EBPF PROCESS : The eBPF program process was loaded with success.
2020-07-10 23:18:57: ebpf.plugin INFO  : EBPF SOCKET : Current shared library /usr/libexec/netdata/plugins.d/libnetdata_ebpf.so.3.10.0 loaded with success.
2020-07-10 23:18:57: ebpf.plugin INFO  : EBPF SOCKET : The eBPF program socket was loaded with success.
2020-07-10 23:19:57: ebpf.plugin ERROR : EBPF PROCESS : pid 21949 sshd states parent 21948, but the later does not exist. (errno 2, No such file or directory)
2020-07-10 23:24:01: ebpf.plugin ERROR : EBPF PROCESS : heartbeat missed 991930 monotonic microseconds
2020-07-10 23:24:07: ebpf.plugin ERROR : EBPF PROCESS : heartbeat missed 974930 monotonic microseconds

**Comment by thiagoftsm** [comment] 2020-07-11 11:10
Hi @prophoto ,

Thank you for your report. Does the error happen during runtime or when you were stopping Netdata? If this happens when you are stopping Netdata, we already have a [PR](https://github.com/netdata/netdata/pull/9484) for it that will be merged next week.

Best regards!

**Comment by prophoto** [comment] 2020-07-13 20:36
Must be at launch since I never get any Apache info into Netdata.

**Comment by thiagoftsm** [comment] 2020-07-13 23:03
Hi @prophoto ,

The following message:

> 2020-07-10 23:19:57: ebpf.plugin ERROR : EBPF PROCESS : pid 21949 sshd states parent 21948, but the later does not exist. (errno 2, No such file or directory)

Is happening because the `ebpf.plugin`  is right now using `/proc` to keep parity with `apps.plugin` charts, and I understand that this can generate a lot of error messages. I updated the PR [9484](https://github.com/netdata/netdata/pull/9484/) to hide these messages that are not a bug, in reality they are more informative.

Best regards!

**Comment by prophoto** [comment] 2020-07-14 13:22
I was hoping this was the cause of my failure to get Apache info into Netdata. I've followed your tutorials and have it working on one of my instances, but can't get it going on a second. Suggestions where I can look to get it going? Any normal screw ups by noobies? Thanks.

**Closed** 2020-07-14 16:42 UTC
Labels: bug, ebpf, needs triage

**Comment by thiagoftsm** [comment] 2020-07-14 19:44
Hi @prophoto ,

The `ebpf.plugin` reads information from kernel ring and allocates memory direct on `heap`, so it cannot have direct relationship with the Apache.
I am not sure about what you are trying to monitor, so I will give you all links that come in mind and I hope they will help you:

- To monitor weblog you have this: https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/weblog
- You can also use `go.d.plugin` to monitor direct the server : https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/apache

These are the tools that I am sure Netdata has to monitor Apache, if this is not enough, please, let us know !

best regards!

**Comment by ilyam8** [comment] 2020-07-14 19:51
> Works fine except I can't get apache logs to show up.

yeah, you dont use `ebpf.plugin` to parse apache logs.

I really dont understand the issue, i was thinking it is ebpf related.

> type=ANOM_ABEND msg=audit(1594422517.795:1589560): auid=4294967295 uid=994 gid=991 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 pid=19998 comm="ebpf.plugin" reason="memory violation" sig=6

@thiagoftsm @Ferroin ^^ is that a problem?

**Comment by thiagoftsm** [comment] 2020-07-14 20:54
@ilyam8  these errors are normal when the Linux has SELinux enabled. Every time this happens, it is necessary to configure SELinux to allow ebpf.plugin to run. We documented the steps for the users to change their system, we are not doing automatically, because this affects directly the user policy.

**Comment by prophoto** [comment] 2020-07-17 14:28
Still figuring Netadata out. I'm sure I will like it more once its working as I need it to! I think I have apache monitoring working based on output below, but its still not showing in the GUI. Thoughts? Do I need to whitelist any other IPs for it to work? Right now I only have localhost, server IP and my work IP.

bash-4.2$ cd /usr/libexec/netdata/plugins.d/
bash-4.2$ ./go.d.plugin -d -m apache
[ INFO  ] main[main] plugin.go:102 instance is started
[ INFO  ] main[main] setup.go:39 loading config file
[ INFO  ] main[main] setup.go:47 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:54 found '/etc/netdata/go.d.conf
[ INFO  ] main[main] setup.go:61 config successfully loaded
[ INFO  ] main[main] plugin.go:106 using config: enabled 'true', default_run 'true', max_procs '0', explicitly enabled modules '1'
[ INFO  ] main[main] setup.go:66 loading modules
[ INFO  ] main[main] setup.go:85 enabled/registered modules: 1/43
[ INFO  ] main[main] setup.go:90 building discovery config
[ INFO  ] main[main] setup.go:116 looking for 'apache.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:123 found '/etc/netdata/go.d/apache.conf
[ INFO  ] main[main] setup.go:128 dummy/read/watch paths: 0/1/0
[ INFO  ] discovery[manager] manager.go:90 registered discoverers: [file discovery: [file reader]]
[ INFO  ] discovery[manager] manager.go:95 instance is started
[ INFO  ] run[manager] run.go:30 instance is started
[ INFO  ] build[manager] build.go:91 instance is started
[ INFO  ] discovery[file manager] discovery.go:71 instance is started
[ INFO  ] discovery[file reader] read.go:39 instance is started
[ INFO  ] discovery[file reader] read.go:40 instance is stopped
[ DEBUG ] apache[local] apache.go:83 using URL http://localhost/server-status?auto
[ DEBUG ] apache[local] apache.go:84 using timeout: 2s
[ INFO  ] apache[local] job.go:152 check success
[ DEBUG ] apache[remote] apache.go:83 using URL http://status.myserverdomain.net/server-status?auto
[ DEBUG ] apache[remote] apache.go:84 using timeout: 2s
[ INFO  ] apache[local] job.go:172 started, data collection interval 1s
[ INFO  ] apache[remote] job.go:152 check success
[ INFO  ] apache[remote] job.go:172 started, data collection interval 1s
[ DEBUG ] run[manager] run.go:41 tick 0
CHART 'netdata.execution_time_of_apache_local' '' 'Execution Time for apache_local' 'ms' 'go.d' 'netdata.go_plugin_execution_time' '' '145000' '1' '' 'go.d' 'apache'
DIMENSION 'time' '' '' '1' '1' ''

CHART 'apache_local.requests' '' 'Requests' 'requests/s' 'requests' 'apache.requests' '' '70000' '1' '' 'go.d' 'apache'
DIMENSION 'total_accesses' 'requests' 'incremental' '1' '1' ''

BEGIN apache_local.requests
SET total_accesses = 1791264
END

CHART 'apache_local.connections' '' 'Connections' 'connections' 'connections' 'apache.connections' '' '70001' '1' '' 'go.d' 'apache'
DIMENSION 'conns_total' 'connections' '' '1' '1' ''

BEGIN apache_local.connections
SET conns_total = 
END

CHART 'apache_local.conns_async' '' 'Async Connections' 'connections' 'connections' 'apache.conns_async' 'stacked' '70002' '1' '' 'go.d' 'apache'
DIMENSION 'conns_async_keep_alive' 'keepalive' '' '1' '1' ''
DIMENSION 'conns_async_closing' 'closing' '' '1' '1' ''
DIMENSION 'conns_async_writing' 'writing' '' '1' '1' ''

BEGIN apache_local.conns_async
SET conns_async_keep_alive = 
SET conns_async_closing = 
SET conns_async_writing = 
END

CHART 'apache_local.scoreboard' '' 'Scoreboard' 'connections' 'connections' 'apache.scoreboard' '' '70003' '1' '' 'go.d' 'apache'
DIMENSION 'scoreboard_waiting' 'waiting' '' '1' '1' ''
DIMENSION 'scoreboard_starting' 'starting' '' '1' '1' ''
DIMENSION 'scoreboard_reading' 'reading' '' '1' '1' ''
DIMENSION 'scoreboard_sending' 'sending' '' '1' '1' ''
DIMENSION 'scoreboard_keepalive' 'keepalive' '' '1' '1' ''
DIMENSION 'scoreboard_dns_lookup' 'dns lookup' '' '1' '1' ''
DIMENSION 'scoreboard_closing' 'closing' '' '1' '1' ''
DIMENSION 'scoreboard_logging' 'logging' '' '1' '1' ''
DIMENSION 'scoreboard_finishing' 'finishing' '' '1' '1' ''
DIMENSION 'scoreboard_idle_cleanup' 'idle cleanup' '' '1' '1' ''
DIMENSION 'scoreboard_open' 'open' '' '1' '1' ''

BEGIN apache_local.scoreboard
SET scoreboard_waiting = 5
SET scoreboard_starting = 0
SET scoreboard_reading = 3
SET scoreboard_sending = 1
SET scoreboard_keepalive = 1
SET scoreboard_dns_lookup = 0
SET scoreboard_closing = 0
SET scoreboard_logging = 0
SET scoreboard_finishing = 0
SET scoreboard_idle_cleanup = 0
SET scoreboard_open = 246
END

**Comment by ilyam8** [comment] 2020-07-20 12:57
@prophoto currently go apache collector is disabled by default, you need to explicitly enable it in the `go.d.conf`, see `go.d.conf` for details.

This enable/disable go/python problem will be solved soon.

**Comment by prophoto** [comment] 2020-07-20 15:43
Here is my config, is there something wrong here? Still no data showing.

`
[centos@server7 netdata]$ cat ./go.d.conf
# netdata go.d.plugin configuration
#
# This file is in YaML format.

# Enable/disable the whole go.d.plugin.
enabled: yes

# Enable/disable default value for all modules.
default_run: yes

# Maximum number of used CPUs. Zero means no limit.
max_procs: 0

# Enable/disable specific g.d.plugin module
# If you want to change any value, you need to uncomment out it first.
# IMPORTANT: Do not remove all spaces, just remove # symbol. There should be a space before module name.
modules:
#  activemq: yes
  apache: yes
#  bind: yes
#  cockroachdb: yes
#  consul: yes
#  coredns: yes
#  dnsmasq_dhcp: yes
#  dns_query: yes
#  docker_engine: yes
#  dockerhub: yes
#  example: no
#  fluentd: yes
#  freeradius: yes
#  hdfs: yes
#  httpcheck: yes
#  k8s_kubelet: yes
#  k8s_kubeproxy: yes
#  lighttpd: yes
#  lighttpd2: yes
#  logstash: yes
#  mysql: yes
#  nginx: yes
#  openvpn: yes
#  phpdaemon: yes
#  phpfpm: yes
#  pihole: yes
#  portcheck: yes
#  pulsar: yes
#  rabbitmq: yes
#  scaleio: yes
#  solr: yes
#  springboot2: yes
#  squidlog: yes
#  tengine: yes
#  unbound: yes
#  vernemq: yes
#  vcsa: yes
#  vsphere: yes
#  web_log: no
#  whoisquery: yes
#  wmi: yes
#  x509check: yes
#  zookeeper: yes
`

**Comment by ilyam8** [comment] 2020-07-20 15:50
Did you check logs? (not debug mode)

**Comment by prophoto** [comment] 2020-07-20 15:55
```
[centos@server7 netdata]$ cat /var/log/netdata/error.log | grep go
sh: /usr/libexec/netdata/plugins.d/go.d.plugin: Permission denied
sh: line 0: exec: /usr/libexec/netdata/plugins.d/go.d.plugin: cannot execute: Permission denied
2020-07-20 15:21:38: netdata ERROR : PLUGINSD[go.d] : read failed: end of file (errno 9, Bad file descriptor)
2020-07-20 15:21:38: netdata INFO  : PLUGINSD[go.d] : PARSER ended
2020-07-20 15:21:38: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 24019) disconnected after 0 successful data collections (ENDs).
2020-07-20 15:21:38: netdata ERROR : PLUGINSD[go.d] : child pid 24019 exited with code 126.
2020-07-20 15:21:38: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 24019) exited with error code 126 and haven't collected any data. Disabling it.
2020-07-20 15:21:38: netdata INFO  : PLUGINSD[go.d] : thread with task id 24006 finished
2020-07-20 15:47:14: netdata INFO  : PLUGINSD[go.d] : thread created with task id 25845
2020-07-20 15:47:14: netdata INFO  : PLUGINSD[go.d] : set name of thread 25845 to PLUGINSD[go.d]
2020-07-20 15:47:14: netdata INFO  : PLUGINSD[go.d] : connected to '/usr/libexec/netdata/plugins.d/go.d.plugin' running on pid 25857
sh: /usr/libexec/netdata/plugins.d/go.d.plugin: Permission denied
sh: line 0: exec: /usr/libexec/netdata/plugins.d/go.d.plugin: cannot execute: Permission denied
2020-07-20 15:47:14: netdata ERROR : PLUGINSD[go.d] : read failed: end of file (errno 9, Bad file descriptor)
2020-07-20 15:47:14: netdata INFO  : PLUGINSD[go.d] : PARSER ended
2020-07-20 15:47:14: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 25857) disconnected after 0 successful data collections (ENDs).
2020-07-20 15:47:14: netdata ERROR : PLUGINSD[go.d] : child pid 25857 exited with code 126.
2020-07-20 15:47:14: netdata ERROR : PLUGINSD[go.d] : '/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 25857) exited with error code 126 and haven't collected any data. Disabling it.
2020-07-20 15:47:14: netdata INFO  : PLUGINSD[go.d] : thread with task id 25845 finished
```

**Comment by ilyam8** [comment] 2020-07-20 18:50
```cmd
...
2020-07-20 15:47:14: netdata INFO  : PLUGINSD[go.d] : connected to '/usr/libexec/netdata/plugins.d/go.d.plugin' running on pid 25857
sh: /usr/libexec/netdata/plugins.d/go.d.plugin: Permission denied
sh: line 0: exec: /usr/libexec/netdata/plugins.d/go.d.plugin: cannot execute: Permission denied
...
```

@Ferroin any ideas why it happens?

**Comment by prophoto** [comment] 2020-07-22 19:50
Ideas? Still can't get any logs to show from Apache.
