### ISSUE TITLE
"System RAM used" metric improperly calculates percentage

### ISSUE THREAD

**Issue by davidmehren** [netdata/netdata#3381] opened 2018-02-02 14:38 UTC
Hi!
I have observed the following behaviour:
- Use netdata to monitor an lxc container
- Increase the amount of RAM available to the container
- Increase the RAM usage of processes inside the container to above the original RAM amount.

You now get alerts like "ram in use 116.5%", because the percentage is still calculated based on the RAM value at netdata start time. If I restart netdata, everything goes back to normal.

**Comment by Ferroin** [comment] 2018-02-02 15:52
Just checked, and this happens with virtual machines when you adjust the memory either via a memory balloon driver or virtualized memory hot-plug (and given that it happens in those cases, I'd be willing to be it happens when doing memory hot-plug on physical hardware too).

**Comment by ktsaou** [comment] 2018-02-02 19:36
hm... the code is caching any values. It just reads `/proc/meminfo` every time and calculate the percentage based on the values read.

Could you please post the ram chart when this happens?

**Comment by ktsaou** [comment] 2018-02-02 19:37
edit: the code is **not** caching.

**Comment by ktsaou** [comment] 2018-02-20 19:51
@Ferroin can you reproduce this?

**Comment by Ferroin** [comment] 2018-02-20 20:52
I can look at checking tomorrow, but I make no guarantee that I'll be able to get to it as things have been somewhat chaotic at work recently.

**Comment by Ferroin** [comment] 2018-02-21 12:29
Hmm...  THis is odd, I can't seem to reproduce it with the setup I had used before when testing just using a regular virtual memory balloon driver to adjust things.  I can also check with virtualized memory hotplug, but that will take somewhat longer to set up.

**Comment by davidmehren** [comment] 2018-02-22 11:07
I just looked at the way the `ram_in_use` metric is calculated:
The value of `used_ram_to_ignore` is equal to the size of the ZFS ARC cache. This cache resides in the host RAM and in my case is much bigger than the RAM available to the container.
I get the following values:
`(1,18 - 9,8) * 100 / (1,18 - 9,8 + 0,15 + 0,68) = 109,94`
If I ignore `used_ram_to_ignore` I get: `1,18 * 100 / (1,18 + 0,15 + 0,68) = 58,7` which is the correct value.

Is there a way to detect that netdata is running inside a container and automatically ignore `used_ram_to_ignore`?

**Comment by ktsaou** [comment] 2018-02-22 21:13
> Is there a way to detect that netdata is running inside a container and automatically ignore used_ram_to_ignore?

hm... interesting...

I can see a case that we should not do this. Many people run netdata in a container to monitor the host. In this case the arc should not be excluded.

I see 2 possible solutions:

1. detect that netdata is running in a container and does not monitor the host (I am not sure how to do these)

2. assume that most users want either A (monitor the host), or B (monitor the container) and provide a sane default for those and instructions for the rest to configure it the right way.

Since, you are the only one who have reported this, I assume your case (netdata in a container, monitoring the container, with zfs on the host) is probably a minority, so if we don't find a way to automatically detect it, I will add a comment on that alarm definition with instructions on how to be customized in this case.

Of course I am open to other ideas...

**Comment by paulkatsoulakis** [comment] 2019-03-04 14:42
Hello there,
 With a little digging i found a way to detect whether we are running in a containerized environment that seems kind of stable.

`grep -qa container=lxc /proc/1/environ` 

I don't have a docker setup at hand right now, but i would assume it has a similar string defined.
Alternatively for docker i have seen also some people suggesting to check for the existence of the file `/.dockerenv` that is created within the docker container.

The only caveat i can see on the above approaches is what will happen if suddenly this environment setup changes layout for any reason. I guess we could just scan for the possible alternatives and if none are found we could just report a comprehensive message to help us notice it quickly

**Comment by tnyeanderson** [comment] 2019-08-08 21:07
My two cents:

I think there should be an option in `stream.conf` for each client to set whether they are in a container. Something like `LXC = yes`.

Then, on the host, we can detect that option to return the results that the user expects. I have a feeling there may be more bugs that crop up for similar reasons, so this can be a way to take care of all of them in one place.

**Comment by tnyeanderson** [comment] 2019-08-18 14:20
The CPU load metric seems to have the same issue (it is metering the host instead of the container). Thinking about it, `LXC` should be set in `[global]` (not `stream.conf`), then we can determine from where we should pull the metrics.

**Comment by thegcat** [comment] 2020-05-10 19:32
Is there progress or planning in this issue? We are still seeing erroneous values here and get warnings about memory being used at 20000+% :-)

**Comment by thiagoftsm** [comment] 2020-05-10 21:01
Hi @thegcat ,

We already have a PR ( https://github.com/netdata/netdata/pull/8913 ) ready to be merged that will fix this, but we are in code freeze for the new release. In the next few days the solution will be merged.

We apologize the delay!

Best regards!

**Comment by vlvkobal** [comment] 2020-05-14 08:13
#8913 is merged. Can we close the issue?

**Comment by amoss** [comment] 2020-05-14 09:00
As long as it fixes the problem.

**Comment by vlvkobal** [comment] 2020-05-14 09:30
@davidmehren, @thegcat, please check if the issue was resolved.

**Comment by davidmehren** [comment] 2020-05-15 20:46
I just checked using `v1.22.1-33-nightly` and get `-126%` on the `ram in use` alert. So there probably won't be any alerts because of that but the value is still wrong ;)

I think @tnyeanderson is right and netdata needs some kind of container detection or setting, which switches the memory and CPU load metrics to use the correct values.

**Comment by amoss** [comment] 2020-08-20 14:54
The calculation of the `ram in use` alert was wrong as it did not include the size of buffers when calculating the total. I've changed this in a PR this morning for another issue (https://github.com/netdata/netdata/pull/9793). This should fix the negative value that you are seeing, but as I commented on the other issue (https://github.com/netdata/netdata/issues/9059) I think we should just remove this alarm as it is not useful - and the available ram alarm is the one that is useful in this case.

**Comment by amoss** [comment] 2020-08-20 14:55
If the change in the PR still produces negative values in your use case please post the output of `/proc/memstat` so that I can the numbers and work out why we are calculating the wrong total.

**Comment by ilyam8** [comment] 2021-08-05 12:10
@davidmehren hey.

The title says "System Ram used" and it looks like you were discussing [ram_in_use](https://github.com/netdata/netdata/blob/a9769d8e413e73e3322aa59efcfaa48f023c5436/health/health.d/ram.conf#L16-L31) alarm.

But according to the OP, I think you were referring to [cgroup_ram_in_use](https://github.com/netdata/netdata/blob/a9769d8e413e73e3322aa59efcfaa48f023c5436/health/health.d/cgroups.conf#L20-L34) alarm. Am I right?

**Comment by davidmehren** [comment] 2021-08-09 09:33
I can't look it up anymore, as we stopped running the `proc` plugin inside containers, but I'm pretty sure I was talking about the `ram_in_use` alarm. We ran netdata *inside* the container, so there shouldn't have been any cgroups to monitor.

**Comment by davidmehren** [comment] 2021-08-09 09:58
I just enabled a default Netdata config inside one container. The container has 2 GB of RAM, but Netdata  still includes the ARC of the host in its calculations and arrives at completely ridiculous values for RAM usage:
![image](https://user-images.githubusercontent.com/5023650/128689458-541e20e8-0297-4a4d-b9c6-a629baa0ca1e.png)

**Comment by cpipilas** [comment] 2022-06-29 15:03
We did several fixes, working as expected now.

**Closed by cpipilas** 2022-06-29 15:03 UTC
Labels: bug, help wanted, priority/low, area/collectors, area/daemon
