### ISSUE TITLE
go.d module doesn't load custom settings

### ISSUE THREAD

**Issue by iredmail** [netdata/netdata#7394] opened 2019-12-02 11:08 UTC
##### Bug report summary

go.d doesn't load custom settings

##### OS / Environment

CentOS 7.

##### Netdata version (ouput of `netdata -V`)

```
# /opt/netdata/usr/sbin/netdata -V
netdata v1.19.0
```

##### Component Name

phpfpm

##### Steps To Reproduce

- Install nginx + php-fpm on a CentOS 7 box, configure nginx to server `https://localhost/status` page.
- Add custom `go.d/phpfpm.conf` with content below (it uses `https` instead of `http`):

```
jobs:
  - name: local
    url: https://localhost/status?full&json
    tls_skip_verify: yes
```

##### Expected behavior

Netdata should load this custom url with `https`, not the default one with `http`.

**Comment by ilyam8** [comment] 2019-12-02 12:37
Hi 
> http://127.0.0.1/status?full&json

is default URL if URL not set, it seems there are some problems with permissions and module is not able to read you config file. As a result it uses default parameters. Could you ensure that config file is readable by `netdata` user?

**Comment by iredmail** [comment] 2019-12-03 01:43
False alarm, sorry about the noise, and thanks for helping. :)

**Comment by iredmail** [comment] 2019-12-08 10:44
I think this is a permission issue due to the (Go) module `web_log` is running as `netdata` user, but Nginx log file `/var/log/nginx/access.log` is not readable by `netdata`.

I tried it on Debian 10 also, Nginx log file `access.log` has owner/group/permission like below:

```
# ls -l /var/log/nginx/access.log
-rw-r----- 1 www-data adm    87 Dec  8 02:43 access.log
```

In this case the `web_log` module can not read it, hence no chart in netdata dashboard. After run `chmod o+r /var/log/nginx/access.log` and restart netdata service, the chart is working.

Although i can set the permission manually, but it's set back to 0640 after logrotate. So i think this is not a good solution.

**Comment by ilyam8** [comment] 2019-12-08 10:50
Yes, netdata should be added to the `adm` group.

I see it shuld be done during install/update

https://github.com/netdata/netdata/blob/8260af09934d9b0dc0b5944b18fe0dd0ac60d831/netdata-installer.sh#L542-L555

**Comment by ilyam8** [comment] 2019-12-08 10:50
How did you install `netdata`?

**Comment by iredmail** [comment] 2019-12-08 10:55
Installed with the binary file (.run.gz) ```./netdata-v1.19.0.run.gz --accept```.
I can see netdata user is assigned to `adm` group, but it didn't work.
I will do some more testing to verify this issue.

Thanks for the fast reply. @ilyam8

**Comment by ilyam8** [comment] 2019-12-08 11:13
I see the file is readable by `adm` group, it should be readable by `netdata` user if the user is a member of the `adm` group (`id netdata`).

The issue is 

> go.d module doesn't load custom settings

We dont have such problem, so i m closing the issue.

We can continue to discuss [this problem](https://github.com/netdata/netdata/issues/7394#issuecomment-562933463) here, no problem.

If you think there is a bug ro something please open a new issue.

**Closed by ilyam8** 2019-12-08 11:13 UTC
Labels: area/external, question
