### ISSUE TITLE
monitoring libvirt through cgroup causes removed VMs to be shown

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#7650] opened 2020-01-01 13:53 UTC
##### Bug report summary
On an opennebula host monitored by netdata, we have some deleted VMs which are still shown on the monitoring webpage:
![image](https://user-images.githubusercontent.com/7656049/71642042-a7dc6700-2cba-11ea-9313-dc64873c1013.png)
output of `systemd-cgls`:
```
│ ├─libvirt-bin.service
│ │ ├─ 1700 /usr/bin/qemu-system-x86_64 -name one-970 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 8192 -realtime mlock=off -smp 8,sock
│ │ ├─ 5003 /usr/bin/qemu-system-x86_64 -name one-1090 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 2048 -realtime mlock=off -smp 2,soc
│ │ ├─ 9394 /usr/bin/qemu-system-x86_64 -name one-929 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 8192 -realtime mlock=off -smp 8,sock
│ │ ├─10517 /usr/bin/qemu-system-x86_64 -name one-633 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 16384 -realtime mlock=off -smp 8,soc
│ │ ├─10675 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
│ │ ├─10676 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
│ │ ├─11323 /usr/bin/qemu-system-x86_64 -name one-1079 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,soc
│ │ ├─18068 /usr/bin/qemu-system-x86_64 -name one-1069 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,soc
│ │ ├─24994 /usr/bin/qemu-system-x86_64 -name one-510 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,sock
│ │ ├─26243 /usr/bin/qemu-system-x86_64 -name one-515 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,sock
│ │ ├─26666 /usr/bin/qemu-system-x86_64 -name one-542 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 8192 -realtime mlock=off -smp 8,sock
│ │ ├─29415 /usr/bin/qemu-system-x86_64 -name one-935 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,sock
│ │ ├─29523 /usr/bin/qemu-system-x86_64 -name one-634 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 16384 -realtime mlock=off -smp 8,soc
│ │ ├─31441 /usr/bin/qemu-system-x86_64 -name one-1000 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,soc
│ │ ├─32261 /usr/bin/qemu-system-x86_64 -name one-999 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,sock
│ │ ├─35505 /usr/bin/qemu-system-x86_64 -name one-983 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,sock
│ │ ├─41493 /usr/bin/qemu-system-x86_64 -name one-631 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,sock
│ │ ├─41904 /usr/bin/qemu-system-x86_64 -name one-632 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,sock
│ │ ├─46127 /usr/bin/qemu-system-x86_64 -name one-1098 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,soc
│ │ ├─59469 /usr/bin/qemu-system-x86_64 -name one-1041 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 8192 -realtime mlock=off -smp 8,soc
│ │ ├─61815 /usr/bin/qemu-system-x86_64 -name one-1014 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,soc
│ │ ├─62371 /usr/sbin/libvirtd
│ │ ├─67222 /usr/bin/qemu-system-x86_64 -name one-979 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,sock
│ │ ├─69803 /usr/bin/qemu-system-x86_64 -name one-1029 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 8192 -realtime mlock=off -smp 4,soc
│ │ ├─81978 /usr/bin/qemu-system-x86_64 -name one-904 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 4096 -realtime mlock=off -smp 4,sock
│ │ └─88221 /usr/bin/qemu-system-x86_64 -name one-1055 -S -machine pc-i440fx-xenial,accel=kvm,usb=off -cpu host -m 2048 -realtime mlock=off -smp 2,soc
```
but the output of `/sys/fs/cgroup/cpuacct/machine/` is:
```
cgroup.clone_children  cpuacct.usage          one-1055.libvirt-qemu  one-478.libvirt-qemu  one-631.libvirt-qemu  one-970.libvirt-qemu
cgroup.procs           cpuacct.usage_percpu   one-1069.libvirt-qemu  one-479.libvirt-qemu  one-632.libvirt-qemu  one-979.libvirt-qemu
cpu.cfs_period_us      notify_on_release      one-1079.libvirt-qemu  one-480.libvirt-qemu  one-633.libvirt-qemu  one-983.libvirt-qemu
cpu.cfs_quota_us       one-1000.libvirt-qemu  one-1090.libvirt-qemu  one-482.libvirt-qemu  one-634.libvirt-qemu  one-999.libvirt-qemu
cpu.shares             one-1014.libvirt-qemu  one-1098.libvirt-qemu  one-510.libvirt-qemu  one-904.libvirt-qemu  tasks
cpu.stat               one-1029.libvirt-qemu  one-476.libvirt-qemu   one-515.libvirt-qemu  one-929.libvirt-qemu
cpuacct.stat           one-1041.libvirt-qemu  one-477.libvirt-qemu   one-542.libvirt-qemu  one-935.libvirt-qemu
```
output of `virsh list`:
```
 Id    Name                           State
----------------------------------------------------
 1     one-510                        running
 3     one-515                        running
 4     one-542                        running
 11    one-631                        running
 12    one-632                        running
 46    one-935                        running
 47    one-904                        running
 61    one-979                        running
 65    one-983                        running
 68    one-1000                       running
 69    one-999                        running
 70    one-970                        running
 71    one-929                        running
 72    one-1014                       running
 83    one-1041                       running
 84    one-1055                       running
 89    one-1079                       running
 96    one-633                        running
 97    one-634                        running
 101   one-1069                       running
 104   one-1029                       running
 105   one-1090                       running
 107   one-1098                       running
```
As you can see there is no VM with id `478` or `479` but we see them on the monitoring dashboard.
##### OS / Environment
Ubuntu 16 
##### Netdata version (ouput of `netdata -V`)
1.19
##### Expected behavior
Only see existing VMs on the host.

**Comment by prologic** [comment] 2020-01-01 20:09
Hi @yasharne Which specific version of Ubuntu is this host running on? Can you also provide the output of `uname -a`? Thanks!

**Comment by yasharne** [comment] 2020-01-02 05:33
Hi @prologic here is the output of `uname -a`:
```
Linux one-17.compute.afra.snapp.infra 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```
and host version is `ubuntu 16.04`

**Comment by yasharne** [comment] 2020-01-02 05:37
Hi @prologic here is the output of `uname -a`:
```
Linux one-17.x.y.z 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
and host version is `ubuntu 16.04`

**Comment by stelfrag** [comment] 2020-01-02 08:54
Hi @yasharne I will try to replicate on ubuntu 16 since in later version I could not replicate by
doing the following

- Start a few VMs with QEMU
- Start Netdata
  - VsM are monitored
  - Stop one VM 
    - Refresh the Netdata page and that VM disappears

However you mentioned deleted VMs. So I will just attempt to replay the above steps and 
delete a VM to try and reproduce

I am assuming you did refresh the web browser page and that Netdata agent was not restarted (since restarting should fix it)

**Comment by ilyam8** [comment] 2020-01-02 08:59
> but the output of /sys/fs/cgroup/cpuacct/machine/ is:

i think that is the problem.

I see the module looking for new cgroups every `find_every`

https://github.com/netdata/netdata/blob/ecc05bbdb68603e0c46d9d413a23cd7a5c669364/collectors/cgroups.plugin/sys_fs_cgroup.c#L3683-L3688



 - mark all cgroups as unavailable
 - find all cgroups
 - remove unavailable

https://github.com/netdata/netdata/blob/ecc05bbdb68603e0c46d9d413a23cd7a5c669364/collectors/cgroups.plugin/sys_fs_cgroup.c#L1554-L1604


Since you have some data for old cgroups in the `/sys/fs/cgroup/cpuacct/machine/` the module marks them as available and doesnt delete.

Probably i am missing something, was a quick look in the code.

**Comment by stelfrag** [comment] 2020-01-02 09:23
@ilyam8  you are correct. I verified that left over data (directory in /sys/fs/cgroup/cpuacct/machine/) messes things up. 

Stopping or deleting a VM should have removed the entry from /sys/fs/cgroup/cpuacct/machine/

**Comment by ilyam8** [comment] 2020-10-28 17:36
> we have some deleted VMs which are still shown on the monitoring webpage

What about `virsh list --all`?

To be honest not really a `cgroups` plugin bug. It monitors cgroups and if some cgroups are not deleted then we keep showing them.

---

I see @stelfrag did some tests

- Start a few VMs with QEMU
- Start Netdata
- VsM are monitored
- Stop one VM
- Refresh the Netdata page and that VM disappears

Looks strange:
- _stop vm => cgroup is removed_ 
- _delete vm => cgroup is not removed_

@yasharne do you have same behavior?

@stelfrag 

> However you mentioned deleted VMs. So I will just attempt to replay the above steps and
delete a VM to try and reproduce

Did you test VM deletion?

**Comment by stelfrag** [comment] 2020-10-29 11:08
> Did you test VM deletion?

@ilyam8 probably not (forgotten); else I would have put a comment here

**Comment by ilyam8** [comment] 2021-08-23 14:32
Closing this issue, because it is Ubuntu 16 specific problem (deleting a VM doesn't remove the corresponding cgroup).

**Closed by ilyam8** 2021-08-23 14:32 UTC
Labels: bug, priority/low, area/collectors, data-collection-mteam
