### ISSUE TITLE
Issue when upgrading Netdata to 1.24.0 on offline system

### ISSUE THREAD

**Issue by dids50x** [netdata/netdata#9791] opened 2020-08-20 07:35 UTC
##### Bug report summary

When trying to upgrade Netdata (1.23.0 to 1.24.0) on an offline system, I got the following error :

```
# bash /tmp/kickstart-static64.sh --disable-telemetry --stable-channel --non-interactive --no-updates --local-files /tmp/netdata-v1.24.0.gz.run /tmp/sha256sums.txt
 --- Found existing install of Netdata under: /opt/netdata ---
 --- Attempting to update existing install instead of creating a new one ---
[/root]# /opt/netdata/usr/libexec/netdata/netdata-updater.sh --not-running-from-cron
curl: (7) Failed connect to api.github.com:443; Connexion refusée
jeu. août 20 09:19:00 CEST 2020 : ERROR:  FAILED TO UPDATE NETDATA : Cannot download https://api.github.com/repos/netdata/netdata/releases/latest
Entering /tmp/netdata-updater-MJIpYD
curl: (7) Failed connect to github.com:443; Connexion refusée
jeu. août 20 09:19:00 CEST 2020 : ERROR:  FAILED TO UPDATE NETDATA : Cannot download https://github.com/netdata/netdata/releases/download//sha256sums.txt
 FAILED

 ABORTED  Failed to update existing Netdata install

#
```

The check for an already existing Netdata installation was not present in previous kickstart file.
I haven't found how to work arround this.

I think it's not normal because I specified the local files to use.
Or I don't do it the right way?

Could you provide help or fix this in kickstart file ?

Thank you.

Regards,

##### OS / Environment

```
/etc/os-release:NAME="Red Hat Enterprise Linux Server"
/etc/os-release:VERSION="7.6 (Maipo)"
/etc/os-release:ID="rhel"
/etc/os-release:ID_LIKE="fedora"
/etc/os-release:VARIANT="Server"
/etc/os-release:VARIANT_ID="server"
/etc/os-release:VERSION_ID="7.6"
/etc/os-release:PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
/etc/os-release:HOME_URL="https://www.redhat.com/"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
/etc/redhat-release:Red Hat Enterprise Linux Server release 7.6 (Maipo)
/etc/system-release:Red Hat Enterprise Linux Server release 7.6 (Maipo)

```

##### Netdata version

```
netdata v1.24.0
``` 

##### Component Name

```
kickstart-static64.sh
```

##### Steps To Reproduce

1. download files for version 1.23.0 on an online system and copy them on an offline system
2. launch the installation on the offline system: bash /tmp/kickstart-static64.sh --disable-telemetry --stable-channel --non-interactive --no-updates --local-files /tmp/netdata-v1.23.0.gz.run /tmp/sha256sums.txt
3. reproduce the steps 1 and 2 for the version 1.24.0

##### Expected behavior

Netdata successfully upgraded to version 1.24.0.

**Comment by amoss** [comment] 2020-08-20 08:05
Looking at the kickstart and updater scripts it looks as if we do not currently support updating offline installations. One of the SRE team can give a more definite answer later. A temporary work-around would be to uninstall the old version before installing 1.24.0. @prologic It looks as if we should add support for offline installs to the updater?

**Comment by dids50x** [comment] 2020-08-20 11:53
@amoss Thank you for your reply.
However, how can I do if I want to upgrade Netdata master, which also is an offline system, without losing metrics history?

**Comment by amoss** [comment] 2020-08-20 12:53
That is more difficult. There are two options, one safer and one more dangerous. The safer option would be to wait until we add support for updating an offline installation - this is what I would recommend. The more dangerous option would be to manually insert the dbengine data-files into a new installation. I would recommend against this as we changed the dbengine between 1.23 and 1.24 and I can't guarantee this would work.

**Comment by dids50x** [comment] 2020-08-20 14:58
@amoss Do you think that Netdata's development team will be able to fix this in a few weeks?

**Comment by amoss** [comment] 2020-08-20 14:59
@prologic is in a different timezone but he will be able to answer later on when he sees these messages.

**Comment by Ferroin** [comment] 2020-08-20 15:13
Yes, we should be able to fix this relatively quickly (I plan to work on this either today or tomorrow, and the fix should be ready by some time next week at the latest). Once the fix is in, you should be able to pull the `kickstart-static64.sh` script directly from the Netdata repo and use that to do the upgrade.

For the record, this is expected but unintended behavior resulting from changes to how we handle running the installer on a system with an existing install (namely, I forgot to account for offline installs when making those changes). My sincerest apologies for the inconvenience this has caused.

---

There is a third option for handling the upgrade if you don't want to wait for the fix. You can actually run the downloaded archive directly like this:

```
/tmp/netdata-v1.24.0.gz.run --accept -- --disable-telemetry --stable-channel
```

The options listed above are what the `kickstart-static64.sh` script would end up passing to the archive script given what options you had listed in your original post.

**Closed** 2020-08-25 05:11 UTC
Labels: area/packaging, bug
