### ISSUE TITLE
dash.html

### ISSUE THREAD

**Issue by eglyn** [netdata/netdata#6913] opened 2019-09-23 08:43 UTC
Hello, 

I am interested by the multi-Host Dashboard (dash.html), but I can not display multiple dashboards on the same page ...
I follow the documentation witch says: 

> Change the following line in dash.html to reflect your URLs. The second URL is used if you access your netdata dashboard from a reverse proxy. The reverse proxy URL is optional, if it is not set then both will use the netdata host URL.

> var dash = new Dash('http://localhost:19999');

and add the dashboard.js to the head section and I see on my dash.html page my netdata server, but how add the others machines ?

documentation says: 
>dash-example.html is an all-in-one page that automatically fetches graphs from all your hosts. Just add your graphs and charts (or use the defaults) one time using the dash-* syntax and it will be automatically replicated for all of your hosts; showing alarms and graphs for all your hosts on one page!

what "using the dash-* syntax" means ?

thx in advance :)

**Comment by cakrit** [comment] 2019-09-23 09:02
@tnyeanderson wanna help with this and perhaps improve the docs and comments in the file?

**Comment by tnyeanderson** [comment] 2019-09-24 14:49
> I see on my dash.html page my netdata server, but how add the others machines ?

I may need to know a little bit more about your setup. `dash.html` works like this: If you have multiple "slave" instances that stream to a master netdata host, then once you set the URL to your master as described, it will fetch the list of the streamed "slave" hosts from the master. Then for *each* of these, it will generate the graphs and charts indicated by the `dash-*` syntax.

Are you hosting `dash.html` on your master? Or on another system?

> and add the dashboard.js to the head section

`dash.html` adds this path automatically when your master URL is set correctly, so this may be part of the problem. Don't add it twice! All that is required of you to get started is change the URL as shown, dash takes care of the rest :)

> what "using the dash-* syntax" means ?

If you look in the `dash.html` file, you will see elements with class names like `dash-graph` and `dash-chart`. These are what is replicated for each streamed host. The file comes preloaded with graphs/charts that are commonly used, but they can be changed to present the graphs that you need. More information regarding the `dash-*` syntax is available [here](https://github.com/netdata/netdata/tree/master/web/gui/custom), just beneath the part about changing the URL (starts with "If you want to change the graphs or styling to fit your needs"). It isn't very clear that this is talking about the dash syntax, so I will work on improving that documentation. Thank you for pointing that out!

If you open up the console, do you see any errors in the log? The streamed hosts are discovered via the master host API in the "init" function, and are parsed in the "find_new_hosts" function. You can add some `console.log`s in these areas to see where the problem is, and make sure those API calls are working properly. Please don't hesitate to report back with what you find. I want this to be easy and seamless; if it is confusing or difficult, then I want to fix it!

Thank you for your interest :)

**Comment by eglyn** [comment] 2019-09-25 06:32
Thanks for your answer, i think i see the issue: i have not configured any streaming ^^,
I have only 3 VM to test Netdata, and Netdata is installed on this 3 VM.
I thought that Dash.html was retrieving the information from the 3 VMs separately.

So, if i understand correctly, i need to choose a master, and stream netdata from the 2 slaves to the master.
And the dash.html check only the master witch have slaves informations.
I am going to check the documentation of the streaming configuration.

Thanks !

**Comment by cakrit** [comment] 2019-09-25 09:53
Yes @egly, that's correct. Closing, please comment if you need more help. 
Thanks @tnyeanderson!

**Closed by cakrit** 2019-09-25 09:53 UTC
Labels: no changelog, question

**Comment by eglyn** [comment] 2019-09-25 10:07
It's ok, i have done the streaming configuration, and everything is working :)

Thank you :)
