### ISSUE TITLE
Not sending Clear Notification when "${DESTINATION}|CRITICAL" enable

### ISSUE THREAD

**Issue by masircana** [netdata/netdata#8739] opened 2020-04-16 17:39 UTC
I have diferent channels for my alarms. In my email I receive warning, critical and clear notification, in my telegram only critical and clear. I update netdata master to the version v1.21.1-20-nightly and since that I dont receive any more clear notifications to Telegram.  
I have one master and 15 streaming to that server, Master in a VM. 
```
Linux do-monitoring-node-01-prod 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="9"
/etc/os-release:VERSION="9 (stretch)"
/etc/os-release:VERSION_CODENAME=stretch
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```
This is my Telegram configuration on health_alarm_notify.conf

```
SEND_TELEGRAM="YES"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}"
DEFAULT_RECIPIENT_TELEGRAM="${TELEGRAM_CHAT_ID}|CRITICAL"
```

When I test my notifications with the plugin this is the output:
```
# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2020-04-16 17:28:10: alarm-notify.sh: INFO: sent email notification for: do-monitoring-node-01-prod test.chart.test_alarm is WARNING to '${DEFAULT_RECIPIENT_EMAIL}'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2020-04-16 17:28:11: alarm-notify.sh: INFO: sent telegram notification for: do-monitoring-node-01-prod test.chart.test_alarm is CRITICAL to '${TELEGRAM_CHAT_ID}'
2020-04-16 17:28:11: alarm-notify.sh: INFO: sent email notification for: do-monitoring-node-01-prod test.chart.test_alarm is CRITICAL to '${DEFAULT_RECIPIENT_EMAIL}'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2020-04-16 17:28:11: alarm-notify.sh: INFO: sent email notification for: do-monitoring-node-01-prod test.chart.test_alarm is CLEAR to '${DEFAULT_RECIPIENT_EMAIL}'
```
And I receive the Critical notification in my Telegram Chat. If I configure the Telegram default recipient like this:

`DEFAULT_RECIPIENT_TELEGRAM="${TELEGRAM_CHAT_ID}"`

And test again the alarm-notify.sh this is the output:

```
# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2020-04-16 17:31:58: alarm-notify.sh: INFO: sent telegram notification for: do-monitoring-node-01-prod test.chart.test_alarm is WARNING to '${TELEGRAM_CHAT_ID}'
2020-04-16 17:31:58: alarm-notify.sh: INFO: sent email notification for: do-monitoring-node-01-prod test.chart.test_alarm is WARNING to ${DEFAULT_RECIPIENT_EMAIL}'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2020-04-16 17:31:59: alarm-notify.sh: INFO: sent telegram notification for: do-monitoring-node-01-prod test.chart.test_alarm is CRITICAL to '${TELEGRAM_CHAT_ID}'
2020-04-16 17:31:59: alarm-notify.sh: INFO: sent email notification for: do-monitoring-node-01-prod test.chart.test_alarm is CRITICAL to '${DEFAULT_RECIPIENT_EMAIL}'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2020-04-16 17:31:59: alarm-notify.sh: INFO: sent telegram notification for: do-monitoring-node-01-prod test.chart.test_alarm is CLEAR to '${TELEGRAM_CHAT_ID}'
2020-04-16 17:31:59: alarm-notify.sh: INFO: sent email notification for: do-monitoring-node-01-prod test.chart.test_alarm is CLEAR to '${DEFAULT_RECIPIENT_EMAIL}'
# OK

```
It's like if I configure just the critical notifications the Clear it's not going to send, but in later versions that work, I have other master with the same configuration on health_alarm_notify.conf with the version v1.15.0-135-nightly and when I test the alarm this is the output:

```
# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2020-04-16 17:34:27: alarm-notify.sh: INFO: sent email notification for: vc-monitoring-node-01-prod test.chart.test_alarm is WARNING to '${DEFAULT_RECIPIENT_EMAIL}'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2020-04-16 17:34:28: alarm-notify.sh: INFO: sent telegram notification for: vc-monitoring-node-01-prod test.chart.test_alarm is CRITICAL to '${TELEGRAM_CHAT_ID}'
2020-04-16 17:34:28: alarm-notify.sh: INFO: sent email notification for: vc-monitoring-node-01-prod test.chart.test_alarm is CRITICAL to '${DEFAULT_RECIPIENT_EMAIL}'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2020-04-16 17:34:28: alarm-notify.sh: INFO: sent telegram notification for: vc-monitoring-node-01-prod test.chart.test_alarm is CLEAR to '${TELEGRAM_CHAT_ID}'
2020-04-16 17:34:28: alarm-notify.sh: INFO: sent email notification for: vc-monitoring-node-01-prod test.chart.test_alarm is CLEAR to '${DEFAULT_RECIPIENT_EMAIL}'
# OK
```

I dont know what happen on the version or if I need to configure something else now. 

Thank you

**Comment by thiagoftsm** [comment] 2020-04-19 23:36
Hi @masircana ,

Firstly I apologize the delay, but I was busy with other work these day, fortunately  I could find a time to work properly with the problem you are reporting.

When Netdata released the version `1.20.0` we fixed a problem reported per an user. According #7756, after to set `|critical` in the default recipient, the user continued receiving `WARN`. We created the PR #7769 to fix this problem, because inside the file `health_alarm_notify.conf` we inform that when `|critical` is defined, we should not send any other notification different of `|critical`.

Considering that you report differs a little bit of the previous request, I think the unique possible solution that can satisfy both cases, it is to bring more two notification options ( `|warn` and `|clean`) for the alarm notification.

I am assigning this issue to me and other developers for we bring this feature.

Best regards!

**Comment by masircana** [comment] 2020-04-20 00:14
Thank for the reply. So I could combine the options. If I want to receive |critical and |clear, may be in two different lines. That Wil be possible?

**Comment by thiagoftsm** [comment] 2020-04-20 01:37
Right now it is not possible, but I already communicated the product team for we plan bring this solution in a near future. We removed this feature to match our documentation, and now with your request we will work to extend the feature.

**Comment by cakrit** [comment] 2020-08-10 09:12
I believe that this was broken by #7769 caused by a probably erroneous bug report in #7756
I will verify and do a PR to fix it, if that's the case.

**Comment by cakrit** [comment] 2020-08-10 10:39
I verified it, #9698 has the fix.

**Closed** 2020-08-14 06:11 UTC
Labels: area/health, bug
