### ISSUE TITLE
How to create a text chart with dynamic label.

### ISSUE THREAD

**Issue by Tommuh** [netdata/netdata#7522] opened 2019-12-13 11:35 UTC
Hello,

The title says it all, is this possible? 

I created my own dashboard (screenshot below to make this clearer) with a few things that are important for us, like PHP FPM requests. This is in milliseconds at default, but when it gets busier during the day it sometimes rises to seconds.

The text chart displays the milliseconds as thousands which isn't really nice, I can make my own conversion in Javascript but maybe there is something build in?

This is the code I use to make the text chart.
`<div data-netdata="phpfpm_www.request_duration"
                                         data-chart-library="textonly"
                                         data-before="0" 
                                         data-after="-540" 
                                         data-textonly-suffix=" MS"                                          
                                         data-points="540">`

![image](https://user-images.githubusercontent.com/2089879/70797213-579d7380-1da4-11ea-9dbe-b46b1be42e0b.png)

**Comment by jacekkolasa** [comment] 2019-12-13 18:54
Hi @Tommuh , we don't have this kind of functionality but this is a very nice idea and it would be definitely good to have this. We have some auto-conversion from "milliseconds", but it is available only in charts like "dygraph" now.

**Comment by Tommuh** [comment] 2019-12-16 09:20
That is great, I will keep an eye on this feature.

**Comment by ilyam8** [comment] 2020-01-22 10:46
@jacekkolasa check the issue, if we need it as `feature request` please reopen

**Comment by Tommuh** [comment] 2020-01-22 13:10
Thank you!

**Comment by ilyam8** [comment] 2021-08-02 13:44
Closing as duplicate of #5246.

**Closed by ilyam8** 2021-08-02 13:44 UTC
Labels: area/web, feature request
