### ISSUE TITLE
Netdata standalone plugins are linking against things they don't need to link against.

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#6723] opened 2019-08-24 08:29 UTC
##### Bug report summary
While playing around with debian packaging, in the process of splitting CUPS plugin to a separate package, i bumped into the following warnings

Apparently we need to rework our build process for the plugins.
It does require some thinking on whether we should attend this and how, so i am adding this issue for investigation 

```
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/netdata-plugin-cups/usr/libexec/netdata/plugins.d/cups.plugin was not linked against libJudy.so.1 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/netdata-plugin-cups/usr/libexec/netdata/plugins.d/cups.plugin was not linked against libjson-c.so.3 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/netdata-plugin-cups/usr/libexec/netdata/plugins.d/cups.plugin was not linked against libuuid.so.1 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/netdata-plugin-cups/usr/libexec/netdata/plugins.d/cups.plugin was not linked against liblz4.so.1 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/netdata-plugin-cups/usr/libexec/netdata/plugins.d/cups.plugin was not linked against libm.so.6 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/netdata-plugin-cups/usr/libexec/netdata/plugins.d/cups.plugin was not linked against libz.so.1 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/netdata-plugin-cups/usr/libexec/netdata/plugins.d/cups.plugin was not linked against libssl.so.1.1 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/netdata-plugin-cups/usr/libexec/netdata/plugins.d/cups.plugin was not linked against libcrypto.so.1.1 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if debian/netdata-plugin-cups/usr/libexec/netdata/plugins.d/cups.plugin was not linked against libuv.so.1 (it uses none of the library's symbols)
```
##### OS / Environment
Any

##### Netdata version (ouput of `netdata -V`)
Latest

##### Component Name
netdata

##### Steps To Reproduce
Run the debian packaging flow

##### Expected behavior
No warnings, no useless linking

**Comment by Ferroin** [comment] 2020-03-05 12:37
Removing the packaging label as this is a build system problem, not a packaging problem.

**Comment by prologic** [comment] 2020-06-24 02:01
Assigning to you @amoss as we very rarely mess around wth the C build system. I know this issue is old so I'm not sure how relevant it is. Feel free to close it if it is not.

**Comment by amoss** [comment] 2020-06-24 09:35
Thanks @prologic :)

**Comment by ilyam8** [comment] 2021-02-01 09:06
@Ferroin @stelfrag is this issue stil relevant or we can close it?

**Comment by Ferroin** [comment] 2021-02-01 13:08
I _think_ it’s still an issue, but I am not certain.

**Comment by Ferroin** [comment] 2021-02-01 14:57
Just confirmed, this is indeed still an issue.

Confirmed by doing a regular install and then running `ldd` on the plugin executables and comparing to the main Netdata executable. The list of linked libraries is identical, which means we have a bunch of stuff we don’t need linked to the various binaries, and possibly have a few things linked to the main netdata binary in some build configurations that we do not need there.

**Comment by Ferroin** [comment] 2021-02-01 14:59
Two other things to note:

* This is an issue with the build system, not our packaging. I’ve checked both our regular install, as well as our binary packages and Docker container, and all of them exhibit this.
* I know it’s _possible_ to fix this, but I do not know _how_ to do it.

**Comment by MrZammler** [comment] 2021-02-02 07:32
Hi! I'm might be off with this, but here it goes:

In Makefile.am, cups.plugin is build with both $(NETDATA_COMMON_LIBS), and $(OPTIONAL_CUPS_LIBS) (which is I think just -lcups).

```
if ENABLE_PLUGIN_CUPS
    plugins_PROGRAMS += cups.plugin
    cups_plugin_SOURCES = $(CUPS_PLUGIN_FILES)
    cups_plugin_LDADD = \
        $(NETDATA_COMMON_LIBS) \
        $(OPTIONAL_CUPS_LIBS) \
        $(NULL)
endif
```

Removing  $(NETDATA_COMMON_LIBS) will result in a cups.plugin linked against fewer libraries:

```
ldd cups.plugin 
	linux-vdso.so.1 (0x00007fffd0129000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f0d4f89f000)
	libcups.so.2 => /usr/lib64/libcups.so.2 (0x00007f0d4f804000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0d4f7e4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0d4f624000)
	libgnutls.so.30 => /usr/lib64/libgnutls.so.30 (0x00007f0d4f46e000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f0d4f454000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f0d4f318000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0d4f8d6000)
	libidn2.so.0 => /usr/lib64/libidn2.so.0 (0x00007f0d4f2f7000)
	libunistring.so.2 => /usr/lib64/libunistring.so.2 (0x00007f0d4f176000)
	libtasn1.so.6 => /usr/lib64/libtasn1.so.6 (0x00007f0d4f160000)
	libnettle.so.8 => /usr/lib64/libnettle.so.8 (0x00007f0d4f123000)
	libhogweed.so.6 => /usr/lib64/libhogweed.so.6 (0x00007f0d4f0da000)
	libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007f0d4f05c000)
```
(It doesn't get rid of e.g. libm.so.6 and some others, but those might be descending from libcups.so.2)

Comparing with when $(NETDATA_COMMON_LIBS) is added:

```
ldd cups.plugin 
	linux-vdso.so.1 (0x00007ffc853a7000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f9241402000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f92412c8000)
	libelf.so.1 => /usr/lib64/libelf.so.1 (0x00007f92412ad000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f9241293000)
	libcrypto.so.1.1 => /usr/lib64/libcrypto.so.1.1 (0x00007f9240fd0000)
	libssl.so.1.1 => /usr/lib64/libssl.so.1.1 (0x00007f9240f3d000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f9240f32000)
	libuv.so.1 => /usr/lib64/libuv.so.1 (0x00007f9240eff000)
	libjson-c.so.5 => /usr/lib64/libjson-c.so.5 (0x00007f9240eec000)
	libcups.so.2 => /usr/lib64/libcups.so.2 (0x00007f9240e51000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9240e31000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9240c71000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9241468000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9240c6a000)
	libgnutls.so.30 => /usr/lib64/libgnutls.so.30 (0x00007f9240ab4000)
	libidn2.so.0 => /usr/lib64/libidn2.so.0 (0x00007f9240a93000)
	libunistring.so.2 => /usr/lib64/libunistring.so.2 (0x00007f9240912000)
	libtasn1.so.6 => /usr/lib64/libtasn1.so.6 (0x00007f92408fc000)
	libnettle.so.8 => /usr/lib64/libnettle.so.8 (0x00007f92408bd000)
	libhogweed.so.6 => /usr/lib64/libhogweed.so.6 (0x00007f9240874000)
	libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007f92407f8000)
```

The resulting "lighter" cups.plugin does run, although I'm not really able to *really* test it...

**Comment by ilyam8** [comment] 2021-08-20 09:46
Closing this issue, because it looks like a very low priority.

**Closed by ilyam8** 2021-08-20 09:46 UTC
Labels: bug, area/collectors, area/build
