### ISSUE TITLE
internal compiler error: Segmentation fault on raspberry pi netdata-v1.26.0-70-gbea0eb64

### ISSUE THREAD

**Issue by miemiekurisu** [netdata/netdata#10147] opened 2020-10-27 09:04 UTC
##### Bug report summary

I try to install netdata on raspberry Pi b3+,
and use the 
`bash <(curl -Ss https://my-netdata.io/kickstart.sh)`
official command.
But it crashed when compiling with the openssh.
I've  tried servial times, but it crashed and cause the pi reboot everytime at the same point.
The last compile messgages are below:

```cmd
make[2]: Leaving directory '/tmp/netdata-updater-8mrls0yZMR/netdata-v1.26.0-70-gbea0eb64/spawn'
make[2]: Entering directory '/tmp/netdata-updater-8mrls0yZMR/netdata-v1.26.0-70-gbea0eb64'
  CC       libnetdata/os.o
  CC       web/api/formatters/json_wrapper.o
  CC       web/api/formatters/charts2json.o
  CC       web/api/formatters/rrdset2json.o
  CC       exporting/read_config.o
  CC       exporting/clean_connectors.o
  CC       exporting/init_connectors.o
  CC       exporting/process_data.o
  CC       exporting/check_filters.o
  CC       exporting/send_data.o
  CC       exporting/send_internal_metrics.o
  CC       collectors/cgroups.plugin/sys_fs_cgroup.o
  CC       collectors/apps.plugin/apps_plugin.o
  CC       libnetdata/adaptive_resortable_list/adaptive_resortable_list.o
  CC       libnetdata/config/appconfig.o
  CC       libnetdata/avl/avl.o
  CC       libnetdata/buffer/buffer.o
  CC       libnetdata/circular_buffer/circular_buffer.o
  CC       libnetdata/clocks/clocks.o
  CC       libnetdata/dictionary/dictionary.o
In file included from /usr/include/arm-linux-gnueabihf/asm/unistd.h:27,
                 from /usr/include/arm-linux-gnueabihf/sys/syscall.h:24,
                 from libnetdata/dictionary/../libnetdata.h:77,
                 from libnetdata/dictionary/dictionary.c:3:
/usr/include/arm-linux-gnueabihf/asm/unistd-common.h:1: internal compiler error: Segmentation fault
 #ifndef _ASM_ARM_UNISTD_COMMON_H
 
In file included from /usr/include/openssl/ssl.h:18,
                 from libnetdata/clocks/../socket/security.h:26,
                 from libnetdata/clocks/../libnetdata.h:310,
                 from libnetdata/clocks/clocks.c:3:
/usr/include/openssl/bio.h:581:1: internal compiler error: Segmentation fault
 int BIO_nread(BIO *bio, char **buf, int num);
 ^~~
```

##### OS / Environment

```
Linux raspberrypi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
/etc/os-release:HOME_URL="http://www.raspbian.org/"
/etc/os-release:SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
/etc/os-release:BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

##### Netdata version

 netdata v1.25.0-107-nightly

##### Steps To Reproduce

1. ...
2. ...

**Comment by mfundul** [comment] 2020-10-27 09:49
Wow, the compiler crashed. Any chance you have bad RAM or bad SD card storage? Can you update your compiler packages?

**Comment by Ferroin** [comment] 2020-10-27 11:57
Seconding what @mfundul said. In roughly 99% of cases, a segfault in the compiler is a hardware issue of some sort. The fact that this happened in a core system header and not Netdata code reinforces this probability.

If this is reproducible after rebooting and consistently fails in the same place, then you’ve got at-rest data corruption somewhere inpersistent storage, and should look at reinstalling _everything_ on the system (not just the compiler, any number of other things may be corrupted as well).

If this is not reproducible after rebooting, or you see the failure happen at different, seemingly random places each time, then the most likely culprits are bad RAM or a bad power supply, and I would suggest testing both.

**Comment by miemiekurisu** [comment] 2020-10-28 09:09
@mfundul @Ferroin Thx for your suggestion, I've upgraded the rasbian OS and tried again.
The compiler and system still crashed at the same point servial times,
until I run the install command direct in tty instead of in TMUX, at last it was compiled successful.

So I still don't know what happend and what the conflict between TMUX and netdata, but it seems everything is OK :)

**Comment by stelfrag** [comment] 2020-11-02 21:08
I am closing this then. It could be SD card. I couldn't reproduce on PRi (eg. in TMUX) 

my env
```
Linux rpi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Closed by stelfrag** 2020-11-02 21:08 UTC
Labels: bug, needs triage
