### ISSUE TITLE
Netdata master is no longer accepting the metrics from the slave

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#8825] opened 2020-04-25 16:08 UTC
##### Bug report summary

Yesterday, We've got an alert indicating netdata ip4 last collected of a slave is 5 minutes ago, When I opened the slave's dashboard in the master node, I realized it doesn't get metrics any more, then I tried to restart the netdata agent on the slave, but no luck.
I switched it's master to the new master and everything seemed fine until today which I got the same alert again. 
Here is what I got in the `error` logs for the slave:
```
2020-04-25 20:26:04: netdata INFO  : STREAM_SENDER[netdata-plugins-02.tool.x.y.z] : STREAM netdata-plugins-02.tool.x.y.z [send to 172.16.76.173:19999]: connecting...
2020-04-25 20:26:04: netdata INFO  : STREAM_SENDER[netdata-plugins-02.tool.x.y.z] : STREAM netdata-plugins-02.tool.x.y.z [send to 172.16.76.173:19999]: initializing communication...
2020-04-25 20:26:04: netdata INFO  : STREAM_SENDER[netdata-plugins-02.tool.x.y.z] : STREAM netdata-plugins-02.tool.x.y.z [send to 172.16.76.173:19999]: waiting response from remote netdata...
2020-04-25 20:26:04: netdata ERROR : STREAM_SENDER[netdata-plugins-02.tool.x.y.z] : STREAM netdata-plugins-02.tool.x.y.z [send to 172.16.76.173:19999]: server is not replying properly (is it a netdata?).
```
in the meanwhile, I didn't get any error in the master, but in the `access` logs I saw this:
```
2020-04-25 20:35:00: 17370: 9301 '[172.21.49.190]:60970' 'CONNECTED'
2020-04-25 20:35:00: 17370: 9301 '[172.21.49.190]:60970' 'DISCONNECTED'
2020-04-25 20:35:00: 17370: 9301 '[172.21.49.190]:60970' 'STREAM' (sent/all = 0/0 bytes -0%, prep/sent/total = 1587830700350.56/1587830700350.83/0.28 ms) 200 'key=12370493-ee42-4989-b6b0-1069e21da4d8&hostname=netdata-plugins-02.tool.x.y.z&registry_hostname=netdata-plugins-02.tool.x.y.z&machine_guid=f3abab38-58b5-11ea-a651-fa163eb44d3e&update_every=5&os=linux&timezone=Etc/UTC&tags=&ver=2&NETDATA_SYSTEM_OS_NAME=Ubuntu&NETDATA_SYSTEM_OS_ID=ubuntu&NETDATA_SYSTEM_OS_ID_LIKE=debian&NETDATA_SYSTEM_OS_VERSION=16.04.6 LTS (Xenial Xerus)&NETDATA_SYSTEM_OS_VERSION_ID=16.04&NETDATA_SYSTEM_OS_DETECTION=/etc/os-release&NETDATA_SYSTEM_KERNEL_NAME=Linux&NETDATA_SYSTEM_KERNEL_VERSION=4.4.0-174-generic&NETDATA_SYSTEM_ARCHITECTURE=x86_64&NETDATA_SYSTEM_VIRTUALIZATION=kvm&NETDATA_SYSTEM_VIRT_DETECTION=systemd-detect-virt&NETDATA_SYSTEM_CONTAINER=unknown&NETDATA_SYSTEM_CONTAINER_DETECTION=none&NETDATA_CONTAINER_OS_NAME=none&NETDATA_CONTAINER_OS_ID=none&NETDATA_CONTAINER_OS_ID_LIKE=none&NETDATA_CONTAINER_OS_VERSION=none&NETDATA_CONTAINER_OS_VERSION_ID=none&NETDATA_CONTAINER_OS_DETECTION=&NETDATA_SYSTEM_CPU_LOGICAL_CPU_COUNT=2&NETDATA_SYSTEM_CPU_FREQ=0&NETDATA_SYSTEM_TOTAL_RAM=4143292416&NETDATA_SYSTEM_TOTAL_DISK_SIZE=23068672&NETDATA_PROTOCOL_VERSION=1.1'
2020-04-25 20:35:00: STREAM: 17358 '[172.21.49.190]:60970' 'REJECTED - ALREADY CONNECTED' host 'netdata-plugins-02.tool.x.y.z' api key '12370493-ee42-4989-b6b0-1069e21da4d8' machine guid 'f3abab38-58b5-11ea-a651-fa163eb44d3e'
2020-04-25 20:35:00: 17263: 9313 '[10.20.18.41]:55232' 'DATA' (sent/all = 1140/11076 bytes -90%, prep/sent/total = 0.43/0.22/0.65 ms) 200 '//api/v1/alarms'

```

##### OS / Environment

Both master and slave:
```
Linux netdata-master-02.tool.x.y.z 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.4 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.4 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

Netdata master: `netdata v1.21.1`
Netdata slave: `netdata v1.21.0`
 

##### Component Name

streaming

**Comment by thiagoftsm** [comment] 2020-04-25 16:15
Hi @yasharne ,

A doubt for I try to recreate the bug here, are you using SSL connection between master and slave?

Best regards!

**Comment by mfundul** [comment] 2020-04-25 16:16
This sounds like the master being busy with the slave for some reason. When the slave restarted and tried to reconnect it got denied access since the master possibly hasn't finished cleaning up their connection. Can you share your master's error log?

**Comment by yasharne** [comment] 2020-04-25 16:17
Hi @thiagoftsm No we don't use any SSL between master and slave, everything was working fine and this happened all of the sudden

**Comment by yasharne** [comment] 2020-04-25 16:21
@mfundul 
```bash
2020-04-25 20:38:00: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32958] : thread created with task id 17463
2020-04-25 20:38:00: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32958] : set name of thread 17463 to STREAM_RECEIVER
2020-04-25 20:38:00: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32958] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:32958: receive thread created (task id 17463)
2020-04-25 20:38:00: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32958] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32958]: multiple streaming connections for the same host detected. Rejecting new connection.
2020-04-25 20:38:00: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32958] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32958]: receive thread ended (task id 17463)
2020-04-25 20:38:00: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32958] : thread with task id 17463 finished
2020-04-25 20:38:05: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32966] : thread created with task id 17464
2020-04-25 20:38:05: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32966] : set name of thread 17464 to STREAM_RECEIVER
2020-04-25 20:38:05: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32966] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:32966: receive thread created (task id 17464)
2020-04-25 20:38:05: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32966] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32966]: multiple streaming connections for the same host detected. Rejecting new connection.
2020-04-25 20:38:05: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32966] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32966]: receive thread ended (task id 17464)
2020-04-25 20:38:05: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32966] : thread with task id 17464 finished
2020-04-25 20:38:10: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32972] : thread created with task id 17473
2020-04-25 20:38:10: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32972] : set name of thread 17473 to STREAM_RECEIVER
2020-04-25 20:38:10: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32972] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:32972: receive thread created (task id 17473)
2020-04-25 20:38:10: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32972] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32972]: multiple streaming connections for the same host detected. Rejecting new connection.
2020-04-25 20:38:10: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32972] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32972]: receive thread ended (task id 17473)
2020-04-25 20:38:10: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32972] : thread with task id 17473 finished
2020-04-25 20:38:15: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32978] : thread created with task id 17474
2020-04-25 20:38:15: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32978] : set name of thread 17474 to STREAM_RECEIVER
2020-04-25 20:38:15: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32978] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:32978: receive thread created (task id 17474)
2020-04-25 20:38:15: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32978] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32978]: multiple streaming connections for the same host detected. Rejecting new connection.
2020-04-25 20:38:15: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32978] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32978]: receive thread ended (task id 17474)
2020-04-25 20:38:15: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32978] : thread with task id 17474 finished
2020-04-25 20:38:20: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32984] : thread created with task id 17476
2020-04-25 20:38:20: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32984] : set name of thread 17476 to STREAM_RECEIVER
2020-04-25 20:38:20: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32984] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:32984: receive thread created (task id 17476)
2020-04-25 20:38:20: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32984] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32984]: multiple streaming connections for the same host detected. Rejecting new connection.
2020-04-25 20:38:20: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32984] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32984]: receive thread ended (task id 17476)
2020-04-25 20:38:20: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32984] : thread with task id 17476 finished
2020-04-25 20:38:25: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32990] : thread created with task id 17478
2020-04-25 20:38:25: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32990] : set name of thread 17478 to STREAM_RECEIVER
2020-04-25 20:38:25: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32990] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:32990: receive thread created (task id 17478)
2020-04-25 20:38:25: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32990] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32990]: multiple streaming connections for the same host detected. Rejecting new connection.
2020-04-25 20:38:25: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32990] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32990]: receive thread ended (task id 17478)
2020-04-25 20:38:25: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32990] : thread with task id 17478 finished
2020-04-25 20:38:30: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32996] : thread created with task id 17480
2020-04-25 20:38:30: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32996] : set name of thread 17480 to STREAM_RECEIVER
2020-04-25 20:38:30: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32996] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:32996: receive thread created (task id 17480)
2020-04-25 20:38:30: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32996] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32996]: multiple streaming connections for the same host detected. Rejecting new connection.
2020-04-25 20:38:30: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32996] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:32996]: receive thread ended (task id 17480)
2020-04-25 20:38:30: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:32996] : thread with task id 17480 finished
2020-04-25 20:38:35: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33002] : thread created with task id 17481
2020-04-25 20:38:35: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33002] : set name of thread 17481 to STREAM_RECEIVER
2020-04-25 20:38:35: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33002] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:33002: receive thread created (task id 17481)
2020-04-25 20:38:35: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33002] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:33002]: multiple streaming connections for the same host detected. Rejecting new connection.
2020-04-25 20:38:35: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33002] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:33002]: receive thread ended (task id 17481)
2020-04-25 20:38:35: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33002] : thread with task id 17481 finished
2020-04-25 20:38:40: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33008] : thread created with task id 17484
2020-04-25 20:38:40: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33008] : set name of thread 17484 to STREAM_RECEIVER
2020-04-25 20:38:40: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33008] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:33008: receive thread created (task id 17484)
2020-04-25 20:38:40: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33008] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:33008]: multiple streaming connections for the same host detected. Rejecting new connection.
2020-04-25 20:38:40: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33008] : STREAM netdata-plugins-02.tool.x.y.z [receive from [172.21.49.190]:33008]: receive thread ended (task id 17484)
2020-04-25 20:38:40: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33008] : thread with task id 17484 finished
2020-04-25 20:38:45: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33014] : thread created with task id 17493
2020-04-25 20:38:45: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33014] : set name of thread 17493 to STREAM_RECEIVER
2020-04-25 20:38:45: netdata INFO  : STREAM_RECEIVER[netdata-plugins-02.tool.x.y.z,[172.21.49.190]:33014] : STREAM netdata-plugins-02.tool.x.y.z [172.21.49.190]:33014: receive thread created (task id 17493)
```

**Comment by yasharne** [comment] 2020-04-25 16:25
changing the master node again fixed the problem but it believes this is a temporary solution like yesterday

**Comment by thiagoftsm** [comment] 2020-04-25 16:25
@mfundul , I agree, probably we will need to also to create an algorithm on master for when the slave is a long time without to send a message, we shut down the previous connection an accept the new.

**Comment by mfundul** [comment] 2020-04-25 16:26
Ok, so I don't know what's the master doing with this connection right now, but it's busy and it's rejecting the slave's attempts to reconnect.

You could wait for a little bit and see if the master finishes whatever cleanup it has to do, and the situation resolves itself.

Otherwise, we are in some unfortunate deadlock situation. The only workaround for that would be restarting the master server. If this happens again we should try and get a backtrace to understand what's going on.

Is the computer that's hosting the master server overloaded? Can it be the master server cannot keep up with the amount of slaves?

**Comment by mfundul** [comment] 2020-04-25 16:27
> 
> 
> @mfundul , I agree, probably we will need to also to create an algorithm on master for when the slave is a long time without to send a message, we shut down the previous connection an accept the new.

This would require some serious refactoring of the plugins.D code since this is possibly what's keeping the master busy.

**Comment by yasharne** [comment] 2020-04-25 16:31
@mfundul No everything is normal as usual. we have disabled all the python and go plugins on the master nodes. the second master monitors 70 nodes and the first one monitors 210 nodes

**Comment by thiagoftsm** [comment] 2020-04-25 16:35
@mfundul during the stress tests you did, could you find a limit for the number of slaves per master depending of the hardware?

**Comment by mfundul** [comment] 2020-04-25 16:38
> 
> 
> @mfundul during the stress tests you did, could you find a limit for the number of slaves per master depending of the hardware?

It depends on the number of active alarms. We still haven't merged the health scaling PR. Without any alarms we can do over 1000 slaves with a 16-core AMD Threadripper CPU. With a lot of alarms though maybe even 200 slaves may prove too many.

**Comment by stohn** [comment] 2020-05-14 14:12
@thiagoftsm 
I started an issue (#9039) which sounds very much like this one. 

In my case no load at all is involved.

Just a slow SSL connection from slave to master and a small buffer size on slave (1MB) triggers this very often for me. As a workaround I increased the buffer size on slave to 10MB which lets this happen not so often anymore.

**Comment by thiagoftsm** [comment] 2020-05-14 16:02
> @thiagoftsm
> I started an issue (#9039) which sounds very much like this one.
> 
> In my case no load at all is involved (master handles 6 slaves, monitors 78 alarms).
> 
> Just a slow SSL connection from slave to master and a small buffer size on slave (1MB) triggers this very often for me. As a workaround I increased the buffer size on slave to 10MB which lets this happen not so often anymore.

Hi @stohn ,

Thank you for your suggestion, would you like to create a PR increasing this buffer?

best regards!

**Comment by mfundul** [comment] 2020-05-14 16:05
> 
> 
> > @thiagoftsm
> > I started an issue (#9039) which sounds very much like this one.
> > In my case no load at all is involved (master handles 6 slaves, monitors 78 alarms).
> > Just a slow SSL connection from slave to master and a small buffer size on slave (1MB) triggers this very often for me. As a workaround I increased the buffer size on slave to 10MB which lets this happen not so often anymore.
> 
> Hi @stohn ,
> 
> Thank you for your suggestion, would you like to create a PR increasing this buffer?
> 
> best regards!

I thought he was talking about this:
https://github.com/netdata/netdata/blob/c35149a3b44c6ef6a4c8c71b5e390700076c2884/streaming/stream.conf#L81

**Comment by stohn** [comment] 2020-05-15 10:29
After I increased buffer size in "netdata/streaming/stream.conf" to 10 MB
`buffer size bytes = 12328960`
I never got my initial problem (could not reconnect after buffer overrun).

So it clearly is related to slave closes connection, master does not recognize/handle it properly.

This also looks like issue #8930

**Comment by ilyam8** [comment] 2020-05-15 11:50
it looks like yes, same problem as in #8930

**Comment by amoss** [comment] 2020-05-22 10:10
The basic problem is that when we receive a duplicate connection (from the same machine GUID) we choose to keep the old dead connection rather than the new live connection. I'm currently doing some work in the streaming code and I can replicate this bug on my setup. The fix will be part of a PR that adds a new feature - should be the middle of next week.

**Comment by amoss** [comment] 2020-05-29 10:04
(repeating here from the comment on #8930)

We've found the problem - it was the stability fixes that were added in March to handle large numbers of slaves. They had an unexpected interaction with the code that rejects multiple connections from the sender. The fix is being delayed slightly because it interacts with another piece of work that is in progress (fixing the gaps in charts when slaves restart). The PR should be complete by the end of next week - I'll let you know when it is finished.

**Closed** 2020-06-03 06:38 UTC
Labels: area/streaming, bug

**Comment by amoss** [comment] 2020-06-03 06:42
@yasharne / @stohn We had a delay in reviewing the PR but it has now been merged with the bug-fix. It is in the master branch now and will be picked up for the nightly build at the end of the day. Please let me know if it improves the behaviour that you see on your configurations, and re-open this issue if it does not fix the problem.

**Comment by stohn** [comment] 2020-06-04 10:52
I installed the new version and it seems the reconnection problem disappeared.

* log shows the reconnect problem
```...
2020-06-04 11:59:51: STREAM: 20941 '[X.X.X.X]:33196' 'REJECTED - ALREADY CONNECTED' host 'host3' api key '...' machine guid '...'
2020-06-04 11:59:56: STREAM: 20984 '[X.X.X.X]:36762' 'REJECTED - ALREADY CONNECTED' host 'host3' api key '...' machine guid '...'
2020-06-04 12:00:01: STREAM: 22286 '[X.X.X.X]:40498' 'REJECTED - ALREADY CONNECTED' host 'host3' api key '...' machine guid '...'
2020-06-04 12:00:06: STREAM: 22704 '[X.X.X.X]:44308' 'REJECTED - ALREADY CONNECTED' host 'host3' api key '...' machine guid '...'
```
* stop old netdata
```
2020-06-04 12:00:08: STREAM: 2223  '[Y.Y.Y.Y]:42214' 'DISCONNECTED' host 'host1' api key '...' machine guid '...'
2020-06-04 12:00:08: STREAM: 2199  '[Z.Z.Z.Z]:17552' 'DISCONNECTED' host 'host2' api key '...' machine guid '...'
```
* you can see old version did not even output a DICONNECT for problematic 'host3'

---

* start new nedtata (git clone + compile of current version)

```
2020-06-04 12:00:57: STREAM: 22968 '[X.X.X.X]:63498' 'CONNECTED'    host 'host3' api key '...' machine guid '...'
2020-06-04 12:01:14: STREAM: 22988 '[Z.Z.Z.Z]:12492' 'CONNECTED'    host 'host2' api key '...' machine guid '...'
2020-06-04 12:01:40: STREAM: 23069 '[Y.Y.Y.Y]:57730' 'CONNECTED'    host 'host1' api key '...' machine guid '...'
2020-06-04 12:01:40: STREAM: 23069 '[Y.Y.Y.Y]:57730' 'DISCONNECTED' host 'host1' api key '...' machine guid '...'
2020-06-04 12:01:43: STREAM: 23278 '[Y.Y.Y.Y]:57742' 'CONNECTED'    host 'host1' api key '...' machine guid '...'
2020-06-04 12:03:34: STREAM: 22968 '[X.X.X.X]:63498' 'DISCONNECTED' host 'host3' api key '...' machine guid '...'
2020-06-04 12:03:35: STREAM: 23460 '[X.X.X.X]:3940'  'CONNECTED'    host 'host3' api key '...' machine guid '...'
...
```

A bit later I also had 3 more blackouts from my problematic streaming client 'host3'  but every reconnect attempt worked. 


So one problem solved, now I need to find out why this streaming client is loosing connection so often...


Thanks for your great software and support.

**Comment by amoss** [comment] 2020-06-04 11:50
That's great news! Happy to hear it. The frequent reconnections will be become less of a problem next week as we are patching the connection to replicate any missing data from the gap. The underlying cause can be many different things. If the connections are simply timing out then it could be packet loss. You mentioned above that you are using SSL - because the transport layer exchanges more packets it means that dead connections time out faster than raw sockets. How many netdata agents do you have have streaming metrics?

**Comment by DominikTrenz** [comment] 2020-06-04 12:43
Thanks for the fix! Do we only have to update the master or does every slave need an update?

**Comment by amoss** [comment] 2020-06-04 14:22
There are heavy change to both the receiver side and the sender side - I would update both to make sure.

**Comment by csch42** [comment] 2020-06-04 16:39
> On 4. Jun 2020, at 12:52, Maik Stohn <notifications@github.com> wrote:
> 
> I installed the new version and it seems the reconnection problem disappeared.
> 
> 

Confirmed. Works even for old clients (not unexpectedly).

Thanks!

	Clemens
