### ISSUE TITLE
'/usr/local/etc/netdata': No such file or directory

### ISSUE THREAD

**Issue by alivxlive** [netdata/netdata#5249] opened 2019-01-22 13:24 UTC
##### Bug report summary
Edit config not working after install or update netdata.
##### OS / Environment
Ubuntu 18.04 LTS

##### Netdata version (ouput of `netdata -V`)
netdata v1.12.0-rc3-18-nightly

##### Steps To Reproduce
There is two cases:
1.after install netdata via command (bash <(curl -Ss https://my-netdata.io/kickstart.sh))
2. after installation edit config not working
` ./edit-config 

USAGE:
  ./edit-config FILENAME

  Copy and edit the stock config file named: FILENAME
  if FILENAME is already copied, it will be edited as-is.

  The EDITOR shell variable is used to define the editor to be used.

  Stock config files at: '/usr/local/lib/netdata/conf.d'
  User  config files at: '/usr/local/etc/netdata'

  Available files in '/usr/local/lib/netdata/conf.d' to copy and edit:
`
and
`./edit-config netdata.conf 
File 'netdata.conf' is not found in '/usr/local/lib/netdata/conf.d'
`

**Comment by cakrit** [comment] 2019-01-22 15:40
This is a duplicate of #5136, which should be fixed by #5244.
After you get tonight's nightly build tomorrow, please verify that it works correctly.

**Comment by cakrit** [comment] 2019-01-23 13:18
Fix verified in #5136. Please do the update, verify it yourself and close this as well.

**Comment by cakrit** [comment] 2019-01-24 16:11
I expect the thumbs up means it works in this case. We're still not 100% done, because #5252  show a case where the config files go to a different directory, but I'm closing this one and we're continuing for a more general fix in #5252

**Closed by cakrit** 2019-01-24 16:11 UTC
Labels: area/packaging, bug, duplicate
