### ISSUE TITLE
[Bug]: kickstart fails with "Gpg Keys not imported, cannot verify repomd.xml for repo netdata-edge"

### ISSUE THREAD

**Issue by ndsda** [netdata/netdata#12154] opened 2022-02-16 13:23 UTC
### Bug description

Still cannot install Netdata on Centos 7 server.

### Expected behavior

Netdata installation to run as normal.

### Steps to reproduce

1.) Run wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
2.) It fails at " --- Checking for libuv availability. ---"

Stops at this point:

```
 --- Checking for libuv availability. ---
Importing GPG key 0x4B987DCC:
 Userid     : "https://packagecloud.io/netdata/netdata-edge (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: f3a9 5d59 f9ce 7471 b2d0 1381 98cc 3e6a 4b98 7dcc
 From       : https://packagecloud.io/netdata/netdata-edge/gpgkey
```

### Installation method

kickstart.sh

### System info

```shell
Linux grace-5 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 7.9.2009 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.9.2009 (Core)
/etc/system-release:CentOS Linux release 7.9.2009 (Core)
```

### Netdata build info

```shell
Cannot install
```

### Additional info

```cmd
# wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
--2022-02-16 13:14:10--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 188.114.96.7, 188.114.97.7, 2a06:98c1:3120::7, ...
Connecting to my-netdata.io (my-netdata.io)|188.114.96.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

    [ <=>                                                                                                                                                ] 45,878      --.-K/s   in 0.001s

2022-02-16 13:14:10 (57.8 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [45878]


/tmp/netdata-kickstart.sh: line 337: /tmp/netdata-test.WYH8mqrr8h: Permission denied
 --- Using /tmp/netdata-kickstart-kFSKPRW0Rl as a temporary directory. ---
 --- No existing installations of netdata found, assuming this is a fresh install. ---
 --- Attempting to install using native packages... ---
 --- Downloading repository configuration package. ---
[/tmp/netdata-kickstart-kFSKPRW0Rl]# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-kFSKPRW0Rl/netdata-repo-edge-1-1.noarch.rpm https://packagecloud.io/netdata/netdata-repoconfig/packages/el/7/netdata-repo-edge-1-1.noarch.rpm/download.rpm
 OK

 --- Installing repository configuration package. ---
[/tmp/netdata-kickstart-kFSKPRW0Rl]# env yum install /tmp/netdata-kickstart-kFSKPRW0Rl/netdata-repo-edge-1-1.noarch.rpm
Examining /tmp/netdata-kickstart-kFSKPRW0Rl/netdata-repo-edge-1-1.noarch.rpm: netdata-repo-edge-1-1.noarch
Marking /tmp/netdata-kickstart-kFSKPRW0Rl/netdata-repo-edge-1-1.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package netdata-repo-edge.noarch 0:1-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================================
 Package                                         Arch                                 Version                              Repository                                                   Size
=============================================================================================================================================================================================
Installing:
 netdata-repo-edge                               noarch                               1-1                                  /netdata-repo-edge-1-1.noarch                               556

Transaction Summary
=============================================================================================================================================================================================
Install  1 Package

Total size: 556
Installed size: 556
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : netdata-repo-edge-1-1.noarch                                                                                                                                              1/1
  Verifying  : netdata-repo-edge-1-1.noarch                                                                                                                                              1/1

Installed:
  netdata-repo-edge.noarch 0:1-1

Complete!
 OK

 --- Checking for libuv availability. ---
Importing GPG key 0x4B987DCC:
 Userid     : "https://packagecloud.io/netdata/netdata-edge (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: f3a9 5d59 f9ce 7471 b2d0 1381 98cc 3e6a 4b98 7dcc
 From       : https://packagecloud.io/netdata/netdata-edge/gpgkey

https://packagecloud.io/netdata/netdata-edge/el/7/x86_64/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo netdata-edge
Trying other mirror.


 One of the configured repositories failed (Netdata Edge),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=netdata-edge ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable netdata-edge
        or
            subscription-manager repos --disable=netdata-edge

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=netdata-edge.skip_if_unavailable=true

failure: repodata/repomd.xml from netdata-edge: [Errno 256] No more mirrors to try.
https://packagecloud.io/netdata/netdata-edge/el/7/x86_64/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo netdata-edge
 --- Checking for usable Netdata package. ---
Importing GPG key 0x4B987DCC:
 Userid     : "https://packagecloud.io/netdata/netdata-edge (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: f3a9 5d59 f9ce 7471 b2d0 1381 98cc 3e6a 4b98 7dcc
 From       : https://packagecloud.io/netdata/netdata-edge/gpgkey

https://packagecloud.io/netdata/netdata-edge/el/7/x86_64/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo netdata-edge
Trying other mirror.


 One of the configured repositories failed (Netdata Edge),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=netdata-edge ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable netdata-edge
        or
            subscription-manager repos --disable=netdata-edge

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=netdata-edge.skip_if_unavailable=true

failure: repodata/repomd.xml from netdata-edge: [Errno 256] No more mirrors to try.
https://packagecloud.io/netdata/netdata-edge/el/7/x86_64/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo netdata-edge
 WARNING  Could not find a usable native package for centos on x86_64.

 --- Attempting to uninstall repository configuration package. ---
[/tmp/netdata-kickstart-kFSKPRW0Rl]# env yum remove netdata-repo-edge
Resolving Dependencies
--> Running transaction check
---> Package netdata-repo-edge.noarch 0:1-1 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

=============================================================================================================================================================================================
 Package                                         Arch                                 Version                             Repository                                                    Size
=============================================================================================================================================================================================
Removing:
 netdata-repo-edge                               noarch                               1-1                                 @/netdata-repo-edge-1-1.noarch                               556

Transaction Summary
=============================================================================================================================================================================================
Remove  1 Package

Installed size: 556
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Erasing    : netdata-repo-edge-1-1.noarch                                                                                                                                              1/1
  Verifying  : netdata-repo-edge-1-1.noarch                                                                                                                                              1/1

Removed:
  netdata-repo-edge.noarch 0:1-1

Complete!
 OK

 WARNING  Could not install native binary packages, falling back to alternative installation method.
```

**Comment by ilyam8** [comment] 2022-02-16 19:24
Hi, @ndsda.

Can you try with `--non-interactive` and as `root` user

> wget -O /tmp/netdata-kickstart.sh [my-netdata.io/kickstart.sh](https://my-netdata.io/kickstart.sh) && sh /tmp/netdata-kickstart.sh --non-interactive

**Comment by ndsda** [comment] 2022-02-16 23:59
Thanks @ilyam8 I tried your suggestion and it installed without any issues.

**Comment by ilyam8** [comment] 2022-02-17 09:52
@ndsda, it is a known bug in YUM when running interactively: it doesn't display confirmation prompts for adding GPG keys.

Perhaps we need to add a note to our documentation @Ferroin @kickoke

**Comment by Ferroin** [comment] 2022-02-17 14:49
Reopening this because I do intend to try and fix the issue, I just have yet to figure out _why_ it’s happening.

I’ll flag this issue in the PR that actually fixes things.

**Comment by kickoke** [comment] 2022-02-18 11:47
@ilyam8 
I just re-read the initial bug description and the user wanted to use the kickstart.sh on a CentOS machine, right? 
I don't understand 100% how yum plays a role in this. 
Should we add a note in `kickstart.md`:

We're currently resolving an installation error on CentOS machines. In the meantime, you can still install Netdata with the kickstart script as root when you set `--non-interactive`. 

```bash
wget -O /tmp/netdata-kickstart.sh [my-netdata.io/kickstart.sh](https://my-netdata.io/kickstart.sh) && sh /tmp/netdata-kickstart.sh --non-interactive
```

**Comment by Ferroin** [comment] 2022-02-18 15:10
@kickoke It’s a bit more complicated than just that, the script also has to be run as root unless the user has passwordless `sudo` set up for the user they are running it as.

**Comment by Ferroin** [comment] 2022-02-25 16:28
OK, I’ve gotten some confirmation that this is also an issue on some Fedora systems as well.

I’m still not sure what’s going on here, and I’m still inclined to believe this is a bug in YUM/DNF itself and not our code, we will need to investigate further regardless.

**Comment by iigorkarpov** [comment] 2022-02-26 05:52
I'm pretty sure that the problem is with our repository organization.

**Comment by iigorkarpov** [comment] 2022-02-27 11:10
The root of repository is (correct me if I'm wrong)
`https://packagecloud.io/netdata/netdata-repoconfig/`

**Comment by Ferroin** [comment] 2022-02-28 12:37
No, the root of the repository in the above example is `https://packagecloud.io/netdata/netdata-repoconfig/el/7/x86_64`, or more generically `https://packagecloud.io/netdata/netdata{,-edge,-repoconfig}/<distro>/<version>/<architecture>`

So it’s not the metadata file location that’s the issue.

**Comment by maneamarius** [comment] 2022-03-24 09:47
I open this PR to fix the issue:
https://github.com/netdata/netdata/pull/12506

**Comment by maneamarius** [comment] 2022-03-24 11:22
Issue should be resolved now, closing.

**Closed by maneamarius** 2022-03-24 11:22 UTC
Labels: bug, area/packaging, area/upstream
