### ISSUE TITLE
Heavy CPU load

### ISSUE THREAD

**Issue by panpansh** [netdata/netdata#6305] opened 2019-06-18 11:33 UTC
uptime 8 days without any more tasks : 

![Capture-netdata](https://user-images.githubusercontent.com/790586/59678426-afc83400-91cc-11e9-9937-06e61bbe4e6e.JPG)

stopping netdata : 

![Capture-netdata-stop](https://user-images.githubusercontent.com/790586/59678441-beaee680-91cc-11e9-9b3a-168717ef3040.JPG)

(re)start netdata : 

![Capture-netdata-restarted](https://user-images.githubusercontent.com/790586/59678461-c79fb800-91cc-11e9-9bd1-14d4e5921c25.JPG)

8% more cpu usage after 8days uptime, what do you think ?

```SH
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 86
Model name:            Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz
Stepping:              3
CPU MHz:               819.226
CPU max MHz:           2700.0000
CPU min MHz:           800.0000
BogoMIPS:              4399.54
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              9216K
NUMA node0 CPU(s):     0-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
```

**Comment by mfundul** [comment] 2019-06-18 11:39
What version of netdata are you running?

**Comment by panpansh** [comment] 2019-06-18 11:51
netdata v1.15.0-70-g8e72397

**Comment by ilyam8** [comment] 2019-06-18 13:29
@panpansh please update to the latest, it is likely that the problem is fixed there

**Comment by panpansh** [comment] 2019-06-19 03:05
ok, using your updater I have this version now : netdata v1.15.0-104-nightly
waiting 8 more days :) thanks

**Comment by ilyam8** [comment] 2019-06-19 17:53
@panpansh 	
according your version 

> netdata v1.15.0-70-g8e72397

the issue you faced is the same as in #6244, so am closing this for now, feel free to reopen if i am wrong

**Closed** 2019-06-19 17:53 UTC
Labels: bug, duplicate, needs triage
