### ISSUE TITLE
automatically monitor many processes, individually, matching a pattern

### ISSUE THREAD

**Issue by b0urb0n** [netdata/netdata#2431] opened 2017-07-07 20:36 UTC
Is there a way to collect on a wildcard group of processes but still report them as individual apps/processes?

I'd like to collect my-app-* where the process name has a random string built into it so multiple can run simultaneously and I know which is which.  I also want to be able to see my-app-X's performance compared to my-app-Y's.

I'd like to capture on all processes named my-app-* and still see their data individually in the dashboard.

**Comment by ktsaou** [comment] 2017-07-07 21:37
I am sorry, but this is not currently possible.

You can however generate `apps_groups.conf` with all your apps as groups, and `killall apps.plugin`. It will do the job, but you will need to redo this every time you add a new app.

**Comment by ktsaou** [comment] 2017-07-07 21:38
btw, I have to say that I like this idea. I was thinking too to extend apps.plugin to monitor individual processes and provide full statistics for them (even a different dashboard section for each of them).

**Comment by b0urb0n** [comment] 2017-07-07 21:45
Not sure if it helps but Telegraf does this in its [input.procstat](https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf#L1756) by using pgrep.

**Comment by wKavey** [comment] 2018-07-13 15:20
Was this ever expanded upon? I would love to see per-process stats such as memory and cpu usage

**Comment by rariteta** [comment] 2018-08-06 07:06
Upvoting for this issue - NetData itself is awesome, but the processtable plugin without this feature is really clumsy. We've migrated to NetData from free NewRelic, where one could easily get an insight of top-20 most resource consuming processes any given minute, and this info was refreshing dynamically depending on the host processes running, without any need to intervene into host configs.
  Thus particularities of app.netdata plugin is a spoon of tar in a barrel of honey.

**Comment by ktsaou** [comment] 2018-09-13 09:28
Well, I think the problem is a bit different.

Most solutions (if I recall correctly, including newrelic) present just a remote "top" view. So you can view the latest resource utilization of each process.

My goal with `apps.plugin` is to allow us have a history for the resource utilization of each process.

To have a history, we need to somehow eliminate the noise and the randomness of the process tree. So, we need to somehow group the processes together and track history of the groups.

netdata does this in a few very nice and quite unique ways:

1. You can enable systemd monitoring, so that you can have resource utilization **per service**.  Check this: https://github.com/firehol/netdata/wiki/monitoring-systemd-services - unfortunately most distros have this disabled by default.

2. `apps.plugin` does a magnificent job. Unlike `top` and all the other similar tools, apps.plugin reports even the resource utilization of the exit children of process! For example, if you have a shell script that spawns hundreds of processes per second, netdata will report its total CPU utilization, while all other tools will not. Check more here: https://github.com/firehol/netdata/wiki/Linux-console-tools%2C-fail-to-report-per-process-CPU-usage-properly

3. `apps.plugin` also provides a lot of pivots on these data: per application group, per user, per user group and we plan to add more (eg. per container)

All the above come with a history. So metrics are tracked over time, are reported to backend databases, alarms can be built using them, etc.

The bad thing is that it needs to group the processes.

So, I suggest to decide a universal `apps_groups.conf` you will use on all your servers. Make a list of all the apps your run, build one `apps_groups.conf` with everything you need, for all the applications you run, and install it on all your servers.

---

I agree it would be nice to also show a remote `top` though. It would be useful, to avoid an ssh session in case you need to know exactly what is happening. But it is not my first priority. So, PRs are accepted...

**Comment by ilyam8** [comment] 2021-07-16 12:36
Closing this feature request. We will re-evaluate the request internally.

**Closed by ilyam8** 2021-07-16 12:36 UTC
Labels: area/collectors, feature request, help wanted, priority/low
