### ISSUE TITLE
[Bug]: Netdata v4.47.1 does not build on FreeBSD 14.0 amd64

### ISSUE THREAD

**Issue by Cris70** [netdata/netdata#18604] opened 2024-09-23 20:59 UTC
### Bug description

Build stops with "exit code 2". 
![immagine](https://github.com/user-attachments/assets/67cc5e94-d7df-4910-bfbf-8559d2efbc35)

There was no other error message that I could spot in the build log.
Where do I go from here?

### Expected behavior

Netdata is compiled and installed in /opt.

### Steps to reproduce

1. I cloned the repository and then switched to the v1.47 branch.
2. Then I tried to build with
`./netdata-installer.sh --install-prefix /opt`
After getting to 14%, the build stopped with "exit code 2". 

### Installation method

from git

### System info

```shell
FreeBSD fbsd.guadagnino.lan 14.0-RELEASE FreeBSD 14.0-RELEASE #0 releng/14.0-n265380-f9716eee8ab4: Fri Nov 10 05:57:23 UTC 2023     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
1400097
```

### Netdata build info

```shell
n/a
```

### Additional info

```
# Mon Sep 23 10:47:17 CEST 2024
CFLAGS="-O2 -pipe" LDFLAGS="" ./netdata-installer.sh--install-prefix/opt
[root /home/cris/netdata-v1.47.1]# /usr/local/bin/cmake -S ./ -B ./build/ -DCMAKE_INSTALL_PREFIX=/opt/netdata -DNETDATA_USER=netdata -DENABLE_PLUGIN_GO=On -DENABLE_BUNDLED_PROTOBUF=On -DENABLE_PLUGIN_SYSTEMD_JOURNAL=Off -DENABLE_PLUGIN_CUPS=Off -DENABLE_PLUGIN_DEBUGFS=Off -DENABLE_PLUGIN_PERF=Off -DENABLE_PLUGIN_SLABINFO=Off -DENABLE_PLUGIN_CGROUP_NETWORK=Off -DENABLE_PLUGIN_LOCAL_LISTENERS=Off -DENABLE_PLUGIN_NETWORK_VIEWER=Off -DENABLE_PLUGIN_EBPF=Off -DENABLE_ACLK=On -DENABLE_CLOUD=On -DENABLE_BUNDLED_JSONC=Off -DENABLE_DBENGINE=On -DENABLE_H2O=On -DENABLE_ML=On -DENABLE_PLUGIN_APPS=On -DENABLE_EXPORTER_PROMETHEUS_REMOTE_WRITE=Off -DENABLE_EXPORTER_MONGODB=Off -DENABLE_PLUGIN_FREEIPMI=Off -DENABLE_PLUGIN_NFACCT=Off -DENABLE_PLUGIN_XENSTAT=Off  ... OK
[root /home/cris/netdata-v1.47.1]# /usr/local/bin/cmake --build ./build/ --parallel 4 -- VERBOSE=1  ... FAILED with exit code 2
```

**Comment by ilyam8** [comment] 2024-09-23 21:11
Duplicate of #18120

**Closed by ilyam8** 2024-09-23 21:11 UTC
Labels: bug, needs triage

**Comment by Cris70** [comment] 2024-09-23 21:18
Hi @ilyam8 , are you sure it's a duplicate?
I saw mrdaemon's build log and it seems nothing like mine.
