### ISSUE TITLE
[Feat]: make openrc conditional

### ISSUE THREAD

**Issue by vermaete** [netdata/netdata#18310] opened 2024-08-12 08:04 UTC
### Problem

When building the netdata (1.46.3) in Yocto there is the following error:
```
ERROR: netdata-1.46.3-r0 do_package_qa: QA Issue: /usr/lib/netdata/system/openrc/init.d/netdata contained in package netdata requires /sbin/openrc-run, but no providers found in RDEPENDS:netdata? [file-rdeps]
ERROR: netdata-1.46.3-r0 do_package_qa: Fatal QA errors were found, failing task.
```

### Description

OpenRC support in Yocto is rather uncommon.  When yocto is packaging the file to be installed it discover that a file needs the 'openrc-run'.  What is not existing.  So it fails.

A possible solution could be to have the possibility do disable the OpenRC feature at configuration (cmake).
Then those files would not be installed. 
Another solution is to patch the CMake files in Yocto itself.

### Importance

nice to have

### Value proposition

1.  Files that are not needed should no be installed.  Kind of security related thing.  And in case of Yocto, the smaller the image the better.
2.  Having a Yocto bitbake recipe for netdata would be useful for a lot of IoT stuff.
3. Having that recipe maintained by Netdata would be great!
...

### Proposed implementation

If possible a` -DDISABLE_OPENRC=TRUE` option to CMake?

**Comment by vermaete** [comment] 2024-08-12 08:10
I assume the same for LSB?
Well, all except sysV and Systemd.  Those are supported by Yocto.

**Comment by ilyam8** [comment] 2024-08-12 08:13
I don't know. But don't create multiple feature requests - close this one and open a new one that covers everything.

**Comment by Ferroin** [comment] 2024-08-12 14:41
As far as I can tell, the specific thing the QA warning is complaining about is that there’s an executable script that has no recognized interpreter. That’s easy enough to fix (we can trivially just mark all of the stuff under that directory as not being executable), and something we should probably do regardless. I’ll have a PR up to make that specific change shortly.

As far as the proposed solution though, adding options for excluding these files from installation has little practical benefit for a nontrivial amount of extra complexity in the build system. The whole section of the directory tree that this is in is 14k of data across 16 files, all with very high compressibility (IOW, this probably fits into less than 4k in something like EROFS or SquashFS). As much as I appreciate Yocto’s desire for tiny system images, the ~8k of actual storage space this might save is either not going to matter at all, or if it does matter it’s highly unlikely the target system will be able to do anything useful running Netdata locally. And accommodating that minuscule gain that won’t even matter for a vast majority of users would add extra complexity to the build system, thus increasing the maintenance burden for us. That type of thing is very solidly in the realm of things that distro-specific patches are for.

**Comment by vermaete** [comment] 2024-08-12 15:45
@Ferroin It seems to work.  I hope to submit the new Yocto recipe within a few day.  There are still a few things open.  E.g. the detection of Go in CMake is failing.  How you mind take over the recipe?

**Comment by Ferroin** [comment] 2024-08-12 17:35
> @Ferroin It seems to work. I hope to submit the new Yocto recipe within a few day. There are still a few things open. E.g. the detection of Go in CMake is failing. How you mind take over the recipe?

I don’t think we’ve got enough resources on our end currently to be able to take over maintenance of the Yocto recipe unfortunately.

Regarding the Go detection, it’s likely that the issue is simply that the toolchain is being installed somewhere that our build system does not expect to find it (on UNIX-like systems, we search in `$PATH` and `/usr/local/go/bin`, with the first working on pretty much every distro I’ve tested the build on, and the second being where the pre-built toolchains from https://go.dev end up installed by default). If you set `GOROOT` correctly in the build environment though (you can run `go env GOROOT` to get the correct value for your install of Go), that will override the detection so that the build system simply looks in `${GOROOT}/bin`, which should always work as long as you have a working copy of the Go toolchain.

**Closed** 2024-08-14 12:00 UTC
Labels: area/packaging, feature request
