### ISSUE TITLE
Unable to resolve my-netdata.io

### ISSUE THREAD

**Issue by wbreiler** [netdata/netdata#11761] opened 2021-11-05 21:00 UTC
##### Bug report summary

I am unable to resolve `my-netdata.io` on any device. 

##### OS / Environment

```
Linux master-pi 5.4.0-1045-raspi #49-Ubuntu SMP PREEMPT Wed Sep 29 17:49:16 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.3 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.3 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Expected behavior

Installation script should be able to grab the file from the website and run, but since the website is unreachable that is not possible.

**Comment by eZwzAEkx** [comment] 2021-11-06 07:10
ping: my-netdata.io: Temporary failure in name resolution

**Comment by ilyam8** [comment] 2021-11-06 15:40
Thanks for reporting, guys. The issue is identified and we are working on resolving it. Will be fixed soon.

**Comment by ilyam8** [comment] 2021-11-06 16:19
The issue is fixed 🎉

**Closed** 2021-11-06 16:37 UTC
Labels: bug, needs triage
