### ISSUE TITLE
Use env vars as default values for alert settings

### ISSUE THREAD

**Issue by githubsaturn** [netdata/netdata#5782] opened 2019-04-03 05:48 UTC
##### Feature idea summary

It'd be great if the values defined in `health_alarm_notify.conf` where being defaulted by the same variable if they exist in environmental variables.

This is really helpful specially in Docker world, where we could just add an `-e DEFAULT_RECIPIENT_SLACK='something'` and everything just works.

https://github.com/netdata/netdata/blob/1219a0a324e1be20d34b6e48af4799f906d0a395/health/notifications/health_alarm_notify.conf#L377

**Comment by cakrit** [comment] 2019-04-03 11:22
I can't think of an easy way to do this. How do people normally provide custom configurations to a docker instance? Can't you e.g. mount a volume containing custom config files and modify the COMMAND to first `cp` the config files to the user config directory?  I haven't done this yet, but I'm sure we have many people who have.

**Comment by Ferroin** [comment] 2019-04-03 11:31
@cakrit It should actually be pretty easy to do this as there's a standard parameter expansion syntax in bash for assigning default values (and we're already pretty deep into needing bash for `alarm-notify.sh`).

    DEFAULT_RECIPIENT_SLACK="$(DEFAULT_RECIPIENT_SLACK:-'')"

Will do exactly what's needed, though it has to be used in `alarm-notify.sh` (where we first define these variables), and the config file either has to have variables we want to use the defaults for commented out, or use the same construct.

**Comment by cakrit** [comment] 2019-04-03 12:32
This is nice actually, but it's not enough. The issue is that alarm-notify.sh is executed by the daemon. The daemon forks a new process and is able to pass an environment to that process, with some minor modifications. The question is how netdata would populate that environment with the appropriate variables (it currently doesn't and the process doesn't get the user's shell environment either, it's the first thing I tried). 

We can probably modify the daemon's `main.c` so, that we can get **all** environment variables and pass them later to `alarm-notify.sh`. i.e. we convert `int main(int argc, char **argv)` to `int main(int argc, char **argv, char **envp)` and pass everything in `envp` to the script. Two things I'm not sure about:
- Need to discuss internally if that change could have any things to watch out for regarding portability, security etc. 
- We'd blindly pass all the variables to `alarm-notify.sh`. I don't expect issues with that, because all the variables used by the script that I know of are initialized first, but I can't be 100% certain. 

@mfundul for some feedback on the first item.

**Comment by Ferroin** [comment] 2019-04-03 12:58
Ah, I didn't realize we were scrubbing the environment when calling `alarm-notify.sh`.  Makes a lot more sense now that it's not exactly easy.

The first suggestion that comes to mind is using some prefix for the variables that are for configuring `alarm-notify.sh`, strip that prefix when building the environment for it, and pass everythign that had that prefix that we are not explicitly generating ourselves.

**Comment by cakrit** [comment] 2019-04-03 14:06
Good idea, something like `NETDATA_` would work. Let me get @mfundul's and @ktsaou's opinion and we can plan this. Docker is very important to us, so we need to do something to help people.

**Comment by githubsaturn** [comment] 2019-04-03 14:14
Just to shed more light on this, I am currently using a 3rd party Docker container. The easy solution they're using is to prepopulate the conf file using the env vars in their run command. 

See this: https://github.com/titpetric/netdata/blob/master/releases/v1.10.0/scripts/run.sh

**Comment by cakrit** [comment] 2019-04-03 14:31
Custom command then, not bad. The only problem with that is that the third party would need to keep updating this command every time we add a new notification method (e.g. smstools3). But of course you can take it and customize it as you like. 

I'm thinking that we need to something better and more generic here, to solve the Docker configuration problem beyond notifications. In kubernetes we used ConfigMap in [our helmchart](https://github.com/netdata/helmchart), so I'm pretty sure we can do something better. I'm just not very proficient in Docker. Has anyone reading this used volumes to put config files in a Docker image? One silly way I was thinking about was to mount a pre-prepared directory containing all the user configurations you want and have our run.sh look for such a directory and copy files to the user directory netdata checks. That was my first response...

**Comment by Ferroin** [comment] 2019-04-03 14:38
@cakrit I would think you could probably just have the directory mounted directly on `/etc/netdata`, or wherever we check in the Docker images.  Overall, that does sound like a much cleaner solution than using environment variables for cases where lots of changes are necessary, but I still think the environment variables would be nice for users who only need to change one or two things (default email recipient for example).

As far as the environment variable prefix, I was thinking something a bit more specific than just `NETDATA_`, as that will make it much clearer exactly _what_ is being configured, and make it less likely that we accidentally start using an environment variable with the same full name for something else.

**Comment by cakrit** [comment] 2019-04-03 14:59
> mounted directly on /etc/netdata

Mounting a directory that contains a symbolic link scares me. Talking about `/etc/netdata/orig`. We could rebuild that symlink and do any needed chown/chmod in run.sh I guess...

**Comment by Ferroin** [comment] 2019-04-03 15:25
@cakrit What's the symlink for?  I'm not seeing it on any of my systems running Netdata.

**Comment by githubsaturn** [comment] 2019-04-03 16:08
As an end-user, I'd rather the mounted directory is an "override" directory, i.e., even if the directory is empty, things just flow with default values. I should only be required to populate the files that I need to override. Does /etc/netdata provide such capabilities?

**Comment by cakrit** [comment] 2019-04-03 16:55
I looked at the Docker documentation again. Since the docker run -v option also accepts specific files, then I'd say that the most generic way forward is to pass as many `-v` options as the config files that you need to pass to the instance. E.g. to pass two files:
```
-v mypath/health_alarm_notify.conf:/etc/netdata/health_alarm_notify.conf 
-v mycustomalarm.conf:/etc/netdata/health.d/mycustomalarm.conf
```

Gents, I looked very seriously into the possibility of using variables while doing the k8s helmchart. With ~200 config files and who knows how many possible options in all those files, it just doesn't make much sense. What WILL help especially for the alarm notifications, is to do a small refactoring so that we don't have one huge `health_alarm_notify.conf`.  In reality, the following are all the settings you would need for SLACK notifications:
```
SEND_SLACK="YES"
SLACK_WEBHOOK_URL=""
DEFAULT_RECIPIENT_SLACK=""
role_recipients_slack[sysadmin]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[domainadmin]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[dba]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[webmaster]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[proxyadmin]="${DEFAULT_RECIPIENT_SLACK}"
role_recipients_slack[sitemgr]="${DEFAULT_RECIPIENT_SLACK}"
```

We could even make it smarter, so that only the first two lines are mandatory. So, perhaps, we just do some refactoring as we always intended to and simplify the config. Then, I think that mounting the volume would be a very straightforward way to go.

**Comment by 8ear** [comment] 2019-04-16 09:49
He guys,
I need also the possibility to forward variables into the container.
My proposal is to do it the same way as grafana: [https://grafana.com/docs/installation/docker/](https://grafana.com/docs/installation/docker/)
There way is to have the variables in special syntax:
> You can do this with any of the configuration options in conf/grafana.ini by setting `GF_<SectionName>_<KeyName>__FILE` to the path of the file holding the secret.

So we need only:
`NETDATA_<Filename>_<SectionName>_<KeyName>=<Value>`
Example:
`NETDATA;health_alarm_notify.conf_SLACK;SEND_SLACK="Yes"`
But we need an delimiter which is not taken in the files. So underscore is a not good delimiter. :-)
Perhaps ; or |

And our run.sh entrypoint script parses the environment variables and write it into the configuration files. Then you can change your variable and restart the container and it is active.

**Comment by 8ear** [comment] 2019-04-16 13:19
What the Hell,
why there are existing such variables:
`    reconnect delay seconds = 5`
` default postpone alarms on connect seconds = 60 `

Why with spaces???

Can not be all variables like the one from health alarm:
` EMAIL_THREADING=`

or easy ones:
` history = 3600`

or better why we can not have variables like: <SECTION>_<NAME-with-more-options>=<VALUE>

**Comment by danimart1991** [comment] 2020-09-05 06:54
Hi. 

Maybe an option at this moment is to use the commands in run.sh in docker-compose installation option.

`sed -i -e "s@SLACK_WEBHOOK_URL=\"\"@SLACK_WEBHOOK_URL=\"${SLACK_WEBHOOK_URL}\"@" /etc/netdata/health_alarm_notify.conf`

but I don't know how to exec this command because at first Netdata run, there is no health_alarm_notify.conf file and must be copied with another command. Maybe using something like: `export EDITOR=touch;/etc/netdata/edit-config health_alarm_notify.conf;` previously.

**Comment by ilyam8** [comment] 2021-07-26 14:42
Closing this feature request. We will re-evaluate the request internally.

**Closed by ilyam8** 2021-07-26 14:42 UTC
Labels: area/health, data-collection-mteam, feature request

**Comment by uhlhosting** [comment] 2023-09-04 10:19
@ilyam8 any updates on this matter?

We seems to have issues with the latest images.

**Comment by ilyam8** [comment] 2023-09-08 13:56
@uhlhosting no updates, unfortunately.

**Comment by ilyam8** [comment] 2023-09-08 14:29
@uhlhosting if you have any ideas/are willing to contribute - you are welcome, the feature request itself is ok.

I didn't test it (and I am not a bash specialist), it could be something as simple as iterating over env vars and declaring everything that has the `NETDATA_HEALTH_` prefix (after removing the prefix).

cc @netdata/agent-sre @MrZammler 

For instance, after [loading configs](https://github.com/netdata/netdata/blob/31924c0eb2fb245bdf047a5f4fe9f5ef10baf24e/health/notifications/alarm-notify.sh.in#L418-L432)


```bash
while IFS='=' read -r -d '' name value; do
  if [[ $name == NETDATA_HEALTH_* ]]; then
    name=${name#"NETDATA_HEALTH_"}
    declare name="$value"
  fi
done < <(env -0)
```

**Comment by uhlhosting** [comment] 2023-09-08 14:44
@githubsaturn you think youd be able to patch this if they accept it? Or maybe add some more details to it?

**Comment by githubsaturn** [comment] 2023-09-08 15:18
Yea i think this works great. Unfortunately i don't have time to build the patch. But i definitely agree with the proposed solution of the specific prefix. The patch will be probably as simple as pasting that snippet in the file referenced above. But def requires testing to make sure it works and I'm versed in netdata.
