### ISSUE TITLE
Netdata RPM package is not signed

### ISSUE THREAD

**Issue by ticktockhouse** [netdata/netdata#11183] opened 2021-05-25 06:29 UTC
##### Bug report summary

Netdata package for CentOS 7 is not signed. The package repo is setup correctly with GPG, but the package itself is not signed, meaning the user must disable GPG checking when installing. This is concerning as it throws the provenance of the package file into question

The error is as follows:

```
    Dependencies Resolved
  
    ================================================================================
     Package       Arch         Version                 Repository             Size
    ================================================================================
    Installing:
     netdata       x86_64       1.31.0-1.el7            netdata_netdata        14 M
    Installing for dependencies:
     libuv         x86_64       1:1.41.0-1.el7          epel                  153 k
  
    Transaction Summary
    ================================================================================
    Install  1 Package (+1 Dependent package)
  
    Total download size: 14 M
    Installed size: 55 M
    Downloading packages:
    Public key for libuv-1.41.0-1.el7.x86_64.rpm is not installed
    Package netdata-1.31.0-1.el7.x86_64.rpm is not signed
```

##### OS / Environment

```
/etc/centos-release:CentOS Linux release 7.8.2003 (Core)
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.8.2003 (Core)
/etc/system-release:CentOS Linux release 7.8.2003 (Core)
```

##### Netdata version

```
Version: netdata v1.31.0
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-libJudy=externaldeps/libJudy' '--with-bundled-lws=externaldeps/libwebsockets' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Features:
    dbengine:                YES
    Native HTTPS:            YES
    Netdata Cloud:           YES 
    Cloud Implementation:    Legacy
    TLS Host Verification:   YES
Libraries:
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```
##### Installation method

https://packagecloud.io/netdata/netdata/install#bash-rpm

##### Component Name

Netdata RPM package

##### Steps To Reproduce

1.Run the script at https://packagecloud.io/netdata/netdata/install#bash-rpm

##### Expected behavior

Netdata package is installed without any issues.

**Comment by Ferroin** [comment] 2022-02-22 15:28
We have plans to sign our packages, but for the moment they are on-hold pending a migration from Package Cloud to self-hosting of our repositories.

**Comment by Ferroin** [comment] 2022-06-29 08:12
Closing this as a duplicate of https://github.com/netdata/netdata/issues/7773.

As mentioned in the most recent comment there, this should be handled as part of the aforementioned migration from PackageCloud to self-hosted repos (we already need GPG set up properly to sign the repo metadata, so signing packages will be trivial to add as well).

**Closed by Ferroin** 2022-06-29 08:12 UTC
Labels: bug, area/packaging, needs triage
