### ISSUE TITLE
Add SCSI device support to smartd_log.chart.py

### ISSUE THREAD

**Issue by ScrumpyJack** [netdata/netdata#4285] opened 2018-09-25 14:03 UTC
man smartd says:
 [For ATA devices] "At each check cycle attributes are logged as a line of semicolon  separated  triplets  of  the  form "attribute-ID;attribute-norm-value;attribute-raw-value;". 
For SCSI devices error counters and temperature [are] recorded in the form "counter-name;counter-value;"

The plugin relies on the attribute-ID, but the smartd log files are only populated with attribute-ID for ATA devices (weirdly) 

Would it be possible to add support for SCSI disk smartd log files into smartd_log.chart.py?

**Comment by l2isbad** [comment] 2018-09-26 06:16
> For SCSI devices error counters and temperature [are] recorded in the form "counter-name;counter-value;"

please post here some lines from SCSI smartd log file

**Comment by ScrumpyJack** [comment] 2018-09-26 10:06
uploaded the csv output for a scsi drive here

https://b.ilet.to/uoluC

**Comment by l2isbad** [comment] 2018-09-26 10:43
Does all those counters has corresponding names/ids?

Which counters should we chart?

**Comment by l2isbad** [comment] 2018-09-26 10:46
@Ferroin any ideas?

**Comment by Ferroin** [comment] 2018-09-26 11:33
From a cursory look at the attributes listed, it seems to me that we should be tracking the following by default:

* `temperature`
* `*-total-unc-errors`: Appears to count uncorrected errors, which should be reported.
* `*-total-err-corrected`: Appears to count corrected errors, which should be reported.

The issue here is that the only one which maps directly to an ATA SMART attribute is temperature.  There's not any ID because SCSI sends the names directly as part of the protocol, instead of ATA, which sends the ID but not the name (and you have to map the ID to the name in software).  The reported values are functionally raw values, but they're in natural units for the counter type (degrees celsius for the temperature, individual errors for the error counters, etc).

**Comment by l2isbad** [comment] 2018-09-26 23:31
@ScrumpyJack 
what do you think?

**Comment by ScrumpyJack** [comment] 2018-09-27 06:40
looks good.
something clever could be done with the ratio
*-gb-processed/*-corr-algorithm-invocations
to get predictive failure, but knowing when that ratio is significant is another story.

**Comment by l2isbad** [comment] 2018-09-29 02:44
Hm, i don't know how to organize dashboard menu..

current version:
![screenshot_20180929_113456](https://user-images.githubusercontent.com/22274335/46240010-fb874300-c3db-11e8-84c4-7e4921c5afd4.png)

do not distinguish between ata and scsi and just add this as menu items?
```python
'read-total-err-corrected',
'read-total-unc-errors',
'write-total-err-corrected',
'write-total-unc-errors',
'verify-total-err-corrected',
'verify-total-unc-errors'
```

**Comment by ktsaou** [comment] 2018-09-29 02:55
I think:

1. power (having `start/stop`, `power on hours`, `power cycle count`)
2. errors (having `read error rate`, `reallocated sector count`, `seek error rate`, `current pending sectors`, `offline uncorrectable`)
3. temperature

I don't have visibility of the charts, so keep in mind you can group `XXX sectors`, `XXX error rate`, `XXX count` of the same family to a single chart. But don't mix incremental and absolute values (prometheus does not like that)

**Comment by l2isbad** [comment] 2018-09-29 05:43
> I don't have visibility of the charts,

Every [attribute](https://github.com/netdata/netdata/blob/master/python.d/smartd_log.chart.py#L18-L91) is a family which has two charts. One with normalized values, one with raw values. Dimensions - disks (super long names, like `KINGSTON_SHFS37A120G-50026B7266003D93`)

**Comment by ktsaou** [comment] 2018-09-29 14:32
> Every [attribute](https://github.com/netdata/netdata/blob/master/python.d/smartd_log.chart.py#L18-L91) is a family which has two charts

hm... this is a problem I think.

Let me try to group them

**Comment by l2isbad** [comment] 2018-09-29 15:02
Definitely a problem. User want to monitor specific attribute, so attribute as a family is nice (easy to choose from dashobard menu). After grouping to groups user will have to look through the titles to find attr in which he interested in.

**Comment by l2isbad** [comment] 2018-09-29 15:08
@ScrumpyJack as a plugin user what do you think?

**Comment by ktsaou** [comment] 2018-09-29 15:43
I think it is more complicated than that.

Let's see an example:

ID| Name                                     | units         | type | family      | alarm          | description
:---:|:-------------------------------------:|:-------------:|:----:|:-----------:|:---------------|:-----------
1 | `Read Error Rate`                        | -             | -    | -           |                | (Vendor specific raw value.) Stores data related to the rate of hardware read errors that occurred when reading data from a disk surface. The raw value has different structure for different vendors and is often not meaningful as a decimal number.
2 | `Throughput Performance`                 | value         | abs  | performance | on decrease    | Overall (general) throughput performance of a hard disk drive. If the value of this attribute is decreasing there is a high probability that there is a problem with the disk.
3 | `Spin-Up Time`                           | ms            | abs  | spin        |                | Average time of spindle spin up (from zero RPM to fully operational [milliseconds]).
4 | `Start/Stop Count`                       | events        | abs  | power       |                | A tally of spindle start/stop cycles. The spindle turns on, and hence the count is increased, both when the hard disk is turned on after having before been turned entirely off (disconnected from power source) and when the hard disk returns from having previously been put to sleep mode.
5 | `Reallocated Sectors Count`              | sectors       | inc  | wear        | sum(-1m) > 0   | Count of reallocated sectors. The raw value represents a count of the bad sectors that have been found and remapped.[25] Thus, the higher the attribute value, the more sectors the drive has had to reallocate. This value is primarily used as a metric of the life expectancy of the drive; a drive which has had any reallocations at all is significantly more likely to fail in the immediate months.
6 | `Read Channel Margin`                    | -             | -    | -           |                | Margin of a channel while reading data. The function of this attribute is not specified.
7 | `Seek Error Rate`                        | -             | -    | -           |                | (Vendor specific raw value.) Rate of seek errors of the magnetic heads. If there is a partial failure in the mechanical positioning system, then seek errors will arise. Such a failure may be due to numerous factors, such as damage to a servo, or thermal widening of the hard disk. The raw value has different structure for different vendors and is often not meaningful as a decimal number.
8 | `Seek Time Performance`                  | value         | abs  | performance | on decrease    | Average performance of seek operations of the magnetic heads. If this attribute is decreasing, it is a sign of problems in the mechanical subsystem.
9 | `Power-On Hours Count`                   | hours         | abs  | power       | warn >5 years? | Count of hours in power-on state. The raw value of this attribute shows total count of hours (or minutes, or seconds, depending on manufacturer) in power-on state.
10 | `Spin-up Retries`                       | retries       | inc  | spin        | sum(-1m) > 0   | Count of retry of spin start attempts. This attribute stores a total count of the spin start attempts to reach the fully operational speed (under the condition that the first attempt was unsuccessful). An increase of this attribute value is a sign of problems in the hard disk mechanical subsystem.
11 | `Calibration Retries`                   | retries       | inc  | spin        | sum(-1m) > 0   | This attribute indicates the count that recalibration was requested (under the condition that the first attempt was unsuccessful). An increase of this attribute value is a sign of problems in the hard disk mechanical subsystem.
12 | `Power Cycle Count`                     | events        | abs  | power       |                | This attribute indicates the count of full hard disk power on/off cycles.
13 | `Soft Read Error Rate`                  | errors        | inc  | errors      | sum(-1m) > 0   | Uncorrected read errors reported to the operating system
100 | `Erase/Program Cycles`                 | -             | -    | -           |                | 
103 | `Translation Table Rebuild`            | -             | -    | -           |                | 
108 | `Unknown (108)`                        | -             | -    | -           |                | 
170 | `Reserved Block Count`                 | %             | abs  | wear        | > 90           | Number of physical erase cycles completed on the SSD as a percentage of the maximum physical erase cycles the drive is designed to endure. Intel SSDs report the available reserved space as a percentage of the initial reserved space.
171 | `Program Fail Count`                   | errors        | inc  | wear        | sum(-1m) > 0   | (Kingston) The total number of flash program operation failures since the drive was deployed.[33] Identical to attribute 181.
172 | `Erase Fail Count`                     | failures      | inc  | wear        | sum(-1m) > 0   | (Kingston) Counts the number of flash erase failures. This attribute returns the total number of Flash erase operation failures since the drive was deployed. This attribute is identical to attribute 182.
173 | `Wear Leveller Worst Case Erase Count` | erases        | abs  | wear        |                | Counts the maximum worst erase count on any block.
174 | `Unexpected Power Loss`                | events        | abs  | power       |                | Also known as "Power-off Retract Count" per conventional HDD terminology. Raw value reports the number of unclean shutdowns, cumulative over the life of an SSD, where an "unclean shutdown" is the removal of power without STANDBY IMMEDIATE as the last command (regardless of PLI activity using capacitor power). Normalized value is always 100.
175 | `Power Loss Protection Failure`        | -             | -    | -           |                | Last test result as microseconds to discharge cap, saturated at its maximum value. Also logs minutes since last test and lifetime number of tests. Raw value contains the following data: Bytes 0-1: Last test result as microseconds to discharge cap, saturates at max value. Test result expected in range 25 <= result <= 5000000, lower indicates specific error code. Bytes 2-3: Minutes since last test, saturates at max value. Bytes 4-5: Lifetime number of tests, not incremented on power cycle, saturates at max value. Normalized value is set to one on test failure or 11 if the capacitor has been tested in an excessive temperature condition, otherwise 100.
176 | `Erase Fail Count`                     | failures      | inc  | wear        | sum(-1m) > 0   | S.M.A.R.T. parameter indicates a number of flash erase command failures.

So, I believe a few values need to be `absolute`, others need to be `incremental` and many have to completely ignored. 

Then to group them, we have to understand what they mean.

Keep in mind many have different labels compared to https://en.wikipedia.org/wiki/S.M.A.R.T.

I you want to do this right and be super useful for all people, I could try to finish this grouping. The above table has to be filled with all attributes and then another pass in needed to understand each family and assign chart names and metric names in each chart.

**Comment by ktsaou** [comment] 2018-09-29 16:33
> Definitely a problem. User want to monitor specific attribute, so attribute as a family is nice (easy to choose from dashobard menu). After grouping user will have to look through the titles to find attr in which he interested in

I am not sure of this use case. Who wants to check a specific SMART attribute? I don't even know the available SMART attributes. Normally, I want netdata to know them and let me know when something is wrong or indicates an issue.

**Comment by l2isbad** [comment] 2018-09-30 03:18
Incremental? I am not optimistic about `raw` values, because of

> but higher raw attribute values may be better or worse depending on the attribute and manufacturer

> As manufacturers do not necessarily agree on precise attribute definitions and measurement units

> Some codes are specific to particular drive types (magnetic platter, flash, SSD)

> Drives may use different codes for the same parameter

> Manufacturers that have implemented at least one S.M.A.R.T. attribute in various products include...

**Comment by ktsaou** [comment] 2018-09-30 18:42
Yes, this is why I have used incremental in `XXX count` and `XXX retries` attributes.

**Comment by Ferroin** [comment] 2018-10-01 11:34
If you give me a few days, I can put together a list of what I know of for certain on the ATA side (what needs to be absolute, what needs to be incremental, what each one means) based on the devices I have immediate access to (an assortment of traditional LMR HDD's and some TLC NAND SSD's).  There are however a few odd cases of attributes that pretty much have to be raw because they can't be reported sanely otherwise.  Temperatures fit this (and luckily almost all modern drives report them in degrees celsius, though there are some older models form US companies that report in Fahrenheit and I've seen a few odd ones that reported in Kelvins).

**Comment by ScrumpyJack** [comment] 2018-10-01 12:07
> @ScrumpyJack as a plugin user what do you think?

What do I think? I think this is the reason why this project is so successful.

**Comment by Ferroin** [comment] 2018-10-01 18:49
OK, regarding data I've found so far:

* Attribute 5 (Reallocated Sector Count) has a slightly different meaning for SSD's.  On HDD's, it tracks the number of physical sectors reallocated by the drive's firmware.  On SSD's, it tracks flash storage erase blocks, which are usually much bigger (2-8MB is typical).
* Attribute 7 (Seek Error Rate) has mostly useless raw values.  However, the cooked value is useful as almost all vendors use it correctly.  Pretty much, if the cooked value is less than 100, there is a non-zero number of seek errors, which is usually indicative of significant mechanical wear on the drive.
* Attribute 9 (Power-on Hours Count) is not actually all that useful in many cases as a generic indicator of drive life expectancy because we can't tell for certain what the actual drive life expectancy is.  Given this, id on't think having an alarm for it is a good idea, though exposing it in a chart is still worthwhile.
* Attribute 10 (Spinup Retries) is cumulative over the life of the drive.  For a healthy drive it should _never_ be above zero, at all.  Any non-zero value here is indicative of either an imminent mechanical failure, a past mechanical failure, or poor operational conditions that are likely to induce a mechanical failure.  However, if the system keeps it's disks spinning all the time (which is not unusual), the proposed alarm will likely never trigger, because the attribute will only change on system startup before Netdata starts.

Other attributes of potential interest include:

* 190 (Airflow Temperature Celsius): Measures the temperature of the airflow in the drive, raw value is in degrees Celsius.  Depending on drive construction, this may or may not be the same as 194 (Temperature Celsius).  Absolute, alarms make sense, but are too context dependent to ship defaults.
* 194 (Temperature Celsius) Measures the temperature of the drive, equivalent to the SCSI `temperature` attribute.  For SSD's this is typically either an aggregate measurement of the temperature of all the Flash chips and the controller, or a simple measurement near the center of the board.  For HDD's, it's usually either a measurement of the internal airflow temperature, or a measurement of the temperature of the drive heads.  Absolute raw value in degrees Celsius, alarms make sense, but are too context dependent to ship defaults.
* 196 (Reallocation Event Count): Tracks the total number of times over the lifetime of the drive that the firmware has reallocated a sector (for HDD's) or a flash erase block (for SSD's).  The raw value is an absolute indication of the total number of events over the lifetime of the drive, so we should track the rate of change and raise an alarm if it's non-zero.  Many HDD's do not seem to have this attribute.jjjjjjjjjjj
* 197 (Current Pending Sector Count): Tracks the number of sectors (or flash erase blocks on SSD's) pending for a rewrite by the drive firmware. Raw value is always an exact count of pending sectors.  Together with attribute 198, this is a reliable indicator of media wear.  This is an absolute value, and should ideally trip an alarm if it's ever non-zero, as that indicates that a media error has been found by the drive.
* 198 (Offline Uncorrectable Sector Count): Tracks the number of sectors (or flash erase blocks on SSD's) with media errors that could not be corrected by the drive firmware.  The raw value is an exact count of failed sectors.  Together with attribute 197, this is a reliable indicator of media wear.  This is an absolute value and needs to be reported as such, but any alarms based on it should report _changes_ in the value, not use a fixed threshold.  A lot of consumer NAS devices will kick disks with a non-zero value here out of a RAID array, but the disks are usually still good for quite some time afterwards despite this.
* 199 (UDMA CRC Error Count): Tracks the total number of UDMA CRC errors the drive has encountered.  The raw value is an absolute count, but charts should track a rate and the the alarms should trigger based on the rate.  I'm not sure what a good alarm would be for this, as I'm still not quite certain about the significance (I think it's indicative of hardware or software issues outside of the drive, but I'm not sure).
* 202 (Percent Lifetime Used): This is an aggregate estimate of how much of the expected life of the disk has been used.  Only widely seen on SSD's.  The cooked value (not the raw one) is the percentage _remaining_ life expectancy for the SSD.  This almost always changes very slowly and is only an integer, so tracking rate of change on the scale Netdata operates at is useless.  Most drives are set to fail SMART health checks when this hits 1%, 5% makes sense as a reasonable warning point for an alarm.

I'll hopefully have some more info tomorrow.

**Comment by ScrumpyJack** [comment] 2018-10-09 17:41
This is awesome research. I don't want to seem impatient, are we any closer to getting them graphed?

**Comment by Ferroin** [comment] 2018-10-09 18:09
@ScrumpyJack Unfortunately I don't think so.

@ktsaou I've not been able to find anything further except stuff that matches up with what you posted, so I think for the moment we probably have sufficient information to work with.

**Comment by l2isbad** [comment] 2018-10-10 07:20
@Ferroin please update [table](https://github.com/netdata/netdata/issues/4285#issuecomment-425654443) with the info you have found (i see `Other attributes of potential interest include`)
And i think we need attr type column (raw/normalized)

**Comment by Ferroin** [comment] 2018-10-10 11:35
Updated, including adding a couple other attributes I've largely confirmed are consistent.  I know of over a dozen more that aren't on the table, but they're so heavily vendor dependent as to whether they appear or not that I don't think we should track them.

Also, I just added the raw/normalized info to the type column, that seems to make the most sense.

**Comment by l2isbad** [comment] 2018-10-10 12:08
@Ferroin 
i see `194 Temperature Celsius abs raw`. But raw value makes no sense (ex.: `194;34;34359738402`)

**Comment by Ferroin** [comment] 2018-10-10 12:43
@l2isbad There's some extra parsing involved regardless of whether you use the normalized value or the raw value, but you can get extra data out of the raw value, hence my suggestion to use the raw value.  I just forgot to mention this in the notes.

More specifically, for both 190 and 194:

* For the normalized value reported value is 100 minus the actual temperature.
* For the raw value it's not directly readable as any value, but it can be parsed to get a minimum and maximum temperature for the drive over some vendor defined time period, plus the current temperature and possibly (on some Western Digital drives) a count of how many times the device has gone over the designed temperature range.  Info on the exact parsing can be found in the `ata_format_attr_raw_value()` function in `atacmds.cpp` in the smartmontools sources.  In short, there are five known formats:
  - The low byte is the current temperature, the third lowest is the minimum, and the fifth lowest is the maximum, with the other three bytes being either `\x00` or `\xff`.  Known to be used by Hitachi and HGST drives.
   - The low byte is the current temperature, the third lowest is the maximum, and the fifth lowest is the minimum, with the other three bytes being either `\x00` or `\xff`.  Known to be used by Kingston SSD's, and I believe also by SanDisk and Crucial SSD's.
  - The low byte is the current temperature, the third lowest is the minimum, and the fourth lowest is the maximum.  The second lowest byte is either `\x00` or `\xff`, and the high two bytes are `\x00`.  Known to be used by Maxtor, Samsung, Seagate, and Toshiba drives.
  - The low byte is the current temperature, the second lowest is the minimum, and the third lowest is the maximum, with the three highest bytes being `\x00`.  Known to be used by some (mostly older) Western Digital drives.
  - The low byte is the current temperature, the third lowest is the minimum, and the fourth lowest is the maximum.  The second lowest is `\x00` or `\xff`, and the high two bytes are an unsigned 16-bit integer indicating how many times the drive has been above the rated operating temperature.

**Comment by ScrumpyJack** [comment] 2018-10-25 13:12
How close are we to having this in a release?

**Comment by l2isbad** [comment] 2018-10-25 13:37
It seems we need to rewrite the whole module. 
For the SATA i have [this](https://github.com/netdata/netdata/issues/4285#issuecomment-425654443)
Families: 

- performance
- spin
- wear
- power
- errors
- temperature

It's not clear to me how to handle SCSI devices.

Additional families at the end of the list? prepend scsi to family,  like

- scsi errors //  (read, write, verify)
- scsi temperature

**Comment by Ferroin** [comment] 2018-10-25 13:50
@l2isbad IMO, it makes more sense to just group the SCSI attributes into the same categories they would be in if it were an ATA device.  We treat SCSI devices the same as ATA devices everywhere else, so it seem odd to me to differentiate here given that the attributes can be trivially grouped into the existing families.

Also, for now, I do think just tracking temperature and read/write/verify errors for SCSI devices is probably fine.  There are some other attributes that it might make sense to track (for example storage utilization for devices that do thin-provisioning in firmware and expose it), but they kind of require hardware to test against, which I'm pretty sure we don't have access to.

**Comment by l2isbad** [comment] 2018-10-25 14:04
> it makes more sense to just group the SCSI attributes into the same categories they would be in if it were an ATA device

Then we need to add ATA/SCSI to every chart title or it will be a mess.

Let's take `temperature` for example

we have

- Airflow Temperature Celsius (ATA)
- Temperature Celsius (ATA)
- Temperature (SCSI)

**Comment by l2isbad** [comment] 2018-10-25 14:16
so we have 3 type of charts

- specific to ATA
- specific to SCSI
- common to both (SCSI temperature and ATA 194 Temperature should be in the same chart)

**Comment by Ferroin** [comment] 2018-10-25 14:34
> so we have 3 type of charts
>
> * specific to ATA
> * specific to SCSI
> * common to both (SCSI temperature and ATA 194 Temperature should be in the same chart)

OK, let me try this from a different angle: _Why_ do we need different charts for SCSI and ATA attributes given that no storage device can provide both simultaneously?  The only configuration that comes close to causing issues with just sharing charts is SATA devices connected to a SAS HBA, but those will still provide ATA SMART attributes only (because the HBA is not involved at all in the data collection except as a transport component).

**Comment by l2isbad** [comment] 2018-10-25 14:41
> Why do we need different charts for SCSI and ATA 

How else?.
ATA has `Soft Read Error Rate` chart.
SCSI has `Read, Write, Verify Error`  charts (or `Uncorrectable, Corrected` depends on grouping).

We can't mix them, right?

All these charts under the `errors` family.

But both scsi and ata has on common chart - temperature.

**Comment by l2isbad** [comment] 2018-10-25 14:44
Or `Soft Read Error Rate` is the same as `read-total-unc-errors` ?

**Comment by Ferroin** [comment] 2018-10-25 14:45
Ah, OK, that's what I was misunderstanding.  I forgot that the module does one chart per attribute. (which still seems odd to me, but that's kind of irrelevant since it's what people are used to at this point).  Sorry about the confusion.

**Comment by l2isbad** [comment] 2018-10-25 14:48
@Ferroin can you provie a match table for SCSI - ATA attrs? 

ATA 194 Temperature Celsius - SCSI temperature

What else?

**Comment by l2isbad** [comment] 2018-10-25 14:50
> I forgot that the module does one chart per attribute

dimensions are disk names

Can you suggest a better approach?

**Comment by Ferroin** [comment] 2018-10-25 15:01
> @Ferroin can you provie a match table for SCSI - ATA attrs?
>
> ATA 194 Temperature Celsius - SCSI temperature
>
> What else?

As far as I know, there's nothing that maps properly except temperature.  At least, none of the attributes reported by the device that @ScrumpyJack was kind enough to provide an attribute dump from appear to.

> dimensions are disk names
>
> Can you suggest a better approach?

The intuitive approach for me is to have one set of charts per disk/device, with each chart being a particular unit, and the dimension names being the attribute names.  I wouldn't necessarily say that's any better than what we currently have though, both approaches have their own issues relating to scaling of the charts, and both produce a potentially very large number of charts.  Given this, I think we should just keep the approach being used currently (people are used to it).

The only tricky point is the temperature chart.  I do think it should be shared, but how to choose what to use for the ATA devices gets tricky.  I'm of the opinion that we should probably use attribute 194 preferentially to attribute 190 and only expose one of them, as that's consistent with how tools like `hddtemp` work.  It would also be really neat to support showing min/max temperature values for ATA devices by parsing the raw values, but that may make the chart really cluttered.

**Comment by l2isbad** [comment] 2018-10-25 15:08
> The intuitive approach for me is to have one set of charts per disk/device, with each chart being a particular unit, and the dimension names being the attribute names. 

Agree. It would simplify all.

The reason why it wasn't implemented in that way  is long disk names (KINGSTON_SHFS37A120G-50026B7266003D93), we can't use them as families.

**Comment by l2isbad** [comment] 2018-10-25 15:13
Second reason is that it's hard to find the chart you need, when there is a lot of charts and all of them under the same family

**Comment by l2isbad** [comment] 2018-10-25 15:16
Titles are hard to read imo. (small font...)

**Comment by l2isbad** [comment] 2018-10-25 15:20
@gmosx What do you think about chart titles? is it only me or not? It's hard to scroll and read titles. They are not stand out, font is small.

**Comment by l2isbad** [comment] 2018-10-25 15:28
> Given this, I think we should just keep the approach being used currently (people are used to it).

@Ferroin  Not a big problem actually :smile: We have already changed approach (each attr family => group of attrs family).

If we find the way how to  `to have one set of charts per disk/device`, it will be cool!

So the question is - how to handle long disk names, we need them for families...

**Comment by Ferroin** [comment] 2018-10-25 15:40
> If we find the way how to to have one set of charts per disk/device, it will be cool!

Should be as simple as just defining the charts differently.  Even if we do that though, we should let people choose that or the chart-per-attribute approach, as having a set per disk/device will translate in some cases to an absolutely insane number of charts (if I'm doing the math correctly, that would potentially be at least a dozen charts per device for most ATA devices).

> So the question is - how to handle long disk names, we need them for families...

Regarding chart titles, it would be nice if they were a bit bigger.  A different choice of font would probably help too.  I've actually been running the dashboard with some minor CSS changes to override things to use a monospace font (I'm using Droid Sans Mono Dotted, which is my preferred font for almost everything these days) and the whole thing (not just chart families, but dimension names and even the chart descriptions) is much easier to read.

As far as disk names for chart names, we probably have to get a bit more involved than just borrowing the smartd names directly.  My thought is to provide a way for the user to remap the disk names as they see fit, have a quick switch to display just the serial number (the part after the `-`, this is likely to be useful for people who actually track disk serial numbers, which is not unusual in enterprise scenarios (or among crazy people like myself)), and possibly a script to generate a mapping from the smartd device names to paths in `/dev`.  Ideally, if we do that, we would also include the original smartd name in any alerts.

**Comment by ScrumpyJack** [comment] 2018-10-25 15:49
On the chart per device or chart per attribute question, it's unclear what you've chosen.
Are you suggesting a default that can be changed?

**Comment by l2isbad** [comment] 2018-10-25 15:53
Ok, good points @Ferroin better to stay with _devices as dimensions_ approach.

**Comment by l2isbad** [comment] 2018-10-25 15:58
> Chart per device would mean potentially thousands of charts, and charts per attribute would mean unreadable charts

`thousands of charts` is no go, so we chose potentially `unreadable charts`

**Comment by ScrumpyJack** [comment] 2018-10-25 16:05
charts per attribute, that's cool. we can narrow that down by device in grafana or something :)

**Comment by l2isbad** [comment] 2018-10-30 11:34
wip

**Comment by l2isbad** [comment] 2018-10-30 14:44
@Ferroin 
`190;64;622592036;	194;36;3435973840`
You suggested to use raw value. How to calc temperature then? :smile:

**Comment by Ferroin** [comment] 2018-10-30 15:14
See https://github.com/netdata/netdata/issues/4285#issuecomment-428556760 or check the `ata_format_attr_raw_value()` function in [atacmds.cpp from the smartmontools sources](https://github.com/smartmontools/smartmontools/blob/master/smartmontools/atacmds.cpp) (its around line 1922).  I"m not sure whether the data is supposed to be LSB or MSB in either case.

You might also want to double check if `smartctl` actually parses the raw values for that device.  Just having it list the attributes should be enough.  If it does parse them, the value in the `RAW_VALUE` column of the output for that attribute will look something like this: `35 (Min/Max 17/44)`

IMO, if we can parse the raw values we should (we give the user more info this way), but if not we should fall back to just exposing the normalized value (and don't forget, the normalized value is supposed to be 100 _minus_ the actual temperature).

**Comment by gmosx** [comment] 2018-10-30 20:54
> @gmosx What do you think about chart titles? is it only me or not? It's hard to scroll and read titles. They are not stand out, font is small.

Yes I agree, the dashboard needs aesthetic improvements. I am entertaining a hybrid approach: incremental improvements in the current dashboard, and an experimental 'dashboard2' sporting a more aggressive redesign. Nothing is set in stone though. Will have more visibility by the time of our meeting.

**Comment by l2isbad** [comment] 2018-10-31 01:17
> and don't forget, the normalized value is supposed to be 100 minus the actual temperature

Not sure about that.
Take a look

hddtemp reports 35
```
[lgz ~]sudo hddtemp /dev/sda
/dev/sda: KINGSTON SHFS37A120G: 35°C
```

smartd log **normalized value is 35**
```
[lgz ~]tail -n 1 /var/log/smartd/KINGSTON_SHFS37A120G-50026B7266003D93.ata.csv | grep -E -o "194(;[0-9]+){2}"
194;35;42952491043
```

smartctl 
```
[lgz ~]sudo smartctl -a /dev/sda | grep ^194
194 Temperature_Celsius     0x0022   035   043   000    Old_age   Always       -       35 (Min/Max 10/43)
```

**Comment by l2isbad** [comment] 2018-10-31 01:44
Power On Hours

[lgz ~]sudo smartctl -a /dev/sda | grep Power_On
  9 Power_On_Hours          0x0032   091   091   000    Old_age   Always       -       8692 (156 14 0)
[lgz ~]sudo smartctl -a /dev/sdb | grep Power_On
  9 Power_On_Hours          0x0032   085   085   000    Old_age   Always       -       13617


`9;91;237786569384436`

`237786569384436` should be decoded too

**Comment by l2isbad** [comment] 2018-10-31 02:40
> To be honest i have no idea how decode 42952491043 to current/min/max. (if this is even possible)
> 194 Temperature_Celsius     0x0022   034   043   000    Old_age   Always       -       34 (Min/Max 10/43)


figured out

```
>>> 42952491042 & 0xFF
34
>>> (42952491042 & 0xFF0000) >> 16
43
>>> (42952491042 & 0xFF00000000) >> 32
10
```

**Comment by l2isbad** [comment] 2018-10-31 12:57
@Ferroin great. but... have you checked if your code works? It has syntax errors, index errors, etc :smile:

**Comment by Ferroin** [comment] 2018-10-31 13:01
@l2isbad  I was a bit more focused on getting the logic translated correctly than making sure it ran.  Give me a couple of minutes and I'll clean it up.

**Comment by Ferroin** [comment] 2018-10-31 13:06
Updated it to fix the errors.

**Comment by l2isbad** [comment] 2018-10-31 13:09
34359738404 contains only current temperature

```
In [14]: parse_temp(34359738404)

In [15]: 34359738404 & 0xFF
Out[15]: 36
```

**Comment by Ferroin** [comment] 2018-10-31 13:11
It looks like that's a case that isn't handled either by the smartmontools code I was looking at.  I may also have just been looking in the wrong place though.

**Comment by l2isbad** [comment] 2018-10-31 13:12
`smartctl` shows `36 (0 8 0 0 0)`

**Comment by Ferroin** [comment] 2018-10-31 13:16
OK, I think I see what's up then.  I forgot to look at the code further down that's responsible for printing the value out.  This case gets handled there instead of in the other decoding logic.

**Comment by l2isbad** [comment] 2018-11-06 13:42
@ScrumpyJack merged the fix

**Closed** 2018-11-06 13:42 UTC
Labels: module/python, question

**Comment by ScrumpyJack** [comment] 2018-11-06 15:01
very very cool.
building it now
