### ISSUE TITLE
[Bug]: Keeps sending Emails notification even with SEND_EMAIL="NO"

### ISSUE THREAD

**Issue by gusarg81** [netdata/netdata#12096] opened 2022-02-07 12:20 UTC
### Bug description

Since last week, all my NetData agents suddenly are sending email notifications when I never enabled this.
I double check SEND_EMAIL="NO" and restarted netdata agent service (all running in Ubuntu 20.04).

In NetData cloud emails notifications are disabled as well.

This was working correctly before one week aprox.

### Expected behavior

To not send email notifications when SEND_EMAIL="NO" is set.

### Steps to reproduce

There is no step really, just set SEND_EMAIL="NO" and test...

### Installation method

kickstart.sh

### System info

```shell
Linux - Ubuntu 20.04
```

### Netdata build info

```shell
From one NetData agent (which is the one that is sending emails):

Version: netdata v1.33.0-21-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by MrZammler** [comment] 2022-02-07 12:32
Hi @gusarg81 !

So, to try to reproduce this, you have in `/etc/netdata/` the `health_alarm_notify.conf` which has `SEND_EMAIL="NO"`, but still it produces email alerts?

What kind of email alerts are you getting, are they related to alerts? Can you please forward one to manolis at netdata.cloud ?

Thank you!

**Comment by ilyam8** [comment] 2022-02-07 12:36
@gusarg81 let's see

> grep -i email /etc/netdata/health_alarm_notify.conf | grep -v "^#

**Comment by gusarg81** [comment] 2022-02-07 12:36
Yes, like I said I receive alerts even when SEND_EMAIL is set to NO. I've configured all netdata agents to send notifications only by Telegram, not by email.

Suddenly, and I don't know why, I've started to receive email alerts since one week ago aprox. (and those agents are installed like half year ago).

**Comment by gusarg81** [comment] 2022-02-07 12:37
grep -i email /etc/netdata/health_alarm_notify.conf | grep -v "^#"
EMAIL_SENDER=""
SEND_EMAIL="NO"
DEFAULT_RECIPIENT_EMAIL="root"
role_recipients_email[sysadmin]="${DEFAULT_RECIPIENT_EMAIL}"
role_recipients_email[domainadmin]="${DEFAULT_RECIPIENT_EMAIL}"
role_recipients_email[dba]="${DEFAULT_RECIPIENT_EMAIL}"
role_recipients_email[webmaster]="${DEFAULT_RECIPIENT_EMAIL}"
role_recipients_email[proxyadmin]="${DEFAULT_RECIPIENT_EMAIL}"
role_recipients_email[sitemgr]="${DEFAULT_RECIPIENT_EMAIL}"

**Comment by ilyam8** [comment] 2022-02-07 12:39
Let's execute `/usr/libexec/netdata/plugins.d/alarm-notify.sh` as `netdata` user.

**Comment by gusarg81** [comment] 2022-02-07 14:56
sudo -u netdata /usr/libexec/netdata/plugins.d/alarm-test.sh

# SENDING TEST WARNING ALARM TO ROLE: sysadmin
2022-02-07 11:55:48: alarm-notify.sh: INFO: sent telegram notification for: amatista test.chart.test_alarm is WARNING to '609992947'
# OK

# SENDING TEST CRITICAL ALARM TO ROLE: sysadmin
2022-02-07 11:55:49: alarm-notify.sh: INFO: sent telegram notification for: amatista test.chart.test_alarm is CRITICAL to '609992947'
# OK

# SENDING TEST CLEAR ALARM TO ROLE: sysadmin
2022-02-07 11:55:50: alarm-notify.sh: INFO: sent telegram notification for: amatista test.chart.test_alarm is CLEAR to '609992947'
# OK

**Comment by gusarg81** [comment] 2022-02-07 14:58
An example of Alert received by email in one of the netdata agent.

![test](https://user-images.githubusercontent.com/6312430/152812589-a94b7c66-1f0f-463a-8c7c-d907c45c657b.png)

**Comment by MrZammler** [comment] 2022-02-07 15:00
@gusarg81 Thanks! Does the email sender contain cloud or you email? Trying to understand if the emails come from the agent or the cloud.

**Comment by MrZammler** [comment] 2022-02-07 15:12
All right, thanks! We will check with the cloud team to see what's going on there, will let you know!

**Comment by ilyam8** [comment] 2022-02-07 15:13
Could be this issue https://github.com/netdata/netdata-cloud/issues/255

**Comment by gusarg81** [comment] 2022-02-07 15:16
> All right, thanks! We will check with the cloud team to see what's going on there, will let you know!

Thanks a lot!

**Comment by ilyam8** [comment] 2022-02-08 13:03
Closing as duplicate of https://github.com/netdata/netdata-cloud/issues/255. If fixing 255 won't work for you @gusarg81 we will reopen this issue.

**Closed by ilyam8** 2022-02-08 13:04 UTC
Labels: bug, area/health, needs triage
