### ISSUE TITLE
says unknown distro for OL distros

### ISSUE THREAD

**Issue by osde8info** [netdata/netdata#8623] opened 2020-04-06 20:09 UTC
##### Bug report summary

Unknown distribution ID: ol

/etc/os-release information:
NAME            : Oracle Linux Server
VERSION         : 7.7
ID              : ol
ID_LIKE         : fedora
VERSION_ID      : 7.7

Unknown distribution ID: ol

/etc/os-release information:
NAME            : Oracle Linux Server
VERSION         : 8.1
ID              : ol
ID_LIKE         : fedora
VERSION_ID      : 8.1

##### OS / Environment

```
oracle linux
```

##### Component Name

installer 

##### Steps To Reproduce

1. ...install
2. ...

##### Expected behavior

SHOULD recognise OL distros

see also https://github.com/netdata/netdata/issues/8604

**Comment by prologic** [comment] 2020-04-07 11:55
Looks like we'll be able to easily verify, test, fix and validate support for Oracle Linux in our CI. There is an [official docker image](https://hub.docker.com/_/oraclelinux/) for OL.

**Comment by prologic** [comment] 2020-04-07 11:56
@osde8info meanwhile if you're in a a hurry and until we get support for Oracle Linux (_either with source-based builds or native packages_); please try installing with the static `kickstart_static64.sh` installer.

**Comment by ilyam8** [comment] 2020-04-07 12:03
i guess it will be problematic, i recall you need a subscription (free/developer) to to be able to use it.

**Comment by prologic** [comment] 2020-04-07 12:06
> i guess it will be problematic, i recall you need a subscription (free/developer) to to be able to use it.

Not according to what I just read. So 🤞

**Comment by ilyam8** [comment] 2020-04-07 12:08
> Not according to what I just read

i used it working on [oracledb collector](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/oracledb).

**Comment by ilyam8** [comment] 2020-04-07 12:09
There were no way to update/install something w/o activating the license, it was something like that.

**Comment by prologic** [comment] 2020-04-07 12:15
Hmm 🤔I'll look into it tomorrow. You're probably right in which case this might be a lot harder than its worth :/

**Comment by Ferroin** [comment] 2020-04-07 12:34
Indeed, Oracle is somewhat draconian with their licensing policies (for example, you _have_ to be part of a company before they'll even consider giving you a free developer account), and tends to get really aggressive if they think you're doing something that their licensing terms would allow them to gouge you for money for doing.

_If_ we end up getting things legitimately set up with them though, we could also in theory work on proper support for Solaris, they have similar 'free for deveopment/testing/demo usage' licensing terms for Solaris 11.

**Comment by prologic** [comment] 2020-04-07 12:42
I'll explore this over the next coming days.

**Comment by osde8info** [comment] 2020-04-08 17:36
FYI
ibm red hat have FREE containers available at http://registry.access.redhat.com/ubi8/ubi:latest
oraclelinux have a FREE container at hub.docker.com

**Comment by osde8info** [comment] 2020-04-09 17:58
kickstart_static64.sh does work for oracle linux 8 (but netdata still not listed as service in firewall-config)

**Comment by prologic** [comment] 2020-04-21 04:54
This is kind of a duplicate of #8602 and the solution is the same as my last comment on #8602

**Closed by prologic** 2020-04-21 04:54 UTC
Labels: bug, priority/low
