### ISSUE TITLE
[default install] mktemp: failed to create directory via template ‘/opt/netdata-kickstart-XXXXXX’: Permission denied

### ISSUE THREAD

**Issue by barrio** [netdata/netdata#5360] opened 2019-02-10 19:04 UTC
vagrant@ubuntu-bionic:~$ bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version: 
mktemp: failed to create directory via template ‘/opt/netdata-kickstart-XXXXXX’: Permission denied
 --- Downloading script to detect required packages... --- 
/dev/fd/63: line 119: /install-required-packages.sh: Permission denied
 ABORTED  Cannot download https://raw.githubusercontent.com/netdata/netdata-demo-site/master/install-required-packages.sh

I tried this first on my KVM VPS running ubuntu bionic and reproduced this error locally in a VM.

According to the docs expected behaviour would be to be prompted for sudo password since /opt is not writable for normal users.

**Comment by cakrit** [comment] 2019-02-11 10:50
We will make `kickstart.sh` default to using `$(pwd)` if `/tmp` has the `noexec` flag.

**Comment by Ferroin** [comment] 2020-03-04 22:51
We cannot reproduce this with a current version of Netdata. It's very likely that this has been fixed in one of the changes to the install scripts.

If this is still an issue, feel free to comment here.

**Closed by Ferroin** 2020-03-04 22:51 UTC
Labels: area/packaging, bug
