### ISSUE TITLE
JVM metrics collector very much desired

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#9210] opened 2020-05-28 16:57 UTC
Thought we already had this for some reason. I recently switched from Spring boot apps to a native Java servlet based server mainly for low latency and performance reasons. When looking to capture JVM metrics via JMX or Jolokia I came across the fact that there is nothing at the moment that can be used out of the box. 

@simonnagl had something going on in this area and it doesn't look like the implementation was merged to the effect. JVM metrics is very common in server implementations including tools like Cassandra, Zookeeper etc can simply be wired as long as a JMX agent exposes the metrics which typically is a simple startup configuration to the process and hence supporting JMX can enable insight in to so many of these JVM/Java based applications.

Looking to see if @cakrit has an opinion on this and if I missed something entirely. I know Chris went through a long exercise collecting information around plugins sometime back to see what can be onboarded for Netdata as inputs and there was a considerable amount of work done there by various contributors couple of years back but I am starting to think these plugins unless they become first class citizens of Netdata it will be tough to evolve them and Netdata usage can become a little fragmented. I love the rich metrics Netdata provides when it comes to host, system, docker etc but then when it comes to supporting other technologies or ways to ingest metrics from other sources there are very limited choices and most times one has to find workarounds such as StatsD etc. which can be become a configuration nightmore

As Netdata is inching towards the APM space I am starting to wonder how these challenges will be addressed. Again this is my limited view of Netdata and its usage, it possible others may not feel the same.

**Comment by cakrit** [comment] 2020-06-08 10:53
Strategically, we intend to move as much as possible towards [OpenTelemetry](https://opentelemetry.io). Issues #7897 and #8613 are in the direction of generically and easily ingesting data from Prometheus exporters. 

Would something like the [Prometheus JMX exporter](https://github.com/prometheus/jmx_exporter) cover the needs for this? I understand it's not out of the box of course...

**Comment by gamefundas** [comment] 2020-09-08 02:16
Adding agents to Java applications do have performance implications no matter how small it is still affects it. OpenTelemetry, Prometheus JMX Exporter all require an agent to be wired to the program startup. Since netdata already has its agent running on the host wouldn't it make sense for it talk to the application via a local JMX port. Alternately jolokia endpoints can be queried if HTTP is preferred. 

With OpenTelemetry is the idea for Netdata agent to expose itself as a OpenTelemetry collector and other modules will have the ability to publish metrics as needed, something very similar to StatsD?

**Comment by dim08** [comment] 2020-09-16 09:51
hi @gamefundas this is Dimitris from product team. We appreciate your contribution, and we would like to ask you if you will be willing to have a get to know you meeting with our product team. If this is the case could you please share some contact details?

**Comment by OneCricketeer** [comment] 2021-01-14 17:48
Duplicate? #364

**Comment by ilyam8** [comment] 2021-07-27 15:23
Closing as duplicate of #364

**Closed by ilyam8** 2021-07-27 15:23 UTC
Labels: feature request, needs triage
