### ISSUE TITLE
Missing network graph for some cgroup containers

### ISSUE THREAD

**Issue by fayak** [netdata/netdata#10260] opened 2020-11-19 14:00 UTC
##### Bug report summary

I'm monitoring some Docker containers using Netdata. Most of them have the network bandwidth graphs (`Bandwidth (cgroup_engage_utils_instance1.net_eth0)` and `Packets (cgroup_engage_utils_instance1.net_packets_eth0)`), but some don't. I don't know why the graphs are missing, since the containers are using the network.

Using `docker inspect` and by looking at files in /sys/class, I found the veth on which my container improperly monitored is attached, and used `tcpdump -n -i vethbfa5874` for 5s to see if there's network usage:
```
1623 packets captured
1723 packets received by filter
80 packets dropped by kernel
```

##### OS / Environment

```
$ uname -a
Linux node01 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch
```

##### Netdata version

 `netdata v1.26.0 (installed via apt)`

##### Component Name

I reckon this graph is generated by the `proc` collector, but is might also be `cgroup`, not sure

##### Steps To Reproduce

Not sure how to reproduce it, I simply installed netdata on a node running > 30 docker containers

##### Expected behavior

Have the network bandwidth usage for all containers

Please let me know if you need more information !

**Comment by ilyam8** [comment] 2020-11-19 14:14
Hi @fayak 

Could it be you that are using [host network driver](https://docs.docker.com/network/network-tutorial-host/) for those containers?

**Comment by ilyam8** [comment] 2020-11-19 14:16
Are there any `veth*` interfaces in the `Network Interfaces` dashboard section?

**Comment by fayak** [comment] 2020-11-19 14:39
Hey @ilyam8 ,

docker inspect reports `"NetworkMode": "bridge",` and 
```
 "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "095247035aa37d1286e5660ae7c0013fc466df4d4199deea7ec26f5213cef3ee",
                    "EndpointID": "4bf614bd1eafe10d734127689910bbaad9178958e34f03f7531a8d430bcfb97b",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:04",
                    "DriverOpts": null
                }
            }
```

for this container.

The `Network Interfaces` dashboard has indeed 2 `veth*` interfaces, including `vethbfa5874`.
The host has 35 veth interfaces (`ip a | grep veth | wc -l`) and 35 docker containers (`docker ps | wc -l` - 1).

I don't know why this veth interface shows up on the Network Interfaces section and not on the cgroup using it though, but it definitely seems like it's linked

**Comment by ilyam8** [comment] 2020-11-19 14:48
> docker inspect reports "NetworkMode": "bridge"

Good, because if it wasn't bridge then lack of network iface metrics is expected.

> The Network Interfaces dashboard has indeed 2 veth* interfaces

I guess you have 2 containers w/o `net eth0`?

**Comment by fayak** [comment] 2020-11-19 14:53
> I guess you have 2 containers w/o net eth0?

Exactly :smile:

**Comment by ilyam8** [comment] 2020-11-19 15:05
Did you try `netdata.service` restart?

**Comment by fayak** [comment] 2020-11-19 15:54
Just did, and it fixed it. Do you have any idea how to prevent this from happening again ?

**Comment by ilyam8** [comment] 2020-11-19 16:02
I think it should happen pretty rare.

@vlvkobal any ideas why/when is it happening?

**Comment by vlvkobal** [comment] 2020-11-19 16:43
No ideas so far.

We are waiting before renaming cgrops and network interfaces because Docker has a lag (#5557). @fayak, have you changed `check for new cgroups every`?

Next time you face the issue, please `grep cgroup error.log` and look at messages with `cgroup-network` and around them.

**Comment by fayak** [comment] 2020-11-19 17:10
No I did not, cgroups plugin configuration is the default one.

Yes I will, but I don't know when it will reproduce, if it will

**Comment by ilyam8** [comment] 2020-11-19 17:14
> but I don't know when it will reproduce, if it will

Since it happens occasionally and rare and we don't know how to reproduce it, i think it is ok to close this issue for now.

@fayak if there are any updates we will reopen the issue.

**Comment by fayak** [comment] 2020-12-14 10:31
Ok so this bug is still happening, and is frequent. I now have 7 containers with their network monitoring "detached" for a single given node.

If I grep the name of one of them, I have:
```
$ grep api-gateway_instance2 error.log*
error.log.4:2020-12-10 22:33:07: netdata INFO  : MAIN : Deleting chart 'cgroup_api-gateway_instance2.throttle_serviced_ops' ('cgroup_api_gateway_instance2.throttle_serviced_ops') from disk...
error.log.4:2020-12-10 22:33:07: netdata INFO  : MAIN : Deleting chart 'cgroup_api-gateway_instance2.throttle_io' ('cgroup_api_gateway_instance2.throttle_io') from disk...
error.log.4:2020-12-10 22:33:22: cgroup-name.sh: INFO: docker container 'addbe3c673d58d71dc044f9504d779a11f55f96cfb4d5dcf05e407cec80ed78f' is named 'api-gateway_instance2'
error.log.4:2020-12-10 22:33:22: cgroup-name.sh: INFO: cgroup 'docker_addbe3c673d58d71dc044f9504d779a11f55f96cfb4d5dcf05e407cec80ed78f' is called 'api-gateway_instance2'
error.log.4:2020-12-10 22:39:56: cgroup-name.sh: INFO: docker container 'addbe3c673d58d71dc044f9504d779a11f55f96cfb4d5dcf05e407cec80ed78f' is named 'api-gateway_instance2'
error.log.4:2020-12-10 22:39:56: cgroup-name.sh: INFO: cgroup 'docker_addbe3c673d58d71dc044f9504d779a11f55f96cfb4d5dcf05e407cec80ed78f' is called 'api-gateway_instance2'
error.log.1:2020-12-13 22:01:20: netdata INFO  : PLUGIN[cgroups] : CGROUP: unregistered network interface rename for 'veth3f3c8b1' as 'eth0' under 'api-gateway_instance2'
error.log.1:2020-12-13 22:02:39: cgroup-name.sh: INFO: docker container 'e78b6006342ec5acdfe4a472a39b30cd5f413d689e1110b7fdf700adc8d54f35' is named 'api-gateway_instance2'
error.log.1:2020-12-13 22:02:39: cgroup-name.sh: INFO: cgroup 'docker_e78b6006342ec5acdfe4a472a39b30cd5f413d689e1110b7fdf700adc8d54f35' is called 'api-gateway_instance2'
```

```
$ grep -r veth3f3c8b1
error.log.4:2020-12-10 22:33:07: netdata INFO  : MAIN : Deleting chart 'net_packets.veth3f3c8b1' ('net_packets.veth3f3c8b1') from disk...
error.log.4:2020-12-10 22:33:07: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net_packets.veth3f3c8b1' (errno 2, No such file or directory)
error.log.4:2020-12-10 22:33:07: netdata INFO  : MAIN : Deleting chart 'net.veth3f3c8b1' ('net.veth3f3c8b1') from disk...
error.log.4:2020-12-10 22:33:07: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net.veth3f3c8b1' (errno 2, No such file or directory)
error.log.4:2020-12-10 22:35:15: netdata INFO  : MAIN : Deleting chart 'net_packets.veth3f3c8b1' ('net_packets.veth3f3c8b1') from disk...
error.log.4:2020-12-10 22:35:15: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net_packets.veth3f3c8b1' (errno 2, No such file or directory)
error.log.4:2020-12-10 22:35:15: netdata INFO  : MAIN : Deleting chart 'net.veth3f3c8b1' ('net.veth3f3c8b1') from disk...
error.log.4:2020-12-10 22:35:15: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net.veth3f3c8b1' (errno 2, No such file or directory)
error.log.4:2020-12-10 22:37:17: netdata INFO  : MAIN : Deleting chart 'net_packets.veth3f3c8b1' ('net_packets.veth3f3c8b1') from disk...
error.log.4:2020-12-10 22:37:17: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net_packets.veth3f3c8b1' (errno 2, No such file or directory)
error.log.4:2020-12-10 22:37:17: netdata INFO  : MAIN : Deleting chart 'net.veth3f3c8b1' ('net.veth3f3c8b1') from disk...
error.log.4:2020-12-10 22:37:17: netdata ERROR : MAIN : Cannot read left-over chart directory to be deleted '/var/cache/netdata/net.veth3f3c8b1' (errno 2, No such file or directory)
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting chart 'net_packets.veth3f3c8b1' ('net_packets.veth3f3c8b1') from disk...
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting chart header file '/var/cache/netdata/net_packets.veth3f3c8b1/main.db'.
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting dimension file '/var/cache/netdata/net_packets.veth3f3c8b1/received.db'.
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting dimension file '/var/cache/netdata/net_packets.veth3f3c8b1/sent.db'.
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting dimension file '/var/cache/netdata/net_packets.veth3f3c8b1/multicast.db'.
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting empty directory '/var/cache/netdata/net_packets.veth3f3c8b1'
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting chart 'net.veth3f3c8b1' ('net.veth3f3c8b1') from disk...
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting chart header file '/var/cache/netdata/net.veth3f3c8b1/main.db'.
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting dimension file '/var/cache/netdata/net.veth3f3c8b1/received.db'.
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting dimension file '/var/cache/netdata/net.veth3f3c8b1/sent.db'.
error.log.4:2020-12-10 22:39:31: netdata INFO  : MAIN : Deleting empty directory '/var/cache/netdata/net.veth3f3c8b1'
error.log.1:2020-12-13 22:01:20: netdata INFO  : PLUGIN[cgroups] : CGROUP: unregistered network interface rename for 'veth3f3c8b1' as 'eth0' under 'api-gateway_instance2'
```

However, I don't have the `veth3f3c8b1` chart under `Network interfaces`. Looking at the current container's veth
```
$ docker exec -it api-gateway_instance2 bash -c 'cat /sys/class/net/eth*/iflink'
288
$ grep -l 288 /sys/class/net/veth*/ifindex
/sys/class/net/vethcd4d326/ifindex
```
I do have `vethcd4d326` under `Network interfaces`. Grepping `vethcd4d326` in Netdata's log gives no result though.

Please let me know if I can do anything else to help

**Comment by vlvkobal** [comment] 2020-12-14 20:44
Please set `debug flags = 0x0000000000100000` and look at `debug.log` for messages like
```
2020-12-14 22:37:21: netdata DEBUG : PLUGIN[cgroups] : (1310@collectors:cgroup_get_char): looking for the name of cgroup '/docker/b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5' with chart id 'docker_b7621f864fa44ba4914
53de45558c34f71eb893007ba404d4647e8250cbb7da5' and title 'docker/b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5'
2020-12-14 22:37:21: netdata DEBUG : PLUGIN[cgroups] : (1317@collectors:cgroup_get_char): executing command "exec /usr/libexec/netdata/plugins.d/cgroup-name.sh 'docker_b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5'" fo
r cgroup 'docker_b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5'
2020-12-14 22:37:21: netdata DEBUG : PLUGIN[cgroups] : (1328@collectors:cgroup_get_char): cgroup 'docker_b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5' should be renamed to 'mongo
'
2020-12-14 22:37:21: netdata DEBUG : PLUGIN[cgroups] : (1400@collectors:cgroup_add     ): cgroup '/docker/b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5' renamed to 'mongo' (title: 'mongo')
2020-12-14 22:37:21: netdata DEBUG : PLUGIN[cgroups] : (1442@collectors:cgroup_add     ): cgroup '/docker/b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5' with chart id 'mongo' (title: 'mongo') does not match systemd ser
vices groups
2020-12-14 22:37:21: netdata DEBUG : PLUGIN[cgroups] : (1180@collectors:read_cgroup_net): looking for the network interfaces of cgroup '/docker/b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5' with chart id 'mongo' and title 'mongo'
2020-12-14 22:37:21: netdata DEBUG : PLUGIN[cgroups] : (1192@collectors:read_cgroup_net): executing command 'exec /usr/libexec/netdata/plugins.d/cgroup-network --cgroup '/sys/fs/cgroup/cpu,cpuacct/docker/b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5'' for cgroup '/docker/b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5'
2020-12-14 22:37:21: netdata DEBUG : PLUGIN[cgroups] : (1482@collectors:cgroup_add     ): ADDED CGROUP: '/docker/b7621f864fa44ba491453de45558c34f71eb893007ba404d4647e8250cbb7da5' with chart id 'mongo' and title 'mongo' as enabled (default was enabled)

```

**Comment by fayak** [comment] 2020-12-16 09:05
Hello @vlvkobal ,

I changed `netdata.conf` 2 days ago to put the following:
```
[global]
        run as user = netdata
        web files owner = root
        web files group = netdata

        [...]

        # timezone = UTC
        debug flags = 0x0000000000100000
        # debug log = none
        access log = none
        debug log = /var/log/netdata/debug.log
        # error log = /var/log/netdata/error.log
        # access log = /var/log/netdata/access.log
        
        [...]
```

`systemctl restart netdata` to apply the changes, but unfortunately there's nothing in `debug.log, and the problem occurred again. Did I missed something ?

**Comment by vlvkobal** [comment] 2020-12-16 09:34
Sorry, I forgot to mention. You should reinstall Netdata using `sudo CFLAGS="-DNETDATA_INTERNAL_CHECKS=1" ./netdata-installer.sh`.

**Comment by fayak** [comment] 2020-12-16 09:53
This require to rebuild netdata, which I can't do on the production server where I encounter this issue (It's installed by apt. I found a staging server that had this issue once, so I'll try there, but I don't know if it'll reproduce again, and how much time I'll have to wait for it to reproduce again, I'll let you know

**Comment by ilyam8** [comment] 2020-12-16 09:59
> This require to rebuild netdata

simple way is to build a docker container with `CFLAGS="-DNETDATA_INTERNAL_CHECKS=1"` and install it

**Comment by ilyam8** [comment] 2021-09-01 12:40
Closing due to no response. @fayak if you still experiencing the problem with the current stable version (v1.31.0), please let us know and we will continue the investigation (keep in mind that we still will need you to compile Netdata with `NETDATA_INTERNAL_CHECKS`).

**Closed by ilyam8** 2021-09-01 12:40 UTC
Labels: bug, area/collectors, Cannot reproduce, data-collection-mteam
