### ISSUE TITLE
Provide Ubuntu PPA

### ISSUE THREAD

**Issue by mgcrea** [netdata/netdata#69] opened 2016-03-30 14:04 UTC
Would be great to have a PPA for an easier install+upgrade workflow.

**Comment by ktsaou** [comment] 2016-03-30 17:59
You are right.
No time for this currently though.
You can of course set this up and I'll let everyone know.

**Comment by gslin** [comment] 2016-05-02 10:13
I've set this up in https://launchpad.net/~gslin/+archive/ubuntu/netdata, please enjoy it.

**Comment by ktsaou** [comment] 2016-05-02 10:56
Nice!

Is this the latest release or the github version?

Can you give me instructions to show at: https://github.com/firehol/netdata/wiki/Installation

**Comment by gslin** [comment] 2016-05-06 14:41
Yeah, but I am not sure how to send pull request for wiki, so may I post here?

    # apt-add-repository ppa:gslin/netdata
    # apt-get update
    # apt-get install netdata

Please feel free to modify it.

**Comment by ktsaou** [comment] 2016-05-06 16:49
thanks!

2 questions:

1. Is this the latest release or the github version?
2. Is this updated automatically, or you do it by hand?

**Comment by gslin** [comment] 2016-05-06 19:45
1. Yes, it's 1.1.0 (current latest version). (Please check https://launchpad.net/~gslin/+archive/ubuntu/netdata this page)
2. This is updated manaually.

**Comment by Sacro** [comment] 2016-05-14 00:17
Is it possible for the deb to create system group and user for netdata? And a systemd config?

**Comment by Sacro** [comment] 2016-05-14 00:20
Also following on from that, chown netdata:netdata /var/cache/netdata

**Comment by Sacro** [comment] 2016-05-14 00:26
And also it seems to require chown -R root:netdata /usr/share/netdata/web/

**Comment by gslin** [comment] 2016-05-17 07:11
These ideas look great, I will improve PPA when available.

**Comment by synthead** [comment] 2016-07-22 23:54
@gslin, could you please include the package sources in your repository?  Also, is there a GitHub repository for this package or something?

**Comment by compuguy** [comment] 2016-09-16 16:28
@gslin With the 1.3.0 release in August your PPA is out of date currently. Any plans to put 1.3.0 up?

**Comment by LeeNX** [comment] 2016-10-10 10:16
Just installed onto Trusty (Ubunut 14.04) and found not init script or systemd config and also had to run ```sudo chgrp -R netdata /usr/share/netdata/web/``` to start from CMD as root, which might not be right, but working as the moment.  
  
Hoping for an update soon! ;-)

**Comment by FedericoCeratto** [comment] 2016-10-12 14:56
FYI various scripts and config files have been publised on https://anonscm.debian.org/git/collab-maint/netdata.git/tree/debian for #42

**Comment by ktsaou** [comment] 2016-10-12 18:01
> FYI various scripts and config files have been publised on https://anonscm.debian.org/git/collab-maint/netdata.git/tree/debian for #42

hm... they did it wrong... they replaced dygraphs library with the system wide one (probably the latest release of them), but the one used by netdata is a commit several months after the latest release, so certain features might be broken...

**Comment by FedericoCeratto** [comment] 2016-10-13 15:40
@ktsaou maybe we should move this discussion on #42 - anyhow only the system wide javascript libraries can be used (barring few exceptions) and the UI seems to be working with the libraries currently in Debian Unstable.

**Comment by ktsaou** [comment] 2016-10-13 15:57
ok. I am closing this, and discuss it at #42

**Comment by codezion** [comment] 2016-12-08 18:02
v 1.4 build seems to be broken at https://launchpad.net/~gslin/+archive/ubuntu/netdata Some missing files?

**Comment by LeeNX** [comment] 2017-01-23 10:07
Gentle nudge about release v1.5.0 - https://github.com/firehol/netdata/releases/tag/v1.5.0, please build the next release packages, I am really lazy ... ;-)

**Comment by vampywiz17** [comment] 2017-03-18 14:32
https://launchpad.net/debian/+source/netdata

**Comment by daenney** [comment] 2017-04-15 23:10
This might prove more useful for Ubuntu to go on: https://launchpad.net/ubuntu/+source/netdata. Unfortunately that only builds for Zesty (17.04) but it should be easy to set something up that tracks that and builds for other versions. The deb's listed there probably install on older versions of Ubuntu too.

**Comment by vith** [comment] 2017-11-26 11:57
Seems the PPA mentioned at https://github.com/firehol/netdata/issues/69#issuecomment-216187479 is 10 months out of date now. Should this issue be re-opened?

**Comment by ktsaou** [comment] 2017-11-27 23:06
re-opened. I can't help though. If anyone can help, please do so...

**Comment by thulle** [comment] 2018-02-04 17:43
I took Federico Ceratto's packaging for debian and made some minor changes to get it to build on launchpad for Ubuntu 16.04 Xenial.
Published here: https://launchpad.net/~thulle/+archive/ubuntu/netdatafromdebian

Two disclaimers:
 - I packaged this for my own evaluation of netdata. It seems to work as intended in ubuntu, but I haven't verified anything more than being able to connect to netdata and see some graphs.
 - Since I'm only evaluating using netdata so far, there's no assurance i will keep updating the packages.

Feel free to try it out. I'd be happy to receive comment on any issues with the package or help any aspiring packager to get going.

**Comment by maravento** [comment] 2018-06-04 19:03
Why do not you update PPA for Ubuntu 18.04?
Why do not you take official PPA?

**Comment by thulle** [comment] 2018-08-21 19:00
I've updated PPA with 1.10 for both Ubuntu 16.04 and 18.04.
Since I've upgraded to 18.04.1 everywhere before I started to update the PPA It's completely untested for 16.04.

**Comment by paulfantom** [comment] 2018-12-20 15:03
To all interested parties: I would like to unify how netdata packages are versioned, more in #5044

**Comment by paulkatsoulakis** [comment] 2019-05-14 06:50
We are running issue #5963 to delivery binary releases under custom netdata repositories for our users.  I will resolve this for now.

Do not hesitate to provide any inputs on the mentioned issue and its subtasks, any contribution is always value, we are what our users wants us to be anyway! :))

I have considered all closed packaging related issues and tried to re-use most contributions with a twist of automation and improvements where possible to get us there.

Of course #5963 is just the attempt to touch base with a long waited project, we will have more and more iterations until we get our packaging to an Enterprise level standard. Your contributions have been of great help so far, so thank you all in advance and see you on the next issue you will need our help!

**Closed by paulkatsoulakis** 2019-05-14 06:50 UTC
Labels: area/packaging, priority/low
