### ISSUE TITLE
[Bug]: Calling edit-config fails in nightly build

### ISSUE THREAD

**Issue by vobruba-martin** [netdata/netdata#14384] opened 2023-01-31 07:37 UTC
### Bug description

I was used to call `/etc/netdata/edit-config` from anywhere. Now I need to `cd` into `/etc/netdata` first to get it working. Is this bug or feature? I have no problems in the latest stable version.

```bash
/etc/netdata/edit-config health.d/disks.conf
/etc/netdata/edit-config: 40: cd: can't cd to health.d
ERROR: health.d/disks.conf is not located under /etc/netdata
```

```bash
cd /etc/netdata/
/etc/netdata/edit-config health.d/disks.conf
Copying '/etc/netdata/../../usr/lib/netdata/conf.d//health.d/disks.conf' to '/etc/netdata//health.d/disks.conf' ... 
Editing '/etc/netdata/health.d/disks.conf' ...
```

### Expected behavior

No need to `cd /etc/netdata`.

### Steps to reproduce

1. `cd /`
2. `/etc/netdata/edit-config health.d/disks.conf`

### Installation method

kickstart.sh

### System info

```shell
Linux server7 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.6 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.6 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

### Netdata build info

```shell
Version: netdata v1.37.0-199-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by Ferroin** [comment] 2023-01-31 14:10
Likely a result of https://github.com/netdata/netdata/pull/13702.

Prior to that being merged, we apparently were assuming the path we got passed was under `/etc/netdata`, while since that change we no longer make such an assumption.

Using an absolute path (or a correctly directed relative path) should resolve this.

**Comment by Dim-P** [comment] 2023-02-14 15:54
This is expected behavior since the changes introduced in https://github.com/netdata/netdata/pull/13702 that @Ferroin quoted above, so it won't be fixed.

**Comment by Ferroin** [comment] 2023-02-14 17:46
To clarify, it is expected behavior that the script is no longer assuming that relative paths are relative to `/etc/netdata`. There were some edge cases where this assumption was not actually working correctly, and we ended up with files being copied into random unrelated directories.

We can consider adding a fallback to assume relative paths are relative to the parent directory of the script itself, though it’s not likely to be an exceptionally high priority.

**Comment by vobruba-martin** [comment] 2023-02-14 19:10
At least the error message `ERROR: netdata.conf is not located under /etc/netdata` should be changed because it is misleading.

**Closed** 2023-02-21 10:45 UTC
Labels: bug, area/packaging
