### ISSUE TITLE
undefined applications show up in system category?

### ISSUE THREAD

**Issue by tve** [netdata/netdata#2385] opened 2017-06-24 15:20 UTC
I'm running the prometheus monitoring system and given that it uses a lot of memory I was wondering why it wasn't showing up in "other" in the application memory monitoring. I finally added it to the app_groups.conf and here's the result:
![image](https://user-images.githubusercontent.com/39480/27509608-ce2ea340-58b5-11e7-9701-b60d4d661e63.png)
As you can see, after the netdata restart to pull the changes in prometheus shows up and it's evident that it previously was classified as "system", isn't that a bug?

**Comment by ktsaou** [comment] 2017-06-24 17:11
Hi,

what did you add to apps_groups.conf to solve this issue? I think it would also be solved even if you just restarted apps.plugin (or netdata).

Let me explain how apps.plugin works:

1. it builds a process tree in memory (tree = all processes arranged in a parent - child relationship), so for most user processes pid 1 (init, or systemd) is the parent and then all the processes much like `ps fax` outputs under Linux.

2. processes matched by `apps_groups.conf` are assigned to dimensions.

3. their unassigned childs are assigned to the dimensions of their parents.

4. if any process is left unasigned is then assigned to the dimension of its parent.

5. Still a few process are left unassinged (their parent is pid 1, and none of their children is assigned to a dimension). These go to `other`.

6. All these assignments are made just once for the lifetime of a process.

7. At the next iteration, we repeat all the above, but processes may have re-arranged (for example a process forked a child, and after some time the parent exited, so the child process has now pid 1 as parent). But apps.plugin still remembers the original assignment from the time this process had a parent different to pid 1. This is probably your case: A process matched by the `system` dimension forked another process, and after some time this new process was left alone, but it was already assigned to the `system` dimension.  

Let me check if I can find a way to detect this process re-arrangement in the code and clear the assignment. Changing assignments is also a bit tricky, mainly because all values reported by the kernel are incremental (not memory of course, but most of the others - so to change an assignment we have to keep track of the volumes we have removed from an incremental dimension).

**Comment by tve** [comment] 2017-06-24 18:39
I had restarted netdata a few minutes prior (prometheus has been running for a long time) and it made no difference.
I just did a `ps fax` and prometheus shows up as top-level process:
```
28493 ?        Ssl  250:53 /home/bin/prometheus -storage.local.retention 20000h -storage.local.serie
```

**Comment by ktsaou** [comment] 2018-11-19 08:35
I can't reproduce this anymore.
I guess it has been fixed via another issue.
If the system persists, please post here and we will try to trace it.

**Closed by ktsaou** 2018-11-19 08:35 UTC
Labels: bug
