### ISSUE TITLE
Error: ACLK Main: could not retrieve challenge from auth response

### ISSUE THREAD

**Issue by jimerickson** [netdata/netdata#9922] opened 2020-09-13 17:59 UTC
##### Bug report summary

i can claim the node but the netdata cloud page always says unreachable. i get a lot of the following in the error.log:
```
2020-09-13 11:56:38: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 0.000 seconds
2020-09-13 11:56:38: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-09-13 11:56:38: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: app.netdata.cloud 443 /api/v1/auth/node/0905f33c-ee6b-421f-8a4f-b14c5590d007/challenge
2020-09-13 11:56:38: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-09-13 11:56:38: netdata ERROR : ACLK_Main : Could not retrieve challenge from auth response: {"challenge":"YrH14byFQogkTxrGjfG/uegXlQvL+x1IqNaPaHoznkk4D7jKglPnnlDZ/NJ7VR+riai6RnQRY7ONYg3kQnmaOMouvAAVXNHRLORl+taFm+yLIDa0W//c1zFV/2OmQfLQMIkWR0OYnq4fnTQ9QJboYSjV2Fyms2MtCdtJGSKybdPSvFpKxXcpxMUZ9/GxYirnD9l0MVIz7MP90idJzZlJSgTrlIfOZycyWoQBkjTilQddlXSAgOhZHVnEH87Mhbzb6URsP3aSjMsDpIi1v0ulhaaxSzgQd3GZTV7Aqw9ApC/2vwSIYWHQpyhMTJRvA2OkYpM8aoRVAGxKRW4Edg19SQ=="}
```
##### OS / Environment

```cmd
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

on a raspberry pi 4 8gb version.

##### Netdata version

 netdata v1.24.0-44-g9996479f

##### Component Name

ACLK
##### Steps To Reproduce

1. claim node
2. go to netdata cloud and it says unreachable
3. check error.log
##### Expected behavior

was hoping to connect to the cloud successfully via ACLK.

**Comment by OdysLam** [comment] 2020-09-14 08:30
Hey @jimerickson,

Welcome to our community :) Can you verify that you are not blocking connections with a firewall, either on the rpi or network-wide? We use port 443 as we establish a secure web-socket. Moreover, how did you install netdata?

**Comment by jimerickson** [comment] 2020-09-14 11:37
well i installed netdata with the netdata-installer.sh script and i have four other nodes all connected to netdata cloud at this location so it not blocked network side. and i did "sudo iptables -F" on the rpi and it still is unreachable on netdata cloud.

**Comment by underhood** [comment] 2020-09-14 14:10
@jimerickson I will try and take a look at this. Just on a hunch can you post output of `ldd` for netdata executable?

**Comment by jimerickson** [comment] 2020-09-14 14:16
sure no problem it is as follows:

pi@raspberrypi-8gb:~ $ ldd /usr/sbin/netdata
linux-vdso.so.1 (0x0000007f8b675000)
libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f8b278000)
libelf.so.1 => /usr/lib/aarch64-linux-gnu/libelf.so.1 (0x0000007f8b24c000)
libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000007f8b21f000)
libcrypto.so.1.1 => /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1
(0x0000007f8af77000)
libssl.so.1.1 => /usr/lib/aarch64-linux-gnu/libssl.so.1.1
(0x0000007f8aedd000)
libuuid.so.1 => /lib/aarch64-linux-gnu/libuuid.so.1 (0x0000007f8aec5000)
libuv.so.1 => /usr/lib/aarch64-linux-gnu/libuv.so.1 (0x0000007f8ae8b000)
liblz4.so.1 => /usr/lib/aarch64-linux-gnu/liblz4.so.1 (0x0000007f8ae60000)
libJudy.so.1 => /usr/lib/aarch64-linux-gnu/libJudy.so.1 (0x0000007f8ae10000)
libjson-c.so.3 => /usr/lib/aarch64-linux-gnu/libjson-c.so.3
(0x0000007f8adf5000)
libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0
(0x0000007f8adc6000)
libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f8ac54000)
/lib/ld-linux-aarch64.so.1 (0x0000007f8b647000)
libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f8ac40000)
librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000007f8ac28000)
libnsl.so.1 => /lib/aarch64-linux-gnu/libnsl.so.1 (0x0000007f8ac00000)

**Comment by underhood** [comment] 2020-09-16 07:44
Hmm,

I tried on Debian AMD64 and it seems to work well. Additionally since you conveniently included what was sent to agent  in log:
`{"challenge":"YrH14byFQogkTxrGjfG/uegXlQvL+x1IqNaPaHoznkk4D7jKglPnnlDZ/NJ7VR+riai6RnQRY7ONYg3kQnmaOMouvAAVXNHRLORl+taFm+yLIDa0W//c1zFV/2OmQfLQMIkWR0OYnq4fnTQ9QJboYSjV2Fyms2MtCdtJGSKybdPSvFpKxXcpxMUZ9/GxYirnD9l0MVIz7MP90idJzZlJSgTrlIfOZycyWoQBkjTilQddlXSAgOhZHVnEH87Mhbzb6URsP3aSjMsDpIi1v0ulhaaxSzgQd3GZTV7Aqw9ApC/2vwSIYWHQpyhMTJRvA2OkYpM8aoRVAGxKRW4Edg19SQ=="}`

I injected that exact response (this is one-time use challenge that we get from cloud to agent so that agent can verify it's identity). It seems to parse here without issue. Not triggering the `Could not retrieve challenge from auth response: %s` error case.

Might be something specific to the RPi and 64bit ARM? I will try to google if I can somehow emulate such thing as I have only older 32bit RPis available to me at this moment.

**Comment by jimerickson** [comment] 2020-09-17 20:49
let me know if you want me to try anything out. i have 2 of these raspberry pi 4 on 64-bit raspbian and the are both showing the same symptoms, however i do have a raspberry pi 0 on 32-bit raspbian and it works fine with netdata. so i think this is related to the 64-bit version of raspbian. i am willing to try anything you can come up with. thanks for all your work netdata has made my life easier!!

**Comment by underhood** [comment] 2020-09-18 18:20
Closest I could get is running aarch64 in qemu with debian.
`qemu-system-aarch64 -M virt -m 4G -cpu cortex-a53`
it connected to cloud without issue. Will try with raspbian next week. The qemu is crazy slow :D

**Comment by underhood** [comment] 2021-01-18 15:55
Tested this on RPi4 with 64bit raspbian but cannot reproduce the issue :/

**Comment by underhood** [comment] 2021-02-25 09:32
@jimerickson unfortunately I cannot reproduce this. I will close the issue for now + there is a complete rewrite of the ACLK component coming in few days.

**Closed by underhood** 2021-02-25 09:32 UTC
Labels: ACLK, bug, needs triage
