### ISSUE TITLE
[Bug]: IPMI plugin not installing on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by SteveBox0** [netdata/netdata#12893] opened 2022-05-12 20:21 UTC
### Bug description

Hello, 

I am currently got a machine running Ubuntu 22.04 with libipmimonitoring-dev (1.6.9-2) and ipmimonitoring (1.6.9) installed. 

I am unable to see the freeIPMI plugin installed and have check the folder location as well. (/usr/libexec/netdata/plugins.d/)
```
sudo su -s /bin/sh netdata
$  /usr/libexec/netdata/plugins.d/freeipmi.plugin 5 debug
sh: 1: /usr/libexec/netdata/plugins.d/freeipmi.plugin: not found
$ ls /usr/libexec/netdata/plugins.d/
acl.sh          alarm-notify.sh  alarm-test.sh            apps.plugin     cgroup-network            charts.d.dryrun-helper.sh  ebpf.d       fping.plugin              go.d.plugin            ioping.plugin       nfacct.plugin  python.d.plugin  slabinfo.plugin  tc-qos-helper.sh
alarm-email.sh  alarm.sh         anonymous-statistics.sh  cgroup-name.sh  cgroup-network-helper.sh  charts.d.plugin            ebpf.plugin  get-kubernetes-labels.sh  health-cmdapi-test.sh  loopsleepms.sh.inc  perf.plugin    request.sh       system-info.sh   template_dim.sh
```

I even created the link as per the documentation but to no luck.

`sudo ln -s /usr/lib/x86_64-linux-gnu/pkgconfig/libipmimonitoring.pc /usr/lib/pkgconfig/libipmimonitoring.pc`

As well as running a fresh reinstall of netdata
`wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --disable-telemetry --disable-cloud --reinstall-clean`

### Expected behavior

IPMI plugin displaying data on netdata web interface.

### Steps to reproduce

1. Install latest Ubuntu server LTS with all current updates
2. Install current libipmimonitoring-dev (1.6.9-2 at the time of writing) and ipmimonitoring (1.6.9 at the time of writing) 
3. Install NetData via kickstart script.
...

### Installation method

kickstart.sh

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux ubuntu 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
netdata -W buildinfo
Version: netdata v1.34.0-148-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

```
Via the web interface /netdata.conf, does not print any plugin related output for IPMI,

[plugins]
	# PATH environment variable = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
	# PYTHONPATH environment variable = 
	# timex = yes
	# checks = no
	# idlejitter = yes
	# tc = yes
	# diskspace = yes
	# proc = yes
	# cgroups = yes
	# enable running new plugins = yes
	# check for new plugins every = 60
	# slabinfo = no
	# perf = yes
	# nfacct = yes
	# ebpf = yes
	# charts.d = yes
	# go.d = yes
	# fping = yes
	# apps = yes
	# ioping = yes
	# python.d = yes

```

**Comment by SteveBox0** [comment] 2022-05-13 04:39
The below commands fixed the issue as a workaround. Then it must just be the installer not detecting IPMI correctly and skipping the package.

sudo apt-get install netdata-plugin-freeipmi
chmod 4755 /usr/libexec/netdata/plugins.d/freeipmi.plugin

**Comment by stelfrag** [comment] 2022-05-13 04:40
Thank you @SteveBox0 , we will take a look

**Comment by vlvkobal** [comment] 2022-05-19 11:20
cc: @netdata/agent-sre

**Comment by SteveBox0** [comment] 2022-06-12 15:34
I have also noticed on some deployments even after installing the netdata-plugin-freeipmi package that i have to run the below for output to show up. E.g. Run debug for 5 seconds and then exit it. IPMI graphs will work from that point onwards.
```
sudo su -s /bin/sh netdata
$  /usr/libexec/netdata/plugins.d/freeipmi.plugin 5 debug
```

**Comment by SteveBox0** [comment] 2022-06-14 06:43
Workaround for the second issue was
`echo "netdata	ALL=(ALL)	NOPASSWD: /usr/libexec/netdata/plugins.d/freeipmi.plugin" >> /etc/sudoers.d/netdata-ipmidcmi`

**Comment by Ferroin** [comment] 2022-06-29 10:52
This is expected behavior (other than needing to manually set permissions on the plugin itself) from our perspective. The IPMI (and CUPS) plugin is split out as a separate package for native packages so that users who don’t actually need it don’t end up having to deal with all the dependencies brought in by FreeIPMI, and we also intentionally have it listed as a suggested package (soft dependency, not installed automatically by default) and not a recommended package (soft dependency, installed automatically).

I can understand however how this would be unexpected from a user perspective. We can’t easily autodetect IPMI in the kickstart script itself, so there’s not any clean way for us to handle this. We will add info about this to the documentation, and look into adding installer options to explicitly pull in IPMI if desired.

**Comment by ilyam8** [comment] 2022-08-16 10:02
@Ferroin that looks like an easy problem to fix (docs only), can you make a PR so we can close the issue?

**Comment by Ferroin** [comment] 2022-08-16 13:01
@ilyam8 Indeed, this one just kind of slipped through the cracks. Will try to have a PR up later today.

**Closed** 2022-08-16 16:09 UTC
Labels: bug, area/packaging, area/docs, collectors/freeipmi
