### ISSUE TITLE
At update: fatal error: Invalid argument

### ISSUE THREAD

**Issue by thepra** [netdata/netdata#10892] opened 2021-03-31 21:59 UTC
##### Bug report summary

Meanwhile updating with `apt upgrade` to 1.30.0 there's a fatal error:
![immagine](https://user-images.githubusercontent.com/7032509/113216519-c8f48480-927c-11eb-94f6-c0f168352643.png)

##### OS / Environment

```
Linux v01d 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal

```

##### Netdata version

1.30.0

##### Installation method

`apt`

##### Steps To Reproduce

1. Execute `apt upgrade` and see the installation failing

##### Expected behavior

The usual successful update

**Comment by ilyam8** [comment] 2021-04-01 09:30
Hi @thepra. Thanks for reporting the issue.

I believe it is duplicate of https://github.com/netdata/netdata/issues/10773

**Closed** 2021-04-01 09:32 UTC
Labels: bug, duplicate, needs triage
