### ISSUE TITLE
Remove deprecated charts.d plugins served by native plugins

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#6151] opened 2019-05-28 17:43 UTC
##### Feature idea summary
Take a look at #4104 and properly remove the legacy charts.d plugins.

##### Expected behavior
Only the c plugins should exist, the netdata-updater should remove references to the old plugins and files related to them.

**Comment by cakrit** [comment] 2019-05-28 17:44
Do a new PR, notice @ktsaou's comment and close #4104.

**Comment by ilyam8** [comment] 2020-01-29 12:58
Why havent we removed them so far? @Ferroin wy didnt we merge https://github.com/netdata/netdata/pull/4104 ?

we could use same logic as in python plugin

https://github.com/netdata/netdata/blob/f5a043ce21642a68c7bef7363163d308edd97074/collectors/python.d.plugin/python.d.plugin.in#L128-L139

**Comment by Ferroin** [comment] 2020-01-29 13:58
@ilyam8 Details are present in the discussion. The quick explanation is that we have a crappy updater script that doesn't remove the files that the previous version installed which weren't included in the new version, so we have to do rather stupid handling for the old collectors that are being removed.

Overall, I'm of the opinion right now that _that_ needs fixed first, and then we can do exactly what #4104 was trying to do, including removing the lines for the scripts that are being removed.

**Comment by ilyam8** [comment] 2020-01-29 14:00
> doesn't remove the files

Yes, i know, but it doesnt stop us to deprecate python collectors (hardcoded logic in orchestrator).

**Comment by Ferroin** [comment] 2020-01-29 14:04
> > doesn't remove the files
> 
> Yes, i know, but it doesnt stop us to deprecate python collectors (hardcoded logic in python.d.plugin).

That doesn't really help us much here though. We already have the relevant collectors disabled by default, the issue is that we can't _remove_ them completely, because the files stick around after an uninstall. That's why we still need the line for `unbound` in the Python collector too for that matter.

Yes, we can remove the files, have at it if you want to do so, but the updater needs fixed too so that we can properly get rid of all references to them.

**Comment by ilyam8** [comment] 2020-01-29 14:28
Well, you will have these lines either in charts.d.plugin or installer. I mean it is easy to add them to charts.d and remove files atm and fix installer later.

**Comment by Ferroin** [comment] 2020-03-04 23:34
Closed by #7962

**Closed by Ferroin** 2020-03-04 23:34 UTC
Labels: area/packaging, feature request, needs triage
