### ISSUE TITLE
Remove duplicate unreachable host in Console

### ISSUE THREAD

**Issue by StefanRu** [netdata/netdata#7381] opened 2019-11-28 14:13 UTC
How can I remove a duplicate unreachable Node? Where is it stored?
![image](https://user-images.githubusercontent.com/5259750/69812658-dfa24b80-11f0-11ea-9510-6dd1c706b2bb.png)

Great product! Love it :)

**Comment by thiagoftsm** [comment] 2019-11-28 14:20
Hi @StefanRu ,

We are glad with your opinion about netdata, thank you!

You can delete the Node when you click on it, and after this you will have the "forget" link on right side.

Best regards!

**Comment by StefanRu** [comment] 2019-11-28 14:29
when I click on the node i have a white website. No header no links.
I try to read the source but no luck here:

<html class="fontawesome-i2svg-active fontawesome-i2svg-complete"><head>
    <title>Netdata Console</title>
    <meta name="application-name" content="netdata">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <style type="text/css">svg:not(:root).svg-inline--fa{overflow:visible}.svg-inline--fa{display:inline-block;font-size:inherit;height:1em;overflow:visible;vertical-align:-.125em}.svg-inline--fa.fa-lg{vertical-align:-.225em}.svg-inline--fa.fa-w-1{width:.0625em}.svg-inline--fa.fa-w-2{width:.125em}.svg-inline--fa.fa-w-3{width:.1875em}.svg-inline--fa.fa-w-4{width:.25em}.svg-inline--fa.fa-w-5{width:.3125em}.svg-inline--fa.fa-w-6{width:.375em}.svg-inline--fa.fa-w-7{width:.4375em}.svg-inline--fa.fa-w-8{width:.5em}.svg-inline--fa.fa-w-9{width:.5625em}.svg-inline--fa.fa-w-10{width:.625em}.svg-inline--fa.fa-w-11{width:.6875em}.svg-inline--fa.fa-w-12{width:.75em}.svg-inline--fa.fa-w-13{width:.8125em}.svg-inline--fa.fa-w-14{width:.875em}.svg-inline--fa.fa-w-15{width:.9375em}.svg-inline--fa.fa-w-16{width:1em}.svg-inline--fa.fa-w-17{width:1.0625em}.svg-inline--fa.fa-w-18{width:1.125em}.svg-inline--fa.fa-w-19{width:1.1875em}.svg-inline--fa.fa-w-20{width:1.25em}.svg-inline--fa.fa-pull-left{margin-right:.3em;width:auto}.svg-inline--fa.fa-pull-right{margin-left:.3em;width:auto}.svg-inline--fa.fa-border{height:1.5em}.svg-inline--fa.fa-li{width:2em}.svg-inline--fa.fa-fw{width:1.25em}.fa-layers svg.svg-inline--fa{bottom:0;left:0;margin:auto;position:absolute;right:0;top:0}.fa-layers{display:inline-block;height:1em;position:relative;text-align:center;vertical-align:-12.5%;width:1em}.fa-layers svg.svg-inline--fa{-webkit-transform-origin:center center;transform-origin:center center}.fa-layers-counter,.fa-layers-text{display:inline-block;position:absolute;text-align:center}.fa-layers-text{left:50%;top:50%;-webkit-transform:translate(-50%,-50%);transform:translate(-50%,-50%);-webkit-transform-origin:center center;transform-origin:center center}.fa-layers-counter{background-color:#ff253a;border-radius:1em;color:#fff;height:1.5em;line-height:1;max-width:5em;min-width:1.5em;overflow:hidden;padding:.25em;right:0;text-overflow:ellipsis;top:0;-webkit-transform:scale(.25);transform:scale(.25);-webkit-transform-origin:top right;transform-origin:top right}.fa-layers-bottom-right{bottom:0;right:0;top:auto;-webkit-transform:scale(.25);transform:scale(.25);-webkit-transform-origin:bottom right;transform-origin:bottom right}.fa-layers-bottom-left{bottom:0;left:0;right:auto;top:auto;-webkit-transform:scale(.25);transform:scale(.25);-webkit-transform-origin:bottom left;transform-origin:bottom left}.fa-layers-top-right{right:0;top:0;-webkit-transform:scale(.25);transform:scale(.25);-webkit-transform-origin:top right;transform-origin:top right}.fa-layers-top-left{left:0;right:auto;top:0;-webkit-transform:scale(.25);transform:scale(.25);-webkit-transform-origin:top left;transform-origin:top left}.fa-lg{font-size:1.33333em;line-height:.75em;vertical-align:-.0667em}.fa-xs{font-size:.75em}.fa-sm{font-size:.875em}.fa-1x{font-size:1em}.fa-2x{font-size:2em}.fa-3x{font-size:3em}.fa-4x{font-size:4em}.fa-5x{font-size:5em}.fa-6x{font-size:6em}.fa-7x{font-size:7em}.fa-8x{font-size:8em}.fa-9x{font-size:9em}.fa-10x{font-size:10em}.fa-fw{text-align:center;width:1.25em}.fa-ul{list-style-type:none;margin-left:2.5em;padding-left:0}.fa-ul>li{position:relative}.fa-li{left:-2em;position:absolute;text-align:center;width:2em;line-height:inherit}.fa-border{border:solid .08em #eee;border-radius:.1em;padding:.2em .25em .15em}.fa-pull-left{float:left}.fa-pull-right{float:right}.fa.fa-pull-left,.fab.fa-pull-left,.fal.fa-pull-left,.far.fa-pull-left,.fas.fa-pull-left{margin-right:.3em}.fa.fa-pull-right,.fab.fa-pull-right,.fal.fa-pull-right,.far.fa-pull-right,.fas.fa-pull-right{margin-left:.3em}.fa-spin{-webkit-animation:fa-spin 2s infinite linear;animation:fa-spin 2s infinite linear}.fa-pulse{-webkit-animation:fa-spin 1s infinite steps(8);animation:fa-spin 1s infinite steps(8)}@-webkit-keyframes fa-spin{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}@keyframes fa-spin{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}.fa-rotate-90{-webkit-transform:rotate(90deg);transform:rotate(90deg)}.fa-rotate-180{-webkit-transform:rotate(180deg);transform:rotate(180deg)}.fa-rotate-270{-webkit-transform:rotate(270deg);transform:rotate(270deg)}.fa-flip-horizontal{-webkit-transform:scale(-1,1);transform:scale(-1,1)}.fa-flip-vertical{-webkit-transform:scale(1,-1);transform:scale(1,-1)}.fa-flip-horizontal.fa-flip-vertical{-webkit-transform:scale(-1,-1);transform:scale(-1,-1)}:root .fa-flip-horizontal,:root .fa-flip-vertical,:root .fa-rotate-180,:root .fa-rotate-270,:root .fa-rotate-90{-webkit-filter:none;filter:none}.fa-stack{display:inline-block;height:2em;position:relative;width:2em}.fa-stack-1x,.fa-stack-2x{bottom:0;left:0;margin:auto;position:absolute;right:0;top:0}.svg-inline--fa.fa-stack-1x{height:1em;width:1em}.svg-inline--fa.fa-stack-2x{height:2em;width:2em}.fa-inverse{color:#fff}.sr-only{border:0;clip:rect(0,0,0,0);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px}.sr-only-focusable:active,.sr-only-focusable:focus{clip:auto;height:auto;margin:0;overflow:visible;position:static;width:auto}</style><link rel="icon" href="data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAP9JREFUeNpiYBgFo+A/w34gpiZ8DzWzAYgNiHGAA5UdgA73g+2gcyhgg/0DGQoweB6IBQYyFCCOGOBQwBMd/xnW09ERDtgcoEBHB+zHFQrz6egIBUasocDAcJ9OxWAhE4YQI8MDILmATg7wZ8QRDfQKhQf4Cie6pAVGPA4AhQKo0BCgZRAw4ZSBpIWJNI6CD4wEKikBaFqgVSgcYMIrzcjwgcahcIGRiPYCLUPBkNhWUwP9akVcoQBpatG4MsLviAIqWj6f3Absfdq2igg7IIEKDVQKEzN5ofAenJCp1I8gJRTug5tfkGIdR1FDniMI+QZUjF8Amn5htOdHCAAEGACE6B0cS6mrEwAAAABJRU5ErkJggg==">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    
    <script type="text/javascript" async="" src="http://xxx.xxx.xxxx.xxx:19999/lib/jquery-2.2.4.min.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-N6CBMJD"></script><script>(function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-N6CBMJD');
        window.dataLayer = window.dataLayer || [];
    </script>
    
    <script>
        function loadJSFile(filename) {
            const s = document.createElement("script")
            s.setAttribute("type", "text/javascript")
            s.setAttribute("src", filename)
            document.getElementsByTagName("head")[0].appendChild(s)
        }

        function loadCSSFile(filename) {
            const l = document.createElement("link")
            l.setAttribute("rel", "stylesheet")
            l.setAttribute("type", "text/css")
            l.setAttribute("href", filename)
            document.getElementsByTagName("head")[0].appendChild(l)
        }

        var cloudBaseURL = localStorage.getItem("cloud.baseURL") || "https://netdata.cloud"

        loadCSSFile(`${cloudBaseURL}/static/console/main.css?v=4`)
    </script><link rel="stylesheet" type="text/css" href="https://netdata.cloud/static/console/main.css?v=4">
<script type="text/javascript" src="https://netdata.cloud/static/console/main.js?v=4"></script><link rel="stylesheet" type="text/css" href="http://xxx.xxx.xxx.xxx:19999/dashboard.css?v20190902-0"></head>

<body class="mdc-theme--background mdc-typography">
    
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-N6CBMJD" height="0" width="0"
            style="display:none;visibility:hidden"></iframe>
    </noscript>
    
    <main id="app" class="console-app" data-host="agent" data-static-base-url="https://netdata.cloud" data-api-base-url="https://netdata.cloud" data-api-base-url-v2="https://netdata.cloud"></main>
    <script>
        const main = document.getElementById("app")
        main.setAttribute("data-static-base-url", cloudBaseURL)
        main.setAttribute("data-api-base-url", cloudBaseURL)
        main.setAttribute("data-api-base-url-v2", cloudBaseURL)

        loadJSFile(`${cloudBaseURL}/static/console/main.js?v=4`)
    </script>
    <script>
        var netdataTheme = "white"
        var netdataNoBootstrap = true
    </script>
    <script type="text/javascript" src="dashboard.js?v20190902-0"></script>


</body></html>

**Comment by thiagoftsm** [comment] 2019-11-28 15:24
What is the browser you are using?

**Comment by StefanRu** [comment] 2019-11-28 18:57
Tried it with 
Chrome Version 80.0.3979.0 (Build officiel) canary (64 bits)
Microsoft IE11.418.18362.0
Microsoft Edge 44.18362.387.0 (error NOT FOUND You just hit a route that doesn't exist... the sadness.)

**Comment by ingenieurmt** [comment] 2019-12-01 11:17
I can confirm I am seeing the same issue. Seems to have started somewhere between v1.18.0 and v1.19.0. There is no way to remove these 'zombie' nodes; clicking on them to bring up a 'forget' button (expected behaviour) renders a blank page instead.

**Comment by ilyam8** [comment] 2019-12-01 12:42
I confirm it.

I can `Forget` unreachable `web-proxy-corp` node, but i cant do it for `ilyam-pc` nodes.

Btw, there is no option to forget not unreachable node, is it expected?

<img width="1415" alt="Screenshot 2019-12-01 at 15 39 35" src="https://user-images.githubusercontent.com/22274335/69914060-d2839780-1450-11ea-8760-987600fba9de.png">

**Comment by VLegakis** [comment] 2019-12-09 11:02
Hello @StefanRu ! 
This issue has been handled. Could you please take a look and confirm?
I'm closing the issue since @ilyam8 confirmed its fixed for him. 
Feel free to reopen it in case your issue persists. 
Many thanks for your feedback!

**Closed by VLegakis** 2019-12-09 11:02 UTC
Labels: bug, cloud

**Comment by ingenieurmt** [comment] 2019-12-10 12:37
Confirmed, I am now able to remove the dangling hosts in the cloud console. Thanks team!
