### ISSUE TITLE
Unable to obtain continuous perf data 

### ISSUE THREAD

**Issue by wtkhysm5** [netdata/netdata#11938] opened 2022-01-06 06:19 UTC
## Environment

OS：CentOS-7.6-4.14.0-115.el7a.0.1.aarch64
Netdata：v1.31.0-242-gb0b0fbd

## Problem/Question

I use the perf.plugins and want to collect all the data every second. It works very well when I do nothing. But when I run some big large programs and CPU fully loaded, it seems netdata can not get continuous data. Cannot see continuous lines  but intermittent line on the dashboard.  

I get this in error.log.

```
2022-01-05 18:13:34: netdata ERROR : PLUGIN[proc] : heartbeat missed 6790000 monotonic microseconds
2022-01-05 18:13:40: netdata ERROR : PLUGIN[proc] : heartbeat missed 4090000 monotonic microseconds
2022-01-05 18:13:43: netdata ERROR : PLUGIN[proc] : heartbeat missed 1890000 monotonic microseconds
2022-01-05 18:13:43: perf.plugin ERROR : MAIN : heartbeat missed 6980000 monotonic microseconds
2022-01-05 18:13:44: netdata ERROR : MAIN : EXPORTING: '150.1.68.201:10121' closed the socket
2022-01-05 18:13:50: perf.plugin ERROR : MAIN : heartbeat missed 6000000 monotonic microseconds
2022-01-05 18:13:52: netdata ERROR : PLUGIN[proc] : heartbeat missed 8010000 monotonic microseconds
2022-01-05 18:13:57: netdata ERROR : PLUGIN[proc] : heartbeat missed 3990000 monotonic microseconds
2022-01-05 18:13:58: netdata ERROR : MAIN : EXPORTING: '150.1.68.201:10121' closed the socket
2022-01-05 18:13:59: perf.plugin ERROR : MAIN : heartbeat missed 7610000 monotonic microseconds
2022-01-05 18:14:05: perf.plugin ERROR : MAIN : heartbeat missed 4650000 monotonic microseconds
2022-01-05 18:14:06: netdata ERROR : PLUGIN[proc] : heartbeat missed 8070000 monotonic microseconds
```

By the way, I already set netdata.conf.
```
[global]
process scheduling policy = rr
process scheduling priority = 99
```
## What I expected to happen

So how can I solve this problem?
Thanks.

**Comment by ilyam8** [comment] 2022-01-11 11:36
Hi, @wtkhysm5.

> it seems netdata can not get continuous data

Do you get gaps on all the charts?

**Comment by ilyam8** [comment] 2022-01-14 09:49
@wtkhysm5 so changing the scheduling policy/priority fixes the problem?

> I change the priority of netdata in netdata.conf, it didn't work.

I see this is expected, see [scheduling settings and systemd](https://learn.netdata.cloud/docs/agent/daemon#scheduling-settings-and-systemd).

**Comment by ilyam8** [comment] 2022-01-18 08:38
Marking this as "wontfix" because it is expected behavior and is [documented](https://learn.netdata.cloud/docs/agent/daemon#scheduling-settings-and-systemd).

**Closed by ilyam8** 2022-01-18 08:38 UTC
Labels: bug, wontfix
