### ISSUE TITLE
Bandwidth counter overflow on master when slave rebooted

### ISSUE THREAD

**Issue by devopsoffice-peter** [netdata/netdata#5297] opened 2019-01-30 14:05 UTC
##### Bug report summary
When a Netdata slave is rebooted, the IP bandwidth counter displays correctly on the slave's dashboard. However, when the slave is viewed from the master's dashboard, there's a huge spike (3.8 Gbps) just after the reboot. This is on a system with a gigabit interface. There are other systems where a reboot causes an even higher spike like 2 million terabits/s.

**Master**
![screenshot from 2019-01-30 14-47-26](https://user-images.githubusercontent.com/47179206/51985464-35597a80-249e-11e9-971d-76057f6ebae0.png)
**Slave**
![screenshot from 2019-01-30 14-47-36](https://user-images.githubusercontent.com/47179206/51985465-35597a80-249e-11e9-823b-f6cdae3d087f.png)

##### OS / Environment
Debian Stretch

##### Netdata version (ouput of `netdata -V`)
netdata 1.11.1+dfsg-2

##### Component name
proc_net plugin

##### Steps To Reproduce
Set up netdata in a master-slave configuration and reboot the slave. Watch the dashboard provided by the master and see the bandwidth spike up after the reboot has completed.

##### Expected behavior
Netdata should handle the interface reset correctly and not display unrealistic values.

**Comment by ilyam8** [comment] 2019-01-30 14:58
it is not only when slave is rebooted. 

https://github.com/netdata/netdata/pull/4538

Very easy to reproduce - restart service, if it has charts with incremental dimensions you will see these huge spikes.

![screenshot_20190130_175742](https://user-images.githubusercontent.com/22274335/51989689-9beb9200-24b8-11e9-8511-826134bf335b.png)

**Comment by cakrit** [comment] 2019-02-02 13:14
Can you please test #5317 and let us know if it works for you? You'll need to compile from source.

**Comment by devopsoffice-peter** [comment] 2019-02-04 11:06
Just did a quick test, netdata v1.12.0-rc3-66-gadaaae7 on both master and slave, compiled from source.

As you can see, the fix only affected one dimension:
![screenshot from 2019-02-04 12-00-58](https://user-images.githubusercontent.com/47179206/52204666-1a5b8180-2875-11e9-8fe3-e6d59d2b6ad7.png)

This is the master dashboard showing slave's metrics, the slave dashboard functions as expected, just like in previous versions.

**Comment by cakrit** [comment] 2019-02-05 16:22
We will conclude the discussion in #4962 and ask you to test again when we know we have a solution.

**Comment by cosmix** [comment] 2019-10-23 11:40
Related to #4962.

**Comment by mfundul** [comment] 2019-10-30 10:11
Closing as duplicate of #4962

**Closed by mfundul** 2019-10-30 10:11 UTC
Labels: area/database, bug, priority/high
