### ISSUE TITLE
Node-list Not Loading on Firefox 70.0

### ISSUE THREAD

**Issue by x86txt** [netdata/netdata#7227] opened 2019-10-30 06:58 UTC
##### Bug report summary
With Firefox 70.0 on macOS 10.15.1. Both netdata 1.17.1,  1.12, and 1.10 show the same behavior when clicking on the nodelist, "Loading..." is displayed. 
Safari 13.0.3 on macOS is fine. 
Chrome 78.0.3904.70 works also.

For Firefox, I'm seeing two errors in the console:

Source map error: Error: request failed with status 404
Resource URL: https://nas1.x86txt.lan/netdata/lib/jquery-2.2.4.min.js
ERROR 407: Cannot HELLO netdata server: https://nas1.x86txt.lan/netdata

However, clicking on those URLs results in both the .js library being displayed and the netdata console being displayed, respectively.

##### OS / Environment
macOS Catalina 10.15.1

##### Netdata version (ouput of `netdata -V`)
netdata 1.17.1, 1.12, 1.10

##### Steps To Reproduce
Open web interface in Firefox, click on my-netdata tab.

##### Expected behavior
Streaming nodes will be shown, as they are in Safari and Chrome.

**Comment by jacekkolasa** [comment] 2019-10-30 09:50
Hi @x86txt does it also break in Firefox private mode?

**Comment by x86txt** [comment] 2019-10-30 22:56
Hi @jacekkolasa - I downgraded to Firefox 68 and it started working immediately. Upgrading back to 70 broke it again. In both cases, I created fresh Firefox profiles also in case something in my old profile was borking it.

Would you like me to proceed with installing a fresh 1.17.1 master and then test with 70? I can't browse directly to a 1.17 node, because they all have 'web mode = none' in their configs. (Assuming I understand correctly that all traffic is rendered by the master 1.10 node?)

**Comment by jacekkolasa** [comment] 2019-10-31 11:59
That's important hint, thanks! I haven't been able to recreate the bug yet, unfortunately, but i'll be doing more research. If you'll see the bug, could you please check near FF address bar if there are any blocked cookies or any blocked traffic?

![image](https://user-images.githubusercontent.com/5786722/67944831-bab0bd80-fbdd-11e9-8750-6a03b5a60406.png)

Also, if you'll have time, could you check the result of last `https://registry.my-netdata.io/api/v1/registry?action=access..` call? Perhaps the problem is related to [this issue](https://github.com/netdata/netdata/issues/7201), which is basically caused by Safari not sending cookies to Registry

**Comment by x86txt** [comment] 2019-10-31 13:02
I just checked for blocked cookie and here is what it reports.

![image](https://user-images.githubusercontent.com/34278354/67948419-0bafba00-fbbc-11e9-83c6-308178972c13.png)

I've also clicked Protection Settings -> Custom -> and unchecked all protections. FWIW, I also disabled HTTPS on the master, but the behavior is the same.

For the registry call, it's not calling https://registry.my-netdata.io, it's calling https://nas1.x86txt.lan (my master) but I think you're on to something. It's throwing a 400 bad request. All other requests are 200.

![image](https://user-images.githubusercontent.com/34278354/67948915-13239300-fbbd-11e9-9485-da15dc3de914.png)

**Comment by x86txt** [comment] 2019-10-31 13:07
Here we go. Browsing directly to that 400 error shows this: 'Your web browser is sending 'DNT: 1' (Do Not Track). The registry requires persistent cookies on your browser to work.'

Setting FF70's DNT setting from Always to Only ... allows it to immediate work.

![image](https://user-images.githubusercontent.com/34278354/67949279-d6a46700-fbbd-11e9-80fa-3773c69e3932.png)

**Comment by jacekkolasa** [comment] 2019-10-31 14:09
Nice catch. For me setting DNT:Always doesn't return 400, but i'll check that, maybe there are some other things involved, why it's working well on my end. Anyway, looks like the problem is bad error handling for registry calls (similarly to https://github.com/netdata/netdata/issues/7201) and i'll create separate issue to fix that. Thanks again!
I'll close the issue then, but if you have any more notes, questions, please respond here

**Closed by jacekkolasa** 2019-10-31 14:09 UTC
Labels: area/web, bug

**Comment by x86txt** [comment] 2019-10-31 20:43
You're most welcome. Thank you for this amazing product.
