### ISSUE TITLE
[ipfs plugin]: ipfs_local.repo_objects chart: API calls to IPFS make it consume too much cpu/ram. Disable by default?

### ISSUE THREAD

**Issue by mkg20001** [netdata/netdata#3156] opened 2017-12-19 21:58 UTC
If there is a lot of stuff in an ipfs node than an `ipfs pin ls` request consumes way to much cpu/ram.
I think the pin ls should be disabled by default as it can cause servers to be out of memory and have high cpu usage.
This is happening on quite a few servers.

**Comment by ktsaou** [comment] 2018-01-14 23:49
@pjz please check this.

If `ipfs pin ls` consumes a lot of CPU/RAM, then yes, it should be disabled by default.

**Comment by mkg20001** [comment] 2018-08-23 12:28
This is still an issue. One way would be to disable `ipfs_local.repo_objects` and possibly `ipfs_local.repo_size` by default (I think these two are causing the heavy usage, unsure if repo_size is cached or calculated on-demand).
For example I have a node with ~5k objects and the IPFS CPU usage jumped from ~20% to ~300% (3 cores fully utilized) after I restarted netdata which auto-detected the node.

**Comment by pjz** [comment] 2018-08-23 14:40
This is likely due to https://github.com/ipfs/go-ipfs/issues/5221 so maybe disable the slow stuff unless/until ipfs fixes that issue?

**Comment by ktsaou** [comment] 2018-08-25 09:34
> This is likely due to ipfs/go-ipfs#5221 so maybe disable the slow stuff unless/until ipfs fixes that issue?

I agree. Can you do this? Probably you can add an option in the module config, so that someone can enable it even if it is slow.

**Comment by ktsaou** [comment] 2018-08-25 09:34
I marked as "bug", though it is not a netdata bug...

**Comment by pjz** [comment] 2018-08-25 20:40
maybe add/assign an 'upstream bug' tag?

**Comment by pjz** [comment] 2018-08-30 19:59
Okay, so after reading some code, the issue is this: there's a lot of data to process.  The chart by default gets the list of all the pins (in json), and then iterates over them to find the recursive ones, building a potentially large list of strings (hashes) as it goes.

https://github.com/firehol/netdata/pull/4095 optimizes this somewhat by avoiding the creation of that list.

If that doesn't fix the issue, then we may have to figure out something else.  Maybe the overhead of doing another API call (asking for just recursive pins) and parsing the response is faster than doing the search in the module? That would look something like:
```python
    cfg = {
            # ...
            '/api/v0/pin/ls?type=recursive':
                [('recursive_pins', 'Keys', len)]
    }
```

**Comment by ktsaou** [comment] 2018-09-12 19:13
> maybe add/assign an 'upstream bug' tag?

nice idea. added it.

**Comment by ktsaou** [comment] 2018-09-12 19:15
> #4095 optimizes this somewhat by avoiding the creation of that list.
> 
> If that doesn't fix the issue, then we may have to figure out something else. Maybe the overhead of doing another API call (asking for just recursive pins) and parsing the response is faster than doing the search in the module

#4095 is now merged.
Is it better?

**Comment by mkg20001** [comment] 2018-09-13 11:56
I don't think I was properly understood:
The `pin ls` calls cause IPFS, **not** netdata to consume too many resources

**Comment by ktsaou** [comment] 2018-09-13 21:18
My fault. Sorry.
@pjz can we avoid these calls, or disable them by default?

**Comment by pjz** [comment] 2018-09-14 20:02
Can't avoid them, but can remove the 'repo object' stats by commenting out that key and value(s) in the `CHARTS` definition (lines 44-50)

**Comment by mkg20001** [comment] 2018-09-14 20:27
Yes, I think making them off-by-default is a great idea

**Comment by Calmarius** [comment] 2018-10-23 00:07
So does disabling this api means we can no longer pin objects?

**Comment by l2isbad** [comment] 2018-10-23 00:17
set to `yes` to enable

https://github.com/netdata/netdata/blob/9f681f10af1128a93f14df6ad4061485300dbc37/collectors/python.d.plugin/ipfs/ipfs.conf#L67-L70

**Comment by pjz** [comment] 2018-10-23 00:18
No, it means that stats on number of total objects and pinned objects won't be kept.

**Comment by l2isbad** [comment] 2018-11-19 08:16
#4224 is merged
call to `/api/v0/pin/ls` is disabled by default
upstream [bug isn't fixed](https://github.com/ipfs/go-ipfs/issues/3874) yet

i am closing this

**Closed by l2isbad** 2018-11-19 08:16 UTC
Labels: bug, wontfix
