### ISSUE TITLE
netdata-installer.sh exited with error 

### ISSUE THREAD

**Issue by rtbon** [netdata/netdata#11869] opened 2021-12-06 15:40 UTC
Hi, I'm trying to install Netdata on a raspberry pi 4 
Previously I used netdata v1.31.0 but when I've tried an update I got an error so I haved uninstall Netdata and when I try to install it again I got again and again this error :
`ABORTED  netdata-installer.sh exited with error `

I used one-line installation script :
`bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel --disable-telemetry`

I hope output from the command can helps
[error.txt](https://github.com/netdata/netdata/files/7661802/error.txt)

Thanks

**Comment by MrZammler** [comment] 2021-12-07 10:40
Hi @rtbon thanks for your report! It seems to be something related to the json-c-dev package.

Can you please past the output of the command `dpkg -s libjson-c-dev` ?

Thanks!

**Comment by rtbon** [comment] 2021-12-07 14:41
Hi & thanks @MrZammler 

> Hi @rtbon thanks for your report! It seems to be something related to the json-c-dev package.
> 
> Can you please past the output of the command `dpkg -s libjson-c-dev` ?
> 
> Thanks!

I got this :

```Package: libjson-c-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 130
Maintainer: Debian QA Group <packages@qa.debian.org>
Architecture: armhf
Multi-Arch: same
Source: json-c
Version: 0.12.1+ds-2+deb10u1
Depends: libjson-c3 (= 0.12.1+ds-2+deb10u1)
Description: JSON manipulation library - development files
 This library allows you to easily construct JSON objects in C,
 output them as JSON formatted strings and parse JSON formatted
 strings back into the C representation of JSON objects.
 .
 The development headers for compiling programs that use libjson-c
 are provided by this package.
Homepage: https://github.com/json-c/json-c/wiki```

May be a bad version ?

**Comment by MrZammler** [comment] 2021-12-08 07:49
Hi @rtbon , yes, there seems to be something maybe with the installation of json-c... I will try to recreate the issue, but in the mean time, can you try passing `--build-json-c` to the kickstart script ? It will try to use a bundled version of json-c which might do as a workaround for the time being.

An installed version of >=0.13 should also be okay... But we should handle the case of older json-c, so it's something we need to look at maybe.

**Comment by rtbon** [comment] 2021-12-08 08:36
Hi @MrZammler, I've tried with `--build-json-c`, but still the same error
[error_2.txt](https://github.com/netdata/netdata/files/7674582/error_2.txt)

**Comment by rtbon** [comment] 2021-12-08 12:09
I try to update **libjson-c-dev**:
```
sudo apt-get update
sudo apt-get install libjson-c-dev
```
return:
```
libjson-c-dev is already the most recent version (0.12.1+ds-2+deb10u1)
```
I found/think 0.15 is only for Bullseye, 0.12.1 is the most recent for Buster:[https://packages.debian.org/fr/buster/libjson-c-dev](url)

**Comment by MrZammler** [comment] 2021-12-08 12:28
The thing is, there is a test for version >13 that allows `json_pointer_get` to be used, and it seems it succeeds in that test, despite you having installed a version 0.12.

There must be some json header files that it picks this define from, can you check for `grep -r JSON_C_MINOR_VERSION /usr/include` to see what it comes up with please ?

**Comment by rtbon** [comment] 2021-12-08 13:12
Yes of course :
```
grep -r JSON_C_MINOR_VERSION /usr/include
/usr/include/json-c/json_c_version.h:#define JSON_C_MINOR_VERSION 13
/usr/include/json-c/json_c_version.h:                            (JSON_C_MINOR_VERSION << 8) | \
```

**Comment by MrZammler** [comment] 2021-12-09 12:12
Well, this is weird. Unless they package 0.12 and change the header to display 13, or somehow multiple versions installed...

The code finds 13 from the include, so it assumes the function `json_pointer_get` will exist, but when it come to link with the library it is not there....

In the mean time, could I suggest that you try our binary builds instead... ?

**Comment by Ferroin** [comment] 2021-12-09 14:13
Is it possible that a different version was installed by hand? Usually that type of thing is the root cause for header mismatches like this.

**Comment by Dim-P** [comment] 2022-05-13 20:16
@rtbon Have you managed to resolve this?

**Comment by MrZammler** [comment] 2022-05-20 12:14
@rtbon Will close this, please if you continue to have problems do re-open (or a new one).

**Closed by MrZammler** 2022-05-20 12:14 UTC
Labels: bug, area/packaging, area/build
