### ISSUE TITLE
[Bug]: service cant start

### ISSUE THREAD

**Issue by marliyev** [netdata/netdata#13284] opened 2022-06-30 18:35 UTC
### Bug description

netdata agent service cant start on client

Ubuntu 20.04.4 LTS
Linux 5.4.0-109-generic
netdata v1.35.0-104-nightly

### Expected behavior

N/A

### Steps to reproduce

1. 

### Error Logs

kernel: [4484994.051211] netdata[2946070]: segfault at 318 ip 000055acc6f89cf4 sp 00007ffd77bd7310 error 4 in netdata[55acc6e20000+359000]
 kernel: [4484994.051216] Code: 55 4c 8d 2d e6 84 22 00 41 54 49 89 f4 55 48 89 fd 53 48 89 f3 48 83 ec 08 eb 0f 0f 1f 00 48 8b 9b e0 01 00 00 48 85 db 74 75 <48> 83 bb 28 01 00 00 00 74 ea 48 8b b3 30 01 00 00 48 8b bd 28 03
 systemd[1]: netdata.service: Main process exited, code=dumped, status=11/SEGV
 systemd[1]: netdata.service: Failed with result 'core-dump'.
 systemd[1]: Created slice User Slice of UID 0.
 systemd[1]: Starting User Runtime Directory /run/user/0...
 systemd[1]: Finished User Runtime Directory /run/user/0.
 systemd[1]: Starting User Manager for UID 0...

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment] 2022-07-01 08:13
@marliyev could you aslo share 
* Netdata build info
```
netdata -W buildinfo
# If get "netdata: command not found", try (required running Netdata)
$(ps aux | grep -m1 -E -o "[a-zA-Z/]+netdata ") -W buildinfo
```

* the [installation method](https://learn.netdata.cloud/docs/agent/packaging/installer#alternative-methods) you used.

![image](https://user-images.githubusercontent.com/82235632/176853733-d606125b-bf5e-49dc-b339-dd776afac719.png)

**Comment by marliyev** [comment] 2022-07-01 08:36
netdata -W buildinfo
Version: netdata v1.35.0-123-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES

**Comment by MrZammler** [comment] 2022-07-01 10:48
Hi @marliyev 

Can you please attach a snippet of `error.log` during the attempt to start? Thanks!

**Comment by marliyev** [comment] 2022-07-01 11:32
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001387.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001388.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001389.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001390.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001391.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001392.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001393.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001394.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001395.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001396.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001397.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001398.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001399.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001400.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : Scanning file "/var/cache/netdata/dbengine/journalfile-1-0000001401.njf"
2022-07-01 11:29:53: netdata INFO  : MAIN : SQLite aclk sync initialization
2022-07-01 11:29:53: netdata INFO  : MAIN : SQLite aclk sync initialization completed
2022-07-01 11:29:53: netdata INFO  : MAIN : File '/var/lib/netdata/cloud.d/claimed_id' was found. Setting state to AGENT_CLAIMED.
2022-07-01 11:29:53: netdata INFO  : MAIN : Health configuration for alarm 'oom_kill' cannot be applied, because the host k8s-prod-master01 does not have the label(s) '_is_k8s_node=false'
EOF found in spawn pipe.
Shutting down spawn server event loop.
Shutting down spawn server loop complete.

**Comment by marliyev** [comment] 2022-07-05 08:36
hi team, any update? i have 400 nodes and 90 of them unreachable coz of this issue, service not starting and some of them service up but still unreachable.

**Comment by MrZammler** [comment] 2022-07-05 08:48
Hi @marliyev sorry for the late reply. Do you have `coredumpctl` installed? Can you check for `coredumpctl list` if there is something for netdata?

**Comment by MrZammler** [comment] 2022-07-05 08:55
Also, does every failed start ends with `Health configuration for alarm 'oom_kill' cannot be applied, because the host k8s-prod-master01 does not have the label(s) '_is_k8s_node=false'` ?

Can you check if removing this alert (https://github.com/netdata/netdata/blob/dd01f896b466ed8411d58a816db8de2b940f7265/health/health.d/ram.conf#L36-L47) from `/usr/lib/netdata/conf.d/health.d/ram.conf` (it should be in that path) allows the agent to start ?

**Comment by marliyev** [comment] 2022-07-05 09:25
coredumpctl list
TIME                            PID   UID   GID SIG COREFILE  EXE
Tue 2022-07-05 09:23:28 UTC  2996884   112   119  11 present   /usr/sbin/netdata

i put this alert to silent, cant start

**Comment by marliyev** [comment] 2022-07-05 09:27
ahm, removed this alert completely from file and service started, looks good now

**Comment by marliyev** [comment] 2022-07-05 09:40
its directly installed on node not on k8s cluster, netdata on on k8s not working, after deploy showing all pods crashloopback

**Comment by ilyam8** [comment] 2022-07-05 10:32
I bumped into the same problem today, closing this issue in favor of #13304 because it is a more specific - condition when Netdata crashes and steps on how to reproduce it.

**Closed by ilyam8** 2022-07-05 10:32 UTC
Labels: bug, area/health

**Comment by marliyev** [comment] 2022-07-05 12:55
thanks
