### ISSUE TITLE
[Bug]: high cpu usage on master after alarms raised by slaves

### ISSUE THREAD

**Issue by ebiagi** [netdata/netdata#13830] opened 2022-10-15 00:32 UTC
### Bug description

I've a master and a couple of slave hosts, when one or more slaves alerts are raised (even when I reboot a slave host) the master netdata CPU usage raise a lot, not lowering until netdata is restarted

### Expected behavior

CPU usage not to grow

### Steps to reproduce

1. raise a test alarm or reboot a slave machine
2.
3.
...

### Installation method

kickstart.sh

### System info

```shell
Linux tsrv01 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
```

### Netdata build info

```shell
Version: netdata v1.34.0-202-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: legacy-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

![immagine](https://user-images.githubusercontent.com/58190975/195960735-b0093d05-69f8-4624-9c98-13d76433da67.png)

the culprit seems to be the stream receiver worker

![immagine](https://user-images.githubusercontent.com/58190975/195960767-d631fd39-c8ff-429d-b8ff-48220c807876.png)

![immagine](https://user-images.githubusercontent.com/58190975/195960789-260b24f1-a1c7-46ba-b9c0-7f1570b8b510.png)

**Comment by MrZammler** [comment] 2022-10-17 07:03
Hi @ebiagi thank for the report. Sorry for this. We'll try to replicate and find the cause.

**Comment by MrZammler** [comment] 2022-10-17 07:04
Is it possible to try with a newer nightly version? We're currently at -228.

**Comment by ebiagi** [comment] 2022-10-24 17:35
Sorry for the late answer, I've upgraded to the v1.36.0-257-nightly but I've also uninstalled and reconfigured the parent host, the problem disappeared.
I've tried to raise some alarms from one or two of the child hosts by stopping some services, the parent reports the alarm correctly but then the CPU is not touched anymore. 
I don't know if it's due to a configuration error, I've applied the previous config lines one by one starting from scratch and editing a new netdata.conf and stream.conf files

**Comment by Dim-P** [comment] 2022-10-24 17:53
@ebiagi Glad to hear it's resolved now, we will keep monitoring this internally to see if it happens on any of our parent - children setups. I am closing this now since it's not an issue anymore, but please prompt us if it occurs again so we can reopen it (or open a new ticket yourself).

**Comment by MrZammler** [comment] 2022-10-24 17:53
Hi @ebiagi thank you very much for the follow up.

There have been some changes since v1.34.0-202-nightly most likely something was fixed by now.

**Closed by Dim-P** 2022-10-24 17:53 UTC
Labels: bug, needs triage
