### ISSUE TITLE
apcupsd.chart does not generate the graph

### ISSUE THREAD

**Issue by vsc55** [netdata/netdata#9176] opened 2020-05-26 20:54 UTC
##### Bug report summary
The apcupsd.chart.sh script fetches the data correctly, but the graph says there is no data.

![image](https://user-images.githubusercontent.com/13438676/82949575-260c1380-9fa4-11ea-8ffe-f49ff2995e53.png)

##### OS / Environment
```
Linux cuernavilla 5.4.28-gentoo-x86_64 #2 SMP Tue Mar 31 11:01:04 CEST 2020 x86_64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz GenuineIntel GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.6
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo/Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:HOME_URL="https://www.gentoo.org/"
/etc/os-release:SUPPORT_URL="https://www.gentoo.org/support/"
/etc/os-release:BUG_REPORT_URL="https://bugs.gentoo.org/"
```

##### Netdata version
netdata v1.22.1-123-nightly

##### Component Name
charts.d/apcupsd.chart
web??

##### Steps To Reproduce
1. config apcupsd.chart:
`./edit-config charts.d/apcupsd.conf`
```
# no need for shebang - this file is loaded from charts.d.plugin

# netdata
# real-time performance and health monitoring, done right!
# (C) 2018 Costa Tsaousis <costa@tsaousis.gr>
# GPL v3+

# add all your APC UPSes in this array - uncomment it too
declare -A apcupsd_sources=(
    ["local"]="192.168.5.250:3551"
)

# how long to wait for apcupsd to respond
#apcupsd_timeout=3

# the data collection frequency
# if unset, will inherit the netdata update frequency
#apcupsd_update_every=10

# the charts priority on the dashboard
#apcupsd_priority=90000

# the number of retries to do in case of failure
# before disabling the module
#apcupsd_retries=10
```
2. Restar daemon netdata.

3. Go to the dashboard and to the UPS section, where the graph should come out, a message appears that says empty.

4. Check apcaccess = OK
```
# apcaccess
APC      : 001,036,0880
DATE     : 2020-05-26 22:49:20 +0200
HOSTNAME : *****
VERSION  : 3.14.14 (31 May 2016) gentoo
UPSNAME  : ******
CABLE    : USB Cable
DRIVER   : USB UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2020-05-26 18:50:10 +0200
MODEL    : Back-UPS RS 900G
STATUS   : ONLINE
LINEV    : 229.0 Volts
LOADPCT  : 42.0 Percent
BCHARGE  : 100.0 Percent
TIMELEFT : 22.2 Minutes
MBATTCHG : 0 Percent
MINTIMEL : 0 Minutes
MAXTIME  : 0 Seconds
SENSE    : Medium
LOTRANS  : 176.0 Volts
HITRANS  : 294.0 Volts
ALARMDEL : 30 Seconds
BATTV    : 27.1 Volts
LASTXFER : Automatic or explicit self test
NUMXFERS : 0
TONBATT  : 0 Seconds
CUMONBATT: 0 Seconds
XOFFBATT : N/A
SELFTEST : NO
STATFLAG : 0x05000008
SERIALNO : *****
BATTDATE : 2013-11-10
NOMINV   : 230 Volts
NOMBATTV : 24.0 Volts
NOMPOWER : 540 Watts
FIRMWARE : 879.L4 .I USB FW:L4
END APC  : 2020-05-26 22:49:21 +0200
```

5. Check plugin = OK
```
# /usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 apcupsd
2020-05-26 22:51:16: charts.d: INFO: main: started from '/usr/libexec/netdata/plugins.d/charts.d.plugin' with options: debug 1 apcupsd
2020-05-26 22:51:16: charts.d: INFO: main: Configuration file '/usr/lib/netdata/conf.d/charts.d.conf' loaded.
2020-05-26 22:51:16: charts.d: INFO: main: Configuration file '/etc/netdata/charts.d.conf' loaded.
2020-05-26 22:51:16: charts.d: INFO: ap: is disabled. Add a line with ap=yes in '/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2020-05-26 22:51:16: charts.d: DEBUG: apcupsd: is enabled for auto-detection.
2020-05-26 22:51:16: charts.d: INFO: example: is disabled. Add a line with example=force in '/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2020-05-26 22:51:16: charts.d: INFO: libreswan: is disabled. Add a line with libreswan=yes in '/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2020-05-26 22:51:16: charts.d: INFO: nut: is disabled. Add a line with nut=yes in '/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2020-05-26 22:51:16: charts.d: INFO: opensips: is disabled. Add a line with opensips=yes in '/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2020-05-26 22:51:16: charts.d: INFO: sensors: is disabled. Add a line with sensors=force in '/etc/netdata/charts.d.conf' to enable it (or remove the line that disables it).
2020-05-26 22:51:16: charts.d: DEBUG: main: enabled charts:  apcupsd
2020-05-26 22:51:16: charts.d: DEBUG: apcupsd: loading module: '/usr/libexec/netdata/plugins.d/../charts.d/apcupsd.chart.sh'
2020-05-26 22:51:16: charts.d: DEBUG: apcupsd: loading module configuration: '/usr/lib/netdata/conf.d/charts.d/apcupsd.conf'
2020-05-26 22:51:16: charts.d: DEBUG: apcupsd: loading module configuration: '/etc/netdata/charts.d/apcupsd.conf'
2020-05-26 22:51:16: charts.d: DEBUG: apcupsd: module 'apcupsd' activated
2020-05-26 22:51:16: charts.d: DEBUG: main: activated modules:  apcupsd
2020-05-26 22:51:16: charts.d: DEBUG: main: requested to run only for: 'apcupsd'
2020-05-26 22:51:16: charts.d: DEBUG: main: activated charts: apcupsd
2020-05-26 22:51:16: charts.d: DEBUG: apcupsd: calling 'apcupsd_create()'...
CHART apcupsd_local.charge '' "UPS Charge for local on 192.168.5.250:3551" "percentage" ups apcupsd.charge area 90001 10
DIMENSION battery_charge charge absolute 1 100

CHART apcupsd_local.battery_voltage '' "UPS Battery Voltage for local on 192.168.5.250:3551" "Volts" ups apcupsd.battery.voltage line 90003 10
DIMENSION battery_voltage voltage absolute 1 100
DIMENSION battery_voltage_nominal nominal absolute 1 100

CHART apcupsd_local.input_voltage '' "UPS Input Voltage for local on 192.168.5.250:3551" "Volts" input apcupsd.input.voltage line 90004 10
DIMENSION input_voltage voltage absolute 1 100
DIMENSION input_voltage_min min absolute 1 100
DIMENSION input_voltage_max max absolute 1 100

CHART apcupsd_local.input_frequency '' "UPS Input Frequency for local on 192.168.5.250:3551" "Hz" input apcupsd.input.frequency line 90005 10
DIMENSION input_frequency frequency absolute 1 100

CHART apcupsd_local.output_voltage '' "UPS Output Voltage for local on 192.168.5.250:3551" "Volts" output apcupsd.output.voltage line 90006 10
DIMENSION output_voltage voltage absolute 1 100
DIMENSION output_voltage_nominal nominal absolute 1 100

CHART apcupsd_local.load '' "UPS Load for local on 192.168.5.250:3551" "percentage" ups apcupsd.load area 90000 10
DIMENSION load load absolute 1 100

CHART apcupsd_local.temp '' "UPS Temperature for local on 192.168.5.250:3551" "Celsius" ups apcupsd.temperature line 90007 10
DIMENSION temp temp absolute 1 100

CHART apcupsd_local.time '' "UPS Time Remaining for local on 192.168.5.250:3551" "Minutes" ups apcupsd.time area 90002 10
DIMENSION time time absolute 1 100

CHART apcupsd_local.online '' "UPS ONLINE flag for local on 192.168.5.250:3551" "boolean" ups apcupsd.online line 90008 10
DIMENSION online online absolute 0 1

2020-05-26 22:51:16: charts.d: DEBUG: apcupsd: 'apcupsd' initialized.
2020-05-26 22:51:16: charts.d: DEBUG: main: run_charts=' apcupsd'
CHART netdata.plugin_chartsd_apcupsd '' 'Execution time for apcupsd plugin' 'milliseconds / run' charts.d netdata.plugin_charts area 145000 10
DIMENSION run_time 'run time' absolute 1 1
2020-05-26 22:51:16: charts.d: DEBUG: apcupsd: sleeping for 3.121 seconds.
BEGIN apcupsd_local.online
SET online = 1
END
BEGIN apcupsd_local.charge
SET battery_charge = 10000
END
BEGIN apcupsd_local.battery_voltage
SET battery_voltage = 2710
SET battery_voltage_nominal = 2400
END
BEGIN apcupsd_local.input_voltage
SET input_voltage = 22900
SET input_voltage_min = 0
SET input_voltage_max = 0
END
BEGIN apcupsd_local.input_frequency
SET input_frequency = 0
END
BEGIN apcupsd_local.output_voltage
SET output_voltage = 0
SET output_voltage_nominal = 0
END
BEGIN apcupsd_local.load
SET load = 4200
END
BEGIN apcupsd_local.temp
SET temp = 0
END
BEGIN apcupsd_local.time
SET time = 2220
END
BEGIN netdata.plugin_chartsd_apcupsd
SET run_time = 490
END
2020-05-26 22:51:20: charts.d: DEBUG: apcupsd: sleeping for 9.511 seconds.
BEGIN apcupsd_local.online 10000000
SET online = 1
END
BEGIN apcupsd_local.charge 10000000
SET battery_charge = 10000
END
BEGIN apcupsd_local.battery_voltage 10000000
SET battery_voltage = 2690
SET battery_voltage_nominal = 2400
END
BEGIN apcupsd_local.input_voltage 10000000
SET input_voltage = 22900
SET input_voltage_min = 0
SET input_voltage_max = 0
END
BEGIN apcupsd_local.input_frequency 10000000
SET input_frequency = 0
END
BEGIN apcupsd_local.output_voltage 10000000
SET output_voltage = 0
SET output_voltage_nominal = 0
END
BEGIN apcupsd_local.load 10000000
SET load = 4100
END
BEGIN apcupsd_local.temp 10000000
SET temp = 0
END
BEGIN apcupsd_local.time 10000000
SET time = 2280
END
BEGIN netdata.plugin_chartsd_apcupsd 10000000
SET run_time = 10
END
2020-05-26 22:51:30: charts.d: DEBUG: apcupsd: sleeping for 9.991 seconds.
^Ccharts.d: cleaning up temporary directory /var/run/netdata-charts.d-cK8YCXYaj6 ...
```

##### Expected behavior
That the graph is generated.

**Comment by vsc55** [comment] 2020-05-26 21:40
Json api:
`http://localhost:19999/api/v1/data?chart=apcupsd_local.charge&_=1590529034013&format=json&points=411&group=average&gtime=0&options=ms%7Cflip%7Cjsonwrap%7Cnonzero&after=-480`
```json
{
   "api": 1,
   "id": "apcupsd_local.charge",
   "name": "apcupsd_local.charge",
   "view_update_every": 1,
   "update_every": 10,
   "first_entry": 0,
   "last_entry": 0,
   "before": 0,
   "after": 0,
   "dimension_names": ["no data"],
   "dimension_ids": ["no data"],
   "latest_values": [null],
   "view_latest_values": [null],
   "dimensions": 0,
   "points": 0,
   "format": "json",
   "result": {
 "labels": ["time", "no data"],
    "data":
 [

  ]
},
 "min": 0,
 "max": 0
}
```

**Comment by ilyam8** [comment] 2020-05-26 21:57
> netdata v1.22.1-123-nightly

hi @vsc55 it is likely duplicate of #9166

**Comment by ilyam8** [comment] 2020-05-26 21:59
The problem is fixed in latest, check it. Im closing the issue, if there are still problems please report back.

**Closed by ilyam8** 2020-05-26 21:59 UTC
Labels: bug, needs triage
