### ISSUE TITLE
failed to bulid

### ISSUE THREAD

**Issue by longtrip1** [netdata/netdata#9660] opened 2020-08-04 19:32 UTC
#### Summary
Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

   If your system cannot find libuuid, although it is installed
   run me with the option:  --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

   If your system cannot find zlib, although it is installed
   run me with the option:  --libs-are-really-here

3. The package json-c-dev (or json-c-devel) has to be installed.

   If your system cannot find json-c, although it is installed
   run me with the option:  --libs-are-really-here

4. You need basic build tools installed, like:

   gcc make autoconf automake pkg-config

   Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

   https://github.com/netdata/netdata/issues
failed to build netdata,what do i do now.
debian7.9

**Comment by hffej01** [comment] 2020-08-12 02:42
I'm having the same issues on Centos 8.  With all of the above being installed.

**Comment by prologic** [comment] 2020-08-13 11:46
Hi @longtrip1 Can you please confirm the steps you used to attempt the installation? Thanks!

**Comment by Odroid-Dude** [comment] 2020-08-27 03:33
I'm getting the same error on macOS (mojave) after running.
`sudo LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" ./netdata-installer.sh --install /usr/local --disable-telemetry --require-cloud`
I was running that because after trying o install via Homebrew I was receiving error `netdata-claim.sh: command not found` when trying to claim a node in netdata_cloud. From here [https://github.com/netdata/netdata/issues/8862#issuecomment-643866479](url)

**Comment by prologic** [comment] 2020-08-27 05:29
This worked fine for me on macOS Catalina 🤷‍♂️ I don't easily have a way to test this on an older macOS version. Some help would be appreicated by the community here.

**Comment by prologic** [comment] 2020-08-31 04:00
I am closing this as I cannot reproduce this problem on either macOS nor CentOS 8. We actually have CI for the later, so _this_ very likely bois down to an environment problem. If you are still experiencing this problem on either platform, __please__ file a bug report with reproducible details we can verify and fix! Thank you. 🙇‍♂️

**Closed by prologic** 2020-08-31 04:00 UTC
Labels: Cannot reproduce, question
