### ISSUE TITLE
High CPU Usage and stop working with apache proxypass

### ISSUE THREAD

**Issue by EdgardoSchiffer** [netdata/netdata#6246] opened 2019-06-07 20:43 UTC
##### Question summary
I recently installed netdata on a 6 server enviroment, and it works fine on all servers but one, the task of this server is to listen and answer to (around) 25k sockets concurrently. For the access to netdata of each server, I configured in the server which resolves my DNS some proxypass rules on apache, and the problem with this last server is that when I access via the DNS netdata just load the first second and then it does not resolve any request, when I check in the server CPU usage for all cores is 100% when it is usually around 40% on each core.
Whenever I access via the server IP everything works fine.

<img width="1028" alt="netdata" src="https://user-images.githubusercontent.com/9885037/59131782-838cf780-8930-11e9-8138-77f58d0f45ff.png">

There's the netdata Application->CPU Graph, which show how the CPU usage increased suddenly by netdata's and how it became normal when I restarted the service.

<img width="1059" alt="netdata2" src="https://user-images.githubusercontent.com/9885037/59131981-1cbc0e00-8931-11e9-93b7-c01ee7572158.png">

Also netdata stats:

<img width="949" alt="netdata3" src="https://user-images.githubusercontent.com/9885037/59132467-7ffa7000-8932-11e9-8f31-54b2e2a1e2a4.png">
<img width="945" alt="netdata4" src="https://user-images.githubusercontent.com/9885037/59132466-7ffa7000-8932-11e9-88f8-430f01836b7b.png">
<img width="952" alt="netdata5" src="https://user-images.githubusercontent.com/9885037/59132465-7ffa7000-8932-11e9-8155-99df34ef7afe.png">
<img width="978" alt="netdata6" src="https://user-images.githubusercontent.com/9885037/59132464-7ffa7000-8932-11e9-99d3-ab9d675c4766.png">

I attach the logs generated when the problem occurs.

[access.log](https://github.com/netdata/netdata/files/3267466/access.log)
[error.log](https://github.com/netdata/netdata/files/3267467/error.log)

**Comment by ilyam8** [comment] 2019-06-07 20:58
Hi @EdgardoSchiffer 	

i think you faced same problem as in https://github.com/netdata/netdata/issues/6244#issuecomment-499938637

which is fixed in latest version.

Could you update your netdata and check if the problem is gone?

**Comment by EdgardoSchiffer** [comment] 2019-06-07 21:37
Thanks, seems to be fixed. 
If the issue persist I'll let you know.

**Comment by ilyam8** [comment] 2019-06-07 21:44
@EdgardoSchiffer nice the problem is solved, sorry for this :cry: 

i am closing the issue in favor of #6244

**Closed by ilyam8** 2019-06-07 21:44 UTC
Labels: no changelog, question
