### ISSUE TITLE
[Question]: Is netdata eBPF plugin crashing server?

### ISSUE THREAD

**Issue by vobruba-martin** [netdata/netdata#12073] opened 2022-02-02 14:42 UTC
### Bug description

I'm investigating issues with our mysql database (threads being stopped, server crashing). I'm just curious if netdata eBPF plugin couldn't be somehow related because of this line I see in Call trace:
```
kernel: [1609020.026497]  bpf_prog_896bb3a8c2cab17b_netdata_tcp_sendmsg+0xbc/0x718
```

### Expected behavior

No server crashing

### Steps to reproduce

For now I have no idea.

### Installation method

kickstart.sh

### System info

```shell
Linux myairbridge12 5.13.0-25-generic #26~20.04.1-Ubuntu SMP Fri Jan 7 16:27:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.3 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.3 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.33.0
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-protobuf' 'CFLAGS=-O2' 'LDFLAGS='
Install type: kickstart-build
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                NO
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

Full report:
```
kernel: [1609020.014208] BUG: unable to handle page fault for address: ffffffffff600dee
kernel: [1609020.014957] #PF: supervisor read access in kernel mode
kernel: [1609020.015393] #PF: error_code(0x0000) - not-present page
kernel: [1609020.015790] PGD 3843014067 P4D 3843015067 PUD 3843017067 PMD 3843019067 PTE 0
kernel: [1609020.016184] Oops: 0000 [#31] SMP NOPTI
kernel: [1609020.016576] CPU: 91 PID: 2019236 Comm: mysqld Tainted: G      D           5.13.0-25-generic #26~20.04.1-Ubuntu
kernel: [1609020.016984] Hardware name: HPE ProLiant DL380 Gen10 Plus/ProLiant DL380 Gen10 Plus, BIOS U46 11/03/2021
kernel: [1609020.017400] RIP: 0010:copy_from_kernel_nofault+0xbe/0x110
kernel: [1609020.017822] Code: 5d 5d c3 4c 89 e1 49 83 fd 03 76 16 31 c0 8b 13 89 11 85 c0 75 cf 48 83 c1 04 48 83 c3 04 49 83 ed 04 49 83 fd 01 76 18 31 c0 <66> 8b 13 66 89 11 85 c0 75 b1 48 83 c1 02 48 83 c3 02 49 83 ed 02
kernel: [1609020.018820] RSP: 0018:ff2c976cc806f9c0 EFLAGS: 00010246
kernel: [1609020.019372] RAX: 0000000000000000 RBX: ffffffffff600dee RCX: ff2c976cc806fa68
kernel: [1609020.019932] RDX: 0000000000000002 RSI: 0000000000000002 RDI: ffffffffff600dee
kernel: [1609020.020493] RBP: ff2c976cc806f9d8 R08: 0000000000000001 R09: 0000000000000101
kernel: [1609020.021055] R10: 0000000000000000 R11: 0000000000000001 R12: ff2c976cc806fa68
kernel: [1609020.021616] R13: 0000000000000002 R14: 000000000000000b R15: 0000000b00000000
kernel: [1609020.022174] FS:  00007efe71fc5700(0000) GS:ff2667893f8c0000(0000) knlGS:0000000000000000
kernel: [1609020.022729] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
kernel: [1609020.023271] CR2: ffffffffff600dee CR3: 0000000e5d4f2002 CR4: 0000000000771ee0
kernel: [1609020.023814] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
kernel: [1609020.024352] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
kernel: [1609020.024886] PKRU: 55555554
kernel: [1609020.025418] Call Trace:
kernel: [1609020.025955]  bpf_probe_read_compat+0x64/0x90
kernel: [1609020.026497]  bpf_prog_896bb3a8c2cab17b_netdata_tcp_sendmsg+0xbc/0x718
kernel: [1609020.027030]  trace_call_bpf+0x66/0xf0
kernel: [1609020.027547]  kretprobe_perf_func+0x50/0x270
kernel: [1609020.028050]  ? tcp_schedule_loss_probe+0x115/0x1b0
kernel: [1609020.028540]  ? tcp_write_xmit+0x552/0xcc0
kernel: [1609020.029014]  kretprobe_dispatcher+0x6c/0x80
kernel: [1609020.029475]  ? inet_sendmsg+0x43/0x70
kernel: [1609020.029934]  __kretprobe_trampoline_handler+0xad/0xe0
kernel: [1609020.030396]  trampoline_handler+0x48/0x60
kernel: [1609020.030855]  kretprobe_trampoline+0x2a/0x50
kernel: [1609020.031303] RIP: 0010:kretprobe_trampoline+0x0/0x50
kernel: [1609020.031742] Code: 89 fc e8 43 a5 01 00 4c 89 f2 4c 89 ee 4c 89 e7 44 0f b6 c0 31 c9 e8 4f 17 36 00 41 5c 41 5d 41 5e 5d c3 cc cc cc cc cc cc cc <54> 9c 48 83 ec 18 57 56 52 51 50 41 50 41 51 41 52 41 53 53 55 41
kernel: [1609020.032647] RSP: c806fd10:ff2c976cc806fcb0 EFLAGS: 00000286
kernel: [1609020.033104] RAX: 000000000000000b RBX: 0000000000000040 RCX: 0000000000000000
kernel: [1609020.033566] RDX: 0000000000000000 RSI: ff2667736fa6e008 RDI: ffffffffff600dde
kernel: [1609020.034028] RBP: ff2c976cc806fcc8 R08: 000fbe39db6e9dee R09: 0000000000000101
kernel: [1609020.034496] R10: 0000000000000000 R11: 0000000000000001 R12: ff2c976cc806fd10
kernel: [1609020.034961] R13: 000000000000000b R14: ff26677329244ec0 R15: 0000000000000000
kernel: [1609020.035423]  sock_sendmsg+0x5e/0x70
kernel: [1609020.035879]  __sys_sendto+0x113/0x190
kernel: [1609020.036331]  ? __cgroup_account_cputime+0x28/0x30
kernel: [1609020.036790]  ? update_curr+0x108/0x1c0
kernel: [1609020.037243]  ? update_curr_fair+0x1c/0x20
kernel: [1609020.037688]  __x64_sys_sendto+0x29/0x30
kernel: [1609020.038126]  do_syscall_64+0x61/0xb0
kernel: [1609020.038576]  ? syscall_exit_to_user_mode+0x27/0x50
kernel: [1609020.039010]  ? do_syscall_64+0x6e/0xb0
kernel: [1609020.039439]  ? do_syscall_64+0x6e/0xb0
kernel: [1609020.039855]  ? syscall_exit_to_user_mode+0x27/0x50
kernel: [1609020.040262]  ? do_syscall_64+0x6e/0xb0
kernel: [1609020.040660]  ? syscall_exit_to_user_mode+0x27/0x50
kernel: [1609020.041049]  ? do_syscall_64+0x6e/0xb0
kernel: [1609020.041427]  ? do_syscall_64+0x6e/0xb0
kernel: [1609020.041790]  ? common_interrupt+0x5a/0xa0
kernel: [1609020.042149]  ? asm_common_interrupt+0x8/0x40
kernel: [1609020.042507]  entry_SYSCALL_64_after_hwframe+0x44/0xae
kernel: [1609020.042866] RIP: 0033:0x7f198915377c
kernel: [1609020.043222] Code: 89 4c 24 1c e8 85 f8 ff ff 44 8b 54 24 1c 8b 3c 24 45 31 c9 89 c5 48 8b 54 24 10 48 8b 74 24 08 45 31 c0 b8 2c 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 30 89 ef 48 89 04 24 e8 b1 f8 ff ff 48 8b 04
kernel: [1609020.043983] RSP: 002b:00007efe71fc3fa0 EFLAGS: 00000246 ORIG_RAX: 000000000000002c
kernel: [1609020.044368] RAX: ffffffffffffffda RBX: 00007ef590017b40 RCX: 00007f198915377c
kernel: [1609020.044751] RDX: 000000000000000b RSI: 00007ef5900008f0 RDI: 000000000000013c
kernel: [1609020.045134] RBP: 0000000000000000 R08: 0000000000000000 R09: 0000000000000000
kernel: [1609020.045519] R10: 0000000000000040 R11: 0000000000000246 R12: 000000000000000b
kernel: [1609020.045897] R13: 0000000000000040 R14: 00007ef5900008f0 R15: 000000000000013c
kernel: [1609020.046276] Modules linked in: bonding tls tcp_bbr sch_fq intel_rapl_msr intel_rapl_common ipmi_ssif xfs nfit libcrc32c x86_pkg_temp_thermal intel_powerclamp coretemp crct10dif_pclmul ghash_clmulni_intel aesni_intel crypto_simd cryptd rapl serio_raw mgag200 drm_kms_helper isst_if_mbox_pci cec rc_core isst_if_mmio i2c_algo_bit isst_if_common fb_sys_fops syscopyarea sysfillrect sysimgblt hpilo acpi_ipmi ioatdma ipmi_si intel_pch_thermal dca acpi_tad ipmi_devintf ipmi_msghandler mac_hid acpi_power_meter drm ip_tables x_tables autofs4 ses enclosure smartpqi xhci_pci crc32_pclmul psmouse ice scsi_transport_sas intel_pmt wmi xhci_pci_renesas
kernel: [1609020.048840] CR2: ffffffffff600dee
kernel: [1609020.049287] ---[ end trace 19f16efaf8dee450 ]---
kernel: [1609020.059932] RIP: 0010:copy_from_kernel_nofault+0xbe/0x110
kernel: [1609020.060401] Code: 5d 5d c3 4c 89 e1 49 83 fd 03 76 16 31 c0 8b 13 89 11 85 c0 75 cf 48 83 c1 04 48 83 c3 04 49 83 ed 04 49 83 fd 01 76 18 31 c0 <66> 8b 13 66 89 11 85 c0 75 b1 48 83 c1 02 48 83 c3 02 49 83 ed 02
kernel: [1609020.061355] RSP: 0018:ff2c976ca1e2f9d8 EFLAGS: 00010246
kernel: [1609020.061836] RAX: 0000000000000000 RBX: ffffffffff600f65 RCX: ff2c976ca1e2fa80
kernel: [1609020.062315] RDX: 0000000000000002 RSI: 0000000000000002 RDI: ffffffffff600f65
kernel: [1609020.062784] RBP: ff2c976ca1e2f9f0 R08: 0000000000000001 R09: 0000000000000101
kernel: [1609020.063246] R10: 0000000000000000 R11: 0000000000000002 R12: ff2c976ca1e2fa80
kernel: [1609020.063705] R13: 0000000000000002 R14: 0000000000000137 R15: 0000013700000000
kernel: [1609020.064162] FS:  00007efe71fc5700(0000) GS:ff2667893f8c0000(0000) knlGS:0000000000000000
kernel: [1609020.064623] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
kernel: [1609020.065080] CR2: ffffffffff600dee CR3: 0000000e5d4f2002 CR4: 0000000000771ee0
kernel: [1609020.065544] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
kernel: [1609020.066003] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
kernel: [1609020.066462] PKRU: 55555554
```

**Comment by ilyam8** [comment] 2022-02-02 14:44
Hi, @vobruba-martin. Looks like the same issue as https://github.com/netdata/netdata/issues/12027.

**Comment by ilyam8** [comment] 2022-02-02 15:17
Closing as duplicate of #12027.

**Closed by ilyam8** 2022-02-02 15:17 UTC
Labels: bug, duplicate, needs triage, area/ebpf

**Comment by thiagoftsm** [comment] 2022-02-03 13:00
Thank you @vobruba-martin to give the detailed information about the problem, I am working on this issue right now.
