### ISSUE TITLE
[Bug]: Install of 1.34.1 on macOS Big Surr failes - ${tmpdir} empty string

### ISSUE THREAD

**Issue by rickard-von-essen** [netdata/netdata#12717] opened 2022-04-19 09:08 UTC
### Bug description

Installation of 1.34.1 on _macOS Big Surr_ failes

```
$ wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh                               
--2022-04-19 10:41:27--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 188.114.97.2, 188.114.96.2
Connecting to my-netdata.io (my-netdata.io)|188.114.97.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

/tmp/netdata-kickstart.sh                                   [ <=>                                                                                                                         ]  59.50K  --.-KB/s    in 0.003s

2022-04-19 10:41:27 (21.9 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [60928]


 --- Checking for existing installations of Netdata... ---
Enter PIN for 'Certificate For PIV Authentication (Yubico PIV Authentication)':
sh: /install-type: Read-only file system
/tmp/netdata-kickstart.sh: line 737: /install-type: No such file or directory
 ERROR  Installer exited unexpectedly (0-737)

This is almost certainly the result of a bug. If you have time, please report it at https://github.com/netdata/netdata/issues/new/choose.
```

### Expected behavior

Installs Netdata without issues.

### Steps to reproduce

1. `wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh`

### Installation method

kickstart.sh

### System info

```shell
Darwin Rickards-MBP.desdichado.se 20.6.0 Darwin Kernel Version 20.6.0: Sun Feb  6 22:48:00 PST 2022; root:xnu-7195.141.24~1/RELEASE_X86_64 x86_64
ProductName:    macOS
ProductVersion: 11.6.5
BuildVersion:   20G517
```

### Netdata build info

```shell
n/a
```

### Additional info

Installing with Homebrew produces a non-working binary,

See https://github.com/Homebrew/homebrew-core/pull/99626

```
$ netdata -W buildinfo

Version: netdata v1.34.1
Configure options:  '--disable-dependency-tracking' '--disable-silent-rules' '--prefix=/usr/local/Cellar/netdata/1.34.1' '--sysconfdir=/usr/local/etc' '--localstatedir=/usr/local/var' '--libexecdir=/usr/local/Cellar/netdata/1.34.1/libexec' '--with-math' '--with-zlib' '--enable-dbengine' '--with-user=netdata' 'UUID_LIBS=-lc' 'UUID_CFLAGS=-I/usr/include' 'CC=clang' 'CFLAGS=-I/private/tmp/netdata-20220419-31357-7ny9v1/netdata-v1.34.1/resources/judy/include' 'LDFLAGS=-L/private/tmp/netdata-20220419-31357-7ny9v1/netdata-v1.34.1/resources/judy/lib' 'CXX=clang++' 'PKG_CONFIG_PATH=/usr/local/opt/json-c/lib/pkgconfig:/usr/local/opt/libuv/lib/pkgconfig:/usr/local/opt/lz4/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/protobuf/lib/pkgconfig:/usr/local/opt/protobuf-c/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    NO
    cgroup Network Tracking: NO
    CUPS:                    YES
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES

$ netdata -D   
fish: Job 1, 'netdata -D' terminated by signal SIGABRT (Abort)
```

**Comment by MrZammler** [comment] 2022-04-19 10:01
Hi @rickard-von-essen ! Can you please share the `error.log` from the execution of Netdata from homebrew? It should be under `/usr/local/var/log/netdata`.

Thanks!

**Comment by iigorkarpov** [comment] 2022-04-19 10:14
I would say it is an installation via kickstart.sh. It does assume Homebrew on the system, but technically speaking, a Homebrew installation looks like

brew install netdata

I can't reproduce this error on Monterrey - everything goes perfectly fine. Judging by the log, there are at least two suspicious places:

a) the use of yubikey keys and error message produced during/after authorization.
b) using fish as the default shell.


` --- Install go.d.plugin ---
[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# curl -q -sSL --connect-timeout 10 --retry 3 --output /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-go-XXXXXX.VhRANUHS/go.d.plugin-v0.32.2.darwin-amd64.tar.gz https://github.com/netdata/go.d.plugin/releases/download/v0.32.2/go.d.plugin-v0.32.2.darwin-amd64.tar.gz
 OK

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# curl -q -sSL --connect-timeout 10 --retry 3 --output /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-go-XXXXXX.VhRANUHS/config.tar.gz https://github.com/netdata/go.d.plugin/releases/download/v0.32.2/config.tar.gz
 OK

go.d.plugin-v0.32.2.darwin-amd64.tar.gz: OK
config.tar.gz: OK
[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# rm -rf /usr/local/netdata/usr/lib/netdata/conf.d/go.d
 OK

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# rm -rf /usr/local/netdata/usr/lib/netdata/conf.d/go.d.conf
 OK

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# tar --no-same-owner -xf /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-go-XXXXXX.VhRANUHS/config.tar.gz -C /usr/local/netdata/usr/lib/netdata/conf.d/
 OK

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# chown -R root: /usr/local/netdata/usr/lib/netdata/conf.d
 OK

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# tar --no-same-owner -xf /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-go-XXXXXX.VhRANUHS/go.d.plugin-v0.32.2.darwin-amd64.tar.gz
 OK

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# mv go.d.plugin-v0.32.2.darwin-amd64 /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin
 OK

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# chown root:staff /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin
 OK

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# chmod 0750 /usr/local/netdata/usr/libexec/netdata/plugins.d/go.d.plugin
 OK

 --- eBPF Kernel Collector ---
 FAILED  Currently eBPF is only supported on Linux on X86_64.

 --- Telemetry configuration ---
You can opt out from anonymous statistics via the --disable-telemetry option, or by creating an empty file /usr/local/netdata/etc/netdata/.opt-out-from-anonymous-statistics

 --- Install netdata at system init ---
file '/Library/LaunchDaemons/com.github.netdata.plist' already exists.
 --- Restarting netdata instance ---

Stopping all netdata threads
[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# stop_all_netdata
 OK

Starting netdata using command '/usr/local/netdata/usr/sbin/netdata'
[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# /usr/local/netdata/usr/sbin/netdata
2022-04-19 12:57:43: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/usr/local/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2022-04-19 12:57:43: netdata INFO  : MAIN : Found 0 legacy dbengines, setting multidb diskspace to 256MB
2022-04-19 12:57:43: netdata INFO  : MAIN : Created file '/usr/local/netdata/var/lib/netdata/dbengine_multihost_size' to store the computed value
 OK

 OK  netdata started!

Downloading default configuration from netdata...
[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# curl -sSL --connect-timeout 10 --retry 3 http://localhost:19999/netdata.conf
 OK

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# mv /usr/local/netdata/etc/netdata/netdata.conf.new /usr/local/netdata/etc/netdata/netdata.conf
 OK

 OK  New configuration saved for you to edit at /usr/local/netdata/etc/netdata/netdata.conf

[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# chmod 0644 /usr/local/netdata/etc/netdata/netdata.conf
 OK

 --- Check version.txt ---
 --- Copy uninstaller ---
 --- Basic netdata instructions ---

netdata by default listens on all IPs on port 19999,
so you can access it with:

  http://this.machine.ip:19999/

To stop netdata run:

  /usr/local/netdata/usr/sbin/netdatacli shutdown-agent

To start netdata run:

  /usr/local/netdata/usr/sbin/netdata

Uninstall script copied to: /usr/local/netdata/usr/libexec/netdata/netdata-uninstaller.sh

 --- Installing (but not enabling) the netdata updater tool ---
Update script is located at /usr/local/netdata/usr/libexec/netdata/netdata-updater.sh

 --- Wrap up environment set up ---
Preparing .environment file
[/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/netdata-v1.34.0-12-gfe3bea8a1]# chmod 0644 /usr/local/netdata/etc/netdata/.environment
 OK

Setting netdata.tarball.checksum to 'new_installation'

The following non-fatal errors were encountered during the installation process:
\n* Currently eBPF is only supported on Linux on X86_64.

 --- We are done! ---

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata  .-.   .-.   .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'               '-'   '-'   '-'   '-'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

 --- is installed and running now! ---
  enjoy real-time performance and health monitoring...

 OK

Tue Apr 19 12:57:59 EEST 2022 : INFO: netdata-updater.sh:  Auto-updating has been ENABLED through cron, updater script linked to /etc/periodic/daily/netdata-updater

Tue Apr 19 12:57:59 EEST 2022 : INFO: netdata-updater.sh:  If the update process fails and you have email notifications set up correctly for cron on this system, you should receive an email notification of the failure.
Tue Apr 19 12:57:59 EEST 2022 : INFO: netdata-updater.sh:  Successful updates will not send an email.
Successfully installed the Netdata Agent.

The following non-fatal warnings or errors were encountered:

  - Command "/bin/bash /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/netdata-kickstart-XXXXXXXXXX.XMLAefe1/install-required-packages.sh netdata" failed with exit code 1.
  - Failed to install all required packages, but installation might still be possible.

Official documentation can be found online at https://learn.netdata.cloud/docs/.

Looking to monitor all of your infrastructure with Netdata? Check out Netdata Cloud at https://app.netdata.cloud.

Join our community and connect with us on:
  - GitHub: https://github.com/netdata/netdata/discussions
  - Discord: https://discord.gg/5ygS846fR6
  - Our community forums: https://community.netdata.cloud/`

**Comment by rickard-von-essen** [comment] 2022-04-19 11:37
> /usr/local/var/log/netdata/error.log

[error.log](https://github.com/netdata/netdata/files/8512608/error.log)

**Comment by rickard-von-essen** [comment] 2022-04-19 11:43
> a) the use of yubikey keys and error message produced during/after authorization.
> b) using fish as the default shell.

Ruling out both of these, removing my Yubikey and setting `SHELL=/bin/bash` and entering `bash`.

```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Rickards-MBP:homebrew-core rickard$ printenv | grep SHELL
NODENV_SHELL=fish
SHELL=/bin/bash
RBENV_SHELL=fish
Rickards-MBP:homebrew-core rickard$ wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
--2022-04-19 13:40:02--  https://my-netdata.io/kickstart.sh
Resolving my-netdata.io (my-netdata.io)... 188.114.97.2, 188.114.96.2
Connecting to my-netdata.io (my-netdata.io)|188.114.97.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/tmp/netdata-kickstart.sh’

/tmp/netdata-kickstart.sh                                  [ <=>                                                                                                                      ]  59.50K  --.-KB/s    in 0.01s

2022-04-19 13:40:02 (5.59 MB/s) - ‘/tmp/netdata-kickstart.sh’ saved [60928]


 --- Checking for existing installations of Netdata... ---
Password:
sh: /install-type: Read-only file system
/tmp/netdata-kickstart.sh: line 737: /install-type: No such file or directory
 ERROR  Installer exited unexpectedly (0-737)

This is almost certainly the result of a bug. If you have time, please report it at https://github.com/netdata/netdata/issues/new/choose.
```

Same issue. 

> I can't reproduce this error on Monterrey

Looking at the Homebrew PR CI builds there seems to be some discrepancies between Monterrey and Big Surr since the build fails on 12 but builds fine on my 11.

**Comment by iigorkarpov** [comment] 2022-04-19 12:22
@rickard-von-essen thank you for excluding both suspects. I misread the log regarding Yubikey. There's nothing wrong about it.
Actually, somehow $tmpdir is undefined in line 737. So kickstart.sh makes an attempt to create /install-type and fails, because macOS does not allow writing to protected parts of the system (System Integrity Protection).

**Comment by rickard-von-essen** [comment] 2022-04-19 13:09
Ok, uninstalling the 🍺  Homebrew installed netdata resolves this issue. Seems like having a homebrew installed version trips up the script in some way.

**Comment by rickard-von-essen** [comment] 2022-04-19 17:02
> off-topic: @rickard-von-essen what are the reasons we [don't add go.d.plugin](https://github.com/netdata/go.d.plugin/issues/677) we creating brew package?

I guess it's just legacy since it didn't exist when I originally created the homebrew packaging formula. But now when there are some native packages (rpm/deb) it's much easier to reverse engineer and verify the package content comparing the different types. Let me review the content in 1.34.1 since it's anyway broken somehow.

**Comment by rickard-von-essen** [comment] 2022-04-20 07:26
@iigorkarpov IMHO I think this is a bug. This should be properly handled with a nice error message or so.

**Comment by iigorkarpov** [comment] 2022-04-20 07:41
I agree with you. This can be easily 'fixed' with such an error messages. But the real solution suggests finding out the reason of what happened. And this is what is quite tricky to achieve because I can't reproduce the issue. But I'll look into kickstart.sh today searching for places where tmpdir is set/modified . Maybe I'll be lucky enough the find the bug.

**Comment by Ferroin** [comment] 2022-06-29 10:57
Closing this as it should be resolved now that https://github.com/netdata/netdata/pull/13206 has been merged.

If this is still an issue, please comment and we will reopen it.

**Closed by Ferroin** 2022-06-29 10:57 UTC
Labels: bug, area/packaging, os/macos
