### ISSUE TITLE
apps.plugin stops

### ISSUE THREAD

**Issue by lohmag** [netdata/netdata#7302] opened 2019-11-11 09:49 UTC
apps.plugin enters the zombie state. The main netdata process continue working. But part of metrics not available. After restart everything works fine for at least 2 weeks.
`root     22187  0.0  0.0      0     0 ?        Z    Oct15   1:10 [apps.plugin] <defunct>`
OS - CentOS Linux release 7.6.1810
Env - works as system daemon
Netdata version - v1.17.1(but it was the same in 1.15,1.16)
Component - apps.plugin
Test case - Usage of apps.plugin metrics

**Comment by vlvkobal** [comment] 2019-11-11 10:17
What messages do you have in the `error.log` for the `apps.plugin` before it dies?

**Comment by lohmag** [comment] 2019-11-11 11:07
I haven't logs becouse it was month ago. I will continue observation for next occurence.

**Comment by vlvkobal** [comment] 2019-11-11 11:25
The issue cannot be reproduced and it lacks information to proceed further with the investigation. I'm closing it. @lohmag feel free to reopen the issue when you have more data to investigate.

**Comment by lohmag** [comment] 2019-11-12 12:47
I updated netdata to `18.1` on all my hosts and today the same error happend on two host in the same time.
The error happened around `12:09-13`
dns-02:
```
IAD dns-02 nmassalitin # ps -aux | grep apps
root     10146  0.0  0.0 112632   724 pts/0    S+   12:42   0:00 grep --colour=auto apps
root     30546  0.2  0.0      0     0 ?        Z    08:08   0:33 [apps.plugin] <defunct>
```
```
IAD dns-02 nmassalitin # tail /opt/netdata/netdata-logs/error.log
2019-11-12 10:08:40: tc-qos-helper.sh: WARNING: FireQoS is not installed on this system. Use FireQoS to apply traffic QoS and expose the class names to netdata. Check https://github.com/netdata/netdata/tree/master/collectors/tc.plugin#tcplugin
2019-11-12 10:08:40: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/usr/lib/netdata/conf.d/tc-qos-helper.conf'.
2019-11-12 10:08:40: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/etc/netdata/tc-qos-helper.conf'.
2019-11-12 11:09:00: tc-qos-helper.sh: WARNING: FireQoS is not installed on this system. Use FireQoS to apply traffic QoS and expose the class names to netdata. Check https://github.com/netdata/netdata/tree/master/collectors/tc.plugin#tcplugin
2019-11-12 11:09:00: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/usr/lib/netdata/conf.d/tc-qos-helper.conf'.
2019-11-12 11:09:00: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/etc/netdata/tc-qos-helper.conf'.
2019-11-12 11:58:35: apps.plugin ERROR : MAIN : Cannot process /proc/24297/io (command 'chronyc') (errno 3, No such process)
2019-11-12 12:09:20: tc-qos-helper.sh: WARNING: FireQoS is not installed on this system. Use FireQoS to apply traffic QoS and expose the class names to netdata. Check https://github.com/netdata/netdata/tree/master/collectors/tc.plugin#tcplugin
2019-11-12 12:09:20: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/usr/lib/netdata/conf.d/tc-qos-helper.conf'.
2019-11-12 12:09:20: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/etc/netdata/tc-qos-helper.conf'.
```
dns-03:
```
IAD dns-03 nmassalitin # ps -aux | grep apps
root     30236  0.1  0.0      0     0 ?        Z    08:08   0:32 [apps.plugin] <defunct>
root     31241  0.0  0.0 112632   724 pts/0    S+   12:37   0:00 grep --colour=auto apps
```
```
IAD dns-03 nmassalitin # tail /opt/netdata/netdata-logs/error.log
2019-11-12 10:38:39: apps.plugin ERROR : MAIN : Cannot process /proc/8015/status (command 'timeout') (errno 3, No such process)
2019-11-12 10:40:19: apps.plugin ERROR : MAIN : Cannot process /proc/12426/cmdline (command 'timeout') (errno 3, No such process)
2019-11-12 10:54:49: apps.plugin ERROR : MAIN : Cannot process /proc/18475/status (command 'keepalived') (errno 3, No such process)
2019-11-12 11:06:39: apps.plugin ERROR : MAIN : Cannot process /proc/17413/cmdline (command 'sleep') (errno 3, No such process)
2019-11-12 11:09:00: tc-qos-helper.sh: WARNING: FireQoS is not installed on this system. Use FireQoS to apply traffic QoS and expose the class names to netdata. Check https://github.com/netdata/netdata/tree/master/collectors/tc.plugin#tcplugin
2019-11-12 11:09:00: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/usr/lib/netdata/conf.d/tc-qos-helper.conf'.
2019-11-12 11:09:00: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/etc/netdata/tc-qos-helper.conf'.
2019-11-12 12:09:20: tc-qos-helper.sh: WARNING: FireQoS is not installed on this system. Use FireQoS to apply traffic QoS and expose the class names to netdata. Check https://github.com/netdata/netdata/tree/master/collectors/tc.plugin#tcplugin
2019-11-12 12:09:20: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/usr/lib/netdata/conf.d/tc-qos-helper.conf'.
2019-11-12 12:09:20: tc-qos-helper.sh: WARNING: Cannot find file '/opt/netdata/etc/netdata/tc-qos-helper.conf'.
```
I don't restart netdata yet maybe youu need something to find problem

**Comment by vlvkobal** [comment] 2019-11-12 13:04
Are there any errors from `PLUGINSD` after the last `apps.plugin` messages?

**Comment by lohmag** [comment] 2019-11-12 13:20
@vlvkobal Full log from start
https://pastebin.com/Sid4chA0

**Comment by lohmag** [comment] 2019-11-12 14:18
I restarted netdata with `strace` applied to apps.plugin subprocess

**Comment by debu99** [comment] 2019-12-17 14:21
even happened the same on 1.19

**Comment by mbarper** [comment] 2020-01-10 10:53
I have the same problem with the plugin apps.plugin and I have tried with https://github.com/netdata/netdata/issues/3740 in case it works.

**Comment by sameedshoaibb** [comment] 2020-02-24 11:16
I have also faced the same issue. Apps.plugin has become a zombie process while other plugins are working fine. I have the latest net data version installed i.e v 1.19

**Comment by vlvkobal** [comment] 2020-03-31 13:04
The issue might be connected to #8530.

**Comment by amoss** [comment] 2020-08-07 10:09
We could not reproduce this problem so we cannot fix it. If new information is available to allow us to reproduce it then please re-open the issue.

**Closed by amoss** 2020-08-07 10:09 UTC
Labels: Cannot reproduce, area/external, bug
