### ISSUE TITLE
[Bug]: recurrent segmentation faults since an upgrade

### ISSUE THREAD

**Issue by RaitoBezarius** [netdata/netdata#13753] opened 2022-10-01 22:34 UTC
### Bug description

Since a system upgrade (`libc`, `systemd`, etc.), netdata 1.36.1 (and nightly 1.35.0-xxx), netdata is crashing regularly every 5 minutes.

### Expected behavior

It should not crash.

### Steps to reproduce

No easy reproducer for now, alas.

### Installation method

from source

### System info

```shell
Linux core-services-01 5.10.80 #1-NixOS SMP Thu Nov 18 13:04:33 UTC 2021 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_CODENAME=raccoon
/etc/lsb-release:DISTRIB_DESCRIPTION="NixOS 22.11 (Raccoon)"
/etc/lsb-release:DISTRIB_ID=nixos
/etc/lsb-release:DISTRIB_RELEASE="22.11"
/etc/lsb-release:LSB_VERSION="22.11 (Raccoon)"
/etc/os-release:BUILD_ID="22.11.git.823e2c9b0a0"
/etc/os-release:ID=nixos
/etc/os-release:LOGO="nix-snowflake"
/etc/os-release:NAME=NixOS
/etc/os-release:PRETTY_NAME="NixOS 22.11 (Raccoon)"
/etc/os-release:VERSION="22.11 (Raccoon)"
/etc/os-release:VERSION_CODENAME=raccoon
/etc/os-release:VERSION_ID="22.11"
```

### Netdata build info

```shell
[root@core-services-01:~]# /nix/store/2w5y4jdkgzqvz8px5zhcf5lrs5nk57rs-netdata-1.35.0-nightly/bin/netdata -W buildinfo
Version: netdata v1.35.0-256-nightly
Configure options: REMOVED
Install type: unknown
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                YES
    JSON-C:                  YES
    libcap:                  YES
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

coredump logs: https://clbin.com/I1xtp

**Comment by thiagoftsm** [comment] 2022-10-02 17:00
@stelfrag I am not sure if the reported issue could have relationship with other `sqlite` issues I reported, but this is something we need to take a look, because the reported environment is completely different of the previous I had tested.

**Comment by MrZammler** [comment] 2022-10-03 07:05
Hi @RaitoBezarius 

Can you share a bit more about your setup? Is it in a parent/child setup? Is it connected to the cloud?

Also, not sure, are there packages provided for 1.36.X versions? Can you check with a latest nightly ?

**Comment by MrZammler** [comment] 2022-10-04 08:17
Can you please also post your `error.log` file ? If you want, you can send to manolis@netdata.cloud.

Thanks!

**Comment by RaitoBezarius** [comment] 2022-10-04 08:23
> Hi @RaitoBezarius
> 
> Can you share a bit more about your setup? Is it in a parent/child setup? Is it connected to the cloud?
> 
> Also, not sure, are there packages provided for 1.36.X versions? Can you check with a latest nightly ?

Yes, this is a parent, it has 3-4 children, it's not connected to the cloud.
I will test for a nightly, no problem.

Sending you the `error.log` by email.

**Comment by MrZammler** [comment] 2022-10-04 09:43
> ~Sending you the `error.log` by email.~ I have a 100MiB+ error.log :D.

Oh! Even gzipped is too much? Can we maybe pick a file transfer if you know any .. ?

Essentially I'm looking for those parts around the times of the crash, not sure how easy it would be to extract just those...

**Comment by RaitoBezarius** [comment] 2022-10-08 16:18
@MrZammler Tried the latest nightly (185): https://clbin.com/ZNDG5 — same crashes.

**Comment by RaitoBezarius** [comment] 2022-10-08 16:19
cc @thiagoftsm

**Comment by thiagoftsm** [comment] 2022-10-08 17:05
Thank you @RaitoBezarius for the report.

I will try to recreate this issue today. I observed that when you wrote the initial description, you were running `Version: netdata v1.35.0-256-nightly`, and right now I am running the following version:

```sh
root@hades:/lib/modules# netdata -v
netdata v1.36.0-183-nightly
```

Please, can you confirm that you already updated for the latest version?

Best regards!

**Comment by RaitoBezarius** [comment] 2022-10-08 17:25
@thiagoftsm 

```
[root@core-services-01:~]# /nix/store/w9dy02548awlm0x8y0jfrqjscw7fbj16-netdata-1.36.0-185-nightly/bin/netdata -v
netdata v1.36.0-185-nightly
```
I confirm :).

**Comment by thiagoftsm** [comment] 2022-10-09 01:57
Hello @RaitoBezarius ,

When your Netdata crashed, did you have an error like this:

```sh
2022-10-09 00:45:00: netdata ERROR : SERVICE : (1152@libnetdata/libnetdat:recursively_del): Cannot read left-over chart directory to be deleted '/var/cache/netdata/b51020a2-329c-11ed-9259-525400c9012a/ip.bcastpkts' (errno 2, No such fil
e or directory)
2022-10-09 00:45:00: netdata ERROR : SERVICE : (1152@libnetdata/libnetdat:recursively_del): Cannot read left over host directory to be deleted '/var/cache/netdata/b51020a2-329c-11ed-9259-525400c9012a' (errno 2, No such file or directory
)
```

 inside your `/var/log/netdata/error.log`?

**Comment by RaitoBezarius** [comment] 2022-10-10 10:36
> Hello @RaitoBezarius ,
> 
> When your Netdata crashed, did you have an error like this:
> 
> ```shell
> 2022-10-09 00:45:00: netdata ERROR : SERVICE : (1152@libnetdata/libnetdat:recursively_del): Cannot read left-over chart directory to be deleted '/var/cache/netdata/b51020a2-329c-11ed-9259-525400c9012a/ip.bcastpkts' (errno 2, No such fil
> e or directory)
> 2022-10-09 00:45:00: netdata ERROR : SERVICE : (1152@libnetdata/libnetdat:recursively_del): Cannot read left over host directory to be deleted '/var/cache/netdata/b51020a2-329c-11ed-9259-525400c9012a' (errno 2, No such file or directory
> )
> ```
> 
> inside your `/var/log/netdata/error.log`?

Yes!

**Comment by RaitoBezarius** [comment] 2022-10-10 10:36
> @RaitoBezarius hi! Also, do you use SSL for streaming?

No!

**Comment by thiagoftsm** [comment] 2022-10-10 12:50
@MrZammler it looks like we are talking about the same issue.

On my end I am using SSL.

**Comment by MrZammler** [comment] 2022-10-11 08:24
Admittedly an interesting experience with NixOS...

I've installed NixOS 22.05, updated to unstable as it seems 22.11, and installed Netdata 1.36.1. I have 10 children streaming to it, and will check it for any crashes.

Can you share your config for Netdata so I can replicate the setup? Btw, was Netdata ok on 22.05 ?

**Comment by RaitoBezarius** [comment] 2022-10-11 11:36
> Admittedly an interesting experience with NixOS...
> 
> I've installed NixOS 22.05, updated to unstable as it seems 22.11, and installed Netdata 1.36.1. I have 10 children streaming to it, and will check it for any crashes.
> 
> Can you share your config for Netdata so I can replicate the setup? Btw, was Netdata ok on 22.05 ?

Yeah, it looked like this: https://git.rz.ens.wtf/Klub-RZ/infrastructure/src/branch/master/machines/core-services-01/monitoring.nix#L80-L134
Netdata was okay on 22.05, more: netdata is okay on other NixOS hosts on unstable and so on.

I had this bug while upgrading from ~22.05 to 22.11 indeed, assuming some state beforehand in `/var/cache/netdata` I think.

**Comment by ktsaou** [comment] 2022-10-24 09:10
Is it still crashing?

**Comment by Dim-P** [comment] 2022-11-04 10:27
@RaitoBezarius Do you still see crashes with the recent nightlies?

**Comment by Dim-P** [comment] 2022-11-14 15:13
@RaitoBezarius Any updates on whether you still observe any crashes?

**Comment by Dim-P** [comment] 2022-11-21 15:28
@RaitoBezarius No problem, thanks for the update. It would be very helpful if you share the database folder that was crashing (maybe upload it on some cloud storage service and send the link to `dpantazis[at]netdata.cloud`) , so maybe we can reproduce the issue.

Just to confirm, you mean you haven't seen any crashes since you started with a clean database?

**Comment by ilyam8** [comment] 2022-12-14 11:30
Closing because clearing the cache fixed the problem. @RaitoBezarius please comment if the problem happens again.

**Closed** 2022-12-14 11:30 UTC
Labels: bug, needs triage
