### ISSUE TITLE
date & time range filter ?

### ISSUE THREAD

**Issue by centminmod** [netdata/netdata#250] opened 2016-04-16 14:24 UTC
Probably related to https://github.com/firehol/netdata/issues/222 but a date and time range filter in dashboard would be nice. So we can narrow in on a specific time range rather than mouse drag back and forth :)

**Comment by ktsaou** [comment] 2016-04-16 16:23
How do you believe should be implemented?
Because if we just end up to have something for the selector, that would be just like a chart (drag back and forth), it will be pointless.

**Comment by centminmod** [comment] 2016-04-16 20:41
Ah i see what you mean - live vs static monitored stats. Maybe the selector when triggered will pause the live plotting at the selected time range ? That would allow us to drag back and forth at that time range point ?

**Comment by ktsaou** [comment] 2016-04-16 21:02
No, I am not interested in live vs paused.

Let's say we have data/time range filter. What would it look like? Drop down calendars/lists? Two text boxes where you write the data/time? Or a slider?

All the charts are today date/time range pickers. So the one you are missing looks like what?

**Comment by centminmod** [comment] 2016-04-16 21:56
Oh the format.. actually i was just viewing my newrelic stats and they have something useful

![image](https://cloud.githubusercontent.com/assets/5899584/14583838/d73b1796-0471-11e6-9d10-168bc69cba42.png)

**Comment by ktsaou** [comment] 2016-04-16 22:30
Oh! I see. I was thinking of adding a list, like the upper of the image you posted, to select the default auto-refreshing duration of the charts.

Now, it is based on your screen resolution: 3 pixels per second, fit as many seconds.
But we could easily select 5min, 10min, 15min, 30min, 1hour, 2hours, etc in auto-refreshing mode. This would also mean that the charts may not auto-refresh per second (the dashboard is smart enough to auto-refresh charts only when they are expected to have new data).

Later, when we will have longer durations we could add a date picker too.

**Comment by gamefundas** [comment] 2017-03-14 18:39
+1 for this feature.
We have a hard time looking at problems that occurred hours back, sometimes going back a day. So it would be good to have a date/time range. Something like the following might come handy. 

![image](https://cloud.githubusercontent.com/assets/5448799/23916836/dc53620e-08c3-11e7-9ef3-4483808ef869.png)

**Comment by ktsaou** [comment] 2017-03-14 21:19
ok, yes, I'll do.

Keep in mind that the faster way to find a time at the charts, is to zoom out (shift + mouse wheel) and then select the part you need (shift + right mouse click and drag). This is probably faster than selecting a date/time range, but I totally understand the need.

**Comment by ktsaou** [comment] 2018-11-23 08:44
@gmosx 	this is on our roadmap.
I am sure I have seen another one requesting the same feature.

**Comment by gmosx** [comment] 2018-11-23 09:50
I think we can do this in netdata agent.

**Comment by kkoomen** [comment] 2019-12-20 06:39
What's the status about this? as it looks like this is a dead issue. I'm urgently waiting for this to be implemented, as I see hardly use to use netdata without this big feature.

Is this implemented? It is partially implemented? Is it done? Or when will it be picked up? What's the status of this? @ktsaou @ilyam8

**Comment by ilyam8** [comment] 2019-12-20 07:28
This is not implemented. I agree that this is important. Current implementation allows to monitor only real time data to be honest. Browsing history is lame 😢

**Comment by kkoomen** [comment] 2019-12-20 08:05
@ilyam8 Could priority be increased?

**Comment by ilyam8** [comment] 2019-12-20 09:54
Currenlty dashboard is under big refactor
https://github.com/netdata/netdata/pull/6516

**Comment by gamefundas** [comment] 2020-06-30 12:49
@ilyam8 any update on this as it has been very difficult to move around the timeline in general especially triaging issues that happens around an event. We were forced to use Chronograf dashboard for some of our analysis.

I think to begin with a simple date/time range picker (global host level) along with some predefined mins, hourly windows should do the trick.

**Comment by ilyam8** [comment] 2020-06-30 12:54
> very difficult to move around the timeline in general especially triaging issues that happens around an event.

@gamefundas i completely agree, it is very hard or even impossible to browse data/charts if you are interested not in real-time (current) data.

@jacekkolasa @dim08

**Comment by dim08** [comment] 2020-07-01 08:15
Hi there, 

I agree, this feature is on the way cc:@manos-saratsis.

**Comment by kiranos** [comment] 2020-09-04 17:24
Hi is there any progress on this topic ?

**Comment by ilyam8** [comment] 2020-09-04 17:50
yes there is progress, i am not aware of the feature release date but it is wip

**Comment by manos-saratsis** [comment] 2020-09-07 11:52
@kiranos @gamefundas The feature is on its way, expected early October.

**Comment by max3163** [comment] 2020-10-30 16:43
Any news about the implementation?

**Comment by jacekkolasa** [comment] 2020-10-30 21:45
Next week on nightlies, thank you for your patience! I'll link the pr to this issue.

**Comment by ilyam8** [comment] 2020-11-16 15:15
fixed in https://github.com/netdata/netdata/pull/10239

**Comment by ilyam8** [comment] 2020-11-16 15:17
<img width="1424" alt="Screenshot 2020-11-16 at 18 17 29" src="https://user-images.githubusercontent.com/22274335/99271678-01e50d00-2838-11eb-8d20-01363be531bb.png">

**Closed** 2020-11-17 17:47 UTC
Labels: area/web, feature request

**Comment by dgsus** [comment] 2020-12-02 10:34
hi team,

im having an issue with this date and time picker....the issue is that sometimes its there and sometimes its not. i really dont understand what causes this to happen...

any insight is much appreciated!

![image](https://user-images.githubusercontent.com/30906366/100861622-017c8100-348a-11eb-9dc3-b7ab114f3a1a.png)


![image](https://user-images.githubusercontent.com/30906366/100861629-04777180-348a-11eb-8bad-bf2b399ac656.png)

**Comment by ilyam8** [comment] 2020-12-04 20:31
There is pretty old dashboard on the 2nd screenshot. How do you get it? Using same url?

**Comment by dgsus** [comment] 2021-01-12 15:14
@ilyam8 hi, yes using the same URL. i got the issue solved by completely turning of the registry.

**Comment by im-yangp** [comment] 2021-03-18 02:15
@dgsus @ilyam8  How did you solve it, I have the same problem
![image](https://user-images.githubusercontent.com/49512694/111563380-d452a500-87d2-11eb-9901-0e2dfcdb6179.png)

**Comment by jacekkolasa** [comment] 2021-03-29 14:40
@im-yangp The problem is that this is the old dashboard version, which was probably installed with a package that has outdated methods of installation. We'll try to fix this by reaching out to 3rd party packagers, but until then, can you reinstall Netdata using recommended methods?
https://learn.netdata.cloud/docs/agent/packaging/installer/

**Comment by iciuperca** [comment] 2021-03-31 15:26
Does not seem to be a browser cache issue.

**Comment by ilyam8** [comment] 2021-03-31 15:43
Well, i had this issue recently 🤷‍♂️ 

Then i suggest to check `netdata-installer.log`

You can see the dashboard downloading process during install. Check it, could be it fails to download it for some reason.
 

```cmd
[ilyam@pc netdata]$ sudo ./netdata-installer.sh --install /opt
...
...
--- Fetching and installing dashboard ---
[/home/ilyam/netdata]# curl -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-dashboard-Kx3FJi/dashboard.tar.gz https://github.com/netdata/dashboard/releases/download/v2.13.28_/dashboard.tar.gz
 OK

dashboard.tar.gz: OK
[/home/ilyam/netdata]# tar -xf /tmp/netdata-dashboard-Kx3FJi/dashboard.tar.gz -C /tmp/netdata-dashboard-Kx3FJi
 OK
...
```

**Comment by iciuperca** [comment] 2021-03-31 16:06
I'm not using the installer, I'm using the autotools build, but the info you provided is useful, thank you.

**Comment by xclusive1111** [comment] 2021-08-03 07:26
Is anyone still having issues with the time range filter?
I'm using the binary installer and everything works out of the box except the time range picker. I try to pick a time range but it only applies the lower bound, the upper bound is completely ignored

[Here's the captured video of this issue](https://streamable.com/em6j12)
