### ISSUE TITLE
libvirt metrics instead cgroups for VM.

### ISSUE THREAD

**Issue by k0ste** [netdata/netdata#3173] opened 2017-12-24 06:51 UTC
In #3144 I find that cgroups metrics on my hypervisors is empty. [Red Hat folks tells](http://lists.ovirt.org/pipermail/users/2017-December/085747.html) better to get libvirt metrics directly (pybind of course). And in #2545 this works but abandoned to the benefit of "shell virsh wrapper". Can we resurrect this question?

**Comment by ktsaou** [comment] 2017-12-25 19:13
I suggest to discuss this on #2545 . @l2isbad said he could write a libvirt netdata plugin in python.

However, I find it strange that you cannot enable cgroups disk accounting. Are all cgroups metrics empty or just disk I/O? So you have CPU, memory, network and you are missing disk?

Which kernel version?
Does your kernel have the following options enabled?

```
CONFIG_BLK_CGROUP=y
CONFIG_CFQ_GROUP_IOSCHED=y
CONFIG_BLK_DEV_THROTTLING=y
```

**Comment by k0ste** [comment] 2017-12-26 06:20
> However, I find it strange that you cannot enable cgroups disk accounting. Are all cgroups metrics empty or just disk I/O?

I think is disabled by Red Hat. In some place...

> So you have CPU, memory, network and you are missing disk?

AFAIK network stat is not present on cgroups, only classify and prio.
`cpuacct.stat`, `cpuacct.usage_percpu`, `memory.stat` - this files have data inside cgroup sysfs. So only disk is missed.

> Which kernel version?
> Does your kernel have the following options enabled?

```shell
[root@ovirt-host1 boot]# uname -r
3.10.0-693.11.1.el7.x86_64
[root@ovirt-host1 boot]# grep CONFIG_BLK_CGROUP config-`uname -r`                                                                                     
CONFIG_BLK_CGROUP=y
[root@ovirt-host1 boot]# grep CONFIG_CFQ_GROUP_IOSCHED config-`uname -r`                                                                              
CONFIG_CFQ_GROUP_IOSCHED=y
[root@ovirt-host1 boot]# grep CONFIG_BLK_DEV_THROTTLING config-`uname -r`                                                                             
CONFIG_BLK_DEV_THROTTLING=y
```

**Comment by l2isbad** [comment] 2017-12-26 11:09
https://github.com/firehol/netdata/issues/2545 is quite heavy in comparison with cgroups.
It was 150-180ms to get all stats from 8 vm's.

**Comment by ktsaou** [comment] 2017-12-26 23:36
@k0ste for network, netdata collects the vnet interface from /proc. It only consults the hypervisor if it cannot find from cgroups the VM it belongs to.From your response I am not sure I understand if this works for your setup (i.e. "are the network interfaces of VMs assigned to each VM at the netdata dashboard?")

Regarding blkio: since the kernel is compiled with these, I guess there must be something else that enables them. I read here: https://libvirt.org/formatdomain.html#elementsBlockTuning:

> The optional blkiotune element provides the ability to tune Blkio cgroup tunable parameters for the domain. If this is omitted, it defaults to the OS provided defaults. Since 0.8.8

Have you tried to add such an element to one of your VMs?

I see reports that this feature should be available even at Centos 6: https://www.redhat.com/archives/libvirt-users/2012-October/msg00051.html

I am not 100% sure if netdata looks for the cgroups files it should. Could you please check the blkio files you have? There may be different versions with data (for example, I see  on my setup `cfq` files netdata does not use.

**Comment by ktsaou** [comment] 2017-12-26 23:43
There is also a `virsh blkiotune` command: https://libvirt.org/cgroups.html

**Comment by k0ste** [comment] 2017-12-27 04:47
> "are the network interfaces of VMs assigned to each VM at the netdata dashboard?"

After #3146 - yes.

`blkiotune` - QoS for block drive. Not metrics.

**Comment by ktsaou** [comment] 2017-12-27 12:15
@k0ste which distro and version is this?

**Comment by k0ste** [comment] 2017-12-27 13:18
@ktsaou, EL7.
`CentOS Linux release 7.4.1708 (Core)`

**Comment by l2isbad** [comment] 2017-12-27 13:33
It's always `CentOS` 😄

**Comment by k0ste** [comment] 2017-12-27 13:39
Yep. First answers in google is manual pages, fourth+ is netdata issues 😅.

**Comment by ktsaou** [comment] 2017-12-27 13:56
oops! the latest centos runs kernel 3.10? not only this is not LTS, it is EOL too: https://www.kernel.org/ - it could be quite possible the issue we face to be a mess of patches backporting...

@k0ste if you start a container (docker, lxc, whatever), does netdata report disk operations? If it does, your kernel is fine. The problem is elsewhere.

If you have enabled systemd monitoring, netdata will also add a disk subsection there if it finds usable disk metrics. Do you have this?

Make sure you have `DefaultBlockIOAccounting=yes` at `/etc/systemd/system.conf`. Check this from more info: https://github.com/firehol/netdata/wiki/monitoring-systemd-services (if you change that setting you have to `systemctl daemon-reexec` and restart a service to wake it up.

**Comment by k0ste** [comment] 2018-01-05 18:19
> oops! the latest centos runs kernel 3.10? not only this is not LTS, it is EOL too: https://www.kernel.org/ - it could be quite possible the issue we face to be a mess of patches backporting...

This is not vanilla 3.10. For now it's like 4.5.

On another device I was started libvirt vm and blk metrics are present. I diff libvirt configuration between this hypervisors and I don't see something special, exclude authentication.

```diff
diff -Naupr /tmp/manager/libvirt/libvirtd.conf /tmp/host/libvirt/libvirtd.conf
--- /tmp/manager/libvirt/libvirtd.conf	2018-01-06 01:07:07.148477168 +0700
+++ /tmp/host/libvirt/libvirtd.conf	2018-01-06 01:07:50.692035542 +0700
@@ -19,7 +19,7 @@
 # using this capability.
 #
 # This is enabled by default, uncomment this to disable it
-listen_tls = 0
+#listen_tls = 0
 
 # Listen for unencrypted TCP connections on the public TCP/IP port.
 # NB, must pass the --listen flag to the libvirtd process for this to
@@ -30,7 +30,7 @@ listen_tls = 0
 # DIGEST_MD5 and GSSAPI (Kerberos5)
 #
 # This is disabled by default, uncomment this to enable it.
-listen_tcp = 1
+#listen_tcp = 1
 
 
 
@@ -82,14 +82,14 @@ listen_tcp = 1
 # without becoming root.
 #
 # This is restricted to 'root' by default.
-unix_sock_group = "libvirt"
+#unix_sock_group = "libvirt"
 
 # Set the UNIX socket permissions for the R/O socket. This is used
 # for monitoring VM status only
 #
 # Default allows any user. If setting group ownership, you may want to
 # restrict this too.
-unix_sock_ro_perms = "0777"
+#unix_sock_ro_perms = "0777"
 
 # Set the UNIX socket permissions for the R/W socket. This is used
 # for full management of VMs
@@ -99,7 +99,7 @@ unix_sock_ro_perms = "0777"
 #
 # If not using PolicyKit and setting group ownership for access
 # control, then you may want to relax this too.
-unix_sock_rw_perms = "0770"
+#unix_sock_rw_perms = "0770"
 
 # Set the UNIX socket permissions for the admin interface socket.
 #
@@ -138,7 +138,7 @@ unix_sock_rw_perms = "0770"
 #
 # To restrict monitoring of domains you may wish to enable
 # an authentication mechanism here
-auth_unix_ro = "none"
+#auth_unix_ro = "none"
 
 # Set an authentication scheme for UNIX read-write sockets
 # By default socket permissions only allow root. If PolicyKit
@@ -147,7 +147,7 @@ auth_unix_ro = "none"
 #
 # If the unix_sock_rw_perms are changed you may wish to enable
 # an authentication mechanism here
-auth_unix_rw = "none"
+#auth_unix_rw = "none"
 
 # Change the authentication scheme for TCP sockets.
 #
@@ -155,7 +155,7 @@ auth_unix_rw = "none"
 # Don't do this outside of a dev/test scenario. For real world
 # use, always enable SASL and use the GSSAPI or DIGEST-MD5
 # mechanism in /etc/sasl2/libvirt.conf
-auth_tcp = "none"
+#auth_tcp = "sasl"
 
 # Change the authentication scheme for TLS sockets.
 #
@@ -164,7 +164,7 @@ auth_tcp = "none"
 #
 # It is possible to make use of any SASL authentication
 # mechanism as well, by using 'sasl' for this option
-auth_tls = "none"
+#auth_tls = "none"
 
 
 # Change the API access control scheme
@@ -467,3 +467,13 @@ auth_tls = "none"
 # Keepalive settings for the admin interface
 #admin_keepalive_interval = 5
 #admin_keepalive_count = 5
+## beginning of configuration section by vdsm-4.20.0
+auth_unix_rw="sasl"
+ca_file="/etc/pki/vdsm/certs/cacert.pem"
+cert_file="/etc/pki/vdsm/certs/vdsmcert.pem"
+host_uuid="6d09ccce-8fd0-4886-92a8-599c88ae0e9c"
+keepalive_interval=-1
+key_file="/etc/pki/vdsm/keys/vdsmkey.pem"
+unix_sock_group="qemu"
+unix_sock_rw_perms="0770"
+## end of configuration section by vdsm-4.20.0
diff -Naupr /tmp/manager/libvirt/lxc.conf /tmp/host/libvirt/lxc.conf
--- /tmp/manager/libvirt/lxc.conf	2018-01-06 01:07:07.255144386 +0700
+++ /tmp/host/libvirt/lxc.conf	1970-01-01 07:00:00.000000000 +0700
@@ -1,31 +0,0 @@
-# Master configuration file for the LXC driver.
-# All settings described here are optional - if omitted, sensible
-# defaults are used.
-
-# By default, log messages generated by the lxc controller go to the
-# container logfile. It is also possible to accumulate log messages
-# from all lxc controllers along with libvirtd's log outputs. In this
-# case, the lxc controller will honor either LIBVIRT_LOG_OUTPUTS or
-# log_outputs from libvirtd.conf.
-#
-# This is disabled by default, uncomment below to enable it.
-#
-#log_with_libvirtd = 1
-
-
-# The default security driver is SELinux. If SELinux is disabled
-# on the host, then the security driver will automatically disable
-# itself. If you wish to disable LXC SELinux security driver while
-# leaving SELinux enabled for the host in general, then set this
-# to 'none' instead.
-#
-#security_driver = "selinux"
-
-# If set to non-zero, then the default security labeling
-# will make guests confined. If set to zero, then guests
-# will be unconfined by default. Defaults to 0.
-#security_default_confined = 1
-
-# If set to non-zero, then attempts to create unconfined
-# guests will be blocked. Defaults to 0.
-#security_require_confined = 1
diff -Naupr /tmp/manager/libvirt/qemu.conf /tmp/host/libvirt/qemu.conf
--- /tmp/manager/libvirt/qemu.conf	2018-01-06 01:07:07.251811036 +0700
+++ /tmp/host/libvirt/qemu.conf	2018-01-06 01:07:50.848703018 +0700
@@ -9,7 +9,7 @@
 # NB, strong recommendation to enable TLS + x509 certificate
 # verification when allowing public access
 #
-vnc_listen = "0.0.0.0"
+#vnc_listen = "0.0.0.0"
 
 # Enable this option to have VNC served over an automatically created
 # unix socket. This prevents unprivileged access from users on the
@@ -542,3 +542,14 @@ vnc_listen = "0.0.0.0"
 #          rollover when a size limit is hit.
 #
 #stdio_handler = "logd"
+## beginning of configuration section by vdsm-4.20.0
+auto_dump_path="/var/log/core"
+dynamic_ownership=0
+lock_manager="sanlock"
+max_core="unlimited"
+remote_display_port_max=6923
+remote_display_port_min=5900
+save_image_format="lzop"
+spice_tls=1
+spice_tls_x509_cert_dir="/etc/pki/vdsm/libvirt-spice"
+## end of configuration section by vdsm-4.20.0
diff -Naupr /tmp/manager/libvirt/qemu-sanlock.conf /tmp/host/libvirt/qemu-sanlock.conf
--- /tmp/manager/libvirt/qemu-sanlock.conf	1970-01-01 07:00:00.000000000 +0700
+++ /tmp/host/libvirt/qemu-sanlock.conf	2018-01-06 01:07:50.838702967 +0700
@@ -0,0 +1,73 @@
+#
+# The default sanlock configuration requires the management
+# application to manually define <lease> elements in the
+# guest configuration, typically one lease per disk. An
+# alternative is to enable "auto disk lease" mode. In this
+# usage, libvirt will automatically create a lockspace and
+# lease for each fully qualified disk path. This works if
+# you are able to ensure stable, unique disk paths across
+# all hosts in a network.
+#
+# Uncomment this to enable automatic lease creation.
+#
+# NB: the 'host_id' parameter must be set if enabling this
+#
+#auto_disk_leases = 1
+
+#
+# The default location in which lockspaces are created when
+# automatic lease creation is enabled. For each unique disk
+# path, a file $LEASE_DIR/NNNNNNNNNNNNNN will be created
+# where 'NNNNNNNNNNNNNN' is the MD5 checkout of the disk path.
+#
+# If this directory is on local storage, it will only protect
+# against a VM being started twice on the same host, or two
+# guests on the same host using the same disk path. If the
+# directory is on NFS, then it can protect against concurrent
+# usage across all hosts which have the share mounted.
+#
+# Recommendation is to just mount this default location as
+# an NFS volume. Uncomment this, if you would prefer the mount
+# point to be somewhere else. Moreover, please make sure
+# sanlock daemon can access the specified path.
+#
+#disk_lease_dir = "/var/lib/libvirt/sanlock"
+
+#
+# The unique ID for this host.
+#
+# IMPORTANT: *EVERY* host which can access the filesystem mounted
+# at 'disk_lease_dir' *MUST* be given a different host ID.
+#
+# This parameter has no default and must be manually set if
+# 'auto_disk_leases' is enabled
+#host_id = 1
+
+#
+# Flag to determine whether we allow starting of guests
+# which do not have any <lease> elements defined in their
+# configuration.
+#
+# If 'auto_disk_leases' is disabled, this setting defaults
+# to enabled, otherwise it defaults to disabled.
+#
+#require_lease_for_disks = 1
+
+#
+# Sanlock is able to kill qemu processes on IO timeout. By its internal
+# implementation, the current default is 80 seconds. If you need to adjust
+# the value change the following variable. Value of zero means use the
+# default sanlock timeout.
+#io_timeout = 0
+
+#
+# The combination of user and group under which the sanlock
+# daemon runs. Libvirt will chown created files (like
+# content of disk_lease_dir) to make sure sanlock daemon can
+# access them. Accepted values are described in qemu.conf.
+#user = "root"
+#group = "root"
+## beginning of configuration section by vdsm-4.20.0
+auto_disk_leases=0
+require_lease_for_disks=0
+## end of configuration section by vdsm-4.20.0
```

Maybe it's not libvirt, any other points?

**Comment by ktsaou** [comment] 2018-01-14 19:51
I think 3 are possible reasons:

1. libvirt
2. systemd
3. kernel

I don't think there anything else to look for this.

**Comment by paulfantom** [comment] 2018-11-22 23:36
Closing issue due to inactivity. Please reopen if this is still relevant.

**Closed by paulfantom** 2018-11-22 23:36 UTC
Labels: question
