### ISSUE TITLE
Curl error while running netdata-updater

### ISSUE THREAD

**Issue by davidmehren** [netdata/netdata#9829] opened 2020-08-27 08:10 UTC
##### Bug report summary
I'm running netdata nightly on a number of hosts. This morning, I got a cron mail from each of them, as `/etc/cron.daily/netdata-updater` seems to output either `curl: (3) <url> malformed
` or `curl: (3) URL using bad/illegal format or missing URL` to stderr.
Running `netdata-update` manually yields (the output seems to be the same on all hosts affected, just with the different error message from curl):
```
Thu 27 Aug 2020 09:38:15 AM CEST : INFO:  Running on a terminal - (this script also supports running headless from crontab)                                                          
curl: (3) URL using bad/illegal format or missing URL
Thu 27 Aug 2020 09:38:15 AM CEST : ERROR:  FAILED TO UPDATE NETDATA : Cannot download /latest-version.txt                                                                            
Thu 27 Aug 2020 09:38:15 AM CEST : INFO:  Current Version: 001024000128
Thu 27 Aug 2020 09:38:15 AM CEST : INFO:  Latest Version: 000000000000
7a58066f5c1b411321115578feb516e2e89513e8ca65aa75f298cfd0fdf92da5 *./netdata-latest.tar.gz
7a58066f5c1b411321115578feb516e2e89513e8ca65aa75f298cfd0fdf92da5 *./netdata-v1.24.0-128-g46e868f9.tar.gz                                                                             
Thu 27 Aug 2020 09:38:15 AM CEST : INFO:  Newest version is already installed
```

##### OS / Environment
This happened on my VM-hosts runnning Proxmox/Debian 10 and on both LXC containers and VMs on them running various versions of Ubuntu and Debian.

Detailed info of one of my Proxmox hosts:
```
Linux iceman 5.4.55-1-pve #1 SMP PVE 5.4.55-1 (Mon, 10 Aug 2020 10:26:27 +0200) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version
`netdata v1.24.0-128-nightly`
 
##### Steps To Reproduce
1. Install netdata nightly using `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait --disable-cloud`
2. Try to run `/etc/cron.daily/netdata-updater` and see the error or wait for cron and get an email.

##### Expected behavior
There are no errors while running `netdata-updater`.

**Comment by kimmoahola** [comment] 2020-08-27 08:25
I have the same problem, appeared today. I have the same `Current Version: 001024000128`. Using debian 10.

**Comment by Ferroin** [comment] 2020-08-27 11:38
Root cause is https://github.com/netdata/netdata/commit/11c610af7417ffa8903b40f940a94b4099b4eab7. I'll have a PR up to fix this shortly, which should be merged either tomorrow or Monday.

Once this is fixed however, you're unfortunately going to need to manually handle the update to get it tow work, either by uninstalling and reinstalling Netdata, _or_ by manually running the updater script with `NETDATA_NIGHTLIES_BASEURL` set to `https://storage.googleapis.com/netdata-nightlies`.

**Comment by Ferroin** [comment] 2020-08-27 11:49
Slight clarification, anybody affected by this will have to manually update _after the next nightly build after this gets fixed goes out_ to get updates working again.

**Comment by ilyam8** [comment] 2020-08-27 13:00
If updated should work when running manually - it doesnt work after the #9831

```cmd
ilyam@debian-s-1vcpu-1gb-fra1-01:/opt/netdata/usr/libexec/netdata$ sudo ./netdata-updater.sh
Thu Aug 27 13:00:01 UTC 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
curl: (3) <url> malformed
Thu Aug 27 13:00:01 UTC 2020 : ERROR:  FAILED TO UPDATE NETDATA : Cannot download /latest-version.txt
Thu Aug 27 13:00:01 UTC 2020 : INFO:  Current Version: 0
Thu Aug 27 13:00:01 UTC 2020 : INFO:  Latest Version: 000000000000
```

**Comment by Ferroin** [comment] 2020-08-27 13:16
@ilyam8 Is that specifically running the fixed version from #9831, or is that a copy you had already installed?

**Comment by ilyam8** [comment] 2020-08-27 13:20
yes, i had that output before #9831 and have it after #9381

**Comment by Ferroin** [comment] 2020-08-27 13:51
Looks like #9381 did not, in fact, fix this. I'm not sure what's actually wrong here, but I'm reopening this until it is properly fixed.

**Comment by Ferroin** [comment] 2020-08-27 14:07
OK, _actually_ figured this out now, #8808 missed one place we were using a variable that it renamed. PR will be up shortly.

**Closed** 2020-08-27 15:47 UTC
Labels: area/packaging, bug

**Comment by Ferroin** [comment] 2020-08-27 16:02
OK, this is actually fixed now.

Users who are affected by this issue need to wait until the next nightly build is published (it should be fully published by 2020-08-28 01:30 UTC, the below options will _technically_ work before then, but the next update will fail the same way and you'll have to fix it again), and then can use one of three approaches to manually fix this:

* Download the fixed updater script from https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/netdata-updater.sh and use it to replace the copy in your installation (located at `/usr/libexec/netdata/netdata-updater.sh`). This will cause the next automatic update to work correctly, which will create an installation that inherently has the fixed version of the script.
* Manually run the updater script like so: `NETDATA_TARBALL_BASEURL=https://storage.googleapis.com/netdata-nightlies /usr/libexec/netdata/netdata-updater.sh`.This simply manually works around the bug in the script, and the updated version that you get from running it this way will have the fixed script.
* Re-run the installer the same way you did originally. If using the `kickstart.sh` script you will need to manually add `--reinsall` to the command you use to invoke the script to prevent it from trying to use the (broken) updater script in the existing install instead of reinstalling.
