### ISSUE TITLE
Kickstart script verification md5sum is out of date, verification fails

### ISSUE THREAD

**Issue by mbravorus** [netdata/netdata#6049] opened 2019-05-19 09:42 UTC
##### Bug report summary
Trying to follow one-line kickstart script validation in https://github.com/netdata/netdata/commits/master/packaging/installer/README.md I found that the validation fails, most likely because the listed md5sum for the script is out of date.

##### OS / Environment
Mac OS X Mojave

##### Netdata version (ouput of `netdata -V`)
N/A

##### Component Name
kickstart installation script

##### Steps To Reproduce
execute verification one-liner as given at the moment of bug report:

`[ "fe451cd039c8f99b2ba4ca0feab88033" = "$(curl -Ss https://my-netdata.io/kickstart.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"`

##### Expected behavior
Expected behaviour would be to receive a successful validation, presuming the script hasn't been tampered with.

Running an `md5sum` on the script itself as available at the time of testing and bug report, I get `15c688e7228ebee83ace1811273cd089`

**Comment by paulkatsoulakis** [comment] 2019-05-19 12:21
Hello @mbravorus i 'm sorry to hear you had this experience. Unfortunately from the time of merging to master, until the new version of kickstart reaches our deployment there is a small deployment gap.

I will confirm this for you, but if you check the README prior to #6048 the md5sums then match the deployed kickstart. FYI we are in the process of properly fully automating this deployment step to avoid this kind of gap.

I won't resolve this until i crosscheck the issue and deploy latest kickstart code

**Comment by paulkatsoulakis** [comment] 2019-05-24 12:08
The issue is now fixed, we had to attend more issue prior to updating kickstart and thus we delayed.
@mbravorus let me know if you face any further problems and thank you for your patience.
Do not hesitate to get in touch with us if you need our assistance again!

**Closed by paulkatsoulakis** 2019-05-24 12:08 UTC
Labels: bug, needs triage
