### ISSUE TITLE
Add ability to use multiple metrics in one custom chart

### ISSUE THREAD

**Issue by kellabyte** [netdata/netdata#2650] opened 2017-08-29 16:02 UTC
I would like to be able to chart multiple metrics on one chart.

**Comment by cobrafast** [comment] 2018-09-11 19:32
It's been over a year, any progress on this?

**Comment by paulfantom** [comment] 2018-09-11 20:06
No and it is not high in priorities list right now. However we are more than happy to accept PRs :smile:

**Comment by ktsaou** [comment] 2018-09-11 20:46
There is a PR: https://github.com/firehol/netdata/pull/3828
A little bit more patience. I think we will have a lot of help in this area soon.

**Comment by ilyam8** [comment] 2021-07-19 14:54
Duplicate of #2359

**Closed by ilyam8** 2021-07-19 14:54 UTC
Labels: area/web, feature request
