### ISSUE TITLE
Feature - Ability to add annotation, tags and notes to charts/dashboard

### ISSUE THREAD

**Issue by gamefundas** [netdata/netdata#9892] opened 2020-09-08 00:03 UTC
Currently our project is looking for ways to integrate Netdata in to our performance/load testing harness. The state of the infrastructure is equally an important metric to analyze along with application performance. Netdata allows us to take snapshots of the dashboard and keep them for offline analysis.

In addition to this what might prove to be useful is ability for us to add notes/comments or annotations/tags to the timeline. Select a time window and tag it as "deployment" or "restart" etc so that these notes then can be seen by others to interpret failures or associated events.

Notes and tags can be attached to time windows or even specific charts to indicate if any specific application config changed, external event occurred etc in the course of the time that potentially caused a spike.

**Comment by vlvkobal** [comment] 2020-09-08 06:41
A duplicate of #6523?

**Comment by amoss** [comment] 2020-09-09 07:08
This is a feature that we are currently very interested in adding, and we are talking internally about ways to implement it. @dim08 / @manos-saratsis perhaps you could talk about use-cases and get some initial input for your ideation?

**Comment by cakrit** [comment] 2020-10-26 17:18
Duplicate of #6523

**Closed by cakrit** 2020-10-26 17:18 UTC
Labels: feature request
