### ISSUE TITLE
provide binary repos for main distros

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#2728] opened 2017-09-13 13:25 UTC
I just saw this: https://www.sublimetext.com/docs/3/linux_repositories.html

If you know how to build such repos, please help...

We could provide binary packages for all package managers, using a statically built netdata, so that we will not care which libc version is installed on each system.

cc: @philwhineray

**Comment by lhw** [comment] 2017-09-20 11:50
Most package maintainers will still build from source, even if provided binaries. Or more likely especially if provided binaries.

And from what I can see on that site the sublime author is just providing standard package repositories for the major distributions. Which you can provide if you want. Some of the package building systems are already in the main git anyway. You just need to set up a automatic build for those as well.

**Comment by ktsaou** [comment] 2017-09-20 15:26
@lhw I just need help to setup this automatic build.

For example, to build the binary `makeself` packages of netdata, there are a few scripts that spawn an alpine docker container, download and build the package and move it to the current directory.

Similarly, we could have scripts to spawn docker containers for all the required distros, build the binary versions of netdata in .deb, .rpm or whatvever and move the final files to the current directory.

Once we have these, then we will need to setup repos as each distribution supports. This would allow people add our repos to their systems to use the packages provided.

Unfortunately, this is just too hard for me. So, I would appreciate some help...

**Comment by n0coast** [comment] 2017-09-23 02:24
I have this working for amazonlinux and CentOS/RHEL in a container, not exactly the way it's presented in the initial comment but I can try and publish what I've got. I'll work on that next week.

**Comment by ktsaou** [comment] 2017-09-23 19:47
thanks! Looking forward for it...

**Comment by n0coast** [comment] 2017-09-25 21:48
Code to generate rpms for CentOS and AmazonLinux here: https://github.com/rei/rpmbuilder I'm happy to help incorporate that into netdata more, but not sure what would be required.

**Comment by FooBarWidget** [comment] 2018-02-26 16:43
Hey there. I have a lot of experience with building distro packages. I am the author of the [Passenger application server](https://www.phusionpassenger.com/) and we provide packages for multiple versions and architectures of Ubuntu, Debian and CentOS. We also provide generic Linux binaries that work on most distros, without using static linking. Binary packages are part of our release pipeline: on every source release our CI server automatically builds and publishes corresponding binary packages. There is very little manual work -- the only time when we need to do something manually is when a new distribution version has been released. The native OS package build system uses Docker containers, [pbuilder-dist](https://wiki.ubuntu.com/PbuilderHowto) and [mock](https://github.com/rpm-software-management/mock/wiki) to build packages for multiple distros from a single server. Our generic Linux binaries build system uses [Holy Build Box](http://phusion.github.io/holy-build-box/).

All our automation work is open source and reproducible. You can find them here:

 * https://github.com/phusion/passenger_apt_automation
 * https://github.com/phusion/passenger_rpm_automation
 * https://github.com/phusion/passenger_binary_build_automation

What kind of help do you need? Are you looking for advice/education or are you looking for people to actually do the work of building an automated packaging pipeline?

**Comment by ktsaou** [comment] 2018-02-26 22:48
wow! nice! thank you!

> What kind of help do you need? Are you looking for advice/education or are you looking for people to actually do the work of building an automated packaging pipeline?

Well... I don't know... I need guidance first I guess...

Up to now we support:

1. installs from git
2. binary makeself installs for x64
3. a few docker containers: debian, alpine, armv7hf, aarch64
4. a `.rpm` can be built with this helper https://github.com/firehol/netdata/blob/master/contrib/rhel/build-netdata-rpm.sh
5. a `.deb` can be built somehow (from https://github.com/firehol/netdata/tree/master/contrib/debian) but I am not sure how.

To really help people, I understand we should provide repos, that can be added to a system, so that netdata can be installed and updated too. I understand we should provide 2 such repos per distribution, one for the latest release and one for nightly updates.

Also, ideally we should use travis for this, so that the whole process will be integrated to our release cycle (which is fully automated, thanks to the work of @philwhineray).

So, I guess the first step is to guide us...

**Comment by FooBarWidget** [comment] 2018-02-27 12:59
All right. Since you're just starting out, we should focus on either RPMs or DEBs, not both at the same time. Making RPMs tends to be easier than making DEBs. Which one do you want to prioritize?

In my experience, Debian (latest version) and Ubuntu (latest LTS version) have the most users, so I would recommend focussing on those first, and forget about older distro versions for now. The differences between Debian and Ubuntu tend to be small.

You say that you're not sure how to build contrib/debian, but contrib/README.md looks pretty clear to me. Do you have specific questions about it?

How is Travis working out for you so far? My experience with Passenger on Travis has not been good. It's free, but it's also very very slow (probably because so many open source projects use them) and is limited in flexibility compared to your own CI server.

**Comment by ktsaou** [comment] 2018-02-27 20:15
Yes, ubuntu is by far the most used distro. Here are a few stats of the new installations using the kickstart scripts for last few days:

```
      1 OracleServer
      1 VMware_Photon_OS
      4 CloudLinux_Server
      6 arch
      6 ManjaroLinux
     11 suse
     17 alpine
     52 fedora
    273 rhel
    896 debian
   1141 centos
   3138 ubuntu
```

I think we are going to need at least ubuntu, centos, debian, rhel.

Let's check ubuntu by version:

```
      1 ubuntu-12
      2 ubuntu-15.04
      2 ubuntu-18.2
      3 ubuntu-18.1
      5 ubuntu-16.10
      6 ubuntu-17.04
      6 ubuntu-18.04
      8 ubuntu-18
      9 ubuntu-0.4.1
     14 ubuntu-18.3
     19 ubuntu-12.04
    228 ubuntu-17.10
    362 ubuntu-14.04
   2478 ubuntu-16.04
```

question: for each distro version do we need a separate ppa?

So, to support the current ubuntu versions we would need:

1. ubuntu-16.04 (latest LTS)
2. ubuntu-14.04 (previous LTS)
3. ubuntu-17.10 (latest release)
4. ubuntu-18.04 (next release)

For debian, I see:

```
      1 debian-2017.10-1
      1 debian-2017.12-1
      1 debian-3.11
      5 debian-2018.01-1
      9 debian-2018.1
     16 debian-
     40 debian-7
    259 debian-8
    567 debian-9
```

So, we would need:

1. debian-7
2. debian-8
3. debian-9
4. debian-next 

The above for the latest of netdata + a nightly? We are already at 16 of them...

Similarly for centos:

```
      2 centos-6.6
      3 centos-2
      3 centos-6
      5 centos-6.5
     26 centos-6.8
     33 centos-6.9
   1068 centos-7
```

and rhel:

```
      1 rhel-2016.03
      1 rhel-3
      1 rhel-7.2
      2 rhel-7.3
     16 rhel-2016.09
     61 rhel-2017.03
     94 rhel-7.4
     95 rhel-2017.09
```

> You say that you're not sure how to build contrib/debian, but contrib/README.md looks pretty clear to me. Do you have specific questions about it?

yeah... I meant I never tried it.

> How is Travis working out for you so far?

hm... it is slow yes (although the last month is acceptable). 

> your own CI server.

We have a VM to spare on this, so it can done.

**Comment by ktsaou** [comment] 2018-02-27 20:25
btw, we already have 2 servers that run all versions of distros as lxc containers:

https://octopuscs.my-netdata.io/
https://stackscale.my-netdata.io/

I use them for testing and they also participate in the demo sites.

**Comment by FooBarWidget** [comment] 2018-03-01 20:32
All right, sounds like it would be wise to start with Ubuntu 16.04 then. Is x86_64 the most popular architecture?

So let's first talk about how Debian packaging works. Its documentation is quite horrible so let me give you a summary of the basic concepts involved.

## Basic packaging workflow

In a nutshell, there is this `debian/` directory which contains all sorts of files that describe the package, such as:

 * What its name, version number, dependencies are.
 * How your application is supposed to be compiled, and (after compilation) which files are supposed to be placed where in the package.

The tool that creates a Debian package is *dpkg-buildpackage*. It is to be run inside your application's source directory. This directory must contain a `debian/` subdirectory. Dpkg-buildpackage compiles your application per your instructions, copies the files that you designated into the package, and outputs a .deb file (among a bunch of other things).

Now, dpkg-buildpackage is a bit weird and counter-intuitive, probably because it was designed from the point of view of an external packager who is not the developer the app. Here are some of the weird facts:

 * dpkg-buildpackage also expects a tarball of the app's source code in the *parent* directory. Yeah, in addition to you already being in the app's source directory. And this tarball must have a specific name.
 * The version number of the package is determined from a changelog file inside `debian/`. This changelog file is to describe all the changes that the packaging work has undergone, and must follow a specific format.

### Redo packaging work per distro version?!

Another weird fact is that they expect you to redo or customize the packaging work for every distribution version! So suppose that on Debian 7/Ubuntu 14.04 you need to install a file to /usr/lib/foo, but on Debian 8/Ubuntu 16.04 you need to install to /usr/lib/bar.

Since most packaging stuff between distribution versions does not change, it would make sense if the packaging specification can describe something like "if debian 7, then /usr/lib/foo; if debian 8, then /usr/lib/bar", because then you only need a single packaging specification to output multiple distribution packages. But you can't. They literally expect you to take the previous `debian/` directory, modify it for the next distro version, and build a new package. Want to package a new version of the same app, but for the previous distro version? Take the previous distro version's `debian/` directory and modify it -- a process which they call "backporting".

Debian/Ubuntu packagers accept this workflow because most of their effort is focused on the latest distribution version. But as you can imagine, this creates a lot of extra effort for people like us who just want to distribute our app to our users, who may be on multiple distribution versions.

For Passenger, I used a preprocessing system to allow me to have a single packaging specification that supports multiple distributions. Clauses like "if debian 7 then ..." are evaluated by the preprocessing system.

## Ecosystem

On top of dpkg-buildpackage, there is this wrapper tool called `debuild` which automate more workflow tasks such as stuff related to signing. You don't need to understand it, just know that it exists and works similarly to dpkg-buildpackage (because it wraps dpkg-buildpackage).

Debian also has a bunch of archaic tools like "pbuilder-dist" which help you build packages for multiple distributions even though you are running on a specific distribution version. But nowadays I don't recommend those tools; it's easier to use Docker for this purpose.

## Recommended reading

The best practical guide on Debian packaging that I know of is [Pragmatic Debian packaging](https://vincent.bernat.im/en/blog/2016-pragmatic-debian-packaging). I am also working on [my own tutorial series](https://github.com/phusion/debian-packaging-for-the-modern-developer) but it's still work in progress.

This concludes today, since it's evening. I'll answer your concrete questions tomorrow.

**Comment by FooBarWidget** [comment] 2018-03-02 11:47
## On APT repositories

Debian packages are just the .deb files. What users usually interact with are APT repositories. They consist of the .deb files themselves and a bunch of metadata files, such as indices, checksums, etc.

I do not recommend self-hosting APT repositories. There are many tools for self-hosting APT repositories, but they all have one or more of the following problems:

 1. Not user friendly
 2. Lack of documentation
 3. Various usage quirks that make them really difficult to work with

The tools that Debian and Ubuntu use for their own repositories have problems (1) and (2). If you *have* to self-host, then choose reprepro because it's the easiest and "only" has problem (3).

Instead, I recommend [PackageCloud](https://packagecloud.io/). They have a free open source plan.

Ubuntu's Launchpad PPA system is a second contender. They are free but their user interface is really bad, and you won't understand what's going on until you've understood several key concepts. However I can guide you through it if so needed.

## Source packages

The .deb files that we usually work with are *binary packages*. But there is also the concept of "source packages". If you just want to provide your own APT repository and packages for users to use, then you don't have to care about this. But if you want to contribute your package to Debian/Ubuntu, or if you want to use Ubuntu's Launchpad PPA system, then you have to know this.

A "source package" is actually a set of 3 files:

 * A tarball of the `debian/` directory, containing the packaging specifications.
 * A tarball of the original application's source code, without the `debian/` directory. The so-called "orig tarball".
 * A file containing checksums of the above.

The idea is that a source package contains and describes everything one needs to generate the corresponding binary package. The source package describes "build dependencies": what dependencies must be installed in order to compile the application.

Debian and Ubuntu packagers work by uploading not binary packages, but source packages to their official repositories. Packagers don't publish binary packages by compiling on their laptop. Instead, the Debian and Ubuntu build farm builds source packages.

This is also how the Ubuntu PPA system works. You upload source packages, not binary packages. Ubuntu's PPA then builds the source packages for you.

This may be quite a hassle to us developers who just want to distribute binaries to users. For example, the other day I was building a package for [the Nginx ModSecurity module](https://github.com/phusion/nginx-modsecurity-ubuntu). Besides the source code of the Nginx ModSecurity module, I also needed the source code of Nginx itself, plus a checkout of the v3/master branch of the ModSecurity project. But the Debian packaging system insists that there must only be 1 orig tarball. So I had to write a script that bundles all 3 of those things together in a single tarball.

PackageCloud on the other hand allows hosting binary packages, so it's probably the most pragmatic choice.

## QA

With that out of the way, let me answer your questions.

> question: for each distro version do we need a separate ppa?

I assume you are referring specifically to the Ubuntu Launchpad PPA system, and not "third party APT repositories" in general.

No, you just need a single PPA. It can host packages for multiple distributions.

**Comment by FooBarWidget** [comment] 2018-03-02 11:58
In this comment I will talk about concrete steps towards a system that generates Ubuntu 16.04 packages every release and on a nightly basis.

The work in contrib/debian/ seems quite outdated. If you're going to publish OS packages, then it is important that they don't conflict with, and gracefully upgrades from, any existing distribution-provided packages that users may have already installed.

In light of this, I suggest taking Debian's or Ubuntu's packaging work as a base. That way you know you are compatible.

You should set up an Ubuntu 16.04-based Docker container which contains the appropriate tools for building a netdata package. Then you can setup a CI job which invokes this container whenever you want.

You can take a look at [my netdata for Ubuntu 16.04 packaging work](https://github.com/phusion/netdata-ubuntu-16.04). It is exactly what I described above. It contains packaging specifications, as well as a Docker container that is able to build the package. The container in that repository is meant to be used interactively, but maybe you modify things here and there to make it work well in a non-interactive CI environment.

**Comment by baoboa** [comment] 2018-03-05 18:16
hello 
@ktsaou 
About packaging and repo for the redhat family i did comment on it in issue #1306 i don't know if you have seen it.
 https://github.com/firehol/netdata/issues/1306#issuecomment-367062480

**Comment by ktsaou** [comment] 2018-03-05 20:42
@FooBarWidget wow! Lot's of useful info! Thank you for sharing your knowledge and experience!

I have requested a FOSS license from packagecloud.

I understand you are quite experienced on this. What do you suggest for an action plan? I mean, it is quite simple to fire a docker and do something, but the whole thing requires a lot of tweaking here and there to be done right.

Is this something you can make a PR to get us started?

The current debian files are maintained by @lhw @FedericoCeratto . These files have been used to submit netdata to debian. Would your changes be conflicting?

(btw, all the package maintainers are listed at #651)

---

@baoboa yes I saw it and seems quite interesting. But let's put debian/ubuntu on track and I think redhat/centos/fedora will follow.

**Comment by ktsaou** [comment] 2018-03-05 23:27
ok we have a packagecloud.io account...

**Comment by FooBarWidget** [comment] 2018-03-06 08:13
> What do you suggest for an action plan?

**Phase 1: basic packaging and automation**

Goals:

 * Have one or more people who have basic knowledge about packaging.
 * Have basic packaging scripts/specs in place, for Ubuntu 16.04 only.
 * Every time you release a new Netdata version, run the packaging script manually to product an Ubuntu 16.04 package, which you can then upload to PackageCloud.

Steps:

1. **People organization.** Designate a person who will be responsible for packaging. Preferably two people, for redundancy. Packaging is tricky and specialized enough as to require dedicated people who are specialized in this.
2. **Learning.** Have them learn the basics of Debian packaging, e.g. through the resources I posted above. Start with packaging a bunch of hello world apps before packaging Netdata, in order to learn how things work.
3. **Packaging script that runs locally (no CI).** Create a script (and corresponding Debian packaging specs) that, given a netdata source tree, uses an Ubuntu 16.04 Docker container to produce an Ubuntu 16.04 package. This script should be fully non-interactive. Once you have this script, you can just run it on a laptop (maybe in Virtualbox) every time you release a new Netdata version. You can [take my netdata packaging work](https://github.com/phusion/netdata-ubuntu-16.04) as a template, and modify it until you have such a script.

**Phase 2: automation and nightly packages**

1. Setup a CI server which runs the packaging script once a day, and which automatically uploads the result to PackageCloud (under a separate repository).
2. Ensure security, monitoring, access control, etc.

**Phase 3: extending to other Debian and Ubuntu versions**

1. **Decide on a packaging spec distro version management strategy.** Different versions of Ubuntu and Debian require slightly different packaging specs. Though most stuff probably stays the same, dependency names may be different, directories may be different, system integrations may be different (e.g. does this distro version use SysV init or systemd?). How do you manage the different packaging specs? Here are some possible strategies:

  1. Maintain a separate packaging spec directory per distribution version, e.g. "contrib/debian8", "contrib/debian9", "contrib/ubuntu16.04", "contrib/ubuntu18.04".

     Pros: each directory allows you to fully focus on the packaging work for that distribution version; you won't get distracted by stuff that is meant for other distribution versions.

     Cons: you will end up with a lot of duplication. Suppose that you want to change the package description. You will have to redo this change for every distribution version.

  2. Maintain a single packaging spec directory (e.g. just "contrib/debian") and use a preprocessing system to generate the final packaging spec for a specific distro version. This is the approach that I use. For example let's say we use Ruby's ERB tool as preprocessing system. In a hypothetical "contrib/debian/control" I could specify:

      ~~~
      Package: netdata
      Dependencies:
        dependency1, dependency2,
        <% if is_distro?("<= debian8") -%>
           dependency-name-for-debian-8-and-earlier
        <% else -%>
           dependency-name-for-debian-9-and-later
        <% end -%>
      ~~~

      Pros: way less duplication. If you want to change something which should be changed the same way for all distros, then you only need to do it once.

      Cons: may potentially end up with a lot of if-else clauses in your files, making the specs hard to read.

2. **Decide on a distribution support policy.** Which distribution versions and architectures do you want to support? "All of them" is a noble goal but not pragmatic. Especially ARM packages are problematic: there are not that many users and also not that many cloud services running on ARM. Managing real ARM hardware is a pain, like managing any real hardware.

   The policy that Passenger maintains is this:

    * Ubuntu: we package for all LTS versions that Canonical still supports, and we package for the latest version even if that's not an LTS. So at the time of writing (2018 March 6), we package for 14.04, 16.04 and 17.10.
    * Debian: we package for all versions that Debian still supports. So at the time of writing we package for Debian 8 and 9.
    * We only package for x86 and x86-64, though soon we will drop x86 (not enough users).

3. Modify the packaging scripts to accept a target distribution version as a parameter.

4. Modify the packaging specs to support the distribution versions you want. There are no specific instructions for this, you just have to find out what modifications are needed by trial and error. Try to build the existing specs on a different Ubuntu/Debian version, try to install them, and test whether everything works. If not, modify whatever needs modifying and try again.

5. Modify the CI server to build multiple packages, one for each supported distribution version. Just invoke the packaging script with a different parameter.

> Is this something you can make a PR to get us started?

Possibly, but at this point I am not able to give a guarantee. I'm quite busy with my day job (I'm an entrepreneur). I may be able to allocate company time to work on this so that it would be a sponsorship of some sort. This means that we'll use netdata and the contributed work to promote ourselves. If you don't mind this then I can investigate this option.

**Comment by FedericoCeratto** [comment] 2018-03-06 09:44
@lhw and me are the authors and uploaders of the Debian and Ubuntu packages.
The packaging files are currently hosted at https://anonscm.debian.org/git/collab-maint/netdata.git/tree/debian
The files are up to date and can be easily reused to build nightly packages without significant modification.
This entire conversation seems to be unnecessary.

**Comment by FooBarWidget** [comment] 2018-03-06 09:49
Ah, I was looking at the contrib/ folder inside the netdata repo. It's good that we know where the actual, up-to-date work is hosted. Thanks for clearing that up.

Still, my conversation also focuses on automation via a CI server. For users, it is ideal if source and binary packages are released simultaneously, instead of needing to wait for the packaging team to do the job. @ktsaou also mentioned the desire to have nightly-built packages. In order to achieve this goal, packaging should be an integral part of the netdata development process, not something external that is "thrown over the wall". A... "DevPackageOps" if you will.

**Comment by ktsaou** [comment] 2018-03-11 12:25
ok, nice info! thank you @FooBarWidget !

@lhw @FedericoCeratto can you help me automate the  whole procedure? I mean:

1. have up to date files for debian/ubuntu packages in the netdata repo
2. have a script build the packages for each supported distro version (it will be called from travis or any other ci we will use)
3. upload the generated files to github releases (with the release procedure - I think @philwhineray can give us a few directions on how this is done)
4. on every merge we do on the master branch, push the generated files to packagecloud so that people will be able to use them

If we can do the above, we can change the installation instructions for debian/ubuntu to use these packages.

**Comment by paulfantom** [comment] 2018-12-20 15:02
To all interested parties: I would like to unify how netdata packages are versioned, more in #5044

**Comment by lhw** [comment] 2018-12-21 08:17
I could link you to how the Gitlab instance from debian itself does the package building:
https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml I make use of it here: https://salsa.debian.org/lhw-guest/looking-glass/blob/master/debian/gitlab-ci.yml
Maybe you can adopt it to travis-ci or similar software. For the build instructions you can pull the latest debian/ from https://salsa.debian.org/debian/netdata
Otherwise I dont really have done any work on automating debian pacakage building.

**Comment by paulfantom** [comment] 2018-12-21 09:01
@lhw thanks for those links, they will be very helpful in the near future! :+1:

Right now I am trying to standardize couple of things in netdata repo to make packaging more robust and flexible so we could extend it to other platforms and integrate into CI pipeline. 
Current high-level plan is to:
1) Clean up and standardize
2) Decommission automake and rely solely on CMake (currently both are used in different scenarios)
3) Adopt CPack

There are some interim steps involved like moving away from git for managing updates and storing nightly build artifacts in GCS.

However main point for now is to simplify and standardize version numbering and to require git while building netdata. I am trying to inform as many netdata packagers as possible since I know that there are existing scenarios which don't rely on git when creating netdata packages.

**Comment by paulkatsoulakis** [comment] 2019-05-05 12:12
Closing this, as we will be attempting to nail this through #5963

We won't be going for CPack and CMake now.
We will re-iterate later once we touch base with what we have now (Autotools).
Going for the longterm goals directly didn't help, it instead cost us a lot of bug fixing on broken existing installers that affected our users.

**Closed by paulkatsoulakis** 2019-05-05 12:12 UTC
Labels: area/packaging, priority/medium
