### ISSUE TITLE
Build packages for Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by n0guest** [netdata/netdata#439] opened 2016-05-22 20:40 UTC
Hi, guys.

I've used an information from #42 and some files from contrib/debian to build a deb package of v1.2.0 for Ubuntu 14.04.x. Will you accept this small improvement to upstream? I guess, having clear instruction for building deb packages for Ubuntu will be useful for someone else.

For a start, you need to install all packages, mentioned in "Install guide" and this additional packages:
- debhelper
- dh-autoreconf
- dpkg-dev

Here is upstart configuration file, that you should put in contrib/debian as netdata.upstart:

```
#  netdata - Real-time charts for system monitoring
#
#  Netdata is a daemon that collects data in realtime (per second)
#  and presents a web site to view and analyze them. The presentation
#  is also real-time and full of interactive charts that precisely
#  render all collected values.

description  "realtime system monitoring daemon"

start on filesystem and net-device-up
stop on runlevel [!2345]

expect daemon
respawn

exec /usr/sbin/netdata
```

And because Ubuntu 14.04 uses upstart instead of systemd, you need to delete mention of systemd from debian/rules near  line 11. All other steps same as for debian - just create a symlink and use dpkg-buildpackage as described in contrib/Readme.md.

PS: Heh, after writing all of these, i've found #69 and existing PPA from @gslin. I hope at least upstart config will be useful? ;)

**Comment by DroWnThePoor** [comment] 2016-06-20 03:40
@n0guest I added gslin's PPA, but it didn't seem to create anything except /etc/netdata/ on my Ubuntu 14.04 system. On the other hand trying to build it myself has given me errors. So I'm going to try your method.

**Comment by ktsaou** [comment] 2016-06-20 05:59
@mcnewton can we integrate this into netdata?

**Comment by paulfantom** [comment] 2016-06-20 09:23
@n0guest wouldn't building packages for ubuntu 14.04 be similar to building them for debian wheezy?
[And we have instructions for building netdata deb on wheezy](https://github.com/firehol/netdata/tree/master/contrib)

**Comment by n0guest** [comment] 2016-06-20 15:13
@paulfantom, sorry, i don't remember exact list of changes. But in short:

- minor changes in debian/control and debian/rules for Debian/Ubuntu (e.g. remove systemd)
- upstart script for Ubuntu 12/14
- small fixes in Debian init script (because of problems with /run)
- something else for CentOS (part of it in #403)

I made those changes and build deb/rpm packages for:

- Debian 7/8
- Ubuntu 12/14
- CentOS 6/7

It was made for internal usage. And surely, it's not a great deal, but i want to share this with rest of community.

PS: BTW, deb packages doesn't include directory for netdata registry. In other words, it disabled by default now. May be, this needs to be fixed also.

**Comment by paulfantom** [comment] 2016-06-20 16:31
@n0guest could you make a PR with your build specs for those systems, especially for CentOS? It would help me a lot with setting up some automated build system for netdata.

**Comment by mcnewton** [comment] 2016-06-20 19:31
Hi,

I don't use Ubuntu, but I thought that they used systemd these days, so upstart configs are just for out of date systems?

The biggest issue is usually creating a debian/rules to build packages for different init systems. You find that you need slight differences for sysvinit vs systemd vs upstart. So just merging changes that make it work for upstart will probably break things for systemd unless it's very carefully done.

For instance, I don't believe you can just remove the systemd references (you say "e.g. remove systemd") from debian/rules to make it work with upstart. You'll then find the correct systemd postinst/prerm scripts are not included and the package then won't work correctly for systemd machines such as Debian Jessie and newer Ubuntu.

Cheers,
Matthew

**Comment by n0guest** [comment] 2016-06-20 19:53
It's little harsh to name LTS releases as "outdated". For a start, 12.04 was released in 2012 and will be supported until 2017. And same logic for 14.04 - released in 2014 and support until 2019. I don't see any reasons why this systems must receive systemd instead of upstart. BTW, i really hate idea, that systemd is used in Ubuntu 16.04 LTS. Just because systemd is a piece of crap. But it's offtopic for this issue ;)

And no, i didn't have any problems with post-install scripts under Ubuntu 12 or 14 (at least with release 1.2.0). And we still have many servers with Debian 7 where is no systemd, just old "plane" init scripts. To be clear - we're supporting servers of our clients and we have to deal with OS, that installed on their server. We can't reinstall to something else, just because we want it.

Yes, i agree, that merging them all (separate init script for Debian 7 and CentOS 6, upstart for Ubuntu 12/14) will cause many inconveniences for end-users. For example, Nginx packages (from official PPA) have init script and upstart. And it often  causes many stupid situations. 
But also, i don't have ideas how to make this right. It's your call to decide. I'm just offering to share what i did to use netdata "normally" on all of this platforms (i.e. w/out any problems with start/stop/restart independently of initialization system specifics).

**Comment by paulfantom** [comment] 2016-06-20 19:53
@mcnewton Yes ubuntu uses systemd now, but we want support for all LTS releases from 12.04. 
Also netdata doesn't use any fancy systemd-specific configuration in service file which cannot be easily ported to init or upstart.

**Comment by n0guest** [comment] 2016-06-20 20:35
I've tried to summarize my changes, but it's a real mess 8)

I doubt, that it worth a PR in this state. You can see it by yourself [here](https://github.com/n0guest/netdata/commit/950823c0a6936c81aa50b4e146183c65ffbd6b2c). If you have any ideas how to make this in a right way - be my guest. And i'll try to clean it up and made more useful for end-users.

**Comment by mcnewton** [comment] 2016-06-20 21:19
OK - as I said, I don't use Ubuntu, I just heard (what seems like a few years ago) they use systemd now; didn't realise there were LTS versions that were still kicking around.

@paulfantom agreed there's no fancy stuff - but I think it's still hard building .debs to support upstart/systemd/sysvinit all from the same debian/rules. But I'm happy to be proven wrong on that one :)

@n0guest exactly the same sentiments on the systemd crap. But definitely off-topic here :) Unfortunately everyone seems to be using it, so it makes sense to be the main thing that is supported, however nasty it may be. Though I'll happily admit it does make some things easier than sysvinit, but only for applications that easily fit into its mould.

Cheers,
Matthew

**Comment by mcnewton** [comment] 2016-06-20 21:28
@n0guest on your changes I would suggest not adding patches for debian control files (debian/control, debian/rules, etc) as that will get very messy very quickly.

IMO it's probably best to make things generic as possible, wherever possible, but where not then to just have a duplicate with the different changes.

So for example it might be possible to update `debian/rules` to put the `--with autoreconf,systemd` into a variable, then somehow detect what is required (look in /etc/debian_version?) or pass it in somehow.

But `debian/control` should probably just have other copies (e.g. `debian/ubuntu14/control`), then the build instuctions say to:

    $ cp -r contrib/debian .
    $ mv debian/ubuntu14/* debian/
    $ dpkg-buildpackage

or similar. Then try and keep files in contrib/debian/ubuntu...(or whatever)/ as few as practically possible. Still messy, but it's always going to be, and means patches in the source tree can't get out of sync.

Maybe someone can find examples of another project that has solved this problem.

Matthew

**Comment by ktsaou** [comment] 2016-06-21 08:42
Having different directories for different distros is probably the most clean solution...

**Comment by n0guest** [comment] 2016-06-22 00:31
> Having different directories for different distros is probably the most clean solution...

So, you've decided? Do you need me to clean up something in my repo before PR? 
I can try to make universal debian/rules files, but i really doubt, that it's possible for debian/control. Because of this, i think it has no sense.

PS: BTW, our package repositories are publicly accessible and if someone want, they can add it like this:

```curl -v https://pkgs.osshelp.ru/install | bash```

We have netdata packages for CentOS/Debian/Ubuntu. But, please, note, that it contains not only netdata packages (nginx w/custom modules, s3cmd, etc).

**Comment by ktsaou** [comment] 2016-06-22 10:04
> So, you've decided?

If it can be done in one directory, it would be perfect. But can be done? If not, then different directories should be used.

> Do you need me to clean up something in my repo before PR?

I am afraid I am not the right person for deciding this. Probably @mcnewton can help (would you please?).

> Our package repositories are publicly accessible

Nice. Could you please open an issue with the content you would like me to publish? I'll add a wiki page for your work, but please give me its content.

**Comment by mcnewton** [comment] 2016-06-22 13:50
I'm pretty busy right now but if I get a chance I'll see if I can take a look.

Multiple directories is probably clean, but leads to a lot of duplication, which is the downside. Especially when one common file needs to be updated, and is then forgotten in other distros. Then you end up maintaining multiple debian/ directories that have all diverged slightly.

Maybe there is a better way, but I'm not currently aware of one, so if anyone has any suggestions they would be welcome :-). Maybe symlinks (or a makefile to make the correct symlinks) for files that are different? TBH I don't think many files will differ between distros, but it may be some of the core ones which cause problems (such as `debian/control` or `debian/rules`).

Matthew

**Comment by ktsaou** [comment] 2016-06-22 21:42
What if we keep only diffs in separate directories? We could, for example, have a base directory and multiple directories for different distros where we keep only the files that are different. Will this work?

**Comment by mcnewton** [comment] 2016-06-23 09:58
"diffs" as in patches, or "diffs" as in files that are different?

Patches would get messy I think.

Files that are different should be workable, but there may be problems with core packaging files such as debian/control or debian/rules.

The alternative might be a contrib/debian/{debian7,debian8,ubuntu14,ubuntu15,...} directories each with their own rules, control, etc files (or maybe symlinks if possible), and then a contrib/debian/common directory with shared files. Still looking a bit messy though, but would mostly solve the problem of lots of duplicated files.

Maybe just have debian/control.ubuntu14, debian/control.ubuntu, debian/control.debian, etc, and a Makefile rule which symlinks the most appropriate one depending on the contents of /etc/debian_version. Just thinking through ideas...

Matthew

**Comment by danfinn** [comment] 2016-08-03 22:09
Does anyone happen to have a set of clear instructions for building Ubuntu packages for 14.04?  I've read through this thread a couple of times but I don't see an obvious answer.

**Comment by ktsaou** [comment] 2016-08-04 21:09
Sorry... I don't know. Anyone else?

**Comment by mcnewton** [comment] 2016-08-04 21:44
On Thu, Aug 04, 2016 at 02:10:14PM -0700, Costa Tsaousis wrote:
> Sorry... I don't know. Anyone else?

I think the closest instructions would be those at

  https://github.com/firehol/netdata/blob/master/contrib/README.md

which should work, though I've not tested on Ubuntu. I don't know if that
version uses systemd or not, so you may have to tweak things as also described
in that readme.

-- 
Matthew

**Comment by paulfantom** [comment] 2018-09-22 17:11
Closing as this is a partial duplicate of #69

**Closed by paulfantom** 2018-09-22 17:11 UTC
Labels: duplicate, packaging
