### ISSUE TITLE
Run the auto-installation script bash <(curl -Ss https://my-netdata.io/kickstart.sh)  failed

### ISSUE THREAD

**Issue by xgxdmx** [netdata/netdata#8589] opened 2020-04-03 04:45 UTC
Run the auto-installation script bash <(curl -Ss https://my-netdata.io/kickstart.sh)  failed

  GEN      netdata
/usr/bin/ld: externaldeps/libwebsockets/libwebsockets.a(unix-caps.c.o): in function `lws_plat_drop_app_privileges':
unix-caps.c:(.text+0x23e): undefined reference to `cap_get_proc'
/usr/bin/ld: unix-caps.c:(.text+0x25a): undefined reference to `cap_set_flag'
/usr/bin/ld: unix-caps.c:(.text+0x262): undefined reference to `cap_set_proc'
/usr/bin/ld: unix-caps.c:(.text+0x282): undefined reference to `cap_free'
/usr/bin/ld: unix-caps.c:(.text+0x2d8): undefined reference to `cap_get_proc'
/usr/bin/ld: unix-caps.c:(.text+0x2f1): undefined reference to `cap_set_flag'
/usr/bin/ld: unix-caps.c:(.text+0x2f9): undefined reference to `cap_set_proc'
/usr/bin/ld: unix-caps.c:(.text+0x319): undefined reference to `cap_free'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:4065: netdata] Error 1
make[2]: Leaving directory '/tmp/netdata-kickstart-CnwrS4/netdata-v1.20.0-303-g007f27cd'
make[1]: *** [Makefile:5124: all-recursive] Error 1
make[1]: Leaving directory '/tmp/netdata-kickstart-CnwrS4/netdata-v1.20.0-303-g007f27cd'
make: *** [Makefile:2788: all] Error 2
 FAILED

 FAILED

 ABORTED  netdata-installer.sh exited with error

**Comment by xgxdmx** [comment] 2020-04-03 04:49
Ubuntu Focal Fossa (development branch) (GNU/Linux 5.5.0-050500-generic x86_64)

**Comment by Ferroin** [comment] 2020-04-03 12:22
@xgxdmx Is this on a clean install with the most recent version of Ubuntu Focal, or have you modified the system in any way?

**Comment by nioConisaC** [comment] 2020-04-03 13:00
I've the same issue ...

**Comment by nioConisaC** [comment] 2020-04-03 13:02
The issue occurred after I've installed cmake. I have tried uninstall netdata and reintall it but get same result as @xgxdmx

**Comment by Ferroin** [comment] 2020-04-03 13:13
We've tried to reproduce this locally and couldn't, and our CI is currently passing for Ubuntu 20.04 (see https://github.com/netdata/netdata/runs/556672828?check_suite_focus=true for recent passing build logs).

To figure out what exactly is going on here we're going to need more info, such as whether this is on a clean install of Ubuntu or not

**Comment by nioConisaC** [comment] 2020-04-03 13:15
I'm on this: NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by nioConisaC** [comment] 2020-04-03 13:16
It's a clean install of Ubuntu, Yes!

**Comment by nioConisaC** [comment] 2020-04-03 13:23
it's entire the same issue as @xgxdmx Mine looks like this: 
externaldeps/libwebsockets/libwebsockets.a(unix-caps.c.o): In function `lws_plat_drop_app_privileges':
unix-caps.c:(.text+0x381): undefined reference to `cap_get_proc'
unix-caps.c:(.text+0x399): undefined reference to `cap_set_flag'
unix-caps.c:(.text+0x3a1): undefined reference to `cap_set_proc'
unix-caps.c:(.text+0x3c1): undefined reference to `cap_free'
unix-caps.c:(.text+0x411): undefined reference to `cap_get_proc'
unix-caps.c:(.text+0x42d): undefined reference to `cap_set_flag'
unix-caps.c:(.text+0x435): undefined reference to `cap_set_proc'
unix-caps.c:(.text+0x455): undefined reference to `cap_free'
collect2: error: ld returned 1 exit status
Makefile:3845: recipe for target 'netdata' failed
make[2]: *** [netdata] Error 1
make[2]: Leaving directory '/home/crn01/netdata'
Makefile:4899: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/crn01/netdata'
Makefile:2569: recipe for target 'all' failed
make: *** [all] Error 2
 FAILED

**Comment by Ferroin** [comment] 2020-04-03 13:47
Oh, you're on 18.04 not 20.04. That at least helps narrow down where the issue might be.

**Comment by Ferroin** [comment] 2020-04-03 13:51
Can you share the output of `dpkg -l | grep libcap`? We think the build-time logic may be failing to correctly detect the presence (or absence) of one of the packages that's needed for an optional part of the build.

**Comment by xgxdmx** [comment] 2020-04-03 13:52
I don't know why, These two days I just routinely use the apt upgrade program. But what I can be sure of is that two days ago there was no problem because I executed this script two days ago.

**Comment by nioConisaC** [comment] 2020-04-03 13:54
I agree with @xgxdmx the issue started 2days ago.
However here's the output:
ii  libcap-dev:amd64                           1:2.25-1.2                                       amd64        POSIX 1003.1e capabilities (development)
ii  libcap-ng0:amd64                           0.7.7-3.1                                        amd64        An alternate POSIX capabilities library
ii  libcap2:amd64                              1:2.25-1.2                                       amd64        POSIX 1003.1e capabilities (library)
ii  libcap2-bin                                1:2.25-1.2                                       amd64        POSIX 1003.1e capabilities (utilities)

**Comment by xgxdmx** [comment] 2020-04-03 13:56
Also if I use this script and add --no-updates, it works withno errors

**Comment by xgxdmx** [comment] 2020-04-03 14:02
`
ii  libcap-dev:amd64                          1:2.32-1                               amd64        POSIX 1003.1e capabilities (development)
ii  libcap-ng0:amd64                          0.7.9-2.1build1                        amd64        An alternate POSIX capabilities library
ii  libcap2:amd64                             1:2.32-1                               amd64        POSIX 1003.1e capabilities (library)
ii  libcap2-bin                               1:2.32-1                               amd64        POSIX 1003.1e capabilities (utilities)
`

**Comment by xgxdmx** [comment] 2020-04-03 14:02
root@Star:~# dpkg -l | grep libcap
ii  libcap-dev:amd64                          1:2.32-1                               amd64        POSIX 1003.1e capabilities (development)
ii  libcap-ng0:amd64                          0.7.9-2.1build1                        amd64        An alternate POSIX capabilities library
ii  libcap2:amd64                             1:2.32-1                               amd64        POSIX 1003.1e capabilities (library)
ii  libcap2-bin                               1:2.32-1                               amd64        POSIX 1003.1e capabilities (utilities)

**Comment by xgxdmx** [comment] 2020-04-03 14:10
> @xgxdmx这是使用Ubuntu Focal最新版本进行的全新安装吗？还是您以任何方式修改了系统？
I used the apt upgraded system and installed nginx, PHP, docker, mariadb, cockpit and other environments

**Comment by Ferroin** [comment] 2020-04-03 14:11
Short term fix until we get this working correctly is to re-install with `--disable-cloud` passed to the installer.

**Comment by underhood** [comment] 2020-04-03 14:12
Is it possible to get configure output from failed install?

**Comment by xgxdmx** [comment] 2020-04-03 14:14
sorry，When I use the installation script plus --stable-channel, it's normal no error. I'm sorry I just said something wrong.

**Comment by xgxdmx** [comment] 2020-04-03 14:15
I've now returned the stable version, it's working

**Comment by nioConisaC** [comment] 2020-04-03 14:18
Ok, the quick fix  worked! Thanks @Ferroin !

**Comment by Ferroin** [comment] 2020-04-03 14:20
Indeed, the stable channel should work for the next few days as well. There's a new stable release coming out early next week though.

Hopefully we should have this fixed by then. We think we've figured out what's wrong, so there should hopefully be a PR up to fix it soon.

**Comment by xgxdmx** [comment] 2020-04-03 14:20
Thank you very much. This is an effective way to upgrade successfully.

**Comment by Ferroin** [comment] 2020-04-03 14:32
Reopening and updating labels. We're certain this is a bug, and we'll close this issue once we've fixed it.

**Closed** 2020-04-03 15:38 UTC
Labels: area/build, area/packaging, bug, priority/high

**Comment by underhood** [comment] 2020-04-03 15:48
@xgxdmx @nioConisaC thank you both for informing us and helping us figure out where the problem was

**Comment by ysamouhos** [comment] 2020-10-08 17:21
Hi guyz.. This one just came up again on ubnt 14.04. 

Exactly same error:
  GEN      netdata
externaldeps/libwebsockets/libwebsockets.a(unix-caps.c.o): In function `lws_plat_drop_app_privileges':
unix-caps.c:(.text+0x309): undefined reference to `cap_get_proc'
unix-caps.c:(.text+0x325): undefined reference to `cap_set_flag'
unix-caps.c:(.text+0x32d): undefined reference to `cap_set_proc'
unix-caps.c:(.text+0x34d): undefined reference to `cap_free'
unix-caps.c:(.text+0x361): undefined reference to `cap_get_proc'
unix-caps.c:(.text+0x379): undefined reference to `cap_set_flag'
unix-caps.c:(.text+0x381): undefined reference to `cap_set_proc'
unix-caps.c:(.text+0x3a1): undefined reference to `cap_free'
collect2: error: ld returned 1 exit status

system is:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

dpkg -l | grep libcap
ii  libcap-dev:amd64                           1:2.24-0ubuntu2                     amd64        development libraries and header files for libcap2
ii  libcap-ng0                                 0.7.3-1ubuntu2                      amd64        An alternate POSIX capabilities library
ii  libcap2:amd64                              1:2.24-0ubuntu2                     amd64        support for getting/setting POSIX.1e capabilities
ii  libcap2-bin                                1:2.24-0ubuntu2                     amd64        basic utility programs for using capabilities

adding --disable-cloud still works
