### ISSUE TITLE
[Bug]: old timestamps in prometheus after high load

### ISSUE THREAD

**Issue by pgassmann** [netdata/netdata#13670] opened 2022-09-16 10:17 UTC
### Bug description

After a server was under high load, we get warnings from victoriametrics (prometheus alternative) that some values have an old timestamp.
The delayed timestamps continue even after the load is back to normal.

```
# first appeared on a Gitlab runner instance
victoriametrics | 2022-08-31T13:28:19.653Z warn VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:68 resetting rollup result cache because the metric netdata_disk_space_GiB_average{job="netdata",instance="127.0.0.1:19999",host="gitlabrunner1",chart="disk_space._boot_efi",dimension="avail",family="/boot/efi",scraper_instance="gitlabrunner1"} (Timestamp=1661951710000, Value=0.054385) has a timestamp older than -search.cacheTimestampOffset=5m0s by 489.000s

# other server:
victoriametrics    | 2022-09-16T09:39:30.071Z	warn	VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:68	resetting rollup result cache because the metric netdata_disk_inodes_inodes_average{job="netdata",instance="127.0.0.1:19999",host="test1",chart="disk_inodes._zfsbulk_hotspare_dev3_zfsbulk_data-verify",dimension="avail",family="/zfsbulk/hotspare/dev3/zfsbulk/data-verify",scraper_instance="test1"} (Timestamp=1663320700000, Value=NaN) has a timestamp older than -search.cacheTimestampOffset=5m0s by 169.000s

```

the timestamp is set by netdata and is somehow not the same for all metrics:
```
root@gitlabrunner1 ~ # curl -s 127.0.0.1:19999/api/v1/allmetrics?format=prometheus | grep efi
netdata_disk_space_GiB_average{chart="disk_space._boot_efi",family="/boot/efi",dimension="avail"} 0.0543847 1661953587000
netdata_disk_space_GiB_average{chart="disk_space._boot_efi",family="/boot/efi",dimension="used"} 0.0042539 1661953587000
netdata_disk_space_GiB_average{chart="disk_space._boot_efi",family="/boot/efi",dimension="reserved for root"} 0.0000000 1661953587000
```

I assume its be because netdata is designed and configured to have low priority. if the system is under high load, netdata will not update as often.
But it should recover itself which it does not.

Restart of netdata fixes the issue.

It was only 1 disk metric that was reported by victoriametrics.

### Expected behavior

* netdata metrics should never be older than 5 min.
* netdata timestamps should not differ much between metrics
* after high load, netdata should recover and provide recent metrics

### Steps to reproduce

1. scrape metrics with vmagent, send to victoriametrics
2. put server under high load for longer period (build job or import job in our case)
3. metric timestamps are older than 5 min 
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
uname -a; grep -HvE "^#|URL" /etc/*release
Linux test1 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.5 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.5 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
# netdata -W buildinfo
Version: netdata v1.36.1
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

workaround would be to disable timestamps https://learn.netdata.cloud/docs/agent/exporting/prometheus#timestamps

Recover by restarting netdata

**Comment by pgassmann** [comment] 2022-10-17 07:57
@ilyam8 do you have an idea why this is not recovering on its own? its great that netdata ensures it does not steal resources when other process need it, but it should work properly once the load is over.

it is always a disk metric that is reported.

**Comment by ilyam8** [comment] 2022-10-17 08:03
Hi, @pgassmann. Any chance you can test the latest nightly release? (using docker container for example) There is a lot of optimization changes since v1.36.1.

**Comment by pgassmann** [comment] 2022-10-24 08:23
@ilyam8 thanks. looking forward to the next release. I now installed the nightly version from the edge apt repository.

Why is the nightly version lower than the current release? `v1.36.0-257-nightly`
our systems do automatically update apt packages.

**Comment by Dim-P** [comment] 2022-10-31 15:12
Hi @pgassmann . Do you still see this issue using the latest nightly release? 

We will also soon release a new stable version (hopefully this week).

**Comment by ilyam8** [comment] 2022-12-14 10:14
Closing due to no feedback and no other similar issues. Will reopen if the problem can be reproduced in v1.37.1

**Closed by ilyam8** 2022-12-14 10:14 UTC
Labels: bug, needs triage

**Comment by pgassmann** [comment] 2023-02-06 12:33
Error didn't appear again.
