### ISSUE TITLE
[Bug]: Segmentation fault using static builds on Raspbian 11 (32-bit)

### ISSUE THREAD

**Issue by Dim-P** [netdata/netdata#13872] opened 2022-10-24 12:44 UTC
### Bug description

When installing the latest nightly on a 32-bit Raspbian, the agent keeps restarting and hitting a segmentation fault.

### Expected behavior

Not to crash.

### Steps to reproduce

Install `netdata v1.36.0-257-g19f023c11` on a 32-bit Raspbian using a static build (default on Raspberry Pi).

### Installation method

kickstart.sh

### System info

```shell
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
```

### Netdata build info

```shell
Version: netdata v1.36.0-257-g19f023c11
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: armv7l
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Core dump:
```
#0  0x00563db4 in memchr (src=src@entry=0x1, c=c@entry=0, n=n@entry=2147483647) at src/string/memchr.c:16
#1  0x005642ae in strnlen (s=s@entry=0x1 <error: Cannot access memory at address 0x1>, n=2147483647) at src/string/strnlen.c:5
#2  0x00562310 in printf_core (f=f@entry=0xb533d238, fmt=fmt@entry=0x5a4d3c "chart://host:%s/instance:%s/dimensions:%s/after:%ld/before:%ld/points:%zu/group:%s%s/options:%s%s%s", ap=ap@entry=0xb533d134,
    nl_arg=nl_arg@entry=0xb533d160, nl_type=<optimized out>, nl_type@entry=0xb533d138) at src/stdio/vfprintf.c:594
#3  0x00562df8 in vfprintf (f=0xb533d238, fmt=fmt@entry=0x5a4d3c "chart://host:%s/instance:%s/dimensions:%s/after:%ld/before:%ld/points:%zu/group:%s%s/options:%s%s%s", ap=..., ap@entry=...)
    at src/stdio/vfprintf.c:683
#4  0x0056379c in vsnprintf (s=<optimized out>, n=255, fmt=0x5a4d3c "chart://host:%s/instance:%s/dimensions:%s/after:%ld/before:%ld/points:%zu/group:%s%s/options:%s%s%s", ap=...) at src/stdio/vsnprintf.c:54
#5  0x00037268 in snprintfz ()
#6  0x00105bac in query_target_generate_name ()
#7  0x00585cec in ?? ()
```

**Comment by blackketter** [comment] 2022-10-24 16:38
Seeing this on Raspbian GNU/Linux 10 (buster) too...

**Comment by Dim-P** [comment] 2022-10-24 17:55
@blackketter We know what's causing this and we are on it, seems like it happens only with static builds, so an immediate workaround is to build Netdata locally (I think this would make it work without the agent crashing).

**Comment by blackketter** [comment] 2022-10-24 18:00
> @blackketter We know what's causing this and we are on it, seems like it happens only with static builds, so an immediate workaround is to build Netdata locally (I think this would make it work without the agent crashing).

Thanks.  I can wait if it's likely to be fixed in the next nightly, but happy to try to build locally if that would help you.

**Comment by ilyam8** [comment] 2022-10-24 18:06
Switching to local builds can be problematic because it takes a lot of time, CPU, and memory resources to build Netdata with ML and Cloud support on a Raspberry Pi device.

**Closed** 2022-10-25 14:24 UTC
Labels: bug, area/packaging

**Comment by MrZammler** [comment] 2022-10-25 15:43
@blackketter Hi! Could tell us please if the problem is fixed for you with tommorow's nightly ?

Thanks!

**Comment by blackketter** [comment] 2022-10-26 02:05
We seem to be back in business.  Thanks so much for the fast turnaround.
