### ISSUE TITLE
Update check in dashboard not working correctly in Docker images.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#9296] opened 2020-06-08 17:03 UTC
##### Bug report summary

In some cases, the update check shown on the dashboard in our Docker images is not correctly reporting the absence of a new version.

##### OS / Environment

Any Docker install

##### Netdata version

Confirmed on current nightiles.

##### Component Name

area/packaging
area/web

##### Steps To Reproduce

Run our official Docker image as shown in the documentation, then navigate to the dashboard.

##### Expected behavior

The update check works correctly.

##### Additional information

I'm fairly certain that this is an unintentional side-effect of how we build Netdata for the Docker images.

**Comment by prologic** [comment] 2020-06-11 12:26
@Ferroin Can you please post screenshots of the error or some sample test? Is it just that if there is no new version it still thinks there is?

**Comment by Ferroin** [comment] 2020-06-11 14:26
> @Ferroin Can you please post screenshots of the error or some sample test? Is it just that if there is no new version it still thinks there is?

Effectively yes, with the caveat that the reported new version doesn't actually exist, and doesn't match the version numbers used in our Docker containers (which may be part of the issue).

I _think_ it's looking at a source other than the Docker images to try and figure out if a new version is available, but I'm not sure, and I don't know how we might fix it (or why it wouldn't be happening in the slightly modified (`FROM netdata/netdata` with stuff to add msmtp for email notification support) images I'm using in production on some of my systems).

**Comment by kachkaev** [comment] 2020-06-14 20:29
Observing this problem using Docker image `netdata/netdata:v1.22.1`: 

<img width="809" alt="Screenshot 2020-06-14 at 20 58 21" src="https://user-images.githubusercontent.com/608862/84602821-eb4e1a80-ae81-11ea-8f39-fe1c602a973e.png">

Issue history: #7295

**Comment by cakrit** [comment] 2020-08-10 13:47
This is how it works, starting at https://github.com/netdata/netdata/blob/master/web/gui/main.js#L2945
For stable versions, we check the github releases. For nightlies, we check GCS. code is copied below for convenience.

Why do we have different version numbers for Docker? Do they at least have the same format? Are we supposed to be looking elsewhere for docker? 

It's not a trivial change to implement a different algorithm to do version checking for docker.  Suppose we do it though, we'll do the same for all other installation methods as well? The logic right now is trivial, if a new version exists **anywhere**, the same exact version will exist **everywhere**, regardless of installation method. 

```
function getGithubLatestVersion(callback) {
    versionLog('Downloading latest version id from github...');

    $.ajax({
        url: 'https://api.github.com/repos/netdata/netdata/releases/latest',
        async: true,
        cache: false
    })
        .done(function (data) {
            data = data.tag_name.replace(/(\r\n|\n|\r| |\t)/gm, "");
            versionLog('Latest stable version from github is ' + data);
            callback(data);
        })
        .fail(function () {
            versionLog('Failed to download the latest stable version id from github!');
            callback(null);
        });
}

function getGCSLatestVersion(callback) {
    versionLog('Downloading latest version id from GCS...');
    $.ajax({
        url: "https://www.googleapis.com/storage/v1/b/netdata-nightlies/o/latest-version.txt",
        async: true,
        cache: false
    })
        .done(function (response) {
            $.ajax({
                url: response.mediaLink,
                async: true,
                cache: false
            })
                .done(function (data) {
                    data = data.replace(/(\r\n|\n|\r| |\t)/gm, "");
                    versionLog('Latest nightly version from GCS is ' + data);
                    callback(data);
                })
                .fail(function (xhr, textStatus, errorThrown) {
                    versionLog('Failed to download the latest nightly version id from GCS!');
                    callback(null);
                });
        })
        .fail(function (xhr, textStatus, errorThrown) {
            versionLog('Failed to download the latest nightly version from GCS!');
            callback(null);
        });
}


function checkForUpdateByVersion(force, callback) {
    if (options.release_channel === 'stable') {
        getGithubLatestVersion(function (sha2) {
            callback(options.version, sha2);
        });
    } else {
        getGCSLatestVersion(function (sha2) {
            callback(options.version, sha2);
        });
    }
    return null;
}
```

**Comment by cakrit** [comment] 2020-08-10 13:47
BTW I did the last changes on this code, so I can pick it up, if we need to change it.

**Comment by cakrit** [comment] 2020-09-14 07:48
@Ferroin / @prologic I will need a reply to https://github.com/netdata/netdata/issues/9296#issuecomment-671364169 if I'm to fix this.

**Comment by prologic** [comment] 2020-09-15 05:20
> @Ferroin / @prologic I will need a reply to [#9296 (comment)](https://github.com/netdata/netdata/issues/9296#issuecomment-671364169) if I'm to fix this.

> > Why do we have different version numbers for Docker? Do they at least have the same format? Are we supposed to be looking elsewhere for docker?

This is because different ecosystems require and use different patterns for versioning and we have to respect that. This includes RPM(s) too. If you do plan to fix this I _would_ recommend using a generalised version parsing/handling library.

**Comment by jacekkolasa** [comment] 2020-10-26 09:23
@Ferroin From what i see there is no issue with different pattern in Docker - it's just that version in docker is always patch nr less than the one available on GCS. The structure of version string stays the same

For example currently, on GCS: https://www.googleapis.com/download/storage/v1/b/netdata-nightlies/o/latest-version.txt?generation=1603673642145948&alt=media gives me `v1.26.0-64-nightly`, and after doing `docker pull netdata/netdata:latest` i see `v1.26.0-63-g92c32f27` in /api/v1/charts payload. I was doing that check for few days and always the number between dashes was smaller on docker by 1. The suffix (`g92c32f27` | `nightly`) is not a problem.

Do you know if this is just a coincidence or maybe that pattern will stay? Is it something we can fix?

**Comment by Ferroin** [comment] 2020-10-26 14:10
I think it’s a side effect of how we currently build the Docker images, and it _should_ be fixable, but I’m not certain what is causing it currently.

In theory, if it does not get fixed before we finally migrate over to GitHub Ations for the release workflow, that migration should fix it as most of that is being done from scratch in such a way that we aren’t screwing around with local commits in the checked out copy of the repo used for the release build like we seem to do currently.

**Comment by Ferroin** [comment] 2020-10-26 14:11
Moving this to the SRE backlog and updating assignee and tags because I’m pretty sure now that it’s a CI/release issue not a dashboard issue.

**Comment by Ferroin** [comment] 2022-02-22 16:21
Enough has changed here that we need to retest to see if it0s still an issue.

**Comment by ilyam8** [comment] 2022-02-22 16:55
Still an issue, but different from https://github.com/netdata/netdata/issues/9296#issuecomment-716422394.

I installed v1.31.1 tag, but

```cmd
[ilyam@pc ~]$ docker exec nd cat /etc/netdata/.environment | grep RELEASE
RELEASE_CHANNEL="nightly"
```

**Comment by Ferroin** [comment] 2022-02-23 18:09
Hmm, that looks like it0s a bug in how we’re building the Docker images. It’s _probably_ harmless (the image does appear to correctly be a build of v1.33.1), but it may be the root cause of this issue also.

**Comment by ilyam8** [comment] 2022-02-23 19:34
@Ferroin, it is the root cause. I forgot to add - manually changing RELEASE_CHANNEL to stable fixed the issue.

**Comment by Ferroin** [comment] 2022-02-24 16:48
OK, probably an issue in our docker CI workflow then, we’re most likely just missing a build arg there to set the channel properly.

**Comment by cpipilas** [comment] 2022-06-29 14:44
Fixed in the latest releases.

**Closed by cpipilas** 2022-06-29 14:44 UTC
Labels: bug, area/ci, area/web, priority/medium
