### ISSUE TITLE
Using python modules in new plugins

### ISSUE THREAD

**Issue by marcomusso** [netdata/netdata#8471] opened 2020-03-24 13:07 UTC
##### Question summary

I managed to write my own python plugin for a custom check and it works fine in debug/trace mode (as `netdata`) according to the docs (snippet):

```
2020-03-24 13:01:56: python.d DEBUG: logcollector_keepalive_message_count[logcollector_keepalive_message_count] :
started, update frequency: 30
CHART logcollector_keepalive_message_count.logcollector_keepalive_message_count '' 'Keepalive message count' 'mess
ages' 'count' 'count' line 20000 30 '' 'python.d.plugin' 'logcollector_keepalive_message_count'
DIMENSION 'count' 'count' absolute 1 1 ' '

BEGIN logcollector_keepalive_message_count.logcollector_keepalive_message_count 0
SET 'count' = 3
END

BEGIN netdata.runtime_logcollector_keepalive_message_count 0
SET run_time = 34
END
```

When running from the agent I get, in `error.log`:

```
2020-03-24 12:02:23: python.d WARNING: plugin[main] : [logcollector_keepalive_message_count] error on loading source : ImportError('cannot import name Elasticsearch',), skipping it
```

This is of course because I'm using the Elasticsearch python module which it seems not being recognised when running from the agent (but it's installed system-wide).

##### OS / Environment

CentOS 7.4.1708
netdata 1.20.0-1 installed as rpm

##### Component Name

python.d scrip

##### Expected results

I was hoping that the debug/trace was enough to guarantee the script to work when executed fro the agent.

**Comment by Ferroin** [comment] 2020-03-24 13:16
There's a known issue with the handling of the Python module search paths being different when running as a plugin from those when just manually running Python. I don't remember if there's an issue open about it or not, but this is likely what you're running into.

**Comment by marcomusso** [comment] 2020-03-24 14:53
But is there a documentation on how to add python modules or shall I consider it a missing feature or a bug?

**Comment by Ferroin** [comment] 2020-03-24 14:59
Basic documentation for the plugins can be found at https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/README.md#how-to-write-a-new-module. That doesn't include info on the above-mentioned issue with the module search paths because it's not a very well understood problem (we know it's there, just not why it's happenng or how to fix it). Behaviorally, the issue is that the Python collectors can't reliably see modules installed through `pip`, even if they're installed as the Netdata user, but (usually) has no issues finding ones installed through the system package manager.

**Comment by marcomusso** [comment] 2020-03-24 15:17
Thanks for elaborating further. Indeed I installed system-wide with `pip` and also tried to copy the module(s) to `/usr/libexec/netdata/python.d/python_modules` without success. I'll try with an rpm if available. This is quite impacting for custom scrips: in this case for example I'm interacting with Elasticsearch.... I could probably use simple requests but it quickly becomes a big job without the possibility of using modules...

**Comment by ilyam8** [comment] 2020-03-24 15:20
There is problem only when python package installed not system-wide.

**Comment by Ferroin** [comment] 2020-03-24 15:21
@ilam8 No, it's also a problem on some systems with 'system wide' isntalls of modules with `pip`. Gentoo for example suffers from this tpe of module search problem.

**Comment by ilyam8** [comment] 2020-03-24 15:27
Why? Are they are not in the system.path? I understand that there is no way for `--user` packages to work - Netdata changes `home` var on start. But whats the problem with system-wide installed?

**Comment by ilyam8** [comment] 2020-03-24 15:30
Anyway there is `PYTHONPATH` option int he `netdata.conf` @marcomusso 

> ImportError('cannot import name Elasticsearch',)

and it is no `no module named...` error 🤔

**Comment by ilyam8** [comment] 2020-03-24 15:36
>  which it seems not being recognised

probably it is not the problem @marcomusso

**Comment by marcomusso** [comment] 2020-03-24 16:16
I'll research a little bit more are report here if I find some workaround...

**Comment by marcomusso** [comment] 2020-03-24 16:59
Disabled selinux
Tried to force different PYTHONPATH with the conf options
Tried enabling full debug (debug flags = 0xffffffffffffffff and restart) =>empty debug.log (!)
Installed module in /usr/libexec/netdata/python.d/python_modules
"simplified" name of script (just before starting banging my head on the desk) to avoid unknown "mistic limitations" :)

No luck yet.

**Comment by ilyam8** [comment] 2020-03-24 17:14
could you share the script source code?

**Comment by marcomusso** [comment] 2020-03-24 17:31
Also installed rpm for python2-elasticsearch6.noarch.
I just started writing this scripts so don't expect a good one but it is working in debug mode.

Script:

```
# -*- coding: utf-8 -*-
# Description: counts number of keepalive mesages in the last 15m
# Author: marcomusso
# SPDX-License-Identifier: GPL-3.0-or-later

from elasticsearch import Elasticsearch
import json

try:
  from queue import Queue
except ImportError:
  from Queue import Queue

from bases.FrameworkServices.UrlService import UrlService

ORDER = [
    'logcollector_keepalive_message_count',
]

CHARTS = {
    'logcollector_keepalive_message_count': {
        'options': [None, 'Keepalive message count', 'messages', 'count', 'count', 'line'],
        'lines': [
            ['count'],
        ]
    },
}


class Service(UrlService):
  def __init__(self, configuration=None, name=None):
    UrlService.__init__(self, configuration=configuration, name=name)
    self.order = ORDER
    self.definitions = CHARTS
    self.update_every = self.configuration.get('update_every', 30)
    self.host = self.configuration.get('host', 'localhost:9200')
    self.username = self.configuration.get('username')
    self.password = self.configuration.get('password')
    self.es = Elasticsearch(
        self.host,
        http_auth=(self.username, self.password),
        verify_certs=True,
        use_ssl=True,
        ca_certs="/etc/ssl/certs/ca-bundle.crt",
    )

  @staticmethod
  def check():
    return True

  def _get_data(self):
    data = dict()
    index = "epenv-*"
    query = "{\"query\":{\"bool\":{\"filter\":{\"range\":{\"@timestamp\":{\"format\":\"epoch_millis\",\"gte\":\"now-15m\",\"lte\":\"now\"}}},\"must\":[{\"term\":{\"program\":\"lhi_keepalive\"}},{\"term\":{\"collector.raw\":\"host-10-67-114-9.net-10-67-0-0.tt3.com\"}}]}}}"
    res = self.es.search(index=index, body=json.loads(query))
    data['count'] = res["hits"]["total"]

    return data or None
```

**Comment by ilyam8** [comment] 2020-03-24 17:38
> from elasticsearch import Elasticsearch


There is `elasticsearch` moudle which was imported before your script (alphabetical order).

**Comment by ilyam8** [comment] 2020-03-24 17:44
See

> ./python.d.plugin elasticsearch logcollector_keepalive_message_count

**Comment by ilyam8** [comment] 2020-03-24 17:47
@marcomusso 

try this fix

https://github.com/netdata/netdata/blob/bb9a7692e35f4317aa73a7c1cd748f4899712ec2/collectors/python.d.plugin/python.d.plugin.in#L174-L176

=>

```python
 def load_module(name): 
     abs_path = os.path.join(DIRS.modules, '{0}{1}'.format(name, MODULE_SUFFIX)) 
     module = SourceFileLoader("pythond_" + name, abs_path) 
```

**Comment by marcomusso** [comment] 2020-03-25 08:58
Fixed in `/usr/libexec/netdata/plugins.d/python.d.plugin` (rpm...). It works, thanks!

**Comment by ilyam8** [comment] 2020-03-25 09:05
This issue will be automatically closed when #8474 is merged.

@marcomusso you applied changes from https://github.com/netdata/netdata/issues/8471#issuecomment-603403357, right?

**Comment by marcomusso** [comment] 2020-03-25 09:31
Yes indeed, sorry fo closing it prematurely, now I see your workflow and it’s ok to keep it open.

**Comment by ilyam8** [comment] 2020-03-25 09:41
> Fixed in /usr/libexec/netdata/plugins.d/python.d.plugin (rpm...). It works, thanks!


Keep in mind that your changes will be overwritten on the next update. I'll try to get #8474 merged today.

**Comment by marcomusso** [comment] 2020-03-25 09:42
Sure, thanks. I can bake that fix in our puppet code until then.

**Closed** 2020-03-25 12:29 UTC
Labels: area/external/python, bug
