### ISSUE TITLE
Defunct timeout processes from charts.d plugin in Docker

### ISSUE THREAD

**Issue by utdrmac** [netdata/netdata#6033] opened 2019-05-16 15:44 UTC
##### Bug report summary
Unable to take actions on system due to inability to fork new processes due to netdata creation of `timeout` defunct processes

##### OS / Environment
Docker, 1.18
Ubuntu 18.04

##### Netdata version (ouput of `netdata -V`)
```
# netdata -V
netdata v1.14.0-11-ge91b9ca
```

##### Component Name
netdata core / charts.d / nut plugin?

##### Steps To Reproduce
Run netdata in docker.
Disable 'apps' plugin.
Enable charts.d plugin for nut, configure nut plugin

```
# cat netdata.conf
[plugins]
  apps = no
```

##### Expected behavior
For netdata to not exhaust kernel of process slots

```
-- The initial discovery of a problem on the system
# docker start grafana
runtime/cgo: pthread_create failed: No space left on device
runtime/cgo: pthread_create failed: No space left on device
SIGABRT: abort
PC=0x7f6c7d022e97 m=3 sigcode=18446744073709551610
...

-- Plus received this alarm from another cron job running
/bin/sh: 1: Cannot fork

-- No space? That's odd.
# df -h /
Filesystem                         Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu--vg-ubuntu--lv  5.9G  3.7G  2.0G  66% /

-- No, not a space issue.
-- What is currently running?
# ps -Af
...
201        300 30437  0 00:11 ?        00:00:00 [timeout] <defunct>
201        301 30437  0 May15 ?        00:00:00 [timeout] <defunct>
201        302 30437  0 02:28 ?        00:00:00 [timeout] <defunct>
201        303 30437  0 08:26 ?        00:00:00 [timeout] <defunct>
201        304 30437  0 04:26 ?        00:00:00 [timeout] <defunct>
201        305 30437  0 12:39 ?        00:00:00 [timeout] <defunct>
...(repeated thousands of times)

-- WTH is that?
# ps -Af | grep 30437
201      30437 30412  1 May15 ?        00:14:16 /usr/sbin/netdata -u netdata -D -s /host -p 19999

-- What? Why is netdata spawning so many timeouts and why are they defuncting?

# ps -Af | grep timeout | wc -l
32127

-- Woah! netdata has spawned 32,000 timeouts! Kill it!

# kill -9 30437
# ps -Af | grep timeout
root      2497   817  0 15:27 pts/0    00:00:00 grep timeout

-- Phew! back to normal
```

**Comment by cakrit** [comment] 2019-05-16 16:46
Can you [run the plugin in debug mode] and show us what you get?
I'd also like to see the configuration in `charts.d/nut.conf`.
I don't have a UPS to test, but I'm sure we'll figure it out...

**Comment by utdrmac** [comment] 2019-05-16 17:24
I ran the debug mode at 5s intervals for 20s. Additionally, the plugin itself was still running in the background when I launched the docker container.

[Log at 2019-05-16 12-20-52 PM.txt](https://github.com/netdata/netdata/files/3188244/Log.at.2019-05-16.12-20-52.PM.txt)

In that short amount of time (perhaps 2-3 minutes total) of my debug and normal run, things started looking bad:

```
# ps -Af | grep timeout | wc -l
48
```

Config:
```
# cat /etc/netdata/charts.d/nut.conf
nut_ups="tripplite@10.10.10.203"
nut_timeout=4
```

**Comment by cakrit** [comment] 2019-05-16 19:41
I don't get what could be happening here, there are some very simple calls in this plugin. It could be related to #5938 so I'm asking @paulkatsoulakis to take a look as well, but I really don't see how you can end up with defunct timeout processes, especially when you actually get data back.

Can you try the following? Do two scripts as shown below and call the test. It should end in 2 sec.

```
chris@chris-ubuntu-18:~$ cat test.sh 
#!/bin/bash

require_cmd() {
	local x=$(which "${1}" 2>/dev/null || command -v "${1}" 2>/dev/null)
	if [ -z "${x}" -o ! -x "${x}" ]; then
		warning "command '${1}' is not found in ${PATH}."
		eval "${1^^}_CMD=\"\""
		return 1
	fi

	eval "${1^^}_CMD=\"${x}\""
	return 0
}

echo "checking for timeout command"
require_cmd timeout || exit 1
echo "command found, testing timeout command"
timeout 2 ./neverend.sh
echo "test successful"

chris@chris-ubuntu-18:~$ cat neverend.sh 
#!/bin/bash

while [ 1 ]; do 
 sleep 1
done
chris@chris-ubuntu-18:~$ ./test.sh 
checking for timeout command
command found, testing timeout command
test successful
```

If that works, without leaving a defunct timeout, try also instead of `timeout 2 ./neverend.sh` putting `timeout 2 ipsc -l` to see if we get anything different. 

Just shots in the dark here, I can't explain this yet...

**Comment by utdrmac** [comment] 2019-05-16 20:02
Thanks for the help. I started the docker instance again, and bash'd into it. Created the scripts and ran `./test.sh` 3 times. Had to modify the script slightly as `timeout` requires a `-t` flag for the time period. All 3 tests exited successfully, as so:

```
bash-4.4# timeout --help
BusyBox v1.29.3 (2019-04-25 10:39:48 UTC) multi-call binary.

Usage: timeout [-t SECS] [-s SIG] PROG ARGS

Runs PROG. Sends SIG to it if it is not gone in SECS seconds.
Defaults: SECS: 10, SIG: TERM.

bash-4.4# ./test.sh
checking for timeout command
command found, testing timeout command
./test.sh: line 18:   967 Terminated              timeout -t 2 ./neverend.sh
test successful
```

But when I checked the processlist (inside docker container still), I see this:

```
bash-4.4# whoami
root
bash-4.4# ps -Af | grep root
   22 root      0:00 /bin/bash
  640 root      0:00 [timeout]
  726 root      0:00 [timeout]
  728 root      0:00 [sleep]
  969 root      0:00 [timeout]
  976 root      0:00 [sleep]
 1029 root      0:00 [timeout]
 1037 root      0:00 [sleep]
 1044 root      0:00 ps -Af
 1045 root      0:00 grep root
```

**Comment by utdrmac** [comment] 2019-05-16 20:05
If there's no immediate solution, my plan is to rewrite this plugin using either the python.plugin or the go.plugin (is there a preference here?)

**Comment by cakrit** [comment] 2019-05-17 08:36
Wow. Ok, first of all, we have an issue, because our condition on whether to use `timeout -t X` or `timeout X` seems to be wrong. @paulkatsoulakis will need to resolve this and it looks like we'll have to be doing a "timeout --help" to be sure. In my Ubuntu VM, I have the other version. However, this is busybox. 

Regarding rewriting the plugin, it would be great. But we still need to figure out what's happening here. 
The following comment seems to be hitting the nail on the head:
https://github.com/vishnubob/wait-for-it/issues/5#issuecomment-208403750

I went to our k8s cluster to see what happens with a simple timeout request from the command line and saw the exact same thing as you. I tried using `-s9` as an option based on something I read, but it doesn't do anything, we still get a zombie. Unless @Ferroin or @ktsaou have another suggestion, it looks like we shouldn't be using timeout at all in these systems. The problem is that I haven't seen an alternative anywhere. 

This is very serious and I'd like to have a fix today, in time for 1.15.0 which due to be released, so all assistance is welcome.

**Comment by utdrmac** [comment] 2019-05-17 22:04
@cakrit The timeout -t flag was fixed in #5938 
As I side note, I spent about 2-3hrs and rewrote this as a python.d module. No more timeout.

**Comment by cakrit** [comment] 2019-05-18 14:08
Yes, I know about #5938, but now it looks like we shouldn't be calling timeout in docker at all. 
It's great that you did the python module so fast! Would you care to do a PR about it?
I'm relabelling this issue so we can figure out how to resolve the generic issue of the timeout call for charts.d in docker.

**Comment by paulkatsoulakis** [comment] 2019-05-19 07:11
This looks interesting, sorry for jumping in too late.
I am investigating and will include it on 1.15

**Comment by ntimo** [comment] 2019-09-11 18:49
Do you have any news for a fix for this?

**Comment by utdrmac** [comment] 2019-09-12 00:16
@ntimo Check out my new script for nut/UPS #6827

**Comment by stevenh** [comment] 2019-10-10 22:31
I just pushed a fix for the underling problem behind this issue, which was the fact the netdata didn't have a process reaper, see above.

This is only an issue when netdata is run in a container where it must perform the task of the unix `init` process and reap any child processes that have been re-parented to it.

**Closed** 2019-10-17 13:35 UTC
Labels: area/external, bug
