### ISSUE TITLE
Closed the socket when exporting data

### ISSUE THREAD

**Issue by oleotiger** [netdata/netdata#10595] opened 2021-02-04 12:04 UTC
I have 8 nodes exporting metrics to timescaledb.

Here I start 8 proscale instances ( for distributed deploy) to listen to 8 ports, one port for each node. （If you have better method to allow lots of nodes to exporting metrics though promscale to timescaledb, please tell me. I don't know if it's better than streaming all metrics to one parent node and exporting to database by the parent node.）

In each node, netdata collects all metrics at 1s interval and exports them with one promscale instance. ( No metrics filter is set).

In `var/log/netdata/error.log`, I can see errors:
```
2021-02-04 19:51:24: netdata INFO  : EXPORTING : (0172@libnetdata:thread_start   ): thread created with task id 51729
2021-02-04 19:51:24: netdata INFO  : EXPORTING : (0135@libnetdata:thread_set_name): set name of thread 51729 to EXPORTING
2021-02-04 19:51:24: netdata INFO  : EXPORTING : (0280@exporting/:read_exporting_): Processing connector instance (promscale)
2021-02-04 19:51:24: netdata INFO  : EXPORTING : (0285@exporting/:read_exporting_): Instance (promscale) on connector (prometheus_remote_write) is enabled and scheduled for activation
2021-02-04 19:51:24: netdata INFO  : EXPORTING : (0317@exporting/:read_exporting_): Instance promscale on prometheus_remote_write
2021-02-04 19:51:24: netdata INFO  : EXPORTING : (0024@exporting/:rrdhost_is_expo): enabled exporting of host 'localhost' for instance 'promscale'
2021-02-04 19:52:19: netdata ERROR : MAIN : (0124@exporting/:simple_connecto): EXPORTING: '150.1.66.109:10121' closed the socket
2021-02-04 19:52:33: netdata ERROR : MAIN : (0124@exporting/:simple_connecto): EXPORTING: '150.1.66.109:10121' closed the socket
2021-02-04 19:52:47: netdata ERROR : MAIN : (0124@exporting/:simple_connecto): EXPORTING: '150.1.66.109:10121' closed the socket
2021-02-04 19:53:01: netdata ERROR : MAIN : (0124@exporting/:simple_connecto): EXPORTING: '150.1.66.109:10121' closed the socket
```

On all 8 nodes I get the error messages as shown above.

I didn't get error message of promscale or postgresql.

What I have tried:

I set debug flags to 0xfffffffffffffff but I didn't get more detailed information that why `closed the socket`

**Comment by vlvkobal** [comment] 2021-02-05 08:47
I ran Promscale
```
docker network create --driver bridge promscale-timescaledb
docker run --name timescaledb -e POSTGRES_PASSWORD=12345678 -d -p 5432:5432 --network promscale-timescaledb timescaledev/promscale-extension:latest-pg12 postgres -csynchronous_commit=off
docker run --name promscale -d -p 9201:9201 --network promscale-timescaledb timescale/promscale -db-password=12345678 -db-port=5432 -db-name=postgres -db-host=timescaledb -db-ssl-mode=allow
```
Configured the exporting engine
```
[prometheus_remote_write:my_prometheus_remote_write_instance]
    enabled = yes
    destination = localhost:9201
    remote write URL path = /write
    data source = raw
    update every = 3
    send charts matching = system.processes
```
There are a few errors `closed the socket` in Netdata's `error.log` but exporting is working.
```
curl http://localhos:9201/api/v1/query?query=%22system.processess%22
{"status":"success","data":{"resultType":"string","result":[1612514445.15,"system.processess"]}}
```
![image](https://user-images.githubusercontent.com/22008543/107010741-6b254e00-679f-11eb-82aa-39ee562ae61d.png)

It looks like Promscale sends empty responses and the exporting engine reconnects from time to time.

**Comment by oleotiger** [comment] 2021-02-07 01:37
It't the same for me. Exporting did work.

But error messages are abnornal.

So should I post this issue for promscale in  github?

**Comment by vlvkobal** [comment] 2021-02-08 16:54
From the `RETURN VALUE` section in the `recv(2)` man: 
> When a stream socket peer has performed an orderly shutdown, the return value will be 0 (the traditional "end-of-file" return).

That's why we are checking for zero value and reconnect. I think the problem is that the same zero value is used in other cases as well:

> Datagram sockets in various domains (e.g., the UNIX and Internet domains) permit zero-length datagrams. When such a datagram is received, the return value is 0.

> The value 0 may also be returned if the requested number of bytes to receive from a stream socket was 0.

I'm not sure if we or the Promscale team can do anything with this. Maybe we shouldn't log [these messages](https://github.com/netdata/netdata/blob/master/exporting/send_data.c#L124) as errors? Is it enough to write them only when debug is enabled? @thiagoftsm, what do you think?

**Comment by vlvkobal** [comment] 2021-09-08 10:08
I think the messages are correct and we shouldn't make any changes to Netdata, so I'm closing the issue.

**Closed by vlvkobal** 2021-09-08 10:08 UTC
Labels: bug, needs triage
