### ISSUE TITLE
netdata fail to resolve in kubernetes

### ISSUE THREAD

**Issue by MansM** [netdata/netdata#8060] opened 2020-02-12 08:47 UTC
Running on kubernetes 1.17
netdata slaves fail to resolve svc name.
all other pods have zero issues resolving netdata, except for the netdata pods (unless it on the host where netdata master runs). 

when I run a pod on the same host as the non working slave they do resolv. I can only reproduce it using the netdata  pods installed with the helm chart
```
kubectl run -n netdata -i --tty test --image=alpine:3.9 --restart=Never -- nslookup netdata.netdata.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      netdata.netdata.svc.cluster.local
Address 1: 10.105.2.192 netdata.netdata.svc.cluster.local
HypriotOS/armv7: root@masterpi in ~
# kubectl get pods -o wide -n netdata
NAME                  READY   STATUS      RESTARTS   AGE   IP            NODE                  NOMINATED NODE   READINESS GATES
netdata-master-0      1/1     Running     0          16h   10.244.2.20   r710bot               <none>           <none>
netdata-slave-2p9jp   1/1     Running     0          16h   10.0.2.23     r710bot               <none>           <none>
netdata-slave-dgps9   1/1     Running     0          16h   10.0.2.20     masterpi              <none>           <none>
netdata-slave-tcrzr   1/1     Running     1          57m   10.0.2.24     r710top.localdomain   <none>           <none>
test                  0/1     Completed   0          13s   10.244.1.31   r710top.localdomain   <none>           <none>
HypriotOS/armv7: root@masterpi in ~
# kubectl exec -it netdata-slave-dgps9 -n netdata nslookup netdata.netdata.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

^Ccommand terminated with exit code 130
HypriotOS/armv7: root@masterpi in ~
# kubectl exec -it netdata-slave-tcrzr  -n netdata nslookup netdata.netdata.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'netdata.netdata.svc.cluster.local': Try again
command terminated with exit code 1
```

##### OS / Environment

```

```

##### Steps To Reproduce

1. ...
2. ...

**Comment by vlvkobal** [comment] 2020-02-12 09:07
Is it a duplicate of #3369, #8044?

**Comment by MansM** [comment] 2020-02-12 09:15
nope, not related

**Comment by vlvkobal** [comment] 2020-02-12 09:35
Ah, I see. It's not about container names in Netdata but about domain names. But then, how it is connected to the Netdata itself?

**Comment by MansM** [comment] 2020-02-12 14:40
As any other pod can resolve the name, I am curious why netdata cant..

**Comment by MansM** [comment] 2020-02-12 15:19
might not be related to netdata,
reading and commenting in: https://github.com/kubernetes/kubernetes/issues/87852

**Comment by MansM** [comment] 2020-02-15 12:35
/close

Did find a workaround: switching flannel to host-gw instead of vxlan:
https://github.com/coreos/flannel/issues/1245#issuecomment-582612891
```
kubectl edit cm -n kube-system kube-flannel-cfg
```
- replace vxlan with host-gw
- save 
- not sure if needed, but I did it anyway: ```kubectl delete pods -l app=flannel -n kube-system```

**Closed** 2020-02-15 12:36 UTC
Labels: bug, needs triage
