### ISSUE TITLE
Changes since release v1.10 (changelog of v1.11)

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#3583] opened 2018-03-27 21:33 UTC
Just release v1.10 - eventually, this ticket will get lot's of great things...

**Comment by ktsaou** [comment] 2018-04-01 21:36
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/DqAtO2dL/1-test)

**Comment by paulfantom** [comment] 2018-09-22 23:30
Duplicate of #4081

**Closed by paulfantom** 2018-09-22 23:30 UTC
Labels: discussion, duplicate
