### ISSUE TITLE
netdata/packaging/installer: Compilation warnings

### ISSUE THREAD

**Issue by paulkatsoulakis** [netdata/netdata#5738] opened 2019-03-29 10:44 UTC
##### Bug report summary
Seems that i am getting some compilation warnings when running build on my MacOS
For the installation of dependencies and install process i followed the website instructions for Mac.

Here's the warnings:
```
....
CC       database/rrdvar.o
 CC       streaming/rrdpush.o
database/rrdset.c:1246:168: warning: format specifies type ‘long’ but the argument has type ‘__darwin_suseconds_t’ (aka ‘int’) [-Wformat]
 CC       collectors/statsd.plugin/statsd.o
       info(“%s: too old data (last updated at %ld.%ld, last collected at %ld.%ld). Resetting it. Will not store the next entry.“, st->name, st->last_updated.tv_sec, st->last_updated.tv_usec, st->last_c...
                                                   ~~~                                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~
                                                   %d
database/../daemon/../libnetdata/log/log.h:83:71: note: expanded from macro ‘info’
#define info(args...)    info_int(__FILE__, __FUNCTION__, __LINE__, ##args)
                                                                     ^~~~
database/rrdset.c:1246:226: warning: format specifies type ‘long’ but the argument has type ‘__darwin_suseconds_t’ (aka ‘int’) [-Wformat]
 ...at %ld.%ld). Resetting it. Will not store the next entry.“, st->name, st->last_updated.tv_sec, st->last_updated.tv_usec, st->last_collected_time.tv_sec, st->last_collected_time.tv_usec);
           ~~~                                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           %d
database/../daemon/../libnetdata/log/log.h:83:71: note: expanded from macro ‘info’
#define info(args...)    info_int(__FILE__, __FUNCTION__, __LINE__, ##args)
                                                                     ^~~~
 CC       web/server/web_client.o
 CC       web/server/web_server.o
 CC       web/server/web_client_cache.o
 CC       web/server/static/static-threaded.o
 CC       collectors/macos.plugin/plugin_macos.o
 CC       collectors/macos.plugin/macos_sysctl.o
2 warnings generated.
 CC       collectors/macos.plugin/macos_mach_smi.o
 CC       collectors/macos.plugin/macos_fw.o
 CCLD     cups.plugin
collectors/macos.plugin/macos_fw.c:118:35: warning: address of array ‘diskstat.name’ will always evaluate to ‘true’ [-Wpointer-bool-conversion]
           if(unlikely(!diskstat.name || !*diskstat.name)) {
                       ~~~~~~~~~~^~~~
./config.h:339:41: note: expanded from macro ‘unlikely’
#define unlikely(x) __builtin_expect(!!(x), 0)
                                       ^
1 warning generated.
 CCLD     netdata
....
```

```
....
CC       daemon/unit_test.o
 CC       web/api/badges/web_buffer_svg.o
daemon/daemon.c:63:40: warning: passing ‘gid_t *’ (aka ‘unsigned int* ’) to parameter of type ‘int *’ converts between pointers to integer types with different sign [-Wpointer-sign]
       if(getgrouplist(username, gid, supplementary_groups, &ngroups) == -1) {
                                      ^~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/unistd.h:653:43: note: passing argument to parameter here
int      getgrouplist(const char *, int, int* , int *);
                                             ^
 CC       web/api/exporters/allmetrics.o
1 warning generated.
 CC       web/api/exporters/shell/allmetrics_shell.o
daemon/global_statistics.c:159:68: warning: passing ‘volatile uint64_t *’ (aka ‘volatile unsigned long long* ’) to parameter of type ‘uint64_t *’ (aka ‘unsigned long long* ’) discards qualifiers
     [-Wincompatible-pointer-types-discards-qualifiers]
       __atomic_compare_exchange(&global_statistics.web_usec_max, &gs->web_usec_max, &n, 1, __ATOMIC_SEQ_CST,
                                                                  ^~~~~~~~~~~~~~~~~
1 warning generated.
 CC       web/api/queries/average/average.o
 CC       web/api/queries/des/des.o
.......
```

##### OS / Environment

```macOS Mojave - 10.14.3```

```
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

##### Netdata version (ouput of `netdata -V`)
Latest 

##### Component Name
netdata/packaging/installer

##### Steps To Reproduce
Just run the installation process for Mac from the website, on a Mac

##### Expected behavior
We have zero tolerance in warnings in our code.

**Comment by prologic** [comment] 2020-03-04 23:14
As discussed internally we cannot repro this:

```sh
$ brew sh
$ autoreconf -ifv
$ ./configure --prefix=/usr
$ make -j 12
.
.
.
  CC       exporting/json/json.o
  CC       exporting/opentsdb/opentsdb.o
  CC       cli/cli.o
  CCLD     cups.plugin
  GEN      netdatacli
  GEN      netdata
brew ~/NetData/netdata$
```

Closing as "cannot reproduce". Please open a new issue if this is still an issue or comment here.

**Closed by prologic** 2020-03-04 23:14 UTC
Labels: area/packaging, bug, priority/low
