### ISSUE TITLE
dockerhub tag v1.18.0 is unavilable in amd64 machine

### ISSUE THREAD

**Issue by weijing24** [netdata/netdata#7084] opened 2019-10-14 09:10 UTC
##### Question summary
When I upgraded to netdata v1.18.0，I failed and this is the error infomation.
```
standard_init_linux.go:211: exec user process caused "exec format error"
```
But when I use the `latest` tag，It gets fine. So I go to docker hub, find that this is no amd64. I think just packge a amd64 docker image will works. Can anybody fix this problem? 
![image](https://user-images.githubusercontent.com/8737314/66740205-250af380-eea5-11e9-89f8-57e3c6ca2f1e.png)

##### OS / Environment
Ubuntu 16.04.4
docker

##### Component Name
dockerhub tag v1.18.0

##### Expected results
netdata/netdata:v1.18.0 can be used in amd64 machine

**Comment by knatsakis** [comment] 2019-10-14 18:19
Hi @weijing24,
Thank you very much for your report.

I believe this is a duplicate of #7063, so lets follow the progress there.

**Comment by knatsakis** [comment] 2019-10-14 18:19
Closing as duplicate of #7063

**Closed by knatsakis** 2019-10-14 18:19 UTC
Labels: area/packaging, no changelog, question
