### ISSUE TITLE
pgsql module failed checks

### ISSUE THREAD

**Issue by alsoGAMER** [netdata/netdata#5625] opened 2019-03-13 16:35 UTC
##### Bug report summary
Pgsql module failed checks so netdata skip it
##### OS / Environment
Debian 9.8 | Pgsql 9.6
##### Netdata version (ouput of `netdata -V`)
1.12.2-34-nightly
##### Component Name
pgsql module
##### Steps To Reproduce
I don't know, it stopped working totally random
##### Netdata log & config file
https://hastebin.com/cihokifuba.pl
https://hastebin.com/rucixuhaco.shell

**Comment by ilyam8** [comment] 2019-03-13 17:03
@alsoGAMER 	

fixes in latest

duplicate of https://github.com/netdata/netdata/issues/5615

**Closed by ilyam8** 2019-03-13 17:03 UTC
