### ISSUE TITLE
apcupsd chart not updating when on battery

### ISSUE THREAD

**Issue by modem7** [netdata/netdata#5428] opened 2019-02-19 17:06 UTC
UPS: SMT1500I connected via USB
OS: Fedora

Current issue: When the UPS goes onto battery, the netdata plugin seems to not gather any further data until the UPS comes back onto power. 

apcaccess status shows the correct values however, so the UPS is certainly communicating correctly with the server. 

![capture1](https://user-images.githubusercontent.com/4349962/53033276-a0c4b580-3468-11e9-875c-f27d03befe33.JPG)
![capture2](https://user-images.githubusercontent.com/4349962/53033567-3f511680-3469-11e9-938a-3e49812ecbf3.JPG)
![capture3](https://user-images.githubusercontent.com/4349962/53033279-a15d4c00-3468-11e9-9d95-923bbbea7859.JPG)

**Comment by cakrit** [comment] 2019-02-19 23:52
This was caused by PR #5037 which resolved issue #3927. 
Please test PR #5435, which should be treating the `ONBATT` status as `ONLINE`. If it works for you, we'll merge it.

**Comment by cakrit** [comment] 2019-02-20 17:52
@modem7 can you please test the fix? Let me know if you need help.

**Comment by modem7** [comment] 2019-02-20 18:21
I'm getting the following once applying the charts.d fix:
```

[alex@localhost ~]$ apcaccess status
APC      : 001,028,0736
DATE     : 2019-02-20 18:19:59 +0000
HOSTNAME : localhost.localdomain
VERSION  : 3.14.14 (31 May 2016) redhat
UPSNAME  : HDAUPS
CABLE    : USB Cable
DRIVER   : USB UPS Driver
UPSMODE  : Stand Alone
STARTTIME: 2019-02-11 13:13:11 +0000
MODEL    : Smart-UPS 1500
STATUS   : ONBATT
BCHARGE  : 88.0 Percent
TIMELEFT : 71.0 Minutes
MBATTCHG : 5 Percent
MINTIMEL : 3 Minutes
MAXTIME  : 0 Seconds
ALARMDEL : 30 Seconds
BATTV    : 25.1 Volts
NUMXFERS : 3
XONBATT  : 2019-02-20 18:18:30 +0000
TONBATT  : 92 Seconds
CUMONBATT: 4192 Seconds
XOFFBATT : 2019-02-19 17:55:09 +0000
STATFLAG : 0x05060010
MANDATE  : 2011-05-08
SERIALNO : AS1119123502
NOMBATTV : 24.0 Volts
FIRMWARE : UPS 07.1 / ID=17
END APC  : 2019-02-20 18:20:02 +0000
```

![capture](https://user-images.githubusercontent.com/4349962/53114721-57de3100-353c-11e9-9674-fe3023c4899e.JPG)

So the issue still seems present. Note that I'm not using modbus in this case.

**Comment by cakrit** [comment] 2019-02-20 18:52
I don't know what modbus is, but it can't be the same code AND using the same output. I ran the `awk` in the script against your exact output and it's showing the charge and the time.

Can you please run the plugin by hand in debug mode? 
```
sudo su -s /bin/sh netdata
/usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 apcupsd
```

Also, please verify that the fix is indeed where it's supposed to be, with a `grep NOBATT /usr/libexec/netdata/charts.d/apcupsd.chart.sh`. It should return a couple of lines.

**Comment by modem7** [comment] 2019-02-20 19:03
Odd, I'm not getting any onbatt results from grep. 

Using https://raw.githubusercontent.com/EnzoAkira/netdata/bbbcdedd312a670c6c0f89061edc46f2f249143b/collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh to update

**Comment by cakrit** [comment] 2019-02-20 19:07
Not sure what that is, please use https://raw.githubusercontent.com/netdata/netdata/cb362dd418ce85051dde399db02ee5aa4a9a8b16/collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh

It's the one from PR #5435 (shown on the right side of the files section, when you view the file in raw format).

**Comment by modem7** [comment] 2019-02-20 19:08
Ah, testing now

**Comment by modem7** [comment] 2019-02-20 19:13
Looks like that's done it!

It's the same as apcaccess -status and getting the relevant results. 

Thanks!

**Comment by cakrit** [comment] 2019-02-20 19:14
Excellent, merging the fix. Thanks for the test.

**Closed** 2019-02-20 19:15 UTC
Labels: area/external, bug

**Comment by putnam** [comment] 2020-02-22 10:24
It would be good to add "CAL ONBATT" as well, which is what the status switches to during battery calibration. Otherwise the same situation arises without any metrics during this time. A typical installation should do a battery calibration about once every 6 months to correct the "runtime remaining" factor as batteries decay.

**Comment by cakrit** [comment] 2020-02-24 20:43
> It would be good to add "CAL ONBATT" as well, which is what the status switches to during battery calibration. Otherwise the same situation arises without any metrics during this time. A typical installation should do a battery calibration about once every 6 months to correct the "runtime remaining" factor as batteries decay.

Nice suggestion. Care to do a PR? Very straightforward logic in the code!

**Comment by Mic-Pod** [comment] 2020-04-12 15:45
Hi,
I think that status "TRIM ONLINE" should also be added. Currently I have the situation when UPS is reporting status TRIM ONLINE but everything works great. Sadly this status is causing metrics not being collected.

# apcaccess status | grep -i status
STATUS   : TRIM ONLINE

# /usr/libexec/netdata/plugins.d/charts.d.plugin debug 1 apcupsd
charts.d: DEBUG: apcupsd: loading module: '/usr/libexec/netdata/plugins.d/../charts.d/apcupsd.chart.sh'
charts.d: DEBUG: apcupsd: loading module configuration: '/usr/lib/netdata/conf.d/charts.d/apcupsd.conf'
charts.d: DEBUG: apcupsd: loading module configuration: '/etc/netdata/charts.d/apcupsd.conf'
charts.d: ERROR: apcupsd: APC UPS local on 127.0.0.1:3551 is not online.
charts.d: ERROR: apcupsd: No APC UPSes found available.
charts.d: ERROR: apcupsd: module's 'apcupsd' check() function reports failure.

**Comment by ilyam8** [comment] 2020-04-12 16:02
Well, i see code expected only `ONLINE` and `ONBATT` statuses

https://github.com/netdata/netdata/blob/231d19351d0ea20aa66fd204215cbb24f34d7575/collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh#L50-L53

And it expected it to be one word.

`apcaccess` command tools docs: [link](https://www.systutorials.com/docs/linux/man/8-apcaccess/).

```
STATUS
: UPS status. One or more of the following (space-separated): CAL TRIM BOOST ONLINE ONBATT OVERLOAD LOWBATT REPLACEBATT NOBATT SLAVE SLAVEDOWN
or
COMMLOST
or
SHUTTING DOWN
```

**Comment by ilyam8** [comment] 2020-04-12 16:10
i tried to google what is `TRIM ONLINE` and found 

> https://sourceforge.net/p/apcupsd/mailman/message/23756977/

However i still dont understand what it means 😄

Since it is

> One or more of the following

it looks like we need to take everything into accout after `STATUS : `. However i assume it was written in such way for a reason (use only first word) 🤔 

Simpe thing is just to add `TRIM ONLINE` and that is it.
