### ISSUE TITLE
netdata dashboard Bug

### ISSUE THREAD

**Issue by zhangsimingshannonai** [netdata/netdata#5985] opened 2019-05-10 07:09 UTC
Hi,I'm using netdata on Ubuntu 16.04 LTS, I found something oddity on the netdata dashboard.
when I run a netdata local , I browse the dashborad through "https://localhost:19999",then I touch 'settings' to get netdata dashboard options,it's OK. 
But I can't click 'close' to get back .Is this a Bug??
Further more , on the netdata.cloud such as "http://newyork.my-netdata.io" ,click "close" can get back to the dashboard. The bug only occored by local access.
waiting for your reply,thanks a lot~

**Comment by vlvkobal** [comment] 2019-05-10 08:29
Have you tried to do a **hard reload** of your local dashboard in your browser?

**Comment by zhangsimingshannonai** [comment] 2019-05-11 07:21
> Have you tried to do a **hard reload** of your local dashboard in your browser?

Maybe netdata must use Public IP to access,I launch netdata on a Public-IP-binding server everything seem to be OK. The problem occured on the server which only have Private IP.
Thanks for your answer.

**Comment by cakrit** [comment] 2019-05-11 10:10
I can tell you that for the issue is to be related to whether an IP is public or private, it can't be netdata that's causing it. In any case, closing it since you're able to move forward.

**Closed by cakrit** 2019-05-11 10:10 UTC
Labels: area/web, no changelog, question
