### ISSUE TITLE
Uninstall does not remove cron.daily entry for update

### ISSUE THREAD

**Issue by markusdd** [netdata/netdata#8165] opened 2020-02-23 10:16 UTC
##### Bug report summary
Upon uninstall in one of my LXC containers I received a cron error mail next night because netdata updater tried to run although it was uninstalled. Root cause is a dead symlink in /etc/cron.daily to the updater

##### OS / Environment
```
turnkey core (so essentially Debian Stretch)

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


```

##### Netdata version
latest greatest
 

##### Component Name
uninstall script

##### Steps To Reproduce
1. Install netdata with daily updates
2. uninstall
3. check dron directories for remains
##### Expected behavior
remove cron entry together with netdata

**Comment by prologic** [comment] 2020-02-23 23:37
I am unable to reproduce this on a Debian 9 chroot/container.

@markusdd Are you able to tell me a little more about your system so I can help root cause this? The entire output logs of running the `/usr/libexec/netdata/netdata-uninstaller.sh` would be useful here (_that's the default path_).

**Comment by cosmix** [comment] 2020-03-04 20:36
We haven't received an answer to this issue @markusdd -- we're closing, if you feel this is in error, please re-open.

**Closed by cosmix** 2020-03-04 20:36 UTC
Labels: Cannot reproduce, area/packaging, bug, needs triage
