### ISSUE TITLE
Debian/Ubuntu package depends on Cups

### ISSUE THREAD

**Issue by roedie** [netdata/netdata#6844] opened 2019-09-13 17:43 UTC
##### Bug report summary
When installing Netdata Debian package from Packagecloud the whole Cups suite is installed as well. This triggers all kinds of dependencies being installed which probably are not needed on most servers.

##### OS / Environment
Debian/Ubuntu

##### Netdata version (ouput of `netdata -V`)
Tested with the 1.17.1 package

##### Steps To Reproduce
root@wonko-the-sane:~# apt install netdata
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  avahi-daemon colord colord-data cups cups-browsed cups-client cups-common cups-core-drivers cups-daemon cups-filters
  cups-filters-core-drivers cups-ipp-utils cups-ppdc cups-server-common fonts-droid-fallback fonts-noto-mono freeipmi
  freeipmi-bmc-watchdog freeipmi-common freeipmi-ipmidetect freeipmi-tools ghostscript gsfonts libavahi-core7
  libavahi-glib1 libcolorhug2 libdaemon0 libexif12 libfontembed1 libfreeipmi17 libgd3 libgphoto2-6 libgphoto2-l10n
  libgphoto2-port12 libgs9 libgs9-common libgusb2 libgutenprint-common libgutenprint9 libieee1284-3 libijs-0.35
  libipmiconsole2 libipmidetect0 libipmimonitoring6 libjbig2dec0 libjudydebian1 liblouis-data liblouis17
  liblouisutdml-bin liblouisutdml-data liblouisutdml8 libmariadb3 libnss-mdns libpoppler82 libprotobuf17 libprotoc17
  libqpdf21 libsane libsane-common libsnmp-base libsnmp30 mariadb-common mysql-common poppler-data poppler-utils
  printer-driver-gutenprint sane-utils ssl-cert update-inetd
Suggested packages:
  avahi-autoipd colord-sensor-argyll cups-bsd foomatic-db-compressed-ppds | foomatic-db printer-driver-hpcups hplip
  cups-pdf smbclient antiword docx2txt imagemagick fonts-noto ghostscript-x libgd-tools gphoto2 gutenprint-locales
  ooo2dbk rtf2xml avahi-autoipd | zeroconf snmp-mibs-downloader fonts-japanese-mincho | fonts-ipafont-mincho
  fonts-japanese-gothic | fonts-ipafont-gothic fonts-arphic-ukai fonts-arphic-uming fonts-nanum gutenprint-doc unpaper
  openssl-blacklist
The following NEW packages will be installed:
  avahi-daemon colord colord-data cups cups-browsed cups-client cups-common cups-core-drivers cups-daemon cups-filters
  cups-filters-core-drivers cups-ipp-utils cups-ppdc cups-server-common fonts-droid-fallback fonts-noto-mono freeipmi
  freeipmi-bmc-watchdog freeipmi-common freeipmi-ipmidetect freeipmi-tools ghostscript gsfonts libavahi-core7
  libavahi-glib1 libcolorhug2 libdaemon0 libexif12 libfontembed1 libfreeipmi17 libgd3 libgphoto2-6 libgphoto2-l10n
  libgphoto2-port12 libgs9 libgs9-common libgusb2 libgutenprint-common libgutenprint9 libieee1284-3 libijs-0.35
  libipmiconsole2 libipmidetect0 libipmimonitoring6 libjbig2dec0 libjudydebian1 liblouis-data liblouis17
  liblouisutdml-bin liblouisutdml-data liblouisutdml8 libmariadb3 libnss-mdns libpoppler82 libprotobuf17 libprotoc17
  libqpdf21 libsane libsane-common libsnmp-base libsnmp30 mariadb-common mysql-common netdata poppler-data
  poppler-utils printer-driver-gutenprint sane-utils ssl-cert update-inetd
0 upgraded, 70 newly installed, 0 to remove and 0 not upgraded.
Need to get 40.2 MB/43.7 MB of archives.
After this operation, 173 MB of additional disk space will be used.
Do you want to continue? [Y/n] 

##### Expected behavior
Have Cups as a recommended/suggested package.

I don't mind making a PR for this.

**Comment by cakrit** [comment] 2019-09-13 18:00
Hi @roedie, this is a duplicate of #6662 and we have PRs #6700 and #6724 for it. We'll be merging them soon.

**Closed by cakrit** 2019-09-13 18:00 UTC
Labels: bug, needs triage

**Comment by roedie** [comment] 2019-09-13 18:26
Sorry about that. I did a quick search but didn’t find them.
