### ISSUE TITLE
[Bug]: Alert notifications UNKNOWN → CLEAR

### ISSUE THREAD

**Issue by ralphm** [netdata/netdata#13366] opened 2022-07-11 14:56 UTC
### Bug description

I'm regularly receiving alert notification e-mails that go from `UNKNOWN` to `CLEAR`. In all cases I examined, there are no prior notifications for the same alert, the time from the previous status is usually a few seconds, but no more than a minute.

### Expected behavior

No notifications of this kind should be sent.

### Steps to reproduce

1. Monitor e-mail notifications over time. Our own production space has several every day.

### Screenshots

![image](https://user-images.githubusercontent.com/116741/178293158-5ed73238-0ffc-45a8-8de8-9d085380c533.png)

### Desktop

N/A

### Additional context

[Alert Link](https://app.netdata.cloud/spaces/ik-nu/rooms/all-nodes/nodes/799316dd-6bdc-4cc8-bd2b-dcf0c4f842df#alarm_chart=powersupply_capacity.hid-00:1f:20:a8:2b:75-battery&alarm_id=powersupply_capacity.hid-00:1f:20:a8:2b:75-battery.linux_power_supply_capacity&alarm_name=linux_power_supply_capacity&alarm_status=clear&alarm_value=45%20%25&alarm_when=1657364093&chartName=chart_powersupply_capacity_hid-00_1f_20_a8_2b_75-battery_linux_power_supply_capacity) 

In this particular case, the machine, a laptop, came out of suspension and the Bluetooth mouse reconnected.

**Comment by hugovalente-pm** [comment] 2022-07-12 12:07
@ralphm moving this ticket to Agent repo since these notifications are triggered from the Agent

@MrZammler I know some transation skips were done for states like `REMOVED` and `UNITIALIZED` ([comment](https://github.com/netdata/product/issues/2819#issuecomment-1057260611), probably we also need to skip the `UNKNOWN`. what do you think?

**Comment by ralphm** [comment] 2022-07-12 16:22
@MrZammler The screenshot is of a cloud notification e-mail, that's why I initially filed it against `netdata-cloud`.

@hugovalente-pm: even if alerts state transitions are initiated by the Agent, this doesn't mean there's nothing that can be done on Cloud to address this. Moving the ticket seems premature.

**Comment by MrZammler** [comment] 2022-07-12 16:39
Okay, we can check tomorrow with @car12o. @hugovalente-pm has a point, and we need to check the alert's history to see what could cause it.

In general though, if it wasn't before critical or warning, the agent should not have sent it...

**Comment by MrZammler** [comment] 2022-07-13 07:42
Ralph hi, can we have the node_id for the node of this alert (it should be listed in `access.log` when it reports protobuf messages exchange)? Is the laptop streaming to a parent, or claimed by itself?

I assume the alert relates to the mouse... Was the laptop maybe used for some time without this mouse? Can you also please send me the output of `http://node:19999/api/v1/alarm_log` to manolis at netdata.cloud ?

Thanks!

**Comment by hugovalente-pm** [comment] 2022-07-15 11:12
@car12o you mentioned this on the daily today. the work you did was to avoid triggering these notifications from Cloud?
just to check, since the conversation had evolved to try to not send these transitions from the Agent to Cloud.

**Comment by car12o** [comment] 2022-07-15 11:17
@hugovalente-pm the issue is on the cloud as the verifycation of if we should notify was broken, I will deploy the fix in a couple of mins.
Regarding these transitions from the Agent to Cloud, we need to have them as they are used to trigger some side processes.

**Comment by car12o** [comment] 2022-07-15 11:48
Fix deployed to prod!

**Closed by car12o** 2022-07-15 11:48 UTC
Labels: bug, needs triage, priority/high, alerts-team

**Comment by hugovalente-pm** [comment] 2022-07-15 11:53
understood, will push this back to netdata-cloud repo
you were right @ralphm 🙇‍♂
