### ISSUE TITLE
File not found by glob when building an rpm (latest code - 20181218)

### ISSUE THREAD

**Issue by ElCoyote27** [netdata/netdata#5033] opened 2018-12-18 22:32 UTC
```
RPM build errors:
    Directory not found: [,..]/BUILDROOT/netdata-1.12.1-20181218.el7.x86_64/usr/lib64/netdata/conf.d/node.d

```
Was solved with:

```
$ git diff -c netdata.spec.in
diff --git a/netdata.spec.in b/netdata.spec.in
index b54a91e..952a47f 100644
--- a/netdata.spec.in
+++ b/netdata.spec.in
@@ -225,7 +225,7 @@ rm -rf "${RPM_BUILD_ROOT}"
 %dir %{_libdir}/%{name}/conf.d/health.d
 %dir %{_libdir}/%{name}/conf.d/python.d
 %dir %{_libdir}/%{name}/conf.d/charts.d
-%dir %{_libdir}/%{name}/conf.d/node.d
+#%dir %{_libdir}/%{name}/conf.d/node.d
 %dir %{_libdir}/%{name}/conf.d/statsd.d
```

**Comment by wcallgair** [comment] 2019-01-08 16:06
@paulfantom acknowledge but in another thread. 
 
Related to https://github.com/netdata/netdata/issues/5053

Currently nobody can use the latest version on centos7

**Comment by paulfantom** [comment] 2019-01-08 17:05
There was a PR #4417 which was intended to be a baseline for a new method of building rpms which would be independent from a build system. But it was rejected on a ground that it needed access to git system (needed to get a version number). However since we have #5051 merged, there is a way to do it independently from a git, so I will refresh idea from #4417.

**Comment by paulkatsoulakis** [comment] 2019-05-14 05:58
Hello,
  It seems that we have attended this issue with the following commit

```
commit 203aea6102e03f6e276865904a331bbefca7604f
Author: Costa Tsaousis <costa@tsaousis.gr>
Date:   Tue Oct 16 22:33:30 2018 +0300
```

Building the RPM, seems to be correct as the needed folders/files are in place
```
[builder@builder03 x86_64]$ rpm -pql netdata-v1.14.0-1.el7.x86_64.rpm  | grep node
/etc/netdata/node.d
/usr/lib64/netdata/conf.d/node.d.conf
/usr/libexec/netdata/node.d
/usr/libexec/netdata/node.d/fronius.node.js
/usr/libexec/netdata/node.d/named.node.js
/usr/libexec/netdata/node.d/node_modules
/usr/libexec/netdata/node.d/node_modules/asn1-ber.js
/usr/libexec/netdata/node.d/node_modules/extend.js
/usr/libexec/netdata/node.d/node_modules/lib
/usr/libexec/netdata/node.d/node_modules/lib/ber
/usr/libexec/netdata/node.d/node_modules/lib/ber/errors.js
/usr/libexec/netdata/node.d/node_modules/lib/ber/index.js
/usr/libexec/netdata/node.d/node_modules/lib/ber/reader.js
/usr/libexec/netdata/node.d/node_modules/lib/ber/types.js
/usr/libexec/netdata/node.d/node_modules/lib/ber/writer.js
/usr/libexec/netdata/node.d/node_modules/net-snmp.js
/usr/libexec/netdata/node.d/node_modules/netdata.js
/usr/libexec/netdata/node.d/node_modules/pixl-xml.js
/usr/libexec/netdata/node.d/sma_webbox.node.js
/usr/libexec/netdata/node.d/snmp.node.js
/usr/libexec/netdata/node.d/stiebeleltron.node.js
/usr/libexec/netdata/plugins.d/node.d.plugin
/usr/libexec/netdata/python.d/python_modules/pyyaml2/nodes.py
/usr/libexec/netdata/python.d/python_modules/pyyaml3/nodes.py
[builder@builder03 x86_64]$ 
```

@ElCoyote27 please do not hesitate to report with a new issue if you have any other problems with packaging.
Allow me to remind here that we have issue #5963 on going, so any knowledge you feel is important for us to know, fell free to share it there.  See ya!

**Closed by paulkatsoulakis** 2019-05-14 05:58 UTC
Labels: area/packaging, bug, priority/low
