### ISSUE TITLE
support AWS Timestream as a back-end

### ISSUE THREAD

**Issue by dbethke** [netdata/netdata#5722] opened 2019-03-27 16:29 UTC
##### Feature idea summary
Support AWS Timestream as a back-end TS database

##### Expected behavior
Send metrics to AWS Timestream! 
Read metrics from AWS Timestream?

Amazon Timestream is a fast, scalable, fully managed time series database service for IoT and operational applications that makes it easy to store and analyze trillions of events per day at 1/10th the cost of relational databases.

**Comment by cakrit** [comment] 2019-03-28 12:02
Thanks for the pointer @dbethke. Do you use it in production? Can you help with testing or any questions that may come up?

**Comment by cakrit** [comment] 2019-03-28 13:23
duplicate of #5596. Closing and continuing there.

**Comment by vlvkobal** [comment] 2019-04-09 09:49
AWS Timestream is a time series database and it doesn't use AWS Kinesis API. I'm reopening the issue. Can anybody provide information about AWS Timestream API/Query laguage?

**Comment by arubacao** [comment] 2020-10-06 14:35
They published a documentation including their API/Query language here:
https://docs.aws.amazon.com/timestream/latest/developerguide/reference.html

**Comment by OdysLam** [comment] 2020-10-07 06:46
Hey @arubacao,

Thanks for that piece of information and welcome to our little community :) If you have any questions, please don't hesitate to reach out!

**Comment by vlvkobal** [comment] 2021-01-28 18:01
Closing the issue due to the lack of interest in this feature.

If there is anybody who is interested in having this implemented please visit our Community Forums and create a new topic in the [Netdata Agent Feature Requests](https://community.netdata.cloud/c/feature-requests/agent-fr/21) category.

**Closed by vlvkobal** 2021-01-28 18:01 UTC
Labels: area/exporting, feature request, group/d-c, help wanted
