### ISSUE TITLE
Netdata in master/slave deployment losing metrics after unsolicited restarts across server estate (caused by cron daily)

### ISSUE THREAD

**Issue by AaronRobinson** [netdata/netdata#7303] opened 2019-11-11 11:17 UTC
##### Question summary
Should the daily logrotate restart netdata and lose monitoring data?
##### OS / Environment
Ubuntu 16.04
##### Component Name
Not sure
##### Expected results
That I don't lose the monitoring data every day

Started noticing this a few weeks ago and just getting around to investigating. I retain the last 24 hours of data. Each morning I check the overnight data. Netdata is now only showing data from around 6:30am. I'm pretty sure that this is being caused by log rotate, which in turn is causing a restart of netdata. And as the data is kept in memory, the overnight data is lost.

What I don't understand is why this has only started happening recently. The logrotate config for netdata hasn't changed since June: -
```
/var/log/netdata/*.log {
        daily
        missingok
        rotate 14
        compress
        delaycompress
        notifempty
        sharedscripts
        postrotate
                /bin/kill -HUP `cat /var/run/netdata/netdata.pid 2>/dev/null` 2>/dev/null || true
        endscript
}
```

**Comment by mfundul** [comment] 2019-11-11 11:24
Can you please share parts of your `/var/log/netdata/error.log` during those suspicious time periods?

**Comment by AaronRobinson** [comment] 2019-11-11 11:44
Sure...

from syslog (confirming cron.daily and the netdata restart)
```
Nov 11 06:25:01 monitor CRON[6628]: (root) CMD (test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily ))
Nov 11 06:25:01 monitor CRON[6629]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)Nov 11 06:26:01 monitor systemd[1]: Reloading.
Nov 11 06:26:01 monitor systemd[1]: Starting Daily apt upgrade and clean activities...
Nov 11 06:26:01 monitor systemd[1]: Started ACPI event daemon.
Nov 11 06:26:01 monitor systemd[1]: Reloading.
Nov 11 06:26:01 monitor systemd[1]: Started ACPI event daemon.
Nov 11 06:26:02 monitor systemd[1]: Started Daily apt upgrade and clean activities.
Nov 11 06:26:07 monitor systemd[1]: Starting Real time performance monitoring...
Nov 11 06:26:07 monitor systemd[1]: Started Real time performance monitoring.
```
and from netdata log (what looks relevant)
```
2019-11-11 06:25:03: netdata INFO  : MAIN : SIGNAL: Received SIGUSR1. Saving databases...
2019-11-11 06:25:03: netdata INFO  : MAIN : Saving database [6 hosts(s)]...
2019-11-11 06:25:03: netdata INFO  : MAIN : Saving/Closing database of host 'my-host'...
2019-11-11 06:25:04: netdata INFO  : STREAM_RECEIVER[my-host,[my-ip]:39772] : RRDSET: chart name 'apps.cpu' on host 'test-scrape-db' already exists.
2019-11-11 06:25:04: netdata INFO  : STREAM_RECEIVER[my-host,[my-ip]:39772] : Initializing file /var/cache/netdata/99436878-888d-11e9-9788-f23c91c237e0/apps.cpu/build.db.
2019-11-11 06:25:04: netdata INFO  : STREAM_RECEIVER[my-host,[my-ip]:39772] : RRDSET: chart name 'apps.cpu_user' on host 'test-scrape-db' already exists.
2019-11-11 06:25:04: netdata INFO  : STREAM_RECEIVER[my-host,[my-ip]:39772] : Initializing file /var/cache/netdata/99436878-888d-11e9-9788-f23c91c237e0/apps.cpu_user/build.db.
2019-11-11 06:25:04: netdata INFO  : STREAM_RECEIVER[my-host,[my-ip]:39772] : RRDSET: chart name 'apps.cpu_system' on host 'test-scrape-db' already exists.
...
2019-11-11 06:25:08: netdata INFO  : MAIN : Databases saved.
...
2019-11-11 06:25:57: netdata LOG FLOOD PROTECTION too many logs (201 logs in 49 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 1151 seconds.
2019-11-11 06:26:01: netdata LOG FLOOD PROTECTION reset for process 'netdata' (prevented 228 logs in the last 53 seconds).
2019-11-11 06:26:01: netdata INFO  : MAIN : SIGNAL: Received SIGTERM. Cleaning up to exit...
2019-11-11 06:26:01: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 0...
2019-11-11 06:26:01: netdata INFO  : MAIN : /usr/libexec/netdata/plugins.d/anonymous-statistics.sh 'EXIT' 'OK' '-'
2019-11-11 06:26:01: netdata INFO  : MAIN : EXIT: cleaning up the database...
2019-11-11 06:26:01: netdata INFO  : MAIN : Cleaning up database [6 hosts(s)]...
...
2019-11-11 06:26:01: netdata INFO  : MAIN : Deleting database of host 'my-host'...
2019-11-11 06:26:01: netdata INFO  : MAIN : Deleting chart 'ipv4.sockstat_udp_mem' ('ipv4.sockstat_udp_mem') from disk...
2019-11-11 06:26:01: netdata INFO  : MAIN : Deleting chart header file '/var/cache/netdata/99436878-888d-11e9-9788-f23c91c237e0/ipv4.sockstat_udp_mem/main.db'.
2019-11-11 06:26:01: netdata INFO  : MAIN : Deleting dimension file '/var/cache/netdata/99436878-888d-11e9-9788-f23c91c237e0/ipv4.sockstat_udp_mem/mem.db'.
2019-11-11 06:26:01: netdata INFO  : MAIN : Deleting empty directory '/var/cache/netdata/99436878-888d-11e9-9788-f23c91c237e0/ipv4.sockstat_udp_mem'
2019-11-11 06:26:01: netdata INFO  : MAIN : Deleting chart 'disk_qops.sda' ('disk_qops.sda') from disk...

```

**Comment by mfundul** [comment] 2019-11-11 12:08
From your syslog it looks like [this](https://superuser.com/questions/1327884/how-to-disable-daily-upgrade-and-clean-on-ubuntu-16-04). I don't it is a netdata issue.

**Comment by AaronRobinson** [comment] 2019-11-11 12:18
Many thanks for you prompt replies btw - appreciated.

Why would anything cron daily is triggering prevent netdata reloading the cached metrics after a restart? Isn't that the issue?

**Comment by mfundul** [comment] 2019-11-11 12:27
> 
> 
> Many thanks for you prompt replies btw - appreciated.
> 
> Why would anything cron daily is triggering prevent netdata reloading the cached metrics after a restart? Isn't that the issue?

That depends, if you're only keeping the data in memory as you implied, that is to be expected. That would be the case if you're using `memory mode = ram`. What is your `netdata.conf` and `stream.conf` in `/etc/netdata`?

**Comment by AaronRobinson** [comment] 2019-11-11 12:39
In stream.conf...
`default memory mode = save`
In netdata.conf
`# memory mode = save`

I believe this is the correct setting to save and reinstate the metrics after a restart? And as above, the cache directory has content - this is where the metrics are saved isn't it?

**Comment by mfundul** [comment] 2019-11-11 12:49
> 
> 
> In stream.conf...
> `default memory mode = save`
> In netdata.conf
> `# memory mode = save`
> 
> I believe this is the correct setting to save and reinstate the metrics after a restart? And as above, the cache directory has content - this is where the metrics are saved isn't it?
> 
That is correct.
> In the logs above I included entries about deleting the database as I thought this may be relevant. Should that be happening? Is the database it refers to the cache on disk that it would use to reinstate the metrics after a restart?

That should not be happening. Can you send me some more detailed logs around the time of the incidents? You can e-mail me at markos@netdata.cloud . You can remove any private information that you don't wish to share.

**Comment by ilyam8** [comment] 2019-11-11 12:53
@AaronRobinson does it happen when you `systemctl restart netdata.service` ?

**Comment by AaronRobinson** [comment] 2019-11-11 13:51
@ilyam8 When I first noticed this a couple of weeks back I restarted netdata on the collector and central server just in case. But I can do this again and report back tomorrow morning.

**Comment by AaronRobinson** [comment] 2019-11-11 14:11
@mfundul logs sent for past 6 days

**Comment by AaronRobinson** [comment] 2019-11-11 14:12
@ilyam8 I just restarted netdata manually and it retained the metrics without issue

**Comment by mfundul** [comment] 2019-11-11 14:20
> 
> 
> @mfundul logs sent for past 6 days

Thank you for sending the logs @AaronRobinson . The first thing I noticed is that you're using `dbengine` and `save` memory modes at the same time. I think what's happening is that your master server is using `dbengine` in `netdata.conf` for its local metrics, and the slaves use `save` in `stream.conf`.

You should refresh your `netdata.conf` file by updating it as shown in the comments inside it:
```
# You can download the latest version of this file, using:
#
#  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
```

It is possible that you were using the default `memory mode` in `netdata.conf` when the default switched to `dbengine`, but the file remained with the stale comment such as:
`# memory mode = save` and it's confusing us.

So now, with the assumption that local metrics are `dbengine` and slave metrics are `save`, when you say that restarting netdata manually retains the metrics I would expect that local metrics are retained either way (`dbengine`) but slave metrics are lost (`save`).

Which is the case here?

**Comment by AaronRobinson** [comment] 2019-11-11 14:38
@mfundul that's been done and yes, it updated the default to dbengine. I've removed the comment and made set it to 'save'. Restart of netdata retains the metrics. 

So to summarise, I had my master config file defaulted to save but there was a subsequent update which changed the default to dbengine but the conf file still showed save. This resulted in netdata becoming confused being told to deal with memory in different ways and this resulted in metrics being lost under certain circumstances. A manual restart retained them. An unsolicited restart didn't.

As before, I'll see what happens in the morning and report back results.

**Comment by AaronRobinson** [comment] 2019-11-11 14:42
Super impressed with the responsiveness and quality of the support on this issue.

**Comment by mfundul** [comment] 2019-11-11 14:57
> 
> 
> @mfundul that's been done and yes, it updated the default to dbengine. I've removed the comment and made set it to 'save'. Restart of netdata retains the metrics.
> 
> So to summarise, I had my master config file defaulted to save but there was a subsequent update which changed the default to dbengine but the conf file still showed save. This resulted in netdata becoming confused being told to deal with memory in different ways and this resulted in metrics being lost under certain circumstances. A manual restart retained them. An unsolicited restart didn't.
> 
> As before, I'll see what happens in the morning and report back results.

Unfortunately that steal does not explain the metrics being lost. In theory streaming hosts and localhost should happily work with different databases independently. I still have to look into why slave hosts are being deleted as if their data had been marked as "obsolete".

**Comment by AaronRobinson** [comment] 2019-11-11 15:22
One other thing worth noting is that they aren't always lost. Some mornings they are there. I think yesterday or day before yesterday they were there. The logs I sent should reflect that.

**Comment by mfundul** [comment] 2019-11-11 15:36
> 
> 
> One other thing worth noting is that they aren't always lost. Some mornings they are there. I think yesterday or day before yesterday they were there. The logs I sent should reflect that.

Do you remember what's being lost exactly? Is it the localhost metrics of the master host itself or is it the slave's data that are being streamed? In the logs it looks like it's the slave's data that are being deleted.

**Comment by AaronRobinson** [comment] 2019-11-11 15:48
Interesting. It looks like some slaves have retained the full 24 hours while others have lost everything pre 6:25am. The master lost everything after the last restart I did about 15 minutes ago.

**Comment by mfundul** [comment] 2019-11-11 15:49
> 
> 
> Interesting. It looks like some slaves have retained the full 24 hours while others have lost everything pre 6:25am. The master lost everything after the last restart I did about 15 minutes ago.

The master probably did not lose anything, it just switched to a different database (`dbengine` -> `save`). You should be able to see the master's metric if you revert to `dbengine` again.

**Comment by AaronRobinson** [comment] 2019-11-11 16:11
> > Interesting. It looks like some slaves have retained the full 24 hours while others have lost everything pre 6:25am. The master lost everything after the last restart I did about 15 minutes ago.
> 
> The master probably did not lose anything, it just switched to a different database (`dbengine` -> `save`). You should be able to see the master's metrics if you revert to `dbengine` again.

Understood - those metrics aren't so important. It's the slave metrics I need most. I thought the same master setting

**Comment by mfundul** [comment] 2019-11-11 20:29
I think I understand now what's happening. The culprit is the combination of the global option `"delete obsolete charts files"` that is on by default (see [here](https://docs.netdata.cloud/daemon/config/)), the database mode `memory mode = save` and the timing of how the slaves and the master host restart their services.

It appears that some slaves restart their netdata service just before the master restarts its service as well. As a result, the slave drops the connection to the master server. The master server marks the absence of the slave as a possibly obsolete/ephemeral host (@thiagoftsm please look at this) and right after that the master itself is instructed to shutdown. All the data are marked as obsolete and are consequently deleted from the master's storage for this slave's database instance.

The immediate solution to your problem is to use `dbengine` instead in both `netdata.conf` and `stream.conf`. `dbengine` is not only the default database these days but has always been the recommended one for master-slave setups. For more details look [here](https://docs.netdata.cloud/database/) and [here](https://docs.netdata.cloud/streaming/#configuration).

The `dbengine` database never deletes any metrics for any reason other than exceeding the configurable disk space  quota. In `save` mode if there is a change in data collection frequency, or if the most recent timestamp was too long ago, or if there is a mismatch in the chart definition, or if something has been marked as obsolete for any reason the data are deleted. I've already seen 2 of those things in your logs @AaronRobinson . It's not a flexible database implementation, in contrast to [dbengine](https://blog.netdata.cloud/posts/release-1.17/).

**Comment by AaronRobinson** [comment] 2019-11-11 20:49
Wow - nice find. Thank you. I've switched over to dbengine now.

I got the following alert after switching over which I'll investigate but monitoring seems to be working.

```
monitor is critical, netdata.dbengine_global_errors (dbengine), 10min dbengine global fs errors = 2 errors

10min dbengine global fs errors = 2 errors
number of File-System errors dbengine came across the last 10 minutes (too many open files, wrong permissions etc)
netdata.dbengine_global_errors
```

**Comment by mfundul** [comment] 2019-11-11 20:50
You should probably increase the number of file descriptors since you're using streaming as described [here](https://docs.netdata.cloud/database/engine/#file-descriptor-requirements).

**Comment by AaronRobinson** [comment] 2019-11-11 21:02
Yep. Thanks for all your help.

**Comment by AaronRobinson** [comment] 2019-11-12 08:34
Pleased to report that overnight metrics retained. One server didn't but the logs show this is file descriptors related so I've now updated as per docs.

Thanks again.

**Comment by ilyam8** [comment] 2019-11-12 08:51
@mfundul is this really high prio bug?

**Comment by mfundul** [comment] 2019-11-12 09:02
> 
> 
> @mfundul is this really high prio bug?

It is and I'm reopening this. The real problem here is that for the setting `memory mode` and values of `map` and `save` it appears that slave netdata metrics can be easily deleted as wrongfully determined obsolete data. Imagine having gathered metrics for a year only for them to be deleted because the slave agent and the master agent happened to shutdown at the same time.

**Comment by ilyam8** [comment] 2019-11-12 09:22
@mfundul i agree, bu i suggest to update OP or, which is better imo, open a new issue with detailed bug description.

**Comment by AaronRobinson** [comment] 2019-11-12 09:25
Sorry for confusion in closing the issue. I had originally created this as
a question not realising there was an issue.

FWIW I’d prob close this as the issue I raised is now solved and create a
new one for the discovered problem.

**Comment by mfundul** [comment] 2019-11-12 09:27
> 
> Sorry for confusion in closing the issue. I had originally created this as a question not realising there was an issue. FWIW I’d prob close this as the issue I raised is now solved and create a new one for the discovered problem.

No need to apologise. I converted this question to a bug so that the discussion is not lost.

**Comment by mfundul** [comment] 2019-11-12 10:04
Referencing comment https://github.com/netdata/netdata/issues/2292#issuecomment-441222512

Should we just phase out `map` and `save`?

**Comment by mfundul** [comment] 2019-11-23 13:29
Reopening due to #7360.

**Comment by AaronRobinson** [comment] 2019-11-23 14:38
Set as suggested. Will report back if I have issues. Thanks all.
```
delete obsolete charts files = no
delete orphan hosts files = no
```

**Comment by cakrit** [comment] 2019-11-29 09:32
Closing for now, we'll reopen if we see a comment here.

**Closed by cakrit** 2019-11-29 09:32 UTC
Labels: area/daemon, area/database, area/streaming, bug, priority/high

**Comment by kousu** [comment] 2021-02-14 11:04
Hello! I have hit this.



##### Bug report summary


netdata

##### OS / Environment

```
Linux monitor.neuro.polymtl.ca 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.2 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.2 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Netdata version

 
netdata v1.19.0

##### Component Name


streaming

##### Steps To Reproduce


1. ...
2. ...

##### Expected behavior


I would like

```
[global]
delete obsolete charts files = no
delete orphan hosts files = no

[API KEY]
default memory mode = dbengine
```

to become the **defaults**. It is a painful surprise to learn you've suddenly lost all your metrics.

I don't fully understand how "orphan files" interacts with `dbengine`; I assume these options made more sense with `save`; I mentioned my confusion in https://github.com/netdata/netdata/issues/10629, and improving the documentation would be one.

**Comment by ilyam8** [comment] 2021-02-16 17:27
@kousu, why do you use to v1.19.0 (released this on 28 Nov 2019)? it is very old, latest stable is v1.29.1

**Comment by kousu** [comment] 2021-02-16 17:34
@ilyam8 I'm on the latest Ubuntu-LTS. This is as new as I can get.

I can't ask my org to deploy bleeding-edge servers just for monitoring. Even getting Ubuntu 20.04 deployed is a struggle we're still in the middle of. Unfortunately, it would make more sense to leave our servers unmonitored than to use software we're unfamiliar with, since at least familiar software breaks in ways we can diagnose and fix faster, manually. I'm trying to improve the situation by doing things like automating more and deploying netdata, but I have to work with what's available.

**Comment by kousu** [comment] 2021-02-16 17:34
I'm surely not the only one in this situation. :shrug:

**Comment by ilyam8** [comment] 2021-02-16 17:40
Check https://learn.netdata.cloud/docs/get#other-operating-systemsmethods, there is no need to update your distro to get Netdata latest.
