### ISSUE TITLE
Free IPMI plug-in does not compile on Debian bullseye

### ISSUE THREAD

**Issue by automaton82** [netdata/netdata#11819] opened 2021-11-22 15:19 UTC
##### Bug report summary

Running the standard install `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` is not creating `/usr/libexec/netdata/plugins.d/freeipmi.plugin` on Debian bullseye with `libipmimonitoring-dev` and `freeipmi-tools` installed on it.

##### OS / Environment

```
Linux pve2 5.13.19-1-pve #1 SMP PVE 5.13.19-2 (Tue, 09 Nov 2021 12:59:38 +0100) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Netdata version

netdata v1.31.0-522-nightly

##### Installation method

One line mode was used `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

##### Component Name

Installer and freeipmi.plugin

##### Steps To Reproduce

1. Install Debian bullseye
2. Login as root
3. Execute `apt-get install libipmimonitoring-dev`
4. Execute `apt-get install freeipmi-tools`
5. Ensure `ipmimonitoring` works by running it
6. Run the one-line kickstart installation method as per above

##### Expected behavior

The freeipmi.plugin is never created and you can't use IPMI. Also netdata.conf does not contain the freeipmi section.

**Comment by automaton82** [comment] 2021-11-22 15:46
After further investigation the bug is in the detection of the libipmimonitoring-dev package. It's not detected on Debian bullseye unless the following command is executed `ln -s /usr/lib/x86_64-linux-gnu/pkgconfig/libipmimonitoring.pc/libipmimonitoring.pc /usr/lib/pkgconfig/libipmimonitoring.pc` which solves this.

I only found this afterwards in https://github.com/netdata/netdata/issues/11381.

**Comment by ilyam8** [comment] 2021-11-22 16:45
Closing as duplicate of #11381

**Closed by ilyam8** 2021-11-22 16:45 UTC
Labels: bug, duplicate, needs triage
