### ISSUE TITLE
[Bug]: new Cloud UI does not work if agent is not connected to cloud.

### ISSUE THREAD

**Issue by pgassmann** [netdata/netdata#15466] opened 2023-07-20 15:55 UTC
### Bug description

I cannot access the new (default) ui of netdata after updating to 1.41.0

netdata is configured behind a reverse proxy with basic auth. node is not claimed netdata cloud

https://netdata.example.com/v1/ works as expected.

/ or /v2 quickly flashes and redirects to /trust which asks again for credentials. when entered again,it shows the following message:

> ### Welcome to Netdata
> Loading latest Netdata Cloud UI...
> 
> We couldn't load the latest Netdata Cloud UI. [You can try again ](javascript:location.reload();)
> Or you can load the [old single node dashboard](javascript:goToOld('/v1');) or a [local copy](javascript:goToOld('/v2');) of Netdata Cloud UI
> [Netdata Cloud UI license](javascript:getAssetFile('/LICENSE.md');)

### Expected behavior

when I access the netdata URL with proper basic auth credentials, I should have access to the ui.

### Steps to reproduce

1. install netdata behind basic auth proxy
2. upgrade to 1.41
3. access webpage

### Installation method

manual setup of official DEB/RPM packages

### System info

```shell
# uname -a; grep -HvE "^#|URL" /etc/*release
Linux storage2 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04.2 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04.2 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
# netdata -W buildinfo
Packaging:
    Netdata Version ____________________________________________ : v1.41.0
    Installation Type __________________________________________ : binpkg-deb
    Package Architecture _______________________________________ : x86_64
    Package Distro _____________________________________________ :  
    Configure Options __________________________________________ :  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Default Directories:
    User Configurations ________________________________________ : /etc/netdata
    Stock Configurations _______________________________________ : /usr/lib/netdata/conf.d
    Ephemeral Databases (metrics data, metadata) _______________ : /var/cache/netdata
    Permanent Databases ________________________________________ : /var/lib/netdata
    Plugins ____________________________________________________ : /usr/libexec/netdata/plugins.d
    Static Web Files ___________________________________________ : /var/lib/netdata/www
    Log Files __________________________________________________ : /var/log/netdata
    Lock Files _________________________________________________ : /var/lib/netdata/lock
    Home _______________________________________________________ : /var/lib/netdata
Operating System:
    Kernel _____________________________________________________ : Linux
    Kernel Version _____________________________________________ : 5.15.0-76-generic
    Operating System ___________________________________________ : Ubuntu
    Operating System ID ________________________________________ : ubuntu
    Operating System ID Like ___________________________________ : debian
    Operating System Version ___________________________________ : 22.04.2 LTS (Jammy Jellyfish)
    Operating System Version ID ________________________________ : none
    Detection __________________________________________________ : /etc/os-release
Hardware:
    CPU Cores __________________________________________________ : 16
    CPU Frequency ______________________________________________ : 3700000000
    CPU Architecture ___________________________________________ : 134766301184
    RAM Bytes __________________________________________________ : 161929400860672
    Disk Capacity ______________________________________________ : x86_64
    Virtualization Technology __________________________________ : none
    Virtualization Detection ___________________________________ : systemd-detect-virt
Container:
    Container __________________________________________________ : none
    Container Detection ________________________________________ : systemd-detect-virt
    Container Orchestrator _____________________________________ : none
    Container Operating System _________________________________ : none
    Container Operating System ID ______________________________ : none
    Container Operating System ID Like _________________________ : none
    Container Operating System Version _________________________ : none
    Container Operating System Version ID ______________________ : none
    Container Operating System Detection _______________________ : none
Features:
    Built For __________________________________________________ : Linux
    Netdata Cloud ______________________________________________ : YES
    Health (trigger alerts and send notifications) _____________ : YES
    Streaming (stream metrics to parent Netdata servers) _______ : YES
    Replication (fill the gaps of parent Netdata servers) ______ : YES
    Streaming and Replication Compression ______________________ : YES (lz4)
    Contexts (index all active and archived metrics) ___________ : YES
    Tiering (multiple dbs with different metrics resolution) ___ : YES (5)
    Machine Learning ___________________________________________ : YES
Database Engines:
    dbengine ___________________________________________________ : YES
    alloc ______________________________________________________ : YES
    ram ________________________________________________________ : YES
    map ________________________________________________________ : YES
    save _______________________________________________________ : YES
    none _______________________________________________________ : YES
Connectivity Capabilities:
    ACLK (Agent-Cloud Link: MQTT over WebSockets over TLS) _____ : YES
    static (Netdata internal web server) _______________________ : YES
    h2o (web server) ___________________________________________ : YES
    WebRTC (experimental) ______________________________________ : NO
    Native HTTPS (TLS Support) _________________________________ : YES
    TLS Host Verification ______________________________________ : YES
Libraries:
    LZ4 (extremely fast lossless compression algorithm) ________ : YES
    zlib (lossless data-compression library) ___________________ : YES
    Judy (high-performance dynamic arrays and hashtables) ______ : YES (bundled)
    dlib (robust machine learning toolkit) _____________________ : YES (bundled)
    protobuf (platform-neutral data serialization protocol) ____ : YES (system)
    OpenSSL (cryptography) _____________________________________ : YES
    libdatachannel (stand-alone WebRTC data channels) __________ : NO
    JSON-C (lightweight JSON manipulation) _____________________ : YES
    libcap (Linux capabilities system operations) ______________ : NO
    libcrypto (cryptographic functions) ________________________ : YES
    libm (mathematical functions) ______________________________ : YES
    jemalloc ___________________________________________________ : NO
    TCMalloc ___________________________________________________ : NO
Plugins:
    apps (monitor processes) ___________________________________ : YES
    cgroups (monitor containers and VMs) _______________________ : YES
    cgroup-network (associate interfaces to CGROUPS) ___________ : YES
    proc (monitor Linux systems) _______________________________ : YES
    tc (monitor Linux network QoS) _____________________________ : YES
    diskspace (monitor Linux mount points) _____________________ : YES
    freebsd (monitor FreeBSD systems) __________________________ : NO
    macos (monitor MacOS systems) ______________________________ : NO
    statsd (collect custom application metrics) ________________ : YES
    timex (check system clock synchronization) _________________ : YES
    idlejitter (check system latency and jitter) _______________ : YES
    bash (support shell data collection jobs - charts.d) _______ : YES
    debugfs (kernel debugging metrics) _________________________ : YES
    cups (monitor printers and print jobs) _____________________ : YES
    ebpf (monitor system calls) ________________________________ : YES
    freeipmi (monitor enterprise server H/W) ___________________ : YES
    nfacct (gather netfilter accounting) _______________________ : YES
    perf (collect kernel performance events) ___________________ : YES
    slabinfo (monitor kernel object caching) ___________________ : YES
    Xen ________________________________________________________ : NO
    Xen VBD Error Tracking _____________________________________ : NO
Exporters:
    AWS Kinesis ________________________________________________ : NO
    GCP PubSub _________________________________________________ : NO
    MongoDB ____________________________________________________ : NO
    Prometheus (OpenMetrics) Exporter __________________________ : YES
    Prometheus Remote Write ____________________________________ : YES
    Graphite ___________________________________________________ : YES
    Graphite HTTP / HTTPS ______________________________________ : YES
    JSON _______________________________________________________ : YES
    JSON HTTP / HTTPS __________________________________________ : YES
    OpenTSDB ___________________________________________________ : YES
    OpenTSDB HTTP / HTTPS ______________________________________ : YES
    All Metrics API ____________________________________________ : YES
    Shell (use metrics in shell scripts) _______________________ : YES
Debug/Developer Features:
    Trace All Netdata Allocations (with charts) ________________ : NO
    Developer Mode (more runtime checks, slower) _______________ : NO
```

### Additional info

# netdatacli aclk-state
ACLK Available: Yes
ACLK Version: 2
Protocols Supported: Protobuf
Protocol Used: Protobuf
MQTT Version: 5
Claimed: No
Online: No
Reconnect count: 0
Banned By Cloud: No

**Comment by ilyam8** [comment] 2023-07-20 16:45
Hi, @pgassmann. I just tested the following setup:

- vm1: ND v1.41.0 debian pkg (just install via kickstart, not claimed).
- vm2: Nginx with basic auth.

I have no problems with accessing ND through NGINX with basic auth.

Does the dashboard work for you when accessing directly?

**Comment by Hufschmidt** [comment] 2023-07-28 07:51
Similar issue with the new v2 interface. As with pgassmann our instances are explicitly disconnected from the cloud and run inside an internal network with now outside access anyway.

Interface is completely empty:
![Screenshot_20230728_094746](https://github.com/netdata/netdata/assets/11391961/dfb89df3-ea36-436b-9f1d-381cc02c76f3)

While `/v1/` works without any issues.

**Comment by Hufschmidt** [comment] 2023-07-28 08:21
Maybe also of relevance might be that all instances are configured to run against a central (cluster) registry, eg.

```
[registry]
    registry hostname = ILIAS - LB (Master)
    enabled = yes
    registry to announce = http://ilias-master.example.de:19999
```

```
[registry]
    registry hostname = ILIAS - LB (Slave)
    enabled = no
    registry to announce = http://ilias-master.example.de:19999
```

**Comment by Hufschmidt** [comment] 2023-08-03 07:56
I just double-checked:

Removing `/var/lib/netdata/cloud.d/cloud.conf` and restarting netdata makes the v2 interface work.

```
# /var/lib/netdata/cloud.d/cloud.conf
[global]
    enabled = no
```

---

So either the v2 interface should be disabled when cloud-connection is disabled this way OR the v2 interface needs a fallback for non-cloud instances.

**Comment by andrewm4894** [comment] 2023-08-03 11:38
thanks @Hufschmidt - i'll try ping correct people internally to figure out how best we can root cause this issue and figure out if/why the fallback to v1 is not working in your case (afaik there is supposed to be a fallback like you suggest - i have a feeling the blank screen might just not being recognised properly as a fallback trigger - will see if someone can help us dig into it).

**Comment by ilyam8** [comment] 2023-08-03 13:18
Ok, managed to reproduce https://github.com/netdata/netdata/issues/15466#issuecomment-1655215801. The problem is invalid characters in the hostname (`(` and `)`).

```
Filename contains invalid characters: spaces/ILIAS-LB(Slave)/rooms/local/overview
```

It happens only with the`/v2` endpoint. That is why removing ` enabled = no` "fixes" the problem. If cloud is enabled (just enabled, it has nothing to do with connection/ACLK) we don't use the bundled version of the dashboard (`/v2` is bundled).

cc @kapantzak @novykh check please, probably a bug in the agent with sanitizing characters.

**Comment by ilyam8** [comment] 2023-08-03 13:38
So for stable channel users with disabled cloud, this will be fixed in the next release, which is scheduled for release next week.

**Comment by ilyam8** [comment] 2023-08-04 12:21
Closing because the problem has been fixed.

**Closed by ilyam8** 2023-08-04 12:21 UTC
Labels: bug, needs triage

**Comment by Hufschmidt** [comment] 2023-08-11 11:33
Can confirm, the v2 interface works in 1.42.0 with cloud disabled and node unclaimed. Big thanks! :heart:

**Comment by emsofo** [comment] 2023-09-17 10:33
I have a similar issue with 1.42.2 running as plugin for OPNSense - I can load the interface under chrome, but under firefox 117 it's stuck on "Welcome to Netdata - Loading latest Netdata UI..." - I can load the "old" interface fine - and if hit refresh many times - I see the error:  "We couldn't load the latest Netdata UI"
