### ISSUE TITLE
[Bug]: Auto update failing to match latest version

### ISSUE THREAD

**Issue by danny-cain-dev** [netdata/netdata#11982] opened 2022-01-17 11:16 UTC
### Bug description

Netdata auto update is failing with the message:

"ERROR:  FAILED TO UPDATE NETDATA : Cannot download latest stable tag from https://github.com/netdata/netdata/releases/latest"

This appears to be because the latest release doesn't have the 'v' prefix which the update script checks for in it's regex:
```
if echo "{$tag}" | grep -vEq "^v[0-9]+\..+"; then
```

Removing the 'v' from the regexp allows the auto updater to run successfully.

### Expected behavior

Updater runs successfully

### Steps to reproduce

1. Run the updater
2.
3.
...

### Installation method

kickstart.sh

### System info

```shell
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.3 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.3 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

### Netdata build info

```shell
Version: netdata v1.32.1
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--with-bundled-lws' '--with-bundled-protobuf' 'CFLAGS=-O2' 'LDFLAGS='
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                YES
    TLS Host Verification:      YES
    Machine Learning:           YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    LWS:                     YES static v3.2.2
    mosquitto:               YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

**Comment by ilyam8** [comment] 2022-01-17 12:06
Hi, @danny-cain-dev. Duplicate of #11906.

> This appears to be because the latest release doesn't have the 'v' prefix which the update script checks for in it's regex:
> if echo "{$tag}" | grep -vEq "^v[0-9]+\..+"; then

Fixed in #11908

You need to set the timestamp on the updater script to an arbitrarily ancient date (for example, with touch -t 1970-01-01T00:00:00) and re-run the updater-script or wait until the next cron run.

**Closed** 2022-01-17 12:07 UTC
Labels: bug, duplicate, area/packaging
