### ISSUE TITLE
[Bug]: Problem naming containers when using Hashicorp Nomad

### ISSUE THREAD

**Issue by cakrit** [netdata/netdata#12419] opened 2022-03-15 19:47 UTC
### Bug description

We have a user with [Hashicorp's Nomad](https://www.nomadproject.io/) for container orchestration. 
The [container identification script](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh.in) doesn't seem to work in their case, so all the containers appear as ids.  

It's likely that we get similar errors as the ones reported in https://github.com/netdata/netdata/issues/9037#issuecomment-645711015

Note that Netdata is running directly on the VM that spawns the docker containers, so access rights is not the issue.

### Expected behavior

Containers should be correctly identified, when using Nomad.

### Steps to reproduce

1. Run Nomad?
2. Install Netdata
3. See cgroup ids instead of names 

### Installation method

kickstart.sh

### System info

```shell
--
```

### Netdata build info

```shell
Don't have it currently, will ask the user to add it, if needed.
```

### Additional info

--

**Comment by ilyam8** [comment] 2022-03-24 22:16
I installed [nomad](https://www.nomadproject.io/docs/install) and started [example.nomad](https://learn.hashicorp.com/tutorials/nomad/get-started-run?in=nomad/get-started) job. As a result, a docker container was created. It appears that the job uses [Docker driver](https://www.nomadproject.io/docs/drivers). So for Netdata, it is just a Docker container and the name resolution script works. I think we need more specific "Steps to reproduce" to fix this issue.

**Comment by marigbede** [comment] 2022-04-06 21:28
So I have a question. When Netdata becomes aware of a container, what fields or metadata does it look for so as to pick the names of the running container?

**Comment by cakrit** [comment] 2022-04-20 17:00
> So I have a question. When Netdata becomes aware of a container, what fields or metadata does it look for so as to pick the names of the running container?

For each cgroup identified, Netdata executes the `cgroup-name.sh` script you can find in one of our folders (don't recall exactly were). On githubt you can see its template [here](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh.in)

@vlvkobal and @ilyam8 this is a very common question. I think we need to document how we name containers (what the script does) somewhere with instructions on how to run it to debug why a container couldn't be identified.

**Comment by marigbede** [comment] 2022-04-20 17:54
Thanks @cakrit. The reason for this questions is if I can make out how Netdata picks out the names (hoping some form of tags can be used to pick out the names of the running containers), then we can finally resolve the issue where we only see IDs instead of container names.

**Comment by cakrit** [comment] 2022-04-21 11:57
The question I still have is if we have a next step. I had missed @ilyam8 's responses above when I wrote this. What we need @marigbede is a way to get to nomad resource name from a cgroup id, by running a linux command.  Perhaps we can ask Hashicorp's support?

**Comment by marigbede** [comment] 2022-04-21 16:20
@cakrit Thanks we are getting there. I want to believe that the default way of configuring the jobs in Nomad sees this **cgroup id** as an optional label.  Therefore, lets use docker for example, if I am running docker on a linux machine manually, what fields would the script or meta data would the script look at to try to pick out the name of the running container. we can either try to hack this by submitting a PR to Nomad or apply some tags, labels, aliases, descriptions, environment variables (or something) within a Nomad Job Spec, that would just handshake with the script and pull the information we need.

I may need more information as to what the cgroup id is, where and how it is stored. That will also assist with my findings.

**Comment by cakrit** [comment] 2022-05-02 17:29
Again took a while for me to respond, apologies @marigbede 

What we need is any command that we can run, that takes as input the container id and returns a name. For docker, we use
`docker ps`.  See first [line 350](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh#L350). This code is called if the `hash` command has returned `docker` as a recently executed program. It passes `docker` and the id to the function defined in [line 48](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh#L48). There you can see that at the end, for this case, 
`NAME="$(docker ps --filter=id="${id}" --format="{{.Names}}")"`

I really can't go much further, I think you'll need to read that script, understand it and run it on your own. When you have found a setup that can return the name you want based on an id, you don't need to do a PR to the script, we can do it ourselves. But we don't have any people familiar with nomad here, so we can't go much further on our own...

**Comment by marigbede** [comment] 2022-05-29 15:03
I will be posting some updates soon.

**Comment by pikeas** [comment] 2022-06-16 16:30
I'm experiencing this as well.

Environment: Netdata 1.35.1 (running on host), Nomad 1.3.1, Ubuntu 22.04.

Netdata logs:

```
# journalctl -u netdata -f
Jun 16 18:15:47 server01 systemd[1]: Started Real time performance monitoring.
Jun 16 18:15:47 server01 netdata[10084]: CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
Jun 16 18:15:47 server01 netdata[10084]: 2022-06-16 18:15:47: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
Jun 16 18:15:48 server01 ebpf.plugin[10272]: Does not have a configuration file inside `/etc/netdata/ebpf.d.conf. It will try to load stock file.
Jun 16 18:15:48 server01 ebpf.plugin[10272]: Name resolution is disabled, collector will not parser "hostnames" list.
Jun 16 18:15:48 server01 ebpf.plugin[10272]: The network value of CIDR 127.0.0.1/8 was updated for 127.0.0.0 .
Jun 16 18:15:48 server01 ebpf.plugin[10272]: Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/usr/lib/netdata/conf.d/apps_groups.conf'
```

Netdata config:
```
# cat /etc/netdata/netdata.conf
[global]
run as user = netdata
bind socket to IP = 10.x.x.x
```

Netdata shows all containers with ID only, except for ones with a prefix of `nomad-slice`.

Running a container in docker directly also appears in Netdata as ID only. AFAIK, Nomad doesn't alter Docker's service configuration, so this may be on the Netdata side.

@cakrit The code from line 48 works for me when run directly:

```
$ docker run --rm --name=test -it ubuntu bash
$ docker ps --filter=id="25c019a42688" --format="{{.Names}}"
test
```

Netdata's panel shows this container as `25c019a42688` rather than `test`.

**Comment by ilyam8** [comment] 2022-06-16 16:37
@pikeas hey

1. if Netdata is running in a docker container too we need to mount docker.sock inside the container (`-v /var/run/docker.sock:/var/run/docker.sock:ro`).
2. if Netdata is installed on the host we need to add `netdata` user to the `docker` (`sudo gpasswd -a netdata docker`) group and restart netdata service.

The 2nd case is either you install Netdata before installing Docker Engine (unlikely) or https://github.com/netdata/netdata/issues/13090.

**Comment by pikeas** [comment] 2022-06-16 16:40
> @pikeas hey
> 2. if Netdata is installed on the host we need to add `netdata` user to the `docker` (`sudo gpasswd -a netdata docker`) group and restart netdata service.
> 
> The 2nd case is either you install Netdata before installing Docker Engine (unlikely) or #13090.

This did the trick! Adding the netdata to the docker group and restarting the service worked.

For the team, it would be great if this logged an error. When Netdata is running, Docker is also running on the host, and the Docker plugin is enabled, it's reasonable to assume that operators want container names.

**Comment by ilyam8** [comment] 2022-06-16 16:51
There is an error, it is not properly formatted but there is. 

I removed `netdata` from `docker`

```cmd
deb-work ~ $ grep permission /opt/netdata/var/log/netdata/error.log
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22id%22%3A%7B%22c4de5f3f675cc106511f8df9aee6da45a2d45f9c7da8807d80f03b0d625b79b9%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22id%22%3A%7B%22c4de5f3f675cc106511f8df9aee6da45a2d45f9c7da8807d80f03b0d625b79b9%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
```

---

> PS - can the container list be sorted by container name?

I think it is sorted by container name. Can you show a screenshot?

**Comment by pikeas** [comment] 2022-06-16 16:57
> There is an error, it is not properly formatted but there is.
> ```batchfile
> deb-work ~ $ grep permission /opt/netdata/var/log/netdata/error.log
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22id%22%3A%7B%22c4de5f3f675cc106511f8df9aee6da45a2d45f9c7da8807d80f03b0d625b79b9%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22id%22%3A%7B%22c4de5f3f675cc106511f8df9aee6da45a2d45f9c7da8807d80f03b0d625b79b9%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied
> ```

Ah, thanks! Then I'm surprised the errors are logged to a separate file - they're invisible to systemd/journalctl.

> > PS - can the container list be sorted by container name?
> 
> I think it is sorted by container name. Can you show a screenshot?

<img width="201" alt="Screen Shot 2022-06-16 at 12 55 25 PM" src="https://user-images.githubusercontent.com/686573/174125461-aa8e5c5b-f33e-4903-b2ba-69b63077e8e4.png">

**Comment by ilyam8** [comment] 2022-06-17 09:05
> This isn't ideal from a permissions perspective - is there a way to grant read-only permissions instead of joining the docker group?

If you are concerned about security - using https://github.com/Tecnativa/docker-socket-proxy is an option. We have a guide on [how to use it with Netdata](https://learn.netdata.cloud/docs/agent/packaging/docker#docker-socket-proxy-safest-option) but it is only for dockerized Netdata.

**Comment by cakrit** [comment] 2022-06-17 14:42
> 2. if Netdata is installed on the host we need to add `netdata` user to the `docker` (`sudo gpasswd -a netdata docker`) group and restart netdata service.

@ilyam8 / @Ferroin shouldn't `kickstart.sh` do this by default? I understand the concerns, but it took us months to get to a suggested fix, for something that apparently we knew all along.

**Comment by ilyam8** [comment] 2022-06-17 15:16
@cakrit, we do it by default (except for cases when we install Docker after Netdata - during Netdata install there was no `docker` group - this case would be fixed by the next Netdata update).

We do it for:

- install from the source.
- static builds.
- native packages were the case where we wouldn't do it. For deb the bug was fixed 4 days ago. For rpm - not fixed atm.

**Comment by xkisu** [comment] 2022-07-31 07:18
> Again took a while for me to respond, apologies @marigbede
> 
> What we need is any command that we can run, that takes as input the container id and returns a name. For docker, we use `docker ps`. See first [line 350](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh#L350). This code is called if the `hash` command has returned `docker` as a recently executed program. It passes `docker` and the id to the function defined in [line 48](https://github.com/netdata/netdata/blob/master/collectors/cgroups.plugin/cgroup-name.sh#L48). There you can see that at the end, for this case, `NAME="$(docker ps --filter=id="${id}" --format="{{.Names}}")"`
> 
> I really can't go much further, I think you'll need to read that script, understand it and run it on your own. When you have found a setup that can return the name you want based on an id, you don't need to do a PR to the script, we can do it ourselves. But we don't have any people familiar with nomad here, so we can't go much further on our own...

Nomad exposes all the job information via environment variable in the container, these environment variables are stable and [well-documented](https://www.nomadproject.io/docs/runtime/environment) so they should be reliable for scripted detection.

Using some bash scripting we can extract information about the Nomad naming without even touching the Nomad API:
```bash
function docker_env_value() {
    local container="${1}"
    local env="${2}"

    echo ${echo $(docker inspect --format '{{ .Config.Env }}' "${container}") |  tr ' ' '\n' | grep "${env}" | sed 's/^.*=//'}
    # or for an all-docker go template solution:
    # $ echo $(docker inspect -f '{{range $index, $value := .Config.Env}}{{if eq (index (split $value "=") 0) "${env}" }}{{range $i, $part := (split $value "=")}}{{if gt $i 1}}{{print "="}}{{end}}{{if gt $i 0}}{{print $part}}{{end}}{{end}}{{end}}{{end}}' "${container}")
}

NOMAD_JOB_ID=$(docker_env_value f5438ad3fa74 NOMAD_JOB_ID) # slug format ID 
NOMAD_JOB_NAME=$(docker_env_value f5438ad3fa74 NOMAD_JOB_NAME) # user-friendly name
NOMAD_NAMESPACE=$(docker_env_value f5438ad3fa74 NOMAD_NAMESPACE) # namespace the job is in
NOMAD_ALLOC_ID=$(docker_env_value f5438ad3fa74 NOMAD_ALLOC_ID) # uuid of the allocation
NOMAD_ALLOC_NAME=$(docker_env_value f5438ad3fa74 NOMAD_ALLOC_NAME) # <job_id>.<group_name>[<alloc_index>]
NOMAD_GROUP_NAME=$(docker_env_value f5438ad3fa74 NOMAD_GROUP_NAME) # task group name/id
NOMAD_TASK_NAME=$(docker_env_value f5438ad3fa74 NOMAD_TASK_NAME) # task name
```

For a Nomad-related name to be useful on the dashboard it'd ideally need to include the namespace, job ID or name, allocation ID, group name and task name. This would be a bit long though (job_uuid + group_name + alloc_ud + task_name) and not easy to quickly correlate with the Nomad system. 

Partial allocation IDs can be passed to Nomad by using the first 8 characters of the allocation ID (cluster operators just need the namespace and alloc ID), so something like this would work really well and look okay:
```bash
SHORT_ALLOC_ID=$(echo "${NOMAD_ALLOC_ID}" | cut -c 1-8)
echo "${NOMAD_NAMESPACE} ${SHORT_ALLOC_ID} ${NOMAD_TASK_NAME}"
# Example output: `default db3b9f1b server`
# Example using the Nomad CLI to get info as an operator:
# $ nomad alloc status -namespace=default -t "{{ (index .TaskStates \"server\").State }}" db3b9f1b
```

**Comment by cakrit** [comment] 2022-08-01 18:07
I simply followed https://learn.hashicorp.com/tutorials/nomad/get-started-run?in=nomad/get-started up to running the example command, opened the netdata UI and saw the name of the container composed of `[NOMAD_TASK_NAME]_[NOMAD_ALLOC_ID]`. 

Here are the details:
```
root@ubuntu2004:~# docker inspect --format '{{ .Config.Env }}' 8abc42979d366b6202785db161b506ffb24fe9fb23c56cd5f2572ad238e78760 | tr ' ' '\n' 
[NOMAD_ADDR_db=127.0.0.1:22225
NOMAD_ALLOC_DIR=/alloc
NOMAD_ALLOC_ID=9a50c573-81bd-01b8-e5d1-8dfe183b5bfd
NOMAD_ALLOC_INDEX=0
NOMAD_ALLOC_NAME=example.cache[0]
NOMAD_ALLOC_PORT_db=6379
NOMAD_CPU_LIMIT=500
NOMAD_DC=dc1
NOMAD_GROUP_NAME=cache
NOMAD_HOST_ADDR_db=127.0.0.1:22225
NOMAD_HOST_IP_db=127.0.0.1
NOMAD_HOST_PORT_db=22225
NOMAD_IP_db=127.0.0.1
NOMAD_JOB_ID=example
NOMAD_JOB_NAME=example
NOMAD_MEMORY_LIMIT=256
NOMAD_NAMESPACE=default
NOMAD_PARENT_CGROUP=/nomad
NOMAD_PORT_db=6379
NOMAD_REGION=global
NOMAD_SECRETS_DIR=/secrets
NOMAD_SHORT_ALLOC_ID=9a50c573
NOMAD_TASK_DIR=/local
NOMAD_TASK_NAME=redis
...
```

Netdata log:
```
root@ubuntu2004:/# grep -i cgroup-name /var/log/netdata/error.log
2022-08-01 13:14:56: cgroup-name.sh: INFO: cgroup 'docker' is called 'docker'
2022-08-01 13:14:56: cgroup-name.sh: INFO: Running command: docker ps --filter=id="8abc42979d366b6202785db161b506ffb24fe9fb23c56cd5f2572ad238e78760" --format="{{.Names}}"
2022-08-01 13:14:56: cgroup-name.sh: INFO: docker container '8abc42979d366b6202785db161b506ffb24fe9fb23c56cd5f2572ad238e78760' is named 'redis-9a50c573-81bd-01b8-e5d1-8dfe183b5bfd'
2022-08-01 13:14:56: cgroup-name.sh: INFO: cgroup 'docker_8abc42979d366b6202785db161b506ffb24fe9fb23c56cd5f2572ad238e78760' is called 'redis-9a50c573-81bd-01b8-e5d1-8dfe183b5bfd'
```

The following command will show exactly what Netdata did...
```
root@ubuntu2004:/# bash -x ./usr/libexec/netdata/plugins.d/cgroup-name.sh docker/8abc42979d366b6202785db161b506ffb24fe9fb23c56cd5f2572ad238e78760 docker_8abc42979d366b6202785db161b506ffb24fe9fb23c56cd5f2572ad238e78760
```

...but essentially it used this:
```
root@ubuntu2004:/# docker ps --filter=id="8abc42979d366b6202785db161b506ffb24fe9fb23c56cd5f2572ad238e78760" --format="{{.Names}}"
redis-9a50c573-81bd-01b8-e5d1-8dfe183b5bfd
```

Screenshot: 
<img width="840" alt="image" src="https://user-images.githubusercontent.com/43294513/182208755-56ca98bf-f8e1-4330-9097-816c45cbbbe3.png">

So apparently, a default Nomad installation properly names its containers and Netdata just gets those names with `docker ps`. I searched a lot in their GitHub issues and documentation to see if this naming convention is hard-coded, or controlled by a configuration somewhere and I couldn't find anything (but I know very little about how it works). Before we continue with a separate implementation which may not actually be needed, can you check the following?

- Do a `docker ps` on your node and see what the `NAMES` column contains. 
- Check if it has to do with the Nomad version. I installed v1.3.2. Perhaps try it on a test VM?
- Check that `example` job to see if has something configured that your jobs don't.

I agree that controlling what the name contains should be our target here, but perhaps we can do it via a config on the nomad side, seeing that it's possible to get the 2 out of the 3 params already in a docker name.

**Comment by ilyam8** [comment] 2022-08-01 18:40
@cakrit Docker is one of Nomad task drivers, see https://github.com/netdata/netdata/issues/12419#issuecomment-1078434388

> Task drivers are used by Nomad clients to execute a task and provide resource isolation. By having extensible task drivers, Nomad has the flexibility to support a broad set of workloads across all major operating systems.

So it is a Docker container **and** Nomad task at the same time. My understanding is that we need somehow to identify that a docker container (or not Docker if using another driver) is a Nomad task and use the task name, not the docker container name.

**Comment by xkisu** [comment] 2022-08-01 20:46
> So apparently, a default Nomad installation properly names its containers and Netdata just gets those names with docker ps. I searched a lot in their GitHub issues and documentation to see if this naming convention is hard-coded, or controlled by a configuration somewhere and I couldn't find anything (but I know very little about how it works). Before we continue with a separate implementation which may not actually be needed, can you check the following?

@cakrit The `<task_name>-<alloc_id>` naming is hard-coded as part of Nomad's standard Docker driver as it's used for correlation by Nomad to associated running containers on the host with a running Nomad job, relevant part of the docs:
> Nomad creates a container after pulling an image. Containers are named {taskName}-{allocId}. This is necessary in order to place more than one container from the same task on a host (e.g. with count > 1). This also means that each container's name is unique across the cluster.
>
> This is not configurable.
https://www.nomadproject.io/docs/drivers/docker#container-name

While this naming does give admins/operators the task name and allocation ID, in systems that are using [namespaces](https://medium.com/hashicorp-engineering/supporting-multiple-teams-on-nomad-clusters-ff65355be431) to organize their running Nomad jobs they also need the namespace ID to be able to look up the allocation. As I noted in https://github.com/netdata/netdata/issues/12419#issuecomment-1200365744 the allocation ID in the container name could also be shortened to the first 8 characters of the UUID (it's how Nomad displays them everywhere) which would make the Nomad-related container IDs much more readable on the Netdata dashboard.

**Comment by cakrit** [comment] 2022-08-02 15:49
Makes sense gents, @ilyam8 I'll try to do it on my local install and do a PR.

**Closed** 2022-08-03 21:23 UTC
Labels: bug, area/collectors, collectors/cgroups

**Comment by marigbede** [comment] 2022-08-15 18:10
@cakrit Thanks for this. Please when will the modifications here be released for use?

**Comment by ilyam8** [comment] 2022-08-15 18:40
@marigbede it's been released, the changes are in the latest stable/nightly release.
