### ISSUE TITLE
Backend "type: prometheus_remote_write" doesn't work for latest docker image

### ISSUE THREAD

**Issue by MykhailoSobol** [netdata/netdata#7590] opened 2019-12-20 11:20 UTC
##### Question summary
Good morning !

Backend "type: prometheus_remote_write" doesn't work for latest docker image.

```
2019-12-20 10:12:31: netdata INFO  : BACKENDS : thread created with task id 27171
2019-12-20 10:12:31: netdata INFO  : BACKENDS : set name of thread 27171 to BACKENDS
2019-12-20 10:12:31: netdata ERROR : BACKENDS : BACKEND: Prometheus remote write support isn't compiled (errno 22, Invalid argument)
2019-12-20 10:12:31: netdata ERROR : BACKENDS : BACKEND: backend is misconfigured - disabling it.
2019-12-20 10:12:31: netdata INFO  : BACKENDS : cleaning up...
2019-12-20 10:12:31: netdata INFO  : BACKENDS : thread with task id 27171 finished
```

My "backend" config 
```
    [backend]
      type = prometheus_remote_write
      destination = xxx.xxx.xxx.xxx:8428
      remote write URL path = /api/v1/write
      enabled = yes
```
When I use same config for server with ubuntu and package was installed from "https://packagecloud.io/netdata/netdata/ubuntu". All works fine.
Is "type: prometheus_remote_write" supported for docker image?   Or Am I missing something?

##### OS / Environment
Docker image netdata/netdata:v1.19.0

**Comment by vlvkobal** [comment] 2019-12-20 12:01
The key phrase is "Prometheus remote write support isn't compiled". @knatsakis please look at the issue.

**Comment by prologic** [comment] 2020-01-14 04:54
https://github.com/netdata/netdata/pull/7691 similarly adds Prometheus remote write backend support for our static builds. I suspect we can do something similar for the Docker image(s).

**Comment by Dany21000** [comment] 2020-08-02 10:06
Hi, 

I'm using one VM with netdata "as central instance" with victoriametrics backend to collect few others netdata configured as streamers.
I'm thinking to replace the VM with a docker stack.

I have this problem, no backend compiled.

Can you provide new image with docker file prepared  with all backends ? like on debian package ?
I'm trying to create my own image from buster and APT package, but it's not very optimal an easier to maintain, it's better to use official image directly from netdata/netdata.

Have a good day.

**Comment by MykhailoSobol** [comment] 2020-08-02 12:31
Hi, 
The backends system is now deprecated in favor of the exporting engine. 
https://learn.netdata.cloud/docs/agent/exporting
but I have not check exporting engine

**Comment by Dany21000** [comment] 2020-08-02 21:24
> Hi,
> The backends system is now deprecated in favor of the exporting engine.
> https://learn.netdata.cloud/docs/agent/exporting
> but I have not check exporting engine

Thanks a lot, I haven't read the release notes since 1.15 or 1.17. Netdata is really good and I have no problem with it... I'm trying to use it in a professional context. At this time it's just for personal use.

**Comment by Dany21000** [comment] 2020-08-02 23:45
I'm still thinking about a compilation problem : 
I work on both netdata,  the first on debian by APT,  the second on docker.

I ve removed the backend section from netdata.conf and create a exporting.conf with the content shown from the edit-config script.

Everything work fine on the full debain VM but no on the docker version : 
```
2020-08-02 23:40:14: netdata INFO  : EXPORTING : Processing connector instance (victoriametrics)
2020-08-02 23:40:14: netdata INFO  : EXPORTING : Instance (victoriametrics) on connector (prometheus_remote_write) is enabled and scheduled for activation
2020-08-02 23:40:14: netdata INFO  : EXPORTING : Instance victoriametrics on prometheus_remote_write
2020-08-02 23:40:14: netdata ERROR : EXPORTING : Prometheus Remote Write support isn't compiled (errno 22, Invalid argument)
```

I'm stupid or not ?

**Comment by prologic** [comment] 2020-08-03 06:27
We (Agent SRE) haven't triaged this. Added to our Followup column to do so. Sorry about that!

**Comment by Dany21000** [comment] 2020-08-03 09:12
> We (Agent SRE) haven't triaged this. Added to our Followup column to do so. Sorry about that!

It's not a problem, i think you'll add this at the compilation list during the next release, it's just a little oversight, nothing else.
Have a good day and lot of thank for this great product.

**Comment by Ferroin** [comment] 2020-08-12 17:11
Confirmed, this is indeed a result of not having the required dependencies at build time.

This should not be as complicated as fixing the static builds was as we do not need a static copy of Snappy for it.

**Comment by prologic** [comment] 2020-08-13 10:44
@MykhailoSobol Please note that this is now in our backlog, however if you wish to help out and contribute a PR we can probably get this in sooner. Thanks!

**Comment by Dany21000** [comment] 2020-08-13 11:05
Great new, I hope to see the next version. Thanks for your work!

**Comment by dginhoux** [comment] 2020-09-06 12:28
This is a similar problem with the docker image.

I hope they will correct it in the next release.

**Comment by prologic** [comment] 2020-09-14 04:32
I believe this is already fixed and should be in the nightly builds. This will be released tomorrow as planned.

**Comment by dginhoux** [comment] 2020-09-15 12:25
Hi, 

I've successfully upgraded my docker "central netdata" instance to 1.25.
Everything work fine and exporting work fine to my opentsdb with the old backend conf.

I'll try new exporting system.

Thank every one.

**Comment by prologic** [comment] 2020-09-16 06:02
Thanks for the confirmation! Closing! 🎉

**Closed by prologic** 2020-09-16 06:02 UTC
Labels: area/packaging, docker, feature request
