### ISSUE TITLE
[Bug]: Multiple chart labels not filtering correctly

### ISSUE THREAD

**Issue by Franck31** [netdata/netdata#16521] opened 2023-12-01 16:22 UTC
### Bug description

When using multiple chart labels (k8s_namespace and k8s_container_name) in the configuration file, the order in which the conditions are presented seems to affect the expected behavior. Specifically, there is an issue with the filtering logic that leads to unexpected results.

my cgroup.cfg looks like this:

> template: k8s_cgroup_10min_cpu_usage
>   on: k8s.cgroup.cpu_limit
>   class: Utilization
>   type: Cgroups
>   component: CPU
>   os: linux
>   hosts: *
>   chart labels: k8s_namespace=!prod-*  k8s_namespace=!test-*  k8s_namespace=!sandbox-* k8s_container_name=!kubecost-network-costs *
>   lookup: average -10m unaligned
>   units: %
>   every: 1m
>   warn: $this > (($status >= $WARNING)  ? (75) : (85))
>   delay: down 15m multiplier 1.5 max 1h
>   summary: Container ${label:k8s_container_name} pod ${label:k8s_pod_name} CPU utilization
>   info: Container ${label:k8s_container_name} of pod ${label:k8s_pod_name} of namespace ${label:k8s_namespace}, \
>         average CPU utilization over the last 10 minutes
>   to: sysadmin

This config *ONLY* remove the alert of the kubecost-network-costs container, but all namespaces alerts still loaded,

if i change the order of my cfg to:

>        chart labels:  k8s_container_name=!kubecost-network-costs k8s_namespace=!prod-*  k8s_namespace=!test-*  k8s_namespace=!sandbox-*  *

All the namespaces alerts are removed but the kubecost-network-costs is present.  

### Expected behavior

both alerts should be removed from the alerts panel and no notifications for this charts should be silent

### Steps to reproduce

1. add multiple chart labels in the cgroups.conf
2. look at the alerts
3. change order of the chart labels in cgroups.conf
4. look at the alerts
...

### Installation method

helmchart (kubernetes)

### System info

```shell
Amazon Linux / EKS
```

### Netdata build info

```shell
Version: netdata v1.40.0
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--disable-dependency-tracking' '--disable-ebpf' 'CFLAGS=-O2 -pipe' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
    HTTPD (h2o):                YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    debugfs:                 YES
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by ilyam8** [comment] 2023-12-01 16:43
Hey, @Franck31. You not only changed the order, but changed the value of `k8s_container_name`.

`k8s_container_name=!kubecost-network-costs *` => `k8s_container_name=!kubecost-network-costs`.

**Comment by ilyam8** [comment] 2023-12-01 22:13
Correct, that is the logic: OR when using multiple labels. By different labels I mean different keys: key=val1 key=val2 key=val3 is the same as key=val1 val2 val3 - that would be 1 label. 

I find it confusing and opened #15203.

If you tell me what you are trying to filter, I can answer whether it is possible with the current implementation of chart labels filter.

**Comment by Franck31** [comment] 2023-12-04 19:16
I think this pattern is the one that is ok:  _k8s_namespace=!prod-* k8s_namespace=!test-* k8s_namespace=!sandbox-* k8s_container_name=!kubecost-network-costs *_

Using my logic only the things in bold should be alerted: 

-Namespace: prod-AA
--Pods: 
  -PodA(containerA1,ContainerA2)
  -PodB(containerB1,ContainerB2)

-Namespace: test-BB
--Pods:
  -Pod1(container11,Container12)
  -Pod2(container21,Container22)

Namespace: kubecost
--Pods: 
  -kubecost-network-costs-4mznh   (kubecost-network-costs)       
  **- kubecost-cost-analyzer (cost-analyzer-frontend|cost-model)**
  **- kubecost-grafana-89dbd544 (Grafana)**

**Namespace: lorem**
**--Pods:**
**- Grafana(grafana)** 
**- myapp(javaapp)**
**- infrapp (pythonapp)**

**Comment by ilyam8** [comment] 2023-12-05 12:52
> Using my logic only the things in bold should be alerted:

Unfortunately, it doesn't work like that. As I mentioned in my previous posts the logic is: 

- positive match returns `true`
- negative (`!`) match returns `false`
- overall it is :`(label1=val1 OR label1=val2) OR (label2=val1 OR label2=val2)`
- overall `true` means select, and `false` means filter out.


Let's take this example

```
k8s_namespace=!prod-* k8s_namespace=!test-* k8s_namespace=!sandbox-* *
k8s_container_name=!kubecost-network-costs *
```

It will select all containers with names != `kubecost-network-costs`, the `k8s_namespace` filter doesn't matter because there is OR between `k8s_namespace` and `k8s_container_name`.

**Comment by ilyam8** [comment] 2023-12-22 00:10
Duplicate of #15203

**Closed by ilyam8** 2023-12-22 00:10 UTC
Labels: bug, needs triage
