### ISSUE TITLE
[Feat]: Support for user-selectable compression parameters for dbengine.

### ISSUE THREAD

**Issue by Ferroin** [netdata/netdata#12473] opened 2022-03-21 12:23 UTC
### Problem

Currently, we only use LZ4 in a single, specific operational mode for compressing metrics data in the dbengine. This assumes a particular trade-off between CPU utilization and I/O, but for some users it may be desirable to either reduce CPU utilization even further at the expense of increased I/O, or reduce I/O even further at the expense of CPU utilization.

### Description

I propose adding support for users to select a different compression algorithm as part of runtime configuration. Users who want to minimize CPU usage can then select a lower compression level, while those who wish to minimize I/O can select a higher compression level.

### Importance

nice to have

### Value proposition

1. On systems where CPU time is cheap but I/O is expensive (for example, some file servers), users can prioritize minimizing the amount of IO generated by Netdata.
2. Conversely, on systems where CPU time is expensive, but I/O is cheap (for example, systems running computationally intensive workloads), users can prioritize minimizing the amount of CPU time Netdata spends on storing metrics.
3. Users who don’t care about CPU usage at all but want to cram as many metrics as possible into a fixed amount of disk space can crank the compression up to higher levels to do so.

### Proposed implementation

At a high level, my suggestion is to add a new option in `netdata.conf` under the `[global]` section, probably named `dbengine compression`. Initially, supported values for this could be:

- `default`: Use the current behavior.
- `lz4`: Use LZ4 in fast mode.
- `lz4hc`: Use LZ4 in high-compression mode.
- `none`: Use no compression (for users who can’t afford _any_ CPU overhead but have no such issues with I/O, or for users who want to use transparent compression in the filesystem instead of whatever compression Netdata provides).

Long-term, we could add other compression algorithms here, such as [zstd](http://facebook.github.io/zstd/) (which can, on it’s fastest settings, almost match LZ4 in terms of compression speed with a marginally better compression ratio, and on it’s default settings can achieve compression ratios equivalent to zlib with a compression speed roughly 2/3 that of LZ4).

**Comment by ilyam8** [comment] 2023-12-29 22:41
Duplicate of #14128

**Closed by ilyam8** 2023-12-29 22:41 UTC
Labels: duplicate, feature request, area/database
