### ISSUE TITLE
.deb package fails to install in Debian 9.11

### ISSUE THREAD

**Issue by thiagoftsm** [netdata/netdata#7131] opened 2019-10-18 13:43 UTC
##### Bug report summary
During my tests with the PR #7118 , I verified that during the installation process I always received the following error:

![VirtualBox_Debian9_18_10_2019_13_02_40](https://user-images.githubusercontent.com/49162938/67099009-b54e7e80-f1ac-11e9-9c6d-d8b81807107e.png)

I also verified that this is an error that we are having since version 1.18.0 as it is possible to see in the installation process of the previous version:

![VirtualBox_Debian9_18_10_2019_13_36_36](https://user-images.githubusercontent.com/49162938/67099111-dca54b80-f1ac-11e9-8e4b-4c0855cdfcbf.png)

I had compiled netdata before to install the packages, and I thought this could be a problem with files present on the system, but after to remove the previous files and try to install again the error persisted. 
##### OS / Environment
Debian 9.11
##### Netdata version (ouput of `netdata -V`)
Version 1.18.0 and 1.18.1
##### Component Name
Packaging
##### Steps To Reproduce
Install the debian packages
##### Expected behavior
Do not have errors during the installation.

**Comment by Ferroin** [comment] 2020-03-05 21:37
I can't reproduce this in a clean Debian 9 container. Closing for now, please comment if it's still an issue.

**Closed by Ferroin** 2020-03-05 21:37 UTC
Labels: area/packaging, bug
