### ISSUE TITLE
[Bug]: FreeIPMI plugin caused system lockup?

### ISSUE THREAD

**Issue by AGI-chandler** [netdata/netdata#14278] opened 2023-01-16 17:58 UTC
### Bug description

I've been going through my systems and installing the FreeIPMI plugin.  I've had success so far with about 3 machines.  However, after installing `netdata-plugin-freeipmi` package (Version 1.37.1, Release 1.el8, Architecture x86_64) and restarting `netdata.service`, the system froze.  I had to send a reset command through the IPMI to get it booted up again.  

The last info logged by netdata was in the error.log:
```
2023-01-15 23:41:53: netdata INFO  : PLUGINSD[freeipmi] : thread created with task id 877892
2023-01-15 23:41:53: netdata INFO  : PLUGINSD[freeipmi] : set name of thread 877892 to PLUGINSD[freeip
2023-01-15 23:41:53: netdata INFO  : PLUGINSD[freeipmi] : connected to '/usr/libexec/netdata/plugins.d/freeipmi.plugin' running on pid 877893
2023-01-15 23:41:53: freeipmi.plugin ERROR : MAIN : update frequency 1 seconds is too small for IPMI. Using 5.
```

and this was recorded in the System Event Log (SEL):
```
533 | 01/15/2023 | 23:43:13 | OS Critical Stop #0x46 | Run-time critical stop () | Asserted
534 | Linux kernel panic: Fatal excep
535 | Linux kernel panic: tion
```

I'm not sure where it got `update frequency 1 seconds` from, or even the replacement value of `5`, since this is all I added to `netdata.conf`:
```
[plugin:freeipmi]
    update every = 10
    command options =
```

Could polling the IPMI every 5 seconds cause this critical stop and kernel panic??

After rebooting, all is working fine and the IPMI is being polled every 10 seconds.

### Expected behavior

System doesn't freeze or lock up after starting freeipmi.plugin

### Steps to reproduce

1. `yum install netdata-plugin-freeipmi`
2. Append to `/etc/netdata/netdata.conf`:
```
[plugin:freeipmi]
    update every = 10
    command options =
```
3. `systemctl daemon-reload`
4. `systemctl restart netdata.service`
...

### Installation method

kickstart.sh

### System info

```shell
Linux EagI 4.18.0-305.25.1.el8_4.x86_64 #1 SMP Wed Nov 3 10:29:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 8.4.2105
/etc/cm-release:Cluster Manager v9.0
/etc/cm-release:master
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="8"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="8"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="CentOS Linux 8"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:8"
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-8"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="8"
/etc/redhat-release:CentOS Linux release 8.4.2105
/etc/system-release:CentOS Linux release 8.4.2105
```

### Netdata build info

```shell
Version: netdata v1.37.1
Configure options:  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--datadir=/usr/share' '--includedir=/usr/include' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-dependency-tracking' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Install type: binpkg-rpm
    Binary architecture: x86_64
    Packaging distro:  
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         NO
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

**Comment by MrZammler** [comment] 2023-01-24 14:35
Hi @AGI-chandler thank you for the report.

We will try to reproduce the issue. Has it occurred again after that time?

**Comment by AGI-chandler** [comment] 2023-01-24 17:32
@MrZammler So far, so good!

**Comment by MrZammler** [comment] 2023-02-07 14:21
Hi @AGI-chandler . I'm guessing it still runs ok ? Can't reproduce this, seems a really weird issue. I'll close this for now, to be honest can't really tie it to netdata 100%. We will check though for sure if we see any indication of this happening again.

**Closed** 2023-02-07 14:22 UTC
Labels: bug, needs triage

**Comment by AGI-chandler** [comment] 2023-02-07 17:08
@MrZammler Ah hehe what timing!&nbsp; Actually this morning with 1.38 update released, system froze again and in researching the system logs, last info logged at the time connection to the system was lost were in `/var/log/dnf.librepo.log`:
```
2023-02-07T04:40:17-0700 INFO Downloading: https://repo.netdata.cloud/repos/stable/el/8/x86_64/netdata-plugin-freeipmi-1.38.0-1.el8.x86_64.rpm
```
<details><summary>In <code>/var/log/dnf.log</code>:</summary>

```
2023-02-07T04:40:17-0700 DEBUG --> Starting dependency resolution
2023-02-07T04:40:17-0700 DEBUG ---> Package netdata.x86_64 1.37.1-1.el8 will be upgraded
2023-02-07T04:40:17-0700 DEBUG ---> Package netdata.x86_64 1.38.0-1.el8 will be an upgrade
2023-02-07T04:40:17-0700 DEBUG ---> Package netdata-plugin-freeipmi.x86_64 1.37.1-1.el8 will be upgraded
2023-02-07T04:40:17-0700 DEBUG ---> Package netdata-plugin-freeipmi.x86_64 1.38.0-1.el8 will be an upgrade
2023-02-07T04:40:17-0700 DEBUG --> Finished dependency resolution
2023-02-07T04:40:17-0700 DDEBUG timer: depsolve: 658 ms
2023-02-07T04:40:17-0700 INFO Dependencies resolved.
2023-02-07T04:40:17-0700 INFO ================================================================================
 Package                      Arch        Version            Repository    Size
================================================================================
Upgrading:
 netdata                      x86_64      1.38.0-1.el8       netdata       41 M
 netdata-plugin-freeipmi      x86_64      1.38.0-1.el8       netdata      839 k

Transaction Summary
================================================================================
Upgrade  2 Packages

2023-02-07T04:40:17-0700 INFO Total download size: 42 M
2023-02-07T04:40:17-0700 INFO Downloading Packages:
2023-02-07T04:40:19-0700 INFO --------------------------------------------------------------------------------
2023-02-07T04:40:19-0700 INFO Total                                            20 MB/s |  42 MB     00:02     
2023-02-07T04:40:19-0700 INFO Running transaction check
2023-02-07T04:40:20-0700 INFO Transaction check succeeded.
2023-02-07T04:40:20-0700 INFO Running transaction test
2023-02-07T04:40:20-0700 INFO Transaction test succeeded.
2023-02-07T04:40:20-0700 DDEBUG timer: transaction test: 824 ms
2023-02-07T04:40:20-0700 INFO Running transaction
2023-02-07T04:40:20-0700 DDEBUG RPM transaction start.
```

</details>

The BMC SEL (System Event Log) contains (from `ipmitool`):
```
  1 | 02/07/2023 | 04:40:35 | OS Critical Stop #0x46 | Run-time critical stop () | Asserted
  2 | Linux kernel panic: Fatal excep
  3 | Linux kernel panic: tion
```
The exported messages from the BMC itself are:
```
1,Critical,2023/02/07 04:40:35,OS Stop/Shutdown(FAN6),runtime critical stop (a.k.a. core dump, blue screen) - Assertion
2,Information,,OS Stop/Shutdown, - Assertion
3,Information,,Others, - Assertion
```

However, FAN6 sensor status in the BMC is "Normal"

Resetting the system through the BMC and booting up... OK
netdata service is masked...
`/lib/systemd/system/netdata.service` is an empty file...
Attempting to reinstall `netdata` and `netdata-plugin-freeipmi` with yum/dnf... I get this message:
```
Package netdata-1.37.1-1.el8.x86_64 is already installed.
Package netdata-1.38.0-1.el8.x86_64 is already installed.
```
Attempting to remove netdata first...
```
Removed:
  netdata-1.37.1-1.el8.x86_64          netdata-1.38.0-1.el8.x86_64          netdata-plugin-freeipmi-1.38.0-1.el8.x86_64          protobuf-3.5.0-13.el8.x86_64         

Complete!
```
Attempting to install netdata...
```
Created symlink /etc/systemd/system/multi-user.target.wants/netdata.service -> /usr/lib/systemd/system/netdata.service.
Installed:
  netdata-1.38.0-1.el8.x86_64                                                        protobuf-3.5.0-13.el8.x86_64                                                       

Complete!
```
netdata is now running and I can see the instance on app.netdata.cloud.

```
# diff /etc/netdata/netdata.conf*
19a20,22
> [plugin:freeipmi]
>     update every = 10
>     command options =
# 
```
Restoring the `/etc/netdata/netdata.conf.rpmsave` and reloading/restarting netdata... OK
Attempting to install `netdata-plugin-freeipmi`...
```
Installed:
  netdata-plugin-freeipmi-1.38.0-1.el8.x86_64                                                                                                                           

Complete!
```
reloading/restarting netdata... OK
IPMI readings now showing up on app.netdata.cloud.
No other issues observed, system appears back to normal.
