### ISSUE TITLE
Reduce false positive notifications on boot

### ISSUE THREAD

**Issue by mailme-gx** [netdata/netdata#7217] opened 2019-10-29 05:13 UTC
### Intro
I found no forum/user group so I resolved to posting a question here

#### Summary
When a system is rebooted many notifications are sent

### Detailed description
We have 10+ virtual machines running on a server 3 each with a netdata instance. 
When the Physical hardware (host) is rebooted it calls a shutdown and then startup of each vm.
When a vm is restarting we get many notifications (first critical then recovered) such as (seeming any number of the below inconsistently)

disk_backlog.sda
disk_util.sda
disk_inodes._dev_shm
disk_space._dev_shm
system.swapio
ipv4.tcphandshake
ipv4.udperrors

Is no one else affected or annoyed with this functionality, is there some sort of misconfiguration?
Is there a way to prevent notifications during shutdown/startup of the system?

I do apologise if this is a duplicate issue, I did try check for a similar issue bot found nothing relevant.

Since this is running on multiple hosts I will focus on the most common:
netdata v1.18.1
os: Arch linux 
kernel: 5.7.3

**Comment by vlvkobal** [comment] 2019-10-29 07:43
Related: #4962, #5297

**Comment by mfundul** [comment] 2019-10-30 10:11
Closing as duplicate of #4962

**Closed by mfundul** 2019-10-30 10:11 UTC
Labels: area/database, bug
