### ISSUE TITLE
IPMI values missing or reports incorrect values

### ISSUE THREAD

**Issue by imily999** [netdata/netdata#9981] opened 2020-09-23 15:05 UTC
##### Bug report summary

Sensors portion is missing fan data, even though ipmitools returns fan speed as percentage. The voltages measured are also way off, unless I somehow created a flux capacitor. 

![Screenshot_20200923-104755](https://user-images.githubusercontent.com/52512586/94030474-da1f7e80-fd8b-11ea-9b13-765d15beb8c5.png)

##### OS / Environment
Archlinux as a Docker container. Docker 2.0.
Machine is HP Proliant ML10v2

##### Netdata version

netdata v1.25.0-48-g83c0121c

##### Steps To Reproduce
Enabled ipmi and reported values were either missing or way off.

**Comment by OdysLam** [comment] 2020-09-23 18:48
Hey @imily999,

You are not nearly close to [1.21 GIGAWATTS](https://www.youtube.com/watch?v=I5cYgRnfFDA&ab_channel=SabrinaPaula), which are required by the flux capacitor, but you are getting close!

Jokes aside welcome to our community! One of our engineers will respond shortly. Just to make sure, can you see the correct voltages using another tool which gathers data from the same data source? 

E.g for nginx, we scrub data from the `/stub` endpoint.

Cheers!

**Comment by imily999** [comment] 2020-09-24 14:03
Ok! So I think the issue is more with the freeipmi plugin not being able to run, so it's only pulling from lm-sensors, which is where those values are reported. Here's the netdata log from docker when trying to start-up the freeipmi plugin

2020-09-24 14:01:34: netdata INFO  : PLUGINSD[freeipmi] : thread created with task id 144


2020-09-24 14:01:34: netdata INFO  : PLUGINSD[freeipmi] : set name of thread 144 to PLUGINSD[freeip


2020-09-24 14:01:35: netdata INFO  : PLUGINSD[freeipmi] : connected to '/usr/libexec/netdata/plugins.d/freeipmi.plugin' running on pid 166


2020-09-24 14:01:35: freeipmi.plugin ERROR : MAIN : ipmi_monitoring_sensor_readings_by_record_id(): internal system error (errno 2, No such file or directory)


2020-09-24 14:01:35: freeipmi.plugin FATAL : MAIN : freeipmi.plugin: data collection failed. # : Invalid argument

**Comment by OdysLam** [comment] 2020-09-25 07:41
@ilyam8, it seems that the plugin does not have access to a file that it is required. Should we mount that file into the docker container?

@imily999, did you follow the instructions here https://learn.netdata.cloud/docs/agent/collectors/freeipmi.plugin ?

**Comment by ilyam8** [comment] 2020-09-25 11:29
@vlvkobal please take a look

**Comment by Saruspete** [comment] 2020-10-01 08:19
Hello @imily999 ,

Can you give the output of the following commands (if they work / bin is available)
```
sudo ipmimonitoring
sudo ipmitool sensor
ls -al /dev/ipmi*
```

**Comment by orgoj** [comment] 2020-12-11 09:09
On our server fan is missing too. Values are in percent.

/usr/libexec/netdata/plugins.d/freeipmi.plugin 5 debug:

> Allocating new sensor data record for sensor '', id 0, number 0, type 65535, state 3, units 255, reading_type 255
Unknown reading type - Ignoring sensor record for sensor '', id 0, number 0, type 65535, state 3, units 255, reading_type 255
Allocating new sensor data record for sensor 'UID Light', id 1, number 1, type 192, state 3, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'UID Light', id 1, number 1, type 192, state 3, units 0, reading_type 255
Allocating new sensor data record for sensor 'Int. Health LED', id 2, number 2, type 192, state 3, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Int. Health LED', id 2, number 2, type 192, state 3, units 0, reading_type 255
Allocating new sensor data record for sensor 'Ext. Health LED', id 3, number 3, type 192, state 3, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Ext. Health LED', id 3, number 3, type 192, state 3, units 0, reading_type 255
Allocating new sensor data record for sensor 'Power Supply 1', id 4, number 4, type 8, state 3, units 255, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Power Supply 1', id 4, number 4, type 8, state 3, units 255, reading_type 255
Allocating new sensor data record for sensor 'Power Supply 2', id 5, number 5, type 8, state 0, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Power Supply 2', id 5, number 5, type 8, state 0, units 0, reading_type 255
Allocating new sensor data record for sensor 'Power Supplies', id 6, number 6, type 8, state 2, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Power Supplies', id 6, number 6, type 8, state 2, units 0, reading_type 255
Allocating new sensor data record for sensor '', id 7, number 0, type 65535, state 3, units 255, reading_type 255
Unknown reading type - Ignoring sensor record for sensor '', id 7, number 0, type 65535, state 3, units 255, reading_type 255
Allocating new sensor data record for sensor 'Fan 1', id 8, number 7, type 4, state 0, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Fan 1', id 8, number 7, type 4, state 0, units 0, reading_type 255
Allocating new sensor data record for sensor 'Fan 2', id 9, number 8, type 4, state 0, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Fan 2', id 9, number 8, type 4, state 0, units 0, reading_type 255
Allocating new sensor data record for sensor 'Fan 3', id 10, number 9, type 4, state 0, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Fan 3', id 10, number 9, type 4, state 0, units 0, reading_type 255
Allocating new sensor data record for sensor 'Fan 4', id 11, number 10, type 4, state 0, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Fan 4', id 11, number 10, type 4, state 0, units 0, reading_type 255
Allocating new sensor data record for sensor 'Fans', id 12, number 11, type 4, state 0, units 0, reading_type 255
Unknown reading type - Ignoring sensor record for sensor 'Fans', id 12, number 11, type 4, state 0, units 0, reading_type 255
Allocating new sensor data record for sensor '', id 13, number 0, type 65535, state 3, units 255, reading_type 255
Unknown reading type - Ignoring sensor record for sensor '', id 13, number 0, type 65535, state 3, units 255, reading_type 255

# ipmitool sensor
> UID Light        | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na        
Int. Health LED  | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na        
Ext. Health LED  | 0x0        | discrete   | 0x0080| na        | na        | na        | na        | na        | na        
Power Supply 1   | na         | discrete   | na    | na        | na        | na        | na        | na        | na        
Power Supply 2   | 170        | Watts      | ok    | na        | na        | na        | na        | na        | na        
Power Supplies   | 0x0        | discrete   | 0x0880| na        | na        | na        | na        | na        | na        
Fan 1            | 21.560     | percent    | ok    | na        | na        | na        | na        | na        | na        
Fan 2            | 21.560     | percent    | ok    | na        | na        | na        | na        | na        | na        
Fan 3            | 26.264     | percent    | ok    | na        | na        | na        | na        | na        | na        
Fan 4            | 26.264     | percent    | ok    | na        | na        | na        | na        | na        | na        
Fans             | 0          | percent    | ok    | na        | na        | na        | na        | na        | na        
Temp 1           | 27.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 40.000    | 42.000    | 46.000    
Temp 2           | 40.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 82.000    | 83.000    
Temp 3           | 40.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 82.000    | 83.000    
Temp 4           | 49.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 5           | 35.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 6           | 36.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 7           | 36.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 8           | 43.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 9           | 38.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 10          | 40.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 11          | 43.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 12          | 39.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 68.000    | 73.000    
Temp 13          | 39.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 68.000    | 73.000    
Temp 14          | 37.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 68.000    | 73.000    
Temp 15          | 35.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 68.000    | 73.000    
Temp 16          | 33.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 68.000    | 73.000    
Temp 17          | 32.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 68.000    | 73.000    
Temp 18          | 32.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 68.000    | 73.000    
Temp 19          | 33.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 20          | 38.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 21          | 45.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 60.000    | 65.000    
Temp 22          | 60.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 110.000   | 115.000   
Temp 23          | 45.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Temp 24          | 41.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 0.000     | 87.000    | 92.000    
Power Meter      | 150        | Watts      | ok    | na        | na        | na        | na        | na        | na        
Memory           | 0x0        | discrete   | 0x4180| na        | na        | na        | na        | na        | na

**Comment by Saruspete** [comment] 2020-12-11 11:14
@orgoj from [freeipmi headers](https://github.com/chu11/freeipmi-mirror/blob/b780823d549c9673411adc9d8d655d49628be4aa/libipmimonitoring/ipmi_monitoring.h.in#L185-L192), the `reading_type 255` is `IPMI_MONITORING_SENSOR_READING_TYPE_UNKNOWN`, which yields the "Unkown reading type".

I would tend to say it's an issue to be addressed by your firmware vendor, as this "unknown" type should not be acceptable (altough ipmitool [defaults to Float, 3 digits precision](https://github.com/ipmitool/ipmitool/blob/master/lib/ipmi_sensor.c#L910) for all of its values). 

The main issue is: If we add the unknown type, it'll also include many many many sensors that are events / bool values not meant to be graphed.

Maybe we should rather add more configuration to the collector, so we can specify more custom / specific values and processing ?

**Comment by orgoj** [comment] 2020-12-11 20:36
OS is Ubuntu 16.04. Netdata use libipmimonitoring-dev which end in libfreeipmi16. Ipmitools default use openipmi project. Freeipmi sensors command-line tools is ipmi-sensors, which in default in default don't show fan speed. It require to use workaround on my server.

> root@l1:~# ipmi-sensors -r 8
ID | Name  | Type | Reading    | Units | Event
8  | Fan 1 | Fan  | N/A        | N/A   | 'transition to Running'
root@l1:~# ipmi-sensors -r 8 -W discretereading
ID | Name  | Type | Reading    | Units | Event
8  | Fan 1 | Fan  | 21.56      | %     | 'transition to Running'

I searching how to define workaround for libipmimonitoring.

**Comment by orgoj** [comment] 2020-12-11 21:52
I found discrete reading flag enabled in netdata. This may be error in libipmimonitoring

> FreeIPMI 1.6.3 - 01/23/19
   30 o Fix DISCRETE_READING workaround in libipmimonitoring.

Ubuntu 16.04 have libipmimonitoring version 1.4.x

**Comment by Saruspete** [comment] 2020-12-12 14:25
The "discrete_reading" of the ipmi-sensors is doing what I said : it ignores the filtering of "unknown" fields.
It's in [ipmi_monitoring.h](https://github.com/chu11/freeipmi-mirror/blob/b780823d549c9673411adc9d8d655d49628be4aa/libipmimonitoring/ipmi_monitoring.h.in#L288-L292) and the comment matches my concerns : 

>  DISCRETE_READING - Allow sensor readings to be read even if the event/reading type
>                     code for the sensor is not valid.  This option works around
>                     poorly defined (and arguably illegal) SDR records that list
>                     non-discrete sensor expectations along with discrete state
>                     conditions.

So, it's clearly not something to be changed by default. On my Dell servers, it would add more than 30 dimensions that should not be added.

The workaround is simple: in the [default](https://github.com/netdata/netdata/blob/master/collectors/freeipmi.plugin/freeipmi_plugin.c#L755-L759) case, add a test to compare the sensor ID with a list in configuration, and force it to be rendered instead of being ignored.

**Comment by ilyam8** [comment] 2021-08-31 14:44
Closing this as "wontfix", because, as @Saruspete [correctly mentioned](https://github.com/netdata/netdata/issues/9981#issuecomment-743133964), the default behaviour of the `freeipmi` plugin is correct and the problem is likely with the firmware.

If someone wants to make a PR with [the suggested workaround](https://github.com/netdata/netdata/issues/9981#issuecomment-743763727) - feel free to do.

**Closed by ilyam8** 2021-08-31 14:44 UTC
Labels: bug, needs triage
