### ISSUE TITLE
Netdata causing load average increase every ~20 minutes

### ISSUE THREAD

**Issue by Daniel15** [netdata/netdata#5234] opened 2019-01-21 00:39 UTC
##### Bug report summary
I noticed on two of my servers that the load average was increasing approximately every 20 minutes:
![](https://d.sb/2019/01/vps03_netdata_dashboard_-_Mozilla_Firefox_17-22.47.36.png)

I suspected a cronjob, but I don't have any cronjobs that run every 20 mins. However, CPU usage doesn't actually increase during that period:
![](http://d.sb/2019/01/vps03_netdata_dashboard_-_Mozilla_Firefox_17-22.47.53.png)

I did some digging and it took a long time to work out what was happening.

Linux updates the load average every 5 seconds. In fact, it actually updates every 5 seconds plus one "tick"

[sched/loadavg.h](https://github.com/torvalds/linux/blob/v4.18/include/linux/sched/loadavg.h#L20):
```
#define LOAD_FREQ	(5*HZ+1) /* 5 sec intervals */
```
[sched/loadavg.c](https://github.com/torvalds/linux/blob/345671ea0f9258f410eb057b9ced9cefbbe5dc78/kernel/sched/loadavg.c#L12-L26)
```
 * The global load average is an exponentially decaying average of nr_running +
 * nr_uninterruptible.
 *
 * Once every LOAD_FREQ:
 *
 *   nr_active = 0;
 *   for_each_possible_cpu(cpu)
 *	nr_active += cpu_of(cpu)->nr_running + cpu_of(cpu)->nr_uninterruptible;
 *
 *   avenrun[n] = avenrun[0] * exp_n + nr_active * (1 - exp_n)
```

`HZ` is the kernel timer frequency, which is defined when compiling the kernel. On my system, it's `250`:
```
% grep "CONFIG_HZ=" /boot/config-$(uname -r)
CONFIG_HZ=250
```

This means that every 5.004 seconds (5 + 1/250), Linux calculates the load average. It checks how many processes are actively running plus how many processes are in uninterruptable wait (eg. waiting for disk IO) states, and uses that to compute the load average, smoothing it exponentially over time.

Say you have a process that starts a bunch of subprocesses every second. For example, Netdata collecting data from some apps. Normally, the process will be very fast and won't overlap with the load average check, so everything is fine. However, every 1251 seconds (5.004 * 250), the load average update interval will be an exact multiple of one second (that is, 1251 is the least common multiple of 5.004 and 1). 1251 seconds is 20.85 minutes, which is exactly the interval I was seeing the load average increase. My educated guess here is that every 20.85 minutes, Linux is checking the load average at the exact time that several processes are being started and are in the queue to run.

I confirmed this by disabling netdata and manually watching the load average:
```
while true; do uptime; sleep 5; done
```
After 1.5 hours, I did not see **any** similar spikes. The spikes **only** occur when Netdata is running.

It turns out other people have hit similar issues in the past, albeit with different intervals. The following posts were extremely helpful:
 - [Investigation of regular high load on unused machines every 7 hours](https://blog.avast.com/investigation-of-regular-high-load-on-unused-machines-every-7-hours)
 - [Understanding why the Linux loadavg rises every 7 hours](https://mackerel.io/blog/entry/tech/high-loadavg-every-7-hours)
 - [Telegraf - high load average every 1h 45m](https://github.com/influxdata/telegraf/issues/3465)
 - [Linux commit that changed load average calculation to be every 5 seconds + 1 tick, instead of exactly every 5 seconds](https://github.com/torvalds/linux/commit/0c2043abefacac97b6d01129c1123a466c95b7c1)

In the end, I'm not sure if I'd call this a bug, but perhaps netdata could implement some jitter so that it doesn't perform checks every one second exactly.

##### OS / Environment
Debian buster

##### Netdata version (ouput of `netdata -V`)
```
netdata v1.12.0-rc2-51-nightly
```

##### Component Name
N/A

**Comment by cakrit** [comment] 2019-01-21 12:04
I wrote a small script to calculate exactly when we would expect the same condition to occur based on the polling period and the kernel frequency. The results are [here](https://docs.google.com/spreadsheets/d/1WUOeTzeTEmLL8CPPCUgJLYRMhj9NLIRIVm03Nrmw9p8/edit?usp=sharing). It's impossible to replicate on my Manjaro which has `CONFIG_HZ=300`, will try to see it on a VM that has `CONFIG_HZ=1000`. Expected period to see the spike will be 16min, 40sec, for a poll period of 1sec.

If anyone wants to redo the calculations to find the minimum period for a different frequency, the script it's this:
```
#!/bin/bash

for hz in 100 200 250 1000; do
 echo "Freq=$hz"
 timer=$(echo "scale=5;5+1/$hz" | bc)
 echo "timer=$timer"
  for poll in 1 2 3 4 5 6 7 8 9 10; do
    i=1
    while [ $i -lt 86401 ] ; do
        if [ $(echo "($timer*$i)%$poll>0" | bc) -eq 0 ] ; then
                echo "$i"
                break
        fi
        i=$((i+1))
    done
 done
done
```

**Comment by mfundul** [comment] 2019-01-21 14:53
Well, if netdata really is doing CPU work the load average is kind of accurate. One idea is to scatter thread scheduling in netdata so that not everything wakes up at once.

**Comment by Ferroin** [comment] 2019-01-21 15:10
Confirmed that it's correlated to collection by netdata, I'm not seeing any such spikes on systems that have only a few collectors and almost nothing that triggers new process creation.

I think adding some jitter to the data collection probably is the best option here, though I really don't know what to suggest for the range of jitter.

**Comment by cakrit** [comment] 2019-01-21 15:50
A random jitter wouldn't help, it would make things worse. At least know the occurence is predictable and very well documented on the mackerel link @Daniel15 provided. Ideally, we would take the polling period and CONFIG_HZ and be able to predictably add a 1ms delay once every X sec, where X is the time window from one artificial spike to the next. The only other (simpler) alternative I can think of, is to sample twice before sending the information (sample, wait 1msec, sample again). Presumably, the two values would be significantly different only at these points, so we could throw away the artificially high value.

**Comment by mfundul** [comment] 2019-01-21 15:56
CONFIG_HZ hacks are only valid for linux. There is also the so called race-to-idle approach in doing things, meaning that you may even want the data collectors to run concurrently and quickly so as to improve the power efficiency of the system. I like the idea of sampling the load average twice though.

**Comment by cakrit** [comment] 2019-01-22 10:05
Of course @Daniel15, you're too kind, what I wrote was a bit idiotic. :-)
I updated the sheet to use LCM and you can just play with the inputs. Unfortunately LCM works only for integers, so you'll see that for freq 300Hz, the cycles are not exact, but the time still shows up as an integer. 

It looks like anything we could do on the netdata side would be very involved. Unless someone can suggest an algorithm that predictably avoids this issue, my only suggestion would be to use CONFIG_HZ=300, which at least in theory wouldn't have a least common multiplier with integer polling periods. In practice there's always rounding, so you can't avoid it unless if you're explicitly introducing a delay at the right moment. 

Regarding possibilities for such an algorithm, I don't know if `/proc/timer_list` can help at all, I don't know what I'm reading there.

**Comment by mfundul** [comment] 2019-01-22 10:11
The issue is inflating the load average, but even if it can be avoided maybe the trade-off is not worth it. Even if netdata threads are uniformly distributed in a time slice that leaves the system less time to go to deep sleep states.

**Comment by Daniel15** [comment] 2019-01-22 19:38
>  Unless someone can suggest an algorithm that predictably avoids this issue

Could it check the value of `CONFIG_HZ` in `/boot/config-$(uname -r)`? That might not work for all Linux distros, but it's there for Debian at least. I did read something about `getconf CLK_TCK`, but that returns `100` for me, so I guess it's something else.

> Even if netdata threads are uniformly distributed in a large enough time slice that leaves the system less time to go to deep sleep states.

It would still be good to have the option for it. Right now, Netdata shows that my server has a large load spike every 20 minutes, but it's really just an artificial thing. I'd like to able to configure alarms without this artificial load influencing them.

I'm not sure if virtualized servers even go into deep sleep states?

> It looks like anything we could do on the netdata side would be very involved

For what it's worth, Telegraf supports jitter, which could be used to make the issue less likely to occur:

> collection_jitter: Collection jitter is used to jitter the collection by a random interval. Each plugin will sleep for a random time within jitter before collecting. This can be used to avoid many plugins querying things like sysfs at the same time, which can have a measurable effect on the system.
https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent
https://github.com/influxdata/telegraf/issues/3465

**Comment by cakrit** [comment] 2019-01-23 12:52
Ok, so it's a random jitter **per plugin**, up to the cofigured maximum, which means that they will be collecting at slightly different offsets each time. This could work, with the caveat that we're already collecting per sec and going towards msec, so it's a little different than what telegraf does. 
@ilyam8 and @vlvkobal is this something we could add easily? @ktsaou what do you think?

**Comment by ktsaou** [comment] 2019-01-23 14:08
We could add an jitter. Is that a big deal.
But have you actually verified this is the case?

What I would like to know if this is triggered by the netdata daemon or the external plugins, or all of them.

If this is triggered by netdata daemon (internal data collection plugins), they all use the heartbeat functions https://github.com/netdata/netdata/blob/f739ab110b21c0d13d67569810302d36bd635746/libnetdata/clocks/clocks.c#L118-L150

A simple offset there could solve the problem.

It may also be triggered by `apps.plugin` which also more resource hungry than anything else. This will also be influenced by the heartbeat functions.

So, can we test this?

**Comment by Ferroin** [comment] 2019-01-23 14:44
@ktsaou I think it's probably a cumulative thing.  Stuff that actually has to spawn a command to get data (the postfix module for example) is almost certainly the biggest offender, but _everything_ that is waking up to fetch data is almost certainly contributing at least a little.

**Comment by paulkatsoulakis** [comment] 2019-02-27 20:13
I am still not familiar enough with the implementation, but something that keeps around on my mind while i was digesting the feedback on this issue:

Given we are focusing on 1s measurements, adding random jitters across the collectors wouldn't risk messing up correlation using time for the various events across the different metrics? Shouldn't sampling across the different collectors be as close as possible?

**Comment by XxLilBoPeepsxX** [comment] 2020-10-03 16:43
I know this is an old issue, but since it is still open, and I am having the same issue now, currently in 2020, I thought it would be worthwhile to mention that I am having severe bottlenecking occur shortly before my server stops serving my website and subdomain-hosted websites for usually around an hour, due to netdata. I'm on ubuntu server 18.04. Has any additional progress been made in this issue, towards a potential workaround or patch? I'm using the latest version of netdata cloud, on the nightly build. Any help would be greatly appreciated, I'm a huge fan of Netdata, I would prefer to continue to use your tool, but if this issue keeps occurring I don't think I will be able to continue using it.

**Comment by Daniel15** [comment] 2020-10-03 17:16
@XxLilBoPeepsxX This issue isn't about *actual* load caused by Netdata; rather it's about artificial load due to how Linux measures load average. If you're encountering actual issues due to Netdata then I'd suggest opening a separate issue, as it's unrelated to this one.

**Comment by XxLilBoPeepsxX** [comment] 2020-10-03 17:21
@Daniel15 will do, thank you, my apologies for commenting on the wrong issue

**Comment by ilyam8** [comment] 2021-08-05 12:26
Closing this issue since it is a discussion and [not a problem caused by Netdata](https://github.com/netdata/netdata/issues/5234#issuecomment-703135543).

@XxLilBoPeepsxX consider opening a new issue.

**Closed by ilyam8** 2021-08-05 12:26 UTC
Labels: area/daemon, monitoring discussion

**Comment by cyfdecyf** [comment] 2022-01-17 03:04
I see exactly the same periodic load averge spike on servers with short workload spike every one second. This issue discussion helped a lot in finding out the root cause. Thanks a lot!

I confirmed this with two tests:

1. Write a program to repeatedly read `/proc/loadavg` with below 1 second interval, use the forth field to get runnable and total kernel scheduling entities.
2. After seeing spikes within 1 second, change kernel `CONFIG_HZ` to a different value and see if the period of load average spike changes as expected.

I'm commenting this issue because I see periodic network latency spikes today. This remides me that **there are other kinds of peoridic spikes that maybe caused by sample point shift or spike point shift**. With 1 second interval of metrics, for short work load spike within 1 second, if the spike time point shifts within 1 second, I'm going to see this periodic spike.

One second metric interval is great, but still not enough if the spike is much less than one second.
