### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Millificent** [netdata/netdata#7966] opened 2020-02-03 21:24 UTC
##### Question summary

Receiving the following error

Press ENTER to run it >
yum install Judy-devel autoconf autoconf-archive autogen automake gcc libmnl-devel libuuid-devel libuv-devel lz4-devel make nmap-ncat openssl-devel python2 zlib-devel
Last metadata expiration check: 2:58:10 ago on Mon Feb  3 19:24:23 2020.
No match for argument: Judy-devel
No match for argument: autoconf-archive
No match for argument: autogen
No match for argument: libmnl-devel
No match for argument: libuv-devel
Error: Unable to find a match: Judy-devel autoconf-archive autogen libmnl-devel libuv-devel

We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues

##### OS / Environment

CentOS 8

**Comment by prologic** [comment] 2020-02-03 23:53
Duplicate of #6967 and fixed by #7890 and #7918 

Please help me test the fixes :) These PRs will be merged soon!

**Comment by prologic** [comment] 2020-02-03 23:54
See also comments in #7936

**Comment by prologic** [comment] 2020-02-11 21:15
Closing this issue as I believe it to be resolved. Please open a new issue if you are still facing problems with installing NetData on CentOS 8.x

**Closed by prologic** 2020-02-11 21:15 UTC
Labels: duplicate, no changelog, question

**Comment by Xplouder** [comment] 2020-02-20 15:03
@prologic i'm still facing problems:

` --- Fetching script to detect required packages... --- 
[/tmp/netdata-kickstart-ZuiI71]$ curl -sSL --connect-timeout 10 --retry 3 https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh 
 OK   
 --- Running downloaded script to detect required packages... --- 
 [/tmp/netdata-kickstart-ZuiI71]$ sudo /usr/bin/bash /tmp/netdata-kickstart-ZuiI71/install-required-packages.sh --dont-wait --non-interactive netdata-all 
Loading /etc/os-release ...
You should have EPEL enabled to install all the prerequisites.
Check: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/
Running in non-interactive mode
 > CentOS Version: 8 ...
 > Checking for epel ...
 > Checking for config-manager ...
 yum config-manager 
 > Checking for PowerTools ...
 yum repolist 
CentOS-8 - AppStream                             40 kB/s | 4.3 kB     00:00    
CentOS-8 - Base                                  39 kB/s | 3.8 kB     00:00    
CentOS-8 - Extras                                15 kB/s | 1.5 kB     00:00    
Docker CE Stable - x86_64                        59 kB/s | 3.5 kB     00:00    
Extra Packages for Enterprise Linux Modular 8 -  43 kB/s |  31 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64   28 kB/s |  17 kB     00:00    
Running in non-interactive mode, assuming yes (y)
 > Would have promptedfor PowerTools not found, shall I install it? ...
 yum -y config-manager --set-enabled PowerTools 
 > Checking for getpagespeed-extras ...
 yum repolist 
CentOS-8 - AppStream                             42 kB/s | 4.3 kB     00:00    
CentOS-8 - Base                                  41 kB/s | 3.8 kB     00:00    
CentOS-8 - Extras                                14 kB/s | 1.5 kB     00:00    
CentOS-8 - PowerTools                           5.9 MB/s | 2.0 MB     00:00    
Docker CE Stable - x86_64                        53 kB/s | 3.5 kB     00:00    
Extra Packages for Enterprise Linux Modular 8 -  48 kB/s |  31 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64   27 kB/s |  17 kB     00:00    
Running in non-interactive mode, assuming yes (y)
 > Would have promptedfor PowerTools not found, shall I install it? ...
 yum -y install https://extras.getpagespeed.com/release-el8-latest.rpm 
Searching for distro_sdk ...
Searching for git ...
 > Checking if package 'git' is installed...
 Searching for gcc ...
 > Checking if package 'gcc' is installed...
 Searching for make ...
 > Checking if package 'make' is installed...
 Searching for autoconf ...
 > Checking if package 'autoconf' is installed...
 Searching for autoconf_archive ...
 > Checking if package 'autoconf-archive' is installed...
 Searching for autogen ...
 > Checking if package 'autogen' is installed...
 Searching for automake ...
 > Checking if package 'automake' is installed...
 Searching for pkg_config ...
 > Checking if package 'pkgconfig' is installed...
 Searching for netcat ...
 > Checking if package 'nmap-ncat' is installed...
 Searching for libz_dev ...
 > Checking if package 'zlib-devel' is installed...
 Searching for libuuid_dev ...
 > Checking if package 'libuuid-devel' is installed...
 Searching for libmnl_dev ...
 > Checking if package 'libmnl-devel' is installed...
 Searching for lm_sensors ...
 > Checking if package 'lm_sensors' is installed...
 Searching for libuv ...
 > Checking if package 'libuv-devel' is installed...
 Searching for lz4 ...
 > Checking if package 'lz4-devel' is installed...
 Searching for openssl ...
 > Checking if package 'openssl-devel' is installed...
 Searching for judy ...
 > Checking if package 'Judy-devel' is installed...
 Searching for nodejs ...
 > Checking if package 'nodejs' is installed...
 Searching for python_pymongo ...
WARNING
package python-pymongo is not available in this system.
You may try to install without it.
Searching for python_mysqldb ...
 > Checking if package 'MySQL-python' is installed...
 Searching for python_psycopg2 ...
 > Checking if package 'python-psycopg2' is installed...
 Searching for python3_pymongo ...
WARNING
package python3-pymongo is not available in this system.
You may try to install without it.
Searching for python3_pymongo ...
WARNING
package python3-pymongo is not available in this system.
You may try to install without it.
Searching for python3_mysqldb ...
WARNING
package python3-mysqldb is not available in this system.
You may try to install without it.
Searching for python3_psycopg2 ...
WARNING
package python3-psycopg2 is not available in this system.
You may try to install without it.
The following command will be run:
 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   yum update  
    Running in non-interactive mode
yum -y install Judy-devel MySQL-python autoconf autoconf-archive autogen automake gcc git libmnl-devel libuuid-devel libuv-devel lm_sensors lz4-devel make nmap-ncat nodejs openssl-devel pkgconfig python-psycopg2 zlib-devel 
Running in non-interactive mode
yum -y install Judy-devel MySQL-python autoconf autoconf-archive autogen automake gcc git libmnl-devel libuuid-devel libuv-devel lm_sensors lz4-devel make nmap-ncat nodejs openssl-devel pkgconfig python-psycopg2 zlib-devel 
Error: Unable to find a match: Judy-devel MySQL-python python-psycopg2
 FAILED   
 WARNING  It failed to install all the required packages, but installation might still be possible. 
 ABORTED  Stopping due to non-interactive mode. Fix the issue or retry installation in an interactive mode.`

Let me know if I should create a new issue.

**Comment by prologic** [comment] 2020-02-20 21:26
@Xplouder What is your OS/Distro version?

**Comment by Xplouder** [comment] 2020-02-20 23:08
@prologic CentOS 8.1

**Comment by prologic** [comment] 2020-02-21 00:36
Confirmed. Filed #8149 to fix as a high priority.
