### ISSUE TITLE
Allow use of system libwebsockets and mosquitto

### ISSUE THREAD

**Issue by candrews** [netdata/netdata#8961] opened 2020-05-11 14:20 UTC
##### Feature idea summary
Currently, netdata builds bundled copies of libwebsockets and mosquitto. It would be better to (at least optionally) use the system provided libwebsockets and mosquitto libraries, just like netdata does for all of its other dependencies.

##### Expected behavior
In the autotools build system, `configure` should take `--enable-libwebsockets` and `--enable-mosquitto` arguments which would look for and use the system libraries.

Note that this issue is a blocker for enabling netdata cloud on distributions that prohibit library bundling, such as Gentoo.

**Comment by amoss** [comment] 2020-05-11 17:04
The version of mosquitto that we use is not standard so we cannot use the system copy. Now that we have got through the release we will talk to the maintainers and see if we can merge our modifications back upstream.

For libwebsockets we have a different problem - we need a specific version that has been compiled in a specific way. If one of the options was not specified in the build then we will link against the system copy successfully but the link will silently fail at runtime. We currently have no way around this so we build the libwebsockets library to ensure that the correct flags are set.

At this time we cannot switch to using the system libraries, even if they are installed.

**Comment by candrews** [comment] 2020-05-11 17:34
> The version of mosquitto that we use is not standard so we cannot use the system copy. Now that we have got through the release we will talk to the maintainers and see if we can merge our modifications back upstream.

That's good news - perhaps when you've submitted the change requests upstream, you could link to them here, and interested parties can follow along.



> For libwebsockets we have a different problem - we need a specific version that has been compiled in a specific way. If one of the options was not specified in the build then we will link against the system copy successfully but the link will silently fail at runtime. We currently have no way around this so we build the libwebsockets library to ensure that the correct flags are set.

Perhaps change requests can be submitted upstream to address this problem, just like what is planned for mosquitto?

**Comment by amoss** [comment] 2020-05-11 17:37
I'm not that we can do the same with libwebsockets. It is not a change to the code or the functionality of the library, the problem is the build configuration. In our case we had weird problems if libcap was not included in the libwebsockets build via a compile-time flag. This is not a change that we can push back upstream - they have support for it already, but it depends on how it is compiled for system packages.

**Comment by candrews** [comment] 2020-05-11 18:00
> In our case we had weird problems if libcap was not included in the libwebsockets build via a compile-time flag.

How about making it optional via a `configure` option? For example, `--enable-system-libwebsockets`? Each distro's packager would be responsible for making sure that the libwebsockets system library is compiled with `libcap` before they enable this option for their package.

**Comment by Ferroin** [comment] 2020-05-11 18:03
> > In our case we had weird problems if libcap was not included in the libwebsockets build via a compile-time flag.
> 
> How about making it optional via a `configure` option? For example, `--enable-system-libwebsockets`? Each distro's packager would be responsible for making sure that the libwebsockets system library is compiled with `libcap` before they enable this option for their package.

I would actually second this sentiment (though I should comment that it's not at ll my decision). Gentoo actually _can_ have libwebsockets built the way we need (it needs to be merged with `USE='caps'` (I've not actively tested this, but building with the `caps` USE flag sets the CMake option that we need set in the libwebsockets build)).

**Comment by amoss** [comment] 2020-05-11 18:04
@core-sre What do you think about how this would affect our packaging and the reliability of Netdata? If it is set wrongly then the agent will crash without any obvious way to diagnose it other than look in the build logs.

**Comment by amoss** [comment] 2020-05-11 18:08
We have posted at the same time :) If we put it in as a configure flag only (i.e. it is not accessible easily from the installer) then I am less concerned about the reliability, although it would be better to put in something like `--with-libwebsockets=` and force the user to supply an explicit path to the library. This reinforces the "at your own risk" nature of overriding this way.

**Comment by Ferroin** [comment] 2020-05-11 18:10
The ideal situation IMO is that we figure out a way to check that LWS was built with libcap support. I don't think we ever really investigated that possibility much as we determined very quickly that none of the major binary distros ship LWS with libcap support.

if we can get that, we can just add an option to use the system copy of LWS (or better yet, default to trying to use it if we don't see the static build in the source tree).

**Comment by underhood** [comment] 2020-05-11 18:15
Hi, guys the reason to bundle Mosq was the changes we did to it to integrate it with LWS.
But for bundling LWS we had (if i remember correctly) different reason -> SOCKS5 support.
Only after doing that we discovered that LWS build system (cmake) does detect lcap in system and builds with it if present. Builds without it as well.
Only thing we had to do is link -lcap if it was build with it to netdata as we didn't find a flag to force it on/off in LWS build.

**Comment by Ferroin** [comment] 2020-05-11 18:18
Ah, yes, you're right @underhood, it was indeed SOCKS5 support that was the issue.

That actually doesn't change much in this case though, Gentoo can do that too (`USE='sock5'` will set that build flag).

**Comment by Ferroin** [comment] 2020-05-11 18:20
It looks like this should be easy to test for too. LWS installs an `lws_config` header as part of the standard install which includes all the build-time settings.

The exact symbol we would need to look for is `LWS_WITH_SOCKS5`. And if we're dynamically linking we can ignore the libcap stuff, because _that_ should be handled correctly by the runtime linker.

**Comment by prologic** [comment] 2020-05-13 03:06
Why are we going out of our way to avoid our own bundled dependencies here? I get that we can push some upstream changes we made to mobmosquitto, but there are very good reasons why we chose to bundle some of our dependencies. Furthermore we are not really thinking about other systems here, e.g: *BSD, macOS, pfSense, Docker Images, Windows, etc. I also find it really hard to imagine that this won't come back to bite us if/when a "system" installed libwebsockets changes in some subtle ways that breaks our agent on those system(s).

**Comment by Ferroin** [comment] 2020-05-13 11:20
> Why are we going out of our way to avoid our own bundled dependencies here? I get that we can push some upstream changes we made to mobmosquitto, but there are very good reasons why we chose to bundle some of our dependencies. Furthermore we are not really thinking about other systems here, e.g: *BSD, macOS, pfSense, Docker Images, Windows, etc. I also find it really hard to imagine that this won't come back to bite us if/when a "system" installed libwebsockets changes in some subtle ways that breaks our agent on those system(s).

Because the ideal situation long term is that each distro is maintaining up-to-date Netdata packages themselves without us having to manage it ourselves.

To actually achieve this, we need to support their requirements for packaging, which in many cases means allowing usage of system libraries instead of bundled ones.  In the specific case of Gentoo, the old mantra of 'you break it you fix it' applies (if it's done correctly on Gentoo, users will have to go seriously out of their way to cause the breakage you're suggesting). For other distros, it's reasonable to expect the package maintainers to ensure that they get things right.

**Comment by prologic** [comment] 2020-05-13 12:51
Please let's table this for the time being (_sorry @candrews_) until we've had a proper chance to review the plan I've proposed and have made a decision going forward regarding packaging in general.

**Comment by candrews** [comment] 2020-05-13 13:22
All major distros prohibit library bundling, and with good reason, including security, legal/licensing, and bug fixing/maintainability. I'm sure the other netdata package maintainers, including @svenstaro @lhw @FedericoCeratto @willysr @didier13150, would be able to elaborate on this topic as well.

Links to distro policies:
Debian: https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code
Fedora: https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries
Gentoo: https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies

Beyond packaging, upstreaming modifications as opposed to forking and bundling is important to both netdata and its dependencies. For example, if netdata doesn't get the changes it needs into upstream mosquitto, netdata will need to carry a fork of mosquitto forever, creating a extra work for it. It may not seem like much extra work, but over time, it's going to really add up. Consider that even Microsoft contributes to upstream Linux, because even for it, carrying permanent forks is just not worth it.

**Comment by Ferroin** [comment] 2020-05-13 14:57
@prologic Our own packaging is functionally orthogonal to this. _No_ distribution is going to accept what we've been working on planning for in their repos (except _possibly_ Ubuntu in their Universe repo).

And long term, it is a _very_ good thing for us if we have packages in the main repos of the major distros that receive regular updates. That lowers the bar for us in terms of our own packaging (we don't have to provide all the special packaging features users want, the distros will take care of that) and gets us both much better exposure and much easier uptake (the need to use a third-party repo or a special installer is a huge turn off for a lot of less tech-savvy users because it's not easy).

**Comment by SWSAmor** [comment] 2020-07-30 08:58
What is happening? Stucked? Can I help you somehow? I'm eagerly want to use Netdata Cloud with my Gentoo servers.

**Comment by prologic** [comment] 2020-08-03 06:22
@SWSAmor We've put this on Ice for the time being... If you want to have a crack at it by all means. There is nothing stopping you from building Netdata from source on Gentoo with our existing tools. What you _may_ not be able to do and expect to work is to build against Gentoo managed libraries for libmosquitto -- libwebsockets should be fine (_as long as its built correctly on Gentoo_).

**Comment by SWSAmor** [comment] 2020-08-03 06:40
Thx for the info.

**Comment by prologic** [comment] 2020-08-03 10:24
LMK how it all goes!

**Comment by Ferroin** [comment] 2020-08-10 11:40
@prologic Unless something has changed while I was gone, we _still_ do not support linking against a system copy of LWS, even if it was built with the 'correct' options for our usage. That's part of the reason this was opened in the first place, until we properly support using system libraries for all the stuff we currently bundle that does not need custom patches, we have features that cannot be properly enabled in the packages for Netdata that are in Portage (which is the first thing most Gentoo users will see of Netdata).

**Comment by amoss** [comment] 2020-08-10 11:42
The plan that we agreed was to add explict `--using-xxx` flags to `configure` to allow explicit override of libraries for an experienced user. It is still planned that we will do this, although we have high priority task right now.

**Comment by Ferroin** [comment] 2020-09-01 14:46
This is now functionally blocking us from getting a full featured package in Homebrew: https://github.com/Homebrew/homebrew-core/pull/60472#discussion_r481074604

**Comment by prologic** [comment] 2020-09-02 05:59
I'm very frustrated by this honestly. 😢

**Comment by leotaku** [comment] 2020-09-17 23:27
Just FYI, this issue is also blocking getting cloud integration into the Nixpkgs package. (NixOS/nixpkgs#92782)

I'd like to offer some constructive feedback that might be useful to in order to make Netdata better accommodate Nixpkgs and maybe also other software distributions.

* Nixpkgs will accept vendored dependencies if they are vendored for a good reason.

*Mosquitto seems like a good candidate for this rule because, as you have mentioned, you use a custom fork with changes that are unlikely to be upstreamed. On the other hand, Netdata depends on upstream Libwebsockets which means the already packaged version should probably be used.*

* If possible, use standardized mechanisms such as pkg-config to detect non-vendored (i.e. system) dependencies.

* Allow the use of environment variables to specify whether a system or vendored dependency should be used, where to find the required files, etc.

* Please allow vendored dependencies to be built and installed in isolation from the main package. (already possible)

*This separation of concerns allows us to keep our build scripts simple and maintainable. Nix also allows us to link libraries only for specific packages, so a vendored dependency could be installed normally and then only be linked into the package that it is used by.*

I hope this has been somewhat helpful, thank you for your work on Netdata!

**Comment by prologic** [comment] 2020-09-18 04:01
@leotaku Thank you the very well written response and feedback. You are right we can use upstream libwebsockets, there is no need to bundle that as I'm not aware of any significant patches we've made for our specific use-case.

libmosquitto OTOH is the one we've made significant changes to that are unlikely to be pushed upstream.

In any case, we also have other "good reasons" to bundle other dependencies that we've also recently done such as libJudy which whilst there are versions of in _some_ limited Linux Distributions / Systems, it's becoming harder to support as its not nearly a widespread library as we'd like. However you'll be pleased to know that in every case we've ensured that we can also built and link against a system version of the same library. We are doing this to reduce the complexity for users and the number of reported "build failures for X" where X is some problematic library.

Next we'll work on libwebsockets and bundle that in the same way and like with libJudy use a system-version if available.

Thanks again! We'll get back to this soon, right now we're focused on improving out packaging workflows. cc @Ferroin

**Comment by Ferroin** [comment] 2020-09-18 11:44
Actually, we _may_ depend on LWS being built a specific way. AFAICT, the original reasoing for bundling LWS was that we wanted to use it's built-in SOCKS5 support, and very few distros actually build it with that support enabled (because they sensibly assume that people will use libsocks from the Dante project, which is what we _should_ have done here for multiple reasons, though I still don't appear to have convinced the C developers and the product team of this). Whether or not we actually _require_ that functionality to be enabled in LWS for the build to work correctly or not I don't know.

**Comment by prologic** [comment] 2020-09-22 06:33
> Actually, we _may_ depend on LWS being built a specific way. AFAICT, the original reasoing for bundling LWS was that we wanted to use it's built-in SOCKS5 support, and very few distros actually build it with that support enabled (because they sensibly assume that people will use libsocks from the Dante project, which is what we _should_ have done here for multiple reasons, though I still don't appear to have convinced the C developers and the product team of this). Whether or not we actually _require_ that functionality to be enabled in LWS for the build to work correctly or not I don't know.

Correct me if I'm wrong, but do we actually use this in production or this a dev-only thing? Who/What uses or connects to app.netdata.cloud via a SOCKS5 proxy? @hmoragrega ?

**Comment by underhood** [comment] 2020-09-22 06:41
@prologic ACLK itself has SOCKS5 proxy support.

To solve this I can modify agent and buildsystem to detect if libwebsockets has SOCKS5 support and create some `#define` based on that. Then modify the code to make SOCKS5 support optional (available based on what libwebsocket has).

**Comment by underhood** [comment] 2020-09-22 06:55
@Ferroin and @prologic 
OK checked that LWS conveniently defines `#ifdef LWS_WITH_SOCKS5` if it was built with SOCKS support. Therefore as the first step, I will make SOCKS support optional in the agent and print an error message to log in case somebody has LWS without SOCKS and tries to use it.
second step would be modifying the installer and configure scripts to allow usage of the system library (perhaps introducing flag like `--dont-bundle-lws`)

**Comment by stelfrag** [comment] 2020-09-22 07:15
> @Ferroin and @prologic
> OK checked that LWS conveniently defines `#ifdef LWS_WITH_SOCKS5` if it was built with SOCKS support. Therefore as the first step, I will make SOCKS support optional in the agent and print an error message to log in case somebody has LWS without SOCKS and tries to use it.
> second step would be modifying the installer and configure scripts to allow usage of the system library (perhaps introducing flag like `--dont-bundle-lws`)

We need to make sure that all the functions we use are available in the system installed version. The `lws_ring_xxxx` functionality comes in mind.

**Comment by prologic** [comment] 2020-09-22 10:50
This all sounds fine guys. I just have one question. Why did we do this in the first place if ND agents can connect to and talk to app.netdata.cloud without SOCKS5? Or am I missing something here like enterprise networks/firewalls/etc? I'm sure we had a good reason (_I just don't recall what it was now :/_)

**Comment by Ferroin** [comment] 2020-09-22 11:12
@prologic Better support for corporate network setups I believe. SOCKS5 is uncommon, but it's far from unusual in corporate settings.

@underhood I agree that that's a sensible first step. Long-term though we _really_ should look into whether we can use libsocks from the Dante project so that we're not dependent on LWS being built a specific way _and_ we can support SOCKS5 for other connections (streaming/replication comes to mind).

**Comment by underhood** [comment] 2020-09-22 11:48
@Ferroin well making SOCKS optional is something we can do now. About allowing support for Dante libsocks or any other library in fact is completely another topic and would have to be agreed on and prioritized by someone higher.

**Comment by Ferroin** [comment] 2020-09-22 11:59
> @Ferroin well making SOCKS optional is something we can do now. About allowing support for Dante libsocks or any other library in fact is completely another topic and would have to be agreed on and prioritized by someone higher.

Indeed, my only point is that if we want _proper_ SOCKS5 support, we shouldn't be relying on a feature that isn't reliably available in one of our existing dependencies.

Put differently, had I known that SOCKS5 support for the ACLK was a goal before the need to bundle LWS got kind of dumped in my lap, I would have actively argued against using the native support in LWS in favor of using libsocks, because then we wouldn't have had to vendor anything except Mosquitto.

**Comment by underhood** [comment] 2021-01-18 15:59
@candrews you can now use system libwebsockets if newer than 3.2.
for libmosquitto that is not possible due to the fact it uses custom patch

We are working on new stack that will remove the need for both of those libraries. Stay tuned :)

I will close this issue as it is done in as much as could be done and becomes obsolete when ACLK-NG comes

**Closed by underhood** 2021-01-18 15:59 UTC
Labels: area/build, area/packaging, feature request
