### ISSUE TITLE
"Missing charts" on v1.15.0-70-nightly  (**solved**)

### ISSUE THREAD

**Issue by Faustino50-Cattaro** [netdata/netdata#6244] opened 2019-06-07 14:01 UTC
##### Bug report summary
We have a few server with Netdata installed on it.
Some servers have precedent version such 1.14 or 1.15.0.63
2 servers have the latest version but in my customized dashboard them doesn't appear (see images)
![123](https://user-images.githubusercontent.com/50456329/59109508-788c9400-893d-11e9-845b-4fe054745e70.png)

If I go on the full page, I can see the whole Netdata with those charts but not from my customized dashboard

##### OS / Environment
2x Debian Server
##### Netdata version (ouput of `netdata -V`)
v1.15.0-70-nightly
##### Component Name
Charts

**Comment by DenHerm** [comment] 2019-06-07 14:18
Even the main https://my-netdata.io/ page seems to have the issue:
![image](https://user-images.githubusercontent.com/51485122/59110619-ca361e00-893f-11e9-9a31-2dd0e09c668d.png)

**Comment by cakrit** [comment] 2019-06-07 14:49
We just noticed it about 30 min ago ourselves. It has to do with the new URL parser. We'll have the fix on tonight's nightly.

**Comment by Faustino50-Cattaro** [comment] 2019-06-07 14:49
OOF

**Comment by cakrit** [comment] 2019-06-07 15:17
We're removing the commits related to the URL parsing and publishing a new nightly. @paulkatsoulakis will comment here when it's done and running on the netdata servers. Apologies guys, we must have tested ~400 URL requests and didn't notice the problem until today. Will ensure we get a good automated API test coverage embedded in our CI in the next couple of weeks.

**Comment by paulkatsoulakis** [comment] 2019-06-07 15:20
Hello all, we just revert the root cause for this issue.
We 'll be building a new nightly version ASAP and let you know here to update again.

Sorry for the inconvenience guys, just to let you know we are *already* working on more longer term solutions for live testing within our internal CI/CD lifecycle so that we eliminate such embarrassing situations. In the meantime, we 'll do our best to attend any issues the fastest possible!

I 'll let you know once we 're ready for you to update

**Comment by DenHerm** [comment] 2019-06-07 15:50
Also FYI, soon after querying "/api/v1/chart?chart=system.cpu" and/or "/api/v1/chart?chart=apps.cpu" with data-dimensions="antivirus"
netdata on the affected hosts (6) started to run at 100% CPU
![image](https://user-images.githubusercontent.com/51485122/59116481-ef308e00-894b-11e9-8507-2db1c9fd8a73.png)
Nothing in the netdata error log - only a 404 notice in the access log:
'DATA' (sent/all = 68/48 bytes -38430716820228227072%, prep/sent/total = 0.03/0.13/0.16 ms) 404 '/api/v1/chart?chart=apps.cpu&_=1559921796532'

**Comment by cakrit** [comment] 2019-06-07 15:55
We're pretty certain that the unreasonable CPU utilization and occasional segfaults are both the effect of the same root cause. You could see either or both after a mishandled query to the API

**Comment by mfundul** [comment] 2019-06-07 15:59
Another question, what `memory mode` are you using?

**Comment by DenHerm** [comment] 2019-06-07 16:22
Default "save" mode.

**Comment by paulkatsoulakis** [comment] 2019-06-07 16:47
@DenHerm Could you please update to latest netdata and let us know if your problem is attended?

**Comment by DenHerm** [comment] 2019-06-07 16:57
Charts are working again. Great stuff!

**Comment by paulkatsoulakis** [comment] 2019-06-07 17:03
That is great to hear @DenHerm!
By all means do let us know if anything else weird happens and we will gladly jump in and solve it again. 

One more time on behalf of the netdata team, we 're sorry for this inconvenience.
We strive hard to secure our releases from such situations, but this is still an on going effort with many fronts to cover!

**Comment by paulkatsoulakis** [comment] 2019-06-09 08:56
As the issue has been mitigated and no further reports have been seen, i will be resolving this.
Do not hesitate to reopen the issue or report a new one, if something goes wrong with Netdata again.
We 'll be glad to help, cheers!

**Closed by paulkatsoulakis** 2019-06-09 08:56 UTC
Labels: bug, priority/high
