### ISSUE TITLE
Netdata sends recovered notification but it should only send critical alerts

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#10624] opened 2021-02-13 15:13 UTC
##### Bug report summary

Our rocket chat is configured to only send critical alerts, but it also sends the recovered alerts. Here is the configuration in `health_alarm_notify.conf`: 
```
DEFAULT_RECIPIENT_ROCKETCHAT="sre-alerts|critical"
```

##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 1.29.1

##### Component Name

health

##### Expected behavior

only see critical alerts

**Comment by ilyam8** [comment] 2021-02-16 09:02
Hi @yasharne 

There is `filtering severity per recipient` feautre, i didn't find its description in the docs. There is only a note that it exists.

I guess it supposed to work like that - if you add `|critical` it means you don't receive WARNING level alarms.

That is filtering function

https://github.com/netdata/netdata/blob/57adb073c5135d88a2b62036612a8650df528bd9/health/notifications/alarm-notify.sh.in#L433-L482

---

If the current alarm status is CRITICAL, it creates a file

https://github.com/netdata/netdata/blob/57adb073c5135d88a2b62036612a8650df528bd9/health/notifications/alarm-notify.sh.in#L454-L459

If the status changes the script checks the file existence (and removes it if status != WARNING)

https://github.com/netdata/netdata/blob/57adb073c5135d88a2b62036612a8650df528bd9/health/notifications/alarm-notify.sh.in#L462-L476

---

It looks like even transition from CRITICAL to WARNING will trigger sending a notification.

I am not sure how it supposed to work since, as i mentioned, i found no documentation.

@thiagoftsm @Ferroin do you guys aware of that filtering by severity feature? (initially was added in https://github.com/netdata/netdata/pull/967)

**Comment by thiagoftsm** [comment] 2021-02-22 11:30
@ilyam8 last year I made a PR bringing what @yasharne is requesting, but there were two PRs [this](https://github.com/netdata/netdata/pull/9698) and [this](https://github.com/netdata/netdata/pull/9740) that we used to brought the original situation, because we understood we were not explaining the main goal of `|critical`.

**Comment by ilyam8** [comment] 2021-02-22 13:04
Yeah, so it is by design. @yasharne it supposed to work like that

https://github.com/netdata/netdata/blob/bcdc5aa88821434051c209ce6ead1f1f1d66aa14/health/notifications/health_alarm_notify.conf#L163-L169

**Comment by yasharne** [comment] 2021-02-24 06:10
@ilyam8 I've been using netdata since version `1.19.0` and the health alarm configuration was always the same (the receiver should only receive the critical alerts) but we never received the recovered alerts, we used to get only the critical alert and getting the `recovered` alerts is something new when I have updated to version `1.29.0`

**Comment by ilyam8** [comment] 2021-02-24 08:45
@yasharne it looks like it was a bug back then

see #8739 (_fixed_ in #9698)

**Comment by yasharne** [comment] 2021-02-28 16:11
@ilyam8 Is it possible to have an option to disable `recovered` messages? 

A similar configuration in alertmanager is `send_resolved: false`

**Comment by ilyam8** [comment] 2021-02-28 16:27
@yasharne it is,i think it is quite easy to add it as a global option. Or you mean per method?

**Comment by ilyam8** [comment] 2021-02-28 17:24
@yasharne i think something like that should do (per method, not per recipient).

The patch:

```diff
0 netdata (master *)$ git diff
diff --git a/health/notifications/alarm-notify.sh.in b/health/notifications/alarm-notify.sh.in
index 3bf8db5f..9c1ace82 100755
--- a/health/notifications/alarm-notify.sh.in
+++ b/health/notifications/alarm-notify.sh.in
@@ -650,6 +650,12 @@ for method_name in ${method_names}; do
     continue
   fi

+  send_clear="${method_name^^}_SEND_CLEAR"
+  if [ "${!send_clear^^}" = "NO" ] && [ "${status}" = "CLEAR" ]; then
+    declare ${send_var}="NO"
+    continue
+  fi
+
   declare -A arr_var=()

   for x in ${roles//,/ }; do
```

If expects `<METHOD_NAME>_SEND_CLEAR` to be `NO/no` 

> ROCKETCHAT_SEND_CLEAR=NO

**Comment by ilyam8** [comment] 2021-02-28 18:01
@yasharne as we've figured out severity filtering feature supposed to work like that. It doesn't filter recover notifications. So i am closing this issue.

I suggest to open a request to add `send_resolved`/`send_clear`.

**Closed by ilyam8** 2021-02-28 18:01 UTC
Labels: area/health, question
