### ISSUE TITLE
NetData no longer installs after recent xenstat commit

### ISSUE THREAD

**Issue by shinji257** [netdata/netdata#5726] opened 2019-03-28 04:26 UTC
##### Bug report summary
After the recent xenstat commit updating or installing Netdata fails with an error referencing collectors/xenstat.plugin/Makefile.in

##### OS / Environment
OS: Ubuntu 18.04.2 LTS
Kernel: 4.15.0-45

OS: Debian 9.8
Kernel: 4.15.18-11-pve

##### Netdata version (ouput of `netdata -V`)
N/A since it won't complete compile

##### Component Name
collectors/xenstat

##### Steps To Reproduce
Run the kickstart script as it quickly reproduces there.

##### Expected behavior
Umm... It installs

For reference here is the install log: https://pastebin.com/raw/NcFb7VRV

**Comment by mailme-gx** [comment] 2019-03-28 04:42
This same bug happens when running update (also running debian)

`/etc/cron.daily/netdata-updater:
./netdata-latest.tar.gz: OK
Thu Mar 28 06:25:06 EET 2019 : INFO: Re-installing netdata...

^
|.-. .-. .-. .-. . netdata
| '-' '-' '-' '-' real-time performance monitoring, done right!
+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


You are about to build and install netdata to your system.

It will be installed at these locations:

- the daemon at /usr/sbin/netdata
- config files in /etc/netdata
- web files in /usr/share/netdata
- plugins in /usr/libexec/netdata
- cache files in /var/cache/netdata
- db files in /var/lib/netdata
- log files in /var/log/netdata
- pid file at /var/run/netdata.pid
- logrotate file at /etc/logrotate.d/netdata

This installer allows you to change the installation path.
Press Control-C and run the same command with --help for help.


--- Run autotools to configure the build environment ---
[/tmp/netdata-updater-Sos5Nw/netdata-v1.13.0-41-g793e03f0]# autoreconf -ivf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:680: error: required file 'collectors/xenstat.plugin/Makefile.in' not found
autoreconf: automake failed with exit status: 1
FAILED


^
|.-. .-. .-. .-. .-. . netdata .-. .-
| '-' '-' '-' '-' '-' sorry, it failed to build... '-' '-'
+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Sorry! netdata failed to build...

You may need to check these:

1. The package uuid-dev (or libuuid-devel) has to be installed.

If your system cannot find libuuid, although it is installed
run me with the option: --libs-are-really-here

2. The package zlib1g-dev (or zlib-devel) has to be installed.

If your system cannot find zlib, although it is installed
run me with the option: --libs-are-really-here

3. You need basic build tools installed, like:

gcc make autoconf automake pkg-config

Autoconf version 2.60 or higher is required.

If you still cannot get it to build, ask for help at github:

https://github.com/netdata/netdata/issues


Thu Mar 28 06:25:11 EET 2019 : ERROR: FAILED TO UPDATE NETDATA : FAILED TO COMPILE/INSTALL NETDATA
run-parts: /etc/cron.daily/netdata-updater exited with return code 1 `

**Comment by mcginty** [comment] 2019-03-28 04:52
Experiencing the same, Debian on an Orange Pi
```
  Operating System: Debian GNU/Linux 9 (stretch)
            Kernel: Linux 4.19.20-sunxi
      Architecture: arm
```

**Comment by rda0** [comment] 2019-03-28 05:47
I can confirm the same on 20+ machines Debian/Ubuntu.

```
 --- Run autotools to configure the build environment --- 
[/tmp/netdata-updater-D6XYxP/netdata-v1.13.0-41-g793e03f0]# autoreconf -ivf 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I build/m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:680: error: required file 'collectors/xenstat.plugin/Makefile.in' not found
autoreconf: automake failed with exit status: 1
 FAILED
```

**Comment by ilyam8** [comment] 2019-03-28 06:09
i see scrit downloads nightly release
`https://storage.googleapis.com/netdata-nightlies/netdata-latest.tar.gz`

And indeed there is no `collectors/xenstat.plugin/Makefile.in`, xenstat.plugin dir contains only xenstat_plugin.c file.

**Comment by ilyam8** [comment] 2019-03-28 06:10
i think it will be fixed on next release.

**Comment by wmtech-1** [comment] 2019-03-28 07:05
Same experience at all our machines. Please fix! Thanks.

**Comment by arjanvlek** [comment] 2019-03-28 08:11
Same issue here. Can you guys please fix it?

**Comment by cakrit** [comment] 2019-03-28 12:32
Travis has been having problems since yesterday, we're doing everything we can to get a nightly build with the fix published.

**Comment by cakrit** [comment] 2019-03-28 12:48
I'm reopening it and leaving it open until we can verify we have published a nightly build. You can see the travis status that is blocking us [here](https://www.traviscistatus.com/), we're looking into a workaround.

**Comment by cakrit** [comment] 2019-03-28 14:44
netdata-latest has been updated on GCS to a previous, stable version. We'll have a newer nightly after we have added some additional checks. The problem turned out not to be related to travis, but to the pipeline we use. We'll add some additional checks to the process, before uploading a new build.

**Comment by paulkatsoulakis** [comment] 2019-03-29 02:12
New nightly build is out and tested. Please do let us know in the case of any further problems.
We are in the process of deep diving into what went wrong with our pipeline and allowed such a problem to reach our customers (issue #5733).

**Closed by paulkatsoulakis** 2019-03-29 02:12 UTC
Labels: area/packaging, bug, priority/high

**Comment by mailme-gx** [comment] 2019-03-29 02:18
I can confirm running /etc/cron.daily/netdata-updater now completes sucessfully
Thank you all for such a prompt fix

**Comment by paulkatsoulakis** [comment] 2019-03-29 02:22
> I can confirm running /etc/cron.daily/netdata-updater now completes sucessfully
> Thank you all for such a prompt fix

Good to know everything works fine now @mailme-gx 
Again we are sorry for the inconvenience in the first place, we are constantly working to make sure we are providing you with the best user experience
