### ISSUE TITLE
High Traffic to Netdata Cloud

### ISSUE THREAD

**Issue by gvasquez95** [netdata/netdata#11095] opened 2021-05-05 14:29 UTC
**Issue with: High charges on AWS due to high traffic**

I just realized that only Netdata actual data sent to NetData Cloud cost us USD 100/daily, due to the high volume involved. How can this be optimized? We currently have a setup of around 40 EC2 instances sending info to your servers. Is some kind of aggregation and/or compression possible? Or maybe VPC peering within AWS?

**Comment by cakrit** [comment] 2021-05-05 14:41
Not good, let us discuss internally and we'll get back to you.

**Comment by gvasquez95** [comment] 2021-05-05 14:44
Thanks @cakrit 

I'll be waiting for your feedback

**Comment by cakrit** [comment] 2021-05-05 16:09
I would like to look at the details of that usage with you @gvasquez95 . Please contact me at chris@netdata.cloud so we can arrange a call. 

A few hints and some info on items in our roadmap, for the benefits of others:
- The chart `netdata.aclk_write_q` shows the outbound bandwidth utilized for data sent from the agent to the cloud. For the nodes you have in a room you can see the aggregate in kbps across all the nodes from the "Overview" screen. e.g. see screenshot at the end.
- We intend to move from json-based payloads to protobuf soon (expected sometime this summer), thus reducing the required BW.
- We will drastically reduce the required BW after each reconnection when a redesign we are implementing is completed. ETA end of June. If your agents are auto-updating each day, they currently reconnect each day and have to re-send all the chart metadata. **So one quick workaround if you have this issue is to disable automatic updates**, until we are finished with the implementation. 
- In the long run and if we are successful, we will have a multi-cloud approach, so e.g. the AWS nodes will be connected to our AWS-hosted cloud, same for Azure, GCP etc.
- We may be moving our infra to AWS some time this year, we're in discussions with them. But the issue would remain for the other providers, which is why BW reduction is a high priority for us.

![image](https://user-images.githubusercontent.com/43294513/117172851-0d45d980-ad81-11eb-8acc-ab4d692df79b.png)

**Comment by gvasquez95** [comment] 2021-05-05 18:08
I just sent you a short email

**Comment by cakrit** [comment] 2021-05-06 22:49
@underhood we went through the aclk_write_q charts with @gvasquez95 
He was showing sustained writes of between 2 and 4 KBps on 4 of his nodes. When we restarted the agents, the pattern disappeared. One of the nodes still had spikes every few seconds, but we couldn't figure out what could be causing them.
Probably important, all of those nodes were running Amazon Linux 2 ARM based architecture (graviton-based). 
Also, we saw on one of them that ebpf wasrunning (in case there may be any relevance)

**Comment by cakrit** [comment] 2021-05-06 22:50
Look at the pattern below, across 1 day. It looks like it's not sustained, but constantly increasing until a restart.

<img width="1587" alt="Screen Shot 2021-05-06 at 18 48 48" src="https://user-images.githubusercontent.com/43294513/117374817-b9bbb480-ae82-11eb-8069-3213c141704f.png">

**Comment by cakrit** [comment] 2021-05-06 23:01
@gvasquez95 says that all the nodes with issues were real-time processors running elixir, which creates and destroys processes all the time. 
I had him disable ACLK until we can replicate the issue and find a solution.

**Comment by underhood** [comment] 2021-05-07 07:54
Those charts indeed indicate there is something causing data to be stuck in the queue and Libwebsockets not being able to push it quickly enough.... In normal operation when not looking at the dashboard in cloud you will have tiny spikes which are MQTT keep-alives. But what is seen in screenshot is indeed not a normal operation.

@gvasquez95 what is the workload on elixir? Can I somehow emulate it (e.g. run the same elixir based OSS server in my VM). Can we add some debug logs manually to try and find the culprit? Can you share error log? (timotej[snail]netdata.cloud)

**Comment by OdysLam** [comment] 2021-05-07 11:04
Kinda offtopic but after we figure this out, @gvasquez95 I would be very interested to hear about your elixir use-case and how you use Netdata to monitor the application.

**Comment by gvasquez95** [comment] 2021-05-07 13:21
> @gvasquez95 says that all the nodes with issues were real-time processors running elixir, which creates and destroys processes all the time.
> I had him disable ACLK until we can replicate the issue and find a solution.

Not exactly all the nodes with issues, but most of them except for one that has a [Forever](https://www.npmjs.com/package/forever) based NodeJS cluster and is also affected by this issue

**Comment by gvasquez95** [comment] 2021-05-07 20:27
@OdysLam we are using netdata just really to monitor the hardware related resources of the EC2 instances, not exactly the elixir app itself

**Comment by gvasquez95** [comment] 2021-05-08 11:30
error logs from `/var/logs/netdata` for 4 nodes available at:

- https://s3.amazonaws.com/tmp.jooycar/disposable/netdata/tc0.tar
- https://s3.amazonaws.com/tmp.jooycar/disposable/netdata/tc1.tar
- https://s3.amazonaws.com/tmp.jooycar/disposable/netdata/tc2.tar
- https://s3.amazonaws.com/tmp.jooycar/disposable/netdata/tc3.tar

**Comment by OdysLam** [comment] 2021-05-10 13:32
Thanks @gvasquez95 for your information. 

How do you monitor the elixir app? Did I correctly understand that you are using StatsD _somewhere_ in the stack?

**Comment by naaano** [comment] 2021-05-10 14:14
Hi, I'm the devops guy at jooycar. I'll add some useful info:
- Elixir apps don't start and kill processes all the time. They're threads within the same process that runs for very long time on most apps. 
- we're not really monitor apps itself, but OS instance resources. 
- The problem might not be related to elixir apps, since we've been experiencing the same issues on apps running on nodeJs and apache spark nodes.  
- what it has been a common pattern, is that everything started when we migrated to graviton based instances (amazon linux 2 over ARM). They almost all have experienced peaks of ram usage (in some cases up to 71% of the total system memory, just for the netdata agent). Shutting the service down (sudo systemctl stop netdata) takes a long time. Sometimes it won't start again (error msg is "Failed at step NAMESPACE spawning /bin/mkdir: Value too large for defined data type" which is a step in systemd unit declaration) and had to reinstall to make it work again.

**Comment by gvasquez95** [comment] 2021-05-11 14:38
@underhood did you find anything worth investigating in the logs I provided?

**Comment by underhood** [comment] 2021-05-11 16:24
@gvasquez95 at the initial look at aclk logs didn't see something suspicious but haven't given up yet

**Comment by underhood** [comment] 2021-05-12 10:55
Running netdata master on Amazon Linux 2 ARM64 doesn't reproduce the issue. Must be sth. else there... configuration? During the constantly increasing writes do you keep Cloud dashboard always displayed somewhere or does it increase all the time?

**Comment by underhood** [comment] 2021-05-12 11:14
Do use use memory mode dbengine on all machines?

**Comment by gvasquez95** [comment] 2021-05-12 13:03
> Running netdata master on Amazon Linux 2 ARM64 doesn't reproduce the issue. Must be sth. else there... configuration? During the constantly increasing writes do you keep Cloud dashboard always displayed somewhere or does it increase all the time?

The dashboard isn't regularly open on any screen

**Comment by gvasquez95** [comment] 2021-05-12 13:04
> Do you use memory mode dbengine on all machines?

dbengine is a Netdata module? If so, we only use the default config, no tweaks at all.

**Comment by underhood** [comment] 2021-05-12 13:20
@gvasquez95 it is configurable setting which determines how are metrics stored. Default is dbengine if it was built successfully.
You can verify by trying:
`http://127.0.0.1:19999/api/v1/charts` one of the json keys will be named `memory_mode`

**Comment by gvasquez95** [comment] 2021-05-12 13:32
@underhood I just checked on 6 of the "problem" EC2 instances and yes, all six of them show `"memory_mode": "dbengine"`

**Comment by cakrit** [comment] 2021-05-12 14:32
@naaano / @gvasquez95 we did in parallel an investigation of Netdata's high memory usage in your infra.
There's a chance both the Agent - Cloud Link (ACLK) high traffic issue and the high memory footprint are connected and due to constantly changing metrics, which however I couldn't identify on the charts themselves. However, can you please let me know if you see a correlation between the memory usage and the egress bandwidth? i.e. were they the same servers that had both issues? If not, we'll ask for some more data for the memory issue as well, because the default settings bring expected memory usage to around 200MB for 3 days of retention, with the number of metrics collected on your nodes.

**Comment by cakrit** [comment] 2021-05-12 14:38
https://github.com/netdata/product/issues/2019 shows how the two can be linked (mentions RAM mode, but dbengine mode also increases memory when dimensions become obsoleted).

**Comment by underhood** [comment] 2021-05-12 14:41
> [netdata/product#2019](https://github.com/netdata/product/issues/2019) shows how the two can be linked (mentions RAM mode, but dbengine mode also increases memory when dimensions become obsoleted).

there is PR for that https://github.com/netdata/netdata/pull/11133

**Comment by underhood** [comment] 2021-05-12 14:52
@gvasquez95 would you be willing to compile netdata with a patch that adds some logs on the problematic node(s)?

**Comment by gvasquez95** [comment] 2021-05-25 14:33
for sure @underhood .... @naaano is the correct one for such compilation procedure

**Comment by underhood** [comment] 2021-05-26 08:44
@gvasquez95 @naaano there has meanwhile been a new Netdata release. There has been some fixes merged that could cause unnecessary messages to be sent over ACLK (to cloud). Before we go ahead with the log patch could you confirm this issue persists also with new Netdata version?

**Comment by UmanShahzad** [comment] 2021-07-06 08:22
@naaano light ping if you were able to check if the new Netdata release fixed the issue or if it still persists?

**Comment by ilyam8** [comment] 2021-09-21 08:40
Closing due to no response. @gvasquez95 @naaano please check the new Netdata release and if the issue remains let us know.

**Closed by ilyam8** 2021-09-21 08:40 UTC
Labels: bug, ACLK
