### ISSUE TITLE
Broken build on FreeBSD

### ISSUE THREAD

**Issue by amoss** [netdata/netdata#9163] opened 2020-05-26 11:59 UTC
##### Bug report summary

On a system with automake 1.16.1 the `netdata-installer.sh` fails with the following output:
```
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
```

Adding the suggested flag does not fix the problem. There is an incompatibility between `automake` 1.16.1 and the default (BSD) make. 

The work-around is to add the `--disable-dependency-tracking` flag to `./configure` and use `gmake` instead of `make` in the installer.

##### OS / Environment

FreeBSD mechani.se 12.0-RELEASE-p4 FreeBSD 12.0-RELEASE-p4 GENERIC  amd64
1200086

##### Netdata version

netdata v1.16.1-1909-g461e3ab4

##### Component Name
Installer / build-system

##### Steps To Reproduce

Install on FreeBSD.

##### Expected behavior

A working installation.

**Comment by prologic** [comment] 2020-05-27 06:15
Did we introduce changes to our build system that introduced this breakage? I suspect we _might_ have because FreeBSD builds were working without too much fuss at one point. Also I'd like to refocus (_time/bandwidth permitting_) on finally getting some form of FreeBSD CI/Testing going and so #9162

**Comment by stevenh** [comment] 2020-05-30 20:00
duplicate of https://github.com/netdata/netdata/issues/9227

**Comment by prologic** [comment] 2020-06-01 02:35
> duplicate of #9227

Other way around :) We're tracking progress here.

**Comment by prologic** [comment] 2020-06-25 04:19
All dependencies satisified:

```#!sh
root@freebsd121:~/netdata # ./packaging/installer/install-required-packages.sh netdata-all
 > FreeBSD Version: 12.1-RELEASE ...
 > Checking for gmake ...

We detected these:
Distribution    : freebsd
Version         : 12.1-RELEASE
Codename        :
Package Manager : install_pkg
Packages Tree   : freebsd
Detection Method: uname
Default Python v: 3

Searching for distro_sdk ...
Searching for autoconf_archive ...
Searching for libz_dev ...
Searching for libuuid_dev ...
Searching for libmnl_dev ...
WARNING
package libmnl-dev is not availabe in this system.

Searching for json_c_dev ...
Searching for lm_sensors ...
Searching for libuv ...
Searching for lz4 ...
Searching for openssl ...
Searching for judy ...
Searching for python3 ...
Searching for python3_pymongo ...

All required packages are already installed. Now proceed to the next step.
```

**Comment by prologic** [comment] 2020-06-25 04:27
And we have Netdata built from source and running on FreeBSD:

```#!sh
Setting netdata.tarball.checksum to 'new_installation'

 --- We are done! ---

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata                          .-.   .-
  |   '-'   '-'   '-'   '-'   '-'   is installed and running now!  -'   '-'
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

  enjoy real-time performance and health monitoring...
```

**Comment by prologic** [comment] 2020-06-25 04:28
Confirming we are actually running:

```#!sh
root@freebsd121:~/netdata # ps aux | grep netdata
netdata 32380   0.0  0.9 32832 19108  -  IN   00:25      0:00.69 /usr/sbin/netdata -P /var/run/netdata/netdata.pid
netdata 32400   0.0  0.4 18676  8536  -  IN   00:25      0:00.01 /usr/sbin/netdata --special-spawn-server
root    32447   0.0  0.4 18580  8044  -  SN   00:25      0:00.05 /usr/libexec/netdata/plugins.d/apps.plugin 1
root    32640   0.0  0.0   524   336  0  R+   00:27      0:00.00 grep netdata
root@freebsd121:~/netdata # curl
curl: try 'curl --help' for more information
root@freebsd121:~/netdata # curl -q -o - http://localhost:19999/api/v1/info | grep version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3524  100  3524    0     0  3441k      0 --:--:-- --:--:-- --:--:-- 3441k
	"version": "v1.23.0-6-g08075dec3",
	"os_version": "12.1-RELEASE",
	"os_version_id": "unknown",
	"container_os_version": "none",
	"container_os_version_id": "none",
	"kernel_version": "1201000",
		"_os_version": "12.1-RELEASE",
		"_kernel_version": "1201000",
root@freebsd121:~/netdata #
```

**Comment by prologic** [comment] 2020-06-25 04:30
FreeBSD Node successfully claimed:

```#!sh
root@freebsd121:~/netdata # netdata-claim.sh -token=**** -rooms=**** -url=https://app.netdata.cloud
Token: ****************
Base URL: https://app.netdata.cloud
Id: ****
Rooms: ****
Hostname: freebsd121
Proxy:
Netdata user: netdata
Generating private/public key for the first time.
Generating RSA private key, 2048 bit long modulus (2 primes)
...............................................................................+++++
............................................................................................................................................................+++++
e is 65537 (0x010001)
Extracting public key from private key.
writing RSA key
Node was successfully claimed.
root@freebsd121:~/netdata #
```

**Comment by prologic** [comment] 2020-06-25 04:31
<img width="888" alt="Screen Shot 2020-06-25 at 14 31 03" src="https://user-images.githubusercontent.com/1290234/85653538-83ed6180-b6f0-11ea-905d-aa3f23027f68.png">

**Closed** 2021-08-25 15:16 UTC
Labels: bug, area/packaging, os/bsd
