### ISSUE TITLE
netdata-updater.sh cron report

### ISSUE THREAD

**Issue by ktsaou** [netdata/netdata#4808] opened 2018-12-01 12:09 UTC
##### Bug report summary

On one of the netdata demo sites, I received this email from cron:

```
/etc/cron.daily/netdata-updater:
/etc/cron.daily/netdata-updater: line 22: UID: readonly variable
No stash found.
From https://github.com/firehol/netdata
   997a529..15d7463  master     -> origin/master
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 15d7463... [ci skip] Automatic changelog update
```

##### OS / Environment

```sh
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

##### Component Name

packaging

##### Expected behavior

This is a problem:

```
/etc/cron.daily/netdata-updater: line 22: UID: readonly variable
```

The key problem is this:

```
# git pull
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>
```

To fix it, I did these:

```sh
# git checkout master
Previous HEAD position was 15d7463... [ci skip] Automatic changelog update
Switched to branch 'master'
Your branch is behind 'origin/master' by 13 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

# git pull
Updating 997a529..15d7463
Fast-forward
 .travis.yml                                         |  10 +-
 .travis/labeler.sh                                  |  84 +++++++++---
 CHANGELOG.md                                        | 110 +++-------------
 CONTRIBUTING.md                                     |   6 +-
 README.md                                           |   2 +-
 collectors/proc.plugin/README.md                    |   2 +-
 collectors/python.d.plugin/README.md                |  15 ++-
 contrib/sles11/README.md                            |   9 ++
 contrib/sles11/alarm-notify-basic.bash3.sh          | 755 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 contrib/sles11/netdata-alarms-bash3.patch           |  10 ++
 contrib/sles11/netdata-automake-no-dist-xz.patch    |  13 ++
 contrib/sles11/netdata-python-plugin-sles11.patch   |  28 ++++
 contrib/sles11/netdata.init                         |  65 ++++++++++
 docs/generator/buildhtml.sh                         |   5 +-
 docs/generator/buildyaml.sh                         |  21 ++-
 docs/generator/themes/material/partials/footer.html |   6 +-
 docs/javascripts/cookie-consent.js                  |  15 +++
 docs/netdata-security.md                            | 125 +++++++++---------
 docs/privacy-policy.md                              |  93 ++++++++++++++
 docs/terms-of-use.md                                | 160 +++++++++++++++++++++++
 installer/netdata-updater.sh                        |   2 +-
 web/api/queries/README.md                           |  46 ++++++-
 web/api/web_api_v1.c                                |  60 +++++++++
 web/api/web_api_v1.h                                |   1 +
 24 files changed, 1448 insertions(+), 195 deletions(-)
 create mode 100644 contrib/sles11/README.md
 create mode 100755 contrib/sles11/alarm-notify-basic.bash3.sh
 create mode 100644 contrib/sles11/netdata-alarms-bash3.patch
 create mode 100644 contrib/sles11/netdata-automake-no-dist-xz.patch
 create mode 100644 contrib/sles11/netdata-python-plugin-sles11.patch
 create mode 100755 contrib/sles11/netdata.init
 create mode 100644 docs/javascripts/cookie-consent.js
 create mode 100644 docs/privacy-policy.md
 create mode 100644 docs/terms-of-use.md
```

Though, running the updater again, produces this:

```
# ./netdata-updater.sh 
./netdata-updater.sh: line 22: UID: readonly variable
Sat Dec  1 12:07:32 UTC 2018 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

Sat Dec  1 12:07:32 UTC 2018 : INFO:  Updating netdata source from github...
No stash found.
Sat Dec  1 12:07:32 UTC 2018 : INFO:  Stashing local git changes. You can use  to reapply your changes.
No local changes to save
Fetching origin
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 15d7463... [ci skip] Automatic changelog update
HEAD is now at 15d7463 [ci skip] Automatic changelog update
Sat Dec  1 12:07:33 UTC 2018 : INFO:  Nothing to be done! (use -f to force re-install)
```

**Comment by ktsaou** [comment] 2018-12-02 21:53
@iFernandoSousa check the next update. Does it break repeatedly. On my server, the repo becomes detached on every update.

**Comment by Tronic69** [comment] 2018-12-02 22:56
Everything is working normally here, but I still get this error messages with "line 22: UID: readonly variable" and it results in a mail for every cron run of updater. 

So, what's the cause for this error? 

`# > git pull
Already up-to-date.

# > ./netdata-updater.sh 
./netdata-updater.sh: Zeile 22: UID: Schreibgeschützte Variable.
So 2. Dez 23:52:41 CET 2018 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

So 2. Dez 23:52:41 CET 2018 : INFO:  Updating netdata source from github...
Kein Stash-Eintrag gefunden.
So 2. Dez 23:52:41 CET 2018 : INFO:  Stashing local git changes. You can use  to reapply your changes.
Keine lokalen Änderungen zum Speichern
Fordere an von origin
HEAD ist jetzt bei 94f829e... [ci skip] Automatic changelog update
HEAD ist jetzt bei 94f829e [ci skip] Automatic changelog update
So 2. Dez 23:52:43 CET 2018 : INFO:  Nothing to be done! (use -f to force re-install)`

**Comment by ndom91** [comment] 2018-12-03 06:33
I'm having a similar problem every few updates lately it seems. I also get the 'line 22: UID: read only variable' problem with a few unmerged files following and then,

fatal: git-write-tree: error building trees Cannot save the current index state

**Comment by arjanvlek** [comment] 2018-12-03 08:10
I once got the "detached head state" report as mentioned by @ktsaou , but now I'm getting the following report every day:

```
/etc/cron.daily/netdata-updater:
/etc/cron.daily/netdata-updater: line 22: UID: readonly variable
No stash entries found.
From https://github.com/firehol/netdata
  376bd7de..0fad9bf5  master     -> origin/master
Previous HEAD position was 376bd7de nvidia_smi: handle `N/A` values (#4893)
HEAD is now at 0fad9bf5 Added info on health configuration, with a separate page for Charts, Dimensions, Alarms, Contexts (#4895)
```

Any way to stop this report from getting in my inbox every day?

**Comment by 0x3333** [comment] 2018-12-03 11:40
To solve:

```bash
cd /usr/local/src/netdata
git merge --abort
git fetch --all
git reset --hard origin/master
./netdata-updater.sh -f
```

**Comment by paulfantom** [comment] 2018-12-03 11:44
Fix is already in #4902.

**Comment by Tronic69** [comment] 2018-12-03 11:46
@0x3333 
Nope, that did not solve anything. Same message like before.

**Comment by Z1ni** [comment] 2018-12-03 15:37
@paulfantom 
Running
```
# git checkout master
# git pull
# ./netdata-updater.sh
```
after #4902 did not work. The repo goes back to the detached head state:
```
./netdata-updater.sh: line 22: UID: readonly variable
Mon Dec  3 17:33:54 EET 2018 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

Mon Dec  3 17:33:54 EET 2018 : INFO:  Updating netdata source from github...
No stash found.
Mon Dec  3 17:33:56 EET 2018 : INFO:  Stashing local git changes. You can use  to reapply your changes.
No local changes to save
Fetching origin
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a0770201... do not use protected variable name in updater script (#4902)
HEAD is now at a0770201 do not use protected variable name in updater script (#4902)
Mon Dec  3 17:34:02 EET 2018 : INFO:  Nothing to be done! (use -f to force re-install)
```

**Comment by Z1ni** [comment] 2018-12-03 15:46
Oh, it seems that the change was made in the installer/netdata-updater.sh, but I have netdata-updater.sh in the root folder.

**Comment by Z1ni** [comment] 2018-12-03 15:49
Also cron.daily has a symlink to the root folder netdata-updater.sh.

**Comment by paulfantom** [comment] 2018-12-03 15:52
You need to run installer again, it should overwrite (copy) new updater script from `installer/` to root directory.

**Comment by Z1ni** [comment] 2018-12-03 15:54
So do I run the root folder netdata-installer.sh?

**Comment by Z1ni** [comment] 2018-12-03 16:00
Also maybe [kickstart.sh#L31](https://github.com/netdata/netdata/blob/d536ba6a438b04166bd4c5337c9658e5d4c83ecb/kickstart.sh#L31) should also be changed, because it uses the same UID variable name.

**Comment by wccropper** [comment] 2018-12-03 16:34
I get this running the updater script on a fresh install

# /etc/cron.daily/netdata-updater 
Mon Dec  3 10:33:52 CST 2018 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

Mon Dec  3 10:33:52 CST 2018 : INFO:  Updating netdata source from github...
No stash found.
Mon Dec  3 10:33:52 CST 2018 : INFO:  Stashing local git changes. You can use  to reapply your changes.
No local changes to save
Fetching origin
HEAD is now at a077020... do not use protected variable name in updater script (#4902)
HEAD is now at a077020 do not use protected variable name in updater script (#4902)
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

Mon Dec  3 10:33:53 CST 2018 : INFO:  Nothing to be done! (use -f to force re-install)

**Comment by Z1ni** [comment] 2018-12-03 17:19
Running `./netdata-installer.sh -u` after checking out master (then a077020) did install the newer netdata correctly, but running `./netdata-updater.sh` after that left the repo again in the detached head state, but now with the new head (be83713a3348781635674092d9f5dbad57091107 at the time of writing).

`netdata-updater.sh` still leaves the repo to the detached head state after every run even if fixed by hand by checking out master and pulling.

**Comment by arjanvlek** [comment] 2018-12-05 10:16
After #4789  it keeps sending me this mail message every day:

```
/etc/cron.daily/netdata-updater:
No stash entries found.
From https://github.com/firehol/netdata
  c9a8408f..bd3cfade  master     -> origin/master
Previous HEAD position was c9a8408f fix info api method compilation warnings (#4911)
Switched to branch 'master'
```

How do i get rid of this? It was supposed to only send errors and not every update log.

**Comment by paulfantom** [comment] 2018-12-05 11:30
Fix is in #4922

**Closed** 2018-12-05 22:05 UTC
Labels: area/packaging, bug, priority/high

**Comment by gllmhyt** [comment] 2018-12-07 05:43
I reinstalled netdata with the workarounds discussed in this thread. I just received today:

```
/etc/cron.daily/netdata-updater:
No stash entries found.
```

And that's all, no longer the big git output.

**Comment by ntimo** [comment] 2018-12-07 10:20
Hello,
I am also getting on my server when running the cronjob:
`/etc/cron.daily/netdata-updater:
No stash entries found.
`

**Comment by arjanvlek** [comment] 2018-12-07 10:47
#MeToo

**Comment by cakrit** [comment] 2018-12-07 12:07
Can you please do the following?
```
ls -l /etc/cron.daily/netdata-updater
```
It should be a symbolic link to <path to netdata git clone>/netdata-updater.sh

If it is, do `/etc/cron.daily/netdata-updater -f`
If it's not, remove it and run <path to netdata git clone>/netdata-updater.sh -f and then execute the ln command that the installer will show you.

At the end, if you do a diff of your /etc/cron.daily/netdata-updater and <path to netdata git clone>/installer/netdata-updater.sh, you should only see REINSTALL_PWD being different.

**Comment by cakrit** [comment] 2018-12-08 12:15
Will be fixed in #4950

**Comment by Paulipaule** [comment] 2018-12-13 07:34
Hello,
I am also getting on my server when running the cronjob:  Keine Stash-Einträge gefunden. (No stash entries found)

I followed the instructions from cakrit. 

What else can I do?

**Comment by cakrit** [comment] 2018-12-13 10:31
Hi @Paulipaule 	PR #4952 fixed this yesterday. If you run your netdata-updater again, you should see the change shown [here](https://github.com/netdata/netdata/pull/4952/files) in the script.

**Comment by Paulipaule** [comment] 2018-12-17 11:11
Hi @cakrit, thanks for the response. Now it seems to work.
