### ISSUE TITLE
Dashboard.js LOADED UNDEFINED

### ISSUE THREAD

**Issue by Wndrr** [netdata/netdata#5508] opened 2019-02-25 22:28 UTC
##### Bug report summary
When including the script to have integrated graphs  `<script src="https://********/dashboard.js"></script>`
The browser console gives 

> localStorage: LOADED UNDEFINED "options.destroy_on_hide" as value undefined of type undefined - dashboard.js:86

The netdata graphs load and work properly but the `dashboard.js` scrip seems to have side effect and it seems like it's messing with fontawesome, because loading the netdata dashboard script makes the fontawesome icons disapear ...

##### OS / Environment
Reproduced on
 - Chrome 72.0.3626.109 (64bit)
 - Firefox 65.0.1

##### Netdata version (ouput of `netdata -V`)
v1.12.1-7-g86ed3869
I'm running in a docker, this seems to be the last available version for docker even though there is a new available version

**Comment by cakrit** [comment] 2019-02-26 11:51
What do you mean by "to have integrated graphs"? Are you talking about a custom dashboard? Can you provide an example that we can use to reproduce, because I don't see this error?

**Comment by Wndrr** [comment] 2019-02-27 18:31
Yes, I mean a custom dashboard. What do you mean by "an example"? The actual link to my netdata instance? https://netdata.viales.fr/dashboard.js

Simply including the link with a `script` tag gives the error.

**Comment by cakrit** [comment] 2019-02-28 11:29
What I mean is that I want to see the html that you are using for your custom dashboard to get your errors. You'll see in the example custom dashboard
https://netdata.viales.fr/tv.html you don't get such errors, just unrelated mixed content (https/http) from the requests to http://registry.my-netdata.io.

So the question is what your custom dashboard has that we can use to trace the issue you're seeing.

**Comment by Wndrr** [comment] 2019-03-01 10:49
The error occurs simply by including the `dashboard.js` script. Even without trying to display any map the `LOADED UNDEFINED` occurs. 

I have tried with and without including a dashboard, it gives the same error. 

Thanks for pointing out the mixed content errors by the way

**Comment by cakrit** [comment] 2019-03-01 11:53
We can't help if we can't have an HTML that reproduces it. On an empty .html, dashboard.js loads fine and it also works without error in tv.html. Without additional info, I can just point to [the docs](https://docs.netdata.cloud/web/gui/custom/), or we can wait until someone from the community who has seen this before jumps in.

**Comment by makutamatey** [comment] 2019-04-23 10:41
I get the same above error even though I am not using a custom dashboard

**Comment by cakrit** [comment] 2019-04-29 15:54
@makutamatey can you please let us know how to replicate your issue? Adding @gmosx

**Comment by JohnnyBee2** [comment] 2019-10-03 07:31
I get the same above error (on 30 different servers) even  though I am not using a custom dashboard.
- different versions of netdata.
- last version 1.17.1-156-nightly

> LocalStorage: LOADED UNDEFINED "options.destroy_on_hide" as value undefined of type undefined   dashboard.js?v20190902-0:1567

Do I have to worry about this?

**Comment by vlvkobal** [comment] 2019-10-25 12:47
@jacekkolasa, please look at the issue.

**Comment by ilyam8** [comment] 2019-11-25 09:15
@jacekkolasa please check the issue, should we close it?

**Comment by jacekkolasa** [comment] 2019-11-25 12:38
Thx Ilya for reminder. This is just a false warning, please do not worry about this, the functionality it is related to is working properly. We'll remove the cause of warning soon. Thanks!

**Closed by jacekkolasa** 2019-11-25 12:38 UTC
Labels: area/web, question
