### ISSUE TITLE
Mongodb Client SSL keyfile support

### ISSUE THREAD

**Issue by fmercier-almerys** [netdata/netdata#6464] opened 2019-07-15 11:37 UTC
Hi

Mongodb recommends using SSL key client file in production. However netdata python.d plugin does not support it. 
Can you make some involvement to add this new configuration ?

```
>>> client = pymongo.MongoClient('example.com',
...                              ssl=True,
...                              ssl_certfile='/path/to/client.pem',
...                              ssl_keyfile='/path/to/key.pem',
...                              ssl_pem_passphrase=<passphrase>)
```

**Comment by ilyam8** [comment] 2019-07-15 12:36
duplicate of https://github.com/netdata/netdata/issues/5884, closing the issue

**Closed by ilyam8** 2019-07-15 12:36 UTC
Labels: feature request, needs triage

**Comment by ilyam8** [comment] 2019-07-15 12:39
@fmercier-almerys i will try to implement #5884, np!

**Comment by fmercier-almerys** [comment] 2019-07-15 12:40
Hi You closed the issue as a duplicated with #5884 but it seems #5884 addresses only server ssl certificate no ?

**Comment by fmercier-almerys** [comment] 2019-07-15 12:43
Ok you prefer #5884 to addresses the two needs, client and server ssl certificates, up to you +1

**Comment by ilyam8** [comment] 2019-07-15 12:49
yes, i plan to add all [client ssl related stuff](https://api.mongodb.com/python/3.3.0/examples/tls.html)
