### ISSUE TITLE
Change settings via Web

### ISSUE THREAD

**Issue by ghost** [netdata/netdata#3044] opened 2017-11-20 18:39 UTC
Hello, I think it would be nice to be able to change settings via web, instead of doing the basic things via terminal. Also, have a username and password before access the monitoring dashboard would be nice.

**Comment by stefnats** [comment] 2017-11-21 09:22
I think the second part, authentication, would (and should?) be done via apache2 / nginx reverse proxy.

**Comment by andyxh** [comment] 2017-11-21 21:33
Thank you for your response :)

**Comment by ktsaou** [comment] 2017-11-23 22:31
Thanks! Yes it is a nice request.

**Comment by paulfantom** [comment] 2018-09-22 15:59
I am highly against this. Netdata is touching too many sensitive parts of the system  and modifying its configuration will cause a huge technical debt due to security concerns of such approach.

**Comment by ktsaou** [comment] 2018-09-23 14:46
> I am highly against this. Netdata is touching too many sensitive parts of the system and modifying its configuration will cause a huge technical debt due to security concerns of such approach.

netdata settings, not system settings. For example, it would be very nice to be able to:

1. create or modify alarms
2. setup alarm notifications 
3. restart auto-detection of a data-collection plugin
4. configure data collection plugins

Of course authentication is required.

**Comment by ktsaou** [comment] 2018-11-23 15:45
@cakrit 	this is probably a feature-set for the hub.

**Comment by cakrit** [comment] 2019-07-11 10:04
Blocked by #6317.

**Comment by cakrit** [comment] 2020-02-23 15:17
Duplicate of #6432

**Closed by cakrit** 2020-02-23 15:17 UTC
Labels: area/daemon, area/web, cloud, config. manager, discussion, feature request
