### ISSUE TITLE
Unix Domain Socket no longer working. Permission denied

### ISSUE THREAD

**Issue by elfgoh** [netdata/netdata#5181] opened 2019-01-16 10:17 UTC
##### Bug report summary
Permission denied is shown in journalctl logs when netdata is configured with Unix Domain Socket. This may be a duplicate of #5178 and related to the recent merge of #4969 

##### OS / Environment
Debian 9, armhf, Beaglebone Black

##### Component Name
Unix Domain socket
##### Steps To Reproduce
- Install at commit 3ecc26b 
-Change `/etc/netdata/netdata.conf`, such that `# bind to = *` becomes `bind to = unix:/run/netdata/netdata.sock tcp:*`
- Restart netdata: ` sudo systemctl restart netdata`
- View logs
```
debian@beaglebone:~$ journalctl -u netdata
-- Logs begin at Thu 2016-11-03 17:16:43 UTC, end at Wed 2019-01-16 10:06:00 UTC. --
Jan 16 09:44:34 beaglebone systemd[1]: Starting Real time performance monitoring...
Jan 16 09:44:35 beaglebone systemd[1]: Started Real time performance monitoring.
Jan 16 10:05:59 beaglebone systemd[1]: Stopping Real time performance monitoring...
Jan 16 10:06:00 beaglebone systemd[1]: Stopped Real time performance monitoring.
Jan 16 10:06:00 beaglebone systemd[1]: Starting Real time performance monitoring...
Jan 16 10:06:00 beaglebone systemd[1]: Started Real time performance monitoring.
Jan 16 10:06:00 beaglebone netdata[11087]: LISTENER: UNIX bind() on path '19999' failed.
Jan 16 10:06:00 beaglebone netdata[11087]: 2019-01-16 10:06:00: netdata ERROR : MAIN : LISTENER: UNIX bind() on path '19999' failed. (errno 13, Permission denied)
Jan 16 10:06:00 beaglebone netdata[11087]: LISTENER: Cannot create unix socket '19999'
Jan 16 10:06:00 beaglebone netdata[11087]: 2019-01-16 10:06:00: netdata ERROR : MAIN : LISTENER: Cannot create unix socket '19999'
Jan 16 10:06:00 beaglebone netdata[11087]: LISTENER: Listen socket tcp:0.0.0.0:19999 opened successfully.
Jan 16 10:06:00 beaglebone netdata[11087]: LISTENER: Listen socket tcp:[::]:19999 opened successfully.
Jan 16 10:06:00 beaglebone netdata[11087]: 2019-01-16 10:06:00: netdata INFO  : MAIN : LISTENER: Listen socket tcp:0.0.0.0:19999 opened successfully.
Jan 16 10:06:00 beaglebone netdata[11087]: 2019-01-16 10:06:00: netdata INFO  : MAIN : LISTENER: Listen socket tcp:[::]:19999 opened successfully.
```
##### Expected behavior
No error is expected when creating unix socket

**Comment by Ferroin** [comment] 2019-01-16 12:38
Based on the logs, Netdata is getting confused and trying to use the TCP port number as the path for the UNIX socket.

Does it work correctly if you remove the `tcp:*` part from the `bind to =` line?

**Comment by krishraghuram** [comment] 2019-01-16 13:30
I have pretty much same error, even though I have explicitly set `bind to` only to a unix socket.

```
# FILE /etc/netdata/netdata.conf

...
...
...
[web]
        # ses max window = 15
        # des max window = 15
        # mode = static-threaded
        # listen backlog = 4096
        # default port = 19999
        bind to = unix:/run/netdata/netdata.sock
...
...
...
```

```
Jan 16 06:26:25 user systemd[1]: Stopping Real time performance monitoring...
Jan 16 06:26:25 user systemd[1]: Stopped Real time performance monitoring.
Jan 16 06:26:25 user systemd[1]: Starting Real time performance monitoring...
Jan 16 06:26:25 user systemd[1]: Started Real time performance monitoring.
Jan 16 06:26:25 user netdata[3843]: LISTENER: UNIX bind() on path '19999' failed.
Jan 16 06:26:25 user netdata[3843]: LISTENER: Cannot create unix socket '19999'
Jan 16 06:26:25 user systemd[1]: netdata.service: Main process exited, code=exited, status=1/FAILURE
Jan 16 06:26:25 user netdata[3843]: 2019-01-16 06:26:25: netdata ERROR : MAIN : LISTENER: UNIX bind() on path '19999' failed. (errno 13, Permission denied)
Jan 16 06:26:25 user netdata[3843]: 2019-01-16 06:26:25: netdata ERROR : MAIN : LISTENER: Cannot create unix socket '19999'
Jan 16 06:26:25 user netdata[3843]: 2019-01-16 06:26:25: netdata FATAL : MAIN :LISTENER: Cannot listen on any API socket. Exiting... # : Success
Jan 16 06:26:25 user netdata[3843]: 2019-01-16 06:26:25: netdata INFO  : MAIN : EXIT: netdata prepares to exit with code 1...
Jan 16 06:26:25 user netdata[3843]: 2019-01-16 06:26:25: netdata INFO  : MAIN : EXIT: cleaning up the database...
Jan 16 06:26:25 user netdata[3843]: 2019-01-16 06:26:25: netdata INFO  : MAIN : Cleaning up database [0 hosts(s)]...
Jan 16 06:26:25 user netdata[3843]: 2019-01-16 06:26:25: netdata INFO  : MAIN : EXIT: removing netdata PID file '/var/run/netdata/netdata.pid'...
Jan 16 06:26:25 user netdata[3843]: 2019-01-16 06:26:25: netdata ERROR : MAIN : EXIT: cannot unlink pidfile '/var/run/netdata/netdata.pid'. (errno 2, No such file or directory)
Jan 16 06:26:25 user netdata[3843]: 2019-01-16 06:26:25: netdata INFO  : MAIN : EXIT: all done - netdata is now exiting - bye bye...
Jan 16 06:26:25 user netdata[3843]: LISTENER: Cannot listen on any API socket. Exiting...
Jan 16 06:26:25 user systemd[1]: netdata.service: Failed with result 'exit-code'.
Jan 16 06:26:25 user netdata[3843]: EXIT: netdata prepares to exit with code 1...
Jan 16 06:26:25 user netdata[3843]: EXIT: cleaning up the database...
Jan 16 06:26:25 user netdata[3843]: Cleaning up database [0 hosts(s)]...
Jan 16 06:26:25 user netdata[3843]: EXIT: removing netdata PID file '/var/run/netdata/netdata.pid'...
Jan 16 06:26:25 user netdata[3843]: EXIT: cannot unlink pidfile '/var/run/netdata/netdata.pid'.
Jan 16 06:26:25 user netdata[3843]: EXIT: all done - netdata is now exiting - bye bye...
```

**Comment by Ferroin** [comment] 2019-01-16 13:46
OK, just confirmed it on my end too (I forgot that I was running a copy of Netdata from before #4969 got merged).

@cakrit Looks like something was broken by #4969.  I never did get a chance to re-test after that first time (not your fault, I just never had the time), so I suspect it was something that got added after I first tested things.  I've taken a look at the full changes from that merge, but nothing is sticking out to me as a probable cause, but I may be missing something (it's a _lot_ of changes and I'm a bit out-of-practice WRT C coding).

**Comment by cakrit** [comment] 2019-01-16 14:07
Checking...

**Comment by cakrit** [comment] 2019-01-16 14:33
Seems to be starting correctly with the PR on my installation.

**Comment by krishraghuram** [comment] 2019-01-16 14:51
Not sure if it was the right way to test... but it worked for me too...

- Went to `/usr/src/netdata.git`
- Pulled pr by `git fetch origin pull/5184/head:pr-5184`
- Ran `netdata-uninstaller.sh` (required root)
- Ran `netdata-installer.sh` (required root)
- Set `bind to = unix:/run/netdata/netdata.sock` and restarted netdata.
- It succesfully created the socket, and my nginx proxy works.

**Closed** 2019-01-16 15:05 UTC
Labels: area/daemon, bug, priority/high

**Comment by cakrit** [comment] 2019-01-16 15:07
The PR was merged. If anyone else faces this issue, please update from git, the fix will also be in the nightly build.

**Comment by elfgoh** [comment] 2019-01-16 16:25
Wow thanks everyone! World class response time to this bug. Makes me ever confident to use netdata from trunk :)
