### ISSUE TITLE
OpenVPN chart is not available in netdata web interface

### ISSUE THREAD

**Issue by Gooman-rus** [netdata/netdata#10465] opened 2021-01-07 16:14 UTC
##### Bug report summary

I have configured OpenVPN monitoring via management interface using [this manual](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/openvpn#charts). Debugging of the collector shows that it is working well but there is no chart of OpenVPN in the web interface. Debug looks like this:
```netdata@server:/usr/libexec/netdata/plugins.d$ ./go.d.plugin -d -m openvpn
[ DEBUG ] main[main] main.go:111 plugin: name=go.d, version=v0.26.2
[ DEBUG ] main[main] main.go:113 current user: name=netdata, uid=999
[ INFO  ] main[main] agent.go:106 instance is started
[ INFO  ] main[main] setup.go:39 loading config file
[ INFO  ] main[main] setup.go:47 looking for 'go.d.conf' in [/etc/netdata /usr/lib/netdata/conf.d]
[ INFO  ] main[main] setup.go:54 found '/usr/lib/netdata/conf.d/go.d.conf
[ INFO  ] main[main] setup.go:61 config successfully loaded
[ INFO  ] main[main] agent.go:110 using config: enabled 'true', default_run 'true', max_procs '0'
[ INFO  ] main[main] setup.go:66 loading modules
[ INFO  ] main[main] setup.go:85 enabled/registered modules: 1/53
[ INFO  ] main[main] setup.go:90 building discovery config
[ INFO  ] main[main] setup.go:116 looking for 'openvpn.conf' in [/etc/netdata/go.d /usr/lib/netdata/conf.d/go.d]
[ INFO  ] main[main] setup.go:123 found '/etc/netdata/go.d/openvpn.conf
[ INFO  ] main[main] setup.go:128 dummy/read/watch paths: 0/1/0
[ INFO  ] discovery[manager] manager.go:90 registered discoverers: [file discovery: [file reader]]
[ INFO  ] discovery[manager] manager.go:95 instance is started
[ INFO  ] run[manager] run.go:30 instance is started
[ INFO  ] build[manager] build.go:106 instance is started
[ INFO  ] discovery[file manager] discovery.go:71 instance is started
[ INFO  ] discovery[file reader] read.go:39 instance is started
[ INFO  ] discovery[file reader] read.go:40 instance is stopped
[ DEBUG ] build[manager] build.go:153 received config group ('/etc/netdata/go.d/openvpn.conf'): 1 jobs (added: 1, removed: 0)
[ DEBUG ] build[manager] build.go:295 building openvpn[local] job, config: map[__provider__:file reader __source__:/etc/netdata/go.d/openvpn.conf address:localhost:5555 autodetection_retry:0 module:openvpn name:local priority:70000 update_every:1]
[ INFO  ] openvpn[local] openvpn.go:101 using address: localhost:5555, connect timeout: 2s, read timeout: 2s, write timeout: 2s
[ INFO  ] openvpn[local] openvpn.go:121 connected to OpenVPN v2.4.4, Management v1
[ INFO  ] openvpn[local] job.go:156 check success
[ INFO  ] openvpn[local] job.go:176 started, data collection interval 1s
[ DEBUG ] run[manager] run.go:41 tick 0
CHART 'netdata.execution_time_of_openvpn_local' '' 'Execution Time for openvpn_local' 'ms' 'go.d' 'netdata.go_plugin_execution_time' '' '145000' '1' '' 'go.d' 'openvpn'
DIMENSION 'time' '' '' '1' '1' ''

CHART 'openvpn_local.active_clients' '' 'Total Number Of Active Clients' 'active clients' 'clients' 'openvpn.active_clients' '' '70000' '1' '' 'go.d' 'openvpn'
DIMENSION 'clients' '' '' '1' '1' ''

BEGIN 'openvpn_local.active_clients'
SET 'clients' = 1
END

CHART 'openvpn_local.total_traffic' '' 'Total Traffic' 'kilobits/s' 'traffic' 'openvpn.total_traffic' 'area' '70001' '1' '' 'go.d' 'openvpn'
DIMENSION 'bytes_in' 'in' 'incremental' '8' '1000' ''
DIMENSION 'bytes_out' 'out' 'incremental' '8' '-1000' ''

BEGIN 'openvpn_local.total_traffic'
SET 'bytes_in' = 3896223
SET 'bytes_out' = 14778542
END

BEGIN 'netdata.execution_time_of_openvpn_local'
SET 'time' = 0
END

[ DEBUG ] run[manager] run.go:41 tick 1
BEGIN 'openvpn_local.active_clients' 998983
SET 'clients' = 1
END

BEGIN 'openvpn_local.total_traffic' 998983
SET 'bytes_in' = 3896308
SET 'bytes_out' = 14778624
END
```

##### OS / Environment

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

##### Netdata version

 netdata v1.28.0

##### Component Name

OpenVPN management interface collector
##### Steps To Reproduce

1. Configure OpenVPN collector using [this manual](https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/openvpn#charts).
2. Debug the collector in order to check that it is working well.
3. Check web interface and see that there is no OpenVPN charts section.

##### Expected behavior

The OpenVPN charts section is available in netdata web interface.

**Comment by ilyam8** [comment] 2021-01-12 09:26
Hi @Gooman-rus 

`openvpn` collector is disabled by default, see https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/openvpn#configuration

Reason

> Currently, the OpenVPN daemon can at most support a single management client any one time.

If we enable it by default it can break other tools that use management interface (example - https://github.com/furlongm/openvpn-monitor).

You need to explicitly enabled it in the `go.d.conf`

```yaml
modules:
#  activemq: yes
#  apache: yes
...
#  openvpn: yes
```

=>

```yaml
modules:
#  activemq: yes
#  apache: yes
...
  openvpn: yes
```

**Comment by ilyam8** [comment] 2021-01-13 09:33
@Gooman-rus i believe the problem is fixed, so i am closing the issue. 

If there are any questions consider to use [our community forum](https://community.netdata.cloud/). Hope you enjoy using netdata!

**Closed by ilyam8** 2021-01-13 09:33 UTC
Labels: area/external, question
