### ISSUE TITLE
Netdata parent web stops working after a while

### ISSUE THREAD

**Issue by yasharne** [netdata/netdata#9821] opened 2020-08-26 12:30 UTC
##### Bug report summary
After upgrading our parent servers to version `1.24.0`, every few hours, we lost metrics on the grafana dashboards and few minutes later we start to get lots of `last collected` indicating children cannot send metrics to the parent.
The children are not `v1.24.0` and They range from `1.20.0` to `1.23.0`.
Here is an error log I found in the logs which seems related:
```
2020-08-26 16:37:27: netdata ERROR : WEB_SERVER[static3] : 854: failed to disable TCP_CORK on socket. (errno 9, Bad file descriptor)
```
The number of allowed softlink for the netdata unit is `65536` and the number of file descriptors for `/opt/netdata/bin/srv/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D` is 280

I'm not sure if it is related or not, but we also have lots of `errno 22` errors as well:
```
2020-08-26 16:19:20: netdata ERROR : STREAM_RECEIVER[plugin-03.app.x.y.z,[172.16.77.75]:36450] : STREAM plugin-03.app.x.y.z [receive from [172.16.77.75]:36450]: disconnected (completed 181 updates). (errno 22, Invalid argument)
2020-08-26 16:19:25: netdata ERROR : STREAM_RECEIVER[plugin-08.app.x.y.z,[172.16.77.208]:50334] : STREAM plugin-08.app.x.y.z [receive from [172.16.77.208]:50334]: disconnected (completed 224 updates). (errno 22, Invalid argument)
2020-08-26 16:37:13: netdata ERROR : STREAM_RECEIVER[plugin-06.app.x.y.z,[172.16.77.59]:58770] : STREAM plugin-06.app.x.y.z [receive from [172.16.77.59]:58770]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:13: netdata ERROR : STREAM_RECEIVER[plugin-04.app.x.y.z,[172.16.77.229]:41490] : STREAM plugin-04.app.x.y.z [receive from [172.16.77.229]:41490]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:13: netdata ERROR : STREAM_RECEIVER[plugin-05.app.x.y.z,[172.16.77.103]:45820] : STREAM plugin-05.app.x.y.z [receive from [172.16.77.103]:45820]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:27: netdata ERROR : STREAM_RECEIVER[plugin-03.app.x.y.z,[172.16.77.75]:50168] : STREAM plugin-03.app.x.y.z [receive from [172.16.77.75]:50168]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:27: netdata ERROR : STREAM_RECEIVER[plugin-02.app.x.y.z,[172.16.77.74]:50820] : STREAM plugin-02.app.x.y.z [receive from [172.16.77.74]:50820]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:27: netdata ERROR : STREAM_RECEIVER[plugin-07.app.x.y.z,[172.16.77.97]:34550] : STREAM plugin-07.app.x.y.z [receive from [172.16.77.97]:34550]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:27: netdata ERROR : STREAM_RECEIVER[plugin-01.app.x.y.z,[172.16.77.73]:51276] : STREAM plugin-01.app.x.y.z [receive from [172.16.77.73]:51276]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:27: netdata ERROR : STREAM_RECEIVER[plugin-05.app.x.y.z,[172.16.77.103]:51544] : STREAM plugin-05.app.x.y.z [receive from [172.16.77.103]:51544]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:27: netdata ERROR : STREAM_RECEIVER[plugin-04.app.x.y.z,[172.16.77.229]:47606] : STREAM plugin-04.app.x.y.z [receive from [172.16.77.229]:47606]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:27: netdata ERROR : STREAM_RECEIVER[plugin-06.app.x.y.z,[172.16.77.59]:37036] : STREAM plugin-06.app.x.y.z [receive from [172.16.77.59]:37036]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:38: netdata ERROR : STREAM_RECEIVER[plugin-06.app.x.y.z,[172.16.77.59]:56190] : STREAM plugin-06.app.x.y.z [receive from [172.16.77.59]:56190]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:38: netdata ERROR : STREAM_RECEIVER[plugin-07.app.x.y.z,[172.16.77.97]:40486] : STREAM plugin-07.app.x.y.z [receive from [172.16.77.97]:40486]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:38: netdata ERROR : STREAM_RECEIVER[plugin-04.app.x.y.z,[172.16.77.229]:41210] : STREAM plugin-04.app.x.y.z [receive from [172.16.77.229]:41210]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:38: netdata ERROR : STREAM_RECEIVER[plugin-01.app.x.y.z,[172.16.77.73]:48830] : STREAM plugin-01.app.x.y.z [receive from [172.16.77.73]:48830]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:37:38: netdata ERROR : STREAM_RECEIVER[plugin-05.app.x.y.z,[172.16.77.103]:45872] : STREAM plugin-05.app.x.y.z [receive from [172.16.77.103]:45872]: disconnected (completed 0 updates). (errno 22, Invalid argument)
2020-08-26 16:40:18: netdata ERROR : PLUGINSD[go.d] : '/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin' (pid 19584) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-08-26 16:40:32: netdata ERROR : STREAM_RECEIVER[plugin-04.app.x.y.z,[172.16.77.229]:36886] : STREAM plugin-04.app.x.y.z [receive from [172.16.77.229]:36886]: disconnected (completed 131 updates). (errno 22, Invalid argument)
2020-08-26 16:41:28: netdata ERROR : STREAM_RECEIVER[plugin-07.app.x.y.z,[172.16.77.97]:50408] : STREAM plugin-07.app.x.y.z [receive from [172.16.77.97]:50408]: disconnected (completed 259 updates). (errno 22, Invalid argument)
2020-08-26 16:41:35: netdata ERROR : STREAM_RECEIVER[plugin-06.app.x.y.z,[172.16.77.59]:37934] : STREAM plugin-06.app.x.y.z [receive from [172.16.77.59]:37934]: disconnected (completed 230 updates). (errno 22, Invalid argument)
2020-08-26 16:43:24: netdata ERROR : PLUGINSD[node.d] : read failed: end of file (errno 22, Invalid argument)
2020-08-26 16:43:24: netdata ERROR : PLUGINSD[node.d] : '/opt/netdata/usr/libexec/netdata/plugins.d/node.d.plugin' (pid 7121) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-08-26 16:43:24: netdata ERROR : PLUGINSD[node.d] : '/opt/netdata/usr/libexec/netdata/plugins.d/node.d.plugin' (pid 7121) exited with error code 127 and haven't collected any data. Disabling it. (errno 22, Invalid argument)
2020-08-26 16:43:24: netdata ERROR : PLUGINSD[perf] : '/opt/netdata/usr/libexec/netdata/plugins.d/perf.plugin' (pid 7142) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-08-26 16:43:24: netdata ERROR : PLUGINSD[perf] : '/opt/netdata/usr/libexec/netdata/plugins.d/perf.plugin' (pid 7142) exited with error code 1 and haven't collected any data. Disabling it. (errno 22, Invalid argument)
2020-08-26 16:43:24: netdata ERROR : PLUGINSD[fping] : '/opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin' (pid 7125) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-08-26 16:43:24: netdata ERROR : PLUGINSD[fping] : '/opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin' (pid 7125) exited with error code 1 and haven't collected any data. Disabling it. (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[node.d] : read failed: end of file (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[node.d] : '/opt/netdata/usr/libexec/netdata/plugins.d/node.d.plugin' (pid 7647) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[node.d] : '/opt/netdata/usr/libexec/netdata/plugins.d/node.d.plugin' (pid 7647) exited with error code 127 and haven't collected any data. Disabling it. (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[python.d] : '/opt/netdata/usr/libexec/netdata/plugins.d/python.d.plugin' (pid 7640) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[ioping] : '/opt/netdata/usr/libexec/netdata/plugins.d/ioping.plugin' (pid 7659) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[ioping] : '/opt/netdata/usr/libexec/netdata/plugins.d/ioping.plugin' (pid 7659) exited with error code 1 and haven't collected any data. Disabling it. (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[perf] : '/opt/netdata/usr/libexec/netdata/plugins.d/perf.plugin' (pid 7690) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[perf] : '/opt/netdata/usr/libexec/netdata/plugins.d/perf.plugin' (pid 7690) exited with error code 1 and haven't collected any data. Disabling it. (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[fping] : '/opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin' (pid 7679) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[fping] : '/opt/netdata/usr/libexec/netdata/plugins.d/fping.plugin' (pid 7679) exited with error code 1 and haven't collected any data. Disabling it. (errno 22, Invalid argument)
2020-08-26 16:45:40: netdata ERROR : PLUGINSD[charts.d] : '/opt/netdata/usr/libexec/netdata/plugins.d/charts.d.plugin' (pid 7662) disconnected after 0 successful data collections (ENDs). (errno 22, Invalid argument)
```

##### OS / Environment

```
4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.5 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

**Comment by yasharne** [comment] 2020-08-27 04:07
After downgrading the parent to `v1.23.2` everything seems fine.

**Comment by amoss** [comment] 2020-08-27 08:09
@mfundul The main difference between 1.23.2 and 1.24 would be the multihostdb and the problem seems to be related to the number of file descriptors.

**Comment by mfundul** [comment] 2020-08-27 08:25
But netdata is only using 280 file descriptors of the 65536 available here.

**Comment by mfundul** [comment] 2020-08-27 08:30
@yasharne are you limiting netdata to 280 file descriptors?

**Comment by mfundul** [comment] 2020-08-27 09:06
@yasharne version 1.24 introduces the multihost DB, so take a look [here](https://github.com/netdata/netdata/blob/master/database/engine/README.md#legacy-configuration) if you haven't.

In theory, multihost DB will use much fewer file descriptors than versions < 1.24. However, there are also the legacy dbengine instance folders, which are kept in the netdata cache for backward compatibility. You can delete those folders to free up space and descriptors, but you will lose the history.

**Comment by yasharne** [comment] 2020-08-27 17:59
@mfundul as I mentioned previously, we have fd limit of `65536` and I have tried both new multi-host DB engine and legacy dbengine configuration and both had the same issue

**Comment by amoss** [comment] 2020-08-28 07:11
@yasharne Is it possible for us to take a look at the full `error.log` for a parent node? If you are willing to share it then you can email it to either mfundul@netdata.cloud or andrew@netdata.cloud so that we can try to diagnose your issue.

**Comment by yasharne** [comment] 2020-08-30 05:32
@mfundul I sent the email to mfundul@netdata.cloud

**Comment by mfundul** [comment] 2020-08-30 07:34
Sorry @yasharne , this was the wrong e-mail. Please send it to markos@netdata.cloud

**Comment by yasharne** [comment] 2020-08-30 07:37
@mfundul Done

**Comment by mfundul** [comment] 2020-08-30 08:08
This looks like a combination of multihost DB in v1.24 and https://github.com/netdata/netdata/issues/8384. I would expect using the code from git master branch or the nightly packages would resolve this.

**Comment by ilyam8** [comment] 2020-08-31 07:03
> go.d is using a timezone 4.5 hours behind from the main process

https://github.com/netdata/netdata/issues/8949#issuecomment-638294959

**Comment by amoss** [comment] 2020-08-31 07:23
> > go.d is using a timezone 4.5 hours behind from the main process
> 
> [#8949 (comment)](https://github.com/netdata/netdata/issues/8949#issuecomment-638294959)

Yes, I thought that might be the cause. The 0.5 hour part threw me a little but maybe the host timezone has an unusual definition of summer time?

**Comment by yasharne** [comment] 2020-08-31 09:00
@amoss It is an EXT4 local disk

**Comment by amoss** [comment] 2020-08-31 09:25
Why do the logs have no entries between the restarts - is the disk saturated so that writes are being dropped or is something else happening?

**Comment by yasharne** [comment] 2020-08-31 10:54
@amoss I'm not sure if it is related to the disk, since we have 4 more parent netdata on the same Baremetal and all of them are working fine and as soon as I downgraded this parent to `v1.23.2`, the problem disappeared. (Other parents are `v1.23.0`)

**Comment by mfundul** [comment] 2020-08-31 11:30
> 
> 
> Why do the logs have no entries between the restarts - is the disk saturated so that writes are being dropped or is something else happening?

I think log flood protection.

**Comment by amoss** [comment] 2020-08-31 11:42
I didn't see the log protection messages but that is possible. 

@yasharne If the problem disappears with the downgrade then it seems most likely that it is the combination of multihost DB and the flushing problem that @mfundul pointed to above. Does upgrading to the nightly that has the flushing fix in it work?

**Comment by yasharne** [comment] 2020-09-05 08:45
@amoss Unfortunately duo to our policy I cannot upgrade to nighly releases, I guess I have to wait until the next stable release

**Comment by Ferroin** [comment] 2020-10-28 15:40
@yasharne Could you please confirm if this is still an issue or not on v1.26.0?

**Comment by yasharne** [comment] 2020-11-01 07:22
@Ferroin There seems to be no problem with `v1.26.0` as one of our parents is running this version for about a week and it is working fine

**Comment by Ferroin** [comment] 2020-11-02 12:26
@yasharne OK, given that it sounds like it’s working, I’m going to close this as fixed.  If you see the same issue again, drop a comment here and we can reopen this and start investigating further.

**Closed by Ferroin** 2020-11-02 12:26 UTC
Labels: bug, need feedback, needs triage
