### ISSUE TITLE
Memory leak in power supply module

### ISSUE THREAD

**Issue by vlvkobal** [netdata/netdata#6132] opened 2019-05-27 09:12 UTC
##### Bug report summary
valgrind reports a memory leak on dir opening:

```
    <text>32,816 bytes in 1 blocks are definitely lost in loss record 988 of 1,015</text>
    <leakedbytes>32816</leakedbytes>
    <leakedblocks>1</leakedblocks>
  </xwhat>
  <stack>
    <frame>
      <ip>0x483777F</ip>
      <obj>/usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so</obj>
      <fn>malloc</fn>
      <dir>/build/valgrind/src/valgrind/coregrind/m_replacemalloc</dir>
      <file>vg_replace_malloc.c</file>
      <line>299</line>
    </frame>
    <frame>
      <ip>0x53328FA</ip>
      <obj>/usr/lib/libc-2.28.so</obj>
      <fn>__alloc_dir</fn>
    </frame>
    <frame>
      <ip>0x53329FC</ip>
      <obj>/usr/lib/libc-2.28.so</obj>
      <fn>opendir_tail</fn>
    </frame>
    <frame>
      <ip>0x1EDBB3</ip>
      <obj>/home/christopher/CLionProjects/netdata/cmake-build-debug/netdata</obj>
      <fn>do_sys_class_power_supply</fn>
      <dir>/home/christopher/CLionProjects/netdata/collectors/proc.plugin</dir>
      <file>sys_class_power_supply.c</file>
      <line>134</line>
    </frame>
    <frame>
      <ip>0x1A3501</ip>
      <obj>/home/christopher/CLionProjects/netdata/cmake-build-debug/netdata</obj>
      <fn>proc_main</fn>
      <dir>/home/christopher/CLionProjects/netdata/collectors/proc.plugin</dir>
      <file>plugin_proc.c</file>
      <line>124</line>
    </frame>
    <frame>
      <ip>0x2103B1</ip>
      <obj>/home/christopher/CLionProjects/netdata/cmake-build-debug/netdata</obj>
      <fn>thread_start</fn>
      <dir>/home/christopher/CLionProjects/netdata/libnetdata/threads</dir>
      <file>threads.c</file>
      <line>126</line>
    </frame>
    <frame>
      <ip>0x4ADBA9C</ip>
      <obj>/usr/lib/libpthread-2.28.so</obj>
      <fn>start_thread</fn>
```

##### OS / Environment
Manjaro Linux 18.0.4 4.19.32-1-MANJARO

##### Netdata version (ouput of `netdata -V`)
netdata v1.15.0-28-gdfa3c906

##### Component Name
power supply module in proc plugin

##### Expected behavior
No memory leaks

**Comment by Volkodavchik** [comment] 2019-07-16 10:05
Definitely, it requires deeper research. Will take a look and share the results.

**Comment by Volkodavchik** [comment] 2019-07-18 10:10
@cakrit  and @vlvkobal few questions appeared during initial analysis:
1. Is "netdata", by default, built and installed via one-liner script with debug symbols? If not, is there a way how to configure it to do so?
2. Will power_supply collector work on a usual PC without any battery? Or it is mandatory to have some laptop/tablet with battery on?
3. What if folder /sys/class/power_supply is empty - does that mean power_supply collector is not active? In short - how to ensure the power_supply collector is working properly with local "netdata" installation?
4. What exact line was used with valgrind memcheck tool to track this particular memory leak?

**Comment by cakrit** [comment] 2019-07-18 10:42
> 1. Is "netdata", by default, built and installed via one-liner script with debug symbols? If not, is there a way how to configure it to do so?

https://docs.netdata.cloud/daemon/#debugging

> 2. Will power_supply collector work on a usual PC without any battery? Or it is mandatory to have some laptop/tablet with battery on?

https://docs.netdata.cloud/collectors/proc.plugin/#linux-power-supply
Without a battery, you won't get anything.

> 3. What if folder /sys/class/power_supply is empty - does that mean power_supply collector is not active? In short - how to ensure the power_supply collector is working properly with local "netdata" installation?

Same as before, without a laptop, it will indeed be empty. You know it works, when you get a chart like this:
![Screenshot from 2019-07-18 12-39-22](https://user-images.githubusercontent.com/43294513/61451313-5da83900-a959-11e9-8362-18a0af0305b2.png)

> 4. What exact line was used with valgrind memcheck tool to track this particular memory leak?

```/usr/bin/valgrind --tool=memcheck --gen-suppressions=all --leak-check=full --leak-resolution=med --show-leak-kinds=all --track-origins=yes --vgdb=no /home/christopher/CLionProjects/netdata/cmake-build-debug/netdata -D```

**Comment by vlvkobal** [comment] 2019-07-18 13:57
You can build Netdata using
`
CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-lto --dont-wait
`

Valgrind was executed this way:
`/usr/bin/valgrind --tool=memcheck --xml=yes --xml-file=/tmp/valgrind --gen-suppressions=all --leak-check=full --leak-resolution=med --show-leak-kinds=all --track-origins=yes --vgdb=no /home/christopher/CLionProjects/netdata/cmake-build-debug/netdata -D`
 
If your system doesn’t have subdirectories for power supplies in `/sys/class/power_supply` you can change
```
[plugin:proc:/sys/class/power_supply]
  # directory to monitor = /sys/class/power_supply
```
in `netdata.conf` to a fake path and populate it manually.
 
The issue was caught on Manjaro:
```
NETDATA_SYSTEM_OS_NAME="Manjaro Linux"
NETDATA_SYSTEM_OS_ID=manjaro
NETDATA_SYSTEM_OS_ID_LIKE=arch
NETDATA_SYSTEM_OS_VERSION=18.0.4
NETDATA_SYSTEM_OS_VERSION_ID=unknown
NETDATA_SYSTEM_OS_DETECTION=Mixed
NETDATA_SYSTEM_KERNEL_NAME=Linux
NETDATA_SYSTEM_KERNEL_VERSION=4.19.32-1-MANJARO
NETDATA_SYSTEM_ARCHITECTURE=x86_64
NETDATA_SYSTEM_VIRTUALIZATION=none
NETDATA_SYSTEM_VIRT_DETECTION=systemd-detect-virt
NETDATA_SYSTEM_CONTAINER=none
NETDATA_SYSTEM_CONTAINER_DETECTION=systemd-detect-virt
```

**Comment by Volkodavchik** [comment] 2019-07-19 14:14
Great thanks for quick responses.
All that helps to build debug version and see power_supply plugin in work:)
![VirtualBox_manjaro_19_07_2019_14_39_24](https://user-images.githubusercontent.com/8694443/61540506-04fe9c00-aa3e-11e9-991a-95a20f4e3f2d.png)

Summary:
After the initial analysis, I was not able to reproduce the same memleak issue, reported above.
It still might be a false-positive issue, based on pull-based memory allocation via underlayer library functions, reported by Valgrind (opendir, readdir, closedir, etc)

Used environment:
- Ubuntu 16.04 LTS (real hardware server machine)
- Manjaro 18.04 (VirtualBox machine on laptop installed from manjaro-gnome-18.0.4-stable-x86_64.iso). 
  Extra steps to build netdata from source were done
	- sudo pacman -Syyu --> updated Manjaro distro to have at least GLIBC_2.29
	- sudo pacman -S base-devel

Basically were done next things to check that issue:

	- Compare netdata release v16 with v15 code (to see if it is required to test v16 separately)
	  [DONE] the same part of power supply plugin without changes, at least in code reported by Valgrind

	- Create a Virtual box machine with Majaro Linux
	  [DONE] Based on the official manjaro-gnome-18.0.4-stable-x86_64.iso image

	- Get initial information about the issue
	  [DONE] Retrieved all information necessary to reproduce the environment

	- Build debug version of netdata for Majaro/Ubuntu env
	  [DONE] All steps necessary to see debug logs with Valgrind and building from the source

	- Setup netdata.service configuration and Vlagrind together and get the summary
	  [DONE]  in netdata.service:	/usr/bin/valgrind --trace-children=yes --track-origins=yes --leak-check=full --show-leak-kinds=all  --verbose --vgdb=no  --log-socket=127.0.0.1:12345 /usr/sbin/netdata -P /var/run/netdata/netdata.pid -D -W set global 'process scheduling policy' 'keep' -W set global 'OOM score' 'keep'
	in some another shell:		
	valgrind-listener 12345 >> ./valgrind.log

	- Generate a Valgring memcheck xml report for v15 on Majaro VirtualBox laptop
	  [DONE] Log in the attachment

	- Generate a Valgring memcheck log report for v15/ v16 on Ubuntu machine
	  [DONE] Log in the attachment

Manjaro logs:
[report.log.zip](https://github.com/netdata/netdata/files/3411361/report.log.zip)
[report_xml.log](https://github.com/netdata/netdata/files/3411364/report_xml.log)
Ubuntu logs:
[2019-07-17_valgrind.log.zip](https://github.com/netdata/netdata/files/3411360/2019-07-17_valgrind.log.zip)

Next steps - modify netdata code, where "dir" is opened, to see how incorrect/missing path to /sys/class/power_supply affects plugin behavior.

**Comment by Volkodavchik** [comment] 2019-07-23 08:18
Recent updates:
-  Was modified the code to simulate case when DIR (/sys/classes/power...) is inaccessible via a collector, to see how it affects memory pool
-  Was modified access permissions to required by power collector folders (/sys/classes/power...) to simulate error with the access

Summary:
All behaves as it should - the issue was not reproduced. Test logs were printed ("TEST TEST TEST !!!") in the netdata error.log, no extra memory leak was reported by Valgrind. Logs are below
[error.log.1.zip](https://github.com/netdata/netdata/files/3420934/error.log.1.zip)
[modified_power.log](https://github.com/netdata/netdata/files/3420935/modified_power.log)

**Comment by cakrit** [comment] 2019-07-23 09:59
I ran it again and didn't see any `definitely lost` or `indirectly lost` for the power supply module, so we're closing as can't reproduce.

**Closed by cakrit** 2019-07-23 09:59 UTC
Labels: Cannot reproduce, area/collectors, bug, help wanted
